### ISSUE TITLE
Shadowsocks always using dedicated GPU

### ISSUE THREAD

**Issue by cydia2020** [shadowsocks/shadowsocks-windows#1000]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.2.1

### Environment(Operating system, .NET Framework, etc)
Windows 10 Insider Preview Build 15002
.NET Framework 2.0 and 3.5

### Steps you have tried
Restart the PC, restart Shadowsocks, Choose Integrated GPU in NVidia control panel

### What did you expect to see?
Not taking any power of dGPU

### What did you see instead?
Shadowsocks is always taking the 'juice' of dedicated GPU so that the software like Photoshop and Lightroom become to lag

**Comment by celeron533** [comment]
Windows 10 Insider Preview 可能会导致奇怪的问题。。。
SS-win需要.net 4.5以上，win10已经自带

**Comment by zvg** [comment]
我也碰到了一样的问题.shadowsocks-windows使用gpu.

系统是 win10 rs1 打了所有补丁.
