### ISSUE TITLE
Make update notification stay a little while longer in Windows 10

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-windows#1003]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.2.1

### Environment(Operating system, .NET Framework, etc)
Windows 10, .NET Framework 4.6.2.

### Steps you have tried
Not relevant.

### What did you expect to see?
Toast notification appear in Action Center.

### What did you see instead?
Notification goes away after a few seconds and there's nowhere to find it.

### Config and error log in detail (with all sensitive info masked)
Not relevant.

Possibly useful link: http://stackoverflow.com/a/32221222/2245107

**Comment by celeron533** [comment]
It looks like controlled by Windows itself.
http://www.howto-connect.com/windows-10-change-time-to-stay-notification-popup/

![image](https://cloud.githubusercontent.com/assets/3608762/21974893/59ff1776-dc04-11e6-9299-ebe5f5473e0e.png)

**Comment by Mygod** [comment]
That's different.

**Comment by florianmonfort** [comment]
@Mygod please develop. What is different?

**Comment by celeron533** [comment]
@florianmonfort , it is different from the screenshot I have posted. At first I was thinking it was just a balloon notification.
![image](https://cloud.githubusercontent.com/assets/3608762/23587022/91282586-01dd-11e7-9ef9-d1eea6c67aac.png)

**Comment by celeron533** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotificationmanager#Windows_UI_Notifications_ToastNotificationManager_CreateToastNotifier_System_String_

But there may have some limitations when using the Toast Notification:

Sending toast notifications from desktop apps
======

Generally, sending a toast notification from a desktop app is the same as sending it from a Windows Store app. However, you should be aware of these differences and requirements:

- For a desktop app to display a toast, the app must have a **shortcut** on the Start screen.
- The shortcut must have an AppUserModelID.
- Desktop apps cannot schedule a toast.

**Comment by wongsyrone** [comment]
Have to keep compatibility with the older operating systems.
You can always get notified with version checking enabled, miss it once is not a big problem.
