### ISSUE TITLE
Windows 10 store doesn't work over Shadowsocks

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-windows#1004]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
Windows 10 x64 14393.693, .NET 4.6.2.

### Steps you have tried
1. `netsh winhttp import proxy source=ie` with admin.
2. Restart.
3. Switch on system proxy.
4. Start Windows Store or other Windows Store app (Wunderlist is tested in this case).
5. Shutoff system proxy.
5. Reload Windows Store or other Windows Store app.

### What did you expect to see?

Good connection! 👍 

### What did you see instead?

After enabling proxy:

> The error code is 0x80072EFD, in case you need it.

Wunderlist doesn't work either. 👎 

After disabling proxy, everything goes back to work.

### Config and error log in detail (with all sensitive info masked)

Not relevant. Nothing extraordinary in the log.

**Comment by Noisyfox** [comment]
#897 #210

**Comment by Mygod** [comment]
Great. I suggest adding `netsh winhttp import proxy source=ie` and that vbs script to troubleshooting wiki page.
