### ISSUE TITLE
Does shadowsocks windows client support vpn ?

### ISSUE THREAD

**Issue by yeweishuai** [shadowsocks/shadowsocks-windows#1005]
hi, guys
  Thanks you all for bringing such great tool to browse international sites.

   I was wondering whether ss windows version can proxy all netflow?   For example, when I want to play Other countries LOL(a game with client installed, not browser netflow),  can I use ss windows client to proxy my game netflow?

Thanks.

**Comment by celeron533** [comment]
You may could use SocksCap or ProxyCap.
