### ISSUE TITLE
shadowsocks连接成功。可是无法翻墙。什么情况啊？

### ISSUE THREAD

**Issue by guodong8698** [shadowsocks/shadowsocks-windows#1007]
shadowsocks连接成功。可是无法翻墙。什么情况啊？

**Comment by chenshaoju** [comment]
请具体描述一下，是什么现象，有无错误提示，以及Shadowsocks日志里有无信息。

**Comment by AmbroseRen** [comment]
![pac](https://user-images.githubusercontent.com/35362717/43045007-f41a6c3e-8de2-11e8-96e2-7caae9ebda34.png)
我的也显示连接上了，但就是无法翻墙。。。。

**Comment by chenshaoju** [comment]
你好，你用的是SSR，不是SS，这是两个不同的东西。

请仔细检查你的配置是否正确，如果仍然不能使用，请与你的服务商联系。

**Comment by AmbroseRen** [comment]
谢谢帮忙，已经弄好了，就是有点慢。我用的是ssr，ss用不了的。

**Comment by lori227** [comment]
使用kcptun加速可以翻墙, 但是直接使用shadowsocks服务器地址就不能翻墙了 为什么
![20180920171340](https://user-images.githubusercontent.com/10476776/45808563-97d48a00-bcf8-11e8-9f0a-7b41bbd9c631.png)
![20180920171401](https://user-images.githubusercontent.com/10476776/45808577-9acf7a80-bcf8-11e8-8b91-d3c08861fdae.png)

**Comment by lori227** [comment]
> 你那是服务器填的啥啊，找shadowsocks可用账号，我当时用的google+的免费账号亲测可用，就是卡成狗。用法呢就是扫描账号的二维码（跳节点网速很慢，如蜗牛），研究可用，但用的话还是用VPN加速器吧，或找代理网站也可。

服务器是我自己用shadowsocks搭建的服务器, 前面能翻墙 后来加了kcptun以后也没问题. 但是直接用shadowsocks就不行了  删了kcptun也不行, 哪里设置有问题吗

**Comment by AmbroseRen** [comment]
我用的是Proxy SwitchyOmega+shadowsocks，没用过kcptun+shadowsocks

**Comment by chenshaoju** [comment]
这个取决于你的服务端的设置，理论上结构应该类似于这样：
SS服务端－KCPTUN服务端－互联网－KCPTUN客户端－SS客户端－浏览器

如果你的SS服务端没有监听在公网端口上，而是监听在了本地环回（127.0.0.1）的话，你是没有办法从外网访问的。

另外，Shadowsocks For Windwos针对非SIP003协议的插件进行了支持，你可以试试看能否直接在SS客户端中调用KCPTUN。 https://github.com/shadowsocks/shadowsocks-windows/wiki/%E4%BD%BF%E7%94%A8%E9%9D%9ESIP003%E8%A7%84%E8%8C%83%E7%9A%84%E6%8F%92%E4%BB%B6

**Comment by discetingfeng** [comment]
大佬  能ping通也能连接上  就是无法访问外网

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history

**Comment by AmbroseRen** [comment]
![image](https://user-images.githubusercontent.com/35362717/67180365-027c5b80-f40c-11e9-9208-bfeb717560d8.png)
优质好用，反哺推荐！

**Comment by chenshaoju** [comment]
请不要发广告……

**Comment by AmbroseRen** [comment]
> 请不要发广告……

给你推荐更好用的啊，不用当没看见就好。我是被SSR坑过，又有人回复我，才回来给入坑的人推荐的。我总共测试过十多个VPN，良心推荐。

**Comment by akirasen** [comment]
> > 请不要发广告……
> 
> 给你推荐更好用的啊，不用当没看见就好。我是被SSR坑过，又有人回复我，才回来给入坑的人推荐的。我总共测试过十多个VPN，良心推荐。

嗯，本来没想回复的。我以前也用SS，SS挂掉了好不容易解决了，写了教程回来推荐给大家，不说赞美我的的互联网精神，还被说成广告。也是无语，我以前也以为只有SS能翻墙。。。

**Comment by akirasen** [comment]
> > 请不要发广告……
> 
> 给你推荐更好用的啊，不用当没看见就好。我是被SSR坑过，又有人回复我，才回来给入坑的人推荐的。我总共测试过十多个VPN，良心推荐。

不过你这个真的是广告啊

**Comment by chenshaoju** [comment]
Issue 是提供报告软件错误的地方。。。这不是论坛。。。

**Comment by Yufei-Z** [comment]
> 你好，你用的是SSR，不是SS，这是两个不同的东西。
> 
> 请仔细检查你的配置是否正确，如果仍然不能使用，请与你的服务商联系。

请问应该怎么做呢？我也遇到了类似问题

**Comment by Robinson-Arivan** [comment]
所以还在吵什么
