### ISSUE TITLE
找不到方法:“Void System.Security.Cryptography.RandomNumberGenerator.GetBytes

### ISSUE THREAD

**Issue by pulsaryu** [shadowsocks/shadowsocks-windows#1008]
`
System.MissingMethodException: 找不到方法:“Void System.Security.Cryptography.RandomNumberGenerator.GetBytes(Byte[], Int32, Int32)”。
   在 Shadowsocks.Encryption.IVEncryptor.randBytes(Byte[] buf, Int32 length)
   在 Shadowsocks.Encryption.IVEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.PipeConnectionReceiveCallback(IAsyncResult ar)
`

**Comment by celeron533** [comment]
Upgrade to .Net Framework 2.6.2

**Comment by chenshaoju** [comment]
@celeron533 4.6.2?

**Comment by celeron533** [comment]
@chenshaoju typo fixed
