### ISSUE TITLE
3.4.3版本Make the previous portable mode as default与Dropbox同步的问题

### ISSUE THREAD

**Issue by dobetter** [shadowsocks/shadowsocks-windows#1009]
3.4.3版本Make the previous portable mode as default
如果将Shadowsocks放在Dropbox中，则会出现一只同步ss_win_temp下的shadowsocks.log，并且同步不成功，提示权限不足！
有没有办法解决呢？

**Comment by chenshaoju** [comment]
你好，请在Dropbox的设置里将ss_win_temp目录取消同步即可。

**Comment by dobetter** [comment]
你说的是选择性同步吧，这样会在本地删除这个目录，没有达到想要的效果；所以目前只有整个shadowsocks目录放到Dropbox之外的目录下；或者使用之前版本！

**Comment by chenshaoju** [comment]
Hmmmm...看来和预想的不一样。。。

**Comment by dobetter** [comment]
是的，有没有什么设置可以把temp放到其他地方呢？

**Comment by hellofwy** [comment]
之前 temp 是在系统临时文件夹，后来移动到了现在的地方

**Comment by chenshaoju** [comment]
１.可以继续使用旧版本SS。
２.参考 http://iphone.91.com/tutorial/syjc/130704/21587885.html ，将 ss_win_temp 重定向到其他目录（未测试）。

**Comment by dobetter** [comment]
ok，谢谢，我来测试下。

**Comment by dobetter** [comment]
暂时使用旧版吧，方法2有点折腾，谢谢！

**Comment by wongsyrone** [comment]
可以参照之前的commit把gettemppath改一下就行了。

**Comment by hellofwy** [comment]
把 temp 默认放到 AppData\Local 会不会好点儿

**Comment by wongsyrone** [comment]
那个文件夹一般情况比较隐蔽，默认便携模式的初衷是不做不明了的事，所有用到的文件都在眼皮底下。

**Comment by dobetter** [comment]
能否让使用者自己选择放到哪里呢？比如通过设置可以放到 AppData\Local

**Comment by zwb1988** [comment]
能否制定一个启动参数，让用户指定临时文件privoxy的存放位置。我用OneDrive也有类似问题。
