### ISSUE TITLE
Feature request - HTTP proxy enhancements.

### ISSUE THREAD

**Issue by ufufufu** [shadowsocks/shadowsocks-windows#101]
Hello, 

I want to make a few suggestions about the built-in HTTP proxy.
1. Ability to change the default port (it is currently hardcoded to 8123) by end-user.
2. Ability to turn off the HTTP proxy.

Thanks.

**Comment by clowwindy** [comment]
No you can't. If you want to run multiple proxies, use other versions instead.

**Comment by ufufufu** [comment]
Is there any alternative versions available? shadowsocks-gui downloads already points to shadowsocks-csharp files.

**Comment by clowwindy** [comment]
http://sourceforge.net/projects/shadowsocksgui/files/dist/shadowsocks-gui-0.6.4-win-ia32.tar.xz/download
