### ISSUE TITLE
请提供可选便携模式的方法

### ISSUE THREAD

**Issue by li3shiyi** [shadowsocks/shadowsocks-windows#1010]
### Version(release version or AppVeyor link)
3.4.3

这个版本的 Make the previous portable mode as default 变更，直接取消了把临时文件放在正常临时目录的选择权。为了照顾小白用户可以更改默认设置，但不能取消选择权呀。

我在多台电脑同步shadowsocks等常用工具软件，更新了这个版本之后每启动一次都会同步新的临时文件，并且privoxy的conf文件名还不是唯一的，多台电脑同时使用时会有同步冲突。

**Comment by wongsyrone** [comment]
1. 做好同步设置是同步软件和用户的事情
2. 大量用户不知道在系统临时文件夹有Shadowsocks的相关文件，贸然清理导致大量同质化问题flood issue tracker
3. 可通过简单revert相关修改达到目的，或者手动修改gettemppath自行指定临时文件释放位置。

综上，wontfix

**Comment by li3shiyi** [comment]
1. 同步软件并无问题，而是由于临时生成的privoxy conf文件没有使用唯一的名称，导致先启动的电脑上有时privoxy会报错。
2. 私以为解决临时文件被清理的更好方法应该是在ss运行期间主动锁定相关文件。
