### ISSUE TITLE
有遇到过上传速度缓慢的问题吗？

### ISSUE THREAD

**Issue by aglent** [shadowsocks/shadowsocks-windows#1011]
之前用的旧版本 2.4
今天装了 最新的3.4.3 上传速度一下子慢了很多
对比了已下载的几个版本 发现老的2.4  2.5.1 是正常的  10MB/s满速
新的 3.3.6  3.4.2.1  3.4.3 的上传速度都很慢 只有200-400KB/s
我也测试了SSCap客户端 上传也是正常的
系统是win7 x64  联通100M对等
确认此问题在win7系统下出现 win10正常

**Comment by zhidd** [comment]
可否分享下流量，

**Comment by dobetter** [comment]
我对比测试也发现了这个问题，相同的服务器，相同的本地网络电脑，
使用3.4.2.1，上传速度：平均1MBps
但是使用2.5.8，上传速度：平均4MBps

差距非常的明显

**Comment by celeron533** [comment]
那么下载速度有影响吗？

**Comment by dobetter** [comment]
暂时还没有进行下载的详细测试，因为测试起来也比较花时间，之前以为上传慢是我的SS服务器问题，结果看到这个后 就进行了上传的详细的对比测试，目前发现上传确实变慢很多，无论是峰值还是均值速度。刚才测试使用2.5.8最高10MBps，和3.4.2最高接近3M差距明显。

**Comment by aglent** [comment]
我这里对等网络 win7 差距不是一点儿 完全是巨大反差 15倍以上  下载没有问题
但装win10就正常  比较奇怪
你试试 强制设置缓冲区 应该可以解决 目前只有这个办法
HKEY_LOCAL_MACHINE \SYSTEM \CurrentControlSet\Services\Afd\Parameters
新建DWORD   十进制
DefaultSendWindow = 65536
DefaultReceiveWindow = 65536
（4096的整数倍）

**Comment by wongsyrone** [comment]
Win 7 is not supported.

**Comment by yuanyuandige** [comment]
你试试 Shadowsocks-Qt5客户端？我用Shadowsocks-WIN客户端，每秒上传谷歌相册也就只有80K-90K，更换Shadowsocks-Qt5，速度恢复正常。

**Comment by C0DETyper** [comment]
Google搜索："TCP加速 Windows" 可以下载锐速serverspeeder开心版，以前不管什么服务器都是上传卡1.2m，开了这个直接跑满带宽（对全局网络有效，不管你使用什么工具）。下载提高百分之30左右，而且更稳定，上传提高到8倍。之前也是在一个youtube视频看到的
https://www.youtube.com/watch?v=NoO_1jToZPI
后来了解这种技术叫做TCP单边加速，应该不止锐速一家有，去百度一下就可以查到发布这种软件的公司，比如在linux服务端搭建的 BBR/BBR魔改版/BBRplus/锐速 都属于TCP单边加速，不过是搭建在linux服务端的，而上面所述是直接安装在Windows本机的，没有想到对上传速度有这么大的提升。可惜仅TCP可以这么做，udp加速是不存在单边加速的，比如流行的udpspeeder都是双边加速，所以想搭建游戏加速器靠从机场主买的服务器很难达到很好的效果，必须要自己搭建VPS（因为你要在服务端设置端口) 才能达到比较好的效果
这个东西算是拯救了我一个youtuber了，不知道为什么几乎没有人知道。。。问很多机场主也都不知道，，卖游戏加速线路的机场主也不会自己搭建udpspeeder然后给端口来优化游戏线路，，不知道为什么。。。

**Comment by C0DETyper** [comment]
还有楼主说的SSCap/SSTap速度正常，正常是不可能正常的，只是SSR/SS锁1.2m/s上传，SSTap/SSCap锁2.4m/s......我当时为了解决上传问题，把什么工具都下载下来了，买了无数机场的高速线路，还自己搭建了很多VPS,,但是不管再快的线路，不管哪个工具，老版本新版本的SS/SSR/V2ray/WireGuard都不能解决上传问题，只能用SSTap锁着2.4m/s勉强维持......然后用了Windows版本锐速以后我之前看不了4K的VPS上传都跑满带宽了。。5-6m/s左右，和上传国内速度一样了。。。比下载还快

**Comment by C0DETyper** [comment]
另外除了这个之外，服务端还有一个特殊的TCP优化方法
https://200cc.iteye.com/blog/2195733
Windows本机打开锐速
linux端安装魔改BBR+这种特殊的TCP优化
总算把我的辣鸡VPS救活了。。据说OpenVZ架构的也有用

**Comment by KKCAT-77** [comment]
直到2025.4.1 ，锐速serverspeeder开心版使用了半年，也不知道是不是失效了，300兆电信宽带以前开锐速，上传直接能跑到6mb/s，今天开始最高只能跑200-300kb/s，切换了无数节点，换了很多机场都无法解决!(挂梯子下载速度依然能跑满300兆)。但是跑国内的测速网站，下载上传速度一切正常！我tm严重怀疑是不是被狗日的电信qos了！真的是草了！只有挂梯子上传速度不行！
