### ISSUE TITLE
啥时候支持 Simple-obfs

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-windows#1013]

**Comment by wongsyrone** [comment]
算是long term plan吧，等不及可以发pr的说

**Comment by Sherlock-Holo** [comment]
建议作者做一个投票

**Comment by elvisw** [comment]
这个应该是支持SIP003 plugin标准吧

**Comment by Suwmlee** [comment]
在cygwin下编译了一个simple-obfs
https://github.com/Suwmlee/simple-obfs/releases
在Standalone模式下配合shadowsocks-windows使用。
