### ISSUE TITLE
ss_privoxy.exe被诺顿NS报毒，能否提交下白名单或者做下修改不被报毒

### ISSUE THREAD

**Issue by ccdasd123** [shadowsocks/shadowsocks-windows#1014]
之前是SS主程序被诺顿NS报毒，现在主程序不报毒了，temp和ss_win_temp里的ss_privoxy.exe均被诺顿NS报毒，SS版本是3.4.3。github这貌似没法传图片，所以希望能提交下白名单或者做下修改让诺顿NS不再报毒，要不每次更新一下都要排除很麻烦。谢谢了

**Comment by chenshaoju** [comment]
你好，我记得诺顿的设置里有一个排除目录的功能。你可以将SS的所在目录加入排除目录里。

**Comment by ccdasd123** [comment]
是的，我知道。谢谢你的回复。我的意思是能不能提交下白名单或者是让诺顿不再报毒，因为老的版本这个程序诺顿NS是不报的。我知道排除，因为排除确实很麻烦，更新一次就要排除一次，很麻烦的

**Comment by hellofwy** [comment]
@wongsyrone @chenshaoju 

我从这个 [sourceforge 地址](https://sourceforge.net/projects/ijbswa/files/Win32/3.0.26%20%28stable%29/)下载的 privoxy-3.0.26.zip，解压后 privoxy.exe 的 SHA-256 是： 2d1bfbeb00b23937791f9d8f51f2f9007e9c6515d0e08fd11cea8acf348572bd
这和我本地 temp 文件下的不同。但文件大小是一样的，都是 378,880 字节。

我本地 temp 文件下的和这次提交里的评论中的 SHA-256 相同：[cbc94e0eb7d148a677518fd23a7e1fba7a90bbbe](https://github.com/shadowsocks/shadowsocks-windows/commit/cbc94e0eb7d148a677518fd23a7e1fba7a90bbbe) 

是我下载的问题吗？

**Comment by wongsyrone** [comment]
不是，这个exe是修改过的二进制，屏蔽了创建托盘图标的系统调用。

**Comment by hellofwy** [comment]
哦，对，好像之前看到过有相关说明
不好意思，打扰了

**Comment by wongsyrone** [comment]
因为做了修改，所以报毒也很正常，可以自己看二进制diff。自己提交一下就行了，剩下的看Norton
