### ISSUE TITLE
"允许来自局域网的连接"无效

### ISSUE THREAD

**Issue by eastau** [shadowsocks/shadowsocks-windows#1016]
从2.5.8升级上3.4.3后"允许来自局域网的连接"失效，将shadowsocks.exe换回2.5.8后马上又正常了。操作系统是win10。两台移动设备Android7和ios10.2通过win10共享使用ss

后面每个版本试了一下，是从3.4.0开始，没办法连通的

**Comment by wongsyrone** [comment]
关闭『保护本地pac』

**Comment by eastau** [comment]
@wongsyrone 谢
