### ISSUE TITLE
Cannot login target.com when using shadowsocks

### ISSUE THREAD

**Issue by neandeny** [shadowsocks/shadowsocks-windows#1017]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by neandeny** [comment]
when using shadowsocks, I cannot login target.com and cannot add item to cart on walmart.com

**Comment by chenshaoju** [comment]
What your shadowsocks version?

**Comment by wongsyrone** [comment]
It doesn't seem to be an issue of Shadowsocks.
