### ISSUE TITLE
Support for SIP004

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-windows#1020]
https://github.com/shadowsocks/shadowsocks-org/issues/30

**Comment by asmadeus08** [comment]
Vote for adding new ciphers based on this discussion https://github.com/shadowsocks/shadowsocks-org/issues/30

**Comment by netroby** [comment]
seems aes-128-gcm  very fast.so please  add it. see shadowsocks-libev

**Comment by asmadeus08** [comment]
@netroby It's not only faster but safer too.

**Comment by lingbaoboy** [comment]
这个是急需功能啊😯
服务端以升级到最新，使用了AEAD协议，win上不知道用什么客户端…

**Comment by wongsyrone** [comment]
又冒出一个 https://github.com/shadowsocks/shadowsocks-org/issues/42 如果这个弄了，还得大改。
所以等协议彻底稳定再考虑，之前在win下可以编译cygwin的ss-libev，就是速度快不了

**Comment by hellofwy** [comment]
@lingbaoboy
麻烦问下，急需是主要基于那些方面考虑？

**Comment by lingbaoboy** [comment]
@hellofwy 
看了
https://blessing.studio/why-do-shadowsocks-deprecate-ota/
这篇文章后就中毒了，立马服务器立升级到3.0.1，使用ChaCha20-IETF-Poly1305加密
结果结果……win没有可用的客户端
你说急不急

**Comment by breakwa11** [comment]
@lingbaoboy 急什么，自发现到公开都相差4个多月了，就不差再多等两三个月了

**Comment by fiercebead** [comment]
自己用没被封过
@lingbaoboy 着急你就用https://github.com/shadowsocks/go-shadowsocks2
在VPS装好golang和git然后编译Win版本很容易
```
GOOS=windows GOPATH=/usr/local/etc/ go get github.com/shadowsocks/go-shadowsocks2
cd /usr/local/etc/bin/windows_amd64/
tar acf /root/go-shadowsocks2.exe.tar.xz go-shadowsocks2.exe
cd
```
后台自动运行https://github.com/shadowsocks/shadowsocks-go/issues/200#issuecomment-278875141
其实不嫌麻烦的人用VMware最好了，用上bbr还能提高上传速度，桥接网卡才有效

**Comment by ccsexyz** [comment]
@lingbaoboy   我想没被封的人应该更多哦，我自己用不支持 OTA 的 shadowsocks-py 用了快两年都没出过事

**Comment by lingbaoboy** [comment]
@ccsexyz @fiercebead 
你们不急我也就不急了，刚给路由器装个ss,可以支持最新的AEAD了

**Comment by hellofwy** [comment]
@lingbaoboy 
目前没有明显的迹象表明会主动探测。
我自己用没有 OTA 的，两个服务器快两年都没出过事。
如果是使用买的公开 ss 服务，被封的几率会高。

AEAD 算法相对来说更安全些，也就是可防止 CCA 攻击。
但其实如果平时对安全要求更高的地方上层用 HTTPS 就好了，不用太关心底层的 SS 协议。

**Comment by WeirdoShaw** [comment]
比起防火墙探测，我更纠结VPS搭的SS反倒被国外网站墙了（估计是防爬所以墙的IP段）……Pi**v、Exh***ai都是挂着梯子上不去……不过还是很想要支持AEAD的客户端。

**Comment by deeporist** [comment]
@WeirdoShaw 一点没错 我tm在ec2 加尼福尼亚北的 ip段全被ehenta拒绝掉了 原本就是看网上说ec2的电信线路渣 东京会绕弯 选加尼福尼亚会快的点 后来用上发现慢是不慢 但是就是死活打不开ehntai

**Comment by ZenFX** [comment]
现阶段在不用AEAD的情况下，服务端是开启OTA还是关闭OTA好？之前服务端一直都是强制OTA的。

**Comment by hellofwy** [comment]
@ZenFX 我自己这么想的：俗话说，不作就不会死。如果只考虑会不会被封，不论是关OTA，开OTA，还是AEAD，用那个都没什么问题，只要自己低调使用，不滥用就好。不是基于协议特征的发现服务器的方法也很多的。

**Comment by breakwa11** [comment]
@ZenFX 只有自己用的话，只要你不作死，一般都不会出什么问题，但也建议不要开OTA，因为能在无感知的状态下检测出来

**Comment by anadano** [comment]
我刚刚还跑到shadowocksR C#下问了。。。破娃大大说等shadowsocks windows适配了她再考虑

**Comment by pexcn** [comment]
目前发现这个可以用：https://github.com/fuckshadows/fuckshadows-windows/tree/shadowsocks

**Comment by wongsyrone** [comment]
Done.
