### ISSUE TITLE
请将临时文件放回系统临时文件目录

### ISSUE THREAD

**Issue by GongT** [shadowsocks/shadowsocks-windows#1022]
更新到3.4.3之后，运行shadowsocks会在程序旁边存放临时文件，这需要较高的权限，并且对同步盘很不友好。
临时文件还是应该放在别的地方。

**Comment by celeron533** [comment]
上次有人提到可弄一个选项，可以让用户选择临时文件的位置：

- 同文件夹
- 系统temp文件夹
- 用户特定文件夹

Pull Requests are welcome.

**Comment by wongsyrone** [comment]
> 这需要较高的权限

我不知道这需要多高的权限

> 对同步盘很不友好

做好同步设置和排除是同步软件该干的

一千个读者有一千个哈姆雷特。

**Comment by wongsyrone** [comment]
我只知道rsync可以方便的设置排除，并且可以增量更新。

**Comment by chenshaoju** [comment]
你好，你仍然可以使用旧版本的SS，如果有更新强迫症，可以使用这个命令将SS的ss_win_temp 目录映射到其他位置：
```
mklink /J "C:\Program Files (x86)\Shadowsocks\ss_win_temp" E:\ss_win_temp
```

其中 C:\Program Files (x86)\Shadowsocks\ss_win_temp 是你的SS所在目录， E:\ss_win_temp 是要转移到的目标目录。

如果目录中有空格，需要用英文半角双引号将路径包围。

**Comment by wongsyrone** [comment]
之前放在系统temp文件夹，很多人强迫症随意清除临时文件夹，然后不能用了就来发issue，我也不知道为啥不能用了。

所以会维持目前临时文件夹的位置，对小白透明友好。
如果有兴趣自己改gettemppath的代码，放到自己喜欢的位置，怎么改可以看commit history。

**Comment by GongT** [comment]
这是windows客户端。但 OneDrive 目前还不支持排除。。这个功能早就题给微软了，他们也接受了，但是一年过去。。。LOL

所以用junction也不行，onedrive还是会把临时文件同步掉。。。

权限问题是特殊情况，如果把ss放在普通用户只读的地方就会出问题。。。（其实配置文件也有这个问题，但只是修改配置会失败而已，不会不能运行）

看起来那个加个选项的pr挺不错

**Comment by JiyongShi** [comment]
可以使用Application.LocalUserAppDataPath或者Application.UserAppDataPath，避免了temp文件夹清理问题，也解决了权限、同步问题

**Comment by zypA13510** [comment]
其实解决方法不是很简单吗，增加一个命令行参数不好吗。没有参数时默认小白配置，但是至少可以手动指定啊。现在这样不管怎么都移不走，连指定启动目录（CurrentDirectory）也不行。
而且这也不符合Windows应用程序的标准吧，正常都是塞到LocalApplicationData里面的，为什么要标新立异。

**Comment by chenshaoju** [comment]
@zypA13510 按照规范来说，的确应该放在 %temp% 文件夹中，但实际情况比较复杂。两年前就不断的有用户反映运行时会随机的崩溃（ https://github.com/shadowsocks/shadowsocks-windows/issues/330 ），是由于一些系统优化软件定时清理 %temp% 导致的，该问题无解，而且频繁有人报告该问题，所以后来加了portable模式，放一个文件就行，但是仍然有人不断的报告该问题，最后只能将portable设置为默认才彻底消停。

当然，如果愿意提交改进该功能的源码，非常欢迎。

**Comment by zypA13510** [comment]
@chenshaoju 我敢说我理解一定准确，不过说规范的话，我觉得各种依赖的exe,dll应该是放在程序同一路径下的（如果必要可能需要安装程序），而配置一般在LocalAppData里面（也有某些直接exe什么的也放这，比如chrome, uTorrent），最后临时文件和log放在temp下。也就是说temp路径下的，既然能清理成功，说明没有正在被占用，应该是不影响程序运行的。
另外 #330 里面说，什么某国产应用直接不分青红皂白把所有临时文件都删了，我觉得这个issue应该报给快播。或者更专业的说，这个是out of scope的。

源码的话，我已经好几年没做Windows开发了，新系统连VS都没装。如果近期有时间也许可以contribute, no promise tho.
