### ISSUE TITLE
ss_win_temp 文件夹是否可以移到别处？以及关于多终端同步使用的问题。

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadowsocks-windows#1025]
你们难道没有多PC使用SS的场景吗？

我原本以为把Shadowsocks整个文件夹丢进Dropbox即可实现任意电脑使用同样的配置，不过现在发现，Dropbox会一直同步ss_win_temp文件夹下的内容且无法完成。特别是Shaodowsocks.log文件。

我的建议是：

1. 按照旧版Shadowsocks的逻辑，需要添加一个txt文件使之绿色化。
2. 可以关闭shadowsocks.log文件，也就是关闭产生日志（但是并不合理）。

更长远的建议是，希望可以把配置相关的文件存储在云端，这个云端环境可以是自行配置的。

**Comment by UP24** [comment]
之前用onedrive同步ss的配置文件，在两台电脑上用，但是发现有时候并不是很好用，因为都设置了开机自启动，配置文件会被占用，导致无法同步。

如果你可以使用同步功能的话，可以仅同步某几个文件，不选ss_win_temp文件夹。

**Comment by DearTanker** [comment]
@UP24 Dropbox还能选择性同步？

**Comment by DearTanker** [comment]
@UP24 感谢，还真有选择性同步，我赶紧试试

**Comment by aoxue** [comment]
建议ss_win_temp目录可配置，或者恢复原来的配置机制
我也有这个问题 ，OneDrive选择性同步不是很方便，会在本地文件夹上显示一个大大的叉叉

**Comment by jinliming2** [comment]
使用Windows 7或更新的系统的话，可以使用符号链接来实现。
可以把配置文件或是要同步的文件直接剪切到同步盘里，然后在SS所在目录使用mklink命令创建符号链接指向同步盘里的那些文件即可。
可以把几条命令写成bat/cmd批处理，即可在新电脑上快速配置。

**Comment by xdeng** [comment]
遇到同样问题，坚果云同步的时候，会产生一些冲突文件。

**Comment by DearTanker** [comment]
目前用Dropbox忽略同步ss_win_temp文件夹后，正常稳定使用中。

**Comment by JiyongShi** [comment]
可以使用Application.LocalUserAppDataPath或者Application.UserAppDataPath，避免了temp文件夹清理问题，也解决了权限、同步问题

**Comment by celeron533** [comment]
@JiyongShi 权限倒不是很大的问题，主要问题是有些用户会用一些优化软件清理各种temp文件夹（系统temp，用户temp等），导致正在运行的ss-win出现问题

**Comment by JiyongShi** [comment]
@celeron533 temp文件夹从长期运行角度来说，肯定不合适，这点windows自己的磁盘清理也是包括在其中的。
Application.LocalUserAppDataPath对应路径："C:\\Users\\??\\AppData\\Local\\Shadowsocks\\Shadowsocks\\3.4.3.0"
Application.UserAppDataPath对应路径："C:\\Users\\??\\AppData\\Roaming\\Shadowsocks\\Shadowsocks\\3.4.3.0"
这种用户数据路径，一般是不会清理的

**Comment by ipcjs** [comment]
加配置文件指定`ss_win_temp`目录也是可以的，Dropbox选择性同步设置起来并不方便。

**Comment by chenwq3** [comment]
Windows 磁盘清理的确会试图清理ss在临时文件中的文件。为了克服该问题，于是就多了ss_win_temp，不过又产生了另外一个问题，我ss放在onedrive上的。所以临时文件也同步了。
不过目前尚未遇到冲突问题。或者冲突问题发生了，而我没有发现。
哈哈。

**Comment by GongT** [comment]
真的是个大问题，用portable.txt吧！

@jinliming2 OneDrive不同步链接，它会把目标文件夹给同步掉。。。很蛋疼。。。

**Comment by chenwq3** [comment]
刚才试了一下，在同一位置创建一个空的文件“shadowsocks_portable_mode.txt”没有作用。

**Comment by GongT** [comment]
@chenwq3 毕竟这个功能还没实现😂

**Comment by yusiwen** [comment]
是否可以考虑把这个目录放到%TMP%目录里，即C:\Users\XXX\AppData\Local\Temp

我也遇到了同步ss整个目录的问题，一直提示同步ss_win_temp目录失败

**Comment by choicky** [comment]
坚果云没有排除子文件夹同步的功能，所以我经常遇到 `ss_win_temp` 因为正在同步而无法读写导致 ss 启动失败。

暂时用了一个笨方法来解决这个问题：

1、禁用 ss 的开机自动启动（最近两年实际上ss都没有成功地开机自动启动，不知是bug还是我电脑问题）

2、写一个 bat 脚本，这脚本先删除 `ss_win_temp`再启动ss

3、这脚本或者其快捷方式可丢在 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` 以实现开机自动运行。

```
@echo off

echo Deleteing ss_win_temp...
rmdir /s/q D:\Program\Shadowsocks\ss_win_temp

echo Starting Shadowsocks...
start "Starting Shadowsocks" "D:\Program\Shadowsocks\Shadowsocks.exe"

exit
```

**Comment by celeron533** [comment]
@choicky 开机启动无效常见的原因：
1. 使用了管理员权限导致失败
2. 反病毒软件

**Comment by choicky** [comment]
@celeron533 两台win10电脑都是裸奔，没有杀毒软件。
也尝试过使用 管理员打开 ss 客户端然后再电机开机启动。

最近一两年都只好自己搞个快捷方式，丢到 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` 中。
