### ISSUE TITLE
无法用shadowsocks上网,log报错。

### ISSUE THREAD

**Issue by R-Josef** [shadowsocks/shadowsocks-windows#1026]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
2.5.2.0

### Environment(Operating system, .NET Framework, etc)
win10 .net4.6 

### Steps you have tried
remove all config of shadowsocks

### What did you expect to see?
i can access insternet by shadowsocks

### What did you see instead?
i can't access internet by shadowsocks

无法用小飞机上网，打开log以后发现一直在重复下列错误报告。求解答！

### Config and error log in detail (with all sensitive info masked)
[2017-02-06 08:40:47] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   在 System.Security.Cryptography.MD5.Create()
   在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   在 Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   在 Shadowsocks.Encryption.PolarSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.Handler.CreateRemote()
   在 Shadowsocks.Controller.Handler.StartConnect()

**Comment by celeron533** [comment]
请尝试使用最新版的SS-win客户端（3.4.3及后续版本）

**Comment by Sak1tama** [comment]
@celeron533 我知道原因，他的win 10 没装上net 3.5 ，所以有些函数找不到

**Comment by R-Josef** [comment]
@celeron533 @Sak1tama 我安装了.net 3.5但是没用，

**Comment by R-Josef** [comment]
换了最新版以后已经解决了，谢谢

**Comment by celeron533** [comment]
解决掉的话可以close issue
