### ISSUE TITLE
如何让所有国外网站都走ss，国内网站全部直连？

### ISSUE THREAD

**Issue by Jermin** [shadowsocks/shadowsocks-windows#1031]
有没有办法实现android版那样的自动分流？

**Comment by celeron533** [comment]
1. 全局：SS-win支持pac脚本。
2. 部分：基于chrome类核心的浏览器使用扩展switchyomega来智能切换代理，但是作用于仅限于浏览器自身。
3. 基于自动检测目标站点：没有内置这个功能，可能有第三方工具可以做到。

**Comment by ShinoharaYuri** [comment]
https://github.com/cyfdecyf/cow
可以跑在樹莓派上面【Pi 1需要自己編譯一下
