### ISSUE TITLE
无法打开Onedrive网页

### ISSUE THREAD

**Issue by cliffzhou** [shadowsocks/shadowsocks-windows#1032]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
Win 10 Pro x64 zh-CN，1607版

### Steps you have tried
使用本地PAC

### What did you expect to see?
正常打开Onedrive网页

### What did you see instead?
EDGE/IE 页面反复刷新，打不开 onedrive.live.com，并在地址栏后反复追加&mkt=zh-CN

### Config and error log in detail (with all sensitive info masked)
已为onedrive指定hosts。
如果我换用其他github上的gfwlist2pac作为在线PAC，而不是使用程序更新的本地pac的话，就不会有问题。
初步怀疑是程序自带的gfwlist源有问题。

**Comment by celeron533** [comment]
程序自带的gfwlist非常古老
`shadowsocks-windows\shadowsocks-csharp\Data\proxy.pac.txt.gz\`
20141104
目前还是建议第一次使用前先更新一下

![image](https://cloud.githubusercontent.com/assets/3608762/23797410/b601a296-05da-11e7-8e89-72f53c34dea4.png)
