### ISSUE TITLE
如何知道我现在已经安装的是哪个版本？

### ISSUE THREAD

**Issue by zzzgit** [shadowsocks/shadowsocks-windows#1033]
去年安装了windows 的 shadowsocks，我现在想知道装的是哪个版本，能查到吗？
这个软件能自动更新吗？

**Comment by breakwa11** [comment]
exe文件右键属性

**Comment by zzzgit** [comment]
2.5.2很旧了，咋办？

**Comment by celeron533** [comment]
@zzzgit https://github.com/shadowsocks/shadowsocks-windows/releases 后续的版本都有自动更新功能。
