### ISSUE TITLE
允许来自局域网的连接，何时加的这个功能？

### ISSUE THREAD

**Issue by zzzgit** [shadowsocks/shadowsocks-windows#1034]
用了一年多，昨天才发现，有“允许来自局域网的连接”这个功能，以前我试着用电脑给手机做代理，怎么试都没有成功，昨天把这个选项选上，就OK了

**Comment by hellofwy** [comment]
2.0.5 2014-11-09
- Fix QRCode size
- Share over LAN option
- Log to temp path instead

https://github.com/shadowsocks/shadowsocks-windows/blob/master/CHANGES

**Comment by zzzgit** [comment]
为啥默认不允许呢

**Comment by chenshaoju** [comment]
你不希望网络中的其他人未经你的允许使用你的服务器把？
