### ISSUE TITLE
使用ipv6代理时出现“ 以一种访问权限不允许的方式做了一个访问套接字的尝试”

### ISSUE THREAD

**Issue by gerwang** [shadowsocks/shadowsocks-windows#1035]
### Version(release version or AppVeyor link)
3.4.3 release

### Environment(Operating system, .NET Framework, etc)
Windows10 64bit 教育网

### Steps you have tried
为bandwagon vps分配ipv6地址
在shadowsocks.json中修改为"server":"::"
在windows客户端下用ipv4地址成功代理
将地址改为同一个vps的ipv6地址后显示ERR_CONNECTION_CLOSED
(PS:在shadowsocks-android端用ipv6地址成功代理)

### Config and error log in detail (with all sensitive info masked)
[2017-02-18 20:38:14] System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by celeron533** [comment]
这看上去不像是一个合法的地址啊
```
在shadowsocks.json中修改为"server":"::"
```

**Comment by gerwang** [comment]
> 在shadowsocks.json中修改为"server":"::"

这句话就是同时监听v4和v6的流量的意思吧。
目前我的问题已解决。
### 补充：我之前用了finalspeed
我发现每当我尝试使用finalspeed的时候，finalspeed会显示`443端口连接失败`，关掉finalspeed后直接连ss也连不上。在重启几次finalspeed并修改设置（总之就是瞎折腾）几次后突然直连ss就能用了，问题解决。目前已没有使用finalspeed，具体原因还需要考证。
