### ISSUE TITLE
打不开右键编辑快捷键

### ISSUE THREAD

**Issue by Stephen-Li** [shadowsocks/shadowsocks-windows#1036]
### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
Win10 64bit 电信

### Steps you have tried
右键菜单编辑快捷键

### Config and error log in detail (with all sensitive info masked)
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.View.HotkeySettingsForm.LoadConfiguration(HotkeyConfig config)
   在 Shadowsocks.View.HotkeySettingsForm..ctor(ShadowsocksController controller)
   在 Shadowsocks.View.MenuViewController.ShowHotKeySettingsForm()
   在 Shadowsocks.View.MenuViewController.hotKeyItem_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.Command.DispatchID(Int32 id)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by hellofwy** [comment]
也许是安全类软件限制了设置快捷键。

**Comment by wongsyrone** [comment]
删掉配置文件，重新打开程序设置。
