### ISSUE TITLE
connect to manifest.robertsspaceindustries.com:80

### ISSUE THREAD

**Issue by petralian** [shadowsocks/shadowsocks-windows#1037]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
Windows 10 fully up to date

### Steps you have tried
All settings the app has to offer

### What did you expect to see?
When opening CIGLauncher (the launcher for Star Citizen) it doesn't show me the launcher. When changing a setting in Shadowsocks it then shows the launcher but it is not tunneled correctly via Shadowsocks.

### What did you see instead?
Nothing... until I change a setting (guess changing settings cut the tunnel off for a moment?)

### Config and error log in detail (with all sensitive info masked)
[2017-02-19 11:50:57] Shadowsocks started
[2017-02-19 11:51:00] connect to eas.outlook.com:443
[2017-02-19 11:51:00] Socket connected to ss server: HK-HGC ****************
[2017-02-19 11:51:02] connect to manifest.robertsspaceindustries.com:80 <<< this is the one that doesn't work...
[2017-02-19 11:51:02] Socket connected to ss server: HK-HGC ****************

**Comment by hellofwy** [comment]
Shadowsocks-windows is just a proxy, so your app has to able using proxy.
Please check if Star Citizen supports proxy.

**Comment by petralian** [comment]
Should it not work by using "global proxy"? There used to be an app called proxifier which in the time could send all the app's traffic through a proxy on 127.0.0.1. I used that to play Word of Warcraft when it was blocked in China. Can Shadowproxy offer the same? Any way to add the full traffic of an app or redirect the entire pc's traffic like VPN would?

**Comment by hellofwy** [comment]
"global proxy" means all traffic through Shadowsocks-windows will been directed to your remote Shadowsocks server.

Shadowsocks-windows don't provide the "proxifier" capability.

By default, Shadowsocks-windows launchs a proxy listen on 127.0.0.1 at port 1081. So you can use some "proxifier" apps to redirect the "entire traffic" they support to Shadowsocks-windows.

**Comment by petralian** [comment]
Awesome, thanks so much for your clear instructions! I will see what I can do from here. Would you ever add an "add program" function to Shadowsocks? Proxifier, proxycap and such are very outdated and unsupported now. It would be of great help to include this function.

**Comment by hellofwy** [comment]
I don't have enough knowledge to implement this function.
Hope someone will implement this.
