### ISSUE TITLE
更换编译选项后软件找不到模块

### ISSUE THREAD

**Issue by yanqiyu** [shadowsocks/shadowsocks-windows#1038]
<img width="1356" alt="2" src="https://cloud.githubusercontent.com/assets/3437889/23112751/ca0795fa-f76d-11e6-979d-b06d19b822e4.png">
如图

**Comment by yanqiyu** [comment]
可不可以发行一个包含libsscrypto.dll源代码的版本

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/libsscrypto
