### ISSUE TITLE
这个软件的内核是自己开发的吗

### ISSUE THREAD

**Issue by zzzgit** [shadowsocks/shadowsocks-windows#1039]
软件的内核是自己开发的吗？
为什么我在苹果市场搜到很多很多shadowshock的app，他们是同一个内核？

**Comment by celeron533** [comment]
因为代码是开源的，所以人人都能改。但是有些组织机构改完后不再开放他们的修改，这点很不好。
这里是最原版的shadowsocks。

**Comment by zzzgit** [comment]
这里都用中文讨论了，牛逼，中国人对这个的需求是世界上最大的

**Comment by wongsyrone** [comment]
你说的那个内核是shadowsocks-libev吧，win这个估计还没啥用的。

**Comment by pexcn** [comment]
内核？是协议吧？--> https://shadowsocks.org/en/spec/protocol.html
