### ISSUE TITLE
windows update

### ISSUE THREAD

**Issue by ghosoft** [shadowsocks/shadowsocks-windows#1040]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
windows10

### Steps you have tried
1. 我把
||microsoft.com/
||windowsupdate.com/
||windows.com/
加进了user-rule

2. 用了fiddler

都不好使

### What did you expect to see?
windows update能正常更新

### What did you see instead?
一直卡在正在检测更新的状态

### Config and error log in detail (with all sensitive info masked)

**Comment by hellofwy** [comment]
win10 更新有国内服务器吧，需要添加规则？

**Comment by ghosoft** [comment]
添麻烦了, 关了吧, 好使了

不过更新了user-rule之后点保存可以看到日志中马上就有检测到规则更新, 但是实际上有个延迟才生效么?


2017-02-21 

zhaitao27 



发件人：hellofwy <notifications@github.com>
发送时间：2017-02-21 11:11
主题：Re: [shadowsocks/shadowsocks-windows] windows update (#1040)
收件人："shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>
抄送："zhaitao"<zhaitao27@163.com>,"Author"<author@noreply.github.com>

win10 更新有国内服务器吧，需要添加规则？

**Comment by hellofwy** [comment]
没看相关功能实现代码，从你的描述来看，规则文件更新后是会自动生效的，不用重启 ss-windows。

**Comment by wongsyrone** [comment]
从 https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/PACServer.cs#L53 你能看到，默认带了个t参数，这个的目的是不让系统缓存pac文件，估计你说等一会才生效就是旧缓存过期了，之后重新载入新的。理论上检测到user-rule变化了就更新到pac.txt里面了。

一个可能相关的东西：https://support.microsoft.com/en-us/help/271361/how-to-disable-automatic-proxy-caching-in-internet-explorer
