### ISSUE TITLE
Shadowsocks 已停止工作

### ISSUE THREAD

**Issue by wangshijun101** [shadowsocks/shadowsocks-windows#1041]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
shadowsocks-3.4.3

### Environment(Operating system, .NET Framework, etc)
windows 7, Service Pack 1
.Net Framework 4

### Steps you have tried
双击打开 Shadowsocks.exe 即出现 “Shadowsocks 已停止工作” 弹框。
尝试 3.3.3 版本的后，运行 .exe 程序不出现任何提示，taskbar 没有任何窗口打开，任务管理器中也找不到 shadowsocks 的程序进程。
### What did you see instead?
![qq 20170221133109](https://cloud.githubusercontent.com/assets/7992941/23152756/2e40ca06-f83f-11e6-83be-75444cfe4f95.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by hellofwy** [comment]
试试安装 Microsoft .NET Framework 4.6.2：https://www.microsoft.com/zh-CN/download/details.aspx?id=53344

https://github.com/shadowsocks/shadowsocks-windows/releases/tag/3.3.3
3.3.3 已经要 Microsoft .NET Framework 4.6.2 了

**Comment by xiaofeng-ling** [comment]
确实是.NET的问题，升级到4.6.2就可以了
