### ISSUE TITLE
windows7 x64旗舰版支持的版本最高到多少？

### ISSUE THREAD

**Issue by justyu** [shadowsocks/shadowsocks-windows#1042]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
最新版3.4.3

### Environment(Operating system, .NET Framework, etc)
window7 旗舰版，x64

### Steps you have tried
从ms官网下载.net 4.6.2，然后安装失败啊

win7 x64旗舰版不支持.net 4.6.2，那么最高支持客户端版本是多少啊？

**Comment by hellofwy** [comment]
3.3.3 已经要 Microsoft .NET Framework 4.6.2 了
请下载之前版本：
https://github.com/shadowsocks/shadowsocks-windows/releases

Microsoft .NET Framework 4.6.2 支持 Win7 SP1：https://www.microsoft.com/zh-CN/download/details.aspx?id=53344

可以先更新到 Win7 SP1

**Comment by kuhanzhu** [comment]
我win7可以安装4.6.2的

**Comment by aifans** [comment]
我是win7 x64 sp1， 安装了Microsoft .NET Framework 4.6.2。使用最新3.4.3版本。
无法保存设置的服务器。。。。。所以只能回退到3.0.0版本。

**Comment by aifans** [comment]
具体就是在编辑服务器页面里，填写好地址、端口等等信息以后，点击添加按钮，能正常添加。点击确定按钮关闭窗口以后，再打开编辑服务器页面，列表中出现服务器地址，但是右边的内容是空的，点击列表中的服务器，提示非法的服务器地址。
但是直接查看目录中的gui-config.json，服务器的信息都存在。

**Comment by aifans** [comment]
退出再重新打开，直接显示编辑服务器的窗口，都是默认值，就像是第一次打开一样。

**Comment by celeron533** [comment]
@aifans 这种现象也是第一次见到，建议：
1. 更换文件夹。有时候各种访问权限会导致奇奇怪怪的问题。一般`C:\`, `C:\Windows`, `C:\Program Files`之类的都会有权限保护。
2. 暂时禁用杀毒软件或管家软件。

**Comment by aifans** [comment]
我是绿色版运行的。放在D:\GreenSofts\ShadowSocksWin这里了。

**Comment by justyu** [comment]
下载了3.3.2.0，可以正常使用。
