### ISSUE TITLE
代理模式能否增加一种，只代理国外地址？

### ISSUE THREAD

**Issue by qadet123** [shadowsocks/shadowsocks-windows#1043]
就是类似手机ss上的那种，过滤局域网和国内地址，只代理国外地址的模式？这样即不用考虑pac列表问题，又不用担心国外地址没有被墙但正常访问速度缓慢的问题，谢谢。

**Comment by hellofwy** [comment]
根据我的理解，shadowsocks-windows 目前无法实现这个功能，因为 代理 的原理是基于域名的，而域名由远程服务器解析，所以不能根据 IP 区分。

**Comment by qadet123** [comment]
所以希望作者是不是可以添加这样一种代理模式，这种模式相对比较实用，不需要考虑pac列表，也不需要用户手动去通过其他途径添加那些没有被墙，但是访问缓慢的网站，只需要把地址段做一下区分就可以获得比较好的使用效果

**Comment by hellofwy** [comment]
工作量很大，而且需要新知识。
我也希望能有这个功能。

**Comment by ThreeGold127** [comment]
对，这个模式就是有些openwrt路由器里的shadowsocks集成的chnroute模式，确实挺好使的

**Comment by catchchances** [comment]
同感，如果作者有空，可以考虑一下。感谢

**Comment by JonasGao** [comment]
如果是 Mac 推荐使用 [PlutoX](http://www.plutox.top/), 如果是 Windows 可以尝试 [cow](https://github.com/cyfdecyf/cow), 不过 cow 不是国家模式，而且也有段时间没更新了。
