### ISSUE TITLE
PAC匹配部分url无效

### ISSUE THREAD

**Issue by clementhk** [shadowsocks/shadowsocks-windows#1044]
http://www.bbc.com/zhongwen/simp/

GFWList文件里有 `.bbc.com/zhongwen`

PAC模式下无法打开，Global模式下可以打开。

**Comment by hellofwy** [comment]
可以自己添加规则

**Comment by clementhk** [comment]
@hellofwy 知道，这个是个bug report，PAC模式下匹配不了`.bbc.com/zhongwen`，GFWList里有非常多这种规则，要不说明不支持这种规则要不应该是bug。

**Comment by hellofwy** [comment]
如果是 bug report，按模板多提供些配置信息

**Comment by clementhk** [comment]
This is an interesting issue, it looks like a PAC problem because http://www.bbc.com/zhongwen/simp/ is not going through proxy (IE) while it is defined in PAC.
When debugging with the PAC file, it seems like it should work, but in reality it doesn't..

```
FindProxyForURL('http://www.bbc.com', 'www.bbc.com')
"DIRECT;"
FindProxyForURL('http://www.bbc.com/', 'www.bbc.com')
"DIRECT;"
FindProxyForURL('http://www.bbc.com/test', 'www.bbc.com')
"DIRECT;"
FindProxyForURL('http://www.bbc.com/zhongwen', 'www.bbc.com')
"PROXY 127.0.0.1:1080;"
FindProxyForURL('http://www.bbc.com/zhongwen/test', 'www.bbc.com')
"PROXY 127.0.0.1:1080;"
```

**Comment by clementhk** [comment]
Note that it doesn't work in both shadowsock-windows and ShadowsocksX-NG PAC mode, but shadowsocksr-csharp works.
Here's the difference, https://www.diffchecker.com/SyhFzrqM , I'll patch shadowsock-windows and see if it works.

**Comment by clementhk** [comment]
Sorry I was wrong, shadowsocksr-csharp only works with "绕过大陆常见域名列表"..

**Comment by Atavic** [comment]
I've never seen the same domain listed more than one time in a .pac file. Here I see:
`FindProxyForURL('http://www.bbc.com', 'www.bbc.com')
"DIRECT;"
FindProxyForURL('http://www.bbc.com/', 'www.bbc.com')
"DIRECT;"
FindProxyForURL('http://www.bbc.com/test', 'www.bbc.com')
"DIRECT;"
FindProxyForURL('http://www.bbc.com/zhongwen', 'www.bbc.com')
"PROXY 127.0.0.1:1080;"
FindProxyForURL('http://www.bbc.com/zhongwen/test', 'www.bbc.com')
"PROXY 127.0.0.1:1080;"`

Some entries are redundant, just leave one entry per domain:
`FindProxyForURL('http://www.bbc.com', 'www.bbc.com')
"DIRECT;"
FindProxyForURL('http://www.bbc.com/zhongwen', 'www.bbc.com')
"PROXY 127.0.0.1:1080;"`

Hope it helps.

**Comment by clementhk** [comment]
Hi @Atavic thanks for joining, the pac file originally from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt then converted to pac by shadowsocks clients (I think), so it is the clients job to fix it if the pac doesn't work.
I'm not in China currently, I will look more into it next time I go back to China if it is not fixed yet.
