### ISSUE TITLE
Enable TCP Fast Open for Windows

### ISSUE THREAD

**Issue by icylogic** [shadowsocks/shadowsocks-windows#1045]
>But even without TLS 1.3, we can combine TCP Fast Open and the TLS False Start option, and reduce the delay from 3-RTT to 1-RTT.
![](https://winblogs.azureedge.net/win/2016/06/TFS-TFO-Diagram-1024x562.png)
https://blogs.windows.com/msedgedev/2016/06/15/building-a-faster-and-more-secure-web-with-tcp-fast-open-tls-false-start-and-tls-1-3/#ebufEVtM1OLzRVuc.97

TCP Fast Open on Windows (Anniversary Update):

```C#
var s = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
var e = new SocketAsyncEventArgs();
s.SetSocketOption(SocketOptionLevel.Tcp, (SocketOptionName)15, true);
e.SetBuffer(buffer, offset, length);
s.ConnectAsync(e);
```

Values for socket options are defined in `10.0.14393.0\shared\ws2ipdef.h`

https://msdn.microsoft.com/en-us/library/windows/desktop/ms738596(v=vs.85).aspx

After receiving the TFO Cookie, we could send SYN+Data with Cookie:

![2017-02-22_09-29-57](https://cloud.githubusercontent.com/assets/2814357/23215799/a0c56ddc-f8e1-11e6-9a2b-05eea0b23e83.png)

TFO has been available for shadowsocks servers on linux for years. I tried to introduce this feature into shadowsocks windows, but it seems to be a big change for the most critical parts (TCPRelay, Socks5Proxy, WrappedSocket, etc.) So I put information here and leave it for you to decide.

**Comment by pexcn** [comment]
win7也支持吗？

**Comment by icylogic** [comment]
@pexcn 
![2017-02-22_10-04-01](https://cloud.githubusercontent.com/assets/2814357/23217148/4a4691fc-f8e6-11e6-889a-16e11c093c34.png)

**Comment by pexcn** [comment]
哦哦，原来如此…

**Comment by wongsyrone** [comment]
The best way to do so is to create another x86 build profile and use the preprocessor to distinguish different profiles. For TFO variant, one should check OS when the program startup.

**Comment by icylogic** [comment]
@wongsyrone That would definitely work. 
But the hardest part is that all of the code relating to sockets follows the `call Connect method ->  ConnectedCallback -> wait to Send/Read` pattern. To take advantage of TCP Fast Open, when a new TCP connection is to be established between the local proxy server and the remote server, the program should use a new pattern: prepare a buffer filled with data to send and call `socket.ConnectAsync`, which may send data during handshaking. Otherwise it's meaningless to use this feature. 

That is, instead of opening a connection and [waiting for data to send](https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/TCPRelay.cs#L750-L767), it waits for the first bytes and then connect while sending these bytes and SYN in a single TCP segment (if it has received the TFO cookie from the same server in previous connecions).

Here's how libev use this feature: https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/local.c#L316-L420 . It waits for data to send and then start a new connection to server if necessary. The way to connect is determined by checking the fast_open option.

If we want to make this feature as an option for every ServerConfig, after reloading the config, this option could be toggled.

See also https://lwn.net/Articles/508865/

**Comment by wongsyrone** [comment]
I'm no longer maintaining this project, you can submit your changes as the reference.

**Comment by Mygod** [comment]
I just took a look and it sure seems quite bothersome to implement. On shadowsocks-android (which is a wrapper of shadowsocks-libev though), TFO is implemented as a global switch: If the system allows it, it will always be used and fall back automatically to the traditional handshakes if client and/or server doesn't seem to support it. The switch is only there for diagnosis purposes.

**Comment by wongsyrone** [comment]
We have to support Windows 7 at least, which is troublesome.

**Comment by wongsyrone** [comment]
1. The gain may not be noticeable compared to the current way.
2. There are no public documentations from MS side, which means the feature hasn't been frozen.

**Comment by Mygod** [comment]
1. I agree.
2. But there is.

**Comment by wongsyrone** [comment]
What will happen if the remote endpoint doesn't support TFO? Should I resend or the OS will handle this for me?

**Comment by wongsyrone** [comment]
I think I got this sorted out.

1. convert to SAEA pattern
2. add check for Win 10 1607 and higher and only set TFO socket option on these supported platforms
3. Set buffer when initial SAEA used when invoking ConnectAsync and start ReceiveAsync when Completed event triggered.

Based on my test, data attached to ConnectAsync will be sent out even if TFO is not supported.

**Comment by wongsyrone** [comment]
I'm a beginner at SAEA pattern. If you want to help to debug, install VS 2017, .NET 4.6.2 development pack and don't use AEAD ciphers.

The WIP version is located at https://github.com/fuckshadows/fuckshadows-windows/commits/refactor-net-module.

**Comment by wongsyrone** [comment]
Just came up another idea to support this

1. drop Forward Proxy support
2. simplify client handshaking, read as many as possible
3. Parse address buffer in one operation
4. Encrypt the first packet, since it may contain additional data
5. Use Socket.ConnectAsync and SetBuffer
6. Others remain the same.

**Comment by wongsyrone** [comment]
Please note that the initial send buffer (encrypted, typically the Address Buffer) attached to Socket.ConnectAsync should not exceed MSS, especially for AEAD ciphers. Otherwise, we may need to re-send the remaining data, which is quite annoying.

**Comment by studentmain** [comment]
Added to v5 milestone, but a refactor to core logic is required.

**Comment by studentmain** [comment]
Seems go-shadowsocks2 will not support TFO, maybe we should do samething.

https://github.com/shadowsocks/go-shadowsocks2/pull/162

**Comment by database64128** [comment]
As mentioned in shadowsocks/go-shadowsocks2#162, TFO is dead.
