### ISSUE TITLE
Shadowsocks does not support Japanese locale. I could provide some help.

### ISSUE THREAD

**Issue by Kiana-Kaslana** [shadowsocks/shadowsocks-windows#1046]
Hello！I am using shadowsocks windows vision for viewing some blocked sites (such as 163 music. it blocks foreign user), but I find it haven't support the language: jp. If you don't mind, I think I can provide some help. My email is `kiana_kaslana[at]yahoo.co.jp`

--edited by @celeron533

**Comment by lixingcong** [comment]
It seems that it was not related to shadowsocks.

Please make an order for Aliyun or another VPS located in China and set up a server on it.

**Comment by gh4685h** [comment]
Sorry, i think i have not described well. What i mean, shadowsocks when the system is set in Chinese, it can show as Chinese, but in system that the language is Japanese it did't used Japanese, it used english ...
=-=, for easy way to explain...Can you add Japanese language to this software?

**Comment by Kiana-Kaslana** [comment]
Sorry, i think i have not described well. What i mean, shadowsocks when the system is set in Chinese, it can show as Chinese, but in system that the language is Japanese it did't used Japanese, it used english ...
=-=, for easy way to explain...Can you add Japanese language to this software?

**Comment by hellofwy** [comment]
Add a Japanese translation file under folder `shadowsocks-csharp/Data/` like the `cn.txt` or `zh_tw.txt`.

Then change the function in code file: https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/I18N.cs#L31

Then it will work, I think.

**Comment by lixingcong** [comment]
Please change your system locate setting on Control Panel.

Change to Chinese(Simp) from Japanese. It may download some system language pack from Microsoft.

**Comment by wongsyrone** [comment]
You can copy an existing translation as the template, for example, copy `shadowsocks-csharp/Data/cn.txt` to `shadowsocks-csharp/Data/jp.txt` and submit your translation as a Pull Request or just paste them here. Someone with write access to this repository will take care of it.

**Comment by Kiana-Kaslana** [comment]
lixingcong sann, I think you haven't understand what I really want chat(´Д` )
I think hellofwy sann and wongsyrone sann got that^ - ^
I am not talking about the windows system, I am talking the software itself.
I mean, shadowsocks can use the correct language such as when windows is Chinese, English ...
But not support japanese=-=

**Comment by celeron533** [comment]
@Kiana-Kaslana , you could also try use unblockYouku (https://chrome.google.com/webstore/detail/unblock-youku/pdnfnkhpgegpcingjbfihlkjeighnddk , https://addons.mozilla.org/en-US/firefox/addon/unblock-youku/) to access some Chinese regional specific sites without any extra proxy server.

**Comment by Kiana-Kaslana** [comment]
@wongsyrone I finished that， just post here is ok？

**Comment by JonasGao** [comment]
@Kiana-Kaslana I think fork this project, and pull request is better 😝 ( thank gad, my poor English )

**Comment by Kiana-Kaslana** [comment]
@JonasGao sorry, I didn't understand=-=ll

**Comment by Choutouketsu** [comment]
@Kiana-Kaslana fork=ブランチ To make it simple, it is a customized version from the original version
![_20170227093817](https://cloud.githubusercontent.com/assets/24585116/23345949/802902a8-fcd0-11e6-9983-2a21972f6126.png)

**Comment by Kiana-Kaslana** [comment]
@Choutouketsu 
https://github.com/Kiana-Kaslana/shadowsocks-windows/tree/master/shadowsocks-csharp/Data
ええと。。。これでいいのか？(´Д` )

**Comment by JonasGao** [comment]
@Kiana-Kaslana I`m already create a pull request to you. [there](https://github.com/Kiana-Kaslana/shadowsocks-windows/pull/1)
you can apply it, and create a pull request to original project

**Comment by JonasGao** [comment]
@Kiana-Kaslana And!!! I`m using mac, so i cant test it, please 
Please help me test it first.

**Comment by Kiana-Kaslana** [comment]
@JonasGao Ok, and what should i do?

**Comment by Choutouketsu** [comment]
@Kiana-Kaslana はい、それではいいと思います。プログラムをすることができません。Σ( ° △ °|||)︴

**Comment by Kiana-Kaslana** [comment]
@Choutouketsu 有り難う〜でも大丈夫、JonasGaoさんは私を助けたい(*ˉ︶ˉ*)

**Comment by Ruilx** [comment]
みんなさん、キアナさんはプログラマーではないて、
ユーザーでございます。でも、このソフトウェアはサインイン中国のインターネットを彼女助けることができると思います。したがって、キアナさんはソースコードからShadowSocksを介してインターネットの問題を発見したいと考えています、またはUIを翻訳のみ致す。
Hi everyone, Kiana is not a professional programmer, just a ShadowSocks's user. I think this software can help her sign in the Chinese internet to use some Chinese-only software. Therefore, Kiana wants to discover the Internet problems via ShadowSocks from the source code, or just translates the UI.
(I know you are using MacOS, why forked ShadowSocks-Windows?)
额...我就不用中文表达上面的意思, 说点别的, 最近好多VPN都用不了了, ShadowSocks好像也没有免费的, 最近翻墙很头疼的... 我只知道Shadows-socks是翻出去的, 竟然还有翻进来的功能? 请大神指教⊙ω⊙谢~

**Comment by celeron533** [comment]
@Ruilx , SS只是协议，想怎么用都可以，比如我的公司看不了weibo图片，所以我用这个东西曲线救国~~

如果 @Kiana-Kaslana 不是专业的编程人士，让其独自提交commit有一定的困难性。翻译文本的工作做完后，其实可以让他人代为提交（不过可以把提交人的名字改成他本人）

While @Kiana-Kaslana is not a profession developer, push the commit may become a bit difficult for him/her. Actually someone could give a hand to commit the translation related files then create a pull request on behalf of Kiana. :heavy_check_mark:

**Comment by celeron533** [comment]
Looks good on my machine.

![image](https://cloud.githubusercontent.com/assets/3608762/23506765/e086e6cc-ff84-11e6-86ff-c0286da18df1.png)

**Comment by Kiana-Kaslana** [comment]
お邪魔します、皆様。( @celeron533 ...)
しかし、私は確かにプログラマーではないてではない。
だから、貴方達の協力が必要。
貴重なご協力、有り難う御座います。
因みに、windowsとMacの翻訳は同じだと思いますが、全く問題はありませんので。 @Ruilx 

それでは、失礼します。

**Comment by JonasGao** [comment]
我提交了 [pull request](https://github.com/shadowsocks/shadowsocks-windows/pull/1059)..... 如果没啥问题这个就可以关了。

**Comment by Ruilx** [comment]
@Kiana-Kaslana Kiana cyann needs learn some github's pull request steps to adjust or amend open-source-project issues as a contributor rather than

**Comment by Ruilx** [comment]
…paste the code on comment board (sorry about that I click the Comment button when I was writing... ), if it is the new interest about you to writing code instead of using software and/or post an issue, I will teach and explain to you how to use git and github(｡･ω･｡)

**Comment by Ruilx** [comment]
如果正确&Merged的话@JonasGao拜托关闭一下Issue&确认一下Pull Request，感谢！
