### ISSUE TITLE
[BUG] Windows shortcut for Enable System Proxy

### ISSUE THREAD

**Issue by florianmonfort** [shadowsocks/shadowsocks-windows#1047]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Environment(Operating system, .NET Framework, etc)

Windows 10

### Steps you have tried

Tried creating a shorcut myself, couldn't figure out how so assuming it doesn't exist.

### What did you expect to see?

To have a page explaining all available shortcuts which does not exist right now, or to have the shortcut just available.

### Config and error log in detail (with all sensitive info masked)

[STORY]

*Rationale*

At the moment, when dealing with foreign sites + work local IPs, I find myself to have to Enable/Disable the Proxy a lot, to be able to switch from accessing our local development environment which uses an office IP THEN switching back when I need to access foreign sites.

Right now I have to use my mouse, go to the system tray and perform total 4 to 5 clicks to get that action done.

*Expected*

- When setting up Shadowsocks on Windows 10, there should be Action Center notification with the following text: "Welcome to Shadowsocks on Windows 10! Quickly Enable / Disable System Proxy by hitting XXX + XXX";
- When hitting the XXX + XXX keyboard shortcut, Shadowsocks should be instantly disabled / enabled.

**Comment by hellofwy** [comment]
There is a build-in shortcut solution.

Right-click the application icon on the notification part of the task bar. There is a menu item about shortcuts.

My version is 3.3.1.

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-windows/blob/master/README.md#global-hotkeys

**Comment by celeron533** [comment]
Hi @florianmonfort , as mentioned in your user story, you need to access to both local network/domestic network and foring/international network at the same time. If you only require this featue with web browsers, you can use Google Chrome (or any Chrome based browsers) and install extension SwitchyOmega to handle the auto proxy switch. https://github.com/FelisCatus/SwitchyOmega

**Comment by florianmonfort** [comment]
@hellofwy thanks for your reply!

![screenshot_37](https://cloud.githubusercontent.com/assets/1446429/23297020/b7fa37c6-fab2-11e6-97bc-270faab9744f.png)

From this particular menu I can't tell which one does what I want, meaning, none of them says "Enable / Disable System Proxy" like it says in the tray?

And at the same I have no idea what shortcut is "available" and not already used for something else in Windows, I wish somebody could have done the work already of what shortcut would be smart you know? So I still haven't activated it.

@celeron533 I also use other browsers like Edge, and sometimes do testing in 360. Browser extensions are not an ideal solution either.

**Comment by hellofwy** [comment]
Should be the first one.

**Comment by florianmonfort** [comment]
Do you have any suggestion of an available shortcut that Windows or regular apps don't use? I can investigate it but if you have something in mind I'll take it lol.

Afterwards I'll close the ticket, I'd suggest though just revising the copy to "Enable/Disable Proxy". I think it's what got me confused and not understand that that's what it was.

**Comment by hellofwy** [comment]
Just use whatever you want.

> Meaning of label color
> 
> Green: This key combination is not occupied by other programs and register successfully.
> Yellow: This key combination is occupied by other programs and you have to change to another one.
> Transparent without color: The initial status.

**Comment by florianmonfort** [comment]
Alright, can close the ticket!

**Comment by florianmonfort** [comment]
Actually no don't close the ticket, I just discovered that after re-starting my computer, re-launching Shadowsocks, the hotkey is still in the Shadowsocks configuration but the shortcut itself doesn't work anymore.

For more information I am on latest Windows 10 production build, Shadowsocks 3.4.2.1

**Comment by hellofwy** [comment]
https://github.com/shadowsocks/shadowsocks-windows/blob/master/README.md#global-hotkeys

> Hotkeys are NOT registered automatically. You should re-register all hotkeys after restarting 
> Shadowsocks. If you are using multiple instances of Shadowsocks, you must set different key 
> combination for other instances.

You should really read the README first.

Though I don't know know why it doesn't auto re-register after restarting.

**Comment by florianmonfort** [comment]
Oh got it. I'll close this now

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/pull/708#issuecomment-247746140
