### ISSUE TITLE
最新版SS在WIndows10系统中PAC模式不可用/Not able to use PAC mode in the latest SS with the Windows 10

### ISSUE THREAD

**Issue by Master-Franklu** [shadowsocks/shadowsocks-windows#1048]
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
Windows 10

### Steps you have tried 
使用管理员模式打开SS 重启电脑都不好用
restart computer and running ss using admin privilege not help 

### What did you expect to see?
正常使用PAC模式配合Chrome的switchOmega应该可以在正常网站/被屏蔽网站中自由切换
It should switch inside/outside GFW automatically collaborate with SwitchOmega in Chrome
### What did you see instead?
但是现在只在全局模式下可以访问被屏蔽网站
But Now, once I turn to PAC mode , then I could only visit website not blocked by GFW like Baidu. Google and Youtube is not working

### Config and error log in detail (with all sensitive info masked)

**Comment by Master-Franklu** [comment]
我有两台电脑，使用的是同样的Switch Omega配置（在线同步功能），一台可以正常使用SS的PAC模式，但是另一台PAC模式下只能打开没被屏蔽的网站，google和youtube不能上

--------------
I've got 2 computer, with the exactly same switch omaga configuration(online sync), but only have 1 PC cannot use PAC mode.

**Comment by zzl1428377909** [comment]
我用pac模式有些网站不能上，但是用全局模式就能访问

**Comment by JonasGao** [comment]
use [this pac.txt](https://github.com/shadowsocks/shadowsocks-windows/files/853116/pac.txt) replace your pac.txt file under shadowsocks root path. And, try again

**Comment by Master-Franklu** [comment]
已经检查到问题 是由于SwitchOmega中未设置自动切换导致 非SS问题。关闭问题  感谢所有回复者
Issue has been address myself, due to 'forget set as Auto-Switch in SwitchOmega' , already confirmed that's not a SS issue. Thanks for all the contributor . Ticket closed.

**Comment by HaskellZhangSong** [comment]
@JonasGao 能不能解释一下这段神秘代码？Windows 10最新SS终于可以PAC代理了。
