### ISSUE TITLE
新版本Privoxy的监听端口

### ISSUE THREAD

**Issue by Imovase** [shadowsocks/shadowsocks-windows#1049]
请问新版本Privoxy的监听端口能否固定呢，每次启动都不一样，使用config.txt配置仍然如此

**Comment by chenshaoju** [comment]
Widnows的EFS服务（lsass.exe）可能会随机监听一个端口，会引起Privoxy无法绑定1080，所以使用了端口随机化。

具体案例请见：https://twitter.com/CaoMu/status/830353061071642624

如果坚持要固定端口可以自行设置一个Privoxy： https://www.privoxy.org/sf-download-mirror/ ，这是我目前的解决办法。

**Comment by wongsyrone** [comment]
这个最初做的动力是有人开机自启两个ss，然后因为都从1080开始向上找可用端口，两个就冲突了。

最后的办法是让tcp stack分配一个，迅速抢占，有兴趣可以改代码。

**Comment by Cye3s** [comment]
是指http代理的端口么？原来在8123上监听，现在随机了很不方面啊

**Comment by selay01** [comment]
对于 shadowsocks3.4.3-win，对于http的填与socks5一样的 ip:端口（比如都是127.0.0.1:1088），试试；我的就可以
感觉新版本的文件夹“ss_win_temp”只是 http代理功能实现 的缓存文件

**Comment by wongsyrone** [comment]
ss_win_temp这里面是程序正常运行需要的所有文件以及产生的文件。
