### ISSUE TITLE
System.MissingMethodException: 找不到方法:“System.Net.Sockets.SocketError System.Net.Sockets.SocketException.get_SocketErrorCode()

### ISSUE THREAD

**Issue by Bpazy** [shadowsocks/shadowsocks-windows#1051]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
Windows10;
.NET4.6

### Steps you have tried
硬盘安装到其他电脑，再装回原电脑之后报错

### What did you expect to see?
正常运行

### What did you see instead?
![image](https://cloud.githubusercontent.com/assets/9838749/23336893/4e64a834-fc18-11e6-90b2-8ca6adb852fa.png)

### Config and error log in detail (with all sensitive info masked)
无配置文件也会报错。
[2017-02-26 11:52:23] [E] System.MissingMethodException: 找不到方法:“System.Net.Sockets.SocketError System.Net.Sockets.SocketException.get_SocketErrorCode()”。
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main()

**Comment by deepsea887** [comment]
sfoiew.com
`ergrgreg`
## tf45gg4g
**rtgtrgrthr**h

> ythytjj6j67j
[rfg.com](url)

**Comment by celeron533** [comment]
最新版SSwin需要
.NET4.6**.2**

另外有时候windows10在后台悄悄安装更新后，需要重启，否则会出现各种奇奇怪怪的问题。

**Comment by chenshaoju** [comment]
请打开注册表编辑器，然后定位到：
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
```
然后右侧会有一个名为 Release 的键值，请问这个键值是？

**Comment by Bpazy** [comment]
0x00060632(394802) @chenshaoju

**Comment by chenshaoju** [comment]
看起来是最新的，请下载 https://www.microsoft.com/en-us/download/details.aspx?id=53344 然后重新安装，安装的过程中选修复即可。

如果仍然不行，下载 https://www.microsoft.com/en-us/download/details.aspx?id=30135 修复工具，然后按照提示重新安装 .NET Framework 6.4.2 即可（可能不会要求重装）。

**Comment by Bpazy** [comment]
两种方法测试之后还是不可以，
我尝试修复系统试试。

**Comment by celeron533** [comment]
端口冲突记得不会是这种报错。
有没有可能是你手上的SS二进制文件出了问题？
重现下载一个SS试试？
被360等防护软件阻止？


如果手上有visualstudio2015，拿一份源代码然后直接调试？

**Comment by Bpazy** [comment]
打开工程直接提示相同的错误，修复.Net不起作用，所以推测是系统某个设置有问题。

修复系统之后问题消失
