### ISSUE TITLE
如何打开更详细的log呢？在windows上，时灵时不灵，怀疑是网管有什么控制。

### ISSUE THREAD

**Issue by footballqq** [shadowsocks/shadowsocks-windows#1052]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

3.4.3
### Environment(Operating system, .NET Framework, etc)
win10

### Steps you have tried
log只显示很少的内容
但更新pac的时候如果不工作会出错。

在其他设备比如安卓就没问题，但其他设备不在这个局域网下。说明远程服务器没问题。
同时Ping远程服务器或者ssh到服务器上也没问题。

### What did you expect to see?

正常翻墙
### What did you see instead?
比如访问google，并不出错，直接停在空白页面

### Config and error log in detail (with all sensitive info masked)
[2017-02-27 16:55:43] Socket connected to ss server: 23.106.xxx:xxx
[2017-02-27 16:56:50] connect to clients4.google.com:443

**Comment by celeron533** [comment]
![image](https://cloud.githubusercontent.com/assets/3608762/23355215/b391f0ca-fd0f-11e6-840d-6669a0f56e24.png)

**Comment by footballqq** [comment]
选了，但log里也只有socket connected和connect to这两种信息
、shadowsocks\ss_win_temp\shadowsocks.log
这个和python那个ssserver不一样吧？等我用那个测试一下

**Comment by footballqq** [comment]
btw, v2ray在公司电脑完全没反应，在家和手机上一切正常。

**Comment by footballqq** [comment]
不工作的时候出这个错。。10分钟前还正常突然又挂了。python的ssserver也不能用应该是出了一些弱智问题。
![sslog](https://cloud.githubusercontent.com/assets/2426208/23388311/59268e10-fd9c-11e6-8804-e6d2fe0f1f8f.png)


[2017-02-28 09:52:54] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by footballqq** [comment]
补充，假设用qq浏览器，会不断提示页面失去响应（chrome里也一样失去响应）

[2017-02-28 10:19:27] connect to www.google.com:443
[2017-02-28 10:19:27] Socket connected to ss server: xxx.xxx.xxx.xxx:1234
[2017-02-28 10:19:28] connect to pagead2.googlesyndication.com:80
[2017-02-28 10:19:28] connect to pagead2.googlesyndication.com:80
[2017-02-28 10:19:28] Socket connected to ss server: xxx.xxx.xxx.xxx:1234
[2017-02-28 10:19:29] Socket connected to ss server: xxx.xxx.xxx.xxx:1234
[2017-02-28 10:19:29] connect to pagead2.googlesyndication.com:80
[2017-02-28 10:19:30] Socket connected to ss server: xxx.xxx.xxx.xxx:1234
[2017-02-28 10:19:30] connect to pagead2.googlesyndication.com:80
[2017-02-28 10:19:30] Socket connected to ss server: xxx.xxx.xxx.xxx:1234
[2017-02-28 10:20:08] connect to accounts.google.com:443
[2017-02-28 10:20:09] Socket connected to ss server: xxx.xxx.xxx.xxx:1234

**Comment by footballqq** [comment]
我回退到 Shadowsocks-3.3.3.zip，暂时可以使用。我观察几天看看还有没有问题……

**Comment by footballqq** [comment]
补充一下，3.4.3出错版本的Shadowsocks下，http://ip111.cn/ 在这个网站查询能否翻墙的时候显示的是“能翻墙”，也就是google的访问ip是vps的ip

**Comment by celeron533** [comment]
首先要排除是不是服务器或者链路的问题。
出现异常的时候，其他设备，比如手机通过移动联通网络还能访问吗？
服务器是否能ping通？
重启服务器后是否有效？

启明星辰可能研发SS的反制措施，误伤率较高，所以一般也就在企事业单位作为上网行为管理。

**Comment by footballqq** [comment]
@celeron533 多谢答复

出现异常时手机通过移动或电信网络均可访问（双卡）
服务器可以ping通，通过ssh访问也没有问题，延迟在200-300ms左右，丢包率很低
重启服务器/客户端均无效（重启电脑都无效。。）
3.4.3间歇性无法访问（还无法重现无法访问的触发条件，但无法访问的时候一个明确现象是更新pac出错，错误前面贴过），3.3.3已经使用了2天还没碰到问题（更新pac没问题）。
我在家里网络用3.4.3也从来没出过问题。所以感觉是在公司有什么特殊情况出现。

公司有sangfor上网行为管理

**Comment by footballqq** [comment]
最诡异的现象是访问google出的是空白页面并且失去响应，同时在log上能看到有少量的进出流量。并不是出现被墙以后的症状。

**Comment by footballqq** [comment]
汇报一下，昨天一整天没出问题尽早仍然一切正常，估计是3.4.3和3.3.3之间的一些差异导致的在特定环境出错。。

**Comment by footballqq** [comment]
2017-3-2 这一天仍然没出问题。。

**Comment by footballqq** [comment]
说起来你可能不信，3.3.3仍然很偶尔会出一些问题（3.4.3 很频繁）。但是我已经发现了终极解决方案。当出现 ss 不正常的时候，我只要ssh登录一下主机，ss就正常了。。

**Comment by celeron533** [comment]
@footballqq 那看来还是网络干扰。

**Comment by jerryshao4u** [comment]
上网行为管理判断你的行为异常,给你断开了吧..

**Comment by footballqq** [comment]
@celeron533 @jerryshao4u nod, 我搜了一下sangfor ingress.exe，没一句好话，先凑活用吧。虽然原理还没搞清楚。。

**Comment by rigious** [comment]
@footballqq 
大哥 我这电脑也是装了sangfor ingress.exe 就时不时白屏，求指导解决方案

**Comment by footballqq** [comment]
@rigious 我前面写了解决方案“但是我已经发现了终极解决方案。当出现 ss 不正常的时候，我只要ssh登录一下主机，ss就正常了。。”
另外现在的版本SS已经很少断开连接了，不知道是ss优化了哪些东西导致不被误杀了还是sangfor从良了不干坏事了。
另外你可以试试v2ray. 我现在v2ray也没问题了但之前v2ray是不行的。

**Comment by chenshaoju** [comment]
查了一下，这个 sangfor ingress.exe 是深信服的内网监控软件，应该是你们企业部署的对吧，这种通常没有办法，这是你们企业的硬性限制。 https://www.zhihu.com/question/20341713

**Comment by tlitiwwhtmi** [comment]
@footballqq  ssh 登录一下ss server就能行了是什么道理。我也ssh一下server就好了。但想不通为什么要这么做

**Comment by footballqq** [comment]
@tlitiwwhtmi 我也想不通。你也被深信服坑了吗？如果是因为上网监控，有可能是他维护了一个白名单，看到是ssh协议就放行这个IP。不是的话长连接就被干掉。

**Comment by tlitiwwhtmi** [comment]
@footballqq  搞不懂，太诡异了。我的mac，在同样的网络环境下就不会有问题，手机也是可以的。就是windows会断掉
