### ISSUE TITLE
编译shadowsocks-csharp3.4.3版本报错

### ISSUE THREAD

**Issue by waideveloper** [shadowsocks/shadowsocks-windows#1055]
错误信息如图：
![qq 20170228221929](https://cloud.githubusercontent.com/assets/11283511/23408696/05475596-fe04-11e6-88ce-2794fc7cd375.png)

**Comment by celeron533** [comment]
看看NuGet是否正确？
![image](https://cloud.githubusercontent.com/assets/3608762/23409858/1d7bf96a-fe08-11e6-97da-752d4bfa6e17.png)

**Comment by waideveloper** [comment]
这个也是对的，如图
![qq 20170301071239](https://cloud.githubusercontent.com/assets/11283511/23438808/894b535c-fe4e-11e6-8306-0ce877f20853.png)

**Comment by wongsyrone** [comment]
我很好奇你那里面为啥有Mono

**Comment by waideveloper** [comment]
我一生成项目，就会在这些目录中下载这些库，并提示上面的错误，源码是从release标签下下载的
![qq 20170301083439](https://cloud.githubusercontent.com/assets/11283511/23440914/1282e832-fe5a-11e6-9d9b-fbd77727854d.png)

**Comment by waideveloper** [comment]
有人帮助，下载下这个版本的源码编译一下，是不是，只是我的编译平台有问题，还是项目中未配置的地方

**Comment by celeron533** [comment]
另外你看看你是不是.net framework 4.6.2?
我debug和release都试了下，能编译。

请尝试删除3rd文件夹下除了zxing以外的所有文件夹后再试。

**Comment by waideveloper** [comment]
我这边可以确定是在.net framework 4.6.2，3rd目录下的内容是Nuget自动下载的，如果手动删除，只要生成项目，就会还原出来，如果把packages.config文件删除，就会提示此项目缺少nuget相关包，我现在，依然没有直接通过编译，现在解决的办法，是我新建立了解决方案，把代码，拷贝过去，引用两个外部类库，可以编译运行

**Comment by JonasGao** [comment]
我这边看了下，3rd 下确实有 Mono.Cecil 库。但是我这边编译并没有问题

**Comment by waideveloper** [comment]
终于解决编译问题了，需要修改一下shadowsocks-csharp.csproj，删除如下节点，如图
![qq 20170302203607](https://cloud.githubusercontent.com/assets/11283511/23507407/ed115b68-ff87-11e6-98b6-fb8f27548be7.png)

**Comment by celeron533** [comment]
我这边也有，但不影响编译，奇怪

```
  <Target Name="CleanReferenceCopyLocalPaths" AfterTargets="AfterBuild;NonWinFodyTarget">
    <CosturaCleanup Config="FodyWeavers.xml" Files="@(ReferenceCopyLocalPaths->'$(OutDir)%(DestinationSubDirectory)%(Filename)%(Extension)')" />
  </Target>
  <Import Project="3rd\Fody.1.29.4\build\dotnet\Fody.targets" Condition="Exists('3rd\Fody.1.29.4\build\dotnet\Fody.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>这台计算机上缺少此项目引用的 NuGet 程序包。使用“NuGet 程序包还原”可下载这些程序包。有关更多信息，请参见 http://go.microsoft.com/fwlink/?LinkID=322105。缺少的文件是 {0}。</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('3rd\Fody.1.29.4\build\dotnet\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '3rd\Fody.1.29.4\build\dotnet\Fody.targets'))" />
  </Target>
```
