### ISSUE TITLE
Please support chacha20-ietf-poly1305.

### ISSUE THREAD

**Issue by Garfield550** [shadowsocks/shadowsocks-windows#1056]
Shadowsocks Windows version: 3.4.3

Windows OS version: Windows 10 15042.0

Shadowsocks libev add chacha20-ietf-poly1305 support on 28 days ago.

See https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.0.0

**Comment by asmadeus08** [comment]
SS-libev add also aes 128/256 GSM which is better by performance test.

**Comment by wongsyrone** [comment]
chacha20-ietf-poly1305 的确速度很快

**Comment by Garfield550** [comment]
@wongsyrone 如果可以，麻烦支持一下，谢谢。

**Comment by wongsyrone** [comment]
Done.

**Comment by asmadeus08** [comment]
@wongsyrone checked https://github.com/shadowsocks/shadowsocks-windows/releases and there is absent any new version.
