### ISSUE TITLE
电脑端和手机端速度对比，PC版速度偏慢

### ISSUE THREAD

**Issue by Loukky** [shadowsocks/shadowsocks-windows#1057]
同样的节点观看同样的YouTube视频，PC端的缓冲速度不超过1W，手机端可轻松3W+.

**Comment by wongsyrone** [comment]
首先你得确定网络一样，比如电脑用电信，手机用移动，有差别是正常的。
两者测试条件都一样的话，可以找找数据收发方面的问题。

**Comment by Loukky** [comment]
同网络，不过我用win10速度能正常。看来是系统的问题。

**Comment by MoeNay** [comment]
挖个坟 我一直也有这个问题来着
