### ISSUE TITLE
Implement AES-*-GCM

### ISSUE THREAD

**Issue by henrypijames** [shadowsocks/shadowsocks-windows#1058]
Is there any particular reason that this C# port has only implemented Chacha20-*, but not AES-*-GCM? Especially since AES-128-GCM is the fastest among the AEAD schemes,

**Comment by hellofwy** [comment]
Just because people who want those ciphers, don't have submitted new Pull requests yet.

**Comment by axeker11** [comment]
issue

**Comment by Garfield550** [comment]
A C# crypto library support ChaCha20-Poly1305 and AES-GCM https://github.com/ektrah/nsec

**Comment by SquirrelCoder** [comment]
Hey man, could you please support the "AEAD Ciphers"?
Most of the other ones are not great or as fast as the AEAD ones.

Thanks a lot.

**Comment by ccboxes** [comment]
hope to add it

**Comment by wongsyrone** [comment]
Done.

**Comment by netroby** [comment]
if you want using AEAD, you can download build release from : https://ci.appveyor.com/project/netroby/shadowsocks-windows/build/job/e4m3b88wyk7dhaaj/artifacts

And you may need set the cipher to chacha20-ietf-poly1305
