### ISSUE TITLE
未预料错误

### ISSUE THREAD

**Issue by imis12** [shadowsocks/shadowsocks-windows#1062]
### Version(release version or AppVeyor link)
version 3.4.3

### Environment(Operating system, .NET Framework, etc)
Windows 10 lastest

### Steps you have tried
Just told me to report this error
`[E] System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Shadowsocks.Model.StatisticsRecord..ctor(String identifier, ICollection`1 inboundSpeedRecords, ICollection`1 outboundSpeedRecords, ICollection`1 latencyRecords)
   在 Shadowsocks.Controller.AvailabilityStatistics.UpdateRecords()
   在 Shadowsocks.Controller.AvailabilityStatistics.Run(Object _)
   在 System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.TimerQueueTimer.CallCallback()
   在 System.Threading.TimerQueueTimer.Fire()
   在 System.Threading.TimerQueue.FireNextTimers()
   在 System.Threading.TimerQueue.AppDomainTimerCallback()`

**Comment by celeron533** [comment]
Duplicated to #906
