### ISSUE TITLE
退出Shadowsocks之后，IE的连接设置，依然留下127.0.0.1的PAC配置痕迹，建议自动备份恢复SS覆盖前PAC配置

### ISSUE THREAD

**Issue by Azlun** [shadowsocks/shadowsocks-windows#1063]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

3.4.3
### Environment(Operating system, .NET Framework, etc)
Win8.1, maybe .NET 4.2

### Steps you have tried
1.Start Shadowsocks.exe and using it very well in my office LAN;
2. Exit Shadowsocks.exe check IE Internet configuration about PAC configuration
3. I am expecting my old PAC from company is restored, 
     ticked:Auto detect PAC configuration;
     ticked:use configuration script: http://10.128.62.123:82/proxy.pac
    but the fact is I can see 
     ticked:Auto detect PAC configuration;
     unticked:use configuration script: http://127.0.0.1:1080/pac?t=20170306101753700&secret=+/Y3+2yXKzf5CfC5IerulJDklJ1MQinZ26BA8hqaZGA=

### What did you expect to see?
I am expecting my old PAC from company is restored, 
     ticked:Auto detect PAC configuration;
     ticked:use configuration script: http://10.128.62.123:82/proxy.pac
Internet should be OK for China sites.

### What did you see instead?
     ticked:Auto detect PAC configuration;
     unticked:use configuration script: http://127.0.0.1:1080/pac?t=20170306101753700&secret=+/Y3+2yXKzf5CfC5IerulJDklJ1MQinZ26BA8hqaZGA=
Internet are all fail"无法显示此页"
### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
If it doesn't affect anything, you can ignore it safely.

BTW, don't try to poke pac URL yourself, it is managed by SS itself.

**Comment by Azlun** [comment]
I am blocked to use the network after exit ss,that is why I raise such a case. I guess most use with old PAC setting before as start will have such critical issue,since SS should manage to restored old setting but I my case not...

**Comment by waitray** [comment]
i really have the same problem. if ss could restored my old pac setting,that is much better.

**Comment by wongsyrone** [comment]
Done.
