### ISSUE TITLE
windows7 32bit  3.4.3 启动报错 “Shadowsocks 已停止工作” 参考过站内类似解决方法 修复失败

### ISSUE THREAD

**Issue by dante1029** [shadowsocks/shadowsocks-windows#1065]
查了查问题解决方法和站内类似的问题 #461 。
按照这个思路尝试Windows update升级显示错误80072ee2，通过第三方工具补丁了KB2742595 KB2789642 KB2737019 KB2487367 KB2729449 KB2604121 KB2656351 KB2736428。
重启系统后仍然报错。

问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	3.4.3.0
  问题签名 03:	5875cf14
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	50484bd7
  问题签名 07:	1204
  问题签名 08:	89
  问题签名 09:	System.TypeLoadException
  OS 版本:	6.1.7600.2.0.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by wongsyrone** [comment]
Microsoft .NET Framework 4.6.2
如果不让安装，使用Win 7 SP1及以上

**Comment by dante1029** [comment]
@wongsyrone 
感谢回复。
4.6.2安装失败：产生阻滞的问题: 此操作系统不支持 .NET Framework 4.6.2。
“如果不让安装，使用Win 7 SP1及以上”，是指？

**Comment by wongsyrone** [comment]
安装带service pack 1的版本，或者使用更新的操作系统

**Comment by dante1029** [comment]
@wongsyrone
安装的版本是 https://www.microsoft.com/zh-CN/download/details.aspx?id=53344 版本描述适用Windows 7 SP1  
更新操作系统可能有点困难，其他版本的 Framework可以解决这个问题么。。。

**Comment by dante1029** [comment]
还是参照 #461中的经验，安装KB2468871重启后仍然报错。 突然记起来一个事儿，在家里的电脑打开ss后提示缺少Framework 4.* 自动弹出下载，在公司的这台没有这儿步骤。
