### ISSUE TITLE
Windows 10无法自动开机启动

### ISSUE THREAD

**Issue by Epilepsy-YDF** [shadowsocks/shadowsocks-windows#1066]
Windows 10 64，勾选或者不勾选“开机启动”这一选项都不会自动开机启动，希望能解决。

**Comment by celeron533** [comment]
先禁用杀毒软件，然后再试。

**Comment by steveshi** [comment]
是不是默认使用管理员权限启动的

**Comment by JonasGao** [comment]
说不定你安装了 360

**Comment by Epilepsy-YDF** [comment]
好像是以管理员权限启动的锅。。

**Comment by xuezheng001** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1066#issuecomment-285014420
感谢楼上的回答，经过验证发现，确实是程序具有管理员权限的问题，不过win10也是坑，win7下好好的，它整这么一出。。。。。
