### ISSUE TITLE
Ios9 移动数据没有APN选项，想用APN正确上网

### ISSUE THREAD

**Issue by XoloveStepth** [shadowsocks/shadowsocks-windows#1067]
WIFI下用了PAC模式总算拜托软件翻墙了，现在想把蜂窝数据都用PAC，但是没有APN接入点这选项，我的安卓机器就有，求教指路

**Comment by JonasGao** [comment]
看了下，还以为你要安卓客户端，原来是 iOS。果断推荐 shadowrocket。对于它是收费软件。我只能说你用了就知道值这个钱。如果你不想用也可以。可以用功能弱很多的 wingy

**Comment by XoloveStepth** [comment]
我指的是不用任何其它软件上网，现在我用wifi 上网不用翻墙，你说的我都有，就是不想在手机用

**Comment by JonasGao** [comment]
安卓上 APN，怎么搞？WIFI 你是在路由上设置了是吧

**Comment by XoloveStepth** [comment]
我看的是苹果，看人家用中国联通不用任何程式翻墙，用的pac转http但自己不知道怎么搞，wifi已经自带翻墙剩下移动通信了

**Comment by celeron533** [comment]
估计是其他人搞的类似于免流一类的东西，也就是说在联通移动的内网再搞一个非官方的APN服务器，然后出去透气。

**Comment by XoloveStepth** [comment]
@

**Comment by XoloveStepth** [comment]
@celeron533 我要的就是这个效果啊，现在我的WIFI自带效果，就希望数据网路了，之前弄过修改APN的描述文件，里面那个代理服务器不知道怎么填，那个代理服务器应该怎么和我的PAC文件和我的带SS的电脑联系起来？求解
