### ISSUE TITLE
DDoS attacks from server while shadowsocks is running

### ISSUE THREAD

**Issue by EugeneRider1** [shadowsocks/shadowsocks-windows#1068]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.3    

### Environment(Operating system, .NET Framework, etc)
Win 7      .NET Framework 4.6

### Steps you have tried
Destroy instance and start up a new one

### What did you expect to see?
Running smooth

### What did you see instead?
DDoS attacks coming from the instance after 2 or 3 days, and it's been like this for awhile. 

### Config and error log in detail (with all sensitive info masked)

My VPS host company has informed me that the instance's been using shadowsocks is constantly outbounding traffic that looks like DDoS. And I have no idea what is going on since the server only runs shadowsocks and nothing else, and it keeps appearing as I repeat the steps above. And the situation didn't happen before. 

I notice some suspicious things, one is from my local network there's DNS polluting. And possible outdated software? 

Thoughts on this?

**Comment by hellofwy** [comment]
From what I know:
1. Check if your Windows is compromised.
2. Check if your Server is compromised.
3. Check if your Shadowsocks server-side software have not been restricting the local addresses. Though this should been default if using the latest versions.
