### ISSUE TITLE
淘宝这两个域名有什么特别之处么? 

### ISSUE THREAD

**Issue by ghosoft** [shadowsocks/shadowsocks-windows#1069]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
win10

### Steps you have tried
![image](https://cloud.githubusercontent.com/assets/4844538/23734259/df44a82e-04b8-11e7-896f-6be49fc05806.png)
淘宝这两个域名用代理走了可是还是会弹出这个

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
不知道为啥要翻墙上淘宝

**Comment by hellofwy** [comment]
和代理没啥关系，可能是 DNS 解析问题。
这个既不是 shadowsocks-windows 问题，也不是 SwitchOmega 问题。
