### ISSUE TITLE
Which version support NET Framework 4.0

### ISSUE THREAD

**Issue by chnt7305** [shadowsocks/shadowsocks-windows#1070]
my os is win xp and i install NET Framework 4.0 
but the latest version not support Framework 4.0
thanks a lot.

**Comment by hellofwy** [comment]
May be before version 3.3.2

**Comment by celeron533** [comment]
> May be before version 3.3.2

U R right.

![image](https://cloud.githubusercontent.com/assets/3608762/23797184/8715b78e-05d9-11e7-9fe0-303c1926c65f.png)
![image](https://cloud.githubusercontent.com/assets/3608762/23797207/9fa94c3e-05d9-11e7-9972-25c6a505c89d.png)

**Comment by vkings1** [comment]
👍

**Comment by chnt7305** [comment]
@hellofwy Ok.Thank you!
