### ISSUE TITLE
中文版官网怎么没有了，不能订购了吗，我的快到期了，还是以后都免费了，，嘎嘎。。。

### ISSUE THREAD

**Issue by softwareCxw** [shadowsocks/shadowsocks-windows#1072]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
Shadowsocks软件一直就是开源和免费的。你遇到的只是使用这个软件提供服务的商家，与这里无关。请联系你的卖家。

**Comment by softwareCxw** [comment]
谢谢

**Comment by Jan9th** [comment]
刚弄明白，不知道有没有合作关系

**Comment by celeron533** [comment]
没有
> 刚弄明白，不知道有没有合作关系

**Comment by vivagonna** [comment]
@Jan9th 最近自己搭建了一个ss，CN2线路，youtube随时1080p秒开，只是费用有点高想找人合租，如果有需要可以联系。

**Comment by kzwr** [comment]
可以联系我，哈哈
