### ISSUE TITLE
windows10 shadowsocks点击需要访问网络的菜单都会出现卡死状态，比如从GFWList更新本地pac，或者检查更新版本，只有重启windows资源管理器才会回复正常

### ISSUE THREAD

**Issue by Milittle** [shadowsocks/shadowsocks-windows#1073]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by footballqq** [comment]
。。。你这提的太不专业了，不过你怎么重启资源管理器？我感觉你是本地权限问题。

**Comment by mizeshuang** [comment]
谢谢，问题已经解决~，在任务管理器里面重启资源管理器
