### ISSUE TITLE
Could not load template file no-server-data or one of its included components.

### ISSUE THREAD

**Issue by hexufeng** [shadowsocks/shadowsocks-windows#1074]
我自己的vps上安装的shadowsocks server，我有两台电脑，Mac上使用最新版本的shadowsocks客户端代理是可以访问Google的，但是windows电脑上安装最新的3.4.3版本的使用同样的配置代理连接上后访问Google就显示：
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

什么问题？

-------------------------English Description follow---------------------------------
i have two PC with Mac OS and Windows. Mac can connect to my vps server and can visit Google, but Windows can not. both have the same config. 
what's the problem ?

thx!

**Comment by celeron533** [comment]
请关闭整个SS-win后，将SS-win移动到其他文件夹（比如我的文档，或者没有空格和中文名的路径）后再试试？

**Comment by celeron533** [comment]
可能是 https://github.com/shadowsocks/shadowsocks/issues/455#issuecomment-158284953 ？

**Comment by celeron533** [comment]
另外还有可能是provixy之前的配置文件被破坏，关闭ss-win后清除temp文件（`%temp%`或SS-win自己的目录）试试

 https://github.com/shadowsocks/shadowsocks-windows/issues/491#issuecomment-193592922

**Comment by LinHuo1** [comment]
换成2.5.x版本试试，我昨天也是用3.4.3出现这错误，换成2.5.6就可以了

**Comment by hexufeng** [comment]
好的，谢谢楼上，周一了我试试看换成2.5.x

**Comment by celeron533** [comment]
如果你的ss文件夹有网络自动备份，比如one drive或百度盘，由于最新版3.4.3的temp文件夹就位于ss主文件夹，也有可能导致这个问题

**Comment by hexufeng** [comment]
还是不行，清除temp or %temp%，还是换成2.5.x版本均不行，windows7系统。

**Comment by hexufeng** [comment]
但是我的Mac上是没问题的，所以应该不是Gov干的。。

**Comment by wongsyrone** [comment]
这个错误是因为Privoxy没有从SS这端接收到数据

**Comment by wongsyrone** [comment]
try https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-yqdou/build/1.0.9/job/e23s241n2uqoxlny/artifacts

**Comment by BlogForMe** [comment]
删除　ss_win_temp里面的文件proixy

**Comment by yztldxdzhu** [comment]
在windows上也出现了这个问题，mac上没有。
我把ss关掉，删除ss_win_temp整个目录，再打开ss，就可以访问谷歌了

**Comment by liyigerry** [comment]
@wongsyrone 

请问你给的方案可以解决吗？你给的方案找不到了。链接失效了。
