### ISSUE TITLE
是否可以增加一个定时删除日志功能？

### ISSUE THREAD

**Issue by xfspace** [shadowsocks/shadowsocks-windows#1077]
Version(release version or AppVeyor link)
**3.4.3.0**

Environment(Operating system, .NET Framework, etc)
**Microsoft Windows [版本 10.0.15060]**

能否增加一个定期清理日志功能？
开了一段时间，日志文件30+MB了。手动清空是不明智的选择吧。。。。
谢谢！

**Comment by JonasGao** [comment]
You can set a windows timer program, automatically delete the file. For example, Run "taskschd.msc"

**Comment by celeron533** [comment]
Amend:
Windows Task Schedule，Windows计划任务 
![image](https://cloud.githubusercontent.com/assets/3608762/24080369/d10f5484-0cd8-11e7-8e7b-f6670af5a460.png)

> You can set a windows timer program, automatically delete the file. For example, Run "taskschd.msc"
