### ISSUE TITLE
关闭shadowsocks时系统代理设置为 自动检测设置 ，导致Chrome打开网页慢

### ISSUE THREAD

**Issue by pengkaiwei** [shadowsocks/shadowsocks-windows#1078]
关闭shadowsocks时系统代理设置为 自动检测设置 ，导致Chrome打开网页慢

shadowsocks取消代理的时候，把系统的局域网设置 里面的代理变为了 自动检测设置 
 
![default](https://cloud.githubusercontent.com/assets/10482885/24055112/ce19fdb6-0b79-11e7-97f0-5e3d16343a6c.PNG)

然后用Chrome打开网页的时候就会 自动下载代理脚本 ，导致打开网页要等待很多秒
![image](https://cloud.githubusercontent.com/assets/10482885/24055151/f47b901e-0b79-11e7-896d-f187b26ea576.png)

希望将shadowsocks取消代理时 将电脑的代理设置 设为无（即不勾选 自动检测设置）

**Comment by Azlun** [comment]
我更推荐是恢复用户原本设置，而不是简单覆盖。如我issue。 https://github.com/shadowsocks/shadowsocks-windows/issues/1063

**Comment by wongsyrone** [comment]
It will restore user's settings now.

**Comment by pengkaiwei** [comment]
That's Good ! Thanks~
