### ISSUE TITLE
能否增加白名单功能

### ISSUE THREAD

**Issue by zidanessf** [shadowsocks/shadowsocks-windows#1079]
现有PAC基于黑名单，只代理PAC列表内的域名。然而，有些域名不在PAC列表中，但是直连很慢。所以，能否增加绕开中国大陆地址的白名单功能，据我所知，安卓端的影梭已经有这个功能了。辛苦作者！

**Comment by lixingcong** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1043#issuecomment-281548384
