### ISSUE TITLE
版本3.4.3 系统win10 ss客户端服务器统计配置 24h 图表横坐标显示问题

### ISSUE THREAD

**Issue by bickman** [shadowsocks/shadowsocks-windows#1085]
版本3.4.3 系统win10 ss客户端服务器统计配置 24h 图表横坐标显示有问题，全部挤在最右边。

还有相关的统计参数得分不知道如何设置，不知道有没有详细的说明，让我能够设置，使用到最快的服务器。

**Comment by celeron533** [comment]
额，折线图的横坐标没有数值，只有纵坐标有。。。
发生这种情况的时候有截图吗或者是有没有什么特殊的使用条件？
![image](https://cloud.githubusercontent.com/assets/3608762/24757190/05fd137a-1b11-11e7-8301-6a8d0a35504e.png)

相关的统计功能还在完善中，部分适用情形下会引发程序错误。

**Comment by bickman** [comment]
嗯，有时候图表横坐标会显示错误，但是之后又好了，所以也不清楚到底什么情况会发生问题
