### ISSUE TITLE
在开机后出现cpu占用基本上100%的情况

### ISSUE THREAD

**Issue by ninn55** [shadowsocks/shadowsocks-windows#1086]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
请问是哪个进程占用了所有的CPU？因为SS-win有很多部分组成。
