### ISSUE TITLE
Are there any plans to backport AEAD ciphers from fuckshadows?

### ISSUE THREAD

**Issue by zeptoTantalum** [shadowsocks/shadowsocks-windows#1088]
It seems that FuckShadows ( https://github.com/fuckshadows ) has been using similar AEAD ciphers to shadowsocks, and implement them on a .NET windows application (fuckshadows-windows) basing on shadowsocks-windows. Are there any plan to backport those ciphers to shadowsocks-windows?

**Comment by lixingcong** [comment]
The name 'Fuc...' sounds likes a joke :)

**Comment by zeptoTantalum** [comment]
@lixingcong That it **sounds** like a joke doesn't mean it **is** a joke. Glancing through its source code, it seems that fuckshadows-windows is based on shadowsocks-windows 3.4.3. It has deprecated OTA, has refactored the core encryption/decryption, has added AEAD ciphers. Seems the main difference between fuckshadows and shadowsocks protocol is the key derivation function, and that fuckshadows is trying to randomize the TCP segment / UDP packet length, which has been strongly proposed by @breakwa11 .

(I am not sure because I don't really read those codes carefully.)

**Comment by zeptoTantalum** [comment]
And the main contributors of shadowsocks-windows, @celeron533 and @wongsyrone , are the main contributors to fuckshadows see ( https://github.com/fuckshadows/fuckshadows-windows/issues/1 ).
Users of shadowsocks-windows are actually in need of those new ciphers ( I myself even use Windows Subsystem for Linux to use shadowsocks-libev ). Fuckshadows-windows might have implemented all this while the development of shadowsocks-windows is almost suspended. So thing is really getting weird...

**Comment by celeron533** [comment]
Sorry that I am not the main contributor of both projects. Just did a little bit work.

![image](https://cloud.githubusercontent.com/assets/3608762/24458179/c2bd03d2-14ca-11e7-88d1-7ec3b830cb99.png)

**Comment by zeptoTantalum** [comment]
So, the question is still not answered. The purpose of fuckshadows is still a mystery. I'm actually worrying that @wongsyrone is trying to fork shadowsocks project again. I don't really hope this happens, since we already have shadowsocksr.

@celeron533 , if you don't mind, may I try to backport AEAD ciphers from fuckshadows? I'm not familiar with cryptography, but with specification and reference implementation exists, maybe I can do it.

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1387#issuecomment-288294307

**Comment by breakwa11** [comment]
@zeptoTantalum 你做呗，我支持

**Comment by wongsyrone** [comment]
Done.
