### ISSUE TITLE
win10 连接偶尔会断了，连接上，但流量出不去。日志就显示connect to ss server

### ISSUE THREAD

**Issue by lqclester** [shadowsocks/shadowsocks-windows#1089]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by myfingerhurt** [comment]
这个问题是你的DNS遭到污染的可能性极大。
