### ISSUE TITLE
新的aes-256-gcm在windows10平台无法正常工作

### ISSUE THREAD

**Issue by kkkkke** [shadowsocks/shadowsocks-windows#1090]
vs2017, 默认编译选项，服务器为shadowsocks-libev，浏览器为chrome的最新版，与此同时aes-256-cfb可以工作。
shadowsocks-libev是用官方centos源的。

# !/bin/bash
config=$(cat <<EOF
{
    "server": "0.0.0.0",
    "server_port": 443,
    "local_address": "0.0.0.0",
    "local_port": 1080,
    "password": "",
    "timeout": 300,
    "method":"aes-256-gcm",
    "mode": "tcp_and_udp",
    "nameserver": "8.8.8.8",
    "user": "shadowsocks",
    "fast_open": true
}
EOF);
echo  "$config" 
yum install epel-release -y;
yum install gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto udns-devel libev-devel -y;
yum install wget -y
wget -P /etc/yum.repos.d/ https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/repo/epel-7/librehat-shadowsocks-epel-7.repo;
yum update -y;
yum install shadowsocks-libev -y;
echo  "$config" > /etc/shadowsocks-libev/config.json;
useradd -r shadowsocks;
chkconfig shadowsocks-libev on;
service shadowsocks-libev start;
以上是我的部署脚本，与实际唯一不同的地方是bbr的开启，但我认为没有影响

**Comment by suikatomoki** [comment]
https://copr-be.cloud.fedoraproject.org/results/librehat/shadowsocks/epel-7-x86_64/00464827-shadowsocks-libev/build-00464827.rsync.log

**Comment by kkkkke** [comment]
@suikatomoki 谢啦，万万没想到官方库里的这么旧

**Comment by netroby** [comment]
You can using the chacha20-ietf-poly1305
