### ISSUE TITLE
建议从剪贴板导入url时 支持导入多个url

### ISSUE THREAD

**Issue by vy0b0x** [shadowsocks/shadowsocks-windows#1091]
我使用的版本应该是3.4 找不到哪里能看版本 但是检查更新提示没有可用的更新 所以应该是最新版的

我使用这个版本从剪贴板导入url时 只能一条一条的导入 如果同时想导入多台服务器 这么做就很不方便

如果能在导入时 对剪贴板的内容根据换行符（#后面用来备注服务器的标签可能含有空白字符）分割 然后逐条处理 那就会很方便了

不知道诸君怎么看？

**Comment by celeron533** [comment]
我没有遇到过这样的用例，最多也就6，7个服务器。
文件夹下的`gui-config.json`里面有保存所有的服务器信息。可以手动直接更改。
或者你想分发一系列的服务器的话，将样板config文件发给其他人。

**Comment by breakwa11** [comment]
> 将样板config文件发给其他人

最早不知道是谁这么提议的，带了个坏的开头

**Comment by wongsyrone** [comment]
Accepted. will support this feature soon.

**Comment by wongsyrone** [comment]
Added via https://github.com/shadowsocks/shadowsocks-windows/commit/43672a8bda1b6493546fe30d4a02359766167bad
