### ISSUE TITLE
shadowsocks不能为chrome代理，其他浏览器都行

### ISSUE THREAD

**Issue by zykcareer** [shadowsocks/shadowsocks-windows#1092]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.3

### Environment(Operating system, .NET Framework, etc)
windows10 专业64位  .NET Framework 4.6
### Steps you have tried
重置chrome默认设置，IE默认设置

### What did you expect to see?
可以正常访问Google

### What did you see instead?

 Windows could not automatically detect this network's proxy settings Detected Detected  

### Config and error log in detail (with all sensitive info masked)

**Comment by FaCetheMoon** [comment]
shadowsocks客户端开启系统代理是否可行？
如果可行说明服务正常。如果不行请检查你的服务端设置是否正确。
单独设置chrome的代理需要switchy proxy插件，请自行在chrome插件中安装
