### ISSUE TITLE
4.0 的 SHA-512 值没贴全

### ISSUE THREAD

**Issue by mengmo** [shadowsocks/shadowsocks-windows#1094]
@wongsyrone
`EECC87861C2B1CF4C455EFB58B1DDB01D9348BC6AFC318636F599C195FEDEC8295A902E30C2977D00F98F7D16F0427CA741DDDBA7D91E2EF`
`EECC87861C2B1CF4C455EFB58B1DDB01D9348BC6AFC318636F599C195FEDEC8295A902E30C2977D00F98F7D16F0427CA741DDDBA7D91E2EF8EB08E16671E342E`
这还真把人给吓了一跳

**Comment by wongsyrone** [comment]
好了，更上去了。
