### ISSUE TITLE
Error with AEAD

### ISSUE THREAD

**Issue by asmadeus08** [shadowsocks/shadowsocks-windows#1095]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0

### Environment(Operating system, .NET Framework, etc)
4.6.2

### Steps you have tried
Installed SS-libev (last version) on Ubuntu 16.10 x64 and change mode to aes-128-gcm.

### What did you expect to see?
Working connection

### What did you see instead?
I choose aes-128-gcm on windows side with new version of client 4.0. But that's what i got on server side
Restart service and other things doesnt help at all

### Config and error log in detail (with all sensitive info masked)
ERROR: failed to handshake with 95.47.57.68: authentication error

**Comment by wongsyrone** [comment]
tested with go-shadowsocks2.
