### ISSUE TITLE
4.0 avast报毒

### ISSUE THREAD

**Issue by zhanglingbei** [shadowsocks/shadowsocks-windows#1096]
![sp170404_184303](https://cloud.githubusercontent.com/assets/12751257/24654507/7b93f2a8-196c-11e7-97fd-33043309a04d.png)

**Comment by pexcn** [comment]
应该是误报

**Comment by karlind** [comment]
确实有毒，更新之后服务器直接被日志记录塞满了，被用来发垃圾邮件了！确实有毒！！

**Comment by myfingerhurt** [comment]
hash值一样吗？

**Comment by ChineTsai** [comment]
我只会狂弹广告窗口

**Comment by chenshaoju** [comment]
你好，刚在VirusTotal使用60款杀毒软件进行检测，未发现病毒：
https://www.virustotal.com/en/file/f02549d525246252199201a281c46e8861839814bd97247e0bcf3dd8ecd7d238/analysis/1492149254/

请尝试更新你的杀毒软件病毒库，然后再试。

**Comment by zhanglingbei** [comment]
@myfingerhurt  hash值一样的

**Comment by zhanglingbei** [comment]
@chenshaoju 我有关注到您提供的网址显示AVAST报无毒，我的AVAST也是时刻保持最新的。
但这个报毒是【行为防护】，就是说是新版shadowsocks中新增的某个进程触发了杀软行为保护，进而对其阻拦。
我发现更新并打开4.0以及之后的版本，shadowsocks.exe所在文件夹内容会变成只读，之前版本均无此情况，不知是否是此操作触发预警。

**Comment by chenshaoju** [comment]
对于大部分杀毒软件的预防护功能，首先判断该软件的使用范围，然后作为参数再进行行为评估。

因此，AVAST可能会因为SS的使用量不高（相对于同时使用AVAST＋SS的环境，可能只占0.001%）而对SS进行严格防护，所有SS的相关操作都可能会被认为是危险操作，比如修改注册表中的代理设置、建立本地的SOCKS/HTTP代理服务器。

具体情况，请参阅AVAST帮助文档中关于行为防护章节。

建议将SS加入白名单或者更换其它杀毒软件，我使用的Avira没有任何报警。
