### ISSUE TITLE
4.0客户端有毒

### ISSUE THREAD

**Issue by karlind** [shadowsocks/shadowsocks-windows#1100]
更新成 4.0 之后，服务器直接被用来发垃圾邮件了，日志文件直接被塞满，整整2个G的日志，全是发垃圾邮件的日志，客户端电脑直接被卡死！
强烈建议换成shadowsocks-qt，这个版本不安全！不安全！

**Comment by pexcn** [comment]
我想这个 issues 可以 close 掉了

**Comment by celeron533** [comment]
1. 检查你的服务器有没有被入侵
2. 检查你的客户端机器有没有被入侵
3. 请从可靠源头下载软件
4. SS-win公开源代码，你可以检查后自己编译保证万无一失

**Comment by karlind** [comment]
忘了来更新这个 issue， 实在是抱歉。
经过排查，我发现了问题不是客户端有毒，客户端很安全，问题出在了`允许来自局域网的连接`，这个选项居然是监听 `0.0.0.0` , 意味着在无认证的情况下允许外部的任何机器的连接，导致了服务器被当做垃圾邮件服务器。本来我压根就没想到会有外部机器连接，因为学校有两道防火墙，之前防火墙一直够能够过滤掉这些外部发起的请求，然而我现在才发现学校的防火墙居然没有过滤掉这些请求。。。
当时轻易下了结论，为了避免误导，所以来更新一下这个 issue， 实在是抱歉。
