### ISSUE TITLE
Windows在连接到PPTP VPN下，shadowsocks无法使用

### ISSUE THREAD

**Issue by 1558204459** [shadowsocks/shadowsocks-windows#1101]
由于某些原因，需要连接到VPN下使用，但是连上VPN之后，发现似乎shadowsocks就没用了，我查看了IE的Internet连接设置，里面有VPN选项与使用配置文件选项，是不是VPN与shadowsocks有冲突，使用VPN之后就无法再使用shadowsocks

**Comment by 1558204459** [comment]
![image](https://cloud.githubusercontent.com/assets/13426994/24788749/b9ec5dce-1ba1-11e7-876d-a6a2043d4169.png)
这个是Internet连接里的配置，有VPN选项，还有下面的局域网设置

**Comment by 1558204459** [comment]
如果是与VPN冲突，那么有什么解决办法吗？

**Comment by 1558204459** [comment]
问题已解决，在使用VPN下，无法再使用shadowsocks配置代理，两者冲突，可以在浏览器里面单独设置

**Comment by temberature** [comment]
修改ss 端口试试

**Comment by zry118** [comment]
免费试用几天高速机场，可上速度4k，还有十几个邀请次数，邀请码：0BKG    链接地址：http://www.vwall.gq/auth/register?code=0BKG

**Comment by Leocat81** [comment]
@1558204459 

> 问题已解决，在使用VPN下，无法再使用shadowsocks配置代理，两者冲突，可以在浏览器里面单独设置

请问你在浏览器哪里单独设置的？我遇到了这个问题
