### ISSUE TITLE
4.0版本在WIN10下， 反选“启用系统代理”时系统代理配置没有取消！

### ISSUE THREAD

**Issue by softfn** [shadowsocks/shadowsocks-windows#1103]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
这个功能目前会恢复到开启『启用系统代理』设置之前的状态。

**Comment by Mak-dz** [comment]
Nothing sorry
