### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by loveGEM** [shadowsocks/shadowsocks-windows#1104]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0

### Environment(Operating system, .NET Framework, etc)
4.6.2 windows7 7601

### Steps you have tried
open

### Config and error log in detail (with all sensitive info masked)
![default](https://cloud.githubusercontent.com/assets/27019971/24809970/281da2f2-1bf3-11e7-8cb3-9dba3d6fdd94.PNG)

**Comment by chenshaoju** [comment]
请下载： https://www.microsoft.com/en-us/download/details.aspx?id=30135 清理掉 .Net Framework 后，重新安装： https://www.microsoft.com/zh-CN/download/details.aspx?id=53344

**Comment by wongsyrone** [comment]
删掉配置文件重新配置一下。

**Comment by loveGEM** [comment]
在win10下安装NET Framework4.6.1，ss4.0.1运行正常，感谢大大
