### ISSUE TITLE
aead加密udp转发失败

### ISSUE THREAD

**Issue by acalimit** [shadowsocks/shadowsocks-windows#1105]
gcm chacha20-ietf-poly1305都这样，换用别的加密正常。
https://github.com/shadowsocks/shadowsocks/issues/827
这边也有人遇到，应该是客户端的问题。

**Comment by wongsyrone** [comment]
try https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-yqdou/build/1.0.10/job/048bahm0kupi3bm8/artifacts

**Comment by wongsyrone** [comment]
OK. someone tell me UDP relay is working now. Closing.
