### ISSUE TITLE
现在的版本是否原生支持udp转发

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-windows#1106]
请告诉我是否原生支持proxycap和sockscap64在我的windows10上一直无法正常工作老是显示无法链接steam

**Comment by wongsyrone** [comment]
try https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-yqdou/build/1.0.10/job/048bahm0kupi3bm8/artifacts

**Comment by wongsyrone** [comment]
Shadowsocks doesn't support UDP fragmentation since the FRAG field is dropped; other should work fine.
