### ISSUE TITLE
新版本的语言显示问题

### ISSUE THREAD

**Issue by xhzwxhz** [shadowsocks/shadowsocks-windows#1109]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### 4.0之后是依据locale来显示了吗？我这里设置的locale=japanese，country=usa，现在最新的两个版本都是显示日文，不喜欢啊，能不能自己设置语言？

**Comment by wongsyrone** [comment]
是的，现在根据系统语言设置来显示对应的语言，默认是英语。之前是英文是因为之前没有添加日语支持。

**Comment by xhzwxhz** [comment]
请问除了按照系统语言显示外能不能有别的方法设置为英文，如果不能能不能麻烦添加一个设置项，个人还是喜欢英文显示，谢谢您的辛苦开发。
