### ISSUE TITLE
电脑重启后日志查看器最大化

### ISSUE THREAD

**Issue by tangshiba** [shadowsocks/shadowsocks-windows#1110]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.1

### Environment(Operating system, .NET Framework, etc)
win10 x64 1607

### What did you expect to see?
日志查看器保持设置大小

### What did you see instead?
日志查看器最大化

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
It is expected. Check https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Properties/Settings.settings

**Comment by tangshiba** [comment]
Before Version 4, if I set the size of the log viewer, then restart the window will maintain the size.
At Version 4, set the size, after restart computer, it will be reset to maximize.
