### ISSUE TITLE
Windows 10 自启动任务栏无法显示图标

### ISSUE THREAD

**Issue by RyanWestinLiu** [shadowsocks/shadowsocks-windows#1112]
Windows 10 设置自启动，开机后代理功能正常，但是任务栏没有显示小飞机图标。于是没有办法进行配置和操作。只能在任务管理器中将进程关掉之后重新启动，图标才会出现。
我觉得 #1066 也有可能是同样的问题。

**Comment by RyanWestinLiu** [comment]
已修改了描述

**Comment by wongsyrone** [comment]
Cannot reproduce on my side.
