### ISSUE TITLE
服务器列表新增折叠功能

### ISSUE THREAD

**Issue by pk000** [shadowsocks/shadowsocks-windows#1115]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.1

### Environment(Operating system, .NET Framework, etc)
Windows 10 Pro 1607 14393.1066

### Steps you have tried
有不同的SS站账号，每个SS站都有约10个服务器，都添加到shadowssocks-win后，菜单列表太长，甚至超过屏幕范围。但是不能用鼠标滚轮滚动列表，只能点击顶端或底部的箭头来滚动。

### What did you expect to see?
（1）鼠标滚动列表功能。
（2）折叠前缀相同的服务器。
第一级菜单abc.com->第二级菜单sg1(IP address:Port)、jp1(IP address:Port)、us1(IP address:Port)
第一级菜单def.com->第二级菜单sg1(IP address:Port)、jp1(IP address:Port)、us1(IP address:Port)
第一级菜单ghi.com->第二级菜单sg1(IP address:Port)、jp1(IP address:Port)、us1(IP address:Port)
形如：
abc.com->sg1(IP address:Port)
---------->jp1(IP address:Port)
---------->us1(IP address:Port)
def.com->sg1(IP address:Port)
---------->jp1(IP address:Port)
---------->us1(IP address:Port)
ghi.com->sg1(IP address:Port)
---------->jp1(IP address:Port)
---------->us1(IP address:Port)

### What did you see instead?
（1）不能用鼠标滚轮滚动列表，只能点击顶端或底部的箭头来滚动。
（2）前缀相同的服务器均排列在一级列表。形如：
abc.com-sg1(IP address:Port)
abc.com-jp1(IP address:Port)
abc.com-us1(IP address:Port)
def.com-sg1(IP address:Port)
def.com-jp1(IP address:Port)
def.com-us1(IP address:Port)
ghi.com-sg1(IP address:Port)
ghi.com-jp1(IP address:Port)
ghi.com-us1(IP address:Port)

### Config and error log in detail (with all sensitive info masked)
配置文件和log无错误。

**Comment by celeron533** [comment]
鼠标可以滚动服务器列表的，你需要先点击一下列表把焦点弄上去才能滚动。

**Comment by pk000** [comment]
聚焦了也不能滚动。

**Comment by wongsyrone** [comment]
No plan for this.
