### ISSUE TITLE
Win10创意者更新版

### ISSUE THREAD

**Issue by Dhgan** [shadowsocks/shadowsocks-windows#1116]
### Version(release version or AppVeyor link)
Shadowsocks-4.0.1

### Environment(Operating system, .NET Framework, etc)
Win10 1703

### Steps you have tried
1. 打开 Shadowsocks
2. 进入 win 10 的设置
3. 点击网络和 Internet
4. 点击拨号
5. 点击宽带连接，点击连接
6. 连接成功

### What did you expect to see?
打开浏览器能访问 Google

### What did you see instead?
访问 Google失败

### Config and error log in detail (with all sensitive info masked)
在Win10创意者更新版（1703）中，若使用宽带连接，代理不起作用。
使用无线网或路由器接过来的网线都正常，唯独使用宽带连接，代理无效。
查看日志没有报错，使用宽带连接后，访问Google没有走代理，设置全局模式也没有走代理

**Comment by hellofwy** [comment]
不要重复提交问题。#1111
请按照模板，提供更多信息。

**Comment by Dhgan** [comment]
Version(release version or AppVeyor link)

Shadowsocks-4.0.1

Environment(Operating system, .NET Framework, etc)

Win10 1703

不知道还要提供哪些信息，查看日志没有报错，使用宽带连接后，访问Google没有走代理，设置全局模式也没有走代理

**Comment by hellofwy** [comment]
“宽带连接” 太宽泛，可以明确问题复现步骤。

**Comment by elvisw** [comment]
“宽带连接” 有可能指Windows的PPPOE连接，因为Windows创建的PPPOE连接默认名称就是“宽带连接” 。

**Comment by henrylethe** [comment]
目前我发现的问题是Win10 1703中使用Shadowsocks-4.0.1, 系统设置中的代理会自动关闭.
尝试过在shadowsocks端重新开启, 过一段时间后又自动关闭了.

**Comment by wongsyrone** [comment]
pppoe连接名字用全英文

**Comment by Dhgan** [comment]
pppoe连接名用英文可以，谢谢 @wongsyrone

**Comment by wongsyrone** [comment]
这个根源是sysproxy获取RAS链接名再应用回去的时候的问题，属于已知bug，但是不知道怎么解决。编码已经用了Unicode，如果有人有兴趣可以给sysproxy发PR
