### ISSUE TITLE
已经添加规则，为什么PAC模式下fonts.googleapis.com无法加载，一直是pending状态，全局模式正常

### ISSUE THREAD

**Issue by bao007fei** [shadowsocks/shadowsocks-windows#1118]
I've already add rules to PAC, why fonts.googleapis.com can't load, always in pending status. Global mode works fine.

**Comment by bao007fei** [comment]
dns 改为8.8.8.8，问题暂时解决。

**Comment by cristhevirgin** [comment]
Hi sir! I'm new here. How can I use that DNS? Thanks

**Comment by bao007fei** [comment]
You can Google "change dns". It's very simple to follow the instruction.

**Comment by bao007fei** [comment]
但是用8.8.8.8 dns访问国内网站响应缓慢，这是个问题。

**Comment by cristhevirgin** [comment]
Pls teach me sir. 😊 It'll brighten my day if you will teach me. 😊 dm me sir on facebook. I'm not active here. Huhu thanks facebook.com/cristhevirgin thanks si!!! 😊
