### ISSUE TITLE
OTA and Streisand

### ISSUE THREAD

**Issue by tiliarou** [shadowsocks/shadowsocks-windows#1119]
OTA is needed by Streisand to connect to Shadowsock server. Is there a way to force OTA again in 4.xx ? Or a way to disable this requirement on my Streisand server ?

**Comment by wongsyrone** [comment]
set 'auth' to false on your server

**Comment by wongsyrone** [comment]
OTA is deprecated and will not be added back, contact Streisand and let them upgrade to use AEAD ciphers.

**Comment by cpu** [comment]
@wongsyrone @tiliarou I have a PR out to upgrade to the latest `shadosocks-libev` and an AEAD construction here: https://github.com/jlund/streisand/pull/611 

@tiliarou Please direct questions about Shadowsocks & Streisand to the Streisand repo and we can triage there :-)
