### ISSUE TITLE
win10 1703兼容问题

### ISSUE THREAD

**Issue by Tarocch1** [shadowsocks/shadowsocks-windows#1120]
windows10 1703 15063.138版本，chrome 57.0.2987.133无法使用Shadowsocks，系统代理无效，chrome流量根本不走代理，edge和ie可用，但速度极慢。
日志大量出现：
System.Net.Sockets.SocketException (0x80004005): 不知道这样的主机。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by wongsyrone** [comment]
> System.Net.Sockets.SocketException (0x80004005): 不知道这样的主机。

日志很清楚
