### ISSUE TITLE
非预期错误.Shadowsocks.Controller.PrivoxyRunner的类型初始值设定项引发异常

### ISSUE THREAD

**Issue by tsfissure** [shadowsocks/shadowsocks-windows#1121]
win7上使用出的问题。
如图：
![prun](https://cloud.githubusercontent.com/assets/15356446/25131150/49075efe-2477-11e7-8ea6-04388518e4d9.png)

**Comment by celeron533** [comment]
和 #828 有点像
安装 .net framework 4.6.2 试试

**Comment by tsfissure** [comment]
@celeron533 我安装了4.5.2结果一样失败了。我搜4.6.2，发现是Developer Pack什么的..很大..请问你有下载地址吗？

**Comment by hellofwy** [comment]
https://www.microsoft.com/zh-CN/download/details.aspx?id=53344
