### ISSUE TITLE
全局模式问题

### ISSUE THREAD

**Issue by gyaoshi** [shadowsocks/shadowsocks-windows#1122]
### Version(release version or AppVeyor link)
4.0.1.0

### Environment(Operating system, .NET Framework, etc)
win10

### Steps you have tried
使用全局模式一段时间后，切换回pac模式，开国内网很慢，感觉仍然是在全局模式。

关闭“启用系统代理”， 再打开，网络才恢复正常。

同样的问题一直存在。

-----------
问题解决。。是我用的DNS不稳定

**Comment by celeron533** [comment]
当你觉得慢的时候，检查一下系统代理设置是什么样子的。是全局还是PAC？两种方式都看一下
* Internet选项
* 去IP.cn检查你的IP
