### ISSUE TITLE
let me change privoxy configurations

### ISSUE THREAD

**Issue by ahmadalli** [shadowsocks/shadowsocks-windows#1123]
### Version(release version or AppVeyor link) 
4.0.1

### Environment(Operating system, .NET Framework, etc) 
Windows 10 creator's update

### Steps you have tried
I've changed privoxy configurations to maximize timeout in order to prevent timeout from privoxy

### What did you see instead?
after enabling shadowsocks again, the config was rewritten

**Comment by celeron533** [comment]
A quick solution is to modify the config template from git and rebuild the project by yourself...
