### ISSUE TITLE
最新版SS，最近经常出现断开情况~~

### ISSUE THREAD

**Issue by Sunnysunny321** [shadowsocks/shadowsocks-windows#1126]
ss版本4.0.1，电脑win7 64位, .Net Framework4.6.2

最近笔记本连接SS代理，总是时而好，时而不好。移动端正常。之前用是没有问题的，最近3天老是出现这样的问题。

日志见下：
[2017-04-24 08:59:49] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)

**Comment by zhangkmsjtu** [comment]
我也遇到过，不过是老版本，换了新版本就好了。

**Comment by celeron533** [comment]
看上去是网络连接不稳定

**Comment by Sunnysunny321** [comment]
这是比较详细的log：
[2017-04-24 09:00:00] Shadowsocks started
[2017-04-24 09:00:00] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by Sunnysunny321** [comment]
目前用的版本就是最新的4.0.1~~

**Comment by Sunnysunny321** [comment]
请问网络连接不稳定可能的原因会是什么呢？
