### ISSUE TITLE
windows10-1703 无法使用新版ss

### ISSUE THREAD

**Issue by wmh90** [shadowsocks/shadowsocks-windows#1127]
手里的3.4.3和4.0.1都无法使用，2.5.2可以用。
有一样问题的吗？

**Comment by hellofwy** [comment]
请提供更多信息

**Comment by wmh90** [comment]
就是更新了win10 1703以后，正常打开ss，显示已连接服务器。但是被墙的网站打不开，在打开ss的时候也没有显示上传、下载的三角图标（以前用是有的）。测试网站：google、wiki，测试浏览器 chrome、edge、ie

**Comment by smdhz** [comment]
![default](https://cloud.githubusercontent.com/assets/8757988/25326305/33d9af84-2902-11e7-99b8-4629e760a741.gif)
没有任何问题，信息不足无法重现

**Comment by wmh90** [comment]
刚刚又试了一下，4.0.1版本，用edge可以正常使用，但是chrome还是不行。1607的时候是的可以正常使用的。
额……我也不知道提供怎样的信息可以让别人复现，还是谢谢了

**Comment by wongsyrone** [comment]
Similar to #1125

**Comment by fandylongzi7** [comment]
在我格式化C盘重装最新版1703的win10后，同样遇到该问题，防火墙已打勾允许，小飞机两个选项都选了全局代理，确认节点是没问题了。但是还是用不了ssr，感觉是不起作用，测试的时候用的是chrome浏览器的在线安装包，一直显示正在联网，却下载不了。但之前1607的Windows也是一样的配置方法，却能正常使用。

**Comment by annBeing** [comment]
@wmh90  谢了， 试了一下edge正常， 我win10 15063 火狐也不可以。。。。
