### ISSUE TITLE
ie代理设置问题

### ISSUE THREAD

**Issue by findlayfeng** [shadowsocks/shadowsocks-windows#1128]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

你好，
   我的使用环境是这样的，“系统代理模式”设置是“全局”的，然后“启动系统代理”前面的勾没有打上钩子，这样后台的代理服务实际上是有运行的，就是ie的代理配置被关闭了，我使用chrome浏览器的SwitchyOmega插件管理链接的代理。
  有些软件会从IE获取代理配置进行访问，这个时候如果我会希望这个软件通过代理访问，我就会勾上“启动系统代理”前面的钩子，这个时候IE的代理被设置，这些软件的访问也会通过代理进行。完了，我希望回复成默认无代理的时候，去掉“启动系统代理”，在以前ie的代理配置会自动关闭，现在不行，需要我手动打开系统配置里面取消代理设置。

### Version(release version or AppVeyor link)
4.0.1

### Environment(Operating system, .NET Framework, etc)
Win10-1703 15063.138 .NET Framework 4.7

### Steps you have tried
额，手动关闭，不过这样很麻烦

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
启用『启用系统代理』之前会记录之前的代理设置，在关闭SS的代理功能之后会恢复。

如果没有正常恢复，可能与 #1125 情况类似。目前没有 Win10-1703 15063.138 的环境。
