### ISSUE TITLE
win7 32位无法使用4.0.1，显示已停止工作。换回3.3.0没问题，其他版本的都不行

### ISSUE THREAD

**Issue by Biluoshilang** [shadowsocks/shadowsocks-windows#1129]
![1](https://cloud.githubusercontent.com/assets/6211395/25557540/123aa7aa-2d46-11e7-8af1-7c7874bde57a.jpg)

不过3.3.0下经常出现网页一直处在加载中的情况……小飞机的蓝、褐三角标都消失了
![2](https://cloud.githubusercontent.com/assets/6211395/25557577/e2bbcb8e-2d46-11e7-8f9a-553ebc9cad1d.jpg)

**Comment by zhaoensi** [comment]
net framework 的问题，卸载掉装上4.6.2以上就行了
