### ISSUE TITLE
最新的4.0.1版本中，如果不配置先好服务器，点击设置快捷键，会出现错误提示框

### ISSUE THREAD

**Issue by lichee0215** [shadowsocks/shadowsocks-windows#1131]
只要配置好服务器，就可以正常使用了。
现在的错误提示框里全是引起错误的代码，建议把这个提示框的内容改为提示用户配置服务器。

**Comment by wongsyrone** [comment]
首次使用未配置的时候还没有创建gui-config.json所以会出现null ref exp
