### ISSUE TITLE
请教一下，windows本机上别的软件是怎么知道ss开了本地代理的？

### ISSUE THREAD

**Issue by mengyaoss77** [shadowsocks/shadowsocks-windows#1132]
实在是google不到了，想不通这个问题。
为什么浏览器就能直接走ss代理?
还是说只要访问墙外服务的软件都能走ss代理？

**Comment by hellofwy** [comment]
这是操作系统提供的功能

**Comment by chenshaoju** [comment]
https://www.google.com/#newwindow=1&safe=off&q=proxy%20auto-config%20(PAC)

**Comment by celeron533** [comment]
上层应用可不管这些，通过操作系统托管访问网络，然后操作系统通过PAC文件决定是否使用代理，使用什么代理。
