### ISSUE TITLE
关于ipv6的设置连上了，但是上不了网

### ISSUE THREAD

**Issue by abearxiong** [shadowsocks/shadowsocks-windows#1133]
感觉刚才问错地方了，
我有一个问题，然后一直尝试没有成功，想请教一下。
搭建了一个shadowsock然后我用shadowsocks-windows
用"server":"::",
然后使用ipv4的时候可以上得了代理。
但是使用ipv6的时候可以连上一下，然后上不了其他网络，
日志只有一段：
_info connecting api.github.con:443 from 2001:·····
info connecting github.con:443 from 2001:·····
info connecting github-cloud.s3.amazonaws.com:4432001····_
## 而且看了日志，当我使用ipv4的时候。我的电脑要是使用4.0.1的版本的用不了，会报错，说
**WARING unsupported addrtype 171,maybe worng password or encryption method
ERROR can not parse header when handling connection form···**
我用4.0.0就可以

用wifi连的网络，可以使用shadowsocks，但是用宽带的不能使用，中途连上，但是一直不能用。

谢谢

**Comment by abearxiong** [comment]
让自己只有ipv6 的情况下然后xshell上去了。 然后看的日志

**Comment by abearxiong** [comment]
换了几个网络，感觉是如果用电脑自带的拨号就不行，教育网的wifi上得去。

**Comment by celeron533** [comment]
教育网允许v6出境，一般的网络不行

**Comment by abearxiong** [comment]
@celeron533   那个是我问错地方的。啦啦啦！！！ 
的确是V6允许出境。
 所以我是在有六的情况下登陆的。  但是，我的网络，通过拨号连接的时候就不能使用那个拨号。我不知道是为什么。

**Comment by abearxiong** [comment]
已解决！！！
我从4换版本，换下去！！！然后才可以，为啥呢？
