### ISSUE TITLE
Could not load template file

### ISSUE THREAD

**Issue by kingcmy** [shadowsocks/shadowsocks-windows#1134]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
2.5.8-4.0.1 all try

### Environment(Operating system, .NET Framework, etc)
win10 ltsb 2016
.net4.0

### Steps you have tried
all steps,search on goole,baidu, reinstall windows 10,switch pac or global etc.

### What did you expect to see?
slove it

### Config and error log in detail (with all sensitive info masked)
when I use shadowsocks to visit www.google.com.hk，the chrome is display error:

500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by celeron533** [comment]
If you would like to use Shadowsocks-Windows 3.0 and above, you should install .Net Framework 4.6.2. This is a mandatory requirement.

必须安装.Net Framework 4.6.2

Do you have any logs? 另外有日志么？敏感信息注意保护。

![image](https://cloud.githubusercontent.com/assets/3608762/25699949/fcbbba26-30f7-11e7-9df8-339812586ac0.png)
