### ISSUE TITLE
启用系统代理，然后在关闭后。自动设置IE局域网选项“自动检测设置”

### ISSUE THREAD

**Issue by neighbads** [shadowsocks/shadowsocks-windows#1137]
这样导致关闭代理后，打开网页会等待很长时间的检测。

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1078#issuecomment-290724853

**Comment by wongsyrone** [comment]
Set IE settings to what you like before enabling system proxy. You settings will be restored after use.
