### ISSUE TITLE
shadowsocks 4.0.1用不了，求更新

### ISSUE THREAD

**Issue by 974648183** [shadowsocks/shadowsocks-windows#1139]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
能否具体描述一下你的问题？
什么叫“用不了”？
有无错误提示？
