### ISSUE TITLE
Connection issuse with VMWare Bridge Protocol enabled

### ISSUE THREAD

**Issue by porsche613** [shadowsocks/shadowsocks-windows#1140]
### Version
shadowsocks-windows 4.0.1

### Environment
Windows 10.0.15063.196 version 1703, .NET 4.7.2046.0, VMWare Worstation Player 12.5.5, SimpleDNSCrypt 0.4.2

### Steps you have tried
* Uninstall SimpleDNSCrypt 0.4.2 (note: DNSCrypt also performs the same issuse after install VMWare)
* Reinstall network adapter drivers
* Reset network in Windows 10 Setting (Windows Setting -> Network and Internet -> State -> Network reset)
* winsocks reset

They aren't work. But when I tried to:

* Uninstall VMWare

It's works, SS perform correctly. But after reinstall VMWare, SS have connection issuse again. Later I diasbled the "VMWare Bridge Protocol" in network adapter property, SS perform correctly again.

### What did you expect to see?
I use SS Client to visited some website blocked in Mainland China, with VMWare installed.

### What did you see instead?
Firefox and Chrome reported "connect time out" or "connection reset" error frequently, but sometimes it can be connect success.

### Config and error log in detail (with all sensitive info masked)
connection log just logged lots of these:
...
"[date, time] connect (website:port)"
"[date, time] (server ip:port) time out"
...

but with a few of connection successfully messages. 

I have tried to run SS Windows client on other computer (without VMWare), I am also using SS Android client app on my smartphone, they work fine and so I can confirm my server also works fine. As I said DNSCrypt service has the same problem with VMWare installed, so maybe this issuse is a compatible problem.

**Comment by Atavic** [comment]
VMware Bridge Protocol driver (vmnetbridge.sys) starts with Service Name VMnetBridge at startup. If you stop the service the problem should be solved.

**Comment by porsche613** [comment]
Update:
If need to use VMware and Bridge Protocol, we can use Windows built-in Bridge Protocol to replace the VM's Bridge Protocol, here is some steps:
* Stop and disable the VMnetBridge Service (via @Atavic )
* Use vmnetcfg(Virtual Netwprk Editor from VMware) to creat a new virtual network adapter without DHCP enabled
* Open the Network and Sharing Center, click Change adapter settings, choose the Virtual NIC we created and the NIC you want to bridge it, right click them and click Bridge Connection

Done, enjoy it~
