### ISSUE TITLE
除了pac规则以外，建议直接绕过hosts文件里的有效域名，减少从shadowsocks经过的流量

### ISSUE THREAD

**Issue by QueenT** [shadowsocks/shadowsocks-windows#1141]
很多人使用的是付费的ss服务，所以如果能够通过hosts直接访问的话，可以节省不少流量，而且直接访问一般会比通过ss更高效。

**Comment by wongsyrone** [comment]
No plan.

**Comment by osdu** [comment]
https://github.com/osdu/shadowsocks-windows-for-anmpserver  可以试试这个 ，我自己修改的，添加了`proxyIgnoreDomains` 参数可以忽略指定域名，pac 脚本也作了修改可以跳过代理
