### ISSUE TITLE
关于win10 1703无法使用chrome翻墙的发现

### ISSUE THREAD

**Issue by isfangwei** [shadowsocks/shadowsocks-windows#1142]
你好，升级到最新的win10系统之后无法通过chrome浏览器翻墙，当我更改宽带连接名称为英文名称之后重启，就可以正常使用了，请检查是否是bug，这一现在在win10上一个版本未曾出现，谢谢。

**Comment by celeron533** [comment]
已有记录。
https://github.com/shadowsocks/shadowsocks-windows/issues/1116#issuecomment-294075565

**Comment by wongsyrone** [comment]
> 更改宽带连接名称为英文名称之后

这个所有历史版本都会有这个问题，并不是新引入的。

**Comment by number018** [comment]
thanks for your answer
