### ISSUE TITLE
建议增加重启功能

### ISSUE THREAD

**Issue by haitaoh** [shadowsocks/shadowsocks-windows#1144]
###遇到的一个问题
ss开着，日志也正常显示连接，但是访问就是有问题，浏览器显示CONNECTED_TIME_OUT。
###我的解决办法
退出，然后再打开ss。（由于ss的特殊性，我一般都放在文件夹深处，不会创建快捷方式访问。所以希望有个重启的功能）

**Comment by chenshaoju** [comment]
该问题及有可能是你的SS服务端连接质量不理想导致的。
如果是租用的服务，请联系你的SS服务商检查线路。
如果是你自己搭建的SS服务端，请尝试：
https://gist.github.com/chenshaoju/b0e20f23efabb8eb2cd4

**Comment by haitaoh** [comment]
谢谢，服务器配置了一下，看下后面的效果。
