### ISSUE TITLE
forward proxy with authorization, username:password@my_company_proxy.com seems not work?

### ISSUE THREAD

**Issue by spectereye** [shadowsocks/shadowsocks-windows#1145]
### Version(release version or AppVeyor link)
shadowsocks/shadowsocks-windows 4.01 (latest)

### Environment(Operating system, .NET Framework, etc)
win 7

### Steps you have tried
forward proxy with authorization, username:password@my_company_proxy.com seems not work?

**Comment by wongsyrone** [comment]
Not supported.

**Comment by tiliarou** [comment]
Since you shadowsock is already supporting http and socks5 proxies, is it that difficult to implement authentication support ?

**Comment by chenshaoju** [comment]
pull requests are aways welcome.

for this moment, you can use 3rd-party proxy software use as "front proxy" to doing authentication like "ccproxy".

![image](https://user-images.githubusercontent.com/515763/41275932-1ccbbed8-6e55-11e8-925b-5fff057961e4.png)

**Comment by tiliarou** [comment]
Thanks, will look into this app and after check if I can understand shadowsock code to propose a commit.
