### ISSUE TITLE
Check clipboard for ss:// links proactively

### ISSUE THREAD

**Issue by jab** [shadowsocks/shadowsocks-windows#1147]
When shadowsocks-windows starts up, it could check if the user has copied an ss:// link to the clipboard, so it could proactively offer to add the server when it detects a new one. Something like:

![screen shot 2017-05-19 at 11 00 51](https://cloud.githubusercontent.com/assets/64992/26253944/fc4b71a8-3c82-11e7-9794-b1a991599e47.png)

Better yet, instead of just checking the clipboard once on startup, shadowsocks-windows could [monitor the clipboard](https://web.archive.org/web/20131104125500/http://www.radsoftware.com.au/articles/clipboardmonitor.aspx) while running, so if a user copies the link after starting shadowsocks, they can still get the offer.

**Comment by celeron533** [comment]
Similar to function 'import URL from clipboard'
![](https://cloud.githubusercontent.com/assets/3608762/26252982/616d41ae-3ce4-11e7-81fa-de4dc160021d.png)

**Comment by jab** [comment]
Yes, similar to "Import URL from clipboard", but better because it's proactive. This saves a new user from having to navigate through two levels of unfamiliar menus and a total of 22 different menu items to find the one they're supposed to click. It may seem like a small change but the usability of the feature will improve dramatically.

**Comment by jab** [comment]
I see this issue got some thumbs up over the last week. 👍 😺 
ss-win maintainers, would you accept a pull request that implemented this?

**Comment by wongsyrone** [comment]
To be honest, I don't think it's really useful. KISS.

**Comment by jab** [comment]
If by KISS you mean "keep it simple, stupid", that's my same motivation for opening this issue. Right now accomplishing basic tasks is unnecessarily complex, especially for new users.

**Comment by smdhz** [comment]
Keep watch clipboard may cause other software crash, e.g. [Clipboard.SetText](https://msdn.microsoft.com/zh-cn/library/ms597043(v=vs.110).aspx) may crash because a download software watching clipboard.

**Comment by wongsyrone** [comment]
Watch clipboard constantly isn't a good idea, we are not software like Thunder. BTW, you can import multiple servers via "import URL from clipboard"
