### ISSUE TITLE
为什么会有这么多启动项-_-b

### ISSUE THREAD

**Issue by CURAS** [shadowsocks/shadowsocks-windows#1148]
![image](https://cloud.githubusercontent.com/assets/14164381/26272644/9b7fa352-3d50-11e7-881e-949c256b18c7.png)
感觉每次更新就会多出两三个的样子。。。。这些长得一样的启动项是有其他作用嘛？求解答

**Comment by celeron533** [comment]
非常奇怪，建议全都清除掉，然后通过客户端内部自带的功能重新设置。
我这边4.0.1只有一个启动项。
你确定你下载的是原版？或者有没有用过奇奇怪怪的版本？

**Comment by CURAS** [comment]
我下的就是github上的版本，在客户端上关闭开机启动之后这些启动项就都没有了，但重新打开之后，这些启动项一个不少的重新出现在任务管理器里。
顺便说一句，这个问题我在半年前左右就遇到了，一直没有解决。

**Comment by wongsyrone** [comment]
Cannot reproduce on my side.

**Comment by CURAS** [comment]
![default](https://cloud.githubusercontent.com/assets/14164381/26273658/9be8dbb8-3d66-11e7-85f1-6c1fcaa06657.png)

去除原有的启动项并重新下载之后，开始只有一个启动项，过了一会儿就变成了这样

**Comment by yoyoyoooooooo** [comment]
我也有一样的问题，最多的时候有16个，全删了以后重新设置是6个
原因未知

**Comment by qiyuey** [comment]
我这边是6个启动项

**Comment by smdhz** [comment]
![default](https://cloud.githubusercontent.com/assets/8757988/26290630/894e23ac-3edb-11e7-9a6c-803d179cc391.JPG)
确实显示6个，不过真正的启动项只有一个，是注册表里的HKCU:Run Shadowsocks_2104208759 Shadowsocks.exe。
所以让Windows自己抽风去吧不要管他了。

**Comment by chenshaoju** [comment]
我猜测，这个是将程序启动后，程序本身再次启动的其他程序也计算进去了。
