### ISSUE TITLE
使用局域网共享时候YouTube很慢

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-windows#1150]
在电脑上还好,但是手机上看YouTube很卡，但是网页浏览很快，希望优化

**Comment by chenshaoju** [comment]
请尝试在电脑上Ping你的服务器IP，延迟有多少？
另外，手机是WiFi把？如果WiFi信号嘈杂，也会有影响。

**Comment by wongsyrone** [comment]
> 手机上看YouTube

如果是App的话，他默认会走UDP

**Comment by chenshaoju** [comment]
噢，我没有研究过手机版的Youtube，My bad. 😅

**Comment by Galaxy0419** [comment]
@wongsyrone 电脑端udp不支持所以慢？
