### ISSUE TITLE
为什么每次重启应用后都需要再注册一次快捷键？ BUG？ 还是原本就这样设计的？

### ISSUE THREAD

**Issue by FantaZZ** [shadowsocks/shadowsocks-windows#1153]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.2

### Environment(Operating system, .NET Framework, etc)
Win10 1607
.net 4.0.30319

### Steps you have tried
close then start app . shortcut keys was failure.

### What did you expect to see?
answer or fix

### What did you see instead?
.

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
#913 希望增加快捷键自动注册选项
