### ISSUE TITLE
It  does't work

### ISSUE THREAD

**Issue by xinyu123200** [shadowsocks/shadowsocks-windows#1154]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.5

### Environment(Operating system, .NET Framework, etc)
win 7  
.NET Framework 4.6.2

### Steps you have tried
nothing

### What did you expect to see?
I hope it could work

### What did you see instead?
It  does not work

### Config and error log in detail (with all sensitive info masked)
![default](https://cloud.githubusercontent.com/assets/20534269/26289296/6e278b7c-3ed1-11e7-8a2a-72aac8fe887b.png)

**Comment by chenshaoju** [comment]
Please try upgrade to 4.0.2 or new:
https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by celeron533** [comment]
你的服务器地址是否填写正确？
