### ISSUE TITLE
instagram图片无法正常查看

### ISSUE THREAD

**Issue by littleyuan** [shadowsocks/shadowsocks-windows#1157]
开通代理前期，instagram网站是可以打开并能浏览图片。现在只能打开网站，图片无法显示。

换了多个代理器均是这样。

**Comment by chenshaoju** [comment]
请确保你的代理列表或PAC代理了 *.cdninstagram.com 域名。

**Comment by wongsyrone** [comment]
用开发者工具看看需要什么域名，然后自己加规则，或者给gfwlist提交issue

**Comment by ycycn** [comment]
我也遇到这个问题了
解决方法如下

右键->PAC->从GFWList更新本地PAC
使用本地PAC
可以正常浏览图片了

我没使用在线PAC。不知道在线PAC效果怎么样。
祝你好运。

**Comment by JieHao258** [comment]
我也是这个问题，图库不显示照片

**Comment by chenshaoju** [comment]
我测试了一下，没有问题。

请按照上面的提示，更新一下本地PAC看看。

![image](https://user-images.githubusercontent.com/515763/74585996-db324580-501d-11ea-9491-b39364eb50aa.png)

**Comment by JieHao258** [comment]
我说的手机端，手机端你显示正常吗？

**Comment by chenshaoju** [comment]
也正常。

![Screenshot_20200216-000858](https://user-images.githubusercontent.com/515763/74591167-91168780-5050-11ea-9688-2a1c0a666d01.jpg)

PS：这儿是Shadowsocks for Windows的Issue列表，Android在 https://github.com/shadowsocks/shadowsocks-android/ 。

**Comment by JieHao258** [comment]
> 也正常。
> 
> ![截图_20200216-000858](https://user-images.githubusercontent.com/515763/74591167-91168780-5050-11ea-9688-2a1c0a666d01.jpg)
> 
> PS：这儿是Shadowsocks for Windows的问题列表，Android在https://github.com/shadowsocks/shadowsocks-android/。
麻烦请教下，我的Ins突然显示不了，需要怎么弄才可以正常呢

**Comment by JieHao258** [comment]
大神，这种手机端出现图库不显示的，也是和墙的规则有关系是吗？

**Comment by chenshaoju** [comment]
不知道。。。
