### ISSUE TITLE
能否将全局流量都发往ss本地代理服务器，再由代理服务器决定pac方式或者全局方式发往ss服务端？

### ISSUE THREAD

**Issue by xiedeacc** [shadowsocks/shadowsocks-windows#1161]
能否将全局流量都发往ss本地代理服务器，再由代理服务器决定pac方式或者全局方式发往ss服务端，这个有点类似VPN，但是VPN由于将所有流量发往了服务器，DNS解析实在太垃圾，访问国内的网站太慢了，如果ss客户端提供一个选项，将全局流量都发送到ss本地代理服务器，这样就不用在每个软件都要设置代理了

**Comment by smdhz** [comment]
你需要cyfdecyf/cow

**Comment by xiedeacc** [comment]
cyfdecy/cow能够拦截所有本地流量，发往二级代理吗？

2017-05-26 15:04 GMT+08:00 Fabre <notifications@github.com>:

**Comment by WenbinHou** [comment]
不是拦截，是二级代理。cow自己是一级代理。

在2017-05-26 16:12:47，侯文彬1400012825@pku.edu.cn写道：

cyfdecy/cow能够拦截所有本地流量，发往二级代理吗？

2017-05-26 15:04 GMT+08:00 Fabre <notifications@github.com>:

**Comment by xiedeacc** [comment]
本质上还是一个代理服务器，这样软件还是需要设置这个代理服务器，比如对于chrome需要结合omegaswitch等插件，我需要的是这么一个软件，本地所有流量，当然127.0.0.1除外，发到ss-local，ss-client类似的代理服务器，然后ss-local根据pac决定发往ss-server还是直接走本地路由出去，其实ss-local本身可以添加这么一个功能，修改本机路由表，将流量都发到自己的端口，这样就不用每个软件都配置代理了

2017-05-26 16:16 GMT+08:00 Wenbin Hou <notifications@github.com>:

**Comment by xiedeacc** [comment]
跟多少层代理没什么关系吧

在 2017年5月26日 下午5:45，YZ Xie <xiedeacc@gmail.com>写道：

**Comment by xiedeacc** [comment]
还是自己来造轮子吧，自己造轮子太浪费时间，生命宝贵啊

在 2017年5月26日 下午5:47，YZ Xie <xiedeacc@gmail.com>写道：

**Comment by nadoo** [comment]
@xiedeacc 试下这个：https://github.com/nadoo/glider

目前的开发分支支持通过配置文件设定代理规则，默认直接访问，列表中的走ss，有个前两天编译打包的版本： https://github.com/nadoo/glider/files/1245821/glider-0.4alpha.zip   需要的话可以看看

**Comment by xiedeacc** [comment]
我用chnrouter解决这个问题了，多谢推荐

2017-08-25 23:05 GMT+08:00 nadoo <notifications@github.com>:
