### ISSUE TITLE
希望客户端能推出时段切换功能

### ISSUE THREAD

**Issue by fhg90** [shadowsocks/shadowsocks-windows#1162]
众所周知家用宽带的白天和晚高峰的网络质量，动不动就抽风的尿性。希望推出时段切换功能。
比如 18:00 ~ 24:00 走优质线路，其余时间走普通线路。甚至可以设置工作日和周末定时切换线路。
这样一来可以更好的节省和调度网络资源。

**Comment by wongsyrone** [comment]
No plan.
