### ISSUE TITLE
我自己用ss改写了一个客户端 

### ISSUE THREAD

**Issue by 380wmda999** [shadowsocks/shadowsocks-windows#1163]
我自己用ss改写了一个客户端 下载地址:http://client.zbbsweb.com/client2.0.0.exe 服务器是我自己的，请问这样不会有侵权吧？

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 基于 GPLv3 协议，请开源。

具体协议请参阅：
非官方中文：https://sites.google.com/site/bergwolf02/gplv3_zh
英文原文：https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by 380wmda999** [comment]
问题是里面封装了我自己的服务器

**Comment by chenshaoju** [comment]
源码发布的话，去掉你自己的服务器即可。
