### ISSUE TITLE
Add an option to disable pac file

### ISSUE THREAD

**Issue by bohrshaw** [shadowsocks/shadowsocks-windows#1164]
To *not* use any pac file at all, I currently have to edit the local pac file to direct all traffic to shadowsocks.

**Comment by celeron533** [comment]
![image](https://cloud.githubusercontent.com/assets/3608762/26529884/91b51df0-43fb-11e7-8ac1-18b868fc857b.png)

**Comment by bohrshaw** [comment]
When "Enable System Proxy" is disabled, "Mode" can't be changed.
And I don't know if the pac file is used when System Proxy is not used.

**Comment by celeron533** [comment]
@bohrshaw 
* when using PAC, tray icon is white.
* when using Global, tray icon is blue.

**Comment by bohrshaw** [comment]
@celeron533 So when the tray icon is gray, the pac file is not used.
I have done some test to conclude this. There should be some documents writing about this behavior.
