### ISSUE TITLE
the shadowssocks doesn't workin windows 10 anymore

### ISSUE THREAD

**Issue by brliya** [shadowsocks/shadowsocks-windows#1165]
it worked at first,, but  from two weeks ago, sometime it works but very slow, most of the time, it doesn't work

### Version(release version or AppVeyor link)
have tried all version 3.4,4.01,3.02

### Environment(Operating system, .NET Framework, etc)
windows 10 home **version, .Net Framework  v4.0.30319

### Steps you have tried
open the shadowssocks,   and open the log windows

### What did you expect to see?
it should show data in and out , 

### What did you see instead?

show error message, and then show always time out

### Config and error log in detail (with all sensitive info masked)
server config
    "server":"my ip address",
    "server_port":8989,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"yourpassword",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": false

local config:
{
  "configs": [
    {
      "server": "my ip address",
      "server_port": 8989,
      "password": "my password",
      "method": "aes-256-cfb",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": false,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": null,
  "proxy": null,
  "hotkey": null
}

[2017-05-28 23:00:26] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-05-28 23:00:56] 192.254.196.182:8989 timed out
[2017-05-28 23:00:58] 192.254.196.182:8989 timed out
[2017-05-28 23:01:01] 192.254.196.182:8989 timed out
[2017-05-28 23:01:01] 192.254.196.182:8989 timed out
[2017-05-28 23:01:06] 192.254.196.182:8989 timed out
[2017-05-28 23:01:06] 192.254.196.182:8989 timed out

**Comment by chenshaoju** [comment]
Please check your server firewall config.

And your server IP has exposed in log.

**Comment by brliya** [comment]
it is awesome, the problem is fixed by opening the port to firewall, thank you so much, you all did a great job! I love you all 👍
