### ISSUE TITLE
希望支持分流

### ISSUE THREAD

**Issue by LBYPatrick** [shadowsocks/shadowsocks-windows#1166]
### Version(release version or AppVeyor link)
Shadowsocks-windows v4.0.2

### Environment(Operating system, .NET Framework, etc)
Windows 10

### What did you expect to see?
有个像ShadowsocksR客户端一样可以分流的选项

### What did you see instead?
然而并没有，PAC那个只适用于系统代理，我得用Proxifier才能搞定Google Drive啊...Proxifier不吃PAC，这就非常尴尬了...

### What do I really want ?
出一个功能，国内网站直连，其他网站走SS，具体参考ShadowsocksR的方案（她家的客户端与shadowsocks-libev搭配的时候有种说不出的慢，所以想换回来Shadowsocks-windows,结果发现没有这个功能...还好是日本服务器不然上网体验会有种想死的感觉），THX

**Comment by wongsyrone** [comment]
Write your own user rules or submit rules to GFWList.
