### ISSUE TITLE
集合已修改；可能无法执行枚举操作

### ISSUE THREAD

**Issue by ccen3020** [shadowsocks/shadowsocks-windows#1168]
不知道什么时候出来的
登陆之后就有（锁定时电脑是一直运行的）
有这个提示时程序可以正常工作
点了确定程序就退出了

### Version(release version or AppVeyor link)
4.0.1

### Environment(Operating system, .NET Framework, etc)
WINDOWS 10 1607（14393.1198）
.net框架应该是4.6

### Steps you have tried
none

### What did you expect to see?
none

### What did you see instead?
none

### Config and error log in detail (with all sensitive info masked)
---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。

   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)

   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()

   在 System.Collections.Generic.List`1.Enumerator.MoveNext()

   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()

   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   在 Shadowsocks.Model.StatisticsRecord..ctor(String identifier, ICollection`1 inboundSpeedRecords, ICollection`1 outboundSpeedRecords, ICollection`1 latencyRecords)

   在 Shadowsocks.Controller.AvailabilityStatistics.UpdateRecords()

   在 Shadowsocks.Controller.AvailabilityStatistics.Run(Object _)

   在 System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)

   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.TimerQueueTimer.CallCallback()

   在 System.Threading.TimerQueueTimer.Fire()

   在 System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)

   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   在 System.Threading.ThreadPoolWorkQueue.Dispatch()

   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---------------------------
确定   
---------------------------

**Comment by celeron533** [comment]
这是一个已知的可靠性统计的bug...

#906 非预期错误：集合已修改；可能无法执行枚举操作
