### ISSUE TITLE
display system notifications for (e.g. connectivity) state changes

### ISSUE THREAD

**Issue by jab** [shadowsocks/shadowsocks-windows#1169]
When ss-win successfully connects/disconnects to/from a shadowsocks server, or when the connection to a server unexpectedly fails, or when any other interesting state change happens, users don't currently get any notification about the state change.

ss-win could show a Windows system notification (the light yellow tooltip/balloon that pops up above its icon in the system tray) to give users a chance to know about and respond to any important changes.

Any interest in this feature?

**Comment by celeron533** [comment]
If user has a bad connection, such as 8% packet loss, the tooltip will behave as a Christmas tree...

**Comment by jab** [comment]
If I understood you correctly, you're saying that if this were implemented naively (e.g. with no debouncing), the tooltip would pop up all the time for users with a bad connection, and could get annoying. Thanks for raising a good point.

Given the choice between the current behavior, where there is no notification whatsoever when the connection is bad (flying blind), and having possibly a lot of notifications, it may be preferable to have a lot of notifications, so at least the user has a chance to know there's an issue and respond (even if the response is just to manually silence notifications temporarily).

However, this could also be implemented a little more intelligently than the extremely naive way, where ss-win unconditionally shows a notification the moment a qualifying state change happens. As a simple first cut, ss-win could throttle or debounce the notifications.

Based on either the connection flapping rate, or even a direct packet loss inspection, ss-win could then even display a higher-level notification like "You seem to have a bad connection to your server", and possibly suppress further notifications until the connection improves.

Not sure it's ever preferable to force the user to fly blind.

**Comment by burningmyself** [comment]
Can you speak Chinese, I can't understand English#

**Comment by celeron533** [comment]
@burningmyself , actually, I hope Trump speaks Chinese, too. However, English is the most common used language in international open source community.

@burningmyself ，我也希望川普能讲中文。但目前英文仍然是国际开源社区最常用的语言。

**Comment by celeron533** [comment]
@jab Thanks for the reply. That's one of the reason we have the network flow (upstream, downstream) on both tray icon (as indicator) and the log viewer. If an user is requesting a webpage and get no response, he/she could:
1. Check the tray icon's upstream/downstream indicator.
2. Mouse middle click the icon to check log for details.

Yes, operations above are not as simple as the way you have mentioned. But if the user have connection problems with a high frequency, I would recommended the user to change server or use an alternative internet connection instead of endless connection notifications.

**Comment by jab** [comment]
This proposal is aimed at the many users who don't know or think to use tooltips or logs to get information about the state of a program. Granted, such users would probably have a hard time even just adding a server to ss-win in the first place. But that's why I proposed #1146 and #1147, in hopes of making ss-win accessible to more users.
