### ISSUE TITLE
Option "Enable System Proxy" not working correctly.

### ISSUE THREAD

**Issue by gonejack** [shadowsocks/shadowsocks-windows#1170]
Version:
At least from v4.02

System:
Windows 10 creator update x64, the .net framework embedded within the system.

Action:
Unchecked the Enable System Proxy.

Expectation:
PAC link would be removed from internet setting.

Fact:
PAC link remains in the internet setting.

Logs:
No explicitly error message posted.
![capture](https://cloud.githubusercontent.com/assets/2720676/26747834/23c79b0e-482b-11e7-9fde-ed2a7ec63642.PNG)

**Comment by burningmyself** [comment]
You say too detailed, thank you, but you can say in Chinese in a piece#

**Comment by celeron533** [comment]
Hi @gonejack , there is fix in commit 816651e about the system proxy settings.
Could you please try to download ss-win 4.04, then manually reset your system proxy settings and launch ss-win client to verify? Thx.

**Comment by gonejack** [comment]
I am on 4.04, and I find the bug since 4.02 (maybe), but didn't post an issue at that time, hoping the bug would just disappear by next update, after updated to the 4.04, the bug still there, so I decide to tell the author.

**Comment by wongsyrone** [comment]
It will restore your settings after Enable System Proxy is unchecked, check the content of user-wininet.json

**Comment by chenshaoju** [comment]
Hello,I tested on my Windows 10 x64 OS,This issue can't replicate.
Please check your security software,If have some function call "Register Protect" or "Proxy Protect".

![2017-06-06](https://cloud.githubusercontent.com/assets/515763/26811353/d7a7bf94-4aa3-11e7-87df-dca89a6fb203.png)

**Comment by chenshaoju** [comment]
Update:
Please right click your shadowsocks.exe,click Properties,If you can see a checkbox name "Unlock",Select it , click Apply,And try again.

World of Warcraft Installer for example:
![2017-06-06 2](https://cloud.githubusercontent.com/assets/515763/26812032/e5d1a554-4aa7-11e7-804d-11a8bef167a3.png)

**Comment by gonejack** [comment]
@chenshaoju there are no security software or antivirus installed, and there are no suck "locked" check box.

@wongsyrone here is the user-wininet.json

```
{
  "UserSettingsRecorded": true,
  "Flags": "5",
  "ProxyServer": "127.0.0.1:1080",
  "BypassList": "<local>;localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*",
  "PacUrl": "http://127.0.0.1:1080/pac?t=20170603000330971"
}
```

by the way, switching between PAC and global is working right.

**Comment by gonejack** [comment]
I try to find out the latest version which working right, but after downgrade to 3.4.3 and upgrade through all update versions to 4.04, the issue just disappears, interesting.

**Comment by chenshaoju** [comment]
Odd 😕
