### ISSUE TITLE
移植到 UWP 平台的可行性探讨

### ISSUE THREAD

**Issue by bdbai** [shadowsocks/shadowsocks-windows#1177]
1. 基于原生 UWP VPN API
之前 @Noisyfox 在 #862 表示微软没有把文档放出来。事实上 [MSDN 文档](https://docs.microsoft.com/zh-cn/uwp/api/windows.networking.vpn)已经有了，只是描述不够清晰，也没有例子。按照前人在 iOS 上的做法，我大概有了一点点思路，但目前并没有着手实现。欢迎一起探讨。
2. [桌面到通用 Windows 平台 (UWP) 桥](https://docs.microsoft.com/zh-cn/windows/uwp/porting/desktop-to-uwp-root)
如果完全抛弃移动版用户，用这种方法也许可以少走些弯路，不过要牺牲掉一些 Win32 特性。

利益相关： Lumia 640 用户

**Comment by pexcn** [comment]
Lumia 640 (Windows Phone 10) 用户 + 1

**Comment by zhcm** [comment]
+1

**Comment by BestOwl** [comment]
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/ffe2645d-7a58-4241-8f2e-e9d1334771f1/uwphow-to-application-the-vpn-api-for-a-uwp-application?forum=wpdevelop

>> Our engineering team are working on publishing the VPN plug-in sample in MSDN

**Comment by bdbai** [comment]
@BestOwl I'm wondering if their engineering team are really working on it, or maybe we are deserted.

**Comment by Noisyfox** [comment]
@bdbai I was thinking about the same question.

**Comment by tommyxu97** [comment]
Surface Pro 4 User  +1

**Comment by florianmonfort** [comment]
I sent them a message on Twitter. Waiting to hear back.

**Comment by florianmonfort** [comment]
All my UWP apps are useless. 有很多的APP不可以用：
- Facebook
- Twitter
- Instagram
- SoundCloud
- Messenger
。。。。

**Comment by celeron533** [comment]
@florianmonfort have you tried Proxifier as a workaround?
https://www.proxifier.com/

**Comment by florianmonfort** [comment]
I believe Shadowsocks client already uses Proxifier? Every time something goes wrong with my server I can see a Proxifier error in my browser, so I'm not sure why you're suggesting to use it?

By the way, some Microsoft guy's response on Twitter: 

![image](https://user-images.githubusercontent.com/1446429/27938485-da42be56-62f0-11e7-8dad-ff2c620dce06.png)

**Comment by florianmonfort** [comment]
@celeron533 I just looked at Proxifier's download page:

![image](https://user-images.githubusercontent.com/1446429/27938518-0a24fcba-62f1-11e7-80cd-2a8a4d0ef880.png)


It clearly states for downloads for Windows 10*: _Windows Desktop applications only_

**Comment by celeron533** [comment]
Hi @florianmonfort , sorry I haven't tried it on my personal Win10 environment.

> Windows 10*: Windows Desktop applications only

IMO, perhaps it only means the Proxifier application itself is winform/mfc based not UWP but still could be used for redirecting other UWP Apps' network usage (unconfirmed, just my personal assumption)

**Comment by celeron533** [comment]
Nop,  shadowsocks-windows uses Privoxy to adapt HTTP proxy to SOCKS5 protocol. Because not all the applications support socks5 proxy.

>I believe Shadowsocks client already uses Proxifier? Every time something goes wrong with my server I can see a Proxifier error in my browser, so I'm not sure why you're suggesting to use it?

**Comment by JamesMackerel** [comment]
也有这个想法，跑来官方的repo想找有没有能够移植的代码，就看到了这个issue。

其实如果要是移植到UWP的话，最好还是支持MOBILE。因为这样意义就更加大了，否则其实如果已经有一个稳定的经典windows客户端，要去重新造一个轮子好像也没什么意义。

现在问题就是官方的文档描述不是很清晰，没有给相关的例程。

其实我觉得这些问题都不大，问题是到底能不能有一个sslocal稳定的在后台运行，不会被杀掉或者挂起，这是最重要的。

**Comment by JamesMackerel** [comment]
另外，请问一下从哪里能看到这个项目的基本架构……我刚刚看了两小时都没想出怎么把ss的部分抽出来。

**Comment by Noisyfox** [comment]
是我肯定从头写，不会基于现在的win版开发uwp版。

**Comment by JamesMackerel** [comment]
被源码虐了那么久之后我也是这么觉得的。感觉跟ui的耦合度太高了……

Noisyfox <notifications@github.com>于2017年7月9日 周日02:36写道：

**Comment by wongsyrone** [comment]
从头写没问题，加密和随机数那部分别随便改就行了

**Comment by florianmonfort** [comment]
I personally don't care about mobile, just care if Shadowsocks can support UWP apps, is this going to happen? It's just more and more apps that will be unusable with time...

@celeron533 not sure I fully understand the translations of this thread!

**Comment by JamesMackerel** [comment]
@florianmonfort 
We are actually discussing the possibility of making a UWP shadowsocks. 
IMO, if we do it recently and do not support windows mobile, it's not much a meaningful work, since legacy application runs well and supports many functions at the time.

**Comment by JamesMackerel** [comment]
https://github.com/Microsoft/Windows-universal-samples/issues/699#event-1159114418

I asked sample from Microsoft, but they refused. I think we may contact directly to the support team.

**Comment by florianmonfort** [comment]
@JamesMackerel have you done so yet? Or are you waiting for someone to do it?

The legacy client supports a lot of features yes, but doesn't support UWP apps, and more and more apps are going to UWP including the most important ones... I'm so annoyed that I can't use my UWP apps right now

**Comment by JamesMackerel** [comment]
@florianmonfort 

Nope, it's only an idea at the time.
For UWP apps, I saw [an article at Stackoverflow](https://stackoverflow.com/questions/42411148/setting-proxy-for-httpclient-in-uwp) says UWP apps would find proxy from Edge/IE automatically. In fact, I have tried to use Edge with this client and it works fine, only by using PAC mode, but haven't tried others.

If we are to develop a UWP client, we must get same sample rather than those doc from Microsoft. However, I will try, but I don't count on it very much.

**Comment by florianmonfort** [comment]
@JamesMackerel ok... So you are waiting to conclude on it once you have made a test?

**Comment by itsuki-hayashi** [comment]
> For UWP apps, I saw an article at Stackoverflow says UWP apps would find proxy from Edge/IE 

@JamesMackerel that is a feature of HttpClient class, not every UWP application use it, and some use custom TCP/UDP protocol which definitely not using HttpClient.

UWP VPN API is the only way to proxify the whole system without the need to develop a custom network driver.

I hope M$ could release a sample code soon.

**Comment by itsuki-hayashi** [comment]
@celeron533

> IMO, perhaps it only means the Proxifier application itself is winform/mfc based not UWP but still could
> be used for redirecting other UWP Apps' network usage (unconfirmed, just my personal assumption)

Wrong. UI of the application does not matter. Proxifier uses `Winsock Layered Service Provider` to proxify applications, which is deprecated as of Windows 8, hence all Metro/UWP applications will simply bypass it, this is done by design.

Desktop application can use `Windows Filtering Platform` to proxify Metro/UWP applications, it is a new API   meant to replace `Layered Service Provider`. However it runs as a network driver and require digital signature, which is far too expensive for a open source project.($223/yr for a code signing certificate from DigiCert, Symantec's will be more expensive).

UWP VPN API is the only proxifier API available for free at Windows platform.

**Comment by JamesMackerel** [comment]
So just use Apple and Android device and let's give up the UWP.

Edsger Lin <notifications@github.com>于2017年8月3日 周四14:07写道：

**Comment by wongsyrone** [comment]
>  let's give up the UWP

Agreed. That's why M$ sucks.

**Comment by bdbai** [comment]
We are here to solve it, not to escape.

**Comment by JamesMackerel** [comment]
We solve when there is a solution.

包布丁 <notifications@github.com>于2017年8月3日 周四15:01写道：

**Comment by dongqiceo** [comment]
UWP的话，会登陆Windows store吗

**Comment by Noisyfox** [comment]
Only if you could get the **SPECIAL PERMISSION** from M$.
Otherwise side-loading is the only option (if we could ever create an UWP VPN app).

**Comment by JamesMackerel** [comment]
@Noisyfox 
It doesn't matter side-loading is the only option or something else that make users difficult to use.
Before we side-load it, we have to develop it first, but we won't be able to do so before M$ release some samples.

**Comment by Noisyfox** [comment]
@JamesMackerel Exactly.

**Comment by bdbai** [comment]
I am currently working on it and trying to find a solution if possiblle.
For those who are interested in it or experienced in network programming, please join my Telegram channel @YtFlowChannel and Telegram group @YtFlow . I will keep updating them with latest progress ASAP.
However the solution still remains unknown.

**Comment by florianmonfort** [comment]
@bdbai do you have a repo we can look at? I think that's the best way to check how you're doing for sure. I would be interested in helping UI wise, I'm a Product Manager so I can manage just fine with Adobe XD and trying to make something nice 😄

**Comment by bdbai** [comment]
@florianmonfort Thanks for your kindly help. :)
However my workspace for this project is in a mess, which means it isn't suitable to push on GitHub at least for now. I will share some code snippet with you in the Telegram channel.

**Comment by florianmonfort** [comment]
@bdbai just joined the group!

**Comment by bdbai** [comment]
Here is a C++/CX wrapper like tun2socks. I think a working sample is coming soon. 

https://github.com/YtFlow/Wintun2socks

**Comment by bdbai** [comment]
So far we have come to the reasonable conclusion that it is absolutely **possible** to adapt Shadowsocks on UWP using UWP VPN Plugin Platform.

![resfromgoogle](https://user-images.githubusercontent.com/5270106/29722071-0af1535a-89f2-11e7-8be8-02cf5b8a34d3.PNG)

For more details, feel free to ask here or in this Telegram group @YtFlow .

**Comment by koolwiki** [comment]
How are things going ? @bdbai

**Comment by bdbai** [comment]
@hbxntsxw Thanks for your kindly attention! At the moment I am working on cryptography libraries and addressing issues related to lwip.

**Comment by realLiangshiwei** [comment]
How are things going ? What can I do for you? @bdbai

**Comment by florianmonfort** [comment]
Would be great to see this arrived!

**Comment by bdbai** [comment]
Several days ago, [YtFlowTunnel](https://github.com/YtFlow/YtFlowTunnel) was published in [YtFlow](https://github.com/YtFlow). This repo, together with [Wintun2socks](https://github.com/YtFlow/Wintun2socks), is intended to inspire those interested in it. 

Actually anyone can make a UWP VPN app out of these repos with a little effort although it would be too unstable to handle daily usage.

**Comment by CaiMiao** [comment]
还有可能面世么，纯WP环境要爬墙头都大了

**Comment by chenshaoju** [comment]
@CaiMiao 请阅读：https://github.com/shadowsocks/shadowsocks-windows/issues/897

**Comment by BestOwl** [comment]
UWP的版本做出来也不太可能上架的，这样Desktop Bridge就没有意义了。 UWP版本主要还是考虑Mobile和Xbox等非PC平台

**Comment by OpportunityLiu** [comment]
@BestOwl 不上架的话XBOX也没法用吧，不就只剩半死不活的Mobile了

**Comment by WenqiangXie** [comment]
从App Service提供的API来看，现有的不太方便做成一个一直在后台运行的任务，只有几个有限的触发条件。Desktop Bridge的话，可以降低获取难度，而且不需要对现有代码大改，配置一个新的编译项目就差不多了。而且在商店的话，也可以防止各种牛鬼蛇神乱改还不遵守协议，也方便获取和更新。

**Comment by OpportunityLiu** [comment]
@WenqiangXie  VPN有专有的API啊，不用App Service

**Comment by BestOwl** [comment]
I've implemented a Socks5 global proxy using BadVPN and UWP VPN platform, it will be very easy to adapt it to Shadowsock.
https://github.com/BestOwl/ShadowsocksUWP

**Comment by Noisyfox** [comment]
> I've implemented a Socks5 global proxy using BadVPN and UWP VPN platform, it will be very easy to adapt it to Shadowsock.
> https://github.com/BestOwl/ShadowsocksUWP

Nicely done!

**Comment by florianmonfort** [comment]
Does that mean we will get ShadhowSocks for UWP soon? @BestOwl would you be able to provide binaries to download from your repository page?

**Comment by BestOwl** [comment]
@florianmonfort Yes, I am working on it, I will publish it once it's ready.

**Comment by florianmonfort** [comment]
@BestOwl Any news? 😛

**Comment by BestOwl** [comment]
Got stucked with a strange bug, please join https://telegram.me/ytflow for further details.

**Comment by bdbai** [comment]
YtFlow is now able to handle system-wide connections using a fake IP pool. It also works fine on Mobile platform. See https://t.me/YtFlowChannel/73

Cc shadowsocks/shadowsocks-windows#862

**Comment by bdbai** [comment]
Now that UWP VPN Platform is proven to work with Shadowsocks, wouldn't it be nicer to create a new repo for official Shadowsocks implementation and work on it?
After that this issue may be closed as well.

**Comment by 5ngs94jzqw** [comment]
I found two bugs of uwp vpn api and find the workaround of them in case someone need it:
https://github.com/ysc3839/UWPToyVpn/issues/1
https://github.com/ysc3839/UWPToyVpn/issues/2

**Comment by bdbai** [comment]
@5ngs94jzqw the problem you have mentioned cannot be reproduced using [YtFlowTunnel](https://github.com/YtFlow/YtFlowTunnel) . Can you provide more detailed clues?

**Comment by 5ngs94jzqw** [comment]
@bdbai 
Do you try connect to a public ip(like 32.xx.xx.xx)?
Do you try to test to watch a youtube video for 10 minutes and make sure the youtube video tcp connection is go over your vpn? Test with small ip packets and small number of ip packets is ok for me too.(some ip packets as big as 1390)

I can see your project is not connect to a public ip(like 32.xx.xx.xx) server from your source code. Maybe that is the reason. Big delay(like 200ms) between client and server may be the reason.

Another reason is my test windows 10 is not exact the same as yours.
This computer also have some bugs with https://reqrypt.org/windivert.html , and I have to add 3 version of windivert to solve all problems in all test windows 10 computers.

**Comment by ghost** [comment]
Maybe we can add YtFlow to shadowsocks organization. @bdbai

**Comment by bdbai** [comment]
@studentmain Is there an official plan to support Shadowsocks on UWP? YtFlow contains a couple of different protocols other than Shadowsocks. We might need a Shadowsocks-only variant, where support for Windows Mobile device family could be dropped and [shadowsocks/Shadowsocks-Net](https://github.com/shadowsocks/Shadowsocks-Net/) could be used. See also shadowsocks/Shadowsocks-Net#6 .

**Comment by ghost** [comment]
> Is there an official plan to support Shadowsocks on UWP?

Not yet. Shadowsocks-Net is build for next major release of shadowsocks-windows.

> We might need a Shadowsocks-only variant

Drop feature is much easier than add feature😄, we're going to drop Windows 7, 32bit x86 and stream cipher too.

**Comment by ghost** [comment]
Transfer issue to Shadowsocks-Net
