### ISSUE TITLE
The network speed of shadowsocks v4.0.4 is lower than shadowsocks 2.5.2

### ISSUE THREAD

**Issue by szwifi** [shadowsocks/shadowsocks-windows#1180]
My network environment is : SS client -- kcptun client --kcptun server -- SS server, VPS solution.
When I used shadowsocks v2.5.2 windows client , youtube 1080P video can be played smoothly, but I changed shadowsocks v4.0.4  windows client, the youtube 1080P can't be played smoothly, the network speed dropped a lot. My shadowsocks server version is V2.8.2 (centos).

Who can help me ? Many thanks !

**Comment by wongsyrone** [comment]
then use shadowsocks v2.5.2 windows client
