### ISSUE TITLE
Shadowsock Error  无法打开使用

### ISSUE THREAD

**Issue by ClausClaus** [shadowsocks/shadowsocks-windows#1181]
![tim 20170608085404](https://user-images.githubusercontent.com/21154310/26907707-14231f10-4c28-11e7-8d2c-abfe4a6503a2.png)
请问谁有遇到过这个问题吗？昨晚win10电脑系统自己更新了，今天打开电脑就这样无法使用，有哪位大佬知道怎么回事的，请帮下忙，谢谢！！！

**Comment by wongsyrone** [comment]
你这是SSR的

**Comment by ClausClaus** [comment]
我要怎么解决这个问题呢！

**Comment by celeron533** [comment]
@ClausClaus 请去 https://github.com/breakwa11/shadowsocks-rss/issues 提问
