### ISSUE TITLE
4.0.4版本非预期错误

### ISSUE THREAD

**Issue by zhstoo** [shadowsocks/shadowsocks-windows#1182]
![1](https://user-images.githubusercontent.com/29277996/26929194-54bb2f14-4c8b-11e7-804c-7110fa10ce41.png)

如上图所示，启动就弹出这个框，之前都是可以用的

**Comment by celeron533** [comment]
看上去和 #1178 有点像啊

**Comment by celeron533** [comment]
请关闭SS，删除同文件夹下的`user-wininet.json`后，重试运行

**Comment by zhstoo** [comment]
已解决

**Comment by zslqhua** [comment]
搭車問下：我ss；ssr都設置為開機啟動，然後，就有端口佔用錯誤提示！於是我把一個本地端口設置成1080,另一個設置成1081，就兩個都可以分別使用了！可是下次開機，又會報錯相同問題，然後再把端口重新設置一下就又可以使用，有沒有什麼辦法一次性解決問題？

**Comment by jeopsh** [comment]
@zslqhua 虽然我也不清楚，但是建议你重新提交一个 Issue。
