### ISSUE TITLE
关闭代理的情况下所有流量都会走代理服务器

### ISSUE THREAD

**Issue by welkinbai** [shadowsocks/shadowsocks-windows#1183]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4
4.0.1版本也会出现，我升级到4.0.4并没解决

### Environment(Operating system, .NET Framework, etc)
win8.1
.NET 4.6.1

### Steps you have tried
关闭启用系统代理，打开日志，发现所有的流量都走的代理服务器。能打开所有墙外网站，ip也是代理服务器的
开启系统代理，在PAC模式下，反而是正确的，百度等地址都没有走代理

### What did you expect to see?
关闭 启用系统代理，小飞机图标变灰后，代理不应该生效

### What did you see instead?
关闭 启用该系统代理，小飞机图标变灰后，全局流量都走了代理服务器

### Config and error log in detail (with all sensitive info masked)
我没有配置正向代理设置
PAC文件是同步的GFWList
其他配置都没有动过

**Comment by welkinbai** [comment]
重新安装了一个纯净的版本，配置好服务器地址，其他配置全部默认，问题依旧

**Comment by celeron533** [comment]
关闭ss后，进入IE手动清空代理服务器设置

**Comment by chenshaoju** [comment]
你的操作系统是Windows 10，并且更新到创作者更新了吗？
https://github.com/shadowsocks/shadowsocks-windows/issues/1170

**Comment by welkinbai** [comment]
手动清理Internet选项里的代理服务器设置，并重装4.0.4版本后，问题消失了，谢谢

**Comment by pexcn** [comment]
既然解决了，怎么不 close 掉这个 issue?

**Comment by dsonwy** [comment]
我也在弄ss的系统代理配置，请问怎么查看流量是否走的代理服务器呢？@welkinbai
