### ISSUE TITLE
Is it possible to make shadowsocks-windows work with .net framework 4.6.1?

### ISSUE THREAD

**Issue by hatogit** [shadowsocks/shadowsocks-windows#1187]
First of all, thanks for the great job.
After upgrading my personal shadowsocks server to 3.0.6, I realized I had to upgrade to the latest  version of windows client to fully utilize the new features of it. But recent versions of shadowsocks-windows only works with .net framework 4.6.2 while on my laptop the latest version I can use is 4.6.1 and I can't change that since it's company property. Is it possible to loosen this requirement a little bit to let it work with version 4.6.1?

**Comment by celeron533** [comment]
Clone the source code, modify or remove the startup .net version checker, then compile your own version.

**Comment by zslqhua** [comment]
可憐我這個英盲！！！
