### ISSUE TITLE
Shadowsocks错误：未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by knightpanda** [shadowsocks/shadowsocks-windows#1188]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by knightpanda** [comment]
4.0.4版本的，打开后出现privoxy Error: Fatal error: can't bind to 127.0.0.1:8123(error number:10104)

**Comment by celeron533** [comment]
一般是因为本机的8123端口被其他程序占用
>4.0.4版本的，打开后出现privoxy Error: Fatal error: can't bind to 127.0.0.1:8123(error number:10104)

**Comment by Kulbear** [comment]
@celeron533 这个办法好像不管用- -

**Comment by sunkang960613** [comment]
请问是怎么解决这个问题的呢？我也遇到了

**Comment by chenshaoju** [comment]
@sunkang960613 能否将错误界面完整截图发上来？

**Comment by sunkang960613** [comment]
每次点击exe就会这样，即使是未配置任何数据的shadowsocks。
![default](https://user-images.githubusercontent.com/14357461/40779995-8f2d4d48-6509-11e8-856b-1263eb23a8ed.png)

@chenshaoju

**Comment by sunkang960613** [comment]
然而在一天之前 还能使用 没有任何问题。期间没有换过操作系统也没有安装其他杀毒软件。

**Comment by chenshaoju** [comment]
``` Error 10106 ``` 这个错误可能和TCP/IP协议或Winsock损坏有关。

请尝试以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一回车，三行执行完毕后重新启动计算机后再试。

**Comment by sunkang960613** [comment]
感谢！问题解决了！
@chenshaoju

**Comment by U0Axuan** [comment]
@chenshaoju 太感谢了

**Comment by readpan** [comment]
@chenshaoju 感谢

**Comment by Askwind** [comment]
哪里都能看到 @chenshaoju 兄
