### ISSUE TITLE
win7 X64 哪一个版本的我都打不开。

### ISSUE THREAD

**Issue by hijoke** [shadowsocks/shadowsocks-windows#1189]
# 打不开 # 
出现：
**Shadowsocks 已停止工作**
出现了一个问题，导致程序停止正常工作。请关闭该程序。
**→ 关闭程序**

**Comment by celeron533** [comment]
安装 .NET Framework 4.6.2

**Comment by chenshaoju** [comment]
.NET Framework 已经升级到了 4.7，请更新：
https://www.microsoft.com/zh-CN/download/details.aspx?id=55170
