### ISSUE TITLE
服务器-》从剪切板导入URL 失效

### ISSUE THREAD

**Issue by iniwo** [shadowsocks/shadowsocks-windows#1190]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
windows 7 sp1 x64

### Steps you have tried
every try

### What did you expect to see?
import a new server config

### What did you see instead?
manual

### Config and error log in detail (with all sensitive info masked)

**Comment by iniwo** [comment]
点击 服务器-》从剪切板导入URL 无反应。

**Comment by breakwa11** [comment]
URL是啥

**Comment by chenshaoju** [comment]
请确保你的URL以SS开头，并且格式类似于：
```
ss://YWVzLTI1Ni1jZmI6MTIzNDU2Nzg5QDEyNy4wLjAuMToxMjM0NQ==#TEST
```
如果你是从你的SS服务商获得的信息，请与你的SS服务商取得联系。
