### ISSUE TITLE
win7下ss v4.0.4双击没反应

### ISSUE THREAD

**Issue by mrdulin** [shadowsocks/shadowsocks-windows#1191]
### Version(release version or AppVeyor link)

ss 4.0.4

### Environment(Operating system, .NET Framework, etc)

win7

双击运行,没有任何错误提示,但是任务栏也没有出现小飞机.

**Comment by mrdulin** [comment]
回退到ss v2.3.1正常了

**Comment by chenshaoju** [comment]
请更新 .NET Framework https://www.microsoft.com/zh-CN/download/details.aspx?id=55170
