### ISSUE TITLE
Unable to set system proxy.

### ISSUE THREAD

**Issue by EAirPeter** [shadowsocks/shadowsocks-windows#1193]
### Version(release version or AppVeyor link)
4.0.4  

### Environment(Operating system, .NET Framework, etc)
Windows 10 version 1703 (OS Build 15063.296)  

### Steps you have tried
Run shadowsocks and try to enable system proxy.  
Set the IE proxy manually.  

### What did you expect to see?
Get my system proxy set to localhost:1080.  

### What did you see instead?
When using shadowsocks, the log keeps showing `Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 12178 (null)`.  
Then I have tried to set manually in `Internet Options-LAN settings`. But when I pressed the OK button, nothing happened.

### Config and error log in detail (with all sensitive info masked)
```
[2017-06-18 23:35:45] Shadowsocks started
[2017-06-18 23:35:45] Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 12178 (null)

   at Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   at Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
```

### Additional Information
I have reviewed the code in sysproxy.  
It seems that [this line](https://github.com/shadowsocks/sysproxy/blob/master/sysproxy/main.c#L186) sets lasterror to 12178.  
It may be a bug in Windows or WinINet.  
What I have described is excatly the same as #1125.  
Please fix this or describe another way to set system proxy.

**Comment by wongsyrone** [comment]
> ERROR_WINHTTP_AUTO_PROXY_SERVICE_ERROR
12178
Returned by WinHttpGetProxyForUrl when a proxy for the specified URL cannot be located.

We are not using any function from winhttp.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa383770(v=vs.85).aspx

**Comment by Sinclair-Liu** [comment]
I have met the same problem. But I think there is something wrong with the system because I could not visit google using greenvpn as well. 已经用不了好多天了，今天用其他的vpn发现也不行。。。不确定windows自带的那种设置的vpn行不行。

**Comment by zslqhua** [comment]
牆又漲高了！

**Comment by chenshaoju** [comment]
@Sinclair-Liu GreenVPN已经挂了。

![screenshot](https://user-images.githubusercontent.com/515763/27442474-e33e9f1a-57a2-11e7-9c42-3cc9258b7eeb.png)

PS:请注意，Shadowsocks-windows和GreenVPN没有关系。

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718
