### ISSUE TITLE
Shadowsocks 启动时抛出异常

### ISSUE THREAD

**Issue by yeyaowei** [shadowsocks/shadowsocks-windows#1195]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Windows7 .NET Framework 4.6.2

### Steps you have tried
双击启动

### What did you expect to see?
正常启动

### What did you see instead?
一个Error Messgebox

### Config and error log in detail (with all sensitive info masked)
![1](https://user-images.githubusercontent.com/8546588/27371821-d4b17116-5694-11e7-9009-33cb5f26ed99.png)

如果不理那个信息框的话，其实是可以正常运行的 但是点了确定程序就会退出。。。

**Comment by chenshaoju** [comment]
请检查你的的系统是否存在某些浏览器代理保护软件，某些安全软件可能会阻止第三方软件设置浏览器代理。

**Comment by yeyaowei** [comment]
然而并没有，不过还是谢谢！实际上自己状况似乎与 #1185 #1178 类似，删除 user-winnet.json 后已经正常了，而这项错误是在我电脑未正常从休眠状态恢复后重启发生的，可能有点关系吧。
