### ISSUE TITLE
random crash 

### ISSUE THREAD

**Issue by Roland0511** [shadowsocks/shadowsocks-windows#1197]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
shadowsocks 3.4.3

### Environment(Operating system, .NET Framework, etc)
windows 7
.net framework 4.6.2

### Steps you have tried
do nothing,just use it normally.and get random crash.

### What did you expect to see?
running normally

### What did you see instead?
show a non-UI Error window,and then crash
![image](https://user-images.githubusercontent.com/588050/27522077-da08b812-5a55-11e7-8cff-d87542867241.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
Please upgrade to 4.0.4
https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by celeron533** [comment]
And disable statistics in:
right click menu -> servers -> statistics config
