### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by RyuAsuka** [shadowsocks/shadowsocks-windows#1199]
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.TypeInitializationException: “MS.Win32.Penimc.UnsafeNativeMethods”的类型初始值设定项引发异常。 ---> System.Runtime.InteropServices.COMException: 没有注册类 (异常来自 HRESULT:0x80040154 (REGDB_E_CLASSNOTREG))

   在 MS.Win32.Penimc.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)

   在 MS.Win32.Penimc.UnsafeNativeMethods.CreatePimcManager()

   在 MS.Win32.Penimc.UnsafeNativeMethods..cctor()

   --- 内部异常堆栈跟踪的结尾 ---

   在 MS.Win32.Penimc.UnsafeNativeMethods.CreateResetEvent(IntPtr& handle)

   在 System.Windows.Input.PenThreadWorker..ctor()

   在 System.Windows.Input.PenThreadPool.GetPenThreadForPenContextHelper(PenContext penContext)

   在 System.Windows.Input.PenThreadPool.GetPenThreadForPenContext(PenContext penContext)

   在 System.Windows.Input.StylusWisp.WispTabletDeviceCollection.UpdateTabletsImpl()

   在 System.Windows.Input.StylusWisp.WispTabletDeviceCollection.UpdateTablets()

   在 System.Windows.Input.StylusWisp.WispTabletDeviceCollection..ctor()

   在 System.Windows.Input.StylusWisp.WispLogic.get_WispTabletDevices()

   在 System.Windows.Input.StylusWisp.WispLogic.RegisterHwndForInput(InputManager inputManager, PresentationSource inputSource)

   在 System.Windows.Interop.HwndStylusInputProvider..ctor(HwndSource source)

   在 System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)

   在 GlobalHotKey.HotKeyManager..ctor()

   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)

   在 Shadowsocks.Program.Main()

**Comment by celeron533** [comment]
类似于 #1194

**Comment by RyuAsuka** [comment]
非常感谢，重新安装.NET Framework 4.7以后问题解决
