### ISSUE TITLE
MAC10.12编译问题

### ISSUE THREAD

**Issue by ilovebamboo** [shadowsocks/shadowsocks-windows#1201]
![qq20170628-124022](https://user-images.githubusercontent.com/6214084/27620935-c325f38e-5bff-11e7-9221-95f8878e9efa.png)

**Comment by ilovebamboo** [comment]
请问这个问题怎么解决啊，求指教啊？

**Comment by chenshaoju** [comment]
这是Windows的客户端，即使你用了VS，也无法编译出Mac上用的客户端。请移步：
https://github.com/shadowsocks/ShadowsocksX-NG/releases

**Comment by ilovebamboo** [comment]
好的，我只是想试试看，切换系统比较麻烦。谢谢回复

**Comment by celeron533** [comment]
目前跨平台的VisualStudio还有很多兼容问题。所以后搞了.Net Core，不过这东西还在完善中。

**Comment by huming2207** [comment]
一年半前做过一点微小的尝试，目前存在的问题我认为主要是对Privoxy、libsscrypto和Sysproxy这些非.NET的库／程序的依赖，以及某些Windows系统特定的代码（注册表编辑等），把这些东西阉割掉就能编译了，但是很麻烦。

此外GUI部分，虽然Mono支持Winform，但Mac下Winform非常恶心，很丑，很卡，不支持HiDPI，用户体验很差，还得重做个Xamarin.Mac的GUI。所以如果能做个针对Mac的C#客户端应该是可行的吧，但是意义不大，以后闲的无聊的时候可以试试。

**Comment by celeron533** [comment]
>所以如果能做个针对Mac的C#客户端应该是可行的吧

可以做个内核，UI都做成web，就像lantern那样
