### ISSUE TITLE
请问客户端加入tfo了么

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-windows#1202]
如题，请问TCP FAST OPEN什么时候加入，还是已经加入了？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by celeron533** [comment]
#1045 欢迎贡献代码

**Comment by wongsyrone** [comment]
TFO is currently under debugging.
With this feature, The current forward proxy must be removed from codebase, since you send requests to proxy and proxy make connections to the remote server. It's meaningless to enable TFO for

> client <-> the proxy server
