### ISSUE TITLE
修改用户规则后不生效

### ISSUE THREAD

**Issue by xLabel** [shadowsocks/shadowsocks-windows#1203]
场景一：
1.修改用户规则
2.发现本地pac文件中已成功set入最新的自定义规则
3.此时chrome进程还在，未关闭
4.刷新页面，依旧没走进代理
5.重启SS客户端，再刷新页面，顺便进入代理

场景二：
1.修改用户规则
2.发现本地pac文件中已成功set入最新的自定义规则
3.此时chrome进程还在，手动关闭所有chrome
4.SS客户端"不"重启
5.重新打开chrome，刷新页面，顺利进入代理

推测：
1.是否因为TCP复用导致更新规则后，无法立刻生效？
2.本地pac已更新，但没load进程内存中使用？

**Comment by celeron533** [comment]
在chrome里安装代理切换工具switchyomega，还能获得更多高级切换控制

**Comment by celeron533** [comment]
可能和 #1332 有关
