### ISSUE TITLE
目前4.0.4版本支持simple-obfs吗？

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-windows#1204]
如果支持，请问如何配置？麻烦给个样例。谢谢！

**Comment by celeron533** [comment]
不支持

**Comment by suikatomoki** [comment]
如果你是win10 直接用linux子系统好了 啥问题都解决了
![qq 20170701210256](https://user-images.githubusercontent.com/10336224/27762251-0cb7e3f6-5ea1-11e7-817e-946e5e50a911.png)

**Comment by Suwmlee** [comment]
参考 #1013 
插件的问题还是用插件的方式来解决。

**Comment by celeron533** [comment]
4.0.6 可通过SIP003 插件系统来启用obfs
