### ISSUE TITLE
非预期错误

### ISSUE THREAD

**Issue by badmintonsong** [shadowsocks/shadowsocks-windows#1205]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
win10

### Config and error log in detail (with all sensitive info masked)
![image](https://user-images.githubusercontent.com/16514873/27717779-faa1e13a-5d79-11e7-951f-f91e3339486e.png)

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718
