### ISSUE TITLE
建议支持一下GFW.Press协议！

### ISSUE THREAD

**Issue by vskllee** [shadowsocks/shadowsocks-windows#1206]
建议支持一下GFW.Press协议！

**Comment by wongsyrone** [comment]
我打赌你一定在说笑

**Comment by vskllee** [comment]
什么说笑？你是说有支持这个协议功能？

**Comment by vskllee** [comment]
我手机上用的Shadowrocket这个软件，里面有GFW.press这个选项，本来以为电脑版的Shadowsocks也会有，结果看却没有这个选项！而GFW.press是免费的，只不过它的软件是个全局模式，很不爽。

**Comment by chenshaoju** [comment]
Shadowrocket并非Shadowsocks for Windows开发的，由于Shadowsocks是开源的，任何人可以加入或修改功能。

作为Shadowsocks for Windows，目前仍然只支持Shadowsocks协议。

GFW.Press和Shadowsocks是两个东西，举个例子，你不可能要求iOS去兼容Android把？😅

**Comment by vskllee** [comment]
这样啊

**Comment by pexcn** [comment]
我也打赌你一定在说笑

**Comment by Maskeva** [comment]
GFW.Press也是开源项目   你可以自己改呀

**Comment by celeron533** [comment]
@vskllee 可能对这个项目有点误解
1. shadowsocks和shadowrocket是完全不同的东西。就如同迅雷和比特精灵。
2. shadowsocks是原始的协议，把自己的本分做好，一般在路线图上不会去考虑兼容其他协议。就好比emule只做edonkey（ed2k）协议。迅雷作为一个集成下载工具，兼容thunder, ed2k, torrent等各种协议。但是注意，迅雷不会改进和开发第三方协议的。
3. 你提到GFW.Press 只有全局代理没有条件代理等，就算有feature request 这个请求应该和GFW.Press提
