### ISSUE TITLE
多IP服务器，请问支不支持，AIP连接就使用Aip代理，B连接用用Bip代理呢?

### ISSUE THREAD

**Issue by wanggeming** [shadowsocks/shadowsocks-windows#1208]
多IP服务器，请问支不支持，AIP连接就使用Aip代理，B连接用用Bip代理呢?

**Comment by chenshaoju** [comment]
这种情况建议以便携模式运行SS，并且复制多份放在不同的目录，设定不同的端口。

如果你是用的是Chrome，可以使用switchyomega设置代理路径。
