### ISSUE TITLE
shadowsocks do not work on win10 creator(1703)

### ISSUE THREAD

**Issue by ShaohuiYuan** [shadowsocks/shadowsocks-windows#1209]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
seens all Version

### Environment(Operating system, .NET Framework, etc)
win10 creator 1703

### Steps you have tried
none

### What did you expect to see?
how to solve？

### What did you see instead?

[shadowsocks.txt](https://github.com/shadowsocks/shadowsocks-windows/files/1117179/shadowsocks.txt)

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
使用其他客户端比如android等是否能连接？

**Comment by ShaohuiYuan** [comment]
Android的可以的，另外我发现可以在edge下可以代理，chrome下无法代理。以前在1607用的好好的。全新安装1703就不行了。

**Comment by ShaohuiYuan** [comment]
@celeron533 ss服务器没问题的，Android的正常使用，可以代理edge，但是不能代理chrome。我觉得可能是哪里设置有问题，但是系统是全新安装的。不知道哪里出现问题。重装过系统，发现 只有在 全新安装win 10 1703的时候出现。其他版本或者升级到1703的都不会出现。

**Comment by celeron533** [comment]
#1125 #1127 都有人反映这个问题，但没法重现

**Comment by ShaohuiYuan** [comment]
@celeron533 在我这可以重现，就是有点麻烦，全新安装win10 1703就行了，不知道用虚拟机可不可以重现，不然的话可以试试 。从低版本win10升级到1703的就正常使用。只有全新安装win10 1703才会。希望能找到问题所在吧。不然我只好退回1607版的win10了   感谢开发者了

**Comment by likesoap** [comment]
@ShaohuiYuan 我是upgrade上去1703 的，也出现了……网站只能load到title （firefox的tab显示 google那些）之后就停住了。

**Comment by JonasGao** [comment]
我觉得对于使用 Chrome 加载失败的情况下，可以查看 devtools 里面的 network 一栏。可以把哪里的连接信息发出来。说不定能对分析问题有一定帮助

**Comment by celeron533** [comment]
可以启用详细日志后再看看有什么详细输出

**Comment by howiezhao** [comment]
如果你是拨号上网的话，把“宽带连接”四个字改成英文然后重启应该就可以了，我之前遇到过类似的问题

**Comment by qifei** [comment]
自从更新了4.0.4，一直无法连接。
手机上的客户端可以用。

**Comment by ShaohuiYuan** [comment]
@celeron533 解决了  用的@howiezhao 的方法

**Comment by celeron533** [comment]
全新安装的win10 会有“宽带连接”？
以前是有issue提到过网络名中文的情况下有无法连接的问题

**Comment by liyuhang1997** [comment]
@howiezhao 早点告诉我就好了，不过我现在用 Wifi，4.0.4也能正常用了。

**Comment by alodan** [comment]
@howiezhao 感谢！！！！终于解决了！！！QAQ

**Comment by Arckman** [comment]
我也是同样的问题，同样是 @howiezhao 的解决办法解决了，感谢！
我的现象如下，仅供参考：
我有pc和笔记本两台设备，笔记本出差到处跑，shadowsocks从没出过问题，pc是家用（宽带连接）。
pc是从win7升级到win10的，shadowsocks也正常使用没啥问题，直到今年。
edge和shadowsocks通信没有问题，在shadowsocks的日志里能看到连接请求及流量。
chrome的任何请求在shadowsocks日志里都没有。

**Comment by flyingsheepbin** [comment]
@howiezhao 解决了，谢谢

**Comment by AnyWAT** [comment]
> 全新安装的win10 会有“宽带连接”？

貌似叫”以太网“
