### ISSUE TITLE
Hotkeys are not working

### ISSUE THREAD

**Issue by milewski** [shadowsocks/shadowsocks-windows#1211]
The Hotkeys are not quite working after a system reboot.... to regain access i have to open the hotkeys menu and click in "Reg All" every time i reboot my system... 

Info:
Shadowsocks 4.0.4 running on windows 101

**Comment by celeron533** [comment]
Reason:
https://github.com/shadowsocks/shadowsocks-windows/pull/708#issuecomment-247746140

**Comment by milewski** [comment]
Still.. that doesnt apply to me...

1 - i only have 1 server
2 - the key binding i'm using is unique.. nothing else is using it elsewhere 
3 - i am only running one instance of Shadowsocks

**Comment by celeron533** [comment]
pull request #1130 would like to register hotkey on startup
