### ISSUE TITLE
版本4.04, non-UI error

### ISSUE THREAD

**Issue by ktzj** [shadowsocks/shadowsocks-windows#1212]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.04

### Environment(Operating system, .NET Framework, etc)
Windows 10 15063.447

### Steps you have tried
启动shadowsocks，即报错然后退出。4.02没有问题。之前4.04也没事，用着用着突然这样了

### Config and error log in detail (with all sensitive info masked)
<img width="1286" alt="default" src="https://user-images.githubusercontent.com/13914118/27768647-e0218b94-5f4a-11e7-9b2a-6251456a9884.png">

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718
