### ISSUE TITLE
an exception occur while open shadowsocks-windows3.3.3 

### ISSUE THREAD

**Issue by Akame-moe** [shadowsocks/shadowsocks-windows#1213]
### Version 
3.3.3

### Environment(Operating system, .NET Framework, etc)
windows Ultimate 7.  / .NET framework 4.5

### Steps you have tried
double click Shadowsocks.exe

### What did you expect to see?
normal.

### What did you see instead?
![error log](https://ooo.0o0.ooo/2017/07/03/5959ea9abddb3.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
Plz install .Net framework 4.6.2 and launch shadowsocks 4.0.4
