### ISSUE TITLE
Add xchacha20poly1305 please

### ISSUE THREAD

**Issue by netroby** [shadowsocks/shadowsocks-windows#1215]
The shadowsocks-libev and shadowsocks-android already support xchacha20poly1305, please add support for shadowsocks-windows. thanks

**Comment by Galaxy0419** [comment]
问过，不会增加，因为还没被规范，而且性能方面讲，chacha20-ietf-poly1305也不错。

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by celeron533** [comment]
#1725
