### ISSUE TITLE
提个建议-关于添加网址

### ISSUE THREAD

**Issue by xdeng** [shadowsocks/shadowsocks-windows#1217]
能不能在右键菜单加个 添加走代理网址 选项啊。
每次遇到访问不了的网站要么就开全局，要么手动去找安装目录修改pac文件，很不方便。

**Comment by celeron533** [comment]
如果安装的是基于chrome的浏览器，可以安装switchyomega
https://github.com/FelisCatus/SwitchyOmega/releases
