### ISSUE TITLE
System.NullReferenceException: 未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by Hstb1230** [shadowsocks/shadowsocks-windows#1218]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Windows10 (1703) ，net4.7以及net3.5(4.0应该装了)

### Steps you have tried
开机，等待ss自动启动

### What did you expect to see?
```
System.NullReferenceException: 未将对象引用设置到对象的实例。

   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)

   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)

   在 Shadowsocks.Controller.ShadowsocksController.Reload()

   在 Shadowsocks.Program.Main()
```

**Comment by Hstb1230** [comment]
刚刚发现这个有人提了=。=

**Comment by Hstb1230** [comment]
还有一个在前几天出现：
![图片](https://img.1sls.cn/Pic/png/6619041ed7ab6bcf8060fb121ed46f80)
也是4.0.4，但是是在运行中出现的，大概复现了两三次。

**Comment by celeron533** [comment]
应该是可靠性统计有线程bug，建议关闭统计功能
>还有一个在前几天出现：
