### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by LLoyou00** [shadowsocks/shadowsocks-windows#1219]
![image](https://user-images.githubusercontent.com/9455777/27990286-15e39798-6484-11e7-8e21-c413f2ca9825.png)

**Comment by imotai** [comment]
我也遇到这样的问题，求解答

**Comment by JamesMackerel** [comment]
@LLoyou00  @imotai 
在报BUG的时候，请详细描述BUG的触发过程，是否能够稳定重现，以及软件运行的环境。

**Comment by LLoyou00** [comment]
是 user-wininet.json statistics-config.json  这两个配置文件中的其中一个导致。。。但是我来的配置文件已经删了。。 不好意思。

出现上述问题后我重新下载了最新版本，可以正常运行。然后我把原来的三个配置文件拷贝进去覆盖了新的配置文件，再次打开又出现上述错误。删掉了上述连个配置文件又可以正常运行。

**Comment by celeron533** [comment]
User-wininet.json格式变化引起，删除即可
