### ISSUE TITLE
Can't open tumblr

### ISSUE THREAD

**Issue by lisi2016** [shadowsocks/shadowsocks-windows#1223]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
windows 10+shadowscocks 4.04

### Environment(Operating system, .NET Framework, etc)
更新了自己PAC文件，打不开网站

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
如果使用全局代理能打开的话，说明协议本身没有问题
