### ISSUE TITLE
Error - UnautnorizedAccessException 

### ISSUE THREAD

**Issue by newtype09c** [shadowsocks/shadowsocks-windows#1224]
Exception Type: UnautnorizedAccessException Stack Trace: 在 System.IO._Error.WinlOError(lnt32 errorCode, String maybeFullPath) S System.IO.FileStream.lnit(String path, FileMode mode, FileAccess access, Int32 rights. Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY-ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) S System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) S Shadowsocks.Model.Configuration.Save(Configuration config) 汪 Shadowsocks.Controller.ShadowsocksController.Toggle£nable(B oolean enabled) 汪 Shadowsocks.View.MenuViewController.£nableltem_Click(Object sender, EventArgs e) S System.Windows.Forms.Menultem.OnClickCEventArgs e) S System.Windows.Forms.Menultem.MenultemOata.ExecuteO S System.Windows.Forms.Command.InvokeO 在 System.Windows.Forms.CommandDispatchlD(lnt32 id) 在 System.Windows.Forms.Notifylcon.WndProc(Message&msg)
在 System.Windows.Forms.Notifylcon.NotifylconNativeWindow.Wnd Proc(Message& m) 在 System.Windows.Forms.NativeWindow.Callback(lntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)

**Comment by newtype09c** [comment]
I can open the Shadowsocks，but when I click something in its menu，the error occurred.

**Comment by celeron533** [comment]
ss运行的文件夹没有足够的读写权限。
很有可能你把ss主程序放在了program files文件夹。比较暴力的解决办法是给ss所在的文件夹加上个everyone可读写的权限。如果你没看懂这个描述。。。把整个ss移到其他文件夹也可以



那个“汪”是什么鬼

**Comment by newtype09c** [comment]
哇，GitHub居然有国人，吓我

**Comment by newtype09c** [comment]
我都没注意到，我用的图转文软件

**Comment by newtype09c** [comment]
确定权限没问题。。。

**Comment by chenshaoju** [comment]
你把Shadowsocks放到 D:\SS\ 目录看看？如果没有这个目录，新建一个目录。

**Comment by tangshiba** [comment]
兄弟, github很多国人啊= =

**Comment by newtype09c** [comment]
2333

**Comment by newtype09c** [comment]
突然想起来其实我没有D盘。。。。HDD用的是ext4......Windows读不出来

**Comment by newtype09c** [comment]
![ba t5v_sv_ fz1eeag rs](https://user-images.githubusercontent.com/30034493/28194292-da9b48fc-6875-11e7-8909-66d85a71bbc9.png)

**Comment by newtype09c** [comment]
所以，，，GG

**Comment by newtype09c** [comment]
随便换了个目录。。。

**Comment by newtype09c** [comment]
![image](https://user-images.githubusercontent.com/30034493/28194319-172cf6bc-6876-11e7-8d12-a1354c1066cb.png)

**Comment by newtype09c** [comment]
感觉和兼容性没多大关系啊
我就更新了下4.0.4就不行了，换回原来3.5.5也不行了

**Comment by newtype09c** [comment]
原来3.5.5一直用的好好的

**Comment by newtype09c** [comment]
我很可能要滚回Ubuntu了。。。。

**Comment by celeron533** [comment]
从报错信息来看，是gui-config文件无法写入。

还有，你可以把要说的话放在一个回复里，别弄得像版聊一样。。。。。。

**Comment by newtype09c** [comment]
无法写入的话，，，我看看权限，，，，

**Comment by newtype09c** [comment]
所以，把gui-config拿走了，让他重新启动自己创建了一个，，，就好了。。。

**Comment by newtype09c** [comment]
谢谢各位啦
