### ISSUE TITLE
正向代理能添加用户名密码吗?

### ISSUE THREAD

**Issue by tangshiba** [shadowsocks/shadowsocks-windows#1225]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Win7 x64

### Steps you have tried
配置正向代理地址和端口

### What did you expect to see?
能够配置用户名密码

### What did you see instead?
不能正常连接代理

### Config and error log in detail (with all sensitive info masked)
[2017-07-10 15:13:23] Socket connected to proxy 192.168.16.189:8080
[2017-07-10 15:13:23] System.Exception: 代理请求失败
   在 Shadowsocks.Proxy.HttpProxy.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by tangshiba** [comment]
看到	前几天rickryo已经提交代码了，不知道什么时候能发布呢？
感谢@rickryo。

**Comment by celeron533** [comment]
着急的话你可以先自己在那个分支上编译

**Comment by wongsyrone** [comment]
不知道有没有人对Windows上的Tcp Fast Open感兴趣，这个和前置代理不能共存

**Comment by tangshiba** [comment]
好不容易安装好vs自己编译了, 运行以后报错 (用户名密码都对过没问题啊) = =

[2017-07-11 14:18:16] connect to github.com:443
[2017-07-11 14:18:16] Socket connected to proxy 192.168.16.189:8080
[2017-07-11 14:18:16] System.Exception: 代理请求失败
   在 Shadowsocks.Proxy.HttpProxy.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-07-11 14:18:16] System.Exception: 代理请求失败
   在 Shadowsocks.Proxy.HttpProxy.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by tangshiba** [comment]
自己先编译了rickryo的分支使用了.

**Comment by celeron533** [comment]
#1214

**Comment by celeron533** [comment]
>不知道有没有人对Windows上的Tcp Fast Open感兴趣，这个和前置代理不能共存

这是个挺矛盾的情况。
1. Tcp Fast Open 仅作用于直连，如果中间有任何代理服务器，会出问题。
2. “中间的任何代理服务器”可以是用户或者系统管理员在当前的计算机上手动/自动设置，也可以是部署在网关附近的透明代理。终端用户有时候难以觉察到透明代理的存在。当然，告知用户打开TFO是“进阶选项，可能会导致连接问题”也是OK的。
3. 也不排除某些审计网关不认可TFO的情况。
