### ISSUE TITLE
360安全卫士拦截shadowsocksIE连接设置，有解决方案吗？

### ISSUE THREAD

**Issue by jinaviva** [shadowsocks/shadowsocks-windows#1226]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
shadowsocks4.0.4

### Environment(Operating system, .NET Framework, etc)
windows7 专业版  .NET 4.6.2
360安全卫士11.4.0

### Config and error log in detail (with all sensitive info masked)
![image](https://user-images.githubusercontent.com/17328342/28009168-04ac88fe-658d-11e7-8902-ac5a6db93c6c.png)

**Comment by tangshiba** [comment]
竟然用360.....

**Comment by jinaviva** [comment]
毕竟360的装机量还是巨大的。

**Comment by jinaviva** [comment]
我觉得shadowsocks-windows须要认真审视这个问题，不然大家都会觉得不好用，其实是360在搞鬼。目前pc要么安装360卫士，要么安装了QQ医生这种，几乎没有裸奔的。

**Comment by celeron533** [comment]
V2ex有人测试过360以及其他国产安全卫士会向真理部回报你的ss服务器地址，害死了一个服务器IP以及旗下所有的用户。所以翻墙和360你还是二选一吧。需要认真审视这个问题并做出决定的用户自己。
另外世界上不是只有360，还有大把的杀毒软件，防护软件可用。

**Comment by lixingcong** [comment]
本项目维护者一定说“我绝对不背这个锅”

**Comment by wongsyrone** [comment]
可以选择自己改嘛，信哪个自己决断

**Comment by gitzhuoer** [comment]
把360卸了呗。  
Windows Defender就够了。清理垃圾用“磁盘清理”程序，防止开机自启用任务管理器，卸载软件用控制面板，当然最好的维护方法是不要装那些国产流氓软件。

**Comment by w0wbin** [comment]
用360的人基本也告别翻墙了吧

**Comment by pexcn** [comment]
卸载360

**Comment by mosquito367** [comment]
用360还翻墙，怎么想的呢？

**Comment by celeron533** [comment]
如果你坚持360和ss共用，可以添加白名单

**Comment by zslqhua** [comment]
是啊！用360,還翻SM q… 豈止是不開學！簡直就是不科學！！！

**Comment by WLZLCX** [comment]
卸载360！！！

**Comment by zslqhua** [comment]
大仙啊～,你用360,就不要科學愛國了好吧！
