### ISSUE TITLE
pac url 能否去掉权限控制（http://127.0.0.1:1080/pac?t=20170711110237963&secret=xxxxx  ）

### ISSUE THREAD

**Issue by snowwalk** [shadowsocks/shadowsocks-windows#1228]
我用的傲游浏览器，pac 的url一直写的是http://127.0.0.1:1080/pac?t=20170711110237963，最近一段时间升级后自动切换总是不起作用，后来发现url中多了一个secret 参数。现在是不是在用这个参数做访问控制？而且每次还是变化的，现在每次启动shadowsocks后，要么只能使用全局模式，要么手动重新设置一下pac 的url才能达到自动切换的目的

**Comment by celeron533** [comment]
出现这个参数只是因为你在ss客户端里勾选了“保护本地PAC”
参考 #966

**Comment by snowwalk** [comment]
不好意思，对这个选项理解错了，以为是保护文件啥的
