### ISSUE TITLE
提个建议，希望能把各个增强功能以插件形式添加

### ISSUE THREAD

**Issue by ohsorry** [shadowsocks/shadowsocks-windows#1230]
主体提供一个核心功能的精简版。其他像热键、负载均衡、局域网连接、自动速度测试和检查、自动采集等等都以插件形式开发，功能可以diy。我想多了吗？

**Comment by celeron533** [comment]
其实很早就有人提过这个设想，不过实施起来动静较大。。。

**Comment by Hope6537** [comment]
何必呢,这么搞下来ROI太低了

**Comment by wongsyrone** [comment]
放到项目中的都应该是和本意紧密相关的功能，其他的不应该添加。

**Comment by ohsorry** [comment]
嗯，动静是不小。可能是我感觉代码组织的有点不习惯。现在是mvc？
像这种工具性客户端程序我一般就按功能拆分代码，简单易读。也不是什么用例巨多的管理系统搞个DDD之类的架构。有的功能一个静态类就够了，以后可能会改动的功能可以抽象一下。用最少代码完成所有功能。UI可以命令行或win32。UI上只是跟UI和交互相关的很少的代码。

总之最后的感觉是各个独立的模块和类各司其职，松散地组织在一起，协作完成整体功能。读起来也容易些。

我可能会这样组织代码：
infrastructure
	...
core
	socks
	encryption
	server类定义
	不是核心可以挪出去
	..
thirdparty
	sysproxy
	QRCode
	...
ui
	wpf或winform
	I18n

定时任务可以用Quartz

总之，这件事干的漂亮！

**Comment by ohsorry** [comment]
读了下除了view部分的代码，这代码写的真是酸爽啊，基本上好像和面向对象没有什么关系。⊙﹏⊙‖∣
贡献两个可以我认为可以重构的点：
sysproxy可以应该改成导出类库吧？interop调用；socks转http(s)也有封装好的c#代码，代码很少，可以不用priovxy。那就不用再开进程啦~。

**Comment by celeron533** [comment]
> 读了下除了view部分的代码，这代码写的真是酸爽

毕竟这个最早是 clowwindy 自己写着玩的工具，后来加上的功能越来越多。。。
