### ISSUE TITLE
4.0.4 错误

### ISSUE THREAD

**Issue by ser0r1** [shadowsocks/shadowsocks-windows#1231]
[2017-07-11 19:13:35] [E] System.IO.FileNotFoundException: 未能加载文件或程序集“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”或它的某一个依赖项。系统找不到指定的文件。
文件名:“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”
   在 GlobalHotKey.HotKeyManager..ctor()
   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   在 Shadowsocks.Program.Main()

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

**Comment by wongsyrone** [comment]
完全卸载 .NET 并重新安装

**Comment by celeron533** [comment]
至少还有两个人反应这个问题而且也是.net损坏。。。
