### ISSUE TITLE
---

### ISSUE THREAD

**Issue by tefiszx** [shadowsocks/shadowsocks-windows#1239]
---

**Comment by celeron533** [comment]
猜测部分app的请求网址没有被pac收录？

**Comment by wongsyrone** [comment]
你可以用Fiddler或者Charles抓包看看

**Comment by tefiszx** [comment]
@celeron533 这个可能性可以排除，同样是FB，网页web端正常，APP超时。

**Comment by tefiszx** [comment]
@wongsyrone 谢谢提供解决问题的思路。另外我想确认一下：ss-win监听的1080端口在没有privoxy的情况下是否可以代理http协议的流量，如果ss-win的监听端口自身就能代理http协议，那ss-win自带的privoxy是起什么作用的？

**Comment by breakwa11** [comment]
手机多数APP根本就不管系统代理设置

**Comment by tefiszx** [comment]
@breakwa11 如果把代理设置手动模式，填入固定ip和端口号，手机的app就能用了。不过代理不能智能分流了，走全局了。

**Comment by celeron533** [comment]
如果是android系统的话，可以安装shadowsocks-android。苹果系统我不太清楚，国内的app store渠道都下架了

**Comment by huangfeihong** [comment]
我也出现这种情况了，想尝试用局域网共享代理的方式统一管理pac，但目前按教程设置的话没能正常上网，但我的正好相反，youtube客户端可以获取信息但没法获取视频，浏览器网页没法打开，不知道是不是浏览器或者系统设置的问题。
![img_0931](https://user-images.githubusercontent.com/15089154/28653094-38a29ac0-72be-11e7-86dd-70463019f836.PNG)
![img_0928](https://user-images.githubusercontent.com/15089154/28653097-38af8528-72be-11e7-8e2e-a8187b72555f.PNG)
![img_0929](https://user-images.githubusercontent.com/15089154/28653096-38ab18c6-72be-11e7-87b6-7adf2e9c4d6c.PNG)
![img_0930](https://user-images.githubusercontent.com/15089154/28653095-38aa3564-72be-11e7-88f9-04e0ab61f5a5.PNG)

**Comment by tefiszx** [comment]
@huangfeihong 你把pac文件里的端口换成privoxy的监听端口试试看？ss的默认监听端口1080不能直接代理http的。

**Comment by chenshaoju** [comment]
你用的是GFWList的PAC还是你自己写的PAC？

打开 Shadowsocks.exe 所在目录，找到 pac.txt 搜索 127.0.0.1 ，将其替换成你的计算机的局域网的IP看看？

**Comment by dkp1993** [comment]
我也发现了这个问题，有解决方案么
