### ISSUE TITLE
听别的地方讨论，SSR比SS安全不容易被GFW发现？

### ISSUE THREAD

**Issue by zjplab** [shadowsocks/shadowsocks-windows#1243]
两个有什么区别？

**Comment by DanielEcho** [comment]
别的地方是指哪儿，请具体给出哪儿安全的原因及代码。

**Comment by pexcn** [comment]
凭什么呢？

**Comment by OOnnnOO** [comment]
因为 ssr fork from ss？

**Comment by LiangkeZhong** [comment]
应该是混淆的原因吧

**Comment by Knight-ZXW** [comment]
SSR windows没有找到下载地址，。。

**Comment by WLZLCX** [comment]
http://tieba.baidu.com/p/5233119045
贴吧里有人认为是SSR开发团队打的广告，因为中国信息不透明 愚民又多，容易相信谣言

**Comment by chenshaoju** [comment]
截至目前，下列加密方法是强烈推荐的，如果你的服务商支持，请尽快使用。
![image](https://user-images.githubusercontent.com/515763/28421381-a00815e0-6d97-11e7-9ecc-48ef5f50498d.png)
http://shadowsocks.org/en/spec/AEAD-Ciphers.html

下列加密方法已经不推荐了，可能会被探测到：
![image](https://user-images.githubusercontent.com/515763/28421454-d3246848-6d97-11e7-9bb3-5e5878ece022.png)

下列加密方法存在已知的弱点，不要使用，详见：https://github.com/shadowsocks/shadowsocks-org/issues/36
![image](https://user-images.githubusercontent.com/515763/28421490-eca90f76-6d97-11e7-89a0-f013cc082ccc.png)
http://shadowsocks.org/en/spec/Stream-Ciphers.html

**Comment by networkthroughput** [comment]
ssr群内也有人中枪

![1](https://user-images.githubusercontent.com/30362800/28488319-ac7d6c60-6ed9-11e7-9ad5-5dcd61f865ee.png)

**Comment by WarmBlackClouds** [comment]
惊

**Comment by wxlzmt** [comment]
可惜 ios端的app `FirstWingy`不支持 `aes-xxx-gcm` , 要不然我就用这种加密方式了.

@chenshaoju

**Comment by chenshaoju** [comment]
@wxlzmt 你好，我没有iPhone，关于iOS的支持，请与该软件开发人员联系。

**Comment by fxbird** [comment]
> EDIT：
> 经人提醒，我发现有一点没说清楚，这是我的失误：AEAD是为了防止对于SS服务器的主动探测（类似于： http://www.solidot.org/story?sid=27059 ，当然这是针对SSH的），不是为了防止流量分析，因为原始协议和OTA协议都有漏洞，所以目前已经不推荐原始协议，并且移除了OTA。
> 
> 截至目前，下列加密方法是强烈推荐的，如果你的服务商支持，请尽快使用。
> ![image](https://user-images.githubusercontent.com/515763/28421381-a00815e0-6d97-11e7-9ecc-48ef5f50498d.png)
> http://shadowsocks.org/en/spec/AEAD-Ciphers.html
> 
> 下列加密方法已经不推荐了，可能会被探测到：
> ![image](https://user-images.githubusercontent.com/515763/28421454-d3246848-6d97-11e7-9bb3-5e5878ece022.png)
> 
> 下列加密方法存在已知的弱点，不要使用，详见：[shadowsocks/shadowsocks-org#36](https://github.com/shadowsocks/shadowsocks-org/issues/36)
> ![image](https://user-images.githubusercontent.com/515763/28421490-eca90f76-6d97-11e7-89a0-f013cc082ccc.png)
> http://shadowsocks.org/en/spec/Stream-Ciphers.html

那你推荐哪个加密方式？

**Comment by iceBear67** [comment]
chacha20
