### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by zongsheng-zhao** [shadowsocks/shadowsocks-windows#1244]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Windows 10

### Steps you have tried
open the shadowsock client, and it crashes

### What did you see instead?
an error dialog with message:

非预期错误，Shadowsocks将退出。请提交此错误到https://github.com/shadowsocks/shadowsocks-windows/issues
System.NullReferenceException:  未将对象引用设置到对象的实例。
在Shadowsocks.Util.SystemProxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
在Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
在Shadowsocks.Controller.ShadowsocksController.Reload()
在Shadowsocks.Program.Main()

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
参考 https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718
