### ISSUE TITLE
建议添加数字签名

### ISSUE THREAD

**Issue by zhuochenming** [shadowsocks/shadowsocks-windows#1245]
有可能的话给软件添加数字签名吧，国内环境不好，一不小心就下载到你懂的那种软件

**Comment by celeron533** [comment]
下载页面有hash值，请自行校对

**Comment by jinliming2** [comment]
数字签名意义不大。
* 自签的证书：
1. 没办法证明安全性
2. 公开公钥的方式：与直接给hash差不多了，唯一的优点就是公钥公开的话，以后只认这一个公钥的就行，而每次给hash可能哪天网站被中间人/假DNS，然后给你一个假页面，软件/hash也是假的了。
* 公共证书：
1. 绝大多数收费，而且很贵
2. 很多人电脑上都信任着国内几大证书机构，完全可以凭借他们进行伪造代签（这种事不是没发生过，详情去看CNNIC）

**Comment by WLZLCX** [comment]
楼主出钱

**Comment by celeron533** [comment]
#321

**Comment by zhuochenming** [comment]
exe文件原来套路这么深😋😋😋学习了 下载这些东西看来还是要找到来源好
