### ISSUE TITLE
推荐一款软件：SSTap，支持SS和SSR

### ISSUE THREAD

**Issue by 6ge** [shadowsocks/shadowsocks-windows#1246]
![default](https://user-images.githubusercontent.com/25245796/28296945-bc23641a-6b9d-11e7-80a5-9178cf8bf1fc.PNG)
官网：https://www.sockscap64.com/sstap

**Comment by breakwa11** [comment]
这里是提问和解决问题的地方，不是你打广告的地方

**Comment by MaiKuraki** [comment]
这种人真的是烦

**Comment by 6ge** [comment]
@breakwa11 我是发现真的好用。用SS或SSR翻墙，cmd ping命令ping不通Google服务器，用SSTap反而能ping通Google服务器。

**Comment by 6ge** [comment]
SSTap会添加一个网络适配器，你们没发现吗？

**Comment by bugsos** [comment]
我 也觉得很好用。不知道楼上的人 激动啥，

**Comment by drliu1202** [comment]
@6ge 的意思可能是希望ShadowSocks也实现操作系统全局代理。
