### ISSUE TITLE
non-UI Error:非预期错误，未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by lifive5** [shadowsocks/shadowsocks-windows#1247]
非预期错误，shadowsocks将退出。
System.NullReferenceException:未将对象引用设置到对象的实例。
在Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxy Server, String pac URL).
怎么解决？

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718
