### ISSUE TITLE
when i start

### ISSUE THREAD

**Issue by iwantsupenpower** [shadowsocks/shadowsocks-windows#1249]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)

win7sp1  .NET Framework4.6.2
### Config and error log in detail (with all sensitive info masked)
---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.NullReferenceException: 未将对象引用设置到对象的实例。

   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)

   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)

   在 Shadowsocks.Controller.ShadowsocksController.Reload()

   在 Shadowsocks.Program.Main()
---------------------------
确定   
---------------------------

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718
