### ISSUE TITLE
Rumor says SS is being blocked.

### ISSUE THREAD

**Issue by likesoap** [shadowsocks/shadowsocks-windows#1251]
![true](https://user-images.githubusercontent.com/29620923/28396348-571b5424-6d2d-11e7-8ebb-7e0af25dabea.jpg)

There are rumors about SS being blocked. Could someone help clarify?

--Likesoap

**Comment by himejisyana** [comment]
能精准识别 SS？

2017年7月20日 上午9:26，"likesoap" <notifications@github.com<mailto:notifications@github.com>>写道：

[true]<https://user-images.githubusercontent.com/29620923/28396348-571b5424-6d2d-11e7-8ebb-7e0af25dabea.jpg>

There are rumors about SS being blocked. Could someone help clarify?

--Likesoap

**Comment by RyanWestinLiu** [comment]
同问

**Comment by mpco** [comment]
ss 有多种加密方法，应该搞清楚被识别的具体是什么
感觉可能是3.0之前的老方法，以及一些不推荐使用的

**Comment by Sophia82** [comment]
我说一种可能性哈。想象一下这个场景：前一分钟你开着qq跟别人吹牛。接下来你开了全局代理，然后qq从瑞典的ip冒了个头。喝茶的时候你报告领导，我莫名其妙穿越了。你说JC蜀黍们会不会信？
那么再引申一下……就算你不开全局，但某输入法出于好奇，看到你有个代理，就试着联系一下某个地址。然后这次你叛逃到日本了……抓住了不是？别不承认，你输入什么都有记录呢……
如果怀着更大的恶意猜测的话，我曾经貌似好像大概可能听说过路由器里面的手脚……如果发送接收的加密信息超过某个阈值的话呢？这些对大数据来说算不算个事呢？
而且你要连接的服务器被证实是ss服务器或者是ss服务器的主要供应商所拥有的ip的话……
这……很难吗？要不是JCSS们太懒的话……

**Comment by lamwood** [comment]
![image](https://user-images.githubusercontent.com/15353684/28403157-07f7c6d8-6d56-11e7-9e6a-40a222517ed9.png)
我看到这个，是不是意味着SS被探测出来了？

**Comment by RyanWestinLiu** [comment]
@lamwood 可怕，这是什么？

**Comment by himejisyana** [comment]
这俩个加密方法报废了?

**Comment by zyf2008Neptune** [comment]
@lamwood 你可以把那些信息填进红框中，看看能不能放得下。

**Comment by shikkoku** [comment]
就是破娃在电报上发的公告通知，但我认为其消息的可靠度存疑。
