### ISSUE TITLE
审查力度逐渐加大，希望加入obfs的插件支持

### ISSUE THREAD

**Issue by mpco** [shadowsocks/shadowsocks-windows#1252]
另外，对于一些不推荐使用的加密方法，或许可以加上“不安全” 的备注或警告

**Comment by akarinet** [comment]
如果是Windows 10 的话，系统里有 Ubuntu 的 bash 可以用，在上面开个ss-local就好。

**Comment by mpco** [comment]
要考虑到用户的广泛性，并不是每个人都用 Win10 或者会 子系统的 Bash。
以开发者的一些努力，降低大部分使用者的门槛，尤其对于这种软件来说，还是很值得的。

**Comment by ThunderEX** [comment]
@akarinet 不明白……ss-server在windows下，ss-local在wsl下，然后手动设PAC？求详解~

**Comment by eric21** [comment]
同求更新,增加OBFS插件支持

**Comment by tianchengye0719** [comment]
跪求OBFS插件啊

**Comment by Suwmlee** [comment]
自己用cygwin编译一个win下的[simple-obfs](https://github.com/shadowsocks/simple-obfs)就可以了
使用方法 [参考](https://github.com/shadowsocks/simple-obfs#standalone-mode)

**Comment by liaobin** [comment]
[https://github.com/shadowsocks/shadowsocks-windows/pull/1298](url)

**Comment by celeron533** [comment]
4.0.6 SIP003
