### ISSUE TITLE
Failed to decode QR code （无法添加来自安卓端的节点）

### ISSUE THREAD

**Issue by ivill66** [shadowsocks/shadowsocks-windows#1253]
### Version(release version or AppVeyor link)

v4.0.4 (for Windows)
v4.1.8 (for Android)

### Environment(Operating system, .NET Framework, etc)
Windows 10 Enterprise Insider Preview 16241

### Steps you have tried
尝试最新版SS 及旧版SS 客户端for Windows

### What did you expect to see?
能够扫描并添加成功由SS Android客户端导出的节点二维码及文字地址形式的分享

### What did you see instead?
无法扫描或解析添加由SS for Android客户端导出的节点二维码及文字地址形式的分享

### Config and error log in detail (with all sensitive info masked)

请问如何解决这个问题？有人遇到同样情形吗？

**Comment by ivill66** [comment]
原来一直都用得好好的，直到前几个SS for Windows更新后，节点居然都丢失了，由于是之前朋友给的节点，无法找到网站上的二维码了，同样的节点我在安卓端上正常使用，但是由安卓端导出后发现，在Windows上无法导入，求教

**Comment by rebiu** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1240 这种?
