### ISSUE TITLE
Built in QRCode scanner are unable to detect multiple QRCode  

### ISSUE THREAD

**Issue by frankwei98** [shadowsocks/shadowsocks-windows#1254]
### My problem and question

I am a front end developer, I want my user to scan QRCode instead of typing info about server.

But it seems that Built in QRCode scanner are unable to detect multiple QRCode (URI is correct)
Single QRCode can be detected,but not multiple.
Is there any possibility to add a feature to detect multiple QRCode and add them once all to user's server list?

Thank you.

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Windows 10 Creator Update 
.Net 4.6.2

### Steps you have tried
10 times maybe

### What did you expect to see?
Built in QRCode Scanner can detect multiple shadowsocks uri in QRCode

### What did you see instead?
Result is 'No QRCode found'

### Config and error log in detail (with all sensitive info masked)
Not related

**Comment by celeron533** [comment]
Please use `ss://` instead of QR code. The windows client could handle multiple `ss:\\` items from clipboard

**Comment by frankwei98** [comment]
Sounds good, Thanks
