### ISSUE TITLE
Error when launching SS

### ISSUE THREAD

**Issue by sonyxu** [shadowsocks/shadowsocks-windows#1257]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)
![image](https://user-images.githubusercontent.com/25625821/28478391-bf789f28-6e8a-11e7-8745-d3d1722f86f0.png)

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718
