### ISSUE TITLE
勾了“允许来自局域网的链接”手机还是不能翻墙

### ISSUE THREAD

**Issue by Song-ZhiPeng** [shadowsocks/shadowsocks-windows#1258]
按照这里操作了：https://jingyan.baidu.com/article/1612d500a3dc8be20f1eee65.html
以前的版本都是可以的，从4个月前发现不能了，使用3.4.0的旧版本可以。

**Comment by pexcn** [comment]
取消 “保护本地PAC”

**Comment by Song-ZhiPeng** [comment]
取消了，还是不行。

**Comment by chenshaoju** [comment]
请检查操作系统自带的网络防火墙。

**Comment by Song-ZhiPeng** [comment]
![qq 20170722220800](https://user-images.githubusercontent.com/17376819/28491859-6e584af8-6f2a-11e7-8406-b389fe30cd28.png)
![qq 20170722220831](https://user-images.githubusercontent.com/17376819/28491860-6e9001f0-6f2a-11e7-9b05-aca2ac88ff26.png)
![qq 20170722220924](https://user-images.githubusercontent.com/17376819/28491861-6eec807e-6f2a-11e7-9301-6d1ef90dc4c3.png)
防火墙已重置并且再次弹出时点了确定，“保护本地PAC”也取消了。

**Comment by himejisyana** [comment]
要检查是不是防火墙问题直接把墙关掉不就好了

(p皿)凸

**Comment by Song-ZhiPeng** [comment]
![qq 20170722221508](https://user-images.githubusercontent.com/17376819/28491933-f8e5eaf8-6f2b-11e7-864e-7d03fac7bad8.png)
![img_0286](https://user-images.githubusercontent.com/17376819/28491934-fab34d76-6f2b-11e7-98a0-5d95fb280bd1.PNG)
Windows 10 Pro 官方正版，刚刚关闭防火墙试了下还是不行。

**Comment by celeron533** [comment]
iPhone的URL加上`http://`

**Comment by cnscorpions** [comment]
同样的问题
