### ISSUE TITLE
广州 长城宽带 一个星期了都无法上YOUTUBE和twitter   

### ISSUE THREAD

**Issue by vida-shamp** [shadowsocks/shadowsocks-windows#1259]
ip  61.164.152.128

twitter快断了一个月了，youtube也有一个多星期了，手机用客户端能链接上twitter，电脑不行。HOSTS是最新的，DNS是GOOGLE的。

**Comment by thelastlin** [comment]
长城？没救了，换运营商吧。

**Comment by vida-shamp** [comment]
突然间发现可以不用SS，不修改DNS就能登录youtube和维基，看youtube的直播720P不卡。

**Comment by lrinQVQ** [comment]
Are you ok? https://github.com/racaljk/hosts/issues/1319
