### ISSUE TITLE
北京联通校园客户端联网后Shadowsocks 4.0.4无法翻墙

### ISSUE THREAD

**Issue by cjzhang0115** [shadowsocks/shadowsocks-windows#1260]
客户端网址：[http://wo201.bbn.com.cn/userAction!loadClient.action](客户端网址)
用其它网络可以正常使用，使用北京联通校园客户端联网后不能使用，日志如下：
 [2017-07-23]20:32:38] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-07-23 20:32:38] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-07-23 20:33:37] 45.78.3.210:443 timed out
[2017-07-23 20:33:37] 45.78.3.210:443 timed out

**Comment by reversengineer** [comment]
Unicom in Kunming is giving me trouble. Speeds have been throttled down significantly. Once was getting 20Mbps, am now lucky to get 1Mbps.

**Comment by himejisyana** [comment]
我很好奇你们为啥喜欢把这些东西放到 issues 上面来😀

**Comment by celeron533** [comment]
#571
