### ISSUE TITLE
windows 4.6.2 版本客户端在win10专业版系统上发生非预期错误后退出

### ISSUE THREAD

**Issue by sinanchi** [shadowsocks/shadowsocks-windows#1261]
【ss客户端】
非预期错误，Shadowsocks将退出。请将此错误提交到https://github.com/shadowsocks/shadowsocks-windows/issues
System.UnauthorizedAccessExeption: 对路径“C:\Program Files\ss\ss_win_temp\shadowsocks.log”的访问被拒绝。
在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTED secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongpath, Boolean checkHost)
在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
在 System.IO.FileStream..ctor(String path, FileMode mode)
在 Shadowsocks.Controller.Logging.OpenLogfile()
在 Shadowsocks.Program.Main()

【事件查看器】
日志名称:          Application
来源:            Application Error
日期:            2017/7/24 12:27:01
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           Surface-LUCYLIU
描述:
错误应用程序名称: Shadowsocks.exe，版本: 4.0.2.0，时间戳: 0x591ea7e8
错误模块名称: KERNELBASE.dll，版本: 10.0.15063.483，时间戳: 0xc3955624
异常代码: 0xe0434352
错误偏移量: 0x000eb802
错误进程 ID: 0xdd4
错误应用程序启动时间: 0x01d3043461a05030
错误应用程序路径: C:\Program Files\ss\Shadowsocks.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: 75ac4c06-97e3-44f3-b5be-2cbc6b7a7ae5
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-07-24T04:27:01.299856600Z" />
    <EventRecordID>43954</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Surface-LUCYLIU</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Shadowsocks.exe</Data>
    <Data>4.0.2.0</Data>
    <Data>591ea7e8</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.15063.483</Data>
    <Data>c3955624</Data>
    <Data>e0434352</Data>
    <Data>000eb802</Data>
    <Data>dd4</Data>
    <Data>01d3043461a05030</Data>
    <Data>C:\Program Files\ss\Shadowsocks.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>75ac4c06-97e3-44f3-b5be-2cbc6b7a7ae5</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by chenshaoju** [comment]
请尝试将 shadowsocks 放到其他目录，比如 D:\SS\ 目录中，C:\Program Files\ 目录在没有管理员权限的目录下没有办法写入文件。

**Comment by sinanchi** [comment]
我在C盘下重建了个文件夹，把客户端放进去，果然解决了问题，谢谢chen桑；）。
（好奇怪，之前一直可以正常运行的）
