### ISSUE TITLE
PAC模式下偶尔会上不去网

### ISSUE THREAD

**Issue by Wahitler** [shadowsocks/shadowsocks-windows#1262]
最近一个月偶尔就上不去网了，非常确定不是网络线路的问题
状况是Pac模式下，大多数是好的，偶尔就是不用翻墙的网站打不开了，需要翻墙的网站还是可以打开
![qq 20170724101903](https://user-images.githubusercontent.com/12858618/28517296-84cf8694-7096-11e7-8540-7756619e709b.png)

![qq 20170724173028](https://user-images.githubusercontent.com/12858618/28517290-7fbdc3d2-7096-11e7-9038-44c23973ebbd.png)

然后看代理设置，启用与禁用系统设置，启用与禁用，系统的局域网设置始终打着对勾，都是【使用自动配置脚本】
![image](https://user-images.githubusercontent.com/12858618/28517344-a674de52-7096-11e7-8cef-5851189b5268.png)
![image](https://user-images.githubusercontent.com/12858618/28517455-02b48898-7097-11e7-86b7-19762c42a32b.png)

我切换到全局模式的话，不论是需要不需要的网站就都能上了

然后这个状态会执行几分钟，几分钟之后就恢复了自然，有两个系统都是这样，1个是win7 专业版，另一个是win10 2016 ltsb版，win10是在遇到win7有这情况，重新安装的另外一个系统

ss的服务器是版瓦工，debian，端口443，本地端口1080，加密方式rc4-md5

**Comment by chenshaoju** [comment]
你是否同时使用了其他VPN/SS类软件？看起来很像pac文件在一瞬间被替换了。

**Comment by Wahitler** [comment]
只使用用shadowsocks啊，没有别的vpn或者ss类软件

**Comment by chenshaoju** [comment]
请尝试以管理员权限启动命令提示符（ｃｍｄ）然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```

执行后重新启动懂计算机，并观察一段时间。

**Comment by Wahitler** [comment]
还是会偶尔出现这种情况，家里的电脑就不会出现着这种情况，但公司的经常会有
