### ISSUE TITLE
shadowsocks-windows打开提示错误

### ISSUE THREAD

**Issue by annata** [shadowsocks/shadowsocks-windows#1263]
非预期错误，Shadowsocks将推出。请提交此错误到https://github.com/shadowsocks/shadowsocks-windows/issues
System.NullReferenceException:未将对象引用设置到对象的实例。
在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable,Boolean global,String proxyServer,String pacURL)
在 Shadowsocks.Controller.SystemProxy.Update(Configuration config,Boolean forceDisable,PACServer pacSrv)
在  Shadowsocks.Controller.ShadowsocksController.Reload()
在 Shadowsocks.Program.Main()

**Comment by annata** [comment]
补充一下，在相同环境下4.0.2是正常的

**Comment by annata** [comment]
出错误的是最新的版本4.0.4

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718
