### ISSUE TITLE
搬瓦工自建的ss跟ssr不知道为啥连接不上……非要把别人的服务器也添加上才可以

### ISSUE THREAD

**Issue by woyouduohenni** [shadowsocks/shadowsocks-windows#1264]
我自建的ss跟ssr在搬瓦工上，但是自己电脑如果选择自己服务器的话不知道为啥连接不上，但是如果添加了其他的服务器（其他人提供的）但是我勾选连接的是自己的服务器就可以顺利fq，这是为啥啊……

**Comment by chenshaoju** [comment]
请检查你的服务器的防火墙（iptables等），以及ss的服务是否在运行。

**Comment by pexcn** [comment]
配置错了

**Comment by woyouduohenni** [comment]
ss服务在运行，配置直接是搬瓦工后台自建的而不是自己部署的，现在ss跟ssr都可以在kvm控制面板直接部署，ss服务在手机上可以顺利翻，但是电脑就是非得有其他的服务器才行，奇怪的是，勾选的是自己的服务器明明，没有其他服务器就不行，有其他服务器就行了……

**Comment by chenshaoju** [comment]
你用的是Shadowsocks还是ShadowsocksR的Windows客户端？

**Comment by woyouduohenni** [comment]
ssr的客户端

**Comment by chenshaoju** [comment]
@breakwa11

**Comment by lianggeng** [comment]
我用的也是搬瓦工自带的ss，ss最近两天能正常用，前十多天一直瘫痪没速度。今天换了SSR之后按照教程设置了还是用不了

具体恢复的操作方法楼主能说下吗

**Comment by lianggeng** [comment]
刚刚在官网服务端点了下Start就可以连上用了，但当时装完SSR之后一直是处于Running状态的阿

**Comment by woyouduohenni** [comment]
@lianggeng 果然running还是要点下start才行……谢谢!

@chenshaoju @pexcn 感谢！

**Comment by satywt** [comment]
@lianggeng 感谢！果然要点下start！

**Comment by sky0014** [comment]
感谢，点下start好了，这有点坑啊，搬瓦工的bug

**Comment by 408892334** [comment]
哈哈,果然running状态还得点一下start,我也解决了

**Comment by ZhaoJing2016** [comment]
thanks 果然点了一下 start，账号就能fq了
