### ISSUE TITLE
可以代理翻墙成功，可是为啥软件退出后就无法正常上网了

### ISSUE THREAD

**Issue by wubohuang** [shadowsocks/shadowsocks-windows#1265]
win10系统，代理了几个小时候，退出ss，发现无法上网了，报以下错误,重启电脑就可以了

无法显示此网页

错误代码： ERR_PROXY_CONNECTION_FAILED
代理服务器出现问题，或者地址有误。

**Comment by chenshaoju** [comment]
请检查IE浏览器的代理设置，包括Internet选项，连接中的拨号设置LAN局域网设置。

**Comment by osdu** [comment]
@chenshaoju ss 会记录原始代理信息，退出时会自动恢复系统代理设置到ss启动前的状态，若ss启动前代理设置不正确或者ss异常退出，会造成无法上网。

可在ss退出时强制禁用系统代理解决这个问题
https://github.com/osdu/shadowsocks-windows-for-anmpserver/commit/fb241a36bc0d7b1365b18de33f78d1a15359e72e

**Comment by chenshaoju** [comment]
这个问题好像已经有人在解决了，仍在讨论中：https://github.com/shadowsocks/shadowsocks-windows/pull/1192

**Comment by xiakai** [comment]
最新的版本退出后，TGP steam游戏平台都无法连接。开启时（未开系统代理）steam连接显示在国外，默认走代理？不太明白

**Comment by chenshaoju** [comment]
请看一下你的Shadowsocks是工作在PAC模式还是全局模式？

另外，请看一下IE的代理设置。

**Comment by R-U-Airil** [comment]
> WIN 10在网络设置里找到代理 然后把代理关掉就好了

你说的应该是internet里的LAN选项吧？我把使用代理去掉后可以正常用原来的网络上网，但是如果重新勾上，不启动ss，就无法正常上网，这是为什么？

**Comment by celeron533** [comment]
>你说的应该是internet里的LAN选项吧？我把使用代理去掉后可以正常用原来的网络上网，但是如果重新勾上，不启动ss，就无法正常上网，这是为什么？

Internet选项里指向了代理服务器，但实际上你的代理服务器没有启动，所有无法上网

**Comment by TheGroundhogDay** [comment]
这个问题已经有人反馈给微软了。 下次启动电脑的时候，还是会自动跳转到启用代理服务器。https://answers.microsoft.com/zh-hans/windows/forum/windows_10-networking/win10/f29a8a34-b696-4a76-b08c-b89b527a0358?messageId=a40a01ce-8c10-4974-9736-5cf6a25162d0
