### ISSUE TITLE
请求增加功能 - 修改全局代理时的no proxy list

### ISSUE THREAD

**Issue by ssquirrel** [shadowsocks/shadowsocks-windows#1266]
首先感谢下devs的辛苦！

我的请求如题，具体来说，每次ss win在启动全局代理的时候都会把localhost和一些局域网的地址写到no proxy那里，可不可以让用户修改no proxy rules呢？user rules好像只有是pac模式才有用的样子。我想用全局代理，但是win系统一有更新，会直接把流量全占满，每次都要自己加rules，比较麻烦，最好是有个txt可以整改，让后ss每次就读那个txt就好啦^_^

**Comment by chenshaoju** [comment]
如果是你的这种情况，建议使用PAC来代理你想要的网站。

**Comment by ssquirrel** [comment]
我用ss的时候99%的网站都要通过ss啊，跟pac模式正好相反。。。。

**Comment by chenshaoju** [comment]
这是一个相反的PAC，在列表中的网址不会通过代理，不在列表中的网址会通过代理。
请记得将 10800 修改为你的SS端口，手动添加网址的话结尾的单引号需要一个英文半角逗号，最后一个网址不需要加逗号。

https://gist.github.com/chenshaoju/84bce1eae2a7974f41430b199d37d532

**Comment by ssquirrel** [comment]
好吧，谢谢了
