### ISSUE TITLE
安装4.0.4提示必须先安装4.0.3，为什么没有4.0.3

### ISSUE THREAD

**Issue by womende1** [shadowsocks/shadowsocks-windows#1267]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
源码里没有这样的提示啊

**Comment by womende1** [comment]
![qq 20170727103152](https://user-images.githubusercontent.com/26131223/28651746-2cacc07c-72b6-11e7-85d7-6f4168e9aef7.png)

**Comment by womende1** [comment]
![image](https://user-images.githubusercontent.com/26131223/28651760-4b214f28-72b6-11e7-8e5c-898a8927efaf.png)
就是这个提示，大神帮忙看看

**Comment by pexcn** [comment]
请升级 .NET Framework 到最新.

**Comment by chenshaoju** [comment]
如果可能，请安装最新的 Microsoft .NET Framework 4.7 ：
https://www.microsoft.com/zh-CN/download/details.aspx?id=55170

**Comment by womende1** [comment]
![image](https://user-images.githubusercontent.com/26131223/28651881-1b233dd0-72b7-11e7-9a80-2eb32f97bd6b.png)
但是又出现了这个问题

**Comment by womende1** [comment]
帮忙给翻译一下

**Comment by chenshaoju** [comment]
你需要给你的Windows安装操作系统补丁，请进入控制面板，Windows安全，Windows Update打补丁。

**Comment by himejisyana** [comment]
@womende1 现在机翻这么厉害不知道去 百度/必应/Google 翻译吗?

(●’◡’●)

**Comment by celeron533** [comment]
@womende1 系统提示你安装.Net Framework
