### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by 1299495750** [shadowsocks/shadowsocks-windows#1268]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.04

### Environment(Operating system, .NET Framework, etc)
win7，.NET Framework, 4.6.2

### Steps you have tried
open .exe

### What did you see instead?
```
---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.NullReferenceException: Object reference not set to an instance of an object.

   at Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)

   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)

   at Shadowsocks.Controller.ShadowsocksController.Reload()

   at Shadowsocks.Program.Main()
---------------------------
确定   
---------------------------
```

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676
