### ISSUE TITLE
crash on windows 10 after KB4025342 and KB4025376

### ISSUE THREAD

**Issue by DanielYWoo** [shadowsocks/shadowsocks-windows#1269]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
tried both 4.0.2/4.0.4

### Environment(Operating system, .NET Framework, etc)
Windows 10 with KB4025342 and KB4025376

### Steps you have tried
Open ss, then it crashes

### Config and error log in detail (with all sensitive info masked)

[2017-07-27 20:53:31] [E] System.TypeInitializationException: “Shadowsocks.Controller.PrivoxyRunner”的类型初始值设定项引发异常。 ---> System.UnauthorizedAccessException: 对路径“D:\Tools\shadowsocks\ss_win_temp\ss_privoxy.exe”的访问被拒绝。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PrivoxyRunner..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Controller.PrivoxyRunner..ctor()
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main()
[2017-07-27 20:53:35] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-07-27 21:05:47] [E] System.TypeInitializationException: “Shadowsocks.Controller.PrivoxyRunner”的类型初始值设定项引发异常。 ---> System.UnauthorizedAccessException: 对路径“D:\Tools\shadowsocks\ss_win_temp\ss_privoxy.exe”的访问被拒绝。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PrivoxyRunner..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Controller.PrivoxyRunner..ctor()
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main()
[2017-07-27 21:05:51] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by wongsyrone** [comment]
没权限

**Comment by DanielYWoo** [comment]
nope， tried with admin

**Comment by chenshaoju** [comment]
KB4025376 is Adobe Flash Player Update,No effect.
I Installed KB4025342  too,but not have this issue.

Do you install some security software?

**Comment by DanielYWoo** [comment]
@chenshaoju thanks for reminding, it's avast!!! Avast kills ss_privoxy **silently**. Avast sucks. I am gonna switch to AVG.

**Comment by losvincent** [comment]
> @chenshaoju thanks for reminding, it's avast!!! Avast kills ss_privoxy **silently**. Avast sucks. I am gonna switch to AVG.

hello,i meet the same problem too,and after unistall avast,it's all okay!!!  so did u solve it then?how to set in avast,so not kills ss_privoxy silently auto?
