### ISSUE TITLE
希望能增加 “绕过大陆和局域网 IP” 的 PAC 规则

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-windows#1270]
大陆 IP 库我自己做了一份 [see](https://raw.githubusercontent.com/LisonFan/china_ip_list/master/china_ip_list) 拿 IPIP 和 APNIC 的库合并的（README 写了）。

光 GFWLIST 不够用了。

**Comment by chenshaoju** [comment]
你见到的“绕过大陆和局域网 IP ”是基于CNRoute以路由方式进行的。

PAC是应用层的处理方式，直接修改浏览器代理即可，CNRoute是路由层的处理方式，需要修改路由表。

目前Shadowsocks for Windows 主要是在协议层处理（本机开个SOCKS5端口），而且操作路由需要触发管理员权限申请，不太适用。

如果你坚持，可以考虑使用Tun2Socks5，并搭配CNRoute。
https://github.com/ambrop72/badvpn/wiki/Tun2socks
https://github.com/fivesheep/chnroutes

**Comment by LisonFan** [comment]
@chenshaoju 
[pac.txt](https://github.com/shadowsocks/shadowsocks-windows/files/1185506/pac.txt)

这里有一份 SSR 的，就是通过 PAC 来实现的（应该是的吧。。）

**Comment by chenshaoju** [comment]
@LisonFan  interesting，理论上pac是按照域名来进行处理的，这种IP处理我第一次见。
刚学习了一下：
https://github.com/breakwa11/gfw_whitelist

**Comment by pexcn** [comment]
这样的话不是要求 DNS 不被污染才能被正确处理吗？

根据域名来处理感觉更佳：https://github.com/R0uter/gfw_domain_whitelist

**Comment by LisonFan** [comment]
@pexcn 还是根据 IP 来好一些，域名不全的。DNS 污染可以用 Pcap_DNSProxy 解决。

**Comment by celeron533** [comment]
可以在代理链上增加个cow
https://github.com/cyfdecyf/cow
