### ISSUE TITLE
软件启动后快捷键不会自动注册

### ISSUE THREAD

**Issue by tmplinshi** [shadowsocks/shadowsocks-windows#1276]
我设置了一个【切换系统代理模式】的快捷键 Ctrl+F12，然而软件每次启动时不会自动注册这个快捷键。希望软件启动后能自动注册已设置的热键，谢谢！

_系统: Window 10 x64
软件: Shadowsocks v4.04_

**Comment by chenshaoju** [comment]
这是故意设置的，避免热键冲突。
详见： https://github.com/shadowsocks/shadowsocks-windows/issues/1172

**Comment by tmplinshi** [comment]
好吧，我自己做了个小工具来解决这个问题 https://github.com/tmplinshi/RegSsHotkey

我建议还是加上这个功能，毕竟有好多人有这个需求啊

**Comment by cairoHy** [comment]
反馈，4.0.5版本插件失效~~ @tmplinshi

**Comment by goreliu** [comment]
避免热键冲突？这为什么会成为一个问题？后运行的实例把之前运行的实例快捷键覆盖就可以了，或者后运行的实例注册快捷键失败不注册也行。

**Comment by celeron533** [comment]
Implemented in #1130
