### ISSUE TITLE
4.0.4启动失败

### ISSUE THREAD

**Issue by DepardieuGao** [shadowsocks/shadowsocks-windows#1278]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
windows10

### Steps you have tried
启动时报错,尝试删除重新解压,重启电脑依旧报错.

### What did you see instead?
System.NullReferenceException:未将对象引用设置到对象的实例.在Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable,Boolean global,String proxyServer,String pacURL)在Shadowsocks.Controller.SystemProxy.Update(Configurtaion config, Boolean forceDisable,PACServer pacSrv)在Shadowsocks.Controller.ShadowsocksController.Reload()在Shadowsocks.Progra.Main()

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
#1185
