### ISSUE TITLE
高可用性的讨论

### ISSUE THREAD

**Issue by kkkkke** [shadowsocks/shadowsocks-windows#1279]
建议增加检测延迟时使用tcp/icmp的选项。这样可以去掉防火墙上icmp的洞，更加隐蔽。

**Comment by pexcn** [comment]
什么意思？

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 目前没有延迟检测。
你可以使用第三方工具替代：
http://www.nirsoft.net/utils/multiple_ping_tool.html

**Comment by JonasGao** [comment]
想要自己控制高可用。这个应该可以实现。图里的 statistics config

![2017-07-30_li](https://user-images.githubusercontent.com/4549584/28750471-b5129a58-751e-11e7-874e-045b01d016f5.jpg)

**Comment by chenshaoju** [comment]
@JonasGao 记忆中这个有问题，会导致崩溃，不知道修复没有。。。

**Comment by celeron533** [comment]
木有

>记忆中这个有问题，会导致崩溃，不知道修复没有

**Comment by database64128** [comment]
Stale conversation. Closing now.
