### ISSUE TITLE
Cannot share over hotspot

### ISSUE THREAD

**Issue by florianmonfort** [shadowsocks/shadowsocks-windows#1280]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4.0

### Environment(Operating system, .NET Framework, etc)
Windows 10 latest production build

### Steps you have tried
Setting to Allow clients from LAN
Forward Proxy

### What did you expect to see?
My mobile hotspot clients would be able to access the Proxy. Tried connecting my PS4 and Android phone to my computer with Shadowsocks turned on and both of them are not using the proxy

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
you need set pac proxy in your phone and ps4 ,And check firewall settings in your pc.

https://github.com/shadowsocks/shadowsocks-windows/issues/1258

**Comment by florianmonfort** [comment]
Ok I see, I managed to make it work, thanks very much! Closing this.
