### ISSUE TITLE
怎么配置ss啊，求指教！下载下来后运行ss直接显示已停止工作。

### ISSUE THREAD

**Issue by hzcly98** [shadowsocks/shadowsocks-windows#1282]
![image](https://user-images.githubusercontent.com/11419958/28755660-82a0ab7c-7592-11e7-866b-b7ece88fa67c.png)

**Comment by chenshaoju** [comment]
请尝试安装：
https://www.microsoft.com/zh-CN/download/details.aspx?id=55170

**Comment by hzcly98** [comment]
忘记说明的一点：ss下载下来安装的过程中，首先提示我要安装.NET Framework ，后来我安装了最新的.NET Framework ，但是在安装的过程中，360管家监控到了什么修改配置或注册文件之类的东西，被我不小心点击拒绝安装了，再然后就是每次运行ss，都报ss已停止工作的错误。是不是因为配置文件安装被我拒绝的原因，如果是，那我现在应该怎么去处理呢？

**Comment by pexcn** [comment]
Please uninstall all about 360's software.

**Comment by chenshaoju** [comment]
请尝试退出并停用360，然后下载并使用 https://www.microsoft.com/en-us/download/details.aspx?id=30135 修复 .net framework ，如果修复失败，请选择卸载然后重新安装。

**Comment by zyf2008Neptune** [comment]
@hzcly98 你还敢用360 😵

**Comment by cookier** [comment]
一定是安装错了版本，你这是win7系统，不要安装最新的ss，不支持win7的。

**Comment by pexcn** [comment]
Windows 7 支持最新 ss-windows 的。

**Comment by zslqhua** [comment]
你還在使用360！你行！你太不愛國了！

**Comment by tangshiba** [comment]
又是一个开着360用SS的。。。。自己作死啊。

**Comment by cookier** [comment]
@pexcn 我昨天就是先安装了最新的SS，跟这一样的错误。后来找了旧版本的，就没问题了。话说我电脑上装着360国际版的杀毒软件，没提示警告，这倒让我对它不放心了= =

**Comment by pexcn** [comment]
我的没问题，卸载360再说吧。

**Comment by hzcly98** [comment]
昨天下班回去果断卸了360，然后重装.net framework，立马好使了！我也是好几年没用windows系统了，一直用的macOS，所以上来就装上了360。。。还是得感谢各位！@chenshaoju
