### ISSUE TITLE
PAC更新失败啊

### ISSUE THREAD

**Issue by trdmm** [shadowsocks/shadowsocks-windows#1283]
前几天还好的，这几天就不行了

**Comment by trdmm** [comment]
2017-07-31 13:26:45] [Info] Connect raw.githubusercontent.com:443
[2017-07-31 13:26:46] [Error] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 远程服务器返回错误: (404) 未找到。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadGFWTemplateCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by eaglet123** [comment]
挂上全局代理重试？

**Comment by chenshaoju** [comment]
你好，你可以尝试手动更新：
https://github.com/gfwlist/gfwlist

我刚才手动更新测试了一下，可以更新，没有问题。

**Comment by pexcn** [comment]
![qq 20170731151530](https://user-images.githubusercontent.com/4590439/28766647-1b8ab682-7603-11e7-8e18-9c998d2f16aa.png)
刚刚试了一下，没有问题。

**Comment by lyyy0412** [comment]
怎样修改PAC更新的地址？

**Comment by chenshaoju** [comment]
是写死的，你可以下载源码修改后重新编译。详见：
https://github.com/shadowsocks/shadowsocks-windows/blob/d21162318eb64041a8a73b3438bb23b582d4cd39/shadowsocks-csharp/Controller/Service/GfwListUpdater.cs#L17
