### ISSUE TITLE
服务开启使用一段时间后会卡住 无法继续使用

### ISSUE THREAD

**Issue by bltbbb** [shadowsocks/shadowsocks-windows#1286]
`[2017-08-01 16:52:09] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)`

然后在服务端命令行中按ctrl+c 又可以继续运行 连接正常

**Comment by bltbbb** [comment]
https://www.zhihu.com/question/30182616/answer/47150511
这是在知乎上搜到的同样问题 跟这个题主描述的基本一致

**Comment by chenshaoju** [comment]
请检查你客户端的服务器IP、端口设置是否正确。
请检查你的服务端的服务是否已经启动，是否绑定在了正确的IP上，端口是否正确，以及iptables或其他防火墙允许了端口访问。

**Comment by bltbbb** [comment]
您好，客户端ip端口密码加密方式 均正确 
因为是一直连接上的 突然会中断 然后到服务端的命令行里面按ctrl+c就能继续运行 过一段时间又是如此

shadowsocks python版

**Comment by celeron533** [comment]
目前python版哪里发现在UDP传输模式下有内存泄漏，时间久了会被内核调度清理

**Comment by chenshaoju** [comment]
@bltbbb 目前libev没有发现这个问题。

**Comment by celeron533** [comment]
这个问题和客户端关系不大，先关闭了
