### ISSUE TITLE
vpn突然上不去了

### ISSUE THREAD

**Issue by TengyuMaVandy** [shadowsocks/shadowsocks-windows#1287]
您好问一下，天行vpn是和咱们一家的么，之前在https://www.txgwvpn.com/ 这个网址买的vpn，今天突然不能用了，不知道这个天行是不是真的。如果是的话，是什么原因造成的呢？
对啦，我用的是shadowsocksR，不知道和咱们是不是一起的。about里给的github，https://github.com/breakwa11/shadowsocks-rss 已经404了……
谢谢！

**Comment by rebiu** [comment]
你好，客户1008701为你服务：
1、SS是**不提供**任何服务，SS只是个单纯的梯子，与卖服务的**没有**任何关系
2、你购买的服务不行应该去找提供服务的商家，而不是这里
3、你用的服务行不行是卖你的商家决定的，不是这里决定的。不过可以多看新闻了解最近动态
4、你说的那个SSR是另外**私人**项目，是从这里拷贝了代码再加**私人**代码，这里是公共项目
5、你说404是那个**私人**决定关闭删除的，具体原因你可以百度找到

满意请关闭这条消息，不满意点击右上角再去百度，谢谢

**Comment by TengyuMaVandy** [comment]
哈哈，哦了，谢谢。

**Comment by pexcn** [comment]
有点意思...
