### ISSUE TITLE
能在现在shadowsocks-windows版基础上加入对v2ray的支持吗？

### ISSUE THREAD

**Issue by Fengzhiying2017** [shadowsocks/shadowsocks-windows#1288]
使用ss已经二年多了，非常好用的一个工具，速度快，稳定，而且客户端把服务器信息添加好后，电脑上的各种应用几乎不用设置就能自动根据请求走代理或是直连，同时各个手机平台的支持也比较好，但在如今不断升级的GFW前，除了本身的完善发展外，是否也可以考虑加入其他服务端的支持呢？
目前类似的项目v2ray，原理与ss基本相似，只是主要采用了vmess协议（同时服务端也支持ss协议，可直接使用ss客户端连接），手机上可以用shadowrocket，但现有的windows客户端还不够完善，兼容性、稳定性有待提升，而现有ss在与需要代理的应用对接、本地入站处理方面已经非常成熟，是否能在ss客户端的基础上增加对vmess等协议的支持，开发出一个全新的v2ray客户端？要做的应该主是把出站请求用vmess打包后与服务端对接，及收到服务端数据后转发给本地应用，不知是否可行？谢谢！

**Comment by celeron533** [comment]
没有计划。

**Comment by pexcn** [comment]
你可以 fork 过去自己改。

**Comment by Fengzhiying2017** [comment]
@pexcn 苦于不会写代码啊！只会用现成的工具写配置。

**Comment by pexcn** [comment]
不会可以学 @Fengzhiying2017

**Comment by tangshiba** [comment]
怎么会要求这里的人去兼容别的应用。。。v2ray的客户端不好用可以反馈给v2ray的作者啊。
