### ISSUE TITLE
非预期错误

### ISSUE THREAD

**Issue by Young1564772491** [shadowsocks/shadowsocks-windows#1289]
![default](https://user-images.githubusercontent.com/20045999/28870480-0c0b33ce-77b3-11e7-8651-9ccb2d3d5b1b.PNG)
系统：Windows 10
,net情况：在线安装包提示.net已经包含在系统内

**Comment by chenshaoju** [comment]
默认情况下， C:\Program Files\ 没有写入权限。请以管理员权限运行Shadowsocks.exe，或者将Shadowsocks.exe放到其他目录下，比如 C:\SS\ 、 D:\SS\ 等。
