### ISSUE TITLE
关于统计配置的问题

### ISSUE THREAD

**Issue by coofo** [shadowsocks/shadowsocks-windows#1291]
希望可以详细说明一下 统计配置
在计分权重的设置中，从描述来看有一些是值越大越好，比如：入站速度 出站速度
但是也有一些是值越小越好的，比如：丢包 延迟
所以 我想知道这些参数是怎么进入计算的，是原值（我要通过权重的正负来处理这两类值），还是进入计算的值已经做过处理（都是越大越好，权重我只要用正数就行）？
这些数值大概是以什么单位进入计算的？

另外还想问一下，
负载均衡下在配置中的服务器被选中概率是否相同？
高可用 和 根据统计 这两种是否一段时间内只使用一台服务器？

**Comment by dlh0011** [comment]
能给我发一个客户端吗，官网买完下载不了

**Comment by chenshaoju** [comment]
@dlh0011 请与你的服务商联系，客户端可能是定制的，不适用。
