### ISSUE TITLE
突然打不开了

### ISSUE THREAD

**Issue by WHongtao** [shadowsocks/shadowsocks-windows#1292]
![default](https://user-images.githubusercontent.com/30196591/28905680-ca030096-7844-11e7-899a-2aa0fc88c326.PNG)
昨天还好好的，今天开机就打不开了。  版本4.0.4

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676

**Comment by dlh0011** [comment]
能发给我一个客户端吗，我刚买完客户端下载不了

**Comment by WHongtao** [comment]
谢谢，问题已解决：关闭SS，删除同文件夹下的user-wininet.json后，重试运行
