### ISSUE TITLE
谁能发给我一个客户端，现在下载不了了不知道为啥

### ISSUE THREAD

**Issue by dlh0011** [shadowsocks/shadowsocks-windows#1293]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/releases

如果无法使用，请与你的服务商联系，客户端可能经过修改，无法通用。
