### ISSUE TITLE
双击打开shadowsocks.exe，报错system.nullreferenceException

### ISSUE THREAD

**Issue by penn201500** [shadowsocks/shadowsocks-windows#1295]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
shadowsocks 4.0.4

### Environment(Operating system, .NET Framework, etc)
win7 x64

### Steps you have tried
双击打开shadowsocks.exe

### What did you see instead?
![image](https://user-images.githubusercontent.com/16840448/28977019-e00969be-7972-11e7-8cba-8c2f4b30de54.png)

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676

**Comment by penn201500** [comment]
change nothing , just download new version shadowsocks4.0.5, problem solved. 
anyway, tks for ur support :)
