### ISSUE TITLE
Non-UI Error and auto quit

### ISSUE THREAD

**Issue by ZhangDubhe** [shadowsocks/shadowsocks-windows#1296]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
windows 10 , .NET Framework is the latest.

### Steps you have tried
non-UI error 

### Config and error log in detail (with all sensitive info masked)
system. NullReferenceException: 未将对象引用设置到对象的实例

**Comment by chenshaoju** [comment]
这种情况一般是由于你的 .NET Framework 损坏导致的，请尝试使用：
https://www.microsoft.com/en-us/download/details.aspx?id=30135

进行修复，如果修复失败，请按照提示进行卸载，然后下载：
https://www.microsoft.com/zh-CN/download/details.aspx?id=55170

重新安装。

**Comment by seraphlive** [comment]
确定是.net损坏原因吗？我也遇到这个错误，前一天到关机都还正常，今天一开机就崩了......用微软的那个修复工具也没查出.net有啥毛病...别的软件工作也都正常......

**Comment by chenshaoju** [comment]
＠seraphlive 有无完整的错误提示？就只有一行“system. NullReferenceException: 未将对象引用设置到对象的实例” 吗？

**Comment by seraphlive** [comment]
@chenshaoju 参考其他链接删除配置文件重新设置问题解决，可能是配置文件有损坏吧，感谢帮助~！

**Comment by ZhangDubhe** [comment]
@chenshaoju 同楼上，修复.Net无作用，删除json文件即可。谢谢帮助！！！
