### ISSUE TITLE
4.0.4运行一段时间后会崩溃

### ISSUE THREAD

**Issue by lifeva** [shadowsocks/shadowsocks-windows#1302]
![tim 20170807162244](https://user-images.githubusercontent.com/11326402/29018450-aac044f4-7b8d-11e7-9588-c6af6e16a085.png)

**Comment by celeron533** [comment]
非预期错误：集合已修改；可能无法执行枚举操作。 #906

**Comment by lifeva** [comment]
把这个可靠性统计功能关闭，是不是就不能使用负载均衡，高可用等策略了呢？

**Comment by celeron533** [comment]
对，会有影响
