### ISSUE TITLE
能不能让127.0.0.1:1080的连接，不判断pac，走全局代理

### ISSUE THREAD

**Issue by imgaohao** [shadowsocks/shadowsocks-windows#1304]
现在有个问题，使用proxifier，设置127.0.0.1:1080与不使用proxifier没什么区别。
最终都会根据shadowsocks的代理模式进行代理。
想让127.0.0.1:1080的代理，全部为全局代理，怎么弄。

**Comment by chenshaoju** [comment]
没看懂你这一段话。

如果你的应用走 127.0.0.1:1080 ，就相当于是全局模式，和PAC无关。

**Comment by imgaohao** [comment]
没问题，是我弄错了。刚试了127.0.0.1:1080是全局模式。
因为之前ins图片显示不出来，图片的host是cdninstagram.com，pac里没有，ss全局代理可以显示。
然后就用proxifier把浏览器程序代理到127.0.0.1:1080，还是显示不出来，所以就以为127.0.0.1:1080是pac模式。

**Comment by shikkoku** [comment]
只会在用SSR客户端那种Bypass LAN&CHINA功能才不会全局。但本项目没有这种功能。

**Comment by imgaohao** [comment]
doub.io这个网站，pac里没有，打算把浏览器代理到127.0.0.1:1080，全局模式，还是访问不了。
doub.io加到pac里或者用ss的全局模式就可以访问。
![default](https://user-images.githubusercontent.com/10082180/29070023-e8c309c0-7c6f-11e7-950b-ffbb2fd7852a.png)

**Comment by shikkoku** [comment]
你用proxifier关了Shadowsock的系统代理没有，最好记得关掉。我觉得锅不在Shadowsock。我没用proxifier只开Shadowsock的全局系统代理访问你那网站正常。

**Comment by imgaohao** [comment]
@shikkoku 我用proxifier时没有关Shadowsock系统代理，不能关吧，关了所有都访问不了。
https://doub.io/
Shadowsock的全局模式是可以访问。但是用proxifier，127.0.0.1:1080全局模式访问不了。

**Comment by shikkoku** [comment]
谁跟你说用了proxifier后关了所有都访问不了。

**Comment by imgaohao** [comment]
真的，我用proxifier，关了Shadowsock系统代理，google.com都访问不了。
算了，不是Shadowsock问题。我用php代码通过127.0.0.1:1080访问了下，是可以的。
proxifier有问题吧。
![image](https://user-images.githubusercontent.com/10082180/29071548-b2846ffa-7c76-11e7-9d8e-a8907904c36a.png)

**Comment by shikkoku** [comment]
关了Shadowsock系统代理，proxifier没写规则的程序都不能走代理了。在规则里的uc浏览器应该还是会全局走才对。127.0.0.1:1080这个代理服务器就算关了系统代理功能SS仍然会连通的。只是没帮你设置系统代理而已。你用了proxifier就不用开了。

**Comment by imgaohao** [comment]
嗯，你说的对，127.0.0.1:1080这个代理服务器就算关了系统代理功能，SS仍然会连通，只是没帮我设置系统代理。但是我用proxifier，不开ss代理，那就没必要用proxifier了，我需要ss的代理访问网站。
为什么说 “你用了proxifier就不用开ss代理了”。

**Comment by shikkoku** [comment]
我的意思其实是说的是开了proxifier，最好不要再开SS的系统代理功能（或者是说你有指定的浏览器要走proxifier时）。

**Comment by shikkoku** [comment]
如果UC浏览器有不启用系统代理功能选项，你开着SS的系统代理功能也应该不会收到影响才对。

**Comment by imgaohao** [comment]
嗯，谢谢呢。还是不用proxifier了。访问不了的网站就只能改pac了或者用ss全局模式。

**Comment by lykosherdshep** [comment]
我遇到相同的问题，不开shadowsocks系统代理，只配置proxifier，根本无法翻墙，我是在proxifier单独配置safari浏览器使用shadowsocks代理，但是任何外网都没法访问
