### ISSUE TITLE
非预期错误，4.04最近发现无法启动了，小白寻求帮助

### ISSUE THREAD

**Issue by hubohan** [shadowsocks/shadowsocks-windows#1305]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
win10 应该目前是最新版本
net framework 4.7

### Config and error log in detail (with all sensitive info masked)
之前一段时间还是可以很好的启动的，这几天忽然使用不了了，是否和framework的版本升级有关？
错误提示：
非预期错误，shadowsocks将退出。请提交此错误到
https://github.com/shadowsocks/shadowsocks-windows/issues
system.NullReferenceException:未将对象引用设置到对象的实例。
在Shadowsocks.Util.SystemProxy.SetIEProxy(Boolean enable,Boolean global,String proxyServer,String pacURL)
在Shadowsocks.Controller,SystemProxy.Update(Configuration config,Boolean forceDisable,PACServer pacSrv)
在Shadowsocks.Controller.ShadowsocksController.Reload()
在Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676

**Comment by hubohan** [comment]
问题已解决，感谢！
