### ISSUE TITLE
在公司使用SS，更新了本地PAC文件，使用PAC模式无法访问wx.qq.com（公司已屏蔽此站点） 但是使用全局模式可访问。

### ISSUE THREAD

**Issue by Buddy119** [shadowsocks/shadowsocks-windows#1306]
更新本地的PAC文件，尝试了  "||qq.com",  ".qq.com", 这两种规则。 使用PAC模式，重启浏览器后，无法打开"wx.qq.com" 如果使用全局模式，可以打开"wx.qq.com"。 我还尝试过，在PAC文件中加入“||ip.cn”,同时使用pac模式访问“ip.cn” 显示走的是代理。 不知道为什么wx.qq.com就是无法访问

**Comment by KaedeShinoda** [comment]
试一下直接把wx.qq.com加进去

**Comment by Buddy119** [comment]
@KaedeShinoda  试过了，也是不行。。。我发现不仅wx.qq.com不行，webQQ 也不行， 在地址栏输入w.qq.com，页面可以显示出来，然后用手机扫码登录，扫完码跳转到下一个页面的时候，页面就被禁了。。。所以我不知道PAC模式，为什么对这种登录型的页面会无效

**Comment by KaedeShinoda** [comment]
试一下HTTPS？

**Comment by Buddy119** [comment]
@KaedeShinoda 你指的是什么

**Comment by KaedeShinoda** [comment]
就是 访问https://wx.qq.com
不过不清楚这个软件是否可以用于这方面 如果不行的话那我就帮不到了

**Comment by Buddy119** [comment]
@KaedeShinoda 我在规则里面加了https://wx.qq.com 是不行的 你说的访问是什么意思

**Comment by KaedeShinoda** [comment]
直接在地址栏访问那个网址 不过我试了下 似乎会强制SSL？

**Comment by Buddy119** [comment]
@KaedeShinoda 直接访问 肯定是访问不了的。。。公司的防火墙把这个网站屏蔽了，所以我才会考虑用SS翻过公司的防火墙

**Comment by chenshaoju** [comment]
请尝试此PAC，此PAC只允许访问 *.qq.com ：
https://gist.github.com/chenshaoju/68f369d099e08d4f9c676771c6c7c8fb

请将 127.0.0.1:10800 替换成你的SS端口。
