### ISSUE TITLE
windows10 今天开始启动失败

### ISSUE THREAD

**Issue by Qquanwei** [shadowsocks/shadowsocks-windows#1307]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
shadowsockes for windows 4.0.4.0

### Environment(Operating system, .NET Framework, etc)

windows 10 x64
.net4.5 , .net 4.6
 
### Steps you have tried

双击打开，报错。 而我运行老版本的shadowsocks(没错我还留着)可以正常运行(version 2.5.2.0)

### What did you expect to see?

正常运行到托盘
### What did you see instead?
![image](https://user-images.githubusercontent.com/9263655/29082338-cab4e854-7c97-11e7-90b2-d3dd4b4ce0a6.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676

**Comment by Qquanwei** [comment]
👍
