### ISSUE TITLE
"Illegal server address" when enabled "high availability"

### ISSUE THREAD

**Issue by KaedeShinoda** [shadowsocks/shadowsocks-windows#1308]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Windows 10 Home ,  .Net Framework 4.0

### Steps you have tried
Right-click the icon, select "server" - "high availability".Double-click the taskbar icon,and click anyone server name from list.

### What did you expect to see?
Show the server info.

### What did you see instead?
It is display a windows "Illegal server address".

### Config and error log in detail (with all sensitive info masked)
I think it just a bug?

(English is not good.)
### Image
 ![snipaste_20170809_104557](https://user-images.githubusercontent.com/13806806/29103061-0684f060-7cf0-11e7-870d-d91db72839d2.png)

**Comment by celeron533** [comment]
You need to delete "未配置服务器" first

**Comment by KaedeShinoda** [comment]
Thanks. 👍
