### ISSUE TITLE
Shadowsocks  non-UI Error

### ISSUE THREAD

**Issue by Qianai** [shadowsocks/shadowsocks-windows#1310]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Windows 7 x64
.Net Framwork 4.7
### What did you expect to see?
http://www.qcraftcdn.tk/p/201708105500384.png

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676
