### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by linrubo** [shadowsocks/shadowsocks-windows#1311]
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.NullReferenceException: 未将对象引用设置到对象的实例。

   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)

   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)

   在 Shadowsocks.Controller.ShadowsocksController.Reload()

   在 Shadowsocks.Program.Main()

**Comment by shiningelf** [comment]
我也遇到了这个问题，再一次异常关机之后，就报这个错了
我觉得应该是异常关机导致配置文件损坏
