### ISSUE TITLE
When connecting to google it shows "500 server internal error - Could not load template file no-server-data or one of its included components."

### ISSUE THREAD

**Issue by dadadabiu** [shadowsocks/shadowsocks-windows#1312]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### What did you expect to see?
I 've been confirmed the server ip.It's right but I connect to google it has a "Could not load template file no-server-data or one of its included components." question retuen back.please help me 3Q so much

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
The shadowsocks have any log output?

**Comment by celeron533** [comment]
Any more details?



"3Q" only works on Chinese: Sam queue
For other native speakers, it pronounces as "three-Q", not "thank you"...

**Comment by dadadabiu** [comment]
--- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-08-11 08:48:11] Shadowsocks started
[2017-08-11 08:48:36] Shadowsocks started
[2017-08-11 08:48:51] Shadowsocks started
[2017-08-11 08:49:16] Shadowsocks started
[2017-08-11 08:50:02] Shadowsocks started
[2017-08-11 08:52:23] Shadowsocks started
[2017-08-11 08:53:26] Shadowsocks started
[2017-08-11 08:53:49] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-08-11 08:53:51] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-08-11 08:54:20] Shadowsocks started
[2017-08-11 09:28:08] Shadowsocks started
[2017-08-11 09:28:49] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-08-11 09:28:49] Shadowsocks started
[2017-08-11 09:31:47] Shadowsocks started
[2017-08-11 10:47:59] Shadowsocks started
[2017-08-11 10:48:00] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
Do you Enable Proxy?
If yes,Please try Disable it.

![image](https://user-images.githubusercontent.com/515763/29200723-30579fe6-7e8a-11e7-8004-9e4fdb3f8fbd.png)

**Comment by celeron533** [comment]
Any updates?

**Comment by buchijiang** [comment]
I met the same problem。is bug? how to solve?

**Comment by chenshaoju** [comment]
@buchijiang https://github.com/shadowsocks/shadowsocks-windows/issues/1312#issuecomment-321726328

**Comment by buchijiang** [comment]
@chenshaoju I tried before,but that not solve problem

**Comment by celeron533** [comment]
看错误报告似乎是在检查更新的时候出了问题。因为一直是从github的release检查更新，这个链接是https的，有涉及到SSL，TLS。暂时停用自动更新，再看看能否上网。

**Comment by celeron533** [comment]
可能和 #1297 类似

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/491#issuecomment-193703181
https://github.com/shadowsocks/ShadowsocksX-NG/issues/106

迹象上看起来是`privoxy`抽筋了
