### ISSUE TITLE
使用ss libev+simple obfs的时候，如果节点有域名，是否还需要填写混淆参数？

### ISSUE THREAD

**Issue by himan85** [shadowsocks/shadowsocks-windows#1313]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
你似乎使用的是SSR
