### ISSUE TITLE
shadowsocks non-UI Error

### ISSUE THREAD

**Issue by shrez28** [shadowsocks/shadowsocks-windows#1314]
File version 4.0.4.0 on Windows 10
I have been using it for around 2 months without any problem.
But for the past couple of days I have getting  non-UI error.
The following is the error message I get when I try to get on to shadowsocks.
![ss_error](https://user-images.githubusercontent.com/30920734/29202851-8b995502-7e9e-11e7-9763-ef728688a8af.png)

I have tried reinstalling the Shadowsocks on my laptop but it still did not work.
It will great if someone can help me to resolve this issue. Thanks.

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676
