### ISSUE TITLE
System.NullReferenceException: 未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by starsy** [shadowsocks/shadowsocks-windows#1316]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Win10 

### Steps you have tried
运行Shadowsocks.exe

### What did you expect to see?
SS正常工作 

### What did you see instead?
SS崩溃，弹出异常窗口
![ss](https://user-images.githubusercontent.com/1459979/29215177-87e48984-7edc-11e7-9310-98b1b3f21106.png)

### Config and error log in detail (with all sensitive info masked)
[2017-08-11 21:28:29] Shadowsocks started
[2017-08-11 21:28:29] [E] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main()
[2017-08-11 21:29:04] Shadowsocks started
[2017-08-11 21:29:04] [E] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main()

**Comment by bzd111** [comment]
重新下载最新版就好了
