### ISSUE TITLE
Is this bulid a fake one? weird.

### ISSUE THREAD

**Issue by jasonliul** [shadowsocks/shadowsocks-windows#1317]
shadowsocks 4.0.5
http://www.softpedia.com/get/Internet/Servers/Proxy-Servers/Shadowsocks.shtml

https://softpedia-secure-download.com/dl/31a49995ab36015289d729405372d357/598d69fe/100252208/software/internet/servers/Shadowsocks-4.0.5.zip

What's new in Shadowsocks 4.0.5
August 11th, 2017
Fix crash when user-wininet.json fail to parse. (#1178)
Bug fixes and improvements.

**Comment by celeron533** [comment]
Sorry for the confusion, there was a 4.0.5 release but with wrong tag. After the correction, the release status comes to draft.
You could compare the MD5 and SHA hash to verity.

**Comment by jasonliul** [comment]
Oh, thanks for clarify.
:)

**Comment by celeron533** [comment]
Now 4.0.5 is released. Thanks for the notification.
