### ISSUE TITLE
3.4.3版本可以使用。4.0.4及0.5无法链接。

### ISSUE THREAD

**Issue by qlngy** [shadowsocks/shadowsocks-windows#1318]
开始我也是使用的4.0.4，使用是没有任何问题的。后来不知道发生了什么就没法再用了。奇怪的是3.4.3却没有问题。下面是4.0.5的日志。系统WIN10，Framework应该没有问题。

[2017-08-12 12:14:32] connect to s.youtube.com:443
[2017-08-12 12:14:32] System.TypeInitializationException: “Shadowsocks.Encryption.EncryptorFactory”的类型初始值设定项引发异常。 ---> System.TypeInitializationException: “Shadowsocks.Encryption.Sodium”的类型初始值设定项引发异常。 ---> System.EntryPointNotFoundException: 无法在 DLL“libsscrypto.dll”中找到名为“sodium_init”的入口点。
   在 Shadowsocks.Encryption.Sodium.sodium_init()
   在 Shadowsocks.Encryption.Sodium..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Encryption.Sodium.get_AES256GCMAvailable()
   在 Shadowsocks.Encryption.EncryptorFactory..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()

**Comment by chenshaoju** [comment]
请退出Shadowsocks，然后删除 shadowsocks.exe 所在目录下的 ss_win_temp 目录，然后再启动Shadowsocks即可。

**Comment by qlngy** [comment]
已解决。谢谢你。

**Comment by celeron533** [comment]
@chenshaoju 最近有2起因`libsscrypto.dll`损坏导致无法使用的情况。。。

**Comment by chenshaoju** [comment]
@celeron533 对，不知道起因，我这儿Win7/Win10的环境还没出过这个现象。我怀疑是不是要改进一下，每次启动时删掉 ss_win_temp ，然后再重新吐出来一次？

**Comment by celeron533** [comment]
发生概率还没高到这个地步

**Comment by qlngy** [comment]
我再说下详细情况。我有三个us IP，奇怪的是us01是没办法使用的，情况不明，但是us01在3.4.3版本是没问题的。然后那天出现libsscrypto.dll这个问题是因为更新后我直接把新版本的ss在文件夹ss_win_temp中打开，具体是否由上述直接引起，不知。

**Comment by myliyifei** [comment]
最近4.0.4版本也是新添加的任何服务器都不行了，显示“目标服务器积极拒绝”。其实没有任何问题。清空SS目录下其他文件，全部重新配置就好了。不知道是哪个文件坏了。

在 2017年8月13日 下午6:49，qlngy <notifications@github.com>写道：

**Comment by qlngy** [comment]
好的。好像我提供了没有验证的信息，因为昨天手机us01也失效了。但今天电脑us01又可以用了。呃...

**Comment by chenshaoju** [comment]
@qlngy 可能你所在的SS服务商的这台服务器挂了。。。
