### ISSUE TITLE
最新版本的客户端被卡巴斯基删掉了

### ISSUE THREAD

**Issue by rvfu98** [shadowsocks/shadowsocks-windows#1319]
卡巴斯基删掉了最新版本的shadowsocks，希望开发者注意一下这个问题

**Comment by jasonliul** [comment]
VT
https://www.virustotal.com/en/file/28825798b1fb3951a536ca6c9805db68f2d9cbb393a4ef363e12f9343e8be8c9/analysis/

提交卡巴误报是你的事情, 喂饭佬~

**Comment by pexcn** [comment]
卸载卡巴斯基

**Comment by rvfu98** [comment]
@pexcn 这可是我在某宝上面花了15块钱买的。

**Comment by rvfu98** [comment]
@jasonliul 好的，谢谢

**Comment by rvfu98** [comment]
@jasonliul 好的，谢谢

**Comment by chenshaoju** [comment]
已联系卡巴斯基进行复查，有结果将会更新。

![unnamed qq screenshot20170812154028](https://user-images.githubusercontent.com/515763/29238991-99290c86-7f74-11e7-86e2-9b2402200ceb.png)

**Comment by rvfu98** [comment]
@chenshaoju 好的，谢谢

**Comment by palalalala** [comment]
提交给卡巴技术支持来个人工分析。INC000008139408 
周一上班了估计才有回复。。。

**Comment by zyf2008Neptune** [comment]
诺顿也一样，每个版本都要手动排除。

**Comment by pexcn** [comment]
@rvfu98 为什么要买？

**Comment by rvfu98** [comment]
@pexcn 专业版的，从淘宝上面买的，难道还有其他破解的方法？

**Comment by utopiawww** [comment]
都不要责怪楼主了，毕竟之前的版本卡巴都没报错。当然我们从没怀疑过ss会有问题。
还有今天升级到卡巴2018，软件目录排除了，文件没被删，但是就是运行不了，直接被卡巴拦截了，不让运行。

**Comment by palalalala** [comment]
@utopiawww 
![qq 20170812224942](https://user-images.githubusercontent.com/30950533/29241659-8dfa4fb4-7fb0-11e7-8950-c180febd08bf.png)
删掉不信任组里的

**Comment by RedTea** [comment]
4.0.4没查到，4.0.5就查到了，确实奇怪。

**Comment by chenshaoju** [comment]
目前大部分杀毒软件都启用了启发式杀毒，当发现使用范围不广，或者新出现的执行文件时会执行该操作。

通过分析代码来判断可能是什么类型的病毒，这存在很大概率的误报，因为很多情况下代码存在相似度（比如都使用了 privoxy.exe 的代码。

**Comment by HankAviator** [comment]
![false alarm](http://imgur.com/a/Z9qEH)

**Comment by pexcn** [comment]
@rvfu98 没听说过哦

**Comment by smdhz** [comment]
什么时候杀毒软件抽风也算作者的责任了？这些厂商锅甩的不要太溜

**Comment by chenshaoju** [comment]
截至本回复发布时，Kaspersky、McAfee和Rising已不再报毒。

![image](https://user-images.githubusercontent.com/515763/29271418-dfce7170-812d-11e7-9169-dd419906a086.png)

**Comment by celeron533** [comment]
>什么时候杀毒软件抽风也算作者的责任了？这些厂商锅甩的不要太溜

也不用太责怪原po，保持警惕也是好事。
