### ISSUE TITLE
更新4.0.5后，卡巴斯基报警

### ISSUE THREAD

**Issue by thinkingmen** [shadowsocks/shadowsocks-windows#1322]
更新4.0.5后，卡巴斯基报警

**Comment by BedivereZero** [comment]
13.08.2017 20.20.22;检测到的对象 ( 文件 ) 已删除。Trojan-Banker.Win32.Banbra.wbhx

**Comment by chenshaoju** [comment]
已在处理中，详见：
https://github.com/shadowsocks/shadowsocks-windows/issues/1319#issuecomment-321964236

**Comment by hVenus** [comment]
说有木马程序

**Comment by puppywin** [comment]
4.0.5 怎么比4.0.4的程序大那么多 大到哪里了？

**Comment by chenshaoju** [comment]
@puppywin 所有的变更介于 Aug 9, 2017 和 Jun 1, 2017 之间，你可以在 https://github.com/shadowsocks/shadowsocks-windows/commits/master 查看变更。

至于为什么会变大…… @celeron533

**Comment by celeron533** [comment]
我之前也注意到了体积变大的问题，但Appveyor编译下来也是这个体积。。。

**Comment by celeron533** [comment]
也有可能是因为这次是在自己机器上编译的缘故，导致debug pdb等的登记路径变化

**Comment by chenshaoju** [comment]
@celeron533 建议仍然基于Appveyor的版本进行发布，自行编译的版本有点…… ）
同时提供Appveyor的地址，会包含散列值等信息，方便核对。

**Comment by abc45628** [comment]
2017年8月14日16:46:25，卡巴已经解除误报

**Comment by repairwa11** [comment]
@chenshaoju 嗨～很高兴在这里遇见你！前辈你好～

**Comment by palalalala** [comment]
![qq 20170814195919](https://user-images.githubusercontent.com/30950533/29270797-fead1fd6-812a-11e7-998e-aef2d0662b99.png)

**Comment by chenshaoju** [comment]
截至本回复发布时，Kaspersky、McAfee和Rising已不再报毒。

![image](https://user-images.githubusercontent.com/515763/29271418-dfce7170-812d-11e7-9169-dd419906a086.png)
