### ISSUE TITLE
端口已被占用

### ISSUE THREAD

**Issue by innbunn69** [shadowsocks/shadowsocks-windows#1324]
无法使用，一打开就提示：
System.Exception:端口已被占用
at Shadowsocks.Controller.Listener.Start(Configuration config)
at Shadowsocks.Controller.ShadowsocksController.Reload()

### Version(release version or AppVeyor link)
4.0.5

### Environment(Operating system, .NET Framework, etc)
Win 7
4.6.2

**Comment by chenshaoju** [comment]
你是否启动了多个Shadowsocks？请检查任务栏的图标托盘区，以及是否被折叠收起来了。

**Comment by innbunn69** [comment]
检查了，没有启动多个ss，一打开就出现这样的提示。

**Comment by chenshaoju** [comment]
检查 Shadowsocks.exe 所在目录下有无 gui-config.json 文件，如果有，用Windows自带的记事本打开。

找到 "localPort": ，将冒号后面的数字修改为其他端口，比如 7777 ，然后保存退出，再启动 Shadowsocks.exe 看看。

**Comment by innbunn69** [comment]
解决了！非常感谢！！！

**Comment by majiqiang** [comment]
哇  太厉害了  果然换了个端口就好了！

**Comment by LifeC0ach** [comment]
感谢大佬！手动改个端口号就好了前面还重启半天
