### ISSUE TITLE
可否增加暂时禁止某几个服务器连接的功能？

### ISSUE THREAD

**Issue by StrollStars** [shadowsocks/shadowsocks-windows#1325]
有些服务器暂时性出现问题，需要临时屏蔽。
如果用“高可用”模式，可能就都走一两个服务器了。
如果删掉下回还要添加回来。
因此建议增加这个功能。

**Comment by celeron533** [comment]
这个功能和性能统计有关，但目前性能统计这个模块问题很多。

**Comment by StrollStars** [comment]
@celeron533 我这个需求可以不需要性能统计功能，前面加个复选框勾选就可以了，当然我不知道实现起来是否困难。
