### ISSUE TITLE
4.0.5的一个BUG(大概是windows的权限导致)

### ISSUE THREAD

**Issue by ArchieMeng** [shadowsocks/shadowsocks-windows#1327]
### Version(release version or AppVeyor link)
Release 4.0.5

### Environment(Operating system, .NET Framework, etc)
Windows 10

### Steps you have tried
原本放置在用户桌面，能够正常打开，今天忽然启动失败，但是更换到用户的下载文件夹中就正常启动了。

错误提示：
![2017-08-17](https://user-images.githubusercontent.com/12139431/29396746-5973b39e-834c-11e7-8554-a93493c27e65.png)

**Comment by chenshaoju** [comment]
请尝试右击 Shadowsocks.exe ，看看有无一个名为 解除锁定 的按钮或选项？

**Comment by ArchieMeng** [comment]
原来的这个文件夹被删掉了，现在也没法复现BUG了。。。

**Comment by wongsyrone** [comment]
这个的原因有很多，一种是上面说的属性里面的锁定，一种是其他杀毒软件后台扫描临时锁定，还有一种是文件系统权限，比如NTFS。

不过所有的可能都不是bug，只表明不让访问罢了。

**Comment by celeron533** [comment]
>原来的这个文件夹被删掉了，现在也没法复现BUG了。。。

所以这不是bug
