### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Hasiy** [shadowsocks/shadowsocks-windows#1329]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Hotkeys.HotKeys.Destroy()
   在 Shadowsocks.Program.Application_ApplicationExit(Object sender, EventArgs e)
   在 System.Windows.Forms.Application.RaiseExit()
   在 System.Windows.Forms.Application.ThreadContext.Dispose(Boolean postQuit)
   在 System.Windows.Forms.Application.ThreadContext.ExitCommon(Boolean disposing)
   在 System.Windows.Forms.Application.ExitInternal()
   在 System.Windows.Forms.Application.Exit(CancelEventArgs e)
   在 Shadowsocks.View.MenuViewController.Quit_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.Command.DispatchID(Int32 id)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.2053.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Shadowsocks
    程序集版本:4.0.5.0
    Win32 版本:4.0.5.0
    基本代码:file:///C:/Users/Downloads/Shadowsocks/Shadowsocks.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.2053.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.2053.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0

    Win32 版本:4.7.2053.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json

**Comment by chenshaoju** [comment]
热键冲突？

**Comment by Hasiy** [comment]
解决了  windows8.1 更新包 KB3186606 后不报错了
