### ISSUE TITLE
日日日,我快疯啦,一大堆异常抛出,一会是字体问题.一会是没安装.net framework

### ISSUE THREAD

**Issue by gsons** [shadowsocks/shadowsocks-windows#1331]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
能否提供操作系统版本、.NET Framework、Shadowsocks等的版本信息？

另外，有无错误截图？

**Comment by smdhz** [comment]
请文明反馈问题，日不能解决任何问题
