### ISSUE TITLE
为什么不能彻底隐藏访问来源？

### ISSUE THREAD

**Issue by BI7PRK** [shadowsocks/shadowsocks-windows#1334]
不能彻底隐藏访问来源。有些网站还显示：
Your IP: 【本地公网IP】，Proxy IP: 【代理服务VPS的IP】

**Comment by chenshaoju** [comment]
某些IP检测网站使用WebRTC进行检测，这种没有办法，可以安装 NoScript 来解决：
https://noscript.net/

你是自己搭的服务器还是租用的第三方的服务商的服务？如果是第三方服务商的，可能服务端会在HTTP头中报告X-Forwarded-For。

**Comment by BI7PRK** [comment]
哦，感谢回复。自己搭的是第三方VPS服务器。

**Comment by chenshaoju** [comment]
安装NoScript后，看看是否还会检出你的真实IP。

**Comment by BI7PRK** [comment]
还是出现的。测试地址如下：
http://fsdfa.le-vel.com/

**Comment by chenshaoju** [comment]
我没有使用代理服务器，他也显示我有，而且这个IP明显不对。

![image](https://user-images.githubusercontent.com/515763/29558646-543932c0-875f-11e7-9d59-f4f7575a25ed.png)

请检查页面中显示的 Your IP ，如果是的公网IP，那么说明可能是你没有正确配置你的浏览器代理。

如果显示的是你的服务器的IP，说明可能是你的服务器的IP被Ban了。

**Comment by BI7PRK** [comment]
哦，天呐。那不知道咋回事了。
代理确认是已经设置了【全局模式（留意一下这里是否存在Bug）。而VPS也是香港。页面显示的也是香港IP。我误以为那是自己的代理服务器IP。刚刚核对一下。它不是。但显示访问来源的公网IP是没错的。

**Comment by chenshaoju** [comment]
我的VPS没有被Ban，所以无法确认。

如果你的 WinHTTP Web Proxy Auto-Discovery Service 没有启动，可能会导致全局模式无效。

https://github.com/shadowsocks/shadowsocks-windows/issues/1321

**Comment by zjl88858** [comment]
这是Incapsula的CDN incapsula的Proxy IP指的是CDN节点的IP
至于Access Denied则有可能是CDN安全组设定阻止了某一国家或者阻止了机房ip。

**Comment by zjl88858** [comment]
补充：
AS19551 | 45.64.64.0/24 | Incapsula Inc
https://bgp.he.net/ip/45.64.64.127

**Comment by BI7PRK** [comment]
Ok, 棒极了。现在我可以忽略那个代理IP。我准备查一下什么原因还能显示真实的访问来源。有结果再报告。感谢！

**Comment by BI7PRK** [comment]
严格测试结果出来了。是我自己的问题：
1、通过VPN通道连接。访问来源是VPN报务器的IP。这说明与浏览器无关
2、退出VPN，用SS连接，全局模式。一访问居然是真实来源。
3、Ctrl+F5...... 哇，变了。原来是浏览器缓存产生的错觉！

**Comment by celeron533** [comment]
> 我自己不能关闭 Issues？麻烦请项目管理员关闭。

自己是可以关闭issue的

**Comment by sxueck** [comment]
因为TCP Header会给你自动添加REMOTE_ADDR字段，而这是不可篡改的，如果你说获取到本地的公网IP，则是X-FORWARD首部的问题
