### ISSUE TITLE
forward proxy 异常：OutOfMemoryException

### ISSUE THREAD

**Issue by PikachuHy** [shadowsocks/shadowsocks-windows#1335]
`System.OutOfMemoryException`

![qq 20170822162147](https://user-images.githubusercontent.com/18223871/29555828-6b580c00-8756-11e7-8803-976c8b583d9a.png)

**Comment by chenshaoju** [comment]
看起来很像内存不足，但是我尚未遇到该问题。

请尝试将Shadowsocks.exe复制到一个新目录，手动重新配置看看？

**Comment by celeron533** [comment]
#693 也提到了`OutOfMemoryException`，而且也和TextWriter有关

**Comment by Flouse** [comment]
![image](https://user-images.githubusercontent.com/1297478/44843760-a096ea80-ac7b-11e8-9787-b3eb68cbd940.png)

**Comment by chenshaoju** [comment]
@Flouse 请不要到处发，移动到 https://github.com/shadowsocks/shadowsocks-windows/issues/1580#issuecomment-417260102 讨论。
