### ISSUE TITLE
无法下载Shadowsocks-4.0.5.zip，其他source code可以下载

### ISSUE THREAD

**Issue by HuanChen1025** [shadowsocks/shadowsocks-windows#1338]
github-production-release-asset-2e65be.s3.amazonaws.com 拒绝了我们的连接请求。

**Comment by HuanChen1025** [comment]
另外，ping github-production-release-asset-2e65be.s3.amazonaws.com ，网络是通的，0丢失， github-production-release-asset-2e65be.s3.amazonaws.com的ip是121.59.17.8

**Comment by pexcn** [comment]
开代理下载

**Comment by celeron533** [comment]
GFW已经介入了你的下载请求。接下来就是先有鸡还是先有蛋的问题了。
