### ISSUE TITLE
不开全局模式的话，打开国内的网站很慢

### ISSUE THREAD

**Issue by v2up** [shadowsocks/shadowsocks-windows#1339]
之前一直用PAC模式，不知道是新版本的问题还是一直就存在：
我这段时间发现打开国内的网站特别慢（貌似https的尤其更慢），比如说B站，天猫等。开了SS后，访问那些被墙的网站反而速度很快。
因此我想到如果所有网站都通过代理来访问，会不会解决这个问题，于是我切换到全局模式。果然，打开国内网站的速度恢复正常了！
这是什么原因呢，你们是怎么解决的？

操作系统：Win 10 pro
SS版本：4.0.5
浏览器：Chrome

**Comment by chenshaoju** [comment]
你好，请在 PAC 模式下访问 http://www.ip.cn ，显示的IP地址是你的服务器IP还是你的公网IP？

如果是服务器IP，说明你的浏览器设置有问题，请退出SS后参阅： https://github.com/shadowsocks/shadowsocks-windows/issues/1234#issuecomment-324923923

如果显示的是你的公网IP，说明你的网络配置有问题，请检查你的物理网卡的DNS是否为国内的DNS或电信的DNS。如果是国外的DNS，比如GoogleDNS，请修改为国内的DNS（ 114.114.114.114 / 223.5.5.5 ）或电信的DNS。

**Comment by paperbag** [comment]
- 你描述了PAC和全局的状况。但如果不走代理情况又是如何，是否也是很慢？
- 一种可能是：B站，天猫，你提到的这两个都使用了 CDN，而你的 DNS 设置不合适，导致访问了不合理的节点。
- 建议：按 F12 进入开发者工具，选择 Network 选项卡，并选上 Disable cache，在 **PAC 模式**下刷新观察是哪里加载比较慢。同时留意在 **PAC** 和**全局**下的 Remote Address 走的是本地代理（127.0.0.1:1080）还是直连。

![screenshot](https://user-images.githubusercontent.com/19257585/29740448-a1c450c4-8a89-11e7-8624-b00241112e60.PNG)

**Comment by v2up** [comment]
@paperbag 不走代理也很慢。
你这么说，我觉得真像你说的CDN的情况，因为迟迟加载不出来的主要是图片、视频这种资源。但是我的是校园网，自动填写DNS，这个你知不知道怎么办？
开发者模式看了，是直连（非localhost）。

总的来说，不是SS的锅，像是DNS的问题？

**Comment by v2up** [comment]
@chenshaoju 是服务器IP。对应你给的参考链接，我的Internet选项那三个选项都没有打勾，这样对不对？

**Comment by v2up** [comment]
@chenshaoju @paperbag 改了DNS，问题解决了！非常感谢两位的指导。

**Comment by chl19940220** [comment]
> * 你描述了PAC和全局的状况。但如果不走代理情况又是如何，是否也是很慢？
> * 一种可能是：B站，天猫，你提到的这两个都使用了 CDN，而你的 DNS 设置不合适，导致访问了不合理的节点。而走代理，访问的是国外的节点，避开了这一问题。
> * 建议：按 F12 进入开发者工具，选择 Network 选项卡，并选上 Disable cache，在 **PAC 模式**下刷新观察是哪里加载比较慢。同时留意在 **PAC** 和**全局**下的 Remote Address 走的是本地代理（127.0.0.1:1080）还是直连。
> 
> ![screenshot](https://user-images.githubusercontent.com/19257585/29740448-a1c450c4-8a89-11e7-8624-b00241112e60.PNG)

我也碰到了这个问题，发现访问B站走的是直连，DNS是校园网的ip地址，请问应该怎么解决，感谢~

**Comment by hclchimumu** [comment]
我也是校园网遇到同样的问题，修改DNS后解决了。果然是在校园网环境下容易发生这种问题吗。

**Comment by LuckyCurve** [comment]
修改了个DNS就可以了

**Comment by xiwypin** [comment]
👍

**Comment by coderbaozi** [comment]
兄弟怎么修改的dns可以教教马

**Comment by coderbaozi** [comment]
> 我也是校园网遇到同样的问题，修改DNS后解决了。果然是在校园网环境下容易发生这种问题吗。

兄弟，你的dns怎么修改的我现在也遇到了一样的情况

**Comment by coderbaozi** [comment]
> Reference

兄弟，你的dns是怎么修改的我也遇到了一样的情况
