### ISSUE TITLE
4.05在pc端无法使用，android使用正常

### ISSUE THREAD

**Issue by waterchinap** [shadowsocks/shadowsocks-windows#1340]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
最新版本4.05

### Environment(Operating system, .NET Framework, etc)
windows10 专业版 64位 版本号1607
.net framwork
据微软官方下载网站说明“在 Windows 10 周年更新和 Windows Server 2016 上，可在“控制面板”中的“已安装更新”下找到包 Microsoft Windows 更新 (KB3186568)。“我的应该是安装上了.net framwork4.7。
我在程序当中卸载了4.6,以及3.x版本的.net framwork

### Steps you have tried
切换过PAC和全局方式，都不能上网。
试过用netsh命令重置网络，无效。

### What did you expect to see?
希望能顺利上google.com等gfwlist上的网站，当无一成功。
墙内无问题。

### What did you see instead?
目前无法上被墙网站，墙内正常。
这个问题应该是最近才发生的，高度可能是.net framwork 产生的。

### Config and error log in detail (with all sensitive info masked)
日志如下，我看了一下，好象还没有人报告这个问题：

[2017-08-26 23:36:34] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by waterchinap** [comment]
重新安装了.net framwork 4.7仍然无法连接被墙网站。

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/476

**Comment by celeron533** [comment]
#1297

**Comment by waterchinap** [comment]
使用netsh 系列命令后重启，仍然无效。
清空temp文件，仍然无效。
出错信息和原来一样。
[2017-08-27 11:30:55] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

感觉一定是win10某次升级后产生的某种问题，此前一直可以使用。

**Comment by vitalzhu** [comment]
No,Windows7 也存在同样的问题。
大概是在2017年8月25日下午出现这个问题，我这边iOS，Mac上都没问题，只有Windows始终连接不上。

**Comment by waterchinap** [comment]
我不太能确定最后一次能用的准确时间，但确定8月26日升级后就不能使用了。如果windows7也出现了这种情况的话，看来和windows升级关系就不大了？

**Comment by lifeva** [comment]
感觉是4.0.5的问题，看来很普遍

**Comment by celeron533** [comment]
4.0.4 可以使用吗？

**Comment by digdig** [comment]
@celeron533 4.0.4不可以用，win7，我试了很多版本，都不可以用，但是mac使用无压力。4.05，3.4.3都不能用。我的也是8月24、25日突然上不了了，之前2.6的版本都用的正常。

**Comment by digdig** [comment]
@lifeva 感觉并非版本问题，是对应系统问题。

**Comment by waterchinap** [comment]
以前的版本也不能用，我两台win10都不能用了。而且更奇怪的是，三台安卓机，小米和kindle fire不能用，而三星还可以。。。那么，觉得目前来说，结论应该就是墙升级了。

**Comment by lifeva** [comment]
我的感觉是win10更新到某个版本以后，SS就不太给力了，升级版本也没有用。常常出错，重启后就好了，所以不是GFW升级。

**Comment by chenshaoju** [comment]
我自己的小笔记本就是Win10，但是我没这个问题……

这样，你有Firefox吗？给Firefox配置一个手动代理，直接走SS的SOCKS5端口，不走PAC，当IE或Chrome不工作的时候，试试Firefox能否工作？

这样可以用于区分到底是PAC的问题还是其它问题。

**Comment by wongsyrone** [comment]
用debug版本，走SOCKS5协议连接，如果使用了AEAD加密可以输出详细的流量信息
或者用wireshark抓包

**Comment by digdig** [comment]
楼上和楼上上的方法太高端了，留给开发者去测吧。作为小白只想用下软件。。。

**Comment by digdig** [comment]
不过我重启电脑后可以上了，不知道是否和[这个](https://github.com/shadowsocks/shadowsocks-windows/issues/476)有关。

**Comment by waterchinap** [comment]
@chenshaoju 我用firefox试过，一样失效。看起来，是在建立连接时就失效了，所以换浏览器没和代理方案都没变化。

**Comment by shikkoku** [comment]
我用最新版本创意者更新 15060.540 使用十分正常。Chrome+SwitchyOmega+4.0.5 AEAD加密。

**Comment by celeron533** [comment]
closed due to inactivity
