### ISSUE TITLE
用一段时间后就上不了被墙的网站了

### ISSUE THREAD

**Issue by Dakwu** [shadowsocks/shadowsocks-windows#1341]
不管是PAC模式还是全局模式，经常用几分钟或一段时间就不能上被墙的网站了（切换一下模式或重启下ss就又好了，但也只能维持一小段时间），但是用 youtube-dl却还能下载YouTube的视频，不知道是浏览器问题还是ss 的问题，系统是win10，ss 4.0.5

**Comment by chenshaoju** [comment]
请尝试以管理员身份运行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，执行完毕后请重新启动计算机，然后看看是否会解决该问题。

**Comment by celeron533** [comment]
无法使用的时候，察看一下你的IE代理设置是否被其他程序覆盖

**Comment by lifeva** [comment]
应该和我的现象一样，这时候要退出SS，重新启动，不过启动时会报错。已经提交了问题  @

**Comment by celeron533** [comment]
@Dakwu 为何close issue呢
