### ISSUE TITLE
希望添加服务器分组功能，在分组的基础上进行负载均衡

### ISSUE THREAD

**Issue by osdu** [shadowsocks/shadowsocks-windows#1342]
希望添加服务器分组功能，在分组的基础上进行负载均衡。

同一个SS服务商一般会提供多个服务器账号，可以将这一组账号进行负载均衡，现在的负载均衡实用性不佳。

**Comment by celeron533** [comment]
这个需求不常见

**Comment by ljhmily** [comment]
这个需求可以有 同服务器多分组还是很常见的

**Comment by celeron533** [comment]
有其他人反应负载均衡后IP在各个服务器之间乱飘，可能会被对方网站判定为恶意攻击或者刷流量机器人，严重的情况可能会被对方网站封禁帐号（比如PT账号、论坛账号等）

**Comment by coofo** [comment]
我也有类似的需求，有时候由于局部网络问题，比如某个海底光缆故障，或者某个国际出口问题，很希望将个别服务器从负载均衡中剔除。但是直接删的话之后又要新增。希望至少提供指定服务器不参与负载均衡的功能。

**Comment by mailsex** [comment]
我也有这个需求，我是用SS+kcptun ，走的UDP，同一个vps 我开了多个kcptun通道，做负载均衡，这样就能避免单个udp端口长时间使用被运营商QOS。

**Comment by chenshaoju** [comment]
该功能已经在讨论中，请移步：https://github.com/shadowsocks/shadowsocks-windows/issues/3040
