### ISSUE TITLE
win10+4.0.5，休眠回来基本就无法工作了，推出重启报错，要反复退出重启ss

### ISSUE THREAD

**Issue by lifeva** [shadowsocks/shadowsocks-windows#1343]
![tim 20170828111944](https://user-images.githubusercontent.com/11326402/29758024-d6bb4378-8be2-11e7-9a52-21e60608ac96.png)

**Comment by chenshaoju** [comment]
请检查是否启动了两个Shadowsocks，如果没有，请执行：
```
netstat -ano -p tcp
```
检查端口是否被占用。

**Comment by lifeva** [comment]
是伴随着休眠回来，无法正常工作发生的。

**Comment by lifeva** [comment]
[2017-08-28 16:37:23] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:23] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:23] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:23] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:24] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:26] GC1 (104.199.245.198:8989) timed out
[2017-08-28 16:37:27] GC1 (104.199.245.198:8989) timed out
[2017-08-28 16:37:28] GC1 (104.199.245.198:8989) timed out
[2017-08-28 16:37:29] GC1 (104.199.245.198:8989) timed out
[2017-08-28 16:37:31] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:31] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:32] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:32] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:32] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:32] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:33] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:34] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:39] GC1 (104.199.245.198:8989) timed out
[2017-08-28 16:37:40] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:41] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:42] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:42] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:42] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:43] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-08-28 16:37:43] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by chenshaoju** [comment]
是否启用了流量统计？如果是，请禁用看看。

**Comment by lifeva** [comment]
我有两台win10的机器，问题是一样的。统计配置页面只有一个打勾的。
![image](https://user-images.githubusercontent.com/11326402/29767453-13afe662-8c15-11e7-8234-586609d3188f.png)

**Comment by chenshaoju** [comment]
是否开启了日志的详细模式？

https://github.com/shadowsocks/shadowsocks-windows/issues/1335#issuecomment-325081107

**Comment by lifeva** [comment]
没有开启详细模式

**Comment by chenshaoju** [comment]
我在我的Win10上测试了一下，休眠后再唤醒，没遇到该问题。

如果可能，请尝试使用：  https://www.microsoft.com/en-us/download/details.aspx?id=30135 ，按照提示进行修复，如果提示要求重新.NET Framework，请从 https://www.microsoft.com/zh-CN/download/details.aspx?id=55170 下载并重新安装。

**Comment by celeron533** [comment]
报错日志似乎是在尝试调用`libsscrypto.dll`的时候发生了问题

任务管理器杀掉
`Shadowsocks`
`Privoxy`
然后重试

**Comment by lifeva** [comment]
@celeron533是的，每次解决的办法就是杀进程。但每次电脑休眠（一般是一晚上）回来，都要这么做才行。用SS两年了，只有最近才这样，估计是win10某个版本后，兼容性除了些问题。

**Comment by chenshaoju** [comment]
你用的Windows 10什么版本？补丁列表？因为这个现象比较罕见，我自己都没遇到过，很奇怪。

![2017-08-30 1](https://user-images.githubusercontent.com/515763/29851096-d013c7ba-8d64-11e7-8712-fef1b723b816.png)

**Comment by lifeva** [comment]
还有，是否可能是和Resilio sync冲突？因为最近这个软件设置了走sock5代理，有条件，可以测试下。
![tim 20170830093107](https://user-images.githubusercontent.com/11326402/29851332-16eb74c0-8d66-11e7-80b6-cb032515b02e.png)
![tim 20170830093029](https://user-images.githubusercontent.com/11326402/29851320-03308056-8d66-11e7-80c6-a03f3c4482ef.png)

**Comment by celeron533** [comment]
另外你的日志有没有成对的休眠、唤醒的记录？
```
[2017-08-29 20:52:30] os suspend
[2017-08-30 18:41:56] os wake up
```

**Comment by celeron533** [comment]
目前也没看到过其他人汇报有这个问题。。。

**Comment by bbb31313** [comment]
我遇到同样问题, 每次休眠后需要重启SS, 也是win10, 为最新版本, 应该是排除和win版本有关. 我也曾用过Resilio sync.

**Comment by bbb31313** [comment]
请问如何解决的? 我也遇到同样问题. 每次唤醒, 必须重启ss, 否则无法工作. 不会主动弹出任何提示窗.

**Comment by bbb31313** [comment]
> @bbb31313 [#1343 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/1343#issuecomment-326013472)

日志中 有 os suspend  的记录, 但并无 os wake up 的

**Comment by chenshaoju** [comment]
你使用的是最新的 4.1.2 吗？

**Comment by bbb31313** [comment]
> 你使用的是最新的 4.1.2 吗？

是的.

**Comment by celeron533** [comment]
@bbb31313
看来是操作系统在唤醒的时候没有激活唤醒事件导致了异常，用的是Windows insider之类的版本吗？硬件是surface pro？

**Comment by bbb31313** [comment]
> @bbb31313
> 看来是操作系统在唤醒的时候没有激活唤醒事件导致了异常，用的是Windows insider之类的版本吗？硬件是surface pro？
硬件为thinkpad , 然后是预装的win10 家庭版.    和本issue 的提出者相同, 我也安装过Resilio Sync, 但已经卸载.
