### ISSUE TITLE
网易UU加速游戏会影响shadowsocks-windows 4.0.5

### ISSUE THREAD

**Issue by liuxyc** [shadowsocks/shadowsocks-windows#1344]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.5

### Environment(Operating system, .NET Framework, etc)
Win10 

### Steps you have tried
开启shadowsocks-windows 4.0.5，可以正常通过chrome的SwitchyOmega通过sock5访问google（并不需要开启shadowsocks-windows的代理模式）
启动网易UU，启动模式4的游戏加速。

### What did you expect to see?
chrome正常访问google

### What did you see instead?
通过chrome访问google失败，报连接已重置，shadowsocks-windows的日志中出现如下错误：

```
[2017-08-29 21:25:08] connect to play.google.com:443
[2017-08-29 21:25:08] System.Net.Sockets.SocketException (0x80004005): 在一个非套接字上尝试了一个操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-08-29 21:25:15] connect to mtalk.google.com:443
[2017-08-29 21:25:15] System.Net.Sockets.SocketException (0x80004005): 在一个非套接字上尝试了一个操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-08-29 21:25:15] System.Net.Sockets.SocketException (0x80004005): 在一个非套接字上尝试了一个操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
```

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
请尝试以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
然后重启计算机再试试。

PS：网易UU请使用模式四试试。

**Comment by liuxyc** [comment]
@chenshaoju 按你描述的做法试了，无效

**Comment by celeron533** [comment]
`netsh winsock reset` 重置完LSP后需要重启
