### ISSUE TITLE
Shadowsocks windows 客戶端沒有 simple-obfs ,請問能否下一版本內置simple-obfs呢? 感謝

### ISSUE THREAD

**Issue by la88962** [shadowsocks/shadowsocks-windows#1347]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
#1252

**Comment by tangshiba** [comment]
@celeron533 早就看到已经合并了插件的代码，一直在等着发布！

**Comment by pexcn** [comment]
试了一下，cygwin 编译的 simple-obfs 速度最快只有 300 多 kb/s

**Comment by wongsyrone** [comment]
除非用C#实现obfs逻辑，不然慢就慢咯

**Comment by 023Sparrow** [comment]
您似乎发错了邮箱XD

Sent from YoMail

**Comment by RemiDre** [comment]
我试了加obfs和不加obfs速度一样快。。。应该是我这里没有qos
