### ISSUE TITLE
咱们官网是那个

### ISSUE THREAD

**Issue by muzisanjin725** [shadowsocks/shadowsocks-windows#1348]
官网是那个服务器 现在的服务器不能用了 我得添加服务器

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 没有官网服务器。

如果你是在某个网站上购买的服务，该网站和Shadowsocks for Windows没有关系。

请与你的SS服务商取得联系。

**Comment by pexcn** [comment]
他说的应该是这个：https://github.com/shadowsocks/shadowsocks-org ?

**Comment by WLZLCX** [comment]
你想多了，哈哈哈哈...
