### ISSUE TITLE
ss 4.0.5 win7 UDP

### ISSUE THREAD

**Issue by hu-bobo** [shadowsocks/shadowsocks-windows#1349]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
ss 4.0.5 win7 支持udp转发吗？如果支持，怎么开启呢。
其实我只是想打美服lol，然而延迟有点高，用了sockscap64，然而进地图就掉线。求帮助啊-.-

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
你用的SS服务端开启了UDP支持吗？Shadowsocks for Windows 是支持的，但是仍然需要你的代理软件和服务端支持。

**Comment by drcayman** [comment]
@chenshaoju   shadowsocks-windows  支持udp了？不需要使用sstap之类的软件

**Comment by drcayman** [comment]
@chenshaoju   shadowsocks-windows 支持udp了？不需要使用sstap之类的软件？ 请帮忙回答下

**Comment by chenshaoju** [comment]
支持的，但是你的应用需要支持SOCKS5 UDP代理：
https://github.com/shadowsocks/shadowsocks-windows/wiki/Shadowsocks-Windows-使用说明#udp

**Comment by Crafsman** [comment]
`upd`
