### ISSUE TITLE
通过热点共享后不能翻墙

### ISSUE THREAD

**Issue by zxam** [shadowsocks/shadowsocks-windows#1350]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.05

### Environment(Operating system, .NET Framework, etc)
win10 1703

### Steps you have tried
已开启全局模式，开启win10热点共享，开启关闭lan代理都尝试过
开启和关闭防火墙也试过了

### What did you expect to see?
的确，是可以在局域网中通过手机代理设置o墙。
但是kindle没有代理选项，无法连接局域网再设置，只能开热点。
如果用vpn，打开电脑热点后不需再在手机中设置即可o墙，希望用ss也可。

### What did you see instead?
但用kindle连接上此热点后，和直连的效果是一样的，相当于没有开ss，国内网站可以打开。

查找了相关网站，只有用局域网的方法。请问怎样设置能够实现所需结果呢？

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
Windows 10 热点模式不支持全局模式或PAC模式。

**Comment by zxam** [comment]
可以通过其他热点软件吗

**Comment by chenshaoju** [comment]
没有用过，不知道。。。你可以试试。

**Comment by suikatomoki** [comment]
https://www.sockscap64.com/ja/forums/topic/%E5%B0%86sstap%E8%99%9A%E6%8B%9F%E7%BD%91%E5%8D%A1%E5%85%B1%E4%BA%AB%E7%BB%99%E5%90%8C%E5%B1%80%E5%9F%9F%E7%BD%91%E5%85%B6%E5%AE%83%E7%9A%84%E4%B8%BB%E6%9C%BA%E3%80%81%E6%8E%8C%E6%9C%BA%E3%80%81
