### ISSUE TITLE
最近几个新版本内存占用过大

### ISSUE THREAD

**Issue by sniperhalo** [shadowsocks/shadowsocks-windows#1351]
虽然只有6-7M但是我的任务管理器排名还是靠前（次于defender），杂七杂八的进程加起来其他大程序就容易卡了（我的内存惭愧的只有4G还运行着64win10），能降下更好，希望作者精简一下优化一下！！

**Comment by chenshaoju** [comment]
不错了，我的２４ＭＢ。

![image](https://user-images.githubusercontent.com/515763/29994956-52e34984-900f-11e7-92bb-94f5c5a2d1d5.png)

**Comment by celeron533** [comment]
关掉360以优化性能

**Comment by tangshiba** [comment]
6.7M的内存很多吗= =
骚年，加内存吧。这才是根本原因。

**Comment by kkkkke** [comment]
不需要吧，随便一个开着youtube的chrome进程就300mb内存了
