### ISSUE TITLE
谁能帮忙开发一个xbox上用的ss app，愿意付费

### ISSUE THREAD

**Issue by doubledonkey** [shadowsocks/shadowsocks-windows#1352]
谁能帮忙开发一个xbox上用的ss app，愿意付费

**Comment by lixingcong** [comment]
买个路由器才50包邮

**Comment by suikatomoki** [comment]
把钱和地址给我 我去帮你买路由器
https://cokebar.info/archives/664

**Comment by cokebar** [comment]
路由器透明代理的话 之前xbox上udp不通 无法代理游戏 ps4是碎片封包 影响部分功能 (see #361)
最近测试了3.0.8版本 ps4碎片封包现象消失  xbox就不清楚了 谁来测试一下(TCP/UDP全局代理)

**Comment by doubledonkey** [comment]
我的意思是开发一个微软商店里的app，可以在xbox上直接下载使用，和windows client一样，不使用路由器。

**Comment by chenshaoju** [comment]
实话实说，这种就算上架了，也会被限区或者强制下架，参考Apple Store大规模下架VPN事件。

**Comment by h2y** [comment]
ss是应用层代理，确实会导致部分游戏连接错误。
解决方式是使用数据链路层代理vpn，不过使用vpn翻墙容易被gfw检测。

**Comment by cokebar** [comment]
@h2y ss支持TCP/UDP proxy，TCP/UDP是传输层，不是应用层。如果一个游戏都是Client/Server模型的通讯，那就可以正常代理。但如果有直接Client to Client的通讯，那就可能出问题。当Client双方都出于NAT后时，需要NAT穿透技术才能使得Client之间能够通讯，比如说STUN的UDP打洞（PS4的网络检测里检测NAT类型时候用的就是STUN）。然而UDP通讯如果再加层透明代理，对于此类打洞技术将变得很不友好，可能使之失效。使用VPN则可以规避这个问题。有些VPN也是有这类似ss的特点，避免GFW的检测；或者使用诸如cisco anyconnect这种比较特殊的vpn也可能防止被封。

**Comment by celeron533** [comment]
@cokebar openvpn over SS

**Comment by ku8h96de4** [comment]
> 
> 
> 实话实说，这种就算上架了，也会被限区或者强制下架，参考Apple Store大规模下架VPN事件。

......xbox玩家谁用国区啊，如何下架。
