### ISSUE TITLE
Win XP如何使用ss?

### ISSUE THREAD

**Issue by RuikangSun** [shadowsocks/shadowsocks-windows#1353]
XP系统无法安装安装.NET Framework 4.6.2,在学校机房无法使用Win 7。

**Comment by chenshaoju** [comment]
你仍然可以使用 2.5.6 版本的Shadowsocks for Windows，在 https://github.com/shadowsocks/shadowsocks-windows/releases/tag/2.5.6 获取。

**Comment by celeron533** [comment]
或者使用qt以及python版客户端

**Comment by suikatomoki** [comment]
go版

**Comment by w153140** [comment]
试了下XP最高版本是3.2
https://github.com/shadowsocks/shadowsocks-windows/releases/tag/3.2

**Comment by AiYooooo** [comment]
如果提示.Net framework有问题，可以安装这个 https://www.microsoft.com/en-us/download/details.aspx?id=17851 然后就可以正常使用了
