### ISSUE TITLE
如何保留自定义 PAC 规则

### ISSUE THREAD

**Issue by bruceCzK** [shadowsocks/shadowsocks-windows#1354]
开了保护本地 pac，试过编辑了一下 pac 文件，下一次从 GFWList 更新以后就会覆盖掉自定义的规则。

**Comment by chenshaoju** [comment]
看看有无 user-rule.txt 文件，如果没有，右击托盘区的纸飞机小图标，选择PAC，选择编辑用户的 GFWList 规则。

**Comment by bruceCzK** [comment]
@chenshaoju 多谢，搞定了
