### ISSUE TITLE
全局模式 无法更改IP地址 不能o墙

### ISSUE THREAD

**Issue by hgwd520** [shadowsocks/shadowsocks-windows#1355]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!
前段时间路线可以正常使用 可变更IP为服务器位置 可访问U2B 谷歌等网站 

现在使用全局或者PAC模式 都无法更改 ip地址  无法访问国外网站
重置网络设置也试过了 
线路应该是没问题 还在有效期 

### Config and error log in detail (with all sensitive info masked)

**Comment by paperbag** [comment]
> 还在有效期

那你应该问去你的 ss 服务提供商。

PS.每次看到如此的 issue 都想甩个链接：[提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)。好歹照着模板把版本什么的都填一下啊。

这里莫有敏感词审查，不用使用o墙，看着很难受。
