### ISSUE TITLE
中国移动光纤无法连接服务器

### ISSUE THREAD

**Issue by AlanNeverStopWin** [shadowsocks/shadowsocks-windows#1356]
连接就显示超时，而且手机上也是无法连接，更换为4G网络后又可以连接上了。

**Comment by w153140** [comment]
换个SS试试？

**Comment by OMICRON3069** [comment]
试试 ping 命令能不能 ping 通服务器，或者 tcping 试一下端口是不是通的？

**Comment by shikkoku** [comment]
请联系你的服务提供商。

**Comment by celeron533** [comment]
>试试 ping 命令能不能 ping 通服务器，或者 tcping 试一下端口是不是通的？

补充：有时候仅仅封TCP和UDP的特定端口，ICMP的ping畅通无阻。
也就是说，不能ping，基本挂了；能ping，只能说明服务器在线，特定端口的情况还是未知
