### ISSUE TITLE
【firefox 55.0.3 (32 位) + shadowsocks 4.0.5】PAC模式部分网址不起作用

### ISSUE THREAD

**Issue by kyzypm** [shadowsocks/shadowsocks-windows#1357]
例如：https://www.google.com 可以访问
然而：https://www.kyzyhello.com 却无法访问

**Comment by paperbag** [comment]
我测试了一下，没有发现问题，我这边火狐的确走了代理。

测试环境：
Firefox 55.0.3 (64-bit)
shadowsocks 4.0.5
![screenshot](https://user-images.githubusercontent.com/19257585/30045078-6d011c98-9234-11e7-888e-e7595133a18a.png)

**Comment by wongsyrone** [comment]
这是他们家的广告，看看名字

kyzypm
kyzyhello[.]com

**Comment by paperbag** [comment]
雾 看了一下 还真是
https://github.com/Hackl0us/Surge-Rule-Snippets/issues/15

**Comment by celeron533** [comment]
https://github.com/gfwlist/gfwlist/issues/714

**Comment by kyzypm** [comment]
额，我申请这个东西当然是为了自己的网站了，我提出网站是为了求助大神帮助不是打广告好不好，前段时间因为打广告网站被墙了，现在都不敢打广告了，再说了这里打广告的功夫还不如去百度贴吧打广告，只是求助作者，你们可以忽略，相信就算是广告你们也不会去购买，何必呢，把自己那套逻辑套在别人身上以为自己见识很广？


奇怪
![default](https://user-images.githubusercontent.com/23031031/30045876-635c2660-9239-11e7-86d3-990085218b97.png)

**Comment by kyzypm** [comment]
ie和chrome倒是没问题，可能是firefox的问题

**Comment by kyzypm** [comment]
![default](https://user-images.githubusercontent.com/23031031/30045947-de08baa4-9239-11e7-9bd9-50646852b1b5.png)

**Comment by JonasGao** [comment]
@kyzypm 看你最后的截图，已经解决了？

解决了就 close 一下吧~

**Comment by kyzypm** [comment]
没弄好
