### ISSUE TITLE
关于代理模式

### ISSUE THREAD

**Issue by King-Ye** [shadowsocks/shadowsocks-windows#1358]
在开启全局模式后，使用命令行 (例如Python的pip )访问国外站点能得到一个较好的结果。
但对于大陆内站点加载速度就堪忧，甚至无法加载。

建议全局模式增加绕过国内IP和局域网IP的功能。

**Comment by chenshaoju** [comment]
建议你为你的Python pip设置代理。

https://www.google.com/search?newwindow=1&safe=off&q=Python%20pip%20proxy&cad=h

**Comment by King-Ye** [comment]
如果除了pip，也需要使用其他的例如yum。
难道只能手动一个个配置？

发这个issue只是建议你们也加一个这个而已。
我正在自己修改客户端给自己用。么么哒

**Comment by chenshaoju** [comment]
你可以在你的PAC里加入你想要代理的地址，这个功能有人提过，详见 https://github.com/shadowsocks/shadowsocks-windows/issues/1270

**Comment by King-Ye** [comment]
好的，谢谢，我去参考一下

**Comment by wencheng1994** [comment]
但是mac版本的ssr如何做这个设置呢？
