### ISSUE TITLE
请问软件右键菜单里边的正向代理设置怎么用？我设置了IP和端口还是不可以用，为什么还要设置IP地址？

### ISSUE THREAD

**Issue by 1462326016** [shadowsocks/shadowsocks-windows#1359]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
如果你上网要通过代理服务器（Socks5 Proxy），则需要设置。

如果你不通过代理服务器上网，则不需要设置，错误的设置会导致无法使用。

**Comment by 1462326016** [comment]
我通过ss连接到了一个服务器，而且通过认证了，可以用，然后我本地设置代理127.0.0.1:1080可以通过代理上网，没问题，那么这个时候正向代理有什么用（这个时候不设置正向代理就可以正常使用）‘？或者说我应该在什么时候用它？

**Comment by chenshaoju** [comment]
请仔细阅读第一句话。

如果你上网需要通过一个代理服务器才能上网，就需要设置。

如果你是直连路由器／光猫上网的，就不需要设置，除非你有特殊需求。

**Comment by 1462326016** [comment]
也就是说可以通过两种方法代理进行上网？一是通过正向代理，用网上不需要认证的代理服务器通过正向代理来上网，这时候ss只相当于一个代理服务器，二是通过ss的IP端口和密码来上网，？是不是这个意思？那如果两个都设置了会不会冲突？或者只用一个？

**Comment by chenshaoju** [comment]
１.如果你设置的代理服务器有效，那么就可以通过SS访问互联网。
２.正向代理和本地代理无关，两个不同的功能。

你可能不知道什么是代理服务器，请先阅读：
https://zh.wikipedia.org/zh-hans/%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by 1462326016** [comment]
我懂了，谢谢你
