### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by LenKiMo** [shadowsocks/shadowsocks-windows#1361]
### Version(release version or AppVeyor link)
4.0.5

### Environment(Operating system, .NET Framework, etc)
Windows 10 Pro 1703 64-Bit
.NET Framework 4.7

### Steps you have tried
Nothing. It will occur by itself when I do nothing, but with programs have internet connection through it.
Maybe occur when come back from sleep.（可能发生于从电脑锁屏状态恢复后）

### What did you expect to see?
An Error message box. After close it Shadowsocks will exit by itself.

### Config and error log in detail (with all sensitive info masked)
Error Message:
https://i.loli.net/2017/09/06/59afb2cd19d3e.png

It seems like log(Even in advanced mode) records nothing.

**Comment by celeron533** [comment]
Related to #906
