### ISSUE TITLE
global 模式 IP 不变

### ISSUE THREAD

**Issue by skyline9002** [shadowsocks/shadowsocks-windows#1362]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
Client : Shawdowsocks 4.05 Window

### Environment(Operating system, .NET Framework, etc)
Window 10

### Steps you have tried
人在国外，没有墙，但是想学习ss。服务器用azure搭建好，客户端使用global模式，IP不变。使用pac模式IP 变了。 完了用2.05的客户端，global模式，IP也变了。有大神知道是为什么吗？

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
你用的什么浏览器？IE还是edge？

**Comment by skyline9002** [comment]
使用的chrome浏览器

**Comment by celeron533** [comment]
chrome可能有缓存。

**Comment by JeffcottLu** [comment]
我也测试了一下，chrome显示的是真实IP，firefox显示的是代理IP；chrome是自建了一套IP缓存池吗？还是通过机器多次连接的不同IP决策出来的？

**Comment by chenshaoju** [comment]
如果你的Chrome使用了某些代理插件，可能会忽略PAC／全局设置。具体的，请参考你的Chrome所使用的插件说明。

![image](https://user-images.githubusercontent.com/515763/35376383-d8a7ba44-01e5-11e8-8c2e-5f0a1ea2dd38.png)
