### ISSUE TITLE
UDP relay does not work with IPv6

### ISSUE THREAD

**Issue by Vohrt** [shadowsocks/shadowsocks-windows#1364]
Version:4.0.5
Environment:Windows 10 1703
直连服务器ipv4地址，udp可用
![default](https://user-images.githubusercontent.com/9927908/30163485-bf3a0d70-940b-11e7-978a-b51743396f05.JPG)
使用本地SOCKS5连接ipv4 udp 可用
![2](https://user-images.githubusercontent.com/9927908/30163568-02c67fec-940c-11e7-9b99-de241233af59.JPG)
使用本地SOCKS5链接ipv6 udp不可用
![3](https://user-images.githubusercontent.com/9927908/30163611-1de5f8ca-940c-11e7-949c-cdf1b7fd927b.JPG)
使用linux路由器内置ss客户端链接ipv6 udp可用
![4](https://user-images.githubusercontent.com/9927908/30163650-4a360190-940c-11e7-83d9-258dab6712d3.JPG)

**Comment by wongsyrone** [comment]
https://blogs.msdn.microsoft.com/webdev/2013/01/08/dual-mode-sockets-never-create-an-ipv4-socket-again/

**Comment by wongsyrone** [comment]
我用SSTap测了ipv4的udp转发，不过没有v6的环境，所以没法测试。如果你

1. Windows Vista 及以上
2. 使用**非**AEAD加密

可以尝试 https://ci.appveyor.com/project/wongsyrone/fuckshadows-windows/build/1.0.208
这里面用了dual mode socket，不过不知道能否正确处理v6情况，如果不能最好抓包出来看看。

**Comment by rainbowcandy** [comment]
@wongsyrone https://ci.appveyor.com/project/wongsyrone/fuckshadows-windows/build/1.0.208
经测试，这个版本能够正确转发v6下的udp，非常感谢。
![default](https://user-images.githubusercontent.com/9927908/30241060-044d7934-95af-11e7-8b21-aa64b54c9c79.JPG)

**Comment by wongsyrone** [comment]
这个是用TAP+SocketAsyncEventArgs重写网络部分的私人分支。如果你不用AEAD加密的话，可以一直用。
顺便可以对比一下和这里版本的速度差别。

**Comment by Julymycin** [comment]
请问是如何解决的，之前这个链接显示：构建未找到或访问被拒绝。
