### ISSUE TITLE
非预期错误 System.Windows.Interop.OSVersionHelper

### ISSUE THREAD

**Issue by gitleej** [shadowsocks/shadowsocks-windows#1365]
TypeInitializationException: The type initializer for 'System.Windows.Interop.OSVersionHelper' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'IsWindows10RS2OrGreater' in DLL 'PresentationNative_v0400.dll'. at System.Windows.Interop.OSVersionHelper.IsWindows10RS2OrGreater() at System.Windows.Interop.OSVersionHelper..cctor() --- End of inner exception stack trace --- at System.Windows.Interop.HwndTarget.InitProcessDpiAwareness() at System.Windows.Interop.HwndTarget.InitializePrimaryDpiScale() at System.Windows.Interop.HwndTarget..ctor(IntPtr hwnd) at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters) at GlobalHotKey.HotKeyManager..ctor() at Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller) at Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
看起来很像 .NET Framework 未能正确初始化，请问操作系统和.NET Framework版本是？
