### ISSUE TITLE
Shadowsocks-windows cannnot recognize URL generated by itself

### ISSUE THREAD

**Issue by CKrome** [shadowsocks/shadowsocks-windows#1367]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Windows 10 Pro x64 1703 

### Steps you have tried
I exported URL from Shadowsocks-windows 4.0.5 and found it cannot be  imported into version 4.0.6.
And I also tried generate URL in version 4.0.6, but it generated the same URL as 4.0.5. So it also cannot be imported into 4.0.6.

### What did you expect to see?
URL imported properly.

### What did you see instead?
Nothing happened.

### Config and error log in detail (with all sensitive info masked)
All logs are simply Shadowsocks started

**Comment by celeron533** [comment]
Bug.
```
        Uri parsedUrl;
        try
        {
             parsedUrl = new Uri(serverUrl);
        }
        catch (UriFormatException)
        {
            continue;
        }
```
URL such as `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpwYXNzd29yZEAxMjcuMC4wLjE6ODM4OA==#local+debug` would be processed as 'UriFormatException; Invalid URI'

**Comment by celeron533** [comment]
A quick workaround is to remove `==` in the first part of your URL and then try again.

**Comment by celeron533** [comment]
Hi @CKrome , there is a test build, could you please verify?

https://ci.appveyor.com/project/celeron533/shadowsocks-windows-3j4p4/build/job/vwjmrxywgino2m2e/artifacts

**Comment by CKrome** [comment]
@celeron533 
After removed ==, URL imported successfully( version 4.0.6 )
And the new test build works! All my URLs were properly imported.

**Comment by celeron533** [comment]
new commit build

https://ci.appveyor.com/project/celeron533/shadowsocks-windows-3j4p4/build/job/o7t5t9jjpgxn8onc/artifacts
