### ISSUE TITLE
淘宝也放到pac里面了啥意思

### ISSUE THREAD

**Issue by xieshen947** [shadowsocks/shadowsocks-windows#1369]
initiative_id=tbindexz_20170910

这个ID是你的吧？
取消代理了谷歌、youtube还能上，谷歌你可以说有DNS缓存，YOUTUBE呢，你告诉我这是真的取消了吗？

**Comment by pexcn** [comment]
莫名其妙

**Comment by chenshaoju** [comment]
你好，这个现象可能是你的运营商劫持了你的淘宝访问并加入了一个返利连接。

请与你的网络服务商联系。

另外，PAC列表（GFWList）不归Shadowsocks for Windows控制，关于完整的列表，你可以参阅：https://github.com/gfwlist/gfwlist/blob/master/gfwlist.txt

**Comment by paperbag** [comment]
> 这个现象可能是你的运营商劫持了你的淘宝访问并加入了一个返利连接。

不是返利链接。initiative_id 参数是淘宝自己加的，刚才我在淘宝上搜索了一下就复现了这一问题。@chenshaoju

**Comment by chenshaoju** [comment]
那么，这个参数和PAC有什么关系？

我刚在未使用SS的计算机上搜了一下OnePlus 5，也加上了这个参数。

**Comment by paperbag** [comment]
我去看了一下 gfwlist，这是他不懂正则造成的误会，事实上 `@@||taobao.com` 是把淘宝排除出去了。@chenshaoju

**Comment by xieshen947** [comment]
那么请问 关闭之后能上youtube是什么原因

**Comment by chenshaoju** [comment]
你可能是用了某些Hosts。

**Comment by celeron533** [comment]
PAC只能定义那些地址走不走代理，没有能力修改你的请求。
这种行为可能是本机网络或者是运营商劫持导致。
