### ISSUE TITLE
Always throw an exception about 'the port is occupied' when I change the shadowsocks setting and use the  obfs-local plugin

### ISSUE THREAD

**Issue by juneszh** [shadowsocks/shadowsocks-windows#1370]
I think its cause the last obfs-local.exe process haven‘t killed then the shadowsocks try to run obfs-local.exe again when it's reload config

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Windows 10

**Comment by juneszh** [comment]
![exception](https://user-images.githubusercontent.com/2436252/30248073-dfd2e13e-9653-11e7-8ba0-68bd2b83a9bf.png)

**Comment by chenshaoju** [comment]
请检查是否启动了多个SS，或者有其他应用占用了 1080 端口。

你也可以检查 gui-config.json 文件，找到 "localPort": 1080, ，将 1080 修改为其他端口然后重试。

**Comment by juneszh** [comment]
@chenshaoju No, It's just happened when I using the obfs-local plugin and change shadowsocks setting

**Comment by chenshaoju** [comment]
4.0.6 already have builtin obfs plugins.
Please check https://github.com/shadowsocks/shadowsocks-windows/issues/1368#issuecomment-328313914

**Comment by juneszh** [comment]
@chenshaoju Sorry, you may misunderstand my issure. My shadowsocks-windows and obfs-local.exe is working fine. Just when I change the shadowsocks setting then it's throw the exception like that screenshot.

But, If I kill the obfs-local.exe process before change shadowsocks setting, it's work.

So, I think this issure is cause the shadowsocks try to run obfs-local.exe again when it's  been changed setting, but unfortunately the last obsf process is still running.

**Comment by chenshaoju** [comment]
interesting,I will test it soon.

**Comment by codexss** [comment]
更换服务器时有几率会出现这个问题，不知道是不是obfs-local.exe的缺陷

**Comment by celeron533** [comment]
Could you please upload your `gui-conf` file. Please remember to sanitize you server and password.

**Comment by juneszh** [comment]
@celeron533 here you are.
[gui-config.zip](https://github.com/shadowsocks/shadowsocks-windows/files/1305791/gui-config.zip)

**Comment by celeron533** [comment]
本地进行了简单测试，仅切换服务器，没有传输数据。未重现这个问题，奇怪
```
    {
      "server": "127.0.0.1",
      "server_port": 1921,
      "password": "password",
      "method": "chacha20-ietf-poly1305",
      "plugin": "plugin\\obfs-local",
      "plugin_opts": "obfs=tls;obfs-host=www.baidu.com",
      "remarks": "local debug",
      "timeout": 5
    },
    {
      "server": "127.0.0.1",
      "server_port": 1921,
      "password": "password",
      "method": "chacha20-ietf-poly1305",
      "plugin": "plugin\\obfs-local",
      "plugin_opts": "obfs=tls;obfs-host=www.baidu.com",
      "remarks": "local debug2",
      "timeout": 5
    }


  "localPort": 1921,
```

**Comment by codexss** [comment]
有这个弹窗的时候手动退出SS进程obfs-local没有杀干净需要手动任务管理器结束……

**Comment by yyysuo** [comment]
因为obfs支持local端添加插件和不添加插件两种连接方式，即对于libev版本的ss，服务端部署后，local端既可以启用也可以不启用，复制一份不启用obfs的ss配置，添加obfs参数后，在本地占用的都是同一个端口，IP也都是同一个IP，所以就报端口被占用的错误了，不知道这种错误应该由ss-win来改来是obfs-local来改。

**Comment by billysingo** [comment]
同样的问题。使用obfs并且正在跑流量的时候如果切换到另一个使用obfs的节点很大几率出现此错误

**Comment by celeron533** [comment]
>同样的问题。使用obfs并且正在跑流量的时候如果切换到另一个使用obfs的节点很大几率出现此错误

客户端这边是不是有不止一台server配置了插件？

**Comment by celeron533** [comment]
>同样的问题。使用obfs并且正在跑流量的时候如果切换到另一个使用obfs的节点很大几率出现此错误

一个可能的原因
https://stackoverflow.com/a/5106755/2075611

**Comment by celeron533** [comment]
额，猜测到一个可能的原因
当更换服务器或者进行任何配置变化的时候，`_listener`会通过`_tcpSocketClose()`和`_udpSocketClose()`关闭连接。然后立刻再重开端口监听。
大流量下tcp不能在第一时间关闭导致端口不能及时释放？

**Comment by studentmain** [comment]
两年以来未见更多报告，obfs插件也已停止更新，先关了。如果问题还在，可以重开。
