### ISSUE TITLE
{EMERGENCY} sip003 properly setup on win client

### ISSUE THREAD

**Issue by asmadeus08** [shadowsocks/shadowsocks-windows#1372]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Win10 x64, Net 4.7

### Steps you have tried
gui config

  "configs": [
    {
      "server": "",
      "server_port": ,
      "password": "",
      "method": "aes-256-cfb",
      "plugin": "obfs-local",
      "plugin_opts": "obfs=tls;obfs-host=cloudfront.net",
      "remarks": "ss",
      "timeout": 6
    }
and on server side it's look like this:

{
    "server":"",
    "server_port":,
    "password":"",
    "timeout":600,
    "method":"aes-256-cfb",
     "plugin":"obfs-server",
     "plugin_opts":"obfs=tls"
}

### What did you expect to see?
I wanna see working obfs tunnel support in win client

### What did you see instead?
https://www.upload.ee/image/7445106/1111.jpg

### Config and error log in detail (with all sensitive info masked)

So i need detail guide how to setup it properly. anyone please help to me.

**Comment by hweidz** [comment]
same problem, just leave  plugin & plugin_opts blank right now, it works too

**Comment by asmadeus08** [comment]
It's work as usual ss connection but i want to include obfs option into ss win version cause i'm already created obfs plugin on my vps

**Comment by celeron533** [comment]
You must have obfs.exe in the same folder and fill its file path in the  plugin field

**Comment by asmadeus08** [comment]
@celeron533 can you help me with that and tell where to get that obfs.exe and what must to be there?

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1368

**Comment by asmadeus08** [comment]
@chenshaoju So that's what i did:
1 Got from here https://github.com/imgk/simple-obfs-Cygwin/releases ss-local and cygwin1.dll then put it on my ss folder
2 Created shortcut of ss-local.exe with the next parameter: ss-local -c user-config.json --plugin obfs-local --plugin-opts "obfs=tls;obfs-host=www.baidu.com"
3 For shadowsocks client i put:
plugin: obfs-local
plugin-opts: obfs=tls;obfs-host=www.baidu.com

Am I right? Or maybe need to do something another?

**Comment by sunkaigoon** [comment]
@celeron533 用auth_sha1_v4 插件 参数为tls1.2_ticket_auth 会报找不到文件的错误。不能这样用吗？

**Comment by chenshaoju** [comment]
@sunkaigoon 你好，你使用的是SS还是SSR？插件是单独的 .exe 插件吗？如果是，从那里获取的？

**Comment by sunkaigoon** [comment]
@chenshaoju 是解析的ssr链接

**Comment by chenshaoju** [comment]
@sunkaigoon SS和SSR只能单向互通，SS不支持SSR的混淆模式，所以。。。。
