### ISSUE TITLE
Unexpecting error 非预期错误 - 访问拒绝

### ISSUE THREAD

**Issue by GeekShane** [shadowsocks/shadowsocks-windows#1373]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Windows10, 64bit

### Steps you have tried
Tried to open

### Config and error log in detail (with all sensitive info masked)

System.UnauthorizedAccessException:对路径"C:\user-wininet.json"的访问被拒绝。
在System.IO._Error.WinIOError(Int32 errorCode, String maybeFullPath)
在System.IO.FileStream,.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs,
String msgPath,Boolean bFormProxy, Boolean useLongPath, Boolean checkHost)
在System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
在Shadowsocks.Util.SystemProxy.Sysproxy.Save()
在Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean
enable, Boolean global, String proxySever, String pacURL)
在Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACSever pavSrv)
在Shadowsocks.Controller.ShadowsocksController.Reload()
在Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
对于启用了UAC的系统，默认情况 C:\ 根目录没有写入权限。
请新建一个目录，比如 C:\SS\ ，然后放进去。
