### ISSUE TITLE
4.0.6无法解析二维码

### ISSUE THREAD

**Issue by 01-Liny** [shadowsocks/shadowsocks-windows#1374]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Win7

### Steps you have tried
分享服务器配置，然后识别屏幕上二维码，显示无法解析二维码，从剪贴板导入URL也没反应

### What did you expect to see?
可以正常解析分享的二维码

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
该问题确认， Windows 7 + 4.0.6 复现。

@celeron533

**Comment by celeron533** [comment]
dup to #1367

**Comment by wangkairong** [comment]
我在win10上也有这个问题

**Comment by sophauer** [comment]
该问题确认， Windows 10 复现

**Comment by emilyzhao21** [comment]
windows 10 无法解析二维码

**Comment by plzcallmeleon** [comment]
同Win10 出现这个问题 下回4.0.5没问题

**Comment by time137** [comment]
Win10 大部分二维码无法解析

**Comment by celeron533** [comment]
请使用这个build测试一下  https://ci.appveyor.com/project/celeron533/shadowsocks-windows-3j4p4/build/job/o7t5t9jjpgxn8onc/artifacts

**Comment by Zzm317** [comment]
是否和base64的等号有关 测试去掉base64的两个等号可以识别

**Comment by eaglet123** [comment]
Win10 1079 同样存在此问题。

**Comment by dancorpse** [comment]
我也是，无法解析，4.0.5版倒是可以

**Comment by liuy1994** [comment]
win10 1079 ，the same problem

**Comment by xuchengpeng** [comment]
on windows 10 1709 enterprise，same problem， old version 4.0.5 works perfect

**Comment by Choutouketsu** [comment]
QR code isn‘’t able to be analysed

**Comment by 1242380113** [comment]
几个月了都没人解决这个问题吗

**Comment by necan** [comment]
看来只有继续用shadowsocksR了

**Comment by celeron533** [comment]
fixed in 4.0.7

**Comment by ReycoChou** [comment]
mac复现

**Comment by chenshaoju** [comment]
你好，这儿是Windows版本的issue列表，因为软件不通用，所以无法处理Mac版本的问题。
