### ISSUE TITLE
为什么最近官网购买的地址经常连不通

### ISSUE THREAD

**Issue by oOtroyOo** [shadowsocks/shadowsocks-windows#1377]
最近总是出现官网个人版的9个地址全都连不上。之后第二天起来就又可以连接了
而且我试着关掉SS，用cmd ping 地址也连不通。

我就想知道是我个人的问题吗，还是近期存在不稳定问题？
难道是我用SS代理来 玩吃鸡，会出问题？

**Comment by mosquito367** [comment]
开会开会，可能开完了就好了，最近就是这样

**Comment by celeron533** [comment]
请联系你的供应商，这里没有也不可能提供任何购买服务
