### ISSUE TITLE
非预期性错误，shadowsocks将退出

### ISSUE THREAD

**Issue by jokermonster** [shadowsocks/shadowsocks-windows#1378]
![image](https://user-images.githubusercontent.com/30726639/30305039-4f92acc0-97a3-11e7-97a9-02424f1bfa96.png)

**Comment by chenshaoju** [comment]
请尝试更新到 4.0.6 版本的SS，或者： https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676

**Comment by Littlechilde** [comment]
楼上正解
