### ISSUE TITLE
SS 4.0.6 obfs-local无法使用

### ISSUE THREAD

**Issue by ticonci** [shadowsocks/shadowsocks-windows#1379]
c#客户端里面已经有了plugin栏位了，报这种错误
![image](https://user-images.githubusercontent.com/12870368/30315982-37f597a0-97d8-11e7-95dc-33aff659919e.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1368

**Comment by ticonci** [comment]
谢谢，是没有下载obfs
下载地址在这：
https://github.com/imgk/simple-obfs-Cygwin/releases

**Comment by flashbarry** [comment]
@ticonci 你好，想问下你在server端的obfs服务端怎么安装的，我ss端安装的是秋水逸冰也就是teddysun的一键安装版本，然后obfs按照官方说明安装的，可是如果用一键安装的自动启动（json配置里添加obfs的配置），客户端ss就无法上网，而如果用命令ss-server -c 某某json，客户端ss不启用obfs也能正常上网。你遇到这种问题吗？或是你知道问题在哪里吗？我写信给秋水逸冰，没有得到回复。
