### ISSUE TITLE
nodejs,  cnpm install : ResponseError: socket hang up (req "error")

### ISSUE THREAD

**Issue by JkVon** [shadowsocks/shadowsocks-windows#1380]
### Version: 
    4.0.6

### Environment
    Operating system: win10 10.0.15063 Build 

### Steps you have tried
    1、npm config set proxy ...
    2、npm config rm proxy ... then close ss ,then try cnpm install , but still hang up 

### Config and error log in detail
[npminstall:get] retry GET http://registry.npm.taobao.org/@angular/cli/download/@angular/cli-1.4.1.tgz after 400ms, retry left 1, error: ResponseError: socket hang up (req "error"), GET http://111.56.13.150:80/1Q2W3E4R5T6Y7U8I9O0P1Z2X3C4V5B/registry.npm.taobao.org/@angular/cli/download/@angular/cli-1.4.1.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":8,"createSocketErrorCount":0,"closeSocketCount":7,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":2,"freeSockets":{},"sockets":{"111.56.13.150:80:":1},"requests":{}})
headers: {}

ResponseError: socket hang up (req "error"), GET http://111.56.13.150:80/1Q2W3E4R5T6Y7U8I9O0P1Z2X3C4V5B/registry.npm.taobao.org/@angular/cli/download/@angular/cli-1.4.1.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":10,"createSocketErrorCount":0,"closeSocketCount":9,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":2,"freeSockets":{},"sockets":{"111.56.13.150:80:":1},"requests":{}})
headers: {}
at createHangUpError (_http_client.js:253:15)
at Socket.socketOnEnd (_http_client.js:345:23)
at emitNone (events.js:91:20)
at Socket.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)

npminstall version: 3.1.4
npminstall args: D:\Program Files\nodejs\node.exe C:\Users\JkVon\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\JkVon.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org -g

**Comment by chenshaoju** [comment]
The shadowsocks-nodejs has abandon.
Please use libev or python version.

**Comment by JkVon** [comment]
抱歉，我以为是ss修改了我的某项网络配置，后来发现是和公司网络过滤有关。
