### ISSUE TITLE
安装 .NET Framework 安全补丁后发生错误

### ISSUE THREAD

**Issue by Onion23** [shadowsocks/shadowsocks-windows#1381]
版本：Windows 7 旗舰版 SP1（6.1.7601），Shadowsocks 4.0.6
补丁：KB4041083（适用于 x64 的 Windows 7 和 Server 2008 R2 上用于 .NET Framework 3.5.1、4.5.2、4.6、4.6.1、4.6.2、4.7 的安全和质量汇总）

![image](https://user-images.githubusercontent.com/13325611/30357009-f39de8b8-986e-11e7-8ee4-f2f02f1c48d6.png)
![image](https://user-images.githubusercontent.com/13325611/30357013-fd2a6654-986e-11e7-85de-3e7c778ef415.png)

**Comment by chenshaoju** [comment]
我测试了一下我自己的SS，在安装更新重启后并未出现此现象。

![image](https://user-images.githubusercontent.com/515763/30358954-3d3338a6-987a-11e7-8c48-f5820e1bdcd9.png)

请尝试使用 https://www.microsoft.com/en-us/download/details.aspx?id=30135 进行修复，如果修复失败，请按照向导完全卸载 .Net Framework ，然后从 https://www.microsoft.com/zh-CN/download/details.aspx?id=55170 重新安装 .Net Framework 。

**Comment by Onion23** [comment]
安装 KB4041083 后，已安装更新中实际看到的补丁为 KB4040973，卸载 KB4040973 后重新安装 KB4041083，报错消失。
![image](https://user-images.githubusercontent.com/13325611/30359846-23296916-9880-11e7-8c5a-43f897805acd.png)

![image](https://user-images.githubusercontent.com/13325611/30359837-182e8956-9880-11e7-8971-92f3f680b394.png)
