### ISSUE TITLE
错误 - ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by wangkairong** [shadowsocks/shadowsocks-windows#1383]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

![image](https://user-images.githubusercontent.com/20257232/30387111-23acbb82-98de-11e7-96cf-542975da1de1.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
该问题已知，等待修复。 https://github.com/shadowsocks/shadowsocks-windows/issues/1374#issuecomment-329211722

**Comment by celeron533** [comment]
重现步骤？

**Comment by celeron533** [comment]
#1397
