### ISSUE TITLE
使用cclear清理电脑垃圾之后，ss就自己退出了，所有保存的设置全部没有了。只能重新设置。

### ISSUE THREAD

**Issue by wheelife** [shadowsocks/shadowsocks-windows#1386]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
没看懂标题的意思，请具体描述一下。

**Comment by wheelife** [comment]
有两次这样的情况，不过我刚刚想重新试试，然后想把他的报错提示截图过来。结果又没有发生我所说的问题了。

**Comment by chenshaoju** [comment]
刚在Windows 7 x64上测试了一下5.34.6207版本的CCleaner，没有出现问题。

**Comment by tangshiba** [comment]
是不是你的ss exe文件的路径的问题。

**Comment by chenshaoju** [comment]
请检查你使用的CCleaner是否为 5.33 版本，如果是，请尽快全盘扫毒。
详情： http://www.solidot.org/story?sid=53877

**Comment by celeron533** [comment]
不要把ss放在temp文件夹下

**Comment by wheelife** [comment]
今天刚好看到这个消息，好在昨天已经把cclear升级了，昨天之前确实我用的不是最新的。

**Comment by celeron533** [comment]
> 有两次这样的情况，不过我刚刚想重新试试，然后想把他的报错提示截图过来。结果又没有发生我所说的问题了。

close as Can Not Reproduce
