### ISSUE TITLE
找不到文件d3dcompiler_47.dll

### ISSUE THREAD

**Issue by BoomHaha** [shadowsocks/shadowsocks-windows#1388]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
请访问 https://support.microsoft.com/en-us/help/4019990/update-for-the-d3dcompiler-47-dll-component-on-windows 了解详情。

**Comment by celeron533** [comment]
前两天遇到相同问题，windows安装了补丁，需要重启，重启后解决。
