### ISSUE TITLE
最新版本在win8下不可用，老版本2.3就可以

### ISSUE THREAD

**Issue by gaotong2055** [shadowsocks/shadowsocks-windows#1390]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Win8, .net 4.6.2

### Steps you have tried
配置都没问题，但是上不了外网，我看浏览器代理也设置了，日志里没有什么异常错误。就是打不开google.com ，dns找不到。

### What did you expect to see?
用老版本2.3的版本就正常

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
请先得知你的SS for Windows 的端口号，如1080。然后启动命令提示符(cmd)，执行：
```
netstat -ano -p tcp
```
能否在第一列找到任何 127.0.0.1:1080 的内容？

**Comment by celeron533** [comment]
新版本去掉了一次性认证，如果你的服务器不兼容，则无法连接

**Comment by gaotong2055** [comment]
@celeron533 可以确认不是服务器兼容的问题，因为4.0.6版本是win10是可以的，连的一样的服务器

**Comment by gaotong2055** [comment]
@chenshaoju 我再确认下，不是我的电脑
