### ISSUE TITLE
当密码中含有 "/" 符号时，生成的 ss://链接就会无法被v4.0.6版本SS客户端识别，包括SS客户端自身生成的链接

### ISSUE THREAD

**Issue by ToyoDAdoubi** [shadowsocks/shadowsocks-windows#1393]
当密码中包括 “/” 斜杠符号时，我生成的和SS客户端生成的 ss:// 链接都无法被 v4.0.6版本的SS客户端识别，无论是二维码扫描还是剪贴板导入。
复现格式如下：
```bash 
chacha20:xxx.xx/xxx/233@127.0.0.1:233
ss://Y2hhY2hhMjA6eHh4Lnh4L3h4eC8yMzNAMTI3LjAuMC4xOjIzMw
```

v4.0.5版本的SS客户端正常。

**Comment by chenshaoju** [comment]
目前二维码和URI导入都有问题，详见：https://github.com/shadowsocks/shadowsocks-windows/issues/1374

**Comment by celeron533** [comment]
先暂时避免使用`/` `:` `@` `#`等符号作为密码

**Comment by celeron533** [comment]
请使用这个版本测试一下

https://ci.appveyor.com/project/celeron533/shadowsocks-windows-3j4p4/build/job/o7t5t9jjpgxn8onc/artifacts

**Comment by ToyoDAdoubi** [comment]
@celeron533 这个版本测试正常，可以正常导入/扫描 密码包含 "/" 的二维码。
不过我提一个意见，可不可以在密码输入框附近加一个选择框，可以选择 明文/加密(*号) 方式来显示密码，这样不用查看密码的时候，必须查看配置文件了，刚才我测试的时候只能去配置文件查看密码是否导入正常。。。

**Comment by celeron533** [comment]
一般用户不太会去察看配置文件的内容，这个需求罕见

**Comment by ToyoDAdoubi** [comment]
@celeron533 并不罕见，有时候一些人账号导入后无法使用，他就要排查是否密码等信息输错，那么他还需要去配置文件查看才行。
还有其他的一些情况可能要修改密码、想要查看当前账号的密码是什么、可能输入密码的时候因为看不到而输入错误等等情况。
毕竟加这个功能并不复杂，点击选择框判断选中是否等于真，如果是就修改密码输入框的输入类型，总会有部分人使用的，这些都是细节。

**Comment by celeron533** [comment]
@ToyoDAdoubi 开个新issue吧，然后把这段话贴上去，方便追踪
