### ISSUE TITLE
High CPU Usage on the System Process

### ISSUE THREAD

**Issue by fishinbox** [shadowsocks/shadowsocks-windows#1394]
### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Windows 10, .Net 4.7 shipped with Windows 10

### Steps you have tried
enable/disable statistics

### What did you expect to see?
normal cpu usage

### What did you see instead?
After long run, couple hours for instance, the System Process shows intensive CPU usage (though limited to single core, that is overall 25% on a quad-core system).
When the statistics function in Shadowsocks-Windows is disabled, the situation no longer present.

### Config and error log in detail (with all sensitive info masked)
May need further debug/logging. Not available at this time.

**Comment by chenshaoju** [comment]
statistics function is buggy.
Please Do not use this function.

**Comment by mahl** [comment]
I'm also experiencing this problem. When connecting to some sites (e.g. facebook), the shadowsocks client uses so much CPU that the computer becomes unresponsive for 20 - 30 seconds.
