### ISSUE TITLE
编辑服务器页面的一个小bug

### ISSUE THREAD

**Issue by S-H-Y-GitHub** [shadowsocks/shadowsocks-windows#1397]
当点击删除按钮将所有的服务器都删除之后再点击复制按钮就会触发这个bug

![](https://ws1.sinaimg.cn/large/006fQHrmly1fjqgwun7p3j30hb0k8tas.jpg)

**Comment by paperbag** [comment]
为何要打码…@S-H-Y-GitHub

**Comment by S-H-Y-GitHub** [comment]
我没打码啊

 

https://ws1.sinaimg.cn/large/006fQHrmly1fjqgwun7p3j30hb0k8tas.jpg

 

发件人: paperbag [mailto:notifications@github.com] 
发送时间: 2017年9月21日 14:35
收件人: shadowsocks/shadowsocks-windows <shadowsocks-windows@noreply.github.com>
抄送: 率怀一 <932495000@qq.com>; Mention <mention@noreply.github.com>
主题: Re: [shadowsocks/shadowsocks-windows] 编辑服务器页面的一个小bug (#1397)

 

为何要打码…@S-H-Y-GitHub <https://github.com/s-h-y-github>

**Comment by celeron533** [comment]
@S-H-Y-GitHub 插播一条新闻，可以根据图片地址反推出新浪微博用户ID
率怀一93272
