### ISSUE TITLE
obfs在服务器端已经开启，客户端的编辑服务器页面应该如何开启？

### ISSUE THREAD

**Issue by dragon100a** [shadowsocks/shadowsocks-windows#1398]
### Version(release version or AppVeyor link)
4.06

### Environment(Operating system, .NET Framework, etc)
win10

### Steps you have tried

服务器端开启了obfs。
用的是这样的步骤
https://github.com/shadowsocks/simple-obfs/issues/103#issuecomment-330844870

接下来 在 ss客户端目录里加入的cygwin1.dll和obfs-local.exe（来自于https://github.com/imgk/simple-obfs-Cygwin/releases   我一开始忘记加入这俩文件，结果导致了报错）

https://github.com/shadowsocks/simple-obfs
usage一节 提到在客户端，
> ss-local -c config.json --plugin obfs-local --plugin-opts "obfs=http;obfs-host=www.bing.com"

对应ss406客户端的“插件”框 里 写 obfs-local，“插件选项”里 写 obfs=http;obfs-host=www.bing.com

前面 obfs=http 我记得在服务器端就这么写的，后面obfs-host=www.bing.com该如何理解呢？

------------以下内容已经过时，请忽略------------------------------------------------------------------
我在这个地方_ 点 确定
![32322323](https://user-images.githubusercontent.com/5362072/30655046-683f2a12-9e62-11e7-8111-729ba7174618.png)
准确来说，就是我在插件里 写的了东西，点确定，就会报错
![33333](https://user-images.githubusercontent.com/5362072/30655073-7884d8d6-9e62-11e7-8c11-a47b74e82dbc.png)
我在服务器端开了obfs，
按照这样的步骤：https://github.com/shadowsocks/simple-obfs/issues/103#issuecomment-330844870
现在我看到406的客户端有插件和插件选项，因此我就往里填写。
点确定，就报错了。

**Comment by chenshaoju** [comment]
你下载了obfs-local.exe 吗？
https://github.com/imgk/simple-obfs-Cygwin/releases

**Comment by dragon100a** [comment]
谢谢告知。已经在ss客户端的目录里加了上述地址里的cygwin1.dll和obfs-local.exe。
https://github.com/imgk/simple-obfs-Cygwin里，usage一节  提到在客户端，

> ss-local -c config.json --plugin obfs-local --plugin-opts "obfs=http;obfs-host=www.bing.com"

对应ss406客户端的“插件”框 里 写 obfs-local，“插件选项”里 写 obfs=http;obfs-host=www.bing.com

前面 obfs=http 我记得在服务器端就这么写的，后面obfs-host=www.bing.com该如何理解呢？

**Comment by chenshaoju** [comment]
将HTTP主机头伪装成成所指定的 obfs-host 。

**Comment by dragon100a** [comment]
@chenshaoju 
承接上回，
问题1
我是在ss客户端里写了bing的伪装，我可以写成任意的？比如百度？？
同时  我在服务器端按照顶楼的步骤安装了obfs后，在ss服务器端的配置文件里只是 加了
"plugin":"obfs-server",
"plugin_opts":"obfs=http"
并没有提到伪装。
因此伪装是 只 需要 在 ss客户端编辑服务器页面 的“插件选项”写，而且还可以 任意写成其他网站？
ss服务器端的配置文件里 只是需要补充写上述2行就行了呗？

问题2
我 看到这样一个图，这个代理软件可以引入ss。
![image](https://user-images.githubusercontent.com/5362072/30677349-df7a548e-9ebd-11e7-846e-f372317fbbd5.png)
我发现obfs好像还不只是一种啊
![21212121](https://user-images.githubusercontent.com/5362072/30677647-7e8bda10-9ebf-11e7-9190-e16539d187ff.png)
同样的，后面还有obfs选项。
这里的plain 应该是 没开启 obfs 吧？
我们一直讨论的https://github.com/shadowsocks/simple-obfs
是 实现 了 这里的 http-simple 吗？

**Comment by chenshaoju** [comment]
１.可以，主机头伪装是可选的。
２.这个是ShadowsocksR的功能，我没用过SSR，但是这个软件可能被其他人改过了。

**Comment by dragon100a** [comment]
@chenshaoju 
那是sockcap64我用这个，结合ss代理游戏，他可以直接引入ss。这个地方选plain后面sbfs参数随便写、留空，测试都是成功的。因此那个plain就是客户端不使用obfs，当然不使用也是可以正常访问的。
选http_simple再写obfs=http;obfs-host=www.bing.com到参数里，测试失败。看起来我们用的simple-obfs和这里提到的http_simple完全不是一回事。
不过那几个选项看起来 并没有 我们配置的 那一种 obfs。

关于伪装
1.ss服务器端是可选的？
ss服务器端配置文件
"plugin":"obfs-server",
"plugin_opts":"obfs=http"
这样就完事了是 吗？
2.ss客户端这边，除了可以任意伪装外。
只写obfs=http能行吗？

**Comment by chenshaoju** [comment]
１.请联系你的SS服务端软件的支持论坛或人员。
２.取决于服务端。
