### ISSUE TITLE
Shadowsocks 崩溃

### ISSUE THREAD

**Issue by diigu** [shadowsocks/shadowsocks-windows#1399]
环境：Win7 x64，.net 4.0 .net 4.5, .net4.6都有安装。
已经正常使用了很久，昨天关机后，今天早晨开机ss自启动，就弹出这个错误信息。
已尝试无效的解决方案：
更新4.0.5,4.0.6无效。
重新安装.net 4.x无效。
重启无效。
换路径到C盘根目录无效。
wpfgfx_v0400.dll文件是存在的。

---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.TypeInitializationException: “<Module>”的类型初始值设定项引发异常。 ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 不是有效的 Win32 应用程序。

   --- 内部异常堆栈跟踪的结尾 ---

   在 MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)

   在 MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()

   在 CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)

   在 ?A0x721f77f1.CreateCModuleInitialize()

   在 ?A0x721f77f1.??__E?A0x721f77f1@cmiStartupRunner@@YMXXZ()

   在 _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)

   在 <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )

   在 <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )

   在 <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )

   --- 内部异常堆栈跟踪的结尾 ---

   在 <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )

   在 .cctor()

   --- 内部异常堆栈跟踪的结尾 ---

   在 GlobalHotKey.HotKeyManager..ctor()

   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)

   在 Shadowsocks.Program.Main()
---------------------------
确定   
---------------------------

**Comment by chenshaoju** [comment]
该问题有类似情况，建议是重装 .Net ： https://github.com/Squirrel/Squirrel.Windows/issues/1108
请尝试使用 https://www.microsoft.com/en-us/download/details.aspx?id=30135 进行修复，如果修复失败，请按照提示清洁安装.Net 4.7。

**Comment by diigu** [comment]
使用.Net Repair工具无效。
安装新版.Net 4.7有效，问题已解决。
多谢。

**Comment by stevenlee87** [comment]
楼主 我跟你的问题一样。

**Comment by stevenlee87** [comment]
我重新安装了.net 4.7 问题依旧。。

**Comment by diigu** [comment]
更新4.0.5,4.0.6无效。
重新安装.net 4.x无效。
重启无效。
ss.exe换路径到C盘根目录无效。

你试试这几种好用么？

**Comment by chenshaoju** [comment]
这看起来很像 wpfgfx_v0400.dll 被破坏了。

这是一个测试，请先扫毒，并检查数字签名，然后放到 C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\ 目录中。

![image](https://user-images.githubusercontent.com/515763/30689493-b02ecd0a-9ef3-11e7-8329-74d9cc1d1870.png)

下载：
[wpfgfx_v0400.zip](https://github.com/shadowsocks/shadowsocks-windows/files/1320671/wpfgfx_v0400.zip)

**Comment by stevenlee87** [comment]
我把所有的.net版本都卸载了(4.0 4.6 4.7)。然后重新安装.net4.0 4.5 4.6 目前已经OK了
