### ISSUE TITLE
shadowsocks non-ui error

### ISSUE THREAD

**Issue by stevenlee87** [shadowsocks/shadowsocks-windows#1400]
version:4.0.6
windows 7 sp1 x64
![ss](https://user-images.githubusercontent.com/4190121/30685075-36b84e86-9ee6-11e7-99b5-c8e052823bfe.jpg)

**Comment by celeron533** [comment]
#1399

**Comment by stevenlee87** [comment]
我安装了.net 4.7还是不行。。

**Comment by chenshaoju** [comment]
请尝试使用修复工具修复看看。 https://www.microsoft.com/en-us/download/details.aspx?id=30135

**Comment by stevenlee87** [comment]
我把所有的.net版本都卸载了(4.0 4.6 4.7)。然后重新安装.net4.0 4.5 4.6 目前已经OK了
