### ISSUE TITLE
非预期错误：索引超出了数组界限

### ISSUE THREAD

**Issue by zehuali90529** [shadowsocks/shadowsocks-windows#1401]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

4.0.6
### Environment(Operating system, .NET Framework, etc)

win10
### Steps you have tried

just open the exe
### What did you expect to see?

the UI
### What did you see instead?

the exception：非预期错误：索引超出了数组界限

**Comment by chenshaoju** [comment]
请尝试将 Shadowsocks.exe 复制到一个空的文件夹（不包含其他配置文件）然后重试。
