### ISSUE TITLE
服务器端已经开启了 tcp fast open，客户端这边如何开启？

### ISSUE THREAD

**Issue by dragon100a** [shadowsocks/shadowsocks-windows#1402]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.06

### Environment(Operating system, .NET Framework, etc)
win10

### Steps you have tried
在 vps 那边，也就是服务器端
在/etc/sysctl.conf中添加net.ipv4.tcp_fastopen = 3
在/etc/shadowsocks-libev/config.json的大括号里，添加"fast_open": true,

{
    "server":["[::0]","0.0.0.0"],
    "server_port":61387,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"**********",
    "timeout":600,
    "method":"aes-256-gcm",
    **"fast_open": true,**
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}

然后reboot

现在 回到 win10的 ss 4.06的配置文件

    {
      "server": "*.*.*.*",
      "server_port": ***,
      "password": "***********",
      "method": "aes-256-gcm",
      "plugin": "obfs-local",
      "plugin_opts": "obfs=http;obfs-host=www.bing.com",
      "remarks": "",
      "timeout": 5
    }

客户端 这边还 需要 添加 "fast_open": true, 吗？
其中 在 客户端的编辑服务器页面，obfs-local填入“插件”框，obfs=http;obfs-host=www.bing.com填入“插件选项”框。好像没看到有 开启fast open的地方？？

**Comment by chenshaoju** [comment]
目前，Shadowsocks for Windows暂不支持Tcp Fast Open。
具体讨论：
https://github.com/shadowsocks/shadowsocks-windows/pull/1328

**Comment by dragon100a** [comment]
@chenshaoju
谢谢告知。
vps 那边，也就是服务器端，我 提升内核 开bbr tfo 装了obfs
ss客户端这边，我只是 需要 配置里 填上obfs

这么说来，目前为止，我能 做的  都做了。

**Comment by celeron533** [comment]
另一种担心是windows客户端的fastopen会不会成为一种流量特征？

**Comment by jayvzh** [comment]
我也想知道，现在使用TCP Fast Open的地方似乎太少了，会不会作为特征容易被检测？
Chrome是flags里显不支持win平台开启，Edge的flags里相关设置消失了，不知道是取消了还是默认开启了？
既然win版ss不支持，我觉得还是直接不开启的好。

**Comment by dragon100a** [comment]
> 我也想知道，现在使用TCP Fast Open的地方似乎太少了，会不会作为特征容易被检测？
> Chrome的flags里显示不支持win平台开启，Edge的flags里相关设置消失了，不知道是取消了还是默认开启了？
> 既然win版ss不支持，我觉得还是直接不开启的好。

服务器 端，我是开启了。win下的客户端不支持。那实质相当于没有开启，也是没有特征的吧， 也不会泄露什么吧，
