### ISSUE TITLE
pc无法加载www.pixiv.net 安卓端可以 同一个ss服务器

### ISSUE THREAD

**Issue by chengzi120dy** [shadowsocks/shadowsocks-windows#1403]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by dragon100a** [comment]
@chengzi120dy 
我这边测试vultr的日本vps打不开，另外一家美国线路能开。不知道什么毛病
都是pc端

**Comment by chenshaoju** [comment]
Pixiv屏蔽了一些机房的IP，有些地区的服务器可能会打不开，比如我在DO的SFO的服务器就打不开。

请确保PC和手机使用的是相同的服务器，如果PC使用了GFWList，请确保已经更新到了最新。

**Comment by dragon100a** [comment]
@chenshaoju 
看起来vultr的日本 看起来就是被 Pixiv 屏蔽的机房 吧。。我用的这块的vps 打不开。除了 换用其它机房的线路访问，没别的办法了吗？

**Comment by chenshaoju** [comment]
好像没有办法。。。

**Comment by celeron533** [comment]
P站官方的屏蔽策略，似乎是以前有人不断用VPS的服务器去抓图，最后官方只能屏蔽这些IP段

**Comment by b1ueb1ues** [comment]
vultr法国节点可以访问

**Comment by IITII** [comment]
> @chengzi120dy
> 我这边测试vultr的日本vps打不开，另外一家美国线路能开。不知道什么毛病
> 都是pc端

简单点，ssh连上去，能ping通p站应该就能访问，ping 不通可能是IP被block了
