### ISSUE TITLE
UI ERROR 软件退出

### ISSUE THREAD

**Issue by powerliao** [shadowsocks/shadowsocks-windows#1404]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
V 4.0.6

### Environment(Windows)
![mmexport1506182228383](https://user-images.githubusercontent.com/20716662/30774826-5743a250-a0bb-11e7-9786-9f2a16a7c49d.jpg)

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
#1376

**Comment by powerliao** [comment]
thx

**Comment by celeron533** [comment]
这个config文件是你自己建立的还是从别的地方复制过来的呢？
