### ISSUE TITLE
obfs exception

### ISSUE THREAD

**Issue by hybtoy** [shadowsocks/shadowsocks-windows#1405]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Win10, .NET Framework - 4.7

### Steps you have tried
Simple, just tried to use OBFS

### What did you see instead?
![screenshot 2017-09-25 002](https://user-images.githubusercontent.com/12900872/30796048-d8074926-a1e9-11e7-9108-71141c72fbb5.png)

### Config and error log in detail (with all sensitive info masked)
[2017-09-25 11:00:39] [E] Failed to start SIP003 plugin: Can not find the specified file

How to use obfs plugin in SS 4.0.6? 
![565](https://user-images.githubusercontent.com/12900872/30796189-66647504-a1ea-11e7-92c8-3242ecacf3ad.png)

**Comment by chenshaoju** [comment]
You need put obfs-local.exe to your shadowsock.exe directory.

Read more: https://github.com/shadowsocks/shadowsocks-windows/issues/1368#issuecomment-328313914

**Comment by hybtoy** [comment]
@chenshaoju 
Thanks. Closed.
