### ISSUE TITLE
无法上网了，无法登陆

### ISSUE THREAD

**Issue by hengaini2055** [shadowsocks/shadowsocks-windows#1407]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

   shadowsocks 4.0.6
### Environment(Operating system, .NET Framework, etc)
  windows 7 .net 4.6.2

### Steps you have tried
  我现在无法上网。登陆之前的用户网站：www.deepss.me无法打开了。
  朋友推荐的新网址 www.mydeep.men，能够打开，但是无法登陆，总是在登陆界面来回刷新。

### What did you expect to see?
 我想知道最新的有效的网址，能够进行用户管理，获得最新的代理地址。

### Config and error log in detail (with all sensitive info masked)

**Comment by hengaini2055** [comment]
前几个月，也有那么3、5天无法使用软件代理上网，后来自然好了。这次是怎么回事？怎么能够让我找到组织？

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 不提供SS服务，请与你的SS服务商联系。

**Comment by hengaini2055** [comment]
不会吧，我一直使用的好好的。只是这两天不行了，那个官网也老是变化，登陆不了。
