### ISSUE TITLE
ss客户端全局模式下大量下载上传数据

### ISSUE THREAD

**Issue by shannonliang312** [shadowsocks/shadowsocks-windows#1408]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.06

### Environment(Operating system, .NET Framework, etc)
windows 10 

### Steps you have tried
开启全局代理

### What did you see instead?
在没有任何 访问网络的情况下，ss在疯狂的下载和上传数据，把带宽全部占满了.....
pac模式一切正常
环境是公司网络

### Config and error log in detail (with all sensitive info masked)

![tim 20170926101101](https://user-images.githubusercontent.com/23253715/30839974-5c976168-a2a7-11e7-81f5-c99880291f48.png)

**Comment by chenshaoju** [comment]
请不要使用全局模式。
或者，请检查是否有迅雷的后台服务在运行。
迅雷会扫描你计算机里的所有资源，然后偷偷上传。
请参阅：
https://www.google.com/search?newwindow=1&safe=off&q=迅雷%20偷偷上传&cad=h

**Comment by shannonliang312** [comment]
@chenshaoju 您好，我电脑上并未安装迅雷~~
之所以用全局模式，是因为有些网站并没有在pac黑名单里，但是直连也非常慢（我经常访问的一些开发网站，以及公司把视频、购物类网站都都屏蔽了，只能用全局模式）
以上这种情况，如何用pac模式访问呢？
谢谢！

**Comment by chenshaoju** [comment]
你使用的是360？请关闭360的SP2P升级加速功能试试。

**Comment by celeron533** [comment]
可以看看是谁在跑流量
![image](https://user-images.githubusercontent.com/3608762/30893350-3cbad8e2-a370-11e7-83d4-879fdde67797.png)

**Comment by shannonliang312** [comment]
@celeron533 请看我的截图~~跟360测出来的一样.....，就是ss的两个程序在跑流量
@chenshaoju 关闭360依旧不行，只能调到pac模式了
![tim 20170927114647](https://user-images.githubusercontent.com/23253715/30894981-c03742ec-a379-11e7-9cee-605750894255.png)

**Comment by celeron533** [comment]
如果不打开全局模式，能否看到有什么程序大量占用带宽？

**Comment by shannonliang312** [comment]
@celeron533 pac模式一切正常~~没有任何程序跑流量.....

**Comment by paperbag** [comment]
由于不能直接地接触到你的电脑，查找问题会比较麻烦，但还是给点建议：
- 如果你想使用 PAC 模式的，建议把相应的网站规则加入到`user-rules.txt`，下面是个例子：
```
||taobao.com^
```
- 全局模式还是要靠自己查找是什么程序造成了这种情况。
- 印象里 ss-windows 有个详细日志的功能开关，可以把它打开，看看代理了哪些网站，再来判断是什么程序造成的。
- 或者在 VPS 上，用`lsof -l`

**Comment by celeron533** [comment]
我的意思是，你开了PAC以后，再去看看有哪些程序直连跑流量的

**Comment by GentleRV** [comment]
所有的网站，你最想看到的规则@ @ | | website.com^

**Comment by shannonliang312** [comment]
@paperbag 好的好的，谢谢你！！目前我就是通过修改规则来实现的~我有自己的VPS搭建的ss服务端，也有直接买的ss服务器，两种都是在全局模式下跑大量流量，我感觉会不会跟公司环境有关......在家就没事.......
我在慢慢找原因吧，不咋影响使用倒是~再次谢谢你！

**Comment by shannonliang312** [comment]
@GentleRV 谢谢~

**Comment by shannonliang312** [comment]
@celeron533 pac模式，只要我没有浏览网络，基本就没流量的，一切正常
![ss](https://user-images.githubusercontent.com/23253715/30996876-89a1cb84-a4f6-11e7-9b00-bf81939ef8de.png)

**Comment by celeron533** [comment]
开启全局模式后，看看除了SS自己相关的那些进程，有没有其他什么进程在大量访问`127.0.0.1`

![image](https://user-images.githubusercontent.com/3608762/31054040-837b92b6-a6dc-11e7-939f-b108364aadcc.png)

**Comment by celeron533** [comment]
#1429 汇报了类似的问题，根据描述，启用统计或局域网连接后会有这个现象

**Comment by shannonliang312** [comment]
@celeron533 这两项我都没有启用~~目前是全局模式下手动kill掉ss_privoxy后就正常了....这个ss_privoxy.exe是干什么的呀？

**Comment by celeron533** [comment]
`ss_privoxy`是把socks5代理转换成http代理

**Comment by gdf159159** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1449

现在全局模式下 有广告

**Comment by Linqing0808** [comment]
这个速度是机器内部交互数据的速度吧？在路由器上看看外网速度。

**Comment by GreyFeatherVoid** [comment]
同样遇到了这个问题，有点怕被偷数据
