### ISSUE TITLE
建议在编辑服务器的密码输入框旁边新增切换密码显示方式的选择框(明文/加密*)

### ISSUE THREAD

**Issue by ToyoDAdoubi** [shadowsocks/shadowsocks-windows#1411]
目前想要查看账号的密码，需要打开配置文件查看才行，这样操作会比较麻烦。
有时候一些人账号导入后无法使用，他就要排查是否密码等信息输错，那么他还需要去配置文件查看才行。
还有其他的一些情况可能要修改密码、想要查看当前账号的密码是什么、可能输入密码的时候因为看不到而输入错误等等情况。
毕竟加这个功能并不复杂，点击选择框判断选中是否等于真，如果是就修改密码输入框的输入类型，总会有部分人使用的，这些都是细节。
如果说是为了防止别人看到密码，那么也不是所有人什么时候都会被别人电脑窥屏。再加上如果别人能操作电脑，直接进入配置文件查看密码等信息好了。密码内容用*号并不能增加多少密码安全性。就是现在很多网站在登陆账号的时候也会在密码输入框后面加一个按钮用来切换密码显示类型。
这些小细节不能因为自己或者周围人用的少或者很少人提出就觉得没人需要而忽略它，毕竟少数人不能代表大多数人，而且很多细节功能是推出前没人想到，推出后很多人觉得这个功能挺好挺方便的。

**Comment by WLZLCX** [comment]
+1

**Comment by lautis0503** [comment]
+1
比如ShadowsocksR的windows客户端，默认隐藏服务器IP和密码，可选显示
