### ISSUE TITLE
  服务器里添加了很多账户   有一些地址时间长了就不能用了    但是我又没有办法一个一个的找出来  能不能有一个功能可以直接删除无法连接的账号

### ISSUE THREAD

**Issue by Elliott-cui** [shadowsocks/shadowsocks-windows#1412]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
没有。
