### ISSUE TITLE
请问现在的官网地址是多少？续费问题

### ISSUE THREAD

**Issue by xieyang784** [shadowsocks/shadowsocks-windows#1413]
What about shadowsocks official website? I need recharge now.

**Comment by pexcn** [comment]
https://shadowsocks.org

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 不销售SS服务，请与你的SS服务商联系。

**Comment by mosquito367** [comment]
Shadowsocks还有官网？

**Comment by WLZLCX** [comment]
鞑清亡了
