### ISSUE TITLE
In PAC mode logging is not visible

### ISSUE THREAD

**Issue by GentleRV** [shadowsocks/shadowsocks-windows#1414]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
latest version

### Environment(Operating system, .NET Framework, etc)
as needed for shadowsocks + win7 x64

### What did you expect to see?
In pac mode see the graphs and verbose logging in the black window.

### What did you see instead?
only see some graphical information when shadowsocks contact github for program updates

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
Cannot reproduce on my environment.
Does it require specific operation sequence? such as: enable verbose first, then enable global PAC, finally open log window, etc.

**Comment by GentleRV** [comment]
What I do is:

The Icon is right below in the taskbar.
I select with right mouse button the icon and set there in PAC mode
Then select Help > Show logs.
In Global mode I see the data in blue and green, in PAC mode nothing to see.
Let me know if you can reproduce it, or what you need more as info

**Comment by GentleRV** [comment]
Herewith a log file 
[shadowsocks log.zip](https://github.com/shadowsocks/shadowsocks-windows/files/1368833/shadowsocks.log.zip)

**Comment by celeron533** [comment]
@GentleRV
I guess the PAC does not redirect any network flow to the proxy.

While there is no more log output:
1. Could you still access to the target website via proxy?
2. Can you check the content of PAC file? (via Internet Explorer --> Internet Options --> Connection)
