### ISSUE TITLE
non-UI Error - InvalidOperationException

### ISSUE THREAD

**Issue by was4444** [shadowsocks/shadowsocks-windows#1415]
### Version(release version or AppVeyor link)
4.0.4

### Environment(Operating system, .NET Framework, etc)
Windows 7

### Error Info

![image](https://user-images.githubusercontent.com/1237906/30969010-b99f77f4-a493-11e7-90f8-61e3f6385c4b.png)

**Comment by CKrome** [comment]
Try update to version 4.0.6 to see whether problem still exists.

**Comment by zxecho** [comment]
Oh, yes.I have a similar problem too. I use the lastest version--4.0.6 on win10.

![image](https://user-images.githubusercontent.com/14368376/30997071-d9226dde-a4f7-11e7-9f84-103d3d1a6231.png)

**Comment by celeron533** [comment]
禁用可靠性统计
