### ISSUE TITLE
更新服务端libev，客户端也需要更新吗

### ISSUE THREAD

**Issue by kang000feng** [shadowsocks/shadowsocks-windows#1418]
想请教最新服务端后能兼容旧的客户端吗？更新服务端后如果没有启用新功能，还是用原来的加密方式，需要更新客户端吗？手机上还是用的旧的客户端不知能否兼容，官方文档也没有讲客户端与服务端版本兼容问题，请大神帮忙解惑！谢谢各位

### Version(release version or AppVeyor link)
3.2

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
不需要。

**Comment by celeron533** [comment]
基本不需要，目前已知的是最新客户端已经放弃了一次性认证，如果老版的服务器上开启了这个，最新版的Windows客户端将无法连接该服务器。

**Comment by cell13** [comment]
想请教下服务端是怎么搭建的，使用的是什么版本，是下面这个版本吗
version: Shadowsocks 2.8.2
