### ISSUE TITLE
插件启动的问题

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-windows#1419]
多个配置，只要其中一个配置里有使用到插件，比如 `obfs-local.exe`, 就会被启动，无论用到插件的配置是不是当前选中状态。想问下能改成，只有用到插件的配置是当前选中状态，才启动 `obfs-local.exe` 之类的吗？

**Comment by celeron533** [comment]
当前的设计是会预载服务器列表中所有的插件，这样在切换服务器的时候不会有明显的插件加载延时。但在拥有大量服务器的情况下带来较多的内存占用情况

**Comment by pexcn** [comment]
不预加载，时间也不会很长吧？

**Comment by AmelieNet** [comment]
你这个插件是在哪里下载的?我服务器配置完obfs-server 但是却没有windows客户端的
