### ISSUE TITLE
所有服务器显示timed out

### ISSUE THREAD

**Issue by JerryRich** [shadowsocks/shadowsocks-windows#1420]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.5

### Environment(Operating system, .NET Framework, etc)
Win7， .NET Framework 4.7

### Steps you have tried
重启，更换服务器，切换系统代理模式

### What did you see instead?
全局模式下无法访问所有网页，pac模式下无法访问列表内的网页，日志显示timed out

### Config and error log in detail (with all sensitive info masked)

**Comment by SuperHentai** [comment]
似乎是21：00开始墙做了什么升级，我的所有服务器的IP都被屏蔽了

**Comment by King-Ran** [comment]
我的昨天就挂掉啦！

**Comment by oldbox** [comment]
me too

**Comment by chenshaoju** [comment]
请与你的SS服务商联系。
可能你的SS服务商服务器被封了，或者跑路了。
我自己搭建的SS没有问题。
