### ISSUE TITLE
连接校园网（联通）VPN之后无法使用SS代理

### ISSUE THREAD

**Issue by rat92497** [shadowsocks/shadowsocks-windows#1421]
“将代理服务器用于以太网或WiFi连接。这些设置不适用于VPN连接。” 这是我在代理设置窗口里看到的，请问跟这个有没有关系？“使用代理服务器”这个选项是开着的，地址是127.0.0.1，端口是1080 （端口跟SS里的设置一样）
我在重装系统之前还是可以用的。连接校园网（每月20GB的流量，学校的IP）-> 连接联通（L2TP，连接之后就不计流量，联通的IP）-> 连接SS（安装过锐速，美国的IP）
但是重装系统之后：
连接校园网（学校的IP）-> 连接联通（联通的IP）-> 连接SS（还是联通的IP） 
但是 连接校园网（学校的IP） -> 直接连接SS不连接联通VPN（美国的IP）就能顺利使用SS代理
会不会是重装系统（WIN10）用了其他版本造成的？
一些设置和UI也跟原来的都不一样了，本来创建VPN连接是要先把用户名和密码输进去之后才能创建，但是重装系统之后没向我要用户名和密码，是我后来自己打开设置把他们保存进去的。
是不是代理有优先等级？
是不是要改注册表？
有没有人遇过这个问题？
求大神们帮一下小弟
十分感谢

**Comment by chenshaoju** [comment]
能看懂？

![image](https://user-images.githubusercontent.com/515763/31314005-0b98f7d4-ac27-11e7-9b39-7281e125edc8.png)

**Comment by rat92497** [comment]
嗯嗯，能看懂。我试一试。谢谢

**Comment by rat92497** [comment]
还是不行。我选了PAC模式，然后VPN设置也自动配置脚本。

**Comment by chenshaoju** [comment]
地址填写的是 http://127.0.0.1:xxxx/pac  吗？其中 xxxx 是你的SS本地SOCKS5端口。

**Comment by rat92497** [comment]
![im8 p7iu _g 0 5fhne0wv](https://user-images.githubusercontent.com/16658377/31314377-e641b16e-ac31-11e7-8667-e8f9047e2fa6.png)

SS的代理端口是1080

**Comment by chenshaoju** [comment]
理论上这样在拨号后就应该会工作了。

**Comment by rat92497** [comment]
本来用得好好的，但是没想到重装系统之后就变成这样子了。不过还是感谢你的帮助 @chenshaoju

**Comment by imba-tjd** [comment]
@chenshaoju 每次切换模式（启用或不启用、pac或全局）都会让这个设置变成全部不选中的状态，这是bug吗？

**Comment by chenshaoju** [comment]
我用的是LAN接入，不是拨号……

@celeron533

**Comment by imba-tjd** [comment]
@chenshaoju 我找到了https://github.com/shadowsocks/shadowsocks-windows/issues/1142

**Comment by chenshaoju** [comment]
噢，对，Win10有这个问题。

**Comment by rat92497** [comment]
解决方法：下载并且安装Switchy Omega，然后开启代理就行了！

**Comment by chenshaoju** [comment]
@2015214115 请问使用的是什么浏览器？Chrome吗？如果是，在Chrome的地址栏中输入 ``` chrome://net-internals#proxy ``` ，显示的是什么？

**Comment by 2015214115** [comment]
@chenshaoju 是chrome，各种设置如下：
![1](https://user-images.githubusercontent.com/30168990/41816158-25658d44-77b0-11e8-8eb1-a7e6fc22faa5.png)
![2](https://user-images.githubusercontent.com/30168990/41816161-29b30a16-77b0-11e8-8092-8e6d7727ab5b.png)
![3](https://user-images.githubusercontent.com/30168990/41816162-2b78e348-77b0-11e8-99cc-11872015b94b.png)

**Comment by chenshaoju** [comment]
请取消这张图片里的设置：
![image](https://user-images.githubusercontent.com/515763/41817663-2f3f5166-77d2-11e8-83f5-d27dfa2dbe3a.png)

这个功能是指当你需要通过代理服务器上网时才需要设置，而你设置为 127.0.0.1 很明显不是你网络中的代理服务器。

**Comment by 2015214115** [comment]
@chenshaoju 解决了，谢谢！

**Comment by ultravires** [comment]
其实都不是正解，表示使用代理的方式可行，但如果你断掉了 CPE 后重新拨号，你就会发现插件也然并卵了。

**Comment by ultravires** [comment]
正解： 打开windows10更新  你会发现提示你“无法检查更新，因为未连接到 Internet。请确保你有手机网络数据或 WLAN 连接，然后重试。”，这个时候你需要将网络断开  用手机开启热点，电脑连接，然后检查更新，然后Windows就会提示你有一个 Internet 更新。点击更新后重启，即可服用！！！

**Comment by Ethanzorx** [comment]
你好!我家换了路由器之后，手机连接路由器的WIFI信号就无法连接vpn，然后我断开wifi用手机流量可以正常连接vpn，请问这是什么问题？最近都有在各个论坛上查找这个问题但是无果，麻烦你了 谢谢

**Comment by chenshaoju** [comment]
这意味着你的路由器的当前公网IP被墙关照了。

请访问 http://www.ip.cn 记下当前的公网IP，然后重新启动你的路由器和光猫，网络恢复后看一下公网IP是否变化了，如果变化了，应该就可以了。。

**Comment by anihao** [comment]
手机和电脑连上校园网后ssr无效了，无法访问外网。

**Comment by lxyok** [comment]
你可以升级一下，或者换一个ss客户端软件，或许可以解决问题
