### ISSUE TITLE
之前用过但是最近用了海豚游戏加速以后就用不了了请问怎么办？

### ISSUE THREAD

**Issue by xqy11** [shadowsocks/shadowsocks-windows#1422]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
请尝试以管理员身份启动命令提示符（cmd.exe），然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
重启计算机后再试。
