### ISSUE TITLE
不能用了吗？？？

### ISSUE THREAD

**Issue by heqiuzhi** [shadowsocks/shadowsocks-windows#1424]
4.0.6
Windows 10
之前都可以用，国庆放假回来就不能用了。手机和PC端都不能用。

**Comment by chenshaoju** [comment]
你用的是 shadowsocks.com 的服务吗？
如果是，请与该服务的负责人联系，该网站（和域名）和Shadowsocks for Windows没有关系。

**Comment by heqiuzhi** [comment]
了解了···谢谢！ 那应该是shadowsocks.com挂了。。。

**Comment by 20anita** [comment]
同不能用..     我用的是shadowsocksvpn.com/shadowsocks.network的，
和shadowsocks.com，好像不是一样的？
翻不了墙连这个网站都进不去...  噗...

**Comment by whight** [comment]
各大ss服务基本都阵亡，看来要自己买主机了

**Comment by ProfFL028** [comment]
已经阵亡一段时间了，好惨，不知道什么时候能修复，而且也连不上shadowsocks

**Comment by chenshaoju** [comment]
这些网站和Shadowsocks for Windows都没有关系。

刚看了一下，翻墙的情况是能打开这些网站的。

另外，我观察到的四家SS服务商都没有问题，我自己搭建的SS也没有问题。

**Comment by KANADEM** [comment]
如果是shadowsocks.com.hk那里购买的话我刚问过了，他们正在努力恢复，部分节点已恢复，需要将ssv7 改为55boom

**Comment by heqiuzhi** [comment]
带上小姨子跑路了啊····

**Comment by wuyafeiJS** [comment]
我也用的是shadowsocks.network。好像真跑路了，shadowsocks.com都好了。就我买的这个不行刚买一个月，悲剧啊
