### ISSUE TITLE
not install

### ISSUE THREAD

**Issue by parks1234** [shadowsocks/shadowsocks-windows#1425]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	4.0.6.0
  问题签名 03:	59b3df83
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	53b50a71
  问题签名 07:	1205
  问题签名 08:	89
  问题签名 09:	System.TypeLoadException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by chenshaoju** [comment]
请尝试安装最新的 .NET Framework https://www.microsoft.com/zh-CN/download/details.aspx?id=55170

**Comment by parks1234** [comment]
我解决了 我是win 装着4.0 ，4.5呢

**Comment by parks1234** [comment]
win7
