### ISSUE TITLE
最新版WIN10 X64无法使用

### ISSUE THREAD

**Issue by nictse2013** [shadowsocks/shadowsocks-windows#1426]
另一台电脑win10 64 可以用,令一台同样的不行，chrome配置相同，SS地址确实可用
更换端口也不行，
求解析。。。。

**Comment by Fyleis** [comment]
win10 X64 企业版 1703有类似问题。检查并非VPS问题，本地亦能访问VPS地址。问题突然出现

**Comment by nictse2013** [comment]
应该就是这个版本，但另一台电脑也是呀。。。。
目前有解决方法么

**Comment by chenshaoju** [comment]
能否具体描述一下，什么是“无法使用”？是无法启动SS，还是能启动，但是无法连接？有无错误提示或者日志？

**Comment by nictse2013** [comment]
客户端可以启动，chrome配置好后，访问YOUTUBE显示

“无法访问此网站

连接已重置。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_RESET”


再次刷新显示“youtube.com 意外终止了连接。”

这台电脑之前用老版本的客户端没事，应该我配置的没错。。。

**Comment by chenshaoju** [comment]
SS日志有什么输出吗？

**Comment by nictse2013** [comment]
to ls
错误日志：

[2017-10-10 19:04:13] connect to clients4.google.com:443
[2017-10-10 19:04:13] System.Net.Sockets.SocketException (0x80004005): 不知道这样的主机。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
这看起来是你输入的服务器名不对……或者你使用的服务器域名被停止解析了。

**Comment by nictse2013** [comment]
就是用的IP，而且这个地址手机、另一台同版本WIN、MAC都能使用

我放弃了。。。

**Comment by celeron533** [comment]
>看来这个软件不能自定IP DNS

所有的软件都没有未卜先知的能力

**Comment by nictse2013** [comment]
上去了一次，又不行了。。。。。。看来不是固定IP DNS的问题。。。。
