### ISSUE TITLE
好好的突然就全 500 Internal Privoxy Error 了

### ISSUE THREAD

**Issue by vip99** [shadowsocks/shadowsocks-windows#1427]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
Shadowsocks-4.0.6

### Environment(Operating system, .NET Framework, etc)
Win10, .NET Framework 4.6.2

### Steps you have tried
运行以下命令无效

netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset

### What did you see instead?

Shadowsocks Python + VPS一键安装， 突然就用不了了， 访问外网全是500 Internal Privoxy Error， 最近墙加固了么？

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
重启VPS后是不是好了？
如果是，我记得Python版有奇怪的崩溃问题，建议使用libev版。

如果重启后仍然不行，你能Ping通你的服务器吗？

**Comment by vip99** [comment]
@chenshaoju 
我重新装了一遍， 还是一样。之前装一下就成功了。
ping 服务器没有问题， 这会儿日志像下面这样的了：

“[2017-10-10 01:50:19] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-10-10 01:50:21] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)”

**Comment by chenshaoju** [comment]
这看起来很像你的服务器IP或者端口不正确，也可能是iptables防火墙没有允许端口或者服务器上的服务端没启动。

发送自基于 Android 系统的 Google Nexus 5X

2017年10月10日 01:56，"vip99" <notifications@github.com>写道：

**Comment by vip99** [comment]
@chenshaoju 
谢谢， 我换了个端口重新搭建了一下，好了， 可能是端口的原因

**Comment by Aleczeng** [comment]
求问具体怎么操作

**Comment by vip99** [comment]
我是小白， 不懂怎么跟你说， 就是重新搭建一下， 卸掉之前的， 之前用的8989端口好像不行了， 随便换了个别的端口就好了

**Comment by Aleczeng** [comment]
是吧代理端口换一下吗？ 我之前的代理端口为1080

**Comment by Aleczeng** [comment]
请教一下 怎么看日志呢

**Comment by Aleczeng** [comment]
服务器端口为37506 代理端口为1080 请问更改端口？谢谢！

**Comment by chenshaoju** [comment]
编辑你服务器上的配置文件。

**Comment by f839903061** [comment]
我今天也遇到这个问题了：500 Internal Privoxy Error

**Comment by hehedahehe** [comment]
重启一下vps就好了，不知道为啥
