### ISSUE TITLE
shadowsocks突然不能用了-500 Internal Privoxy Error

### ISSUE THREAD

**Issue by 379350697** [shadowsocks/shadowsocks-windows#1428]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
windows10
.NET Framework  :  v4.0.30319

### Steps you have tried
reset shadowsocks
服务器能ping通

### What did you see instead?
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

### Config and error log in detail (with all sensitive info masked)
```
[2017-10-10 09:37:31] Shadowsocks started
[2017-10-10 09:37:58] Shadowsocks started
[2017-10-10 09:38:05] Shadowsocks started
[2017-10-10 09:38:10] ************:8388 timed out
[2017-10-10 09:38:10] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

**Comment by chenshaoju** [comment]
如果这是你自己搭建的服务器，不要使用默认端口（8388），已知该端口被重点关照。

**Comment by 379350697** [comment]
换了端口好了

**Comment by ZhengshuaiPENG** [comment]
@chenshaoju 之前改了9402， 也是不行的，现在办法就是使用一个小于443的可能会比较稳定

**Comment by ahtcfg24** [comment]
我一开始用1139，也是500，后来换成了25以后，成功解决了

**Comment by 2017Hsy** [comment]
为什么我给了端口之后还有问题？

**Comment by chenshaoju** [comment]
请检查配置是否正确，端口、加密方式、密码是否一致，如果启用了OTA，请禁用。

**Comment by celeron533** [comment]
>为什么我改了端口之后还有问题？
亦可能是连接被干扰

**Comment by decemberpei** [comment]
I switched to an older release and the issue is gone immediately.  i.e. V4.0.8 has the issue while V4.0.5 does not.

**Comment by chenshaoju** [comment]
If your server using OTA, then this function has been discarded.
