### ISSUE TITLE
ss_privoxy.exe 进程占用大量带宽原因？

### ISSUE THREAD

**Issue by emacle** [shadowsocks/shadowsocks-windows#1429]
4.0.6版本 
 只要开启允许局域网的连接或者 统计配置中勾选了启用统计的选项，就会开启ss_privoxy.exe 进程 ， 该进程的网络上传与下载的速度一直会达到2MB/s，导致系统经常卡死，请问是什么原因？该如何解决？（关闭那两个功能后ss_privoxy.exe 进程立刻消失了 系统也不卡）

**Comment by celeron533** [comment]
当年推出统计的时候只是个实验功能，bug较多，建议关闭

**Comment by johnx7271** [comment]
我自己有个版本，完全不用ss_privoxy.exe

**Comment by celeron533** [comment]
有启用插件么？

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1577#issuecomment-353873483
