### ISSUE TITLE
突然不能用了，500 Internal Privoxy Error

### ISSUE THREAD

**Issue by xym2009** [shadowsocks/shadowsocks-windows#1431]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
win10
NET Framework 4.5.1

### Steps you have tried
尝试了不同的服务器，us,hk,jp,sg都不行

### What did you see instead?
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:
Could not load template file no-server-data or one of its included components.
Please contact your proxy administrator.
If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory)

### Config and error log in detail (with all sensitive info masked)
[2017-10-10 10:41:13] Shadowsocks started
[2017-10-10 10:41:28] System.Net.Sockets.SocketException (0x80004005): 这是在主机名解析时通常出现的暂时错误，它意味着本地服务器没有从权威服务器上收到响应。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by celeron533** [comment]
请和你的服务提供商联系
