### ISSUE TITLE
如何更换已搭建好SS的服务器的端口和IP

### ISSUE THREAD

**Issue by 493740573** [shadowsocks/shadowsocks-windows#1436]
使用Xshell5要如何操作 OS是Debian 7 x64  望指教 万分感谢

**Comment by chenshaoju** [comment]
通过修改你所使用的服务端的 config.json 文件，可能位于 /etc/shadowsocks/ 目录中。
具体请参阅你的服务端程序的帮助文件或说明。
如果你是用的是懒人包，请与懒人包的制作者联系获得帮助。

**Comment by 493740573** [comment]
感谢
