### ISSUE TITLE
一人使用“分享服务器配置”并截图后，另一人使用“扫描屏幕上的二维码”无效

### ISSUE THREAD

**Issue by zhuhangyu** [shadowsocks/shadowsocks-windows#1439]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
win7
.net framework 4.6.2

### Steps you have tried
别人给我“分享服务器配置”，出现二维码，截图给我，我使用“扫描屏幕上的二维码”无效
或者别人给我复制url，我拷贝之后，使用“从剪贴板导入URL”无效
### What did you see instead?
无法解析二维码

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
#1374
