### ISSUE TITLE
使用obfs插件失败

### ISSUE THREAD

**Issue by rsinensis** [shadowsocks/shadowsocks-windows#1444]
![qq 20171011215457](https://user-images.githubusercontent.com/6966865/31444516-00a5fd72-aecf-11e7-8535-3d9187bfce57.png)

**Comment by chenshaoju** [comment]
你需要将 obfs-local.exe 放到你SS所在目录下。
详见： https://github.com/shadowsocks/shadowsocks-windows/issues/1368
