### ISSUE TITLE
How to verify if obfs-local is working client-side (and server-side)?

### ISSUE THREAD

**Issue by elasticblitz** [shadowsocks/shadowsocks-windows#1445]
This is a question rather than an issue - 

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Windows 7 x64

### Steps you have tried
Deploy the server-side with obfs-server that doesn't give information about whether it is really obfuscating the packages or not, with the only sign being some warnings when disconnected;

Deploy the client with simple-obfs-cygwin (local), that doesn't give anything in log besides "Started SIP003 plugin for [redacted] on 127.0.0.1:57593 - PID: 9504", either.

Since the server can be connected even if obfs is not working, there's no indication it's doing its job or not...

### What did you expect to see?
See verbose outputs from obfs-local to make sure it's working?

Thanks a ton in advance!

**Comment by chenshaoju** [comment]
check resource monitor in task manager,If you can see obfs-local.exe progress and network connection in Network Activity,Then obfs-local.exe is working.

**Comment by elasticblitz** [comment]
Thanks a lot!
Still, it might be better if there's something like logging or console output ;D

**Comment by celeron533** [comment]
It is controlled by the plugin itself

>Still, it might be better if there's something like logging or console output ;D

**Comment by elasticblitz** [comment]
> It is controlled by the plugin itself
On shadowsocks-libev server side, simple-obfs console outputs are integrated. - That kind of integration could be great!
