### ISSUE TITLE
Linestorm VPN 好几天没法访问了，请问官方如何处理，谢谢

### ISSUE THREAD

**Issue by sunbbon** [shadowsocks/shadowsocks-windows#1447]
Linestorm VPN 好几天没法访问了，使用美国 日本 新加坡各服务器都不行，linestorm 官网也访问不了。

我就是外贸公司的一般用户，不知道具体技术原因？请问官方这种情况该如何处理呢？

**Comment by celeron533** [comment]
这里不是官方
