### ISSUE TITLE
我的所有服务器都没办法测试延时了，也就是无法连接

### ISSUE THREAD

**Issue by airsimonhan** [shadowsocks/shadowsocks-windows#1448]
### Environment win10 64

很突然，一下子就不行了，全部连接不上，服务器是us11之类的，而且最肯爹的是官网也上不去，里面别的服务器啥的我也看不了啊

**Comment by paperbag** [comment]
> Shadowsocks for Windows 不销售SS服务，请与你的SS服务商联系。

**Comment by asdfzxh8** [comment]
bucunzai keep a seceret or not or mustxx to keep a secret
