### ISSUE TITLE
全局模式下 有广告???

### ISSUE THREAD

**Issue by gdf159159** [shadowsocks/shadowsocks-windows#1449]
0.0.0.0  shama5.com
0.0.0.0  adm.th123.com
0.0.0.0  xf.yellowto.com
0.0.0.0  sc.ofo112.com
0.0.0.0  www.60mil.com
0.0.0.0  www.fun.tv
0.0.0.0  irs01.com
0.0.0.0  q.funshion.com
0.0.0.0  cnzz.mmstat.com
0.0.0.0  stat.funshion.net
0.0.0.0  static.funshion.com
0.0.0.0  pcookie.cnzz.com

全局模式下访问网页 就会在请求这些地址

pac下是没有的

**Comment by paperbag** [comment]
* 这不是 shadowsocks-windows 造成的。
* 代理时，hosts 文件不会生效。
* 请使用 Adblock Plus 等浏览器扩展解决网页广告问题。

**Comment by gdf159159** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1408

已经证明了 你们在全局模式下动了手脚 自行编译的就不会访问这些网址

风云给你们多少广告费?

**Comment by paperbag** [comment]
* 看不出你是怎么证明的，这两个 issue 没有任何关系。
* 如果你觉得有问题，请给出具体的网址，以及出现了哪些广告。

**Comment by celeron533** [comment]
你的机器中了恶意软件。本来这些地址在墙外无法访问，也没有被PAC定义在了翻墙网址列表中。全局模式下就能访问了。你说的证据不能说明什么。开源项目会有人夹带私货而不被发现？

**Comment by chenshaoju** [comment]
请尝试使用诺顿强力清除器扫描系统：
https://security.symantec.com/nbrt/npe.aspx?lcid=2052

**Comment by celeron533** [comment]
另外有可能是你下载的客户端被人动了手脚
