### ISSUE TITLE
问下 windows有什么测速tool可以详细记录SS的上行/下行带宽的

### ISSUE THREAD

**Issue by AmelieNet** [shadowsocks/shadowsocks-windows#1450]
自带的看不到顶 希望推荐一个windows工具
不然我都不清楚 GFW对我的IP限制了没有

**Comment by chenshaoju** [comment]
任务管理器->性能标签->资源监视器。

网络标签->网络活动的进程中找到shadowsocks.exe或obfs-local.exe，选中前面的小勾，然后就能看到对应进程的网速和TCP连接情况了。
