### ISSUE TITLE
请问是什么配置错误了吗？

### ISSUE THREAD

**Issue by longkm** [shadowsocks/shadowsocks-windows#1451]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
Shadowsocks-win-2.5.1

### Config and error log in detail (with all sensitive info masked)
[2017-10-13 01:14:47] System.Net.Sockets.SocketException: 这是在主机名解析时通常出现的暂时错误，它意味着本地服务器没有从权威服务器上收到响应。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.StartConnect()

**Comment by chenshaoju** [comment]
你所使用的服务器消失了，可能是域名停止解析或者被墙了。

请与你的SS服务商联系。
