### ISSUE TITLE
4.0.6可否更新XP系统的支持？

### ISSUE THREAD

**Issue by TouAkira** [shadowsocks/shadowsocks-windows#1452]
4.0.6要求安装NET Framework 4.6，但是电脑系统为XP无法安装
前期版本没有gsm加密方式无法对服务器连接，只有通过4.0.6版本进行连接，,能否对该问题更新解决？

**Comment by chenshaoju** [comment]
Windows XP 已经在三年前停止支持了，如果你需要使用最新的加密方法，建议使用Python版本：
https://github.com/shadowsocks/shadowsocks/issues/986
