### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by chengzhenping** [shadowsocks/shadowsocks-windows#1453]
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by chengzhenping** [comment]
what's the problem?

**Comment by chenshaoju** [comment]
Please upload your shadowsoks logs.
Maybe is your server has been blocked.
If you buy this shadowsocks form somewhere ,please contact your shadowsocks provider.

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1345#issuecomment-326476709

**Comment by liangzulin** [comment]
If you are using amazon AWS, please make sure to allow 8388 port for ss client connection. I solve the problem by this.

**Comment by JJJeffery** [comment]
I always used the amazon AWS EC2, every platform was working, But not working long ago, I don't know why?

**Comment by AlphaJi** [comment]
Shadowsocks server log is useful for my problem.
