### ISSUE TITLE
插件启用失败

### ISSUE THREAD

**Issue by jiangming1399** [shadowsocks/shadowsocks-windows#1454]
### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Windows 10 1703  64位

### Steps you have tried
1. 将Kcptun的执行文件重命名为kcptun后放到ss文件夹下
2. 使用如图所示的配置。
3. 单独使用kcptun不会出现此信息

### What did you expect to see?
![tim 20171014163359](https://user-images.githubusercontent.com/6049028/31574216-7ea84ec0-b0fd-11e7-9dce-b43b919a3cba.png)
日志中马赛克的是其他的配置的服务器IP地址。
任务管理器中kcptun的进程的命令行为“kcptun”

**Comment by chenshaoju** [comment]
请检查kcptun配置是否正确，从你的提示来看，似乎配置有问题。

simple-obfs的话，服务器地址填写的就是你的服务器地址，kcptun我没用过。

**Comment by jiangming1399** [comment]
问题解决。使用了原版的kcptun，而不是SIP-003支持的kcptun。

**Comment by webdone** [comment]
请教一下，有SIP-003支持的kcptun吗？哪里可以下载呢

**Comment by jiangming1399** [comment]
@webdone shadowsocks/kcptun

**Comment by vennsong** [comment]
@jiangming1399 
请问win的客户端 插件 配置kcptun 怎么解决的啊？
