### ISSUE TITLE
原版SS+chacha20-ietf-poly1305 与 SSR混淆 哪个安全？

### ISSUE THREAD

**Issue by aglent** [shadowsocks/shadowsocks-windows#1455]
听说现在都推荐用chacha20-ietf-poly1305了 不知道与SSR相比 哪个防止被检测到？

**Comment by chenshaoju** [comment]
chacha20-ietf-poly1305 一样被墙（我），你可以试一下simple-obfs。

https://github.com/shadowsocks/simple-obfs

**Comment by zyf2008Neptune** [comment]
一个是加密方式、一个是软件。
无论你用ss还是ssr，不要使用任何教程里的服务器端口配置。

**Comment by McContax** [comment]
麻烦问下各位dalao，windows的SSR应该怎么搞
