### ISSUE TITLE
端口最近频频被封，如何破解

### ISSUE THREAD

**Issue by kanggaogang** [shadowsocks/shadowsocks-windows#1456]
端口最近频频被封，如何破解。使用一天端口就被检测出来，然后被封。是加密算法被破解了吗还是？

**Comment by chenshaoju** [comment]
这是流量监测，你可以尝试搭配obfs进行使用，但是无法保证。

https://github.com/shadowsocks/simple-obfs

**Comment by zyf2008Neptune** [comment]
服务器端口不要使用常用端口（80、433、80xx、83xx）

**Comment by amaork** [comment]
可能是检测算法升级了，最近常用端口被封，换了端口就 OK, 试了没几次 IP 都被封了 T_T

**Comment by Heisenburg1900** [comment]
用了两天被封了端口，该怎么办……

**Comment by dancorpse** [comment]
请问端口设置有什么讲究么？应该用常用端口还是随意数字都没有关系？

**Comment by lanmingle** [comment]
哈哈，我 docker 跑的，在服务器上整了个定时任务，每隔 6 小时自动重启容器，容器端口是随机的，再通过 shell 导出端口，然后通过 curl 发微信信息，完美解决怕给封端口这个问题。

**Comment by JJJeffery** [comment]
难道前不久没法用了，是因为端口被封了？我一直用的1240端口，都正常使用1年多了。就前不久不能使用了。

**Comment by kanggaogang** [comment]
换了好多次端口，使用一天就被封了，搞得人都没法跟国外客户沟通了。最近也不敢换端口了，免得服务器地址被屏蔽。目前还没找到有效的办法。
