### ISSUE TITLE
第一次设置，连不上，不知是没设置正确还是其他问题

### ISSUE THREAD

**Issue by zwl1619** [shadowsocks/shadowsocks-windows#1458]
第一次设置，连不上，不知是没设置正确还是其他问题。
云主机上使用的这个：
https://github.com/oddrationale/docker-shadowsocks
根据文档，使用方法是运行一条命令：
```
docker run -d -p 1984:1984 oddrationale/docker-shadowsocks -s 0.0.0.0 -p 1984 -k $SSPASSWORD -m aes-256-cfb
```
服务端就设置完了。   

客户端分别使用ss和ssr尝试，都连不上；
客户端ss是这样设置的：
```
服务器地址：xx.xx.xx.xx
服务器端口：1984
密码：******
加密：aes-256-cfb
备注：
超时（秒）:5
代理端口：1984
```

客户端ssr是这样设置的：
```
服务器ip：xx.xx.xx.xx
服务器端口：1984
密码：******
加密：aes-256-cfb
协议：origin
协议参数：
混淆：random_head
混淆参数：
备注：
```

其他设置都没修改，使用的默认设置。哪里没有设置正确吗？

**Comment by chenshaoju** [comment]
请在服务器上执行 netstat -ln 查看你的SS服务端口是否开放。

如果没有开放，请与你的服务端支持人员联系。

**Comment by ycl20140111** [comment]
楼主搞定了没？我的情况是这样就一直超时
[2017-10-22 22:38:05] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-10-22 22:38:17] Shadowsocks started
[2017-10-22 22:38:32] 45.77.179.xx:xxxx timed out

**Comment by chenshaoju** [comment]
请确保你的IP能Ping通，如果能Ping通，请确保你的端口是通的，可使用 tcping.exe 进行测试：
https://www.elifulkerson.com/projects/tcping.php
