### ISSUE TITLE
恳求高人莫要抛弃XP系统

### ISSUE THREAD

**Issue by 0577215664** [shadowsocks/shadowsocks-windows#1459]
不知是何故，新版SS在XP系统里如死尸般，任凭点按，一动也不动，急煞人也。在此特求高人妙手回春，令SS在XP里重振雄风。

**Comment by rebiu** [comment]
1、XP已脱离维护期
2、XP不能安装上.NET 4.7
3、新版SS需要.NET 4.7

解决办法
1、收购微软，重新维护XP
2、用会XP支持的旧版本（不安全）
4、使用其他客户端（例如QT的）
5、使用命令行https://github.com/shadowsocks/shadowsocks-windows/issues/1452

**Comment by chenshaoju** [comment]
.Net Framework 2.x 存在某种不明原因的内存泄漏，一段时间后会吃光内存导致崩溃。而相同代码在 4.x 上编译后则无此问题。

详见： https://github.com/shadowsocks/shadowsocks-windows/issues/244

**Comment by ganwen1994** [comment]
惨死在插屁上了哦 为什么要还用插屁 O(∩_∩)O哈哈~

**Comment by celeron533** [comment]
#1452
