### ISSUE TITLE
Can not find "penimc.dll" after the last windows update

### ISSUE THREAD

**Issue by dcosmic** [shadowsocks/shadowsocks-windows#1460]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Windows 10 Enterprise 2015 LTSB

### Steps you have tried
restart the program

### What did you expect to see?
work properly

### What did you see instead?
crash

### Config and error log in detail (with all sensitive info masked)
[2017-10-15 13:30:35] [E] System.DllNotFoundException: 无法加载 DLL“penimc.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 MS.Win32.Penimc.UnsafeNativeMethods.CreateResetEvent(IntPtr& handle)
   在 System.Windows.Input.PenThreadWorker..ctor()
   在 System.Windows.Input.PenThreadPool.GetPenThreadForPenContextHelper(PenContext penContext)
   在 System.Windows.Input.PenThreadPool.GetPenThreadForPenContext(PenContext penContext)
   在 System.Windows.Input.TabletDeviceCollection.UpdateTabletsImpl()
   在 System.Windows.Input.TabletDeviceCollection.UpdateTablets()
   在 System.Windows.Input.TabletDeviceCollection..ctor()
   在 System.Windows.Input.StylusLogic.get_TabletDevices()
   在 System.Windows.Input.StylusLogic.RegisterHwndForInput(InputManager inputManager, PresentationSource inputSource)
   在 System.Windows.Interop.HwndStylusInputProvider..ctor(HwndSource source)
   在 System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   在 GlobalHotKey.HotKeyManager..ctor()
   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   在 Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
Please use Microsoft .NET Framework Repair Tool And follow wizard to fix problem https://www.microsoft.com/en-us/download/details.aspx?id=30135

If Microsoft .NET Framework Repair Tool can't fix this issue,Please Uninstall .Net Framework And Reinstall from: https://www.microsoft.com/en-us/download/details.aspx?id=55170
