### ISSUE TITLE
关于obfs的设置?

### ISSUE THREAD

**Issue by AmelieNet** [shadowsocks/shadowsocks-windows#1461]
![1](https://user-images.githubusercontent.com/7888766/31586956-5c371bf0-b20b-11e7-9cc0-2bde149bb10d.png)
### 1. obfs=tls;obfs-host=www.bing.com 这一段用加引号吗?
![2](https://user-images.githubusercontent.com/7888766/31586957-5fc55bb0-b20b-11e7-8f10-772f0f662b9b.png)
### 2. 为什么这个程序没有命令行参数呢?SS把设置告诉obfs了吗?

**Comment by chenshaoju** [comment]
１. https://github.com/shadowsocks/shadowsocks-windows/issues/1368

２.请访问 https://github.com/shadowsocks/simple-obfs 获取具体信息。
