### ISSUE TITLE
4.0.6二维码问题.

### ISSUE THREAD

**Issue by ganwen1994** [shadowsocks/shadowsocks-windows#1462]
同样的二维码,在SSR和4.0.6前版本识别无问题,唯独4.0.6有无法解析的问题.

不知道大家是不是都这样?

**Comment by chenshaoju** [comment]
该问题已知 https://github.com/shadowsocks/shadowsocks-windows/issues/1367

**Comment by GalaxyQiang** [comment]
我的也是，显示无效二维码，4.0.6

2017-10-16 4:35 GMT+08:00 ganwen1994 <notifications@github.com>:

**Comment by kmlixh** [comment]
我的也是4.0.6提示无法识别二维码

**Comment by LegendarYi** [comment]
4.0.6的已知bug, 等待更新修复吧.

**Comment by xuchengpeng** [comment]
on windows 10 1709 enterprise，same problem， old version 4.0.5 works perfect
