### ISSUE TITLE
could you please add 'json' for import servers 

### ISSUE THREAD

**Issue by liujason212** [shadowsocks/shadowsocks-windows#1464]
if you could support add servers by importing json format file  ,it will be so cool

如果你可以支持导入json格式的来添加服务器，真的会很棒……你也知道现在GFW多少可怕了

**Comment by celeron533** [comment]
URL格式已经足够，可以多行同时导入。
目前4.0.6解析URL和二维码有bug，DEV版本已经修复。
https://github.com/shadowsocks/shadowsocks-windows/issues/1367#issuecomment-331759358
