### ISSUE TITLE
关于shadowsocks的端口大家是如何操作的呢？今年5月12号，永恒之蓝virus是443端口，似乎是网络共享打印机的端口，会不会被侦测?

### ISSUE THREAD

**Issue by KuiperSirius** [shadowsocks/shadowsocks-windows#1465]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
永恒之蓝是139和445，HTTPS是443。

http://www.sohu.com/a/140705221_610132
