### ISSUE TITLE
建议增强user-rule相关功能

### ISSUE THREAD

**Issue by wusatosi** [shadowsocks/shadowsocks-windows#1468]
由于是学生党，学校网络封了部分网站所以经常使用user-rule，深感其中还有能改进的部分

1. user-rule和GFW-list有冲突
如同 #1408 下paperbag所说，因为gfw-list里包含了`@@||taobao.com`所以即使在user-rule内包含了`||taobao.com`的情况下ss依旧会无视taobao.com的代理要求，这一点对于不仅要访问Google但同时还要有其他特殊访问需求的人来说并不是很人性化，希望能对此改进

2. 希望能像log界面那样检查目前从user-rule载入的要求和正则，因为第一个问题所以总是苦恼于这些规则是否被载入进了ss

3. 希望能有个工具帮助用户输入user-rule，这个能在某种层面上可以解决第一个问题，可以做在ss内部亦或成为一个独立的工具

谢谢

**Comment by celeron533** [comment]
问题1：
最快的解决方法是使用类似于switchyOmega的基于浏览器自身的代理切换和控制软件。
由于现在是把`user-rule`追加在`gfwlist`之后，如果某条目已在`gfwlist`命中，后续的逻辑判断也不会被运行。所以设计上面临的问题是：遇到此类冲突，谁的优先级更高？（换言之，`user-rule`和`gfwlist`的内容写入顺序）

问题2：
Internet选项中可以看到当前生效的pac

问题3：
找一个好一点编辑器，如`notepad++`, `vscode`等

**Comment by jinliming2** [comment]
1. 个人觉得应该优先使用个人配置的，这样更合理吧？？！所以建议调整一下写入顺序。
2. 目前日志里是支持显示用户规则变化信息的。
![image](https://user-images.githubusercontent.com/10294977/32417024-c109f97a-c28d-11e7-914d-d04b1f80b0f4.png)
3. @celeron533 我觉得楼主的意思是做一个规则工具，而不是普通的带语法高亮的编辑器。一个用于生成规则语法的图形化工具，以便于非程序员方便编写自己的规则。
类似于这样：
![image](https://user-images.githubusercontent.com/10294977/32417084-d7a372be-c28e-11e7-95aa-da0d03072476.png)

**Comment by celeron533** [comment]
@jinliming2 
1. 将会调整user-rule在PAC中的顺序，将其放在前部而不是尾部。（这不禁让我想到了IPtables的chain顺序和cisco的路由顺序。。。）
2. #1332 已知bug :worried:。有时候在修改了user-rule后，最终的pac文件内容和预期不符。
3. 期待第三方工具出现

**Comment by Jingyu-Yan** [comment]
@celeron533 
使用最新的4.0.7后，虽然改动user-rule时会添加到PAC的前部，但是对于实际使用是没有效果的，上gfw-list里包含的'@@||xxx.com'依然是优先于user-rule的'||xxx.com'规则

**Comment by celeron533** [comment]
@Jingyu-Yan 已有人发现并提交了PR。惭愧。
#1564
