### ISSUE TITLE
Pac 更新问题

### ISSUE THREAD

**Issue by dry11orange** [shadowsocks/shadowsocks-windows#1470]
### Environment(win7, .NET Framework 4.5)

当更改user-rule文件时
程序能够实时监测到更改
并更新到pac文件

但当pac文件更改后
这些更改并没有生效
需要重新启动客户端才可以

能够在更改了pac文件或者user-rule文件之后
程序自动重载这些配置文件

**Comment by celeron533** [comment]
这里有个已知的bug

**Comment by wusatosi** [comment]
启用系统代理/更换PAC-全局模式也可以修复
