### ISSUE TITLE
访问ipv6网站失败

### ISSUE THREAD

**Issue by cathy0213** [shadowsocks/shadowsocks-windows#1471]
win10 ss 4.0.6
服务器配置如下：
```
{
    "server": "0.0.0.0",
    "server_ipv6": "[::]",
    "local_address": "127.0.0.1",
    "local_port": 1081,
    "port_password":{
        "aaa":"xxx"
        "bbb":"xxx"
    },
    "timeout": 120,
    "method":"aes-256-cfb",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": "",
    "redirect": "",
    "dns_ipv6": false,
    "fast_open": false,
    "workers": 1
}
```
### 客户端设置ipv4地址时，访问google, youtube成功
但设置ipv6地址后，访问失败
ss日志显示：
[2017-10-21 10:04:13] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

请问应该怎么解决？是不是服务端的配置有问题？

**Comment by chenshaoju** [comment]
你的服务器有IPv6地址吗？
如果没有，是无法使用的，请使用 ```ip addr``` 命令或 ``` ifconfig ``` 命令检查。

![image](https://user-images.githubusercontent.com/515763/31847715-48dc27c0-b653-11e7-9186-d4fd4bc7455a.png)

**Comment by cathy0213** [comment]
@chenshaoju 服务器地址有IPv4和IPv6，当客户端使用服务器的IPv4地址时，能够ping通服务器的IPv6地址，能够访问ipv6.google.com，无法访问bt.byr.cn，显示 找不到服务器 DNS 地址。
但当客户端使用服务器的IPv6地址时，会出现前面描述中的问题，日志显示：向一个无法连接的网络尝试了一个套接字操作。

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/1035#issuecomment-284996308

**Comment by cathy0213** [comment]
> 请尝试：#1035 (comment)
@chenshaoju 
遇到的问题类似，但我没有使用finalspeed，server改成“::”也是失败的。
大概也需要我瞎折腾吧 : )

**Comment by celeron533** [comment]
1. 确认你的server是有能力访问v6站点的
2. 一般居民网络不太会允许v6直接出境，大学网络似乎可以

**Comment by KuiperSirius** [comment]
事实上，就目前的基础设施建设而言，IPv4短时间是不可能放弃的，尾大不掉的现状没办法。IPv6地址目前是无法播放YouTube视频的，况且，你的ISP一般是不会给你分配IPv6地址的。IPv6地址还是常见于教育机构和科研机构。

**Comment by KuiperSirius** [comment]
1.常用的方法其实可以转化IPv4流量，利用隧道传输，可以自建，也可以寻找可以提供IPv6的VPN商家（比较稀少且价格不菲）。
2.您大可不必担心，您可以向一些iOS开发人员求助。（苹果强制要求，2016年6月1日起，AppleStore中应用程序必须支持IPv6地址）他们是无法绕开这个问题的，定然能给予您帮助。

**Comment by celeron533** [comment]
使用v4 socks5透传v6的协议应该是没有问题的
