### ISSUE TITLE
如何在同一端口实现socks5与http

### ISSUE THREAD

**Issue by ritou11** [shadowsocks/shadowsocks-windows#1472]
ss支持socks5代理，同时设置系统代理的时候，也是同一端口，这个代理是http的。而ss_privoxy并不是在同一端口将socks转化为http，那么shadowsocks-windows中的这个功能是怎么实现的？

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/ShadowsocksController.cs#L547

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/Listener.cs#L123

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/Listener.cs#L205

**Comment by celeron533** [comment]
IE ----(http 1080)----> privoxy ----(socks5 random port)----> ss client
记得privoxy也接受socks5请求

**Comment by Fengzhiying2017** [comment]
内部应该做了端口映射吧

**Comment by LaelLuo** [comment]
> IE ----(http 1080)----> privoxy ----(socks5 random port)----> ss client
> 记得privoxy也接受socks5请求

我看了一下两者占用的端口就感觉很奇怪 ssr socks5代理占用1080端口 privoxy占用随机端口 但是1080端口却可以代理http
