### ISSUE TITLE
科学上网互助群 Telegram 群ID @ss2048

### ISSUE THREAD

**Issue by wulongji2016** [shadowsocks/shadowsocks-windows#1473]
考虑到微信等不安全，采用国外聊天软件 Telegram
群ID @ss2048 (直接在搜索栏搜索即可）
或者链接：t.me/ss2048

另外 欢迎尝试一下频道功能：
@ssvpn1024
或者t.me/ssvpn1024
(直接在搜索栏搜索即可）

群名：科学上网

ss 2048

建群目的：分享和交流科学上网经验，仅用于科学学术研究目的，禁止涉及敏感话题。
该软件请 自行翻墙下载 支持安卓 苹果 和PC端。大部分地区，注册时 需翻墙才能收到验证码

经典的网友回复：能科学上网的时候也不怎么需要交流，不能上网的时候想交流发现要先科学上网，这不是有点绕吗？

没有办法啊，谁敢在微信等国内聊天软件公开讨论科学上网呢？
![ss 2048](https://user-images.githubusercontent.com/24681808/31860368-71d84612-b721-11e7-9dad-c42f31720f3c.jpg)

**Comment by wulongji2016** [comment]
群已经270多人了

**Comment by aglent** [comment]
多谢

**Comment by willis-hu** [comment]
我的安卓和电脑客户端怎么都搜索不到…………

**Comment by wulongji2016** [comment]
搜索 @ss2048 即可 

@willis-hu

**Comment by gaoshijun1993** [comment]
请问使用telegram怎么配置pac包?我每次都必须切换到全局模式

**Comment by aolphn** [comment]
群是不是解散了，怎么搜不到？
