### ISSUE TITLE
在vultr自建的vps连接手机和win失败问题在线等

### ISSUE THREAD

**Issue by ycl20140111** [shadowsocks/shadowsocks-windows#1474]
手机端shadwosocks用的是Wingy v1.1.12build:1705231.电脑版shadowsocks4.0.6都是在shadowsocks官网里下载的。System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-10-22 22:38:17] Shadowsocks started
[2017-10-22 22:38:32] 45.77.179.xx:xxxx timed out

**Comment by ycl20140111** [comment]
在vps里安装的这个东东
Shadowsocks success

Congratulations, Shadowsocks-Python server install completed!

Your Server IP        :  45.77.179.xx

Your Server Port      :  xxxx 

Your Password         :  xxx 

Your Encryption Method:  aes-256-gcm 


Welcome to visit: https://teddysun.com/486.html
Enjoy it

**Comment by ycl20140111** [comment]
System.IO.IOException: 由于远程方已关闭传输流，身份验证失败
这是在win客户版4.0.6里的日志。我mac电脑里现在什么翻墙软件都不用开也可以连外网，我也不知道是不是我在mac电脑用终端执行脚本的原因所致。太难了。

**Comment by ycl20140111** [comment]
高手进来帮忙看看啊。

**Comment by chenshaoju** [comment]
看起来你用的是懒人包，请确保你的IP能Ping通，如果能Ping通，请确保你的端口是通的，可使用 tcping.exe 进行测试：
https://www.elifulkerson.com/projects/tcping.php

如果仍然搞不定，请与你的懒人包制作者联系，以便排查问题。

**Comment by 0312birdzhang** [comment]
我的也是这个错误
```
System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

**Comment by LBYPatrick** [comment]
请自己配置一次，按照官方的教程写config, 然后
```bash
nohup sserver -c (配置文件路径) -d start > ss.log &
```
你还可以通过换成shadowsocks-libev来使用chacha20等新型算法而不是aes-256-gcm，这样可以提高速度
祝你好运。

**Comment by AndroidPreView** [comment]
我的也是一样问题，怎么解决呢，看了上面的答案有点不是很明白，可以在解释清楚点吗？
