### ISSUE TITLE
开启代理后自动开启“跳过本地地址的代理服务器”

### ISSUE THREAD

**Issue by iPhoneos0** [shadowsocks/shadowsocks-windows#1475]
开启ss后，自动勾选了Internet选项-LAN设置-“跳过本地地址的代理服务器”。
然后我这里由于权限不足，是灰色无法更改的，现在我如何恢复这里的未勾选的状态？
求助，谢谢

**Comment by chenshaoju** [comment]
选中这个就可以取消了：

![image](https://user-images.githubusercontent.com/515763/31893482-396e4204-b83e-11e7-97c8-d0f18bf36560.png)

**Comment by iPhoneos0** [comment]
下面那个代理服务器的两个选项是全灰色的，无法设置，因为权限的设置，但是我这里又不好找有权限的人，十分尴尬

**Comment by chenshaoju** [comment]
打开注册表编辑器，定位到
```
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Connections\DefaultConnectionSettings
```
找到 ``` DefaultConnectionSettings ``` 键值并删除即可。

**Comment by iPhoneos0** [comment]
权限不足，打不开注册表，十分尴尬

**Comment by celeron533** [comment]
看来要通过sysproxy.exe手动设置了

**Comment by chenshaoju** [comment]
``` reg ```命令能用吗？

**Comment by iPhoneos0** [comment]
开始菜单没有运行，尝试运行注册表编辑器提示被禁用

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/31937812-3419b0d6-b8e8-11e7-933b-38891a4a5fc0.png)

**Comment by iPhoneos0** [comment]
我打不开cmd，提示被禁用，但是我新建一个bat文件，输入reg /?，打开是可以在一瞬间看到图片上的这些提示的

**Comment by chenshaoju** [comment]
尝试执行：
```
reg delete "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections" /v DefaultConnectionSettings
```

**Comment by celeron533** [comment]
另一种思路。解铃还需系铃人，ss-win使用ss_win_temp下的sysproxy.exe来设置代理的。sysproxy.exe的行为比较底层，能绕过你的IT限制。按照以下参数调整试试看。
```
Usage: sysproxy.exe global <proxy-server> [<bypass-list>]
             bypass list is a string like: localhost;127.*;10.* without trailing
 semicolon.
       sysproxy.exe pac <pac-url>
       sysproxy.exe query
       sysproxy.exe set <flags> [<proxy-server> [<bypass-list> [<pac-url>]]]
             <flags> is bitwise combination of INTERNET_PER_CONN_FLAGS.
             "-" is a placeholder to keep the original value.
```

**Comment by celeron533** [comment]
无法直接打开`cmd.exe`可以使用命令复制`cmd.exe`到`mycmd.exe`，然后尝试运行`mycmd.exe`

**Comment by wongsyrone** [comment]
用这个 global <proxy-server> [<bypass-list>]

在bypasslist里面去掉前缀的 <local> 这个是特殊标记，用来勾选『本地地址不使用代理服务器』的

**Comment by wongsyrone** [comment]
具体sysproxy传参看Util/SystemProxy/Sysproxy.cs

**Comment by ouyangrui** [comment]
> 具体sysproxy传参看Util/SystemProxy/Sysproxy.cs

请问sysproxy 关闭代理应该如何传参，没有找到代码，感谢
