### ISSUE TITLE
简述目前的情况供大家参考

### ISSUE THREAD

**Issue by nictse2013** [shadowsocks/shadowsocks-windows#1476]
今天开始有线上不去，折腾一上午无果，换无线后可以，此间IOS一直可以
换无线后，ios也不可以了，以上都在统一运行商下。ios换流量后又可以。
下午找了个别的账号，无线 iOS都可以了，但有线还是不行
看来有所动作了。。。。。。

**Comment by pexcn** [comment]
毫无参考价值

**Comment by nictse2013** [comment]
iOS老地址突然又能上了，同一地址台式机还是不行

**Comment by huangmin2667** [comment]
南京的情况差不多，也是这样，流量目前还能用，WIFi已经不能用了，不知道是定点封还是一刀切的，我在公司还可以用

**Comment by huangmin2667** [comment]
我认为真没有必要，我们就是干活的，就是查查资料，方便工作，哎搞成现在这个样。

**Comment by nictse2013** [comment]
奇怪的是同一个网下，iOS没问题，WIN端就是不行。。。。

**Comment by lowkeyjoe** [comment]
看样子gfw升级了，翻墙事业还努力。

**Comment by nictse2013** [comment]
最新情况 网线不行 WIFI可以 WIN端，应该是升级了，不知道用的什么侦测方法。。。。。。

**Comment by ikkyusan123** [comment]
参考v2ex的帖子https://www.v2ex.com/t/400557#reply79，这是因为网络开启了端口白名单，我们公司网络ss不能用，但是家庭网络就能用，手机连移动4G也能用，但是连wifi就不行。

**Comment by nictse2013** [comment]
LS，我上面说的就是公司的情况，不过公司的网线和WIFI的DNS不一样，应该是不同的网络

但是奇怪的是我在家也是WIN10网线上不去，mac ios没事
我在另一个帖子里发过，偶尔上了一次后就不行了

今天把插无线网卡试试

**Comment by nictse2013** [comment]
现在我这网线突然可以了，只能理解为不是客户端的问题，是更上面的事。
ls可以试试
