### ISSUE TITLE
服务器端口设置成22不能代理

### ISSUE THREAD

**Issue by ikkyusan123** [shadowsocks/shadowsocks-windows#1479]
### Version(release version or AppVeyor link)
Shadowsocks 4.0.5

### Environment(Operating system, .NET Framework, etc)
win7 旗舰版， .NET Framework 4.7

### Steps you have tried
我把服务器端口设置了22、80、443、8388共4个端口，22端口不能实现代理，其他三个都行

### What did you expect to see?
公司网络对端口进行了封堵，只有22端口能用，我想通过22端口实现代理。

### Config and error log in detail (with all sensitive info masked)
日志里面没有弹出任何错误

**Comment by chenshaoju** [comment]
如果你的服务器的sshd已经工作在22端口，那么你将不能使用22端口作为SS的代理。

因为端口是独占的。

**Comment by ikkyusan123** [comment]
我的ssh端口确实是22端口，谢谢解答。
