### ISSUE TITLE
测试了三台电脑，都是win10，两台可以链接，还有一台报错目标计算机积极拒绝，是我第三台电脑配置的问题？

### ISSUE THREAD

**Issue by Mindsj** [shadowsocks/shadowsocks-windows#1480]
测试了三台电脑，都是win10，两台可以链接，还有一台报错目标计算机积极拒绝，是我第三台电脑配置的问题？

**Comment by celeron533** [comment]
如果是同一个网络，那基本上是配置问题

**Comment by Mindsj** [comment]
是同一网络，这个报错可能是哪个设置影响了。。。研究了半天，试了很多办法都没用。。。又遇到类似问题的吗

**Comment by LBYPatrick** [comment]
@Mindsj 这个问题还真的挺蛋疼的，但是关掉shadowsocks再开就好了。坐标美国东部，也有这个问题，某墙不背这个锅，应该可以当成bug反馈了

**Comment by chenshaoju** [comment]
请尝试在有问题的计算机上使用TCPing：
https://www.elifulkerson.com/projects/tcping.php

对你的SS服务器所在的IP和端口进行测试，格式为：
```
tcping.exe 123.45.67.89 9876
```
其中 123.45.67.89 替换为你的服务器IP， 9876 替换为你的SS所在端口。

**Comment by nictse2013** [comment]
你的WIN10是网线还是WIFi

**Comment by Mindsj** [comment]
@nictse2013 网线和wifi都试了下，都不行，两者有什么区别吗

**Comment by celeron533** [comment]
win10近期有推送大补丁，虽然没有提示一定要重启机器，但有时候部分应用程序会抽筋。我自己也遇到过一起，还以为服务器被干掉。重启后恢复。

**Comment by yoo0** [comment]
tcping 能通，但是依然连不上。不知道什么情况

**Comment by chenshaoju** [comment]
@yoo0 请帖出日志。

**Comment by yoo0** [comment]
@chenshaoju 
[2017-10-30 14:44:06] System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password, Boolean onetimeauth, Boolean isudp)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2017-10-30 14:44:06] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.TCPHandler.Close()

**Comment by chenshaoju** [comment]
@yoo0 是否启用了状态统计，如果是，禁用看看。
