### ISSUE TITLE
window ss

### ISSUE THREAD

**Issue by AndroidPreView** [shadowsocks/shadowsocks-windows#1481]
ios和mos都可以使用，同一服务器，之前winow可以，这几天就不行了，不知道大家有没有这个问题

**Comment by chenshaoju** [comment]
我没有这个问题，是相同网络吗？

**Comment by AndroidPreView** [comment]
不同网络

**Comment by chenshaoju** [comment]
已知该问题为不可抗力。
详情阅读：
http://www.solidot.org/story?sid=54258
和
http://www.solidot.org/story?sid=54249

**Comment by nictse2013** [comment]
我说同网不行，其他情况如LZ，尝试WIFI链接试试

**Comment by nictse2013** [comment]
我是同网其他情况如LZ，建议WIFI链接试试

**Comment by yoo0** [comment]
我也有你这个情况，连得同一wifi。ios和mac可以用，windows死活连不上。另外一个服务器就可以上，很奇怪。

**Comment by JJJeffery** [comment]
我自己在EC2上搭建的SS，之前各平台（Android\Windows\IOS）一直能用，在十九大前夕的某一天（记不清楚了）就全部不能用了，能连接上但没网。
