### ISSUE TITLE
使用windows局域网内允许访问  pac地址更改后 只有本机生效 局域网访问则不生效

### ISSUE THREAD

**Issue by df4712** [shadowsocks/shadowsocks-windows#1482]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
微软的说法是，有３０秒的延迟。不过你可以按照下列方法修改一下试试：

https://answers.microsoft.com/en-us/ie/forum/ie8-windows_xp/internet-explorer-proxy-settings-timeout/b357c3a1-7ff5-4b3a-80b3-0eb42ba51274?auth=1

**Comment by celeron533** [comment]
你的其他局域网主机的PAC地址有没有填？因为有时候用户会直接填写代理端口，转发所有流量而不是那个pac的地址。

**Comment by df4712** [comment]
我这边局域网主机用的是Chrome浏览器+SwitchyOmega  估计方法不对 ie的我测试一下

**Comment by chenshaoju** [comment]
看看这个参数：

![image](https://user-images.githubusercontent.com/515763/32153001-9ea6aed0-bd62-11e7-8f8d-4999893a32f7.png)

**Comment by df4712** [comment]
@chenshaoju  更新的参数选择后 无效

**Comment by celeron533** [comment]
禁用 secure PAC
