### ISSUE TITLE
ss

### ISSUE THREAD

**Issue by cangqiongzhizhou** [shadowsocks/shadowsocks-windows#1483]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

4.0.4
### Environment(Operating system, .NET Framework, etc)
windows 10 1709（16299.19）

### Config and error log in detail (with all sensitive info masked)

**Comment by cangqiongzhizhou** [comment]
Google chrome 和 Microsoft edge都出现这种情况。而且关闭了代理之后无法恢复。无论是下载文件时手动选择下载位置，还是上传文件时选择文件，又或者另存为时弹出的文件选择窗口，只要弹出来，浏览器就会未响应

**Comment by celeron533** [comment]
这个现象一般和代理没有联系
