### ISSUE TITLE
連入ss-server正常，但不能訪問server端的區域網路

### ISSUE THREAD

**Issue by kib67835** [shadowsocks/shadowsocks-windows#1485]
### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
windows 10

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
请尝试使用Firefox，并单独指定代理看看？并确保No Proxy里没有 192.168.xx.xx 的IP地址。

PS：我修改了端口号，请按照实际情况填写。

![image](https://user-images.githubusercontent.com/515763/32140234-6695cf5e-bc94-11e7-9dfe-2fad8cac6463.png)

**Comment by kib67835** [comment]
我試過了，如chenshaoju的方法是可行的，網頁是可以連入的。
再請教兩件事
1 有方法可以連入區網的網路芳鄰嗎？
2 拜訪區網的功能能關掉嗎？

感謝chenshaoju的回覆

**Comment by celeron533** [comment]
1. ss设计之初只是一个Web代理，并不代理类似于SMB等网上邻居（台：网路芳邻）等协议
2. 通过iptables实现，网上应该有例子
