### ISSUE TITLE
索引超出数组界限 - Sysproxy

### ISSUE THREAD

**Issue by 9hj** [shadowsocks/shadowsocks-windows#1487]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

4.0.6
### Environment(Operating system, .NET Framework, etc)

win10 
### Steps you have tried
run the client

### Config and error log in detail (with all sensitive info masked)
System.IndexOut

**Comment by chenshaoju** [comment]
你好，只有这一行内容吗？

如果是，请将 SS 所在目录下的 config.json 文件改名移动到其他目录，然后再启动看看。

**Comment by 9hj** [comment]
![qq 20171028185329](https://user-images.githubusercontent.com/15857307/32133782-9284ebbe-bc11-11e7-9bcd-114cc6db28c4.png)
您好，不好意思打扰了，
issue未提交全抱歉，
将config.json移动后，启动也是错误
重下客户端，错误也是不变，

之前使用情况良好，未有过的情况

![qq 20171028185329](https://user-images.githubusercontent.com/15857307/32133781-860681c2-bc11-11e7-8a2e-a358afb83330.png)

**Comment by 9hj** [comment]
您好，不好意思打扰了，
issue未提交全抱歉，
将config.json移动后，启动也是错误
重下客户端，错误也是不变，

之前使用情况良好，未有过的情况

![qq 20171028185329](https://user-images.githubusercontent.com/15857307/32133813-e43d8e52-bc11-11e7-84da-9f2906d0ab01.png)

**Comment by chenshaoju** [comment]
请退出SS，然后删除ss所在目录下的ss_win_temp文件夹，然后再试。

如果仍然不行，请将 Shadowsocks.exe 复制到一个空目录，再从这个空目录中启动，能否正常？

**Comment by 9hj** [comment]
您好，重新下载客户端，重新启动电脑，都未解决问题，4.0.5版本也不可以了，
但是以前用的2.5.6可以
丢虚拟机跑肯定没问题的，
这系统的问题，自己捣鼓吧，要不然还原哭~~~~

**Comment by chenshaoju** [comment]
请尝试使用 https://www.microsoft.com/en-us/download/details.aspx?id=30135 进行修复。

如果修复失败，请下载 https://www.microsoft.com/en-us/download/details.aspx?id=55170 ，并按照提示卸载然后重新安装。

**Comment by 9hj** [comment]
我重装4.7.1，还是出错，必须4.7？不过没关系，出错信息不点确认还是可以正常使用，点了确认就强退

**Comment by chenshaoju** [comment]
4.6.2也可以用，但是出于安全考虑，仍建议使用最新版本来避免漏洞或其它问题。

**Comment by celeron533** [comment]
可能是`sysproxy.exe`的输出并没有符合格式。
`        private static void ParseQueryStr(string str)
        {
            string[] userSettingsArr = str.Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
            _userSettings.Flags = userSettingsArr[0];

            // handle output from WinINET
            if (userSettingsArr[1] == "(null)") _userSettings.ProxyServer = null;
            else _userSettings.ProxyServer = userSettingsArr[1];
            if (userSettingsArr[2] == "(null)") _userSettings.BypassList = null;
            else _userSettings.BypassList = userSettingsArr[2];
            if (userSettingsArr[3] == "(null)") _userSettings.PacUrl = null;
            else _userSettings.PacUrl = userSettingsArr[3];

            _userSettings.UserSettingsRecorded = true;
        }
`
找到你`ss_win_temp`下的`sysproxy.exe`，使用参数`query`执行，并贴出结果。
如下图：
![image](https://user-images.githubusercontent.com/3608762/32140450-9c9db74a-bc9b-11e7-923e-f2f017076cfc.png)

**Comment by 9hj** [comment]
![qq 20171030123414](https://user-images.githubusercontent.com/15857307/32154873-b5bfee18-bd6e-11e7-83db-26d56c6ef075.png)
好像是的

**Comment by wongsyrone** [comment]
把StringSplitOptions.RemoveEmptyEntries去掉

**Comment by wongsyrone** [comment]
使用 `sysproxy query > a.txt`命令，然后把生成的a.txt源文件发出来，需要看包含不可见字符的内容

**Comment by wongsyrone** [comment]
有个恢复方法，管理员运行

```
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable /t REG_DWORD /d 0 /f
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyServer /f
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyOverride /f
```

然后再次 sysproxy.exe query

理论结果应该是

```
>sysproxy query
1
(null)
(null)
(null)
```

**Comment by 9hj** [comment]
解决了，非常感谢
写注册表前
![qq 20171030162938](https://user-images.githubusercontent.com/15857307/32161271-df7b4542-bd8f-11e7-88bf-751172cdc71d.png)
写注册表后
![qq 20171030163101](https://user-images.githubusercontent.com/15857307/32161284-eeaa4824-bd8f-11e7-8edc-249942713cfb.png)

**Comment by 9hj** [comment]
解决了，非常感谢！
![qq 20171030162938](https://user-images.githubusercontent.com/15857307/32161473-98e30d62-bd90-11e7-94b0-5768e3bce329.png)
![qq 20171030163618](https://user-images.githubusercontent.com/15857307/32161476-9c9bfbd0-bd90-11e7-8093-c14a9ddbd9bd.png)

**Comment by anzyhui** [comment]
> 有个恢复方法，管理员运行
> 
> ```
> reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable /t REG_DWORD /d 0 /f
> reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyServer /f
> reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyOverride /f
> ```
> 然后再次 sysproxy.exe query
> 
> 理论结果应该是
> 
> ```
> >sysproxy query
> 1
> (null)
> (null)
> (null)
> ```

或者
在注册表中，找到指定的键，删除就行：
![image](https://user-images.githubusercontent.com/15945043/47699725-cece8180-dc4e-11e8-952c-40e124635528.png)
