### ISSUE TITLE
Exception - 集合已修改

### ISSUE THREAD

**Issue by zzj0311** [shadowsocks/shadowsocks-windows#1490]
### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
win10 1709, I guess it's .net 4.5.1

### Steps you have tried
nothing

### What did you expect to see?
nothing

### What did you see instead?
![ERROR_LOG](https://user-images.githubusercontent.com/12032057/32142875-48c0695c-bcdb-11e7-88cf-44fe7d7c2085.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
Please try Disable "Enable Statistics" In here:

![image](https://user-images.githubusercontent.com/515763/32143321-85b189a2-bce2-11e7-9e1c-13f9907995e8.png)

https://github.com/shadowsocks/shadowsocks-windows/issues/1168
