### ISSUE TITLE
一直显示"非法服务器地址"

### ISSUE THREAD

**Issue by chaodongyue** [shadowsocks/shadowsocks-windows#1492]
### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
WIN10 X64, .NET Framework v4.0.30319, 加密方式chacha20-ietf,服务端 shadowsocks-libev

### Steps you have tried
nothing

### What did you expect to see?
nothing

### What did you see instead?
![tim 20171030164756](https://user-images.githubusercontent.com/1543666/32161952-4f7c3548-bd92-11e7-871e-a755a1f0c064.jpg)

### Config and error log in detail (with all sensitive info masked)

**Comment by chaodongyue** [comment]
使用android和SSCapV4.0时可以连接的

**Comment by celeron533** [comment]
你输入了什么数据？

**Comment by chaodongyue** [comment]
服务器地址(IP),端口,密码和选择加密,,然后点击添加.点回去刚刚添加的就出这个错

**Comment by chenshaoju** [comment]
该提示是正常的，如果你新建了一个服务器信息，但是不填写任何数据并点击其他服务器配置信息就会出现该提示。

点击确定后，会返回你新建的服务器信息，点击删除按钮删掉你所新建的服务器信息即可。

**Comment by chaodongyue** [comment]
希望增加这使用上的体验优化

**Comment by fabware** [comment]
被这个问题坑到了，作为一个"老手"还浪费不少时间。原因是填完服务器信息后没有立即点“确认”，而是点了“添加”（要不然为什么说自己是老手呢，有时候有些软件你不点添加，下次还得再输一遍），这时再点“确认”或服务器信息的时候就会出现“非法服务器地址”的问题。解决办法很简单，在选中“未配置的服务器”的状态下，点击“删除”，就可以了。

这是一个软件本身交互设计的问题。下面详细重现步骤和改进的建议：

重现的方法：
1、打开软件（现在左侧是“未配置的服务器”），在右侧“服务器”的表单中填入正确的服务器信息；
2、点击“添加”；
3、然后在左侧点击刚才输入的服务器（或者点“确认”），就会碰到“非法服务器地址”。

在这个时候，用户已经完全无法正常使用软件。当弹出“非法服务器地址”的时候，用户会以为是自己刚才输入的服务器地址不对，而没有注意到是“未配置的服务器”地址为空不对。

改进建议：
1、在用户切换到已经填好的服务器时，不要检查未对“未配置的服务器”的默认值做过任何修改的表单；
2、在用户已经填写了至少一个服务器的情况下，点击“确认”，不要检查未对“未配置的服务器”的默认值做过任何修改的表单。

非常感谢开发者的辛苦工作，也希望能对此做一些改进，帮到使用者也给自己省一些麻烦。
