### ISSUE TITLE
请问什么时候支持xchacha20-ietf-poly1305？

### ISSUE THREAD

**Issue by moonwater** [shadowsocks/shadowsocks-windows#1493]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6.0

### Environment(Operating system, .NET Framework, etc)
windows

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
#1135
