### ISSUE TITLE
所有网页都不能访问打开

### ISSUE THREAD

**Issue by gemma-tqm** [shadowsocks/shadowsocks-windows#1496]
win10
.net 应用和功能列表显示4.6，在“启用或关闭windows 功能”里可以看到4.7高级服务。（已手动从官网下载4.7.1并且安装）
vpn版本4.0.4，也在github下载4.0.6用了，一样不能打开任何网页
加密 aes-256-cfb
代理端口 1080

### Steps you have tried
①开启Shadowsocks.exe
②右键任务栏，启动系统代理，选择pac或者全局都试过
③浏览器选择“系统代理”
④打开网页，显示无法访问此网站

### What did you expect to see?
①我是普通用户，使用vpn主要是访问网站，3月19日付费购买vpn之后一直用着也挺正常，今天登陆就发现不能打开网页了。请问可以怎么样去找出什么原因并且解决~
②之前是在这个网站 https://portal.shadowsocks.com.hk/index.php 购买的，现在这个网站貌似已经无用了，请问后续是在哪个地方去续费或者查询自己账户？

**Comment by rebiu** [comment]
1、请联系你购买的服务商
2、你上面提到的服务器和这个开源项目没半毛钱关系
3、所以不是软件问题

**Comment by gemma-tqm** [comment]
@rebiu 好的吧，谢谢~ 我是右键任务栏-帮助-关于，就跳到这里来了，所以以为可以联系到。不好意思。
