### ISSUE TITLE
putty 输入IP 地址打开后没反应，是什么原因？

### ISSUE THREAD

**Issue by xzyn2016** [shadowsocks/shadowsocks-windows#1499]
![default](https://user-images.githubusercontent.com/32762811/32313177-734ecb7e-bfdc-11e7-9865-80a8a755b133.png)

**Comment by pexcn** [comment]
putty 的问题都发到这来？

**Comment by xzyn2016** [comment]
找不到putty的论坛我就发这了，能告诉我论坛地址不？中文的
