### ISSUE TITLE
关于win10下wifi可以墙，网线无法墙的问题

### ISSUE THREAD

**Issue by HiramYong** [shadowsocks/shadowsocks-windows#1502]
win10下使用的是4.0.6版本，使用过程中碰到一个奇怪的问题，用网线连接成功连接到服务器，但不会产生数据流量，墙外网站无法打开。换成wifi连接，一切正常。手机端也能正常使用。
问题补充：win10防火墙都处于关闭状态

**Comment by chenshaoju** [comment]
请尝试以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，都执行完毕后重启后再看看。

**Comment by yohannhao** [comment]
@chenshaoju 
刚刚按你的方法尝试了一下，无果

**Comment by chenshaoju** [comment]
SS的日志里有无输出？

**Comment by yohannhao** [comment]
@chenshaoju 
![image](https://user-images.githubusercontent.com/28978545/32402121-f984b042-c157-11e7-9fb2-9cbd6fbc819d.png)

**Comment by chenshaoju** [comment]
不确认发生了什么。
可能的原因有：
１.加密方式不正确
２.密码不正确。
３.在不支持OTA的服务器上启用了OTA。（如果服务器配置界面没显示OTA选项的话则忽略该原因）

**Comment by JerwinLiao** [comment]
我也出现了同样的问题，wifi可以，拨号不可以

**Comment by chenshaoju** [comment]
拨号可能需要退出然后再启动SS一次看看。

如果可能，使用Firefox然后指定代理看看？

注意，下图中的 12345 需要替换为你SS在本地的端口号。

![image](https://user-images.githubusercontent.com/515763/32437072-20435ca4-c321-11e7-9e5f-0e28a0e9f59f.png)

**Comment by JJJeffery** [comment]
我自己在EC2上搭建的SS，之前各平台（Android\Windows\IOS）一直能用，在十九大前夕的某一天（记不清楚了）就全部不能用了，能连接上但没网。

**Comment by JerwinLiao** [comment]
事实上，拨号上网能连接vpn服务器，但是这边浏览器发出请求，ss的日志没有反应，浏览器指定了代理和端口也没有用，每次重启ss都会重置vpn设置，电信的wifi可以用。我用的教育网，会不会是这个原因呢？

**Comment by chenshaoju** [comment]
有可能你的教育网有某种屏蔽？

**Comment by chenshaoju** [comment]
PS：有人跟你类似，但是他是联通校园网（？），你看看 https://github.com/shadowsocks/shadowsocks-windows/issues/1421

**Comment by yohannhao** [comment]
@chenshaoju @JerwinLiao @JJJeffery 
我用的是学校的网络，拨号要通过锐捷，大概是这个原因吧，谢谢诸位

**Comment by JerwinLiao** [comment]
但是前几天是没有问题的，我同学用的电信没问题，这几天教育网就不行了。

**Comment by chenshaoju** [comment]
无法确认。。。也许你的教育网客户端出现了某种限制？

**Comment by codehz** [comment]
@chenshaoju 
我发现的这个问题的**其中一个原因**是pac没有设置成功，win10 1709的某个build(?)修改了PPPoE连接的安全设置，无法通过原有方式设置PPPoE连接的pac网址，通过--proxy-pac-url运行的chrome是可以正常使用的

**Comment by chenshaoju** [comment]
@codehz 请尝试按照 https://github.com/shadowsocks/shadowsocks-windows/issues/1527 方法监测PAC变动。

**Comment by SaHaes** [comment]
@chenshaoju 
我用手机搭的ss可以正常运行，但win10电脑上就没有效果，日志我也看不懂，不知道怎么办了
![error3](https://user-images.githubusercontent.com/33786939/33017074-ee551d66-ce2b-11e7-950e-b97e51dc4bf5.jpg)

**Comment by yohannhao** [comment]
@SaHaes 请问您是不是用了校园网，或者拨号名为中文？

**Comment by SaHaes** [comment]
@yohannhao 
是校园网，但别人同样使用校园网没有出现这样的问题，就没往这方面想

**Comment by yohannhao** [comment]
@SaHaes 我的也是校园网，拨号名称由中文改为英文，便可以用了，不知您是否是这个问题

**Comment by SaHaes** [comment]
@yohannhao 
请问在哪里修改拨号名称，刚接触不太懂

**Comment by yohannhao** [comment]
@SaHaes 就是你电脑上的宽带拨号名称，和此软件无关，如图
![image](https://user-images.githubusercontent.com/28978545/33018390-2917af54-ce31-11e7-8875-754e0fd54223.png)

**Comment by SaHaes** [comment]
@yohannhao 试了一下，还是无法使用，不过还是谢谢你的帮助

**Comment by TNumFive** [comment]
@SaHaes 我和你是一样的网络，你可以试一下改名字后断开重新连接网络，我只改名字也不行，但是从新连接之后就可以了。

**Comment by SaHaes** [comment]
@TNumFive 看了一下，我的电脑是采用LAN接入，不是拨号的，所以改名称的方法可能不适合我的电脑

**Comment by 3nj0y** [comment]
手机连家里的wifi可以使用，电脑连wifi就不行，是否跟客户端不同有关系

**Comment by mj163163** [comment]
我有两台电脑，win7的可以用，win10的就不可以，连接也是提示超时，偶然能上一会，但是win7和手机都没问题，看来win10确实哪里有问题@SaHaes

**Comment by Lz1y** [comment]
我也出现了同样的问题，wifi可以，光纤不可以。。。

**Comment by chenshaoju** [comment]
@Lz1y WiFi和光纤是同一个网络吗？

如果是，请尝试在 控制面板\网络和 Internet\网络连接 中将你的“本地连接”（可能是本地连接 2、3、4……）改名为纯英文的（比如 Network）试试。

**Comment by 2018shawn** [comment]
我认为大家的问题是网线连接的代理设置，https://doub.io/ss-jc39/自行查看解决办法

**Comment by DavichiHug** [comment]
我也遇到了这个问题，在学校实验室用学校的网络，用PPPoE拨号上网然后shadowsocks连不到google，但是用隔壁笔记本的360wifi却可以连接google，而且还ping不通

![image](https://user-images.githubusercontent.com/23614846/38181078-63987182-3663-11e8-9e31-9de68563486a.png)

**Comment by chenshaoju** [comment]
SS不是VPN，Ping不走代理，所以无论你是否使用SS，都无法Ping通过。

如果是PPPoE拨号，请在拨号连接上后退出SS，然后再启动SS看看。

**Comment by DavichiHug** [comment]
@chenshaoju 非常感谢，解决了

**Comment by Chulinet** [comment]
宽带连接名称改为英文后也解决了，虽然不知道什么原因

**Comment by znkevin** [comment]
在编辑页面把代理端口改为2080完美解决。

**Comment by 5060** [comment]
我也遇到了一样的问题，我的网络是校园网；我先把ss关了，拨号成功之后在开ss，得到了解决。原因不明

**Comment by felixzhoume** [comment]
* windows 10
* 拨号上网
* 不是校园网

将宽带连接修改为英文状态，然后断开链接重连之后SS正常工作了

**Comment by Askmyc1995** [comment]
天啊这到底是什么bug为什么改成英文就好了？？？

**Comment by osmium18452** [comment]
> 在编辑页面把代理端口改为2080完美解决。

同改成2080就翻出去了

**Comment by wujiajun1998** [comment]
我是电脑可以翻，但是手机用移动流量就翻不了，手机连wifi就可以翻

**Comment by Lz1y** [comment]
> 我是电脑可以翻，但是手机用移动流量就翻不了，手机连wifi就可以翻

我也是这样，流量开关重启一次可以短暂的翻出去

**Comment by hybirdworld** [comment]
同是校园网 拨号上网 就把名称改了就可以了，这是什么原因啊

**Comment by lizhuhua310** [comment]
破号上网，改英文名称后可以使用

**Comment by XJTUKevin** [comment]
拨号上网，改英文名称之后可以用，为什么啊？

**Comment by Harrysii** [comment]
有用，名称改为英文就可用，这太神奇了

**Comment by hanchan66** [comment]
WIFI可以，有线网络不行的情况下，同样的本地监听端口改为2080完美解决。

**Comment by linhaismail** [comment]
> @Lz1y WiFi和光纤是同一个网络吗？
> 
> 如果是，请尝试在 控制面板\网络和 Internet\网络连接 中将你的“本地连接”（可能是本地连接 2、3、4……）改名为纯英文的（比如 Network）试试。

公司拔了网线使用无线网就可以，插上网线就不行。改了名字，完美解决！

**Comment by hoking3** [comment]
对啊，拨号上网，把名称改成英文然后断开ssr再连就可以翻墙了，感谢感谢！

**Comment by scorpiopr** [comment]
校园教育网，把名称改成英文再重启电脑重新连接，已经可以连上了！

**Comment by Andy96665** [comment]
太厉害了，改成英文完美解决！！谢谢解决

**Comment by ShougangShen** [comment]
请问电脑LAN接入，不是拨号联网怎么解决呢？

**Comment by Andy96665** [comment]
不好意思啊，我也是小白我也不太清楚

ShougangShen <notifications@github.com> 于 2020年6月7日周日 16:07写道：

**Comment by Alex-dengxz** [comment]
win10系统环境
有线网络下无法翻墙，但是无线网络下可以
有线网络：电信（非拨号），一开始发现是公用网络，改为专用后未解决问题。
关闭防火墙未能解决。
（也无法连接steam好友服务器（无线下不需要翻墙也能连接），然后比较奇怪的leetcode有线网络下也不能正常显示）

**Comment by 1091515459** [comment]
公司网络，改成全英名字重启，亲测可用

**Comment by qwe93450** [comment]
> @SaHaes 我和你是一样的网络，你可以试一下改名字后断开重新连接网络，我只改名字也不行，但是从新连接之后就可以了。

我也是这样

**Comment by Lincest** [comment]
端口改成2080 + 宽带连接改成英文 + 重启 亲测可

**Comment by Whenshow** [comment]
把宽带连接改名为英文，我改成了PPPOE，重启软件，进行连接就行了

**Comment by Untacki** [comment]
> @SaHaes 我的也是校园网，拨号名称由中文改为英文，便可以用了，不知您是否是这个问题

非常感谢

**Comment by Whenshow** [comment]
你好，是这个问题，我改成英文名就可用了，谢谢！发自我的华为手机-------- 原始邮件 --------发件人： Untacki ***@***.***>日期： 2021年5月5日周三 18:37收件人： shadowsocks/shadowsocks-windows ***@***.***>抄送： Whenshow ***@***.***>, Comment ***@***.***>主    题： Re: [shadowsocks/shadowsocks-windows] 关于win10下wifi可以墙，网线无法墙的问题 (#1502)



@SaHaes 我的也是校园网，拨号名称由中文改为英文，便可以用了，不知您是否是这个问题



非常感谢

**Comment by yofufufufu** [comment]
哥们今天一不小心开着v2ray代理认证校园网，结果认证过了以后网速极其慢，后来用移动热点翻墙都很慢。最后把网线拔了再插回去，再认证就没问题了。完事了以后搜索原因搜到这个问题，不知道有没有大佬解答，如果有学校的同学的遇到和我一样的问题也可以**插拔网线**再登录校园网试试

**Comment by yofufufufu** [comment]
> 哥们今天一不小心开着v2ray代理认证校园网，结果认证过了以后网速极其慢，后来用移动热点翻墙都很慢。最后把网线拔了再插回去，再认证就没问题了。完事了以后搜索原因搜到这个问题，不知道有没有大佬解答，如果有学校的同学的遇到和我一样的问题也可以**插拔网线**再登录校园网试试

补充一下，我当时还不是翻不出去，我是能翻但是速度很慢。甚至有一段时间开着PAC访问b站都很慢，严重怀疑是教育网对代理有某种限制，最色的是我后来改用热点翻，没有拔网线都没用！

**Comment by yofufufufu** [comment]
> > 哥们今天一不小心开着v2ray代理认证校园网，结果认证过了以后网速极其慢，后来用移动热点翻墙都很慢。最后把网线拔了再插回去，再认证就没问题了。完事了以后搜索原因搜到这个问题，不知道有没有大佬解答，如果有学校的同学的遇到和我一样的问题也可以**插拔网线**再登录校园网试试
> 
> 补充一下，我当时还不是翻不出去，我是能翻但是速度很慢。甚至有一段时间开着PAC访问b站都很慢，严重怀疑是教育网对代理有某种限制，最色的是我后来改用热点翻，没有拔网线都没用！

再补充一下，严格来说我不是插拔网线，我笔记本没有网线口，我是用了转接的，是插拔了USB接口

**Comment by 2306681547** [comment]
怎么改英文名啊

**Comment by TNumFive** [comment]
> 怎么改英文名啊

@2306681547 拨号上网的话，重新建立一个拨号上网链接，建立过程中可以设置网络名称。已经建立好的就找找网络适配器之类的，可能可以修改

**Comment by 2306681547** [comment]
> > 怎么改英文名啊
> 
> 
> 
> @2306681547 拨号上网的话，重新建立一个拨号上网链接，建立过程中可以设置网络名称。已经建立好的就找找网络适配器之类的，可能可以修改

那个大佬求求了，我改完英文名了，但是v2ray还是无法访问外网，但wifi是可以的

**Comment by TNumFive** [comment]
> > > 怎么改英文名啊
> > 
> > 
> > @2306681547 拨号上网的话，重新建立一个拨号上网链接，建立过程中可以设置网络名称。已经建立好的就找找网络适配器之类的，可能可以修改
> 
> 那个大佬求求了，我改完英文名了，但是v2ray还是无法访问外网，但wifi是可以的

@2306681547 ssr需要改是因为window下的编码问题，导致查找适配器的时候匹配不上。
不知道v2ray是不是这个原因，你可以朝着这个方向找找原因

**Comment by rongchaoChen** [comment]
我不是用的ssr是买的vpn。也是光猫直连后无法上网经过修改连接名称为英文可以了

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！

**Comment by fkjkkll** [comment]
> 公司网络，改成全英名字重启，亲测可用

神呐，天使

**Comment by xiaocheng223** [comment]
修改之后可以了，感恩

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！

**Comment by 2306681547** [comment]
已经解决，用clash可以替代V2rayN无法代理宽带的问题！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月8日(星期六) 中午11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shadowsocks/shadowsocks-windows] 关于win10下wifi可以墙，网线无法墙的问题 (#1502)





 
修改之后可以了，感恩
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hellozengweibin** [comment]
> @SaHaes 就是你电脑上的宽带拨号名称，和此软件无关，如图 ![image](https://user-images.githubusercontent.com/28978545/33018390-2917af54-ce31-11e7-8875-754e0fd54223.png)

在我将宽带名称的中文字符修改为英文字符后就可以正常使用拨号上网，成功通过VPN代理到外网，感谢！

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！

**Comment by wyblxy** [comment]
> @SaHaes 就是你电脑上的宽带拨号名称，和此软件无关，如图 ![image](https://user-images.githubusercontent.com/28978545/33018390-2917af54-ce31-11e7-8875-754e0fd54223.png)

谢谢，可以了，不过这是为啥呢

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！

**Comment by akisyy** [comment]
将“宽带连接”更改为英文.

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！

**Comment by lunkh** [comment]
我也是，WiFi可以换网线就不行，用的win11，后来在网络设置把"代理">“自动检测设置"打开就好了

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！

**Comment by GrimmYun** [comment]
想问一个问题，最近手机一用梯子，光猫宽带就会断一下，重连，网是电信宽带，这是电信设置什么了吗？

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！

**Comment by Zeal-katou** [comment]
居然真的可以。。。 原理是啥。。

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！

**Comment by shusuYYDS** [comment]
各位，我是数据能正常出，但是wifi和光纤都不行

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！

**Comment by roaminger** [comment]
感谢 @HiramYong @akisyy @Whenshow @Lincest ，来看2024年win11，将系统设置中->高级网络设置->网络适配器名称由“以太网”或者任何中文名改为英文就可以了

**Comment by wujiajun1998** [comment]
您好，我是吴佳俊。我已收到你的来信，我会尽快查阅并处理，感谢来信！
