### ISSUE TITLE
有些新的服务器端口用不了

### ISSUE THREAD

**Issue by henry16851** [shadowsocks/shadowsocks-windows#1504]
4.0.6版本SS，有些服务商的地址除了地址，密码，端口，加密方式外还多了下面这几个东西，类似混淆？ 貌似4.0.6用不了，怎么解决？ 手机shadowrocket没问题，

Protocol:
Protocol Param:
Obfs:
Obfs Param:

**Comment by chenshaoju** [comment]
这是ShadowsocksR支持的内容，具体请阅读你的SS服务商的支持库或帮助说明。

**Comment by henry16851** [comment]
Shadowsocks什么时候支持这些？ 我还是想用回原版，

**Comment by pongfcnkl** [comment]
应该是让你的ss服务商支持ss吧，怎么反过来了。。。

**Comment by henry16851** [comment]
小白不太懂这些，大概知道SSR就是SS的增强版这个说法
