### ISSUE TITLE
文件打不开

### ISSUE THREAD

**Issue by yangchaoqian** [shadowsocks/shadowsocks-windows#1505]
[2017-11-05 10:32:15] [E] System.ArgumentException: 字体“Consolas”不支持样式“Regular”。
   在 System.Drawing.Font.CreateNativeFont()
   在 System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font..ctor(String familyName, Single emSize)
   在 Shadowsocks.Model.LogViewerConfig..ctor()
   在 Shadowsocks.Model.Configuration.Load()
   在 Shadowsocks.Controller.ShadowsocksController..ctor()
   在 Shadowsocks.Program.Main()
[2017-11-05 10:35:16] [E] System.ArgumentException: 字体“Consolas”不支持样式“Regular”。
   在 System.Drawing.Font.CreateNativeFont()
   在 System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font..ctor(String familyName, Single emSize)
   在 Shadowsocks.Model.LogViewerConfig..ctor()
   在 Shadowsocks.Model.Configuration.Load()
   在 Shadowsocks.Controller.ShadowsocksController..ctor()
   在 Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
请使用Windows自带的记事本打开 SS 所在目录下的 gui-config.json 文件，找到【 "Font": "Consolas, 8pt",】（不含大括号） 一行，删掉后保存退出，再启动看看。

**Comment by celeron533** [comment]
#1376
