### ISSUE TITLE
运行ss不久死机

### ISSUE THREAD

**Issue by verck** [shadowsocks/shadowsocks-windows#1506]
开了之后就会出现死机，时间随机不超过5分钟。鼠标什么的完全动不了然后就显示要重启了。

**Comment by chenshaoju** [comment]
你好，我没遇到过这个现象。
请问“显示要重启了”是个什么显示？能否拍照或者截图上来？
如果有一个错误代码（类似于 0x12345678），请把错误代码也发上来。

**Comment by verck** [comment]
你好，
我发现了是在win10下， 打开steam后就会死机。不开steam没问题。 包括4.0.6和4.0.5再之前的版本就不清楚了。
其实就是win10的蓝屏，代码没记下来，另外桌面上图标之前摆放的位置都会全部回到最左边默认排列。

**Comment by celeron533** [comment]
这个看上去和ss没有很大的联系。蓝屏一般都是系统内核或者是内核相关的驱动发生了无法挽回的错误。

**Comment by verck** [comment]
试过好几次。不管steam和ss哪个后开只要两个在就死机。

**Comment by chenshaoju** [comment]
你好，我也同时在使用Steam和SS，但是没有问题。
若需要解决问题，请提供蓝品代码和拍照（最好有）。

![image](https://user-images.githubusercontent.com/515763/32473972-26423ace-c3a5-11e7-8c91-04d1a7e3bac7.png)

**Comment by verck** [comment]
除此之外，电脑装机到现在9个月没出现过蓝屏。 可能是steam更新有bug 我再看看下次更新后还会不会有这个问题

**Comment by celeron533** [comment]
@chenshaoju 喜+1 剁手

**Comment by verck** [comment]
现在突然就开着都没事了。死机总共发生了3次持续了2天，都是死机两三分钟后才蓝屏。两次是开着steam再开ss死机，一次是开着ss很久没事才开的steam死机。

**Comment by chenshaoju** [comment]
@verck 我猜测是你的硬件可能有问题，也可能是驱动或者什么地方有问题，现象本身和SS无关。

@celeron533 [二哈]

**Comment by yuinma** [comment]
也有同样的问题最近一直困扰我，这情况是从4月4号开始的，之前一直很好。现象是ss开个两三分钟win就卡死黑屏任务管理器都打不开，只能按电源键重启，我以为中毒，重装过两次系统，还检测过硬盘，后来才发现是开ss的原因，换ssr，ssd都有相同的问题，使用clash却一切正常，不知原因。昨天使用新的4.10版本，还是这样。现在不敢开ss了。

**Comment by chanendy** [comment]
同样的问题，打开ss后几分钟就黑屏死机，只能重启。win10，ss版本4.4.1.0，安装在非C盘。
