### ISSUE TITLE
无法访问日志

### ISSUE THREAD

**Issue by PineBillows** [shadowsocks/shadowsocks-windows#1507]
点击Show Logs就会出现如图提示
[图](http://i217.photobucket.com/albums/cc262/Goat-Lee/SS.jpg)

**Comment by chenshaoju** [comment]
请尝试删除 gui-config.json 文件中的：
```
  "logViewer": {
……
  },
```
一节，然后再试一下。

**Comment by PineBillows** [comment]
已经删除，一模一样的报错……

**Comment by chenshaoju** [comment]
如果将 Shadowsocks.exe 单独复制到一个空目录里，是否还有该问题？

如果仍然有，请访问 https://www.microsoft.com/en-us/download/details.aspx?id=30135 下载修复器按照向导修复 .NET 。

如果修复失败，请访问 https://www.microsoft.com/zh-CN/download/details.aspx?id=56115 下载最新版的 .NET 重新安装。

**Comment by PineBillows** [comment]
呃，换别的地方可以运行，在原文件夹就怎么也不行。
我试着删除了图片中最上面的那个文件，好像解决了。

**Comment by celeron533** [comment]
类似 #1396 
修改程序启动位置后，系统会新建一个文件夹保存配置文件 

![image](https://user-images.githubusercontent.com/3608762/32473619-5da8afcc-c3a3-11e7-983f-4c53946104e7.png)
