### ISSUE TITLE
能不能让2个shadowsocks服务端建立联接？

### ISSUE THREAD

**Issue by wzzjhc** [shadowsocks/shadowsocks-windows#1508]
能不能让2个shadowsocks服务端建立联接？
windows客户端 111.111.111.111，联接 A服务,222.222.222.222，A服务器联接B服务器333.333.333.333
然后客户端就从B服务器出来IP变成333.333.333.333
这个可以实现吗？

**Comment by chenshaoju** [comment]
那么你在A服务上做个端口转发转发到B不就完了？

**Comment by wzzjhc** [comment]
A服务端口转发到B，那么密码按A服务的来还是按B服务的来呢？

**Comment by chenshaoju** [comment]
B，A只是充当一个端口转发。
