### ISSUE TITLE
window 7 64bit ss doesn't work

### ISSUE THREAD

**Issue by cinyearchan** [shadowsocks/shadowsocks-windows#1509]
![filehelper_1509960984199_88](https://user-images.githubusercontent.com/15631504/32434577-6fdf3c72-c319-11e7-9472-e5be4e068437.png)

**Comment by chenshaoju** [comment]
请问使用的是什么版本的SS？可以在启动SS后，将鼠标悬停在系统托盘区纸飞机图标上，会显示版本号。

**Comment by wzzjhc** [comment]
它的情况我遇到过，你是不是把SS的文件夹隐藏了？不要隐藏，然后重启，就解决了。如果还不行，建议你重装win7系统。
------------------------
you can rebuild win7 system。
