### ISSUE TITLE
请问，我想设置一个指定的网址，然后可以在线更新GFWlist，官方的内容并不全

### ISSUE THREAD

**Issue by wzzjhc** [shadowsocks/shadowsocks-windows#1511]
请问，我想设置一个指定的网址，然后可以在线更新GFWlist，官方的内容并不全。

谁会吗？

我想跟我的朋友一起分享。

不行的话只能让他们自己下载了。

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/32482934-d03758b4-c3d4-11e7-9870-b97215b31545.png)
