### ISSUE TITLE
Shadowsocks-4.0.6 can not run on windows 7 ultimate version 64 bit

### ISSUE THREAD

**Issue by gameliu007** [shadowsocks/shadowsocks-windows#1513]
![image](https://user-images.githubusercontent.com/29156357/32529513-f50aaade-c473-11e7-835e-c37e9c36614b.png)

**Comment by gameliu007** [comment]
This problem has been solved by myself.

![image](https://user-images.githubusercontent.com/29156357/32529871-e51f1bd0-c475-11e7-89f4-3041e2a2301c.png)

**Comment by chenshaoju** [comment]
Actually,you just need .NET Framework ,You can get up to date version at here:
https://www.microsoft.com/net/download/windows

**Comment by Chinese-Xu** [comment]
今天修改了源码，让程序运行在非4.6.2上。
其实目前整个项目只有3处用到了4.6.2的新函数。改回去貌似也没什么影响。
所以为什么不降低对于framework的版本依赖呢？

**Comment by celeron533** [comment]
>其实目前整个项目只有3处用到了4.6.2的新函数

主要是随机数和加密那一块。你可以fork代码然后改成低版本.net framework
