### ISSUE TITLE
don't work in win10 1703

### ISSUE THREAD

**Issue by magiceye** [shadowsocks/shadowsocks-windows#1515]
can not open google.com by any web browser like chrome or edge, ping google.com has no response
OS win10 1703 15063.674
SS 4.0.6
firewall was disabled, run ss by administrator
SS can run without any error message, the log is:
[2017-11-08 20:58:01] Shadowsocks started
[2017-11-08 20:58:04] connect to api.github.com:443
[2017-11-08 20:58:04] Socket connected to ss server: xxxxxxx

no more message whatever I try include open google.com, launch google earth, ping google.com
No bandwidth also in an out both zero except ss starting has a short period in bandwidth (very tiny, I think it due to access github)

delete all ss releated file and restart it, useless.
try to install .net 4.5, but os tell me it already included in system, no need to install.

**Comment by magiceye** [comment]
No bandwidth also in an out both zero except ss starting has a short period in bandwidth (very tiny, I think it due to access github)

**Comment by magiceye** [comment]
Same server ip addr, same ss, works in win7

**Comment by chenshaoju** [comment]
If copy Shadowsocks folder from Windows 7 computer to Windows 10 computer,It's can work or not?
