### ISSUE TITLE
能把.net framework的那个依赖去掉么？

### ISSUE THREAD

**Issue by gouchaoer** [shadowsocks/shadowsocks-windows#1517]
就一个转发流量的客户端，新机器就要安装那么大一个包

**Comment by gouchaoer** [comment]
安装那个很慢很慢，你的心不会痛么？我们有C/C++实现的win下的客户端么？

**Comment by chenshaoju** [comment]
１. Shadowsocks for Windows 本身基于 .NET C# 开发，这是历史问题，我也想用C++的客户端。
２. .NET Framework 安装速度慢是微软/你机器的问题。
３.仍有第三方的客户端可以替代，比如SSTap，或者基于 .NET framework 2.0 的 SSR 。
４.欢迎提交代码，或创建新的分支。

**Comment by zyf2008Neptune** [comment]
有c++/qt5的版本

**Comment by rebiu** [comment]
win 7 自带 .NET 3.5 ，你可以用QT版本的，或者用旧版本的
win 10 自带 .NET 4.5，不需要要安装
所以你的系统是什么呢

**Comment by pongfcnkl** [comment]
QT比C#难用多了
另外下载地址:
https://github.com/shadowsocks/shadowsocks-qt5/releases

**Comment by gouchaoer** [comment]
我系统win10但是你这话。net framework版本太好了估计，改天我用php写个ss的客户端，0依赖

**Comment by chenshaoju** [comment]
PHP果然是世界上最好的语言 
![default](https://user-images.githubusercontent.com/515763/32609980-5e5f80d0-c59c-11e7-991d-3ba7b6068426.jpg)

**Comment by KuiperSirius** [comment]
摒弃开发开发架构的做法，犹如为了改良战机性能而改变气动布局，充满难度而且风险很大。其实.NET Framework挺稳定的。重中之重应该是流量协议特征的隐藏，切不可舍本逐末哦~

**Comment by tangshiba** [comment]
表示win10从来没有装个.net、、、新系统直接就能用。

**Comment by pongfcnkl** [comment]
最新的win10 1709已经预装.net 4.7了

**Comment by shikkoku** [comment]
我用Windows 10都不用另外装.NET。一直从2.x用上来的。

**Comment by celeron533** [comment]
>安装那个很慢很慢，你的心不会痛么？我们有C/C++实现的win下的客户端么？

你该换电脑了。
大部分的软件都有运行环境、运行库的设定，java，php，python等都是这样的。
如果你要玩最新的3A大作，不但要安装DX，还要安装.Net和各种runtime。
.Net framework 4.6.2可以兼容运行最低至4.0的程序集，即便是你今天不装，明天你使用其他需要4.6.2的程序依旧要安装。

**Comment by Shiratsuyu** [comment]
你改天写个PHP的，然后为了跑你PHP的版本还得去装个Apache？
![23431cbf-b21a-41a1-a879-3918321ee949](https://user-images.githubusercontent.com/17449060/32697502-8dcfc03c-c7cc-11e7-96b9-76b173d6d170.png)

**Comment by violarulan** [comment]
[×] 为了 .net 4.7 的版本去装 .net 4.7
[√] 为了跑你 PHP 的版本去装个 PHP

**Comment by myblur** [comment]
真是看不下去这个issue啊

**Comment by wongsyrone** [comment]
> 改天我用php写个ss的客户端，0依赖

等待不依赖PHP的客户端

**Comment by kmahyyg** [comment]
你需要monoproject

**Comment by celeron533** [comment]
#1452
