### ISSUE TITLE
请问我访问google.hk显示证书失效怎么解决？

### ISSUE THREAD

**Issue by lorcx** [shadowsocks/shadowsocks-windows#1518]
能够访问youtube，但是访问googl主页就会显示 NET::ERR_CERT_AUTHORITY_INVALID，这应该怎么解决？

**Comment by chenshaoju** [comment]
google.com.hk or google.hk ？

**Comment by lorcx** [comment]
google.com.hk

**Comment by lorcx** [comment]
Google Internet Authority G3 
无法将这个证书添加到一个受信任的机构

**Comment by chenshaoju** [comment]
这可能是你的系统证书链有问题。
详情阅读：
https://textslashplain.com/2017/10/23/google-internet-authority-g3/

**Comment by lorcx** [comment]
问题解决了 
下载  https://secure.globalsign.net/cacert/Root-R2.crt    这个证书 安装到 受信任的根证书机构就可以了
