### ISSUE TITLE
奇怪的问题！求助

### ISSUE THREAD

**Issue by newyhj** [shadowsocks/shadowsocks-windows#1521]
ver:4.0.6
PAC最后日期：2017/11/10
将代理模式切换至：全局模式

所有网页均访问正常。唯有一款软件 ：google adwords editor无法验证用户登录 .直接提示：
---------------------------
Google AdWords编辑器
---------------------------
您遇到了暂时性的网络问题。请检查您的网络连接和代理设置，然后重试。如果仍有问题，请与您的系统管理员联系。

**Comment by chenshaoju** [comment]
https://support.google.com/adwords/editor/answer/36582?hl=en

**Comment by celeron533** [comment]
开启全局代理，然后重启你要使用的软件。有些软件只认启动时候的系统代理设置，如果后来系统代理设置变化，该软件不会更新自己的连接方式。
