### ISSUE TITLE
Weeks ago, I saw people talked about the development of UWP version?

### ISSUE THREAD

**Issue by onbigion13** [shadowsocks/shadowsocks-windows#1526]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
2.5.8

### Environment(Operating system, .NET Framework, etc)
Windows10, Net 4.7.1

### Steps you have tried

beg the developers for uwp version of SS.
### What did you expect to see?

the publication of the UWP version of shadowsocks.
### What did you see instead?

none of uwp version is developed.
### Config and error log in detail (with all sensitive info masked)

**Comment by zyf2008Neptune** [comment]
然而win10手机不再会有了。

**Comment by celeron533** [comment]
#1177
