### ISSUE TITLE
windows 10下PAC模式会在闲置时失效，必须切换到全局后才能继续代理

### ISSUE THREAD

**Issue by matho10** [shadowsocks/shadowsocks-windows#1527]
我遇到的这个问题很奇怪。我用的是windows 10，如果不浏览网页，过一会PAC模式就会失效，无法打开网页，只有手动切换到全局模式再切回来才能继续使用。又发现如果改一下快捷键设置，也能重新用PAC。

在MAC、安卓手机上都没有这个问题，排除是服务器问题。

**Comment by chenshaoju** [comment]
很有可能是有某些软件修改了你的浏览器PAC设置。

如果你不确认，请使用 https://docs.microsoft.com/en-us/sysinternals/downloads/procmon 监测注册表变化，通过仅显示 AutoConfigURL 作为关键词。

![image](https://user-images.githubusercontent.com/515763/32719792-7e6eaf06-c89c-11e7-8784-8538f1926b3a.png)

**Comment by Taniffer** [comment]
我也遇到了这个问题。。。。也是切全局再切回来解决的。。。

**Comment by alsorain** [comment]
谢谢 chenshaoju，按你的方法发现问题了，是最新的Avast会和shadowsocks冲突。关了Avast的“行为防护”后一切正常。
具体设置在Avast主界面-设置-元件 中。

**Comment by matho10** [comment]
谢谢 @chenshaoju 按你的方法查到问题了，是最新版的Avast会干扰shadowsocks 工作。关闭 "设置-元件-行为防护" 之后ss可以正常工作。
@Taniffer 可参考。
