### ISSUE TITLE
无法解析二维码

### ISSUE THREAD

**Issue by luckyaffer** [shadowsocks/shadowsocks-windows#1529]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
windows 10 x64, .net 4.7.02046和.net 3.5

### Steps you have tried
服务器中扫描二维码

### What did you expect to see?
成功扫描到服务器配置

### What did you see instead?
无法解析二维码
替换成4.0.5版本正常

**Comment by chenshaoju** [comment]
该问题已知： https://github.com/shadowsocks/shadowsocks-windows/issues/1367
