### ISSUE TITLE
PAC自定义规则更改以后仍用原来设置

### ISSUE THREAD

**Issue by dspjm** [shadowsocks/shadowsocks-windows#1530]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
不知道怎么看，点击about进入网页。但是应该是最新版

### Environment(Operating system, .NET Framework, etc)
Windows

### Steps you have tried
1.更新user-rules.txt
2. 点击secure local pac
3. 点击update pac from gfwlist
4. 刷新网页
5. 关闭浏览器，更换浏览器访问

### What did you expect to see?
1. 访问网页的ip地址改变（如http://showip.net/）

### What did you see instead?
1. 访问网页的IP地址不变，如已使用代理，则仍用代理，未使用代理仍不使用代理
2. pac.txt即时是有更新的
3. 等待很长一段时间后，曾遇到过用新的设置访问网站，但一般仍然无效

### Config and error log in detail (with all sensitive info masked)
user-rules.txt:
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet

||mozilla.org
!@@||www.whatismyip.com
ip.cn
!||whatismyip.network
||showip.net

**Comment by celeron533** [comment]
鼠标悬停系统托盘即可看到软件版本。
有的杀毒软件或者去广告插件会阻止新的PAC生效。

**Comment by dspjm** [comment]
版本号是4.0.6。我又试了一下，已经关闭杀毒软件，仍然不正常。不过我发现切换成global模式以后再切换成pac模式就可以更新，或者退出再打开也可以。

**Comment by celeron533** [comment]
应该是这个已知的bug
#1332

**Comment by celeron533** [comment]
fixed in
46d40fec678c7ab3c1cd6743e675aa13b6d6af77
and #1564
