### ISSUE TITLE
从剪切板导入URL 无效 4.0.6

### ISSUE THREAD

**Issue by Moobusy** [shadowsocks/shadowsocks-windows#1532]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)

win10
### Steps you have tried
复制同事分享的 ss://...... 链接，右键图标-服务器-从剪切板导入URL， 没有反应
换回老版正常

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
该问题已知 #1367
将包含在下个release
