### ISSUE TITLE
SIP003: Port confilct after PC Sleep/Wake

### ISSUE THREAD

**Issue by xlighting2017** [shadowsocks/shadowsocks-windows#1533]
### Version(release version or AppVeyor link)
4.0.6
### Environment(Operating system, .NET Framework, etc)
Win10 Pro x64
### Steps you have tried
Sleep with SS connected,  and wake up in the morning

### What did you expect to see?
Continue to work

### What did you see instead?
when the problem occurs, there are  2  obfs-local   in the task manager, and if you manually kill both of them, and restart SS, it's working again

### Config and error log in detail (with all sensitive info masked)
this is not  100% happening, but I've seen it several times
![image](https://user-images.githubusercontent.com/25970065/33105861-579064a4-cf6a-11e7-853d-aa26d547955c.png)

**Comment by celeron533** [comment]
Link to #1466
