### ISSUE TITLE
UI方面的问题？前几天任务栏图标突然右键没反应了，之后重新打开程序就变成这样不能用了

### ISSUE THREAD

**Issue by Noob-I-Am** [shadowsocks/shadowsocks-windows#1534]
### Version(release version or AppVeyor link)
4.0.5 & 4.0.6

### Environment(Operating system, .NET Framework, etc)
windows 10 x64    .NET Framework v4.0.30319

### Steps you have tried

  前几天正常使用4.0.5版，任务栏图标突然右键没反应了不能弹出交互菜单，然后终止进程重新打开客户端就开始不正常，客户端ui加载不正常，一启动就处于未响应状态，鼠标无法操作 ，重新下载客户端，换4.0.6版，兼容模式运行，管理员运行都试了，还是一样，客户端所在目录下可以生成ss_win_temp文件夹，但是客户端不正常

### What did you see instead?
![image](https://user-images.githubusercontent.com/26078785/33129755-037fae30-cfcc-11e7-8d93-89e490284a5f.png)

**Comment by celeron533** [comment]
可能是log文件过大？

**Comment by chenshaoju** [comment]
请尝试删除 ss_win_temp 目录后重试。

**Comment by Noob-I-Am** [comment]
删除ss_win_temp目录并不能解决，尝试过在其他目录下解压新的客户端，还是一样。可能除了重装系统应该没有其他解决办法了

**Comment by viterman** [comment]
我也遇到了，右键无法使用，点击无效，4.0.6  win10  删除所有文件，重新下载设置后也是还是一样，不知道怎么了。

**Comment by chenshaoju** [comment]
请尝试删除 Shadowsocks.exe 所在的 ss_win_temp 目录，如果仍然不行，可能是 .NET Framework 损坏，请尝试使用： https://www.microsoft.com/en-us/download/details.aspx?id=30135 进行修复，如果修复失败，请安装最新的 .NET Framework 试试看： https://www.microsoft.com/net/download/thank-you/net471 。

**Comment by celeron533** [comment]
或者金庸反病毒软件，有时候各种安全卫士会制止某些ss相关进程启动

**Comment by celeron533** [comment]
#1929 #1755
