### ISSUE TITLE
最近一个月突然变得极慢

### ISSUE THREAD

**Issue by zianfu** [shadowsocks/shadowsocks-windows#1535]
大概从十月底的时候变得很慢，mac和windows都是，手机用的少没感觉。但前两个感觉很明显，之前youtube用学校的网1080P无压力，现在有时144都卡的飞起。所有服务器和端口的设置都没有变过，想知道怎么回事？

**Comment by chenshaoju** [comment]
可能是你到你的服务器丢包严重，也可能你的网络存在QoS，降低了不明流量的优先级。

我在U2B的测试结果：
![1](https://user-images.githubusercontent.com/515763/33194765-42f1f28e-d10d-11e7-8e52-3c488e71e2d5.png)

**Comment by WillyTuring** [comment]
我最近也频频出现此问题，请问该如何解决呢？

**Comment by chenshaoju** [comment]
如果你是自己买的VPS搭的，请检查到你的服务器的Ping的延迟是否过高，是否存在丢包。

如果你是购买的SS服务，请与你的SS服务商联系。

**Comment by networkthroughput** [comment]
这个问题和shadowsocks无关,你自己或者你的服务的网络问题.
