### ISSUE TITLE
Hello, can you publish the server configuration of shadowsocks? Thank you!

### ISSUE THREAD

**Issue by whatsSumer** [shadowsocks/shadowsocks-windows#1536]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by networkthroughput** [comment]
No,Build a server or buy a services form somewhere and own your risk.
