### ISSUE TITLE
安装4.0.6版本不能翻墙

### ISSUE THREAD

**Issue by luolinyuan** [shadowsocks/shadowsocks-windows#1537]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!
下载了4.0.6的版本无法翻墙，使用4.0.5的依然可以翻墙，这是什么原因引起的
### Version(release version or AppVeyor link)
4.0.6

### Config and error log in detail (with all sensitive info masked)

**Comment by networkthroughput** [comment]
开了OTA对吧,OTA不支持了.
