### ISSUE TITLE
我购买了阿里云的ecs，用来做udp转发，目的是支持pubg游戏

### ISSUE THREAD

**Issue by wangluyichen** [shadowsocks/shadowsocks-windows#1538]
但是不知道用这个代理软件能实现不，很多教程是针对sstap的，还有 super socks5cap,我想在局域网内实现二级代理，在转发到 阿里云，不知道这个应该怎么做，需要什么软件

**Comment by networkthroughput** [comment]
你需要搭配sockscap来用,比较麻烦,不如直接用sstap
