### ISSUE TITLE
字体报错

### ISSUE THREAD

**Issue by qianzyGit** [shadowsocks/shadowsocks-windows#1542]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
win7 sp1
.net 4.6.2
### Steps you have tried
安装Consolas字体
双击程序
### What did you expect to see?
正常运行

### What did you see instead?
报错

### Config and error log in detail (with all sensitive info masked)
[2017-11-30 00:54:44] [E] System.ArgumentException: 字体“Consolas”不支持样式“Regular”。
   在 System.Drawing.Font.CreateNativeFont()
   在 System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font..ctor(String familyName, Single emSize)
   在 Shadowsocks.Model.LogViewerConfig..ctor()
   在 Shadowsocks.Model.Configuration.Load()
   在 Shadowsocks.Controller.ShadowsocksController..ctor()
   在 Shadowsocks.Program.Main()

**Comment by celeron533** [comment]
接到过多起字体问题的报告，都是同一字体同一问题，是不是你下载的第三方版本中自带了配置文件，然后里面使用了当前不支持的字体样式（regular）
删掉配置文件后重试还是这样的吗？

**Comment by qianzyGit** [comment]
我查了下font文件中，consolas没有regular样式，只有3个其他的，应该是这个原因。有删除过配置文件

**Comment by celeron533** [comment]
音却斯廷

![image](https://user-images.githubusercontent.com/3608762/33409164-e1b8c2c0-d5b4-11e7-9bd2-f1d8d12ae316.png)

**Comment by qianzyGit** [comment]
能麻烦把consolas这个字体包给我发一份么，我覆盖一下试试，邮箱1172621132@qq.com，十分感谢

**Comment by celeron533** [comment]
@qianzyGit  https://cn.bing.com/search?q=consolas+regular&ensearch=1
