### ISSUE TITLE
I need to use a plugin and a forward proxy at the same time

### ISSUE THREAD

**Issue by ImPat** [shadowsocks/shadowsocks-windows#1543]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### What did you expect to see?
Being able to use a forward proxy to access the internet and use simple-obfs to bypass the firewall. (Simple Authentication Proxy)

### What did you see instead?
Shadowsocks-win ignores the proxy(as expected)

I'm behind a very restrictive firewall that is forcing me to use simple-obfs. But that same network is forcing me to use an HTTP proxy server with user:password authentication.  Any way I can get around that? (Other software recommendations welcome as well)

**Comment by celeron533** [comment]
You need a plugin which has the ability to forward via a proxy.

Web browser --> provixy --> shadowsocks --> plugin --> forward --> proxy server --> Internet

**Comment by wx00** [comment]
My solution is to run them seperately.
in --> shdowsocks --(plugin ip/port)--> plugin --(w/ settings for proxy)-->  proxy --> out

**Comment by ImPat** [comment]
I've decided to use an alternative solution instead.
