### ISSUE TITLE
Unexpected error 

### ISSUE THREAD

**Issue by CharlieHunnam** [shadowsocks/shadowsocks-windows#1547]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Environment(Operating system, .NET Framework, etc)
Windows 10

### Steps you have tried
Restart the program, and run normally.
![snipaste_2017-12-01_09-24-26](https://user-images.githubusercontent.com/34146898/33463875-dd25cba6-d67a-11e7-8b49-b5a794e5b525.png)

### What did you expect to see?
How can I overcome this issue.

### Config and error log in detail (with all sensitive info masked)
![image](https://user-images.githubusercontent.com/34146898/33463893-e9bd5b5e-d67a-11e7-80f6-1281098b88c3.png)

**Comment by networkthroughput** [comment]
c:\program files\ 文件夹默认没有写入权限
不要将ss放到这个目录下
你可以新建一个目录，比如 d:\ss\ 然后放进去

**Comment by CharlieHunnam** [comment]
好的，明白了，非常的感谢！
