### ISSUE TITLE
服务器端口同时开启shadowsocks-python与shadowsocks-libev 服务，出现500 Internal Privoxy Error，本地日志显示远程服务器timeout

### ISSUE THREAD

**Issue by leitaoxman** [shadowsocks/shadowsocks-windows#1548]
服务器端口同时开启shadowsocks-python与shadowsocks-libev 服务，用了大概半月，突然出现500 Internal Privoxy Error

#Version(release version or AppVeyor link)

Shadowsocks-python与Shadowsocks-libev都为最新版，加密方式为最新的aes-256-gcm，没有用obfs
设置监听端口都为1080（没有设置不同监听端口），本地同时使用libev 和python上网
Environment(Operating system, .NET Framework, etc)

#出现的问题
尝试更改所有端口都用不了，服务器可以正常ping通，远程登录服务器都无法登陆

#尝试的方法
1.运行以下命令无效
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
2.重启VPS，卸载python，shadowsocks-libev，只装一种也无效。
3.装了ssr，试了各种混淆，协议，也无效

#讨论
是没设置VPS不同的监听端口，本地同时使用libev 和python上网的话会导致服务器的服务器bug 还是GWF封了端口

**Comment by chenshaoju** [comment]
服务端换个端口看看？

**Comment by celeron533** [comment]
If there is no problem in iptables but SSH still does not work, it means your server has been "listed"

**Comment by leitaoxman** [comment]
@celeron533 ,iptables is no problem, and I add the ports in /etc/firewalld/zones/public.xml , and systemctl restart firewalld. However, it does not have an effect.  Finally, I deployed a new vps.

**Comment by leitaoxman** [comment]
补充一下，当初装的时候没有考虑很多，同时装了ss-python和ss-libev，服务器的监听端口都设置为了1080。客户端Linux，android，windows，同时都在用，用了半月出现上述问题。ps：想同时装的，要将监听端口设置不一样。现在重新配了vps，ss-python：local port-1080, ss-libev: local port-1081，用一段时间看看到底是不是GFW封了端口
