### ISSUE TITLE
SocksCap64及SSTap作者停止维护了！

### ISSUE THREAD

**Issue by jiawei-zheng** [shadowsocks/shadowsocks-windows#1554]
希望windows版能增加udp转发的功能而不需要另外使用其他软件

**Comment by chenshaoju** [comment]
请阅读：
https://github.com/shadowsocks/shadowsocks-windows/wiki/Shadowsocks-Windows-使用说明#udp

另外，停止维护不意味着不能用了，只是不更新了，还是能用。
