### ISSUE TITLE
Unable to load DLL 'libsscrypto.dll'

### ISSUE THREAD

**Issue by Hopecrisy** [shadowsocks/shadowsocks-windows#1555]
### Version(release version or AppVeyor link)

Shadowsocks 4.0.6 with KCPTUN 20170718

### Environment(Operating system, .NET Framework, etc)

Windows 10 x64, with .NET Framework 4.7.1

### Steps you have tried

1. close Shadowsocks-windows
2. delete ss_win_temp
3. reboot Shadowsocks-windows

### What did you expect to see?

Works.

### What did you see instead?

Error 500 in Chrome, and "Unable to load DLL 'libsscrypto.dll'" in Log.

### Config and error log in detail (with all sensitive info masked)
[log.txt](https://github.com/shadowsocks/shadowsocks-windows/files/1527814/log.txt)

**Comment by chenshaoju** [comment]
Please try put shadowsocks.exe to other directory like "D:\SS\" ?

**Comment by celeron533** [comment]
Try this:
![image](https://user-images.githubusercontent.com/3608762/33652299-d3f6498e-daa3-11e7-9140-b84b29e99fa6.png)
