### ISSUE TITLE
[Feature Request] 左键单击托盘图标切换“PAC模式”、“全局模式”与“禁用系统代理” 

### ISSUE THREAD

**Issue by fatjing** [shadowsocks/shadowsocks-windows#1556]
升级到最新版火狐后找不到好用的代理扩展，干脆不装了。但是平时浏览过程中切换代理模式还是挺频繁的，现在每次都要右键托盘图标之后再选（用鼠标浏览不用键盘快捷键），非常不方便。
还有一个想要的功能就是定期自动从GFWList更新本地PAC。
如果这两个功能加上了就彻底不需要浏览器代理扩展了。

**Comment by chenshaoju** [comment]
https://addons.mozilla.org/en-US/firefox/addon/switchyomega/

**Comment by celeron533** [comment]
注意SwitchyOmega for Firefox目前仍在开发阶段，会有各种bug
