### ISSUE TITLE
Firefox 57每次重启电脑后都需要更新PAC URL才能使用

### ISSUE THREAD

**Issue by mmqmzk** [shadowsocks/shadowsocks-windows#1557]
Firefox更新57以后原来的Foxproxy不能用了, 用的是选项里的pac URL配置. 请问是否Firefox的问题?
version 4.0.6

**Comment by chenshaoju** [comment]
https://addons.mozilla.org/en-US/firefox/addon/switchyomega/

**Comment by mmqmzk** [comment]
了解了, 谢谢
