### ISSUE TITLE
请问怎么用SSR地址在SS软件里面使用，大神教程一下 ，OK

### ISSUE THREAD

**Issue by weihua168** [shadowsocks/shadowsocks-windows#1558]
我在别的地方获取了一个可以用的高速SSR但是不知道导入到SS软件里面使用！望大神解救一下！

SSR地址：怎么在SS软件里面使用

**Comment by chenshaoju** [comment]
如果你的SSR使用了特定协议（origin以外的），将不能兼容SS。
