### ISSUE TITLE
4.0.6 在win10下睡眠重新唤醒后没反应

### ISSUE THREAD

**Issue by qwemicheal** [shadowsocks/shadowsocks-windows#1559]
win10睡眠，再唤醒，小飞机界面什么的操作正常，但是不起作用，小飞机上的上行下行两个箭头也不出现，退出再次打开有也不起作用，只能重启电脑解决。

**Comment by chenshaoju** [comment]
请尝试以管理员身份启动命令提示符或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，如果遇到有几个失败的，不用管，然后重启计算机再试试。

**Comment by qwemicheal** [comment]
在cmd下试了下，问题没哟再出现。
