### ISSUE TITLE
当打开正向代理设置后 填入127.0.0.1：1080后 ss就没有连接了 

### ISSUE THREAD

**Issue by imzhenji** [shadowsocks/shadowsocks-windows#1561]
我想使用proxifier为steam游戏加速，根据教程是先在ss客户端中的正向代理设置里选择socks5代理 然后填入127.0.0.1 端口写1080 但是我写完确定后 ss就使用不了了， 接收不到数据了。 我试着将端口设置为我服务器的端口也没有用。
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
这个功能的目的是当你访问互联网过程中需要通过代理服务器（比如某些企业网络需要设置代理才能上网）时使用的。
如果你可以直接访问互联网，则不需要设置该功能，错误的设置会导致无法使用。
如果教程确实如此编写，你看得教程可能是错的，请与你的教程编写者联系（留言、邮件等方式）。
