### ISSUE TITLE
win10出现500 Internal Privoxy Error

### ISSUE THREAD

**Issue by xiebruce** [shadowsocks/shadowsocks-windows#1562]
win10 客户端，新安装的系统，服务器端自己配置，mac可以连接，iphone可以连接，说明不是服务器端问题，但在win10，不管用最新版的4.0.6，还是用2.5.6都显示以下错误，另外，我之前在另一个电脑（小米笔记本，家庭版正版win10，刚开始也不行，后来谷歌下载了SwitchyOmegara插件啥也没设置，竟然又行了，而且奇怪的是我删除了SwitchyOmega也可以，但IE本来死活不行，后来换了管理员账号之后又不行，而且错误我已经不记得是不是下边这个错误了），求教怎么解决这问题

500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by chenshaoju** [comment]
SS日志里有什么显示吗？

这个现象高度的可能性是服务器IP不对、端口不对、加密方式不对或者密码不对。

**Comment by luminouser** [comment]
以前我也遇到了这个问题，换了个服务器端口号，就没有遇到这个问题了，仅供参考。

**Comment by xiebruce** [comment]
@chenshaoju 你说的这些都不太可能吧，我mac是没问题的，windows的所有配置，都是直接扫描mac版生成的二维码的

**Comment by xiebruce** [comment]
@luminouser 没用，我有两个服务器端口号，都不行

**Comment by chenshaoju** [comment]
如果可能，请将 Shadowsocks.exe 复制到一个新的空目录中，手动重新设置看看？不要用二维码。

**Comment by xiebruce** [comment]
@chenshaoju 可能是我直接放在D盘的原因(虚拟机新装的D盘没任何东西就直接丢进去了)，我没有建目录，现在我在D盘建了个目录，把它放进去，还是扫描二维码，可以访问了，没问题了，Thanks you.

**Comment by zhuweijia** [comment]
各位大佬，问下现在哪里有免费的账号分享啊，之前这个“http://www.ishadowsocks.org/”现在好像没有了啊？？

**Comment by networkthroughput** [comment]
你可以自己搭一个
