### ISSUE TITLE
求助，非预期错误。4.0.7

### ISSUE THREAD

**Issue by MoNianls** [shadowsocks/shadowsocks-windows#1563]
![image](https://user-images.githubusercontent.com/24475225/33794126-661c8f90-dd00-11e7-9569-36dae77870e3.png)

**Comment by chenshaoju** [comment]
请尝试删除SS所在的 ss_win_temp 文件夹然后重试。

**Comment by MoNianls** [comment]
谢谢，虽然它又自动好了
