### ISSUE TITLE
How to stop this message 'shadowsocks service is preventing shutdown'

### ISSUE THREAD

**Issue by cinebam** [shadowsocks/shadowsocks-windows#1565]
### Version(release version or AppVeyor link)
I'm not using it.

### Environment(Operating system, .NET Framework, etc)
Windows10

### Config and error log in detail (with all sensitive info masked)
When I tried to shutdown my PC then the message appeared that 'shadowsocks service is preventing shutdown'
I couldn't found that service so cannot remove that. Maybe, that service is handled by github.com.
Thank you for your attention in this problem.

**Comment by chenshaoju** [comment]
For all I know,Shadowsocks for Windows is NOT running as a service all the time.

Please download Autoruns from https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns
,After start autoruns.exe as Administrator, go to services tab,check all entry, Is any service name or image path with/include "shadowsocks" ? if yes,then right click this entry,and click Delete.

If you are not using shadowsocks ,For security consideration,Please use Norton Power Eraser scan your computer: https://us.norton.com/support/tools/npe.html

**Comment by celeron533** [comment]
Perhaps your Shadowsocks is a modified version. Please ask your provider for help.
