### ISSUE TITLE
Only allow DNS traffic

### ISSUE THREAD

**Issue by hdavy2002** [shadowsocks/shadowsocks-windows#1569]
Aplogies, if this is wrong place to ask a geenral question. I was looking for a forum on main site.

My question is: Instead of piping entire user's traffic via shadow socks. Is it possible to pipe dns traffic only. I have a hosted pihole dns server and want to protect in from public abuse. Many thanks folks.

Cheers

**Comment by chenshaoju** [comment]
Maybe you can use iptables on servers site to filter other protocol,Allow shadowsocks port and dns protocol only?

**Comment by cn4** [comment]
Maybe this will help: https://github.com/nadoo/glider
