### ISSUE TITLE
帐号被删号 My acc had been deleted without notice

### ISSUE THREAD

**Issue by kaopl91** [shadowsocks/shadowsocks-windows#1570]
我是在11月30号在www.gfwsi.com购买了一个月的产品。自我购买到今日，该产品都无法使用。我曾经提交过无数个服务单希望客服反馈，但并没有结果，后来我只能要求退款。但gfwsi在未通知我的情况下，删除了我的帐号，还屏蔽了我的IP，使我无法注册新帐号。
以下是我的帐号：kaopl_91@hotmail.com
产品编号：1080
端口编号：50072
目前我希望你们能及早给我一个合理解释，并提供有效的解决方案。

**Comment by chenshaoju** [comment]
你好，Shadowsocks for Windows 项目和你所购买的SS服务（ www.gfwsi.com ）没有关系。
该服务商使用了Shadowsocks的客户端，但是该服务商和Shadowsocks客户端没有直接关系，任何人都可以使用Shadowsocks的客户端。
