### ISSUE TITLE
new 4.0.7 sucks

### ISSUE THREAD

**Issue by shm007g** [shadowsocks/shadowsocks-windows#1571]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.7

### Environment(Operating system, .NET Framework, etc)
windows

### Steps you have tried
connect as usual

### What did you expect to see?
quick connect to google

### What did you see instead?
slow or can't connect

### Config and error log in detail (with all sensitive info masked)
replace 4.0.6 with 4.0.7, it really sucks. slow and web page can't be open. get 4.0.6 back, and it works fine.
4.0.7 really sucks.

**Comment by chenshaoju** [comment]
Here is my test result:
4.0.7(aes-256-gcm+simple-obfs_http): http://www.speedtest.net/result/6878088885.png
4.0.6(aes-256-gcm+simple-obfs_http): http://www.speedtest.net/result/6878096356.png

What is your method (encryption) in use?
If you ping your server,Is stable (packet loss) ?
