### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wyatton** [shadowsocks/shadowsocks-windows#1573]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.7

### Environment(Operating system, .NET Framework, etc)
Win7 .net framework 4.6

### Steps you have tried
start application

### What did you expect to see?
show me the main UI

### What did you see instead?
crash

### Config and error log in detail (with all sensitive info masked)
[2017-12-15 13:49:20] [E] System.ArgumentException: 字体“Consolas”不支持样式“Regular”。
   在 System.Drawing.Font.CreateNativeFont()
   在 System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font..ctor(String familyName, Single emSize)
   在 Shadowsocks.Model.LogViewerConfig..ctor()
   在 Shadowsocks.Model.Configuration.Load()
   在 Shadowsocks.Controller.ShadowsocksController..ctor()
   在 Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
Please open control panel,Appearance and Personalization,Fonts,And find a font name "Consolas",double-click to open it.
![image](https://user-images.githubusercontent.com/515763/34032289-5697d084-e1b0-11e7-9ebf-03e26bec916a.png)

Can you see a there is a font name "Consolas 常规" or "Consolas Regular" ?
![image](https://user-images.githubusercontent.com/515763/34032374-beb0d4ea-e1b0-11e7-9d7e-a7242849e3b5.png)

**Comment by celeron533** [comment]
#1376

**Comment by wyatton** [comment]
resoloved, thanks
