### ISSUE TITLE
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 

### ISSUE THREAD

**Issue by IanWu98** [shadowsocks/shadowsocks-windows#1574]
Shadowsocks电脑端无法正常使用，以下是日志显示的内容：
[2017-12-16 00:23:34] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 127.0.0.1:1080
在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
--- 内部异常堆栈跟踪的结尾 ---
在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- 内部异常堆栈跟踪的结尾 ---
在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请尝试启动命令提示符（ｃｍｄ）或者PowerShell，执行：
```
ping 127.0.0.1
```
能Ping通吗？

**Comment by YangLiG** [comment]
可以

**Comment by IanWu98** [comment]
好像不能 @chenshaoju 
![default](https://user-images.githubusercontent.com/34579796/34069254-d1c23fb0-e287-11e7-88e8-cf83a00382dd.JPG)

**Comment by chenshaoju** [comment]
这个问题似乎无解，请尝试以管理员身份启动命令提示符（ｃｍｄ）或者PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，三行执行完毕后重新启动看看。

我已经Google过了，但是没有确切结果：
https://www.google.com/#newwindow=1&safe=off&q=ping%20127.0.0.1%20general%20failure

如果仍然不行，请在备份数据后尝试重新安装／重置操作系统。

**Comment by IanWu98** [comment]
已经试过了，还是不行。只能重装系统了 @chenshaoju

**Comment by celeron533** [comment]
本地`127.0.0.1`都无法ping通，说明你这边IP协议栈出了问题
