### ISSUE TITLE
每次运行shadowsocks后，本地PAC网址都是不一样的，导致局域网内其它终端需重新设置的问题

### ISSUE THREAD

**Issue by yelosheng** [shadowsocks/shadowsocks-windows#1575]
一般PAC网址都是如下格式：

> http://192.168.XX.XX:1080/pac?t=20171216154526289&secret=3IKIOorEOdKgvEXMnxncMe20JQVBxKNSTJJRDJLrFLk=

其中pac?后面的内容每次运行都会不一样，导致局域网内原来利用这个PAC翻墙的终端需要重新设置新的PAC网址，实在是很麻烦的一件事情。
不知道有没有什么好的办法。

**Comment by chenshaoju** [comment]
问号后面的可以忽略的。
你可以直接设置为 http://192.168.xx.xx:1080/pac 。

**Comment by yelosheng** [comment]
我原来尝试过，好像不行。刚刚又试了一下，pac网址不带后面的一长串字符串的话的确是不行。

**Comment by chenshaoju** [comment]
你在客户端电脑上直接用浏览器访问 http://192.168.xx.xx:1080/pac ，会下载回来一个PAC文件吗？

如果不会，请尝试取消位于PAC菜单（右击托盘区纸飞机）下的“保护本地PAC”选项。

**Comment by yelosheng** [comment]
按照您的建议，取消了“保护本地PAC”，pac网址变成了http://192.168.xx.xx/pac?t=20171216231037105，直接通过http://192.168.xx.xx/pac的话，还是不行，而通过上面的带？t=20171216231037105的网址就可以下载pac文件。

**Comment by chenshaoju** [comment]
真是奇怪，我的测试结果是取消后就行了：
![image](https://user-images.githubusercontent.com/515763/34071795-3ef22710-e2b7-11e7-8fa0-ec7d2015d9da.png)

PS：请确保选中了“允许来自局域网的连接”。

**Comment by yelosheng** [comment]
啊，不好意思，按照您的建议可以了。是我自己忘记吧1080的端口号写上了。
太感谢您了，陈少举先生！！
