### ISSUE TITLE
Add new function to listen outer port | 能否加入监听外部端口的特性

### ISSUE THREAD

**Issue by Clyde-Li** [shadowsocks/shadowsocks-windows#1576]
监听外部端口，在局域网内非常实用，可以避免各端单独建立SS链接的开销。
也能解决安卓模拟器难以使用本机代理的问题。
(虽然netsh interface portproxy add v4tov4 可以手动转发)
希望能考虑, Thanks!

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/34071423-24997cf2-e2b1-11e7-814b-d25ed7760d23.png)

**Comment by Clyde-Li** [comment]
抱歉没说清楚，我的意思是想在外部使用不同的端口

**Comment by XiLingHost** [comment]
你可以尝试用nginx之类的工具进行端口转发
