### ISSUE TITLE
ss_privoxy.exe 这个为什么无法结束掉，最近因为这个东西老是占CPU

### ISSUE THREAD

**Issue by cgpeter96** [shadowsocks/shadowsocks-windows#1577]
搞的电脑卡的飞起，= =头大 询问怎么结束掉这个东西

**Comment by chenshaoju** [comment]
ss_proxy.ext 不是 Shadowsocks for Windows 的一部分，请检查是否中毒了或者使用的是某种修改版的SS。

Shadowsocks for Windows 自带的是 ss_privoxy.exe 。

**Comment by cgpeter96** [comment]
@chenshaoju   是我打错了 ss_privoxy.exe  ，但是这个进程总是占了30%的cpu = =和我的ss服务器挂了有关系？

**Comment by chenshaoju** [comment]
你用的什么版本的SS？如果你机器有大量的HTTP请求经过SS的话，有可能会有这个现象。

请尝试在Releases区块里对比你所使用的SS的MD5/SHA1是否匹配。

如果一致，请尝试退出SS，然后删除 ss_win_temp 目录后重启SS试试。

**Comment by cgpeter96** [comment]
@chenshaoju  版本我也不太确定 最近ss就是各种卡 点开就卡，右键菜单一闪而过= =

**Comment by chenshaoju** [comment]
不确定发生了什么。

**Comment by cgpeter96** [comment]
@chenshaoju   给了点新思路 谢谢

**Comment by cgpeter96** [comment]
@chenshaoju   对了  这个ss_privoxy进程无法直接结束？

**Comment by chenshaoju** [comment]
我试了一下，可以结束。

所以我很怀疑是不是你用的版本是某个修改版或者植入了某些东西的版本。

![test2](https://user-images.githubusercontent.com/515763/34078732-0a8e9658-e35b-11e7-8796-8948428a5d76.gif)

**Comment by celeron533** [comment]
可能和 #1429 类似？

**Comment by Jingyu-Yan** [comment]
@celeron533 
@chenshaoju 
最近启动软件之后，经常出现软件卡死的情况，任务管理器中显示如下
![qq 20171220002353](https://user-images.githubusercontent.com/20572290/34167941-2a49d1c8-e51e-11e7-8301-66c91d116053.png)
然后我只能在管理器中“结束任务”，但是依然会遗留下privoxy.exe的任务无法结束，如下图中
![qq 20171220002502](https://user-images.githubusercontent.com/20572290/34167957-32c45eae-e51e-11e7-9d83-7a9e1f995548.png)
并且使用taskkill命令结束时会提示“没有此任务的实例在运行”（第一次忘了截图所以pid不同）
![qq 20171220005435](https://user-images.githubusercontent.com/20572290/34168897-ada01224-e520-11e7-9101-882e00f24777.png)
然后我只有关机才有可能正常使用

**Comment by chenshaoju** [comment]
你的截图中的确没有一个PID是 9712 的进程。
我也反复测试了多次，没有这个问题。
能告诉我你从什么地方下载的SS吗？

![test](https://user-images.githubusercontent.com/515763/34191578-0e915d88-e583-11e7-8ac1-ff2e64dccae8.gif)

**Comment by Dololo87** [comment]
我也是这种情况，很卡并且无法退出，需要强行关机才行，楼主解决了没有

**Comment by Dololo87** [comment]
在任务管理器强行退出会留下一个“Privoxy的”的进程，占用CPU很高，并且无法左下角关机和重启（会卡死），需要强行关机或重启

我怀疑是Privoxy这个进程的问题，无法在任务管理器强行关闭，关机和重启导致卡死估计也是由于无法关闭这个进程

**Comment by Jingyu-Yan** [comment]
@chenshaoju 
我说明了啊，命令中的截图是后来又出现时补充截图的，当然和之前截图中的pid是不同的
我使用的就是这个项目中的下载的4.0.7
卡死情况具体是：
- 任务栏图标右键菜单每次点击都是出现不到一秒自动消失；
- 左键双击时可以打开主界面，但是也是卡住的，没办法操作；
- 代理也没有正常工作

我并没有在正常使用的情况下去直接结束任务，我是由于程序卡死了，我才会尝试结束任务来重启代理，但是并结束不掉

**Comment by Dololo87** [comment]
@Jingyu-Yan 

我跟你的情况一样，怀疑是win10升级导致兼容问题，你是什么系统

**Comment by chenshaoju** [comment]
不确定具体是什么问题，请尝试下载 https://www.microsoft.com/en-us/download/details.aspx?id=30135 ，按照向导修复 .NET 。如果仍然不行，请从 https://www.microsoft.com/net/download/thank-you/net471 并修复安装 .NET 看看。

**Comment by Jingyu-Yan** [comment]
@Dololo87 
我也怀疑最近一两个月，或者前一次大版本更新导致的，之前从来没有遇见过，但是我并没有频繁的使用，所以不太确定
我本来是使用ssr的，然后出现了这个问题，就换了ss，但是也这样就只能在这提问题了，毕竟ssr停止更新了

**Comment by Dololo87** [comment]
@Jingyu-Yan 
我是最近几天才出现的问题，每天都用，之前没这问题

**Comment by chenshaoju** [comment]
另外，能贴出你们的Windows版本吗？
开始菜单->设置(齿轮)->系统->关于->Windows 规格->OS 内部版本

我的是16299.125，没问题。

**Comment by Jingyu-Yan** [comment]
我和你是一样的版本，那可能是更新补丁导致的？

**Comment by Dololo87** [comment]
@chenshaoju 

同样版本

会不会是360之类的导致的？我安了360安全卫士

**Comment by chenshaoju** [comment]
我没有使用３６０的产品。

**Comment by chenshaoju** [comment]
这是我的补丁列表：

![2017-12-25 5](https://user-images.githubusercontent.com/515763/34340669-6bfea194-e9c3-11e7-800e-25740ce0c912.png)

**Comment by Jingyu-Yan** [comment]
那基本是一样的
![image](https://user-images.githubusercontent.com/20572290/34340701-f193b326-e9c3-11e7-8a5d-2f1125b6ee63.png)
![image](https://user-images.githubusercontent.com/20572290/34340710-083188b0-e9c4-11e7-9eb5-f64b3a2f2578.png)

**Comment by chenshaoju** [comment]
请尝试上面的 .NET 修复步骤，看看是否能解决。

**Comment by Dololo87** [comment]
我刚把360删了，试了下可以正常退出，难道真是360的问题？！

**Comment by Jingyu-Yan** [comment]
.net的安装，没有修复的选项，提示已安装或者更高版本，我现在正在尝试先在win功能中卸载.net，但是卡住了
![image](https://user-images.githubusercontent.com/20572290/34340762-0fd2b02a-e9c5-11e7-840e-07786dd23d3e.png)

**Comment by chenshaoju** [comment]
那个修复工具呢？

**Comment by Jingyu-Yan** [comment]
我运行过修复工具了，但还是一样，没有变化

**Comment by Jingyu-Yan** [comment]
打开软件后，日志中一直显示这个
![image](https://user-images.githubusercontent.com/20572290/34353833-79fddbbe-ea65-11e7-9ad0-1c85b2a7da63.png)
然后尝试切换服务器后就卡死了
使用的服务器在手机上都是正常使用的

**Comment by chenshaoju** [comment]
这意味着你的服务器配置有问题，或者服务器挂了。

如果可能，请尝试将 Shadowsocks.exe 单独放到一个新的目录中，比如 D:\SS\ 然后手动重新配置一下看看。

**Comment by WcLyic** [comment]
我这边也遇到这个问题 硬关机几次才找到临时处理方法:SS不能放快捷方式到桌面,一旦创建了快捷方式,无论是通过快捷方式打开还是直接手动在资源管理器打开都是会死锁. 只要桌面没快捷方式,或者打开的不是桌面快捷方式路径所指向的就完全没问题 今天手贱尝试创建个快捷方式看看还有没有问题, (或许只是我这边的个人问题)
另外上面图里的日志没截完整,目标计算机拒绝连接并不是指向SS服务器而是privoxy所监听的端口,上面的可以对照下日志里面的ip和privoxy.conf所定义的监听地址.

**Comment by chenshaoju** [comment]
@Jingyu-Yan 做一个测试，Ping 127.0.0.1 ，能通吗？

**Comment by ZhongdaZeng** [comment]
同样这个问题。。用ipad或者手机都没有问题，电脑练就orz了

**Comment by chenshaoju** [comment]
@ZhongdaZeng 请将SS的日志发上来。

**Comment by chenshaoju** [comment]
@WcLyic 请尝试Ping 127.0.0.1，能通吗？

**Comment by ZhongdaZeng** [comment]
@chenshaoju 
偶尔会没有事。。(今天早上跪了，现在又可以了

[2017-12-29 09:31:08] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2017-12-29 09:31:23] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2017-12-29 09:31:39] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2017-12-29 09:39:01] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-12-29 16:10:11] Shadowsocks started

**Comment by chenshaoju** [comment]
```
[2017-12-29 09:39:01] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
```

结尾有个 127.0.0.1:1080 ，可能和系统有关。

当SS使用正常，和出现该现象的时候，请 Ping 127.0.0.1 ，看看在这两种情况下能否Ping通。

该问题有一个类似现象，似乎无解： https://github.com/shadowsocks/shadowsocks-windows/issues/1574

**Comment by chenshaoju** [comment]
你的SS是不是监听在本机的1080端口？

如果是，换一个端口看看，比如 10800 ？

**Comment by Jingyu-Yan** [comment]
嗯，我现在换成10800了，但是是否还有问题就不知道了

**Comment by lovingfrank** [comment]
用ShadowsocksR-dotnet2.0.exe正常，ShadowsocksR-dotnet4.0.exe那个privoxy会卡死

**Comment by WcLyic** [comment]
写个批处理自动改文件夹名并运行 一周下来体验良好 感觉我会慢慢习惯了

**Comment by ZhongdaZeng** [comment]
试了一下改用shadowsocksR 2.0的也会卡死。。

**Comment by ZhongdaZeng** [comment]
@WcLyic 请问改文件夹名是什么意思？

**Comment by Justsoos** [comment]
ss_privoxy.exe 本来就是 著名的 [privoxy](https://www.privoxy.org/)，基本无修改内置到 ss 和 ssr 里，用来提供 http 代理转换 socks5 代理用的一个类似管道的软件。

如果出问题了，应该从下面两个方面入手：
1，是否多开了几个 privoxy，互相之间冲突。之前ssr和ss版本，都有多开privoxy问题
2，是否和其他软件，比如著名的恶心软件迅雷会抢1080等端口，造成系统错乱
最后，是否被篡改，验证一下 md5/sha1，一般来说，不应该出这个问题。

**Comment by Justsoos** [comment]
我去测了一下，ssr  ShadowsocksR-win-4.9.0\temp\ShadowsocksR-dotnet4.0.exe
和ss  Shadowsocks-4.0.7\ss_win_temp\ss_privoxy.exe
两个文件完全相同，都是 privoxy 3.0.26.0

sha1：08bbd134b075c7f10397e84444acbcc33beb8da2

**Comment by Justsoos** [comment]
楼主和有问题的，可以试一下，先关闭ss，再删除文件后重启
"Shadowsocks\Shadowsocks-4.0.7\ss_win_temp\privoxy_-177508268.conf"
最后那串数字可能有不同。

这里面定义的端口号可能是引发冲突的关键。另外，请先修改你的 ss 本地服务端口，到高端口，1080这种建议不要用，很容易引发 360，迅雷等流氓冲突。

**Comment by celeron533** [comment]
@Justsoos 还有一种可能是用户错误的将前置代理填成了现在的本地代理端口导致回环出现
