### ISSUE TITLE
如何只代理非大陆IP的网站？

### ISSUE THREAD

**Issue by Fezreal** [shadowsocks/shadowsocks-windows#1578]
手机上面的surge和shadowrocket只要这两行规则就能运行得非常好。
GEOIP CN,DIRECT
FINAL,PROXY

而电脑上面的原版ss搭配gfwlist使用情况很不理想，
gfwlist更新的速度太慢了，很不符合实际情况。

有什么**简单的实现办法**吗？本人是初学者， 太高级的办法估计我用不了。

**Comment by chenshaoju** [comment]
https://github.com/breakwa11/gfw_whitelist

**Comment by cn4** [comment]
https://github.com/nadoo/glider
https://github.com/cn4/gfwlist2glider

**Comment by laoasl** [comment]
mark

**Comment by ksotin** [comment]
@chenshaoju 这个白名单结合 Win 版 shadowsocks 具体怎么用？

**Comment by chenshaoju** [comment]
@ksotin move to https://github.com/shadowsocks/shadowsocks-windows/issues/1685
