### ISSUE TITLE
内存溢出：System.OutOfMemoryException: Exception of type

### ISSUE THREAD

**Issue by cnsimo** [shadowsocks/shadowsocks-windows#1580]
### Version(release version or AppVeyor link)
https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.0.7

### Environment(Operating system, .NET Framework, etc)
WIN 10/.NET 4.5

### Steps you have tried
后台正常运行

### Config and error log in detail (with all sensitive info masked)
![image](https://user-images.githubusercontent.com/22788893/34138481-b1d5cc92-e4aa-11e7-9d5b-5c1b00e69ca1.png)

**Comment by celeron533** [comment]
看看log文件是不是过大

**Comment by 54Simo** [comment]
@celeron533 我一直开着【显示日志】页面，开了2个小时不到，好像是日志的问题。但是 4M 算大吗？
![image](https://user-images.githubusercontent.com/22788893/34138904-e7bd19f8-e4ac-11e7-8d3b-ba5c7d48661a.png)

**Comment by chenshaoju** [comment]
你从什么地方下载的SS？请提供下载的连接。

**Comment by celeron533** [comment]
另外可能是net framework有问题

**Comment by celeron533** [comment]
>我一直开着【显示日志】页面，开了2个小时不到，好像是日志的问题。但是 4M 算大吗？

若是开了`详细日志`，会输出较多内容。如果显示日志的窗口一直开着，里面的textbox可能因为追加内容过多过快崩溃。

**Comment by winfield001** [comment]
我的也是out of memory exception, 而且是突然出现的，之前好好的，但目前手机端是正常的，没找到原因

**Comment by chenshaoju** [comment]
@winfield001 请问版本？是自己编译的还是Release版本？

**Comment by Flouse** [comment]
![image](https://user-images.githubusercontent.com/1297478/44844166-bd7fed80-ac7c-11e8-9db1-70a646550c0b.png)
![image](https://user-images.githubusercontent.com/1297478/44844182-c4a6fb80-ac7c-11e8-8fc3-a27b22d8b5e6.png)
这边也出现了同样的问题。

我是共享了 PAC 给办公室其他机器使用，所以连接数较多。

**Comment by chenshaoju** [comment]
@Flouse 请尝试右击任务栏托盘区的纸飞机图标，确保没有选中帮助中的“详细记录日志”。

如果仍然不行，请退出SS，然后删除 SS 目录下的 ss_win_temp 目录，然后再试。

**Comment by Flouse** [comment]
@chenshaoju 我确实是选中帮助中的“详细记录日志”。

**Comment by winfield001** [comment]
@chenshaoju 版本4.0.4，在小夜博客下载的，应该是released的版本

**Comment by chenshaoju** [comment]
@winfield001 无法确认第三方提供的版本是否存在问题，请尝试一下自动编译的版本：
https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by winfield001** [comment]
@chenshaoju 只需要删掉原先的文件夹是吗

**Comment by chenshaoju** [comment]
@winfield001 直接放进去并替换原文件也可以，不过建议新建一个目录，手动重新配置一下看看。

**Comment by winfield001** [comment]
@chenshaoju 可以了，非常感谢！

**Comment by lhuang001** [comment]
和上面一样报错，尝试过上述方法无效，设备是surface pro最新版，防火墙和杀毒软件全部关闭。并且客户端容易闪退，请问是什么原因呢？

**Comment by lhuang001** [comment]
已经尝试过删除temp文件夹，关闭“详细日志”并重新打开ss，依然无效。会不会因为surface系统的原因？

**Comment by lhuang001** [comment]
从4.0.7到最新版本都有这个问题，surface系统是windows10 专业版

**Comment by lhuang001** [comment]
[图片]

**Comment by lhuang001** [comment]
![1](https://user-images.githubusercontent.com/21240907/45965369-dcdf2000-c05a-11e8-9c16-c5a705f3c620.jpg)

**Comment by chenshaoju** [comment]
你的错误提示内容和上面完全不一样。

从提示来看，你的Windows网络栈可能有问题。

请以管理员身份启动命令提示符（ｃｍｄ）或PowerShell，然后执行：
```
netsh inetrface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机即可。

备注：如果你的计算机是手动指定IP的，重启后需要再手动指定一次，如果你自动分配（DHCP）则无需此操作。
