### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by p5310787** [shadowsocks/shadowsocks-windows#1582]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Windows 7 64bits 

### Steps you have tried
尝试重新安装.net 4.7.1以及4.6.2

### What did you expect to see?
恢复使用

### Config and error log in detail (with all sensitive info masked)

**Comment by p5310787** [comment]
![image](https://user-images.githubusercontent.com/33742267/34191810-e5937e3c-e584-11e7-8f85-5bde9479a10e.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1573

**Comment by p5310787** [comment]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	Shadowsocks.exe
  问题签名 02:	4.0.7.0
  问题签名 03:	5a2b6f10
  问题签名 04:	System.Drawing
  问题签名 05:	4.7.2558.0
  问题签名 06:	59d41483
  问题签名 07:	5b3
  问题签名 08:	6b
  问题签名 09:	System.ArgumentException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by p5310787** [comment]
3q I have resolved the problem

**Comment by p5310787** [comment]
3q
