### ISSUE TITLE
无法解析某些二维码

### ISSUE THREAD

**Issue by sijidou** [shadowsocks/shadowsocks-windows#1585]
类似下列链接，在链接尾部含有“=”号的时候，就无法解析二维码，导入链接也无效。
但是在其他客户端上又是有效的。
ss://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxccccwNjg=

**Comment by chenshaoju** [comment]
请尝试使用最新的 4.0.7 版本。

**Comment by ganwen1994** [comment]
@chenshaoju   4.0.7.0 我也一样 4.6.0无问题。

**Comment by chenshaoju** [comment]
你好，我尝试扫描了两家SS服务商提供的二维码，都没有问题。
请注意，如果你扫描的是SSR的二维码，可能不会有反应。

**Comment by ganwen1994** [comment]
@chenshaoju 是SS二维码  我用的商家没有提供SSR服务 这个问题很奇怪，我尝试了几次，分别在不通的套餐里扫同样的节点，一个可以，一个不行，节点全部都一样，密码都一样，只有端口不同。

但我用SSR扫二维码，全部无问题，SSR可以扫SS的二维码，正常识别。

**Comment by chenshaoju** [comment]
我怀疑可能和某个特殊字符有关（密码中的特殊符号？），但是无法确认。

**Comment by ganwen1994** [comment]
@chenshaoju     没有特殊符号 密码为全数字  我是也很纳闷....

ssr可以解析原版二维码 一点问题也没有 只是在SS上有问题。 很奇怪的问题

无所谓了，反正一个二维码也不影响什么。

只是反馈一下。

**Comment by chenshaoju** [comment]
我尝试生成了一个：
```
ss://YWVzLTI1Ni1jZmI6MTIzNDU2QDExMS4yMi4zMy40NDoxMjM0NQ==
```
![image](https://user-images.githubusercontent.com/515763/34332377-e922f8f4-e96a-11e7-9f67-230192d28dca.png)

但是扫描没有问题。。。

**Comment by ganwen1994** [comment]
我刚刚联系的这家提供商的站长，说有这个BUG， 然后站长把他的服务器连接域名更换成.com结尾 就可以扫描了。  原先的域名是club 一换回去就不能扫描。  MDZZ...................


然后也好像并不是这么回事，因为原本的有的能扫有的不行，换成.com就全部可行了。MDZZ..................

**Comment by celeron533** [comment]
你的地址有没有带上`ss://`头？

**Comment by celeron533** [comment]
有点奇怪，我这里无法重现

**Comment by bushi1107** [comment]
我的是安卓版扫了没反应。。。求大神，还有安卓版从粘贴面板导入总是导入失败。。。

**Comment by chenshaoju** [comment]
如果你扫描的是SSR的二维码，不会有反应。

**Comment by iclodq** [comment]
SSR会一直不支持吗?

**Comment by chenshaoju** [comment]
如果你需要混淆，可搭配 simple-obfs 使用： https://github.com/shadowsocks/simple-obfs/releases

**Comment by celeron533** [comment]
有具体范例二维码吗
