### ISSUE TITLE
访问个别站（例如GETCHU）会很卡，但改用同一IP的VPN就正常

### ISSUE THREAD

**Issue by sumirecccp** [shadowsocks/shadowsocks-windows#1586]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.07

### Environment(Operating system, .NET Framework, etc)
WIN10 X64, NET4.7

### Steps you have tried
访问某些站点（例如getchu等）http://www.getchu.com/soft.phtml?id=970693 时页面会卡半天都出不来，但是使用同一服务器的VPN的话还是可以顺畅访问的

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
这种情况意味着你没有代理页面上的其他元素，比如：
```
*.i-mobile.co.jp
*.googleapis.com
*.google.com
*.cloudflare.com
...
```
等等，如果你使用Chrome浏览器，可以使用 https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif 检查哪些页面元素没有正确代理。

**Comment by sumirecccp** [comment]
谢谢回答，但应该不是你所说的问题。模式是选的全局代理，omega显示未加载的资源也全部来自*.getchu.com.
另外CHROME左下角状态栏会显示“正在等待可用的SOCKET……”

![qq 20171225100112](https://user-images.githubusercontent.com/10594381/34330702-ad2776fa-e95a-11e7-98a6-a8afb7044c20.jpg)

**Comment by chenshaoju** [comment]
只有这一个网站这样吗？如果不是的话，我怀疑系统的Winsocks可能有问题。请尝试以管理员身份启动命令提示符（ｃｍｄ）或PowerShell，然后运行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
如果你的安全软件拦截了，请允许，三行命令执行完毕后重启计算机试试。

**Comment by sumirecccp** [comment]
暂时只发现这个站有问题，别的站还没遇到。虚拟机里也试过了，症状一样。

另外诸如动态网等网站则是反过来，只有SS和VPS本机能够访问，VPN就不行

**Comment by sumirecccp** [comment]
今天仔细检查了一下设置，发现是SwitchyOmega里的代理形式被设成了HTTP，改成socks5后恢复正常。
自己另外用Privoxy建立了一个HTTP代理服务器后也是出现一样的问题，暂时不清楚是http代理的限制还是omega的bug

**Comment by chenshaoju** [comment]
应该是HTTP代理的限制，RFC2616建议到每个服务器的连接不超过2个。 https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.1

**Comment by sumirecccp** [comment]
另外使用一些在线webhttp代理访问getchu还是可以正常载入整个页面的，只是速度慢点
建议改进下客户端机制 让IE，EDGE也能正常访问
MAXTHON，chrome这种可以有机制单独设置socks5代理的浏览器倒是可以正常使用，IE就不行
