### ISSUE TITLE
startup:System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by jobsdavid** [shadowsocks/shadowsocks-windows#1588]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.7

### Environment(Operating system, .NET Framework, etc)
windows10 pro,.NET Framwork v4.0.30319

### Steps you have tried
replace shadowsocks.exe（4.0.6） to latest shadowsocks.exe,open with administration 

### What did you expect to see?
running like before updated.

### What did you see instead?
tip：System.IndexOutOfRangeException: 索引超出了数组界限

### Config and error log in detail (with all sensitive info masked)
log info：[2017-12-25 20:47:00] Shadowsocks started
[2017-12-25 20:47:01] [E] System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Shadowsocks.Util.SystemProxy.Sysproxy.ParseQueryStr(String str)
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1416

**Comment by jobsdavid** [comment]
@chenshaoju 还是那个样子的，我换了个路径，删了电脑的缓存。重启电脑，这个情况还是发生。求助 >_<

**Comment by chenshaoju** [comment]
请尝试 https://github.com/shadowsocks/shadowsocks-windows/issues/1487#issuecomment-340370635

**Comment by jobsdavid** [comment]
@chenshaoju thanks a lot!!!
