### ISSUE TITLE
你们这几天开SS有没有很卡并且无法退出的情况

### ISSUE THREAD

**Issue by Dololo87** [shadowsocks/shadowsocks-windows#1589]
你们这几天开SS有没有很卡并且无法退出的情况，在任务管理器强行退出会导致无法上网，需要强行关机

**Comment by Dololo87** [comment]
是这几天才出现的问题，ss和ssr都有这种情况

**Comment by Dololo87** [comment]
在任务管理器强行退出会留下一个“Privoxy”的程序，占用CPU很高，并且无法左下角关机和重启（会卡死），需要强行关机或重启

**Comment by chenshaoju** [comment]
move to https://github.com/shadowsocks/shadowsocks-windows/issues/1577
