### ISSUE TITLE
非预期错误,Shadowsocks异常退出,请求大家的帮助

### ISSUE THREAD

**Issue by rilakkuma33** [shadowsocks/shadowsocks-windows#1590]
win7 64位旗舰版 之前一直正常使用
昨天更新系统补丁失败然后还原系统
然后打开开机ss客户端后就提示缺少两个dll文件,自己找到下载放入系统后接着就提示以下错误
请求大家的帮助,谢谢
![qq 20171226114336](https://user-images.githubusercontent.com/34849133/34346398-18654a50-ea32-11e7-8750-42cd94be75bd.jpg)

**Comment by xlf655** [comment]
一样的问题，同问问。

**Comment by chenshaoju** [comment]
看起来你的 .NET 损坏了，请尝试下载 https://www.microsoft.com/en-us/download/details.aspx?id=30135 ，按照向导修复 .NET 。如果仍然不行，请从 https://www.microsoft.com/net/download/thank-you/net471 先下载并升级/修复安装 .NET 看看。

**Comment by rilakkuma33** [comment]
我的问题解决了,不过原因仍然未知,
刚刚又尝试了一下更新windows补丁,一共有一百多个重要补丁,但仍然和之前一样更新失败还原系统,
在配置失败>>>自动重启,重复了4次后...顺利进入系统...
接着ss客户端就不报错了...大概windows自动修复了点什么吧...
现在反而需要解决windows补丁一直更新失败的问题了Orz
