### ISSUE TITLE
求助 打开报错，不能正常使用

### ISSUE THREAD

**Issue by xlf655** [shadowsocks/shadowsocks-windows#1591]
![default](https://user-images.githubusercontent.com/31313631/34354309-56d0da80-ea68-11e7-8798-020eacfdc871.png)
打开之后就报错，不知道哪里出了问题。

**Comment by chenshaoju** [comment]
请尝试将单独 Shadowsocks.exe 放到一个新目录中，比如 D:\SS\ ，然后再试。

**Comment by xlf655** [comment]
已经解决了  是换一个路径就好了 谢谢。

**Comment by google9002** [comment]
放在C盘是会这样，尝试管理员启动，或者赋予完全控制权限都可以解决
