### ISSUE TITLE
有没有命令行带参数快捷启动方式？

### ISSUE THREAD

**Issue by laikitleung** [shadowsocks/shadowsocks-windows#1593]
RT

**Comment by chenshaoju** [comment]
如果你需要命令行方式来启动SS，你可能需要尝试Shadowsocks for Python： https://github.com/shadowsocks/shadowsocks/tree/master

**Comment by cn4** [comment]
https://github.com/nadoo/glider

**Comment by laikitleung** [comment]
如果有windows下命令行启动方式就好了

**Comment by celeron533** [comment]
问题是为什么要带启动参数呢？

**Comment by polyval** [comment]
有命令行的话就可以写个脚本自动抓账号自动连接了
