### ISSUE TITLE
win10 pac模式下小飞机不闪烁，无法正常使用

### ISSUE THREAD

**Issue by ZhuangAlliswell** [shadowsocks/shadowsocks-windows#1597]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.6

### Environment(Operating system, .NET Framework, etc)
Win10 

### Steps you have tried
打开shadowsocks.exe软件后，启用系统代理，使用扫描二维码方式获取服务器配置信息，pac模式下小飞机不闪烁，打开chrome之后，在代理中配置127.0.0.1:1080之后无法登陆墙外网站，i.e.google youtube等，查看log文档，只有Shadowsocks started，无后续流量信息。

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
请尝试最新的 4.0.7 。

**Comment by celeron533** [comment]
1. 可能是你的chrome中有其他代理托管插件，比如unblock优酷等，他也会虚拟一个代理导致你的其他代理设置失效
2. 确保端口号正确
3. 360安全卫士

可以在IE中设置代理服务器然后用IE访问Google

**Comment by ZhuangAlliswell** [comment]
现在已经恢复正常，感觉过一段时间就好了。原因不详。

2018-01-13 11:54:35"Allen Zhu" <notifications@github.com>写道：

可能是你的chrome中有其他代理托管插件，比如unblock优酷等，他也会虚拟一个代理导致你的其他代理设置失效
确保端口号正确
360安全卫士

可以在IE中设置代理服务器然后用IE访问Google
