### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by calcyu** [shadowsocks/shadowsocks-windows#1599]
win10 64位
.net 提示已经是最新，无法更新

---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.DllNotFoundException: 无法加载 DLL“penimc.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。

   在 MS.Win32.Penimc.UnsafeNativeMethods.CreateResetEvent(IntPtr& handle)

   在 System.Windows.Input.PenThreadWorker..ctor()

   在 System.Windows.Input.PenThreadPool.GetPenThreadForPenContextHelper(PenContext penContext)

   在 System.Windows.Input.PenThreadPool.GetPenThreadForPenContext(PenContext penContext)

   在 System.Windows.Input.TabletDeviceCollection.UpdateTabletsImpl()

   在 System.Windows.Input.TabletDeviceCollection.UpdateTablets()

   在 System.Windows.Input.TabletDeviceCollection..ctor()

   在 System.Windows.Input.StylusLogic.get_TabletDevices()

   在 System.Windows.Input.StylusLogic.RegisterHwndForInput(InputManager inputManager, PresentationSource inputSource)

   在 System.Windows.Interop.HwndStylusInputProvider..ctor(HwndSource source)

   在 System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)

   在 GlobalHotKey.HotKeyManager..ctor()

   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)

   在 Shadowsocks.Program.Main()
---------------------------
确定   
---------------------------

**Comment by chenshaoju** [comment]
请尝试卸载并重新安装 .NET ：https://www.microsoft.com/net/download/thank-you/net471

**Comment by celeron533** [comment]
#1199
#1194 
#1460
