### ISSUE TITLE
总是周期性的激活任务栏

### ISSUE THREAD

**Issue by wibrst** [shadowsocks/shadowsocks-windows#1602]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version (release version or AppVeyor link)
4.0.7

### Environment  (Operating system, .NET Framework, etc)
Win7 SP1  .NETv4.0.30319 

### Steps you have tried
我设置系统任务栏自动隐藏，PC工作过程中，总是会突然自动弹出任务栏。这时候，大家都有常识，即某一个程序激活了任务栏，鼠标右键点击即可恢复任务栏自动隐藏。
据此发现，很多情况都是shadowsocks激活了任务栏。

### What did you expect to see?
期望：任务栏不要被自动激活弹出

### What did you see instead?
现象：任务栏经常被自动激活弹出

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
在Windows 10 16299.125 上测试了30分钟，没有发现任务栏自行弹出的现象。

请问是将纸飞机图标放在托盘区的折叠区域还是在折叠区以外？

如果可能，请做个实验，退出SS，观察24小时看看是否还会出现该现象？

**Comment by roro4ever** [comment]
这种情况我也会出现，但是我认为不是SS引起的，而是修改了WIN10的默认程序，尤其是浏览器改成非IE的情况下。

**Comment by xin344** [comment]
你是不是在使用QQ输入法，它的升级程序会间歇性获取焦点

**Comment by celeron533** [comment]
closed due to inactivity
