### ISSUE TITLE
PAC用户自定文件没有生效

### ISSUE THREAD

**Issue by Tan-Tshunglee** [shadowsocks/shadowsocks-windows#1604]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
v4.0.7

### Environment(Operating system, .NET Framework, etc)
Windows 7 SP1,  .Net Framework 4.6.01590

### Steps you have tried
由于公司把GitHub给封了，所以我们GitHub放到了用户规则里面。以前的版本都是OK的。
直到升级到了v4.0.7 这个版本，好像GitHub又没有通过代理访问了。
重启ShadowSocks 客户端和重启chrome浏览器都没有解决这个问题。
只有设置了系统全局代理，GitHub就可以访问了。

### Config and error log in detail (with all sensitive info masked)

**Comment by Tan-Tshunglee** [comment]
PAC 模式可以访问一些被墙的网址，例如google 和twitter。只是我在用户规则文件里面指定网址没有走代理。

**Comment by celeron533** [comment]
可能是由于 46d40fec678c7ab3c1cd6743e675aa13b6d6af77 仅仅更改了一半的PAC功能，导致某些情况出现问题。#1564 应该修复了这些问题，下个release会有。如果着急的话可以下载那个pull request的CI的build或者回退到4.0.6

**Comment by Tan-Tshunglee** [comment]
非常奇怪的，4.0.7 同一版本，过几天这个问题就没有了。现在我就是用PAC 模式访问的GitHub。

**Comment by zjbdiy** [comment]
之前尝试4.6  win10 64bit pac更新不成功  自己编译的没有问题  现在4.7应该是没有问题的
