### ISSUE TITLE
任务栏飞机图标右击无反应，更换目录也不行

### ISSUE THREAD

**Issue by fonrich** [shadowsocks/shadowsocks-windows#1605]
任务栏飞机图标右击无反应，无法开启代理或者设置其他，版本是4.0.6 更换新版本4.0.7也不行，请问怎么处理，谢谢！

**Comment by chenshaoju** [comment]
请尝试使用 https://www.microsoft.com/en-us/download/details.aspx?id=30135 进行修复，如果修复失败，请按照提示重新清洁安装.Net 4.7.1 ： https://www.microsoft.com/net/download/dotnet-framework-runtime

**Comment by celeron533** [comment]
另外考虑卸360

**Comment by fonrich** [comment]
你好.Net 4.7.1修复也不行






 
------------------ Original ------------------

**Comment by fonrich** [comment]
您好
没有360软件，后来换成Shadowsocks-3.4.2.1就好了，4版本的都不能用


谢谢




 
 
------------------ Original ------------------

**Comment by fonrich** [comment]
换成Shadowsocks-3.4.2.1

**Comment by chenshaoju** [comment]
该问题很高的可能性是 .NET 损坏或者系统有问题导致的。

如果很纠结该问题，你可能需要重装系统或重置系统（Win10）。

**Comment by YWNA-Leon** [comment]
更新一种解决方法：
控制面板-> 卸载程序->启用或关闭Windows功能->
打开.NET Framework 3.5 4.7中的所有功能。
实测有效
