### ISSUE TITLE
电脑在出国后无法访问Google

### ISSUE THREAD

**Issue by Siriu5J** [shadowsocks/shadowsocks-windows#1608]
外国内使用Shadowsocks PAC模式。现在到了国外，国内网站可以访问，Google, Facebook, Twitter等无法访问。开启Shadowsocks之后又可以访问了。有没有什么解决办法。谢谢

**Comment by chenshaoju** [comment]
请在退出SS后，进入 控制面板、网络和 Internet，打开 Internet 选项，然后找到连接选项卡，并点击局域网设置按钮，取消下图中的两个复选框后确定、确定，再试。

![image](https://user-images.githubusercontent.com/515763/34491950-87e3e9b0-f020-11e7-9865-19051dffe4d5.png)

**Comment by Siriu5J** [comment]
@chenshaoju我试了，还是不行。出国了手机出墙了，电脑仿佛还卡在墙内。

**Comment by Siriu5J** [comment]
@chenshaoju而且按照这个方法做之后会弹出：你的连接不是私密连接

**Comment by chenshaoju** [comment]
是什么地方会弹出“你的连接不是私密连接”的提示？能否截个图？

**Comment by celeron533** [comment]
“不是私密连接”说明在直连状态下https的证书出了问题。
可能在你的机器上安装过底层的广告过滤软件或者其他梯子。

**Comment by chenshaoju** [comment]
另外，请检查是否有使用Hosts翻墙，如果有，请记得清空Hosts文件。

**Comment by Siriu5J** [comment]
@chenshaoju好，谢谢，我回去看一看

**Comment by Siriu5J** [comment]
@chenshaoju我查看过hosts，没有改过

**Comment by Siriu5J** [comment]
@celeron533但是我连接了ss就可以连接了

**Comment by Siriu5J** [comment]
@celeron533而且情况是只有我刚刚连接过的网站刷新了才会出现这个错误。打开新网页就会连接不上。我觉得还是和PAC有关。

**Comment by Siriu5J** [comment]
@chenshaoju
![default](https://user-images.githubusercontent.com/35037404/34518053-7f6e636c-f0b8-11e7-8c24-1ba53b516cf1.png)

**Comment by chenshaoju** [comment]
能否检查一下你的Firefox的代理设置？我怀疑你的Firefox可能设置了一个代理。

或者你的DNS有问题，请检查你所使用的DNS是自动分配还是手动指定的，如果你制定了国内的DNS，也可能会有这个问题。

**Comment by Siriu5J** [comment]
@chenshaoju应该不是Firefox的问题，因为Chrome, IE都不能用。我去看看DNS吧

**Comment by Siriu5J** [comment]
@chenshaoju Anyway, 我重置了网络，现在OK了。谢谢

**Comment by SeniorZhai** [comment]
同样的情况，清DNS解决

**Comment by whalehelo** [comment]
windows10 求助 。就谷歌不能上网，其他页面能访问。vpn DNS 都清理了，急死了

**Comment by whalehelo** [comment]
谷歌卸了 网卡也卸载了都不行。急死了
