### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by XXXXXXOOOOOO** [shadowsocks/shadowsocks-windows#1610]
[2018-01-03 15:52:28] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.String.ReplaceInternal(String oldValue, String newValue)
   在 System.String.Replace(String oldValue, String newValue)
   在 Shadowsocks.Controller.PACServer.SendResponse(Byte[] firstPacket, Int32 length, Socket socket, Boolean useSocks)
[2018-01-03 15:52:28] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.String.ReplaceInternal(String oldValue, String newValue)
   在 System.String.Replace(String oldValue, String newValue)
   在 Shadowsocks.Controller.PACServer.SendResponse(Byte[] firstPacket, Int32 length, Socket socket, Boolean useSocks)
[2018-01-03 15:52:28] [E] Exception Detail: 
System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.Text.StringBuilder.ReplaceBufferInternal(Char* newBuffer, Int32 newLength)
   在 System.Windows.Forms.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
   在 System.Windows.Forms.Control.get_WindowText()
   在 System.Windows.Forms.TextBoxBase.get_WindowText()
   在 System.Windows.Forms.TextBoxBase.ScrollToCaret()
   在 Shadowsocks.View.LogForm.UpdateContent()
   在 Shadowsocks.View.LogForm.Timer_Tick(Object sender, EventArgs e)
   在 System.Windows.Forms.Timer.OnTick(EventArgs e)
   在 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[2018-01-03 15:52:28] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.Text.StringBuilder.ToString()
   在 System.IO.StreamReader.ReadToEnd()
   在 System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   在 System.IO.File.ReadAllText(String path, Encoding encoding)
   在 Shadowsocks.Controller.PACServer.GetPACContent()
   在 Shadowsocks.Controller.PACServer.SendResponse(Byte[] firstPacket, Int32 length, Socket socket, Boolean useSocks)
[2018-01-03 15:52:28] System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 System.String.Concat(String str0, String str1)
   在 Shadowsocks.Controller.PACServer.SendResponse(Byte[] firstPacket, Int32 length, Socket socket, Boolean useSocks)

**Comment by XXXXXXOOOOOO** [comment]
4.0.7

**Comment by chenshaoju** [comment]
请尝试退出SS，然后删除 Shadowsocks.exe 所在目录下的 ss_win_temp 文件夹，然后再试。
