### ISSUE TITLE
win10 1709 x64 启动异常

### ISSUE THREAD

**Issue by sinkingsoul** [shadowsocks/shadowsocks-windows#1611]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.07 还有之前的版本都试过

### Environment(Operating system, .NET Framework, etc)
win10 1709 x64 系统自带的.NET Framework4.7
从1607用易升全新安装到的1709,之前1607保存个人文件升级到1709没问题

### Steps you have tried
1.尝试过重新安装.NET Framework,被系统阻止,暂时没找到方法重装.NET Framework
2.网上下载libsscrypto.dll放入SYSTEM32或SYSWOW64并注册,提示缺少另外的DLL.

### Config and error log in detail (with all sensitive info masked)
[2018-01-03 16:05:54] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-01-03 16:05:59] connect to clients1.google.com:443
[2018-01-03 16:05:59] System.TypeInitializationException: “Shadowsocks.Encryption.EncryptorFactory”的类型初始值设定项引发异常。 ---> System.TypeInitializationException: “Shadowsocks.Encryption.Sodium”的类型初始值设定项引发异常。 ---> System.DllNotFoundException: 无法加载 DLL“libsscrypto.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.Sodium.sodium_init()
   在 Shadowsocks.Encryption.Sodium..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Encryption.Sodium.get_AES256GCMAvailable()
   在 Shadowsocks.Encryption.EncryptorFactory..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()

**Comment by chenshaoju** [comment]
libsscrypto.dll 是 Shadowsocks.exe 自己吐出来放到 ss_win_temp 目录中的。
请尝试将 Shadowsocks.exe 单独放到一个另外的目录试试，比如 D:\SS\

**Comment by sinkingsoul** [comment]
@chenshaoju 谢谢,尝试单独一个目录成功开启了.
