### ISSUE TITLE
能否添加直接使用Privoxy分流HTTP代理的功能(针对局域网共享)

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-windows#1612]
如题，将pc的代理共享给局域网使用，但是pac分流似乎有一些奇怪的问题，例如编辑或更新gfwlist规则后无法即时生效，重启电脑后pac失效等(已经去掉本地pac保护)，这并不总是会出现，而且我没有发现在本地有同样的问题。最后我直接用Privoxy开固定端口分流似乎工作得更好，gfwlist到Privoxy规则的转换也十分简单，有现成的项目。既然ss本身也用到了Privoxy，能否将其作为一个可选功能让用户自行开启？

**Comment by chenshaoju** [comment]
实际上我也有这个需求，不过现成的解决方法是当成 ss_privoxy.exe 不存在，然后自己配一个 privoxy.exe 并监听在其他端口上。

**Comment by kevinzh1** [comment]
我目前也是自己配了一个，配置不麻烦，就是gfwlist更新有点不便，我本地还是用的pac…如果能整合进去最好了。

**Comment by MatcherAny** [comment]
我的做法是再开一个Privoxy，添加配置
```
listen-address 0.0.0.0:1080
forward-socks5 / localhost:1081 .
```
![default](https://user-images.githubusercontent.com/29697421/34591971-fbb36546-f1fb-11e7-8a5d-3614c54c280e.png)


但是直接合并就好了~~~~

**Comment by cn4** [comment]
试下我的规则，配合glider
https://github.com/cn4/gfwlist2glider

**Comment by celeron533** [comment]
Privoxy体积小巧但功能有限，如果有功能上较大的需求，可以用squid3做个带有认证、缓存的代理
