### ISSUE TITLE
希望能修复“端口已被占用”问题

### ISSUE THREAD

**Issue by iamsurfing** [shadowsocks/shadowsocks-windows#1615]
github上的ss4.0.7
ofbs-local来自https://github.com/shadowsocks/simple-obfs/releases 的0.0.5版本
使用的是win10
win10自带的.net
偶尔会在“允许来自局域网的连接”开关，切换服务器，开启关闭系统代理或切换系统代理模式时，会出现错误。
 System.Exception: 端口已被占用
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
任务管理器显示两个obfs-local.exe进程。
如果要继续使用，就要把两个进程结束，再“允许来自局域网的连接”开关，切换服务器，开启关闭系统代理或切换系统代理模式，才能用。如果不结束两个进程，就会一直显示端口已被占用。
（可能有的时候不会显示两个进程，但是解决方法是一样的。）
希望能修复这个bug。

**Comment by celeron533** [comment]
#1466

**Comment by celeron533** [comment]
可以先试试 @hyec 的pull request 版本
https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/4.0.7.8/job/dtcmar9e06gcne73/artifacts

**Comment by iamsurfing** [comment]
抱歉，由于windows版ss还有一个不可避免的问题，在开启或关闭网游加速器的时候所有需要监听端口的服务都会失效，需要重新点一下。所以，我已经把ss客户端架到路由器上了。

**Comment by celeron533** [comment]
网游加速器可能强制修改过系统代理

**Comment by sitiger** [comment]
github上的ss4.0.7
没有使用ofbs-local等东西
使用的是win10
win10自带的.net,因为出过问题修复过
,也是楼主的问题,不频繁

**Comment by EricBrownz** [comment]
端口被占也有过
不过还行，不是经常
