### ISSUE TITLE
原生socks5

### ISSUE THREAD

**Issue by LiRRRR** [shadowsocks/shadowsocks-windows#1616]
希望可以增加一个原生的socks5服务器选项。
或者大佬们知道有什么socks5的客户端支持局域网分享吗？
现在想在电脑开个socks5客户端用provixy转成http, 然后通过局域网分享给PS4使用。

**Comment by chenshaoju** [comment]
你所谓的“原生的socks5服务器”具体是指怎么个原生法？

在编辑服务器界面右下角的那个代理端口号就是一个SOCKS5端口。

**Comment by celeron533** [comment]
>在编辑服务器界面右下角的那个代理端口号就是一个SOCKS5端口。

这个端口可以同时接收http代理和socks5代理请求

**Comment by LiRRRR** [comment]
@chenshaoju  我是指socks5明文代理, 不是搭的ss, 没有加密. 比如在chrome SwitchyOmega插件中指定socks5+IP+port就可以代理. 只用proxifier设置下socks5+ip+port.
目前环境是socks5代理到国内vps, 然后转发到国外vps。

**Comment by chenshaoju** [comment]
你的意思是你要自己搭建一个Socks5代理？

http://www.catonmat.net/blog/linux-socks5-proxy/

**Comment by LiRRRR** [comment]
@chenshaoju 呃, 现在socks5代理是搭好的, 可以只用proxifier等客户端来代理, 但是proxifier并没有局域网连接这个功能. 我也一直在用ss, 所以想问下增加支持明文socks5服务器这个功能好做吗(就是可以充当普通socks5客户端)？感谢 😄

**Comment by chenshaoju** [comment]
不太可能……Shadowsocks设计的目的不是为了这个。。。我建议你考虑为你的局域网部署proxifier或者其他软件。。。

**Comment by cn4** [comment]
试下这个吧，有socks5：
https://github.com/cn4/gfwlist2glider

**Comment by scruel** [comment]
也希望和 Qv2ray 等一样支持配置 socks5 代理，前置代理没见过其他客户端有更好用的。。。
