### ISSUE TITLE
【疑惑】System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。

### ISSUE THREAD

**Issue by Qingmu** [shadowsocks/shadowsocks-windows#1617]
使用安卓端能够连上，win10却出现`System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许`，能够ping通，但是telnet和tcping则被挡，但客户端已加进防火墙规则

另，虽然已安装finalspeed，但是目前是用ss客户端直连

### Version(release version or AppVeyor link)
ss 4.0.7

### Environment(Operating system, .NET Framework, etc)
win10

### Steps you have tried
1. 按照troubleshooting，把ss_win_temp删了一遍
2. 查看防火墙规则，ss已经加进去了（多年以前把ssr也加进去了，应该没影响吧）
3. 使用管理员权限打开ss
4. 尝试D:\XX\tcping.exe XX 443，然而`Probing XXX:443/tcp - No response - time=2002.224ms`，但是能够ping通
5. 把ss客户端默认的端口1080改为，6666,8888，仍然无效，使用netstat -a 发现相应的端口处于`TIME_WAIT`状态
### What did you expect to see?
win10 能够连上

### What did you see instead?
安卓端，使用同样的配置能连上
win10在log里则显示
```
 System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
```

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1035

**Comment by Qingmu** [comment]
就是这个！！
`server`改成`::`就好~

多谢多谢~~

**Comment by JimLee1996** [comment]
别用finalspeed了，直接用kcp协议
