### ISSUE TITLE
PAC模式下建议增加IPv6站点直连功能

### ISSUE THREAD

**Issue by IMconnor** [shadowsocks/shadowsocks-windows#1619]
> 教育网在正确配置了DNS的前提下，比如通过dnscrypt或unbound等工具，Google或Facebook这类网址可以通过IPv6直连。默认的pac.txt不支持这一操作，访问具有aaaa记录的网址较慢，建议增加一个教育网IPv6站点直连的选项。只需将pac.txt最后的FindProxyForURL函数增加一个语句即可：

> 现在的版本

```
function FindProxyForURL(url, host) {
    if (defaultMatcher.matchesAny(url, host) instanceof BlockingFilter) {
        return proxy;
    }
    return direct;
}
```

> 增加IPv6支持后

```
function FindProxyForURL(url, host) {
    if (shExpMatch(dnsResolveEx(host), "*:*")) {
	return direct;
    }
    if (defaultMatcher.matchesAny(url, host) instanceof BlockingFilter) {
        return proxy;
    }
    return direct;
}
```

> 不过这个办法不支持Firefox，Chrome这类使用IE代理的浏览器全部支持。

**Comment by chenshaoju** [comment]
你好，Shadowsocks for Windows 使用的是 https://github.com/gfwlist/gfwlist 的 PAC 列表，对于该 PAC 并没有控制权，你可以前往 GFWList 的 issue 提交建议。

**Comment by IMconnor** [comment]
@chenshaoju 
gfwlist是个list，对应的是pac.txt里面的var rules列表…要提我也应该找 https://github.com/clowwindy/gfwlist2pac 这个项目去提，不过已经404啦。而且主要是需要在软件里做个开关，默认关闭，有IPv6接入时才可选打开。
```
// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac
```

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/blob/7021edd61fad790b861fdf13647b585c96e7310e/shadowsocks-csharp/Controller/Service/GfwListUpdater.cs#L17

**Comment by IMconnor** [comment]
这么说好了，gfwlist是url列表不是pac列表，没有任何js函数。pac.txt由3部分组成：gfwlist + user-rule + adblock plus的js函数，现在只需要稍微改动adp部分的最后一个FindProxyForURL函数增加IPv6支持而已，希望不要再误会了…
Service部分应该要涉及这两个文件

> shadowsocks-windows/shadowsocks-csharp/Controller/Service/GfwListUpdater.cs
> shadowsocks-windows/shadowsocks-csharp/Controller/Service/PACServer.cs

**Comment by celeron533** [comment]
如果你使用的是基于chromium核心的浏览器或FF浏览器，可使用switchyOmega再叠加一层自己的代理设置，非常灵活

**Comment by IMconnor** [comment]
@celeron533 有没有大体的思路我试试看？不过FF应该不支持IPv6 Extensions to Navigator Auto-Config File Format，这是微软的东西。

**Comment by IMconnor** [comment]
@celeron533 试了一下，switchyOmega日常用是很灵活，不过可定制性还不如自己手动改pac.txt。拿到域名需要解析是否存在aaaa记录，这需要改代码，目前在switchyOmega里面办不到。其实每次从gfwlist更新完pac再打个补丁也还好，算了算了，这需求太小众。
