### ISSUE TITLE
System.InvalidOperationException:Collection was modified;

### ISSUE THREAD

**Issue by sujinde** [shadowsocks/shadowsocks-windows#1620]
情景：Android开发环境环境下，看了一会斗鱼直播，再回来就爆如图错误；
系统：Win7旗舰版
看直播浏览器：Google Chrome | 63.0.3239.84 (正式版本) （64 位） (cohort: Stable)
![_20180108185826](https://user-images.githubusercontent.com/13985030/34668213-4f2f5c90-f4a7-11e7-8c06-4c06ab1f23fb.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1490
