### ISSUE TITLE
重庆联通校园网确实无法使用。。

### ISSUE THREAD

**Issue by liyoufei** [shadowsocks/shadowsocks-windows#1622]
win10，4.0.7，网线接入并用dr.com登校园网账号翻不过
然而用手机的热点却可以。。
或许  是本地网络哪里没有配置好？

**Comment by chenshaoju** [comment]
日志中有什么显示吗？

**Comment by liyoufei** [comment]
请问怎么查看日志呀
另外，我用xshell也不能登陆我的vps，只有连接手机热点才可以

**Comment by chenshaoju** [comment]
右击托盘区的纸飞机图标，帮助，显示日志。

如果你的网络有很严格的端口屏蔽/审核/过滤，可能会有问题。

**Comment by celeron533** [comment]
推测：
1. 学校可能封端口
2. 学校可能有包探测
3. Dr客户端可能会干扰ss客户端

**Comment by liyoufei** [comment]
![019](https://user-images.githubusercontent.com/22241341/34727396-b53d6d84-f591-11e7-9c12-bf460234485d.jpg)

**Comment by 875353581** [comment]
请问大大，我这个是什么问题，弄了一天了，不知道什么情况
[2018-01-12 10:35:12] Shadowsocks started
[2018-01-12 10:40:18] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于意外的数据包格式，握手失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
@875353581 请尝试在另一台计算机或者手机上再配置一次，看看能否使用。

如果能，请检查有问题的计算机上的SS设置（IP、端口、密码、加密方式等）是否正确。

如果不能，请检查服务端配置是否正确，如果你是购买的某个SS服务商的，请与你的SS服务商联系。

如果确认无误，并且手机／其他计算机上没有问题，请在有问题的计算机上以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
并重启计算机然后再试。

如果仍然不行，请尝试使用 https://www.microsoft.com/en-us/download/details.aspx?id=30135 修复 .NET Framework，如果修复后仍然不工作，请尝试安装最新的 .NET Framework： https://www.microsoft.com/net/download/dotnet-framework-runtime 。

若都不行，说明你的系统可能损坏了，请尝试重新安装操作系统。

**Comment by 875353581** [comment]
按照步骤重置，修复NET还是不行。我用的是Vultr的服务器，其他现象包括：连上服务器开启ss然后查IP，没有变化，依然是国内IP；服务器只有22端口能连上，其他端口不行；SS里从GWlist更新本地PAC失败：Failed to update PAC file

**Comment by chenshaoju** [comment]
这基本上是因为你的配置有问题。

请尝试检查服务端的配置是否正确，如果你使用了默认的端口，请更换一个试试。

**Comment by 875353581** [comment]
已经解决了，谢谢大大。我换了Shadowsocks-4.0.6就好了，居然是这个问题

**Comment by chenshaoju** [comment]
不过我还是认为不是版本问题，因为手机上也不行。
