### ISSUE TITLE
Win10 1709 ss CSharp 4.0.7 自动退出

### ISSUE THREAD

**Issue by cmj1b** [shadowsocks/shadowsocks-windows#1623]
错误应用程序名称: Shadowsocks.exe，版本: 4.0.7.0，时间戳: 0x5a2b6f10
错误模块名称: ntdll.dll，版本: 10.0.16299.192，时间戳: 0x16e7ff7f
异常代码: 0xc0000005
错误偏移量: 0x0005d0ec
错误进程 ID: 0x199c
错误应用程序启动时间: 0x01d387c4fa5a6dfb
错误应用程序路径: C:\opt\Shadowsocks\Shadowsocks.exe
错误模块路径: C:\Windows\SYSTEM32\ntdll.dll
报告 ID: 1e7f45af-0bdf-4821-9a0b-cb26126b6c02
错误程序包全名: 
错误程序包相对应用程序 ID: 

大概每一天会出现一次，间隔最长为22小时

**Comment by chenshaoju** [comment]
从错误情况来看，0xc0000005为访问冲突，很可能是你的系统存在某些安全软件、内核驱动或者系统文件损坏。

请尝试重新启动计算机，看看能否解决。

也可能是 .NET Framework 损坏，请尝试使用： https://www.microsoft.com/en-us/download/details.aspx?id=30135 进行修复，如果修复失败，请安装最新的 .NET Framework 试试看： https://www.microsoft.com/net/download/thank-you/net471 。

**Comment by sssshadowsocks** [comment]
预订服务地址 https://portal.shadowsocks.la/aff.php?aff=12091
• Windows  客戶端下載 https://portal.shadowsocks.la/files/Shadowsocks-4.0.6.zip 注：需要安裝 .NET FrameWork 4.6.2 以上版本
• iOS  相關客戶端與使用方法請參考下述鏈接： https://github.com/Shadowsocks-Wiki/shadowsocks/blob/master/4-ios-settings.md
• MAC OS  請更新到 ShadowsocksX-NG 使用 下載地址： https://portal.shadowsocks.la/files/ShadowsocksX-NG.1.6.1.zip
• Android下載地址  下載地址： https://portal.shadowsocks.la/files/shadowsocks-nightly-4.2.5.zip
• Linux用戶  請使用最新的 Shadowsocks-libev 命令行版本 安裝與使用請參考：https://github.com/shadowsocks/shadowsocks-libev
