### ISSUE TITLE
win 10 下浏览youtube网速只能看480p的视频，但是在苹果手机上使用SsrConnectPro却可以流畅观看720p

### ISSUE THREAD

**Issue by ydw9527** [shadowsocks/shadowsocks-windows#1625]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.7

### Environment(Operating system, .NET Framework, etc)
win 10
vps是搬瓦工的那套中国特供版的套餐
### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
你好，我在Win10上测试了一下，没有问题。

![2018-01-14 1](https://user-images.githubusercontent.com/515763/34907988-53e0f22e-f8c3-11e7-9739-2c833f7fe233.png)

如果你确认电脑和手机使用的是相同的配置，可能和你操作系统的网络和协议栈有关系，请尝试以管理员身份启动命令提示符（cmd）或PowerShell，执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，三行都执行完毕后重启计算机再看看效果。

**Comment by sssshadowsocks** [comment]
和自己的网速有关
https://portal.shadowsocks.la/aff.php?aff=12091

**Comment by ydw9527** [comment]
原来是路由器的原因，重启下就好了
