### ISSUE TITLE
在全局模式下，hosts文件里的设置会被忽略，导致破解的lightroom连接到了adobe的验证服务器，请问有什么办法解决呢？

### ISSUE THREAD

**Issue by ydw9527** [shadowsocks/shadowsocks-windows#1626]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
０.出于安全考虑，建议不要使用盗版软件。

１.如果是这种情况，建议使用PAC模式，并且将你想要代理的地址放到PAC文件中。

**Comment by sssshadowsocks** [comment]
预订服务地址 https://portal.shadowsocks.la/aff.php?aff=12091
• Windows  客戶端下載 https://portal.shadowsocks.la/files/Shadowsocks-4.0.6.zip 注：需要安裝 .NET FrameWork 4.6.2 以上版本
• iOS  相關客戶端與使用方法請參考下述鏈接： https://github.com/Shadowsocks-Wiki/shadowsocks/blob/master/4-ios-settings.md
• MAC OS  請更新到 ShadowsocksX-NG 使用 下載地址： https://portal.shadowsocks.la/files/ShadowsocksX-NG.1.6.1.zip
• Android下載地址  下載地址： https://portal.shadowsocks.la/files/shadowsocks-nightly-4.2.5.zip
• Linux用戶  請使用最新的 Shadowsocks-libev 命令行版本 安裝與使用請參考：https://github.com/shadowsocks/shadowsocks-libev
