### ISSUE TITLE
如何让国外ip都走ss

### ISSUE THREAD

**Issue by Cherrs** [shadowsocks/shadowsocks-windows#1628]

**Comment by chenshaoju** [comment]
这个可能对你有帮助：https://github.com/shadowsocks/shadowsocks-windows/issues/1270

**Comment by Cherrs** [comment]
@chenshaoju 不太懂那个cow。。具体原理是什么呢，pac不能根据ip代理吗

**Comment by chenshaoju** [comment]
我对PAC没有仔细研究，详情阅读： https://github.com/breakwa11/gfw_whitelist

**Comment by Cherrs** [comment]
好吧 貌似和我的需求有点不太一样，不过还是谢谢了 @chenshaoju

**Comment by afmnnn** [comment]
不能用了大神怎么办能修好吗

**Comment by Cherrs** [comment]
@afmnnn 什么不能用了?

**Comment by afmnnn** [comment]
@Cherrs shadowsocks-windows-4.0.7  通过https://freess.cx/ 扫二维码 使用全局模式不能上国外网站 pac模式下 有时能上有时不能上 
win7 64位 前几天开始这样的 之前好好的都能用 现在不知什么问题

**Comment by Cherrs** [comment]
@afmnnn 可能是freess的服务器出了问题，这个我无法给你解决啊。
