### ISSUE TITLE
Shadowsocks non-UI Error 非预期错误Shadowsocks将退出。

### ISSUE THREAD

**Issue by TalentJack** [shadowsocks/shadowsocks-windows#1630]
ss版本4.0.4.0
win10系统
启动ss就报错
报错信息如下：
System.NullReferenceException:未将对象引用设置到对象的实例。
在Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable,Boolean global,String proxyServer, String pacURL)
在Shadowsocks.Controller.SystemProxy.Update(Configuration config,Boolean forceDisable, PACServer pacSrv)
在Shadowsocks.Controller.ShadowsocksController.Reload()
在Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
请先尝试：
https://github.com/shadowsocks/shadowsocks-windows/issues/1178#issuecomment-308097676

如果仍然不行，请删除 Shadowsocks.exe 所在目录下的 ss_win_temp 目录后再试。

**Comment by TalentJack** [comment]
下载新版本后使用一切正常,谢啦
