### ISSUE TITLE
搬瓦工19.9年套餐补货了，需要的可以去买一个玩玩

### ISSUE THREAD

**Issue by haochiburujiaozi** [shadowsocks/shadowsocks-windows#1631]
等了这么久，终于补货了，19.9美金加上优惠码算下来才120人民币，结合shadowsocks非常合算。

[国内镜像购买链接](https://bwh1.net/aff.php?aff=24912)

给大家分享下，打扰了。

安装教程可参考：
https://www.tbreak.top/kda/56/

**Comment by celeron533** [comment]
no spam
