### ISSUE TITLE
无法翻墙

### ISSUE THREAD

**Issue by gauss-clb** [shadowsocks/shadowsocks-windows#1632]
自己用国外的vps搭了ss， 国内windows用了这个客户端，使用PAC代理，刚开始设置好是可以翻墙的，并且设置了开机自启，但下次开机就不能翻墙了，只能上国内网站， 关闭ss客户端，连国内的网页上不了， 这是怎么回事？ 使用全局代理， 什么网都上不了？ 太奇怪了。

**Comment by chenshaoju** [comment]
你是局域网上网对吧？

请检查这个地方，如果没开启SS的情况下启用了，请取消勾上的那个选项，然后再试。

![image](https://user-images.githubusercontent.com/515763/35190601-6ea52e80-fea0-11e7-8ac9-b7999b013489.png)

**Comment by qq425540458** [comment]
@chenshaoju         请问一下PAC设置里的保护本地PAC是什么意思   需要勾选吗？  有时勾选了反而出现500 Internal Privoxy Error 不能访问外网的问题。

**Comment by chenshaoju** [comment]
选中保护本地PAC与否并不会导致５００错误。

如果有５００错误，可能是你的服务器不通了，比如网络质量差。

如果你的服务端使用的是默认的端口，请更换一个，已知默认端口被重点关照。

**Comment by gauss-clb** [comment]
@chenshaoju 你说的默认端口是8388吗？ 还有本地端口1080？ 是不是这些导致不能翻墙？

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1428

**Comment by qq425540458** [comment]
@chenshaoju 对了 ，保护PAC是勾选好还不是不够选 ？ 我不知道这个是什么意思 。

**Comment by chenshaoju** [comment]
好象是防止PAC被修改。

**Comment by ccwinner** [comment]
取消勾选以后是不是要重启计算机？我取消勾选以后，还是不能翻墙

**Comment by gauss-clb** [comment]
@ccwinner 修改一下服务器的ss配置文件，将默认端口8388改掉，我改了就能翻墙了，不需要取消勾选的，就是要PAC代理， 取消勾选应该是你关闭了ss客户端，然后上不了网， 此时不需要代理。

**Comment by ccwinner** [comment]
@gauss-clb 服务器设置里面已经把端口改成我的了 还是不行。我用macbook连是可以翻墙的，windows就失败

**Comment by ccwinner** [comment]
@gauss-clb 你windows下的ssr版本是什么

**Comment by qq425540458** [comment]
@gauss-clb   我也一样的问题，你是指编辑服务器改代理端口吗 ？ 原来是1080的， 请问你改的多少可以翻墙？

**Comment by chenshaoju** [comment]
如果你搭建的是SSR的服务端，那么你需要使用SSR的客户端。

**Comment by gauss-clb** [comment]
@ccwinner 好像就是ss，不是ssr

**Comment by gauss-clb** [comment]
@qq425540458 1080是本地端口，服务器那边默认设置的是8388，这个端口可能被重点关注了

**Comment by lolipopsq** [comment]
<html>
<body>

别折腾XX-NET了，推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history
