### ISSUE TITLE
net framework安装失败，错误代码0x800f081f

### ISSUE THREAD

**Issue by i4b3thu9nx2** [shadowsocks/shadowsocks-windows#1634]
![image](https://user-images.githubusercontent.com/35629462/35191019-5062aeb0-feab-11e7-9b3a-31e89e1411c2.png)
另外在“启用或关闭windows功能”里面试图打开net4.6会跳出一个叫做组件存储已损坏0x80073712的东西。以前曾经按教程弄过，不记得当时有这种问题，最近重装系统换了win10不知道有没有关系？

**Comment by chenshaoju** [comment]
请尝试使用 https://www.microsoft.com/en-us/download/details.aspx?id=30135 进行修复。

**Comment by i4b3thu9nx2** [comment]
@chenshaoju 刚才尝试过了……

**Comment by chenshaoju** [comment]
查了一下，比较复杂。

可能和你系统的补丁库有关，你可能使用过某些清理软件清理过系统的MSI安装包，导致该问题。

请尝试使用 https://support.microsoft.com/zh-cn/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed 的方法看看能否修复。

**Comment by i4b3thu9nx2** [comment]
@chenshaoju 下载了刚打开就说进行疑难解答时出错……

**Comment by chenshaoju** [comment]
你这个系统有问题的可能性很高。。。我建议你备份数据，然后重置系统看看……

**Comment by i4b3thu9nx2** [comment]
@chenshaoju 但是刚重装一个多月啊……是他重装过程中出了岔子还是我自己又装了奇怪的东西？

**Comment by chenshaoju** [comment]
这我就不知道了，你的系统。。。。  ¯\_(ツ)_/¯
