### ISSUE TITLE
win10下 3.4.3 翻墙如google突然500 error

### ISSUE THREAD

**Issue by liaojixiao1306410122** [shadowsocks/shadowsocks-windows#1636]
刚更新win10后也出现过500，但是把浏览器代理设置里的勾全取消掉就可以上了。 
然而前几天玩pubg的时候开了uu加速了亚服同时又忘了关ss，卡在了进入跳伞等待区的界面，遂关掉ss就进去了。接着问题来了，昨天连上ss，换了好几个服务器，并且确定服务器没有问题的情况下，chrome和edge访问google一直500，试过了百度上的所有方法都没效果，求解。
ps：用3.4.3的原因是最新的版本用二维码功能扫描老是无效。

**Comment by chenshaoju** [comment]
SS的日志中有什么显示吗？

**Comment by liaojixiao1306410122** [comment]
[2018-01-23 19:49:21] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

完全看不懂.. 另外服务器一直在显示 time out

**Comment by liaojixiao1306410122** [comment]
android手机装了ss连同一个服务器在另一个的wifi下可以用，但是在4g和自己家的wifi就用不了，关键是之前电脑是可以用的..自己除了uu加速器和ss同时开了一次之外 没有任何特别的操作了..

**Comment by qq425540458** [comment]
你是不是用的免费SS  我之前用免费 现在不行了  全都是500错误

**Comment by chenshaoju** [comment]
你是自己搭的SS服务器、购买的SS服务、还是用的某个免费的SS服务？

如果是自己搭的，看这里：https://github.com/shadowsocks/shadowsocks-windows/issues/1629

如果你是购买的SS服务，请与你的SS服务商联系。

如果是免费的……恩……另外找个把。

**Comment by liaojixiao1306410122** [comment]
之前一直用的公司老大搭的vps，公司ss是装在路由器上的，win8系统的时候在家里也一直可以用公司的vps上google等，升级到win10之后就500了，后来考虑是不是公司vps原因，就换了多个免费ss来试，发现在家里依旧500，但是在公司尝试用mac的ss客户端也能用这些免费的(就是whoer里可以看到ip变成这些免费ss的ip了)... 我就想搞清楚是我win10电脑原因还是服务器原因... 家里两台win10的都连不上...因为比较小白..所以搞的自己有点不敢自己去买vultr什么的自己搭

**Comment by chenshaoju** [comment]
你手机上有SS吗？相同的配置手机上能用吗？

**Comment by Steve789** [comment]
可以作如下尝试：
1.在windows命令提示符中运行：netsh winsock reset  重置本地端口为默认。
2.继续在命令提示符运行：ipconfig /flushdns  刷新本地DNS缓存。
3.参考https://www.zhihu.com/question/19721279 清理chrome DNS缓存、重置端口。
以上仅供参考，不保证解决问题也可能是ss服务器根本联不通或ss配置错误。

**Comment by tickdock** [comment]
<html>
<body>

助你跨过GFW，来到自由世界！推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by celeron533** [comment]
500错误有时候是由于客户端收到了空回复，部分原因是连接受到干扰或者对方网站服务器（不是ss服务端）在中途主动断开

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/884#issuecomment-260284108
