### ISSUE TITLE
不需要勾开启代理，只要打开软件就能直接代理，关闭软件直接断网

### ISSUE THREAD

**Issue by publig** [shadowsocks/shadowsocks-windows#1637]
关闭代理之后会直接上不了网。
不用勾开启代理自动就能代理，只要软件开着
更改pac和全局的选项需要关闭软件在打开才有效

**Comment by publig** [comment]
win7 64位 不具备管理员权限

**Comment by publig** [comment]
用的是非常老的版本 2.5 明天用4.0.7测一下 主要4.0.7的下载链接我这边访问访问不了

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1632#issuecomment-359221581

**Comment by tickdock** [comment]
<html>
<body>

助你跨过GFW，来到自由世界！推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>
