### ISSUE TITLE
为什么每次版本升级都要在新版本里手动设置各种信息？不能平滑升级吗？

### ISSUE THREAD

**Issue by lingshow** [shadowsocks/shadowsocks-windows#1638]
我正在使用ss4.0.6，系统提示我可以升级到4.0.7，我点了升级，系统自动下载了4.0.7的zip包下来
打开4.0.7，发现各种代理信息都需要重新填写，为什么不能直接由4.0.6升级到4.0.7呢？这样手动好麻烦啊。

**Comment by publig** [comment]
在你的4.0.6的文件夹下应该有个json文件 把那个文件拖到4.0.7下应该就行了

**Comment by lingshow** [comment]
再请教一下ls，有好几个json文件，复制哪一个呢？
有user-wininet.json
statistics-config.json
gui-config.json
谢谢。

**Comment by publig** [comment]
gui-config.json 应该是这个吧 我现在用的是十分老的版本，没有上面两个json
我可以晚上帮你测一下

**Comment by celeron533** [comment]
zip包解压后覆盖原先的exe即可

**Comment by rebiu** [comment]
保留 gui-config.json 就可以了，这个是记录用户信息的
