### ISSUE TITLE
一周被封3次，有什么好的替代品吗？

### ISSUE THREAD

**Issue by google9002** [shadowsocks/shadowsocks-windows#1639]
最好同样是开源的
ss用了一年零8个月都没出问题，结果最近一周连续被封3次（1次被封端口，算我自己作的用的8388端口；1次被短时间封IP，目前已解封；1次大概是永久被封IP了，目前4、5天了国内依然ping不通vps的IP），加密方式一直是aes-256-cfb，用的搬瓦工的最便宜的vps，不支持据说更安全的gcm加密
听说ssr更不容易被封，但是转了一圈发现似乎并不是这样，现在有点慌

**Comment by lickety** [comment]
为什么会被封?

**Comment by chenshaoju** [comment]
建议更新服务端以启用gcm算法，另外你可以尝试加一个Simple-obfs： https://github.com/shadowsocks/simple-obfs ，这个比较复杂，你需要自己研究。

**Comment by google9002** [comment]
@chenshaoju 请问能求一个更新服务器的命令吗？我网上找到的ss服务器端的安装命令似乎都是Python版的2.8.2，谢谢

**Comment by chenshaoju** [comment]
如果你的是通过 pip 安装的话，不支持的，你需要使用源码包，具体参考： https://github.com/shadowsocks/shadowsocks/issues/1097

**Comment by google9002** [comment]
@chenshaoju 太感谢了，我尝试一下！
