### ISSUE TITLE
路由器部署之后电脑网线直连可以用wifi下的设备用不了

### ISSUE THREAD

**Issue by shenzhenhan** [shadowsocks/shadowsocks-windows#1641]
固件是老毛子

**Comment by networkthroughput** [comment]
你路由器的问题,检查你的路由器设置

**Comment by chenshaoju** [comment]
你好，如果你是在路由器上部署的SS，请与你的SS软件包或者教程作者联系以获得帮助。

这儿是 For Windows 的，完全是两个东西。

**Comment by shenzhenhan** [comment]
谢谢老哥

2018年1月26日 09:32，"Chen Shaoju" <notifications@github.com>写道：
