### ISSUE TITLE
Probable GPL violation of ss-win. 

### ISSUE THREAD

**Issue by ReVanTis** [shadowsocks/shadowsocks-windows#1642]
I found a newly released software on Steam yesterday and the reviews shows it's probably a GPL-violation to ss-win. 
I'm really no expert so correct me if I'm wrong. 

Tower Accelerator: 
http://store.steampowered.com/app/758670/Tower_Accelerator/
http://tower-accelerator.leanapp.cn

Review: 
http://steamcommunity.com/id/fylab/recommended/758670/

Author response:
http://steamcommunity.com/app/758670/discussions/0/1692659769949273158/

I haven't bought or studied into it yet but depending on how the author uses the code/binary they should either be releasing source code of this software or at least indicates ss-win github link in the release if only ss binary is called. 

Anyone already bought it or simply would like to take a look into this?

**Comment by celeron533** [comment]
Thanks for reporting

**Comment by wongsyrone** [comment]
Can anyone post its executable?

**Comment by celeron533** [comment]
>Can anyone post its executable?

I am in office now and not able to login to Steam. However, from the review comment...
![image](https://user-images.githubusercontent.com/3608762/35421925-dbedcd6a-0280-11e8-9376-6156485879c7.png)

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/35443426-00e402c8-02e6-11e8-9bc7-20c549d29049.png)

**Comment by celeron533** [comment]
@wongsyrone 
[TowerAccelerator.zip](https://github.com/shadowsocks/shadowsocks-windows/files/1669711/TowerAccelerator.zip)

系统托盘鼠标点击中键能显示log

**Comment by antigravities** [comment]
Tower Accelerator has been removed from the Steam Store.

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/35713119-9f7c1dca-0800-11e8-8788-297d2288a5a4.png)

**Comment by ReVanTis** [comment]
In case you want to follow up, 
Tower Accelerator author has moved to: 
http://tower-accelerator.leanapp.cn
after get removed from Steam.

**Comment by ReVanTis** [comment]
Hah, I got banned on his community. 

You have been permanently banned from all Tower Accelerator discussions.
You were banned by a Tower Accelerator developer.
Reason: "恶意用户"
