### ISSUE TITLE
又碰到新状况了：win7系统ss+kcptun的配置，pac模式，墙外流畅，墙内反而巨慢了。

### ISSUE THREAD

**Issue by yelosheng** [shadowsocks/shadowsocks-windows#1645]
标题描述的翻墙方案我已经用了有大半年了，一直很好；这几天出现了上述的诡异情况：访问墙外网站非常流畅，YouTube看1080p没有压力，可是访问墙内的网站却非常吃力，有时候打开百度都要等好久。

**Comment by chenshaoju** [comment]
没看懂，为什么你要通过SS访问百度？

**Comment by yelosheng** [comment]
是我公网的IP地址。
我选的pac模式，理论上访问百度淘宝等是不走ss的。可这就是问题诡异之处。

**Comment by chenshaoju** [comment]
请做一个测试，在关闭SS，但是开启ktcp的情况下，网速是否正常？

然后，关闭SS并关闭ktcp的情况下，网速是否正常？

**Comment by yelosheng** [comment]
经排查，好像是因为安装了“Backup and Sync for Google Photos and Google Drive”的缘故，把它卸载后好像就恢复正常了。卸载后使用了一个小时没有问题，重新安装Backup and Sync for Google Photos and Google Drive后问题重现。
不知道为什么，不过google的软件向来比较霸道，和苹果一样不尊重用户，所以嫌疑的确是比较大的。

**Comment by chenshaoju** [comment]
比较怀疑。。。我也在用这个，但是没这个问题。。。。

**Comment by nizongdai** [comment]
你tracert一下是不是就可以了，看看当你访问百度的时候，是怎么走的。
