### ISSUE TITLE
我这边编译Android项目提示缺少部分C代码，make: *** No rule to make target `D:/shadowsocks-android-4.4.5/core/src/main/jni/pcre/dist/pcre_byte_order.c

### ISSUE THREAD

**Issue by juwusheng** [shadowsocks/shadowsocks-windows#1646]
make: *** No rule to make target `D:/shadowsocks-android-4.4.5/core/src/main/jni/pcre/dist/pcre_byte_order.c', needed by `D:/shadowsocks-android-4.4.5/core/build/intuermediates/ndkBuild/debug/obj/mlocal/x86/objs-debug/pcre/pcre/dist/pcre_byte_order.o'.  Stop.
/libsodiu
，楼主能不能把Android项目core/jni/pcre缺少的文件上传上去

**Comment by CNMan** [comment]
Android项目在这里
https://github.com/shadowsocks/shadowsocks-android

**Comment by juwusheng** [comment]
Android项目core库中jni/pcre文件下文件找不到
![qq 20180127102930](https://user-images.githubusercontent.com/18287999/35467730-48a06f18-034d-11e8-816c-4056c252934e.png)

**Comment by chenshaoju** [comment]
这个Issue是for Windows的，请移步二楼提供的地址。

这是两个完全不同的东西，发在这儿很有可能得不到解决。

**Comment by celeron533** [comment]
@juwusheng 你图中圈出的文件夹实际上引用了另一个git项目，你可以在网上搜索`git submodules`来了解详情
另外这里是windows端~~
