### ISSUE TITLE
建议引入ssr的 “服务器连接统计” 功能，加入一键测试更好

### ISSUE THREAD

**Issue by Justsoos** [shadowsocks/shadowsocks-windows#1647]
各位抱歉，违个小规，希望能给使用 ss 的用户带来方便和实惠。
之前发到了2016年这个close的issue里，https://github.com/shadowsocks/shadowsocks-windows/issues/768#issuecomment-360973221
可能没啥人看到，新开一个open的如下：

虽然现在破娃 @breakwa11 也退隐了，但酸酸乳的windows客户端上 “服务器连接统计” 这个东西真是太有用了。

比如，我在这里提出的这个用法，用来测试账号和查看使用状态：
https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/33#issuecomment-355440457

**目前用ss的服务账号，在ssr上基本不通用了，也就是说，用ssr 客户端来批量测试ss 的账号，监测状态不现实了，希望 ss 的作者能引入这个功能到 ss 客户端上来**，让使用者一目了然看到自己那些服务账号可用，丢包，延迟，…… 等等一系列有效信息。

更进一步，如果能做出来一键测试，那就更好了。在我用ssr过程里，这个功能太重要了。一目了然，而现在ss客户端，完全眼前一团黑，什么数据都未知的。

发一个图片，你感觉一下，拥有上百ssr账号，如何挑选出一个好用的也是个难题（绝非臭显） …… 并且随时能查看自己科学上网的科学数据，这些账号可能几个小时前还可用，但突然就连接错误（被GFW了）或者空连（端口可能掉了）…… 总之，这些数据在 shadowsocks 里用户一无所知。顺便说，延迟84的和330的，使用体验天差地别：

![0099snap](https://user-images.githubusercontent.com/3480043/35470827-6c3fa1ee-038b-11e8-98ce-61f9f6ab1dd5.png)

**Comment by celeron533** [comment]
测速可能会产生流量特征

**Comment by Justsoos** [comment]
最起码，让用户一目了然这么清晰的连接状态数据，历史数据，并能够因此做出主动决策，这还不够因食废噎吗？

**Comment by rainbowcandy** [comment]
不同意加这个，昨天大面积封的美东和新加坡的机器几乎全是SSR+复杂混淆，SS的机器很多用rc4加密的都没事，现在SSR里面所有的可疑机制最好全都不要加

**Comment by Justsoos** [comment]
> @rainbowcandy 不同意加这个，昨天大面积封的美东和新加坡的机器几乎全是SSR+复杂混淆，SS的机器很多用rc4加密的都没事，现在SSR里面所有的可疑机制最好全都不要加

这是相当纯真的 迫害后应激神经过敏 + 无逻辑无证据乱推锅 吧。封不封ssr 某些机场，和用户是否能拿到详实的数据有一毛钱关系吗？

**Comment by rainbowcandy** [comment]
不知道你有什么证据证明我无逻辑乱甩锅，这是昨天大型vps出租交易论坛近千人的滞后公开结果的不记名投票的结论，我觉得比你直接在这那嘴说说要更有逻辑



发自我的小米手机
在 Justsoos <notifications@github.com>，2018年1月28日 12:22写道：

@rainbowcandy<https://github.com/rainbowcandy> 不同意加这个，昨天大面积封的美东和新加坡的机器几乎全是SSR+复杂混淆，SS的机器很多用rc4加密的都没事，现在SSR里面所有的可疑机制最好全都不要加

这是相当纯真的 迫害后应激神经过敏 + 无逻辑无证据乱推锅 吧。封不封ssr 某些机场，和用户是否能拿到详实的数据有一毛钱关系吗？

**Comment by Justsoos** [comment]
@rainbowcandy  您的陈腐的酸臭味真是让我不惊讶，shadowsocks 做到现在，我都懒得打开，因为根本没有足够的数据让我知道，我应该选择那个服务器账号来使用。而 “负载均衡” 引发的诸如 google 人机检测，频繁换 IP 出现的各种后遗症都没法解决。

以至于，你又拿出来一个不着四六的投票来证明 “SSR 可疑的东西都不要加进来”，用来暗示证明 SSR 的不妥甚至肮脏。

大型机场单 IP 同时服务数百用户，本身就是最大的GFW抓模式，封 IP 证据的推动力，几千小白用户所谓不知背后四六五的投票，与协议和SSR 与SS 加密之争有一毛钱逻辑关系？你拿这种证据来驳斥用户需要更详细服务信息的需求，这之间，您用过脑子吗？还是您脑子里一直的 阶级斗争 都用来与人 （ss 与ssr 的政治斗争）斗其乐无穷了？？

您的发言，就是个笑话

**Comment by rainbowcandy** [comment]
你tm有病？我就发表自己的意见，你怎么跟踩尾巴似的满嘴喷粪？俩软件还出来阶级斗争了？文革被迫害的神经病也跑到github上了？



发自我的小米手机
在 Justsoos <notifications@github.com>，2018年1月28日 12:38写道：

@rainbowcandy<https://github.com/rainbowcandy> 您的陈腐的酸臭味真是让我不惊讶，shadowsocks 做到现在，我都懒得打开，因为根本没有足够的数据让我知道，我应该选择那个服务器账号来使用。而 “负载均衡” 引发的诸如 google 人机检测，频繁换 IP 出现的各种后遗症都没法解决。

以至于，你又拿出来一个不着四六的投票来证明 “SSR 可疑的东西都不要加进来”，用来暗示证明 SSR 的不妥甚至肮脏。

大型机场单 IP 同时服务数百用户，本身就是最大的GFW抓模式，封 IP 证据的推动力，几千小白用户所谓不知背后四六五的投票，与协议和SSR 与SS 加密之争有一毛钱逻辑关系？你拿这种证据来驳斥用户需要更详细服务信息的需求，这之间，您用过脑子吗？还是您脑子里一直的 阶级斗争 都用来与人 （ss 与ssr 的政治斗争）斗其乐无穷了？？

您的发言，就是个笑话

**Comment by Justsoos** [comment]
抱残守缺，对好东西，优秀的产品功能，动辄施以政治斗争暗示，进行排斥，搞小白投票来迫害异己，这种开发社区的流氓文化，十足的有病！！
您不过是这种文化下一个个体毒瘤，谢谢您的表演。精彩！ @rainbowcandy

**Comment by chenshaoju** [comment]
这个讨论已经离题了。

实际上，早在2016年，有人提交过这方面的代码： https://github.com/shadowsocks/shadowsocks-windows/pull/447

但是，这引起了两个问题：
１.流量特征：从Wa11的角度，如果某个IP的流量类型不明，而且总是有固定的流量（通过下载某个文件来测速），那么很高的可能性会被识别。如果是Ping，可能会提升一点难度，但是来源IP的Ping＋不明流量本身就是一种特征，而且某些SS/SSR服务出于安全考虑，是禁Ping的。

２.流量消耗：大部分的SS/SSR服务都是按流量包月的，比如每个月20GB，如果要保证使用流畅，那么测试间隔就会比较短（５分钟一次？），流量消耗就会比较大（小文件难以测试出性能），假设１０分钟测试一次，每次消耗500KB，那么一天就是将近70MB流量，一个月下来会消耗掉2GB（10%）。

所以，这就是为什么在 https://github.com/shadowsocks/shadowsocks-windows/issues/768 中，直接建议用户使用高可用性模式以及 PingInfoView 手动测试。

BTW，SS/SSR都是开源的，如果你有特定需求，也可以自己加功能，制作你自己的专版SS/SSR。

**Comment by Justsoos** [comment]
如果你有深入疑问，请忘记测速这个功能，**把 “服务器连接统计” 功能作为本贴主题**。

至于用户是不是拿这个功能去作测速，是用户的权力。

说到如何测试会导致被GFW，完全是你自己定义的前提，如何消耗流量，如何产生特征。这些都可以通过小技术细节规避，比如 www.google.com 302之前的页面，根本不到1K，完全可以用来作测试，乱序轮询 amazon，fb，twitter的某些跳转页面，都是短小页面，也可以规避模式识别。如此简单的东西，你不想做可以说不作，不要拿GFW 来当背锅侠，这其中没有逻辑关系。

另外，我说一下我的 SSR 用法，我每天开电脑，测一次，一个服务器轮询2-3次，访问的是超短网页（小于1k），不曝光具体 URL，避免广告嫌疑（你可以猜想是google 302跳转之前的小页面），总共也用不掉500k，每个ssr 账号根本用不掉20k，但出来的数据足够我这一天选择参考，也能让我清除的知道那些账户是被G了，那些是流量耗尽，那些是端口掉了，这些信息你能让用户清楚明白的知道吗？

另外，我现在根本不想用 shadowsocks-windows，面对一个毫无数据依赖的界面，有50个服务器账号又有个毛线用？？根本没有参考数据可选。

而更多用户遇到问题，比如端口掉了（空连），被短暂G了（连接错误），太多细节，shadowsocks-windows 相比 SSR 根本就是原始软件。

另外，制作这个功能，需要引入 dotNet，至少 SSR 是这样作的，是不是 shadowsocks-windows 没这个能力，我不好说，但的确是不小的工程。

再再次，如果本开发社区文化就是这么流氓的话，我也懒得再说一句。让你们继续抱残守缺去吧。

再另外，不是为了能造福最多用户，我根本就不会在此发帖。面对一个灰突突的 shadowsocks-windows 毫无可参考信息的界面。我根本不想用这个软件。如果算沉默的大多数的投票，很多用户会用脚投票，转投SSR 

看图，和首贴对比，落后了两个时代的软件，有什么好自豪的？
![0100snap](https://user-images.githubusercontent.com/3480043/35479461-211000f8-0433-11e8-98f0-3ae017061483.png)

**Comment by Justsoos** [comment]
陈少举？ 换头像了没认出来。。。。

**Comment by Justsoos** [comment]
说一下，我前天打开已经一年不用的 shadowsocks-windows ，放进去50个账户，但根本不知道那个是能用的，那个是高带宽可以 u2b 的，那个是时延低可以 game 的。用着用着就卡了，丢包了，但只能通过我肉身上网来测试，，，，？

让我一个一个去肉身测试？别闹了，浪费生命好么，幸好有 SSR 这样更优秀的竞争者！还可以知道什么是更优秀的！

我本来不想批评 ss 抱残守缺，但有流氓跳出来暗示什么 “SSR那些可疑东西”，好丑陋的嘴脸，找打！
歇歇吧！

**Comment by chenshaoju** [comment]
对，是我，但是我没参与这个开发。[二哈]

SS设计的目的就是轻量，尽量不实现SS以外的功能，太多的功能会导致各种问题，比如状态统计，已经是dead code了。现在以至于混淆(simple-obfs)和加速(ktcp)都是以插件的形式实现的。

所以与其加入这些功能，不如购买一个好一点的SS服务或者搭建一个国内转发节点。

PS：如果你是自己购买／搭建的这５０个服务器，那你真是厉害。如果你用的是免费的，那么免费的本身就不可靠，也谈不上稳定，这点不能甩锅给SS。

**Comment by Justsoos** [comment]
现在很多大机场就提供50个节点，世界各地都有，订阅后自己选节点。这已经是行业标准了吧。买三个大机场的账号，就有100多节点可用了…… （选择困难症，和用订阅的小白们，会用 ss 么？根本不会）

另外，如果你要反馈某些节点问题，对于普通用户来说，ss 毫无数据支持，或许有少的可怜的历史 log，复杂度和可见度，拿出来根本不顶用，反而造成更多的交流障碍。
普通用户如何评估那个 ss/ssr 服务是好的，那个是坏的？数据呢？难道都靠臆测？凭手感吗？
很多机场节点都会有短暂失连等复杂问题，如何反馈给机场这些问题？
或者说，你一个用户如何暂停这个节点，去选另外一个节点？
不客气的说，用 ss 根本就是在瞎蒙。。。

面对无数据，无订阅的 ss 如此落后来说，凭啥不学习 ssr 呢？

**Comment by chenshaoju** [comment]
关于功能，上一个回复已经说了。

对于你的情况，其实你没有必要一股脑的将你服务商的SS服务器都导入SS里。

我建议你在当前网络将你的服务器列表导入 PingInfoView ，然后将速度最快的一个服务器单独加入SS里，如果你感觉不稳定了，就再看一下 PingInfoView ，并将新的稳定服务器加入SS，差不多有３～５个服务器的时候，针对你的网络的，比较稳定线路就筛选出来了。

这个时候，你就可以选择高可用模式。

**Comment by Justsoos** [comment]
你说的我基本都测过，我作python脚本用过 ping，tcping，hping，connect，stun ……，但都没有 ssr 这个连接统计来的内容详实有效，深入反馈ssr 协议内的握手和连接错误，以及流量，历史，用前者测，都还差1-2层网络协议层次呢。

而更方便的是，在 ssr 统计窗口上就可以直接排序、选用、禁用、复制链接共享给朋友，或者自己备份下来。这些都不涉及是否会增加GFW识别模式的问题，大大方便了普通用户的使用。

或者说，没有这个功能，我就绝不会用 ssr 了。就像现在，我又把 ss 扔一边，再不想用了。哈哈，我就不宣传了，省的你们说我来做广告。哈哈哈。

另外，现在真的几乎没有机场用ss了，我找到的都是骨灰了。从订阅到使用，到计费计量，到部署，沉迷轻量级的 ss 至少在功能和尊重用户上落后3年，太不友好了！！如果现在还有人用 SSR 几千人投票说协议被G，那一点不奇怪，因为根本没有优秀的机场还在用 ss 了。

**Comment by chenshaoju** [comment]
这个只能说各取所需，有些服务商认为SSR好，有些人为SS好。

**Comment by networkthroughput** [comment]
你说的"好用"的ssr在几天前都被墙了,只剩下ss存货.别跟个小屁孩一样"你这个东西不好用，老子再也不用了"打滚撒泼,你觉得不好你来改,大家写的免费的东西没人逼着你用.
talk is cheap, show me the code.
爱玩玩不完滚

**Comment by Justsoos** [comment]
> @networkthroughput  你说的"好用"的ssr在几天前都被墙了,只剩下ss存货.别跟个小屁孩一样"你这个东西不好用，老子再也不用了"打滚撒泼,你觉得不好你来改,大家写的免费的东西没人逼着你用.
> talk is cheap, show me the code.
> 爱玩玩不完滚

您这种国产特色流氓，我见多了。可惜啊，我给朋友测 ss 账号，我犯得着告诉你这些事儿吗？ 老子ssr 有几百可用节点，我是看不过去 ss 曾经是我最常用 fq 软件，现在堕落成这样落后，才来发帖，希望让更多用户受益的。

您这种中国特色屌丝流氓，对我来说，算个屁。

**Comment by Justsoos** [comment]
哈哈哈，如此来说，乔布斯也要给理中客让路了。看来用户需求就是个屁啊，可以毫不用尊重。
说个题外话例子，有机场技术和我讲，v2ray 实在对机场友好度为负数，其协议会把一个下载1G文件的代理访问链接直接 download 到服务器内存里来…… 流量直接爆掉。我就不说 ss 有多少不友好了，有很多人说过了。 @chenshaoju

**Comment by Justsoos** [comment]
我去看了下 PingInfoView  如果只是一个 icmp 探测，这东西基本没啥用。ss/ssr 服务节点的上下行速率和丢包信息，50%都探测不出来，它完全不是 inbound 代理测试工具。看到这里我身上一冷，连混迹 ss 社区如此深入的陈少举都只能给出这样的粗陋解决办法 …… 还是证明 ssr 这功能太牛逼了 @chenshaoju

**Comment by chenshaoju** [comment]
是的， PingInfoView 如名字所示，只是一个Ping工具，只能作为初级的网络检测使用。

我比较懒，只会使用Windows下的图形化的工具。

如果是TCP连接状态，除开付费的HostMonitor，暂时还没找到比较好的批量检测工具。

但是对于普通用户的大多数情况，Ping的信息已经足够了解当前到服务器的网络质量了。

**Comment by Justsoos** [comment]
你又懒，又只会用图形工具，看了我这贴后，还不转投 ssr 成为用户了？ （手动笑晕，哈哈

在 ssr 这个工具上，我经常可以用 u2b 来看到最高流量飙到多少M来判断服务器线路优劣。用最低延迟排序找网页浏览最舒服的节点。 那，用起来真是舒服，太舒服！

**Comment by chenshaoju** [comment]
我只能说SS能满足我目前的性能需求，介于安全性、速度和便利性的一个平衡点上，没有换的动力（因为懒），而你所说的速度，关键还是看你所使用的服务器线路是否好。

![screenshot](https://user-images.githubusercontent.com/515763/35480370-845fbee6-0447-11e8-80e3-3cf544e7a982.png)

**Comment by likesoap** [comment]
A：提议这样这样，
作者：不考虑

结论：讨论完毕，这贴可以关了。

**Comment by networkthroughput** [comment]
我倒是看出来了,二楼的作者不同意,于是陈少举在给你查issue历史,给你提供其他的办法,你不接受,B个不停,还反过来讽刺给你提供办法的人.
你自己去看issue列表,10个问题9个是他解决的,你做了什么?喷?讽刺?
呵呵

**Comment by Justsoos** [comment]
@chenshaoju  没什么奇怪，3年前我也像你这么用 ss，因为没什么数据可看，换节点也麻烦的要命。但这一年我用 ssr 后，已经让 ss 彻底退休了。没见过好东西，就推说是尊重传统，这不是啥时髦的人类行为怪癖。哈哈

另外，楼上流氓 @networkthroughput 请你不要在这放屁，我本贴提议两个：
1，设置服务器节点统计信息给用户
2，设计一键测速

陈少举只是给出一键测速有可能带来GFW模式识别，并没有证明给用户详细统计信息有什么问题。你这样歪曲事实，我只能用放屁来形容你的文字。

**Comment by Justsoos** [comment]
> @rainbowcandy 不同意加这个，昨天大面积封的美东和新加坡的机器几乎全是SSR+复杂混淆，SS的机器很多用rc4加密的都没事，现在SSR里面所有的可疑机制最好全都不要加

我再补充一下，已经有机场老板和我证明，最近有人卧底大机场，买小号订阅后举报全部 IP，此人狗屁逻辑不通，用什么小白投票来证明 SSR 里有可疑的机制。比造谣还要恶劣。

更何况，设置一个 “服务器节点统计信息”功能，与 SSR 被封有个毛线逻辑关系？纯粹是利用 ss ssr 社区不良政治斗争文化，打压他人的流氓行为！

**Comment by networkthroughput** [comment]
那你就用你的ssr呗,反正breakwall也收手不干了,现在ss的人冒着被人间蒸发的风险在这里给所有人免费开发软件,解决问题,提供办法,你说一大堆然后说满足不了你的要求撒手不用了几个意思?
最早期的ss还是记事本手动写配置,在dos里敲命令启动,怎么没人BB?
免费的东西,没人逼你用,爱用用不用滚,少BB.

**Comment by Justsoos** [comment]
> @networkthroughput 那你就用你的ssr呗,反正breakwall也收手不干了,现在ss的人冒着被人间蒸发的风险在这里给所有人免费开发软件,解决问题,提供办法,你说一大堆然后说满足不了你的要求撒手不用了几个意思?
> 最早期的ss还是记事本手动写配置,在dos里敲命令启动,怎么没人BB?
> 免费的东西,没人逼你用,爱用用不用滚,少BB.

你可以耍流氓，我也可以曝光你。没什么，想让我滚，你没那个资格。中国特色屌丝臭流氓

**Comment by chenshaoju** [comment]
我也觉得没有什么必要讨论下去了，就此打住把。

毕竟Issue是提出问题的地方，不是吵架的地方。

**Comment by yoyoyoooooooo** [comment]
多个代码贡献者都认为这个需求没什么必要，你要就自己pull代码，写代码又不是公益活动，为什么要被你骂几句就花上几十个小时写代码、测试，这时间去赚钱不好么？
如果你认为有用户需求的，你可以fork一个分支出去满足你的需求
目前代码满足安全性是唯一要求
满口脏话不断，这是社区，不是骂街的地方

**Comment by newcoderlife** [comment]
不赞成加入此功能。我认为与代理用户流量无关的流量都要尽量避免。

**Comment by XinoAssassin** [comment]
很简单的事情，Shadowsocks-Windows 本身就是开源的。你想加什么功能而开发者不同意，最简单的就是自己 fork 出来自己写。
没必要扯半天 Shadowsocks-Windows 与 ShadowsocksR-Windows 哪个更好。
我恰恰就是因为 ShadowsocksR-Windows 的多余功能太多而返回来用原版的反例。

**Comment by Justsoos** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1649
这是一个识货的。为你点赞 @WordlessEcho

**Comment by Justsoos** [comment]
在为一个开源社区 contribute 选择之前，一定要考虑其文化和价值感的认同与否。
本贴并不只是一个功能建议贴，更是一个社区文化钓鱼贴。
完全不出意料，抱残守缺者总有理由，而核心开发者的潜规则政治正确态度，又会感染强化旗下的流氓粉丝冲锋陷阵，制造矛盾。
SS和SSR的历史纠葛确实与此有关，但不可否认，抱残守缺文化更甚。
中国流氓化社会潜规则，更甚。
@chenshaoju @WordlessEcho

**Comment by SilverBut** [comment]
事情很简单。
Justsoos：我希望加个流量统计功能
chenshaoju：不加
WordlessEcho：不加
XinoAssassin：不加
…………
众人：不加

然后author就开始撒泼打滚。
已经离题成这样，建议@chenshaoju 把这个issue关掉吧，技术问题上另一贴讨论去。
author你如果觉得需要加的话自己fork一份自己加，记得遵守GPL。

**Comment by chenshaoju** [comment]
@SilverBut 我没有这个仓库的权限，也不想要权限。。。

另外，我没钦定过不加这个功能，我也控制不了这个仓库，只是看到讨论离题到一定阶段后告知历史原因和其他方案。

就这样。

**Comment by celeron533** [comment]
开源社区的诞生：80年代初`Richard Stallman`就是因为不满MIT人工智能实验室的各种系统使用限制（必须购买、仅限学校使用、不能随意分发、没有源码、不能自己修改）而发起了自由软件运动和开放源代码哲学，继而和`Linus Torvalds`等人搞出了Linux。
开源社区的原则：很简单，在遵守开源协议的框架下，你可以随意修改别人的代码，增减自己喜欢的功能。一切都是自由的。因此才有了现在百家争鸣、百花齐放的景象。
开源项目：很多开源项目成长于活跃的社区讨论，这是再正常不过的。但过激的言辞并不能增强说服别人的概率。

一直有人在争论SS和SSR，如同甜豆浆和咸豆浆之争。对，`breakwa11`觉得原版SS太简洁，甚至说是简陋，所以做了个多功能的带R增强版（后来也开源了）。这是在开源社区中再正常不过的现象：“既然原项目满足不了我，那我自己做一个呗”。

>Talk is cheap, show me the code.
Linus Torvalds



在座的各位不论是学生还是社会人，不论是不是这个项目的`contributor`，相信都是喜欢这个项目的，不然也不会来发言、围观。项目的`member`也只是维护者，并不意味着世界上只有他们可以写代码。世界上所有的人都有这个权力。

我们大家都自自己的生活、自己的工作、自己的时间。开发、维护这些软件正在消耗自己的业余时间，而且是公益性质，没有任何收入。单凭几个个体是无法支撑这个项目的，7x24小时有需求必应是不可能的。

心寒的是飞机场都在闷声大发财，但几乎没有向社区贡献过代码。似乎社区就是免费的苦力。从这个角度看，@justsoos 也是受害人之一。

抱歉写了这么多废话。希望社区里的各位都能以礼待人，少些无意义的争吵、多些技术性的讨论以及代码研究。

>Talk is cheap, show me the code.

**Comment by Justsoos** [comment]
@celeron533  说这些历史故事，我同意并认同。
问题是，本贴首贴其实还是个用户投票贴，所谓的本开发社群的开发者潜规则态度和流氓粉丝的攻击性表态，都在上面林林总总。

我的意思：
第一，一个已经完善了如此多用户贴心功能的SSR，和一个还远没有任何重视的SS，他们是近亲软件，同时摆在用户面前，拥有 show code 能力的懒人，我也是懒人，我会有动力去给SS写一个巨大的dotNet补丁吗？ 

第二，SS 与 SSR 之间并没有这种刚性二选一需求，而多个机场技术都说过，不选SS作服务，因为其对机场十分不友好，即没有订阅，也没有流量监控等多种 @breakwa11 破娃作的SS社区所谓 “多余无用的功能”。在过去一年半时间里，80%以上机场都投奔了SSR，不客气说，还在用SS作机场的恐怕都是玩票的吧。如果有这么多机场提供好用的懒人SSR服务，我作为一个用户，何必还要show code 给SS？

第三，把SSR的dotNet 代码搬家到SS来，一方面涉及可能破娃和ssr作者代码版权问题，一方面SS和SSR本来就是近亲，移植代码根本不是难事，只是这个态度问题。这就是我要说的，本社区的某些文化，阻止了这种 show code 的重要障碍。

第四，疯狂冲锋陷阵的流氓粉丝，上面好几位。有这种文化培养出来的社区，我为什么要去搬家SSR的code，来给流氓粉丝长脸？只有一位观众，@WordlessEcho  主动开了新帖子，表示这个功能我需要，是好东西。其他人都是什么态度？我只能用呵呵来形容

我既然不能说服、诱惑本社区用户和开发者，看到SSR的优秀功能而主动去学习，本贴义务就到此为止了。至于SS产业链里开发者无法得到补偿的问题，这是开源社区早就有的问题。太多人人已经说过多次，不敢接受捐赠，怕公开身份，人身危险。这并不能证明开机场的就是无人性的掠夺者商人吧。

呵呵，为什么你们不能拥有美好的东西？

**Comment by Justsoos** [comment]
补充一下，SSR dotNet 和数据统计代码不是我贡献的，我没有权力搬家过来show code，对于近亲SS和SSR来说，当要移植过来也不是难事，甚至说相当简单。

为什么SSR那边没有人作这事儿，这就是为啥不能拥有美好事物的原因 -- 看完本贴，可解，您的社区文化有毒啊

**Comment by chenshaoju** [comment]
准确的说，你有这个权利，SS是基于GPL协议的，基于SS的SSR也必须是GPL协议（详见： http://www.ruanyifeng.com/blog/2011/05/how_to_choose_free_software_licenses.html ）。

所以，任何人都可以将SSR的这部分代码复制过来进行优化并加入SS，只是没人这么做而已。（我不会写程序）

**Comment by XinoAssassin** [comment]
第一，您没有动力，本项目目前的主开发者也没有动力。结论：不加，有问题吗？
第二，本来就没有什么硬性二选一之分，ShadowsocksR 与 Shadowsocks 之间也不是完全不兼容，我可以用着服务端是由 ShadowsocksR 提供的服务而客户端选择 Shadowsocks, 选择权在用户手里不是吗？而机场选什么——机场是干什么的，他们要赚钱的，哪个更方便他们赚钱他们选哪个不是显而易见的吗？
第三，双方都遵循 GPL 协议的情况下，代码搬家不存在版权问题，何况直接搬肯定不行要改写挺多东西的。开源说白了就是抄来抄去，大家互相借鉴功能和代码共同发展。
第四，卜好意思，ShadowsocksR 的拥趸中也不乏如此“疯狂冲锋陷阵的流氓粉丝”吧。当年闹得沸沸扬扬的几个事件哪个背后不是被两派“疯狂冲锋陷阵的流氓粉丝”所推动着的呢？但这不是所谓的“社区文化”，从来就没有人承认过，而大部分人是中立和平的，请不要将这强加到 Shadowsocks 的使用者、贡献者、开发者头上来。
最后，您这全文一直在提的 `show code` 这个词，恐怕您没明白到底是让谁来 `show code`. 所谓的”美好的东西”也是相对的，您和大部分人都认为这些功能都是“美好的东西”，但这并不能让另外可能是少数人的我们也认为这是“美好的东西”。当然，我并没有贬低 ShadowsocksR 的意思，`breakwa11`的贡献也是有目共睹的。

**Comment by likesoap** [comment]
建议从 @rainbowcandy 第一次留言之后开始看，就知道谁是疯狗了。

**Comment by WordlessEcho** [comment]
Just stop arguing, please. @Justsoos you are requiring a feature, just keep issue clean and clear. **There is NOT a forum.** Move this topic to other place.

Shadowsocks and ShadowsocksR have different thoughs. Sometime you need to learn to enjoy its beauty or change it by code and discussion.

========================================

请各位不要吵了。 @Justsoos 你想要加一个功能，让 issue 简洁明了即可。**这里不是论坛。** 把这个话题转到别的地方讨论吧。

Shadowsocks 和 ShadowsocksR 有着各自不同思路，有时你只需要学会欣赏其美感，或者用代码及讨论来改变它。

**Comment by tickdock** [comment]
<html>
<body>

助你跨过GFW，来到自由世界！推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by qd678** [comment]
这 Justsoos 明显是个心智不成熟的小P孩，想要新功能自己去加，嚷嚷自己没动力，凭什么让别人给你加。
各位没必要再理会了，简直拉低下限。

**Comment by Jinpeiqi** [comment]
众人不愿加还在这里撒泼真是有意思。

**Comment by Justsoos** [comment]
我说的很清楚了，这是个钓鱼贴。
同时也是鄙视你们这个社区流氓文化的。
非常成功，钓出很多中国流氓。

**Comment by likesoap** [comment]
本来不想再关注这个贴了，不过说到流氓，建议大家看看从“rainbowcandy ” 回复第一帖开始看，就很清楚了。

**Comment by chenshaoju** [comment]
此Issue没必要继续回应下去了，Lock把。 @celeron533

**Comment by systemintegration759** [comment]
@Justsoos 摆着来要功能的,要不到于是厚着脸皮继续闹,钓什么鱼,扯什么流氓文化,还什么非常成功,你也是中国的,go fuck yourself.
