### ISSUE TITLE
[Feature Request] data statistics

### ISSUE THREAD

**Issue by WordlessEcho** [shadowsocks/shadowsocks-windows#1649]
Discussion in #1647 is chaotic, so I open a new issue to discuss.
@Justsoos request a ShadowsocksR-like feature called "data statistics" (image from @Justsoos):
![Image from the issue 1647](https://user-images.githubusercontent.com/3480043/35470827-6c3fa1ee-038b-11e8-98ce-61f9f6ab1dd5.png)

### Reason:
- Many Shadowsocks server have data restriction.
- It's hard to monitor data statistics and different the server from Shadowsocks by third-party tools.
- Shadowsocks Android also have a simple data statistics.
- Data statistics can analyze the server status easily, even in load balancing mode. Such as error and timeout.

So I think it's necessary to build in this feature into the Shadowsocks Windows.

**Comment by yoyoyoooooooo** [comment]
Compared with OBFS or TCP Fast Open, I don`t think it is a priority.
Ping feature would cause unnecessary security issue.
Total data statistic seem reasonable, but user usually use the shadowsocks in more than one device, it is impossible to compare the server limitation with the data statistic.
That is why this is a frequency request without implementation.

**Comment by galaxy001** [comment]
I think we can limit the test to upon user's click.
And it is also helpful to record the statistics during using a server. We may keep a history of last 3 days or so.

**Comment by SilverBut** [comment]
Can be a reasonable feature but need either:
1. a random delay between each detection
2. a manual detect trigger instead of a fixed one

Maybe for either ways, we need a relatively random content length to prevent more characteristics from being detected.

**Comment by XinoAssassin** [comment]
延迟这个问题能否直接利用 TCP 包的时间戳来实现，这样就不会引入新的安全问题

**Comment by celeron533** [comment]
Another point need to consider:
If a server requires plug-in, need to start plug-in before speedtest and shut down the plug-in after test.
