### ISSUE TITLE
安装好以后，还是上不了外网

### ISSUE THREAD

**Issue by zhaodamao** [shadowsocks/shadowsocks-windows#1650]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
请具体描述一下，你所使用的SS版本，并提供你的SS的日志信息等。

请记得掩盖掉日志里的服务器IP和端口信息。

**Comment by zhaodamao** [comment]
ss是最新版本，如下这是日志信息

图片上传不了，只能复制粘贴来了


[2018-01-29 15:03:50] Shadowsocks started
[2018-01-29 15:05:05] Shadowsocks started
[2018-01-29 15:05:17] System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
[2018-01-29 15:05:17] Shadowsocks started
[2018-01-29 15:06:03] Shadowsocks started
[2018-01-29 15:07:38] Shadowsocks started
[2018-01-29 15:07:44] Shadowsocks started
[2018-01-29 15:11:37] Shadowsocks started
[2018-01-29 15:11:43] Shadowsocks started
[2018-01-29 15:12:33] Shadowsocks started
[2018-01-29 15:16:34] Shadowsocks started
[2018-01-29 15:16:42] Shadowsocks started
[2018-01-29 15:17:22] Shadowsocks started
[2018-01-29 15:17:35] Shadowsocks started
[2018-01-29 15:17:38] Shadowsocks started
[2018-01-29 15:17:57] Shadowsocks started
[2018-01-29 15:18:00] Shadowsocks started
[2018-01-29 15:18:55] Shadowsocks started
[2018-01-29 15:21:16] Shadowsocks started
[2018-01-29 15:22:51] Shadowsocks started
[2018-01-29 15:26:33] Shadowsocks started
[2018-01-29 15:27:30] Shadowsocks started
[2018-01-29 15:30:14] Shadowsocks started
[2018-01-29 15:49:09] Shadowsocks started
[2018-01-29 16:04:55] Shadowsocks started
[2018-01-29 16:47:51] Shadowsocks started
[2018-01-31 09:19:37] Shadowsocks started
[2018-01-31 09:23:12] Shadowsocks started

**Comment by chenshaoju** [comment]
你有配置你的SS软件的服务器信息吗？如果SS软件的编辑服务器（双击任务栏托盘区的纸飞机小图标）里什么东西都没有的话，是无法使用的。

另外，请确保启用了系统代理，以及代理模式工作在PAC模式。

如果可能，请尝试更新GFWList看看：
![image](https://user-images.githubusercontent.com/515763/35602092-55abd9b4-0671-11e8-90af-b13278ea9e04.png)

**Comment by zhaodamao** [comment]
都有啊。。。都是正常的啊，就是上不了外网，怎么回事啊，，急急急
![qq 20180131103508](https://user-images.githubusercontent.com/22090129/35602302-9bcf1f22-0672-11e8-9fe7-af340269f9bf.png)
![qq 20180131103527](https://user-images.githubusercontent.com/22090129/35602303-9c0aa8d0-0672-11e8-97f3-ea8194b7b919.png)

**Comment by chenshaoju** [comment]
GFWList 呢？

另外，你用的什么浏览器？

**Comment by zhaodamao** [comment]
谷歌chrome浏览器

GFWList 刚才已经点击更新过，还是不行呢
![qq 20180131104128](https://user-images.githubusercontent.com/22090129/35602491-76c15f32-0673-11e8-8d4a-03b854db9ae9.png)

**Comment by chenshaoju** [comment]
尝试取消保护本地PAC看看。

另外，请确保你的Chrome没有代理插件控制，如果有，暂时禁用看看。

**Comment by zhaodamao** [comment]
取消了保护本地PAC。还是不行呢，我没有代理插件啊。因为没有vpn，chrome什么插件都没有下载安装啊。。。

**Comment by chenshaoju** [comment]
请看一下请看一下你的IE浏览器设置的这个地方，是什么样子。

PS：不要照着我的写，每个人可能不一样。

![image](https://user-images.githubusercontent.com/515763/35602709-bab2ec78-0674-11e8-8c1d-2f7fd3faf917.png)

**Comment by zhaodamao** [comment]
是这样子的。![image](https://user-images.githubusercontent.com/22090129/35602785-26111f58-0675-11e8-9067-a0ffdb6fff21.png)

**Comment by chenshaoju** [comment]
有什么东西阻碍了SS设置你的系统代理。

请尝试暂时退出所有可能的安全软件（３６０、QQ电脑管家等等等。。。），然后退出SS并重新打开SS再试。

**Comment by chenshaoju** [comment]
另外，你看起来使用的是一个非常旧的版本。

请尝试更新看看： https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by zhaodamao** [comment]
我更新过了，我没有打开任何的安全软件啊，，，，怎么办，，还是不行
![image](https://user-images.githubusercontent.com/22090129/35603192-1788da0a-0677-11e8-9f46-abb6e6cdc380.png)

**Comment by zhaodamao** [comment]
不是免费的

**Comment by chenshaoju** [comment]
基本上确定可能和你的系统有关，请尝试强制Chrome使用代理的方法看看：

右击Chrome的快捷方式，并在目标的末尾加上以下参数：
```
 --proxy-server="socks5://127.0.0.1:1080"
```
然后关闭所有的Chrome窗口，确保任务管理器没有chrome.exe的进程后，并再次启动Chrome后试试，你的Chrome会将所有网页流量经由SS。

效果类似下图：
![image](https://user-images.githubusercontent.com/515763/35603862-569c0728-067a-11e8-8f47-62666379dc4a.png)

如果还不行，请贴出SS日志里的内容。

**Comment by zhaodamao** [comment]
好了好了，万分感谢，还想问下，那对我开发不影响吧？？谢谢！~~

**Comment by chenshaoju** [comment]
这是针对Chrome的设置，目前你的Chrome所有流量都会经过SS，消耗可能会很高，而且访问国内网站可能会很慢。

你应该尽快安装一款Chrome的分流代理插件，（比如 https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif ），并尽快取消快捷方式中所加上的参数。

**Comment by zhaodamao** [comment]
如果我用免费的翻墙软件，也还是不能翻墙，该怎么办呢

**Comment by zhaodamao** [comment]
我打算重装系统了

**Comment by chenshaoju** [comment]
你需要手动配置 SwitchyOmega 以让你需要访问的地址经过SS，这个就超出该 Issue 的范围了，具体的请访问 https://github.com/FelisCatus/SwitchyOmega/wiki （右边的菜单）阅读教程。

**Comment by zhaodamao** [comment]
那我重装下系统是不是就不用这么麻烦了？

**Comment by chenshaoju** [comment]
如果你准备重装了，请先尝试该办法，如果仍然不行，很高的可能性是系统问题了：https://github.com/shadowsocks/shadowsocks-windows/issues/1487#issuecomment-340370635

由于错误提示不一样，我不确定是否真的是该问题导致的。

**Comment by zhaodamao** [comment]
可是你发的那个链接，教程我看不懂，不知道如何操作，哭~~~~

**Comment by chenshaoju** [comment]
先退出SS，然后点击开始菜单，选择程序或所有程序，指向附件，找到命令提示符后右击，选择以管理员身份运行。

然后复制文中的三条命令，并在命令提示符的窗口内右击，选择粘贴。

前两行命令会自动执行，第三行命令按一下回车即可。

然后再启动SS看看。

**Comment by zhaodamao** [comment]
弱弱的问一句，文中的三条命令在哪里~

**Comment by chenshaoju** [comment]
```
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable /t REG_DWORD /d 0 /f
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyServer /f
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyOverride /f
```

**Comment by njzhe91** [comment]
你好！我也遇到了类似的问题。重装系统后，下载了最新的SS 4.0.7，但是发现用Chrome无法翻墙。IE浏览器却翻墙正常，重装Chrome后问题依旧。请问是什么原因呢？

**Comment by chenshaoju** [comment]
请检查你的Chrome浏览器是否安装有某些代理插件，如果可能，进入 chrome://extensions 进行检查，如果不确定，请都禁用看看。

**Comment by njzhe91** [comment]
我的Chrome Extentions里只有Docs，禁用后依然不行

**Comment by chenshaoju** [comment]
如果IE可以的话，那就不应该，可能Chrome做了什么变化，我暂时无法确认（我用的是 Proxy SwitchyOmega ）。

**Comment by tickdock** [comment]
<html>
<body>

助你跨过GFW，来到自由世界！推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by cnhyk9527** [comment]
six

**Comment by Lunacyyyy** [comment]
弱弱的问。。不会怎么配置服务器。。。

**Comment by studentmain** [comment]
联系你的服务提供商。如果没有，去shadowsocks-libev下面学习自己搭一个

Lunacyyyy <notifications@github.com> 于 2018年4月24日周二 11:45写道：

**Comment by hybirdworld** [comment]
十分感谢，更新了本地PAC并取消了保护本地PAC就可以用了。重装系统之后直接用chrome插件了，怪不得ss一直用不了。

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history
