### ISSUE TITLE
如何保护本机IP地址

### ISSUE THREAD

**Issue by thatname** [shadowsocks/shadowsocks-windows#1651]
使用shadowsocks之后，用google搜索“IP”，会显示本机IP，显示的还是中国大陆的地址，并不是服务器所在地的IP。这怎么可能做到？按说发往google的报文IP头地址必然是服务器所在地址，否则服务器不可能收到google返回的报文。

使用shadowsocks如何保证匿名性呢？

**Comment by thelastlin** [comment]
请检查你的代理设置。
如果真要保证匿名性，还请使用Tor / I2P。

**Comment by celeron533** [comment]
如@thelastlin 所说，代理服务器并不一定能完全隐藏你的IP地址

**Comment by chenshaoju** [comment]
你好，请检查是否更新了GFWList，以及是否启用了系统代理。

![image](https://user-images.githubusercontent.com/515763/35602092-55abd9b4-0671-11e8-90af-b13278ea9e04.png)

**Comment by celeron533** [comment]
另外可以刷一下浏览器缓存。我自己测试看到的是服务器地址
