### ISSUE TITLE
在公司新安装的ss无法翻墙在线等

### ISSUE THREAD

**Issue by lw5885799** [shadowsocks/shadowsocks-windows#1653]
如题 开始配置报500internal proxy error  后来链接超时了

**Comment by lw5885799** [comment]
win10系统 4.07的ss

**Comment by chenshaoju** [comment]
日志中有什么显示吗？

**Comment by lw5885799** [comment]
已经解决了，在浏览器代理中加入http://127.0.0.1:1080/pac?t=XXXXXXXXXXXXXXX就好用了 谢谢
