### ISSUE TITLE
新版本shadowsocks不能用

### ISSUE THREAD

**Issue by amlearner** [shadowsocks/shadowsocks-windows#1654]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.7

### Environment(Operating system, .NET Framework, etc)

win 10      4.6.2
### Steps you have tried

ping通，改端口（1080→10800），删除重新安装，取消保护本地PAC，更新PAC，
### What did you expect to see?

能上谷歌
### What did you see instead?

谷歌上不了。老版本2.3的shadowsocks可以照常上谷歌。但是4.0.7 的不行。
### Config and error log in detail (with all sensitive info masked)

![image](https://user-images.githubusercontent.com/31589038/35695886-bfcdc53c-07c0-11e8-9582-82abf51edd77.png)
![image](https://user-images.githubusercontent.com/31589038/35695937-e436db66-07c0-11e8-9401-e7c0c792c2f5.png)
![image](https://user-images.githubusercontent.com/31589038/35696010-16eeaaa2-07c1-11e8-9969-5bdf808c8afc.png)

**Comment by celeron533** [comment]
删除`ss_win_temp`文件夹后重试

**Comment by amlearner** [comment]
删除ss_win_temp重新打开ss还是不行。重新打开ss之后在路径里又生成了ss_win_temp文件夹

**Comment by chenshaoju** [comment]
请尝试将 Shadowsocks.exe 放到一个新的，独立的目录中，比如 D:\SS\ 。

**Comment by amlearner** [comment]
可以啦！之后我尝试把D:\SS\ 路径的shadowsocks删除，只在原文件夹路径下有shadowsocks依然可以工作。。。。可是之前就不行，好奇怪。

**Comment by amlearner** [comment]
现在又不行了。。。玄学。。。
尝试：先在D:\Shadowsocks-4.0.7\路径运行Shadowsocks.exe，配置好服务器和PAC文件后，可以ping通，之后把Shadowsocks.exe文件剪切粘贴到D:\SS\路径，可以ping通。
结果：不能打开谷歌。

**Comment by chenshaoju** [comment]
SS的日志里有什么显示吗？

**Comment by amlearner** [comment]
![image](https://user-images.githubusercontent.com/31589038/35732180-77517e0a-0853-11e8-8b06-74810e820125.png)
日志信息很少，上面的信息是4.0.7版本的。ss_prixoxy.exe依然打不开。
2.3版本可以正常使用。
买的搬瓦工的VPS，搬瓦工服务器端的Shadowsocks是一键安装的，电脑上2.3版本的也是按照链接下载。
![image](https://user-images.githubusercontent.com/31589038/35732425-43eeaa96-0854-11e8-9f4e-b165733022a7.png)

**Comment by celeron533** [comment]
禁用杀毒软件

**Comment by amlearner** [comment]
杀毒软件早早的就关了。。。
更新版本主要是因为4.0-2.3不能更新PAC，所以我把4.0.7下载之后更新一下PAC，再把这个PAC文件和gui-config.json复制到4.0-2.3版本路径下。。。
我再试试看看4.0.6这样的版本可不可以

**Comment by chenshaoju** [comment]
如果可以，请将在本仓库Releases页面下载回来的 Shadowsocks-4.0.7.zip 里的 Shadowsocks 解压到一个新的，空目录里，不要覆盖 config.json ，手动重新配置一次看看。

另外，请确保在退出SS后，任务管理器里没有 Shadowsocks.exe 和 ss_prixoxy.exe 残留。
