### ISSUE TITLE
[E] decryption error

### ISSUE THREAD

**Issue by Weeker** [shadowsocks/shadowsocks-windows#1655]
版本 shadowsocks-libev 3.1.3

配置改为"plugin_opts":"obfs=http;failover=127.0.0.1:8080"，shadowsocks-windows 就报 [E] decryption error 错误，Surge 、Shadowrocket 都正常。

配置改为 "plugin_opts":"obfs=http"就没有任何问题

**Comment by chenshaoju** [comment]
客户端使用的是哪里的 obfs-local.exe ？

**Comment by Weeker** [comment]
shadowsocks-windows 4.0.7 不是支持混淆了吗？

**Comment by chenshaoju** [comment]
客户端默认不支持，你需要搭配 simple-obfs 使用，将 obfs-local.exe 放到 shadowsocks.exe 所在的目录才行： https://github.com/shadowsocks/shadowsocks-windows/issues/1368

**Comment by Weeker** [comment]
感谢少举
