### ISSUE TITLE
Shadowsocks non-UI Error - AbandonedMutexException

### ISSUE THREAD

**Issue by sitiger** [shadowsocks/shadowsocks-windows#1656]
System.Threading.AbandonedMutexException: 由于出现被放弃的mutex, 等待过程结束。
在System.Tthreading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millosecondsTimeou, Boolean hasThreadAffinity, Boolean exitContext)
在System.Tthreading.WaitHandle.WaitOne(Int32 millosecondsTimeou, Boolean exitContext)
在Shadowsocks.Program.Main()

发生多次，概率大概60%，即两次开机至少发生一次。
win10 1709

**Comment by chenshaoju** [comment]
请尝试使用 https://www.microsoft.com/en-us/download/details.aspx?id=30135 修复 .NET ，如果修复后仍然不行，请前往 https://www.microsoft.com/net/download/thank-you/net471 下载.NET 4.7.1并更新或修复。

**Comment by celeron533** [comment]
另外也有可能存在多个客户端同时启动的现象
