### ISSUE TITLE
The next step of running the program

### ISSUE THREAD

**Issue by NeilHu1994** [shadowsocks/shadowsocks-windows#1657]
I have already downloaded the program, When I run the program could you tell me the next step? I have no idea how to fill the blanks?
![image](https://user-images.githubusercontent.com/36002240/35737366-2f4125c6-0866-11e8-83e6-30e58436f776.png)

**Comment by NeilHu1994** [comment]
I'm not sure if I need to buy the server info? Please Help Me!!!

**Comment by NeilHu1994** [comment]
Anyone else?

**Comment by celeron533** [comment]
You need a server.

**Comment by NeilHu1994** [comment]
Thanks!  It **works** like magic now !!!!
