### ISSUE TITLE
shadowsocks能不能使用teredo ipv6通道？

### ISSUE THREAD

**Issue by styrenes** [shadowsocks/shadowsocks-windows#1658]
ipv4被封是迟早的事情。

**Comment by chenshaoju** [comment]
１.Shadowsocks for Windows 支持SS客户端到SS服务端的IPv6地址。
２.请确保你的客户端和服务器都具备IPv6地址。
３.能Ping通或者能访问到你的SS服务器。

测试截图：
![screenshot](https://user-images.githubusercontent.com/515763/35762444-c6e39114-08d1-11e8-8adb-73cf8a27a9c5.png)

**Comment by chenshaoju** [comment]
１.Shadowsocks for Windows 和 Simple-obfs 均支持SS客户端到SS服务端的IPv6地址。
２.请确保你的客户端和服务器都具备IPv6地址。
３.从客户端能使用IPv6地址Ping通（ping -6）或者能以其它方式（HTTP/HTTPS/SSH etc...）访问到你的SS服务器。

测试截图：
![screenshot](https://user-images.githubusercontent.com/515763/35762506-77b1a328-08d2-11e8-9cf5-5406e2455354.png)

**Comment by styrenes** [comment]
说了等于白说，
你就是搞反火墙的吧？发了这个贴，就把我ip封了

**Comment by systemintegration759** [comment]
嚯,这屎盆子来得快噢,他都不知道你的ip就把你封了,你是小学生吗?
他说的内容你有看吗?只要你ip6地址能通就行了,傻啦吧唧的,滚回去读你的语文课本把,别在这丢人现眼.

**Comment by chenshaoju** [comment]
Teredo IPv6 只是 IPv6 over IPv4 的形式之一，只要使用IPv6地址从你的从你的客户端到你的服务器能通就行，Teredo IPv6 是操作系统提供支持的，具体可访问 https://en.wikipedia.org/wiki/Teredo_tunneling 了解详情。

Shadowsocks for Windows 本身不能直接使用 Teredo IPv6 协议。

如果你是自己搭建的SS，不要使用默认端口，已知该端口被重点关照：https://github.com/shadowsocks/shadowsocks-windows/issues/1629

FTR，本人未在GFW或其相关单位供职。

请文明使用Issue列表，你发的内容有1600+的人会收到邮件。

**Comment by systemintegration759** [comment]
@chenshaoju 你就一佛系的,对人太好了,吃力不讨好,你得学linus上来就喷.
