### ISSUE TITLE
总是提示非法服务器地址

### ISSUE THREAD

**Issue by Berlain** [shadowsocks/shadowsocks-windows#1659]
请问为什么总是提示非法服务器地址？下载最新的4.0.7版本。

**Comment by chenshaoju** [comment]
请检查你输入的服务器地址是否含有为半角英文数字和英文句号以外的字符。

**Comment by Berlain** [comment]
没有的，我切换到英文输入法，一个字符一个字符输入，还是不行。这个地址应该就是我的VPS的服务器地址吧，密码就是文件里设置的密码吧？

**Comment by chenshaoju** [comment]
你输入的是IP地址吗？注意，没有引号或者其他的东西，你的服务器地址应该类似于：
```
aaaa.bbbb.com
```
或者：
```
123.45.67.89
```
这种格式。

**Comment by celeron533** [comment]
另外不需要输入诸如`http://`之类的协议头

**Comment by fabware** [comment]
被这个问题坑到了，作为一个"老手"还浪费不少时间。原因是填完服务器信息后没有立即点“确认”，而是点了“添加”（要不然为什么说自己是老手呢，有时候有些软件你不点添加，下次还得再输一遍），这时再点“确认”或服务器信息的时候就会出现“非法服务器地址”的问题。解决办法很简单，在选中“未配置的服务器”的状态下，点击“删除”，就可以了。

这是一个软件本身交互设计的问题。下面详细重现步骤和改进的建议：

重现的方法：
1、打开软件（现在左侧是“未配置的服务器”），在右侧“服务器”的表单中填入正确的服务器信息；
2、点击“添加”；
3、然后在左侧点击刚才输入的服务器（或者点“确认”），就会碰到“非法服务器地址”。

在这个时候，用户已经完全无法正常使用软件。当弹出“非法服务器地址”的时候，用户会以为是自己刚才输入的服务器地址不对，而没有注意到是“未配置的服务器”地址为空不对。

改进建议：
1、在用户切换到已经填好的服务器时，不要检查未对“未配置的服务器”的默认值做过任何修改的表单；
2、在用户已经填写了至少一个服务器的情况下，点击“确认”，不要检查未对“未配置的服务器”的默认值做过任何修改的表单。

非常感谢开发者的辛苦工作，也希望能对此做一些改进，帮到使用者也给自己省一些麻烦。

**Comment by chenshaoju** [comment]
这个流程可能需要优化一下，“添加”其实是指保留现有项目然后添加一个新的空白项目，有些用户可能理解成填写好了后点一下添加才能完成保存。

不过“完全用不了”也不太正确，只需要选中“未配置的服务器”，再点击“删除”即可。

**Comment by fabware** [comment]
“添加”用户理解为填写好了点一下添加才能保存，问题也是不大，这也是现在软件真实的行为。我说的“完全用不了”是指，用户没有发现这个问题就无法用。如果在添加时，立即修改了软件的配置文件，下次启动发现可以从这个错误中恢复，也算是个可行的方案。

另外一方面，在用户点击已添加的服务器的时候，确实是没有保存“未配置的服务器”的预期的，特别是用户没有在“未配置的服务器”里面填写东西。所以本身这个交互是有一些问题的。

至少可以做个简单的改动，把没填的错误改为“服务器地址不能为空”，估计这样至少不会认为自己输入的地址错了（因为这个错误我还跑去把密码的特殊字符给改了），而是忘了填了。
