### ISSUE TITLE
如何使用ss代理来访问内网的FTP、远程桌面

### ISSUE THREAD

**Issue by y6821552** [shadowsocks/shadowsocks-windows#1660]
目前网络情况如下：
客户有内网环境，提供一台windows服务器（A）可以提供外网访问，外网访问内网中的其他服务器只能通过远程A服务器来进行连接。目前我在A服务器中搭建了SS服务端，http请求内网其他服务器站点正常访问。现在想做到访问内网其他的FTP以及远程桌面也从SS服务端代理走，这样就不用先进内网远程A服务器，直接在本地进行操作。不知这个方法是否可行，请大神们指教！！万分感谢！

**Comment by chenshaoju** [comment]
你是想在外网通过A计算机访问A计算机所在的内网吗？

先决条件，服务器A有公网IP或者做了端口映射。

如果是的话，在服务器上搭建SS的服务端，客户端使用SS的客户端，然后使用第三方的FTP客户端，比如FileZilla，设置代理为 127.0.0.1 即可。

远程桌面的话，有一些第三方的客户端支持SOCKS5代理，具体请自行搜索 mstsc socks5 proxy 。

**Comment by y6821552** [comment]
@chenshaoju 感谢您的回复，服务器A中有端口映射可以从外网访问。我使用transmit进行访问ftp的，设置代理后依然是无法访问，请帮忙看下是否配置错误。如图：
![qq20180205-171444](https://user-images.githubusercontent.com/17564659/35796790-9ae8ab4e-0a98-11e8-9231-367635c1e1b5.png)
![qq20180205-171927](https://user-images.githubusercontent.com/17564659/35796821-bac9dbd6-0a98-11e8-8ffe-0081820df07c.png)
感谢您！

**Comment by chenshaoju** [comment]
我没有Mac，不知道。。。以FileZilla举例，你需要在软件里配置你的代理地址（我的是10800），并且单独在你的FTP连接里指定使用代理。

![image](https://user-images.githubusercontent.com/515763/35796958-28f7e620-0a99-11e8-87ee-6300d97fba97.png)

![image](https://user-images.githubusercontent.com/515763/35797010-4a5eefe8-0a99-11e8-9772-441b0b40e5af.png)

**Comment by y6821552** [comment]
@chenshaoju 多谢您的指导，已经能成功的连接FTP。
不过远程桌面还是没能找到解决方案，Google中大多是SSH连接的方式？我没有找到如何连接到Windows的方法。

**Comment by chenshaoju** [comment]
查了一下，有一个名为 CoRD http://cord.sourceforge.net 的开源Mac客户端可以实现，我没有Mac，你可以试试。

![cord-preferences-4](https://user-images.githubusercontent.com/515763/35840178-822821d8-0b2f-11e8-8fef-6b16e0baddb0.png)

**Comment by y6821552** [comment]
谢谢帮助，我现在试下。另外，还想请教下Windows自带的mstsc软件是否可以设置socks5代理呢？

**Comment by chenshaoju** [comment]
你可以试一下 sockscap32 或 Proxifier 看看。

**Comment by y6821552** [comment]
好的，非常感谢！

**Comment by ElegantLin** [comment]
你好，请问你ssr的客户端的内网IP是？

因为我现在也有一个类似的需求，我有一个阿里云的服务器（内网+公网），我希望用ssr帮我把电脑都加到一个内网的局域网里面，请问这样可以做吗？

谢谢解答

**Comment by y6821552** [comment]
我没有尝试把电脑加到局域网内，只是将内网服务器作一个通道去访问内网的其他服务。

**Comment by ElegantLin** [comment]
是的是的，谢谢你。

求问 @chenshaoju ssr可以实现这种需求吗？

谢谢！

**Comment by chenshaoju** [comment]
我从来没有这样用过……

**Comment by ElegantLin** [comment]
> 我从来没有这样用过……

好的好的，谢谢老哥。。。
