### ISSUE TITLE
shadowsocks-windows代码学习--自动更新

### ISSUE THREAD

**Issue by Evilrabbit520** [shadowsocks/shadowsocks-windows#1661]
请问一下各位shadowsocks开发者，shadowsocks是采取什么方式更新的？我学习C#现在想通过分析shadowsocks-windows客户端源代码进行学习，但是在shadowsocks的更新方面我完全没搞懂，只看到更新代码里面有一个更新用的URL，打开链接就是很多类似于更新日志的东西，麻烦各位帮我解答一下，谢谢啦！

**Comment by chenshaoju** [comment]
具体的代码实现位于 https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/UpdateChecker.cs ，而文中的更新地址，是Github提供的API所返回的JSON，你可以访问 https://developer.github.com/v3/repos/releases/ 了解关于该API的详情。

**Comment by Evilrabbit520** [comment]
emmmmmmm，我想请问一下我如果根据Github提供的API接口进行升级应该怎么操作？是需要将更新好的版本放在什么地方还是将他发布在某台服务器？

**Comment by Evilrabbit520** [comment]
emmmmmmm，我想请问一下我如果根据Github提供的API接口进行升级应该怎么操作？是需要将更新好的版本放在什么地方还是将他发布在某台服务器？

**Comment by celeron533** [comment]
在github上新建一个release

**Comment by Evilrabbit520** [comment]
嗯嗯，首先谢谢两位的解答，我建好了releases,那接下来发布新的版本客户端仍然没有提示或者说是检查更新，日志里面仍然显示找不到服务器，没法正常获取更新，这个模块一直很迷。
这里再次感谢各位的认真解答，谢谢啦！
![1](https://user-images.githubusercontent.com/25611476/35869588-63e9eeb6-0b9a-11e8-8dd6-07e25d6b52f3.png)

**Comment by Evilrabbit520** [comment]
会不会是因为我把路径改为了"Photon"?

**Comment by chenshaoju** [comment]
你访问 api.github.com 吗？

**Comment by celeron533** [comment]
log里有127.0.0.1
ss的更新过程需要经过ss服务器的，很明显在你本机上没有服务器程序

**Comment by wongsyrone** [comment]
大概流程

下载JSON串
加UA header，WebClient通过本地出去，本地listener有几个services，他们的关系是chain of responsibilities，流程是PortForwarder->Privoxy->TCPRelay->remote SS server
JSON反序列化获取JSON对象数组，每个对象一个release实体entity
版本号: entity.name
取得版本号之后排序检查最新版本，有几个实用方法是干这个的。
release实体对应的asset数组: entity.assets
因为一般只有一个asset: entity.assets[0]
下载链接: entity.assets[0].browser_download_url
链接给 DownloadFileAsync，异步完成之后触发CheckUpdateCompleted提示外部订阅者。

**Comment by Evilrabbit520** [comment]
好的好的，我可以试试，谢谢

**Comment by Evilrabbit520** [comment]
很不好意思，由于我也是新手，对Git不是很了解，在这里一直问大家也很不好意思，但是确实解决不了问题，只要学会这个模块我以后开发软件的时候自动更新就可以解决啦。所以说很不好意思。
麻烦再请问一下，我看了github的API文档，但是还是有点迷，我应该怎么获取到位于 https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/UpdateChecker.cs 这个文件中的更新链接川，我在Git中已经发布了了两个版本，但是都没法在客户端获取到更新，而我按照自己的理解写出了一个链接串是这样的https://api.github.com/repos/我的Github名/存储库名/release，还请各位帮我解答一下，再次感谢！

**Comment by celeron533** [comment]
建议还是先系统学习C#和visual studio的断点与debug用法

**Comment by Evilrabbit520** [comment]
所谓的“ss服务器”是服务端嘛？服务端是开源的吗？log里面的127.0.0.1这个地址是什么意思？

**Comment by Evilrabbit520** [comment]
所谓的“ss服务器”是服务端嘛？服务端是开源的吗？log里面的127.0.0.1这个地址是什么意思？

**Comment by chenshaoju** [comment]
是指用户配置的SS服务器信息，服务端是开源的 https://github.com/shadowsocks/shadowsocks-libev ，log 里的 127.0.0.1 说明你没有在客户端里配置SS服务器信息。
