### ISSUE TITLE
编译成64位代理无法工作，32位没问题

### ISSUE THREAD

**Issue by fifc** [shadowsocks/shadowsocks-windows#1662]
编译成64位代理无法工作，32位没问题，应该是个bug

**Comment by celeron533** [comment]
因为有些外部的native dll库是32位的，所以64位的主程序在调用这些库的时候会产生问题

**Comment by avatar21** [comment]
有同样问题，无法编译。
请支持，如果64位没有存在价值，为什么都系统升级64位了呢。
不支持就不支持，low就low，别瞎扯。

**Comment by chenshaoju** [comment]
你好，这个其实是原生库的问题，Shadowsocks for Windows使用了一些第三方库，而这些库没有提供64位版本，并非Shadowsocks for Windows自身的问题。

**Comment by fifc** [comment]
所用第三方库不都是开源的吗？编译个64位版本出来应该是可行的啊！

**Comment by celeron533** [comment]
@avatar21 @fifc 
pull request are welcome
Here is opensource community, you can do anything on the code as you wish without any payment.

For the 3rd party components, you could also sent pull requests to their project repository to make their project x64 compatible or give a x64 compiler profile at least. Also a simplified regression test may necessary to make sure the x64 build profile and artifact did not break any functions which is quite common to happen in native programs such as C, C++, GO.

**Comment by fifc** [comment]
actually i mean what specific pkg lacks of 64 port?

**Comment by celeron533** [comment]
@fifc I checked the external referenced, almost all the packages has 64bit binary builds. 😅

If has 32bit and 64bit builds in release:
1. There is no significant performance improvement as @wongsyrone mentioned.
2. Slightly added more maintenance work.
3. User need to know which version they need to download.

**Comment by Vndroid** [comment]
If all the external have a 64-bit version package, why not release two versions? After all, this is the future trend.

**Comment by studentmain** [comment]
Maybe we can have an 'All CPU' version by drop native 3rd-party library?

**Comment by celeron533** [comment]
@studentmain

or we can have both x86 and x64 native library and used corresponding ones by platform.

**Comment by fifc** [comment]
maybe it is safe to  drop 32bit support. it is not likely that a 32bit old pc  need to run ss

**Comment by studentmain** [comment]
为时尚早，现在还有不少的Win7 32位机。明年或者后年再考虑丢弃32位比较合适。不过我还是倾向于any cpu。any cpu几乎唯一的阻碍是libsscrypto.dll，其他的原生组件都可以（在合理缩减一些功能后）丢弃。

**Comment by Vndroid** [comment]
> 为时尚早，现在还有不少的Win7 32位机。明年或者后年再考虑丢弃32位比较合适。不过我还是倾向于any cpu。any cpu几乎唯一的阻碍是libsscrypto.dll，其他的原生组件都可以（在合理缩减一些功能后）丢弃。

Tell me about it! Let's do it(drop 32bit) one month later. lol

**Comment by Stzx** [comment]
看来可以考虑，明年迁移到 .NET 5

**Comment by studentmain** [comment]
#2833 有 All CPU 目标了
