### ISSUE TITLE
以资源文件形式打包的二进制文件，ss_privoxy等，有源代码吗？

### ISSUE THREAD

**Issue by fifc** [shadowsocks/shadowsocks-windows#1663]
想全部自己编译一下

**Comment by celeron533** [comment]
关于ss_privoxy
https://github.com/shadowsocks/shadowsocks-windows/issues/950#issuecomment-267729873
其他的如sysproxy等都能在github找到源码

**Comment by celeron533** [comment]
22275959982f83b07995dec7183911921fd81b4d
