### ISSUE TITLE
添加插件后报错

### ISSUE THREAD

**Issue by luzi1024** [shadowsocks/shadowsocks-windows#1666]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.7

### Environment(Operating system, .NET Framework, etc)
Win10 .net4.7

### Steps you have tried
---------------------------
Shadowsocks 错误: 系统找不到指定的文件。
---------------------------
System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。

   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)

   在 System.Diagnostics.Process.Start()

   在 Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()

   在 Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server)

   在 Shadowsocks.Controller.ShadowsocksController.StartPlugins()

   在 Shadowsocks.Controller.ShadowsocksController.Reload()
---------------------------
确定   
---------------------------

### What did you see instead?
有没有人遇到过啊，该怎么解决

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
你好，你需要将插件的程序放到你 Shadowsocks.exe 所在的目录下，具体请阅读：https://github.com/shadowsocks/shadowsocks-windows/issues/1368

**Comment by luzi1024** [comment]
谢谢，已经解决了^_^
