### ISSUE TITLE
如何在通知栏以外控制ss

### ISSUE THREAD

**Issue by ColinTree** [shadowsocks/shadowsocks-windows#1667]
我这生活环境比较恶劣
学校电脑不显示通知栏，不支持.net 4.6.2，没管理权限
所以我都是用改json，taskkill来开关的，结果就是kill之后全局崩网啥都上不了打开又500
主要就是通知栏问题比较严重，怎么解决呢

**Comment by ColinTree** [comment]
现在只能用3.3.2

**Comment by albertofwb** [comment]
你可以用 QT 版本的 ss

**Comment by Youxikong** [comment]
kill后打开IE浏览器，在Internet选项中，将链接卡片的局域网设置中取消所有勾选，网络就能正常使用了。

**Comment by celeron533** [comment]
这个use case实在是太罕见了，所以暂时没有计划
