### ISSUE TITLE
SS最新版本被Avast杀毒软件误报

### ISSUE THREAD

**Issue by okudayukiko** [shadowsocks/shadowsocks-windows#1668]

**Comment by chenshaoju** [comment]
你好，刚上传到VirusTotal进行了检查： https://www.virustotal.com/en/file/a70fb02dcc14557bfcd6b3e167e5d28f058a0481cf3433af8144ea49bf838a6b/analysis/1518084197/ ，列表中的杀毒软件，包括Avast均未报毒

请使用第三方Hash工具（ 如 https://quickhash-gui.org ）核对 Shadowsocks.exe 的校验码：
MD5:2fefd08c98b8134ca793cca1e37d73f2
SHA1:3cd849a020468ca7859d08b0e951dd228ffd2a17
SHA256:a70fb02dcc14557bfcd6b3e167e5d28f058a0481cf3433af8144ea49bf838a6b
