### ISSUE TITLE
[建议]在issue编辑框内增加先阅读wiki的中文提示

### ISSUE THREAD

**Issue by thelastlin** [shadowsocks/shadowsocks-windows#1669]
**描述** 许多人提问题前没有先看wiki，也不知道去搜索，净问些重复问题，可能他们不懂英文，不知道要先看wiki。

**建议** 在原有的编辑框提示中加上一句话中文提示，提醒他们先仔细阅读wiki。

**Comment by celeron533** [comment]
这样子issue template会变得越来越长
有可能在未来对客户端的一部分UI进行改版，加入wiki，Q&A链接等

**Comment by celeron533** [comment]
目前加了一点
1e04279d374d77477c742b89641468d66f5b6f28
