### ISSUE TITLE
Add an option to let user wrap SIP003 environment variables as normal in-line arguments

### ISSUE THREAD

**Issue by celeron533** [shadowsocks/shadowsocks-windows#1672]
### Just a brainstorm

According to https://github.com/shadowsocks/shadowsocks-org/issues/28 , the SIP003 arguments are delivered by environment variables:
Mandatory:
`SS_REMOTE_HOST`, `SS_REMOTE_PORT`, `SS_LOCAL_HOST` and `SS_LOCAL_PORT`
Optional:
`SS_PLUGIN_OPTIONS`

--------
Currently, a SIP003 "compatible" plugin program must able to read and grab its Process environment variables when being launched. Equivalent to the following console commands:

1. ss-win set the environment variables
```
set SS_REMOTE_HOST=1.2.3.4
set SS_REMOTE_PORT=9999
set SS_LOCAL_HOST=127.0.0.2
set SS_LOCAL_PORT=33333
set SS_PLUGIN_OPTIONS=foobar
```
2. Then ss-win launch the plugin
```
start someplugin.exe
```

--------
If user has plugins whose implementation does not following SIP003 standard, user should have a work-around to give the in-line arguments when starting the plugin program. For instance:

1. ss-win set the environment variables
```
set SS_REMOTE_HOST=1.2.3.4
set SS_REMOTE_PORT=9999
set SS_LOCAL_HOST=127.0.0.2
set SS_LOCAL_PORT=33333
set SS_PLUGIN_OPTIONS=foobar
```
2. User typed the format and pattern for the in-line arguments wrapper
```
-remote %SS_REMOTE_HOST%:%SS_REMOTE_PORT% -local %SS_LOCAL_HOST%:%SS_LOCAL_PORT% %SS_PLUGIN_OPTIONS%
```
3. Then ss-win launch the plugin by using the wrapper
```
start someplugin.exe -remote %SS_REMOTE_HOST%:%SS_REMOTE_PORT% -local %SS_LOCAL_HOST%:%SS_LOCAL_PORT% %SS_PLUGIN_OPTIONS%
```
which will be parsed into
```
start someplugin.exe -remote 1.2.3.4:9999 -local 127.0.0.2:33333 foobar
```

It should expand the selection of third-party plug-in programs.

**Comment by madeye** [comment]
The reason we use environment variable is to avoid special character issue in the command line, e.g key s like `^%$&^\/`.

However, it's still worth to support CLI args in windows as some users would try to use non-SIP003 plugins.
