### ISSUE TITLE
A mistake in Local Network Range 

### ISSUE THREAD

**Issue by kyang922** [shadowsocks/shadowsocks-windows#1674]
you add following IP Range to exclude Local Network in shadowsocks windows client,
`localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*`

But I think **172.32.*** is not a private network range, the IPv4 Private Network 172.16.0.0/12 is from 172.16.* to 172.31.*

**Comment by celeron533** [comment]
Thanks!
