### ISSUE TITLE
4.0以上版本ui经常崩溃

### ISSUE THREAD

**Issue by dayue1984** [shadowsocks/shadowsocks-windows#1676]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0+

### Environment(Operating system, .NET Framework, etc)
windows10 x64

### Steps you have tried
正常运行中界面自行崩溃

### What did you see instead?
重启后右下角图标出现，但是右键点击没反应，代理也没有任何作用。
凡是4.0以后版本使用一个月左右时间都会出现这个问题，就是突然崩溃，然后重新运行后程序功能无效，systray icon也不响应点击，只能重装系统或者用回3.x版本。
尝试过的解决办法包括：用ms的工具修复dotnet；卸载dotnet重装；清理注册表；更换程序目录；使用兼容性助手，都不能使程序正常运行。

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
你的操作系统是Windows 10吗？有过类似的报告，可能和系统补丁有关。

https://github.com/shadowsocks/shadowsocks-windows/issues/1577

**Comment by dayue1984** [comment]
win10专业版64位，如果需要可以给我一个debug版本协助测试，这个问题困扰我很久了，一开始以为杀软或者dotnet问题，重装过很多遍系统，基本上一个月就挂。现在还在用3.4.3版本，一直稳定。

**Comment by chenshaoju** [comment]
我是Windows 10家庭版 64位，能否看一下日志文件， Shadowsocks.log 里有什么东西吗？

**Comment by dayue1984** [comment]
上一次崩溃时候我把temp目录整个删了，没有留存。现在运行4.0.7的话log里就一条程序已启动，就没别的了，但是点击没反应，代理也不起作用。

**Comment by chenshaoju** [comment]
https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/4.0.7.14/job/gkqpjr883owplc89/artifacts

这是Debug版本。

**Comment by dayue1984** [comment]
好的，我试下，再崩溃把log贴过来

**Comment by dayue1984** [comment]
ss刚崩溃了，错误提示是端口被占用，弹出来两次，然后重启电脑后bug复现，ui不响应，代理无效，log如下：
[2018-02-17 19:26:41] Shadowsocks started
[2018-02-17 19:26:41] [D] sodium: AES256GCMAvailable is True
[2018-02-17 19:26:41] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor

**Comment by dayue1984** [comment]
[2018-02-17 18:06:35] controller stopped
[2018-02-17 18:06:35] os suspend
[2018-02-17 19:18:11] os wake up
[2018-02-17 19:18:21] System.Exception: 端口已被占用
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
[2018-02-17 19:19:05] System.Exception: 端口已被占用
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
[2018-02-17 19:19:30] Shadowsocks.Util.SystemProxy.ProxyException
   在 Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
[2018-02-17 19:19:30] controller started
[2018-02-17 19:19:30] Shadowsocks.Util.SystemProxy.ProxyException
   在 Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
[2018-02-17 19:19:30] controller started
[2018-02-17 19:20:36] Shadowsocks started
[2018-02-17 19:20:37] [D] sodium: AES256GCMAvailable is True
[2018-02-17 19:20:37] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
=========================

**Comment by chenshaoju** [comment]
换一个代理端口看看？如果已经无法启动SS界面，请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/1324

**Comment by chenshaoju** [comment]
对了，你是唤醒后遇到该问题？如果是，看这里： https://github.com/shadowsocks/shadowsocks-windows/issues/1559

**Comment by dayue1984** [comment]
改端口解决，所以端口占用后程序直接卡死？谢谢了！继续观察！

**Comment by celeron533** [comment]
>改端口解决，所以端口占用后程序直接卡死？谢谢了！继续观察！

一般端口被占用后不会卡死
但是有时候一些安全软件可能导致莫名其妙的问题
