### ISSUE TITLE
Win10 下 Shadowsocks 停止工作

### ISSUE THREAD

**Issue by zyd232** [shadowsocks/shadowsocks-windows#1677]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.7 & 3.4.3，两个版本都尝试过了。

### Environment(Operating system, .NET Framework, etc)
Windows 10 专业版，版本 1709，OS内部版本 16299.192
.NET Framework 安装了 3.5 和 4.7 版本

### Steps you have tried
可ping通127.0.0.1。

使用“netstat -ano”命令，未发现1080端口被占用。

全新的、光秃秃的Shadowsocks.exe，4.0.7 和 3.4.3 两个版本，分别单独放在不同目录下（非系统盘），打开后都会停止工作（停止工作后，任务管理器里没有相关进程残留）。

### What did you expect to see?
可正常使用的Shadowsocks。

### What did you see instead?
打开 Shadowsocks.exe 后，显示UI界面，但2秒后便弹出“Shadowsocks已停止工作”。

### Config and error log in detail (with all sensitive info masked)
\ss_win_temp\shadowsocks.log: 
`[2018-02-15 12:01:09] Shadowsocks started`

没什么有用的信息……ss_privoxy.log是空的（因为一打开就崩溃了）。

然后使用了 #1676 中 @chenshaoju 提供的4.0.7.14的Debug版本，日志如下：
\ss_win_temp\shadowsocks.log: 
```
[2018-02-15 12:08:41] Shadowsocks started
[2018-02-15 12:08:41] [D] sodium: AES256GCMAvailable is True
[2018-02-15 12:08:41] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
=========================
```

**Comment by chenshaoju** [comment]
崩溃的话，停止工作对话框下面的调试信息有什么？

**Comment by zyd232** [comment]
整个窗口就只有以下内容，也没有详细信息之类的可下拉的内容：

> Shadowsocks

> **Shadowsocks 已停止工作**
> 由于出现问题，程序停止正常工作。Windows 将关闭程序，并会在有可用的解决方案时通知你。

> [ 关闭程序(C) ]

**Comment by chenshaoju** [comment]
请打开资源浏览器，在地址栏输入“控制面板”（不含双引号），打开控制面板后在对话框右上角的搜索控制面办中输入“解决方案”，并点击“查看可靠性历史记录”。

然后从新打开的可靠性监视程序对话框的下半部分的列表中找到Shadowsocks的崩溃记录，双击，然后点击复制到剪切板，并粘贴上来。

**Comment by zyd232** [comment]
源
Shadowsocks

摘要
已停止工作

日期
‎2018/‎2/‎15 16:01

状态
已发送报告

描述
错误的应用程序路径:	F:\Shadowsocks\Shadowsocks.exe

问题签名
问题事件名称:	APPCRASH
应用程序名:	Shadowsocks.exe
应用程序版本:	4.0.7.0
应用程序时间戳:	5a2b6f10
故障模块名称:	d3d9.dll
故障模块版本:	10.0.16299.98
故障模块时间戳:	e2fbf0fc
异常代码:	c0000005
异常偏移:	000481d1
OS 版本:	10.0.16299.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	2beb
其他信息 2:	2beba6fb4680d73a8c78ca7c24ccdb46
其他信息 3:	afe9
其他信息 4:	afe9c5ff3db24c3300bbaf74265da1cc

关于该问题的额外信息
存储段 ID:	2ef819be0bcab86e3a3466358f66d6eb (1888246524000261867)

**Comment by zyd232** [comment]
找到原因了……上面故障模块名称是 d3d9.dll，所以就想到是不是有相关进程冲突……

后来发现是 RivaTuner Statistics Sever 的问题（它是 MSI Afterburner 的 OSD 服务端）。只要把 RivaTuner Statistics Sever 中的 Application Detection Level 调到 Low 或以上，就会导致Shadowsocks停止工作。

**Comment by chenshaoju** [comment]
可能会存在某种限制，如果该应用支持黑名单或者排除列表之类的功能的话，请将 Shadowsocks.exe 加进去看看。

**Comment by zyd232** [comment]
谢谢~已解决。

**Comment by zyd232** [comment]
估计不少 PC 游戏玩家都在用 MSI Afterburner，所以这个问题应该蛮普遍的。这个问题不止会导致Shadowsocks 崩溃，也可能导致其他使用 .NET 开发 GUI 的程序出问题。

解决办法：
打开MSI Afterburner——点击 “Settings” 按钮——“OSD显示”选项卡——点击“OSD服务端兼容性属性”下的“更多”按钮，从而打开 RivaTuner Statistics Sever 设置面板。

在 RivaTuner Statistics Sever 设置面板中，点击左下角Add按钮，添加新的 Application Profile Properties，把受影响的程序（如Shadowsocks）加进去。然后点击添加的项目，在右侧把“Application Detection Level” 调为“None”。

**Comment by celeron533** [comment]
感谢 @zyd232 的详细内容和研究结果 :)
