### ISSUE TITLE
支持RTMP协议嘛

### ISSUE THREAD

**Issue by zjplab** [shadowsocks/shadowsocks-windows#1678]
平时有什么软件需要科学上网我都是用Proxifier配合SS，现在想在youtube上面直播，需要用到rtmp协议，发现好像行不通？

**Comment by chenshaoju** [comment]
查了一下，RTMP分四种，RTMPS、RTMPE、RTMPT和RTMFP。

其中，RTMPS、RTMPE、RTMPT使用的是TCP协议。

RTMFP是UDP，可能你需要在你的SS服务端开始UDP支持。 https://github.com/shadowsocks/shadowsocks-libev/blob/master/README.md
