### ISSUE TITLE
[UI疑问] “statistics strategy configuration form”中统计数值的单位

### ISSUE THREAD

**Issue by ty359** [shadowsocks/shadowsocks-windows#1680]
### Version(release version or AppVeyor link)
Shadowsocks 4.04

### Environment(Operating system, .NET Framework, etc)
Win 10

### Steps you have tried
打开 "服务器" -》 "统计配置..."

在“statistics strategy configuration form” UI中用于给服务器打分的参数（latency，inboundspeed，responresponse等）没有标注单位，能不能解释一下这些参数的单位。

如果可以的话，应该在UI中注明这些单位，或者在readme中提供关于这个功能的说明

**Comment by celeron533** [comment]
有兴趣的话可以自己研究研究一下代码
但到目前为止，这个统计功能本身所带来的性能问题似乎更严重。。。坑了

**Comment by icylogic** [comment]
speed: KiB/s 
https://github.com/shadowsocks/shadowsocks-windows/blob/5ba8f9a004ecdede2184bcc68f0433b5564ed429/shadowsocks-csharp/Controller/Service/AvailabilityStatistics.cs#L36

latency: milliseconds
https://github.com/shadowsocks/shadowsocks-windows/blob/11514dbf0230976e4f83b4424fbbd66e7bacd937/shadowsocks-csharp/Controller/ShadowsocksController.cs#L451

这个功能很久以前写的，水平比较烂  …… 对于给大家带来的困扰表示抱歉 ……

**Comment by studentmain** [comment]
给CalculationControl加一个

**Comment by database64128** [comment]
The statistics feature has been removed in #2994. Closing now.
