### ISSUE TITLE
Shadowsocks error: the system cannot find the file specified

### ISSUE THREAD

**Issue by xiaopigu** [shadowsocks/shadowsocks-windows#1681]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.8

### Environment(Operating system, .NET Framework, etc)
windows 10

### Steps you have tried
using the qr code to add servers and manually entering them

### What did you expect to see?
Shadowsocks to start

### What did you see instead?

![capture](https://user-images.githubusercontent.com/25901225/36296877-7ca73296-132a-11e8-92d3-86e4fbb14e8b.PNG)

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
You need to download the plugin program and fill where the .exe file in Server config form

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1368

**Comment by zhanyang5858** [comment]
go this address to download the zip and unzip at the root folder of shadowsocks

下载以下链接的zip，解压在ss的根目录然后就可以了

https://github.com/shadowsocks/simple-obfs/releases
