### ISSUE TITLE
大哥除了别人反映的Avast外我电脑上的Windows Defender也报毒，已经升级过最新版本了。

### ISSUE THREAD

**Issue by ku8h96de4** [shadowsocks/shadowsocks-windows#1683]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chendeshen** [comment]
me too. Windows Defender reported.

Threat Description: trojan:win32/spursint.f!cl
Win32/Spursint
Updated on Apr 12, 2016
Windows Defender detects and removes this threat.  This threat has been detected as one of the executable malware that are distributed through URLs. Find out ways that malware can get on your PC.
Alert level: SEVERE
Trojan:Win32/Spursint.F!cl
Updated on Sep 12, 2016
Alert level: SEVERE
Trojan:Win32/Spursint.A!cl
Updated on Mar 21, 2016
Windows Defender detects and removes this threat.  A trojan is a type of malware that can’t spread on its own. It relies on you to run them on your PC by mistake, or visit a hacked or malicious webpage.  They can steal your personal information, download more malware, or...
Alert level: SEVERE

**Comment by jasonliul** [comment]
https://www.virustotal.com/
https://www.hybrid-analysis.com/
自行送测判断, 纳凉这许多伸手等喂饭?

**Comment by chenshaoju** [comment]
Hi, I just upload Shadowsocks for Windows 4.0.8 to VirtusTotal again, The check result is all clean.

Please try to update your anti-virus databases.

https://www.virustotal.com/en/file/286f65de52031116b93665d6aadbe56f0e0a6662315c1d4dfb7ddd78cbc179ae/analysis/1518926041/

And please check your shadowsocks.exe checksum is same with release pages value.

**Comment by chenshaoju** [comment]
BTW, I don't use Avast and MSE, But I still upload Shadowsocks.exe to the false positive category.

Please waiting for anti-virus databases update.

![image](https://user-images.githubusercontent.com/515763/36348178-f6a4d74e-14a4-11e8-82a2-0f91c6467ca6.png)

![image](https://user-images.githubusercontent.com/515763/36348347-8224367c-14a8-11e8-9cde-58afe6a8e623.png)

Update: The Microsoft (MSE) has checked the shadowsocks.exe, This is clean.
https://www.microsoft.com/en-us/wdsi/submission/3ab94e4e-7bdd-473d-9230-599202fd2e57

![image](https://user-images.githubusercontent.com/515763/36348362-e1d047d2-14a8-11e8-85e7-ece747e15a28.png)

**Comment by celeron533** [comment]
#1668

**Comment by chenshaoju** [comment]
For now, Windows Defender has not detected.


![2018-02-20](https://user-images.githubusercontent.com/515763/36410387-bba49654-164b-11e8-93aa-4973669a8a75.png)


Version:
![2018-02-20 1](https://user-images.githubusercontent.com/515763/36410531-69461102-164c-11e8-9730-a11a97c8dcc0.png)

**Comment by chenshaoju** [comment]
Final Update:
The Avast has updated their anti-virus databases, After 24 hours should be fine.

![image](https://user-images.githubusercontent.com/515763/36551809-6da879cc-1833-11e8-820b-bfbf90454f9c.png)

**Comment by asuradaII** [comment]
![image](https://user-images.githubusercontent.com/15797571/36764953-037c3314-1c6a-11e8-9e8d-73a8620795b0.png)
