### ISSUE TITLE
增加“绕过中国大陆地址”过滤条件

### ISSUE THREAD

**Issue by ksotin** [shadowsocks/shadowsocks-windows#1685]
能否增加 Android 版那样的过滤条件“绕过中国大陆地址”？

**Comment by chenshaoju** [comment]
目前暂时做不到，不过有一个第三方的中间件可以做到，具体请阅读： https://github.com/breakwa11/gfw_whitelist/blob/master/README.md

**Comment by ksotin** [comment]
@chenshaoju 怎么和Windows客户端配合使用？

**Comment by chenshaoju** [comment]
未经测试，请先试一下：

下载 whitelist.pac 或 whiteiplist.pac 或 proxy.pac 文件（按照你的需求，请仔细阅读二楼的网址）后，用文本编辑器打开，找到
```
var wall_proxy = 'PROXY www.abc.com:443;'; 
```
将其修改为
```
var wall_proxy = 'PROXY 127.0.0.1:1080;'; 
```
注意：1080是你的SS的代理端口，可在编辑服务器界面右下角看到。

保存后，将文件名修改为 pac.txt ，并替换到你SS所在目录下的 pac.txt 文件即可。

请将SS设定为PAC模式，使用本地代理，并启用系统代理。

**Comment by ksotin** [comment]
@chenshaoju 好的，非常感谢！

**Comment by aglent** [comment]
楼主用chrome或firefox的 代理扩展URL里填写https://raw.githubusercontent.com/breakwa11/gfw_whitelist/master/whiteiplist.pac

**Comment by ksotin** [comment]
@chenshaoju whitelist 和 whiteiplist 哪一个可以避免DNS污染问题？

**Comment by chenshaoju** [comment]
@ksotin 我没用过，所以。。。你可以试一下。

**Comment by ksotin** [comment]
@chenshaoju 直接把 whiteiplist.pac 添加到客户端的在线 PAC URL 里可以吗？

**Comment by chenshaoju** [comment]
@ksotin 不确定，因为我没这么用过。

**Comment by ksotin** [comment]
@chenshaoju 目前没有什么问题，非常感谢您的帮助

**Comment by ksotin** [comment]
@aglent chrome 扩展 proxy.pac whitelist.pac whiteiplist.pac 这三个选哪一个，有什么建议吗？

**Comment by aglent** [comment]
@ksotin Proxy.pac是白名单+黑名单模式 首选这个
或者whiteiplist.pac 国内IP直连 国外IP走代理

**Comment by ksotin** [comment]
@aglent 白名单+黑名单具体是怎么工作的？whitelist域名列表和whiteiplist IP列表效果有什么不同？
