### ISSUE TITLE
SS only works on admin account

### ISSUE THREAD

**Issue by tazdevil1** [shadowsocks/shadowsocks-windows#1689]
Windows 10 Enterprice, 64bit, Chinese Simplified

ShadowSocks 4.07

SS does not work on non-admin account, even if I run on non admin account to generate directory and files.  All UI works.  Can't visit sites such as YouTube from within China.

All are fine when I run SS on admin account.

Also ShadowSocks 4.08 is blocked by Windows Defender (saying it is virus or trojon )

**Comment by chenshaoju** [comment]
Please put Shadowsocks.exe to a new directory, Like "D:\SS\", Do not put "C:\Program Files\".

About anti-virus: https://github.com/shadowsocks/shadowsocks-windows/issues/1683#issuecomment-366492207

**Comment by tazdevil1** [comment]
Following the instruction, I was able to put SS client in C:\Users\Public\ss-4.07 and link to the server on one PC, non-admin user.

I failed to do so on another PC.  Checking the proxy settings I see (as attached)

![image](https://user-images.githubusercontent.com/36652906/36419620-afc0b18a-15ef-11e8-990b-e80bd66c3604.png)

**Comment by tazdevil1** [comment]
I've figured out why.  There is an video app IQIYI (爱奇艺) that is interfering with the proxy setting.  After I uninstall IQIYI (爱奇艺) app all are good.
