### ISSUE TITLE
开着shadowsocks打游戏游戏卡成ppt

### ISSUE THREAD

**Issue by OtakuAndFitness** [shadowsocks/shadowsocks-windows#1690]
大家有没有这个现象？我是Windows10 1709，cpu：i7-6700hq，ram：8g，gpu：965m，玩游戏时显卡切换到独显的。shadowsocks使用版本是4.0.8

**Comment by chenshaoju** [comment]
Windows 7 x64 SP1 i5-3320M 16G GT650M 没有这个现象。如果是双显卡切换（Intel/Nvidia），请确保在Nvidia控制面板中是自动。如果仍然不行，请尝试右击游戏的快捷方式，并选择用图形处理器运行中的 “高性能 Nvidia 图形处理器” 。

**Comment by pexcn** [comment]
网络游戏？

**Comment by chenshaoju** [comment]
另外，已知某些网络游戏（比如暴雪娱乐旗下的风暴英雄）在网络质量不好的情况下也会掉帧，即使计算机的硬件配置很高。

如果你使用的是SS的全局模式，请尝试切换到PAC模式，或者取消选中“启用系统代理”后，重启游戏看看。

**Comment by celeron533** [comment]
如果启用了详细日志输出的话，也会比较吃CPU。

**Comment by OtakuAndFitness** [comment]
我用ff15的评分软件试的，开着shadowsocks分数超不过1000，不开上3000
ps：ff15评分软件是为了检查pc能不能跑起来ff15而制作的，分数1999以下代表pc不足以运行ff15，3000-4999则此pc是标准配置，可以运行ff15

**Comment by celeron533** [comment]
@OtakuAndFitness 会不会和这个有关 https://github.com/shadowsocks/shadowsocks-windows/issues/1677#issuecomment-365852784
