### ISSUE TITLE
In-coming UI Change: All-in-one settings form (work in progress)

### ISSUE THREAD

**Issue by celeron533** [shadowsocks/shadowsocks-windows#1691]
Less tray icon right button clicks.

![image](https://user-images.githubusercontent.com/3608762/36434467-09e0b5ca-169a-11e8-8fae-a8aa4a3955e1.png)

![image](https://user-images.githubusercontent.com/3608762/36434474-0e194d0a-169a-11e8-8504-181f675f64b2.png)

![image](https://user-images.githubusercontent.com/3608762/36434480-11a20e08-169a-11e8-9a70-dff442896324.png)

**Comment by wongsyrone** [comment]
Any reason?

**Comment by celeron533** [comment]
>Any reason?

Just work in "Playground"
https://github.com/celeron533/shadowsocks-windows/tree/UI
1. Preparing to reduce the right click menu items. (forward proxy, start on boot, edit hotkeys, help (check updates, about))
2. It has better UX when switching between tabs rather than windows. And may simplify  `controller_ConfigChanged` event between forms.

Further plan:
3. Will add one `About` tab. May include license annotation & component summary, dependency check, github link, wiki link, Q&A link, etc.
![image](https://user-images.githubusercontent.com/3608762/36460087-cf884926-16f1-11e8-942e-27840b34f791.png)

5. May rewrite some part of Config Form

**Comment by studentmain** [comment]
It looks good, how's it going?

**Comment by celeron533** [comment]
Did a very beginning prototype and then found that everything all logic code together behind the GUI is not good...
Later had the thought to rewrite the config form with a better data structure.

**Comment by studentmain** [comment]
So it's the old problem again, code quality...... Personally I'd like a WPF/HTML based GUI, but it has too much work to do.

**Comment by Stzx** [comment]
So it seems that there is still a lot of work ahead of time before the release of .NET 5.

I can first rewrite the interface using WPF.

Also strip the data structure to split the project into multiple subprojects.
