### ISSUE TITLE
shadowsocks 4.0.8 无法启动，显示丢失VCRUNTIME140.dll

### ISSUE THREAD

**Issue by dancorpse** [shadowsocks/shadowsocks-windows#1692]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.8 

### Environment(Operating system, .NET Framework, etc)
win 7 64 位，net framework 4.6.2 

启动程序时显示计算机丢失VCRUNTIME140.dll

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1679

**Comment by het2er** [comment]
本人Win 7 32位，.net framework 4.7.1，更新4.0.8版本后同样遇到这一问题。自行安装Microsoft Visual C++ 2017 Redistributable后问题解决，但在本仓库找了一下并没有看到关于新版本需要安装此组件的说明。仅供参考。
