### ISSUE TITLE
能否在设置中指定单独的http端口

### ISSUE THREAD

**Issue by hyacinthus** [shadowsocks/shadowsocks-windows#1694]
好苦恼，我一直是自己架http的。 后来发现mac的自带了，这很好。
后来发现windows的也自带了，这也很好。
结果发现windows的不能设置成不一样的。
我各种app同步的proxy配置就歇菜了。。。比如vscode

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 的代理端口其实是HTTP和SOCKS5协议并存的，一个端口上有两个服务。

如果你希望自己指定一个HTTP端口，现阶段的方案是自行启动一个 Privoxy ，并配置：
```
forward-socks5 / 127.0.0.1:1080 .
listen-address  127.0.0.1:8080
```

当然，端口可以按照你的需求修改。

**Comment by hyacinthus** [comment]
谢谢回复，我已经这么做了，过来只是吐槽下。

处女座觉得启动两个privoxy有点蛋疼而已。。。

**Comment by chenshaoju** [comment]
习惯就好，习惯就好。 [二哈]

![image](https://user-images.githubusercontent.com/515763/36551175-f48f1c86-1831-11e8-87de-fc476949a7bb.png)
