### ISSUE TITLE
shadowsock 4.0.8无法启动

### ISSUE THREAD

**Issue by Xiphoray** [shadowsocks/shadowsocks-windows#1695]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

4.0.8

### Environment(Operating system, .NET Framework, etc)

win10 1709 64位   netframework 4.7

### Steps you have tried

各种删文件，单独移到其他位置都试过

防火墙之类的确定已经对其允许

#1297 里的全部试过

直接ping我的vps是可以通的

我的伙伴用同样的ss版本，同样的vps能上

如果开全局后启动，还是能连上国内的网，感觉代理完全没有启动

###  Config and error log in detail (with all sensitive info masked)

> [2018-02-23 17:03:56] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
>    在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
>    在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
>    在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
>    --- 内部异常堆栈跟踪的结尾 ---
>    在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
>    在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
>    --- 内部异常堆栈跟踪的结尾 ---
>    在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
>    在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
> [2018-02-23 17:04:29] Shadowsocks started
> [2018-02-23 17:04:29] 
> =========================
> Registered Encryptor Info
> aes-128-cfb=>StreamOpenSSLEncryptor
> aes-192-cfb=>StreamOpenSSLEncryptor
> aes-256-cfb=>StreamOpenSSLEncryptor
> aes-128-ctr=>StreamOpenSSLEncryptor
> aes-192-ctr=>StreamOpenSSLEncryptor
> aes-256-ctr=>StreamOpenSSLEncryptor
> bf-cfb=>StreamOpenSSLEncryptor
> camellia-128-cfb=>StreamOpenSSLEncryptor
> camellia-192-cfb=>StreamOpenSSLEncryptor
> camellia-256-cfb=>StreamOpenSSLEncryptor
> rc4-md5=>StreamOpenSSLEncryptor
> salsa20=>StreamSodiumEncryptor
> chacha20=>StreamSodiumEncryptor
> chacha20-ietf=>StreamSodiumEncryptor
> aes-128-gcm=>AEADOpenSSLEncryptor
> aes-192-gcm=>AEADOpenSSLEncryptor
> aes-256-gcm=>AEADOpenSSLEncryptor
> chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
> =========================
> 
> [2018-02-23 17:04:29] Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 12178 (null)
> 
>    在 Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
>    在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
>    在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
>

**Comment by chenshaoju** [comment]
分两个部分：
１.
```
[2018-02-23 17:03:56] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
```
这意味着你的目标SS服务器可能挂了、端口不正确或被墙了、密码或加密方式不对，请仔细检查配置，如果有必要，请用Windows自带的记事本打开SS所在目录下的 gui-config.json 文件仔细检查。具体请阅读： https://github.com/shadowsocks/shadowsocks-windows/issues/1629

２.
```
[2018-02-23 17:04:29] Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 12178 (null)
```
系统代理设置失败，该问题应该不会发生，猜测和WinHTTP服务有关，但是SS并不使用该系统服务。此问题有可能和系统有关。请进入控制面板（可打开我的电脑，在地址栏里输入“控制面板”四个字进入），管理工具，服务，找到 WinHTTP Web Proxy Auto-Discovery Service 服务并检查是否启动。具体请阅读：https://github.com/shadowsocks/shadowsocks-windows/issues/1193

**Comment by Xiphoray** [comment]
发现 WinHTTP Web Proxy Auto-Discovery Service 被禁用了，但选项条全是灰色，无法启动，正在查怎么启动

**Comment by JasonOldWoo** [comment]
原来用得好好的，自从更新了4.0.8就出现下面的问题了。

[2018-02-26 20:02:45] connect to api.github.com:443
[2018-02-26 20:02:45] Socket connected to ss server: xxxx
[2018-02-26 20:02:46] System.DllNotFoundException: 无法加载 DLL“libcrypto-1_1.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.OpenSSL.EVP_get_cipherbyname(Byte[] name)
   在 Shadowsocks.Encryption.OpenSSL.GetCipherInfo(String cipherName)
   在 Shadowsocks.Encryption.AEAD.AEADOpenSSLEncryptor.InitCipher(Byte[] salt, Boolean isEncrypt, Boolean isUdp)
   在 Shadowsocks.Encryption.AEAD.AEADEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.SendToServer(Int32 length, AsyncSession session)
   在 Shadowsocks.Controller.TCPHandler.StartPipe(AsyncSession session)
[2018-02-26 20:02:46] connect to api.github.com:443
[2018-02-26 20:02:46] Socket connected to ss server: xxxx
[2018-02-26 20:02:46] System.DllNotFoundException: 无法加载 DLL“libcrypto-1_1.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.OpenSSL.EVP_get_cipherbyname(Byte[] name)
   在 Shadowsocks.Encryption.OpenSSL.GetCipherInfo(String cipherName)
   在 Shadowsocks.Encryption.AEAD.AEADOpenSSLEncryptor.InitCipher(Byte[] salt, Boolean isEncrypt, Boolean isUdp)
   在 Shadowsocks.Encryption.AEAD.AEADEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.SendToServer(Int32 length, AsyncSession session)
   在 Shadowsocks.Controller.TCPHandler.StartPipe(AsyncSession session)
[2018-02-26 20:02:46] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by JasonOldWoo** [comment]
4.0.7亲测正常，只有4.0.8有问题。

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1679

**Comment by JasonOldWoo** [comment]
@chenshaoju 明白了，谢谢！

**Comment by Xiphoray** [comment]
发现开启WinHTTP Web Proxy Auto-Discovery Service会导致电脑无法联网，有线wifi都连不了，求大神指教。。。
