### ISSUE TITLE
无法加载libcrypto-1_1.dll

### ISSUE THREAD

**Issue by lx0758** [shadowsocks/shadowsocks-windows#1696]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.8

### Environment(Operating system, .NET Framework, etc)
WIN10/WIN SERVER 2008
.NET 4.6.2

### Steps you have tried
SERVER提示VC库找不到,拷贝已修复.然后以为正常工作,结果直接报500,,客户端无报错.
随后切换低版本工作正常

### What did you expect to see?
正常工作...

### What did you see instead?
查看日志发现记录无法加载libcrypto-1_1.dll

### Config and error log in detail (with all sensitive info masked)
[2018-02-23 17:26:04] System.DllNotFoundException: 无法加载 DLL“libcrypto-1_1.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.OpenSSL.EVP_get_cipherbyname(Byte[] name)
   在 Shadowsocks.Encryption.OpenSSL.GetCipherInfo(String cipherName)
   在 Shadowsocks.Encryption.Stream.StreamOpenSSLEncryptor.initCipher(Byte[] iv, Boolean isEncrypt)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.SendToServer(Int32 length, AsyncSession session)
   在 Shadowsocks.Controller.TCPHandler.StartPipe(AsyncSession session)

**Comment by lx0758** [comment]
后来尝试拷贝libcrypto-1_1.dll到Shadowsocks.exe同级目录,故障依旧.日志如下:
[2018-02-23 17:46:31] Shadowsocks started
[2018-02-23 17:46:31] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
=========================

[2018-02-23 17:46:34] System.BadImageFormatException: 试图加载格式不正确的程序。 (异常来自 HRESULT:0x8007000B)
   在 Shadowsocks.Encryption.OpenSSL.EVP_get_cipherbyname(Byte[] name)
   在 Shadowsocks.Encryption.OpenSSL.GetCipherInfo(String cipherName)
   在 Shadowsocks.Encryption.Stream.StreamOpenSSLEncryptor.initCipher(Byte[] iv, Boolean isEncrypt)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.SendToServer(Int32 length, AsyncSession session)
   在 Shadowsocks.Controller.TCPHandler.StartPipe(AsyncSession session)
[2018-02-23 17:46:34] System.BadImageFormatException: 试图加载格式不正确的程序。 (异常来自 HRESULT:0x8007000B)
   在 Shadowsocks.Encryption.OpenSSL.EVP_get_cipherbyname(Byte[] name)
   在 Shadowsocks.Encryption.OpenSSL.GetCipherInfo(String cipherName)
   在 Shadowsocks.Encryption.Stream.StreamOpenSSLEncryptor.initCipher(Byte[] iv, Boolean isEncrypt)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.SendToServer(Int32 length, AsyncSession session)
   在 Shadowsocks.Controller.TCPHandler.StartPipe(AsyncSession session)
[2018-02-23 17:46:34] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-02-23 17:46:52] System.BadImageFormatException: 试图加载格式不正确的程序。 (异常来自 HRESULT:0x8007000B)
   在 Shadowsocks.Encryption.OpenSSL.EVP_get_cipherbyname(Byte[] name)
   在 Shadowsocks.Encryption.OpenSSL.GetCipherInfo(String cipherName)
   在 Shadowsocks.Encryption.Stream.StreamOpenSSLEncryptor.initCipher(Byte[] iv, Boolean isEncrypt)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.SendToServer(Int32 length, AsyncSession session)
   在 Shadowsocks.Controller.TCPHandler.StartPipe(AsyncSession session)

**Comment by lx0758** [comment]
实测4.0.7及之前版本无故障

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1679#issuecomment-366187297
