### ISSUE TITLE
Add multi server with obfs plugin cause multi console opened in the background

### ISSUE THREAD

**Issue by nestlelatte** [shadowsocks/shadowsocks-windows#1697]
Version: Latest 4.0.8 with obfs-local 0.0.5
Operating system: Windows10(10.0.16299.248)

Each server added with obfs-plugin will cause a conhost.exe&obfs-local.exe opened in the background.
And I'm sure that there is only one server activated at one time.
If there is one server activated, is multi conhost needed?
Features or bugs 
thx

**Comment by chenshaoju** [comment]
This is a known issue: https://github.com/shadowsocks/shadowsocks-windows/pull/1618#commitcomment-27599331

**Comment by nestlelatte** [comment]
@chenshaoju Thx. Looking forward to next release.
