### ISSUE TITLE
公司内网使用正向代理后无法穿透

### ISSUE THREAD

**Issue by pulllantern** [shadowsocks/shadowsocks-windows#1698]
使用公司的http代理，填入“正向代理”设置后无法连上ss-server。ss-server是利用docker设置在我自己家里的nas上，使用公司代理后，利用proxifier的proxy checker功能发现无法连接ss-server。不填写正向代理，使用proxifier进行设置使用也是一样的情况。一开始以为是公司的防火墙问题，后来使用GAE的localhost:8087端口作为http代理端口也是一样的情况，求解决方案。手机wifi开热点给公司电脑，去掉正向代理是可以正常连线ss-server的。

**Comment by chenshaoju** [comment]
请确保你所使用的HTTP代理支持HTTPS(Secure)连接（不是指HTTPS代理），以CCProxy为例，箭头所指的这两个选项都需要选上。

![image](https://user-images.githubusercontent.com/515763/36624673-1744d2c2-194d-11e8-89c5-f3e9066d4abd.png)

**Comment by pulllantern** [comment]
非常感谢。但是由于是公司代理，不是我自己设定的，因此无法确认是否支持这些连接。有验证的方法吗？

**Comment by chenshaoju** [comment]
https://www.baidu.com ，能打开吗？注意，是 https:// 。

**Comment by pulllantern** [comment]
这个打开没有问题的。下面是proxy checker的结果，https 协议ok的。我现在就是用代理登陆的github，所以应该没问题啊……
![image](https://user-images.githubusercontent.com/15796963/36625072-5a69397a-1953-11e8-812d-c911db5a49b0.png)

**Comment by pulllantern** [comment]
但是在proxifier中使用这个代理作为前置测试shadowsocks，就给了下面的这个错误提示。
![image](https://user-images.githubusercontent.com/15796963/36625116-44a7edc4-1954-11e8-957f-76bee2d19bb4.png)

**Comment by chenshaoju** [comment]
你设置的是HTTPS代理，但是图中日志显示的是 www.baidu.com:80 ，应该是HTTP。

注意：“HTTP代理”和“HTTPS代理”，是两个东西，你需要使用支持HTTPS协议的HTTP代理。

**Comment by pulllantern** [comment]
受教了，谢谢，我再仔细确认一下，谢谢～～～

**Comment by pulllantern** [comment]
我想还有个可能是透明代理对于端口的访问问题。家中nas上的ss-server利用路由转发的端口是公网的12000端口，也许代理无法访问这个端口。想设置成80或者8080伪装成web，但是你懂的，电信把这些端口都封闭了……

**Comment by chenshaoju** [comment]
有一个 node.js 平台的第三方的开源应用可以将HTTPS代理转换为HTTP代理： https://github.com/theikkila/https2http ，你可能得自己研究一下了，我没使用过。

**Comment by pulllantern** [comment]
谢谢，我立刻去看一下。现在电脑上的GAE代理倒是可以访问非80或者443端口，但是不支持https协议，您提供的这个应该可以用，我研究一下。

**Comment by wongsyrone** [comment]
你有proxifier就不用内置的前置代理功能了，写好规则就行了，我也是内网环境

**Comment by pulllantern** [comment]
我两个方法都尝试了，都不行啊。也有可能是我自己架的ss-server有问题，现在没有办法判断，直连是没问题的，头疼。

**Comment by pulllantern** [comment]
我两个方法都尝试了，都不行啊。也有可能是我自己架的ss-server有问题，现在没有办法判断，直连是没问题的，头疼。

**Comment by chenshaoju** [comment]
直连没问题的话，基本上确认是你的代理的问题。

核心问题还是因为你内网的代理是HTTPS的，不是HTTP的。

**Comment by pulllantern** [comment]
貌似的确是这样……
![image](https://user-images.githubusercontent.com/15796963/36628470-d8672b6e-1987-11e8-915d-a93f2e067a40.png)

**Comment by chenshaoju** [comment]
看起来这个HTTPS2HTTP不支持HTTPS。。。估计没戏了。
