### ISSUE TITLE
shadowsocks非预期错误 问题，无法启动

### ISSUE THREAD

**Issue by MinhLee92** [shadowsocks/shadowsocks-windows#1701]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
Shadowsocks-4.0.8.zip

### Environment(Operating system, .NET Framework, etc)
.NET Framework 4.7.1

### Steps you have tried
先下载 Shadowsocks,之后安装 .NET Framework 4.7.1, 最后打开 Shadowsocks客户端

### What did you see instead?
弹出两个错误窗口，第一个是 显示 非预期错误， 第二个是 出现了一个问题，导致程序正常工作，请关闭改程序。
### Config and error log in detail (with all sensitive info masked)

![360 16290621171361](https://user-images.githubusercontent.com/36792777/36630966-b111c664-19aa-11e8-8544-fb2dfcd6761f.png)
![360 16320218455449](https://user-images.githubusercontent.com/36792777/36630967-c9e3c930-19aa-11e8-99dd-bfbd6a3a8232.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1573

**Comment by MinhLee92** [comment]
Thanks

**Comment by MinhLee92** [comment]
resolved,  Great
