### ISSUE TITLE
4.0.8下载PAC list失败，提示

### ISSUE THREAD

**Issue by wenkyzhang** [shadowsocks/shadowsocks-windows#1702]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.08

### Environment(Operating system, .NET Framework, etc)
win7 旗舰版SP1 .NET framework4.6.2

### Steps you have tried
1. 下载了最新的4.0.8，替换原有的文件
2. 执行shodowsocks.exe
3. 启动成功
4. 选择”PAC“--”从GFWLISTG更新本地PAC“

### What did you expect to see?
PAC更新成功

### What did you see instead?
提示系统找不到”vcruntime140.dll“

### Config and error log in detail (with all sensitive info masked)

运行日志：
> [2018-02-25 15:31:40] System.DllNotFoundException: 无法加载 DLL“libcrypto-1_1.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.OpenSSL.EVP_get_cipherbyname(Byte[] name)
   在 Shadowsocks.Encryption.OpenSSL.GetCipherInfo(String cipherName)
   在 Shadowsocks.Encryption.Stream.StreamOpenSSLEncryptor.initCipher(Byte[] iv, Boolean isEncrypt)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.SendToServer(Int32 length, AsyncSession session)
   在 Shadowsocks.Controller.TCPHandler.StartPipe(AsyncSession session)
[2018-02-25 15:31:40] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1679
