### ISSUE TITLE
支持SIP008在线配置

### ISSUE THREAD

**Issue by AnnAngela** [shadowsocks/shadowsocks-windows#1703]
如同 ShadowsocksR 一样，这样当服务器提供方变更服务器地址时可以自动变更本地服务器设定。

**Comment by AnnAngela** [comment]
感觉都没人关注这个的=。=

**Comment by celeron533** [comment]
建议使用ssr

**Comment by AnnAngela** [comment]
但是我感觉 SSR 已经走向邪教了=。=

**Comment by lkmvip** [comment]
现在的订阅好像都是按照SSR格式写的

**Comment by pongfcnkl** [comment]
这个只对商家有用
自己搭建不分享的话一般一个URL可以长期使用没必要用订阅
还不如把精力用在混淆上。

**Comment by AnnAngela** [comment]
没错就是用于梯子平台变更服务器列表时用的……所以还是很希望能添加进去的……

**Comment by Amayadream** [comment]
不是每个人都有精力去搭建和维护自己的节点, 为了节约时间很多人还是会选择购买服务商提供的服务, 这种情况下订阅功能是非常重要的, 所以我赞成[加入订阅功能]的提议

**Comment by celeron533** [comment]
订阅的服务端是商家自己实现的，各有各的实现手法
另外本项目并未与任何商家合作

**Comment by studentmain** [comment]
> 订阅的服务端是商家自己实现的，各有各的实现手法
> 另外本项目并未与任何商家合作

一个折中的方法：提供重新加载配置文件的能力，但不实现任何解析订阅链接的功能。这样可以由独立的程序解析订阅并修改服务器列表。

**Comment by zeeqy** [comment]
订阅功能很有用。我就是自用，因为自用所以经常关注打折信息，常常换服务器，每次都要重新调整所有设备上的配置，很麻烦。

**Comment by midle110** [comment]
一帮商家充点钱给这个开源事业吧
天天想着人家免费给你开发。

ss意图就是个人搭建使用
商用自己找人去开发

**Comment by studentmain** [comment]
一些早期的技术试验，似乎并不兼容于常见订阅：https://github.com/shadowsocks/shadowsocks-windows/tree/with_online_config

基于目前讨论结论和问题热度，重开但标记为wontfix

**Comment by studentmain** [comment]
https://github.com/shadowsocks/shadowsocks-android/pull/2392

隔壁安卓版加了，并且把大版本号滚到了5。

就个人而言还是不想加，订阅协议未标准化。而且考虑到目前代码质量（一点也不MVC的MVC），即使要加也要等重构之后加。

**Comment by studentmain** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/89 关于订阅标准的一则草案

**Comment by studentmain** [comment]
基于https://github.com/shadowsocks/shadowsocks-org/issues/89#issuecomment-578396069

> We're finalizing the online config support......

考虑列入v5更新计划

**Comment by AnnAngela** [comment]
没想到一年前的wontfix居然还能重见天日（x

**Comment by faydanube** [comment]
1. 直接使用 SSR 订阅进行更新
2. 然后复制 SSR 的 `gui-config.json` 覆盖到 SS
3. 在 SS 直接支持订阅功能之前，使用此方法可以完美解决。
