### ISSUE TITLE
feature request ; group servers to allow load balancing per group

### ISSUE THREAD

**Issue by wt72** [shadowsocks/shadowsocks-windows#1704]
I'm using several Shadowsocks servers in different location. Each location has several servers.

Currently when you use 'load balancing' it would cycle through ALL servers, instead it should stick with a group of servers. 

Example:

Group "Asia"
 server HongKong 1
 server HongKong 2
 server HongKong 3

Group "Europe"
 server Germany 1
 server Germany 2
 server France 1

Group "US west"
 server Los Angeles 1
 server San Diego 1
 server San Jose 1
 server San Jose 2

Group "US East"
 server New York

When choosing "load balancing" or "high availability" SS now cycles through all servers, while some of them might be far away or slow. Would be nice to be able to select a 'group'.

**Comment by studentmain** [comment]
#1372
