### ISSUE TITLE
a new issue :  invalidoperationExeption

### ISSUE THREAD

**Issue by drduan** [shadowsocks/shadowsocks-windows#1706]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
    
![_20180226140642](https://user-images.githubusercontent.com/7875572/36655622-bf3749b2-1afe-11e8-85fd-0d430e0b93ad.png)
Shadowsocks-4.0.7
### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1490
