### ISSUE TITLE
Is there a distribution of win32 which can be used in win7 32bit

### ISSUE THREAD

**Issue by albertjone** [shadowsocks/shadowsocks-windows#1707]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
 shadowsocks4.07

### Environment(Operating system, .NET Framework, etc)
 win7 34bit 

### Steps you have tried
i've tried shadowsocks4.07 in win7 34bit ,but it can't work and prompt: need newer version of .netframework than 4.6.2,but when i've installed the 4.6.2version , it prompts newer version of .netframework need

### What did you expect to see?
well worked

### What did you see instead?
i've tried shadowsocks4.07 in win7 34bit ,but it can't work and prompt: need newer version of .netframework than 4.6.2,but when i've installed the 4.6.2version , it prompts newer version of .netframework need

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
Please open Control panel, Program, Uninstall a program, Can you find a program name "Microsoft .NET Framework 4.6.2 (or with SDK)"?

If possible, please attach a screenshot.

![image](https://user-images.githubusercontent.com/515763/36659011-f80d9804-1b0d-11e8-9453-631b8a708471.png)

**Comment by celeron533** [comment]
Current release is x86
You may need to install .net framework as @chenshaoju mentioned
