### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by 0winner0** [shadowsocks/shadowsocks-windows#1708]
**_

- [ ] 这个到底怎么用，给个链接，关于怎么使用的。还有，使用这个软件后免费吗？

_**

**Comment by chenshaoju** [comment]
你可以在 https://github.com/shadowsocks/shadowsocks-windows/wiki/Shadowsocks-Windows-使用说明 找到使用说明，Shadowsocks for Windows 是开源免费的，但是你可能需要自行搭建服务器或购买第三方的服务，这些服务不受 Shadowsocks for Windows 控制，也没有关系。
