### ISSUE TITLE
[feature] auto switch on or off depending on connected Wi-Fi SSID

### ISSUE THREAD

**Issue by jiakai1000** [shadowsocks/shadowsocks-windows#1710]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.8

### Environment(Operating system, .NET Framework, etc)
Windows 10 pro x64

### What did you expect to see?
auto switch on or off depending on connected Wi-Fi SSID

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
no plan
