### ISSUE TITLE
请教：我本地环境本身需要走代理服务器上网，并且需要用户名密码，如何配置ssclient呢？

### ISSUE THREAD

**Issue by uemahra** [shadowsocks/shadowsocks-windows#1712]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
最新版ss（4.0.8）

### Environment(Operating system, .NET Framework, etc)
win10，.net够，程序正常，只是不会设置

### Steps you have tried
尝试了Proxifier

### What did you expect to see?
连上。。。开心

### What did you see instead?
连不上。。。惆怅

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
关于密码认证的代理服务器，目前有一个版本，但是由于冲突尚未解决，暂时无法提供，请等待后续版本发布： https://github.com/shadowsocks/shadowsocks-windows/pull/1214

**Comment by uemahra** [comment]
谢谢，明白了，那有什么workaround的方法吗，比如我用一个能填密码的软件走公司网络的代理，然后这个软件分出来一个不要密码的代理填到ss的正向代理设置里

**Comment by chenshaoju** [comment]
Proxifier应该可以。。。但是我没测试过。。。。

**Comment by wukakal** [comment]
可以试试 CNTLM，

**Comment by studentmain** [comment]
#2260
