### ISSUE TITLE
阿里云centos搭建SS，出现500 Internal Privoxy Error，新手求教

### ISSUE THREAD

**Issue by suagrXu** [shadowsocks/shadowsocks-windows#1713]
1.浏览器错误信息
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

2.
在实例中运行_      netstat -noa | grep :443
结果：
tcp6          0    0:::8990    :::*   LISTEN  off(0.00/0/0)**

**Comment by chenshaoju** [comment]
如果你用的是libev，请确保你的 ss-server 是否启动了。

**Comment by echoscope** [comment]
我建议换一个服务器提供商试一试

**Comment by ganwen1994** [comment]
不要使用阿里雲搭建此類服務，喝茶雖然不至於，但是被監控，很容易被墻。

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks/issues/1180
