### ISSUE TITLE
为什么在windows10下，只有全局模式才可用，切换成pac就不能用了，mac和Android都正常

### ISSUE THREAD

**Issue by EndlessTJ** [shadowsocks/shadowsocks-windows#1714]
## 之前可以用，这几天突然就变成这样了

**Comment by chenshaoju** [comment]
你是否有使用爱奇艺？ https://github.com/shadowsocks/shadowsocks-windows/issues/1689#issuecomment-366937201

**Comment by EndlessTJ** [comment]
@chenshaoju 你是指网页版的，还是客户端。用过网页版的。客户端没用过

**Comment by EndlessTJ** [comment]
看之前你让访问那个看ip的地址，在pac模式下是公网IP，全局模式下是服务器io

**Comment by jjandnn** [comment]
@EndlessTJ pac当然是公网ip，这个没问题。mac和安卓都可以，就说明，服务端，路由，没问题。是win10的设置问题。1，浏览器，2，防火墙，3，hosts，4，dns。
dns指定114、114、114、114，备用8888。hosts确保全是版本，没任何添加。防火墙，不用说了，国产除火绒外，其余都卸载。浏览器，用360的断网急救独立版（绿版，千万别用他家别的东西），刷一遍。然后，按火绒的垃圾清理，防止新版chrome问题多，css加载的毛病造成无法翻的假象。

**Comment by jjandnn** [comment]
忘说了，这样还有问题，浏览器，换一个。

**Comment by EndlessTJ** [comment]
@jjandnn    谢谢！我试试

**Comment by kusion** [comment]
我在win10上，两个模式都用不了。iphone上用的另外一种ss可以

**Comment by chenshaoju** [comment]
请看一下Windows 10 的 设置，网络和 Internet，代理，这里是什么样子的？

![2018-03-01](https://user-images.githubusercontent.com/515763/36824646-65d5d748-1d3e-11e8-83fd-1cb86084d48a.png)

**Comment by EndlessTJ** [comment]
@chenshaoju 用全局模式时候，下面的手动代理设置会自动打开

**Comment by chenshaoju** [comment]
@EndlessTJ 那么PAC模式呢？

**Comment by EndlessTJ** [comment]
@chenshaoju 我好想知道原因了，使用chorme会自动地位到服务器的地址，搜索后缀是www.google.com.ph。把.ph改成.hk就可以正常使用了。只有window有这种情况。mac也是.ph就没有问题

**Comment by chenshaoju** [comment]
Odd，如果可能，从菜单里的GFWList更新一下PAC看看是否还会有该问题。

**Comment by EndlessTJ** [comment]
@chenshaoju 是哪个问题，更新后可以用了。谢谢
