### ISSUE TITLE
4.0.8版本无法访问内网ip 如192.168.3.1

### ISSUE THREAD

**Issue by Se7enZHOU** [shadowsocks/shadowsocks-windows#1716]
如题，开了全局模式后可以访问外网可是不能访问内网ip，无法管理路由器和其他内网设备？

怎么解？

**Comment by chenshaoju** [comment]
这种情况通常建议使用PAC模式，但是如果你坚持用全局模式，并且是使用浏览器管理的话，那么请尝试在浏览代理设置的部分将你的内网IP加入 No Proxy列表。

比如，你的局域网IP段是 192.168.1.1~192.168.1.254，那么加入 192.168.1.0/24 即可。

![image](https://user-images.githubusercontent.com/515763/36879801-6e4b1646-1e00-11e8-975f-9fa3899e74f7.png)

**Comment by 7SevenZHOU** [comment]
抱歉，我的表述有错误，我的真实意图是访问ss服务器端的内网。
比如我在境外有个树莓派当作ss服务器，我想通过ss客户端管理树莓派所在的内网设备（如路由器）。
这种情况下我试了PAC和全局都不行。

**Comment by 7SevenZHOU** [comment]
ios端的potatso lite客户端可以实现

**Comment by celeron533** [comment]
看看你的服务器防火墙设置有没有屏蔽内网直接访问

**Comment by chenshaoju** [comment]
你的树莓派能从你的客户端被访问到吗？如果能，在浏览器里强制指定代理看看（不启用SS的系统代理，直接在浏览器里指定本机SS的代理，127.0.0.1:1080）。

**Comment by gfj7817** [comment]
@chenshaoju  我的情况和他一样，但是老版本不存在此问题。
具体架构是这样，我有个服务器做了ss server，这台ss server内网地址为：192.168.1.11，然后通过端口映射把ss server的端口映射出去，我用client去连接，可以正常连接，也可以使用server的网络，我的client的ip地址也显示和ss server的公网ip地址一样，但是我想访问和ss server相同内网的服务a：192.168.1.12的服务，却无法访问。此问题在4.0.7版本上也有同样问题，在某个老版本上却不存在此问题。由于原老版本已更新，不能确定是哪个版本，晚点尝试出来再告知你。

**Comment by celeron533** [comment]
开了全局代理后还有这个问题？
另外在浏览器设置里需要排除掉“跳过局域网地址”

**Comment by gfj7817** [comment]
打开了全局模式还有这个问题，4.0.6 版本也有此问题。
我用的chrome浏览器，没有办法设置需要排除掉“跳过局域网地址”
安卓的shadowsock一直不存在此问题。

**Comment by gfj7817** [comment]
如果你需要测试环境，我可以提供个环境给你测试。

**Comment by celeron533** [comment]
>我用的chrome浏览器，没有办法设置需要排除掉“跳过局域网地址”

去IE那边修改系统全局代理选项，参考@chenshaoju 的截图

**Comment by gfj7817** [comment]
@celeron533 我觉得你还没有明白我的意思，我的意思是在开启全局代理模式的情况下，不但可以通过ss server访问公网，还可以访问ss server服务器的的内网，而不需要访问本地的内网。
经测试，上个可用版本为：3.3.6 ，之后的版本均不可用。
请作者看看这个版本后有什么这方面的限制吧，感谢作者的维护。

**Comment by celeron533** [comment]
了解情况了
>这种情况下我试了PAC和全局都不行
打开了全局模式还有这个问题，4.0.6 版本也有此问题

但是我这边开启全局代理（且不绕过局域网地址）后直接访问服务器资源没有问题。

**Comment by gfj7817** [comment]
我的ss server服务器的内网ip为192.168.1.11，我想通过ss server服务器去访问和ss server一个内网的另外服务器192.168.1.20，或者内网的网关路由192.168.1.1 均不可以。我不知道什么情况造成。
但是我使用3.3.6版本，就可以直接访问，无需设置任何东西。

**Comment by gfj7817** [comment]
我的ss server服务器的内网ip为192.168.1.11，我想通过ss server服务器去访问和ss server一个内网的另外服务器192.168.1.20，或者ss server的内网网关路由192.168.1.1 均不可以。我不知道什么情况造成。
但是我使用3.3.6版本，就可以直接访问，无需设置任何东西。

**Comment by celeron533** [comment]
@gfj7817 另外请注意ss默认只是web代理，如果你是向通过这个访问内网其他机器的telnet ssh等是不可行的

**Comment by gfj7817** [comment]
@celeron533 
其实web代理也摆脱不了是tcp的代理，其实udp的协议也支持的。
已换回3.3.6版本，可以正常使用。感谢你们的分享。

**Comment by celeron533** [comment]
>已换回3.3.6版本，可以正常使用

这个确实比较神奇

**Comment by studentmain** [comment]
@celeron533 3.3.6是WinINET的最后一个版本。之所以sysproxy的版本不能用：
https://github.com/shadowsocks/shadowsocks-windows/blob/ac45b44c097c084c5ae0a897bf82198aa71867ba/shadowsocks-csharp/Util/SystemProxy/Sysproxy.cs#L47

**Comment by celeron533** [comment]
@studentmain sysproxy也是调用wininet，可能里面的实现还是有问题。不过我在win10下我这边测试没问题

**Comment by wsldl123292** [comment]
我在服务端的电脑上可以访问172，192，10网段的服务，但是在家里是用ss客户端连接服务端后，全局代理，可以访问内网172，192的服务，但是访问不了10网段的服务，为什么呢

**Comment by studentmain** [comment]
@wsldl123292 SS正常情况只能代理使用系统代理的，换句话说，命令行ping啊， minecraft这种直接用socket的游戏啊，是不会被代理的。
用什么工具访问什么服务，两边网络拓扑如何。

**Comment by wsldl123292** [comment]
> @wsldl123292 SS正常情况只能代理使用系统代理的，换句话说，命令行ping啊， minecraft这种直接用socket的游戏啊，是不会被代理的。
> 用什么工具访问什么服务，两边网络拓扑如何。

就是浏览器访问一个域名端口的web项目，ss服务端主机可以访问，客户端就无法访问，但是其他ip段的内网web项目可以访问

**Comment by fengshengxie** [comment]
> > @wsldl123292 SS正常情况只能代理使用系统代理的，换句话说，命令行ping啊， minecraft这种直接用socket的游戏啊，是不会被代理的。
> > 用什么工具访问什么服务，两边网络拓扑如何。
> 
> 就是浏览器访问一个域名端口的web项目，ss服务端主机可以访问，客户端就无法访问，但是其他ip段的内网web项目可以访问

回到3.36版本就可以用了。我也有这个需求。新的版本好像都无法访问。

**Comment by celeron533** [comment]
@fengshengxie 在发出访问请求的时候，log里有变化吗？IE的internet选项中有没有绕过局域网地址？

**Comment by hhmob** [comment]
我这边也遇到了一样的问题，SS服务器在那边的局域网是192.168.1.136，我想连上SS以后，在3.3.6版本的SS客户端选全局代理，是可以正常访问SS服务器所在局域网的路由器192.168.1.1的。但是当升级到最新的4.1.6就不能了，这个非常非常好重现，请尽快修复一下，感谢

**Comment by xman55555** [comment]
同样有这个问题,192段和172段的局域网的都访问不了...很奇怪...

**Comment by polym** [comment]
支持的，需要打开「Internet 属性 -> 连接 -> 局域网设置 -> 高级」，在「例外」中把需要用到的网段去掉

**Comment by robben16** [comment]
今天遇到了同样的问题，google了一下找到了这里，最后还是下了336版本用了，希望作者能够持续关注这个问题

**Comment by database64128** [comment]
In a nutshell, if you want to connect to your Shadowsocks server's private IPv4 ranges, don't use the GUI to set your system proxy. Instead you should manually set your system's proxy settings without adding private IPv4 ranges to the exception list. I don't think any changes should be made on our side, as it would make the system proxy settings overly complicated.

**Comment by pengliheng** [comment]
加白名单啊

**Comment by pengliheng** [comment]
我有多台电脑, 想在一台电脑上装 shadowsock, 其他电脑都可以通过局域网 ip:port  代理 翻墙. 但是现在好像不行

**Comment by chenshaoju** [comment]
如果启用了允许其他设备连入，应该没有问题。

如果仍然不行，检查一下Windows自带的网络防火墙？

**Comment by pengliheng** [comment]
我不是 window 我是 macos,

**Comment by chenshaoju** [comment]
此 Issue 主要还是针对Windows版本的疑难解答和错误报告，我没有Mac……

**Comment by Jonnyan404** [comment]
想访问 ss-server 所在机器的内网 IP 段,目前看下来,还是只能使用 3.3.6 版本才能实现了.
新版本下,有没有哪位知道如何配置啊?

**Comment by zhyaof** [comment]
这个问题，今天我抓包确认了下，原因是这样的。比如我的 ss 服务器 IP 是 1.2.3.4
同时服务器有另一张内网网卡 192.168.1.1 和内网网段 192.168.0.0/24，此时客户端访问内网服务 192.168.0.2
抓包看到的效果是：1.2.3.4 -> 192.168.0.2
然后包从内网网卡传过去了，192.168.0.2 收到包之后，会回 1.2.3.4，因为 1.2.3.4 是公网，从公网出去了，nat 出去了，这个不符合预期。
ss 服务器应该用 192.168.1.1 去访问 192.168.1.2，内网服务回包到 ss 服务器 192.168.1.1，然后通过公网返回 ss 客户端。
应该代码有某个地方访问的时候 bind 了客户端来的网卡 ip，使客户端的包从哪个接口来就从哪个接口出去。
我这边临时的解决办法是，在 192.168.0.2 上加一条路有，ip route add 1.2.3.4/32 via 192.168.0.1，强制内网服务返回公网的数据包走内网，但这样不现实，有的内网服务太多了，而且不一定有权限加路由。

**Comment by zhyaof** [comment]
review 了下源码，并实测，config json 添加以下配置后，就可以访问内网了：
```
    "out_bind": "0.0.0.0",
    "ignore_bind":"127.0.0.1"
```
out_bind 就是 ss 访问的时候绑定哪个地址，0.0.0.0 就是任意地址，由操作系统和路由选择。
ignore_bind 就是 bind 到这个地址时，忽略，默认是含有内网导致无法访问的，这个改成 127.0.0.1，如果需要访问 ss 本机服务的话，就不要加上了。

**Comment by weixiaobao124** [comment]
经测新的版本不行，换成3.3.6就可以了
