### ISSUE TITLE
win10 好像只能网页走代理，程序都不行，大家是这样吗？

### ISSUE THREAD

**Issue by hkdanielp** [shadowsocks/shadowsocks-windows#1717]
安卓和ios都可以，win10连上后哪怕是全局代理都不行，浏览器无问题。可是程序不行，流量不走ss客户端。

**Comment by hkdanielp** [comment]
pac 模式和全局模式好用浏览器都是实时设置，就是程序不走代理可惜。。。。。。。。。。

**Comment by chenshaoju** [comment]
请具体描述一下是什么程序？叫什么名字？

**Comment by hkdanielp** [comment]
例如，像应用商店。

**Comment by chenshaoju** [comment]
Windows 10的UWP应用可能还不支持系统代理或PAC模式，这是因为操作系统的限制，具体请参考： https://github.com/shadowsocks/shadowsocks-windows/issues/897

**Comment by shuangxi2006** [comment]
Win10自带的邮件，不能添加Google账户，添加时会出现连接超时。
![20180303161714](https://user-images.githubusercontent.com/6763123/36932054-6bbae3bc-1efe-11e8-82ad-0224384fe428.png)

**Comment by chenshaoju** [comment]
@shuangxi2006 请阅读：https://github.com/shadowsocks/shadowsocks-windows/issues/897
