### ISSUE TITLE
非预期错误，怎么解决

### ISSUE THREAD

**Issue by luyaov587** [shadowsocks/shadowsocks-windows#1722]
![tim 20180304142653](https://user-images.githubusercontent.com/28943461/36942845-1f7414e6-1fb8-11e8-9513-2dd3e0e80c4a.png)

**Comment by chenshaoju** [comment]
请使用最新的 4.0.8 版本，如果仍然不行，请退出SS，然后删除 Shadowsocks.exe 所在目录下的 ss_win_temp 文件夹后再试。

**Comment by luyaov587** [comment]
谢谢帮忙已解决，升级了新版本，之前是4.0.4，再次感谢
