### ISSUE TITLE
还是会启动2个obfs-local进程

### ISSUE THREAD

**Issue by nasaboy** [shadowsocks/shadowsocks-windows#1723]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.8

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
windows7 64bit  .net 4.7.1

### Steps you have tried / 操作步骤
启动shadowsocks

### What did you expect to see? / 期望的结果
混淆插件启动1个进程

### What did you see instead? / 实际结果
如果添加的2个服务器带了混淆参数，混淆插件会启动2个进程，我看4.0.8是有修复这个bug的，但是实际是没有。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2018-03-04 22:42:15] Started SIP003 plugin for 35.**.*.**:** on 127.0.0.1:59003 - PID: 1760
[2018-03-04 22:42:15] Started SIP003 plugin for **.**.com:*** on 127.0.0.1:59004 - PID: 3200
[2018-03-04 22:42:15] Shadowsocks started
[2018-03-04 22:42:15] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
=========================

**Comment by chenshaoju** [comment]
该问题已知，等待修正： https://github.com/shadowsocks/shadowsocks-windows/pull/1618#commitcomment-27599331

**Comment by nasaboy** [comment]
谢谢少举，那关了。
