### ISSUE TITLE
有没有计划将ss可以用到的插接集成到ss里面 如obsf

### ISSUE THREAD

**Issue by Quiet95scholar** [shadowsocks/shadowsocks-windows#1724]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
你好，目前的SS对于ktcp、simple_obfs都是使用插件的形式支持的，这样更新比较方便，也不至于导致客户端膨胀。

如果你正在寻找插件，可前往下列地址获取：
kcptun： https://github.com/shadowsocks/kcptun
simpe_obfs：https://github.com/shadowsocks/simple-obfs
