### ISSUE TITLE
希望可以支持服务器url批量导入

### ISSUE THREAD

**Issue by chuhe0** [shadowsocks/shadowsocks-windows#1727]
ss-win 4.0.8  
测试 服务器url 批量导入，只能识别并导入第一个服务器url
希望可以支持批量导入

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1703

**Comment by chuhe0** [comment]
我没想订阅，只是导入url 而已呀   我没那么奢侈  
只是单个url——>批量url

**Comment by chuhe0** [comment]
那是真的奇怪了……我粘贴到写字板就是这样一行一行的呀

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chuhe0** [comment]
感谢，我回头开电脑测试下

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chuhe0** [comment]
感谢楼上  已解决  是我这边的链接格式问题
