### ISSUE TITLE
年后PC端连ss好像被限速了，同样的网络，安卓端可以跑满速

### ISSUE THREAD

**Issue by Simon-CN** [shadowsocks/shadowsocks-windows#1728]
用的是最新的客户端，网速到100k之后就上不去了，但是用手机连同个路由的WiFi就可以跑到满速，搞得我有点不明觉厉，求个大佬告诉我怎么回事呀。。。

**Comment by chenshaoju** [comment]
你好，我刚测试了一下，速度没有明显变化。很高可能性和你的网络环境有关。

如果你是自己搭的服务端，请尝试配合simple_obfs并绑定在80端口试试，可能和你的运营商的QoS有关。

![image](https://user-images.githubusercontent.com/515763/37128702-49a491cc-22b6-11e8-8334-7e3602eaf7fb.png)

**Comment by 508869994** [comment]
我也有同样的情况！

**Comment by haorld** [comment]
我也是，年后突然速度特别慢，重启过shadowsocks服务器，也修改过端口，均没有改善。

**Comment by pexcn** [comment]
加钱换更好的 VPS 你会卡？
![1517061007774666](https://user-images.githubusercontent.com/4590439/37342559-e916ea78-26ff-11e8-99ab-a7613919d695.jpg)

**Comment by Simon-CN** [comment]
测了一波，貌似是教育网出口炸了。。

**Comment by celeron533** [comment]
Windows下的obfs混淆程序有一定的性能损失

**Comment by celeron533** [comment]
遇到过类似情况，windows10有时候会抽筋降速，重启后正常

**Comment by yutian155** [comment]
同求， 我的也是安卓跑满速上传的，pc的只能100k，不知道什么原因求教！！

**Comment by chafer516** [comment]
同求， 我的也是，带宽100M，安卓跑78M，pc的只能跑10M，win10系统。SS开全局模式，浏览器通过获取系统代理上网。

**Comment by chenshaoju** [comment]
我JP的服务器被Wa11了，现在用的UK的服务器，使用SS aes-256-gcm + GoQuite 443，速度尚可：
![image](https://user-images.githubusercontent.com/515763/47058015-c78e8900-d1f5-11e8-8b26-a08222de548a.png)

@chafer516 你可以尝试重置一下TCP/IP和Winsock看看，是否有改善：https://github.com/shadowsocks/shadowsocks-windows/issues/1953#issuecomment-411334801

**Comment by chafer516** [comment]
问题解决了，https://jingyan.baidu.com/article/fec4bce28bb1c9f2618d8bb2.html
指定入站TCP吞吐量级别”，选择最大级别为3，

**Comment by C0DETyper** [comment]
下载 Windows版锐速 上传直接跑满

**Comment by Remmml** [comment]
你好，请问问题解决了吗，我也有这样的问题
