### ISSUE TITLE
 非预期错误 - Text limited to 127 characters

### ISSUE THREAD

**Issue by 21wan** [shadowsocks/shadowsocks-windows#1731]
![default](https://user-images.githubusercontent.com/24545756/37239357-1e746872-2475-11e8-958d-9e2b8c1134dd.jpg)
在我放入gui-config.json文件后打开 就会出现这类错误
错误如上图
而删除则可以正常打开
gui-config.json内容如下图
![nrniuvf sqzm77kvg k62op](https://user-images.githubusercontent.com/24545756/37239394-bf703486-2475-11e8-9b6a-052fa7432b86.png)
错误日志如下
> Shadowsocks.Program.Main()[2018-03-10 15:17:04] [E] System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: Text limited to 127 characters
   在 Shadowsocks.Util.ViewUtils.SetNotifyIconText(NotifyIcon ni, String text)
   在 Shadowsocks.View.MenuViewController.UpdateTrayIcon()
   在 Shadowsocks.View.MenuViewController..ctor(ShadowsocksController controller)
   在 Shadowsocks.Program.Main()

**Comment by celeron533** [comment]
Remarks 太长

**Comment by 21wan** [comment]
remakes改至4中+1数字还是不行
是server字符太多的原因么

**Comment by 21wan** [comment]
感谢

**Comment by celeron533** [comment]
当然服务器地址太长也是个原因

**Comment by celeron533** [comment]
Refined in 257448a80a0d4f448c2770fe4c9d1aaadaea574b
