### ISSUE TITLE
报错！

### ISSUE THREAD

**Issue by 508869994** [shadowsocks/shadowsocks-windows#1733]
![s _ f mu g3fk8r5z8r](https://user-images.githubusercontent.com/24713005/37254730-ec32e0ec-257c-11e8-97ae-11be0fb6bc9b.png)

**Comment by chenshaoju** [comment]
这意味着你下载的 simple-obfs 缺少 msys-2.0.dll 文件，请确保是从 https://github.com/shadowsocks/simple-obfs/releases 获取的 simple-obfs 。

**Comment by pexcn** [comment]
发 issue 发得就好像你跟大爷似的，别用感叹号了
