### ISSUE TITLE
4.0.8 版本win10 表现为恶意文件

### ISSUE THREAD

**Issue by chenyeah** [shadowsocks/shadowsocks-windows#1734]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.8

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10 版本 10.0.16299.248

### Steps you have tried / 操作步骤
打开4.0.8版本会出现
![tim 20180312224627](https://user-images.githubusercontent.com/22478003/37290551-7ffa6ee2-2647-11e8-9322-0b004d89d576.png)
然而4.0.7 版本则不会出现 我的windows defender已经关闭了

**Comment by chenshaoju** [comment]
你好，我刚测试了一下，并没有该问题，Windows 10 x64 1709 16299.251，Windows Defender 4.12.17007.18022。

另外，刚上传到VirusTotal进行检查，未发现问题：
https://www.virustotal.com/en/file/286f65de52031116b93665d6aadbe56f0e0a6662315c1d4dfb7ddd78cbc179ae/analysis/1520869000/

请确保你获取的4.0.8版本的 Shadowsocks.exe 的校验码符合发布页面的内容：
```
MD5: BC47339FC21AB79434E7FC1781D84A50
SHA1: 0B071773FC91284FB6FACD65BB936DB3310194DD
SHA256: 286F65DE52031116B93665D6AADBE56F0E0A6662315C1D4DFB7DDD78CBC179AE
SHA512: 28C6CC93B918C59C72E49F5F1A44E521830780F7C6BB57CFB2E8D36FDCE1D5624EFC7BFC329DFA84453DE8C51B2C4CF1291C6B1F9845705BE598771B9D760083
```

**Comment by chenyeah** [comment]
![image](https://user-images.githubusercontent.com/22478003/37316929-e3dd7ea4-269c-11e8-943b-0c96653880ea.png)
校验码是符合的 我都是都是github 发布页面下载的

**Comment by chenyeah** [comment]
我再看看是不是电脑其他问题 谢谢您的解答

**Comment by chenshaoju** [comment]
你的电脑是否在域（活动目录）里？或者说，该电脑是普通网络环境还是企业网络环境？

**Comment by chenyeah** [comment]
因为最近电脑炸了 重新装了系统 系统更新全部完成后 才开始装软件，网络是家里普通网络。运行4.0.7版本则没有问题，一运行4.0.8 就会有恶意文件提示，VC++ 环境 都装了 不存在依赖问题！杀毒软件就装了火绒，可火绒扫描该文件也没有报毒！ 我也是无法了！

**Comment by chenshaoju** [comment]
请尝试右击 Shadowsocks.exe ，点击属性，能否看到一个叫“解除锁定”的按钮？如果能，点一下，然后再试。

类似下图（以Chrome为例）：
![image](https://user-images.githubusercontent.com/515763/37318431-692e8b36-26a5-11e8-913c-244543924fef.png)

**Comment by celeron533** [comment]
4.0.8更新了libsscrypto库，可能会导致部分杀毒软件的启发式病毒扫描误报。猜测更新病毒库后会被排除。不放心的话自行编译或者使用老版本

**Comment by chenyeah** [comment]
系统更新到 Windows 10 x64 1709 16299.251 就没有该警告了 😅
