### ISSUE TITLE
win 7系统报丢失d3dcompiler_47.dll错误，并提示反馈

### ISSUE THREAD

**Issue by tom0392** [shadowsocks/shadowsocks-windows#1735]
在win 7系统中使用Shadowsocks-4.0.7版本出现问题截图如下：
先是报 计算机中 丢失d3dcompiler_47.dll，点击确定后显示：
![image](https://user-images.githubusercontent.com/19758369/37332717-6d439918-26e2-11e8-9af9-28e6db1e7215.png)
目前系统中.NET Framework版本为
![image](https://user-images.githubusercontent.com/19758369/37332775-9e2aabf2-26e2-11e8-985f-364f43d7d0e9.png)
已经安装Microsoft Visual C++ 2015 Redistributable (x86)
![image](https://user-images.githubusercontent.com/19758369/37332885-de9e7204-26e2-11e8-987e-1b0502f63a1c.png)
请问有什么解决办法吗？
还有之前的https://portal.shadowsocks.com上不了，我没法登陆自己账户，也没法联系上提供商了。。。
请问有新的地址嘛？

**Comment by chenshaoju** [comment]
你好， shadowsocks.com 不是 Shadowsocks for Windows 的一部分，这是一个独立的SS服务销售商，和 Shadowsocks for Windows 项目没有关系，Shadowsocks for Windows 不以任何形式提供SS服务。

关于问题， d3dcompiler_47.dll 看起来很像你的 DirectX 组件损坏了，如果在等待一段时间（通常是Windows在后台安装补丁，详见： https://github.com/shadowsocks/shadowsocks-windows/issues/1388 ）后重启计算机仍然无效，请尝试重新安装 DirectX 组件看看： https://www.microsoft.com/en-us/download/details.aspx?id=35
