### ISSUE TITLE
使用的时候中途关闭SS在开启SS，火狐浏览器无法科学上网

### ISSUE THREAD

**Issue by pongfcnkl** [shadowsocks/shadowsocks-windows#1736]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.8
### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win7   4.7 火狐58

### Steps you have tried / 操作步骤
使用的时候中途关闭SS在开启SS，开启的火狐浏览器无法科学上网，必须重启火狐才能正常使用，好像chrome没问题

### What did you see instead? / 实际结果
无法科学上网

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

![qq 20180313193606](https://user-images.githubusercontent.com/24273319/37339532-ec1e1336-26f5-11e8-9ddf-9273a478e8b3.jpg)

**Comment by chenshaoju** [comment]
日志中看不出来什么问题，我用Firefox 58.0.2+FoxyProxy，测试未发现该问题。

如果确定退出SS，然后再启动SS仍然无法使用Firefox上网，请检查任务管理器，在退出SS后，进程中的 Shadowsocks.exe 和 ss_privoxy.exe 是否消失。

**Comment by pongfcnkl** [comment]
@chenshaoju 我没装FoxyProxy有没有关系？
退出后这两个进程是消失了。

**Comment by chenshaoju** [comment]
应该没有关系，刷新一下也不行？

另外，你的Firefox的代理设置工作在自动检测还是手动指定？

如果可能，手动指定代理然后再试一次，看看是否还会有该问题？

![image](https://user-images.githubusercontent.com/515763/37390878-680ff942-27a4-11e8-81f1-54edfe7658d9.png)
