### ISSUE TITLE
win7下能用什么版本，4.0.8等新版本win7不支持最新的.net

### ISSUE THREAD

**Issue by wangming19** [shadowsocks/shadowsocks-windows#1737]
win7能有什么版本的ss客户端，手机没问题，但是因为工作需要，换电脑很频繁，我把ss放在了U盘里，但是win7的电脑上没办法用最版本，原来的2.3版本已经连接不上了

**Comment by celeron533** [comment]
安装 .net framework 4.6.2

**Comment by wangming19** [comment]
win7装不上最新的.net啊

**Comment by chenshaoju** [comment]
装不上的提示是什么？

**Comment by wangming19** [comment]
产生阻滞的问题：此操作系统不支持.NET Framework 4.6.2

**Comment by wangming19** [comment]
产生阻滞的问题：此操作系统不支持.NET Framework 4.6.2

**Comment by chenshaoju** [comment]
你的操作系统如果是 Windows 7 的话，请确保安装了SP1补丁。

如果无法确定，请右击计算机，选择属性，然后看这里有无写着 Service Pack 1。

![image](https://user-images.githubusercontent.com/515763/37442653-8a1ad338-2842-11e8-98d8-852c55b23ee1.png)

如果看不到，请安装Widows 7 SP1补丁： https://www.microsoft.com/zh-cn/download/details.aspx?id=5842

**Comment by wangming19** [comment]
是安装6.1的X64版本对吧

**Comment by chenshaoju** [comment]
取决与你的操作系统，如果是 64 位的，则安装 windows6.1-KB976932-X64.exe ，如果是 32 位的，则安装 windows6.1-KB976932-X86.exe 。

**Comment by wangming19** [comment]
非常感谢，FB加你好友了🙏陈先生

**Comment by wangming19** [comment]
SP1更新安装失败，也不折腾了，刚刚一个版本一个版本的挨个儿试，发现3.3即便是没有更新SP1也可以用，反正我自己的电脑用的最新的，在单位办公就无所谓了，用3.3了。不过还是很感谢！chen
