### ISSUE TITLE
win7下无法运行

### ISSUE THREAD

**Issue by DanIsADreamer** [shadowsocks/shadowsocks-windows#1738]
win7重新安装的系统，打开软件报错。
![image](https://user-images.githubusercontent.com/28108039/37388831-eeb134f0-279c-11e8-9c7b-03fa54afb67d.png)

**Comment by chenshaoju** [comment]
请确保安装了最新的 .net framework https://www.microsoft.com/net/download/thank-you/net471 ，并且安装了 x86 版本的 Visual C++ 2015 Redistributable https://www.microsoft.com/en-us/download/details.aspx?id=53840
