### ISSUE TITLE
由于目标计算机积极拒绝，无法连接

### ISSUE THREAD

**Issue by greatbody** [shadowsocks/shadowsocks-windows#1739]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
3.0

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows 7/虚拟机环境/VBox

### Steps you have tried / 操作步骤
在虚拟机中启动SS，无法访问google
在宿主机中启用SS，可以正常访问google
虚拟机采用桥接方式连接到网络

### What did you expect to see? / 期望的结果
期待虚拟机也可以正常访问google

### What did you see instead? / 实际结果
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-03-14 23:49:49] *:443 timed out
[2018-03-14 23:49:50] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 *:443
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-03-14 23:49:52] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 *:443
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-03-14 23:49:54] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 *:443
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
{
  "configs": [
    {
      "server": "*",
      "server_port": 443,
      "password": "*",
      "method": "aes-256-cfb",
      "remarks": "",
      "auth": true
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": false,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "pacUrl": null,
  "useOnlinePac": false,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "logViewer": {
    "fontName": "Consolas",
    "fontSize": 8.25,
    "bgColor": "Black",
    "textColor": "White",
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "width": 800,
    "height": 471,
    "top": 89,
    "left": 0
  }
}

**Comment by chenshaoju** [comment]
首先，你的虚拟机里能上网吗？
其次，在虚拟机里能Ping通你的服务器吗？

**Comment by greatbody** [comment]
很久没看了，有时间再重现的时候来补充。
