### ISSUE TITLE
如果长期开着允许局域网连入，有可能被部分批量代理扫描肉鸡服务器扫描到

### ISSUE THREAD

**Issue by sumirecccp** [shadowsocks/shadowsocks-windows#1740]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.08

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10 x64

### Steps you have tried / 操作步骤
最近两天总是发现许多莫名其妙的域名请求和什么都没开的情况下照样走大量流量，程序也经常弹出内存不足的问题崩溃，进行了一番分析才发现可能是被网上的一些代理扫描肉鸡服务器盯上了，从而被恶意利用。
如果是用路由器上网又不经常换本地端口的话，这是一个严重的安全隐患。
在防火墙中设置把shadowsocks的外部连接地址设置为只允许局域网IP后，问题得到解决。

### What did you expect to see? / 期望的结果
建议：或者在设置页面中对socks5代理增加一个用户名/密码验证功能，或者说在激活时添加的防火墙规则设置为只允许局域网IP连入。当前默认是允许所有IP连入。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by celeron533** [comment]
局域网里的任何敏感服务都不应该暴露给外网

**Comment by sumirecccp** [comment]
同意，不过由于默认是全开的，一直都没注意

**Comment by chenshaoju** [comment]
```
如果是用路由器上网又不经常换本地端口的话，这是一个严重的安全隐患。
```
在默认情况下，如果你是通过路由器上网，你内网中的端口是不可能被外网访问到的，除非你做了DMZ或者端口映射故意将你的计算机暴露给外网或者让外网访问你的代理端口。

**Comment by sumirecccp** [comment]
DMZ有需要所以是一直开着的，一些P2P下载软件有用

**Comment by chenshaoju** [comment]
根据我的了解，在我使用的P2P类软件（eMule、Tixati（BT）、fopnu）都可以通过端口映射解决，甚至包括Bitcoin、Zeronet、Bitmessage这种分布式P2P应用。整体来说，你的需求并不需要使用DMZ。

![image](https://user-images.githubusercontent.com/515763/37440684-ab816014-2838-11e8-8e6d-79112f95efe0.png)

DMZ在某些情况下可能会暴露你系统的弱点（比如Windows文件共享、远程桌面、远程注册表访问等）。

**Comment by sumirecccp** [comment]
现在默认情况下开启允许局域网连入后windows防火墙中会弹出提示并自动添加几条shadowsocks允许所有远程IP连入的规则。建议将其修改为默认只允许局域网IP访问。或者设个安全提示窗口也行。

DMZ我还是有需要的

**Comment by chenshaoju** [comment]
此社区无法对该功能提供任何保证或承诺，在该功能实现前，若需要启用允许局域网访问，建议使用端口映射而非DMZ。

如果坚持需要使用DMZ，建议关闭“允许局域网访问”功能，并单独搭建一个Privoxy并配置访问规则，仅允许你所在局域网的IP访问。

**Comment by sumirecccp** [comment]
好吧，我也是摊上这事儿了才想到发帖。当前我已经调好防火墙了，顺便发个帖子警示下其他的人

在 2018年3月15日 上午10:20，Chen Shaoju <notifications@github.com>写道：

**Comment by chenshaoju** [comment]
建议修改一下标题，不要这么耸动。

比如，“在启用路由器DMZ的情况下若开启SS的允许局域网访问，会导致外网也能访问。”

**Comment by sumirecccp** [comment]
关键倒不是能不能让外网访问，因为有时候确实有可能要让外网访问本机代理（偶尔让朋友使用之类的）。主要还是要做个安全提醒以及添加默认只让局域网IP访问的规则。

**Comment by chenshaoju** [comment]
@sumirecccp 对于这个问题，在文字方面将会考虑做出改进，欢迎提交反馈： https://github.com/shadowsocks/shadowsocks-windows/pull/1743/files

**Comment by sumirecccp** [comment]
但是当前只有四个文件修改了？“允许来自局域网的连接”我觉得没多大问题，但是可以每次勾选的时候弹一个说明警告弹窗。

**Comment by sumirecccp** [comment]
当然按你那个pull里说的增加设置一个只监听部分IP段的功能也可以

**Comment by chenshaoju** [comment]
我不会写程序，所以只能从文字方面改进，不过这个描述的确有点问题。

至于弹窗警告或者IP段识别，我不懂这个了。

**Comment by sumirecccp** [comment]
好吧，我过去在维基百科上看到过你，一直以为你是程序大师
另外我觉得原标题问题不大，因为一旦被扫描到很可能被一些攻击程序直接拿来当肉鸡攻击其他人，从而造成服务器负担过重以及超流量等问题

**Comment by chenshaoju** [comment]
并不是。。。会一点VB6，早就淘汰了的东西。

不过我还是认为这个事情属于edge case，开了局域网共享，同时又做了DMZ，这种情况实属罕见。

**Comment by sumirecccp** [comment]
这个你就想成是没用路由器直接和modem连接PPPOE拨号上网的case就可以了，我这次就是因为程序频繁崩溃且流量被大量占用才发现的这个问题

**Comment by chenshaoju** [comment]
如果是PPPoE直接拨号，那就根本没必要开启这个功能；不过即便如此，描述也有问题，所以提交了修改。

BTW，现在很多地区的宽带拨号是没有公网IP的，需要申请。

**Comment by sumirecccp** [comment]
可以开，因为有一个东西叫做USB无线AP，插在USB接口上就可以发射无线网络
虽然部分地区可能是没有公网IP的，但是另一些地区则直接就是公网IP

**Comment by chenshaoju** [comment]
我没有使用过这种设备，不予置评。

不过文字已经提交了，先这样吧。

**Comment by celeron533** [comment]
@sumirecccp 如果开了DMZ，你这台机器上的任何服务都会被暴露给公网，不论是samba文件共享、HTTP web服务，ftp，snmp管理，telnet等都会被公网访问到。这一点需要使用者自己注意
