### ISSUE TITLE
怎么设置win10自动更新走SS？

### ISSUE THREAD

**Issue by hnyhan** [shadowsocks/shadowsocks-windows#1741]
Microsoft 商店app不能走SS，已经通过Fiddlerr解决了，系统的自动更新在哪里设置可以走SS呢

**Comment by chenshaoju** [comment]
Windows 10 的 Windows Update 是基于系统代理设置的，请点击开始菜单，进入设置（齿轮），网络和Internet，代理，进行查看。

**Comment by hnyhan** [comment]
开全局的情况下，在network -proxy里面自动、手动都设置了，还是不能走代理

**Comment by chenshaoju** [comment]
非常奇怪，微软的文档里是这么写的：
```
By default, Windows Update impersonates the user who's logged on to the computer in order to obtain updates. If you're using a proxy.pac file or have proxy settings deployed through Group Policy or another method, make sure that your Internet Explorer proxy settings are configured correctly. If you are manually defining a proxy setting, make sure that the Automatically detect settings check box is not selected. This check box may override your manual proxy settings and cause connection issues. 

To verify, go to Internet Options > Connections > LAN Settings. Or, in Windows 10, go to Settings > Network & Internet > Proxy.
```
https://support.microsoft.com/en-us/help/3084568/can-t-download-updates-from-windows-update-from-behind-a-firewall-or-p

**Comment by celeron533** [comment]
而且自动更新应该是和系统代理一致的，否则那些公司局域网的需要设置代理服务器的终端都无法更新了

**Comment by hnyhan** [comment]
win7时代，开了自动更新的电脑有时候会卡在更新界面几个小时，影响办公，因此IT把所有微软更新屏蔽了
win10走SS，有时候可以更新，有时候连不上，时好时坏，系统proxy设置试了几种组合，还是没找到规律

**Comment by wongsyrone** [comment]
win10 自动更新是metro，基于winhttp，代理不同于IE的wininet

从IE导入：
```bat
netsh winhttp import proxy source=ie
```

独立设置：
```bat
netsh winhttp set proxy 127.0.0.1:1088 "<local>;localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*"
```

**Comment by chenshaoju** [comment]
Interesting，我一直以为Windows Update实际上是后台服务 BITS 和 wuauserv 负责的，界面只是负责显示状态。。。

**Comment by Fankbai** [comment]
@hnyhan 您现在可以使用ss更新win了吗？

**Comment by bokemanoh** [comment]
> win10 自动更新是metro，基于winhttp，代理不同于IE的wininet
> 
> 从IE导入：
> 
> ```batchfile
> netsh winhttp import proxy source=ie
> ```
> 
> 独立设置：
> 
> ```batchfile
> netsh winhttp set proxy 127.0.0.1:1088 "<local>;localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*"
> ```

netsh winhttp 会让所有程序经过SS联网吗？比如说BT客户端（utorrent, bittorrent一类）会不会也通过SS联网了？

**Comment by chenshaoju** [comment]
请不要到处发，移动到：https://github.com/shadowsocks/shadowsocks-windows/issues/2735

**Comment by bokemanoh** [comment]
抱歉
