### ISSUE TITLE
用pac代理模式，发现bbc的中文网站没用呀

### ISSUE THREAD

**Issue by ddyllen-z** [shadowsocks/shadowsocks-windows#1742]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.8版本

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win7，.net 版本是4.0,3.5都有安装

### Steps you have tried / 操作步骤
代理模式切换到PAC模式

### What did you expect to see? / 期望的结果
BBC中文网应该会总走代理

### What did you see instead? / 实际结果
没有走，打不开，要用全局代理模式才能打开

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

看了pac的列表里面有bbc的域名，但是确实没有走到代理，开全局模式没问题。

**Comment by chenshaoju** [comment]
请尝试更新一下PAC文件看看？右击托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。

由于GFWList不由Shadowsocks for Windows控制，如果仍然不行，请与GFWList联系：
 https://github.com/gfwlist/gfwlist

**Comment by ddyllen-z** [comment]
@chenshaoju 更新试过了，我去那边反馈看看吧。

**Comment by ddyllen-z** [comment]
自己添加一条自定义规则：`".bbc.com"`，就有效.
