### ISSUE TITLE
cmd

### ISSUE THREAD

**Issue by hwk603** [shadowsocks/shadowsocks-windows#1744]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by celeron533** [comment]
???

**Comment by hwk603** [comment]
Sorry, I didn't even know how this issue occurred. I didn't make the issue 15 hours ago.
