### ISSUE TITLE
4.0.9 Release包Win10报毒trojan:win32/critet.bs

### ISSUE THREAD

**Issue by yhnbgfd** [shadowsocks/shadowsocks-windows#1746]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Win10 x64 .NET4.7

### Steps you have tried / 操作步骤
正常使用

### What did you expect to see? / 期望的结果
应该不会报毒

### What did you see instead? / 实际结果
Win10自带杀毒软件报毒：trojan:win32/critet.bs  
通过SS自动更新以及从github release下载的文件都报毒，经检查报毒exe的SHA与release中一致  
自己源码编译的不会报毒  

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by Jamesxql** [comment]
+1

**Comment by wangmingph** [comment]
+1，文件第一次被删掉了，重新解压了一个，然后允许它在这个设备上
![1](https://user-images.githubusercontent.com/19575952/37480744-05a81b8c-28bb-11e8-8317-35051bbbf652.PNG)

**Comment by wangmingph** [comment]
Windows规格 OS 内部版本 16299.309

**Comment by SquirrelCoder** [comment]
I assume, you guys are talking about the fact, that Windows 10 defender is automatically deleting Shadowsocks.exe. If this is indeed the subject of this issue, then I have this problem too. I hat to exclude it to work.

**Comment by yhnbgfd** [comment]
Do not trust it because my own compiled program does not report viruses

**Comment by TianLi-520** [comment]
我的显示Trojan:Win32/Tiggre!rfn和Trojan:Win32/Critet.BS

**Comment by tobyxdd** [comment]
Any significant difference in file size between your compiled version and release version? If it really does contain a trojan then the file size is likely to be bigger.

**Comment by yhnbgfd** [comment]
The file size is the same between the compiled version and the released version, both are 2.14 MB (2,245,632 byte)

**Comment by SquirrelCoder** [comment]
@yhnbgfd could you check the SHA384 of both the original `Shadowsocks.exe` with your compiled version? 

You can use the following in PowerShell

```
Get-FileHash Shadowsocks.exe -Algorithm SHA384 | Format-List
```

**Comment by yhnbgfd** [comment]
@SquirrelCoder SHA changes every time I compile, so it's always different from the original exe.

**Comment by SquirrelCoder** [comment]
@yhnbgfd Really? That's odd! It shouldn't be that way.

**Comment by yhnbgfd** [comment]
@SquirrelCoder Yes, I tried it without modifying any code just to recompile

**Comment by Sykue** [comment]
Seeing the same report with 4.0.9 as well

**Comment by CNife** [comment]
同样的问题，今天早上一开机 Windows Defender 就报了错。
Release 4.0.9，Hash 值吻合

**Comment by QJiDea** [comment]
我的也同样报毒，已退回4.0.8

**Comment by yyysuo** [comment]
同样的问题，+1，难道是微软配合gov？

**Comment by cybmp3** [comment]
我觉得可能是GOV上报病毒。M$随便看了眼，嗯这就是毒吧。

**Comment by ziruizhuang** [comment]
+1 退回了4.0.8

**Comment by gumptie** [comment]
+1，同样报毒，已退回4.08

**Comment by yyysuo** [comment]
问题是昨天才更新的时候没有报毒，稳定运行1天了才报的毒。

**Comment by ziruizhuang** [comment]
看change log，发现libcrypto_1_1_dll被替换成了libsscrypto_dll，两个文件单扫都不报毒，但是会不会是4.0.9里面用的libsscrypto_dll容易被提取特征。建议改回libcrypto_1_1_dll试试。

**Comment by ziruizhuang** [comment]
也可能是WD的误报https://forum.kerbalspaceprogram.com/index.php?/topic/172357-trojanwin32critetbs/

**Comment by sunweiqiang** [comment]
+1
Seeing the same report with 4.0.9 as well

**Comment by yangyu** [comment]
The same issue, it is strange.

**Comment by yhnbgfd** [comment]
@ziruizhuang 不会的，因为我自己编译了一份是不会报毒的，所以跟第三方库肯定没关系，要么被针对了，要么刚好那个release碰撞到某些特征码了。

**Comment by 91he** [comment]
Got the same problem.

**Comment by ziruizhuang** [comment]
1.263.562.0 版本的病毒定义引入了这个detection Definition available date: Mar 14, 2018 07:57 PM UTC
4.0.9发布时间是Mar 14, 2018, 10:32 PM GMT+8，或者Mar 14, 2018, 02:32 PM UTC
从时间上看的确有前后关系。

https://www.microsoft.com/en-us/wdsi/definitions/antimalware-definition-release-notes?RequestVersion=1.263.562.0&Release=Released&Package=AM

**Comment by piedgogo** [comment]
+1, 已退到 4.0.8

**Comment by chenfd99** [comment]
+1

**Comment by SAmmer0** [comment]
SHA-256 calculation process reports virus too.

**Comment by longbow0** [comment]
Same problem. Version 4.0.8 was also reported to be trojan:win32/critet.bs. Only version 4.0 worked.

**Comment by tsanie** [comment]
strange, because the size of the release one is the same as my self-compiled one.
so I think there is almost impossible a virus bundled in it. 🤕

**Comment by celeron533** [comment]
4.0.9 virus scan result
https://www.virustotal.com/en/file/b4810eb33bbc3888e66d51db3c76a52abe7b98d8520584daa8d92c03e412be57/analysis/

**Comment by maolibu** [comment]
同样的问题，暂时回到8

**Comment by cbwang2016** [comment]
![default](https://user-images.githubusercontent.com/18070081/37499772-9cc9037e-2900-11e8-9410-7c1e87cf3d0c.PNG)
However:
![default](https://user-images.githubusercontent.com/18070081/37499793-b37f399e-2900-11e8-84ee-623f1b3f56f1.PNG)

**Comment by RazorXu** [comment]
Same problem. Version 4.0.7 is Ok.

**Comment by chenshaoju** [comment]
The problem has been revived.
此问题已经在我的Win10上复现：
![screenshot](https://user-images.githubusercontent.com/515763/37499973-b9d1c694-2901-11e8-80d5-eacd60516b5b.png)

This issue has been reported to Microsoft and is waiting for review.
此问题已经报告给Microsoft等待复查：
![image](https://user-images.githubusercontent.com/515763/37500098-8a4f85a4-2902-11e8-9241-25e87793e438.png)

**Comment by li2282231** [comment]
我也有相同的问题，win10自动报毒，允许威胁以后就可以正常使用了，希望作者解决一下

**Comment by chenshaoju** [comment]
此问题微软的问题，已经报告给微软等待解决。

**Comment by ziruizhuang** [comment]
![2018-03-16 -](https://user-images.githubusercontent.com/2201480/37501018-5ad216ca-2907-11e8-86ff-c5d600d6156c.png)
WD的report有结果了，not malware

**Comment by chenshaoju** [comment]
@ziruizhuang 请仔细看右边的定义版本号，似乎是大于 1.263.562.0 才会遇到这个问题，我的版本是 1.263.585.0

**Comment by chenshaoju** [comment]
@yhnbgfd @tobyxdd @SquirrelCoder @tsanie 

About compile issue, The Shadowsocks for Windows compile is by 3rd services name "appveyor".
关于编译问题， Shadowsocks for Windows 的编译是经由第三方服务 appveyor 进行的。

The compile process is a non-human operation.
整个编译过程无人为介入操作。

This is appveyor build version, Society 4.0.9 release version, you can download and compare the hash. https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/4.0.9.0/job/6hqoct7lt1jm25m9/artifacts

这是 appveryor 编译的版本，对应释出的 4.0.9 版本，你可以在这里下载到由 appveyor 编译的版本并手动对比文件的散列值（是否和发布页的一致）：
https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/4.0.9.0/job/6hqoct7lt1jm25m9/artifacts

**Comment by ziruizhuang** [comment]
@chenshaoju 右边的版本号应该是指系统自动的检测引擎的定义版本。自动检测很快就出了No malware detected。这里的final determination是过了差不多2个小时出的。不太了解WD的流程，不清楚这个final determination是否是有安全人员人工介入检测后的结果。

**Comment by tonyhook** [comment]
1.263.598.0，4.0.9，没有误报

**Comment by iKirby** [comment]
Windows Defender 定义版本 1.263.598.0 已经修正了误报问题
Windows Defender Definition version 1.263.598.0 has fixed this false positive.

**Comment by wangmingph** [comment]
Windows Defender升级到1.263.598.0版本，扫描新下载的Shadowsocks.zip仍然报毒
![1](https://user-images.githubusercontent.com/19575952/37516035-d39d23de-2947-11e8-8c21-242a53947cb2.PNG)

**Comment by wangmingph** [comment]
Windows 10 企业版 16299.309，是通过SS的全局模式升级的Windows Defender

**Comment by chenshaoju** [comment]
If really care about this issue, Please rollback to 4.0.7 or 4.0.8, And waiting for Microsoft update their virus definition.
如果很在在意的话，请退回4.0.7或4.0.8，等待微软更新病毒库。

If don't care, Please add Shadowsocks.exe to the white list.
如果不在意，请把Shadowsocks.exe加入例外。

The source code is right here, And anyone can review code.
源代码就摆在这里，任何人都可以检查代码。

**Comment by yhnbgfd** [comment]
@chenshaoju 是否可以再编译一份放在这里，给那些没条件编译又想用新版本又不放心的人下载使用。

**Comment by chenshaoju** [comment]
@yhnbgfd 包括我自己编译的，都无法保证透明度， appveyor包括获取源码和编译的过程都是公开的。

说穿了，没人能保证编译者会不会加料，甚至可能是无意中被加料（XcodeGhost事件，参见：  http://www.jiemian.com/article/385911.html ）

这个问题其实是微软误报了，只能等微软解决问题，而不是想办法绕过这个误报，因为没有办法保证另一个版本就不会出问题。

旧版本仍然可以使用，没有冲突或限制。

如果你非常坚持（强迫症等原因），需要一个暂时不会被误报的版本，可前往 https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/4.0.9.1/job/94tdv6o0h8byh9e3/artifacts 下载，着同样是 appveyor 编译的版本，仅仅是更新了说明和自动更新的版本信息。

但是，这不能保证未来再次被微软误识别为恶意软件。

**Comment by cbwang2016** [comment]
@chenshaoju 为什么可以确定是误报？

**Comment by chenshaoju** [comment]
@cbwang2016 这是全球６５款杀毒软件的扫描报告： https://www.virustotal.com/en/file/d618d4fde2212052636f91e7efd35ab907317354d76693006177c507cba772c0/analysis/1521187678/

截至目前，没有一款报毒。

**Comment by piedgogo** [comment]
今天 4.8 也被删了。早上开机莫名其妙跳出个 cmd 窗口，随手就关掉了，不知道是不是和这个有关系。

**Comment by cbwang2016** [comment]
@piedgogo 无法复现问题

**Comment by longbow0** [comment]
今天仍然出现这个问题，相关的文件是 .Shadowsocks_v4.0.9.exe.~cfc

**Comment by chenshaoju** [comment]
这个事情让我很困惑。


微软在线的扫描并没有扫出来任何问题（定义版本：1.263.814.0）
![image](https://user-images.githubusercontent.com/515763/37642508-47e8099e-2c58-11e8-932a-8aa52948d2df.png)


但是Win10上的Windows Defender，相同的定义版本，却扫出来有问题。
![2018-03-20 2](https://user-images.githubusercontent.com/515763/37642536-6872990e-2c58-11e8-8cbd-9c6e050ee64d.png)


而最新的VirusTotal扫描仍然没有任何一款杀毒软件（包括Microsoft）报告存在问题：
https://www.virustotal.com/en/file/d618d4fde2212052636f91e7efd35ab907317354d76693006177c507cba772c0/analysis/1521533790/

**Comment by longbow0** [comment]
有哪位用的是英文或者其他语言版本的win10，是否会有这样的问题？

**Comment by pexcn** [comment]
没遇到这个问题，因为我已经把 windows defender 禁用了 :smile:

**Comment by jasonliul** [comment]
@chenshaoju
那是微软的启发式扫描, 自动清除威胁, 用户无法控制.

之前发过, Defender Control
https://www.sordum.org/9480/defender-control-v1-3/

**Comment by ziruizhuang** [comment]
问题解决
执行如下命令
      cd %ProgramFiles%\Windows Defender
      MpCmdRun.exe -removedefinitions -dynamicsignatures
      MpCmdRun.exe -SignatureUpdate

参考：
https://forum.kerbalspaceprogram.com/index.php?/topic/172357-trojanwin32critetbs/
https://www.microsoft.com/en-us/wdsi/definitions

**Comment by chenshaoju** [comment]
@ziruizhuang 你好，我测试了两次，仍然不行，能否看一下你的Windows Defender的病毒和威胁防护、扫描历史记录，会有一个允许的威胁，里面是不是有一个 Trojan:Win32/Critet.BS ？

![2018-03-21 10](https://user-images.githubusercontent.com/515763/37694200-361baad8-2d00-11e8-8e44-db22faae0de9.png)

**Comment by ziruizhuang** [comment]
没有允许过，进行这个操作前还确认过是查杀的。
但是我的执行结果和你的不太一样。我的是Starting Dynamic Signature removal.，你的是starting rollback。
```
C:\Program Files\Windows Defender>MpCmdRun.exe -removedefinitions -dynamicsignatures

Service Version: 4.12.17007.18022
Engine Version: 1.1.14600.4
AntiSpyware Signature Version: 1.263.854.0
AntiVirus Signature Version: 1.263.854.0
NRI Engine Version: 2.1.14202.0
NRI Signature Version: 118.8.0.0

Starting Dynamic Signature removal.
Done!

Service Version: 4.12.17007.18022
Engine Version: 1.1.14600.4
AntiSpyware Signature Version: 1.263.854.0
AntiVirus Signature Version: 1.263.854.0
NRI Engine Version: 2.1.14202.0
NRI Signature Version: 118.8.0.0

C:\Program Files\Windows Defender>  MpCmdRun.exe -SignatureUpdate
Signature update started . . .
Signature update finished.
```

**Comment by chenshaoju** [comment]
感谢 @ziruizhuang 的点拨，在阅读微软的文档后，该问题可能需要通过以下步骤解决。

１.以管理员身份启动命令提示符（cmd）或PowerShell。

２.进入 C:\Program Files\Windows Defender\ 目录，执行：
```
cd %ProgramFiles%\Windows Defender\
```

３.执行下面清空 Windows Defender 病毒定义的命令：
```
MpCmdRun.exe -RemoveDefinitions -All
```

４.重新更新完整的  Windows Defender 病毒定义：
```
MpCmdRun.exe -SignatureUpdate
```

通过以上操作即可不再被误报，已在Windows 10 x64上测试通过。
![2018-03-21 11](https://user-images.githubusercontent.com/515763/37695506-e3d18422-2d0a-11e8-9517-86723b473242.png)

参考阅读：https://technet.microsoft.com/en-us/library/gg131918.aspx

**Comment by sh5525** [comment]
似乎不止是微软报毒，这是VirusTotal的页面：https://www.virustotal.com/#/file/31e418c35253b2453f22b9818f95404d866350192b6fb810eb3943a759b58903/detection
是从下载网页直接抓的（dl.bintray.com/rime/weasel/weasel-0.10.0.0-installer.exe）
为防止误解，底下还有53个引擎都是绿的，没有截图出来。
![default](https://user-images.githubusercontent.com/11629684/38393169-0cc2edfa-38f8-11e8-9473-1f020f9d72f8.png)

**Comment by chinarabbit** [comment]
Win10,最近升级4.0.9版本一直报毒,itunes升级报签名无效.今天改用SS全局下载更新,4.0.9升级正常,itunes升级也正常了.单位用的联通网络,家里用的电信网络,都是一样.何解?
