### ISSUE TITLE
Shadowsocks 4.0.9报毒

### ISSUE THREAD

**Issue by sn01615** [shadowsocks/shadowsocks-windows#1747]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows 10 家庭版

### Steps you have tried / 操作步骤
自动更新下载的zip包报毒
Trojan:Win32/Critet.BS
类别：特洛伊木马
地址：file: E:\...\ss_win_temp\Shadowsocks-4.0.9.zip

### What did you expect to see? / 期望的结果
正常更新

### What did you see instead? / 实际结果
报毒，解压后会被系统删除

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
Note: moving to https://github.com/shadowsocks/shadowsocks-windows/issues/1746
