### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by bnjmk** [shadowsocks/shadowsocks-windows#1748]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
shadowsocks/shadowsocks-windows Releases 4.0.8

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10家庭版1709 16299.309 

### Steps you have tried / 操作步骤
1. 清除dns缓存 `chrome://net-internals/#dns` , `ipconfig /flushdns`
2. shadowsocks系统代理模式选全局模式
3. chrome打开[www.example.com](url)等个网站
4.  一共5个节点分别测试 
5. 然后换andriod手机再来一次

### What did you expect to see? / 期望的结果
都能正常访问

### What did you see instead? / 实际结果
win10 4个节点显示403 Forbidden nginx 1个节点能访问 
android 5个都能访问
其他网站 youtube google , win10 android都能访问

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
这意味着你的服务器的IP被对方屏蔽了。

如果你是在某个服务商购买的SS服务，请与你的服务商联系。

**Comment by bnjmk** [comment]
安卓端都可以访问 @chenshaoju

**Comment by chenshaoju** [comment]
你的SS服务商提供的５个节点中，４个在Windows上无法访问，但是这４个可以访问Google、Youtube等网站？

如果是，很高的可能性的确是你所使用的服务器有问题。

为了确认，你是否有安装Firefox？如果有，请尝试手动配置Firefox的代理看看，可参照下图：
如果可能，手动指定代理然后再试一次，看看是否还会有该问题？

![image](https://user-images.githubusercontent.com/515763/37390878-680ff942-27a4-11e8-81f1-54edfe7658d9.png)


如果确认这样结果也相同（５个服务器中４个不行１个行），这很高的可能性是你所使用的服务器有问题，或者你所使用的SS服务器被网站服务商暂时性阻止了，如果你的服务商提供了QQ群或者Telegram群组，请咨询一下群内的其他人员使用有问题的服务器是否正常。

**Comment by bnjmk** [comment]
@chenshaoju 还是一样 ,如果是服务器问题 为什么android客户端不会有这个问题

**Comment by chenshaoju** [comment]
这就是最奇怪的问题了，你确认PC和Android上使用的是相同的IP、相同的端口以及相同的加密算法和密码？

**Comment by bnjmk** [comment]
@chenshaoju IP,端口,加密算法,密码,肯定都是相同的 
有没有可能是  https://github.com/shadowsocks/shadowsocks/issues/750

**Comment by chenshaoju** [comment]
这个 403 Forbidden 的提示肯定是 nginx 返回的结果，而Shadowsocks for Windows使用的是privoxy，而这个 nginx 肯定是你所访问的网站服务器的。

而 SS 的服务端（假设是Python），也并没有 nginx ，除非你是用的服务端上有一个nginx给你过滤掉了。

因此不太可能是SS本身的问题。

**Comment by bnjmk** [comment]
@chenshaoju 不只几个网站是403 Forbidden  ,是一堆网站,这是搜索到的网页截图,里面个个都是403
![2018-03-16_125317](https://user-images.githubusercontent.com/28582077/37504533-ebfe2bfe-2919-11e8-80d0-a03c35974d72.png)

**Comment by celeron533** [comment]
>win10 4个节点显示403 Forbidden nginx 1个节点能访问
android 5个都能访问
其他网站 youtube google , win10 android都能访问

如果android和windows用的是同一台ss服务器，高度怀疑是你的windows机器上有组织访问的软件，比如各种助手、卫士、广告拦截等
