### ISSUE TITLE
连接自动断开，无法科学上网

### ISSUE THREAD

**Issue by fishhhhh** [shadowsocks/shadowsocks-windows#1749]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10 

### Steps you have tried / 操作步骤
开启客户端，正常连接服务器，日志正常，但无法科学上网
服务器监控时发现最初连接成功，一段时间之后连接消失，日志无异常，期间客户端无任何操作

使用手机端和其他PC端均无异常

### What did you see instead? / 实际结果
无法科学上网

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![a](https://user-images.githubusercontent.com/24807594/37500339-f19b42ce-2903-11e8-9f7e-c546dd7eb53b.png)
![b](https://user-images.githubusercontent.com/24807594/37500420-6610a32e-2904-11e8-8656-1bb9de9f49a9.png)
![c](https://user-images.githubusercontent.com/24807594/37500411-5d444d7c-2904-11e8-982d-16806fae0024.png)
![d](https://user-images.githubusercontent.com/24807594/37500412-5d797e5c-2904-11e8-8414-4797c16f2e62.png)

**Comment by chenshaoju** [comment]
你用的不像是 Shadowsocks-python 的服务端？

加密算法用 aes-256-gcm 看看呢？如果你的服务端支持的话。

另外，如果没反映了，使用 tcping （ https://www.elifulkerson.com/projects/tcping.php ）检测到服务器的端口，通吗？

**Comment by fishhhhh** [comment]
@chenshaoju 
用的服务端是别人封装过的（https://github.com/getlantern/forum/issues/5620），按照这个来的，加密算法看了下不支持 aes-256-gcm 。
用手机端和其他PC端都能正常使用，就现在这台电脑不正常，检测过服务器端口没问题。

**Comment by chenshaoju** [comment]
可能和操作系统的协议栈有关，请尝试以管理员身份启动命令提示符（ｃｍｄ）或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，三行执行完毕后重启计算机看看。

**Comment by celeron533** [comment]
可能系统代理服务器设置在中途被其他软件篡改

**Comment by chenshaoju** [comment]
在出现问题的时候，进入设置（齿轮），网络和 Internet ，代理，看看是如何显示的？可能的话，截个图。

**Comment by fishhhhh** [comment]
![a](https://user-images.githubusercontent.com/24807594/37505460-f13c75f2-291f-11e8-89f8-3e3e9ccee40b.png)

具体的脚本地址为 http://127.0.0.1:1080/pac?t=20180313132345524&secret=5k2k25ZFrcaXNtiPK2OZG8zNaGGoBfXIN/ve9pn8dPc=

**Comment by chenshaoju** [comment]
在出现问题的时候也是显示的这个吗？

有意思的地方是，t=20180313.... ，理论上应该是最后一次启动SS时的时间。

你的系统时钟对吗？

**Comment by fishhhhh** [comment]
系统时钟是对的，这么说来好像13号的时候是可以用的，14号有次windows的更新，更新了以后就不行了

**Comment by chenshaoju** [comment]
做一个测试，退出SS，在上图中删除“脚本地址”中的内容，然后关闭“使用安装程序脚本”，再关闭该窗口。

然后再次打开SS，能否恢复正常？

另外，你的Win10版本是多少？可执行 winver 命令看到具体的版本号。

**Comment by fishhhhh** [comment]
版本1709，OS内部版本16299.309
测试发现代理页面设置的东西都不能正常保存，包括“自动检测设置”，“使用安装脚本程序”，“脚本地址”等内容，设置完成后切换设置菜单，再切换回来又会变回原样

**Comment by chenshaoju** [comment]
可能你的系统有什么东西阻碍了你设置代理，可能是某些安全软件之类的。

请暂时退出所有可能的安全软件，然后再尝试手动删除代理设置看看？

**Comment by fishhhhh** [comment]
安全软件用的火绒，关闭了不能设置，卸载后重启也不能设置，这就尴尬了

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 有一个名为 sysproxy.exe 组件，位于 Shadowsocks.exe 所在目录下的 ss_win_temp 目录中。
请使用命令提示符进入到该目录，然后执行：
```
sysproxy.exe query
```
此时，会列出你当前的浏览器设置，并截图保存。
然后，执行：
```
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable /t REG_DWORD /d 0 /f
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyServer /f
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyOverride /f
```
这会清空你浏览器的代理设置。
然后，再执行：
```
sysproxy.exe query
```
并截图保存，然后再启动SS看看代理是否正确的设置上去了。

如果仍然不行，请将两张截图发送来看看。

**Comment by fishhhhh** [comment]
第一次查询：
![a](https://user-images.githubusercontent.com/24807594/37507302-c38505bc-2928-11e8-8a95-62b4417f3cec.png)
执行清空浏览器代理设置并查询：
![b](https://user-images.githubusercontent.com/24807594/37507309-d10090e4-2928-11e8-8f8d-3850cc06fa52.png)
启动SS后查询：
![c](https://user-images.githubusercontent.com/24807594/37507327-e27d82b4-2928-11e8-9ba7-3d08627b927b.png)

整个过程中代理设置均无变化

**Comment by chenshaoju** [comment]
不好意思，还有一个叫 AutoConfigUrl 的键值，也删掉看看：
```
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v AutoConfigUrl /f
```

**Comment by fishhhhh** [comment]
![a](https://user-images.githubusercontent.com/24807594/37507845-7c19c76e-292b-11e8-883f-bfe6fe72a933.png)

![b](https://user-images.githubusercontent.com/24807594/37507822-5cc64496-292b-11e8-80c3-7db524fd0812.png)

**Comment by chenshaoju** [comment]
OK，再启动SS的话，是否能设置代理了？

**Comment by fishhhhh** [comment]
还是和之前一样无法使用，设置里面的脚本地址还是20180313XXXX

**Comment by fishhhhh** [comment]
1. 通过路由器上网
2. 未设置VPN相关内容
3. 局域网设置中的内容与“设置-网络和internet-代理”中一致，且一样不能保存

查询资料找到该解决方案：
修改注册表HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
ProxySettingsPerUser ，值修改为1，即可手动修改代理内容。

此时测试ss代理，发现每次ss启动时代理均成功，但过30s左右后代理失效
使用手机即其他PC端测试未发现此问题

**Comment by chenshaoju** [comment]
这很有可能意味着你的电脑上有什么东西会取消你的PAC代理，可能是某些安全软件，也可能是某些应用软件。（案例：https://github.com/shadowsocks/shadowsocks-windows/issues/1689#issuecomment-366940637）

如果有Firefox，请参考下图独立配置Firefox的代理设置，看看是否还会失效。

![image](https://user-images.githubusercontent.com/515763/37390878-680ff942-27a4-11e8-81f1-54edfe7658d9.png)

**Comment by fishhhhh** [comment]
Firefox设置后可以正常代理，Chrome不行，对Chrome有没有什么解决方案？

**Comment by chenshaoju** [comment]
个人观点，仅供参考，和此项目无关：
https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif

**Comment by fishhhhh** [comment]
已解决，感谢大佬。

**Comment by Kerinlin** [comment]
> 已解决，感谢大佬。

想问下如何解决的？目前也遇到30s左右自动断开的情况

**Comment by Ares-cz** [comment]
请问还有可以使用的ssr一键安装脚本嘛 已经很长一段时间 ssr的登录都成问题 经常一个ip搭建好 刚刚可以登上google 一会儿就又不行了 去查ip情况 也是通的 大家又和我一样问题的嘛



在 2020-03-27 15:19:47，"欧阳铖" <notifications@github.com> 写道：

已解决，感谢大佬。

想问下如何解决的？目前也遇到30s左右自动断开的情况

**Comment by Ares-cz** [comment]
我也是遇到连接上 自动断开的问题
不知道大佬们是如何解决的













在 2020-03-27 15:19:47，"欧阳铖" <notifications@github.com> 写道：

已解决，感谢大佬。

想问下如何解决的？目前也遇到30s左右自动断开的情况
