### ISSUE TITLE
4.0.9 怎么就被windows自动删除了？

### ISSUE THREAD

**Issue by wyfang** [shadowsocks/shadowsocks-windows#1750]
文件夹下这个exe已经小时了。
![qq20180316-110432](https://user-images.githubusercontent.com/17900420/37501573-ecbe15dc-2909-11e8-99fe-79776faf73a2.png)
![qq20180316-110443](https://user-images.githubusercontent.com/17900420/37501576-ee5f80d8-2909-11e8-98cb-dbe65b375649.png)

**Comment by wyfang** [comment]
![qq20180316-110620](https://user-images.githubusercontent.com/17900420/37501622-2971c7f8-290a-11e8-8d76-302228b47379.png)

**Comment by chenshaoju** [comment]
此问题已知，已报告给微软等待解决： https://github.com/shadowsocks/shadowsocks-windows/issues/1746#issuecomment-373581916

**Comment by ywg663** [comment]
![tim 20180316114448](https://user-images.githubusercontent.com/3354857/37502747-8c29db06-290f-11e8-9002-e5a9060d0f57.png)

**Comment by chenshaoju** [comment]
@ywg663 请尝试更新你的Windows Defender 定义到 1.263.598.0 或更高，看看是否解决了： https://github.com/shadowsocks/shadowsocks-windows/issues/1746#issuecomment-373591123

**Comment by sejabs** [comment]
不行，已经升级到最新的定义。只要zip文件一解压就报威胁。

**Comment by chenshaoju** [comment]
@sejabs 奇怪，如果很在意，请退回4.0.7或4.0.8，如果不在意，请加入例外列表等待微软核查。

**Comment by sejabs** [comment]
@chenshaoju  也有可能是Antimalware Service Executable一直在运行的缘故。这个程序从早上就启动，一直占用20%左右的CPU，现在还在运行中-_-!

**Comment by jasonliul** [comment]
@sejabs
Defender Control
https://www.sordum.org/9480/defender-control-v1-3/

那是微软病态自恋的启发式扫描, 一坨便便, 值得禁用

**Comment by sejabs** [comment]
@jasonliul  换了卡巴，重启之后安静了。4.0.9可以用了。

**Comment by onlyJinx** [comment]
我以为就我出问题了，以为下载的exe被替换。。。。。

**Comment by celeron533** [comment]
合并讨论到 #1746
