### ISSUE TITLE
更新最新版本任务栏无法显示图标

### ISSUE THREAD

**Issue by udeve** [shadowsocks/shadowsocks-windows#1751]
版本4.0.9.0
清空文件目录重新安装，重启均无法显示任务栏图标
之前版本也出现过同样问题
操作系统win10（1709）

![image](https://user-images.githubusercontent.com/32419091/37504239-ff7eb286-2917-11e8-8cd9-ac68e68ac6fc.png)

**Comment by chenshaoju** [comment]
在我的Windows 10 和 Windows 7 上无法观察到该问题。

请尝试结束 Shadowsocks.exe 的任务，然后重新启动 Shadowsocks.exe ，是否可以？

如果仍然不行，请打开注册表编辑器，然后定位到：
```
HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify
```
右边会有两个名为 IconStreams 和 PastIconStream 的项目，分别右击，选择删除。

然后重启计算机看看？

**Comment by udeve** [comment]
非常感谢您在百忙之中的解答，我做的尝试如下
结束 Shadowsocks.exe 的进程，然后重新启动 Shadowsocks.exe 仍然没有任务栏图标
注册表里面没有PastIconStream 的项目，删除 IconStreams后重启仍没有任务栏图标

**Comment by chenshaoju** [comment]
我找了另一台Windows 10专业版，测试了一下也没有问题。

请确保安装了最新的 .NET Framework https://www.microsoft.com/net/download/dotnet-framework-runtime

如果仍然不行，我怀疑很高的可能性是你的系统有问题。如果可能，请备份数据，然后重置系统看看？

**Comment by RPCheung** [comment]
我在win7 上遭遇到同样的  #1751 问题    但 我只在设置了 开机启动时 出现该问题
![image](https://user-images.githubusercontent.com/18390076/37551756-c63372bc-29e1-11e8-91bc-5288c196bad4.png)

**Comment by chenshaoju** [comment]
结束任务，然后再启动是不是就好了？

**Comment by RPCheung** [comment]
是的 ，但 再次重启操作系统   观察 4.0.9的开机启动，还是无法在任务栏找到图标，却有进程存在，我的环境是  win7 sp1    .net framework 4.6.2，非常感谢您在百忙之中的答复

**Comment by RPCheung** [comment]
是的 ，但 再次重启操作系统   观察 4.0.9的开机启动，还是无法在任务栏找到图标，却有进程存在，我的环境是  win7 sp1    .net
framework 4.6.2，非常感谢您在百忙之中的答复

2018-03-17 13:48 GMT+08:00 Chen Shaoju <notifications@github.com>:

**Comment by chenshaoju** [comment]
这个很高的可能性是系统响应问题，建立了进程但是没来得及显示图标。

也可能和系统的图标缓存有关，这是一个第三方的小工具，用于重建系统图标缓存的，请先试一下看看：
http://www.thewindowsclub.com/rebuild-corrupt-icon-cache-with-icon-cache-rebuilder

**Comment by RPCheung** [comment]
经测试 将  .net framework 4.7.1后，该问题得到解决，非常感谢您在百忙之中的答复

在 2018年3月17日 下午3:06，Chen Shaoju <notifications@github.com>写道：

**Comment by celeron533** [comment]
也可能是病毒防护软件误报清理掉了部分程序功能
