### ISSUE TITLE
User rules的语法问题

### ISSUE THREAD

**Issue by kran** [shadowsocks/shadowsocks-windows#1752]
可能和SS关系不大，但实在找不到答案
根据 https://adblockplus.org/en/filter-cheatsheet 的教程（还有pac.txt)的现有规则：
如果想让 http://2017.ip138.com/ic.asp 走代理（而不是整个域），是完全可行的，比如：
```
2017.ip138.com/ic.asp
```
或者用正则。

但实际测试，完全不起作用。只有：
```
2017.ip138.com/*
```
类似这种不根据路径判断的规则才有效。
请教该如何写这样的根据路径判断的规则？

**Comment by chenshaoju** [comment]
```
Separator
The address must either end here or a separator character like ? or / has to follow.
```
试试：
```
||2017.ip138.com/ic.asp^
```

**Comment by kran** [comment]
@chenshaoju 这样写也无效
```
||2017.ip138.com
```
但这样是可以

**Comment by kran** [comment]
不行的，我每次修改pac或user rule都会关闭/开启一次系统代理。
刚才也测试了。

**Comment by chenshaoju** [comment]
Odd ，我这儿可以，你用的是 .Net Framework 4.7.1 + SS 4.0.9 ？

![image](https://user-images.githubusercontent.com/515763/37506974-711b4bfc-2927-11e8-9dd3-714cab5e1526.png)

**Comment by kran** [comment]
SS 4.0.9 , .Net framework系统里最高就是4.7.1，不确定它用的哪个版本。
但确实不行，好奇怪。

**Comment by chenshaoju** [comment]
我找了一台Win10测试了一下，也得开启／关闭系统代理一次才能正常工作，但是无论末尾有无 ``` ^ ``` 都能访问。

![2018-03-16 3](https://user-images.githubusercontent.com/515763/37507350-035de1fe-2929-11e8-8b94-6930b7e3b1c4.png)

**Comment by kran** [comment]
我这不行……
清理后重新做一次也没起作用。
如果可以，您远程帮忙看一下不知道是不是太冒昧。

**Comment by chenshaoju** [comment]
我想我搞清楚是怎么回事了。

你是不是自定义了 pac.txt ，没有使用SS从gfwlist提供的 pac.txt ？

**Comment by kran** [comment]
刚开始是这样，之后我有删除了所有文件。现在的pac.txt内容是这样：
```
var proxy = "__PROXY__";

var rules = [
  "||2017.ip138.com/ic.asp^",
  "||2dbook.com",
  "||4tern.com",
  "|http://85.17.73.31/",
  "||adorama.com",
  "||agnesb.fr",
```

**Comment by chenshaoju** [comment]
你自己写的PAC可能会不工作，我还没仔细看代码，似乎只能使用从菜单中更新下来的 pac.txt 。

应该是有什么代码在 pac.txt 里工作，才能使用 user-rule.txt 。

请备份当前的 pac.txt ，然后从托盘区纸飞机图标的右键菜单中选择“从GFWList更新本地PAC”看看。

**Comment by kran** [comment]
我没辙了，还是不行。

**Comment by chenshaoju** [comment]
现在的情况是，你是否使用了“从GFWList更新本地PAC”更新下来的PAC，并且将 ``` ||2017.ip138.com/ic.asp ``` 写入了 user-rule.txt ？

**Comment by kran** [comment]
没错：
1. 删掉目录下除gui-config和exe外的其他文件
2. 启动ss，更新pac，更新user-rule
3. 编辑user-rule
4. 关闭系统代理， 启动系统代理

没有作用。。

**Comment by chenshaoju** [comment]
请看一下你的浏览器代理设置，PAC生效了吗？应该会出现一个类似 ``` http://127.0.0.1:1080/pac ``` 开头的内容。

![image](https://user-images.githubusercontent.com/515763/37508418-e86cf7e0-292d-11e8-8eaf-39378dffcb5e.png)

注意，如果你有使用某些VPN，可能需要检查VPN的连接。

**Comment by kran** [comment]
我这里只有“局域网设置”里面和你截图一样，访问那个地址，内容就是pac.txt，而且里面也确实有ip138的规则。

**Comment by kran** [comment]
其实我看，代理一定是起作用了，因为
```
2017.ip138.com/*
```
这样的规则是有效的，只要加path，就不行。

**Comment by kran** [comment]
```
function FindProxyForURL(url, host) {
    if (url.startsWith("http://2017.ip138.com/ic.asp")) {
	return proxy;
    }
    if (defaultMatcher.matchesAny(url, host) instanceof BlockingFilter) {
        return proxy;
    }
    return direct;
}
```

奇怪，我把pac下的函数改成这样，也不管用。

**Comment by kran** [comment]
我感觉发现问题了：
如果我把FindProxyForUrl函数改成这样：
```
if (url.match(/ip138.com\/$/)) {
		return proxy;
}
```
是会走ss的，正则匹配了结尾了，说明url根本就没有path部分。

**Comment by chenshaoju** [comment]
你可能得去GFWList问一下了，Shadowsocks使用的是GFWList的列表，对GFWList并没有控制权： https://github.com/gfwlist/gfwlist

**Comment by kran** [comment]
说实话，我也不认为这是gfwlist的问题，它只是文本，看起来是浏览器并没有把完整的url传递给pac脚本。但你那里是好用的，这就有点挠头了。

**Comment by chenshaoju** [comment]
我的情况很特殊，我是自己写的PAC，使用GFWList的确没有问题，也不需要反复关闭开启系统代理。

请尝试使用GFWList的PAC后，增加下列行：
```
|http://2017.ip138.com/ic.asp
```
然后再试。

**Comment by kran** [comment]
偶然发现IE是走代理的，但ff，edge都不走。
ff的网络配置是：使用系统的代理设置。

这行只在ie下有效：
```
|http://2017.ip138.com/ic.asp
```
去掉path部分后所有浏览器都有效。

**Comment by chenshaoju** [comment]
测了一下，我这儿也是只有IE工作。猜测要么是GFWList的实现有问题，要么是浏览器不支持了。。。这个我就不懂了。。。

**Comment by kran** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file

这里有写：

> The URL being accessed. The path and query components of https:// URLs are stripped. In Chrome, you can disable this by setting PacHttpsUrlStrippingEnabled to false, in Firefox the preference is network.proxy.autoconfig_url.include_path.

是需要设置的。:(  
这一天。。。。

**Comment by chenshaoju** [comment]
Hmmmm....

**Comment by kran** [comment]
@chenshaoju 多谢今天的指导。 那我就关闭issue了。
