### ISSUE TITLE
由于目标计算机积极拒绝，无法连接

### ISSUE THREAD

**Issue by kshu1989** [shadowsocks/shadowsocks-windows#1754]
使用Google服务器，服务器配置，ubuntu
使用： ufw disable  关闭了防火墙

ifconfig:
ip地址：a.a.a.a
实际机器外网ip地址：b.b.b.b

server：“0.0.0.0"
这个配置成b.b.b.b server启动失败，看了教程，改成0.0.0.0，可以启动。

客户端配置：
服务器地址：b.b.b.b

客户端报错：
System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

```
[2018-03-16 16:52:48] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult) 在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult) 在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar) 
```

**Comment by chenshaoju** [comment]
这意味着你到你的服务器的端口不通。

请尝试使用 tcping 从客户端检查到你的服务端口是否通畅： https://www.elifulkerson.com/projects/tcping.php

**Comment by kshu1989** [comment]
tcping a.a.a.a 确实不通Probing a.a.a.a:80/tcp - No response - time=2015.925ms
试了自己开的端口，也不通
服务器监听的ip不对？
instance-1:~$ sudo netstat -an | grep '3889'
tcp        0      0 0.0.0.0:3889            0.0.0.0:*               LISTEN     
udp        0      0 0.0.0.0:3889            0.0.0.0:*                          
kshu1989@instance-1:~$

**Comment by kshu1989** [comment]
@chenshaoju 
服务器端口打开
instance-1:~$ sudo netstat -an | grep '3889'
tcp        0      0 0.0.0.0:3889            0.0.0.0:*               LISTEN     
udp        0      0 0.0.0.0:3889            0.0.0.0:*                          
客户端依然tcping 不通
Probing a.a.a.a/tcp - No response - time=2001.660ms

**Comment by chenshaoju** [comment]
这意味着你的服务端配置不正确，请检查包括iptables在内的网络防火墙。

tcping 需要带上你的端口号，比如你的服务器是 123.45.67.89 ，端口在 9876 的话：
```
tcping 123.45.67.89 9876
```

**Comment by kshu1989** [comment]
还是不行，tcping带了端口的，不通
instance-1:~$ netstat -lnp|grep 3889
(No info could be read for "-p": geteuid()=1001 but you should be root.)
tcp        0      0 0.0.0.0:3889            0.0.0.0:*               LISTEN      -               
udp        0      0 0.0.0.0:3889            0.0.0.0:*                           -      

tcping a.a.a.a 80  也不通
我用的是ubuntu，端口应该已经打开了
nstance-1:~$ sudo ufw status
Status: active
To                         Action      From
--                         ------      ----
80                         ALLOW       Anywhere
3889                       ALLOW       Anywhere
80 (v6)                    ALLOW       Anywhere (v6)
3889 (v6)                  ALLOW       Anywhere (v6)

不过现在已经好了。
我安装了apache，启动后，使用netstat 看到80端口已经开了，tcping 80端口可以通的。
然后我把shadowsocks配置改成80端口，关了apache，之后可以通了，netstat上也有80端口已经打开。

问题应该是服务器端口没打开，查了这么久，不知道怎么打开端口，使用了iptables ，ufw等，不过最终还是谢谢！

**Comment by chenshaoju** [comment]
也可能和你服务商提供的管理后台的防火墙有关，具体的请参阅你服务器服务商的帮助页面。
