### ISSUE TITLE
ss-win4.0.9在整理系统后异常：Shadowsocks 错误: 不支持此接口

### ISSUE THREAD

**Issue by patxiao** [shadowsocks/shadowsocks-windows#1757]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
OS：win7旗舰版sp1
.NET Framework：4.6.2和4.7.1均不行

### Steps you have tried / 操作步骤
之前现象：Mac和Mobile都可用，Windows也可用（ss-win4.06），但是编辑本地PAC文件会有GUI报错，因此删除了一些第三方GUI程序。

当前现象：Mac和Mobile依然可用，Windows启动ss报错（4.06/4.09），切换模式、切换服务器报错，代理不生效。

已尝试操作：
1. 卸载安装.NET Framework 4.6.2
2. 卸载安装VC2015
3. 升级到.NET Framework 4.7.1
4. 下载最新ss-windows 4.09
均无效。

### What did you expect to see? / 期望的结果
正常使用

### What did you see instead? / 实际结果
报错

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
启动/切换模式报错：
---------------------------
Shadowsocks 错误: 不支持此接口
---------------------------
System.ComponentModel.Win32Exception (0x80004005): 不支持此接口    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)    at System.Diagnostics.Process.Start()    at Shadowsocks.Controller.PrivoxyRunner.Start(Configuration configuration)    at Shadowsocks.Controller.ShadowsocksController.Reload()
---------------------------
确定   
---------------------------

日志信息：
[2018-03-18 12:03:33] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-03-18 12:14:03] System.InvalidOperationException: 没有与此对象关联的进程。
   在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.get_MainWindowHandle()
   在 System.Diagnostics.Process.CloseMainWindow()
   在 Shadowsocks.Controller.PrivoxyRunner.KillProcess(Process p)
[2018-03-18 12:14:07] System.InvalidOperationException: 没有与此对象关联的进程。
   在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.get_MainWindowHandle()
   在 System.Diagnostics.Process.CloseMainWindow()
   在 Shadowsocks.Controller.PrivoxyRunner.KillProcess(Process p)
[2018-03-18 12:47:49] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by patxiao** [comment]
>删除文件夹无效。
关闭防火墙无效。

猜测和防火墙无关，没有改动防火墙配置，猜想和Windows的网络连接模块有关。
下图是ss启动/切换模式的报错：
![e3056d50f9baeb7c438d3a3aaa06cae0](https://user-images.githubusercontent.com/5857326/37563128-11c8796a-2ab5-11e8-8e7a-35885c15da7e.png)

下图是Window异常检测引导的1080相关配置信息：
![51f0ea9c01e8ffaaaf8e80bec291c87d](https://user-images.githubusercontent.com/5857326/37563142-2f6b5ce4-2ab5-11e8-9638-ba0e1d13a490.png)

**Comment by chenshaoju** [comment]
这是两个东西。

不过，从提示上看，和自带的Privoxy有关。

把 Shadowsocks.exe 放到另一个目录看看？比如 D:\SS\ ？

另外，是否有什么安全软件阻止了应用启动之类的？

**Comment by patxiao** [comment]
换了目录后提示相同。
只安装了腾讯电脑管家，已经关闭了。

**Comment by chenshaoju** [comment]
你是否配置了插件？比如kcptun或者simpel obfs之类的？

**Comment by chenshaoju** [comment]
另外，进入 Shadowsocks.exe 目录下的 ss_win_temp 文件夹，有一个 ss_privoxy.exe ，双击，能否出来一个提示？

类似这样，我想知道你的 privoxy 能否起来。
![image](https://user-images.githubusercontent.com/515763/37563474-6a7be400-2abc-11e8-9b07-733e4222186e.png)

**Comment by patxiao** [comment]
>没有配置插件。
打开ss_privoxy.exe提示和你的一样。

还有一个信息：昨天操作后，我的windows普通登录账户，右键没有“以管理员身份打开”这个选项了。

另外做网络异常诊断有如下提示：
![8ac128393302388ce2bd4ea740591813](https://user-images.githubusercontent.com/5857326/37563539-f904c6f0-2abd-11e8-896b-338b11dc2414.png)

**Comment by chenshaoju** [comment]
如果你能启动SS，能显示服务器界面的话，把编辑服务器界面右下角的1080换一个端口看看，比如12321。

如果无法启动SS，请用Windows自带的记事本打开 Shadowsocks.exe 所在目录下的 gui-config.json ，找到 ```"localPort": 1080,```，将1080修改为别的端口，保存退出后再试。

我个人感觉你这个系统好像有问题。

**Comment by patxiao** [comment]
能启动ss，之前也改过端口，刚刚又改了，结果一样。

**Comment by eromoe** [comment]
整理系统  估计指的是 ccleaner 。 今天升级windows 发现c盘不够了，下了个。
之后就出错了， 然后在进程里看到了 avast 。 卸载后就正常了， ccleaner 也这么流氓了
