### ISSUE TITLE
url encoded ipv6 SS-URI link cause shadowsocks-android crash 生成的二维码/URI导致 shadowsocks-android 崩溃

### ISSUE THREAD

**Issue by zmz125000** [shadowsocks/shadowsocks-windows#1758]
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
Shadowsocks-4.0.9

### Steps you have tried / 操作步骤
注：用了 simple-obfs 才会这样
on shadowsocks-windows share ipv6 server config and scan qrcode using shadowsocks-android 

### What did you expect to see? / 期望的结果
ss://[method&password]@**[fdc3:90ba:caaa:4e91::]**:443

### What did you see instead? / 实际结果
shadowsocks-android crash
ss://[method&password]@**fdc3%3a90ba%3acaaa%3a4e91%3a%3a**:443

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
你好，我使用 4.5.0 版本的 Shadowsocks for Android 扫了一下Shadowsocks for Windows生成的二维码，没有问题。这是一个无效服务器，使用IPv6地址，你可以测试一下：
![image](https://user-images.githubusercontent.com/515763/37578368-5607d652-2b73-11e8-9fb2-0e6d7721ce35.png)

你是不是用了simple_obfs或者ktcp这种插件？

**Comment by zmz125000** [comment]
@chenshaoju 对， 用了 simple-obfs 才会这样。

**Comment by chenshaoju** [comment]
此问题可能需要跨项目协调，请等待开发人员处理。

**Comment by celeron533** [comment]
Reproduced the issue after enable the plug-in with ipv6

**Comment by celeron533** [comment]
@zmz125000  请查看下这个build时候解决了问题
https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/4.0.9.10/job/ef49s1343ts4fa5t/artifacts

**Comment by zmz125000** [comment]
@celeron533 
ss://[method&password]@[fdc3:90ba:caaa:4e91::]:443
IP 要加方括号

**Comment by celeron533** [comment]
@zmz125000 
https://tools.ietf.org/html/rfc5952

>6.  Notes on Combining IPv6 Addresses with Port Numbers
   There are many different ways to combine IPv6 addresses and port
   numbers that are represented in text.  Examples are shown below.
   o  [2001:db8::1]:80
   o  2001:db8::1:80
   o  2001:db8::1.80
   o  2001:db8::1 port 80
   o  2001:db8::1p80
   o  2001:db8::1#80

**Comment by zmz125000** [comment]
@celeron533
不加括号 shadowsocks-android 会崩溃，看来要到那边开 issue

**Comment by celeron533** [comment]
>不加括号 shadowsocks-android 会崩溃

RFC里建议v6地址加括号
桌面客户端这边需要再看看做这个改动会不会影响到其他程序的读取

不过android读没括号的已经崩了~

**Comment by celeron533** [comment]
Android版生成的QR是带方括号的
`ss://YWVzLTI1Ni1jZmI6c2RzZGZzZGY@[fe80::1111:1111:1111:1111]:8388#local%2Bv6`

**Comment by celeron533** [comment]
Please try this build.
Added square brackets for SIP002 server address.
https://ci.appveyor.com/project/celeron533/shadowsocks-windows-3j4p4/build/job/ng54kq03d79uccj3/artifacts

**Comment by zmz125000** [comment]
@celeron533 Testing passed

**Comment by celeron533** [comment]
@zmz125000 有空的话麻烦请看看IPv4和域名的识别情况

**Comment by madeye** [comment]
It's been fixed via https://github.com/shadowsocks/shadowsocks-android/commit/c64e15acad1b4b8e93d6e639bbb894c4650b3657

**Comment by celeron533** [comment]
Thanks @madeye ! I've also added brackets for SIP002 SIP003 server share protocol in Windows version.
