### ISSUE TITLE
部分程序可通过ss代理上网，部分不行，全局代理也不能上网

### ISSUE THREAD

**Issue by i65536** [shadowsocks/shadowsocks-windows#1759]
在今天之前我这台电脑使用ss来上网是完全没有问题的。
今天我更新了系统（Windows 10 企业版 Build 17120.rs4_release.180309-1616），重启完后恰好Shadowsocks客户端也下载了更新（4.0.9）。
这是背景。
————————————————
其后出现故障：
Chrome通过Proxy SwithyOmega设置127.0.0.1:1080代理，**正常连接**
Firefox通过Autoproxy设置127.0.0.1:1080代理，**正常连接**
Telegram通过程序内设置127.0.0.1:1080代理，不能连接
SocksCap64设置127.0.0.1:1080代理，不能连接，提示“协商代理认证方式失败”
启用系统代理（PAC或全局），所有走IE代理的程序均不能连接

尝试过：
重启电脑、重置网络、关闭防火墙、更换ss本地代理端口、删除ss重新配置、换ss文件夹名、用老版本ss，均不能解决问题
查看ss日志无报错，但上述不能连接的时候不会出现访问域名的记录
netstat -ano 上述无论是否正常连接的情况，端口监听和活动连接均可看到

另一台电脑的情况：
系统也是17120，专业版；ss也更新到了4.0.9
无上述问题

通过上述现状猜测：
服务端正常
ss客户端与服务端之间的连接正常
ss客户端成功开启了本地代理端口
问题出在本地socks5这块

部分程序可以通过该端口连接，部分程序不能通过该端口连接，说明问题出在这里，并且有程序提示“协商代理认证方式失败”，是不是问题出现在socks5协议认证这块？我不懂这部分内容，纯属猜测，还请各位帮忙解决一下这个问题。谢谢！

**Comment by chenshaoju** [comment]
Telegram请确保使用了 TCP With custom socks5-proxy 选项。

请尝试使用 https://www.proxifier.com/download/ 提供的 Proxy Checker 测试一下你的本地SS代理看看？
![image](https://user-images.githubusercontent.com/515763/37593461-0725d0b8-2bad-11e8-924a-8066c5121907.png)

测试的时候请注意选择SOCKS5。
![image](https://user-images.githubusercontent.com/515763/37593476-13f83600-2bad-11e8-8e70-886e3bcff450.png)

**Comment by i65536** [comment]
@chenshaoju 谢谢回答。
我测试了一下，可以通过，但Telegram依然不能连接。如下图：
![default](https://user-images.githubusercontent.com/37533738/37594606-aa2ab5b4-2bb0-11e8-980b-bd2bb4b6d4e3.PNG)
![2](https://user-images.githubusercontent.com/37533738/37594608-aa71fcee-2bb0-11e8-932e-e7230986e450.PNG)

**Comment by chenshaoju** [comment]
这虽然不太可能，但是这个意思看起来是你的服务器屏蔽／无法到达这些IP／域名？你服务器的DNS可能有问题？

请尝试修改 Proxy Checker 的 Test Settings ，将 Target host其修改为 149.154.167.99，Port 为 80 。

还有 core.telegram.org ，Port 也是 80 。

能否测试成功？这是Telegram的API Server之一。

![image](https://user-images.githubusercontent.com/515763/37604522-227f0bb2-2bcc-11e8-85e0-f6f96c0a7712.png)

**Comment by i65536** [comment]
@chenshaoju 上述测试可通过
![1](https://user-images.githubusercontent.com/37533738/37628624-27a0d3ca-2c15-11e8-87ca-d666e7a0ccae.PNG)
![2](https://user-images.githubusercontent.com/37533738/37628642-392af620-2c15-11e8-88a7-69fa6f0f88cd.PNG)

**Comment by celeron533** [comment]
（我没细看上面的内容）看看是不是迅雷干扰了socks5

**Comment by i65536** [comment]
@celeron533
应该不是，卸载了迅雷没有效果，另一台电脑上也有同一版本的迅雷但没问题

**Comment by i65536** [comment]
我测试了v2ray、蓝灯等类似工具，也出现同样现象，问题应该不在Shadowsocks。
我准备重置系统或者回上一版本了。

**Comment by chenshaoju** [comment]
这看起来很像你的电脑上有什么东西干扰了本地SOCKS连接，但具体是什么，可能比较难搞清。

通过测试，基本上能确定SS和你的服务器都没有问题。

请检查后台进程，是否有系统以外的不明进程在运行。

猜测和Winsocks有关，请尝试以管理员身份启动命令提示符（CMD）或PowerShell，然后运行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```

如果仍然不行，可能需要重置系统看看了。

**Comment by i65536** [comment]
@chenshaoju 之前试过重置网络了，无效。

已回退前一版本系统（Build 17115.rs4_release.180302-1642），一切恢复正常。
看来就是系统新版本出现的问题。

谢谢各位

**Comment by i65536** [comment]
今天系统升级到了 Build 17127，跟17120版同样的问题
