### ISSUE TITLE
I hope the client listens "[::1]"

### ISSUE THREAD

**Issue by giftzn** [shadowsocks/shadowsocks-windows#1760]
### What did you expect to see? / 期望的结果
I hope the client listens "[::1]".

### What did you see instead? / 实际结果
Client listening does not listen to local IPV6 address.

> https://github.com/shadowsocks/shadowsocks-android is listening on local IPV6.

Although this is a detail, if the proxy address is localhost, some clients will request the IPV6 address and then request the IPV4 address, resulting in an increase in the local delay.

**Comment by celeron533** [comment]
What are the software's name and how much delay?

**Comment by giftzn** [comment]
`Telegram Desktop` will do this, `Xshell` even directly shows that the connection failed, Because it is connected to the IPV6 address.
