### ISSUE TITLE
4.0.7升级到4.0.9版本，运行obfs插件无法建立连接

### ISSUE THREAD

**Issue by Suwmlee** [shadowsocks/shadowsocks-windows#1761]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10   .net framework 4.6.2

### Steps you have tried / 操作步骤
将运行正常的4.0.7版本替换为4.0.9版本

### What did you expect to see? / 期望的结果
使用obfs插件运行正常

### What did you see instead? / 实际结果
使用4.0.9版本后，不使用obfs运行正常，使用obfs后，无法建立连接

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
Started SIP003 plugin for 123.123.123.213:1234 on 127.0.0.1:8578 - PID: 15184
System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult) in D:\Projects\Proxy\shadowsocks-windows\shadowsocks-csharp\Util\Sockets\WrappedSocket.cs:line 140
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult) in D:\Projects\Proxy\shadowsocks-windows\shadowsocks-csharp\Proxy\DirectConnect.cs:line 63
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar) in D:\Projects\Proxy\shadowsocks-windows\shadowsocks-csharp\Controller\Service\TCPRelay.cs:line 741

备注：
======
单独命令行启动obfs插件，将4.0.9版本的SS端口指向obfs是正常的。

**Comment by chenshaoju** [comment]
你好，你用的是simple-obfs吗？ https://github.com/shadowsocks/simple-obfs

**Comment by Suwmlee** [comment]
你好，是的

**Comment by chenshaoju** [comment]
你的服务端是否已经搭建好了 simple-obfs ？这个提示看起来很像你的obfs配置不正确或者服务端没有使用obfs，导致连接被拒绝(refused)。

**Comment by Suwmlee** [comment]
simple-obfs已经用了很久了，今天看到win版本有4.0.9就升级了一下，配置什么的都没有改过，就替换了一个应用程序而已。

我这边的情况是，4.0.9版本不使用simple-obfs是可以正常访问的，使用simple-obfs就无法访问了。在我以前使用的4.0.7版本上没有这个问题，simple-obfs也可以正常使用。

如果单独启动simple-obfs的客户端，设置其本地端口8089，将SS服务器设置为127.0.0.1，端口设置为8089，这样也是使用simple-obfs插件，也是可以正常访问的，所以simple-obfs应该是没有问题的。

**Comment by chenshaoju** [comment]
有点不同的是，你自己指定了8089，但是SS却是8578，这个端口应该是随机的。

我怀疑你本机是不是有网络防火墙之类的东西？

如果退回 4.0.7 ，是否就正常了？

**Comment by Suwmlee** [comment]
4.0.7都是正常的，上面都说过了。问题应该出在SS内部管理插件的端口上。我本机的防火墙都是关着的
		
		

		
	




On Tue, Mar 20, 2018 at 6:27 PM +0800, "Chen Shaoju" <notifications@github.com> wrote:












有点不同的是，你自己指定了8089，但是SS却是8578，这个端口应该是随机的。


我怀疑你本机是不是有网络防火墙之类的东西？


如果退回 4.0.7 ，是否就正常了？

**Comment by celeron533** [comment]
有尝试过4.0.8么？

**Comment by chenshaoju** [comment]
最奇怪的地方就在这里，我使用了 shadowsocks-libev_3.0.8-1_amd64.deb + simple-obfs_0.0.4-1_amd64.deb 在 Debian 9.4 x64 上的服务器环境上搭建了一个。

客户端使用 Windows 7 SP1 x64 + Shadowsocks for Windows 4.0.9 + simple-obfs 0.0.5 ，并没有问题。

不过今天也有一位用户报告了类似的问题，但是不是 obfs 相关：https://github.com/shadowsocks/shadowsocks-windows/issues/1759

能否告知你的Windows 10具体版本？

**Comment by Suwmlee** [comment]
正好有时间看了下，问题解决了

4.0.7之后的某个版本解决了插件的一个bug，引发的问题。现在更新所有软件和配置，已经正常连接了。

Thanks

**Comment by chenshaoju** [comment]
@Suwmlee 顺带问一下，“更新所有软件和配置”，是指使用 4.0.9 的 Shadowsocks for Windows 和 0.0.5 的 simpel-obfs 吗？

**Comment by Suwmlee** [comment]
嗯，问题主要在4.0.9的SS-win的配置上。
我之前用的simpel-obfs 是自己编译的，顺带更新了下最新的simpel-obfs 。

**Comment by chenshaoju** [comment]
明白了，感谢。

**Comment by polong** [comment]
我问一下，我路由器也出现类似问题，我用openwrt-shadowsocks有用simple-obfs插件，3.1.3版本就连不上，而3.1.2版本就连得上，是一个问题吗？怎么解决？

**Comment by Suwmlee** [comment]
@polong openwrt上的我不太清楚，我路由器上年前更新过一次，使用正常。
我遇到的这个问题是因为以前ss-win会启动多个插件，现在只启动对应的插件，正好我在使用的节点配置有点问题，其他未使用的节点配置是正确的。
