### ISSUE TITLE
开启pac模式无法使用Google

### ISSUE THREAD

**Issue by crazystudy** [shadowsocks/shadowsocks-windows#1764]
只有在全局模式下才能正常使用Google,pac模式无法使用.

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
WIN10   .net framework  4.6.1

**Comment by chenshaoju** [comment]
你好，请尝试更新一下PAC看看？可以右击托盘区的纸飞机图标，选择PAC菜单后，点击“从GFWList更新本地PAC”。

**Comment by crazystudy** [comment]
完美解决,谢谢

**Comment by huangtting** [comment]
@chenshaoju 不好意思打扰一下。我也遇到了这个问题，已从“从GFWList更新本地PAC”。shadowsocks版本为4.1.5。全局模式可用，运行在本机80端口
日志如下：
![企业微信截图_15540879048983](https://user-images.githubusercontent.com/26655372/55301225-119abc80-546e-11e9-9eee-481322edca6e.png)
好像只要开启pac模式就没有上下行流量。

**Comment by chenshaoju** [comment]
请检查一下这个地方：
![2019-03-28 (1)](https://user-images.githubusercontent.com/515763/55163990-c6e71f00-51a5-11e9-9996-eabf021663b8.png)
