### ISSUE TITLE
shadowsocks同一服务器在学校电脑上可以上自己电脑上上不了

### ISSUE THREAD

**Issue by zyl112233** [shadowsocks/shadowsocks-windows#1765]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
shadowsocks 4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10

RT
同一服务器在学校电脑上能用 而且很快 自己电脑上就用不了了

**Comment by chenshaoju** [comment]
请问日志中有什么显示吗？另外通过浏览器访问的话，显示什么？

**Comment by zyl112233** [comment]
@chenshaoju 谢谢你的回答 问题已解决。只是学校的WiFi昨天晚上出问题 电脑是直接接网线的。 今天已经恢复正常。
