### ISSUE TITLE
官网上不去了？

### ISSUE THREAD

**Issue by Gloamwood** [shadowsocks/shadowsocks-windows#1766]
好像是前天开始就登不上去了0.0

**Comment by chenshaoju** [comment]
Shadowsocks 的官网是 shadowsocks.org ，如果你在某个宣称 Shadowsocks 官网的网站上购买了服务，该网站和 Shadowsocks 项目没有任何关系。

Shadowsocks for Windows 不以任何形式销售 SS 服务。

**Comment by Gloamwood** [comment]
哦哦，谢谢啦，
