### ISSUE TITLE
QRCodeSplashForm.cs窗口设计器打不开

### ISSUE THREAD

**Issue by Coel0728** [shadowsocks/shadowsocks-windows#1768]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Win10,VS2015

### Steps you have tried / 操作步骤

双击打开QRCodeSplashForm.cs[设计]

### What did you expect to see? / 期望的结果

正常打开

### What did you see instead? / 实际结果

创建窗口句柄时出错

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
创建窗口句柄时出错。

在 System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
在 System.Windows.Forms.Control.CreateHandle()
在 System.Windows.Forms.Form.CreateHandle()
在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
在 System.Windows.Forms.Control.CreateControl()
在 System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
在 System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
在 System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
在 System.Windows.Forms.Control.SetVisibleCore(Boolean value)
在 System.Windows.Forms.Form.SetVisibleCore(Boolean value)
在 System.Windows.Forms.Control.set_Visible(Boolean value)
在 System.Windows.Forms.Design.DesignerFrame.Initialize(Control view)
在 System.Windows.Forms.Design.DocumentDesigner.Initialize(IComponent component)
在 System.Windows.Forms.Design.FormDocumentDesigner.Initialize(IComponent component)
在 System.ComponentModel.Design.DesignerHost.AddToContainerPostProcess(IComponent component, String name, IContainer containerToAddTo)
在 System.ComponentModel.Design.DesignerHost.PerformAdd(IComponent component, String name)
在 System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.CreateComponent(Type componentType, String name)
在 System.ComponentModel.Design.Serialization.DesignerSerializationManager.CreateInstance(Type type, ICollection arguments, String name, Boolean addToContainer)
在 System.ComponentModel.Design.Serialization.DesignerSerializationManager.System.ComponentModel.Design.Serialization.IDesignerSerializationManager.CreateInstance(Type type, ICollection arguments, String name, Boolean addToContainer)
在 System.ComponentModel.Design.Serialization.TypeCodeDomSerializer.Deserialize(IDesignerSerializationManager manager, CodeTypeDeclaration declaration)
在 System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
在 Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
在 Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.DeferredLoadHandler.Microsoft.VisualStudio.TextManager.Interop.IVsTextBufferDataEvents.OnLoadCompleted(Int32 fReload)

**Comment by chenshaoju** [comment]
Odd，看起来很像你的 .NET Framework损坏了，请尝试使用 https://www.microsoft.com/en-us/download/details.aspx?id=30135 进行修复看看。

**Comment by Coel0728** [comment]
还是不行，只有这个打不开

![qq 20180324185555](https://user-images.githubusercontent.com/36911192/37863182-197e54c4-2f95-11e8-8a9d-507ae993a6af.png)
![qq 20180324185546](https://user-images.githubusercontent.com/36911192/37863189-2822f50c-2f95-11e8-92a3-18e73302a979.png)

**Comment by studentmain** [comment]
重新下载一下源代码？或者直接打开代码本身看看？

Coel0728 <notifications@github.com> 于 2018年3月24日周六 18:57写道：

**Comment by Coel0728** [comment]
打开代码没有问题，也没有报错，就是设计报错。我换了别的版本（比如3.4.1）也是这样。

**Comment by studentmain** [comment]
- 在 Microsoft.VisualStudio.Design.Serialization.CodeDom.MergedCodeDomParser.System.CodeDom.Compiler.ICodeParser.Parse(TextReader stream)
- 在 System.CodeDom.Compiler.CodeDomProvider.Parse(TextReader codeStream)
- 在 Microsoft.VisualStudio.Shell.Design.Serialization.CodeDom.CodeDomDocDataAdapter.get_CompileUnit()
- 在 Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
- 在 Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.DeferredLoadHandler.Microsoft.VisualStudio.TextManager.Interop.IVsTextBufferDataEvents.OnLoadCompleted(Int32 fReload) 

VS2017 .net framework 4.6.2 同样的错误

**Comment by Coel0728** [comment]
怎么解决呢？

**Comment by studentmain** [comment]
错误不太稳定，每次打开错误都不一样……现在我这错误是类PerPixelAlphaForm可以进行设计但不是文件中的第一个类……

Coel0728 <notifications@github.com> 于 2018年3月24日周六 19:33写道：

**Comment by studentmain** [comment]
类QRCodeSplashForm直接继承Form之后可以了……但是不清楚有没有副作用

**Comment by studentmain** [comment]
推测故障原因是一个.cs里面包含有两个Form的派生类。把PerPixelAlphaForm中的内容搬到QRCodeSplashForm里，并删除PerPixelAlphaForm后可以正常显示窗口设计器。
但是考虑到QRCodeSplashForm用于处理扫描二维码，不存在典型的窗口也就并不需要窗口设计，可以不处理。
@Coel0728 
@chenshaoju 如果要处理，我发pr?

**Comment by Coel0728** [comment]
谢谢了

**Comment by chenshaoju** [comment]
可以的，最终还需要 @celeron533 Approve。
