### ISSUE TITLE
如何编译provixy，我在source forge找到了，不会编译

### ISSUE THREAD

**Issue by Coel0728** [shadowsocks/shadowsocks-windows#1772]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）

VS2015 4.6.5
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
没有sln，网上说要用make，应该怎么编译?谢谢各位大神

**Comment by studentmain** [comment]
第三方组件，去他们那边提问。如果不知道什么是make，自己上网查查。不过其实没有自己编译一个的必要。

Coel0728 <notifications@github.com> 于 2018年3月25日周日 18:29写道：

**Comment by celeron533** [comment]
>没有sln

因为privoxy并不是基于visualstudio的项目。编译方法需要去privoxy那边查看，不属于本repo的范畴
