### ISSUE TITLE
客户端无法打开，非预期错误。可能和更新系统补丁有关

### ISSUE THREAD

**Issue by orangewangjie** [shadowsocks/shadowsocks-windows#1773]
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues  System.BadImageFormatException: 未能加载文件或程序集“System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”或它的某一个依赖项。该模块应包含一个程序集清单。 文件名:“System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”    在 Shadowsocks.Model.StatisticsStrategyConfiguration..ctor()    在 Shadowsocks.Model.StatisticsStrategyConfiguration.Load()    在 Shadowsocks.Controller.ShadowsocksController..ctor()    在 Shadowsocks.Program.Main()  警告: 程序集绑定日志记录被关闭。 要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。 注意: 会有一些与程序集绑定失败日志记录关联的性能损失。 要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

**Comment by chenshaoju** [comment]
你好，请安装最新的 .NET Framework https://www.microsoft.com/net/download/thank-you/net471

**Comment by angluaJs** [comment]
是最新版的.net framework ,仍然报这个错误

**Comment by chenshaoju** [comment]
@angluaJs 请尝试再次下载.NET安装程序（见楼上），然后修复安装一次看看。
