### ISSUE TITLE
遇到一个诡异的问题-假死

### ISSUE THREAD

**Issue by hanzochen** [shadowsocks/shadowsocks-windows#1775]
shadowsocks最近在一台电脑上出现“假死”状况，具体情况如下：
win10，自建vps，ss版本4.0.9，赋予管理员权限。
每次启动后，1分钟左右就会进入假死状态，也就是0流量，此时只要去更换服务器，或者干脆在原服务器上重新点击一次，又可以正常翻墙，但是不久又回到那个假死状态。
日志查看过了，没有任何提示。换另两台电脑，同样win10，同样的服务器，很流畅。几台电脑的win10都是自动更新。
试过关闭defender和杀毒，也没什么效果。近期有印象的就是4.0.9被defender拦截一次，手动允许了。

不知道是不是win10的某些服务没设定为自动所以导致这个状况的？只能求助各位大神。

**Comment by hanzochen** [comment]
另外，退回4.0.8和4.0.7都试过了，一样的问题

**Comment by chenshaoju** [comment]
有使用系统代理吗？你使用的是全局模式还是PAC模式？

另外，你是否安装了爱奇艺？ https://github.com/shadowsocks/shadowsocks-windows/issues/1689#issuecomment-366937201

**Comment by hanzochen** [comment]
PAC和全局都是同样问题，全局会导致彻底无法上网。没有爱奇艺的x86程序，只有uwp，而且对照组的其他机器基本软件安装情况都是几乎相同的。

**Comment by chenshaoju** [comment]
可能和协议栈有关，请以管理员身份启动命令提示符（ｃｍｄ）或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一回车，三行执行完毕后重新启动计算机看看。

**Comment by hanzochen** [comment]
都试过了，问题依旧

**Comment by chenshaoju** [comment]
日志中有无任何错误提示？

**Comment by hanzochen** [comment]
不想为了个ss重装系统啊……所以来问问ss在win10下依赖哪些系统服务，我去查查是否有被禁用的。

**Comment by chenshaoju** [comment]
SS不依赖服务，依赖 .NET Framework 组件，但是如果.NET组件有问题，很大的可能性一启动就会有问题，不会出现一开始能用但是过一会儿就失效的问题。

如果有Firefox，请参考下图独立配置Firefox的代理设置，看看是否还会失效。

![image](https://user-images.githubusercontent.com/515763/37390878-680ff942-27a4-11e8-81f1-54edfe7658d9.png)

**Comment by celeron533** [comment]
问题发生的时候检查一下系统代理是不是被其它软件夺走了
以前也有人汇报过类似的问题，结果是有其他工具在后台间歇性的覆盖系统代理

**Comment by hanzochen** [comment]
并非如此，我去查过，ss假死时候，系统代理仍然是pac脚本，并没有任何变化

**Comment by chenshaoju** [comment]
@hanzochen 请问使用Firefox测试，结果如何？

**Comment by hanzochen** [comment]
@chenshaoju 毛病依旧，疑难杂症了。各种实验后，确定是ss本身卡死。算了，等下次重装系统吧……

**Comment by chenshaoju** [comment]
你是否使用的预览版Win10？最近有很多类似的报告： https://github.com/shadowsocks/shadowsocks-windows/issues/1774

**Comment by hanzochen** [comment]
@chenshaoju 没有，是稳定支线的win10，没有去开通创意者线路什么的。算了，幸好不怎么看视频，手动去反复激活就是了，等下次重装系统吧。幸好笔记本上正常。

**Comment by chenshaoju** [comment]
对了，单独使用Firefox并指定代理的测试做了吗？一样会失效？

**Comment by hanzochen** [comment]
@chenshaoju 一样，就是ss本身进程出现问题了，100%确定。

**Comment by chenshaoju** [comment]
问题就在这里，我自己用的也是Win10，但是从来没遇到过该问题。

如果启用SS详细日志，在出现问题后１～２分钟，是否有显示？右击纸飞机小图标，选择帮助，有一个详细记录日志。

**Comment by hanzochen** [comment]
@chenshaoju 我也很奇怪，因为我其他win10的电脑也没问题，装的软件也都大同小异，而ss日志也是毫无反应，但是就是需要去重新“激活”一下才能运行个几分钟。

**Comment by chenshaoju** [comment]
如果启用详细日志呢？

**Comment by hanzochen** [comment]
@chenshaoju 肯定早就启用了，就是什么都没有

**Comment by chenshaoju** [comment]
可能真需要重置系统看看了。。。请记得备份数据后再重置。

**Comment by hanzochen** [comment]
更新了一次win10，莫名其妙好了。

**Comment by chenshaoju** [comment]
@HTSW 你是否使用的是拨号连接（比如PPPoE）上网？如果是，把你的拨号连接的连接名改成英文的看看？

**Comment by HTSW** [comment]
谢谢回复，我这里发现是我的代理设置有问题，现在已经设置好了，谢谢解答

2018-05-12 17:00 GMT+08:00 Chen Shaoju <notifications@github.com>:

**Comment by yeah188** [comment]
我有类似问题，但只会在公司网络使用ss才会出现假死现象。而且时间出现不固定，有时候用一天也没事，有时候一直会假死。
之前解决方法是xshell5连接一下我的代理服务器就恢复了(都不用登陆，只是连接一下)。现在升级到xshell6了，老办法就不能用了。不知道为啥，整个问题和解决方法都，莫名其妙的

**Comment by chenshaoju** [comment]
SS的日志中有显示任何内容吗？

**Comment by yebanqingxing** [comment]
已经弄好啦，多谢

在 2019年2月22日星期五，Chen Shaoju <notifications@github.com> 写道：
