### ISSUE TITLE
A new problem about Auto-downloading of the new version 4.0.9

### ISSUE THREAD

**Issue by WildBlizzard** [shadowsocks/shadowsocks-windows#1776]
I using the version of 4.0.5 and i don't want to download the 4.0.9(cause of Windows defender‘s warned).
But i found a problem recently, that the software of shadowsocks(4.0.5) always download the latest version(4.0.9) to my laptop automatically.
And i really don't like the behavior.
Do you all have the same problem with me?
Please tell me here,thank you.

**Comment by WildBlizzard** [comment]
By the way,the update notice will showing on the screen when you do the reboot every time ...

**Comment by WildBlizzard** [comment]
First of all, I would like to thank you for your long-standing contributions to this forum.

Yes,I always see you replying to another users here,it's not your own thing but you doing that and well done,it's great.

And I have successfully settled the problem on the basis of the above,.

Thank you again!

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/38005394-04dac44a-3273-11e8-9d38-aaad512b7109.png)
