### ISSUE TITLE
shadowsocks.availability.json一直增大

### ISSUE THREAD

**Issue by medsonk** [shadowsocks/shadowsocks-windows#1777]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win7

### Steps you have tried / 操作步骤
ss启动之后，ss_win_temp文件夹下的shadowsocks.availability.json一直增大。最初是增大到30M发现不对劲，然后删了temp文件夹。后来发现这个json文件大概每天都增大2、3M。（btw，我每次升级都是把新exe直接丢过去覆盖旧exe的，应该没啥关系）

**Comment by chenshaoju** [comment]
请右击托盘区的纸飞机图标，选择服务器，并点击统计配置，然后取消选中Enable Statistics，再点击确定即可。

![image](https://user-images.githubusercontent.com/515763/38003489-531d802e-326a-11e8-8b0b-f9bfafa55afd.png)

**Comment by medsonk** [comment]
great，问题已解决！
