### ISSUE TITLE
4.0.9版本，启动ss后avast报IDP.Generic并将ss删掉了

### ISSUE THREAD

**Issue by FreeEager** [shadowsocks/shadowsocks-windows#1778]
shadowsocks 4.0.9 release版本，
avast程序版本18.2.2318   (2018年最新版本)，
病毒库是180327-1   (昨天刚更新)

SHA256和MD5校验通过，

解压Shadowsocks-4.0.9.zip后双击运行shadowsocks.exe，avast弹出对话框，称ss_win_temp\ss_privoxy.exe和shadowsocks.exe含IDP.Generic威胁，然后自动将这两个文件删掉了

这个IDP.Generic报告是否正常？谢谢！

//////
更新：OS版本是windows 7 Ultimate x64

**Comment by celeron533** [comment]
#1746 
#1750

**Comment by FreeEager** [comment]
OS版本是windows 7 Ultimate x64

**Comment by chenshaoju** [comment]
此问题已报告给 AVAST ，等待处理。在等待期间，请确保你所下载的 Shadowsocks.exe (4.0.9)的散列值和发布页一致：
```
MD5: 416D19FA0878A9E9B260580B559EF8DE
SHA1: 88E5D9A81BE58B9241110EDD62D30D2182B4C5DA
SHA256: D618D4FDE2212052636F91E7EFD35AB907317354D76693006177C507CBA772C0
SHA512: 212A90729B8435B4C1919EF9B7B1D9399F69D23CB9F2BD093B4138F0CBCFE1E45D5D0390157EA863E18A97AAA54B9A270106B2CE116A82BB09E0491E88AAD94A
```

如果确定无误，且需急于使用SS，请将 Shadowsocks.exe 加入白名单AVAST等待处理。
![image](https://user-images.githubusercontent.com/515763/38013325-5e30359c-3297-11e8-8ddc-c7ba95352971.png)

**Comment by FreeEager** [comment]
@chenshaoju  散列值和发布页面的经过校验是一致的，暂且将ss目录加入了avast排除目录，待会儿通过vs2017编译源码打个包试试看还会不会报错

**Comment by chenshaoju** [comment]
自己编译的话也是一个方案，理论上应该不会触发检测。

**Comment by chenshaoju** [comment]
AVAST 已经更新了病毒库，可能需要至多24小时才会生效。请在3月30日后更新病毒库后再扫描看看，是否还会有问题。

![image](https://user-images.githubusercontent.com/515763/38043890-d5aa7fbc-32ea-11e8-8aae-b1a35c24a022.png)

**Comment by FreeEager** [comment]
昨天自己编译的也是报同样的威胁和自动删除文件，刚刚更新了病毒库后不再报错了
