### ISSUE TITLE
插件问题

### ISSUE THREAD

**Issue by jwl09** [shadowsocks/shadowsocks-windows#1779]
可否增加一个开关来决定插件是否采用sip003的形式加载,因为有些程序不能读取环境变量设置的端口，造成ss无法连接到插件程序监听的端口？

**Comment by chenshaoju** [comment]
你可以这样试试：在SS客户端里将你的服务器IP设置成 127.0.0.1 ，端口为客户端插件的监听端口号即可，无需在SS客户端里填写插件和插件选项。

然后手动启动你的插件，即可让你的SS客户端通过指定的插件访问。

**Comment by celeron533** [comment]
#1672

**Comment by chenshaoju** [comment]
是的，SS本身只接受符合该规范的插件。

**Comment by jwl09** [comment]
@chenshaoju 好的谢谢
