### ISSUE TITLE
[Feature request] Support for no encryption

### ISSUE THREAD

**Issue by ac130kz** [shadowsocks/shadowsocks-windows#1780]
I found a fork of libev, which actually allows to send unencrypted data (https://github.com/spyff/shadowsocks-libev-nocrypto). I wonder whether it is difficult to add support for it within the Windows application or even merge the option

**Comment by wongsyrone** [comment]
No encryption is only for debugging; you can write your implementation and keep it as a fork. I would not merge when I was the maintainer. You can consult @celeron533 for comments.

**Comment by celeron533** [comment]
Is it not encouraged to implement without encryption as @wongsyrone mentioned.

**Comment by ac130kz** [comment]
@celeron533 I was thinking of creating a lightweight firewall bypass, rather than providing security

**Comment by studentmain** [comment]
Firewall can detect keyword, so some security is necessary.

Mikhail Krassavin <notifications@github.com> 于 2018年3月31日周六 21:20写道：

**Comment by VirtualSmile** [comment]
I'm looking to do the same for the Windows Client. I have no idea however where to work to add in an option for "none" or "no" encryption. Simply for tunneling game data over a LAN network (for testing). Is there somewhere you could upload (instead of merging) that I could use to compile and test? Thanks!

**Comment by ac130kz** [comment]
@VirtualSmile you can try out shadowsocks-rust, it actually has this feature

**Comment by celeron533** [comment]
or just use a socks5 or http proxy

**Comment by studentmain** [comment]
Try rc4-md5. **WARNING: it's unsafe**
