### ISSUE TITLE
shadowsocks-libev 4.0.9 微软杀软曾经报毒过  windows10  现在没有再报毒了0.0

### ISSUE THREAD

**Issue by hikkiii** [shadowsocks/shadowsocks-windows#1783]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
此问题已知，也有具体的解决方法：　https://github.com/shadowsocks/shadowsocks-windows/issues/1746#issuecomment-374836632
