### ISSUE TITLE
WebRTC会导致VPN的IP地址泄露，运营商也会DNS劫持。可以查阅相关资料详细了解

### ISSUE THREAD

**Issue by hikkiii** [shadowsocks/shadowsocks-windows#1784]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by celeron533** [comment]
1. 这不是VPN
2. 由于上一点，本项目的最终目的不是保密和匿名，而是提供一种流量混淆通过某些障碍

**Comment by chenshaoju** [comment]
如果你使用Chrome，可以通过第三方插件来解决WebRCT的问题： https://chrome.google.com/webstore/detail/npeicpdbkakmehahjeeohfdhnlpdklia

安装后，进入选项，选择最后一个“Use my proxy server (if present)”。
