### ISSUE TITLE
非预期错误 - shadowsocks.log 访问拒绝

### ISSUE THREAD

**Issue by baronv5** [shadowsocks/shadowsocks-windows#1785]
![snipaste_2018-03-30_12-23-37](https://user-images.githubusercontent.com/7010266/38124741-ab68bbb0-3416-11e8-8f63-190eb53e0d7f.png)

### 版本
系统版本：Windows Server 2016 Standard
SS版本：4.0.9

### 操作环境
Microsoft .NET Framework 4.6.2 or higher, Microsoft Visual C++ 2015 Redistributable (x86)已安装

### 操作步骤
Shadowsocks.exe文件在D盘，左键双击打开

### 期望的结果
正常打开

### 实际结果
显示图中所示非预期错误

### 配置文件和日志文件
ss_privoxy.log文件是空的

### 注意
右键”以管理员身份运行“可正常打开

**Comment by studentmain** [comment]
管理员权限下是否完全正常？

Baron_Shaw <notifications@github.com> 于 2018年3月30日周五 12:35写道：

**Comment by chenshaoju** [comment]
如果你新建一个目录，比如 D:\SS\ 然后再把 Shadowsocks.exe 放过去，还有该问题吗？

**Comment by baronv5** [comment]
@chenshaoju 我在D盘中是建了Shadowsocks文件夹的。

**Comment by chenshaoju** [comment]
我知道，但是这个提示意味着你对于 D:\Shadowsocks\ 目录没有权限，所以让你新建一个目录再看看。

当然，也有可能是安全软件软件拦截了。

**Comment by baronv5** [comment]
@chenshaoju 重建目录后正常了。
