### ISSUE TITLE
打开压缩shadowsocks就显示已停止工作，解压了也不行

### ISSUE THREAD

**Issue by Nafdraz** [shadowsocks/shadowsocks-windows#1786]
之前用的ssr也没什么问题，压缩文件照用，有没大佬知道什么原因啊

**Comment by chenshaoju** [comment]
１.请确保安装了最新的 .NET Framework ： https://www.microsoft.com/net/download/thank-you/net471
２.请确保安装了32位（x86）的 Microsoft Visual C++ 2015 Redistributable ： https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by Nafdraz** [comment]
下了.NET Framework 可以用了，谢谢
