### ISSUE TITLE
新版一切正常除了没有代理效果的请教。

### ISSUE THREAD

**Issue by tc173club** [shadowsocks/shadowsocks-windows#1787]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
Shadowsocks4.0.9.exe
### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win7  X64  
.NET FRAMEWORK 4.7.1 
C++ 2017 Redistributable（x64）14.10.25008（此处是否必须要有C++ 2015 ？2017理论上不是向下兼容吗） 
### Steps you have tried / 操作步骤
正常运行Shadowsocks.exe或者管理员身份运行Shadowsocks.exe
### What did you expect to see? / 期望的结果
科学上网
### What did you see instead? / 实际结果
很久以前就有这个问题，更新新版以后代理无效，但是并没有什么明显的错误提示，仅仅是PC端无效，同wifi环境手机正常且满速，所以一直使用旧版 3.4.2.0，但是最近升级到最新的4.0.9以后，开启以后已经彻底无效，无论全局还是PAC模式，PAC文件可以正常更新，但是无论4.0.9还是 3.4.2.0均已经无效，LSP重置过，网络缓存清理过，文件更换单独目录尝试过，系统防火墙关闭了，没有安装国产流氓安全软件....请问还有如何的拯救措施？

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2018-03-31 15:05:16] connect to api.github.com:443
[2018-03-31 15:05:16] Socket connected to ss server: xxx (x.x.x.x:xxxx)
[2018-03-31 15:05:37] Shadowsocks started
[2018-03-31 15:05:37] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

**Comment by sumirecccp** [comment]
这个问题估计单纯是软件没设置连接代理 或者是ip，端口填错

**Comment by tc173club** [comment]
@sumirecccp  基本错误排查过了的，不是设置问题

**Comment by sumirecccp** [comment]
日志里面没看到其他软件连接ss的记录，你应该开了记录详细日志的吧

**Comment by tc173club** [comment]
是开了记录详细日志  需要关闭的吗？

**Comment by chenshaoju** [comment]
如果有Firefox，请参考下图独立配置Firefox的代理设置，看看是否还会显示本本地地址。

![image](https://user-images.githubusercontent.com/515763/37390878-680ff942-27a4-11e8-81f1-54edfe7658d9.png)

端口默认为 1080 ，如果在SS的编辑服务器界面修改过也请一并修改。

**Comment by tc173club** [comment]
@chenshaoju  因为这个问题发生很久了，很大可能是和系统环境有关系，能修改的都已经修改过了，想不到的位置只能靠重做系统恢复，但是最近先不做，所以在其他问题里看到用SwitchyOmega+SS实现 PAC规则，先这么用着吧。只是多开一个插件而已，等以后重做了就都解决了，先不折腾了，同时感谢@chenshaoju和@sumirecccp

**Comment by chenshaoju** [comment]
@RhettButlerX 此问题看起来很像是由于加密方式、密码不对引起的。

如果你是自己搭建的服务器，请确保没有使用默认端口（8388），已知该端口被重点关照。 https://github.com/shadowsocks/shadowsocks-windows/issues/1711

**Comment by RhettButlerX** [comment]
@chenshaoju  这是最近出现的问题。。服务器的确是自搭的，但是端口不是默认的。。加密和密码也检查了几遍都是正确的，而且我的iphone上用这个ip可以正常的代理。所以我想应该是pc上的ss客户端没有正常工作。也参考了之前的一些问题 #1241 但是都没有解决。。我的系统是win10，但是最近没有什么更新。.net framework也已升级到最新的了。

**Comment by chenshaoju** [comment]
@RhettButlerX 这么说有点奇怪，但是能否做个测试，搭一个 simpe-obfs 看看，是否还会有此问题？

**Comment by chenshaoju** [comment]
@RhettButlerX 有一定的可能性是你电脑的流量行为模式被盯上了，所以出现手机和电脑的差异化。

**Comment by RhettButlerX** [comment]
@chenshaoju 可能是这样。我已经注意极力避免安装一些软件了，但是像某讯的社交软件实在无法避免，不知道把他们扔沙盒里有没有用。。。

**Comment by chenshaoju** [comment]
@RhettButlerX   你可以试试QQ国际版，不过和你本机的软件可能无关，应该是你的网络流量模型。

不过这些都是猜测，目前没有准确答案。

**Comment by RhettButlerX** [comment]
@chenshaoju  好的。我以后会注意，谢谢你的指导。
