### ISSUE TITLE
您们的服务器地址是自己建的还是购买的，能介绍个吗？

### ISSUE THREAD

**Issue by JK456** [shadowsocks/shadowsocks-windows#1788]
您们的服务器地址是自己建的还是购买的，能介绍个吗？

**Comment by chenshaoju** [comment]
请不要在此询问服务商信息，Shadowsocks for Windows不销售也不推荐服务商。

没有人能对第三方的服务商提供担保。

**Comment by 828768** [comment]
[在用的一个](https://vip.wubase.com)，还挺爽
