### ISSUE TITLE
shadowsocks连接问题

### ISSUE THREAD

**Issue by jiejie336** [shadowsocks/shadowsocks-windows#1789]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
shadowsocks 4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows10

### Steps you have tried / 操作步骤

正常运行
### What did you expect to see? / 期望的结果
解决说所提到的问题问题

### What did you see instead? / 实际结果
我在4.0.6的时候升级到了4.0.9，我没有启动系统代理，它自动会帮我连接的，然后我退出软件在打开网页就会
“未连接到互联网
代理服务器出现问题，或者地址有误。”
上不了网。主要是，我连shadowsocks的时候，看一些网页的视频会很卡的，用打开outlook邮箱其中一个账号也会老是提示要输入密码。
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）[2018-04-01 11:40:27] connect to mtalk.google.com:5228
[2018-04-01 11:40:27] Socket connected to ss server: xxx (x.x.x.x:xxxx)
[2018-04-01 11:40:30] Shadowsocks started
[2018-04-01 11:40:30] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor

**Comment by chenshaoju** [comment]
１.退出SS。
２.删除 Shadowsocks.exe 目录下的 user-wininet.json 文件。
３.启动SS，此时 user-wininet.json 会再次生成，请再次删除。
４.再次退出SS。
５.打开Internet Explorer选项，进入连接选项卡，点击局域网设置按钮。
６.确保局域网（LAN）设置显示类似下图，没有选中的选项。
![image](https://user-images.githubusercontent.com/515763/38169648-600f2356-35a2-11e8-9d61-f1e9caf0ac63.png)

此时不使用SS应该也可以访问没有被墙的网站了。

**Comment by jiejie336** [comment]
好了，谢谢你！！！
