### ISSUE TITLE
windows10 64bit 1709  打开系统代理 IE可以正常使用代理，但chrome和Firefox都无法使用

### ISSUE THREAD

**Issue by Cost11** [shadowsocks/shadowsocks-windows#1791]
![default](https://user-images.githubusercontent.com/37539782/38185568-594b61bc-3681-11e8-8178-292ae56ed44a.PNG)
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
release version 4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
windows10 专业版 1709 OS内部版本16299.309

### Steps you have tried / 操作步骤
打开系统代理，（PAC模式）IE 可以正常访问google.com
chrome 和Firefox无法访问google.com 
相同的shaodowsocks配置文件，到windows8.1上就都能使用
当firefox使用SwitchyOmega插件时，google.com就能访问

### What did you expect to see? / 期望的结果
我想问到底怎么解决让chrome能使用系统代理，不需要使用插件

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
你好，如果你的Chrome和Firefox有使用代理插件，那么很可能PAC会不生效。这种情况请在你的代理插件里指定PAC。

![image](https://user-images.githubusercontent.com/515763/38185219-b70bccda-367f-11e8-991c-033a37491eac.png)

**Comment by chenshaoju** [comment]
新版没有做任何关于PAC方面的修改。

如果IE在使用SS的时候可以访问被墙和未被墙的的网站，IE在不使用SS的时候可以访问未被墙的网站的话，很高的可能性是你的Chrome/Firefox浏览器插件配置有误。

如果可能，请卸载或停用你的Chrome/Firefox代理插件，并会从新启动Chrome/Firefox，Chrome应该就可以直接使用了。

Firefox在卸载／停用代理插件后可能还需要修改一个地方：
![image](https://user-images.githubusercontent.com/515763/38186159-1e3a53aa-3684-11e8-94b3-84ff9bae9370.png)

**Comment by Cost11** [comment]
可我现在是新装的系统新装的chrome，就是chrome不能访问外网，chrome没装任何代理插件，无论是PAC还是全局，chrome都不能访问外网，内网可以访问。

**Comment by Cost11** [comment]
现在的状态就是，chrome和firefox都不能使用系统代理

**Comment by chenshaoju** [comment]
我在我的 Windows 10 1709 16299.334 上使用 Firefox 59.0.2 (x64) 测试了一下，无法复现该问题。
![2018-04-02 1](https://user-images.githubusercontent.com/515763/38188739-d2a611e8-368f-11e8-8208-6014ccc48c3d.png)

该问题可能是由于你的系统中有某种因素拦截了第三方浏览器获取当前的代理设置情况。

Chrome提供了一个诊断方法，请在Chrome的地址栏里输入： ```chrome://net-internals/#proxy``` ，会提示当前的PAC脚本路径和来源，正常情况应该如下图（我自定义了10800端口，请忽略），请看一下你的Chrome是如何显示的：
![2018-04-02 2](https://user-images.githubusercontent.com/515763/38188970-ade7f01e-3690-11e8-8c7f-b8e6e6e30e04.png)

**Comment by Cost11** [comment]
不知道你能不能试一下，设置网络连接为拨号连接，且连接名字设置为宽带连接，重启，用那个宽带连接连接网络，我估计你可以复现我的问题。我改了宽带连接名字 结果问题就消失了，我不确定是不是这个原因，但我现在没有那个问题。我想麻烦你尝试复现我的那个问题，看看第三方浏览器无法使用系统代理的原因到底是不是因为拨号连接的那个名字是中文的原因。

**Comment by chenshaoju** [comment]
已知部分计算机上，中文的宽带连接名称可能会有问题：https://github.com/shadowsocks/shadowsocks-windows/issues/1502#issuecomment-345680039

另外，如果在未拨号的情况下启动SS，然后再拨号，也可能会有问题：https://github.com/shadowsocks/shadowsocks-windows/issues/1502#issuecomment-377843864

**Comment by Cost11** [comment]
我这没有条件直接测试本地网络，我不知道你有没有试过，本地有线网络直接连接笔记本上网，会不会出现我上面的情况

**Comment by chenshaoju** [comment]
我的笔记本就是直接插网线的，你可以看到上图的截图左下角有一个电池图标和有线网络连接的图标。

**Comment by Lyooo** [comment]
@chenshaoju 感谢，我也遇到同样问题，把连接名称从中文改成英文就解决了

**Comment by KingDeng** [comment]
我想说的是困扰了我两周的问题终于在这里找到了答案。我说我的手机可以上，偏偏电脑就是不能呢，平常都是用chrome的，今天偶然发现IE能上，就来这里找答案，原来是插件惹的祸。

**Comment by Cost11** [comment]
@KingDeng 插件？你用的代理插件吗？

**Comment by KingDeng** [comment]
@Cost11 我是工作需要装了一个切换hosts的插件

**Comment by logicr** [comment]
楼主你好，我的问题和你一模一样，只能用ie上网，手机也没问题，就是其他浏览器不行，也没用插件，如果解决了，麻烦告知。

**Comment by freshgeek** [comment]
我也是这个情况, 使用ie 可以 ,使用其他浏览器就和没代理一摸一样.(今天忽然不行的,之前可以代理,自建服务器 手机使用没问题)
刚才使用chrome://net-internals/#proxy
显示
Effective proxy settings
Use DIRECT connections.
Source: SYSTEM
直接使用了连接 .
是否有解决?
系统版本1709

**Comment by chenshaoju** [comment]
@freshgeek 请打开Internet Explorer 选项，点击连接选项卡，并点击局域网配置，确认有启用“使用自动配置脚本”吗？

![image](https://user-images.githubusercontent.com/515763/38667338-c8cc3ae4-3e73-11e8-8580-9b4343c8ec5d.png)

**Comment by freshgeek** [comment]
@chenshaoju  
刚才试过了,发现还是ie可用,谷歌不可用.
我没开ss时配置如下
![1](https://user-images.githubusercontent.com/20513615/38668467-9720fe6e-3e76-11e8-9564-f519a0f66792.png)
打开后,ie正常使用,谷歌不可用时配置如下
![2](https://user-images.githubusercontent.com/20513615/38668483-9cd2970a-3e76-11e8-9733-ff1e0c920b6c.png)
日志文件如下
![3](https://user-images.githubusercontent.com/20513615/38668573-c4e41eda-3e76-11e8-9a98-687b11105a39.png)

**Comment by logicr** [comment]
@freshgeek 已解决，这是Win10的锅，好像是因为使用拨号链接之后，shadowsocks无法进行系统代理。具体解决方法为：在chrome中添加代理插件stiwchyomega，然后跟着操作提示，我是设置的全局，协议选择了socks5 代理服务器：127.0.0.1，端口：1080，开启之后就可以连接了。

**Comment by Cost11** [comment]
使用拨号链接的人，拨号连接的名字不能是中文，换成“ADSL”什么的英文，重启之后就能用。

**Comment by WangRongXuan** [comment]
@Cost11 之前shadowsocks死活用不了，各种排查未果，一直没想到问题出在这里，还是偶然发现的，原来windows10中文下默认的拨号名称就叫“宽带连接” 🤣

**Comment by muzinian** [comment]
我这边现在是chrome 正常模式时使用ss无法访问外网，使用隐身模式可以通过ss访问外网。其它浏览器都可以访问(windows 10 1803 wiif是英文名称)，通过`chrome://net-internals/#proxy`查看，正常模式下显示如下：
![default](https://user-images.githubusercontent.com/2555512/44378838-b434a980-a535-11e8-8735-f35c5bf94ac1.png)
隐身模式下显示如下：
![default](https://user-images.githubusercontent.com/2555512/44378936-2a391080-a536-11e8-8636-4281f8050fd8.png)

**Comment by chenshaoju** [comment]
@muzinian 这意味着你的浏览器被什么插件接管了代理（隐身模式会自动禁用所有插件）。

**Comment by muzinian** [comment]
@chenshaoju 浏览器的插件都仅用了，代理显示如下：
![default](https://user-images.githubusercontent.com/2555512/44384978-a3456180-a550-11e8-82eb-0ebddb2eebce.png)
插件已经完全禁用
![default](https://user-images.githubusercontent.com/2555512/44385014-c2dc8a00-a550-11e8-9207-7c7fa0d99f49.png)

**Comment by chenshaoju** [comment]
或者是你的Chrome启动快捷方式有猫腻？

**Comment by muzinian** [comment]
@chenshaoju 我清除chrome的数据，卸载重装就好了，没有检查快捷方式，估计可能是的

**Comment by 1phalley** [comment]
@chenshaoju 我win10最新版偶尔也会出现手机正常,chrome经常断开的情况
表现为1号线路使用一两分钟就断开不能翻墙(但日志里并没有显示断开连接)
切换2号线路一两分钟又断开
需要频繁切换直到所有线路试完,然后重启ss重来一次
我的截图是这样
![snipaste_2018-09-02_20-47-00](https://user-images.githubusercontent.com/35102295/44956149-e3fa8e80-aef1-11e8-9672-8a521912c3bc.png)

**Comment by chenshaoju** [comment]
我看了一下，你的SS的代理端口是1081吗？

感觉有什么东西设置了全局代理，或者你的SS是工作在全局代理模式吗？

**Comment by maoturing** [comment]
@chenshaoju 感谢，我也遇到同样问题，把连接名称从中文改成英文就解决了

**Comment by lfydegithub** [comment]
我今天也遇到了同样的问题。
首先我打开了ss的windows客户端，我确定账户是可用 的，
然后，我的UC浏览器是可以上谷歌的，谷歌浏览器竟然不行，
谷歌浏览器必须开启Proxy SwitchyOmega插件才能用，可我之前是不用开就能用的，我要 搞定他
然后我就设置了PAC
![image](https://user-images.githubusercontent.com/29767851/54583102-0e570800-4a4e-11e9-813a-5caac1387caa.png)，更新了一下规则，就好了

**Comment by AnyWAT** [comment]
> ps.真是佩服UC，竟然直接就翻墙了，什么插件都不用

貌似正常的Chrome 也是可以不用插件而使用系统代理的

**Comment by jiahuifu** [comment]
可以这么玩
google-chrome --proxy-server="socks5://127.0.0.1:1080"

**Comment by libo-0379** [comment]
pppoe宽带连接名字改为英文,电脑重启解决了.谢谢

**Comment by myliwenbo** [comment]
> @chenshaoju 浏览器的插件都仅用了，代理显示如下：
> ![default](https://user-images.githubusercontent.com/2555512/44384978-a3456180-a550-11e8-82eb-0ebddb2eebce.png)
> 插件已经完全禁用
> ![default](https://user-images.githubusercontent.com/2555512/44385014-c2dc8a00-a550-11e8-9207-7c7fa0d99f49.png)

问一下你解决了么：

1. 我的ie可以翻墙，chrome不可以翻墙
2. chrome开无痕模式可以翻墙
3. chrome去掉所有插件的情况下还是不可以翻墙....
![](//img.xjdai.vip/201907261117_998.png)
![](//img.xjdai.vip/201907261117_493.png)
![](//img.xjdai.vip/201907261117_552.png)
![](//img.xjdai.vip/201907261117_335.png)

**Comment by myliwenbo** [comment]
![20190726111151](https://user-images.githubusercontent.com/29202248/61923566-21975880-af97-11e9-8299-43b85d328917.jpg)
![20190726111254](https://user-images.githubusercontent.com/29202248/61923567-222fef00-af97-11e9-835f-7c88a4ec554e.jpg)
![20190726111603](https://user-images.githubusercontent.com/29202248/61923568-222fef00-af97-11e9-8846-86767d3cf266.jpg)
![20190726111628](https://user-images.githubusercontent.com/29202248/61923569-22c88580-af97-11e9-94a8-7f87048ebc54.jpg)

**Comment by chenshaoju** [comment]
请尝试删除 Shadowscks.exe 所在目录下的 pac.txt ，然后启动SS，在任务栏托盘区的纸飞机图标上右击，选择PAC，再点击从本地更新PAC看看？

**Comment by jiahuifu** [comment]
linux系统
命令行启动
google-chrome --proxy-server="socks5://127.0.0.1:1080"

**Comment by shanmu1964** [comment]
尝试了多种方法，检查没有配置插件，代理正常，就是不能使用，IE浏览器则正常，卸载重装也不生效。
卸载时，清理用户数据，再重装，则可以使用。不清楚是什么原因。

**Comment by 306859314** [comment]
我也遇到相同问题，宽带连接改成英文，重启后解决，一定要重启

**Comment by TWOLMAN** [comment]
最简单的办法，下载一个谷歌代理管理插件，所有问题全搞定,插件名字：switchysharp，然后设置成系统代理，问题圆满结束###

**Comment by TWOLMAN** [comment]
> @chenshaoju 浏览器的插件都仅用了，代理显示如下：
> 
> 插件已经完全禁用
> 
> 
> The@chenshaoju browser plug ins are all used, and the proxy shows the following: The plug INS are completely disabled
> 
> 问一下你解决了么：
> 
> Ask If you've solved it:
> 
> 我的ie可以翻墙，chrome不可以翻墙 My Ie can go over the wall, chrome can't
> chrome开无痕模式可以翻墙 Chrome works in traceless mode to get around walls
> chrome去掉所有插件的情况下还是不可以翻墙.... Chrome still can't get over the wall without all the plugins..
下载谷歌代理管理插件，简单有效 switchysharp插件名字

**Comment by heiyu121** [comment]
@Cost11 我是用这个方式解决的https://www.vpnto.net/posts/chrome-shadowsocks/

**Comment by heiyu121** [comment]
@Cost11 我是用这个方法解决的https://www.vpnto.net/posts/chrome-shadowsocks/希望对你有帮助

**Comment by osgg** [comment]
> @Cost11 我是用这个方法解决的[https://www.vpnto.net/posts/chrome-shadowsocks/希望对你有帮助](https://www.vpnto.net/posts/chrome-shadowsocks/%E5%B8%8C%E6%9C%9B%E5%AF%B9%E4%BD%A0%E6%9C%89%E5%B8%AE%E5%8A%A9)

连接打不开了

**Comment by AnyWAT** [comment]
> 连接打不开了

https://www.vpnto.net/posts/chrome-shadowsocks/ [希望对你有帮助]( )
链接与非链接之间需添加空格

**Comment by DaGaiBa** [comment]
@chenshaoju 感谢，宽带连接名字改成英文就完美解决了

**Comment by songhui123** [comment]
我使用的是搜狗浏览器，以前好好地能用，现在是突然不能用了，咋回事呢，求解
代理工具项：使用IE的代理工具设置，配置用的是trojan-Qt5
（截图了不能上传发出，只能用文字描述了）

**Comment by qw235534** [comment]
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
麻烦问一下这个怎么解决？

**Comment by libo-0379** [comment]
好像缺少文件

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: qw235534 ***@***.***>
发送时间: Monday, April 11, 2022 12:45:13 PM
收件人: shadowsocks/shadowsocks-windows ***@***.***>
抄送: libo-0379 ***@***.***>; Comment ***@***.***>
主题: Re: [shadowsocks/shadowsocks-windows] windows10 64bit 1709 打开系统代理 IE可以正常使用代理，但chrome和Firefox都无法使用 (#1791)


Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
麻烦问一下这个怎么解决？

―
