### ISSUE TITLE
服务器 → 高可用     具体是怎样的规则？

### ISSUE THREAD

**Issue by justforadblock** [shadowsocks/shadowsocks-windows#1792]
能否言简意赅的描述一下，谢谢。

我想实现类似于手机端surge那样的Url-test功能

**Comment by chenshaoju** [comment]
```High availability: choosing the best server (low latency and packet loss)``` 

具体的算法实现请参阅：https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Strategy/HighAvailabilityStrategy.cs
