### ISSUE TITLE
4.0.9日志有Registered Encryptor Info的信息

### ISSUE THREAD

**Issue by mcmxciv** [shadowsocks/shadowsocks-windows#1793]
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本

Shadowsocks 4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）

windows 10 1709

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件

**升级到4.0.9后，每次启动shadowsocks，日志中都会生成Registered Encryptor Info的信息

[2018-04-03 08:32:03] Shadowsocks started
[2018-04-03 08:32:03] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

请问如何把Registered Encryptor Info以下的信息屏蔽掉？

**Comment by studentmain** [comment]
改代码自己编译，或者眼不见心不烦

mcmxciv <notifications@github.com> 于 2018年4月3日周二 11:03写道：

**Comment by celeron533** [comment]
这是4.0.9新添加的，用于检查加密解密初始化是否正常
不想看的话可以自己改代码
