### ISSUE TITLE
可否加一个固定的国外IP绕行规则？

### ISSUE THREAD

**Issue by MasterLivens** [shadowsocks/shadowsocks-windows#1794]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Steps you have tried / 操作步骤
在菜单里选中，”绕过局域网和国内IP"

### What did you expect to see? / 期望的结果
在访问网页的时候，所有的国外IP都自动翻墙，无需经过GFW列表来查询

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
有第三方的解决方案，可以通过PAC白名单实现，具体请参阅： https://github.com/breakwa11/gfw_whitelist

**Comment by celeron533** [comment]
> PAC rule的加载是否支持热加载
应该是支持的，有fileWatcher在监视文件修改

**Comment by codexss** [comment]
希望能像这个项目一样有个SMART ROUTER
https://github.com/XX-net/XX-Net

**Comment by DearTanker** [comment]
这个真的很有需要。手动编辑用户规则真是受够了。。已经加了几百个IP了。。

有时候并不是因为网站被墙，而是打开慢。

**Comment by zjplab** [comment]
可以尝试双重shadowsocks
