### ISSUE TITLE
pc版无法连接网络，手机版可以。

### ISSUE THREAD

**Issue by 1711700938** [shadowsocks/shadowsocks-windows#1795]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请提供具体一些的信息，比如PC版SS的日志，浏览器有无返回错误信息。

另外，PC和手机在同一路由器下吗？如果是，请仔细检查PC端的配置是否正确，IP、端口、密码、加密算法是否一致。

**Comment by chenshaoju** [comment]
请在PC上使用 TCPing 进行测试： https://www.elifulkerson.com/projects/tcping.php ，这是命令提示符下使用的软件，格式为：
```
tcping 123.45.67.89 9876
```
请将 123.45.67.89 替换为你的服务器的IP或域名，将 9876 替换成你SS服务器的端口，看看通吗？

**Comment by 1711700938** [comment]
日志显示：由于目标计算机积极拒绝，无法连接

发送自 Windows 10 版邮件应用

发件人: Chen Shaoju
发送时间: 2018年4月3日 16:48
收件人: shadowsocks/shadowsocks-windows
抄送: 1711700938; Author
主题: Re: [shadowsocks/shadowsocks-windows] pc版无法连接网络，手机版可以。 (#1795)

请提供具体一些的信息，比如PC版SS的日志，浏览器有无返回错误信息。
另外，PC和手机在同一路由器下吗？如果是，请仔细检查PC端的配置是否正确，IP、端口、密码、加密算法是否一致。

**Comment by chenshaoju** [comment]
@1711700938 如果确定客户端的IP、端口无误的话，这意味着你的服务器可能被屏蔽了，或者服务器端口没有打开。

**Comment by 1711700938** [comment]
有时候又可以连上，不稳定

发送自 Windows 10 版邮件应用

发件人: Chen Shaoju
发送时间: 2018年4月4日 14:57
收件人: shadowsocks/shadowsocks-windows
抄送: 1711700938; Mention
主题: Re: [shadowsocks/shadowsocks-windows] pc版无法连接网络，手机版可以。 (#1795)

@1711700938 如果确定客户端的IP、端口无误的话，这意味着你的服务器可能被屏蔽了，或者服务器端口没有打开。

**Comment by chenshaoju** [comment]
@1711700938 如果是你自己搭建的服务，请尝试加一个Simple-obfs看看。有类似的报告，但是不确定：https://github.com/shadowsocks/shadowsocks-windows/issues/1787#issuecomment-377857225

**Comment by baiuwlyd** [comment]
我也遇到了同样的问题，请问解决了吗？同样的服务器配置在android手机上可以正常使用，win10系统就不行，日志里面没有报任何错误，只是提示了很多Registered Encryptor Info，请问有什么解决办法吗？

**Comment by 1711700938** [comment]
还没有解决，有时候可以连接，有时候连不上。 在2018年04月05日 01:37 ，baiuwlyd写道： 我也遇到了同样的问题，请问解决了吗？同样的服务器配置在android手机上可以正常使用，win10系统就不行，日志里面没有报任何错误，只是提示了很多Registered Encryptor Info，请问有什么解决办法吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by freehehe** [comment]
https://i.loli.net/2018/04/14/5ad0d48aaa4a4.png 
https://i.loli.net/2018/04/14/5ad0d501e090e.jpg 
把宽带连接几个汉字改为英文就好，然后重新拨号

**Comment by o2o2oz** [comment]
shadowsocks-windows 4.0.9 / windows 10
Microsoft .NET Framework 4.6.2  已经安装

同样的问题，确认输入信息无误
浏览器：ERR_CONNECTION_TIMED_OUT
TCPing 测试服务器, 50ms



日志：

Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-04-20 09:57:24] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.EntryPointNotFoundException: 无法在 DLL“libsscrypto.dll”中找到名为“md5_ret”的入口点。
   在 Shadowsocks.Encryption.MbedTLS.md5_ret(Byte[] input, UInt32 ilen, Byte[] output)
   在 Shadowsocks.Encryption.MbedTLS.MD5(Byte[] input)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor.LegacyDeriveKey(Byte[] password, Byte[] key, Int32 keylen)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor.InitKey(String password)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor..ctor(String method, String password)
   在 Shadowsocks.Encryption.Stream.StreamOpenSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2018-04-20 09:57:24] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.EntryPointNotFoundException: 无法在 DLL“libsscrypto.dll”中找到名为“md5_

**Comment by chenshaoju** [comment]
```
System.EntryPointNotFoundException: 无法在 DLL“libsscrypto.dll”中找到名为“md5_ret”的入口点。
```

请尝试按照：https://github.com/shadowsocks/shadowsocks-windows/issues/1774#issuecomment-377866138 操作，看看能否解决。
