### ISSUE TITLE
报错，，非预期性错误

### ISSUE THREAD

**Issue by Lijianxiong8** [shadowsocks/shadowsocks-windows#1796]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by Lijianxiong8** [comment]
![qq 20180403234758](https://user-images.githubusercontent.com/35649576/38260723-f35dc67c-379a-11e8-8bf7-59229f0dc7b0.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1376
