### ISSUE TITLE
4.0.9用全局代理上不了Google

### ISSUE THREAD

**Issue by EallanW** [shadowsocks/shadowsocks-windows#1798]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows 10
這部電腦已安裝 .NET Framework 4.6.2 (含) 以上版本的更新。

### Steps you have tried / 操作步骤
安裝4.0.9
配置服務器信息
啟用系統代理
設置全局模式
使用線上pac
訪問Google.com

### What did you expect to see? / 期望的结果
能夠打開Google

### What did you see instead? / 实际结果
打不開，錯誤信息如下

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
配置文件：

{
  "configs": [
    {
      "server": "",
      "server_port": ,
      "password": "",
      "method": "rc4-md5",
      "plugin": "",
      "plugin_opts": "",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": true,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1081,
  "pacUrl": "https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt",
  "useOnlinePac": true,
  "secureLocalPac": false,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": ""
  }
}

日誌信息：
[2018-04-05 14:22:15] Shadowsocks started
[2018-04-05 14:22:16] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-04-05 14:22:21] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:22:25] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:22:26] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:22:26] System.Reflection.TargetInvocationException: 作業期間發生例外狀況，使得結果無效。如需例外狀況詳細資訊，請檢查 InnerException。 ---> System.Net.WebException: 基礎連接已關閉: 傳送時發生未預期的錯誤。 ---> System.IO.IOException: 驗證失敗，因為遠端群體已經關閉傳輸資料流。
   於 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   於 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   於 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   於 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   於 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   於 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-04-05 14:22:40] Shadowsocks started
[2018-04-05 14:22:40] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-04-05 14:22:47] connect to www.evernote.com:443
[2018-04-05 14:22:52] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:22:52] connect to www.evernote.com:443
[2018-04-05 14:22:57] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:22:57] connect to www.evernote.com:443
[2018-04-05 14:22:57] connect to collect.tealiumiq.com:443
[2018-04-05 14:23:00] connect to client.dropbox.com:443
[2018-04-05 14:23:02] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:02] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:02] connect to collect.tealiumiq.com:443
[2018-04-05 14:23:05] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:05] connect to client.dropbox.com:443
[2018-04-05 14:23:07] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:07] connect to collect.tealiumiq.com:443
[2018-04-05 14:23:07] connect to ssl.google-analytics.com:443
[2018-04-05 14:23:10] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:12] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:12] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:12] connect to ssl.google-analytics.com:443
[2018-04-05 14:23:17] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:17] connect to ssl.google-analytics.com:443
[2018-04-05 14:23:17] connect to collect.tealiumiq.com:443
[2018-04-05 14:23:22] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:22] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:22] connect to collect.tealiumiq.com:443
[2018-04-05 14:23:27] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:27] connect to collect.tealiumiq.com:443
[2018-04-05 14:23:27] connect to ssl.google-analytics.com:443
[2018-04-05 14:23:32] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:32] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:32] connect to ssl.google-analytics.com:443
[2018-04-05 14:23:37] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:37] connect to ssl.google-analytics.com:443
[2018-04-05 14:23:37] connect to collect.tealiumiq.com:443
[2018-04-05 14:23:42] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:42] Vultr (45.32.231.172:25) timed out
[2018-04-05 14:23:42] connect to collect.tealiumiq.com:443

錯誤信息：

Your connection is not private
Attackers might be trying to steal your information from www.google.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: baidu.com

Issuer: GlobalSign Organization Validation CA - SHA256 - G2

Expires on: Apr 25, 2018

Current date: Apr 5, 2018

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIJfTCCCGWgAwIBAgIMHD8o4CgjMvJLvhHdMA0GCSqGSIb3DQEBCwUAMGYxCzAJ
BgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMTwwOgYDVQQDEzNH
bG9iYWxTaWduIE9yZ2FuaXphdGlvbiBWYWxpZGF0aW9uIENBIC0gU0hBMjU2IC0g
RzIwHhcNMTcwNjI5MDUzMjA3WhcNMTgwNDI1MDUzMTAyWjCBpzELMAkGA1UEBhMC
Q04xEDAOBgNVBAgTB2JlaWppbmcxEDAOBgNVBAcTB2JlaWppbmcxJTAjBgNVBAsT
HHNlcnZpY2Ugb3BlcmF0aW9uIGRlcGFydG1lbnQxOTA3BgNVBAoTMEJlaWppbmcg
QmFpZHUgTmV0Y29tIFNjaWVuY2UgVGVjaG5vbG9neSBDby4sIEx0ZDESMBAGA1UE
AxMJYmFpZHUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJkP
C0Lev6L0shNY3OTO5JwO8gxzm2VAPDoBvHIppd2jyg27lUNCS3LhZEQW++J1cXvR
AMIDezTK0i9HUk5dqWKJzH5JY+8pn6/iylIoKDvEqNVylLJ7auilO/6l0SOE6Xfc
6FqE11EjIDNwb4zfbcqMLPRkpr9n6DFEbJztNGs+GCE5zNm1bpJbouo+E35EbgP7
sqXCz0a2TOl58Ubx6857DAmeTcKqTkHg0LkAhmhapCjxZW4vEW/izxQCAlJpqhaZ
YremnO4L0HiwTdwXicdT7uCZoKEkzylNDrUbULbl2mOvqKqRhj/YKrxOXlmMtmDw
NgHqI5ojbEj683/GwwIDAQABo4IF5zCCBeMwDgYDVR0PAQH/BAQDAgWgMIGgBggr
BgEFBQcBAQSBkzCBkDBNBggrBgEFBQcwAoZBaHR0cDovL3NlY3VyZS5nbG9iYWxz
aWduLmNvbS9jYWNlcnQvZ3Nvcmdhbml6YXRpb252YWxzaGEyZzJyMS5jcnQwPwYI
KwYBBQUHMAGGM2h0dHA6Ly9vY3NwMi5nbG9iYWxzaWduLmNvbS9nc29yZ2FuaXph
dGlvbnZhbHNoYTJnMjBWBgNVHSAETzBNMEEGCSsGAQQBoDIBFDA0MDIGCCsGAQUF
BwIBFiZodHRwczovL3d3dy5nbG9iYWxzaWduLmNvbS9yZXBvc2l0b3J5LzAIBgZn
gQwBAgIwCQYDVR0TBAIwADCCAm8GA1UdEQSCAmYwggJiggliYWlkdS5jb22CDGJh
aWZ1YmFvLmNvbYIMd3d3LmJhaWR1LmNughB3d3cuYmFpZHUuY29tLmNughJjbGlj
ay5obS5iYWlkdS5jb22CEGxvZy5obS5iYWlkdS5jb22CEGNtLnBvcy5iYWlkdS5j
b22CEHduLnBvcy5iYWlkdS5jb22CFHVwZGF0ZS5wYW4uYmFpZHUuY29tgg9tY3Qu
eS5udW9taS5jb22CCyouYmFpZHUuY29tgg4qLmJhaWZ1YmFvLmNvbYIRKi5iYWlk
dXN0YXRpYy5jb22CDiouYmRzdGF0aWMuY29tggsqLmJkaW1nLmNvbYIMKi5oYW8x
MjMuY29tggsqLm51b21pLmNvbYINKi5jaHVhbmtlLmNvbYINKi50cnVzdGdvLmNv
bYIPKi5iY2UuYmFpZHUuY29tghAqLmV5dW4uYmFpZHUuY29tgg8qLm1hcC5iYWlk
dS5jb22CDyoubWJkLmJhaWR1LmNvbYIRKi5mYW55aS5iYWlkdS5jb22CDiouYmFp
ZHViY2UuY29tggwqLm1pcGNkbi5jb22CECoubmV3cy5iYWlkdS5jb22CDiouYmFp
ZHVwY3MuY29tggwqLmFpcGFnZS5jb22CCyouYWlwYWdlLmNugg0qLmJjZWhvc3Qu
Y29tggpiYWlmYWUuY29tghAqLnNhZmUuYmFpZHUuY29tgg4qLmltLmJhaWR1LmNv
bYIRKi5zc2wyLmR1YXBwcy5jb22CDCouYmFpZmFlLmNvbYISKi5iYWlkdWNvbnRl
bnQuY29tggsqLmRsbmVsLmNvbTAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
AwIwHQYDVR0OBBYEFDnZhdMK9Lb1LZYZt+PopFDjb49cMB8GA1UdIwQYMBaAFJbe
YfG9HBYpUxzAzH07gwBA5hp8MIIB9wYKKwYBBAHWeQIEAgSCAecEggHjAeEAdgDd
6x0reg1PpiCLga2BaHB+Lo6dAdVciI09EcTNtuy+zAAAAVzyVdHYAAAEAwBHMEUC
IBNOrz/Mgd93jU1z2wLvePgxZDGdY3jjMYjPbTw6hyyOAiEA5zeHfn0BTaILn/CN
VKsaYvChLC0jPnUvHiDKeinmlbMAdwCkuQmQtBhYFIe7E6LMZ3AKPDWYBPkb37jj
d80OyA3cEAAAAVzyVdHKAAAEAwBIMEYCIQDp/p2I7HmVYISY/Ppk1rip1gnx6QeG
O+GqbuQ2LtDc9AIhAKIYn58spyi6GLOfyAX67MKjjdTjE7YW5TkzHTfxyMheAHUA
u9nfvB+KcbWTlCOXqpJ7RzhXlQqrUugakJZkNo4e0YUAAAFc8lXSNQAABAMARjBE
AiAMCXVUzvAInks06rR+pKCGDx+JqjfkraOGwYEaB78teAIgQQWXCdMkAjKIbyEv
pnuv+NCXm0IprMnt4AgTVNFYWAgAdwDuS723dc5guuFCaR+r4Z5mow9+X7By2IMA
xHuJeqj9ywAAAVzyVdPpAAAEAwBIMEYCIQDnmblfe4Q2wgP3M8eyA06nIjYoFuKK
OXEydfkm6J23LwIhAKPGQnqNrwyAA7MPyenIIz2ACi3b/bvQifSRGOoE4xhoMA0G
CSqGSIb3DQEBCwUAA4IBAQBiFbq1dBFAKfhJ1Ary45OgTEPeidaY83tpTv4M8LrS
OZsbQdaa9hs0QzLhUDF4ji7+y7SMvRkXkYCJDarz+pE4215qFOgn/0X9FD/o/0o5
ubmvWrwbN0puf2eG6hcnMEADxL54Pko+2y4FL3NXwARAb3UEkNCY5MlOumfzQjSr
mcuQrZrGDwOm0Db4ktCf6DLqFDjdIK/p8/pKGREdhgs5Cppu8TW90NlUtl3KRf1X
cL7Cc0AQyJBUvTdBNe8YausScDSLuDFUTQKSPXSkGr498XrxDCi873owzPvdAPEX
ISSihrc2dS1we346T0bFV+I0NianRcYhxXxFxFO1vmRb
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEaTCCA1GgAwIBAgILBAAAAAABRE7wQkcwDQYJKoZIhvcNAQELBQAwVzELMAkG
A1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jv
b3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw0xNDAyMjAxMDAw
MDBaFw0yNDAyMjAxMDAwMDBaMGYxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9i
YWxTaWduIG52LXNhMTwwOgYDVQQDEzNHbG9iYWxTaWduIE9yZ2FuaXphdGlvbiBW
YWxpZGF0aW9uIENBIC0gU0hBMjU2IC0gRzIwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQDHDmw/I5N/zHClnSDDDlM/fsBOwphJykfVI+8DNIV0yKMCLkZc
C33JiJ1Pi/D4nGyMVTXbv/Kz6vvjVudKRtkTIso21ZvBqOOWQ5PyDLzm+ebomchj
SHh/VzZpGhkdWtHUfcKc1H/hgBKueuqI6lfYygoKOhJJomIZeg0k9zfrtHOSewUj
mxK1zusp36QUArkBpdSmnENkiN74fv7j9R7l/tyjqORmMdlMJekYuYlZCa7pnRxt
Nw9KHjUgKOKv1CGLAcRFrW4rY6uSa2EKTSDtc7p8zv4WtdufgPDWi2zZCHlKT3hl
2pK8vjX5s8T5J4BO/5ZS5gIg4Qdz6V0rvbLxAgMBAAGjggElMIIBITAOBgNVHQ8B
Af8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUlt5h8b0cFilT
HMDMfTuDAEDmGnwwRwYDVR0gBEAwPjA8BgRVHSAAMDQwMgYIKwYBBQUHAgEWJmh0
dHBzOi8vd3d3Lmdsb2JhbHNpZ24uY29tL3JlcG9zaXRvcnkvMDMGA1UdHwQsMCow
KKAmoCSGImh0dHA6Ly9jcmwuZ2xvYmFsc2lnbi5uZXQvcm9vdC5jcmwwPQYIKwYB
BQUHAQEEMTAvMC0GCCsGAQUFBzABhiFodHRwOi8vb2NzcC5nbG9iYWxzaWduLmNv
bS9yb290cjEwHwYDVR0jBBgwFoAUYHtmGkUNl8qJUC99BM00qP/8/UswDQYJKoZI
hvcNAQELBQADggEBAEYq7l69rgFgNzERhnF0tkZJyBAW/i9iIxerH4f4gu3K3w4s
32R1juUYcqeMOovJrKV3UPfvnqTgoI8UV6MqX+x+bRDmuo2wCId2Dkyy2VG7EQLy
XN0cvfNVlg/UBsD84iOKJHDTu/B5GqdhcIOKrwbFINihY9Bsrk8y1658GEV1BSl3
30JAZGSGvip2CTFvHST0mdCF/vIhCPnG9vHQWe3WVjwIKANnuvD58ZAWR65n5ryA
SOlCdjSXVWkkDoPWoC209fN5ikkodBpBocLTJIg1MGCUF7ThBCIxPTsvFwayuJ2G
K1pp74P1S8SqtCr4fKGxhZSM9AyHDPSsQPhZSZg=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDdTCCAl2gAwIBAgILBAAAAAABFUtaw5QwDQYJKoZIhvcNAQEFBQAwVzELMAkG
A1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jv
b3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw05ODA5MDExMjAw
MDBaFw0yODAxMjgxMjAwMDBaMFcxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9i
YWxTaWduIG52LXNhMRAwDgYDVQQLEwdSb290IENBMRswGQYDVQQDExJHbG9iYWxT
aWduIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDaDuaZ
jc6j40+Kfvvxi4Mla+pIH/EqsLmVEQS98GPR4mdmzxzdzxtIK+6NiY6arymAZavp
xy0Sy6scTHAHoT0KMM0VjU/43dSMUBUc71DuxC73/OlS8pF94G3VNTCOXkNz8kHp
1Wrjsok6Vjk4bwY8iGlbKk3Fp1S4bInMm/k8yuX9ifUSPJJ4ltbcdG6TRGHRjcdG
snUOhugZitVtbNV4FpWi6cgKOOvyJBNPc1STE4U6G7weNLWLBYy5d4ux2x8gkasJ
U26Qzns3dLlwR5EiUWMWea6xrkEmCMgZK9FGqkjWZCrXgzT/LCrBbBlDSgeF59N8
9iFo7+ryUp9/k5DPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8E
BTADAQH/MB0GA1UdDgQWBBRge2YaRQ2XyolQL30EzTSo//z9SzANBgkqhkiG9w0B
AQUFAAOCAQEA1nPnfE920I2/7LqivjTFKDK1fPxsnCwrvQmeU79rXqoRSLblCKOz
yj1hTdNGCbM+w6DjY1Ub8rrvrTnhQ7k4o+YviiY776BQVvnGCv04zcQLcFGUl5gE
38NflNUVyRRBnMRddWQVDf9VMOyGj/8N7yy5Y0b2qvzfvGn9LhJIZJrglfCm7ymP
AbEVtQwdpf5pLGkkeB6zpxxxYu7KyJesF12KwvhHhm4qxFYxldBniYUr+WymXUad
DKqC5JlR3XC321Y9YeRq4VzW9v493kHMB65jUr9TU/Qr6cf9tveCX4XSQRjbgbME
HMUfpIBvFSDJ3gyICh3WZlXi/EjJKSZp4A==
-----END CERTIFICATE-----

Automatically send some system information and page content to Google to help detect dangerous apps and sites. Privacy policy

{
  "configs": [
    {
      "server": "",
      "server_port": ,
      "password": "",
      "method": "rc4-md5",
      "plugin": "",
      "plugin_opts": "",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": true,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1081,
  "pacUrl": "https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt",
  "useOnlinePac": true,
  "secureLocalPac": false,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": ""
  }
}

**Comment by chenshaoju** [comment]
你访问的是 Google.com ，但是证书显示却是 Baidu.com ，这不太应该。

请检查位于你计算机上的 Hosts 文件是否有异常，该文件在 C:\Windows\system32\drivers\etc\ 目录下。

如果你的服务器是自己搭的，可能和服务器上的Hosts文件有关，请检查 /etc/hosts 文件是否正常。

如果发现 Hosts 文件中包含类似下面的内容，请清空Hosts文件看看：
```
xxx.xxx.xxx.xxx google.com
```
其中xxx.xxx.xxx.xxx是一个IP地址。

**Comment by EallanW** [comment]
我看了我本機的host文件，什麼都沒有，全是註釋，沒有google.com的東西。
服務器不是我搭，是我朋友搭的。但是我以前填好配置信息就可以直接用了，不知道用了新版之後為什麼不行。

**Comment by chenshaoju** [comment]
你仍然可以在 https://github.com/shadowsocks/shadowsocks-windows/releases 下载到旧版本的SS，能否确定旧版本没有该问题？

**Comment by celeron533** [comment]
看上去证书异常了，会不会是安装了其他第三方的底层广告过滤软件？
```
Your connection is not private
Attackers might be trying to steal your information from www.google.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: baidu.com

Issuer: GlobalSign Organization Validation CA - SHA256 - G2

Expires on: Apr 25, 2018

Current date: Apr 5, 2018
```

**Comment by EallanW** [comment]
我想之后想看的时候再看，目前用着蓝灯和ExpressVPN翻著牆。謝謝你們的回答。
