### ISSUE TITLE
3.4.3 可以使用  4.0.9不能使用

### ISSUE THREAD

**Issue by pzx521521** [shadowsocks/shadowsocks-windows#1799]
服务器用的node.js版本的ss

**Comment by chenshaoju** [comment]
如果你的服务器启用了OTA，请禁用，具体原因请阅读： https://blessing.studio/why-do-shadowsocks-deprecate-ota/

node.js 版本已经废弃了，服务端建议使用libev版本： https://github.com/shadowsocks/shadowsocks-libev
