### ISSUE TITLE
CPU at 100% when I download files or stream videos.

### ISSUE THREAD

**Issue by sanasigma** [shadowsocks/shadowsocks-windows#1800]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
shadowsocks-windows 4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows 10

### Steps you have tried / 操作步骤
Restarting the PC, deleting the server profile, deleting the client, updating .NET framework and visual studio

### What did you expect to see? / 期望的结果
I was expecting for a smooth connection until started noticing the lag on my PC.

### What did you see instead? / 实际结果
Lags, CPU usage went up to 100% at all times, the processes that made the cpu usage go 100% was "NT kernel and system" "shadowsocks" "privoxy".

Screenshots:
https://drive.google.com/open?id=1WgfMN6yaDU02qyjiu7Tw3ISNsIYL-it1
https://drive.google.com/open?id=1knkTI_nZms04NKo8iWESsUuSTpC_1feC
https://drive.google.com/open?id=16-82u7S8Xb80bbiRrGurPCEJCEk-jz3p

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
This issue may case by damaged windows socket or TCP/IP protocol stack.

Please start cmd.exe or PowerShell in Administrator, And run these command:
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```

And reboot computer.

**Comment by celeron533** [comment]
Here are the screenshots copied from original post:
![image](https://user-images.githubusercontent.com/3608762/38429850-33cf26ca-39f2-11e8-9958-117852c4c2c8.png)
![image](https://user-images.githubusercontent.com/3608762/38429854-376cce36-39f2-11e8-85ce-50035e437327.png)
![image](https://user-images.githubusercontent.com/3608762/38429858-3a088108-39f2-11e8-9821-a33bc5c6c498.png)

**Comment by celeron533** [comment]
It seems Chrome also has a lot of CPU usages.
And did it also happen in early days?

**Comment by sanasigma** [comment]
@chenshaoju I followed all the steps you provided
https://drive.google.com/open?id=1qX85I8b1t6GAWJy0sO_sNBuOyXFXEus_

Now, it's a lot better now. I'll do a bit more testing and see whether the high CPU usage doesnt come back
https://drive.google.com/open?id=1r2MZJ3t1AMuX4VYOXv2hezzFyJ_BfpfD

**Comment by sanasigma** [comment]
@celeron533 yes, i have a lot of chrome apps and extensions. but now after i tried his @chenshaoju solution, it is fine.
https://drive.google.com/open?id=1tIbpnG1_TixF1_2W9iPmi8Mvy3iqa_dR
https://drive.google.com/open?id=15-u5ULMF7tk-dcq3DmbSmakUuZEfpjiZ
