### ISSUE TITLE
4.0.7版本出现无法加载DLL“libsscrypto: 找不到指定的模块。

### ISSUE THREAD

**Issue by onntootn** [shadowsocks/shadowsocks-windows#1801]
之前一直可以使用，今天为了下一个别的软件安装了c++2015 Red X64（失败了） ，.net4.6.1(以前就安装了4.6.2)，360修复了下环境之后，再启动ss出现问题。详细如下

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.DllNotFoundException: 无法加载 DLL“libsscrypto”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.MbedTLS.md5(Byte[] input, Int32 ilen, Byte[] output)
   在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   在 Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   在 Shadowsocks.Encryption.NoneEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle._InvokeConstructor(Object[] args, SignatureStruct& signature, IntPtr declaringType)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.View.ConfigForm..ctor(ShadowsocksController controller, UpdateChecker updateChecker, Int32 focusIndex)
   在 Shadowsocks.View.MenuViewController.ShowConfigForm(Boolean addNode)
   在 System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5472 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
ShadowsocksR
    程序集版本: 4.7.0.0
    Win32 版本: 4.7.0.0
    基本代码: file:///F:/vpn/new%20txwpn/ShadowsocksR-4.7.0/ShadowsocksR-dotnet2.0.exe
----------------------------------------
System.Windows.Forms
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5468 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5476 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5476 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Drawing.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5420 (Win7SP1.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing.resources/2.0.0.0_zh-CHS_b03f5f7f11d50a3a/System.Drawing.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5472 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5420 (Win7SP1.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

x86版本一直都安装不成功，但是之前ss一直没出现过问题。希望老师们帮帮忙。

**Comment by chenshaoju** [comment]
你好，请问无法安装 x86 版本的 Visual C++ 2015 Redistributable 的错误提示是什么？

**Comment by celeron533** [comment]
4.0.9做了静态编译，试一下

**Comment by onntootn** [comment]
我的程序和控制里有c2015，但我猜它没安装成功，我试着修复后，提示0x80070308，组件的客户端请求一个操作，但由于组件实例的状态，该操作无效。这个问题很早以前就有，但是那时我的ss没有出问题

**Comment by chenshaoju** [comment]
建议尝试一下 4.0.9 版本。

**Comment by onntootn** [comment]
4.0.9版本能正常启动，连接之后提示proxy已停止工作

**Comment by chenshaoju** [comment]
SS的日志里有什么显示吗？
