### ISSUE TITLE
关于近段时间shadowsocks突然无法使用的问题的求助

### ISSUE THREAD

**Issue by Reasuon** [shadowsocks/shadowsocks-windows#1802]
这段时间突然间我突然不能使用shadowsocks了，完全连接不上，但是此前我是可以使用的，我尝试性ping了服务器，一切正常，我也新搭建了一个服务器使用ssserver，但是我的shadowsocks仍旧不能连接上服务器，希望可以得到帮助，谢谢

这是我的环境:

- windows10和安卓
- shadowsocks 4.0.7

这是报错:
[2018-04-07 23:07:27] Shadowsocks started
[2018-04-07 23:07:34] Shadowsocks started
[2018-04-07 23:14:31] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 127.0.0.1:10811
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

底下是我的报错信息和我的配置截图
![image.png](https://upload-images.jianshu.io/upload_images/10971244-274f05f51e209db4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![image.png](https://upload-images.jianshu.io/upload_images/10971244-fff0a50e097e5a88.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![image.png](https://upload-images.jianshu.io/upload_images/10971244-98e2aabeaa3b4610.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![image.png](https://upload-images.jianshu.io/upload_images/10971244-e124a3ef000e7308.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by chenshaoju** [comment]
我试了一下，你的三个IP中，只有最后一个端口是通的，前面两个端口都不通。

能Ping通不意味着端口能通，请尝试使用 TCPing 进行测试：https://www.elifulkerson.com/projects/tcping.php

这是命令提示符下的软件，格式为：
```tcping 123.45.67.89 9876```

其中 123.45.67.89 替换为你的服务器的IP， 9876 替换为你的端口。

另外，你的日志中有一行内容比较让人在意：
```
[2018-04-07 23:14:31] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 127.0.0.1:10811
```

请尝试Ping 127.0.0.1 ，通吗？如果通，使用上面的tcping命令检查 127.0.0.1 10811，通吗？

**Comment by Reasuon** [comment]
@chenshaoju 十分感谢您的协助，已成功排查为端口问题，似乎我就得服务器因为某种不可抗力进行了端口封禁？在更换端口和重新修改防火墙规则后已能够重新访问，新的服务器应该只是我搭建失败的问题
最后再次感谢您的帮助
