### ISSUE TITLE
4.0.9版本，用户自定义规则功能失效。

### ISSUE THREAD

**Issue by cityloveyou** [shadowsocks/shadowsocks-windows#1804]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows7

### Steps you have tried / 操作步骤
1, 编辑user-rule.txt ， 按正确语法编写自定义规则，如：
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||katespade.com
||dictionary.com
||virustotal.com
||starbucks.com

2，保存， 并执行“从GFWList更新本地PAC”操作。
3， 检查pac.txt

### What did you expect to see? / 期望的结果
期望自定义的规则被合并进pac.txt 从而使自定义规则生效

### What did you see instead? / 实际结果
实际pac.txt并没包含自定义的规则，因此用户自定义规则无法生效。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
你好，请试一下IE浏览器是否能正常工作？已知IE以外的浏览器可能会有问题： https://github.com/shadowsocks/shadowsocks-windows/issues/1752#issuecomment-373666279

**Comment by cityloveyou** [comment]
@chenshaoju 也不是，在4.0.7版本上， 执行“从GFWList更新本地PAC”后， 打开pac.txt，能看到自定义的规则被合并到 var rules数组的末尾，但是4.0.9就没有这个行为了。
ss应该是只从pac.txt读取，而不会自动查找user-rule ， 所以只有在pac.txt中存在的定义，才能走ss。纠结。。。

**Comment by cityloveyou** [comment]
@chenshaoju 哦。。。。。自定义规则被添加到rules数组的**首部**而非**尾部**了。
哈哈，好吧好吧，是我粗心了。
