### ISSUE TITLE
Edge浏览器QQ邮件中图片不走PAC

### ISSUE THREAD

**Issue by MstKenway** [shadowsocks/shadowsocks-windows#1805]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10家庭版

### Steps you have tried / 操作步骤
使用EDGE浏览器打开QQ邮箱阅览邮件时，有些图片不走PAC（在Chrome上会走PAC）不知道什么原因……有没有大神解释一下……全局模式下可以看到图片，pac模式下无法加载图片

### What did you expect to see? / 期望的结果
邮件中图片正常显示

### What did you see instead? / 实际结果
EDGE浏览器邮件中图片无法加载显示（即一个×，图片上的超链接仍有效），chrome上能正常在pac模式下浏览。换成全局模式后，edge浏览器也能显示图片。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请尝试以管理员身份启动命令提示符（ｃｍｄ）或PowerShell，然后执行：
```
netsh winhttp import proxy source=ie
```
后重启计算机再试，参考阅读： https://github.com/shadowsocks/shadowsocks-windows/issues/897

**Comment by chenshaoju** [comment]
我测试了一下，没有问题，edge应该会自动引用IE的PAC。

我想问一下，你希望QQ邮箱附件走PAC的目的是什么？你在国外，想反向回国内？

![screenshotcut 3](https://user-images.githubusercontent.com/515763/38592709-283c6c60-3d70-11e8-8b24-c5500a25ced6.jpg)

**Comment by MstKenway** [comment]
![edge](https://user-images.githubusercontent.com/29791637/38594030-06bd3a36-3d77-11e8-83d1-175733ee907f.png)
![chrome](https://user-images.githubusercontent.com/29791637/38594032-0a367880-3d77-11e8-949b-fa881830b256.png)
@chenshaoju 感谢你的关注和回答。是这样的，edge浏览器下的确能走pac的，谷歌等网站确实可以访问，仅仅是在邮箱中，那些无法直接访问的网站发来的邮件中的图片无法加载，譬如推特发了一些广告邮件过来，同样的邮件在chrome中可以加载显示，在edge中无法加载显示。上图第一个是edge下的推特广告，第二个是chrome下的推特广告。

**Comment by chenshaoju** [comment]
我试了一下，相同的PAC的情况下，IE没有问题，但是edge有问题。

通过F12开发工具调试了一下，显示请求正常，返回200，但是实际上是edge从缓存里取数据，由于缓存里并没有内容，所以图片不显示。

这可能是edge的问题。

![screenshotcut 4](https://user-images.githubusercontent.com/515763/38595198-ed7596c6-3d7c-11e8-90ce-6a6128ecfcce.jpg)

**Comment by MstKenway** [comment]
@chenshaoju 谢谢，所以这是edge的问题，目前暂时无法从shadowsocks客户端进行改变是这样吧？那也就不去管它了……
