### ISSUE TITLE
4.0.9使用一段时间后突然不能正常使用，必须重装系统才能解决

### ISSUE THREAD

**Issue by yuzunyue** [shadowsocks/shadowsocks-windows#1806]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题
使用一段时间后，就突然不能科学上网，而且游览器开启后打开的第一个网页总是特别慢，重装系统后恢复正常，但一段时间后又变成这个样子

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.8和4.0.9均出现过此类问题

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows 10 1709

### Steps you have tried / 操作步骤
在手机上可以正常使用SS，说明服务器是正常的，删除配置文件后问题依然存在，ping服务器可以ping通，修复LSP无法解决

### What did you expect to see? / 期望的结果
希望可以在不重装系统下能找到问题所在，每次都要重装系统简直要爆炸了

### What did you see instead? / 实际结果
等待解决中...

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2018-04-10 21:56:44] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
你的日志中有一行：
```
127.0.0.1:1080
```
当出现问题的时候，Ping 127.0.0.1，通吗？

如果不通，该问题似乎无解，有一个类似案例： https://github.com/shadowsocks/shadowsocks-windows/issues/1574 ，推测可能是操作系统的协议栈损坏了或者发生了什么。

能否仔细回忆一下，出现问题前发生了什么？是否安装了什么软件或者进行过什么操作？

**Comment by yuzunyue** [comment]
ping 127.0.0.1 ，无法PING通，提示一般故障，和案例 #1574 一样，问题出现前我一直是在家里使用网线连接笔记本，问题发生时，我把笔记本带到网吧，使用WIFI上网，然后就成这个样子了，印象中之前几次好像也是切换成WIFI就出问题了

**Comment by yuzunyue** [comment]
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
使用后还是无法解决 @chenshaoju

**Comment by chenshaoju** [comment]
此问题很有可能是操作系统的协议栈损坏了。

但是具体是怎么损坏的，以及如何修复，目前网上没有这方面的解决方法。

如果可能，请备份数据，再重置一次系统，并留意一下具体是执行过什么操作，安装过什么软件，或者修改过什么配置后导致的，这可能会帮助到其他人，并有助于解决该问题。

**Comment by yuzunyue** [comment]
好的，我再重装系统试试

**Comment by yuzunyue** [comment]
@chenshaoju 今天问题又出现了，操作是我使用了另外一台登录过我账户的WIN10电脑（重装系统以后一直没使用过这台电脑），而且之前几次出问题也是因为我使用了另外一台登录我账户的WIN10电脑，这些电脑也安装了shadowsocks

**Comment by chenshaoju** [comment]
你的Windows 10补丁打齐了吗？

**Comment by chenshaoju** [comment]
非常奇怪的问题，你是否有使用其他VPN产品，或者网络加速器／网游加速器之类的？

**Comment by yuzunyue** [comment]
使用UU加速器，我刚开始也怀疑过，用UU自带的LSP恢复工具，还是不行

**Comment by chenshaoju** [comment]
很早以前有一个类似的报告，但是好像无解： https://github.com/shadowsocks/shadowsocks-windows/issues/1344

**Comment by yuzunyue** [comment]
嗯嗯，我再找找原因，希望能解决，感谢您的热心回答
