### ISSUE TITLE
PAC user-rule is broken

### ISSUE THREAD

**Issue by metanqy** [shadowsocks/shadowsocks-windows#1807]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### What did you expect to see? / 期望的结果
youbute.com should be excluded.

### What did you see instead? / 实际结果
youtube.com's connection still using shadowsocks

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[user-rule.txt](https://github.com/shadowsocks/shadowsocks-windows/files/1897579/user-rule.txt)

**Comment by chenshaoju** [comment]
In my case, The user-rule.txt is working.

Please make sure you are using correct format and updated GFWList.

g.e.
```
@@||google.com
```

![image](https://user-images.githubusercontent.com/515763/38607468-4af7720a-3dab-11e8-981a-853378d85083.png)

**Comment by celeron533** [comment]
please check your PAC file content. It should include your user-rule changes.
