### ISSUE TITLE
win10运行这个，然后直接关机，重新启动后（这时候ss还没启动），网页就都打不开了，显示代理服务器错误

### ISSUE THREAD

**Issue by fawdlstty** [shadowsocks/shadowsocks-windows#1808]

**Comment by chenshaoju** [comment]
请在为未开启SS的情况下打开Internet Explorer选项，点击连接选项卡，再点击局域网设置按钮，然后，请确保取消了使用自动配置脚本后，点击确定即可（如下图）。

![image](https://user-images.githubusercontent.com/515763/38610222-c7fd22e8-3db2-11e8-98a0-a2553cfc871a.png)

**Comment by celeron533** [comment]
如果你在SS里设置了启用系统代理，SS会修改当前代理，在正常退出的时候会还原之前的代理设置。非正常退出会导致代理设置不能被还原到原先的状态
