### ISSUE TITLE
shadowsocks退出 切换模式报错

### ISSUE THREAD

**Issue by youjinli** [shadowsocks/shadowsocks-windows#1809]
### Config and error log in detail 

![59914922377838896](https://user-images.githubusercontent.com/19640596/38653505-a88fe2fc-3e3d-11e8-8ea6-6a65122635c4.jpg)

**Comment by chenshaoju** [comment]
请删除 Shadowsocks.exe 所在目录下的 user-wininet.json 文件，然后再试。

**Comment by youjinli** [comment]
@chenshaoju 不行呢  没有安装  我直接下载zip解压点击exe程序就运行了   Shadowsocks.exe在本地找不到

**Comment by chenshaoju** [comment]
请尝试将整个压缩包解压到一个固定的文件夹，比如 D:\SS\ 然后再试试？

**Comment by youjinli** [comment]
@chenshaoju  好  我换了4.0.7版本  还会报错 就用你的方法试试  谢谢~

**Comment by celeron533** [comment]
看样子似乎是sysproxy.exe被干掉了

**Comment by chenshaoju** [comment]
请尝试暂时退出或停用安全（杀毒）软件看看？
