### ISSUE TITLE
拨号上网连接名称包含中文时无法使用

### ISSUE THREAD

**Issue by freehehe** [shadowsocks/shadowsocks-windows#1810]
ss 在接入有线的情况下有时候会出现无法连接的情况，但是接入 WiFi 正常。发现基本为拨号上网的原因 
https://i.loli.net/2018/04/14/5ad0d48aaa4a4.png 
https://i.loli.net/2018/04/14/5ad0d501e090e.jpg 
把宽带连接几个汉字改为英文就好

哪个地方出问题了?

**Comment by rebiu** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1142

**Comment by chenshaoju** [comment]
这个地方是应该优化一下，当检测到网络连接类型发生变化的时候，重新套用PAC代理。

**Comment by celeron533** [comment]
一直有人反映这个问题，但似乎只有win10存在这个问题？

**Comment by Leelugen** [comment]
换了个英文名字 ，终于行了

**Comment by Lemzon** [comment]
I solved the problem that I was puzzled for a long time, thx. @Leelugen

**Comment by partholon** [comment]
> 一直有人反映这个问题，但似乎只有win10存在这个问题？

这个问题一直都在，起码WIN7就有这个问题，注册表里拨号连接的项是一个二进制项，用中文名就是乱码，SS估计是搜索不到对应的项改不了。

**Comment by celeron533** [comment]
应该是sysproxy对双字节支持不佳导致

**Comment by jsboer** [comment]
换了名字之后可能要重启电脑才行，如果重启遇到更新订阅失败的问题，把之前的订阅的链接删除掉重新添加订阅链接。

**Comment by Ultrasty** [comment]
🐂的，问题解决了
