### ISSUE TITLE
程序直接运行不了

### ISSUE THREAD

**Issue by s757959919** [shadowsocks/shadowsocks-windows#1811]

**Comment by s757959919** [comment]
Shadowsocks 已停止工作

**Comment by liangzhenL** [comment]
我也是这样，不知道为什么。一台电脑可以运行，另外一台电脑不能打开软件

**Comment by chenshaoju** [comment]
请问有无什么错误提示？能否截个图？

**Comment by s757959919** [comment]
我用的最新版，然后更新了下 .NET Framework 4.6.2  可以了

**Comment by chenshaoju** [comment]
OK，下次请务必要提供具体信息，我不是神，不可能光凭“运行不了”这四个字就能知道是什么问题。

**Comment by s757959919** [comment]
嗯嗯。 麻烦了。辛苦

**Comment by liangzhenL** [comment]
![_20180414172344](https://user-images.githubusercontent.com/37231287/38766722-a52a869a-4008-11e8-8ffa-cf0672a428a7.png)
请问这样可以看出是什么问题吗？

**Comment by chenshaoju** [comment]
@liangzhenL 很有可能你没有安装 .NET Framework，建议安装最新版后看看：　https://www.microsoft.com/net/download/dotnet-framework-runtime

**Comment by liangzhenL** [comment]
已安装.NET Framework 4.6.2不行，我回去安装.NET Framework 4.7.1看看

**Comment by chenshaoju** [comment]
也可能是 .NET Framework 损坏了，这个可能需要进一步分析，如果仍然崩溃，请将详细信息里面的部分发上来看看。

**Comment by jasonliul** [comment]
应该是.net的问题, 4.71下面, ss4.09总是有问题, 经常是这样, 浏览器新开页面, ss却不做连接. 4.08稍好.

但是升级新版4.72会一切正常, 请列位尝试.

**Comment by NAVrasZ** [comment]
![image](https://user-images.githubusercontent.com/20354364/39963555-0fed51e8-56a1-11e8-8534-0a013cb87104.png)
win10 1803 64bit
.net 4.72
vcredist2017_x86

**Comment by chenshaoju** [comment]
@NAVrasZ 你是否使用了插件？

请尝试再次启动看看，该问题可能和某些安全软件有关： https://github.com/shadowsocks/shadowsocks-windows/issues/1849

**Comment by NAVrasZ** [comment]
hmm没有插件，加入defender白名单重启后还是一样，sha512值符合...

**Comment by chenshaoju** [comment]
如果可能，请做一个测试，将 shadowsocks.exe放到一个新的目录中，手动重新配置，还会有这个现象吗？

**Comment by NAVrasZ** [comment]
噢确实，删掉其他文件后可以运行了

**Comment by ritaswc** [comment]
@NAVrasZ   你直接装一个TeamViewer，给他远程看看，这么沟通多麻烦

**Comment by chenshaoju** [comment]
出于安全考虑，不建议使用远程控制等方式。

因为无法保证连接上来的人是你所期望的那个人。

**Comment by nemolpsky** [comment]
我也是这个问题，不过我在公司电脑win10上运行的时候他会提示我说下载.net，但是我在win7的时候就没有提醒直接跳出个框提示停止运行，刚下了.net等下重启后试试看。

**Comment by nemolpsky** [comment]
已经可以用了，确实是要下载最新的.net，只不过不知道为啥win10有提示，win7没提示。

**Comment by celeron533** [comment]
> 已经可以用了，确实是要下载最新的.net，只不过不知道为啥win10有提示，win7没提示。

win7上手自带framework3.5，运行4.6.2的程序直接挂
win10使用较老的安装盘装出来自带framework4.5，能运行部分4.6.2程序的特性，所以ss-win能启动并检测你当前framework版本号
