### ISSUE TITLE
更新GFWlist老是失败

### ISSUE THREAD

**Issue by buchuanqiuku** [shadowsocks/shadowsocks-windows#1812]
手机端连接使用是正常的 这是日志
ss是4.0.9 windows7 64位 
[2018-04-14 16:12:20] Shadowsocks started
[2018-04-14 16:12:20] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-04-14 16:13:08] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by buchuanqiuku** [comment]
@chenshaoju 这个应该是什么原因知道不

**Comment by buchuanqiuku** [comment]
@chenshaoju 这个应该是什么原因知道不

**Comment by chenshaoju** [comment]
```
[2018-04-14 16:13:08] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
```
这一行意味着你没有配置SS服务器，或者你所配置的SS服务器被墙、配置不正确等其他原因导致无法使用。

**Comment by chenshaoju** [comment]
Ping只代表你到服务器能通，不意味着你到服务器的端口能通，请使用 tcping （ https://www.elifulkerson.com/projects/tcping.php ）测试看看，这是命令提示符下的工具，格式为：
```
tcping 123.45.67.89 9876
```
其中 123.45.67.89 为你服务器的IP， 9876 为你的服务器的端口。

如果不通，请与你所在公司的网管联系。

**Comment by buchuanqiuku** [comment]
tcping测试也能通

**Comment by chenshaoju** [comment]
Hmmmm.....，全局模式能打开Google吗？

**Comment by buchuanqiuku** [comment]
真奇怪 刚说还不能用 现在又能更新成功了 好像这个问题是间歇性的

**Comment by chenshaoju** [comment]
¯\\\_(ツ)_/¯ 也许是临时性的网络故障，也可能是你所在的网络部署了内容过滤／信息防泄漏产品。

**Comment by buchuanqiuku** [comment]
有可能 谢谢解答
