### ISSUE TITLE
Question: How to fill in field 'Plugin Options:'

### ISSUE THREAD

**Issue by john564** [shadowsocks/shadowsocks-windows#1813]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.6 But same question with later versions
https://github.com/shadowsocks/shadowsocks-windows/releases/download/4.0.6/Shadowsocks-4.0.6.zip

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows

### Steps you have tried / 操作步骤
tried using the SIP standard 
ss://Herekeyok@185.123.456.789:12345/?plugin=kcptun;mode=fast2;crypt=salsa20

#####################################################################
I have shadowsocks over kcptun working on windows by running kcptun from cmd.
I cannot figure out the correct format to use shadowsocks GUI kcptun plugin.

I provide an example of a kcptun config file, how to convert this into Plugin Options 
or better still, just load from the file, e.g. C:\kcptun\kcptun_config.json

=======================================================

The latest GUI for shadowsocks has incorporated plugins
How to fill in Plugin Options ? (please use the kcptun config from below as example)

Plugin : C:\kcptun\client_windows_amd64.exe
Plugin Options : 

=======================================================
== running kcptun from cmd
== kcptun config,  saved at C:\kcptun\kcptun_config.json

{
"localaddr": ":54321",
"remoteaddr": "185.123.456.789:12345",
"key": "Herekeyok",
"crypt": "salsa20",
"mode": "fast2",
"conn": 6
}

= I download the kcp windows exe, and save e.g.
C:\kcptun\client_windows_amd64.exe

= run
cmd.exe /k C:\kcptun\client_windows_amd64.exe -c C:\kcptun\kcptun_config.json

= also need to make a new instance of shadowsocks to connect to localhost:54321

**Comment by celeron533** [comment]
Currently, the `plugin options` only set the option string as an environment key-value pair.
A possible enhancement which perhaps be implemented to parse CLI arguments to the plugin directly: #1672

**Comment by john564** [comment]
Please give a working example, for kcptun and/or simple obfs.
For windows kcptun 
Plugin : C:\kcptun\client_windows_amd64.exe
Plugin Options : ????????????

**Comment by celeron533** [comment]
#1368

**Comment by john564** [comment]
Ok, So, am I correct.

It does not work with kcptun 
Sp still need to still use old way of running kcptun from cmd ?

It does work with obfs, details

Get obfs-local.exe from 
https://github.com/shadowsocks/simple-obfs/releases

Plugin C:\obfs-local.exe
Plugin Options obfs=http;obfs-host=www.bing com

**Comment by chenshaoju** [comment]
I'm confused,Do you have kcptun?
You need use kcptun to use kcptun: https://github.com/shadowsocks/kcptun/

**Comment by john564** [comment]
I used 
https://github.com/xtaci/kcptun
https://github.com/xtaci/kcptun/releases

**Comment by chenshaoju** [comment]
Shadowsocks for Windows ONLY support plugins if it's accord with SIP003 , For more info,Please read: https://github.com/shadowsocks/shadowsocks-org/issues/28

**Comment by john564** [comment]
Confirm its working. Here are my notes.

Get kcptun (client_windows_amd64.exe) from 
https://github.com/shadowsocks/kcptun/releases

Does not work with standard kcptun
https://github.com/xtaci/kcptun/releases

# generic, save to e.g. C:\
Plugin C:\client_windows_amd64.exe
Plugin Options mode=fast2;key=Herekeyok;crypt=salsa20

also need to make a new instance of shadowsocks to connect to 
185.123.456.789:12345
where port 12345 is the kcptun listening port on the server
(not the ss listening port on the server you normally connect to)
