### ISSUE TITLE
希望添加翻墙回国功能，安卓版有仅代理中国大陆地址，PC版好像没有。

### ISSUE THREAD

**Issue by laomms** [shadowsocks/shadowsocks-windows#1814]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
你好，目前暂时不支持，不过这种情况建议不要使用系统代理，并且专门使用一个浏览器（比如Firefox）为翻回国内配置代理设置即可。

![image](https://user-images.githubusercontent.com/515763/38797048-e68b641e-418f-11e8-8220-72098ce64226.png)


请注意：你需要有一个位于中国大陆内的SS服务器。

**Comment by laomms** [comment]
我有中国IP的SS服务端，如果用全局方式，可以翻回去，可以识别为国内IP，但是反而google等网站上不了，不知道能不能添加仅代理中国IP的选项，本地的网络不经过代理。
