### ISSUE TITLE
使用这个软件如何不能访问pinterest ，请问如何才可以访问呢？

### ISSUE THREAD

**Issue by wtsurfy** [shadowsocks/shadowsocks-windows#1815]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
你好，测试了一下，没有问题。
![image](https://user-images.githubusercontent.com/515763/38796844-4365b79e-418f-11e8-8b1f-55c03a6f53b3.png)

请尝试右击任务栏托盘区的纸飞机小图标，选择PAC，再点击“从GFWList更新本地PAC”看看？

**Comment by wtsurfy** [comment]
那奇怪了，我其他网站都可以上唯独这个网站上不去。我ping 了一下也没有通过。。我用的google浏览器和IE浏览器都上不去。还哪里有问题。。还请多多指教。。或者留个微信咨询一下。谢谢

**Comment by wtsurfy** [comment]
我试了一下，全局模式可以上，PAC模式上不去。。这是什么原因？
![m 04zr0gys dy b6y clm](https://user-images.githubusercontent.com/38415184/38911419-d136df9e-4301-11e8-9847-26a5885d0204.png)

**Comment by celeron533** [comment]
查看一下是否有下列文件的读写问题（或者其中有的文件正在被其他文本编辑器、文件同步工具占用）
```
gfwlist.txt
user-rule.txt
abp.txt
```
或者删除`ss_win_temp`文件夹有再试
