### ISSUE TITLE
对于没有代理选项的程序能不能像Proxifier那样代理呢? 

### ISSUE THREAD

**Issue by ghosoft** [shadowsocks/shadowsocks-windows#1816]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### What did you expect to see? / 期望的结果
![snipaste_2018-04-17_11-21-42](https://user-images.githubusercontent.com/4844538/38847031-0d79f3f4-4232-11e8-8a84-0a3d1d3314b3.png)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
理论上大部分应用都可以使用Proxifier代理，请检查你的Proxifier选项设置，某些情况下需要在Proxifier里的应用列表里添加，右击可能无效。

**Comment by ghosoft** [comment]
qq家族的东西, ss开全局也不能(全功能)代理, 比如微信(不能发图, 可能刷不出头像), qq音乐(能听歌, 不能用微信号扫码登陆), 可是proxfier却可以, 为什么呢?
