### ISSUE TITLE
为什么我在服务器改了密码以后，关掉iptables才能用。。。

### ISSUE THREAD

**Issue by LEONllllsu** [shadowsocks/shadowsocks-windows#1820]
一开始配置了多端口，然后改了一个端口的密码，后面查看iptables的配置 里面没了我之前开放的端口，然后我再添加端口进去，还是不能使用ss。。。
关了iptables就好了

**Comment by chenshaoju** [comment]
这意味着你的端口配置有误，通常情况可能是这样的：
```
iptables -A INPUT -p tcp --dport 1234 -j ACCEPT
```
其中 1234 是你的SS端口。
