### ISSUE TITLE
Add instructions how to connect to Outline server

### ISSUE THREAD

**Issue by neluzhin** [shadowsocks/shadowsocks-windows#1821]
Please add instructions to your wiki /documentation how to connect to [Outline](https://getoutline.org) server.

**Comment by celeron533** [comment]
Normally it needs `server ip`, `port` and `encryption method`.

**Comment by jun9** [comment]
> The Outline share link contains the direct link actually.
> 
> https://s3.amazonaws.com/outline-vpn/index.html#/invite/ss%3A*****************
> 
> copy string from ss (after index.html#/invite/ in the share link ) to the end,and decode it with url decoder ,that's the direct link.
https://github.com/Jigsaw-Code/outline-server/issues/101
