### ISSUE TITLE
win10更新后无法使用ss访问外网

### ISSUE THREAD

**Issue by scz77** [shadowsocks/shadowsocks-windows#1822]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
正式版4.08 4.09

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10 1709 os 16299.371
.net framework 4.5.1

### Steps you have tried / 操作步骤
使用ss无法访问外网，以管理员权限打开，并连接至在APP superWINgy中测试过可以访问外网的服务器
尝试过issues提到过的办法，包括删除json后缀文件，reset ipv4 ipv6 winsocket，每次仅在打开ss的瞬间有一个入站date，然后再无任何出站入站数据，ping127.0.0.1 ping 服务器都通

### What did you expect to see? / 期望的结果
能正常访问，未升级win10之前还可以用，升级之后就不可以了

### What did you see instead? / 实际结果
无法访问外网

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

[2018-04-20 20:40:26] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-04-20 20:40:26] connect to api.github.com:443
[2018-04-20 20:40:26] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-04-20 20:40:26] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by scz77** [comment]
你好，多谢回复，我刚刚尝试了一下把拨号连接的名字改成英文然后打开自动设置代理就可以了，但是win10会自动关闭自动设置代理，不知道为什么，仅供win10更新后不能上网的情况参考一下

**Comment by celeron533** [comment]
>但是win10会自动关闭自动设置代理

可能是其他第三方程序影响？
