### ISSUE TITLE
客户端2.3.1可以，但4.0.8和4.0.9都不行 哪位解决这个问题了

### ISSUE THREAD

**Issue by type-writer** [shadowsocks/shadowsocks-windows#1825]
分别在两台电脑上试过
一台win7、Framework3.5、有线网连接；
另外一台是win10、Framework4.7、无线网连接；
用2.3.1版本的客户端连接正常，google、youtube都能打开
用4.0.9、4.0.8都不行，全部参数设置完全一样
哪位遇到这个问题并且解决了？

**Comment by chenshaoju** [comment]
如果你的服务器使用了一次性验证（OTA），请在服务端关闭该功能，后续版本已经不再支持该功能。

具体信息请阅读： https://blessing.studio/why-do-shadowsocks-deprecate-ota/

**Comment by type-writer** [comment]
非常感谢

2018-04-26 18:43 GMT+08:00 Chen Shaoju <notifications@github.com>:

**Comment by Starxyz** [comment]
我从4.0.8升到4.0.9的时候不能用，后来把4.0.8原来那个文件夹删掉，在新的文件夹打开4.0.9重新配置端口后就能用了。你是不是直接把新版的exe文件解压到旧版的文件夹去了？
