### ISSUE TITLE
4.09速度过慢的问题

### ISSUE THREAD

**Issue by Ikaruga13** [shadowsocks/shadowsocks-windows#1826]
之前一直用sockcap64挂的SS
最近嫌不方便换了4.09版shadowsock
但是用sockcap挂youtube一般都能有15000Kbps的速度
但是用shadowsock能上1000Kbps都不错了
请问具体是什么问题
服务器是vultr
系统日志无报错
浏览器chrome和edge都试了没区别
需要怎样解决这问题???

**Comment by chenshaoju** [comment]
你好，测试了一下我在英国的服务器，没有问题，也达不到15000Kbps的速度，但是不至于慢到1000Kbps。

![image](https://user-images.githubusercontent.com/515763/39309395-75371d5e-499a-11e8-8326-3ca1d086849a.png)

如果你是自己搭建的服务器，请尝试在服务端启用 hybla 拥塞算法，看看是否有改进。
https://gist.github.com/chenshaoju/b0e20f23efabb8eb2cd4

**Comment by Ikaruga13** [comment]
比较奇怪的是 使用sockcap64的情况下
同一时间 基本上我用4.09就只有sockcap64的十分之一的速度
我不清楚是我系统的问题还是软件设置或者服务器的问题
电脑 服务器 系统都是同一个
只是觉得没理由差这么多 
![qq 20180426220405](https://user-images.githubusercontent.com/38713933/39310914-3620486c-499e-11e8-88f6-8c0b3e3d5b3b.jpg)
这个是白天用sockcap的速度 晚上没那么快
![8 a5o e mk xx b vj6f0h](https://user-images.githubusercontent.com/38713933/39310961-54592b46-499e-11e8-9091-8355db632174.png)
这是5分钟前测试的速度

然后用4.09的......
![solw](https://user-images.githubusercontent.com/38713933/39311010-6ec75926-499e-11e8-8405-c7a55fe08b18.png)

忍不了好吧......

**Comment by Ikaruga13** [comment]
刚刚我用亚马逊的AWS测试了一下好像没问题
然后就回到vultr换地方新开了个服务器好像也没问题
基本确定是服务器问题了....

老服务器的情况基本上是用sockcap下 连接前10秒左右和4.09客户端同样速度
10秒后速度才起来  连续播放U管 跳视频也不会降速
4.09客户端速度就只能一直维持低速了..

我自己也是个小白.把老服务器关了
回头再碰到这种情况需不需要保留问题服务器以供测试?

**Comment by chenshaoju** [comment]
Hmmmmm....不知道了，也许被重点关照了？

**Comment by manjuprajna** [comment]
try use BBR
