### ISSUE TITLE
Is there any way to replace the icon shown in the status bar?

### ISSUE THREAD

**Issue by skygate2012** [shadowsocks/shadowsocks-windows#1828]
Can I customize the task icon shown in the status bar? I tried putting `icon.png` under the root folder of shadowsocks program, like in shadowsocksR, but it doesn't seems to work.

**Comment by studentmain** [comment]
Download source code, replace icon, build from source code.

skygate <notifications@github.com> 于 2018年4月27日周五 07:23写道：
