### ISSUE TITLE
4.0.9版扫描二维码时出现"无法解析二维码"的提示

### ISSUE THREAD

**Issue by LX314** [shadowsocks/shadowsocks-windows#1829]
二维码在 MAC 电脑上正常使用, 并且 YouToBe 1080P 视频不卡顿

Win10 最新版, 除了自带的 defender, 没有安装任何杀毒软件.

**Comment by LX314** [comment]
兼容性, 管理员身份打开都不行

**Comment by chenshaoju** [comment]
你好，这儿有三个二维码，你可以测试一下能否扫描： https://github.com/shadowsocks/shadowsocks-windows/issues/1585#issuecomment-353826657 ，我测试了一下，没有问题。

另外，你的二维码是SS的还是SSR的？SS无法识别SSR的二维码。

**Comment by LX314** [comment]
额不能识别 SSR 吗? 抱歉, 第一次用这个软件, 我换成 SS再试一下.

**Comment by LX314** [comment]
@chenshaoju 你好, 请问 SSR 链接可以转成 SS 吗? 怎么转换

**Comment by chenshaoju** [comment]
SS只支持SSR的 origin 协议，且混淆模式只能为 plain 。

其他参数（服务器IP、端口、密码、加密等）互相对应。

二维码转换好像没有较好的办法，你只能手动转换过去。

**Comment by LX314** [comment]
好的 谢啦~
