### ISSUE TITLE
报错： System.UnauthorizedAccessException:对路径的访问被拒绝

### ISSUE THREAD

**Issue by Pavel-king** [shadowsocks/shadowsocks-windows#1830]
win10 
4.0.9版 运行程序就报错
4.0.4版 输入服务器地址和密码后点击确定 会报错
![1](https://user-images.githubusercontent.com/12945916/39345208-b2d69a0c-4a19-11e8-8092-2ea0e2beebe2.png)

**Comment by chenshaoju** [comment]
这意味着你的 Shadowsocks.exe 所在目录没有写入权限，请尝试新建一个目录，比如 D:\SS\ 然后把 Shadowsocks.exe 放进去后再执行看看？
