### ISSUE TITLE
Vimeo temporarily blocked - Vimeo视频无法访问

### ISSUE THREAD

**Issue by mimimhmh** [shadowsocks/shadowsocks-windows#1831]
无法使用Vimeo视频，出现You have been temporarily blocked。 点击‘I'm not a robot’后持续加载，无法访问到下一页面。 

有没有人遇到同样的问题？ 

怎么解决啊？ 急~很急~ 

多谢多谢

I cant visit Vimeo pages. There shows 'You have been temporarily blocked'. It is still loading after I click 'I'm not a robot' button. 

Anyone meet the same problem? Need help~ 

Cheers

**Comment by aglent** [comment]
是用GCE吗？它们的IP被Vimeo屏蔽了

**Comment by celeron533** [comment]
你使用的中转服务器被Vimeo拉进了黑名单

**Comment by Henryyichao** [comment]
XX-net/XX-Net#4740
