### ISSUE TITLE
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。

### ISSUE THREAD

**Issue by iSteveyang** [shadowsocks/shadowsocks-windows#1833]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9 最新版

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10 最新版， 安装.NET Framework 4.62 提示已安装更高， 安装Microsoft Visual C++ 2015 Redistributable (x86)提示已安装其他版本

### Steps you have tried / 操作步骤
使用最新版ss客户端，使用扫描屏幕二维码录入，服务器经其他设备检测可用，直接开启代理，PAC模式

### What did you expect to see? / 期望的结果
访问谷歌，YouTube等正常网站

### What did you see instead? / 实际结果
无法访问

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![image](https://user-images.githubusercontent.com/20753221/39413840-dc969d6a-4c62-11e8-86fc-cc07eff93ddf.png)
![image](https://user-images.githubusercontent.com/20753221/39413857-180b8b94-4c63-11e8-8ce0-3e2d5be367a2.png)

**Comment by chenshaoju** [comment]
此问题看起来很像是你服务器端口没打开或者被墙了。

如果确认配置无误，同时配置与其他设备相同且其他设备能正常工作的话，请以管理员身份启动命令提示符或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一回车，三行执行完毕后重新启动计算机后再试试。

**Comment by iSteveyang** [comment]
您好，根据您的提醒，是被win10自带的防火墙墙了，我添加了信任，可以正常上网了，谢谢您
