### ISSUE TITLE
客户端错误代码0

### ISSUE THREAD

**Issue by Leoin01** [shadowsocks/shadowsocks-windows#1836]
版本：4.0.9
操作环境：Win 10 x64 Version 1803(OS Build 17134.5)
操作步骤：直接运行
期望的结果：正常运行

Fatal error . can't check configuration file 'config.txt':(error number 0)

[2018-05-03 15:11:51] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
这意味着你所使用的服务器有问题，可能是客户端配置端口不正确，也可能是你的服务器被墙了，或者服务器端口不正确，防火墙配置不正确等。

**Comment by Leoin01** [comment]
可是我服务器信息什么都没填写的时候都这样的报错，手机用的一样的服务器可以正常使用的

**Comment by chenshaoju** [comment]
Windows 版和 Android版不一样，Windows版默认不带服务器，Android默认带了一个服务器。
