### ISSUE TITLE
Chrome在Windows 10 1803会卡死

### ISSUE THREAD

**Issue by dwzrlp** [shadowsocks/shadowsocks-windows#1839]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows 10 1803

### Steps you have tried / 操作步骤
使用Chrome会卡死，整个系统无法操作，鼠标可以移动，会有滴滴的声音。
彻底卸载更新过chrome，感觉不像是chrome的问题。然后如果不打开shadowsocks的情况，chrome正常使用没问题。打开shadowsocks的情况下，使用一会儿chrome就会卡死

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
这是Windows 10 1803的问题，具体请阅读： https://www.cnbeta.com/articles/soft/722261.htm

**Comment by dwzrlp** [comment]
谢谢你，跟这个描述完全相同，我只是搜索的时候没找到这个，谢谢你！抱歉我以为是shadowsocks的问题。
