### ISSUE TITLE
SS是怎样在1080这socks代理端口上做了http兼容？

### ISSUE THREAD

**Issue by hoodiearon** [shadowsocks/shadowsocks-windows#1841]
填写socks代理端口而不必填写privoxy的监听端口，直接能进入浏览器访问Google，令我感到困惑不解

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1472

**Comment by wongsyrone** [comment]
listener获得首包，根据首包特点用责任链模式传递给注册的服务

**Comment by loremwalker** [comment]
也就是说层层调用，总有一个会处理并转为相应协议到同一端口上是吧？
