### ISSUE TITLE
帮助下的显示日志报错

### ISSUE THREAD

**Issue by Eestinian** [shadowsocks/shadowsocks-windows#1842]
### Config and error log in detail 
![error](https://user-images.githubusercontent.com/30518681/39695884-a10d42c8-521e-11e8-960d-99cfb536fb27.png)

**Comment by chenshaoju** [comment]
这个现象非常奇怪。

请尝试删除 C:\Users\Eestinian\AppData\Local\Shadowsocks 目录后再试。

**Comment by celeron533** [comment]
#1396

**Comment by Eestinian** [comment]
嗯，删除了4.0.9对应的那个user.config就可以了
