### ISSUE TITLE
访问超时 ERR_TIMED_OUT

### ISSUE THREAD

**Issue by yangchendoit** [shadowsocks/shadowsocks-windows#1844]
访问 https://developer.mozilla.org 超时，之前也遇到过访问其他网站偶尔超时的情况，但google正常，查看日志也并未看到异常。

**Comment by chenshaoju** [comment]
很有可能是你的服务器到这个网址的连接有问题。

也可能是你的服务器的 DNS 设置有问题，如果是自己搭建的服务器，尝试使用 8.8.8.8 作为 /etc/resolv.conf 看看？
