### ISSUE TITLE
”高可用“和”根据统计“实现方式上有什么区别？

### ISSUE THREAD

**Issue by reaCodes** [shadowsocks/shadowsocks-windows#1846]
shadowsocks-windows: 4.0.9

设置中”高可用“是通过延迟和丢包率来实现切换的吗？我使用”根据统计“是无法连接的状态，这两者具体是以怎么样的方式工作的？

**Comment by celeron533** [comment]
#1792

**Comment by reaCodes** [comment]
@celeron533 ”根据统计“是怎么工作的？

**Comment by celeron533** [comment]
>”根据统计“是怎么工作的？

Please check the source code
