### ISSUE TITLE
字体“Consolas”不支持样式“Regular”

### ISSUE THREAD

**Issue by viyski** [shadowsocks/shadowsocks-windows#1848]
System.ArgumentException: 字体“Consolas”不支持样式“Regular”。
   在 System.Drawing.Font.CreateNativeFont()
   在 System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   在 System.Drawing.Font..ctor(String familyName, Single emSize)
   在 Shadowsocks.Model.LogViewerConfig..ctor()
   在 Shadowsocks.Model.Configuration.Load()
   在 Shadowsocks.Controller.ShadowsocksController..ctor()
   在 Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1376
