### ISSUE TITLE
4.0.10不支持win7吗？

### ISSUE THREAD

**Issue by lilongcnc** [shadowsocks/shadowsocks-windows#1850]
现在的最新版本不支持win7吗？很郁闷......
chacha20-ietf-poly1305 加密方式有办法在win7上支持吗？求大大解惑呀~~~

**Comment by chenshaoju** [comment]
你好，支持的。

![image](https://user-images.githubusercontent.com/515763/39974901-0e4b5020-575e-11e8-895b-2b9d5d1be730.png)

**Comment by wongsyrone** [comment]
Windows 7 SP1

**Comment by lilongcnc** [comment]
必须是win7 sp1才可以？
