### ISSUE TITLE
好吧，看样子我还是不会编辑规则

### ISSUE THREAD

**Issue by Tissio** [shadowsocks/shadowsocks-windows#1852]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）

最新版 4.0.10？
### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）

win10 1803
### Steps you have tried / 操作步骤
众所周知，自带的GFWILST并不完美，所以我是自己添加PAC规则。我看了网上的语法，以twitch.tv，以及网站AVGLE.com为例。
第一步，在user-rule中输入
||twitch.tv^   以及    ||avgle.com^
[pac.txt](https://github.com/shadowsocks/shadowsocks-windows/files/2001213/pac.txt)
  (有回车）
第二步，从GFWLIST更新本地PAC规则
第三步，发现PAC文件里，头几行有了相应的代码

### What did you expect to see? / 期望的结果
twitch 和 avgle应该走代理，速度应该很快

### What did you see instead? / 实际结果
twitch avgle并没有走代理，而且我的google drive file居然连不上来咯。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
（可以不传嘛，我不知道传哪些）

**Comment by chenshaoju** [comment]
你用的什么浏览器？

请尝试一下IE，IE是否可以工作？

**Comment by Tissio** [comment]
我用的chrome，切换到IE后，在PAC模式下，twitch的访问速度还是不如全局，几乎是PAC看不了（已经加入规则，如果没有加错的话）

**Comment by chenshaoju** [comment]
第一感觉是这种流媒体的服务没有走代理，可能网站使用了WebRTC或者其他技术导致pac不生效。

请尝试在Chrome上使用WebRTC Network Limiter （ https://chrome.google.com/webstore/detail/webrtc-network-limiter/npeicpdbkakmehahjeeohfdhnlpdklia?hl=zh-CN ），并使用最后一个选项看看。

**Comment by zfk513** [comment]
AVGLE #滑稽

**Comment by wuqiling97** [comment]
流媒体获取数据的域名跟网站域名可能不同，比如youtube的视频数据就是从*.googlevideo.com上下载的

**Comment by billysingo** [comment]
没记错的话twitch是jtvnw.net和ttvnw.net这两个。只加twitch.tv是没法将直播视频代理的。
另外那个网站就不知道了
