### ISSUE TITLE
请问有没有配置全局模式下 部分网站直连的方法？

### ISSUE THREAD

**Issue by DreamXiao** [shadowsocks/shadowsocks-windows#1856]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.10

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win 7

### Steps you have tried / 操作步骤
我看IE浏览器设置里面开启全局模式后 已经有不使用代理服务器的配置。但是我一切换全局/pac模式后，这个配置又变成了默认的：
;localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*
我在user-wininet.json文件里面追加了
"BypassList":"localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*;**120.26.***<local>",好像没什么效果。

### What did you expect to see? / 期望的结果
开启全局模式的情况下，可以设置部分网站不走代理，直连。

### What did you see instead? / 实际结果
实际上，我的需求是这样的，我在HOSTS文件里面配置了
120.26.111.111 wiki.xxxx.com
这样的，我想开启全局模式后 我访问120.26.111.111 或者wiki.xxxx.com这个地址的时候能够不走代理就好了。如果需要每次在IE浏览器局域网设置里面添加这两个地址的话好像太麻烦了点。麻烦请告知。

**Comment by DreamXiao** [comment]
![tim 20180518164324](https://user-images.githubusercontent.com/4948854/40225191-f54774c2-5aba-11e8-92fd-0cebe79d6cc6.jpg)
![tim 20180518164331](https://user-images.githubusercontent.com/4948854/40225192-f57cd680-5aba-11e8-8a05-39bc0cbc3c41.jpg)

**Comment by chenshaoju** [comment]
user-wininet.json 的目的是在设置代理前，将用户的代理设置保存下来，退出SS后还原。

这种情况，需要使用例外符号，请在 user-rule.txt 增加一行：
```
@@||wiki.xxx.com
```
也可能是：
```
@@||wiki.xxx.com^
```
具体请参阅： https://adblockplus.org/filter-cheatsheet#exceptions

**Comment by DreamXiao** [comment]
@chenshaoju 你好，我在user-rule里面设置了。而且pac里面也看到设置的记录了，但是不生效。
![tim 20180518180615](https://user-images.githubusercontent.com/4948854/40229411-bfd2cc2c-5ac6-11e8-8871-3c04ccf462f0.jpg)
![tim 20180518180629](https://user-images.githubusercontent.com/4948854/40229421-c5a4d85c-5ac6-11e8-9f47-25fd3ae194b8.jpg)

**Comment by DreamXiao** [comment]
![tim 20180518182947](https://user-images.githubusercontent.com/4948854/40230318-ada598d8-5ac9-11e8-996a-e5e0664c7a45.jpg)
打开是这样显示的

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/40235627-706cf56a-5add-11e8-9f35-a9c587ad0d8f.png)

以“让 *.google.com.hk ”不经过代理为例，设置为：
![image](https://user-images.githubusercontent.com/515763/40235678-9192ed58-5add-11e8-9ece-8ca7b6ad33fe.png)

**Comment by DreamXiao** [comment]
还是不行。我不知道是不是我改了hosts的原因。
直接用ip+端口号访问没问题。域名+端口号访问就500

**Comment by chenshaoju** [comment]
搜了一下，你这个需求可能无解，PAC和Hosts好象是冲突的。

但是，有一个第三方的 Web 调试工具可以提供办法，该方法未经测试，仅供参考：

https://superuser.com/questions/91837/using-proxy-server-to-act-as-hosts-file
