### ISSUE TITLE
能否加入socks5服务器的支持

### ISSUE THREAD

**Issue by dosgo** [shadowsocks/shadowsocks-windows#1858]
1.主要是用于通过国内vps给ss加速，路径：本地白名单->socks5->国内vps->ss->国外vps。
2.如果你太忙，我可以自己实现。
3.如果我开发完成了，我希望你能帮我合并到主版本里面，我不想维护一个单独的版本。谢谢

**Comment by chenshaoju** [comment]
```国内vps->ss->国外vps``` 这一节 https://github.com/shadowsocks/shadowsocks-libev 已经实现了，叫 ss-redir 。

**Comment by dosgo** [comment]
我现在是要本地sock5到国内vps的。。。

**Comment by dosgo** [comment]
国内vps->ss->国外vps直接用sslocal就行了。。。然后把sock5端口开放出来不就行了

**Comment by chenshaoju** [comment]
对，但是顺带一提， socks5 是明文的，国内的大部分机房有监控过滤系统，知道你在干啥。

**Comment by dosgo** [comment]
机房有监控没关系，国内不会有GFW过滤。。你的意思是我在国内的vps搭个ss，然后转发到国外vps的ss？

**Comment by dosgo** [comment]
算了，不折腾了，直接用nginx 端口转发
