### ISSUE TITLE
求助，手机端可以实现科学上网，电脑端却不行

### ISSUE THREAD

**Issue by aaronwu0122** [shadowsocks/shadowsocks-windows#1860]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
Shadowsocks 4.0.10

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows 8.1  NET Framework 4.7

### Steps you have tried / 操作步骤
搬瓦工服务器搭建，账号在iphone上可以正常翻墙，在windows却无法访问被墙网站，Chrome显示ERR_CONNECTION_TIMED_OUT

### What did you expect to see? / 期望的结果
能够在PC端科学上网

### What did you see instead? / 实际结果
手机端可以翻墙，电脑端不行

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2018-05-21 09:28:28] Shadowsocks started
[2018-05-21 09:28:28] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================
```

**Comment by chenshaoju** [comment]
请右击托盘区的纸飞机图标，确保选中了“启用系统代理”，如果仍然不行，请再次右击纸飞机图标，选择 PAC ，并点击“从GFWList更新本地PAC”选项。

**Comment by MoonJustry** [comment]
同楼上，最新版本SS-windows，偶尔出现pc端google超时（持续时间较长，全局或者pac都不行），但是同一时间安卓是可以google的，相同的pc内网环境，同事的SS pc没任何问题。

**Comment by chenshaoju** [comment]
出现问题的时候，日志中有什么显示吗？

**Comment by MoonJustry** [comment]
没有什么异常显示，就是显示去连接，然后卡在那了。今天如果出现我就贴个图上来

**Comment by chenshaoju** [comment]
这个难以看出任何问题，如果你有Firefox，指定浏览器代理能否试用？请参考下图：

![image](https://user-images.githubusercontent.com/515763/37390878-680ff942-27a4-11e8-81f1-54edfe7658d9.png)

**Comment by chenshaoju** [comment]
你的服务器是自己搭的吗？

如果是，能否加一个Simple-obfs看看？有一个类似的报告，加上Simple-obfs后正常了：
https://github.com/shadowsocks/shadowsocks-windows/issues/1787#issuecomment-377845563

Simple-obfs： https://github.com/shadowsocks/simple-obfs

**Comment by MoonJustry** [comment]
@chenshaoju 加了Simple-obfs，目前pc没有问题，但是安卓连不上了，服务器ss端口或者Simple-obfs配置的端口都不行，需要做什么配置么

**Comment by chenshaoju** [comment]
https://play.google.com/store/apps/details?id=com.github.shadowsocks.plugin.obfs_local&hl=en_US

**Comment by MoonJustry** [comment]
😂pc 又挂了，谷歌连接关闭。。。停掉obfs 手机正常。。难道我真的被盯上了？？我只是个coder查查资料而已啊😂

**Comment by chenshaoju** [comment]
不知道了。。。你这个情况非常奇怪，但是感觉系统问题的可能性很高。。。
你同事的电脑和你的电脑在同一个局域网把？如果是，几乎可以肯定是系统问题，但是无法确认到底是什么问题。。。

**Comment by MoonJustry** [comment]
最近服务器换成了libev+obfs，上面的问题依然存在，使用我的账号在其他同事的pc上也无法登录，但是外网pc、手机都没问题。讲道理公司也没必要对我一个人的服务器ip做限制吧。。。不懂了

**Comment by celeron533** [comment]
>讲道理公司也没必要对我一个人的服务器ip做限制吧

有必要。有时候加密流量大量往来，公司审计网关会根据策略自动屏蔽

**Comment by MoonJustry** [comment]
刚刚问了网管，公司网络没有限制。
server出现的error，但是好像不影响使用

2018-06-08 01:48:16 ERROR: failed to handshake with 127.0.0.1: authentication error
 2018-06-08 01:48:16 [simple-obfs] ERROR: remote recv: Connection reset by peer
 2018-06-08 01:48:16 ERROR: failed to handshake with 127.0.0.1: authentication error
 2018-06-08 01:48:16 [simple-obfs] ERROR: remote recv: Connection reset by peer
 2018-06-08 01:48:37 ERROR: failed to handshake with 127.0.0.1: authentication error
 2018-06-08 01:48:37 [simple-obfs] ERROR: remote recv: Connection reset by peer
 2018-06-08 01:48:38 ERROR: failed to handshake with 127.0.0.1: authentication error
