### ISSUE TITLE
4.0.10搭配SwitchyOmega使用在未勾选启用系统代理的情下无法上传文件。

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-windows#1861]
4.0.9无此问题。

**Comment by chenshaoju** [comment]
你好，我测试了一下并没有问题。

请检查你的SwitchyOmega是否代理了你所使用的网站的上传路径或域名。

![image](https://user-images.githubusercontent.com/515763/40289696-72afcfa8-5cec-11e8-8217-12f1d8e91625.png)
