### ISSUE TITLE
win10 Shadowsocks开全局代理 之后打开chrome 系统大概率蓝屏

### ISSUE THREAD

**Issue by gaoyucindy** [shadowsocks/shadowsocks-windows#1862]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.9

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows10 NET Framework 4.6

### Steps you have tried / 操作步骤
1.打开 Shadowsocks  
2.打开全局代理
3.打开chrome
等待一会 系统大概率蓝屏

第3步换成打开 微软的Edge不会出现蓝屏

### What did you expect to see? / 期望的结果
修复问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by gaoyucindy** [comment]
chrome关闭了硬件加速还是一样过了一会蓝屏

**Comment by chenshaoju** [comment]
我在我的Windows 10 1803 上测试了30分钟，暂时没发现问题。

蓝屏的话，会生成一个 Dump 文件，位于 C:\Windows\Minidump\ 目录中，请挑一个最新生成的，打包，上传上来看看。

![2018-05-23 1](https://user-images.githubusercontent.com/515763/40428267-75e6e46c-5ed2-11e8-9785-b23b4782e33f.jpg)

**Comment by gaoyucindy** [comment]
https://github.com/gaoyucindy/test/blob/master/052718-8984-01.dmp
文件麻烦看下
