### ISSUE TITLE
Shadowsocks not working after sleep

### ISSUE THREAD

**Issue by shinohara-rin** [shadowsocks/shadowsocks-windows#1863]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.10 Release

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows 10

### Steps you have tried / 操作步骤
1. Sleep your pc
2. Wake up

### What did you expect to see? / 期望的结果
see below

### What did you see instead? / 实际结果
Http proxy is not listening as expected
Restarting shadowsocks didn't solve the problem, but a reboot did.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

```
[2018-05-23 18:25:21] Shadowsocks started
[2018-05-23 18:25:22] 
=========================
Registered Encryptor Info
...
...
=========================

[2018-05-23 18:26:07] controller stopped
[2018-05-23 18:26:07] os suspend
[2018-05-23 18:26:18] controller stopped
[2018-05-23 18:26:18] os suspend
```
===config===
```
listen-address 127.0.0.1:61648
toggle 0
logfile ss_privoxy.log
show-on-task-bar 0
activity-animation 0
forward-socks5 / 127.0.0.1:411 .
hide-console
```

**Comment by shinohara-rin** [comment]
logging out solved it too.

**Comment by chenshaoju** [comment]
I tested on my Windows 10 1803, Everything is fine. I guess this may case by Winsock or TCP/IP stack.
Please start cmd or PowerShell in Administrator, And run these command:
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
After running 3 commands, reboot computer, and test again.

**Comment by celeron533** [comment]
Normally the log file should have `os wake up` status to trigger shadowsocks reapply the configs:
```
[2018-06-01 13:39:28] controller started
[2018-06-01 18:45:02] controller stopped
[2018-06-01 18:45:02] os suspend
[2018-06-04 09:13:09] os wake up
[2018-06-04 09:13:19] Shadowsocks started
```
