### ISSUE TITLE
求救, 電腦端無法連上網, 伺服器端沒問題

### ISSUE THREAD

**Issue by eason1234567** [shadowsocks/shadowsocks-windows#1864]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
Shadowsocks-4.0.10

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）

Winsows10

### Steps you have tried / 操作步骤
電腦端使用時出現錯誤,   伺服器端沒問題, 

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

![image 922](https://user-images.githubusercontent.com/39612002/40527107-80ac71fa-5fb8-11e8-80ca-79a91a6e8992.jpg)

**Comment by chenshaoju** [comment]
请确保安装了 Microsoft Visual C++ 2015 Redistributable (x86) https://www.microsoft.com/en-us/download/details.aspx?id=53840

下载时请选择３２位元版本。
