### ISSUE TITLE
Win10 可以无法使用

### ISSUE THREAD

**Issue by Black-di** [shadowsocks/shadowsocks-windows#1865]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
Shadowsocks-4.0.10

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10：1709
.NET Framework：4.5

### Steps you have tried / 操作步骤
1.配置
2.开启服务
3.开启全局模式

### What did you expect to see? / 期望的结果
可以科学上网

### What did you see instead? / 实际结果
无法上网

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[shadowsocks.log](https://github.com/shadowsocks/shadowsocks-windows/files/2038712/shadowsocks.log)

**Comment by chenshaoju** [comment]
日志中看不出任何问题，唯一的一行：
```[2018-05-25 16:55:55] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。```

意味着到你的服务器的连接被重置。

你有其他的设备吗？比如手机或另一台计算机，相同的配置在其他设备上能使用吗？

**Comment by Black-di** [comment]
HI chenshaoju

多谢帮助，找了一天的资料，都没有效果，最后把程序由D盘挪到C盘就好用了。。。。

**Comment by chenshaoju** [comment]
Hmmmm.... OK
