### ISSUE TITLE
希望模式选择里有SSR那种"直连模式"

### ISSUE THREAD

**Issue by cocody** [shadowsocks/shadowsocks-windows#1866]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
在用SSR时, 开发步骤是 浏览器(代理) -> whistle ->(代理到SSR sock 127.0.0.1:1080) -> SSR选择直连模式
这样就能在调试程序时, 也能够访问google

但在用SS时, 由于没有直连模式则采用PAC模式, 同样采用上述方式连接发生了问题. 调试程序与浏览google只能二选一, 不知道发生了什么问题导致的.

### What did you expect to see? / 期望的结果
调试本地 Node.js 的程序 localhost:6574 与 浏览google 能够同时进行

### What did you see instead? / 实际结果
无法同时共存, 只能设定SS的开启关闭快捷键

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
对于这种情况，暂时的方案是停用系统代理，并针对你的浏览器使用第三方代理插件，比如Chrome的SwitchOmega： https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif

SwitchOmega可以提供更加灵活的扩展，也可以导入GFWList。

**Comment by iammsf** [comment]
既生瑜何生亮。
直接取消啟用系統代理就好了，何必多一個直連模式出來

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/40954917-83bcdeca-68b9-11e8-86ca-456c3733736c.png)

想要直连的时候，停用系统代理

或者如@chenshaoju 所言，在浏览器上安装第三方代理控制插件
