### ISSUE TITLE
近期無法使用pac模式代理

### ISSUE THREAD

**Issue by iammsf** [shadowsocks/shadowsocks-windows#1867]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.10

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Win10 1803 64位 .net 4.6.2

### Steps you have tried / 操作步骤
使用pac模式

### What did you expect to see? / 期望的结果
代理特定網址，繞行大多數網址

### What did you see instead? / 实际结果
PAC模式無法代理上網，沒有進出站數據通過SS客戶端，日誌未提供任何信息。切換全局模式代理正常，但無法繞行

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2018-05-26 05:56:40] Shadowsocks started
[2018-05-26 05:56:40] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================
```

**Comment by chenshaoju** [comment]
你是否有使用Chrome浏览器？如果是，请在Chrome的浏览器地址栏中输入：
``` chrome://net-internals/#proxy ```
请问显示什么？如果可能，请截图发上来。

**Comment by littleyuan** [comment]
我的也是无法使用了，输入你的网址出现的是这个：
Effective proxy settings
PAC script: data:application/x-ns-proxy-autoconfig;base64,dmFyIHByb3h5UHJvdG9jb2wgPSAiU09DS1M1IjsKdmFyIHByb3h5U2VydmVyID0gIjE1MC45NS4xNzYuMTA2OjE3NzciOwovL3ZhciBwcm94eVNlcnZlciA9ICI2Ny4yMTYuMjA0LjEwOjE3NzciOwoKdmFyIHByb3h5SG9zdHMgPSBbCiAgImNsaWVudHMyLmdvb2dsZS5jb20iLAogICJjbGllbnRzMi5nb29nbGV1c2VyY29udGVudC5jb20iCl07CgpmdW5jdGlvbiBGaW5kUHJveHlGb3JVUkwodXJsLCBob3N0KSB7CiAgZm9yICh2YXIgaSA9IDA7IGkgPCBwcm94eUhvc3RzLmxlbmd0aDsgaSsrKSB7CiAgICBpZiAoaG9zdCA9PSBwcm94eUhvc3RzW2ldKSB7CiAgICAgIGFsZXJ0KCItLSBQUk9YWSBSRVE6ICIgKyB1cmwpOwogICAgICByZXR1cm4gcHJveHlQcm90b2NvbCArICIgIiArIHByb3h5U2VydmVyICsgIjsgRElSRUNUIjsKICAgIH0KICB9CiAgcmV0dXJuICJESVJFQ1QiOwp9Cg==

**Comment by iammsf** [comment]
@chenshaoju 
不好意思啊最近沒有用電腦所以一直沒看回復。
在Chrome提供的頁面顯示如下：
Effective proxy settings
Use DIRECT connections.
Source: SYSTEM
Original proxy settings
PAC script: http://127.0.0.1:1080/pac?t=20180529181005478
Source: SYSTEM
也就是說我在pac模式下是直連的嗎？

**Comment by chenshaoju** [comment]
@littleyuan 这意味着你的浏览器代理设置被插件劫持了。如果使用的SS的PAC，那么应该是这样的：
![2018-05-29 2](https://user-images.githubusercontent.com/515763/40653127-c3ebca62-636c-11e8-82c8-febef2bc474c.png)

@iammsf 是的，这意味着你的PAC代理并未被Chrome采用，如果Chrome采用了，会显示如上图所示。

**Comment by iammsf** [comment]
@chenshaoju
先前都是正常的，幾天前突然就這樣了，有什麼解決方案啊

**Comment by chenshaoju** [comment]
@iammsf 你是否使用了浏览器插件？比如SwitchyOmega？有一个类似的报告： https://github.com/FelisCatus/SwitchyOmega/issues/683

**Comment by iammsf** [comment]
@chenshaoju
瀏覽器未安裝任何代理插件
(話說都有SS了還要那些東西幹啥)

**Comment by iammsf** [comment]
@chenshaoju 
感謝提供幫助，已經解決了。是Win10升級到1803後自動取消勾選了代理配置。手動勾選就解決了

**Comment by chenshaoju** [comment]
@iammsf 感谢回报。

**Comment by iammsf** [comment]
@chenshaoju 
哎呦，有點難受。。。
手動勾選LAN代理配置之後，效果等同於打開全局模式。。。我再倒騰倒騰試試

**Comment by Rich1e** [comment]
@iammsf 
我的系统也是win10 1803，Chrome安装了SwitchyOmega，如果打开自动切换模式，页面都打不开；只有将SwitchyOmega改成系统代理，shadowsocks-windows开全局，chrome中才能正常代理；
但事实上我不希望打开shadowsocks-windows全局设置，只打算在chrome中使用代理。研究了一下，还是不知道该怎么配置，如果你有办法，请提供帮助谢谢。

PS：chrome://net-internals/#proxy
SwitchyOmega系统代理：PAC script: http://127.0.0.1:1080/pac?t=20180529181005478
SwitchyOmega自动切换：PAC script: data:application/x-ns-proxy-autoconfig;base64,dmFyIHByb3h5UHJvdG9jb2wgPSAiU09DS1M1IjsKdmFyIHByb3h5U2VydmVyID0gIjE1MC45NS4xNzYuMTA2OjE3NzciOwovL3ZhciBwcm94eVNlcnZlciA9ICI2Ny4yMTYuMjA0LjEwOjE3NzciOwoKdmFyIHByb3h5SG9zdHMgPSBbCiAgImNsaWVudHMyLmdvb2dsZS5jb20iLAogICJjbGllbnRzMi5nb29nbGV1c2VyY29udGVudC5jb20iCl07CgpmdW5jdGlvbiBGaW5kUHJveHlGb3JVUkwodXJsLCBob3N0KSB7CiAgZm9yICh2YXIgaSA9IDA7IGkgPCBwcm94eUhvc3RzLmxlbmd0aDsgaSsrKSB7CiAgICBpZiAoaG9zdCA9PSBwcm94eUhvc3RzW2ldKSB7CiAgICAgIGFsZXJ0KCItLSBQUk9YWSBSRVE6ICIgKyB1cmwpOwogICAgICByZXR1cm4gcHJveHlQcm90b2NvbCArICIgIiArIHByb3h5U2VydmVyICsgIjsgRElSRUNUIjsKICAgIH0KICB9CiAgcmV0dXJuICJESVJFQ1QiOwp9Cg==

**Comment by chenshaoju** [comment]
@Rich1e @littleyuan 
有意思的是，你们两个人自动切换下的PAC代理经过解码后是这样的：
```
var proxyProtocol = "SOCKS5";
var proxyServer = "150.95.176.106:1777";
//var proxyServer = "67.216.204.10:1777";

var proxyHosts = [
  "clients2.google.com",
  "clients2.googleusercontent.com"
];

function FindProxyForURL(url, host) {
  for (var i = 0; i < proxyHosts.length; i++) {
    if (host == proxyHosts[i]) {
      alert("-- PROXY REQ: " + url);
      return proxyProtocol + " " + proxyServer + "; DIRECT";
    }
  }
  return "DIRECT";
}
```

这很明显你们的浏览器并没有遵守代理设置，或者由于你们配置了一个错误的PAC列表或者代理，导致无法正常使用。

这个 ``` 150.95.176.106:1777 ``` 很明显是一个公开的代理服务器，而不是你本机的SS代理。

你们是不是使用了什么一件翻墙包之类的应用？

**Comment by harris2015** [comment]
我的 chrome://net-internals/#proxy 执行结果 跟chenshaoju的一样  但还是不能用pac文件模式  下载的最新的版本  win7x64系统
