### ISSUE TITLE
make Shadowsocks SSR compatible

### ISSUE THREAD

**Issue by venusbahar** [shadowsocks/shadowsocks-windows#1868]
Hello.
Please make [Shadowsocks](https://github.com/shadowsocks/shadowsocks-windows/releases) compatible with SSR protocol.
I mean that [ShadowsocksR](https://github.com/shadowsocksrr/shadowsocksr-csharp/releases) for windows (v4.9.0) is not as perfect as Shadowsocks!
Also, ShadowsocksR for windows has been not updated since last year.
Thanks.

**Comment by studentmain** [comment]
Use shadowsocksRR instead of shadowsocksR.

Alireza Farvardin <notifications@github.com> 于 2018年5月27日周日 03:57写道：

**Comment by venusbahar** [comment]
Thanks for answer.
I did not found any download link for **ShadowsocksRR**.
Can you please give me download page for it?

**Comment by chenshaoju** [comment]
ShadowsocksRR: https://github.com/shadowsocksrr/shadowsocksr-csharp/releases

And there is a client name electron-ssr, You can try it too: https://github.com/erguotou520/electron-ssr/releases

Please Attention: ShadowsocksRR and electron-ssr is not part of Shadowsocks for now.
