### ISSUE TITLE
之前下了老版本的shadows，现在有重新下载了，导致运行不了这个程序

### ISSUE THREAD

**Issue by mushangui** [shadowsocks/shadowsocks-windows#1871]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请问“运行不了”有什么提示吗？能否截个图？

**Comment by mushangui** [comment]
谢谢，已经解决了，用的是已管理员身份运行
