### ISSUE TITLE
为什么安卓客户端都有绕过局域网和中国大陆，PC端却没有。。

### ISSUE THREAD

**Issue by Rem1x-2019** [shadowsocks/shadowsocks-windows#1873]
这个功能非常好用，国外的所有网站都走代理，速度会比不开代理打开快，STEAM也可以快速打开，

但是为什么PC端没有这个功能，

我也看过ss-libev支持ACL规则，尝试启用过，可是没有效果(可能姿势不对，如果有大佬会用，请告知）

为什么PC端不加个绕过局域网和中国大陆地址，如果有其他办法，请告诉我，谢谢。

中国的IP地址库可以在这里找到
http://www.ipdeny.com/ipblocks/data/aggregated/cn-aggregated.zone
经常更新的，

**Comment by pongfcnkl** [comment]
pc有pac

**Comment by 17301008** [comment]
朋友，我说的是白名单，不是黑名单，PAC是GFWLIST，黑名单，，我的意思是，除了大陆，其他全走代理，懂我意思了吗？

**Comment by thelastlin** [comment]
欢迎贡献代码。

**Comment by stu4355226** [comment]
On Sat, Jun 9, 2018 at 11:58 AM 17301008 <notifications@github.com> wrote:
the

**Comment by celeron533** [comment]
> 朋友，我说的是白名单，不是黑名单，PAC是GFWLIST，黑名单，，我的意思是，除了大陆，其他全走代理，懂我意思了吗？

@17301008 所以你可以不使用gfwlist，自己找一份白名单来作为PAC使用。GFWLIST的维护并不在本项目范围内，最初内嵌GFWlist只是为了方便用户

**Comment by 17301008** [comment]
@celeron533  我记得不是有ACL功能，但是我开启了没效果，不知道是不是我姿势不对，
用的是下面这个ACL的语法，但是无论大陆还是国外都打不开。IP地址我也更新了，
https://github.com/shadowsocks/shadowsocks-libev/blob/master/acl/chn.acl

**Comment by aglent** [comment]
新版的firefox 代理扩展都不能使用pac，要么全局代理，要么系统代理（gfwlist分流），没法自由地在gfwlist和ip分流之间切换。 （chrome的代理扩展就没有这个限制）
所以 如果SS客户端能支持gfwlist和绕过大陆ip方式两种pac 最好不过了

**Comment by celeron533** [comment]
>我记得不是有ACL功能

ss-win目前没有这个功能。。。

**Comment by celeron533** [comment]
> 新版的firefox 代理扩展都不能使用pac

https://support.mozilla.org/en-US/questions/1175165

**Comment by aglent** [comment]
@celeron533 
我试了试 
Firefox 61 设置（Network Proxy）是可以使用pac文件的 但只能使用一种pac
SwitchyOmega扩展不能直接使用pac 所以我在Firefox设置中使用了pac代理，这时扩展里的direct和system proxy调用的是FF设置里的代理。自动忽略了Shadowsock开启的系统代理。
如果Firefox不设置代理，并开启Shadowsock的系统代理，这时direct就是直连，system proxy调用的是shadowsock的系统代理。
所以我没法在SwitchyOmega扩展里随时切换黑名单和IP分流两种场景，好像其它扩展也做不到。希望shadowsock开启的系统代理中能选择黑名单和IP分流两种pac模式。我记得SSR之前的版本里有这样的功能，不知道shadowsock能否增加这个功能？

**Comment by Immueggpain** [comment]
我有遇到socks代理根本不支持pac。。。所以自己写了个智能选路，不过是java的

**Comment by iBug** [comment]
我刚从楼主提供的那个 `ipdeny.com` 的列表里生成了一个 PAC 文件：https://github.com/iBug/pac/blob/master/bypass-lan-and-china.pac

这个 repo 已经包含了生成该文件所需的代码 (Python)，可以自己更新 PAC，我也会不定时更新这些代码。

目前我自己的 SS 客户端就在用 repo 里的 PAC 文件。

**Comment by 17301008** [comment]
@iBug 那么应该怎么使用这个PAC，我服务端是shadowsocks-libev，不太会设置，。。
电脑端没有使用PAC的地方。。。

**Comment by iBug** [comment]
@17301008 电脑端？右键纸飞机，在 PAC 一栏里有个 “编辑本地 PAC” 的选项。打开 `pac.txt` 清空原来的内容，然后把我写的那个 PAC 全部粘贴进去就可以了。

<https://github.com/shadowsocks/shadowsocks-windows/releases>

**Comment by 17301008** [comment]
@iBug 非常感谢，测试已经成功，ip111.cn测试也正常，有没有手机端的，因为手机端的经常不正常，淘宝走的国外DNS，所以连接的国外的CDN节点，速度很慢，还有好多软件也是这样.....

**Comment by 17301008** [comment]
@iBug 经过进一步测试，tumber进不去，然后facebook显示不正常，不知道为什么，google正常，youtube正常，其他的没有墙的网站也正常，不知道你那边是不是也这样。你可以试试，
![1](https://user-images.githubusercontent.com/38907613/44730330-4549e880-ab13-11e8-8df1-f2cf5157f9ea.jpg)
![2](https://user-images.githubusercontent.com/38907613/44730331-45e27f00-ab13-11e8-889b-c707e5dfc87a.jpg)

**Comment by iBug** [comment]
@17301008 我的没有任何问题，DNS没有用国外的，纸飞机服务器在AWS的美国节点，你所说的几个网站都能正常打开。另外 Tumber 不是个网站，应该是 Tumblr

**Comment by iBug** [comment]
@17301008 手机端可以考虑在 Custom Rule (我系统语言是英文)里直接把上面那个网址的子网列表加进去，再加上内网的IP段 (`192.168.0.0/16`这样) 就可以了

**Comment by tsingbinjung** [comment]
> 我刚从楼主提供的那个 `ipdeny.com` 的列表里生成了一个 PAC 文件：https://github.com/iBug/pac/blob/master/bypass-lan-and-china.pac
> 
> 这个 repo 已经包含了生成该文件所需的代码 (Python 代码和一个 `build.sh`)，可以自己生成 PAC，我也会不定时更新这些代码。
> 
> 目前我自己的 SS 客户端就在用 repo 里的 PAC 文件。希望能帮助到大家。欢迎 Star!
> 
> I just created a PAC file from the China IP address list on `ipdeny.com` provided by the OP: https://github.com/iBug/pac/blob/master/bypass-lan-and-china.pac
> 
> Code used to create that PAC is included in the repository, some Python code and a simple build script. Anyone can generate the PAC with those code, which I'll periodically take a look and update.
> 
> The PAC file in the repository is deployed to my Shadowsocks clients. Welcome to star my repo.

很好用呀

**Comment by carlray1988** [comment]
> 我刚从楼主提供的那个`ipdeny.com`的列表里生成了一个PAC文件：[https](https://github.com/iBug/pac/blob/master/bypass-lan-and-china.pac)：[//github.com/iBug/pac/blob/master/bypass-lan-and-china.pac](https://github.com/iBug/pac/blob/master/bypass-lan-and-china.pac)
> 
> 这个repo已经包含了生成该文件所需的代码（Python代码和一个`build.sh`），可以自己生成PAC，我也会不定时更新这些代码。
> 
> 目前我自己的SS客户端就在用repo里的PAC文件。希望能帮助到大家。欢迎Star！
> 
> 我刚刚从`ipdeny.com`OP提供的中国IP地址列表中创建了一个PAC文件：[https](https://github.com/iBug/pac/blob/master/bypass-lan-and-china.pac)：[//github.com/iBug/pac/blob/master/bypass-lan-and-china.pac](https://github.com/iBug/pac/blob/master/bypass-lan-and-china.pac)
> 
> 用于创建该PAC的代码包含在存储库中，一些Python代码和一个简单的构建脚本。任何人都可以使用这些代码生成PAC，我会定期查看并更新。
> 
> 存储库中的PAC文件部署到我的Shadowsocks客户端。欢迎主演我的回购。

人才啊,感谢,这样是最好的,手机端早就有这个功能了,绕过局域网和中国地址,外国地址全部代理

**Comment by oneWalker** [comment]
非大陆和局域网走代理其实真的非常好，因为有的可能是白名单 但是你发现他是黑名单 比如xampp的网址
