### ISSUE TITLE
关于 shadowsocks-windows 的系统代理exception hosts的设置

### ISSUE THREAD

**Issue by xjasonlyu** [shadowsocks/shadowsocks-windows#1877]
#### shadowsocks-windows 客户端的系统代理设置里

- 如果每次手动修改系统代理设置里的 exception hosts（例外），那么下次启动客户端的时候那些 例外 又会被重新覆盖。

- 如果修改客户端目录下的 user-wininet.json 的 BypassList， 重启客户端这个文件又被重新还原了。

所以这个要怎么设置呢？貌似文档里没有看到相关的设置方法。

**Comment by chenshaoju** [comment]
user-wininet.json 的作用是记录启动时用户的代理情况，在退出SS时使用 user-wininet.json 恢复。

在某些情况下， user-wininet.json 可能会导致配置混乱，请尝试执行以下操作：

１.退出 SS ，进入 Shadowsocks.exe 所在的目录，找到 user-wininet.json ，删除或者重命名。
２.进入控制面板，打开 Internet 选项，点击连接选项卡，点击局域网设置，点击高级按钮，然后按照你的情况设置例外列表。
３.设置完毕后点击确定，系统可能会出现无效代理服务器的提示，点击是即可。
４.再次启动 Shadowsocks.exe ，此时你的代理例外设置会被保存，即可正常使用。
