### ISSUE TITLE
shadowsocksR显示Starting ShadowsocksR success，查看状态是ShadowsocksR is stopped

### ISSUE THREAD

**Issue by smilepasta** [shadowsocks/shadowsocks-windows#1878]
**启动服务**
```
[root@host /]# /etc/init.d/shadowsocks start
IPv6 support
2018-06-05 12:29:11 INFO     util.py:92 loading libcrypto from libcrypto.so.10
2018-06-05 12:29:11 INFO     shell.py:74 ShadowsocksR 3.4.0 2017-07-27
started
Starting ShadowsocksR success
```

**查看状态**
```
[root@host /]# /etc/init.d/shadowsocks status
ShadowsocksR is stopped
```

反复启动，查看状态，都是stopped，请看一下。

**Comment by chenshaoju** [comment]
你好，ShadowsocksR和Shadowsocks是两个东西，而且你这个好象是Linux的，这儿是Windows的Issue列表。

**Comment by smilepasta** [comment]
你好，我用的是windows-client，使用android-client可以代理上网，使用windows-client不能上网，日志中也没有错误提示。使用的版本是4.0.10。

**Comment by chenshaoju** [comment]
ShadowsocksR是单向兼容Shadowsocks的，如果你坚持要在服务端使用ShadowsocksR，那么服务端必须配置协议为origin，混淆为plain。

从你的提示来看，你的SSR服务端在启动后自行停止了，为了方便分析，请执行以下命令（Debian／Ubuntu？）：
``` journalctl -u shadowsocks.service ```

然后将日志发送上来。

**Comment by smilepasta** [comment]
你好，我再补充一下，我使用Chrome插件SwitchyOmega可以访问google.

**Comment by chenshaoju** [comment]
请尝试确保启动了系统代理，并且工作在PAC模式。

如果仍然不行，请右击任务栏托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。

**Comment by smilepasta** [comment]
谢谢你的帮助，正是因为我没有启动系统代理，所以才导致的这个情况。
