### ISSUE TITLE
希望能添加黑白名单功能，强制某些域名或者ip走代理或者不走

### ISSUE THREAD

**Issue by EndOfMaster** [shadowsocks/shadowsocks-windows#1879]
如题

**Comment by chenshaoju** [comment]
你好，如果你是用的是Shadowsocks自带的PAC模式＋GFWList，你可以通过右击任务栏托盘区的纸飞机图标，选择PAC，再点击“编辑 GFWList 的用户PAC规则“。

然后，在出现的记事本窗口中新起一行，输入你想要经过或者绕过的域名，格式为：

经过代理：```||example.com```
绕过代理：```@@||example.com```

即可，请记得将 ```example.com``` 替换成你想要经过或者绕过的域名。

具体请参照：https://adblockplus.org/filter-cheatsheet

**Comment by EndOfMaster** [comment]
额。。写了没用啊。。我刚刚写了个战网亚服的就绕不过去。。还是给我跳回去国服了。。我开全局就行。。

**Comment by chenshaoju** [comment]
请问你是怎么写的？如果可能，请截个图发上来看看。
你用的是什么浏览器？Chrome？
如果是Chrome，在Shadowsocks.exe工作于PAC模式的情况下，在Chrome的地址栏中输入：``` chrome://net-internals#proxy ``` 显示的是什么？

**Comment by EndOfMaster** [comment]
主要是其他的没什么问题。。比如google啊。。什么的。。

**Comment by EndOfMaster** [comment]
进去以后点商店

**Comment by chenshaoju** [comment]
经测试，暴雪商店使用的实际上是 https://eu.shop.battle.net/en-us 的域名（基于英国服务器的测试结果），因此，你需要将 battle.net 加入你的 user-rult.txt 。

![image](https://user-images.githubusercontent.com/515763/41272962-0bb97b40-6e4a-11e8-8829-3ea0f2286869.png)

**Comment by EndOfMaster** [comment]
完美解决。。谢谢。。其实这是个使用的问题。。。
