### ISSUE TITLE
shadowsocks-windows UDP问题

### ISSUE THREAD

**Issue by Bluemiaocat** [shadowsocks/shadowsocks-windows#1881]
使用SuperSocks5Cap搭配shadowsocks-windows版本是4.0.10，测试NAT类型（所有开启UDP转发的节点），得到的结果是UdpBlocked，而使用shadowsocksR版本是4.7（使用同样节点）得到的结果是PortRestrictedCone
![snipaste_2018-06-10_16-52-59](https://user-images.githubusercontent.com/36540279/41199980-bfe731d4-6cce-11e8-85b2-d4de93874094.png)
![photo_2018-06-10_16-42-17](https://user-images.githubusercontent.com/36540279/41199981-c4680e0e-6cce-11e8-91b7-b4413bacfbb0.jpg)
@celeron533 @madeye

**Comment by xyj1999** [comment]
我有经过游戏（GTA5）测试，NAT类型是UDP被屏蔽，并不能正常游戏，使用SSR客户端来使用SS则一切正常

**Comment by chenshaoju** [comment]
感谢报告，测试了一下，的确有问题，服务器端开启UDP支持的情况下，客户端不会发送UDP请求到服务器，感觉SS客户端什么地方有问题。

如果你用于游戏，个人建议使用SSTap： https://www.sockscap64.com/zh-hans/sstap/

请注意：SSTap不是 Shadowsocks for Windows 的一部分。

**Comment by xyj1999** [comment]
@chenshaoju 使用SSTap会导致游戏的nat类型是nat3，根本没办法游戏，所以希望能尽快修复这个BUG

**Comment by 17301008** [comment]
我直接安装anyconnect上游戏，完全没问题，SS的UDP支持还是不太好，

**Comment by celeron533** [comment]
了解了， @xyi1999
服务端用的是libev还是python？

**Comment by xyj1999** [comment]
@celeron533 服务端用的是libev

**Comment by celeron533** [comment]
Hi @wongsyrone , I noticed in `UDPRelay.cs`:
```
            public void Send(byte[] data, int length)
            {
                IEncryptor encryptor = EncryptorFactory.GetEncryptor(_server.method, _server.password);
                byte[] dataIn = new byte[length - 3];
                Array.Copy(data, 3, dataIn, 0, length - 3);
                byte[] dataOut = new byte[65536];  // enough space for AEAD ciphers
                int outlen;
                encryptor.EncryptUDP(dataIn, length - 3, dataOut, out outlen);
                Logging.Debug(_localEndPoint, _remoteEndPoint, outlen, "UDP Relay");
                _remote?.SendTo(dataOut, outlen, SocketFlags.None, _remoteEndPoint);
            }
```
But I am not sure why there is a 3 byte offset?

**Comment by wongsyrone** [comment]
忽略两字节rsv和一字节frag

**Comment by celeron533** [comment]
>忽略两字节rsv和一字节frag

Thx
```
# SOCKS5 UDP Request
# +----+------+------+----------+----------+----------+
# |RSV | FRAG | ATYP | DST.ADDR | DST.PORT |   DATA   |
# +----+------+------+----------+----------+----------+
# | 2  |  1   |  1   | Variable |    2     | Variable |
# +----+------+------+----------+----------+----------+

# SOCKS5 UDP Response
# +----+------+------+----------+----------+----------+
# |RSV | FRAG | ATYP | DST.ADDR | DST.PORT |   DATA   |
# +----+------+------+----------+----------+----------+
# | 2  |  1   |  1   | Variable |    2     | Variable |
# +----+------+------+----------+----------+----------+

# shadowsocks UDP Request (before encrypted)
# +------+----------+----------+----------+
# | ATYP | DST.ADDR | DST.PORT |   DATA   |
# +------+----------+----------+----------+
# |  1   | Variable |    2     | Variable |
# +------+----------+----------+----------+

# shadowsocks UDP Response (before encrypted)
# +------+----------+----------+----------+
# | ATYP | DST.ADDR | DST.PORT |   DATA   |
# +------+----------+----------+----------+
# |  1   | Variable |    2     | Variable |
# +------+----------+----------+----------+

# shadowsocks UDP Request and Response (after encrypted)
# +-------+--------------+
# |   IV  |    PAYLOAD   |
# +-------+--------------+
# | Fixed |   Variable   |
# +-------+--------------+
```

**Comment by xyj1999** [comment]
@celeron533 不好意思再次打扰，这个问题有望在下个版本解决吗？也非常感谢你们能抽空开发shadowsocks，让我们这些小白能愉快的墙外冲浪

**Comment by celeron533** [comment]
@xyj1999 最近一直在外出。。。抱歉

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1106#issuecomment-292711020 不知道GTA是不是带了FRAG?

**Comment by xyj1999** [comment]
GTA带不带FRAG这个要怎么进行测试？现在表示看91的时候视频也不能正常加载，，，，

**Comment by xyj1999** [comment]
91的是我自身设置问题，不好意思

**Comment by xyj1999** [comment]
@celeron533 很感谢更新，但是问题还是依旧，我这个问题不是一个BUG吗？

**Comment by celeron533** [comment]
现在还不确定，试过ProxyCap和SocksCap吗

**Comment by xyj1999** [comment]
![image](https://user-images.githubusercontent.com/36540279/43686934-154eab22-9900-11e8-8d37-f2e7f7829adc.png)
问题复现~ @celeron533

**Comment by xyj1999** [comment]
![beta](https://user-images.githubusercontent.com/36540279/43686946-3d930b3c-9900-11e8-9cc5-bb38a8946ccb.png)
问题复现~ @celeron533

**Comment by celeron533** [comment]
我这边重现了一样问题。有空看看

**Comment by celeron533** [comment]
加密后的UDP包送去了服务器就没有任何UDP返回。。。很有可能是服务器直接判断加密方法不符，然后就没有然后了

**Comment by Bluemiaocat** [comment]
是的，加密使用的AEAD @celeron533

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/50383253-c6dd0c00-06ea-11e9-868d-8228af5bcefa.png)
@Bluemiaocat sockscap64 自带的测试结果是什么呢

**Comment by Bluemiaocat** [comment]
@celeron533

**Comment by Bluemiaocat** [comment]
@celeron533 
![image](https://user-images.githubusercontent.com/36540279/50383815-fd6c5400-06f5-11e9-9cd1-b02e1b6187ec.png)没有问题

**Comment by superdollar** [comment]
这个问题解决了吗？

**Comment by celeron533** [comment]
@superdollar please try https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/25078158/job/ku65g6pncm2yseud/artifacts

**Comment by superdollar** [comment]
试了一下还不行，目前还不确定是什么问题
topic : openvpn (udp, turned on socks-proxy) over ss

server : shadowsocks-libev 3.1.3 (UDP relay enabled)
client : 4.1.6.8 & 4.1.6.18 (TCP works)
method : aes-256-cfb

client log : Socket connected to ss server : **** : 443
server log : nothing

**Comment by chenshaoju** [comment]
如果你希望使用OpenVPN over SS，你应该考虑使用OpenVPN的TCP模式。

**Comment by superdollar** [comment]
TCP模式是可以工作的，就是怕TCP over TCP的问题想试试能不能UDP over TCP
顺便问一下，如果是ss是UDP relay方式，ss server 和 client 之间因该还是tcp数据流吧？

**Comment by superdollar** [comment]
UDP relay WORKS! so openvpn works in udp over udp mode
* SS server : shadowsocks-libev 3.1.3 (ubuntu 18.04) with UDP relay
* SS client : 4.1.7.1
* openvpn v2.2.3 UDP mode with socks-proxy option

Thanks for fixing udp problem.

**Comment by studentmain** [comment]
#2387, maybe we can close it now?

**Comment by superdollar** [comment]
I personally believe that this ticket can be closed. Thanks.
