### ISSUE TITLE
pc端无法连接服务器

### ISSUE THREAD

**Issue by lhuang001** [shadowsocks/shadowsocks-windows#1882]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
4.0.10

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
windows10 1803
chrome

### Steps you have tried / 操作步骤
打开之后无法连接服务器，但是手机端可以正常连接

### What did you expect to see? / 期望的结果
尝试更换chrome版本，shadowsocks版本均无效

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请先执行该测试：
１.右击开始菜单，点击运行。
２.输入： ``` ping 127.0.0.1 ```，然后回车。
３.能看到回应的时间还是只能看到请求超时？如果无法分辨，请截图发上来。

**Comment by lhuang001** [comment]
显示一般错误
![1](https://user-images.githubusercontent.com/21240907/41203806-bc16e9e2-6d0e-11e8-8839-74a8abe56b11.png)

**Comment by chenshaoju** [comment]
该问题很高的可能性是你的系统损坏导致的，具体请参阅： https://github.com/shadowsocks/shadowsocks-windows/issues/1806

**Comment by lhuang001** [comment]
看了#1806，我的状况和他一样，ss不能使用，chrome打开第一个网页缓慢，并且也是系统突然蓝屏之后才出现问题。百度查询ping 127.0.0.1 一般故障之后发现是windows defender防火墙的原因，关闭防火墙之后可以正常使用了。关闭防火墙的链接：https://www.cnblogs.com/marsggbo/p/8519704.html
打扰了，谢谢您的帮助。
（ps这个报错真的看不懂，希望能改善错误信息，这样也可以减少提交issue）
