### ISSUE TITLE
上传视频至YouTube极慢

### ISSUE THREAD

**Issue by RuikangSun** [shadowsocks/shadowsocks-windows#1883]
使用过bbr了，效果不明显.
看视频、下载什么的速度都可以接受，但上传YouTube视频速度极慢，几KB/s.

**Comment by chenshaoju** [comment]
请在全局模式或者浏览器全局代理的情况下访问 http://www.speedtest.net 测试一下你的速度？

**Comment by thelastlin** [comment]
部分运营商上下行速率不对称，检查一下。

**Comment by linfan68** [comment]
我也遇到这个问题，从昨天晚上开始的。在aws东京的lightsail服务器，之前直连下载2mb/上传2mb，通过ss连下载10mb/上传6mb/ping<100。现在下载5mb/上传接近0kb/ping~300。
换了aws新加坡的节点稍微好一些也没有明显改善，BBR都有，结果都是speedtest链接东京/新加坡的测速点测出来的。

不知道这种性能问题一般怎么诊断？

**Comment by celeron533** [comment]
@linfan68 也是上传youtube缓慢？如果不同地区不同服务器都出现缓慢现象，可能：
1. 国际网关新策略
2. win10的更新
3. Youtube日常维护
4. 光缆故障

**Comment by linfan68** [comment]
昨天琢磨了一晚上，今天早晨居然自己好了……
 PING 87 ms
 DOWNLOAD 89.42 Mbps
 UPLOAD 11.38 Mbps

**Comment by RuikangSun** [comment]
下载2.75Mb/s，上传1.20Mb/s，应该不是网速的问题。
只有上传YouTube非常慢，电脑约50kb/s，手机约200kb/s。其他网站(比如pornhub)的下载都很快。
这是怎么回事呢？

**Comment by chenshaoju** [comment]
无法确定这个问题，猜测和WebCRT有关，你有uBlock Origin吗？有的话，启用这个选项看看？

![image](https://user-images.githubusercontent.com/515763/43261134-42b46f6a-910e-11e8-840a-b5d1925764f4.png)

**Comment by C0DETyper** [comment]
Google搜索："TCP加速 Windows" 可以下载锐速serverspeeder开心版，以前不管什么服务器都是上传卡1.2m，开了这个直接跑满带宽（对全局网络有效，不管你使用什么工具）。下载提高百分之30左右，而且更稳定，上传提高到8倍。之前也是在一个youtube视频看到的https://www.youtube.com/watch?v=NoO_1jToZPI

**Comment by C0DETyper** [comment]
后来了解这种技术叫做TCP单边加速，应该不止锐速一家有，去百度一下就可以查到发布这种软件的公司，比如在linux服务端搭建的 BBR/BBR魔改版/BBRplus/锐速 都属于TCP单边加速，不过是搭建在linux服务端的，而上面所述是直接安装在Windows本机的，没有想到对上传速度有这么大的提升。可惜仅TCP可以这么做，udp加速是不存在单边加速的，比如流行的udpspeeder都是双边加速，所以想搭建游戏加速器靠从机场主买的服务器很难达到很好的效果，必须要自己搭建VPS（因为你要在服务端设置端口) 才能达到比较好的效果

**Comment by C0DETyper** [comment]
这个东西算是拯救了我一个youtuber了，不知道为什么几乎没有人知道。。。问很多机场主也都不知道，，卖游戏加速线路的机场主也不会自己搭建udpspeeder然后给端口来优化游戏线路，，不知道为什么。。。

**Comment by Bill0412** [comment]
拯救了另一个YouTuber
