### ISSUE TITLE
*fbcdn.net 资源加载失败

### ISSUE THREAD

**Issue by galloperleon** [shadowsocks/shadowsocks-windows#1884]
### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）
SSR 4.7.0

### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
Windows 10
.net 4.0

### Steps you have tried / 操作步骤
尝试过以下步骤
1，直接启用全局模式+SwitchOmega（系统代理）
2，启动直连模式+SwitchyOmega( pac或者全局代理模式）

### What did you expect to see? / 期望的结果
访问facebook 

### What did you see instead? / 实际结果
只有一个问题： facebook无法访问。google和其他大部分网站都可以访问。
无法访问原因是*.fbcdn.net 资源加载失败。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
显示问题如附件。

![qq 20180612130250](https://user-images.githubusercontent.com/32817092/41292272-aa0c0b2a-6e84-11e8-8157-d024c9561c7d.png)
![qq 20180612130254](https://user-images.githubusercontent.com/32817092/41292275-ab07a4ee-6e84-11e8-931f-9472919c419a.png)

**Comment by chenshaoju** [comment]
SS和SSR是两个东西。

请尝试在你的服务器上Ping static.xx.fbcdn.net ，能否通？有可能 fbcdn.net 屏蔽了你的服务器IP。

另外，请检查你本机的Hosts文件，如果你使用过某些Hosts修改器，可能会有这个问题。

Hosts文件位于 C:\Windows\system32\drivers\etc\ 目录中。

**Comment by galloperleon** [comment]
嗯，现在的问题是SSR，不是SS。

ping的通。

本机hosts文件没有修改过。还是默认都内容如下：
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost

现在怀疑是不是电信线路都问题。联通的网络测试可以连接上，情况如下：
1）直接SSR全局或者pac模式，访问正常。
2）SSR直连模式+SwitchyOmega（全局模式），会提示*.fbcdn.net 资源加载失败，但是等待网页加载的过程结束后，可以正常访问，提示有一个资源加载失败。

除了fb网站以外，我用电信网络访问国外都网站都会很慢，联通就会快很多。

**Comment by chenshaoju** [comment]
这个很难判断出可能的问题，尝试更换协议、混淆可能有帮助。

**Comment by galloperleon** [comment]
好的 谢谢您的建议。我先尝试一下，可以的话再来更新。

**Comment by galloperleon** [comment]
您好，我刚测试过。修改了一下加密方法，协议，混淆，可以用了。不知道为什么，不过现在是正常使用了。谢谢您的指点。
