### ISSUE TITLE
请问你们现在最新的域名是什么

### ISSUE THREAD

**Issue by DonClaud** [shadowsocks/shadowsocks-windows#1885]
有一段时间没有使用你们的服务，点击之前网址的链接无法进入网站，想重新购买服务

**Comment by chenshaoju** [comment]
你好， Shadowsocks for Windows 不提供也不销售SS服务，如果你在某处购买了自称 Shadowsocks 官方的SS服务，极有可能是假冒的。

目前 Shadowsocks 项目的官方网站是 https://shadowsocks.org 。

**Comment by studentmain** [comment]
#1766

**Comment by chenshaoju** [comment]
是的，被墙了，只是一些介绍性的内容。

这个网站不销售SS服务。
