### ISSUE TITLE
最近又上不去了，三天前还可以，请问该怎么调整？

### ISSUE THREAD

**Issue by yuuka99** [shadowsocks/shadowsocks-windows#1887]
之前是可以上的，大概三天前wifi也上不去，手机也上不去，移动数据也上不去。
部分日志：

> [2018-06-13 21:15:35] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:35] connect to clients1.google.com:443
> [2018-06-13 21:15:35] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:36] hk1-sta17.5xe4q.site:36335 timed out
> [2018-06-13 21:15:36] hk1-sta17.5xe4q.site:36335 timed out
> [2018-06-13 21:15:36] connect to clients1.google.com:443
> [2018-06-13 21:15:36] connect to clients1.google.com:443
> [2018-06-13 21:15:36] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:37] connect to clients1.google.com:443
> [2018-06-13 21:15:37] connect to clients1.google.com:443
> [2018-06-13 21:15:37] connect to clients1.google.com:443
> [2018-06-13 21:15:37] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:37] connect to clients1.google.com:443
> [2018-06-13 21:15:38] connect to clients1.google.com:443
> [2018-06-13 21:15:38] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:38] hk1-sta17.5xe4q.site:36335 timed out
> [2018-06-13 21:15:38] connect to clients1.google.com:443
> [2018-06-13 21:15:38] connect to clients1.google.com:443
> [2018-06-13 21:15:38] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:38] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:39] connect to clients1.google.com:443
> [2018-06-13 21:15:39] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:40] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:40] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:40] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:41] connect to clients1.google.com:443
> [2018-06-13 21:15:41] connect to clients1.google.com:443
> [2018-06-13 21:15:41] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:41] hk1-sta17.5xe4q.site:36335 timed out
> [2018-06-13 21:15:41] connect to clients1.google.com:443
> [2018-06-13 21:15:41] connect to clients1.google.com:443
> [2018-06-13 21:15:42] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:43] connect to clients1.google.com:443
> [2018-06-13 21:15:43] connect to clients1.google.com:443
> [2018-06-13 21:15:43] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:44] connect to clients1.google.com:443
> [2018-06-13 21:15:44] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:44] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:46] hk1-sta17.5xe4q.site:36335 timed out
> [2018-06-13 21:15:46] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:47] connect to clients1.google.com:443
> [2018-06-13 21:15:50] connect to clients1.google.com:443
> [2018-06-13 21:15:50] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:50] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:50] connect to clients1.google.com:443
> [2018-06-13 21:15:50] connect to clients1.google.com:443
> [2018-06-13 21:15:50] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:50] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:52] connect to clients1.google.com:443
> [2018-06-13 21:15:52] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:54] connect to clients1.google.com:443
> [2018-06-13 21:15:56] connect to clients1.google.com:443
> [2018-06-13 21:15:56] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:56] connect to clients1.google.com:443
> [2018-06-13 21:15:56] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:15:59] hk1-sta17.5xe4q.site:36335 timed out
> [2018-06-13 21:15:59] connect to clients1.google.com:443
> [2018-06-13 21:16:00] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:16:26] connect to clients1.google.com:443
> [2018-06-13 21:16:26] Socket connected to ss server: hk1-sta17.5xe4q.site:36335
> [2018-06-13 21:16:27] connect to clients1.google.com:443
> [2018-06-13 21:16:27] Socket connected to ss server: hk1-sta17.5xe4q.site:36335

**Comment by thelastlin** [comment]
**注意：请隐去如服务器地址的关键信息**
试着ping一下服务器？如果ping得通请再次检查配置。若检查配置未发现问题，可能是端口被封，请更换服务器端口。

=============
ping了一下，没有问题。可能是你配置错了；也可能是端口被封，需要换一下。

**Comment by chenshaoju** [comment]
我测试了一下，你的端口是通的，请仔细检查你的端口是否正确（是否是你用的），以及密码、加密方式是否正确。

**Comment by yuuka99** [comment]
@chenshaoju  您好，我之前是在网站充值年费然后获得端口和配置，现在借用别人的vpn搜索了一圈并不知道改怎么更改。之前的年费就作废了？我要自己搭建服务器吗？

**Comment by yuuka99** [comment]
@thelastlin @chenshaoju 感谢帮助，已经解决了。

**Comment by chenshaoju** [comment]
@yuuka99 https://github.com/shadowsocks/shadowsocks-windows/issues/1766
