### ISSUE TITLE
手机可以连上但电脑连不上

### ISSUE THREAD

**Issue by Yuannbo** [shadowsocks/shadowsocks-windows#1889]
我的手机可以连上，但电脑却不行。
我查看了日志，电脑连的时候主要显示以下信息，
```
can not parse header
ERROR    can not parse header when handling connection from XXX.XX.XX.XX
```
后面又会提示` ERROR    invalid hostname: `后面跟一堆乱码 
这个会不会是win7与ubuntu编码不同造成的问题？
请问该怎样解决呢？
还有就是我的手机连接的时候不是很稳定，延迟会在300ms到1000多左右跳动，下载速度也会跳动平均大概200多kb/s。
我用了网上找的一键部署脚本，也开启了bbr加速，请问还有没有啥好办法能提高ss速度的。
（补充一下：刚又看了眼，当我开全局代理的时候任一网页都打不开，所以应该是说电脑是连着ss服务端的）

**Comment by chenshaoju** [comment]
``` can not parse header ``` 这个的意思是无法解析数据包头，可能是由于你所配置的服务器加密方式不一致，或者密码不一致导致的。

``` ERROR invalid hostname: ```，这意味着你输入的服务器域名不正确，无法解析，请尝试Ping你的服务器域名，能否解析出IP或者能否Ping通？

如果全局代理情况下，任何网页都打不开，说明你没有与你的服务器建立连接，因此无法打开任何网站。
