### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by Rain120** [shadowsocks/shadowsocks-windows#1890]
ping 服务器IP有用，但是就是没法上网，总是无法连接

**Comment by chenshaoju** [comment]
``` 由于目标计算机积极拒绝，无法连接。 ``` 这意味着你的服务器能通，但是由于端口未开放，连接失败。

请检查你的服务器上的SS端口是否正确，以及网络防火墙（如 iptables 等）是否允许了你的SS端口访问。

**Comment by Rain120** [comment]
@chenshaoju 什么意思？没看懂，我昨天还是正常的呢

**Comment by chenshaoju** [comment]
你的服务器是你自己搭的还是买的？如果是自己搭的，请检查服务器上的SS服务是否启动了。如果是购买的，请与你的SS服务商联系。

**Comment by Rain120** [comment]
@chenshaoju ping服务器的IP地址有数据流动啊，但是Google上不去

**Comment by chenshaoju** [comment]
能否将完整的日志贴上来？请记得将你的服务器地址信息替换成其他内容。

**Comment by Rain120** [comment]
![qq 20180615090908](https://user-images.githubusercontent.com/20939839/41445435-2029cefc-707c-11e8-97fe-5847934b7e6b.png)
@chenshaoju 就是保证错误

**Comment by chenshaoju** [comment]
你有手机或者其他设备吗？相同的设置能否在其他设备上使用？这看起来的确就是你所使用的端口被关闭了。

即使无法使用，也会有一点点数据流量，就是服务器发来的拒绝回应和客户端发出的连接请求。

**Comment by Rain120** [comment]
@chenshaoju 之前也遇到这种情况，是迅雷的端口占用了，然后我按照这种方式解决还是没用，今天试了下朋友的，好像也是这个原因

**Comment by chenshaoju** [comment]
最好先测试一下，缩减问题范围。

**Comment by Rain120** [comment]
@chenshaoju 刚才找朋友也试了试，不是迅雷端口问题，应该是服务器端口问题，都是500的错误

**Comment by chenshaoju** [comment]
从你的备注来看，你应该是购买的SS服务，如果是，请访问你的SS服务商网站，检查服务器地址是否有更新，或者换一个地区的服务器试试。

**Comment by jasonliul** [comment]
CurrPorts 
https://www.nirsoft.net/utils/cports.html

检查一下详情...

怀疑服务器问题, 检查端口是否开放
https://portchecker.co/check

**Comment by Rain120** [comment]
@jasonliul 应该是服务器到到期了

**Comment by NatterSteven** [comment]
我这里也出现这个问题了，但是服务器端应该没问题，是自己搭建的。不同设备上：Windows和Android设备都无法连接，其中Windows上是这个错误，而Mac和iOS都可以正常连接。请问有可能是什么问题呢？

**Comment by chenshaoju** [comment]
@NatterSteven 能否将日志贴上来？请记得隐藏你的服务器IP或域名。

**Comment by NatterSteven** [comment]
我刚刚换了一个端口之后似乎好了。之后遇到这个问题的，可以试试换一个端口看看。

**Comment by fuzhouxxdong** [comment]
@chenshaoju 图是和上面的一样，手机是扫描的电脑上的二维码，可以用

**Comment by chenshaoju** [comment]
@fuzhouxxdong 你有Firefox吗？能否做一个这样的测试，单独配置Firefox代理，然后取消SS的系统代理，看看能否使用？

![37390878-680ff942-27a4-11e8-81f1-54edfe7658d9](https://user-images.githubusercontent.com/515763/39850547-8c82ab36-5444-11e8-9030-f22b88125b54.png)

**Comment by chenshaoju** [comment]
@fuzhouxxdong 通常是你的服务器IP被“关照”了……

**Comment by lifeaAngle** [comment]
同，我重启系统就好了

**Comment by magicmei666** [comment]
为啥呀。。。真不明白。。
