### ISSUE TITLE
socks协议不被tor认可

### ISSUE THREAD

**Issue by relei1988** [shadowsocks/shadowsocks-windows#1893]
Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Or search from issue board / 或在issue board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
Please answer these questions before submitting your issue. Thanks! / 请按照以下格式描述你的问题

### Version(release version or AppVeyor link) / 版本（正式版或基于AppVeyor的链接）

Shadowsocks4.0.10
### Environment(Operating system, .NET Framework, etc) / 操作环境（操作系统，.NET Framework等）
windows10

### Steps you have tried / 操作步骤
使用TOR浏览器-7.5.5版本，尝试使用socks4/socks5/http代理方式使用Shadowsocks4.0.10

### What did you expect to see? / 期望的结果

成功连接
### What did you see instead? / 实际结果

tor浏览器报错，信息为无法辨识的socks协议
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
shadowsocks端无报错，但没有连接信息。

此外，如果使用shadowsocks2.0版本则socks协议被tor浏览器认可。xp,win10均可

**Comment by chenshaoju** [comment]
请检查你的Tor的 torrc 文件，是否有以下内容：
```
SOCKS5Proxy 127.0.0.1:1080
```

**Comment by 0zoxnoyy** [comment]
xp系统由于.net版本的问题，没法使用ss4.0.10。
