### ISSUE TITLE
mac ssr 无法翻墙

### ISSUE THREAD

**Issue by jerryli8079** [shadowsocks/shadowsocks-windows#1895]
手里2台mac，老的15寸一直正常ssr 翻墙，新的13寸 同样的ssr账号，同样的客户端，却无法翻墙。
仔细看新13寸的端口，没有异常，proxy listen port 试了改了几次，也不行。却发现新13寸的chrome  的proxy始终是http://127.0.0.1:0/proxy.pac，到底是哪个问题？

**Comment by chenshaoju** [comment]
你好，这是 Shadowsocks for Windows 的Issue列表，Shadowsocks 和 ShadowsocksR 是两个不同的东西，而且 Windows 和 Mac 也是不同的系统。

**Comment by jerryli8079** [comment]
sorry, delete it
