### ISSUE TITLE
关于shadowsocks-windows中插件参数的问题

### ISSUE THREAD

**Issue by LYCX2015** [shadowsocks/shadowsocks-windows#1896]
Shadowsocks version / 影梭版本
4.0.10

 Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10*64

开发者们，您们好，我想请问下，主程序中的插件参数怎么填？
我在网上可以查到插件程序及插件选项的填法，比如这样：
插件程序：obfs-local
插件选项：obfs=tls;obfs-host=www.bing.com
但是插件参数却没有相应的使用说明，可能是功能是最近才开发出来的，所以网上没有相应的使用说明，故来此请教，烦请告之，谢谢。
![qq 20180618171155](https://user-images.githubusercontent.com/16850625/41527840-f4293fa8-731a-11e8-935d-97ea0ceb0065.jpg)

**Comment by LYCX2015** [comment]
好的，谢谢告之，目前符合SIP003规范的插件，仅有 kcptun 及 simple-obf ？

**Comment by celeron533** [comment]
@LYCX2015 而且是改版过的kcptun和simple-obfs
原版的没有SIP003支持

**Comment by john564** [comment]
For obfs
Get obfs-local.exe from 
https://github.com/shadowsocks/simple-obfs/releases

following SIP003 standard to pass parameters
```
Plugin Program C:\obfs-local.exe
Plugin Options obfs=http;obfs-host=www.bing.com
```

or

CLI non SIP003 standard
```
Plugin Program C:\obfs-local.exe
Plugin Arguments --obfs http --obfs-host www.bing.com
```


Again, need to make a new instance of shadowsocks to connect to the listening port of obfs-server, on the server. (not the ss listening port on the server you normally connect to)

**Comment by celeron533** [comment]
>CLI non SIP003 standard
```
Plugin Program C:\obfs-local.exe
Plugin Arguments --obfs http --obfs-host www.bing.com
```

@john564 , you should also add `SS_REMOTE_HOST`, `SS_REMOTE_PORT`, `SS_LOCAL_HOST`, `SS_LOCAL_PORT`, `SS_PLUGIN_OPTIONS` when the plugin program does not support SIP003 standard.

Reference: #1672

**Comment by john564** [comment]
@celeron533 

**1)** In the shadowsocks GUI, you cannot leave the following fields empty.

# Empty "Proxy port" gives  error
input string was not in a correct format.

# Empty "Server Addr" gives error
Invalid server address
 
# Empty "Server Port" gives error
Illegal port number format

So this data must be entered in the shadowsocks GUI.
"Server Addr" and "Server Port" are the obfs server and port 
not shadowsocks server and port

**2)** trying to put the same data again as arguments does not work

-s SS_REMOTE_HOST -p SS_REMOTE_PORT -l SS_LOCAL_PORT -b SS_LOCAL_HOST --obfs http --obfs-host www.bing.com

where 
SS_REMOTE_HOST = "Server Addr"
SS_REMOTE_PORT = "Server Port"
SS_LOCAL_HOST = 127.0.0.1
SS_LOCAL_PORT = "Proxy port"

removing data -l SS_LOCAL_PORT -b SS_LOCAL_HOST
then it works.
But -s SS_REMOTE_HOST -p SS_REMOTE_PORT
must use the same values as the GUI "Server Addr" and "Server Port"
so there is little added value.

**Comment by celeron533** [comment]
@john564 
Please try https://github.com/shadowsocks/shadowsocks-windows/pull/1818#issuecomment-381996176 to check whether the arguments have been send to the plugin program or not.

How the plugin program handle the arguments (such as, does not support remote port or port occupied) is not in the scope.

**Comment by celeron533** [comment]
#1974 #1977

**Comment by celeron533** [comment]
Please try 4.1.2

**Comment by john564** [comment]
> 
> 
> Please try 4.1.2

testing 4.1.2, I did not see any functional changes
what am I suppose to see ?

**Comment by celeron533** [comment]
@john564  4.1.2 has fixed a bug about the Plugin Arguments
And @chenshaoju written a wiki page of how to use Arguments

https://github.com/shadowsocks/shadowsocks-windows/wiki/%E4%BD%BF%E7%94%A8%E9%9D%9ESIP003%E8%A7%84%E8%8C%83%E7%9A%84%E6%8F%92%E4%BB%B6

**Comment by john564** [comment]
Thanks, Can confirm its working, Followed this English wiki , and using latest [kcptun ](https://github.com/xtaci/kcptun/releases)non-SIP003 

https://github.com/shadowsocks/shadowsocks-windows/wiki/Working-with-non-SIP003-standard-Plugin
