### ISSUE TITLE
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。

### ISSUE THREAD

**Issue by NeilKleistGao** [shadowsocks/shadowsocks-windows#1898]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows10 64bit framework4.7

### Steps you have tried / 操作步骤
服务器没有问题，可以通过telnet，直接使用PAC进行代理<br/>
尝试过删除配置文件，ss_win_temp文件夹，netsh命令(其中`netsh interface ipv6 reset`有一条重置失败)

### What did you expect to see? / 期望的结果
成功翻墙:)

### What did you see instead? / 实际结果
浏览器显示：
```
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
```

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
日志中出现：
```
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

**Comment by chenshaoju** [comment]
``` 由于远程方已关闭传输流，身份验证失败。 ```
请仔细检查你所使用的IP、端口、加密方式、密码是否一致。

如果确认无误，请使用 tcping 测试到你的服务器端口是否正常。

你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。

这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
```
tcping 123.45.67.89 9876
```
其中 123.45.67.89 替换为你的服务器IP， 9876 替换为你的你的SS端口，看看能否通？如果通，会提示 Port is open ，如果不通，会提示 No response 或 Port is close 。

**Comment by chenshaoju** [comment]
如果你的服务器能Ping通，但是端口不通，有一定的可能是你的端口被封了，换一个端口看看。

**Comment by NeilKleistGao** [comment]
已尝试，服务器既可以ping通，也可以通过tcping

**Comment by chenshaoju** [comment]
@NeilKleistGao 如果确定tcping能通，并且其他设备上（比如手机）可用，可能和操作系统的Winsocks或TCP/IP协议栈有关，请尝试：　https://github.com/shadowsocks/shadowsocks-windows/issues/1851#issuecomment-389032767 ，如果是你自己搭建的的服务器，有一些比较罕见的情况可能需要套一个simple-obfs看看： https://github.com/shadowsocks/shadowsocks-windows/issues/1787

**Comment by NeilKleistGao** [comment]
simple-obfs加上后无效<br/>
运行`netsh interface ipv4 reset`时出错：
```
正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。
```

ipv6时也会出现相同错误<br/>
已使用管理员身份启动powershell和cmd

**Comment by chenshaoju** [comment]
有几个错误是正常的，如果重置后仍然不行，你可能需要往后看了。

**Comment by NeilKleistGao** [comment]
@chenshaoju 重置后仍然不行

**Comment by chenshaoju** [comment]
你有其他的设备可以测试一下吗？比如手机或者其他计算机？在相同的网络下能否正常工作？

**Comment by chenshaoju** [comment]
@marionxue 请先确保相同的配置可以在同网络下的其他设备（如另一台计算机或手机）上使用，如果不能，请将手机切换到数据网络，看看是否可以使用，如果仍然不能，说明你的服务器被墙了，请更换端口或者更换IP，如果你是购买的服务，请与你的服务商联系更换另一个域名或IP。

**Comment by marionxue** [comment]
在手机可以登录，但是window10上还是不行

**Comment by chenshaoju** [comment]
@marionxue 能否将日志贴上来？请记得隐藏你的服务器IP或域名。

**Comment by TGhoul** [comment]
@chenshaoju 你好，我也遇到同样的问题，我是使用公司的网络，需要手动设置IP才能访问外网，ping我的ss地址也能ping通，tcping端口号也能ping通，能帮忙分析一下问题出在哪里吗？

**Comment by marionxue** [comment]
@chenshaoju 我的错误日志昨晚在window10上将防火墙关闭之后就可以正常使用了， @TGhoul 你可以尝试把防火墙关闭试试呢

**Comment by TGhoul** [comment]
@marionxue 好的，谢谢，我尝试一下。

**Comment by marionxue** [comment]
@chenshaoju   错误日志和标题一样，但是现在已经恢复了,尝试的操作就是吧winow10上的防火墙关闭了,vpn就正常了,然后在启用防火墙 @TGhoul

**Comment by TGhoul** [comment]
@marionxue 我的关了防火墙还是不行，可能是公司内网的原因吧。

**Comment by chenshaoju** [comment]
@TGhoul 能否将日志发送上来？

**Comment by TGhoul** [comment]
@chenshaoju 
[2018-06-26 13:28:06] controller started
[2018-06-26 13:34:08] Shadowsocks started
[2018-06-26 13:34:08] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-06-26 13:34:09] connect to api.github.com:443
[2018-06-26 13:34:10] Socket connected to ss server: 我在墙外
[2018-06-26 13:34:10] connect to api.github.com:443
[2018-06-26 13:34:10] Socket connected to ss server: 我在墙外
[2018-06-26 13:34:10] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by TGhoul** [comment]
@chenshaoju 

[2018-06-26 13:28:06] controller started
[2018-06-26 13:34:08] Shadowsocks started
[2018-06-26 13:34:08]
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
[2018-06-26 13:34:09] connect to api.github.com:443
[2018-06-26 13:34:10] Socket connected to ss server: 我在墙外
[2018-06-26 13:34:10] connect to api.github.com:443
[2018-06-26 13:34:10] Socket connected to ss server: 我在墙外
[2018-06-26 13:34:10] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
--- 内部异常堆栈跟踪的结尾 ---
在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- 内部异常堆栈跟踪的结尾 ---
在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
``` 由于远程方已关闭传输流，身份验证失败。 ```
这意味着从你当前的计算机到你的服务器的连接被重置了，有两种可能，一种是你的服务器被墙了，如果是你自己的服务器，请尝试换一个端口看看。

另一种可能是你们公司部署了内容防泄漏产品（比如深信服），会切断SS的连接。

**Comment by TGhoul** [comment]
@chenshaoju 好的非常感谢

**Comment by TGhoul** [comment]
@chenshaoju 您好，请问您了解还有有其他解决方案吗？我看见同事用lantern是可以的。

**Comment by chenshaoju** [comment]
@TGhoul lantern的原理和SS的不一样，你的SS服务是免费的，还是购买的，还是自己搭建的？

**Comment by TGhoul** [comment]
@chenshaoju 我是自己搭建的，更换端口我尝试了443，和22，不过不幸的是没有成功，我正在尝试80端口。

**Comment by chenshaoju** [comment]
@TGhoul 请仔细检查你的加密方式、密码和端口是否正确，另外，如果你的VPS服务商有网络防护墙，请记得允许端口通过，还包括系统自带的网络防火墙。

**Comment by TGhoul** [comment]
@chenshaoju 非常感谢，这个我都检查了，我是直接复制手机端的配置信息，防火墙也检查了，刚测试80端口失败，tcping80端口不通。

**Comment by TGhoul** [comment]
@chenshaoju 要解决我这个问题，是不是就得自己动手撸一个代理了？😭

**Comment by chenshaoju** [comment]
没看懂你的意思，你的是自己搭的吗？相同的配置手机上能用吗？

你不会是将SS手机版里的那个服务器复制过来的把？

**Comment by TGhoul** [comment]
@chenshaoju 我的意思是我手机上的配置信息，可以连接，我直接把配置导出到剪切板，复制到电脑端来用了。

**Comment by chenshaoju** [comment]
你没回答我的问题。
你手机里的SS服务是你自己搭的，还是SS手机版安装好后自带的那个SS服务器？

如果你的服务器是你自己搭的，你能在PC端手动配置一次测试看看吗？

**Comment by TGhoul** [comment]
@chenshaoju 服务器是我自己搭建的，不是使用的SS手机版安装好后自带的那个SS服务器，我刚手动输入了一下服务器地址和密码和加密方式，测试了一下不通过。我觉的导出配置的肯定比手动输入正确率高吧。

**Comment by chenshaoju** [comment]
你是否启用了代理？如果是，请停用看看，右击托盘区的纸飞机图标，选择正向代理设置，然后取消选中“使用代理”即可。
