### ISSUE TITLE
最近总是连不上，求解答

### ISSUE THREAD

**Issue by vincentdd** [shadowsocks/shadowsocks-windows#1899]
### Shadowsocks version / 影梭版本
4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7   .Net 4.6.2  Microsoft Visual C++ 2015 Redistributable 
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
配置：
```
{
  "configs": [
    {
      "server": "****************",
      "server_port": 8388,
      "password": "***************",
      "method": "aes-256-gcm",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": false,
  "shareOverLan": true,
  "isDefault": false,
  "localPort": 1080,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": true,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": ""
  }
}
```
日志：
```
[2018-06-21 22:02:29] connect to api.github.com:443
[2018-06-21 22:02:34] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

**Comment by chenshaoju** [comment]
如果你的服务器能Ping通，但是端口不通，有一定的可能是你的端口被封了，换一个端口看看。

**Comment by qinfchn** [comment]
我也出现了这个问题，服务器ip能ping通。但是却始终出现错误提示，不管是换系统，换端口，重搭SS都无法解决

**Comment by chenshaoju** [comment]
@qinfchn 能否将具体的错误提示和日志粘贴上来？

**Comment by qinfchn** [comment]
@chenshaoju 就是和这个一模一样

**Comment by vincentdd** [comment]
今天想换个vps，装好后putty也登不上上去，提示超时，用的vultr的，该不会ban的是ip吧

**Comment by chenshaoju** [comment]
@qinfchn 移动宽带有一个自己的“墙”。

@vincentdd 如果你确定IP一样，并且VPS开机了，那么被Ban的IP的可能性很高。

**Comment by qinfchn** [comment]
@chenshaoju 现在通过ping.me发现国内的节点都是绿的，但是用tcping命令的话得到的提示就是No response。会不会是SSH端口被封了？

**Comment by chenshaoju** [comment]
看起来是的。

**Comment by xyj1999** [comment]
现在功夫网会进行TCP阻断，情况就是IP通，SSH无法连接，换个不被阻断的IP就行

**Comment by vincentdd** [comment]
确认是ip问题，换了一个好用的ip就好了，话说现在脚盆机房里能用的被ban的ip有点多，换了好久才有个好用的

**Comment by chenfw2017** [comment]
我也是有差不多这个情况，家里的宽带是联通，SS就是连不上，但ping和SSH正常。公司是电信，SS一切正常。难道联通的FW厉害点- -

**Comment by chenshaoju** [comment]
@chenfw2017 能否测试一下 tcping ，看看端口是否通？

你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。

这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
```
tcping 123.45.67.89 9876
```
其中 123.45.67.89 替换为你的服务器IP， 9876 替换为你的你的SS端口，看看能否通？如果通，会提示 Port is open ，如果不通，会提示 No response 或 Port is close 。

**Comment by chenss1992** [comment]
@chenfw2017 我之前遇到过IP被墙，但是ping.pe都ping的通。后来vps官方检测出的IP已被墙。所以说可能被墙了

**Comment by qinfchn** [comment]
@chenfw2017 我和你情况一样，家里移动连不上。但是在办公室的电信就可以连得上，之后我去联系了vps那边，结论是IP被ban

**Comment by PetitDevil** [comment]
换个ip就行了啊 ip被封很多次的说




On Jun 28, 2018, at 11:43 AM, qinfchn <notifications@github.com<mailto:notifications@github.com>> wrote:


@chenfw2017<https://github.com/chenfw2017> 我和你情况一样，家里移动连不上。但是在办公室的电信就可以连得上，之后我去联系了vps那边，结论是IP被ban

**Comment by chenfw2017** [comment]
@chenshaoju   用你说的工具 试过了，通的，提示port is open. 不过SS依然不可用。

**Comment by chenshaoju** [comment]
@chenfw2017 SS的日志里有什么显示吗？

**Comment by haiyouwho** [comment]
同样是这个情况， 远程连接被关闭：
1. 家里2个电脑，台式机是黑苹果加win10双系统，都能连接上
2. 手机和笔记本都连接Wi-Fi，笔记本win10 连接不上，出现这个日志，手机可以上。
3. 公司电脑也报这个log，但是手机连接公司Wi-Fi也能上。

应该是ss-local 的问题， 目前网上没找到可行的解决办法，有时间去看下源码试试。
