### ISSUE TITLE
第一次用SS连不上,电脑的SSR和手机的SS正常连接

### ISSUE THREAD

**Issue by BaFXSe** [shadowsocks/shadowsocks-windows#1900]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
2.5

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
WIN10      4.6.2

### Steps you have tried / 操作步骤
IP 端口 密码

### What did you expect to see? / 期望的结果
正常连接

### What did you see instead? / 实际结果
连接不上服务器

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
最新的错误方式（不知道为什么传不上去图）
[2018-06-24 09:28:48] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 System.Net.DownloadStringCompletedEventArgs.get_Result()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

之前的错误方式

[2018-06-23 12:56:25] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

或者

[2018-06-23 11:17:40] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 68.XX8.XX2.XXX.4XX
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
或者
[2018-06-23 11:04:10] System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 ::1:8388                     （之前这里是IP和端口 后来错误就变成这个1:8388了）
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)

**用SSR或者安卓手机的SS可以正常连接，我是昨天刚开始弄的，之前没有过使用经验，但是确定是按教程输入，没有弄错步骤。**

**Comment by chenshaoju** [comment]
``` 操作过程中出现异常，结果无效。 有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。 ``` 
这意味着你的链接被切断了，不过这个可能不是重点。

```System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 ::1:8388 ```
这意味着到你本机连接的8338端口出问题了，请尝试在SS的编辑服务器右下角的代理端口输入框中换一个端口看看，比如 10800 端口。

**Comment by BaFXSe** [comment]
看到你的建议之后更改了代理端口
最新的反应是
[2018-06-24 11:25:02] HA switching to server: 68.1XX.1XX.XX:XXX
[2018-06-24 11:25:02] Shadowsocks started
[2018-06-24 11:25:04] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 System.Net.DownloadStringCompletedEventArgs.get_Result()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

看起来似乎没什么变化，SSR的设置里确实点的是origin和plain，毕竟手机的ss和电脑的ssr都能用，我怀疑是电脑上ss和系统的某种设置出了点问题，然鹅我不知道该怎么弄。有必要在win10的设置里调节代理的设置吗，或者类似的操作。但是似乎别人都用的好好的

**Comment by chenshaoju** [comment]
如果确定相同的配置在同一个局域网中的其他设备上可以使用的话，请尝试在有问题的计算机上以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，三行执行完毕后重新启动即可。

如果仍然不行，请尝试升级到最新的 4.0.10 看看。

**Comment by BaFXSe** [comment]
三行命令执行完毕重启后无改观，错误代码是一样的。
更新到4.0.1问题解决。
非常感谢

**Comment by 13kmsteady** [comment]
@chenshaoju
您好，我在电脑上安装 4.1.2 的 ss 无法访问 Google，后来使用 4.0.9 的 ss 可以访问 Google。今天下午脑抽筋的下载了一个 ssr，结果俩都不能使用了。我删除 ssr，ss 还是不能使用。请问该怎么处理？多谢

**Comment by chenshaoju** [comment]
感觉是你所使用的服务器不稳定……

如果可能，请尝试确保相同的配置在相同网络下的其设备上能够使用。

如果仍然不行，日志中有什么显示吗？
