### ISSUE TITLE
关于转http代理的建议provixy

### ISSUE THREAD

**Issue by welenwho** [shadowsocks/shadowsocks-windows#1904]
最近才发现，window版本提供了http代理的功能，问题是，http的端口号是随机的，我知道以前也是固定的，会有冲突问题，但是随机的并不友好，你需要每次都打开配置文件查看，我建议提供给用户设置，这样我是可以清楚知道自己设置了哪个端口，如果冲突加个提示，用户进行更改就可以了，mac版本就很好用，希望越做越好

**Comment by chenshaoju** [comment]
你好，你在编辑服务器界面右下角的代理端口中所设定的端口是HTTP/SOCKS5代理复用端口号，这一个端口同时支持HTTP代理协议和SOCKS5代理协议。

**Comment by welenwho** [comment]
@chenshaoju 感谢回复解答，很棒！！
