### ISSUE TITLE
UX: 非法服务器地址

### ISSUE THREAD

**Issue by CallMeR** [shadowsocks/shadowsocks-windows#1907]
### Shadowsocks version / 影梭版本
Windows 4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows10 对应

### Steps you have tried / 操作步骤
我的SS服务器给的地址为 aa.bb.cc.dd 的形式，会报非法服务器地址。
用IP写入后，点击添加按钮，可以在左侧列表中显示。但是点击上一个服务器地址，同样会报服务器地址非法。

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/42155246-6df68caa-7e1a-11e8-8ce5-cc8cd98b5afe.png)

**Comment by chenshaoju** [comment]
可能和你的配置文件混乱有关。

请尝试退出SS，然后将 Shadowsocks.exe 所在目录下的 gui-config.json 重命名，最后再启动SS，然后重新配置看看。

**Comment by CallMeR** [comment]
删除了gui-config.json后，配置一个aa.bb.cc.dd:port的服务器直接点击确定，可以正常添加一个，再次进入服务器编辑界面时，点击刚才配置的那个，还是会报非法服务器。 @chenshaoju

**Comment by chenshaoju** [comment]
你是这样配置的：
![image](https://user-images.githubusercontent.com/515763/42194050-9f05e838-7ea4-11e8-9fc2-7d195bd418d6.png)

还是这样配置的：
![image](https://user-images.githubusercontent.com/515763/42194064-ad3e09b2-7ea4-11e8-845e-9b212c335c47.png)

？

**Comment by litingfeng** [comment]
@chenshaoju 我有相同问题，是第二种配置。以为是版本问题，换成另一台电脑可以用的4.0.9版本后，仍然会提示非法。

**Comment by chenshaoju** [comment]
@litingfeng 你是手动输入的还是粘贴的？某些情况下粘贴可能会粘贴一个特殊符号进去。

**Comment by CallMeR** [comment]
第二种配置

**Comment by chenshaoju** [comment]
请先Ping你的地址，确保能解析出IP或者能Ping通。

如果确定无误，请用Windows自带的记事本打开 Shadowsocks.exe 所在目录下的 gui-config.json 文件，会看到你的服务器地址在一个名为 server 的参数里，看起来应该类似于：
```
"server": "aaa.bbb.ccc",
```
能否看一下字符间是否有一个换行，或者特殊符号？

**Comment by fabware** [comment]
被这个问题坑到了，作为一个"老手"还浪费不少时间。原因是填完服务器信息后没有立即点“确认”，而是点了“添加”（要不然为什么说自己是老手呢，有时候有些软件你不点添加，下次还得再输一遍），这时再点“确认”或服务器信息的时候就会出现“非法服务器地址”的问题。解决办法很简单，在选中“未配置的服务器”的状态下，点击“删除”，就可以了。

这是一个软件本身交互设计的问题。下面详细重现步骤和改进的建议：

重现的方法：
1、打开软件（现在左侧是“未配置的服务器”），在右侧“服务器”的表单中填入正确的服务器信息；
2、点击“添加”；
3、然后在左侧点击刚才输入的服务器（或者点“确认”），就会碰到“非法服务器地址”。

在这个时候，用户已经完全无法正常使用软件。当弹出“非法服务器地址”的时候，用户会以为是自己刚才输入的服务器地址不对，而没有注意到是“未配置的服务器”地址为空不对。

改进建议：
1、在用户切换到已经填好的服务器时，不要检查未对“未配置的服务器”的默认值做过任何修改的表单；
2、在用户已经填写了至少一个服务器的情况下，点击“确认”，不要检查未对“未配置的服务器”的默认值做过任何修改的表单。

非常感谢开发者的辛苦工作，也希望能对此做一些改进，帮到使用者也给自己省一些麻烦。

**Comment by celeron533** [comment]
谢谢反馈
这个问题基本也就在添加第一台服务器的时候出现，偷懒先坑了。。。。

**Comment by daquexian** [comment]
@celeron533 为什么要关闭这个 issue？这个问题并没有解决，而且很恼人。如果点“确定”那窗口就会直接关闭，点“添加”又会报非法服务器地址（这个问题我很确定两年前就存在，我很惊讶现在竟然还没有解决），我到底要怎么做才能在这个窗口添加多个服务器？

**Comment by celeron533** [comment]
>这个问题并没有解决，而且很恼人

左侧列表点击默认的空服务器，在右边编辑各种内容，然后保存。

**Comment by daquexian** [comment]
@celeron533 “保存”指的是什么？“确定”吗？点击“确定”是不会遇到问题的，但这个 issue 提出的问题完全和这个无关。如果我想添加多个服务器，我是不是应该在输入完服务器信息之后点击“添加”？（点击“确定”会直接退出界面）点击添加之后就会遇到这个恼人的问题。https://github.com/shadowsocks/shadowsocks-windows/issues/1907#issuecomment-406153660 已经说的很清楚了

**Comment by celeron533** [comment]
>那么为什么要关闭 issue？
确实不妥

**Comment by vsp6688** [comment]
> 被这个问题坑到了，作为一个"老手"还浪费不少时间。原因是填完服务器信息后没有立即点“确认”，而是点了“添加”（要不然为什么说自己是老手呢，有时候有些软件你不点添加，下次还得再输一遍），这时再点“确认”或服务器信息的时候就会出现“非法服务器地址”的问题。解决办法很简单，在选中“未配置的服务器”的状态下，点击“删除”，就可以了。
> 
> 这是一个软件本身交互设计的问题。下面详细重现步骤和改进的建议：
> 
> 重现的方法：
> 1、打开软件（现在左侧是“未配置的服务器”），在右侧“服务器”的表单中填入正确的服务器信息；
> 2、点击“添加”；
> 3、然后在左侧点击刚才输入的服务器（或者点“确认”），就会碰到“非法服务器地址”。
> 
> 在这个时候，用户已经完全无法正常使用软件。当弹出“非法服务器地址”的时候，用户会以为是自己刚才输入的服务器地址不对，而没有注意到是“未配置的服务器”地址为空不对。
> 
> 改进建议：
> 1、在用户切换到已经填好的服务器时，不要检查未对“未配置的服务器”的默认值做过任何修改的表单；
> 2、在用户已经填写了至少一个服务器的情况下，点击“确认”，不要检查未对“未配置的服务器”的默认值做过任何修改的表单。
> 
> 非常感谢开发者的辛苦工作，也希望能对此做一些改进，帮到使用者也给自己省一些麻烦。
