### ISSUE TITLE
配置上应该是没有问题，IPhone可以的， 但是win7 连接不上， shadowsocks-windows是最新版

### ISSUE THREAD

**Issue by Amos1st** [shadowsocks/shadowsocks-windows#1909]
```
[2018-07-03 10:48:35] Shadowsocks started
[2018-07-03 10:48:35] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
```

有没有可能是Windows的防火墙问题呢？抑或是其他原因呢，烦请帮忙看看，谢谢！

**Comment by chenshaoju** [comment]
使用Firefox的情况下，访问任意网站，SS的日志里有什么显示吗？

**Comment by Amos1st** [comment]
@chenshaoju 只有一些连接的信息而已，没有什么error的

[2018-07-03 11:26:27] Socket connected to ss server: xxx.xxx.xxx.xxx:1024
[2018-07-03 11:26:27] Socket connected to ss server: xxx.xxx.xxx.xxx:1024
[2018-07-03 11:26:27] connect to www.google-analytics.com:443

**Comment by chenshaoju** [comment]
请检查你的网络连接是否为中文名。

**Comment by Amos1st** [comment]
@chenshaoju  是修改 "控制面板\网络和 Internet\网络和共享中心" 这里么？不太确定

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/42250750-bba2d5de-7f65-11e8-97a2-4ea6c332e2a5.png)

**Comment by Amos1st** [comment]
我电脑是win7的，没有找到图中的LAN呢 @chenshaoju 
![image](https://user-images.githubusercontent.com/13114457/42272779-d2e2ad92-7fb9-11e8-85eb-7f300bfee707.png)

**Comment by chenshaoju** [comment]
@Amos1st 点击左上方的“更改适配器设置”。
