### ISSUE TITLE
firefox用PAC模式无效

### ISSUE THREAD

**Issue by jyuan15** [shadowsocks/shadowsocks-windows#1913]
SS版本为4.0.10，之前版本同样情况。
firefox多个版本（40,45,48,52等）使用PAC模式均无效，打不开被墙网页，日志无输出信息，全局模式则正常使用。
但Chrome在PAC模式下又可以用。

**Comment by jyuan15** [comment]
@chenshaoju 插件是foxyproxy，火狐代理设置一直是默认的“系统代理”，但在使用PAC模式时，foxyproxy是关闭的。
而且刚才试过即使把foxyproxy删除，还是不能用pac

**Comment by chenshaoju** [comment]
我用的也是FoxyProxy，在禁用代理，并且确认是使用系统代理的情况下，并没有发生问题。

![image](https://user-images.githubusercontent.com/515763/42303431-cc448cf4-8053-11e8-8575-254a707ee48f.png)

能否检查一下插件列表，看看是否有其他的代理插件在工作？

请尝试点击Firefox的菜单，选择Web开发，然后点击网络。

随后，打开一个被墙的网站，比如 www.google.com.hk ，并点击第一个请求，右侧会有一个远程地址（或者Remote address），这个地址是什么？能否截个图？

![image](https://user-images.githubusercontent.com/515763/42303502-42e53aca-8054-11e8-9fe9-9dea91e96c60.png)

**Comment by jyuan15** [comment]
刚才又试了，发现52版可以用pac，40、45、48都不能用，这几个版本火狐的设置和插件都完全一样。

按你的方法查看，好像并没有你说的远程地址：

![2018-07-05_211211](https://user-images.githubusercontent.com/12642186/42325353-89669650-8055-11e8-94a6-ec3d5d6d7940.jpg)

**Comment by chenshaoju** [comment]
已知旧版本的Firefox有BUG，当PAC大于一定尺寸后会导致Firefox无法获取PAC文件：  https://github.com/shadowsocks/shadowsocks-windows/issues/487

**Comment by jyuan15** [comment]
变通了一下，在FoxyProxy中把SS设置为”使用系统代理“，居然就可以用PAC了，这是什么原因？

![2018-07-06_011150](https://user-images.githubusercontent.com/12642186/42337488-7b5d988a-8076-11e8-953b-ca513e35a190.jpg)

**Comment by chenshaoju** [comment]
所以。。。你之前并没有关闭FoxyProxy？

也许是FoxyProxy的问题？

**Comment by jyuan15** [comment]
之前设置的是“手动配置”，无法使用pac，然后就关了FoxyProxy，仍然不能用。
现在不解的是，为何通过FoxyProxy用系统代理（PAC）就行，而火狐直接用系统代理就不行？

**Comment by chenshaoju** [comment]
无法确认。。。从你的FoxyProxy界面来看，你用的Firefox应该是有段历史的老版本了。

**Comment by jyuan15** [comment]
是40版，昨天特意下了SS2.7.3和一个小于110K的pac文件来测试，结果还是只有52版能用PAC模式，4X版都不行。

**Comment by chenshaoju** [comment]
建议使用最新版的Firefox，以避免安全问题。

**Comment by linqh1** [comment]
一样碰到这个问题了，firefox版本：75.0 (64 位)

我一开始以为firefox的系统代理设置被破坏了，后面我发现如果把chrome的SwitchProxy关了，在pac模式下chrome也是访问不了被墙网页。

看来firefox和chrome的代理设置是一样的，问题应该出在插件的系统代理上，它们应该有做一些其他的工作，使得PAC模式下能访问被墙网页？

**Comment by chenshaoju** [comment]
你是否通过拨号连接访问互联网？如果是，拨号连接是不是中文的？如果是，改成英文的试试。

**Comment by linqh1** [comment]
很奇怪，目前又可以了。看来应该不是firefox的问题

**Comment by harryhare** [comment]
我现在用的Firefox84.0.2 (64-bit)，一样的问题。chrome 正常，应该是firefox的锅
