### ISSUE TITLE
The English term "clean logs" is a bit unnatural.

### ISSUE THREAD

**Issue by skygate2012** [shadowsocks/shadowsocks-windows#1915]
Native speakers usually use "clear logs" or "clean up the logs" instead of "clean logs" for this action.
![scr](https://user-images.githubusercontent.com/7148976/42324854-f686bc7e-8096-11e8-97b8-d0652cf4486e.png)

**Comment by batdkuwlh** [comment]
recommend a ss  providers https://ss.plus
