### ISSUE TITLE
shadowsock连接不上服务器

### ISSUE THREAD

**Issue by johnsonchen2018** [shadowsocks/shadowsocks-windows#1918]
日志里内容如下：

System.InvalidOperationException: 同一个套接字上正在进行另一个异步操作时，不能调用 BeginConnect。
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()

**Comment by chenshaoju** [comment]
启动Shadowsocks后，双击任务栏托盘区的纸飞机图标，在编辑服务器界面右下角的代理端口中，更换一个端口，比如2080，然后再试。

**Comment by johnsonchen2018** [comment]
好的，我来试试。谢谢了！

在 2018-07-08 18:52:50，"Chen Shaoju" <notifications@github.com> 写道：

**Comment by Alwayslazydog** [comment]
> 请尝试换一个高位的端口，比如 10800 。
> 
> 如果仍然不行，请把日志发上来确认一下。

[2019-02-14 11:57:36] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-02-14 11:57:49] Shadowsocks started
[2019-02-14 11:57:52] Shadowsocks started

然后下面就是一直timed out

**Comment by chenshaoju** [comment]
``` 由于远程方已关闭传输流，身份验证失败。 ```

这很有可能意味着从你当前的网络到你的服务器的链接被切断了。

请确保你的服务器工作正常，如果可能，请使用 tcping 进行测试，在出现time out时，看看端口是否能连通。

你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。

这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
```
tcping -t 123.45.67.89 9876
```
其中 123.45.67.89 替换为你的SS服务器地址， 9876 替换为你的你的SS端口，然后回车，此时，如果显示 Port is open ，这说明端口通，如果不通，则可能提示 No response 或 Port is close。
