### ISSUE TITLE
是否由于shadowsocks导致网页访问速度变慢？

### ISSUE THREAD

**Issue by XiangBicheng** [shadowsocks/shadowsocks-windows#1919]
### Shadowsocks version / 影梭版本
4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

### Steps you have tried / 操作步骤
- 开启shadowsocks时（确认未勾选全局代理），多数网页打开速度极度缓慢，优酷首页加载完毕需超过20秒，学堂在线首页加载完毕超过20秒，百度主页略快但仍有明显迟钝，个别网页无法打开。
- 托盘区运行shadowsocks，但取消勾选“启用系统代理”，基本没有好转。
- 完全退出shadowsocks，仍然没有好转。

### 补充：
上述情况之前也出现过，因其他原因重装过系统，问题也同时解决。

**Comment by XiangBicheng** [comment]
是不是因为错误设置shadowsocks导致代理无法正确选择流量通过路径？

**Comment by chenshaoju** [comment]
请确保SS工作在PAC模式而不是全局模式。

请打开浏览器，访问 http://www.ip.cn ，请问显示的是你的公网地址还是你的SS服务器的地址？

**Comment by XiangBicheng** [comment]
我没有做什么事情，但是我重启过后，网络又正常了。
