### ISSUE TITLE
启用系统代理后，Edge 浏览器无法使用 hosts 中设置的域名

### ISSUE THREAD

**Issue by Aqours** [shadowsocks/shadowsocks-windows#1920]
### Shadowsocks version / 影梭版本
4.0.9.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 (1803)

### Steps you have tried / 操作步骤
1. 配置一个可以的代理并设置为启用系统代理
2. 设置 hosts `127.0.0.1 eg.github.com`
3. 启动一个本地服务并在根目录放一个 index.html 文件
4. 使用 Edge 浏览器访问 `http://eg.github.com/index.thml`

### What did you expect to see? / 期望的结果
可以访问文件

### What did you see instead? / 实际结果
无法访问

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
n/a

**Comment by chenshaoju** [comment]
你好，这是微软Windows系统本身的限制，如果你使用代理，本机的Hosts将会失效。

**Comment by chenshaoju** [comment]
这个问题之前有个类似讨论，但是我还是没搞清楚是怎么回事： https://github.com/shadowsocks/shadowsocks-windows/issues/1856

你能否做一个测试，将你想要直连的域名以例外的方式加入 user-rule.txt ，这种情况下hosts能生效吗？

另外，请测试一下IE的情况。

**Comment by Aqours** [comment]
以加入 user-rule.txt 的方式，域名可以访问，但是没有经过 hosts。

找到了问题的原因了，是 Windows 10 loopback 的问题（和 Edge 浏览器 `about:flags` 里的设置不同）。
参考：
- https://blogs.msdn.microsoft.com/msgulfcommunity/2015/07/01/how-to-debug-localhost-on-microsoft-edge/
- https://stackoverflow.com/questions/32384571/why-does-microsoft-edge-open-some-local-websites-but-not-others-where-the-doma/32828629
- https://developer.microsoft.com/en-us/microsoft-edge/platform/faq/#how-can-i-debug-localhost

**Comment by Aqours** [comment]
另外有点奇怪的问题，Edge 浏览器用代理（PAC/全局）访问 google 的时候非常慢，twitter 就没问题。在 IE 下也没问题。不相关的话请忽略
![qq 20180710141330](https://user-images.githubusercontent.com/8586286/42493977-7c751750-8451-11e8-8e84-3fab501a88f3.png)

**Comment by chenshaoju** [comment]
感谢反馈。

edge慢的话，Chrome/Firefox慢吗？

**Comment by Aqours** [comment]
Chrome/Firefox 正常
