### ISSUE TITLE
有偿/WIN版shadowsocks可以给SOCKS5增加验证么？默认只能改端口没有账号密码选项

### ISSUE THREAD

**Issue by 556a** [shadowsocks/shadowsocks-windows#1921]
WIN版shadowsocks可以给SOCKS5增加验证么？默认只能改端口没有账号密码选项
谁能搞下加我QQ592595684

**Comment by chenshaoju** [comment]
如果你愿意在本地跑一个CCProxy的话，CCProxy的二级代理可以帮到你：https://github.com/shadowsocks/shadowsocks-windows/issues/1145

**Comment by 556a** [comment]
@chenshaoju CCProxy 用不了我自己改过客户端认证流成和认证加密,我需要找个人 改下shadowsocks之后我自己改认证流程和认证加密.

**Comment by celeron533** [comment]
#1612
