### ISSUE TITLE
可以申请将被墙的域名加入到默认的PAC里吗？

### ISSUE THREAD

**Issue by flyzy2005** [shadowsocks/shadowsocks-windows#1923]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.09

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
4.5

### Steps you have tried / 操作步骤
无

### What did you expect to see? / 期望的结果
走PAC模式就能打开（*.flyzy2005.com）

### What did you see instead? / 实际结果
全局模式可以打开，但是PAC打不开

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
我看有些站，如doub.io就在默认的PAC里的，我想请问一下能在哪个地方申请（如提issues）将某个被GWF拉黑的域名加入到默认PAC吗？而是必须走全局或者要别人也手动改PAC文件才可以？
还是说这种申请要你的站必须有一点名气的？
谢谢！

**Comment by chenshaoju** [comment]
你好，Shadowsocks for Windows 使用的PAC列表基于GFWList。

请移步 https://github.com/gfwlist/gfwlist/issues 进行提交。

**Comment by flyzy2005** [comment]
好的 谢谢！
