### ISSUE TITLE
Hope to download from Microsoft Store

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-windows#1925]
Microsoft Store can update apps automatically. Could you please upload it to Microsoft Store?

**Comment by studentmain** [comment]
You mean UWP? This program is not ready for UWP yet.

Richa <notifications@github.com> 于 2018年7月12日周四 11:54写道：

**Comment by celeron533** [comment]
Do you mean let Microsoft Store uses the proxy to connect?

https://github.com/shadowsocks/shadowsocks-windows/issues/897#issuecomment-261753745
