### ISSUE TITLE
不知道为什么 感觉性能反应不如以前了

### ISSUE THREAD

**Issue by zfk513** [shadowsocks/shadowsocks-windows#1926]
点开显示界面延时有点高  对于我这种经常要换服务器的
不是很友好

**Comment by chenshaoju** [comment]
我试了一下，Windows 7系统上目测300ms左右出现界面。

你是有许多服务器在里面吗？

**Comment by zfk513** [comment]
是的 我已经回退版本了 速度明显提升了 orz

**Comment by everyx** [comment]
新版本 UI 部分的确是有问题，经常无响应

**Comment by celeron533** [comment]
你现在用的是哪个版本？又是哪一个版本的性能更好呢？
UI这边最近一直没有大改动。

**Comment by everyx** [comment]
@celeron533 现在用的就是最新的 release 版本 4.0.10，之前的被我删掉了，不知道啥版本了 😓
