### ISSUE TITLE
win7下打开，进程无响应

### ISSUE THREAD

**Issue by QingyangChen** [shadowsocks/shadowsocks-windows#1929]
### Shadowsocks version / 影梭版本
4.0.9/4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7、.NET 4.6.2

### Steps you have tried / 操作步骤
双击打开

### What did you expect to see? / 期望的结果
正常运行

### What did you see instead? / 实际结果
进程无响应

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2018-07-14 15:29:02] Shadowsocks started
[2018-07-14 15:29:02] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================
```

**Comment by YoulianBoshi** [comment]
尽量不要把小飞机放进系统盘

**Comment by QingyangChen** [comment]
@chenshaoju @YoulianBoshi 
谢谢两位的指点。但是我还是没有解决问题。我这次描述的清楚点。

1. 双击打开之后，**主界面无响应**，如下图：
![ss_1](https://user-images.githubusercontent.com/18388868/42790956-3e2a26a8-89a0-11e8-9938-9b2ff2b8239f.png)

2. 任务栏托盘区的**纸飞机右击无反应**，但是**鼠标悬停到纸飞机上**，会有提示：
![ss_3](https://user-images.githubusercontent.com/18388868/42791014-873b92d2-89a0-11e8-8197-384660a2910e.png)

3.通过命令行**查看端口占用情况**，似乎程序已经正常运行：
![ss_2](https://user-images.githubusercontent.com/18388868/42791037-9f5681c4-89a0-11e8-8f17-7f8544486da6.png)
 
4. 点击主界面任意区域，会提示程序无响应，需要关闭
![ss_4](https://user-images.githubusercontent.com/18388868/42791048-b969d0fc-89a0-11e8-870c-cbe6ff8c2381.png)

**Comment by chenshaoju** [comment]
这个问题看起来很像是界面问题，可能和操作系统或者和.NET框架有关。
１.请先确保已经安装好所有的补丁。
２.请检查安装的是否为最新的 .NET 框架：https://www.microsoft.com/net/download/dotnet-framework-runtime
３.如果提示已经安装相同版本，可能需要使用.NET框架修复工具修复看看： https://www.microsoft.com/en-us/download/details.aspx?id=30135

**Comment by Wings-Fantasy** [comment]
我有同样的问题，我的电脑是win10专业版，同样的操作：双击打开未响应在同样的位置，.NET提示已安装或安装了更高版本，修复工具也已经用过了，还是未响应

**Comment by chenshaoju** [comment]
双击打开没反应的话，看一下任务管理器，有没有 Shadowsocks.exe 的进程？（默认文件名的话）

**Comment by Wings-Fantasy** [comment]
进程有
还有，我已经解决了，解决办法：回退到3.4.3版本

**Comment by chenshaoju** [comment]
进程有的话，检查一下托盘区，是否有图标？

如果没有，可以尝试将新版的SS单独放到一个空目录中，重新配置一下看看。

也可能和某些安全（杀毒）软件的拦截有关。

**Comment by Wings-Fantasy** [comment]
我的状态和上面的图片是完全一样的，杀毒软件是微软内置的，没有报毒

**Comment by celeron533** [comment]
@chenshaoju 可能和#1755 有关

**Comment by chenshaoju** [comment]
@celeron533 maybe with https://github.com/shadowsocks/shadowsocks-windows/issues/1922

**Comment by chenshaoju** [comment]
请楼上几位检查一下Windows Update已安装补丁列表，是否有一个名为“KB4338818 ”的补丁？如果是，请尝试卸载该补丁，或者进入可选更新，安装一个名为 KB4338821 的补丁，看看是否可以了？

参考资料：
https://support.microsoft.com/en-us/help/4338818/windows-7-update-kb4338818
https://support.microsoft.com/en-us/help/4338821/july242018kb4338821osbuildpreviewofmonthlyrollup

**Comment by Wings-Fantasy** [comment]
我的系统是win10，安装不了KB4338821，也没有KB4338818补丁

**Comment by Jetranger** [comment]
OS是否是安装的Ghost版，是否安装了360、电脑管家之类的全家桶？

**Comment by Wings-Fantasy** [comment]
官方原版系统，全家桶从来不装的

**Comment by chenshaoju** [comment]
忘记说了，主要是Win7/2008R2系统。
Windows 10暂时还没找到解决方案，而我这儿的Win10一直没问题。

**Comment by Wings-Fantasy** [comment]
还是避免一下线程死锁吧，能不用线程锁就尽量不用

**Comment by chenshaoju** [comment]
@Wings-Fantasy 估计得等这个pull request（ https://github.com/shadowsocks/shadowsocks-windows/pull/1755 ）经由开发人员合并后才能解决了。。。

**Comment by everyx** [comment]
更新到新版以后也出现了这个问题，系统是 Windows Server 2008R2，试试打一下补丁看看

**Comment by crow0258** [comment]
我也出现了该问题，原来一直运行良好，我的操作系统是win10，和描述情况一模一样，右键小图标无反应，重新放置到其他文件夹后，打开界面卡死，补丁全是最新的。我也是看到回退到3.4.3后解决了该问题。

**Comment by IlO0OlI** [comment]
我也出现了该问题，原来一直运行良好，我的操作系统是win10 1709，和描述情况一模一样，右键小图标无反应。
4.0.10
之前一直是正常使用的，有一次我一直双击右下角图标，然后程序就崩溃了，像一楼那样，试了很多版本最高能用的是4.0

**Comment by gaoyangthu** [comment]
@chenshaoju
Windows7 7601 64位，4之前的版本没有问题，更新到4.0.10后遇到同样的问题。只要右键点击任何菜单，程序就死了，无法通过其访问网络，在任务管理器中也无法结束进程。

**Comment by chenshaoju** [comment]
@gaoyangthu https://github.com/shadowsocks/shadowsocks-windows/issues/1929#issuecomment-406128120

**Comment by gaoyangthu** [comment]
@chenshaoju 
谢谢！检查了一下，这个问题确实实在安装了KB4338818补丁之后出现的。又安装了KB4338821，一切恢复正常:-)

**Comment by chenshaoju** [comment]
这是一个**非官方**的编译版本：[Shadowsocks_unofficial.zip](https://github.com/shadowsocks/shadowsocks-windows/files/2239606/Shadowsocks_unofficial.zip)

该版本基于最新的代码（1124 commits）合并了  https://github.com/shadowsocks/shadowsocks-windows/pull/1755 所提供的补丁。

该版本理论上可以解决 https://github.com/shadowsocks/shadowsocks-windows/issues/1929#issuecomment-405427097 所遇到的界面卡死问题，如果你是能看到编辑服务器界面，但是修改或点击某些菜单条目后卡死，请阅读 https://github.com/shadowsocks/shadowsocks-windows/issues/1929#issuecomment-406128120 。

已在Windows 10 x64 1803 (17134.167) 和Windows 7 SP1 x64上进行了测试，暂未发现问题。

有遇到该问题的用户可以试一下，看看能否解决问题。
@QingyangChen @Wings-Fantasy @everyx @crow0258 @IlO0OlI 

校验码（Shadowsocks_unofficial_base1124_merged1755_20180730_[8605aadd].exe）：
MD5：d4feb84a84a95167804786d9e0f30dde
SHA1：ad78e0d403d32e2f39581d157b2d845c5f1497fb
SHA256：5ee306b44879430c12ec894e608189abcaeb704fa4739ac366f2b0fb2a2f2651

病毒扫描报告：
https://www.virustotal.com/#/file/5ee306b44879430c12ec894e608189abcaeb704fa4739ac366f2b0fb2a2f2651/detection

**Comment by IlO0OlI** [comment]
@chenshaoju 好了

**Comment by xutianyi1999** [comment]
@chenshaoju  win10最新版已解决

**Comment by celeron533** [comment]
有可能在`sysproxy query`查询当前系统代理设置的时候由于未知原因没有返回结果（查询出错？）

**Comment by chenshaoju** [comment]
我不懂代码。。。只是将 https://github.com/shadowsocks/shadowsocks-windows/pull/1755/files 中的 Sysproxy.cs 替换到了最新的源码中……

**Comment by everyx** [comment]
看了一下 #1755 的讨论和应用资料，补充一个现象，界面无响应后使用任务管理器杀 shadowsocks 和 sysproxy 进程都杀不掉，是否为参考文档中描述的 死锁 的行为，最终我只能强制注销/重启。

**Comment by celeron533** [comment]
#1755 merged to master branch. Will be included in next release.

**Comment by IlO0OlI** [comment]
4.1.0版本发布了，Win10没问题
