### ISSUE TITLE
New feature request: icon color for different choice in settings

### ISSUE THREAD

**Issue by Nidhoggur1993** [shadowsocks/shadowsocks-windows#1931]
### Shadowsocks version / 影梭版本
4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows Server 2016 Standard
.NET Framework 4.6

### Steps you have tried / 操作步骤
Do not need

### What did you expect to see? / 期望的结果
A feature to make the color for icon have different choice in the setting.

I know it's available to run multiple clients if I put them in different folders and listen to different local ports, but the icon in taskbar is all the same.
Thanks.

![different local port but same icon](https://user-images.githubusercontent.com/12947582/42802585-f55b78c4-89d5-11e8-9df3-14ab67450918.png)

**Comment by celeron533** [comment]
You can hover your mouse on the icon to view the ports.

**Comment by celeron533** [comment]
Or you can replace the icon and rebuild the project by yourself.
