### ISSUE TITLE
连接后10分钟无法访问谷歌

### ISSUE THREAD

**Issue by huangtting** [shadowsocks/shadowsocks-windows#1932]
### Shadowsocks version / 影梭版本
4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win 7

### Steps you have tried / 操作步骤
开启PAC模式后，等待大概10分钟后，无法访问google.com等网络。
只有重新连接，然后才可以访问谷歌。
然后过10分钟又不可以。

### What did you expect to see? / 期望的结果
能够正常上网

### What did you see instead? / 实际结果
10分钟后无法访问谷歌

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
实际上在公司才会这样，在家不会。
![_15319647207814](https://user-images.githubusercontent.com/26655372/42916744-376acb48-8b39-11e8-877f-fac22e12cdf8.png)
访问谷歌时，不会检测到，没有更新的信息显示在日志里。

**Comment by chenshaoju** [comment]
除开谷歌，其他被墙的网站，比如Facebook、Twitter等，能访问吗？

同一时间，如果你手机上有SS，相同的配置使用3G/4G网络是否可以？

如果其他网站也不行，有很高的可能性是你所在的网络部署了内容过滤系统，请尝试加一个Simple-obfs或者GoQuite进行混淆。

**Comment by huangtting** [comment]
@chenshaoju 同一时间手机使用4G可以连上那些网站，但是电脑不行。
使用Simple-obfs后还是不行，配置如下：
![_15319700545430](https://user-images.githubusercontent.com/26655372/42919545-0cd0b436-8b45-11e8-9a20-1da8cd1ace67.png)

**Comment by chenshaoju** [comment]
你可能需要试试TLS模式。

另外，极为罕见的案例可能和系统有关，请尝试以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机即可，如果你的计算机是固定IP，重启后需要手动设置一下IP地址，如果是自动分配，则不需要。

**Comment by huangtting** [comment]
@chenshaoju 不得不说，还是不行。

**Comment by chenshaoju** [comment]
我开始怀疑要么是ISP问题，要么是你的网络真的有某种系统在过滤流量，但是具体是什么，不知道。

**Comment by gumptie** [comment]
版本4.0.10在PC （win10）上也是会经常出现假死情况，需要更换其他服务器，不停来回折腾。不过，换回4.0.9后就什么问题就没有
版本4.0.10在surface pro 就很正常

**Comment by chenshaoju** [comment]
@gumptie 如果你的假死情况类似于 https://github.com/shadowsocks/shadowsocks-windows/issues/1929#issuecomment-405427097 ，该问题已知，可能和 https://github.com/shadowsocks/shadowsocks-windows/issues/1929#issuecomment-406133899 有关。

**Comment by huangtting** [comment]
@chenshaoju 我觉得网络应该没有问题。毕竟同事用得没有什么问题。 可能是电脑设置问题，当然也不排除版本本身的问题。@gumptie 换了4.0.9之后没有改善。

**Comment by chenshaoju** [comment]
这个问题是不是最近一个月内出现的？

**Comment by huangtting** [comment]
@chenshaoju 确切地讲，我是在一个月内才开始使用的..等我周一再去试下重置电脑重启看看。

**Comment by chenshaoju** [comment]
刚开始用就有这个问题吗，还是……？

**Comment by huangtting** [comment]
@chenshaoju 在公司刚开始用就是这样。

**Comment by DeviesVi** [comment]
在这个4.0.10确实出现了同样的问题，之前同样的网络环境未曾发生，安卓设备在相同环境下可以正常访问，日志显示到服务器的连接超时

**Comment by chenshaoju** [comment]
无法判断可能的问题……你可能需要考虑重置系统看看了。

请记得备份数据。

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1943#issuecomment-409907530

**Comment by huangtting** [comment]
@celeron533 看了你的回答，但是公司电脑上并没有其他代理软件。如果有可能，我会尝试换个操作系统玩一下

**Comment by moon-dark** [comment]
怕是插件的问题？注意浏览器左下角提示。

我的AdBlock偶尔间隔一段时间就导致Google Chrome不能访问网络。


2018-08-02 23:01 GMT+08:00 Ting <notifications@github.com>:

**Comment by chenshaoju** [comment]
你们公司是不是用了域登录（或者称为活动目录）？

如果是，有没有可能你们公司网管给你们下发了不同的账户策略？
