### ISSUE TITLE
Feature: Import multiple space-deliminated ss links from clipboard

### ISSUE THREAD

**Issue by Artoria2e5** [shadowsocks/shadowsocks-windows#1933]
Shadowsocks version: 4.0.10
Environment: irrelevant

## Steps
1. Copy multiple `ss://` links, each separated by a space (` `), into the clipboard
2. "Import from clipboard"

## Expected behavior
I expect to see all the servers imported individually.

## Actual behavior
Only one server entry is created; all other links went into its name.

## Workaround
Paste the links into notepad++, and replace all spaces with a newline `\n`.

**Comment by celeron533** [comment]
It is not common to have this scenario....
And the workaround could solve this problem, too.
If you are getting the server list from a provider, perhaps ask them to generate a list by using newline-deliminated.
OR you could also modify the code to add space as the deliminator when parsing the clipboard string.
