### ISSUE TITLE
对于目前shadowsocks-windows项目的看法

### ISSUE THREAD

**Issue by Wings-Fantasy** [shadowsocks/shadowsocks-windows#1934]
我最开始用shadowsocks的时候，只想用它作为翻墙代理。
如今，shadowsocks项目越来越臃肿，仅对于我个人来说，我只用到了不到80%的功能。
所以，我建议这个项目分版本发布：

 - 精简版：只保留作为正常VPN使用的功能，例如服务器的添加、选择、删除，本地代理。
 - 普通版：加入快捷键、正向代理配置一类的辅助功能
 - 高级版：加入插件等高级功能

本建议仅代表我个人观点，希望开发人员能考虑一下。

最后，放一个shadowsocks免费服务器的网站：[免费上网账号](URL removed)

**Comment by chenshaoju** [comment]
太多版本会增加维护难度。

另外，请勿在此推广SS服务。
