### ISSUE TITLE
我最近几天都是超时，怎么办！

### ISSUE THREAD

**Issue by gebiWangshushu** [shadowsocks/shadowsocks-windows#1936]
都是这样，你们遇到过吗？

![tim 20180723235158](https://user-images.githubusercontent.com/27838829/43087941-956ee2f4-8ed3-11e8-915d-a31bc3f2c283.png)

**Comment by chenshaoju** [comment]
你好，你所使用的服务器好像被墙了，看起来你的SS服务是购买的，请访问你的SS服务商网站获取新的服务器地址，或者联系你的SS服务商以寻求帮助。

PS：请记得删除日志中的服务器地址等信息。

**Comment by gebiWangshushu** [comment]
感谢回复！我晚上回去换个地址再试~
