### ISSUE TITLE
关闭ss后不能正常访问网络

### ISSUE THREAD

**Issue by Acytoo** [shadowsocks/shadowsocks-windows#1937]
## 这个问题我前几天遇到过一次，清空dns， 重置网络连接，重启什么的就能解决，但今天无论如何都不能直接访问Google，按照 #1917 操作过，也不能访问Google ，所以还请各位能人帮忙解决以下。

# 代理设置一切为直连，清过dns， 重置过电脑网络连接，重启过，还是不行。

**Comment by Acytoo** [comment]
刚刚手动指定https:// ,结果能打开google了，但是直接进google.com.hk，连接就会被重置，然后网站不可达，所以请问ss会做些什么呢？这好像是一个很久的bug了吧？

**Comment by chenshaoju** [comment]
```刚刚手动指定https:// ,结果能打开google了，但是直接进google.com.hk，连接就会被重置，然后网站不可达，所以请问ss会做些什么呢？这好像是一个很久的bug了吧？```

你是在退出SS的情况下进行这个测试的吗？如果是，并且你有Firefox的话，如果在Firefox的网络，代理设置中将代理方式改成无代理（或No Proxy），能否访问？

**Comment by Acytoo** [comment]
我是在退出SS后测试的，只有Google chrome， 在Google chrome中使用switch Omega，直连，系统代理，还是自己的设置都不正常能工作

**Comment by chenshaoju** [comment]
退出SS后，如果确认系统代理已经关闭，该问题可能和SS无关，可能和你的DNS或者网络环境有关。

猜测可能是SwitchOmega影响的，请尝试禁用该插件，重启Chrome后再试。

如果可能，也请测试一下IE浏览器的访问情况。

**Comment by Acytoo** [comment]
禁用了switchomega，也试了edge，问题依旧。只是如果我指定进https://www.google.com.hk, 就好了，然后再次进Google也没问题，可能是dns吧
