### ISSUE TITLE
Is it possible to use multiple plugins?

### ISSUE THREAD

**Issue by jibon57** [shadowsocks/shadowsocks-windows#1938]
### Shadowsocks version / 影梭版本

shadowsocks-libev 3.2.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows 10 64 bits

### What did you expect to see? / 期望的结果

Multiple SIP003 standard plugins

### What did you see instead? / 实际结果

Single SIP003 standard plugin

Can I use both kcptun & obfs at a same time without writing a separate script? I can see the option name is "Plugin Program". Is it possible to inset both plugins configuration or need to use single plugin either kcptun or obfs?

**Comment by wongsyrone** [comment]
Based on the spec,

> a. Plugin over plugin is NOT supported. Only one plugin can be enabled when a shadowsocks service is started.

http://shadowsocks.org/en/spec/Plugin.html

**Comment by john564** [comment]
Either run the plugins from CMD, and separate script. 
or daisy-chain two instances of shadowsocks together, with a different plugin in each.

**Comment by celeron533** [comment]
You can also let SS-win launch a script which will execute both plug-ins you want.

**Comment by jibon57** [comment]
@celeron533 will you please show an example?

**Comment by chenshaoju** [comment]
For example, You want to use simple-obfs and go-quite on your client site:
```
start obfs-local.exe -s 123.45.67.89 -p 1234 -l 9876 --obfs http
start gq-client.exe -l 8765 -p 9876 -s 127.0.0.1
start shadowsocks.exe
```
And setup your shadowsocks server as 127.0.0.1 , Port as 8765 .

**Comment by jibon57** [comment]
@chenshaoju it's still remain same as my problem. I mean need to use external script.. At present I am doing almost like that. 
ShadowSocks + Obfs ==> Kcptun (external script) 

So, what I have deserved `ShadowSocks + Obfs + Kcptun`  (no external script) .. same as MacOS client.
