### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by qiyongxiao** [shadowsocks/shadowsocks-windows#1939]
### 1.Shadowsocks version 
4.0.10

### 2.Environment(Operating system, .NET Framework, etc) 
- OS:
   Windows 10 17713rs5
   .Net Framework4.7

### 3.All setting
![image](https://user-images.githubusercontent.com/7349963/43190678-2e5b10ec-902c-11e8-9e7a-e724eeb0bd56.png)

### 4.Open www.google.com.hk with QQBrower based on chrome cores
![image](https://user-images.githubusercontent.com/7349963/43190849-926044e0-902c-11e8-932b-45f5e4406749.png)

### 5.Proxy logs 
```
=========================
[2018-07-25 16:33:14] System.Net.Sockets.SocketException (0x80004005): 不知道这样的主机。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

```
## 6.Here is the settings in windows system
- set Internet Exploere 
![image](https://user-images.githubusercontent.com/7349963/43191017-e59e4580-902c-11e8-99b0-030dce1ba81d.png)

- win-->settings-->Network Internet -->proxy
![image](https://user-images.githubusercontent.com/7349963/43191109-1652da2e-902d-11e8-9681-e87e79a3f7ae.png)

### <font color="red" size=3> How do I use shadowsocks 4.0.10 with windows10 17713rs5?</font>

**Comment by chenshaoju** [comment]
```[2018-07-25 16:33:14] System.Net.Sockets.SocketException (0x80004005): 不知道这样的主机。```

Please use ping command to ping your server, Can get the response or just timeout? (maybe is unknown host).

**Comment by qiyongxiao** [comment]
@chenshaoju it's time out. please see the above of "proxy logs"
![image](https://user-images.githubusercontent.com/7349963/43191928-ccdf7918-902e-11e8-83a4-c497231e9afa.png)

**Comment by chenshaoju** [comment]
No, I Mean Ping your Shadowsocks Server.
