### ISSUE TITLE
 System.ArgumentException: Font 'Consolas' does not support style 'Regular'.

### ISSUE THREAD

**Issue by hey22222** [shadowsocks/shadowsocks-windows#1940]
[2018-07-26 00:12:35] [E] System.ArgumentException: Font 'Consolas' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize)
   at Shadowsocks.Model.LogViewerConfig..ctor()
   at Shadowsocks.Model.Configuration.Load()
   at Shadowsocks.Controller.ShadowsocksController..ctor()
   at Shadowsocks.Program.Main()

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1848

**Comment by chenshaoju** [comment]
简单地说，你的系统里缺少一种名为 Consolas 的字体。

你能在字体里找到这个字体吗？如果能，双击这个字体，能看到一个名为 Consolas  常规的样式吗？

![image](https://user-images.githubusercontent.com/515763/43244890-f7ecbb74-90de-11e8-98ac-a4e2b970cffa.png)

![image](https://user-images.githubusercontent.com/515763/43244896-fe2c6746-90de-11e8-9a2d-918d4bb6e608.png)

**Comment by hey22222** [comment]
好的，问题已经解决，但是环境部署好后不起作用怎么破，一样的设置，台式机能翻墙了，笔记本还是没效果，大佬知道大概会有什么原因嘛？

**Comment by chenshaoju** [comment]
SS的日志中有什么显示吗？

**Comment by hey22222** [comment]
[2018-07-26 15:55:00] Shadowsocks started
[2018-07-26 15:55:00] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================
，对比了下笔记本和电脑的日志，都是一个样子的，而且好像是在正常运行了的啊

**Comment by chenshaoju** [comment]
如果你访问了被墙的网站，并且不成功的情况下，日志中还是这几行内容，可能和你的代理设置有关。

请右击托盘区的纸飞机小图标，确保选中了“启用系统代理”，代理模式为“PAC”。如果仍然不行，请在此右击托盘区的小图标，选择PAC，然后点击“从GFWList更新本地PAC”，然后再看看。

**Comment by hey22222** [comment]
上面所说的配置都没错，我试了下点击“从GFWList更新本地PAC”，然后提示 ”未发现更新，如有问题请提交给GFWList”

**Comment by chenshaoju** [comment]
你有Firefox吗？能否做一个这样的测试，单独配置Firefox代理，然后取消SS的系统代理，看看能否使用？

![37390878-680ff942-27a4-11e8-81f1-54edfe7658d9](https://user-images.githubusercontent.com/515763/39850547-8c82ab36-5444-11e8-9030-f22b88125b54.png)

**Comment by hey22222** [comment]
Firefox配置完后ss取不取消代理都能翻了，我依样画葫芦在chrome也设置成功能翻了，多谢。不过，这是什么原因呢，有不设置能和我台式一样配置好ss就直接能用的方法吗

**Comment by chenshaoju** [comment]
有可能你的系统的PAC代理有问题，指定后Firefox就全局翻墙了。

你的操作系统是什么？Win10还是Win7？

**Comment by hey22222** [comment]
win7 64位

**Comment by hey22222** [comment]
可以了，局域网自动检测那边打勾就自动识别了
