### ISSUE TITLE
突然PC端无法使用 但手机端就可以使用

### ISSUE THREAD

**Issue by rebornwanga** [shadowsocks/shadowsocks-windows#1941]
使用4.0.10版本
前几天突然PC端就无法正常使用 使用全局代理无法上网 有时候会突然能用一下 
但手机可以 在同一个WiFi下
换个无线网络也可以正常使用 
在issue里查看了发现了类似的问题 但没有找到解决方案

**Comment by rebornwanga** [comment]
win7＆win10都是这种情况 
运行 ping 127.0.0.1
显示小于1ms

**Comment by rebornwanga** [comment]
[2018-07-26 14:43:36] hk01.ipip.pm:52362 timed out
[2018-07-26 14:43:41] hk01.ipip.pm:52362 timed out
[2018-07-26 14:43:41] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-07-26 14:44:59] hk01.ipip.pm:52362 timed out
[2018-07-26 14:44:59] hk01.ipip.pm:52362 timed out
[2018-07-26 14:44:59] hk01.ipip.pm:52362 timed out
[2018-07-26 14:45:55] Shadowsocks started
[2018-07-26 14:45:55] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-07-26 14:46:08] connect to www.googleapis.com:443
[2018-07-26 14:46:09] connect to www.google.com:443
[2018-07-26 14:46:13] connect to www.googleapis.com:443
[2018-07-26 14:46:13] hk01.ipip.pm:52362 timed out
[2018-07-26 14:46:14] hk01.ipip.pm:52362 timed out
[2018-07-26 14:46:18] hk01.ipip.pm:52362 timed out

**Comment by chenshaoju** [comment]
请记得删去日志里的服务器信息。

从日志里来看，这意味着从你的计算机到SS服务器超时了，端口没有反应。

能否测试一下 tcping ，看看SS无法使用的时候，从你的计算机到SS服务器的端口是否通？

你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。

这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
```
tcping -t 123.45.67.89 9876
```
其中 123.45.67.89 替换为你的SS服务器地址， 9876 替换为你的你的SS端口，然后回车，这个测试会持续下去，按下Ctrl + C即可停止，但是暂时不要按 Ctrl + C 。

此时，会显示 Port is open ，这说明端口通，然后正常使用SS。

当发现SS不通的时候，提示是否变成了 No response ？

**Comment by rebornwanga** [comment]
麻烦了 
Probing 74.117.182.136:52362/tcp - No response - time=2000.882ms 一直显示这个

**Comment by chenshaoju** [comment]
74.117.182.13 这个IP看起来很像被GFW污染的IP，我Ping了你一下你日志中的域名，IP不是这个。

你的SS服务应该是购买的，如果是，请与你的SS服务商联系。

**Comment by rebornwanga** [comment]
好的

**Comment by rebornwanga** [comment]
是购买的

**Comment by rebornwanga** [comment]
但我用手机可以用 手机开热点电脑也可以用 这是什么原因呢

**Comment by chenshaoju** [comment]
可能和DNS有关？你电脑的DNS是自动获取的吗？还是手动指定的？

**Comment by rebornwanga** [comment]
自动获取的

**Comment by chenshaoju** [comment]
你可以试一下，将你SS服务商提供的SS服务器域名填写到 https://www.websitepulse.com/help/testtools.hostname-test.html ，转换成IP后，将IP地址填写到SS客户端里再试试，应该就可以了。

**Comment by rebornwanga** [comment]
可以了 谢谢
