### ISSUE TITLE
###decryption error

### ISSUE THREAD

**Issue by vansi1989** [shadowsocks/shadowsocks-windows#1942]
### Shadowsocks version / 影梭版本
V4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 1803(OS 内部版本17134.191) 
.NET Framework-----v4.0.30319

### Steps you have tried / 操作步骤
![i u5y6 _bm_ 7vh4s a8m67](https://user-images.githubusercontent.com/19898356/43314100-7ffbaae4-91c4-11e8-894f-260120d4dcf2.png)
![g4 n6rwrnukcz kbkp4nl6](https://user-images.githubusercontent.com/19898356/43314108-844a8eda-91c4-11e8-9213-437af257f288.png)

### What did you expect to see? / 期望的结果
去除此错误，新手，不知道描述够不够清楚，请赐教。

### What did you see instead? / 实际结果
经过N遍的尝试依然失败。我有两台电脑，win10版本完全一致，设置也应该完全一致(我已经对照设置N遍了，应该不会错，包括ss以管理员模式启动)，但另一台就没有报错，上google也正常。而这一台就偶尔能连上一下。
ps:我将“问题电脑”重装系统，以确保和“正常电脑”一致，刚装完系统是可以的，但重启后就出现以上描述问题了。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![6_x 8bffoogt37 c 8i 9](https://user-images.githubusercontent.com/19898356/43313980-2371ffe4-91c4-11e8-9a94-78f7cef3d597.jpg)
![um teaj m_e kxe 2 vd](https://user-images.githubusercontent.com/19898356/43314320-2a1ff9bc-91c5-11e8-9c95-32d0eb178f23.jpg)
![s cm ye 2aprb87ab5ro](https://user-images.githubusercontent.com/19898356/43314435-7d37feb0-91c5-11e8-9f5d-aabe672f3256.png)

**Comment by chenshaoju** [comment]
先确认一下，你的服务商使用的是SS还是SSR？

**Comment by vansi1989** [comment]
我不知道，怎么看是ss还是ssr呢？我是在官网直接买的
![image](https://user-images.githubusercontent.com/19898356/43323463-4fa9db84-91e4-11e8-9e08-2becbe96d222.png)

**Comment by chenshaoju** [comment]
看了一下，应该是SS。

不过你的问题比较难确定，请尝试升级到最新版本的SS看看？
https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by chenshaoju** [comment]
这个东西的意思是连接被重置。

你用的SS服务商是否有终端数限制？比如一个帐号只允许特定数量以内的终端，比如３个终端同时用就会切断链接之类的？

**Comment by vansi1989** [comment]
Hi，
   感谢你的耐心回复。
   我试过几个版本都不行，可是今天在www.shadowsocks.com的下载栏里看到发布的是4.0.6版本的，下了一个，基本不弹这个错误了，不知道是不是这个版本log信息没打印。总体来说，问题基本解决，可以上网了，偶尔一下连不上，可以接受。

**Comment by chenshaoju** [comment]
感觉是有某种干扰，但是无法确定。
