### ISSUE TITLE
确保了服务器配置可用，笔记本电脑使用拨号链接校园网络，ss无法正常使用。为什么？

### ISSUE THREAD

**Issue by ZakeyDrower** [shadowsocks/shadowsocks-windows#1946]
确保了服务器配置可用，笔记本电脑使用拨号链接校园网络，ss无法正常使用。为什么？
奇怪的是，虽然没法访问墙外网站，但是chrome浏览器下可正常接收facebook的消息推送

**Comment by chenshaoju** [comment]
在拨号成功后，请退出SS，然后再打开SS即可。

**Comment by kaiko-www** [comment]
> 在拨号成功后，请退出SS，然后再打开SS即可。

可否解释一下原理?

**Comment by chenshaoju** [comment]
@kaiko-www 目前怀疑和编码有关，中文的话，拉取到的连接名是一堆乱码。

**Comment by shysters** [comment]
校园宽带准入的软件禁止这样的代理行为，接入的设备认证发现时代理可能就被禁止联网。
