### ISSUE TITLE
win10 UTF8环境下PAC切换全局报错窗口乱码

### ISSUE THREAD

**Issue by Conight** [shadowsocks/shadowsocks-windows#1947]
> win10 UTF8环境下PAC切换全局报错窗口乱码

![1](https://user-images.githubusercontent.com/12389161/43518702-7111a6ba-95bf-11e8-969e-57dbe94e751e.jpg)
![2](https://user-images.githubusercontent.com/12389161/43518704-72e809fc-95bf-11e8-8066-a9a8eaf15cbd.jpg)

- env

![1](https://user-images.githubusercontent.com/12389161/43518766-9e752384-95bf-11e8-84d8-76426240620a.jpg)
![2](https://user-images.githubusercontent.com/12389161/43518770-a019d388-95bf-11e8-8fba-3228ec299301.jpg)

- Shadowsocks 4.0.10.0

![Shadowsocks 版本ver](https://user-images.githubusercontent.com/12389161/43517794-7e6a529c-95bc-11e8-8672-0d911de13259.jpg)

- `win10` `.NET 4.0.30319`

![win10 ver](https://user-images.githubusercontent.com/12389161/43517927-f4d31a18-95bc-11e8-991b-cbecf5e7d29d.jpg)

![.NET ver](https://user-images.githubusercontent.com/12389161/43517949-00276202-95bd-11e8-9aba-2ce90f05cfee.jpg)

- config.json

```json
{
  "configs": [
  ],
  "strategy": null,
  "index": 1,
  "global": true,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": ""
  }
}
```

- log

```log
[2018-08-01 19:04:33] Started SIP003 plugin for XX.XX.XX.XX:XX on 127.0.0.1:4787 - PID: 15436
[2018-08-01 19:04:33] Shadowsocks started
[2018-08-01 19:04:33] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================
```

**Comment by chenshaoju** [comment]
如果你的操作系统设定是英文，那么SS的界面也应该英文的，请问这个提示以外，界面的其他部分显示的是中文还是英文？我测试了一下，英文的系统提示也应该是英文的。

![image](https://user-images.githubusercontent.com/515763/43629524-14cc8aa6-9730-11e8-9d75-3f9e609a7a27.png)

**Comment by Conight** [comment]
@chenshaoju  是英文，只有在切换的时候会提示乱码。不会影响正常使用

![1](https://user-images.githubusercontent.com/12389161/43636193-f21ba8b6-9743-11e8-82b5-924f53325f4d.jpg)

![conight_2018-08-03_17-38-44](https://user-images.githubusercontent.com/12389161/43636250-1b7a5b80-9744-11e8-92ed-a072c27e5cfd.jpg)

![1](https://user-images.githubusercontent.com/12389161/43636264-25a1d110-9744-11e8-98f1-3746bd3b17c0.jpg)

![ERROR_GIF](https://user-images.githubusercontent.com/12389161/43636373-796fd940-9744-11e8-8cdb-e932d306c2ca.gif)

**Comment by celeron533** [comment]
Try uncheck that beta UTF8 option.

![](https://user-images.githubusercontent.com/12389161/43518766-9e752384-95bf-11e8-84d8-76426240620a.jpg)
