### ISSUE TITLE
程序无法打开

### ISSUE THREAD

**Issue by liriqingone** [shadowsocks/shadowsocks-windows#1951]
![1](https://user-images.githubusercontent.com/37327205/43620038-584c24da-9703-11e8-93d8-94869792f9b3.PNG)

**Comment by chenshaoju** [comment]
１.请确保已经安装了最新的 Microsoft .NET Framework ：
https://www.microsoft.com/net/download/dotnet-framework-runtime

２.请确保安装了３２位的 Microsoft Visual C++ 2015 Redistributable ：
https://www.microsoft.com/zh-CN/download/details.aspx?id=53840
