### ISSUE TITLE
遇到https会一直“正在建立安全连接”

### ISSUE THREAD

**Issue by FHZDCJ** [shadowsocks/shadowsocks-windows#1953]
系统版本：Windows教育版，已更新所有补丁，当前系统是最新版本
影梭版本：4.0.9(由4.0.10回退至4.0.9且无改善)
浏览器：Chrome67.0.3396.99（测试过多版本都是同样的问题）
DNS：首选223.5.5.5 备选223.6.6.6（使用阿里DNS）
问题描述：加载大部分https协议网站时浏览器左下角都会长时间显示“正在建立安全连接”，此时如果我在shadowsocks上右键，选择PAC，勾选或取消勾选“保护本地PAC”选项，加载了许久仍在建立安全连接的网页就会瞬间开始加载，并马上加载完成(100M宽带)

**Comment by chenshaoju** [comment]
你的SS服务是买的还是自己搭的？

如果是自己搭的，你是否有使用插件，比如simple-obfs或者kcptun之类的？

或者，是否有使用TCP Fast Open之类的参数？

**Comment by FHZDCJ** [comment]
@chenshaoju 是自己搭建的，没有使用插件，也没有设置参数，这个问题之前没有(Windows 10 企业版)，后使用官网镜像安装Windows10教育版才出现这个问题

**Comment by chenshaoju** [comment]
请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，三行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。

重启后看看效果是否有改善。

**Comment by guxin0123** [comment]
chrome内核的浏览器  “正在建立安全连接” 解决方案
删除 注册表 HKEY_CURRENT_USER\Software\Microsoft\SystemCertificates\Root
