### ISSUE TITLE
系统睡眠后再启动提示热键注册失败

### ISSUE THREAD

**Issue by giftzn** [shadowsocks/shadowsocks-windows#1954]
### Shadowsocks version / 影梭版本
Pre-release 4.1.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 企业版 17134.191

### Steps you have tried / 操作步骤
设备进入睡眠再启动

### What did you see instead? / 实际结果
启动后弹框提示：热键注册失败

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
无相关日志，已经确认没有其他程序占用热键

**Comment by giftzn** [comment]
是SSD，不是卡顿的，你可能没开启快捷键设置里的“启动时注册热键”，我忘说这个了

**Comment by chenshaoju** [comment]
@giftzn 确认了，复现步骤如下：
设置热键并启用“启动时注册热键”后确定。
进入休眠／待机状态，无时间长短要求。
再次唤醒计算机，出现注册热键失败的提示。
如果尝试注册全部热键，会注册失败。

@celeron533

**Comment by celeron533** [comment]
唤醒后重复注册热键了。。。

**Comment by voq** [comment]
恩，系统唤醒时会调用Start()，之前没注意。

**Comment by voq** [comment]
@celeron533  呃，我看你改了点东西没有用我的PR，那你那直接改好了....

**Comment by chenshaoju** [comment]
@giftzn 请尝试该自动编译的版本，是否解决了问题：
https://ci.appveyor.com/project/celeron533/shadowsocks-windows-3j4p4/build/4.1.0.1/job/mg63ga9c78v61f6d/artifacts

**Comment by giftzn** [comment]
这个版本已经解决，谢谢
