### ISSUE TITLE
portable mode 是做什么用的？

### ISSUE THREAD

**Issue by Crafsman** [shadowsocks/shadowsocks-windows#1957]
请问，版本4.1.0的那个`portable mode`是做什么用的？

**Comment by celeron533** [comment]
切换temp文件夹位置：
勾选：使用当前文件夹
不勾选：使用系统文件夹
https://github.com/shadowsocks/shadowsocks-windows/blob/80e4bec8c823c0ac2f46686b6e745da2cf49d0c0/shadowsocks-csharp/Util/Util.cs#L39

**Comment by Crafsman** [comment]
这个temp文件， 放在当前文件夹和放在系统文件夹有什么讲究吗?
它们有啥其他的影响吗？
还是都可以，看偏好了？

**Comment by chenshaoju** [comment]
是的，看偏好了，有些人（ｍｅ）喜欢将应用产生的数据都放在一个文件夹，有些人则认为临时数据该放在临时文件夹（ %temp% ）。
