### ISSUE TITLE
Windows7打不开最新版 报错字体不支持样式

### ISSUE THREAD

**Issue by 464979532** [shadowsocks/shadowsocks-windows#1958]
![3](https://user-images.githubusercontent.com/3524108/43936420-eb7883a2-9c8a-11e8-9692-92c92ed1d167.jpg)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1940

**Comment by 464979532** [comment]
谢谢，安装consolas字体后解决
