### ISSUE TITLE
forward proxy是作甚么的

### ISSUE THREAD

**Issue by Crafsman** [shadowsocks/shadowsocks-windows#1959]
![forward proxy](https://user-images.githubusercontent.com/15353430/43937268-ff372988-9c9f-11e8-8796-c157a1771983.PNG)

4.1.0版本的 forward proxy是作甚么的？

假如我想用的话，怎么用？

**Comment by Crafsman** [comment]
![server](https://user-images.githubusercontent.com/15353430/43937510-6b4c7730-9ca1-11e8-843e-233ee4ae4ff8.PNG)
代理服务器 不是在这里添加吗？

**Comment by chenshaoju** [comment]
你的意思是指“代理服务器”还是“SS服务器”？

**Comment by Crafsman** [comment]
我的理解是 ss服务器就是代理服务器。

不是吗？

**Comment by chenshaoju** [comment]
不是。。。你正常上网（含未被墙的网站）如果需要通过代理，那么需要设置代理服务器。

SS服务器是指你购买或者搭建的服务器。

前者填写在 Edit Proxy 窗体中，后者填写在 Edit Servers 窗体中。

**Comment by celeron533** [comment]
Direct connect:
```
Your web browser -------(http/socks5) -----> shadowsocks client ---(tunnel)---> shadowsocks server -----> the Internet
```

Forward proxy:
```
Your web browser -------(http/socks5) -----> shadowsocks client ---(tunnel)---> LAN proxy server ---(tunnel)---> shadowsocks server -----> the Internet
```

**Comment by hdzhx** [comment]
关了我也没看懂这个是什么？
