### ISSUE TITLE
去除空白符号

### ISSUE THREAD

**Issue by RogerLiNing** [shadowsocks/shadowsocks-windows#1960]
建议给服务器IP、服务器端口输入框添加自动去除空白的机制(trim)。因为在实际使用的时候，复制IP时可能不小心多了空白符号，会导致无法连接，但是又很难察觉到这个细节。

![image](https://user-images.githubusercontent.com/18111035/44011444-3ea85bda-9eeb-11e8-9736-0adb8cb6be2b.png)

**Comment by chenshaoju** [comment]
你用的版本非常旧了，我测试了最新版，在IP后面加了一个空格，没有问题。

https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by RogerLiNing** [comment]
@chenshaoju 谢谢你的回答，Shadowsocks-4.1.0 版本测试通过。
