### ISSUE TITLE
ConfigForm中一处不安全逻辑

### ISSUE THREAD

**Issue by SoDa-GitHub** [shadowsocks/shadowsocks-windows#1961]
View/ConfigForm.cs第231~237行
236行的LoadSelectedServerDetails函数虽然在函数内检查了index是否越界，以确保LoadSelectedServerDetails自身不会出现异常，但是，当index越界时，下一行

_lastSelectedIndex = ServersListBox.SelectedIndex;

却依然执行，并记录这个错误的越界值。

因此，虽然本次不会异常，当再次触发SelectedIndexChanged时，执行到第233行
ServersListBox.Items[_lastSelectedIndex] = _modifiedConfiguration.configs[_lastSelectedIndex].FriendlyName();

会报错越界并崩溃

**Comment by SoDa-GitHub** [comment]
SelectedIndexChanged缺少166行

            if (_lastSelectedIndex < 0 || _lastSelectedIndex >= ServersListBox.Items.Count)
            {
                _lastSelectedIndex = 0;
            }

这种判断机制

**Comment by SoDa-GitHub** [comment]
231行可以改为
if (_lastSelectedIndex >= 0 && _lastSelectedIndex < _modifiedConfiguration.configs.Count)

**Comment by celeron533** [comment]
Thx. Pull requests are welcome

**Comment by celeron533** [comment]
Merged. Thx @SoDa-GitHub
