### ISSUE TITLE
NewsFlow in Win10's Microsoft Store  can't connect BBC's Rss;

### ISSUE THREAD

**Issue by MrBenWang** [shadowsocks/shadowsocks-windows#1963]
1、I use Chrome ， I can open http://feeds.bbci.co.uk/zhongwen/simp/rss.xml 
2、I install NewsFlow in Microsoft Store，add rss http://feeds.bbci.co.uk/zhongwen/simp/rss.xml ， it can‘t find the website；
3、I use  PAC or Global， the result is the same

Please help me，I want to read with rss。 Thanks！

**Comment by Immueggpain** [comment]
IIRC, store app can't access 127.0.0.1.

**Comment by studentmain** [comment]
try outline-client, it should works with UWP app

**Comment by Immueggpain** [comment]
If you use powershell, try `foreach($f in Get-ChildItem $env:LOCALAPPDATA\Packages) {CheckNetIsolation.exe LoopbackExempt -a "-n=$($f.Name)"}`

**Comment by MrBenWang** [comment]
thanks all!

I just want this app to use shadowsocks.  So I used this command, it works.
`CheckNetIsolation.exe LoopbackExempt –a –n=6958MaxN.Newsflow_5jrsa023thkzc`

I search `CheckNetIsolation`  , find the article from msdn. It might help. 
https://msdn.microsoft.com/en-us/library/windows/apps/Hh780593.aspx
