### ISSUE TITLE
下载最新的版本 发现没有aes-256-gcm这个加密方式了

### ISSUE THREAD

**Issue by Greathfs** [shadowsocks/shadowsocks-windows#1966]

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/44246318-365c5f80-a210-11e8-8b89-882ea297572c.png)

请确保你是在 https://github.com/shadowsocks/shadowsocks-windows/releases 获取的客户端。

**Comment by zxeoc** [comment]
有的，在列表比较靠下的位置

**Comment by Greathfs** [comment]
4.0.9是有的 最新的没发现啊

**Comment by Greathfs** [comment]
不好意思 不好意思 是我没看见
