### ISSUE TITLE
如何禁用pac

### ISSUE THREAD

**Issue by imcaset** [shadowsocks/shadowsocks-windows#1967]
设置里面只有本地pac和在线pac。我完全用不到pac，不知道如何禁用pac
是不是配置文件夹下删除pac.txt后，就能禁用pac

**Comment by studentmain** [comment]
任务栏图标右键->系统代理模式->全局模式

发送自 Windows 10 版邮件应用

发件人: imcaset
发送时间: 2018年8月16日 22:39
收件人: shadowsocks/shadowsocks-windows
抄送: Subscribed
主题: [shadowsocks/shadowsocks-windows] 如何禁用pac (#1967)

设置里面只有本地pac和在线pac。我完全用不到pac，不知道如何禁用pac
是不是配置文件夹下删除pac.txt后，就能禁用pac

**Comment by imcaset** [comment]
我还有其他软件不用ss，只是Firefox全部用ss，能不能禁用pac啊，
我现在都是修改pac文件，全部通过ss连接，我发现不修改pac.txt，好像Firefox也全用ss

**Comment by chenshaoju** [comment]
你好，这种情况取消“使用系统代理”即可，这种情况下PAC和全局模式的虽然选项还在，但是会失效。

**Comment by imcaset** [comment]
就是说不用系统代理，pac就是禁用的吧

**Comment by chenshaoju** [comment]
使得。

**Comment by celeron533** [comment]
只要你开了SS， 本地端口一直会监听全局请求。你可以手动在浏览器里设置相应的全局代理服务器。PAC值不是一种锦上添花的半自动配置机制，让浏览器根据PAC来决定哪些地址走代理。
- 启用系统代理：
SS全局监听，浏览器直接使用代理。
- 启用PAC：
SS全局监听，产生一个PAC文件，并设定IE浏览器的代理定向到PAC规则，浏览器根据PAC内容来决定是否对某一地址使用代理。
