### ISSUE TITLE
非SIP003插件的正确使用方式？

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-windows#1969]
### Shadowsocks version / 影梭版本
4.1.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
WIN7 64bit  .NET Framework4.72

### Steps you have tried / 操作步骤
设置插件参数

### What did you expect to see? / 期望的结果
可启用非SIP003插件

### What did you see instead? / 实际结果
非SIP003插件（原版Kcptun)无效

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
服务器地址：服务器IP
服务器端口：服务器kcptun端口
插件程序：路径\kcptun.exe
插件选项：空
插件参数：-c 路径\config.json
config.json:
{
    "key": "密钥",
    "crypt": "salsa20",
    "mode": "manual",
    "conn": 1,
    "autoexpire": 300,
    "mtu": 1300,
    "sndwnd": 512,
    "rcvwnd": 1024,
    "datashard": 30,
    "parityshard": 15,
    "dscp": 46,
    "nocomp": true,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10,
    "quiet": true
}

使用以上方式，kcptun已启用，实际无效。

改为：
插件程序：路径\kcptun.exe
插件选项：空
插件参数：-key 密钥 -crypt salsa20 -mode manual -conn 1 -autoexpire 300 -mtu 1300 -sndwnd 512 -rcvwnd 1024 -datashard 30 -parityshard 15 -dscp 46 -nocomp true -acknodelay false -nodelay 0 -interval 20 -resend 2 -nc 1 -sockbuf 4194304 -keepalive 10

kcptun已启用，实际仍无效。
请教非SIP003插件的正确使用方式？

**Comment by colalan** [comment]
@chenshaoju  就是说新增加的“插件参数”不适用于非SIP003规范的kcptun吗？哪非SIP003规范的obfs呢？
如不支持，这个功能添加的意义是什么？

**Comment by colalan** [comment]
希望能完善调用CLI插件的功能，配合使用[kcpraw](https://github.com/ccsexyz/kcpraw)实现加速同时突破UDP Qos是有必要的。

**Comment by chenshaoju** [comment]
哦，实际上你使用的是kcpraw，不是kcptun？你应该一开始说清楚，错误的配置会导致不工作。

请尝试只填写插件程序和插件参数，并参考以下插件参数配置：
```
-l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT%  -key 密钥 -crypt salsa20 -mode manual -conn 1 -autoexpire 300 -mtu 1300 -sndwnd 512 -rcvwnd 1024 -datashard 30 -parityshard 15 -dscp 46 -nocomp true -acknodelay false -nodelay 0 -interval 20 -resend 2 -nc 1 -sockbuf 4194304 -keepalive 10
```

由于是盲写的，我并没有使用kcpraw，你可以先试试。

**Comment by colalan** [comment]
代码中可否添加“插件参数”的非空判断。如果“插件参数”非空，则不要生成%SS_LOCAL_HOST%、%SS_LOCAL_PORT% 、 %SS_REMOTE_HOST%、%SS_REMOTE_PORT%，并对插件程序附值。

这样编缉服务器信息如下：
服务器地址：127.0.0.1 <==kcptun本地监听地址
服务器端口：1099 <==kcptun本地监听端口
插件程序：路径\kcptun.exe
插件选项：空
插件参数：-l 127.0.0.1:1099 -r SS服务器地址:SS服务器端口 -key 密钥 -crypt salsa20 -mode manual -conn 1 -autoexpire 300 -mtu 1300 -sndwnd 512 -rcvwnd 1024 -datashard 30 -parityshard 15 -dscp 46 -nocomp true -acknodelay false -nodelay 0 -interval 20 -resend 2 -nc 1 -sockbuf 4194304 -keepalive 10

是否可以这样较简单的实现非SIP003插件的使用呢？

**Comment by chenshaoju** [comment]
根据SIP003的规范： https://github.com/shadowsocks/shadowsocks-org/wiki/Plugin

这几个变量是必定要提供的。

当然，你也可以不理会这些配置，手动设置你的情况。

**Comment by colalan** [comment]
@chenshaoju 谢谢，你的方法是有效的！

**Comment by studentmain** [comment]
@colalan 我尝试实现了一下你说的做法。[这是生成的exe文件](https://down.scsfdx.org/Shadowsocks.exe)，希望你能试试。
在插件参数中可以直接使用%SS_REMOTE_HOST% %SS_REMOTE_PORT%等，当插件选项为空时会将其自动替换为相应值，但同时仍然生成相应环境变量。
SHA1: 1EFB89BA21E0D84B5AA2DA9EED2200B552EDC4BF

**Comment by chenshaoju** [comment]
@studentmain 测试了一下，能兼容符合SIP003规范的插件，因为kcptun的环境没有了，无法测试非SIP003规范的插件。

如果可能，欢迎提交PR。😘

**Comment by celeron533** [comment]
> 改为：
插件程序：路径\kcptun.exe
插件选项：空
插件参数：-key 密钥 -crypt salsa20 -mode manual -conn 1 -autoexpire 300 -mtu 1300 -sndwnd 512 -rcvwnd 1024 -datashard 30 -parityshard 15 -dscp 46 -nocomp true -acknodelay false -nodelay 0 -interval 20 -resend 2 -nc 1 -sockbuf 4194304 -keepalive 10

你至少需要填写要让kcptun监听哪一个本地端口，然后远程的kcptun服务器的IP和端口

插件工作原理实际上只是一个额外的代理链：
直连： ss-win (connect to 202.12.34.56:1234) --> (listening on 0.0.0.0:1234) ss-server
插件： ss-win (connect to 127.0.0.1:9999) --> (listening on 127.0.0.1:9999) kcptun client (connect to 202.12.34.56:4321) --> (listening on 0.0.0.0:4321) kcptun server (connect to 127.0.0.1:1234) --> (listening on 0.0.0.0:1234) ss-server

**Comment by colalan** [comment]
@studentmain 你提供的执行文件有效，确实能在非sip003规范的原版KCPTUN上实现。
原版KCPTUN不支持%SS_LOCAL_HOST% %SS_LOCAL_PORT% %SS_REMOTE_HOST% %SS_REMOTE_PORT%这样的环境变量作为参数，经由你说的自动替换为“127.0.0.1:1099”这样的参数后，确实有效实现原版KCPTUN带参数运行。
但由于是对参数进行变量转换，所以无法支持-c config.json这样的由配置文件运行了。

**Comment by colalan** [comment]
@celeron533 如果插件参数填写为：-l 127.0.0.1:1099 -r 44.55.66.78:1234 -key 8888 -crypt salsa20 -mode manual -conn 1 -autoexpire 300 -mtu 1300 -sndwnd 512 -rcvwnd 1024 -datashard 30 -parityshard 15 -dscp 46 -nocomp true -acknodelay false -nodelay 0 -interval 20 -resend 2 -nc 1 -sockbuf 4194304 -keepalive 10
如你说的，给出确定的kcptun监听端口。
这样也是无法实现的，因为当ss-win设置中“插件程序”为非空时，ss-win自行生成了个%SS_LOCAL_PORT%变量作为它的服务器端口，也就是说ss-win的服务器端口并非KCPTUN参数中定义的监听端口：1099，所以无法完成连接。

**Comment by studentmain** [comment]
@colalan 给个示例配置文件看看？

**Comment by studentmain** [comment]
判断插件参数是不是-c config.json那就过了，说不定某个奇葩插件要求用-d cfg.ini读配置文件呢。
依我看改一下插件的配置部分的代码来得更直接。

**Comment by colalan** [comment]
@studentmain 你的实现方法已经很好了，无必要非得支持配置文件方式。如可能，望并入主分支中。

**Comment by studentmain** [comment]
@chenshaoju @colalan PR已发

**Comment by chenshaoju** [comment]
@colalan 请尝试该版本的SS，是否可以配合非SIP003规范的插件并具备变量的情况下工作：
https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/4.1.1.11/job/ltbdckeq5lhrsmwf/artifacts

**Comment by colalan** [comment]
@chenshaoju 你的这个版本可以配合非SIP003规范的插件运行!

ss-win设置如下:
服务器地址：44.55.66.78 <==示例:SS服务器IP
服务器端口：1234 <==示例:服务器kcptun监听端口

插件程序：D:\KCPTun\KCPTun.exe <==示例:插件路径
插件选项：空
插件参数：-l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT% -key password -crypt salsa20 -mode manual -conn 1 -autoexpire 300 -mtu 1300 -sndwnd 512 -rcvwnd 1024 -datashard 30 -parityshard 15 -dscp 46 -nocomp true -acknodelay false -nodelay 0 -interval 20 -resend 2 -nc 1 -sockbuf 4194304 -keepalive 10

测试了原版kcptun和它的再开发版kcpraw,均可以正确加载运行插件.
good job!

**Comment by chenshaoju** [comment]
@colalan 感谢你的回报，谢谢！ 😘

**Comment by colalan** [comment]
SIP003规范的“插件选项”中的可以不填"-l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT%"这部份。
非SIP003规范插件不知可否做到不在填写参数时必填，就像SIP003规范的插件在填写插件选项时一样，交由代码完成补充。
亦或可以合并SIP003规范和非SIP003规范插件的选项填列，统一它们的参数或选项填列方式，这样就不必区分插件是否符合SIP003规范。

**Comment by chenshaoju** [comment]
主要是无法控制插件的参数， kcptun 用的是 -r 和 -l ，但是别的插件不一定，比如simple-obfs是 -s -p -l ，这个是开发者决定的，控制不了。

**Comment by colalan** [comment]
@chenshaoju 你说的对，毕竟SIP003规范的插件目前只有两个，还是专门针对ss-win再楄写的。无需关心它们的参数形式。

**Comment by colalan** [comment]
小小封议,可否将"插件选项"和"插件参数"的填列合并为一个,加个复选框来对是否SIP003规范进行区分.这对代码处理两种插件的方式也有帮助吧.
因为"插件选项"和"插件参数"对于新手来说理解点难度.

**Comment by studentmain** [comment]
提议把"插件参数"改为"命令行参数"，毕竟很多其他地方说的选项，指的其实是命令行参数。有些人（包括我）咋看来插件选项就是插件参数。

**Comment by celeron533** [comment]
> 提议把"插件参数"改为"命令行参数"

@studentmain PR is welcome :)

**Comment by tatorhan** [comment]
如果用KCPTUN作为加速，SS 4.1.2插件程序、参数都怎么配置

**Comment by chenshaoju** [comment]
请仔细阅读：
https://github.com/shadowsocks/shadowsocks-windows/wiki/%E4%BD%BF%E7%94%A8%E9%9D%9ESIP003%E8%A7%84%E8%8C%83%E7%9A%84%E6%8F%92%E4%BB%B6

**Comment by vinsec** [comment]
> @chenshaoju 你的这个版本可以配合非SIP003规范的插件运行!
> 
> ss-win设置如下:
> 服务器地址：44.55.66.78 <==示例:SS服务器IP
> 服务器端口：1234 <==示例:服务器kcptun监听端口
> 
> 插件程序：D:\KCPTun\KCPTun.exe <==示例:插件路径
> 插件选项：空
> 插件参数：-l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT% -key password -crypt salsa20 -mode manual -conn 1 -autoexpire 300 -mtu 1300 -sndwnd 512 -rcvwnd 1024 -datashard 30 -parityshard 15 -dscp 46 -nocomp true -acknodelay false -nodelay 0 -interval 20 -resend 2 -nc 1 -sockbuf 4194304 -keepalive 10
> 
> 测试了原版kcptun和它的再开发版kcpraw,均可以正确加载运行插件.
> good job!

it works and thanks for contribuying your solution:)
