### ISSUE TITLE
[Wiki] non-sip003 plugin usage manual merge request

### ISSUE THREAD

**Issue by chenshaoju** [shadowsocks/shadowsocks-windows#1971]
I wrote a manual for non-sip003 standard plugin usage.

Please merge to the wiki page.

Preview: [English](https://github.com/chenshaoju/shadowsocks-windows/wiki/Working-with-non-SIP003-standard-Plugin) [Chinese](https://github.com/chenshaoju/shadowsocks-windows/wiki/使用非SIP003规范的插件)

Sourcecode: https://gist.github.com/chenshaoju/9796bb4783b81f64d718065801b085ca

No copyright, Feel free to use or modify it. 

Thanks.

**Comment by colalan** [comment]
@chenshaoju have you tried this? if not, please test it!

**Comment by chenshaoju** [comment]
@colalan I used plugin is SIP003 standard, so I only tested with cmd.exe, use ` c:\windows\system32\cmd.exe` and `/c echo %SS_REMOTE_HOST% >d:\test.txt` to test environment variables is working or not.

I will try kctpun as sample.

**Comment by colalan** [comment]
@chenshaoju  please use non-sip003 test

**Comment by chenshaoju** [comment]
Interesting, If using Shadowsocks for Windows, it will not work, kcptun process will keep restart.

But if I set the same config with environment variables manually, It can work.

![image](https://user-images.githubusercontent.com/515763/44297407-8ec05980-a303-11e8-9f74-c4b34ae67d06.png)

I think the document is all right, but some wrong in this process.

For cautiously, I have changed the title.

**Comment by chenshaoju** [comment]
I think what happens here.

Shadowsocks for Windows directly give these environment variables name to the plugin.
![image](https://user-images.githubusercontent.com/515763/44297792-14df9e80-a30a-11e8-980b-cdc995f946fa.png)

Unfortunately, It's will not work, the plugin usual is unable to process these environment variables.

But these environment variables can pass by cmd.exe, If I set Plugin Program is:
```C:\Windows\system32\cmd.exe```

And set Plugin Arguments is:
```/c D:\Shadowsocks\client_windows_amd64.exe -l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT% --key 123456 --crypt salsa20 --mode fast2```

 It's can work.
![image](https://user-images.githubusercontent.com/515763/44297889-b7e4e800-a30b-11e8-8f89-cd03d9632c75.png)

There is some coding work here. 😅

**Comment by studentmain** [comment]
大概知道为什么有问题了，简单的说，cmd才会解释环境变量。

**Comment by celeron533** [comment]
Added to:

[使用非SIP003规范的插件](https://github.com/shadowsocks/shadowsocks-windows/wiki/%E4%BD%BF%E7%94%A8%E9%9D%9ESIP003%E8%A7%84%E8%8C%83%E7%9A%84%E6%8F%92%E4%BB%B6)

[Working with non SIP003 standard Plugin](https://github.com/shadowsocks/shadowsocks-windows/wiki/Working-with-non-SIP003-standard-Plugin)

**Comment by chenshaoju** [comment]
Thanks for your work!
