### ISSUE TITLE
服务器地址如何获取

### ISSUE THREAD

**Issue by hztgz** [shadowsocks/shadowsocks-windows#1975]
1、想咨询下如何获取服务器地址：
2、mac 上如何使用。

**Comment by chenshaoju** [comment]
１.你可以自行搭建一个SS服务端，或者找第三方购买，不过此处不能提供这方面的信息。
２.Mac上可以考虑使用 https://github.com/shadowsocks/ShadowsocksX-NG

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/44309432-1b990f00-a3f9-11e8-95eb-cf546a25fa0f.png)
