### ISSUE TITLE
Windows 10 RS5，当处于 PAC 模式时，每次睡眠唤醒后都多出一个 pacjsworker.exe 进程

### ISSUE THREAD

**Issue by l1ken** [shadowsocks/shadowsocks-windows#1979]
也许与 RS5 的新沙盒有关。https://twitter.com/epakskape/status/1007316208087994368

### Shadowsocks version / 影梭版本
4.1.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 build 17741

### Steps you have tried / 操作步骤
1. 切换到 PAC 模式
2. Windows 选择睡眠，然后重新登陆

### What did you expect to see? / 期望的结果
不要新出现 pacjsworker.exe

### What did you see instead? / 实际结果
新出现了一个 pacjsworker.exe

**Comment by chenshaoju** [comment]
Google了一下，整个互联网只有另一个SSR的issue中提到了这个文件。

![image](https://user-images.githubusercontent.com/515763/44354898-a4897680-a4dd-11e8-801c-cddc00ecf18e.png)

你能把这个 exe 上传上来看看吗？或者打包成 zip 上传也行。

**Comment by l1ken** [comment]
嗯，RS5 (version 1809) 后系统就自带这个文件了
[pacjsworker.zip](https://github.com/shadowsocks/shadowsocks-windows/files/2304344/pacjsworker.zip)

**Comment by chenshaoju** [comment]
https://www.virustotal.com/#/file/b48eec1a68e933b7f26fb041f843240346920aaeb261131334eefc09fd90d5c8/details

没有数字签名，看起来很像是微软签发的文件。

从文件说明来看（HTTP Auto Proxy Detection Worker Process），这看起来是一个自动代理检测工具。

但是从文件名来看，这看起来很像是用于处理PAC中JS脚本的工具。

因为这是微软的决定，这边控制不了。

如果你非常在意，可以你停用SS的系统代理，使用Firefox或者SwitchyOmega单独指定代理，应该就不会出现这个了。

**Comment by l1ken** [comment]
最后发现是 PacUrl 后面的参数。每次设置系统代理的时候就会有新的参数，系统就会启动新进程进行处理。影梭这边有功能依赖这些参数，确实不太好处理。我自己本地 fork 了一份，删掉了参数。多谢帮助啦！

**Comment by chenshaoju** [comment]
此问题在升级到1809后出现，在一些论坛也有该问题报告：
https://steamcn.com/t430331-1-1

初步研究了一下，这个 pacjsworker.exe 是经由WinHttpAutoProxySvc服务（WinHTTP Web Proxy Auto-Discovery Service）启动的，这个服务无法通过重新启动或者停止来清除这些 pacjsworker.exe 进程，如果尝试结束 pacjsworker.exe 的任务，会自动重新启动该进程，只能重新启动计算机。

当然，也可以找到WinHttpAutoProxySvc服务所在的svchost.exe进程然后结束，但是不推荐这样。

查了一下文档：
https://docs.microsoft.com/en-us/windows/desktop/winhttp/winhttp-autoproxy-support
https://docs.microsoft.com/en-us/windows/desktop/winhttp/autoproxy-issues-in-winhttp

不知道是否能有优化的余地？

@celeron533

**Comment by changjiangblog** [comment]
请问大家解决了吗

**Comment by changjiangblog** [comment]
求一个解决方法，我的电脑现在很多这个进程。

**Comment by chenshaoju** [comment]
@changjiangblog 这个问题和微软改变了PAC的处理机制有关，可能得等维护人员修改程序。

目前，除开重新启动计算机，尽量减少切换服务器，减少修改代理模式以外，暂时没有较好的解决办法。

**Comment by SamuelYG** [comment]
我刚发现这个问题，数了下竟然有七八十个进程😱（看来只好暂时不睡眠电脑了）

**Comment by changjiangblog** [comment]
对，加起来就

> 我刚发现这个问题，数了下竟然有七八十个进程😱（看来只好暂时不睡眠电脑了）

对，加起来就特别占资源了，只能期待开发者解决了

**Comment by dspjm** [comment]
我也有这个问题

**Comment by dspjm** [comment]
微软有bug了吗，需要去报吗？

**Comment by dspjm** [comment]
微软有个bug了，大家去upvote和评论催微软修一下吧 https://aka.ms/AA33ywa

**Comment by Joelism** [comment]
Hi, 我根据 @l1ken 评论的方法删去这行地址的参数后 https://github.com/shadowsocks/shadowsocks-windows/blob/98538e32c043a8d1c0cb57937c6c9a19c4d2e380/shadowsocks-csharp/Controller/Service/PACServer.cs#L54 系统就不会启动新进程了。

在我有限的测试中，本地更改完 pac 后，只要切到全局再切到 pac 模式就能更新系统 pac。不知道可不可以在软件层面做一些操作。

当然这只是不完美的 workaround，而且会使“保护本地 PAC”功能不可用。在微软修复这个问题以前，希望大神们能找到更好的方法。

**Comment by dspjm** [comment]
@Joelism 使用这个workaround是需要改代码并重编译吗？有没有现成的fork之类的，谢谢。

**Comment by Nolancie** [comment]
这个问题不知道新版的1901版的WINDOWS有没有解决。

**Comment by Nolancie** [comment]
是的，有必要反馈。我等下也去反馈一个。

changJiang <notifications@github.com> 于2018年12月3日周一 下午9:54写道：

**Comment by Nolancie** [comment]
> > 这个问题不知道新版的1901版的WINDOWS有没有解决。
> 
> 所以大家赶紧向微软报告这个bug吧

必要要反馈了，这个问题相当严重。尤其是开了几十个进程之后，对CPU跟硬盘都是负担。

**Comment by Feketerigo0827** [comment]
请问4.13 prerelease版本中的 Fix sysproxy hanging issue 针对的是否是这个问题呢

**Comment by celeron533** [comment]
@Feketerigo0827 release notes 里面笔误。实际上没有这个。

**Comment by jen-ping** [comment]
每运行一次，就增加７８个甚至十几个进程！问题非常明显，希望微软尽快解决！

**Comment by tlanyan** [comment]
Hello，我（应该）已经解决这个问题并发布了编译后的文件，详情请看：系[统出现大量HTTP Auto Proxy Detection Worker Process](https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/)

没时间看的可直接下载编译好的exe测试：[ShadowSocks-4.1.4-1.zip](http://39.105.118.158/Shadowsocks-4.1.4-tlanyan2.zip)

**Comment by KIRI-Z** [comment]
> Hello，我（应该）已经解决这个问题并发布了编译后的文件，详情请看：系[统出现大量HTTP Auto Proxy Detection Worker Process](https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/)
> 
> 没时间看的可直接下载编译好的exe测试：[ShadowSocks-4.1.4-1.zip](http://39.105.118.158/Shadowsocks-4.1.4-tlanyan2.zip)

你好，我看到你的pr里提交的是你博客中所说的方案二。我在尝试方案一时遇到了点问题
```
// 文件： shadowsocks-csharp\Controller\Service\PACServer.cs
public void UpdateConfiguration(Configuration config)
{
  this._config = config;

  if (config.secureLocalPac)
  {
    // 注释掉部分
    // var rd = new byte[32];
    // RNG.GetBytes(rd);
    // PacSecret = $"&secret={Convert.ToBase64String(rd)}";
    // **下面这部分4.1.4版本的ss中是没有的 如果要添加的话 PAC_SECRET_FILE 未声明**
    if (!File.Exists(PAC_SECRET_FILE))
    {
      var rd = new byte[32];
      RNG.GetBytes(rd);
      string secret = Convert.ToBase64String(rd);
      PacSecret = $"secret={secret}";
      File.WriteAllText(PAC_SECRET_FILE, secret);
    }
    else
    {
      PacSecret = $"secret={File.ReadAllText(PAC_SECRET_FILE)}";
    }
    // ----------------------------------- 以上部分 -----------------------------------
  }
  else
  {
    PacSecret = "";
  }
  // 注释掉部分
  // PacUrl = $"http://127.0.0.1:{config.localPort}/pac?t={GetTimestamp(DateTime.Now)}{PacSecret}";
  PacUrl = $"http://127.0.0.1:{config.localPort}/pac?{PacSecret}";
}
```

**Comment by tlanyan** [comment]
@KIRI-Z 是编译不通过的问题吗？
我博客中给出的代码不完整，你要在类中新增一个`PAC_SECRET_FILE`常量:

`private const string PAC_SECRET_FILE = "pac-secret.txt";`

**Comment by KIRI-Z** [comment]
> @KIRI-Z 是编译不通过的问题吗？
> 我博客中给出的代码不完整，你要在类中新增一个`PAC_SECRET_FILE`常量:
> 
> `private const string PAC_SECRET_FILE = "pac-secret.txt";`

已解决，谢谢！

**Comment by dspjm** [comment]
> 
> 
> Hello，我（应该）已经解决这个问题并发布了编译后的文件，详情请看：系[统出现大量HTTP Auto Proxy Detection Worker Process](https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/)
> 
> 没时间看的可直接下载编译好的exe测试：[ShadowSocks-4.1.4-1.zip](http://39.105.118.158/Shadowsocks-4.1.4-tlanyan2.zip)

支持加入ss官方版本，不胜其烦。别等微软了。

**Comment by database64128** [comment]
不需要修复了，在最新预览版18334中，只需要睡眠再唤醒，多余的pacjsworker.exe就会消失。

**Comment by database64128** [comment]
在19H1预览版18351和20H1预览版18850中，pacjsworker.exe的行为是一致的，旧的进程会在5分钟后自动退出。因此，将来这个issue只会影响1809这个系统版本。我觉得这个issue可以关闭了。

**Comment by htetwai12** [comment]
#Khitoe

**Comment by Feketerigo0827** [comment]
> 在19H1预览版18351和20H1预览版18850中，pacjsworker.exe的行为是一致的，旧的进程会在5分钟后自动退出。因此，将来这个issue只会影响1809这个系统版本。我觉得这个issue可以关闭了。

19H1不知道要什么时候才能有正式版，而且说不定又要想1809一样延迟推送。预览版的特性能否保持到正式版也是问题。

**Comment by database64128** [comment]
@Feketerigo0827 如果你像我一样长期有用预览版，你就会知道，现在这个时期Fast Ring的预览版会和将来的正式版几乎无区别。目前的18362极有可能成为1903的正式build。

**Comment by ZeddG93** [comment]
1809版本可以用脚本杀掉这个进程树。（仅供强迫症用户使用
```powershell
if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs; exit }

$list = Get-Process -Name pacjsworker

if($list.Length -gt 0){
    $childId = $list[0].Id
    $instance = Get-CimInstance Win32_Process -Filter "ProcessId = '$childId'"
    $parent = Get-Process -Id $instance.ParentProcessId
    Start-Process $parent.Kill() -Verb runAs
}
```

**Comment by AnyWAT** [comment]
1903来了
![image](https://user-images.githubusercontent.com/37962734/55767449-92c80400-5aab-11e9-98f6-1467dff5bcf0.png)

**Comment by ZeddG93** [comment]
> 1903来了
> ![image](https://user-images.githubusercontent.com/37962734/55767449-92c80400-5aab-11e9-98f6-1467dff5bcf0.png)

面向普通用户推送是五月下旬。

**Comment by AnyWAT** [comment]
😋非普通用户一枚？

**Comment by celeron533** [comment]
见到有网友安装后蓝屏或者安装过程中回滚了，win10每次更新都让人惊喜

**Comment by AnyWAT** [comment]
一次过。。。

**Comment by ZeddG93** [comment]
> 见到有网友安装后蓝屏或者安装过程中回滚了，win10每次更新都让人惊喜

这种通常都是用户程序/驱动的问题多。我台式和sbook基本都能正常升级。

**Comment by lzm04521** [comment]
1903依然也有这个问题，测试过了

**Comment by chenshaoju** [comment]
测试了一下，该问题在 Windows 10 1903的表现是，一段时间后（5分钟？10分钟？）多余的进程会自动消失：
![2019-04-26](https://user-images.githubusercontent.com/515763/56788016-ddc67300-6830-11e9-91ae-3061db746f12.png)

一段时间后：
![2019-04-26 (1)](https://user-images.githubusercontent.com/515763/56788048-efa81600-6830-11e9-8838-ec1bfce93942.png)

**Comment by lzm04521** [comment]
emmmm 确实，1903，5分钟左右就消失了。

关于1903的安装包，msdn已经放出来了，可以去msdn i tell you 下载~
