### ISSUE TITLE
同样的配置4.0.6可以用 4.0.9~4.1.1不能用 

### ISSUE THREAD

**Issue by eiet** [shadowsocks/shadowsocks-windows#1981]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.0.6
4.0.9~4.1.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

1.hp 8400 g2
2.联想e420
3.某昆山机（笔记本） 
4.台式组装机 

系统全是win10_(1083)  

运行库用了3DM游戏运行库3.0  很全

排除其他软件干扰  因为朋友们的机子  —— 2跟3 都是我在itellyou上拿的下载链接 然后新装的系统

### Steps you have tried / 操作步骤

浏览器:centbrowser
插件:switchyomega
so就添加了个代理服务器 socks5 127.0.0.1:1080
服务器是自己搭建的  用的谷歌云  ss+bbr 用了快一年了

有直接在刚装完的系统上使用新版——不能连接（E420）

先使用旧版 ——能登陆google网站后，再使用新版——不能连接(g2)

先使用新版不能连接后——使用旧版可以恢复连接但是经过几次折腾发现恢复需要一小段时间才能翻
刚刚关掉新版再用旧版不能马上翻（g2）

在旧版可以使用的情况下，应该跟配置没关系的感觉。。。
看日志就只是time out 

之前没想过来问问这茬，今天刚给人装的系统（E420）还是
不能用最新的4.1.1  觉得奇怪 便来请教请教
之前在台式机用的gfw的pac
今天俩台电脑（我自己的g2跟朋友的E420）都用了这个
https://prudent-travels.000webhostapp.com/pac.php?a=PROXY&b=192.168.1.1:8123
今天搜这问题有人说可能跟pac有关，所以在v2ex找的
https://github.com/lbp0200/mono_pac

无论是win10提醒的更新下载的压缩包还是在github这里下载页面下载的4.1.1都不能用

有尝试把1080端口改成10800端口测试 依旧不行

### What did you expect to see? / 期望的结果
使用更新后的版本实现访问被屏蔽的网络。

### What did you see instead? / 实际结果
乖乖用回旧版。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

日志文件分为俩种 一种是在旧版配置文件上直接覆盖运行程序的
```
[2018-08-21 03:01:08] Shadowsocks started (4.1.1)
[2018-08-21 03:01:08] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-08-21 03:02:06] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.EntryPointNotFoundException: 无法在 DLL“libsscrypto.dll”中找到名为“md5_ret”的入口点。
   在 Shadowsocks.Encryption.MbedTLS.md5_ret(Byte[] input, UInt32 ilen, Byte[] output)
   在 Shadowsocks.Encryption.MbedTLS.MD5(Byte[] input)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor.LegacyDeriveKey(Byte[] password, Byte[] key, Int32 keylen)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor.InitKey(String password)
   在 Shadowsocks.Encryption.Stream.StreamEncryptor..ctor(String method, String password)
   在 Shadowsocks.Encryption.Stream.StreamOpenSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
```

——————————————————————————————————————————————
——————————————————————————————————————————————

一种是把运行程序丢到一个空的文件夹里
```
[2018-08-21 02:36:59] Shadowsocks started (4.1.1)
[2018-08-21 02:36:59] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-08-21 02:37:03] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-08-21 02:37:05] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-08-21 02:37:05] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

**Comment by studentmain** [comment]
确认旧版本能用嘛。把旧版本的gui-config.json粘过去试试。

**Comment by eiet** [comment]
我用新版本覆盖代替旧版 启动也是不行额 
现在想重置下服务器的ss看看行不行

**Comment by eiet** [comment]
发完问题就去折腾   弄了半天终于可以了 
尝试着改掉1080端口 结论 无效
就奔着服务器去 想着客户端如果没问题 可能出现在服务端上
然后开始折腾  试着改掉连接密码  改完后  无效 新版连同旧版都不能用了 emmmm表示很奇怪
只能拿另一个限流的工具来排查  就找了网上别人的一键脚本 刷完一遍后再测试 然而并没用什么用
期间也有用iphone测了一下  都是能ping通 访问的时候空白页面
接着又找了个一键脚本  结果依旧是连接不能
然后就想要不重置一下重新配置好了 ， 结果谷歌的重置不知道是啥操作 重置了几遍  再连接SSH
BBR跟SS还是开启状态。。。。。。（嘛是不是压根就没重置）
来来回回几次后没死心 拿起手机测一遍  哎嘛通了  但是电脑连不上  噫 怪哉   干脆重启电脑

然后  emmmm 新版旧版都能用了   _(:з)∠)_
 
重启后   开了新版的时候我看了日志  2018-08-21 06:08:08 还在积极拒绝
重启完   2018-08-21 06:10:18  就能接上了（旧版自启 连通 关掉 开启新版看的日志）

这样我分不清到底是客户端还是服务端的问题了_(:з)∠)__(:з)∠)_




_(:з)∠)_

**Comment by celeron533** [comment]
安装Microsoft Visual C++ 2015 Redistributable x86

**Comment by chenshaoju** [comment]
https://www.microsoft.com/zh-CN/download/details.aspx?id=53840

**Comment by eiet** [comment]
看了一眼能使用的G2 确实没有这个库 有2013 跟 2017 emmm

**Comment by chenshaoju** [comment]
两个方面：
１：
请确保安装的是x86的2017，2015已经被2017替代 https://github.com/shadowsocks/shadowsocks-windows/issues/1948

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

另一种可能是，请尝试将其放到一个英文路径的文件夹里，比如 D:\SS\ 试试，某些系统（日文？）可能会有问题。


２：`由于目标计算机积极拒绝，无法连接。` 这个意味着你连接的服务器不通，请确保你的服务器IP、端口号是正确的。

**Comment by eiet** [comment]
正常能用了 刚刚在朋友那里配置4.0.10的时候 不能连接 直接来下4.1.1 然后放新文件夹就可以了    那台电脑还没有装其他的东西就一个刚装完的系统  也能用了  
顺带一提在没翻墙情况下  英文页面能下载  中文页面一直连不了 不知道啥愿意哦

**Comment by celeron533** [comment]
>英文页面能下载 中文页面一直连不了

https://github.com/shadowsocks/shadowsocks-windows/releases
https://shadowsocks.org/en/index.html

除此以外的都是非官方渠道
