### ISSUE TITLE
win7 停止工作

### ISSUE THREAD

**Issue by peach-djf** [shadowsocks/shadowsocks-windows#1987]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	4.1.1.0
  问题签名 03:	5b777c3c
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	4ba1da6f
  问题签名 07:	11cd
  问题签名 08:	89
  问题签名 09:	System.TypeLoadException
  OS 版本:	6.1.7601.2.1.0.256.4
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by chenshaoju** [comment]
请确保安装了最新的 .NET Framework： https://www.microsoft.com/net/download/dotnet-framework-runtime

顺带请记得安装Microsoft Visual C++ 2015 Redistributable (x86): https://www.microsoft.com/en-us/download/details.aspx?id=53840
