### ISSUE TITLE
windows10崩溃bug

### ISSUE THREAD

**Issue by luoluoshu** [shadowsocks/shadowsocks-windows#1988]
Shadowsocks 4.11和4.09

硬件为小米笔记本pro 系统为windows10专业版1803  .net 框架版本4.7
在安装
2018 年 8 月 14 日 - KB4343909（操作系统内部版本 17134.228）
系统更新后，打开shadowsocks win客户端一段时间后电脑会卡死，按什么都没反应。任务管理器可以看到shadowsocks进程占用磁盘读取100% ，十几秒后彻底死机。
再没有安装自动更新前没有问题。在不同Windows版本系统一使用没有问题。

**Comment by chenshaoju** [comment]
你好，我的Windows 10 1803 17134.228 也安装了KB4343909，但是没有遇到该问题。

请尝试右击托盘区的纸飞机图标，指向帮助，确保没有选中“记录详细日志。

**Comment by celeron533** [comment]
- 取消“详细记录日志”
- 不要使用前置代理，如果你不理解这是什么的话。错误的设置可能导致回环
- 杀毒软件干扰
- 从官方渠道下载

**Comment by celeron533** [comment]
any updates?
