### ISSUE TITLE
shadowsocks-go百年不支持chacha20-ietf-poly1305

### ISSUE THREAD

**Issue by LsnmxNB** [shadowsocks/shadowsocks-windows#1989]
哪位大神接手一下shadowsocks-go
如题，百年不支持chacha20-ietf-poly1305啊
https://github.com/shadowsocks/shadowsocks-go

**Comment by chenshaoju** [comment]
请尝试使用 Python 版： https://github.com/shadowsocks/shadowsocks/tree/master ，关于 chacha20-ietf-poly1305 加密方式的问题，请访问：https://github.com/shadowsocks/shadowsocks/issues/1046

或者，请尝试 libev 版： https://github.com/shadowsocks/shadowsocks-libev

**Comment by LsnmxNB** [comment]
@chenshaoju  GO版本安装方便啊，可惜没人更新了

**Comment by reee** [comment]
libev我感觉有内存泄漏问题- -。。。python版本依赖一大堆麻烦。。。哎
