### ISSUE TITLE
Pc端，port正常，IE能够翻墙，但是chrome无法翻墙。并且IE每隔一段时间就会翻墙不成功。好像是提示TSL不安全

### ISSUE THREAD

**Issue by Stephen2252** [shadowsocks/shadowsocks-windows#1990]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by Stephen2252** [comment]
shadowsocks 4.1.1
操作系统 ：win10 
操作步骤： 正常操作，安装，输入vpn地址、端口、密码，连接，启用系统代理
期望的结果：chrome等所有浏览器都能连得上外网，并且不会出现tsl不安全的提示信息
实际结果：Pc端，port正常（open），IE能够翻墙，但是chrome无法翻墙。并且IE每隔一段时间就会翻墙不成功。**好像是提示TSL不安全**
配置文件和日志文件：
![default](https://user-images.githubusercontent.com/40737041/44851946-80275a00-ac94-11e8-8ca9-ac9354f318cb.JPG)

[2018-08-30 20:31:17] Shadowsocks started (4.1.1)
[2018-08-30 20:31:17] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-08-30 20:31:25] connect to config.pinyin.sogou.com:80
[2018-08-30 20:31:26] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-08-30 20:35:53] connect to canonicalizer.ucsuri.tcs:80
[2018-08-30 20:35:54] Socket connected to ss server: 178.128.223.93:10514
[2018-08-30 20:35:55] connect to canonicalizer.ucsuri.tcs:80
[2018-08-30 20:35:55] Socket connected to ss server: 178.128.223.93:10514
[2018-08-30 20:36:21] connect to config.pinyin.sogou.com:80
[2018-08-30 20:36:21] Socket connected to ss server: 178.128.223.93:10514
[2018-08-30 20:36:32] connect to s1.mini.wpscdn.cn:80
[2018-08-30 20:36:32] Socket connected to ss server: 178.128.223.93:10514

**Comment by Stephen2252** [comment]
![default](https://user-images.githubusercontent.com/40737041/44852415-c335fd00-ac95-11e8-9d84-b850d6d45f08.JPG)

**Comment by chenshaoju** [comment]
这看起来你的Chrome并没有读取PAC，而是直接连接互联网。

请问这是在启动SS，并且SS启用了系统代理的情况下吗？

**Comment by Stephen2252** [comment]
是的，我觉得你说这个原因很有道理。我觉得我的chrome被某种无名势力给改了。请问怎么解决

**Comment by chenshaoju** [comment]
你是否有使用某些代理插件？你可以在Chrome的的设置，高级设置中看到。

![image](https://user-images.githubusercontent.com/515763/44892396-18feb980-ad17-11e8-8b97-7924a9ce163a.png)

**Comment by Stephen2252** [comment]
![image](https://user-images.githubusercontent.com/40737041/44895405-cfb66600-ad26-11e8-8eb9-ed19c7404c65.png)
没有使用，或许以前用过，需要使用吗

**Comment by chenshaoju** [comment]
你是局域网直接上网还是拨号上网？比如PPPoE或者校园拨号网络？

如果是，你把拨号网络连接改成英文名看看？

**Comment by Stephen2252** [comment]
感谢，按你说的改成英文名解决了chrome上网问题，**但是新问题又出现了**。**电脑关机重启之后没有办法连接网络，**
![default](https://user-images.githubusercontent.com/40737041/44897068-07c0a780-ad2d-11e8-8c68-ec79f2bb4d4b.JPG)
只有运行shadowsocks之后才能上网，偶尔shadowsocks还不好连接成功（这个问题不太重要）之后断开shadowsocks也能实现上网

**Comment by chenshaoju** [comment]
请尝试退出SS后再关机或重启。

**Comment by Stephen2252** [comment]
好的，十分感谢。有问题还会在这个地方咨询您，希望别介意23333333

**Comment by chenshaoju** [comment]
先搜索 Issue 会有帮助。

![doge](https://user-images.githubusercontent.com/515763/44898863-bc10fc80-ad32-11e8-8d21-6af9c0cad663.png)

**Comment by Stephen2252** [comment]
已经搜索issue，但是仍未解决。有时将shadowsocks断开，不能正常上网。出现下图情况，有什么办法解决吗
![image](https://user-images.githubusercontent.com/40737041/44908160-11f29e00-ad4d-11e8-9910-c69626b4aa27.png)

**Comment by chenshaoju** [comment]
@Stephen2252 日志中显示什么吗？请发出来看看，记得隐去你的服务器地址。

**Comment by G-lost** [comment]
chrome请使switchyOmega插件

**Comment by KlausWu** [comment]
> 你是局域网直接上网还是拨号上网？比如PPPoE或者校园拨号网络？
> 
> 如果是，你把拨号网络连接改成英文名看看？

请问如果是校园网有线上网，存在IE可以，Chrome不行的情况。我该怎么办呀
