### ISSUE TITLE
无法访问YouTube

### ISSUE THREAD

**Issue by youlei12138** [shadowsocks/shadowsocks-windows#1992]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请尝试更新本地PAC，右击托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。

**Comment by youlei12138** [comment]
我试过了，没有用。找不到YouTube IP地址

**Comment by youlei12138** [comment]
没有用，提示找不到ip地址




| |
youlei12138
邮箱：youlei12138@163.com
|

Signature is customized by Netease Mail Master

在2018年09月01日 19:01，Chen Shaoju 写道：

请尝试更新本地PAC，右击托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。

**Comment by chenshaoju** [comment]
你当然找不到，是以域名形式存在在PAC里的。

另外，请确保你使用的SS服务器能正常工作，你能访问其他被墙的网站，比如Google。

**Comment by youlei12138** [comment]
我可以访问Google，但是访问不了youtube，更新了也不行，求大神指点

**Comment by chenshaoju** [comment]
你有Firefox吗？能否为Firefox单独设置一个代理，用用看，是否能访问Youtube？

需要排除是否是PAC或者系统代理有问题，具体的设置请参考下图：

![image](https://user-images.githubusercontent.com/515763/37390878-680ff942-27a4-11e8-81f1-54edfe7658d9.png)

**Comment by youlei12138** [comment]
我用的chrome，而且我用之前的VPN可以访问YouTube是怎么回事啊

**Comment by youlei12138** [comment]
我没有开系统代理，开了之后就好，谢谢大佬




| |
youlei12138
邮箱：youlei12138@163.com
|

Signature is customized by Netease Mail Master

在2018年09月05日 22:26，Chen Shaoju 写道：

猜测可能和本机代理有关，也可能和你的SS服务器被Youtube屏蔽了有关。

在你进一步测试之前，我无法提供更多信息。
