### ISSUE TITLE
请问如何设置win10下一直保持链接不自动断开

### ISSUE THREAD

**Issue by ScrinX** [shadowsocks/shadowsocks-windows#1995]
之前一直没有此问题,最近发现连接后一段时间不用就会自动断开,需要重新再连才能使用.win10操作系统64位,请问是需要设置哪里来改善?

**Comment by chenshaoju** [comment]
日志中有什么显示吗？另外你使用的SS版本是……？

**Comment by ScrinX** [comment]
多谢回复 附上日志截图 使用的最新的4.1.1,    4.0也测试了也有
![20180904120147](https://user-images.githubusercontent.com/42953101/45009378-6c844680-b03a-11e8-8116-573d4ef38bde.jpg)
此问题.

**Comment by chenshaoju** [comment]
日志中看不出来任何问题，你启用了系统代理吗？是PAC模式？

如果可能，当无法使用的时候，看一下浏览器的代理设置，是否被清空了？

![image](https://user-images.githubusercontent.com/515763/45010202-db639e80-b03e-11e8-96c4-f2a70022cf84.png)

**Comment by ScrinX** [comment]
启用系统代理了,pac模式,脚本没有问题.

**Comment by chenshaoju** [comment]
日志中是空的，这个非常奇怪。

你有Firefox吗？能否为Firefox单独设置一个代理，用用看，是否会突然断开？如果断开了，SS的日志中有什么显示吗？

![image](https://user-images.githubusercontent.com/515763/37390878-680ff942-27a4-11e8-81f1-54edfe7658d9.png)

**Comment by celeron533** [comment]
> 他到时间自动断开的时候,脚本就没有了

如果你安装了其他代理软件或者某些安全软件，他们会每隔一段时间修改/还原你的系统代理

**Comment by ScrinX** [comment]
电脑里只有 avast 奇怪的是 之前一直没有此问题 最近没有安装过其他软件

**Comment by ScrinX** [comment]
win10里 哪个地方的设置 会影响到这个问题吗

**Comment by chenshaoju** [comment]
Windows 10 本身不会影响这个设置，是你的系统里有东西修改了你的代理设置。如果你是技术人员，可以尝试使用ProcMon监控注册表键值的变化，你可以在 https://github.com/shadowsocks/shadowsocks-windows/issues/1943#issuecomment-416096579 了解具体信息。

**Comment by ScrinX** [comment]
ProcMon下载完打开后彻底懵了,有没有简单一点的监控方法,或者其他办法.

**Comment by ScrinX** [comment]
现在的问题就是脚本那块总是自动清空

**Comment by chenshaoju** [comment]
@ScrinX 请备份数据，然后重置系统看看。

**Comment by ScrinX** [comment]
我卸载了avast 问题已解决 怀疑是最近的avast一次更新后 改变了规则
