### ISSUE TITLE
校园网拨号的情况下Chrome和Steam客户端无效，但是Edge和IE可以（火狐也可以）

### ISSUE THREAD

**Issue by noddinagushpa** [shadowsocks/shadowsocks-windows#1996]
Shadowsocks version / 影梭版本 2.3
Windows 10 1803

**问题如下：**
使用PAC，打开系统代理，端口1080，关掉了迅雷服务
校园网支持ipv6，不拨号的时候只能用ipv6
拨号前，Chrome只能登上被✖掉的网站（因为设置了PAC规则，被墙掉的会走ipv6代理）（这里没毛病）
拨号后，Chrome只能登上✔的网站（似乎是忽视了PAC和代理，直接走的拨号的ipv4的连接）（这里就有问题了）
主要是拨号对Chrome选择走不走代理产生了影响，求助，提前感谢~

Dropbox似乎也有这个问题？

**Comment by chenshaoju** [comment]
请尝试将你的拨号连接名修改为英文的。

另外，请在拨号后再启动SS。

**Comment by noddinagushpa** [comment]
似乎起作用了，请问这是为什么呢？→（改成英文名就好了）

**Comment by chenshaoju** [comment]
可能和字符编码有关，具体原因不明。

**Comment by noddinagushpa** [comment]
感谢解答~！
