### ISSUE TITLE
翻墙成功之后youtube能上但是quora上不去，请问什么原因

### ISSUE THREAD

**Issue by Stephen2252** [shadowsocks/shadowsocks-windows#1997]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
shadowsocks 4.1.1
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
正常操作，安装，输入vpn地址、端口、密码，连接，启用系统代理

### What did you expect to see? / 期望的结果
能上quora

### What did you see instead? / 实际结果
不能上

**Comment by Stephen2252** [comment]
配置文件如下图
![default](https://user-images.githubusercontent.com/40737041/45068643-08758700-b0fb-11e8-967d-77bd1bd32144.JPG)

**Comment by Stephen2252** [comment]
更新成功，但还是无法上quora。手机翻墙都可以上，奇了怪

**Comment by chenshaoju** [comment]
你的手机和电脑是相同的配置（SS服务器地址、端口等）吗？

另外，电脑上能打开其他被墙的网站（比如Google、Facebook等）吗？

**Comment by Stephen2252** [comment]
可以上了，不知道昨天是啥原因，算是以解决了吧

**Comment by piri7001** [comment]
@Stephen2252  现在还是可以上吗？我是手机可上quora和reddit，PC浏览器无法打开quora和reddit

**Comment by chenshaoju** [comment]
@piri7001 请尝试按照上面的方法更新一下PAC看看。另外，请确保能打开Google。

**Comment by piri7001** [comment]
@chenshaoju 谢谢回复。上面的方法已经尝试了，还是不行。谷歌可以打开，事实上目前为止除了上述两个，其他网站都正常。

**Comment by chenshaoju** [comment]
你是否使用过Hosts文件？如果是，检查你的Hosts文件是否为默认值。

如果Hosts文件没有问题，你的服务器是自己搭建的还是购买的？如果是自己搭建的，在服务器上使用curl 命令访问quora或reddit，能访问吗？
```
curl -vv https://www.quora.com

**Comment by piri7001** [comment]
@chenshaoju 现在可以上去了，没有进行任何改动，之前上不去的情况持续了大概一周。之前也尝试过将Hosts文件恢复默认，但是当时没有解决。如果下次遇到这种情况我再查一下服务器端，感谢你的帮助~

**Comment by tiddlyz** [comment]
我也有一样的问题，现在还是pc端上不去quora，Android手机端没有任何问题.
`curl -vv https://www.quora.com` 在server上运行正常，能得到quora的网页内容。

**Comment by chenshaoju** [comment]
这个问题让人很困惑，你能访问其他的网站吗？比如Google？Youtube？Facebook？我自己测试了一下，并没有这个问题。。。

**Comment by celeron533** [comment]
如果你是买来的服务（rua.ss8.site看上去很像），另一种可能是有人用爬虫通过这台服务器抓取过quora导致这台服务器IP倍拉入黑名单。

另一种情况则是通过图形化的浏览器访问quora需要加载其他域的资源，然而那个域由于种种原因无法到达。

**Comment by zyf2008Neptune** [comment]
我是P站上不去。

**Comment by chenshaoju** [comment]
@zyf2008Neptune Pixiv屏蔽了日本以外的许多国家的VPS/云服务IP段，我位于SGP、SFO和LON的服务器都无法访问P站，但是日本本地的可以。

**Comment by zyf2008Neptune** [comment]
@chenshaoju 果然ping不同，这下就尴尬了，tls1.3不出hosts也用不了。

**Comment by celeron533** [comment]
>Pixiv屏蔽了日本以外的许多国家的VPS/云服务IP段

因为之前有人用vps抓站

**Comment by ayumiymk** [comment]
代理模式切换成全局的就可以了？我的是这样。。。

**Comment by RedemptionC** [comment]
> 代理模式切换成全局的就可以了？我的是这样。。。

切换成全局确实可以。。但是感觉这样有点浪费。。？

**Comment by chenshaoju** [comment]
请尝试右击任务栏托盘区的SS图标，选择PAC，再点击"编辑GFWList的用户规则"，然后增加一行：
```
||quora.com
```
保存退出记事本后，退出SS，再启动SS，即可生效。
如果需要更多信息，请参阅： https://github.com/shadowsocks/shadowsocks-windows/issues/1879

**Comment by RedemptionC** [comment]
> 请尝试右击任务栏托盘区的SS图标，选择PAC，再点击"编辑GFWList的用户规则"，然后增加一行：
> 
> ```
> ||quora.com
> ```
> 保存退出记事本后，退出SS，再启动SS，即可生效。
> 如果需要更多信息，请参阅： #1879

现在能打开quora的登陆界面，但是点其他任何都没反应，登陆就提示405.。

**Comment by chenshaoju** [comment]
我测试了一下，好像还得允许一个叫`quoracdn.net`的域名
请再加一行：
```
||quoracdn.net
```

**Comment by boyingwell** [comment]
更新gfwlist显示failed，加了||quoracdn.net，||quora.com也不行。

**Comment by chenshaoju** [comment]
更新 GFWList Failed说明你的服务器不通。
如果你的服务器是你自己搭的，请前往 https://ipcheck.need.sh/ 测试连通性，并检查服务端工作是否正常。

如果你是找机场买的服务，请检查客户端配置是否正确，如果可能，请访问你的机场服务商更换另一个服务器试试。

**Comment by zhalice2011** [comment]
更新 GFWList就OK了呢

**Comment by Tokaiii** [comment]
> 我测试了一下，好像还得允许一个叫`quoracdn.net`的域名
> 请再加一行：
> 
> ```
> ||quoracdn.net
> ```


> 请尝试右击任务栏托盘区的SS图标，选择PAC，再点击"编辑GFWList的用户规则"，然后增加一行：
> 
> ```
> ||quora.com
> ```
> 保存退出记事本后，退出SS，再启动SS，即可生效。
> 如果需要更多信息，请参阅： #1879

感谢大牛  帮你更正一下 你刚刚说的是win下的设置   mac下添加的应该是 ! quora.com   就好

**Comment by AiksRiver** [comment]
> 代理模式切换成全局的就可以了？我的是这样。。。

真的！

**Comment by Yohahaha** [comment]
> > 我测试了一下，好像还得允许一个叫`quoracdn.net`的域名
> > 请再加一行：
> > ```
> > ||quoracdn.net
> > ```
> 
> > 请尝试右击任务栏托盘区的SS图标，选择PAC，再点击"编辑GFWList的用户规则"，然后增加一行：
> > ```
> > ||quora.com
> > ```
> > 保存退出记事本后，退出SS，再启动SS，即可生效。
> > 如果需要更多信息，请参阅： #1879
> 
> 感谢大牛 帮你更正一下 你刚刚说的是win下的设置 mac下添加的应该是 ! quora.com 就好

亲测可行

**Comment by rangershs** [comment]
“从GFWList更新本地PAC”
亲测有效！

**Comment by daidai21** [comment]
因为大部分都在使用PAC模式，quora的静态资源被墙了，但是vpn设置的这个静态资源是没有被墙的（直接访问的静态资源），所以登陆不了

最简单的方法就是设置为全局模式

**Comment by swdenglian** [comment]
> 请尝试右击纸飞机图标，选择系统代理模式，并选择PAC，然后再次右击纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”，然后再试。

还需要重启 ss 客户端软件就非常ok

**Comment by MrxWilliam** [comment]
全局代理就可以了，因为pac模式有的网站并没有更新

**Comment by zry118** [comment]
免费试用几天高速机场，可上速度4k，还有十几个邀请次数，邀请码：0BKG 链接地址：http://www.vwall.gq/auth/register?code=0BKG

**Comment by anakubaby** [comment]
> 更新成功，但还是无法上quora。手机翻墙都可以上，奇了怪

你好，我也遇到和你一样的问题，请问你现在解决了吗？

**Comment by anakubaby** [comment]
> 你的手机和电脑是相同的配置（SS服务器地址、端口等）吗？
> 
> 另外，电脑上能打开其他被墙的网站（比如Google、Facebook等）吗？

能上YouTube，Facebook，但是上不了quora，提示ip次数太多，可是我换了节点换了甚至换了其他机场的节点都提示ip地址访问次数太多上不去，请问该如何解决？

**Comment by anakubaby** [comment]
> reddit

我和你一样的情况，同样的节点，手机上能上quora，电脑上不了quora，你后面怎么解决的？

**Comment by daidai21** [comment]
@anakubaby 
是因为quora和其他网站不一样，部分CDN也被墙了，但是这个墙的名单中却没有它，你要设置全局代理，所有的流量都绕过墙就好了

**Comment by lvjiaying1984** [comment]
把||quora.com写入pac文件试下。
