### ISSUE TITLE
chocolatey package for shadowsocks-windows is deprecated

### ISSUE THREAD

**Issue by chantisnake** [shadowsocks/shadowsocks-windows#1998]
I was the maintainer for the [chocolatey](https://chocolatey.org/) package for shadowsocks-windows.
  I am deprecating the chocolatey package for shadowsocks-windows because I no longer have time to maintain it.

  I have requested for another package maintainer here: https://github.com/chocolatey/chocolatey-package-requests/issues/413
  The chocolatey package page for shadowsocks-windows : https://chocolatey.org/packages/shadowsocks-windows

  Sorry for all the inconvenience I have caused.

**Comment by celeron533** [comment]
Thanks for your contribution in the community!

**Comment by studentmain** [comment]
已有新的chocolatey包，故关闭
