### ISSUE TITLE
多用户的问题

### ISSUE THREAD

**Issue by miaoweiwei** [shadowsocks/shadowsocks-windows#2001]
怎么使用用户名和密码登录

**Comment by chenshaoju** [comment]
没有这种功能，如果你购买的服务商有自己的客户端，请与你的服务商联系并使用服务商提供的客户端。

**Comment by miaoweiwei** [comment]
我的是自己搭建的，我看在服务端可以设置多用户，可以开发一下吗

**Comment by chenshaoju** [comment]
我没看懂你的意思，客户端使用“多用户”的目的是什么？你的意思是是你一台计算机上要同时使用多个SS客户端吗？

如果是，你可以创建多个不同的目录，将 Shadowsocks.exe 复制进去，并挨个配置即可。

**Comment by chenshaoju** [comment]
服务端的确是可以设置多个用户，但是不存在使用用户名的方式，只能以端口的方式设置多个用户。

具体请参阅：https://github.com/shadowsocks/shadowsocks/wiki/Configure-Multiple-Users

**Comment by miaoweiwei** [comment]
也就是说登录的时候只是指定的端口不同，每个密码对应不同的端口对吗

**Comment by chenshaoju** [comment]
不同的端口和密码，是。

**Comment by miaoweiwei** [comment]
谢啦
