### ISSUE TITLE
win10使用最新工具，最新.net，c++2015无法登陆谷歌，麻烦解答一下

### ISSUE THREAD

**Issue by 1221vincent** [shadowsocks/shadowsocks-windows#2002]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
最新版本4.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10,最新.net,c++2015

### Steps you have tried / 操作步骤
下载最新shadowsock，填写vps的账号密码端口，使用谷歌浏览器，IE浏览器均无反应。
日志也没有消息。

### What did you expect to see? / 期望的结果
可以登陆谷歌

### What did you see instead? / 实际结果
无法登陆谷歌

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

[2018-09-13 16:50:12] Shadowsocks started (4.1.1)
[2018-09-13 16:50:12] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor

**Comment by chenshaoju** [comment]
SS没有帐号的概念，所以你不可能填写进去账号。

请确保你填写的是你的服务器上的SS服务的帐号信息，而不是你VPS的SSH登录的帐号信息。
