### ISSUE TITLE
Shadowsocks Windows 不能正确设置非代理的本地地址

### ISSUE THREAD

**Issue by XeroChen** [shadowsocks/shadowsocks-windows#2003]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
ALL （4.1.2 included）

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 （10.0.17134.285）

### Steps you have tried / 操作步骤
预置条件: 
1> shadowsocks-windows开启
2> 服务器配置完毕, 勾选"启用系统代理"
3> 系统代理模式设为"全局代理"

操作序列:
step 1) 系统托盘 -> 打开“网络和Internet”设置 ->代理->"手动设置代理"
手动编写不使用代理的条目 *.ngwdev.com (解析到192.168.25.8)
![image](https://user-images.githubusercontent.com/20438791/45527157-d1932580-b80c-11e8-96ff-67b522029c48.png)
随后点击"保存"

step  2) 在shadowsocks-windows系统托盘中取消勾选"启用系统代理"
step  3) 在shadowsocks-windows系统托盘中勾选"启用系统代理"

### What did you expect to see? / 期望的结果
*.ngwdev.com 条目在系统中保留

### What did you see instead? / 实际结果
*.ngwdev.com 条目被删除, “网络和Internet”设置 ->代理->"手动设置代理"中被恢复为默认设置
![image](https://user-images.githubusercontent.com/20438791/45527203-fc7d7980-b80c-11e8-982a-c94074277bd6.png)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

![image](https://user-images.githubusercontent.com/20438791/45527250-3e0e2480-b80d-11e8-989d-a539ffe07af2.png)

**Comment by chenshaoju** [comment]
测试了一下，没有问题。
![image](https://user-images.githubusercontent.com/515763/45528193-d4dce000-b811-11e8-9327-803be8e5c897.png)

仔细看了一下，该问题存在一个步骤操作问题，请尝试执行以下操作：
１.退出SS。
２.删除Shadowsocks.exe所在目录下的user-wininet.json文件，也可能位于 .\ss_win_temp 目录中。
３.按照你的要求设置绕过代理的情况。
４.启动SS。

此时应该已经恢复了。

**Comment by XeroChen** [comment]
从任务栏形状看你应该用的Windows 7

按照你的操作步骤....我在Windows 10 上问题依旧

**Comment by XeroChen** [comment]
![image](https://user-images.githubusercontent.com/20438791/45534217-057e4300-b82d-11e8-994d-8436c6e6b444.png)

**Comment by XeroChen** [comment]
找了一遍, 应该只有这里会把"不使用代理设置"的配置恢复成这样.
获取配置/应用配置,这个过程, 理论上不应该存在硬编码啊.

**Comment by chenshaoju** [comment]
请确保你已经按照上面的步骤操作了一次。

![upload](https://user-images.githubusercontent.com/515763/45536727-e71c4580-b834-11e8-8b0c-d9b15aff78e0.gif)

**Comment by XeroChen** [comment]
问题依旧.
你的截屏中启用系统代理后小飞机是白色,而且使用了自动配置脚本,说明你没有按照我ISSUE里面的复现时设置"全局模式",而是使用了"PAC模式"

**Comment by wongsyrone** [comment]
并没有问题，只有在关闭系统代理设置的状态下，点“启用系统代理”才会记录用户的代理设置，step1和2反过来就对了

**Comment by XeroChen** [comment]
@chenshaoju 的理解是准确的: "设置例外的域名在全局模式下也能保持例外"

**Comment by XeroChen** [comment]
@celeron533 无论PAC和全局都需要对自定义设置进行保留.否则在可逆的操作(启用/取消全局代理)的过程中, 出现了不一致的操作结果, 原则上有点说不过去吧.

**Comment by wongsyrone** [comment]
这种情况可以多做一个窗体（之前为啥没有，懒）增加一个例外列表输入框，增加一个按钮可以直接填入默认内网部分到输入框。

缺点：小白不会写，导致需要额外的逻辑处理异常；增加复杂度
好处：可定制性增强

另一种思路，额外地址列表做到json配置文件中，但不提供设置窗体，由高级用户自行定制，对小白用户透明

**Comment by studentmain** [comment]
![2018-10-08 1](https://user-images.githubusercontent.com/17123090/46596483-46f1cd80-cb0f-11e8-9f27-3f1294673333.png)

像这样？在设置代理时，把用户填写的例外设置与内置局域网IP例外直接合并，作为新的例外设置。倒是既用不着加窗口也用不着改配置文件，只是不方便拿ss-windows代替常规VPN接入局域网了。（不过也可以加个开关选择是否代理局域网IP）

[Shadowsocks.zip](https://github.com/shadowsocks/shadowsocks-windows/files/2455034/Shadowsocks.zip)
SHA1: 222bf83a879570985479ea5b0da5c9e5da2e7b01  Shadowsocks.exe

**Comment by Luke-lujunxian** [comment]
> ![2018-10-08 1](https://user-images.githubusercontent.com/17123090/46596483-46f1cd80-cb0f-11e8-9f27-3f1294673333.png)
> 
> 像这样？在设置代理时，把用户填写的例外设置与内置局域网IP例外直接合并，作为新的例外设置。倒是既用不着加窗口也用不着改配置文件，只是不方便拿ss-windows代替常规VPN接入局域网了。（不过也可以加个开关选择是否代理局域网IP）
> 
> [Shadowsocks.zip](https://github.com/shadowsocks/shadowsocks-windows/files/2455034/Shadowsocks.zip)
> SHA1: 222bf83a879570985479ea5b0da5c9e5da2e7b01 Shadowsocks.exe

那这个issue算是解决了吗？

**Comment by studentmain** [comment]
暂时不算，只是让试试能不能用。能用再提PR。

**Comment by studentmain** [comment]
现在解决了
