### ISSUE TITLE
xp下能用的最高版本是3.2，但最近总是无法连接上

### ISSUE THREAD

**Issue by wodewansui** [shadowsocks/shadowsocks-windows#2005]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
3.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
操作系统是xp sp3 
.net环境是4.0
浏览器是360极速浏览器最新版

### Steps you have tried / 操作步骤
最近这几天利用版本3.2连接总是失败，试遍了所有配置都无法成功，但其他朋友通过4.1.2能够连接上

### What did you expect to see? / 期望的结果
能够连接上

### What did you see instead? / 实际结果
任何配置都无法连接成功，要么是无法连接上，要么连接上就返回一个错误，总之无法连接成功

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
以下为无法连接上的情况
```
[2018-09-17 11:59:16] b.isxc.top:17442 timed out
[2018-09-17 11:59:19] b.isxc.top:17442 timed out
[2018-09-17 11:59:23] b.isxc.top:17442 timed out
[2018-09-17 11:59:23] b.isxc.top:17442 timed out
[2018-09-17 11:59:26] b.isxc.top:17442 timed out
[2018-09-17 11:59:29] b.isxc.top:17442 timed out
[2018-09-17 11:59:29] b.isxc.top:17442 timed out
[2018-09-17 11:59:32] b.isxc.top:17442 timed out
[2018-09-17 11:59:32] b.isxc.top:17442 timed out
[2018-09-17 11:59:32] b.isxc.top:17442 timed out
[2018-09-17 11:59:33] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```
以下为连接成功但返回错误的情况
```
[2018-09-17 11:59:44] Shadowsocks started
[2018-09-17 12:03:57] Shadowsocks started
[2018-09-17 12:04:01] Socket connected to ss server: b.isxb.top:18105
[2018-09-17 12:04:01] connect to api.github.com:443
[2018-09-17 12:04:01] Socket connected to ss server: b.isxb.top:18105
[2018-09-17 12:04:01] connect to api.github.com:443
[2018-09-17 12:04:01] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

**Comment by chenshaoju** [comment]
你好，经过测试，你的服务器不通，可能挂了。

如果你是购买的服务，请与你的服务器提供商联系。

在线测试地址：（海外） https://www.infobyip.com/tcpportchecker.php ，（国内）http://tool.chinaz.com/port/ 。

**Comment by wodewansui** [comment]
> 你好，经过测试，你的服务器不通，可能挂了。
> 
> 如果你是购买的服务，请与你的服务器提供商联系。
> 
> 在线测试地址：（海外） https://www.infobyip.com/tcpportchecker.php ，（国内）http://tool.chinaz.com/port/ 。

这个网址里有一些免费的SS提供：
https://us.ishadowx.net/

我现在连接如下地址可以连接上
地址：a.isxc.top
端口：17473
密码：isx.yt-22353018
加密方式：aes-256-cfb
但显示如下返回错误
[2018-09-17 14:51:25] Shadowsocks started
[2018-09-17 14:51:28] Socket connected to ss server: a.isxc.top:17473
[2018-09-17 14:51:28] connect to api.github.com:443
[2018-09-17 14:51:28] Socket connected to ss server: a.isxc.top:17473
[2018-09-17 14:51:28] connect to api.github.com:443
[2018-09-17 14:51:29] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
``` 从传输流收到意外的 EOF 或 0 个字节 ``` 这个提示的意思是连接被重置，通信的过程中被墙切断了连接。

可能这个免费的服务被重点关照了。

**Comment by wodewansui** [comment]
> `从传输流收到意外的 EOF 或 0 个字节` 这个提示的意思是连接被重置，通信的过程中被墙切断了连接。
> 
> 可能这个免费的服务被重点关照了。

那为啥其他朋友在同样的网络下在win7或者win10的电脑上用4.1.2可以成功连接访问呢？

**Comment by chenshaoju** [comment]
从提示来看，你的连接的确被切断了，不排除是你的电脑上有什么东西切断了连接。

建议多更换几个服务器测试一下。

**Comment by wodewansui** [comment]
> 从提示来看，你的连接的确被切断了，不排除是你的电脑上有什么东西切断了连接。
> 
> 建议多更换几个服务器测试一下。

最开始的时候shadowsocks 3.2可以用，后来我下了一个ShadowsocksR-4.7.0-win，然后也试着用了一下，发现ShadowsocksR不好用，再切换到shadowsocks 3.2，就发现总也无法成功连接了，你看跟ShadowsocksR有关系吗？

**Comment by chenshaoju** [comment]
据我了解SS和SSR之间没有冲突。

如果你确定相同的情况下只有您的不能使用，请尝试以管理员身份启动命令提示符（CMD），然后执行：
```
netsh interface ip reset c:\log.txt
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机看看。

**Comment by wodewansui** [comment]
> 据我了解SS和SSR之间没有冲突。
> 
> 如果你确定相同的情况下只有您的不能使用，请尝试以管理员身份启动命令提示符（CMD），然后执行：
> 
> ```
> netsh interface ip reset c:\log.txt
> netsh interface ipv6 reset
> netsh interface tcp reset
> netsh winsock reset
> ```
> 一行一回车，四行执行完毕后重新启动计算机看看。

你好，你给的这几个命令是不是有点问题？首先，重置ipv6的意思是？我现在用的是ipv4，然后
netsh interface tcp reset 这个命令无法执行，说找不到interface tcp reset命令，所以你给的这几个命令无法完整执行

后来，我切换到无线网卡发现3.2版本可以正常使用，原来我之前翻的时候用的是无线网卡，但是用有线网卡就会有上述问题

这是何解？

**Comment by chenshaoju** [comment]
XP系统过于古老，第三行可能不支持，我手上没有环境测试。

这一套命令的目的是重置TCP/IP协议，包含IPv6，因为不确定你的环境情况。

也许是你的无线网络干扰太大？

**Comment by wodewansui** [comment]
> XP系统过于古老，第三行可能不支持，我手上没有环境测试。
> 
> 这一套命令的目的是重置TCP/IP协议，包含IPv6，因为不确定你的环境情况。
> 
> 也许是你的无线网络干扰太大？

不是，我一次只用一个网卡，用无线就会断开有线，用有线就会断开无线，也许是跟墙有关

**Comment by wodewansui** [comment]
确实很奇怪

**Comment by celeron533** [comment]
启动shadowsocks后尽量不要再切换有线无线网络。
