### ISSUE TITLE
同一个网络情况下，都是win10，同样的客户端，一个能翻墙，另一个不能翻墙

### ISSUE THREAD

**Issue by wyfoffice** [shadowsocks/shadowsocks-windows#2006]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

电脑1     能用
电脑2是前两天刚买回来的美版thinkpad x1c 6th    不能用

### Shadowsocks version / 影梭版本
电脑1：4.07
电脑2:   4.07

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
电脑1：win10家庭版     4.7
电脑2：win10专业版     4.7

### Steps you have tried / 操作步骤
电脑2关闭防火墙
电脑2删去shadowsocks，重新安装

### What did you expect to see? / 期望的结果
电脑2能翻墙

### What did you see instead? / 实际结果
失败了

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

配置信息：

服务器地址（IP）： 45.32.76.143
服务器端口（port）： 12345
密码（password）： **********（隐去）
加密（Encryption Method）： aes-256-cfb

电脑1正常就不贴了

电脑2：

在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2018-09-17 18:28:18] System.TypeInitializationException: “Shadowsocks.Encryption.EncryptorFactory”的类型初始值设定项引发异常。 ---> System.TypeInitializationException: “Shadowsocks.Encryption.Sodium”的类型初始值设定项引发异常。 ---> System.DllNotFoundException: 无法加载 DLL“libsscrypto.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.Sodium.sodium_init()
   在 Shadowsocks.Encryption.Sodium..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Encryption.Sodium.get_AES256GCMAvailable()
   在 Shadowsocks.Encryption.EncryptorFactory..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()

**Comment by celeron533** [comment]
Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue

**Comment by wyfoffice** [comment]
@celeron533 试过 https://github.com/shadowsocks/shadowsocks-windows/issues/942 的方法了，但还是不行哦

**Comment by celeron533** [comment]
>试过 #942 的方法了，但还是不行哦

你用libsscrypto.dll作为关键词。

**Comment by wyfoffice** [comment]
> 请安装32位的Microsoft Visual C++ 2015 Redistributable：
> https://www.microsoft.com/en-us/download/details.aspx?id=53840

我已经安装了 2017版欸

**Comment by chenshaoju** [comment]
@wyfoffice 请确保安装了32位的2017 https://aka.ms/vs/15/release/vc_redist.x86.exe

**Comment by wyfoffice** [comment]
@chenshaoju 现在安装了2015的32位，还是不行

**Comment by wyfoffice** [comment]
@chenshaoju 
我知道我为啥失败了。。因为我是美版的，系统默认应该是要英文（虽然我已经切换成中文了），我把文件路径改成英文的就好了
可以考虑把这个添加到错误自查里去哈

**Comment by wyfoffice** [comment]
@chenshaoju 对对，我也是看了那个问题才想到的，这个可以加进去哈哈，针对海淘用户

**Comment by celeron533** [comment]
英文系统下的中文路径异常可能和这个有关

![image](https://user-images.githubusercontent.com/3608762/45701051-c5a6bb00-bba0-11e8-9eb4-4fbbe69acf46.png)

**Comment by TheTrueMan** [comment]
@chenshaoju 想请问一下我的版本是4.1.8.0的版本，启动的时候，只有入站的流量，网站访问不了，这是什么原因

**Comment by chenshaoju** [comment]
@TheTrueMan 你好，这种情况可能是你的配置不正确，如果可能，建议你新发一个帖子，贴一下日志，方便分析问题。
