### ISSUE TITLE
shadowsocks 2.5.1电脑端忽然就不能用了，System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。

### ISSUE THREAD

**Issue by tileyuan** [shadowsocks/shadowsocks-windows#2007]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
2.5.1

### Steps you have tried / 操作步骤
电脑端之前使用一直正常，忽然一天不能使用（有可能是win8.1自动更新造成，没注意）。手机端可以正常使用。尝试ping了服务器端，没问题。尝试查看了端口1080，没有发现其他程序占用，也修改了端口，都没有效果。
尝试使用全局代理，用微软浏览器，也不行。（之前一直用的chrome）

### What did you expect to see? / 期望的结果
期望能正常使用，望大神救我

### What did you see instead? / 实际结果
目前不能解决

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2018-09-17 21:58:21] System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。 104.224.***.***:56685
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
１.在编辑服务器界面换一个代理端口看看。https://github.com/shadowsocks/shadowsocks-windows/issues/564

２.https://github.com/shadowsocks/shadowsocks-windows/issues/1617

**Comment by celeron533** [comment]
Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue

**Comment by tileyuan** [comment]
告诉大家一个好消息。我经过换端口，查ip等等折腾，始终未能解决。最后我重新安装了个新版的shadows，搞定了😄真是意外啊！！
