### ISSUE TITLE
System.ComponentModel.Win32Exception(0x80004005)：文件名或扩展名太长。

### ISSUE THREAD

**Issue by wingyBaci** [shadowsocks/shadowsocks-windows#2009]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.1（发现没有收到更新的提示）

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows10 .net framework 4.5.1

### Steps you have tried / 操作步骤
长时间运行（全局模式）或者是笔记本息屏之后再打开，发现无法上网，于是我就去检查，然后影梭就给我报了一个“非预期错误”System.ComponentModel.Win32Exception(0x80004005)：文件名或扩展名太长。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
System.ComponentModel.Win32Exception (0x80004005): 文件名或扩展名太长。
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start()
   在 Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Controller.ShadowsocksController.ToggleEnable(Boolean enabled)
   在 Shadowsocks.View.MenuViewController.EnableItem_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.Command.DispatchID(Int32 id)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chenshaoju** [comment]
将 Shadowsocks.exe 单独放到一个新的目录，比如 D:\SS\ ，然后手动重新配置一次看看？

**Comment by wingyBaci** [comment]
> 将Shadowsocks.exe单独放到一个新的目录，比如D：\ SS \，然后手动重新配置一次看看？
我试过了，还是一样的，但是我下了一个最新的一个版本，目前没有发现这个问题了。

**Comment by chenshaoju** [comment]
该问题和 https://github.com/shadowsocks/shadowsocks-windows/issues/2013 一致，可能是由于有什么东西修改了系统代理导致的，但是具体是怎么回事，还无法确认。
