### ISSUE TITLE
Win7下SS无法连接 显示 System.ArgumentException: No server configured

### ISSUE THREAD

**Issue by NiorYee** [shadowsocks/shadowsocks-windows#2011]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
windows 4.1.1.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7

### Steps you have tried / 操作步骤
SS无法连接 日志如下：
```
[2018-09-19 21:51:00] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2018-09-19 21:51:00] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
```
但是在其他的电脑上可以连接这个服务器

### What did you expect to see? / 期望的结果
希望能解决问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
这意味着你没有配置任何服务器，双击屏幕右下角的纸飞机图标，在打开的编辑服务器界面中能看到你的服务器吗？还是白的？

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1907#issuecomment-406153660
