### ISSUE TITLE
Win10 SSR 無法訪問外網

### ISSUE THREAD

**Issue by shinchanzp** [shadowsocks/shadowsocks-windows#2012]
### Shadowsocks version / 影梭版本
ShadowsocksR-win-4.9.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10, NET Framework 4.7.03056

### Steps you have tried / 操作步骤
一切設定依照教程
Mode模式設置全局
Proxy rule規則設置A.繞過局域網和大陸; B.忽略繞過
Server是依據cove cloud訂閲的ip地址包括美國日本臺灣等服務器，在手機中使用shadowsocks連接正常 而pc無法連接外網；此外，使用時有選中所需服務器
Global setting, port setting未操作

一切就緒后依次于chrome, 360瀏覽器, ie, edge試用，皆無法訪問外網 國内網絡訪問無問題
網絡環境是一臺主路由器設置了固定端口 自動獲取dns 橋接一臺路由器
網絡連接一切正常 且與主路由、副路由器皆試過直連與wifi連接
除了edge本身可以訪問youtube 其他瀏覽器一概不能訪問外網

### What did you expect to see? / 期望的结果
連接後能通過啓用ss在多個瀏覽器訪問外網

### What did you see instead? / 实际结果
連接後沒有一個瀏覽器可以訪問外網

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
配置頁：
![image](https://user-images.githubusercontent.com/33599385/45773461-f78d4f80-bc7c-11e8-8a22-2ace98f5ec42.png)
![image](https://user-images.githubusercontent.com/33599385/45773491-0d9b1000-bc7d-11e8-8949-87bd8c8b55d9.png)
![image](https://user-images.githubusercontent.com/33599385/45773509-1ab7ff00-bc7d-11e8-9a7f-6f8c9ad67383.png)
![image](https://user-images.githubusercontent.com/33599385/45773553-37eccd80-bc7d-11e8-9aeb-40c9063dcff2.png)
![image](https://user-images.githubusercontent.com/33599385/45773554-37eccd80-bc7d-11e8-8a10-9ac51b57118d.png)

日志頁：
![image](https://user-images.githubusercontent.com/33599385/45773646-64084e80-bc7d-11e8-9436-1436d2adf9fc.png)
360瀏覽器訪問youtube:
![image](https://user-images.githubusercontent.com/33599385/45773711-91ed9300-bc7d-11e8-89f6-14d71c886d87.png)
Google瀏覽器訪問youtube:
![image](https://user-images.githubusercontent.com/33599385/45773841-00325580-bc7e-11e8-9cca-464edeaebc3c.png)
ie可以訪問的youtube:
![image](https://user-images.githubusercontent.com/33599385/45774028-851d6f00-bc7e-11e8-9d38-6141a70dbd35.png)

（我怎麽隱隱約約覺得是360在搞鬼？？？）

**Comment by shinchanzp** [comment]
Ohhhh! 是我搞錯了…… Sorry……
emm不過換成PAC模式還是不能夠使用
Anyhow我先找找SSR的group詢問一下
謝謝！！~

**Comment by HougeLangley** [comment]
@shinchanzp 您好，您的问题是否获得解决，因为我前几天发现了同样的问题。
