### ISSUE TITLE
打开时错误 SetIEProxy

### ISSUE THREAD

**Issue by MaxZzyo** [shadowsocks/shadowsocks-windows#2013]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.1 和 4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 家庭中文版1803 (17134.286)
.NET Framework 版本不确定, 但之前一直正常使用

### Steps you have tried / 操作步骤
双击打开

### What did you expect to see? / 期望的结果
正常打开使用

### What did you see instead? / 实际结果
之前一直正常使用 4.1.1
19日晚上开机启动的方式打开, 提示错误, 手动开启, 仍然错误 4.1.1版本
20日上午仍然开机启动提示错误, 手动开启, 仍然错误 4.1.1版本
20日更新到 4.1.2 版本, 仍然出错
把ss程序单独放到另一个文件夹启动, 仍然错误
错误标题 ----  Shadowsocks non-UI Error

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![err](https://user-images.githubusercontent.com/40203749/45789751-d72cb780-bcb3-11e8-8c34-7f3bdc2bb673.png)
[shadowsocks.log](https://github.com/shadowsocks/shadowsocks-windows/files/2399194/shadowsocks.log)

**Comment by MaxZzyo** [comment]
18日更新过windows系统, 但18, 19日都是正常使用, 期间也重启过不少次, 都是一切正常, 直到19日晚上再开机的时候才出现的错误

**Comment by chenshaoju** [comment]
请尝试： https://github.com/shadowsocks/shadowsocks-windows/issues/1487#issuecomment-340370635

**Comment by chenshaoju** [comment]
差不多一个意思，初步判断可能是由于什么变量太长导致超过处理能力。

**Comment by MaxZzyo** [comment]
> 差不多一个意思，初步判断可能是由于什么变量太长导致超过处理能力。

#1487 
这个里面说到的 sysproxy.exe query
第一次输出了一大串乱码, 直到最后才是 ProxyThorn 软件目录下的 一个 proxy.pac 文件
类似于 D:\\按时发生地方时间恢复好温柔强耦合哦亲为后期维护群殴我和噢请问\proxy.pac
这种样子, 中间的乱码有大概好几页,
然后删掉http代理之后, 就恢复正常的 路径显示了, 不知道什么情况

**Comment by chenshaoju** [comment]
感觉是你所说的那个软件有问题。

**Comment by studentmain** [comment]
在Windows 7上面试了一下ProxyThorn，没有发现设置后系统代理出现乱码。同时试了sysproxy带超长参数（约8500字符），同样能够正常运行。

**Comment by MaxZzyo** [comment]
我之前也是正常用的ss， ProxyThorn也很长时间没用了，不知道为什么就出了这个问题

- You complete me

**Comment by studentmain** [comment]
我开始时的测试方法有问题，长参数事实上被截断了。明天我试试拿Windows API输入长参数。

**Comment by chenshaoju** [comment]
@MaxZzyo 环境还在吗？上面提到的注册表位置里是如何表现得？

**Comment by MaxZzyo** [comment]
> @MaxZzyo 环境还在吗？上面提到的注册表位置里是如何表现得？

用 #1487 的注册表修改方法，搞定了，现在 sysproxy.exe query 结果是

3
127.0.0.1:1080
<local>;localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*
(null)

最后的 null 就是之前乱码的路径，那个路径有大概20个左右的中文。
现在那个文件也已经删了，应该不会再被加到这里了

**Comment by MaxZzyo** [comment]
这个是没修复前出问题的 sysproxy.exe query 结果
[errors.log](https://github.com/shadowsocks/shadowsocks-windows/files/2498006/errors.log)

**Comment by studentmain** [comment]
问题归根到底是命令行参数超长，没法通过Process对象直接塞给sysproxy。现在最新的代码加入了一些缓解措施，失败时会尝试重置系统代理。不过要彻底解决还得修sysproxy.exe。

MaxZzyo <notifications@github.com> 于 2018年10月20日周六 下午5:47写道：

**Comment by studentmain** [comment]
![image](https://user-images.githubusercontent.com/17123090/47255342-195b3b80-d4a2-11e8-9ec1-b5b7679e8e31.png)

你怎么抓的log，`sysproxy.exe query > error.log` ?开头这个fffe有点意思

**Comment by MaxZzyo** [comment]
> ![image](https://user-images.githubusercontent.com/17123090/47255342-195b3b80-d4a2-11e8-9ec1-b5b7679e8e31.png)
> 
> 你怎么抓的log，`sysproxy.exe query > error.log` ?开头这个fffe有点意思

sysproxy.exe query > errors.log
这样。。

**Comment by MaxZzyo** [comment]
> @MaxZzyo 谢了，如果方便，把现在的输出也这样抓一下发出来。姑且先把这个情况记着。

[now.log](https://github.com/shadowsocks/shadowsocks-windows/files/2498267/now.log)

**Comment by wongsyrone** [comment]
这不是 BOM 么

UTF-16（小端序） | FF FE |

**Comment by wongsyrone** [comment]
是根据 `_O_U16TEXT` 来的

**Comment by studentmain** [comment]
@wongsyrone 考虑到#1487 ，在输出UTF16LE的情况下按理说程序应该抛出一个indexOutOfRange。这里正常工作了，有点奇怪。
