### ISSUE TITLE
Shadowsocks Non-UI Error - Controller.Hotkeys.HotKeys.Init

### ISSUE THREAD

**Issue by KuhaQueen** [shadowsocks/shadowsocks-windows#2014]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10教育版

### Steps you have tried / 操作步骤
双击打开程序

### What did you expect to see? / 期望的结果
正常工作

### What did you see instead? / 实际结果
报错

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
System.TypeInitializationException: “<Module>”的类型初始值设定项引发异常。 ---> System.Runtime.InteropServices.SEHException: 外部组件发生异常。
   在 _initatexit_app_domain()
   在 <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   在 <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   在 <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   在 .cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 GlobalHotKey.HotKeyManager..ctor()
   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   在 Shadowsocks.Program.Main()
[2018-09-21 20:07:25] [E] System.TypeInitializationException: “<Module>”的类型初始值设定项引发异常。 ---> System.Runtime.InteropServices.SEHException: 外部组件发生异常。
   在 _initatexit_app_domain()
   在 <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   在 <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   在 <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   在 .cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 GlobalHotKey.HotKeyManager..ctor()
   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   在 Shadowsocks.Program.Main()
```

**Comment by chenshaoju** [comment]
从提示来看，是热键注册的过程中出现了问题。

请尝试打开 Shadowsocks.exe 所在目录下的 gui-config.json 文件，找到 "RegHotkeysAtStartup" ，并将后面的`true`修改为`false`，保存退出后重试。

如果可能，请检查 "hotkey" 花括号内框住的内容中，是否存在一个位于冒号左边部分的空双引号（ "" ）内容。

**Comment by KuhaQueen** [comment]
> 从提示来看，是热键注册的过程中出现了问题。
> 
> 请尝试打开 Shadowsocks.exe 所在目录下的 gui-config.json 文件，找到 "RegHotkeysAtStartup" ，并将后面的`true`修改为`false`，保存退出后重试。
> 
> 如果可能，请检查 "hotkey" 花括号内框住的内容中，是否存在一个位于冒号左边部分的空双引号（ "" ）内容。

`{
  "configs": [
    ...
  ],
  "strategy": null,
  "index": 3,
  "global": false,
  "enabled": false,
  "shareOverLan": true,
  "isDefault": false,
  "localPort": 1006,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": false,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": ""
  }
}`

以上为gui-config.json内容, 并未发现此项目, 另: 此问题于今日windows更新后出现
当前WIndows版本1803(17134.286)

**Comment by chenshaoju** [comment]
我刚更新了一下，更新到了 17134.286，但是无法复现该问题，SS工作正常。

![2018-09-22](https://user-images.githubusercontent.com/515763/45893702-b4f38080-bdfe-11e8-92d9-cd390da60a19.png)

如果可能，请尝试使用最新版的 .NET Framework 看看？如果已经安装，请修复安装一次看看：
https://www.microsoft.com/net/download/dotnet-framework-runtime

**Comment by celeron533** [comment]
怀疑是.net framework有损坏。
因为快捷键初始化要识别语言和键盘布局

**Comment by chenshaoju** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=30135

试试这个，记得重启。
