### ISSUE TITLE
shadowsocks for windows 

### ISSUE THREAD

**Issue by satmuts** [shadowsocks/shadowsocks-windows#2015]
my case is very simple or that how it seems . i have proxy software on my PC . i get access to the proxy from this software via 127.0.0.1 Port 9951 . everything works great . Now i want my brother who live in another city to have access to this Proxy . my idea is

1- Installing shadowsocks  Server 
2- set server address > 127.0.0.1 and Port > 9951 this is where i get my socks 5 from the software i have 
3- give my brother access to connect to this server 
4- server will redirect all my brother connection via 127.0.0.1 port 9951

is this how simple it is ?

What IP i should give him when i'm behind NAT ? is it my Public IP ? Sorry for this noob Question this is not even my aria and have no idea if this is what shadowsocks is all about 

I will pay 100$ in btc for the one who get access to my PC "TeamViewer" and setup this . i already install python + shadowsocks server but have no idea how to make it work

**Comment by XeroChen** [comment]
Your question is definitely not about shadowsocks. It's all about how to build a tunnel between external PC and internal PC across NAT boundary.

There is no way to solve this problem unless you have permission to control the router at the edge of your NAT network. According to the principle of NAT, your brother's PC cannot directly initiate a connect to your server behind NAT.  
You must give your brother your public IP exposed by your NAT router and then setup a route rule (eg. port mapping) in your router to direct the traffic to the private IP of your PC.
Another way is to initiate a reverse connection to you brother(only if he had a accessible/public IP), it's far beyond this discussion...

**Comment by celeron533** [comment]
As @XeroChen mentioned,
Normally the server should have a public IP.

If both of the machines are in NAT, the following projects may help:
https://github.com/fatedier/frp
https://github.com/inconshreveable/ngrok
(etc..)

These projects are not related to shadowsocks. Please study and ask questions in their project's page.

**Comment by satmuts** [comment]
so my only problem with shadowsocks is because I'm behind NAT ? what if i rent Windows server with Public / Static IP and run my proxy server there with 127.0.0.1 / 9951 is this still possible to redirect all my brother traffic through that proxy ? i like shadowsocks and the idea that it has an IOS Client and DNS VIA SOCKS is exactly what i love about shadowsocks

**Comment by celeron533** [comment]
I remember will not resolve the DNS via socks5 by default.
Discussion:
https://github.com/FelisCatus/SwitchyOmega/issues/1534
