### ISSUE TITLE
影梭无法打开

### ISSUE THREAD

**Issue by fatinghenji** [shadowsocks/shadowsocks-windows#2017]
### Shadowsocks version /
4.1.2

### Environment(Operating system, .NET Framework, etc) / 
Windows10 家庭中文版

### Steps you have tried / 
下载最新版，解压，双击运行

### What did you expect to see? /
正常打开

### What did you see instead? / 
没有任何反应

### Config and error log in detail (with all sensitive info masked) / 
不清楚从哪里获取

**Comment by chenshaoju** [comment]
请确保安装了最新的 Microsoft .NET Framework ：
 https://www.microsoft.com/net/download/dotnet-framework-runtime

以及Microsoft Visual C++ 2015 Redistributable （３２位，选x86那个）：
https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by fatinghenji** [comment]
> 请确保安装了最新的Microsoft .NET Framework：[https](https://www.microsoft.com/net/download/dotnet-framework-runtime)：
> [//www.microsoft.com/net/download/dotnet-framework-runtime](https://www.microsoft.com/net/download/dotnet-framework-runtime)
> 
> 以及Microsoft Visual C ++ 2015 Redistributable（32位，选x86那个）：[https](https://www.microsoft.com/en-us/download/details.aspx?id=53840)：[//www.microsoft.com/en-us/download/details.aspx？](https://www.microsoft.com/en-us/download/details.aspx?id=53840) id [=](https://www.microsoft.com/en-us/download/details.aspx?id=53840) 53840
> [](https://www.microsoft.com/en-us/download/details.aspx?id=53840)

这两个软件我都已经安装了，但是依旧无法启动

**Comment by chenshaoju** [comment]
无法打开的话，请检查一下任务管理器，有无 Shadowsocks.exe 的进程？

如果可能，将 Shadowsocks.exe 单独放到一个新的目录中，如 D:\SS\ ，能启动吗？

**Comment by fatinghenji** [comment]
> 无法打开的话，请检查一下任务管理器，有无Shadowsocks.exe的进程？
> 
> 如果可能，将Shadowsocks.exe单独放到一个新的目录中，如D：\ SS \，能启动吗？

两个方法都尝试了，并没有用

**Comment by chenshaoju** [comment]
请看一下 Shadowsocks.exe 所在的目录下有无 ss_win_temp 目录？如果有，请进入该目录，有一个名为 shadowsocks.log 的文件，请将该文件的内容贴上来看看。

**Comment by fatinghenji** [comment]
> 请看一下Shadowsocks.exe所在的目录下有无ss_win_temp目录？如果有，请进入该目录，有一个名为shadowsocks.log的文件，请将该文件的内容贴上来看看。

我再我的电脑里并不能找到这个文件夹

**Comment by chenshaoju** [comment]
该问题可能未知，似乎是由于 Shadowsocks.exe 在启动的一瞬间被什么东西终止了。

请尝试检查计算机上的安全软件是否有拦截，如果仍然不行，可能需要备份数据并重置系统看看了。

**Comment by celeron533** [comment]
禁用杀毒软件
