### ISSUE TITLE
UI ERROR 非预期错误 - SetIEProxy

### ISSUE THREAD

**Issue by Tortoise1** [shadowsocks/shadowsocks-windows#2019]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
打开ss后正常使用

### What did you expect to see? / 期望的结果
无错误

### What did you see instead? / 实际结果
弹出错误弹窗

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![image](https://user-images.githubusercontent.com/22978161/46127980-d0c6ae80-c264-11e8-9b7d-0e9a22557975.png)

**Comment by chenshaoju** [comment]
请尝试： https://github.com/shadowsocks/shadowsocks-windows/issues/2013
