### ISSUE TITLE
WIN10报Shadowsocks non-UI Error，给管理员权限后开机自启无法使用

### ISSUE THREAD

**Issue by HowardMaCloud** [shadowsocks/shadowsocks-windows#2020]
### Shadowsocks version / 影梭版本

4.1.2 
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10 X64

### Steps you have tried / 操作步骤

刚开始设置开机启动报System.UnauthorizedAccessException错误，查找Issues后，由于本机是SSD因此未分区，所以将文件放在C:\Tools下，对文件右键选择所有用户使用管理员权限后，开机无法自动启动，但启动不报错误
### What did you expect to see? / 期望的结果

开机可以自动启动
### What did you see instead? / 实际结果
无法启动

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.UnauthorizedAccessException: 对路径“C:\Tools\Shadowsocks-4.1.2\ss_win_temp\shadowsocks.log”的访问被拒绝。

   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)

   在 System.IO.FileStream..ctor(String path, FileMode mode)

   在 Shadowsocks.Controller.Logging.OpenLogFile()

   在 Shadowsocks.Program.Main()
---------------------------
确定   
---------------------------

**Comment by HowardMaCloud** [comment]
> 请尝试删除 Shadowsocks.exe 所在目录下的ss_win_temp 文件夹，或者赋予你 Shadowsocks.exe 所在目录和子目录的当前Windows用户账户完整的控制权。

您好，首先感谢您的回复！
已尝试使用方法一，问题未解决
关于方法二，我给予文件夹权限后问题未解决，但我使用的是微软账户，未切换到本地账号，也未找到微软账户的权限管理

**Comment by chenshaoju** [comment]
我也是Microsoft ID登录的，但是也有这个界面，请确认你的系统：
![Screenshot](https://user-images.githubusercontent.com/515763/46189777-f0241100-c322-11e8-9f33-270bd9f4d826.png)

**Comment by HowardMaCloud** [comment]
你好，可能是我表述有误，上图我也是有的，我本来想表述的意思是没有找到对应我登录账号的用户名所对应的权限组，我登录的用户名类似“123@126.com”这种。
在上述安全里，我将其文件夹已设置了完全控制，但是问题依旧未解决。

**Comment by chenshaoju** [comment]
请测试一下：
在 C:\ 新建一个目录，比如 C:\SS\ ，然后赋予 C:\SS\ 目录 Everyone 权限，类似这样：
![2018-09-28 3](https://user-images.githubusercontent.com/515763/46191560-90316880-c32a-11e8-811b-abd8b86cadfa.png)

然后单独将 Shadowsocks.exe 复制进去，重新配置，看看是否还会出问题。

**Comment by HowardMaCloud** [comment]
你好，非常感谢您的耐心解答，现阶段问题已解决
解决办法：
1、删除Tools目录下的所有SS文件，包括程序
2、安装了一个“微软常用运行库合集”
3、重新安装net包与VC包，将程序重新拷入tools\SS文件夹内
4、文件夹的权限管理未作处理（采用系统默认）
重启后问题解决

**Comment by chenshaoju** [comment]
Hmmm...我觉得是权限问题，也许是复制过程重置了权限（继承了新权限）。

理论上VS或dotNET运行库不会对权限造成影响。
