### ISSUE TITLE
关于IPv6的支持咨询

### ISSUE THREAD

**Issue by MrXionGe** [shadowsocks/shadowsocks-windows#2021]
你好，我并不是提交问题，所以没有按照预设的格式来，请谅解。
我最近发现一部分VPS开始支持IPv6了，所以特意来资讯一下，我们的小工具在服务端和客户端（Windows和Android）都支持配置IPv6的地址吗？

**Comment by chenshaoju** [comment]
我没有办法确认Android的情况，但是Windows和libev版是肯定支持的。

https://twitter.com/chenshaoju/status/1043793175280844801

**Comment by MrXionGe** [comment]
@chenshaoju  好的多谢！还有赞一下你推特的刺客信条背景，哈哈！
