### ISSUE TITLE
关于例外设定

### ISSUE THREAD

**Issue by yige2020** [shadowsocks/shadowsocks-windows#2022]
老铁能把例外配置重构一下吗，多次尝试各种方法均无法保存自定的例外域名，软件隔一段时间后自动恢复默认值，每次都需要到IE里重新设定，做开发的经常需要定义多个本地域名做测试，真的非常痛苦。

**Comment by chenshaoju** [comment]
请右击托盘区的纸飞机图标，选择PAC，再点击“编辑用户GFWList的用户规则“，然后在生成的 user-rule.txt 文件中，按照下列格式添加你想要的例外即可：
```
@@||example.com
@@||123.45.67.89
```

**Comment by osdu** [comment]
参考 https://github.com/osdu/shadowsocks-windows-plus/commit/40cfa4b139d1c8e5e091a1126a12a8e2c149c139 自己编译一个，全局模式可以支持五组例外域名。

**Comment by chenshaoju** [comment]
此问题已在4.1.3.1中得到经解决。

**Comment by osdu** [comment]
@chenshaoju 有设置界面吗？

**Comment by studentmain** [comment]
没有，直接取系统代理设置中的例外

**Comment by osdu** [comment]
@studentmain 嗯了解，刚看了下新版本。我现在用的自己修改的版本，WEB 开发比较方便。不过还是建议添加一个参数，可以自己追加全局模式下的例外列表

**Comment by ylvict** [comment]
@yige2020 这个已经在 a63dec84 中改了，现在可以手动修改ss_win_temp\user-wininet.json 里的 BypassList ，把自己需要bypass的域名列在这个列表中即可。
