### ISSUE TITLE
不能连接服务器

### ISSUE THREAD

**Issue by DuYLEi** [shadowsocks/shadowsocks-windows#2023]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows10 .NET 4.6.2
### Steps you have tried / 操作步骤
无法连接服务器

### What did you expect to see? / 期望的结果

连接成功
### What did you see instead? / 实际结果

并不能按照#1487解决
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
``` 由于远程方已关闭传输流，身份验证失败。 ```

请确保你的服务器工作正常，如果可能，请使用tcping 进行测试，看看端口是否能连通。

你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。

这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
```
tcping -t 123.45.67.89 9876
```
其中 123.45.67.89 替换为你的SS服务器地址， 9876 替换为你的你的SS端口，然后回车，此时，如果显示 Port is open ，这说明端口通，如果不通，则可能提示 No response 或 Port is close。

**Comment by DuYLEi** [comment]
Port is open，但浏览器仍不能上Google

**Comment by DuYLEi** [comment]
而且错误日志依然是上面的内容

**Comment by chenshaoju** [comment]
端口是通的情况下，请仔细检查你的配置是否正确，包括端口、加密算法、密码是否和服务器一致。

另外，你有其他的计算机或者手机吗？相同的配置，其他设备能否使用？

**Comment by DuYLEi** [comment]
与服务器一致，并且同一网络下，其他电脑和手机都能正常使用，会不会是被封IP了

**Comment by chenshaoju** [comment]
有个类似的报告：https://github.com/shadowsocks/shadowsocks-windows/issues/2016 ，你可能需要套一层simple-obfs或者goquite之类的插件进行混淆。

**Comment by DuYLEi** [comment]
谢谢指导，我电脑连接手机可以代理，连接宽带不行，可能运营商给封禁了，不过混淆问题还不会解决

**Comment by chenshaoju** [comment]
建议试试２２、４４３、３３８９端口。
