### ISSUE TITLE
异常大量占用CPU

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-windows#2024]
### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10专业版17134.112，默认并未手动安装任何版本的.NET Framework，但是能正常使用SS

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
断网后，开始异常大量占用CPU期间的日志：

[2018-09-29 12:10:59] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

都是这一段同样的日志

补充说明图片：
![s s](https://user-images.githubusercontent.com/10991795/46240998-5fad0580-c3e2-11e8-9117-d1de9cc9ebb0.JPG)
断网后异常大量占用CPU

![ss](https://user-images.githubusercontent.com/10991795/46241001-705d7b80-c3e2-11e8-963d-94cc6e2e94d2.JPG)
回复网络连接后，CPU占用正常

**Comment by chenshaoju** [comment]
请问你上网时网线直接插上就上网了，还是需要通过一个程序或者拨号才能上网？

**Comment by Aniark** [comment]
@chenshaoju 我是用手机USB网络共享

**Comment by celeron533** [comment]
难道是由于网卡消失落到了回环？@chenshaoju

**Comment by chenshaoju** [comment]
感觉是在尝试继续在这个不存在的网卡上监听或者发起连接？这一块我不太懂了）

**Comment by celeron533** [comment]
我在设备管理器中直接禁用硬件没能重现 @chenshaoju

**Comment by chenshaoju** [comment]
@celeron533 刚测试了一下，发现无法复现。我怀疑是否和升级到了Windows 10 1809有关。

@Aniark 请问你的Windows 10是否已经升级到了1809？是否还有此问题？

**Comment by Aniark** [comment]
@chenshaoju 尚未升级1809——考虑到微软每次更新都会带来一堆bug的尿性，我选择了”半年频道“推迟更新

**Comment by chenshaoju** [comment]
@Aniark 那么你是否还有该问题？能否测试一下？

**Comment by Aniark** [comment]
@chenshaoju 再次测试了一下，目前发现使用ss作为IDM的代理下载文件的时候断网，会出现这个bug。用chrome下载的话就没有

**Comment by celeron533** [comment]
@Aniark 是不是IDM在断掉后不断尝试连接呢

**Comment by Aniark** [comment]
@celeron533 是的
