### ISSUE TITLE
ss手机可用，win7 不可用，提示 同一个套接字上正在进行另一个异步操作时，不能调用 BeginConnect。

### ISSUE THREAD

**Issue by U-23** [shadowsocks/shadowsocks-windows#2025]
System.InvalidOperationException: 同一个套接字上正在进行另一个异步操作时，不能调用 BeginConnect。
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()

**Comment by chenshaoju** [comment]
请双击托盘区的纸飞机图标，在右下角的代理端口中换一个端口看看，比如2080或者3080。

https://github.com/shadowsocks/shadowsocks-windows/issues/1918

**Comment by U-23** [comment]
> 请双击托盘区的纸飞机图标，在右下角的代理端口中换一个端口看看，比如2080或者3080。
> 
> #1918

测试过了，还是一样

**Comment by U-23** [comment]
> 可能和TCP/IP或Winsocks有关，请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
> 
> ```
> netsh interface ipv4 reset
> netsh interface ipv6 reset
> netsh interface tcp reset
> netsh winsock reset
> ```
> 一行一回车，四行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。
> 
> 重启后看看效果是否有改善。

大佬，还是没用@chenshaoju。另外台电脑显示
System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()

**Comment by chenshaoju** [comment]
你是否有使用一种像U盘一样的免费WiFi？就是那种插上就能让其他设备通过计算机上网的那玩意儿。

`提供了一个无效的参数` 可能和你的网络有关：https://github.com/shadowsocks/shadowsocks-windows/issues/1902 。

**Comment by U-23** [comment]
> 你是否有使用一种像U盘一样的免费WiFi？就是那种插上就能让其他设备通过计算机上网的那玩意儿。
> 
> `提供了一个无效的参数` 可能和你的网络有关：#1902 。

还真是。其他都测了，没注意到这个，解决了。谢谢大佬@chenshaoju

**Comment by walix123** [comment]
> 请双击托盘区的纸飞机图标，在右下角的代理端口中换一个端口看看，比如2080或者3080。
> 
> #1918

发生类似情况，手机可用，同一局域网其他电脑可用。日志提示：[Error] connect to update server error。改个端口好了。。。

**Comment by Alwayslazydog** [comment]
> 你是否有使用一种像U盘一样的免费WiFi？就是那种插上就能让其他设备通过计算机上网的那玩意儿。
> 
> `提供了一个无效的参数` 可能和你的网络有关：#1902 。

老哥 我的都试了 还是不行 台式用的是无线网卡USB 那种，笔记本 安卓也不行 连不上

**Comment by x82423990** [comment]
我也是这样的，，， 紧急求助。。。
![image](https://user-images.githubusercontent.com/10044279/52767903-ce73be00-3066-11e9-9863-9a2a862b9735.png)

**Comment by chenshaoju** [comment]
能否在有问题的计算机上测试一下 tcping ？
https://github.com/shadowsocks/shadowsocks-windows/issues/2209#issuecomment-463503308
