### ISSUE TITLE
开机启动不能正常工作

### ISSUE THREAD

**Issue by C0ye** [shadowsocks/shadowsocks-windows#2026]
### Shadowsocks version / 影梭版本
4.0.10.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 Pro Build 17134
.NET版本v4.0.30319

### Steps you have tried / 操作步骤
最近开始不能正常开机启动，没有七七八八的卫士助手，应用程序在系统启动项中，不知道有没有和我一样的?

**Comment by chenshaoju** [comment]
请阅读： https://github.com/shadowsocks/shadowsocks-windows/issues/1906

**Comment by C0ye** [comment]
> 请阅读： #1906

我尝试在卡巴加入信任和完全关闭卡巴斯基，都自启不了。而且跟这个issue有些区别，我这个是压根不运行。总之很感谢

**Comment by C0ye** [comment]
翻了一个上古老坟，原因在于不知道什么时候把SS改成默认管理员启动了，关掉就行了。

**Comment by C0ye** [comment]
好像是windows UAC的一个老问题

**Comment by chenshaoju** [comment]
如果你启用了UAC，并且将SS配置为以管理员身份启动，理论上在开机的时候会一个授权确认。

不过完全没反应这个还是很奇怪。
