### ISSUE TITLE
Windos10 1809无法使用

### ISSUE THREAD

**Issue by lzxyz** [shadowsocks/shadowsocks-windows#2029]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10企业版 版本号1809 
.NET Framework 4.7

### Steps you have tried / 操作步骤
打开Shadowsocks-》更新PAC-》失败
### What did you expect to see? / 期望的结果
正常使用

### What did you see instead? / 实际结果
无法使用

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
{
      "server": "23.106.152.74",
      "server_port": 443,
      "password": "*******",
      "method": "aes-256-cfb",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 20
    }
```
日志
```
[2018-10-05 10:18:49] Shadowsocks started (4.1.2)
[2018-10-05 10:18:49] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-10-05 10:18:51] connect to api.github.com:443
[2018-10-05 10:18:52] Socket connected to ss server: 23.106.152.74:443
[2018-10-05 10:18:52] connect to api.github.com:443
[2018-10-05 10:18:52] Socket connected to ss server: 23.106.152.74:443
[2018-10-05 10:18:52] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-10-05 10:18:58] connect to clients1.google.com:443
[2018-10-05 10:18:59] Socket connected to ss server: 23.106.152.74:443
[2018-10-05 10:18:59] connect to clients1.google.com:443
[2018-10-05 10:18:59] Socket connected to ss server: 23.106.152.74:443
[2018-10-05 10:19:00] connect to clients1.google.com:443
[2018-10-05 10:19:00] Socket connected to ss server: 23.106.152.74:443
[2018-10-05 10:19:00] connect to clients1.google.com:443
[2018-10-05 10:19:00] Socket connected to ss server: 23.106.152.74:443

```

**Comment by lzxyz** [comment]
BWG搭建的。同一个网络能用下windows版本不能用，安卓版本能用，都是同样的混淆算法

**Comment by chenshaoju** [comment]
这个问题目前无法解释，所以需要进一步测试。如果可能，请搭一个混淆测试一下以进行验证，原帖后来没反映了，不知结果。

**Comment by lzxyz** [comment]
> 这个问题目前无法解释，所以需要进一步测试。如果可能，请搭一个混淆测试一下以进行验证，原帖后来没反映了，不知结果。

用Simple-obfs也无法使用（windows无法使用）。加密换到camelia-265-cfb也无法使用（安卓能使用 windows不行）。重装系统去了

**Comment by chenshaoju** [comment]
如果你还没有重装，该问题也可能和TCP/IP或Winsocks有关，请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。

重启后看看效果是否有改善。

**Comment by lzxyz** [comment]
没有作用。还是老样子。

**Comment by lzxyz** [comment]
暂时找到能用的shadowsocks-go 中shadowsocks-local-win64-1.1.5配合SwitchyOmega能用

**Comment by chenshaoju** [comment]
是否已经重装系统了，但是还是不行？

**Comment by celeron533** [comment]
#2032 有提到在更新以后出现framework损坏，修复后恢复正常，可以试一下

**Comment by lzxyz** [comment]
这个应该是新版系统的问题。.NET 3.5勾上也不行，4.7全勾上也不行。😔重启系统去了，暂时用替代方案玩玩

**Comment by chenshaoju** [comment]
无法确定。。。。
![2018-10-09](https://user-images.githubusercontent.com/515763/46653234-0c079c80-cbd8-11e8-8e8f-2ab6b0a0b6fd.png)

**Comment by lzxyz** [comment]
企业版

**Comment by chenshaoju** [comment]
理论上跟企业版／家庭版／教育版等版本没有关系……
