### ISSUE TITLE
希望添加监听gui-config.json变化

### ISSUE THREAD

**Issue by Fndroid** [shadowsocks/shadowsocks-windows#2031]
目前对于gui-config.json的加载似乎是在Shadowsocks启动或者进入节点列表然后点击“确定”才会触发，希望可以考虑增加对gui-config.json变化的监听。

这样第三方可以直接对这个文件进行修改然后直接影响Shadowsocks界面（包括节点列表和菜单）而不需要重启应用。

例如从iOS或Android的其他应用配置文件生成对应的gui-config.json，这样对文件进行覆盖后能直接生效并在菜单中选择节点使用。

**Comment by celeron533** [comment]
iOS和Android生成的配置文件和Windows桌面版有较大差异，不建议直接使用

**Comment by Fndroid** [comment]
@celeron533 我已经编写了对应转换的API

**Comment by Fndroid** [comment]
好吧，感谢
