### ISSUE TITLE
有时打开网页会报GET https://www.youtube.com/ net::ERR_CONNECTION_CLOSED 200错误

### ISSUE THREAD

**Issue by lijingchun0** [shadowsocks/shadowsocks-windows#2033]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 

### Steps you have tried / 操作步骤
有时会出现    GET https://www.youtube.com/ net::ERR_CONNECTION_CLOSED 200错误
页面显示空白，有时重启下服务器就好了，没有改其他任何配置

### What did you expect to see? / 期望的结果
能正常连接

### What did you see instead? / 实际结果
有时不能连接

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
{
    "server":"0.0.0.0",
    "server_port":***,
    "password":"*******",
    "timeout":300,
    "user":"nobody",
    "method":"chacha20",
    "fast_open":true,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp"
}

**Comment by chenshaoju** [comment]
日志中有什么显示吗？

**Comment by lijingchun0** [comment]
> 日志中有什么显示吗？

=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-10-09 17:37:16] connect to s.ytimg.com:443
[2018-10-09 17:37:16] connect to www.youtube.com:443
[2018-10-09 17:37:16] Socket connected to ss server: ******:****
[2018-10-09 17:37:16] Socket connected to ss server: *******:*****
[2018-10-09 17:37:18] connect to www.youtube.com:443
[2018-10-09 17:37:18] Socket connected to ss server: *******:*****
[2018-10-09 17:37:18] connect to www.youtube.com:443
[2018-10-09 17:37:18] Socket connected to ss server: *******:*****
[2018-10-09 17:39:09] connect to translate.google.com:443
[2018-10-09 17:39:09] Socket connected to ss server: *******:*****
[2018-10-09 17:39:10] connect to translate.google.com:443
[2018-10-09 17:39:10] Socket connected to ss server:*******:*****
[2018-10-09 17:42:38] connect to clients1.google.com:443
[2018-10-09 17:42:38] Socket connected to ss server: *******:*****
[2018-10-09 17:48:22] connect to clients1.google.com:443
[2018-10-09 17:48:22] Socket connected to ss server: *******:*****
[2018-10-10 08:54:40] Shadowsocks started (4.1.2)
[2018-10-10 08:54:41]

**Comment by JYG0723** [comment]
遇到同样的问题，手机上一直可以正常使用，
win10笔记本连得手机热点的网络，有时候开了ss和没开ss。有时候一天都打不开google，有时候自己就好了，最近经常这样。

日志一样：
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor

**Comment by chenshaoju** [comment]
@JYG0723 请尝试连接上网络后，退出SS，然后再启动SS看看。

@lijingchun0 日志中看不出来什么问题，可能和TCP/IP或Winsocks有关，请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。

重启后看看效果是否有改善。

**Comment by lijingchun0** [comment]
> @JYG0723 请尝试连接上网络后，退出SS，然后再启动SS看看，另外，确保你的连接名字不是中文的。
> 
> @lijingchun0 日志中看不出来什么问题，可能和TCP/IP或Winsocks有关，请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
> 
> ```
> netsh interface ipv4 reset
> netsh interface ipv6 reset
> netsh interface tcp reset
> netsh winsock reset
> ```
> 一行一回车，四行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。
> 
> 重启后看看效果是否有改善。

没有用 ε=(´ο｀*)))唉

**Comment by chenshaoju** [comment]
日志中看不出来什么问题。。。可能你的服务器存在某些（网络或系统）方面的问题。。。

也许换一个端口可能有用。

**Comment by lijingchun0** [comment]
> 日志中看不出来什么问题。。。可能你的服务器存在某些（网络或系统）方面的问题。。。
> 
> 也许换一个端口可能有用。

瓦工的vps   脚本用的/teddysun大佬的   我朋友和我用的一样的  不知道我的为啥就有这种问题

**Comment by JYG0723** [comment]
> @JYG0723 请尝试连接上网络后，退出SS，然后再启动SS看看，另外，确保你的连接名字不是中文的。

尝试了多次还是老问题，连接名字也不是中文的。后来再也连不上了google，后来我尝试把客户端软件的"允许其他设备连入"勾选上了之后就可以成功访问了。并且几天下来感觉比较稳定。

比较好奇这是什么原因？使原本就需要点开吗，我操作不当关掉了吗？

**Comment by chenshaoju** [comment]
本来不需要点开的，这个功能是提供给当前网络上所有人使用的……
唯一的区别是如果未选择则绑定在 127.0.0.1 供你自己使用，如果选中了就绑定在 0.0.0.0 上供当前网络的所有人使用。

**Comment by celeron533** [comment]
1. 开全局代理看看
2. 如果装过wifi共享工具可能会有此问题？
