### ISSUE TITLE
Windows Update 1809第一个补丁后出现端口被占用错误

### ISSUE THREAD

**Issue by isaacwang2018** [shadowsocks/shadowsocks-windows#2035]
### Shadowsocks version / 影梭版本

4.1.2
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

windows 10 1809
### Steps you have tried / 操作步骤

10月5日升级到1809，一切正常，也没出现网上说的文件丢失的问题。
10月10日更新微软的1809的第一个补丁KB4464330，发现同时更新了KB4465477（不可卸载）和flash更新。
重启后，打开ss弹出错误对话框，提示端口被占用，以一种访问权限不允许的方式使用套接字。
![_20181010115052](https://user-images.githubusercontent.com/44013500/46712363-437f5300-cc83-11e8-8b3f-032e01418bf0.png)

### What did you expect to see? / 期望的结果

恢复正常
### What did you see instead? / 实际结果

？
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
normal

**Comment by chenshaoju** [comment]
![2018-10-10 2](https://user-images.githubusercontent.com/515763/46715282-e939be80-cc91-11e8-9eb2-bdfdcaeba7ac.png)

我也安装了这个补丁，但是没有这个问题。

请尝试双击纸飞机图标，在编辑服务器界面右下角换一个端口看看？

**Comment by isaacwang2018** [comment]
看起来我比你多更新了一个KB4465477，查了一下：Servicing stack update for Windows 10, version 1809: October 9, 2018。
是不是这个的问题啊，堆栈补丁。
不知道有没有人打过这个补丁但没有我这个问题的

**Comment by chenshaoju** [comment]
我改了1080，也没这个错误……
![2018-10-10 3](https://user-images.githubusercontent.com/515763/46716673-8f3bf780-cc97-11e8-94f4-e9ce99dfb005.png)

不过能work就行。

**Comment by celeron533** [comment]
可能其他服务占据了这个端口。

**Comment by chenshaoju** [comment]
不像是该补丁导致的问题。

![2018-10-10 4](https://user-images.githubusercontent.com/515763/46717984-68cc8b00-cc9c-11e8-9574-703268ebf1e7.png)

**Comment by isaacwang2018** [comment]
netstat -aon|findstr 1080
没有发现此端口被占用啊

**Comment by DevSplash** [comment]
> netstat -aon|findstr 1080
> 没有发现此端口被占用啊

1809后有几个系统进程会随机使用1080端口，比如lsass.exe SearchUI.exe等，以及非系统进程如Nvidia的一个服务进程也可能使用，原因不明

**Comment by lzskyline** [comment]
管理员模式运行cmd:
netsh int ipv4 show dynamicport tcp
netsh int ipv4 set dynamic tcp start=49152 num=16384
重启即可
