### ISSUE TITLE
time out 基础连接已经关闭: 发送时发生错误

### ISSUE THREAD

**Issue by liuruiqi1993** [shadowsocks/shadowsocks-windows#2038]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
(4.1.2)

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

win10家庭中文版

 .NET Framework 
![a1](https://user-images.githubusercontent.com/33003931/46782571-4cdaef00-cd59-11e8-94c5-959aa8cdf0de.PNG)
![a2](https://user-images.githubusercontent.com/33003931/46782351-8101e000-cd58-11e8-8c42-f9db5f7b4b83.PNG)

装4.6.2会提醒
![a3](https://user-images.githubusercontent.com/33003931/46782373-92e38300-cd58-11e8-8ea1-ecd64b46577a.PNG)

### Steps you have tried / 操作步骤
防火墙全关了
没有杀毒软件
tcping  open
试过了reset
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
账号密码公司给的别人可以用

### What did you see instead? / 实际结果

开了Shadowsocks所有的网页都打不开，包括百度

代理会自己变成这样
![aaa](https://user-images.githubusercontent.com/33003931/46782631-7431bc00-cd59-11e8-861a-6991a70283f5.PNG)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2018-10-11 13:30:54] Shadowsocks started (4.1.2)
[2018-10-11 13:30:54] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-10-11 13:30:58] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```
详细日志里会提示time out

**Comment by chenshaoju** [comment]
``` 由于远程方已关闭传输流，身份验证失败。 ```

请确保你的服务器工作正常，如果可能，请使用tcping 进行测试，在出现time out时，看看端口是否能连通。

你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。

这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
```
tcping -t 123.45.67.89 9876
```
其中 123.45.67.89 替换为你的SS服务器地址， 9876 替换为你的你的SS端口，然后回车，此时，如果显示 Port is open ，这说明端口通，如果不通，则可能提示 No response 或 Port is close。

**Comment by liuruiqi1993** [comment]
```
Ping statistics for 23.83.233.82:443
     31 probes sent.
     31 successful, 0 failed.  (0.00% fail)
Approximate trip times in milli-seconds:
     Minimum = 173.184ms, Maximum = 217.978ms, Average = 193.079ms
```

**Comment by chenshaoju** [comment]
这个是在显示timeout的时候吗？

看起来是通的，如果可能，请套一个Simple-obfs或者GoQuite看看，有一个类似的案例，加上obfs就好了： https://github.com/shadowsocks/shadowsocks-windows/issues/2016

**Comment by liuruiqi1993** [comment]
不是自己搭的服务器也是这样解决吗？

**Comment by chenshaoju** [comment]
请与你的服务商联系，或者访问你的服务商网站，更换一个服务器地址或者IP。
