### ISSUE TITLE
无法打开匿名级安全令牌

### ISSUE THREAD

**Issue by Massdama** [shadowsocks/shadowsocks-windows#2039]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.12

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7 64bit 7601 NET Framework4.6.2

### Steps you have tried / 操作步骤
无法连接VPS

### What did you expect to see? / 期望的结果
 Shadowsocks.Util.SystemProxy.ProxyException: Error setting options: 1347 无法打开匿名级安全令牌。

   at Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   at Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   at Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
你的DCOM组件可能被修改过。

请尝试： https://www.cnblogs.com/renrsh/p/6670648.html
