### ISSUE TITLE
不打开ss的时候，部分软件无法上网（并未设置代理模式）

### ISSUE THREAD

**Issue by sarmey** [shadowsocks/shadowsocks-windows#2040]
## 操作步骤
用腾讯视频（其他部分游戏也一样）来举例：
- 当我右下角退出SS客户端的时候（也就是不开启SS客户端），腾讯视频的播放页面无法播放。
- 当我双击打开SS客户端，腾讯视频（以及其他游戏）就能正常播放（连接）

PS：Internet选项 - 连接 - 局域网设置 - 自动检测设置（勾选该选项，其他两个选项都无勾选）
PS：腾讯视频（以及其他游戏）无“设置代理模式”选项
PS：无论是否开启SS客户端，浏览器（IE，Edge，Chrome，Firefox）都能正常上网。

##  期望的结果
不开启SS客户端的时候，腾讯视频及游戏能正常连接

## 实际结果
不开启SS客户端，部分软件无法连接网络；开启SS客户端，就都没问题。
感觉就是部分客户端强制通过SS代理上网，但是重点是这些客户端并没有设置代理模式

## Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
此问题可能和系统代理有关，在某些情况下， user-wininet.json 可能会导致配置混乱，请尝试执行以下操作：
　　１.退出 SS ，进入 Shadowsocks.exe 所在的目录，找到 user-wininet.json ，删除或者重命名。
　　２.进入控制面板，打开 Internet 选项，点击连接选项卡，点击局域网设置，确保选中了“自动检测设置”，并且**未选中**“使用自动配置脚本”和“为LAN使用代理服务器“。
　　３.设置完毕后点击确定，然后再确定。
　　４.请检查是否可以上网。
　　５.再次启动 Shadowsocks.exe ，此时你的代理例外设置会被保存，即可正常使用。

**Comment by jokezhao** [comment]
好的
