### ISSUE TITLE
联通无法使用

### ISSUE THREAD

**Issue by lex0bomb** [shadowsocks/shadowsocks-windows#2041]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10 64 1803 17134.345

### Steps you have tried / 操作步骤
SS没有问题 本地网络运营商 使用移动 启动SS 无任何问题 
但是 换成联通光纤 PPPoe拨号上网 启动SS无任何反应 
全局模式 蓝色纸飞机无数据传输指示（红色绿色都没有）
NET Framework 4.6.2 和 Microsoft Visual C++ 2015 Redistributable (x86) 均已正常安装

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2018-10-16 06:22:16] Shadowsocks started (4.1.2)
[2018-10-16 06:22:16] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================
```

**Comment by lex0bomb** [comment]
无法访问此页面

•确保 Web 地址https://www.google.com 正确
•在必应上搜索此站点
•刷新页面







详细信息  详细信息   


发生临时 DNS 错误。请尝试刷新页面。


错误代码: INET_E_RESOURCE_NOT_FOUND

**Comment by chenshaoju** [comment]
如果是电脑上直接PPPoE拨号，请在拨号成功后退出SS，然后再启动。

另外，请确保PPPoE的拨号连接名称为英文或数字，“宽带连接”或其他中文的连接名称可能会不工作。

**Comment by lex0bomb** [comment]
这是。。。为啥。。。真的可以了。。。。
但是 莫名速度变慢了
以前用移动的光纤 youtube播4K视频 连接速度基本维持在6xxxxkbps
 
现在用联通基本就在1xxxxkbps

**Comment by chenshaoju** [comment]
运营商线路问题，这个没办法控制。

**Comment by lex0bomb** [comment]
多谢! 这个疑难杂症居然这么解决的..........
