### ISSUE TITLE
外网不能使用局域网中的PAC代理

### ISSUE THREAD

**Issue by yl332332** [shadowsocks/shadowsocks-windows#2042]
在外网打开PAC网址，提示Invalid header received from client.错误，这个怎么办？
Google了下有下面解决方法，但ss_privoxy没有config.txt配置文件：
**privoxy Invalid header received from client.
2016年10月12日 10:42:34 friendan 阅读数：5133 标签： privoxy  更多
个人分类： privoxy 代理 config.txt
今天使用privoxy代理出现如下错误：
Invalid header received from client.

解决方法：
在proxy.exe配置文件config.txt中加入如下配置项即可：
accept-intercepted-requests 1**

**Comment by chenshaoju** [comment]
你是要在公网上访问你的SS所提供的PAC吗？
pac不是由privoxy提供的，是ss本身提供的服务。
请尝试右击托盘区的纸飞机图标，然后启动“允许其他设备连入”，然后再试。
注意：这会使得你的SS代理端口也暴露在公网上，可能会被其他人利用，存在风险。

**Comment by yl332332** [comment]
> 你是要在公网上访问你的SS所提供的PAC吗？
> pac不是由privoxy提供的，是ss本身提供的服务。
> 请尝试右击托盘区的纸飞机图标，然后启动“允许其他设备连入” ，然后再试。
> 注意：这会使得你的SS代理端口也暴露在公网上，可能会被其他人利用，存在风险。

是做代理服务器用的，在局域网中可以，但公网使用就会提示错误。
局域网中：http://192.168.0.1:1080/pac?t=20181016084431207&secret=AKBFSAFd+MFDASFOwuFSAFDmNAtFDSABYb8=可以使用，但
外网：http://域名:1080/pac?t=20181016084431207&secret=AKBFSAFd+MFDASFOwuFSAFDmNAtFDSABYb8=就提示错误。

pac是ss重新封装的ss_privoxy提供的，ss_privoxy只有一个privoxy_-621990493.conf配置文件，但根据Google的解决方法配置没有用。

**Comment by chenshaoju** [comment]
不确定你所说的情况，SS所指定的代理端口是监听在Shadowsocks.exe的进程上的。

我试了一下，在启用允许其他设备连入后，IP地址是可以的，但是计算机名的确不行，域名可能也不行，请尝试使用IP看看。

**Comment by fuxianwu** [comment]
@chenshaoju，你的问题解决了没有，我也遇到这个问题了，在内网穿透后，无法提供外网服务，提示Invalid header received from client，在ss_win_temp文件夹下的privoxy_-1769133987.conf中增加参数accept-intercepted-requests 1也不行，哎，尴尬

**Comment by chenshaoju** [comment]
@fuxianwu 我没有这个需求，因为将代理端口直接暴露在公网上是非常危险的，可能会被人发现然后做一些出格的事情，也可能会被第三方监测到。

你用的内网穿透具体是什么内网穿透？还是做了一个端口映射？

**Comment by rascalquan** [comment]
我也遇到了，不过我是在内网里，经测试发现，IP可以，换成机器名就不行了，应该是无法解析导致的吧

**Comment by celeron533** [comment]
取消“保护本地PAC”
