### ISSUE TITLE
win10笔记本从屏保重新进入系统，ss客户端经常失效

### ISSUE THREAD

**Issue by iocharset** [shadowsocks/shadowsocks-windows#2043]
### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10笔记本，Chrome浏览器（69.0.3497.100），Proxy SwitchyOmega插件（2.5.20）
Shadowsocks客户端没启动系统代理，通过Proxy SwitchyOmega分流

### Steps you have tried / 操作步骤
离开一段时间，笔记本进入屏保，回来重新进入桌面，在Chrome中输入需要走代理的网址，无法访问，错误提示：ERR_PROXY_CONNECTION_FAILED。重启Shadowsocks客户端，则恢复正常，问题解决。

早前好几个版本都一直有这个问题，因为可以重启解决，影响不大，一直没管。

**Comment by chenshaoju** [comment]
该问题也可能和TCP/IP或Winsocks有关，请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。

重启后看看效果是否有改善。

**Comment by celeron533** [comment]
从各种用户的反馈情况来看，这个似乎是个例，极有可能和你的操作系统有关。。。

**Comment by AlvinSeyir** [comment]
我也有这个问题...

**Comment by chenshaoju** [comment]
@AlvinSeyir 日志里有任何现实吗？

**Comment by AlvinSeyir** [comment]
> 
> 
> @AlvinSeyir 日志里有任何显示吗？

我是小白…这是我日志里面的一段，日志里面有很多这样的内容，还请您看看是怎么回事：
[2019-01-19 18:36:10] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-01-19 18:36:10] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-01-19 18:36:10] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-01-19 18:36:21] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
这一节日志看起来很像你的设备没有网络。。。查了一下，和这个一样：https://github.com/shadowsocks/shadowsocks-windows/issues/2024

我怀疑你的无线网卡是不是会在休眠或者待机的情况下断开以节省电力，看起来就是这个设备消失了一样。

这个时候，你的设备没有任何可以使用的网络接口了，于是就变成这个提示了。

如果可能，请做一个测试：

１.打开设备管理器，选中设备树顶部你自己的计算机名，然后点击操作菜单，选择添加过时硬件。
２.下一步后，点击（高级），然后下一步，从列表中选择网络适配器，下一步。
３.从列表中的厂商找到 Microsoft ，型号里找到 Microsoft KM-TEST 环回适配器（也可能是Microsoft Loopback Adapter）。
４.一直下一步，直到完成。

最后，你可以在网络连接里看到多了一个网络连接，重启计算机后再观察一下是否会出现这个现象。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
