### ISSUE TITLE
能不能自动更新gfwlist

### ISSUE THREAD

**Issue by LsnmxNB** [shadowsocks/shadowsocks-windows#2044]
本地哪个PAC不会自动更新啊，总要手动更新麻烦，谢谢！
GFWList URL(Github): https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by chenshaoju** [comment]
你好，SS内置的PAC就是GFWList的。 https://github.com/shadowsocks/shadowsocks-windows/blob/8ce4b3b8967be1df0409a5992bb9746cbbb155c2/shadowsocks-csharp/Controller/Service/GfwListUpdater.cs#L17

**Comment by LsnmxNB** [comment]
@chenshaoju  你好，请问会不会自动更新啊？我发现都要自己手动更新

**Comment by chenshaoju** [comment]
我没有用过这个功能，我的PAC是自己写的。

我的理解是，“在线PAC”应该就是直接从GFWList上下载回来的。

**Comment by LsnmxNB** [comment]
@chenshaoju  我的意思是，能定期自动更新PAC，要不然很烦自己一个月点一次更新

**Comment by studentmain** [comment]
事实上想要的不是gfwlist作为在线pac（注：这从技术上来说不可行），而是自动更新gfwlist。就后者而言，显然是可行的，虽然我个人不打算写，但是欢迎其他人写。

**Comment by studentmain** [comment]
#2170
