### ISSUE TITLE
userrule中非例外规则无法覆盖pac中的例外规则(@@开头的)

### ISSUE THREAD

**Issue by wuqiling97** [shadowsocks/shadowsocks-windows#2047]
### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 1803

### Steps you have tried / 操作步骤
比如"fonts.googleapis.com"在pac.txt当中是不走代理的，规则为"@@||fonts.googleapis.com"。现在我想让该域名走代理，于是在user-rule.txt当中添加“||fonts.googleapis.com”，并且等待user-rule更新到pac当中。

### What did you expect to see? / 期望的结果
fonts.googleapis.com使用了shadowsocks访问

### What did you see instead? / 实际结果
fonts.googleapis.com仍未走代理。在更新后的pac.txt中看到
```
var rules = [
  "||fonts.googleapis.com",
  ...,
  "@@||fonts.googleapis.com",
  ...
]
```

### 可能的原因
试着直接编辑pac.txt文件，将例外规则（带@@的）放到无@@的规则的前面，结果仍然没有走代理。将例外规则删除，此时目标网站终于走代理了。

可能是因为例外规则的优先级高于非例外规则，导致例外规则一旦出现，就无法用非例外规则覆盖。

该问题目前可以通过手动编辑pac解决，但是一旦从gfwlist更新pac就需要重新编辑，请问是否有更好的方法？

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[pac.txt](https://github.com/shadowsocks/shadowsocks-windows/files/2495812/pac.txt)
[user-rule.txt](https://github.com/shadowsocks/shadowsocks-windows/files/2495813/user-rule.txt)
[shadowsocks.log](https://github.com/shadowsocks/shadowsocks-windows/files/2495815/shadowsocks.log)

**Comment by chenshaoju** [comment]
你好，pac.txt 是基于 GFWList 获取的：
https://github.com/shadowsocks/shadowsocks-windows/blob/8ce4b3b8967be1df0409a5992bb9746cbbb155c2/shadowsocks-csharp/Controller/Service/GfwListUpdater.cs#L17

目前， `fonts.googleapis.com` 在国内有镜像，没有必要走代理，这应该也是GFWList将其加入排除列表的原因：
![image](https://user-images.githubusercontent.com/515763/47219544-af7b5d00-d3e1-11e8-8b11-f4eac20786ce.png)

用户在 user-rule.txt 中添加的规则会自动位于规则的顶部，理论上在用户保存 user-rule.txt 的时候会自动生效，但是如果不生效，你可能需要退出SS，关闭所有浏览器，然后再启动SS，再打开浏览器试试。

**Comment by wuqiling97** [comment]
我只是拿fonts.googleapis.com举个例子。我判断是否走代理的方式，是看浏览器控制台network界面显示的remote address有没有变成127.0.0.1:1080，如果网站走代理就会是这个域名。

在我试过各种重启ss的方法之后，那些pac当中有例外规则的域名就无法走代理，没有例外规则，只要在user-rule中写上匹配规则，就能走代理。

所以可以确定是ss的问题。

**Comment by chenshaoju** [comment]
测试了一下，的确是这样的，需要等待开发人员进一步判断。

如果你很着急，可以从菜单内的gfwlist中更新本地PAC后，手动去掉即可。

@celeron533

**Comment by wuqiling97** [comment]
> > 那些pac当中有例外规则的域名就无法走代理，没有例外规则，只要在user-rule中写上匹配规则，就能走代理。
> 
> pac是从gfwlist下载的
> user-rule顾名思义，用户自己写的，默认为空
> 
> 要判定一个域名是否需要代理，
> 
> 1. 首先使用user-rule来匹配，只要有命中（不论是条目规定走代理或不走代理），就结束。
> 2. 如果ruse-rule没有命中，则继续走默认的pac内容。

但是这个判定规则在user-rule里面写着"||fonts.googleapis.com"，pac里写着"@@||fonts.googleapis.com"就会失效。按照你说的规则，该域名会走代理，但实际上没有走

**Comment by celeron533** [comment]
好，我看看

**Comment by celeron533** [comment]
测试了两种情况：
1. 在gfwlist中标明了需要代理（`||costco.com`），在`user-rule`里指定排除代理（`@@||costco.com`）。有效。刷新后costco网站提示本地区限制访问。
2. 在gfwlist中标明了排除代理（`@@||ip.cn`），在`user-rule`里指定需要代理（`||ip.cn`）。无效。ip.cn依旧显示了我现在的网络IP。

可能在生成的PAC（基于js）中，在生成blacklist和whitelist和调用这两个list的时候有点问题
```
    matchesAnyInternal: function(location, contentType, docDomain, thirdParty, sitekey)
    {
        var candidates = location.toLowerCase().match(/[a-z0-9%]{3,}/g);
        if (candidates === null)
        {
            candidates = [];
        }
        candidates.push("");
        var blacklistHit = null;
        for (var i = 0, l = candidates.length; i < l; i++)
        {
            var substr = candidates[i];
            if (substr in this.whitelist.filterByKeyword)
            {
                var result = this.whitelist._checkEntryMatch(substr, location, contentType, docDomain, thirdParty, sitekey);
                if (result)
                {
                    return result;
                }
            }
            if (substr in this.blacklist.filterByKeyword && blacklistHit === null)
            {
                blacklistHit = this.blacklist._checkEntryMatch(substr, location, contentType, docDomain, thirdParty, sitekey);
            }
        }
        return blacklistHit;
    },
```

**Comment by celeron533** [comment]
#2196 优化解决该问题
