### ISSUE TITLE
启动的时候提示端口被占用

### ISSUE THREAD

**Issue by heartacker** [shadowsocks/shadowsocks-windows#2048]
### Shadowsocks version / 影梭版本

`4.1.2`

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

`windows 10 64 1809`

### Steps you have tried / 操作步骤

启动电脑

### What did you expect to see? / 期望的结果
没有报错

### What did you see instead? / 实际结果
提示端口被占用

需要退出之后重新启动
![snipaste_2018-10-20_11-30-39](https://user-images.githubusercontent.com/1876302/47250832-91524300-d45b-11e8-8f56-2dd6d7e36d9d.png)

**Comment by chenshaoju** [comment]
点击确定后，双击右下角的纸飞机图标，在编辑服务器界面的右下角有个代理端口，请尝试换一个端口看看，比如 10800 。

如果启动SS后右下角看不到纸飞机图标，请用Windows自带的记事本打开Shadowsocks.exe所在目录下的gui-config.json文件，找到`"localPort": 1080,`，将其修改为`"localPort": 10800,`，保存退出后再启动SS看看。

**Comment by celeron533** [comment]
更换端口，然后重试
