### ISSUE TITLE
Shadowsocks UI Error - Sysproxy.SetIEProxy

### ISSUE THREAD

**Issue by DaisukiOshino** [shadowsocks/shadowsocks-windows#2050]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
NET. 4.7

### Steps you have tried / 操作步骤
退出Shadowsocks时弹出 不过在这之前obfs的插件也报错了

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

![image](https://user-images.githubusercontent.com/26147618/47255853-4bbc6700-d4a9-11e8-9a6f-d3883dbf69ee.png)

**Comment by studentmain** [comment]
关杀毒软件试试，给个管理员权限试试

**Comment by chenshaoju** [comment]
请尝试将 Shadowsocks.exe 放到一个新建的目录，比如 D:\SS\ ，然后重新配置一次看看。

请检查Shadowsocks.exe 所在目录下的 ss_win_temp 目录中的 sysproxy.exe 是否存在。

如果有安全软件，请将 Shadowsocks.exe 所在目录下的 ss_win_temp 目录中的 sysproxy.exe 加入例外列表或者白名单。

**Comment by DaisukiOshino** [comment]
> 请尝试将 Shadowsocks.exe 放到一个新建的目录，比如 D:\SS\ ，然后重新配置一次看看。
> 额 这不是必现问题
> 请检查Shadowsocks.exe 所在目录下的 ss_win_temp 目录中的 sysproxy.exe 是否存在。
> 在
> 如果有安全软件，请将 Shadowsocks.exe 所在目录下的 ss_win_temp 目录中的 sysproxy.exe 加入例外列表或者白名单。
并没有拦截或杀掉 我用的是Microsoft自带的安全中心

**Comment by chenshaoju** [comment]
Hmmmm......不确定了，这看起来是有什么东西拦截了Shadowsocks.exe调用 sysproxy.exe 。

**Comment by studentmain** [comment]
如果会操作，可以用Sysinternal那一套工具看看究竟发生了什么。
你提到了obfs插件也报错了，相应错误是什么。
不过搞不好还是要重装大法……

**Comment by DaisukiOshino** [comment]
> 如果会操作，可以用Sysinternal那一套工具看看究竟发生了什么。
> 你提到了obfs插件也报错了，相应错误是什么。
> 不过搞不好还是要重装大法……

不会啊😂
忘了截图了 不过应该会有下次报错
重装大法应该没用 因为我这笔记本之前黑果一次 黑果之前就弹过现在装回Win还会有

**Comment by celeron533** [comment]
可能和这个类似？ https://github.com/shadowsocks/shadowsocks-windows/issues/1774#issuecomment-431288569

**Comment by chenshaoju** [comment]
此问题应该在最新版本中得到了缓解，若仍有问题请再次打开此Issue。
