### ISSUE TITLE
关于vps连接，pc端延迟爆炸，移动端一切正常

### ISSUE THREAD

**Issue by kaiko-www** [shadowsocks/shadowsocks-windows#2052]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10 ，iOS 12.0.0
校园网（both校园网出口和运营商联通出口）

### Steps you have tried / 操作步骤
1. 发现在pc端使用ss基本扑街，移动端无问题。
2.  在pc端ping了vps地址，基本全连接超时，偶有延迟很高的连接成功，使用xshell连接vps也是很难成功
3. 在iOS端的ShadowRocket测试延时，基本只有3ms，使用顺畅
4. 升级ss 至最新版本，没有改善
ps：移动端和pc端都是在校园网环境下拨号上网，不存在网络环境不同的问题

### What did you expect to see? / 期望的结果
希望pc端的延迟能和移动端一样正常

### What did you see instead? / 实际结果
Failed，and don't know why.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
考虑了一下可能ss本身的配置和这个问题关系并不是很大...
暂时空缺，视情况补充

**Comment by chenshaoju** [comment]
如果你在PC上Ping你的服务器会丢包且延迟很高的话，属于你的PC所使用的网络有问题，和SS无关。

如果你坚持要在PC上使用，请将PC连接上手机上网。
