### ISSUE TITLE
关于统计配置功能的优化

### ISSUE THREAD

**Issue by StrollStars** [shadowsocks/shadowsocks-windows#2054]
版本4.1.2
目前的统计配置功能只有英文界面，而且统计图好难看（其实没看懂）。
建议能够显示中文界面，并且优化下统计图，例如显示纵轴坐标。

**Comment by chenshaoju** [comment]
状态统计已经好几年没更新了，而且有BUG……

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
