### ISSUE TITLE
win10下必须开shadowsocks全局模式才能上网，使用pac只能访问墙外内容，关掉ss强内外都无法访问

### ISSUE THREAD

**Issue by ZhenghuaXu** [shadowsocks/shadowsocks-windows#2055]
正常使用shadowsocks 4.1.0 （不确定当时是否启动），但是忽然网页无法打开，我切换到全局模式后，墙内外网站都ok，但是我切换到pac模式后，发现所有墙内网站（如百度、b站）均无法打开，但是墙外网站（如google）均可以打开。最后我关掉shadowsocks，发现墙内外所有网站都无法打开。在这个过程中 微信pc版和TIM是没有受到任何影响的。

请问这个问题应该如何解决？是不是pac文件问题？ 但是我关闭ss后同时关掉所有代理设置，还是无法打开百度等墙内网站。

**Comment by ZhenghuaXu** [comment]
问题解决了……是学校DNS服务器的问题……

**Comment by xuya227939** [comment]
@ZhenghuaXu 我遇到的是PAC无法访问，全局代理可以访问外网，请问如何修改DNS？

**Comment by chenshaoju** [comment]
请尝试右击任务栏托盘区的小图标，确保选中了“启用系统代理”，系统代理模式为“PAC模式”。

如果仍然不行，请指向PAC，选择“从GFWList更新本地PAC“，然后再试。
