### ISSUE TITLE
有没有可能将来支持黑名单模式？或者有没有可能支持Surge的规则？

### ISSUE THREAD

**Issue by raymondgit** [shadowsocks/shadowsocks-windows#2059]
现在的shadowsocks for Windows客户端通过pac文件中的规则判断是否需要走代理，如果命中则走代理，不命中则直连。但是随着被墙的网站越来越多，有没有可能支持完全相反的策略，只要没有命中规则的网站都走代理。就好比我用surge，最简单两条规则就可以实现：
```
- GEOIP,CN,DIRECT
- FINAL,,Proxy
```

**Comment by raymondgit** [comment]
我看了一下参考链接，还是没解决我说的问题。我理解现在的模式，不管是走代理还是绕过代理，都是需要在用户规则中明确需要「走或不走」的网址清单。假定我要绕过所有中国的网站，按照目前的模式，我顶多也只能配置 @@||cn ？可是怎么绕过 163.com，qq.com这些呢？ 如果是Surge规则按照我上面的示例配置，就可以根据ip地址绕过所有中国的网站。

**Comment by raymondgit** [comment]
我知道短期内没有办法，所以想了解将来有没有考虑过想这个方向迭代？

**Comment by aglent** [comment]
https://github.com/breakwa11/gfw_whitelist 里面的proxy.pac结合了黑白名单
