### ISSUE TITLE
Chrome无法通过Shadowsocks上网

### ISSUE THREAD

**Issue by Devin49** [shadowsocks/shadowsocks-windows#2068]
如题。系统是win10，不管有没有用SwitchOmega或是否全局代理都无法上网。
win10+ss+SwitchOmega+Chrome = 无法上网
win10+ss+全局代理+Chrome = 无法上网

win10+ss+IE/Edge/Firefox = 正常

试过卸载迅雷，但是还是无法上网。
求助。

**Comment by celeron533** [comment]
查看本地shadowsocks的log，确认到底是哪里的问题：
1. 没有收到浏览器的请求
2. 浏览器有请求，但本地转发出了问题
3. 远程ss服务器出现问题
4. 其他

**Comment by chenshaoju** [comment]
请检查你的Chrome设置（chrome://settings/），代理是否被第三方插件接管了。

![image](https://user-images.githubusercontent.com/515763/48310833-9a54b100-e5d0-11e8-948b-1e5728ea94a1.png)

**Comment by yangshuochina** [comment]
这个与操作系统和浏览器没关系吧，我是1809，可以正常使用。你先确定你的Shadowsocks是否可以正常用。
