### ISSUE TITLE
界面改改吧,真有点不像样

### ISSUE THREAD

**Issue by ugksoft** [shadowsocks/shadowsocks-windows#2073]
界面有点乱吧, 而且端口还写死的

这哪像是一个正常的exe啊, 很多操作习惯之类,完全是mac这种没有经历过正式商用的傻子风格

或许说话不太客气,但是确实太太.....

抱歉

**Comment by studentmain** [comment]
个人看法
1，界面只是装饰，要不是现在不是人人都会玩终端，半个窗口都懒得拖。
2，哪里的端口，说句"端口是写死的"没用。
3，ss-windows是一个非盈利项目，换句话说不仅是一个没有经历过商用的项目，还是一个不会考虑商用的项目。
 4，这exe挺正常的啊，界面使用的windows原生组件，杀毒软件也不报毒，也不会给你偷偷下载软件什么的，简直再正常不过了。
5，看看别人咋提issue的。

**Comment by chenshaoju** [comment]
如果你是要修改本地代理端口，可以在编辑服务器界面右下角修改。
此端口同时提供SOCKS5和HTTP代理。
