### ISSUE TITLE
Shadowsocks Non-UI Error - Sysproxy

### ISSUE THREAD

**Issue by biubiubiu322** [shadowsocks/shadowsocks-windows#2074]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
2017 win10企业版

### Steps you have tried / 操作步骤
开启SS显示非预期错误

### What did you expect to see? / 期望的结果
之前都能正常使用，突然就不能使用了

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![image](https://user-images.githubusercontent.com/44396114/48670912-3fd0cd00-eb5b-11e8-8812-dfe563069352.png)

**Comment by studentmain** [comment]
推荐阅读：#2013

https://ci.appveyor.com/api/buildjobs/m9xrgusccaey0fnc/artifacts/shadowsocks-csharp%2Fbin%2Fx86%2FDebug%2FShadowsocks.exe
试试这个，试完把日志发过来。

**Comment by biubiubiu322** [comment]
谢谢 问题解决

**Comment by biubiubiu322** [comment]
> 推荐阅读：#2013
> 
> https://ci.appveyor.com/api/buildjobs/m9xrgusccaey0fnc/artifacts/shadowsocks-csharp%2Fbin%2Fx86%2FDebug%2FShadowsocks.exe
> 试试这个，试完把日志发过来。

用你的APP问题解决，谢谢

**Comment by studentmain** [comment]
日志呢

**Comment by celeron533** [comment]
Close due to no more feedback
