### ISSUE TITLE
Whatsapp windows 客户端pac模式下无法登录，全局模式下可以登录。

### ISSUE THREAD

**Issue by chohyu** [shadowsocks/shadowsocks-windows#2075]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭
Whatsapp windows 客户端pac模式下无法登录，全局模式下可以登录。
### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows7 64bit, NET Framework4.7.2

### Steps you have tried / 操作步骤
user-rule.txt 内已反复调试填入以下规则：
||web.whatsapp.com
||whatsapp.com
||whatsapp.net

### What did you expect to see? / 期望的结果
能在pac模式下使用客户端版本的whatsapp。

### What did you see instead? / 实际结果
无法登录客户端。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
搜了一下，搜到一片文章：
https://kb.smoothwall.net/Content/applications/allowWhatsApp.htm

好象是IP，而不是域名（我没有使用WhatApp，仅供参考）。

**Comment by zjwangmin** [comment]
确实 我跟你一样 网页版也可以  就是客户端版本不行

**Comment by AustinZhou** [comment]
同样的问题

**Comment by vince224** [comment]
暂时就用网页版

**Comment by AustinZhou** [comment]
这个问题还没有大佬发现吗？
