### ISSUE TITLE
Any plans to migrate to linux environments?

### ISSUE THREAD

**Issue by Shawn-ye** [shadowsocks/shadowsocks-windows#2076]
这个client的高可用模式非常好用， 目前在linux平台下，据我所知，没有类似的client。请问各位开发者有计划迁移到linux平台下吗？如果有这样的计划，我愿意协助重写一部分代码。
我的构想是：
* docker部署，用.net core框架，重写原有代码
* 移除GUI，用配置文件配置

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-libev/

启动也只是一个脚本的事情：
```
ss-local -s SERVER -p PORT -l 1080 -k PASSWORD -m EncryptionAlgorithm
```

代理的配置可以用浏览器的插件实现，比如SwitchOmega。

**Comment by chenshaoju** [comment]
没，只是一个client。

**Comment by Shawn-ye** [comment]
ok, 我先评估评估工作量。

**Comment by studentmain** [comment]
工作量有点恼火，与其说这是shadowsocks-csharp，不如说这是shadowsocks-windows。
加密算法是native dll实现的，系统代理是运行时释放一个单独的exe修改，http代理是内置一个privoxy变出来的，这些全都是win32特有的东西……移除了GUI就真的和C#没多少关系了……

**Comment by Shawn-ye** [comment]
@studentmain 看来还不如自己重写一个？
