### ISSUE TITLE
最新版本中有个便携模式，请问有什么用.

### ISSUE THREAD

**Issue by samoyedsun** [shadowsocks/shadowsocks-windows#2077]
便携模式是干啥用的，我发现开启或者不开启都不影响正常使用.....

**Comment by studentmain** [comment]
字面意思，勾上的话会把临时文件之类的写在程序所在目录，方便你把程序装u盘里面带着跑。

samoyedsun <notifications@github.com> 于 2018年11月19日周一 上午12:53写道：
