### ISSUE TITLE
从gfwlist更新pac文件后，之前的编辑全部丢失。

### ISSUE THREAD

**Issue by ohsorry** [shadowsocks/shadowsocks-windows#2078]
### Environment(Operating system, .NET Framework, etc) / Win7 x64, .net 4.6+

希望修改本地pac编辑的保存逻辑。从gfwlist更新pac.txt，只添加pac条目，不替换pac.txt。

**Comment by chenshaoju** [comment]
请把你的自定义规则放入 user-rule.txt 中，详见： https://github.com/shadowsocks/shadowsocks-windows/issues/1879

**Comment by ohsorry** [comment]
原来是这么用的。之前一直用的“编辑本地pac文件”菜单。
辛苦啦，谢谢。
