### ISSUE TITLE
win10 1809 ipv6不支持

### ISSUE THREAD

**Issue by xiadingZ** [shadowsocks/shadowsocks-windows#2079]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 1809 17763.134

### Steps you have tried / 操作步骤
先测试服务器的ipv4地址，连接成功
换成服务器的ipv6地址，连接失败
在cmd中ping -6 服务器的ipv6地址，连接成功
在macos客户端使用shadowsocksx-ng，用ipv6地址连接服务器，连接成功

### What did you expect to see? / 期望的结果

将shadowsocks-windows中的ip地址填写服务器的ipv6地址也能成功

### What did you see instead? / 实际结果
将ipv4地址换成ipv6地址就不能连接了，然而在cmd中可以ping通ipv6地址

**Comment by chenshaoju** [comment]
请确保你使用 [ ] 括号将你的IPv6地址括起来了。

https://twitter.com/chenshaoju/status/1043793175280844801

**Comment by xiadingZ** [comment]
在shadowsocks-windows客户端的ip地址栏不加[]，保存后在左侧栏的显示中会自动加上[]。 我刚刚试了填ip时加上[], 左侧栏显示了两重，[[]]。 依然连接不上

**Comment by chenshaoju** [comment]
我又尝试测试了一遍，还是没有问题。

![image](https://user-images.githubusercontent.com/515763/48682144-b4e6e580-ebe1-11e8-85fe-167b180c4e40.png)


请尝试以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机看看？

**Comment by xiadingZ** [comment]
依然不行，日志中显示timeout
<img width="428" alt="screenshot 2018-11-19 at 10 06 18 am" src="https://user-images.githubusercontent.com/16729275/48682357-f1ffa780-ebe2-11e8-98af-c3c59580d701.png">

**Comment by chenshaoju** [comment]
请确保你的其他配置（端口、加密算法、密码）和IPv4一致。

另外，我想再确认一下，请使用tcping测试一下到你的IPv6地址的端口是否能通：
https://www.elifulkerson.com/projects/tcping.php

**Comment by xiadingZ** [comment]
用tcping 测ipv4和ipv6都行不通。但是我用ping和ping -6能连通

<img width="950" alt="screenshot 2018-11-19 at 10 14 00 am" src="https://user-images.githubusercontent.com/16729275/48682672-61c26200-ebe4-11e8-95b.png">

**Comment by xiadingZ** [comment]
用tcping测试ipv6和ipv4都连通不了。但是我用ping和ping -6都能连通。
当填ipv4地址时，在网页上测出了ipv6的地址，不知道这算不算是走的ipv6流量还是ipv4流量？
<img width="950" alt="screenshot 2018-11-19 at 10 14 00 am" src="https://user-images.githubusercontent.com/16729275/48682710-9f26ef80-ebe4-11e8-97f7-bc04cecbc8cb.png">

**Comment by chenshaoju** [comment]
理论上如果能Ping通公网上的IPv6地址的话，那么本机是具备IPv6接入和访问能力的。

**Comment by xiadingZ** [comment]
用tcping测试服务器的代理端口，ipv6不通，ipv4是通的。 
在macos用shadowsocksx-ng连接ipv6地址是可行的，服务器的ipv6功能正常

**Comment by chenshaoju** [comment]
MacOS和Windows在同一个网络吗？

如果是，可能你的操作系统的IPv6有问题，请尝试检查一下IPv6的设置：
https://support.microsoft.com/en-us/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users

可选择 `Prefer IPv4 over IPv6 in prefix policies` 这个。

**Comment by chenshaoju** [comment]
能否确认一下你的虚拟机的网络是桥接模式还是NAT模式？

也许要桥接到一个物理网卡上。

![image](https://user-images.githubusercontent.com/515763/48688423-313cf100-ec01-11e8-995d-765df2669d94.png)

或者，你的虚拟机的虚拟化实现有问题。

**Comment by xiadingZ** [comment]
我都是根据默认设置来的，在win10上ping ipv6地址没问题，应该是支持ipv6的。
<img width="688" alt="screenshot 2018-11-19 at 2 11 54 pm" src="https://user-images.githubusercontent.com/16729275/48689377-3603a400-ec05-11e8-898f-a1064330398f.png">

**Comment by wongsyrone** [comment]
我记得好像当时没写ipv6支持的东西

**Comment by wongsyrone** [comment]
有兴趣可以看一下以前的玩具实现，利用dual stack单一socket支持v4和v6

https://github.com/fuckshadows/fuckshadows-windows/commit/38259e9595d469cc8c20e9d68f7644b6a4ef793f

UDP需要把IPv4Mapped再map回去

**Comment by xiadingZ** [comment]
😂那还有啥win10支持ipv6 socks5的方法么？校园网走ipv4费流量

**Comment by wongsyrone** [comment]
估计得改代码，现在我用TLS 1.3翻墙了，很久都没碰ss代码了

**Comment by xiadingZ** [comment]
可以
<img width="860" alt="screenshot 2018-11-19 at 3 11 43 pm" src="https://user-images.githubusercontent.com/16729275/48691454-926ac180-ec0d-11e8-9432-ef40bb942925.png">

**Comment by chenshaoju** [comment]
请尝试使用 tcping 测试一下：
```
tcping [240c::6666] 53
```

看能否通：
![image](https://user-images.githubusercontent.com/515763/48691534-d52c9980-ec0d-11e8-8eb8-072fbb8d1ca1.png)

如果能通，说明你的IPv6实现没有问题，如果不通，则说明IPv6实现有问题。

**Comment by xiadingZ** [comment]
<img width="561" alt="screenshot 2018-11-19 at 3 17 37 pm" src="https://user-images.githubusercontent.com/16729275/48691654-4704e300-ec0e-11e8-8e18-5219ed19296a.png">
