### ISSUE TITLE
运营商封禁IP 如何解决

### ISSUE THREAD

**Issue by welcomehub** [shadowsocks/shadowsocks-windows#2081]
手机能上，宽带不能上

**Comment by chenshaoju** [comment]
请尝试更换你的服务器IP，或者联系你的运营商要求解封。

**Comment by chenshaoju** [comment]
如果你钱又多的话，可以租一个阿○云或者腾○云作为转发，经由国内的云服务进行中转。

**Comment by pexcn** [comment]
换运营商也行

**Comment by welcomehub** [comment]
@chenshaoju @pexcn 现在又正常了 很奇怪的问题 难道是运营商短暂的封禁？

**Comment by welcomehub** [comment]
@chenshaoju @pexcn 谢谢两位老铁
 运营商这样短暂封锁 
然后又解封
 是什么套路？

**Comment by hellodengfei** [comment]
@welcomehub 我这边也遇到这种情况过, 请问如何解决?

**Comment by CGJ-020** [comment]
弄个域名呗

**Comment by welcomehub** [comment]
> @welcomehub我这边也遇到这种情况过，请问如何解决？

我的目前好了 ，电脑宽带是移动，偶尔不稳定， 手机是联通，没有问题。

**Comment by welcomehub** [comment]
> 弄个域名呗

这个不太懂，我目的很单纯 ，只看看油管视频
