### ISSUE TITLE
所以最近突然变慢是因为被电信QOS了吗？

### ISSUE THREAD

**Issue by evan8686** [shadowsocks/shadowsocks-windows#2083]
### Shadowsocks version / 影梭版本
4.1.2版本
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10 64bit

家用PC网络为 中国电信  50M带宽。  手机4G LTE是 中国联通

speedtest.net 测速  本地带宽（不使用任何代理）速度没问题，可以跑满50M宽带应有速度。
基本上晚上高峰时期，挂SS，就只有1兆（100kb/s）的速度。 到了凌晨1点之后，又可以跑差不多10M带宽的高速。但其实用了3个月都正常，最近半个月才开始变慢。

如果是手机LTE的话，用speedtest.net 的app挂SS测速，在高峰期还是比较理想的速度，并没有被限速的样子，可以跑大概下行 900kb/s，上行速度也不错。

这样子的话，我本地带宽是没问题，如果用联通4G可以跑到高速，那么，我的VPS服务也没问题。因此，这样推测是中国电信qos限速？

这有办法绕过限速吗？

**Comment by celeron533** [comment]
电信的国际出口已经堵爆。联通和移动没有这么严重。
