### ISSUE TITLE
PC端 500错误

### ISSUE THREAD

**Issue by k9990009** [shadowsocks/shadowsocks-windows#2084]
Shadowsocks version / 影梭版本
4.1.2版本

Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 64位

 Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

[2018-11-26 11:06:56] Shadowsocks started (4.1.2)
[2018-11-26 11:06:56] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor

我自己搭建的SS服务，手机端OK，PC端访问google一直是500，我已经开启了系统代理，启用PAC模式，更新了GWFList，日志如上，也没报错

**Comment by chenshaoju** [comment]
日志中什么都没有……只能盲测一下了。

请以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机看看。如果安全软件跳出，请允许所有操作。

**Comment by k9990009** [comment]
我试试

**Comment by RichardSunMS** [comment]
遇到同样的问题，试了这些reset. 还是不行。

**Comment by chenshaoju** [comment]
@RichardSunMS 你的日志中是否有任何显示？

**Comment by k9990009** [comment]
我的好了，昨天按上面重置后，重启无效。今天我开电脑又尝试了下，又可以了，莫名其妙
