### ISSUE TITLE
每次启用系统代理，或切换服务器时，旧的HTTP Auto Proxy Detection Worker Process进程不能正常关闭，这样就会导致有多个HTTP Auto Proxy Detection Worker Process进程在运行，希望能解决这个问题

### ISSUE THREAD

**Issue by ming1221** [shadowsocks/shadowsocks-windows#2092]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by ming1221** [comment]
我使用的Windows10 1809，不知道是系统问题还是影梭的问题

**Comment by studentmain** [comment]
系统问题，上全局模式。

ming1221 <notifications@github.com> 于 2018年12月2日周日 上午11:43写道：

**Comment by chenshaoju** [comment]
此问题已知，请移步：https://github.com/shadowsocks/shadowsocks-windows/issues/1979
