### ISSUE TITLE
shadowsocks-windows支持tcp fastopen了是吗？配合obfs插件，该如何配置？

### ISSUE THREAD

**Issue by dragon100a** [shadowsocks/shadowsocks-windows#2093]
### Shadowsocks version / 影梭版本
4.12

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 1803

### Steps you have tried / 操作步骤
服务器端：Debian v9
1.因为内核较新，因此很顺利的开启了bbr。
2./etc/sysctl.conf的末尾添加net.ipv4.tcp_fastopen = 3，开启tfo
3.安装shadowsocks-libev
4.安装obfs server
git clone https://github.com/shadowsocks/simple-obfs.git
cd simple-obfs
git submodule update --init --recursive
./autogen.sh
./configure && make
make install
ln -s /usr/local/bin/obfs-server /usr/bin
在/etc/shadowsocks-libev/config.json中添加：
"fast_open": true,
"plugin":"obfs-server",
"plugin_opts":"obfs=http"

客户端：
shadowsocks文件夹中，添加obfs-local.exe和msys-2.0.dll（https://github.com/shadowsocks/simple-obfs/releases）
编辑服务器页面是这样写的：
![22222222](https://user-images.githubusercontent.com/5362072/49338889-93ffa500-f663-11e8-8cd4-df628fa0f604.png)
本地配置文件内容如下：
   {
      "server": "*.*.*.*",
      "server_port": *,
      "password": "*****",
      "method": "***",
      "plugin": "obfs-local",
      "plugin_opts": "obfs=http",
      "plugin_args": "obfs-host=www.bing.com",
      "remarks": "",
      "timeout": 5
    },

那么 tcp fastopen 该怎么加入呢？

**Comment by chenshaoju** [comment]
界面上插件只能用一个，不过你可以自行使用参数再启动一个，然后在界面上指向 127.0.0.1 和你的本地插件端口。

**Comment by chenshaoju** [comment]
抱歉，看错了，是TCP Fast Open，不是KCPTUN。
这个事情有讨论，但是好像由于操作系统的支持问题搁置了，目前仍然不支持TCP Fast Open： https://github.com/shadowsocks/shadowsocks-windows/pull/1328

**Comment by dragon100a** [comment]
@chenshaoju 
https://github.com/shadowsocks/shadowsocks-windows/pull/1328#ref-pullrequest-303794072
上面这个链接提到，不是已经支持了吗？难道 后来又取消了？？？

**Comment by chenshaoju** [comment]
对，这是libev版支持了，不是Windows版。

**Comment by studentmain** [comment]
话说你simple-obfs看的哪篇

**Comment by dragon100a** [comment]
@chenshaoju 
那看起来客户端这边就没什么事情了。
补充一个其他问题：
在 **服务器端** tcp fastopen与obfs一起用时，
我看到有地方这样写的：
"fast_open": true,
    "plugin": "obfs-server",
    "plugin_opts": "obfs=http;fast-open=true"
在**插件参数**后面多了一个“fast-open=true”，而且下划线变成了减号。
这样写科学吗？开启fastopen，需要写2次吗？

**Comment by dragon100a** [comment]
@chenshaoju 
先表示感谢。给出了参数列表。根据上述内容，总结一下。
服务器端的配置文件除了原有内容，应该附加：
"plugin":"obfs-server",
"plugin_opts":"obfs=http;fast-open=true"
客户端的配置文件除了原有内容，应该附加：
"plugin": "obfs-local",
"plugin_opts": "obfs=http",
"plugin_args": "obfs-host=www.bing.com;fast-open=true",

这样应该就是完美了吧~
