### ISSUE TITLE
怎么设置在全局模式下部分网站不走代理的呢？

### ISSUE THREAD

**Issue by MightyWing** [shadowsocks/shadowsocks-windows#2096]
如题，因为部分国外网站是登陆验证和网站本身是不同域名的。有些离谱的更使用到多层验证，pac模式下很难满足登陆的需求。有什么方法设置在全局模式下部分网站不走代理的呢（即全局模式下的黑名单）？

**Comment by chenshaoju** [comment]
你可以试试：https://github.com/breakwa11/gfw_whitelist

**Comment by AnyWAT** [comment]
较新的 https://github.com/MatcherAny/whitelist.pac

**Comment by studentmain** [comment]
现在的（尚未release的）代码有相应功能，不过是通过手动改系统代理例外实现的。

**Comment by MightyWing** [comment]
@AnyWAT 我知道pac，但有些网站比较麻烦。..因为有些软件破解要设置hosts，切换全局模式 软件就废了

**Comment by MightyWing** [comment]
选择全局模式 后，貌似怎么动pac文件都没有用。所有流量都走代理了

**Comment by MightyWing** [comment]
查找了代码。发现可以通过修改`function FindProxyForURL(url, host) {
    if (defaultMatcher.matchesAny(url, host) instanceof BlockingFilter) {
        return direct;
    }
    return proxy;
}`实现，但是这样还存在风险。不小心按到全局模式，还会出现软件破解失败的情况

**Comment by MightyWing** [comment]
@studentmain 通过手动改系统代理例外实现的 怎么做呢？我可以自己用vs发布一份新的

**Comment by MightyWing** [comment]
@studentmain 通过手动改系统代理例外实现的 怎么做呢？我可以自己用vs发布一份新的

**Comment by AnyWAT** [comment]
> 因为有些软件破解要设置hosts，切换全局模式 软件就废了

😂本贴主题：怎么设置在全局模式下部分网站不走代理的呢？

> 较新的 https://github.com/MatcherAny/whitelist.pac

只是追2楼 @chenshaoju 。。。

> 有什么方法设置在全局模式下部分网站不走代理的呢（即全局模式下的黑名单）？

貌似（以往的）黑名单是需代理的（名单），所以 @chenshaoju 给出了不需代理的白名单，可结合系统 hosts 使用。至于楼主坚持非全局模式下。。。不识码的我不会玩了😝

**Comment by studentmain** [comment]
#2003 @MightyWing

**Comment by MightyWing** [comment]
谢谢。。按这样设置。搞定了。

**Comment by studentmain** [comment]
@MightyWing 刚刚发布了4.1.3测试版，相应代码已经release了

**Comment by MightyWing** [comment]
@studentmain 我利用master分支发布了最新版本，发现界面没什么不同。。具体要怎么操作呢。

**Comment by MightyWing** [comment]
好的。

**Comment by advpetc** [comment]
可以看一下gfwlist: https://github.com/gfwlist/gfwlist/wiki
