### ISSUE TITLE
iTunes网页无法打开

### ISSUE THREAD

**Issue by cooper1x** [shadowsocks/shadowsocks-windows#2097]
### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 1803 x64

### Steps you have tried / 操作步骤
iTunes连接在pac模式下无法打开，例如
[https://itunes.apple.com/us/app/小爱同学/id1436959122?mt=8](https://itunes.apple.com/us/app/小爱同学/id1436959122?mt=8)
更新过PAC还是不行，必须开全局才可以。

### What did you expect to see? / 期望的结果
期望能够通过同步在线PAC来解决这个问题

### What did you see instead? / 实际结果
无法打开iTunes页面。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
日志里面没有这条访问记录。

**Comment by chenshaoju** [comment]
请尝试添加到 user-rule.txt  ，详见：https://github.com/shadowsocks/shadowsocks-windows/issues/1879

**Comment by cooper1x** [comment]
@chenshaoju 好的，请问GFWlist的源在哪呢？如果能加入进去就更好了

**Comment by chenshaoju** [comment]
iTunes在国内没有被墙把……？

GFWList： https://github.com/gfwlist/gfwlist

**Comment by cooper1x** [comment]
@chenshaoju 可能我用的谷歌搜索打开的是美版的
