### ISSUE TITLE
是否可以实时更新本地PAC策略，或者右键菜单加入选项

### ISSUE THREAD

**Issue by TypicalSEE** [shadowsocks/shadowsocks-windows#2098]
使用本地PAC策略，修改PAC文件后，貌似需要关闭代理再重新启用才能生效。有没有可能使其即时生效，或者在托盘图标的右键菜单加一条“刷新本地PAC”的功能，谢谢！

**Comment by TypicalSEE** [comment]
Oh,看了WIKI，发现好像是会实时监控的，但是在我这里好像没有起作用~

**Comment by chenshaoju** [comment]
编辑的时候只要保存一次，即可立刻生效。

**Comment by iAM261917** [comment]
> 编辑的时候只要保存一次，即可立刻生效。

在我的实际使用过程中，修改PAC/user-rule之后，查看日志虽然有监控到PAC被改变的记录，但是还是需要重新选一次PAC模式才能生效。

**Comment by celeron533** [comment]
浏览器自身缓存了之前的pac文件内容，所以虽然后续提供的pac内容已刷新，但是浏览器会视而不见，除非pac的文件名发生变化（参数）

**Comment by mu-yu** [comment]
> 浏览器自身缓存了之前的pac文件内容，所以虽然后续提供的pac内容已刷新，但是浏览器会视而不见，除非pac的文件名发生变化（参数）

是否有自动刷新 pac 缓存的方法呢？@celeron533

**Comment by mu-yu** [comment]
实测chrome不会自动更新…

**Comment by AnyWAT** [comment]
> 实测chrome无法自动应用新的pac

参照 https://github.com/MatcherAny/whitelist.pac 并利用 https://raw.githubusercontent.com/KyonLi/ss-pac/master/ss.pac 可自建黑名单下的 auto switch 情景模式，随时添加切换规则。貌似白名单下几乎不见“未加载资源”😂

**Comment by mu-yu** [comment]
> > 实测chrome无法自动应用新的pac
> 
> 参照白名单 https://github.com/MatcherAny/whitelist.pac 的auto white 情景模式，并利用 https://raw.githubusercontent.com/KyonLi/ss-pac/master/ss.pac 可自建黑名单下的 auto switch 情景模式，随时添加并自动应用切换规则。
> 不过，貌似白名单下几乎不见“未加载资源”😂

因为公司IT装了EndPoint，导致插件的auto switch模式不可用才想起来改user-rule.txt的，死循环了…😂

**Comment by mu-yu** [comment]
目前临时解决方案：
改完userrule.txt 后用 listary 快速重启shadowsocks
`cmd /c taskkill /f /IM "Shadowsocks.exe" && start D:\greenProgram\shadowsocks\Shadowsocks.exe`

**Comment by rainmor** [comment]
操作系统： Win10
浏览器: Chrome
问题跟楼主遇到的一样。我每次修改为user-rule，都必须重启系统代理

**Comment by chenshaoju** [comment]
我做了一个测试，在编辑`user-rule.txt`后保存退出，浏览器的PAC地址并没有发生任何变化，停用并重新启动系统代理后PAC地址才会变化。

也许是因为地址没有变化，所以系统就一直从缓存里取PAC，而不会再重新获取。

可能是这个问题引起的？

**Comment by studentmain** [comment]
诶，搞不好是诶，我明天试试。

Chen Shaoju <notifications@github.com> 于 2018年12月11日周二 下午9:06写道：

**Comment by chenshaoju** [comment]
搜了一下，微软有一个注册表键值和组策略设置，可以关闭浏览器的PAC缓存，有兴趣的可以试一下：
https://support.microsoft.com/zh-cn/help/271361/how-to-disable-automatic-proxy-caching-in-internet-explorer

**Comment by cywy** [comment]
我个人的解决方法是给“切换系统代理模式”添加快捷键，每次修改pac后按两次快捷键即可立即生效。
