### ISSUE TITLE
413版本有一些问题，建议各位暂时不要更新

### ISSUE THREAD

**Issue by xin344** [shadowsocks/shadowsocks-windows#2102]
打开会引起一些异常无法使用，具体原因我也没仔细查，请各位暂时不要升级。

**Comment by xin344** [comment]
There're some problems in recently updated version 4.1.3, I didn't found the reason, but I suggest you upgrade to the new version in days later.

**Comment by chenshaoju** [comment]
请具体描述问题。

**Comment by celeron533** [comment]
should be fixed in 4.1.3.1

**Comment by xin344** [comment]
> should be fixed in 4.1.3.1

thx a lot.
