### ISSUE TITLE
Shadowsocks 4.1.3 prerelease 日志中的sysproxy hanging修复没有作用

### ISSUE THREAD

**Issue by Feketerigo0827** [shadowsocks/shadowsocks-windows#2103]
### Shadowsocks version / 影梭版本
4.1.3 prerelease

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 17763.168 .NET Framework 4.7.2

### Steps you have tried / 操作步骤
切换pac/全局模式；系统睡眠/唤醒

### What did you expect to see? / 期望的结果
HTTP auto proxy detection进程正常

### What did you see instead? / 实际结果
HTTP auto proxy detection进程出现积累，只能重启清理（关机，开机无效）

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by celeron533** [comment]
please try 4.1.3.1
