### ISSUE TITLE
Win10 LTSC 2019 非预期错误

### ISSUE THREAD

**Issue by saygoodbyebye** [shadowsocks/shadowsocks-windows#2105]
4.1.3 出现错误，4.1.2暂时无问题
![1](https://user-images.githubusercontent.com/19968269/49689211-1d7a1000-fb59-11e8-81c8-316282e9af2f.png)

**Comment by chenshaoju** [comment]
请尝试此版本是否解决了该问题：https://github.com/shadowsocks/shadowsocks-windows/issues/2100#issuecomment-445434934 （Debug.zip）。

**Comment by celeron533** [comment]
should be fixed in 4.1.3.1
