### ISSUE TITLE
今天似乎开始大规模封杀了

### ISSUE THREAD

**Issue by Nz666-Kshatriya** [shadowsocks/shadowsocks-windows#2106]
doub.io不见了

**Comment by studentmain** [comment]
![screenshot_2018-12-09-10-12-51-223_com android chrome](https://user-images.githubusercontent.com/17123090/49692667-2d1a4880-fb9b-11e8-9c78-a52583cd8262.png)

顺便一提，本项目不解决机场被一锅端的情况。

**Comment by xionCode** [comment]
能ping通远程主机，但SSH连不上，SS也用不了，这是被封了吗？：）

**Comment by Wenbin-Xu** [comment]
是啊 能ping上 但是连不上。。

**Comment by shuangz** [comment]
大家都是这个样子吗？

**Comment by chenshaoju** [comment]
如果你从某个第三方的SS／SSR服务商购买了SS／SSR服务，请与该服务商联系。

此处不提供也不销售SS／SSR服务。

**Comment by tzyqq191** [comment]
https://ipcheck.need.sh/检查显示全部梯子服务器国内TCP阻断

**Comment by yuzunyue** [comment]
我的两台梯子也是，能ping通但是连不上

**Comment by jasonliul** [comment]
加个前置 例如 183.129.242.126:1080 袜5
无法保证你处也满速

**Comment by jasonliul** [comment]
自建的要采用AEAD新型加密, 3个gcm, chacha20-ietf-poly1305

**Comment by lehr** [comment]
Digitalocean 换浮动IP就能重新连上了。

**Comment by waysup** [comment]
这两年的规律：开大会前后会有一波阻断 所以推测应该是要开4中圈会:grinning:

**Comment by yuzunyue** [comment]
> 这两年的规律：开大会前后会有一波阻断 所以推测应该是要开4中圈会

我还以为是因为加拿大的事，准备动手之前的限制舆论呢23333

**Comment by IriKaQ** [comment]
我的昨天也被墙了，无缘无故啊，用的人又不多，就几个人，流量也不大。

**Comment by KDWangBoss** [comment]
今天一波骚动，我还以为服务器被封了，晚上7点多的时候又好了
