### ISSUE TITLE
打开shadowsocks后，添加ss节点，并点击了启动服务，便出现了错误，之后一打开便是报错

### ISSUE THREAD

**Issue by a1351936853** [shadowsocks/shadowsocks-windows#2107]
### 解决我的问题

###[2018-12-09 10:36:47] [E] Exception Detail: 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv, Boolean noRetry)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Controller.ShadowsocksController.ToggleEnable(Boolean enabled)
   在 Shadowsocks.View.MenuViewController.EnableItem_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.Command.DispatchID(Int32 id)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[2018-12-09 11:02:50] Shadowsocks started (4.1.3)
[2018-12-09 11:02:50] 
[shadowsocks.log](https://github.com/shadowsocks/shadowsocks-windows/files/2660219/shadowsocks.log)

**Comment by zhouxiaoxu** [comment]
升级4.1.3后提示该错误

**Comment by chenshaoju** [comment]
请尝试该版本是否解决了问题：
https://github.com/shadowsocks/shadowsocks-windows/issues/2100#issuecomment-445434934 （Debug.zip）

**Comment by a1351936853** [comment]
> 请尝试该版本是否解决了问题：
> [#2100 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2100#issuecomment-445434934) （Debug.zip）
用这个版本就完美解决了问题，是什么原因导致的呢？

**Comment by chenshaoju** [comment]
浏览器的代理设置问题。
