### ISSUE TITLE
由于远程方已关闭传输流，身份验证失败

### ISSUE THREAD

**Issue by JovianHuang** [shadowsocks/shadowsocks-windows#2109]
### Shadowsocks version / 影梭版本 4.1.2
今天早上七点多的时候还可以连接成功，到了十点多的时候突然出现这样的情况。检查了一下搬瓦工的服务器是正常的。
看了一下Log，发现了这个异常： 由于远程方已关闭传输流，身份验证失败。

具体日志：
[2018-12-09 11:37:15] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
这意味着从你的计算机到你的服务器的链接被切断了，请尝试重新启动你的光猫和路由器，然后再试。

如果你的SS服务是购买的，请与你的SS服务商联系或访问SS服务商的网站更新或更换服务器信息。

如果你是自己搭的，请Ping你的服务器，如果能通，请尝试更换一个SS端口看看。

如果Ping也不通，但是从海外能Ping通的话（ https://ping.eu/ping/ ），说明你的服务器可能被墙了，请更换一个IP或新开一个服务器。

**Comment by yuzunyue** [comment]
我的也是，两台服务器都被都不行了，都是搬瓦工的
