### ISSUE TITLE
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效

### ISSUE THREAD

**Issue by Pyw2003** [shadowsocks/shadowsocks-windows#2110]
### Shadowsocks version / 影梭版本
4.1.3 & 4.1.2版本都尝试过

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### What did you see instead? / 实际结果
今天早晨出现的情况：
关闭ss时baidu.com，github.com能打开，google.com无法打开
PAC模式下baidu.com能打开，但github.com和google.com都无法打开
全局模式下所有网页都无法打开
其它设备（手机、平板）也出现相似情况，无法使用
浏览器显示：
```
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

```
无法从GFWList更新本地PAC，显示：
`操作过程中出现异常，结果无效。有关异常的详细信息，有关异常的详细信息请查看InnerException`

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
4.1.3 & 4.1.2版本日志显示的都是以下内容，日志里流量图入站出站均为零：
```
[2018-12-09 11:28:21] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-12-09 11:28:27] 104.225.***.31:312 timed out
```

**Comment by chenshaoju** [comment]
这意味着从你的计算机到你的服务器的链接被切断了，请尝试重新启动你的光猫和路由器，然后再试。

如果你的SS服务是购买的，请与你的SS服务商联系或访问SS服务商的网站更新或更换服务器信息。

如果你是自己搭的，请Ping你的服务器，如果能通，请尝试更换一个SS端口看看。

如果Ping也不通，但是从海外能Ping通的话（ https://ping.eu/ping/ ），说明你的服务器可能被墙了，请更换一个IP或新开一个服务器。

**Comment by Pyw2003** [comment]
> 这意味着从你的计算机到你的服务器的链接被切断了，请尝试重新启动你的光猫和路由器，然后再试。
> 
> 如果你的SS服务是购买的，请与你的SS服务商联系或访问SS服务商的网站更新或更换服务器信息。
> 
> 如果你是自己搭的，请Ping你的服务器，如果能通，请尝试更换一个SS端口看看。
> 
> 如果Ping也不通，但是从海外能Ping通的话（ https://ping.eu/ping/ ），说明你的服务器可能被墙了，请更换一个IP或新开一个服务器。

能够Ping通我的服务器，已更改端口，依然无效

**Comment by chenshaoju** [comment]
如果可能，请做一个测试，套一个kcptun（udp）看看？

**Comment by Pyw2003** [comment]
> 如果可能，请做一个测试，套一个kcptun（udp）看看？

具体怎么操作？

**Comment by neveroldmilk** [comment]
手里的搬瓦工全灭了，默哀。

**Comment by yuzunyue** [comment]
> > 我没有使用板瓦工的服务，但是你可以试试更换IP：
> > https://twitter.com/FatherSucker/status/1071629353644044288
> 
> 经检查是IP被封，申请更换后恢复。怎么操作套kcptun（udp）？有指南吗？

百度一下，你就知道

**Comment by yuzunyue** [comment]
> 手里的搬瓦工全灭了，默哀。

一台先换一下IP吧，我先换了一台的IP观望一下，害怕再被封
