### ISSUE TITLE
使用在线PAC gfwlist无法访问网络啊

### ISSUE THREAD

**Issue by Songmanual** [shadowsocks/shadowsocks-windows#2113]
https://github.com/gfwlist/gfwlist 我从这里获取的在线地址 放入在线PAC网址里面 无效

**Comment by AnyWAT** [comment]
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by studentmain** [comment]
其实内置的就是这个……

**Comment by HankAviator** [comment]
貌似是最近的版本出现了这个问题，没有什么错误提示。

**Comment by AnyWAT** [comment]
> https://github.com/gfwlist/gfwlist 我从这里获取的在线地址 放入在线PAC网址里面 无效

貌似只有 https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt 等非PAC？
黑名单在线：https://raw.githubusercontent.com/KyonLi/ss-pac/master/ss.pac
白名单在线：https://raw.githubusercontent.com/MatcherAny/whitelist.pac/master/whitelist.pac
