### ISSUE TITLE
服务器可ping，但是ss连接timed out，地理位置移动了几十公里，又换了运营商之后依然不行，这是被墙了吗？要不要换IP？

### ISSUE THREAD

**Issue by iAM261917** [shadowsocks/shadowsocks-windows#2114]
![c__windows_system32_cmd exe 2018_12_10 1_56_50](https://user-images.githubusercontent.com/42721712/49700863-4a90f600-fc1f-11e8-8dc2-823569672dc2.png)
![in_ 3 050mib out_ 582 3kib 2018_12_10 1_56_45](https://user-images.githubusercontent.com/42721712/49700865-4e247d00-fc1f-11e8-9258-3422bf59571d.png)

**Comment by chenshaoju** [comment]
是，如果你用的是板瓦工，请尝试更换IP。

https://twitter.com/FatherSucker/status/1071629353644044288

**Comment by iAM261917** [comment]
> 是，如果你用的是板瓦工，请尝试更换IP。
> 
> https://twitter.com/FatherSucker/status/1071629353644044288

是的，是搬瓦工，谢谢啦~
那条推特上的还是五周能换一次，我这里变成十周一次了，估计是一时间换的人太多，搬瓦工搞不过来了。
