### ISSUE TITLE
整合的privoxy的默认参数不合适

### ISSUE THREAD

**Issue by uuip** [shadowsocks/shadowsocks-windows#2115]
### Shadowsocks version / 影梭版本
所有

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win 10

### Steps you have tried / 操作步骤
浏览器同时打开多页页面

### What did you expect to see? / 期望的结果
浏览器正常加载

### What did you see instead? / 实际结果
在达到privoxy的限制后，浏览器显示 Maximum number of open connections reached.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

问题在于privoxy默认连接数128
6.9. max-client-connections
 Specifies:
    Maximum number of client connections that will be served.
但是每次客户端都是新的privoxy，所以这个参数即使改了也没用，因为改了需要重启privoxy；而重启ss客户端又时新的privoxy旧配置没了。
我记得之前有个版本是去掉privoxy的。

**Comment by chenshaoju** [comment]
这种情况最好自己跑一个privoxy，设定上级SOCKS5代理：
```
forward-socks5 / 127.0.0.1:1080 .
```

这样你就可以指定你想要的参数了。

**Comment by studentmain** [comment]
#2158

**Comment by uuip** [comment]
非常感谢更新。
