### ISSUE TITLE
4.0.6版本 启动后退出 Controller.Hotkeys.HotKeys.Init

### ISSUE THREAD

**Issue by Herod142** [shadowsocks/shadowsocks-windows#2118]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.0.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win 7 NET Framework 3.5.1

### Steps you have tried / 操作步骤
启动后退出

### What did you see instead? / 实际结果
![image](https://user-images.githubusercontent.com/45760996/49734632-db1f1300-fcbf-11e8-981b-c9e4c27669c4.png)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2018-12-10 21:03:23] [E] System.MissingMethodException: 找不到方法:“System.Nullable`1<Int32> MS.Win32.SafeNativeMethods.GetCurrentSessionId()”。
   在 System.Windows.Interop.HwndTarget..ctor(IntPtr hwnd)
   在 System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   在 GlobalHotKey.HotKeyManager..ctor()
   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   在 Shadowsocks.Program.Main()
[2018-12-10 21:06:14] [E] System.MissingMethodException: 找不到方法:“System.Nullable`1<Int32> MS.Win32.SafeNativeMethods.GetCurrentSessionId()”。
   在 System.Windows.Interop.HwndTarget..ctor(IntPtr hwnd)
   在 System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   在 GlobalHotKey.HotKeyManager..ctor()
   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   在 Shadowsocks.Program.Main()
```

**Comment by Herod142** [comment]
![image](https://user-images.githubusercontent.com/45760996/49734913-b8412e80-fcc0-11e8-9528-f8147240b33f.png)

**Comment by Herod142** [comment]
![123](https://user-images.githubusercontent.com/45760996/49734966-deff6500-fcc0-11e8-8594-8cefa5cfd056.png)

**Comment by celeron533** [comment]
1. 升级到最新版
2. 参考#2014
