### ISSUE TITLE
ios端可以连接 但是windows端的连接不了（在虚拟机和两台不同的电脑上都试过了，手机开热点也不行）

### ISSUE THREAD

**Issue by yinlang832** [shadowsocks/shadowsocks-windows#2125]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本

4.1.3.1
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windos10 
4.7.2
### Steps you have tried / 操作步骤
正常操作 在虚拟机和两台不同的电脑上都试过了，手机开热点也不行

### What did you expect to see? / 期望的结果
成功连接

### What did you see instead? / 实际结果
未能连接

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2018-12-18 09:38:17] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2018-12-18 09:38:28] Shadowsocks started (4.1.3.1)
[2018-12-18 09:38:28]

**Comment by yinlang832** [comment]
用tcp工具ping过了 是通的

**Comment by chenshaoju** [comment]
你是否有使用插件？

**Comment by yinlang832** [comment]
> 你是否有使用插件？

没有使用过插件

**Comment by yinlang832** [comment]
> 你是否有使用插件？

![image](https://user-images.githubusercontent.com/8005721/50139768-94dc3c00-02dd-11e9-9201-072516d16609.png)

**Comment by yinlang832** [comment]
> 请记得隐藏你的服务器信息（左边）。
> 
> 请确保你的密码、加密方式正确，另外，你没有开启正向代理把？
> 没有开启 此外我尝试ping了一下ip， ping是能ping通的
但是
![image](https://user-images.githubusercontent.com/8005721/50141324-2b126100-02e2-11e9-9fc7-7925ac4d46bf.png)
![image](https://user-images.githubusercontent.com/8005721/50141366-441b1200-02e2-11e9-9afb-69548550bc31.png)
![image](https://user-images.githubusercontent.com/8005721/50141415-67de5800-02e2-11e9-8524-cf439aaf60c8.png)

**Comment by chenshaoju** [comment]
请隐藏你的服务器信息（第二张图）。

很难确定你的这个现象，感觉是你电脑上有什么东西或者网络上有什么东西直接掐断了你的访问过程。

如果你的服务器是自己搭的，套一个kcptun或者goquite看看？

**Comment by yinlang832** [comment]
到最后也没确定原因。。换了台服务器好了，感觉可能和人在帝都有关系吧。。封的比较严
