### ISSUE TITLE
An unexpected exception occurred after wakeup windows 10

### ISSUE THREAD

**Issue by xuemin-chang** [shadowsocks/shadowsocks-windows#2128]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭
An exception dialog is shown when I open my notebook running windows 10. It was fallen into sleep last night. No related error until then.
The detail information was:
![image](https://user-images.githubusercontent.com/23445752/50259366-c4568a00-043e-11e9-980d-c31c0a9ebeb2.png)

### Shadowsocks version / 影梭版本
4.1.2.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 Home 中文版
OS 版本:          10.0.17134 暂缺 Build 17134dx
.NET Framework 4.7.2

### Steps you have tried / 操作步骤
No other operations.

### What did you expect to see? / 期望的结果
Continue to run without exiting.

### What did you see instead? / 实际结果
Exited.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
Didn't see any logs. Where are they?

**Comment by chenshaoju** [comment]
请右击托盘区的纸飞机小图标，指向“服务器”，然后点击“统计配置”，并取消“Enable Statistics”复选框，并点击OK按钮即可。
