### ISSUE TITLE
无法更新PAC 点击GFWlist 提示无法更新 

### ISSUE THREAD

**Issue by lt201081** [shadowsocks/shadowsocks-windows#2129]
![_20181220105651](https://user-images.githubusercontent.com/31964103/50261143-2a92db00-0446-11e9-92db-de4f659311cc.png)

**Comment by chenshaoju** [comment]
你好，你使用的SSR，不是SS。

这意味着你的配置有误，或者服务器不通，请仔细检查服务器工作是否正常，服务端程序是否启动，端口、加密方式、密码、混淆方式等配置是否正确。
