### ISSUE TITLE
在线pac无法使用

### ISSUE THREAD

**Issue by Anyiran** [shadowsocks/shadowsocks-windows#2130]
### Shadowsocks version / 影梭版本
4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows 8.1 
.net 4.7.2

### Steps you have tried / 操作步骤
设置在线 pac 为
https://raw.githubusercontent.com/MatcherAny/whitelist.pac/master/whitelist.pac
并启用系统代理

### What did you expect to see? / 期望的结果
系统能够正常访问

### What did you see instead? / 实际结果
无法访问，切换到本地 pac ( gfwlist )后正常，把上述白名单的内容复制到 pac.txt 后
又无法访问

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
{
  "version": "4.1.3.1",
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "portableMode": true,
  "pacUrl": "https://raw.githubusercontent.com/MatcherAny/whitelist.pac/master/whitelist.pac",
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": true,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}
```

**Comment by pexcn** [comment]
https://github.com/MatcherAny/whitelist.pac/issues/new

**Comment by chenshaoju** [comment]
看了一下说明：https://github.com/MatcherAny/whitelist.pac/blob/master/README.md ，好象是通过 Chrome + SwitchOmega 使用的。

**Comment by Anyiran** [comment]
> 
> 
> 看了一下说明：https://github.com/MatcherAny/whitelist.pac/blob/master/README.md ，好象是通过 Chrome + SwitchyOmega 使用的。

那就是说在线pac基本没有白名单模式的吗?

**Comment by AnyWAT** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2113#issuecomment-445547705 貌似 gfwlist 支持的是黑名单

**Comment by Anyiran** [comment]
> 
> 
> 看了一下说明：https://github.com/MatcherAny/whitelist.pac/blob/master/README.md ，好象是通过 Chrome + SwitchyOmega 使用的。

发现当chrome用系统代理时，白名单可用，IE11就不行，某些软件内嵌网页打不开

**Comment by celeron533** [comment]
猜测：有些软件内嵌的页面可能是本地文件系统地址甚至是某些特殊的协议+地址组合，导致没有命中白名单然后走代理
