### ISSUE TITLE
win10 ss客户端闪退

### ISSUE THREAD

**Issue by cyanideee** [shadowsocks/shadowsocks-windows#2132]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.2 / 4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 家庭版 64位操作系统   .NET Framework 4.7.2  Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24215

### Steps you have tried / 操作步骤
双击启动Shadowsocks客户端

### What did you expect to see? / 期望的结果
正常使用

### What did you see instead? / 实际结果
Shadowsocks闪退

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2018-12-23 21:22:31] Shadowsocks started (4.1.2)
[2018-12-23 21:22:31] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2018-12-23 21:22:56] Shadowsocks started (4.1.2)
[2018-12-23 21:22:56] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================
```

**Comment by cyanideee** [comment]
C:\SS\  D:\SS\  E:\SS\  F:\SS\ 都尝试过了，电脑除了自带的windows defender外，没有安装任何安全软件，window defender的实时保护和防火墙也已经全部禁用了

**Comment by chenshaoju** [comment]
这个现象很难得出准确结果，可能得盲测一下，请尝试从：
https://www.microsoft.com/en-us/download/details.aspx?id=30135

下载 .NET Framework 修复工具，按照提示操作，修复一次后重新启动计算机，看看能否启动SS。

**Comment by cyanideee** [comment]
依然闪退..

**Comment by chenshaoju** [comment]
你可能需要备份数据，然后重置系统看看了。

**Comment by studentmain** [comment]
https://ci.appveyor.com/api/buildjobs/f1w5tdr3d8t9a6ce/artifacts/shadowsocks-csharp%2Fbin%2Fx86%2FDebug%2FShadowsocks.exe

还是先拿debug配置的试试，看看能不能抓到详细日志。

**Comment by neozhu** [comment]
怎么又开始活跃了，不是作者被关起来了吗

**Comment by studentmain** [comment]
@neozhu 开源软件的生死不依赖于特定个体的生死。顺便一问，火星天气如何。

**Comment by celeron533** [comment]
如果是公司、学校或者企业的计算机，请确认公司IT有没有设置相应策略定时关闭违规软件
