### ISSUE TITLE
使用本地PAC无法使用，全局可以

### ISSUE THREAD

**Issue by nightmaring** [shadowsocks/shadowsocks-windows#2134]
### Shadowsocks version / 影梭版本
v3.4.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows 10
.NET Framework 4.0

### Steps you have tried / 操作步骤
启动软件，使用本地PAC无法上google.com，并且无日志，全局可以

### What did you expect to see? / 期望的结果
翻墙

### What did you see instead? / 实际结果
无法使用PAC

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请更新到最新版（https://github.com/shadowsocks/shadowsocks-windows/releases），启动SS后，右击托盘区的纸飞机图标，选择PAC，然后再选择“从GFWList更新本地PAC”即可。
