### ISSUE TITLE
windows fucking tap.

### ISSUE THREAD

**Issue by LiveChief** [shadowsocks/shadowsocks-windows#2135]
Hey can we please add a feature for windows tap like outline, i love that client but its doesn't support TCP at all and fucking hate it for that matter so can we please add windows tap, and more people would use this client as a normal vpn instead of a proxy, 

i just want to vpn everything like android instead of proxying everything // most of the apps i use don't support proxy at all

sorry for the broken English i am pretty fucking high.

**Comment by studentmain** [comment]
Keep calm......
- ss-windows is a 'portable app'. It mean you can run it in USB disk, SMB share, RDP disk mapping, etc. So you mean you want it install TAP driver everywhere ( even Windows Server )?
- When Outline add TAP driver, their team used 2 months to make it stable (I means, at least works for most people). IMO, if ss-windows add TAP, after another 2 months, maybe we're still try to make it work. 
- Here's an old-school workaround, it's a little heavy but works well. "VPN over Shadowsocks".
  1. Install SoftEtherVPN and shadowsocks on both server and client --SEVPN can works on single TCP connection and provide both TCP and UDP access
  2. Open shadowsocks, just open and select server, don't "connect" --Which means set your system proxy
  3. Open SEVPN, connect via SOCKS5 proxy.
  4. Enjoy
- Or you just need sstap?

**Comment by LiveChief** [comment]
Or you just need sstap?
>just this please.

**Comment by studentmain** [comment]
My SEVPN over SS works well... Use SEVPN latest RTM and V2Ray (SS compatible) latest on server side

FYI
- https://github.com/Jigsaw-Code/outline-client/issues/391
- https://github.com/Jigsaw-Code/outline-client/issues/329#issuecomment-449046222

**Comment by LiveChief** [comment]
Tried it and hated it, would rather use TAP.
