### ISSUE TITLE
SS客户端闪退

### ISSUE THREAD

**Issue by ChenChiChi** [shadowsocks/shadowsocks-windows#2136]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.0.4

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 专业版

### Steps you have tried / 操作步骤
双击打开

### What did you expect to see? / 期望的结果
自动翻墙

### What did you see instead? / 实际结果
[2018-12-28 10:52:01] [E] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main()

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请升级到最新版。 https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by firstblood1985** [comment]
升到最新版之后还是有同样的闪退问题。
而且ss_win_temp不让删，删了之后会被报该目录找不到的exception

**Comment by chenshaoju** [comment]
请将 Shadowsocks.exe 放到一个新目录，比如 D:\SS\ 目录看看。

**Comment by q13392** [comment]
把.net版本升级到4.6.2可以解决
https://www.microsoft.com/en-us/download/confirmation.aspx?id=53344
