### ISSUE TITLE
PAC 规则对于某些网址不生效，以及浏览器不能实时更新的问题

### ISSUE THREAD

**Issue by g495326** [shadowsocks/shadowsocks-windows#2140]
● Shadowsocks version / 影梭版本
4.1.2

● Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7 Sp1

● Steps you have tried / 操作步骤
1、在user-rule.txt中写入「||ip.cn」，见下图
![2019-01-01_144257](https://user-images.githubusercontent.com/41222130/50570789-bf48f180-0dd3-11e9-974b-d1779f9a9f2f.png)
2、重启「系统代理」（可以看到pac文件确实改变了，但是浏览器好像并没有使用的新pac规则，如果可以的话，这个问题可否回答下？）
3、再次打开「https://ip.cn」，但是ip地址仍然是我本机的ip，而不是远程服务器的ip，见下图
![2019-01-01_144834](https://user-images.githubusercontent.com/41222130/50570812-bd336280-0dd4-11e9-95eb-917bfc78ef04.png)

● What did you expect to see? / 期望的结果
显示远程服务器ip，就像我使用「全局代理」模式下的显示，见下图
![2019-01-01_145434](https://user-images.githubusercontent.com/41222130/50570826-5a8e9680-0dd5-11e9-83e3-c7fce5d4b1bd.png)

● What did you see instead? / 实际结果
就像没有使用使用代理访问一样

● Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
我认为和此项关系不大，因为类似的查询ip的网站如「https://www.iplocation.net/」类似设置是可以生效的。

PS: 这问题让我一度很奇怪，希望尽快收到作者的回复。

**Comment by chenshaoju** [comment]
请尝试升级到最新版本，在修改 user-rule.txt 后，请关闭系统代理然后再打开即可立刻生效。

https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by chenshaoju** [comment]
请退出SS，打开 gfwlist.txt 文件，应该会看到一个名为 ` "@@||ip.cn" `一行，删掉后再启动SS后再试。

**Comment by g495326** [comment]
在 gfwlist.txt 文件中没有找到所说的"@@||ip.cn"的一行，如下图。
![2019-01-01_154647](https://user-images.githubusercontent.com/41222130/50571132-dc35f280-0ddc-11e9-8375-4bec91ec27aa.png)

倒是在pac.txt文件中找到了，不知否说的是否是这个。如下图
![2019-01-01_155114](https://user-images.githubusercontent.com/41222130/50571141-38991200-0ddd-11e9-9d63-5e399d84b211.png)

**Comment by chenshaoju** [comment]
对对，就是 pac.txt ，不好意思打错了。

**Comment by g495326** [comment]
非常感谢，可以使用了。

能否更新一下，在更新user-rule.txt后自动生效，而不是关闭系统代理然后再打开才行。

期待你的回答。

**Comment by chenshaoju** [comment]
该问题已知，详见：https://github.com/shadowsocks/shadowsocks-windows/issues/2098

**Comment by g495326** [comment]
我仔细浏览了#2098，以及你最后提交的链接内容。

但是仍然算不上最佳的解决方案，而我想要的结果仅是在user-rule.txt改变后，浏览器能够适用改变后新pac文件（丢弃原来的缓存，重新缓存，而不是不缓存。如微软英文所示）。

「then you may want to disable the Automatic Proxy Result Cache feature. This will result in client-side processing of every GET request that is issued by Internet Explorer. As a result, Internet Explorer performance may be impacted depending on the logic of the Automatic Proxy Configuration Script and its size.」

既然ss能够检测到文件的变化，那为什么不让其自己自动关闭系统代理再自己打开呢？

**Comment by chenshaoju** [comment]
I Don't know ，具体可以阅读帖子里 Celeron533 的回复。

**Comment by g495326** [comment]
虽然他的回复解释了问题，但是好像仅解释了为何pac没法自动适用原因，但是对于让软件自身重启系统代理并没有回答。不过还是希望能解决好吧！还有感谢你的热心回答。

对了，能否解释下「保护本地pac」是什么意思。ss好像并没有阻止其他软件编辑该pac文件。
![2019-01-01_165559](https://user-images.githubusercontent.com/41222130/50571466-8d8d5600-0de6-11e9-9b9f-dae3aa1cbf1d.png)

**Comment by chenshaoju** [comment]
作用好像是在PAC代理地址中生成一个PacSecret的随机数：
https://github.com/shadowsocks/shadowsocks-windows/blob/98538e32c043a8d1c0cb57937c6c9a19c4d2e380/shadowsocks-csharp/Controller/Service/PACServer.cs#L43

**Comment by g495326** [comment]
Thanks a lot. Good Mood Everyday.

**Comment by AnyWAT** [comment]
貌似复制文件夹到任意位置都是以原来参数运行

**Comment by celeron533** [comment]
>对了，能否解释下「保护本地pac」是什么意思。

@g495326 所有的PAC文件内容请求会要求带有指定的secret=<base64key>，这样不是所有的局域网用户都能使用这个PAC
