### ISSUE TITLE
SS在其它电脑上无法使用

### ISSUE THREAD

**Issue by mouleimu** [shadowsocks/shadowsocks-windows#2141]
问题1：同一份ss文件夹下的文件，复制过去之后一开始可以用，后来重启不能使用。PAC内的网址均不能访问，如果切换全局模式，所有网址无法访问。原来的电脑这两种模式不影响使用。
问题2：Win 10的电脑高版本和低版本的ss都可以打开，win 8 的电脑低版本的可以打开，高版本的不行。

**Comment by lucksevenl7** [comment]
@mouleimu 最新版本的ss需要 .NET Framework 4.6.2，您的win 8上安装了吗？

**Comment by celeron533** [comment]
some antivirus would disallow system level proxy change.
