### ISSUE TITLE
求助 打开就报错，不能正常使用

### ISSUE THREAD

**Issue by wangkedba** [shadowsocks/shadowsocks-windows#2142]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本

4.1.3.1
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

windows10
### Steps you have tried / 操作步骤

解压后打开
### What did you expect to see? / 期望的结果

正常使用
### What did you see instead? / 实际结果
报错，

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
system.TypeInitializationException:
"Shadowsocks.Encryption.EncryporFactory"的类型初始值设定项引发异常。 --->
System.TypeinitializationException:"Shadowsocks.Encryption.Sodium"的类型初始值设定引发异常。 ---> System.DllNotFoundException:无法加载“libsscrypto.dll":找不到指定模块。（异常来自 hresult:0x8007007E）

**Comment by chenshaoju** [comment]
请尝试新建一个目录，如 D:\SS\ ，然后将 Shadowsocks.exe 单独放进去，执行看看是否能够使用。

**Comment by wangkedba** [comment]
可以了，谢谢！
