### ISSUE TITLE
使用SS的PAC模式后，国内正常访问的网站变得特别慢

### ISSUE THREAD

**Issue by williamsleed** [shadowsocks/shadowsocks-windows#2143]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Win10 专业版本
版本号1803

### Steps you have tried / 操作步骤
使用SS的PAC模式后，国内正常访问的网站变得特别慢，比如baidu.com、taobao.com，全局模式加载国内网页反而特别快，被墙的网站如google.com无论是PAC还是全局模式始终很快，关闭SS后国内网站访问速度恢复正常

### What did you expect to see? / 期望的结果

期望使用PAC模式，国内网站访问不受影响，按需使用

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
配置文件都是默认的，没有修改过。

**Comment by williamsleed** [comment]
浏览器使用的是Chrome和360安全浏览器。DNS：8.8.8.8  114.114.114.114

**Comment by chenshaoju** [comment]
请尝试在启动SS，PAC模式下访问 http://www.ip.cn ，显示的IP地址是你的国内IP还是你的SS服务器IP？

**Comment by celeron533** [comment]
如果你已经在路由器上部署过ss，不要再在PC上使用ss，这样会导致数据走两次隧道

**Comment by williamsleed** [comment]
@chenshaoju 刚测试了几次手机和PC，我PAC模式无法打开https://www.ip.cn/ 全局才可以

**Comment by williamsleed** [comment]
@celeron533 路由上没有部署，只有PC在用

**Comment by lucksevenl7** [comment]
@williamsleed https://www.ip.cn/  不需要ss也能访问，有可能是你机器或者路由器的dns设置出现了一点问题？

**Comment by williamsleed** [comment]
上不去，路由器拨号上网DNS自动设置为：124.207.160.106 , 219.239.26.42。无法更改。DHCP那的DNS可以更改：114.114.114.114，8.8.8.8  我是长城宽带，不知道是不是运营商那是否给墙了，有别的可查问题地址吗？  经过多次测试  确实是开SS PAC模式国内有问题 ，不开国内没问题。

**Comment by chenshaoju** [comment]
如果你不开SS，能否正常访问国内的网站？

另外，PAC模式下，如果 ip.cn 打不开的话，百度能打开吗？在百度搜索 ip ，显示的IP是国内的IP还是你的服务器的IP？

**Comment by AnyWAT** [comment]
> 路由器拨号上网DNS自动设置为：124.207.160.106 , 219.239.26.42。无法更改。

PPPoE高级设置——手动设置DNS服务器

**Comment by williamsleed** [comment]
> > 路由器拨号上网DNS自动设置为：124.207.160.106 , 219.239.26.42。无法更改。
> 
> TP路由器：网络参数——WAN口设置——高级设置——PPPoE高级设置——手动设置DNS服务器

谢谢，这是老版本的路由 。我是新版路由。没有WAN 只有DHCP服务器的DNS设置

**Comment by williamsleed** [comment]
> 如果你不开SS，能否正常访问国内的网站？
> 
> 另外，PAC模式下，如果 ip.cn 打不开的话，百度能打开吗？在百度搜索 ip ，显示的IP是国内的IP还是你的服务器的IP？

@chenshaoju PAC模式下百度是本地ip,全局模式下是服务器Ip

**Comment by chenshaoju** [comment]
这说明你的国内访问是正常的，但是PAC模式有些国内网站打不开，但是全局模式能打开的话，可能是你的网络服务商存在问题。

如果你不使用SS，可能也无法打开这些网站。

**Comment by williamsleed** [comment]
> 这说明你的国内访问是正常的，但是PAC模式有些国内网站打不开，但是全局模式能打开的话，可能是你的网络服务商存在问题。
> 
> 如果你不使用SS，可能也无法打开这些网站。

是的，回到原来的问题。平时正常访问的网站，打开SS PAC就会变慢，可能是什么原因？

**Comment by chenshaoju** [comment]
理论上浏览器查询PAC这个过程可能会影响到一点速度，但是速度影响不应该太大，除非你的计算机内存很小或者处理器速度很慢……感觉不太可能。

能否做个测试，使用 fast.com 测试速度，SS工作在PAC模式和没有开启SS的情况下，速度如何？

**Comment by williamsleed** [comment]
> 从第二张图来看，经过了你的代理，速度还快一些。不过这个不是测试目的，确定第二张图是在pac模式下进行的吗？
> 
> 因为 gfwlist 好像没有代理 fast.com 。

不好意思，中午回复完您之后就断网了，网络刚恢复，早上测试的是PAC模式和全局模式，SS关闭没有测试，现在重新测试补充一下，如下图：
![pac](https://user-images.githubusercontent.com/15337053/50684228-ac425580-104f-11e9-8555-4376a8478d1e.png)
![default](https://user-images.githubusercontent.com/15337053/50684230-acdaec00-104f-11e9-933c-89c98c869f4e.png)
![ss](https://user-images.githubusercontent.com/15337053/50684231-acdaec00-104f-11e9-8831-2f6ed3184b35.png)

**Comment by chenshaoju** [comment]
这现象比较难以解释，PAC和全局能正确的显示你的客户端IP，但是延迟都很高。

关闭SS后，延迟很低，但是速度又很慢。

我不确定发生了什么。

**Comment by williamsleed** [comment]
issues

> 这现象比较难以解释，PAC和全局能正确的显示你的客户端IP，但是延迟都很高。
> 
> 关闭SS后，延迟很低，但是速度又很慢。
> 
> 我不确定发生了什么。

好吧，谢谢，那暂时我就先开着SS吧。不开卡的不适应哈哈。感谢大佬！顺便问个别的问题：
我用SSTAP连接SS节点。UDP经常失败，偶尔能通过，请问是什么问题，是否有别的issues连接已经解决的？我用的是flyzy2005/ss-fly的一键搭建脚本 https://github.com/flyzy2005/ss-fly

**Comment by chenshaoju** [comment]
不太确定，我没有使用过SSTAP。

**Comment by williamsleed** [comment]
> 不太确定，我没有使用过SSTAP。

好的，感谢大佬。

**Comment by LeonSparta** [comment]
> > 不太确定，我没有使用过SSTAP。
> 
> 好的，感谢大佬。

挖个坟，UDP是需要服务器支持UDP转发才能开的

**Comment by ahbiaoge** [comment]
PAC模式后，国内正常访问的网站变得特别慢或打不开，你们遇到这种情况没？

**Comment by chenshaoju** [comment]
请退出 Shadowsocks ，进入 Shadowsocks.exe 所在的目录，使用任意文本编辑器打开 gui-config.json 文件，找到 `"geositePreferDirect": false,` ，并将其修改为 `"geositePreferDirect": true,` ，保存退出后删除同目录下的 pac.txt 文件，再启动 Shadowsocks 即可。

若已经为 `"geositePreferDirect": true,` ，请直接删除同目录下的 pac.txt 文件后，再启动 Shadowsocks 即可。
