### ISSUE TITLE
今天更新了最新版本shadowshocks出现非预期错误，将退出

### ISSUE THREAD

**Issue by hzwengwei** [shadowsocks/shadowsocks-windows#2146]
![default](https://user-images.githubusercontent.com/46445306/50766791-89b17600-12b5-11e9-803a-50dc6350c01b.png)

**Comment by hzwengwei** [comment]
问题解决了

**Comment by yaohcn** [comment]
请问怎么解决的？

**Comment by chenshaoju** [comment]
最新版本应该解决了该问题：
https://github.com/shadowsocks/shadowsocks-windows/releases
