### ISSUE TITLE
PAC模式与正向代理的问题

### ISSUE THREAD

**Issue by Clackz** [shadowsocks/shadowsocks-windows#2150]
版本4.1.3.1，系统 Win10 1809
PAC模式是否无法通过正向代理连接？设置为全局代理时可以正常上网，然而设置为PAC模式就无法上网。

**Comment by chenshaoju** [comment]
正向代理的作用是指当你上网需要通过你所在机构的代理服务器上网时才需要进行配置的。

你上网时需要通过一个代理服务器，还是直接就可以上网？

如果是后者，不需要设置正向代理。

**Comment by Clackz** [comment]
> 正向代理的作用是指当你上网需要通过你所在机构的代理服务器上网时才需要进行配置的。
> 
> 你上网时需要通过一个代理服务器，还是直接就可以上网？
> 
> 如果是后者，不需要设置正向代理。

公司网络是需要通过一个代理服务器的，如果代理服务器无效的话，全局模式应该也会受到影响。

**Comment by chenshaoju** [comment]
我测试了一下，基于CCProxy搭建的SOCKS5服务器在PAC模式下没有任何问题。

![2019-01-11 2](https://user-images.githubusercontent.com/515763/51015580-bf9d7580-15a7-11e9-83be-07d0c680ec22.png)

![qq 20190111134731](https://user-images.githubusercontent.com/515763/51015587-c1673900-15a7-11e9-91aa-bded4cf021e0.png)

这个问题可能和代理服务器无关，有可能你的系统PAC工作不正确。

你使用的是普通的局域网上网，还是拨号（或虚拟）连接？

**Comment by Clackz** [comment]
> 我测试了一下，基于CCProxy搭建的SOCKS5服务器在PAC模式下没有任何问题。
> 
> ![2019-01-11 2](https://user-images.githubusercontent.com/515763/51015580-bf9d7580-15a7-11e9-83be-07d0c680ec22.png)
> 
> ![qq 20190111134731](https://user-images.githubusercontent.com/515763/51015587-c1673900-15a7-11e9-91aa-bded4cf021e0.png)
> 
> 这个问题可能和代理服务器无关，有可能你的系统PAC工作不正确。
> 
> 你使用的是普通的局域网上网，还是拨号（或虚拟）连接？

DHCP分配的局域网地址，但是需要软件登录认证，如果是系统PAC工作问题的话，我回家再试试看，不过我公司的代理服务器是用HTTP方式的，不知道有没有关系呢？
![default](https://user-images.githubusercontent.com/42225208/51015877-cf698980-15a8-11e9-8616-97bc786a84e0.png)

**Comment by chenshaoju** [comment]
理论上需要你的HTTP代理服务器支持Http CONNECT方式https://github.com/shadowsocks/shadowsocks-windows/issues/2072#issuecomment-440929022

不过由于全局模式可以，应该不是代理服务器的问题。请尝试退出认证软件，然后打开网络连接，看一下当前的网络连接列表，当打开认证软件并连接后，否多了一个你的认证连接出现或者连接上了？

这个连接是中文的名字吗？

**Comment by nanjian5** [comment]
有同样的问题
公司只支持http代理
然后shadowsocks windows client设置全局模式可以，设置pac模式不行，pac文件能正常更新

**Comment by chenshaoju** [comment]
因为你上网本身需要经过代理，PAC也是设置代理的一种，会冲突。

这种情况你只能依赖浏览器的PAC代理或者使用第三方的代理插件了。
