### ISSUE TITLE
shadowsocks non-UI error

### ISSUE THREAD

**Issue by LEGENDMOUSE** [shadowsocks/shadowsocks-windows#2152]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本

4.1.3.1
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

windows 10..NET Framework 3.5
### Steps you have tried / 操作步骤

打开shadowsocks
### What did you expect to see? / 期望的结果

能用
### What did you see instead? / 实际结果

一打开就退出
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![default](https://user-images.githubusercontent.com/46600009/51038022-ee8a0a80-15ec-11e9-9251-9b1e136f2b7b.png)
![1](https://user-images.githubusercontent.com/46600009/51038023-efbb3780-15ec-11e9-8997-1ebfb9509160.png)

**Comment by chenshaoju** [comment]
请确保你是从 https://github.com/shadowsocks/shadowsocks-windows/releases 获取的SS客户端。

另外，你的计算机是你自己的，还是属于一个机构（企业？学校？单位？）？。

**Comment by LEGENDMOUSE** [comment]
> 请确保你是从 https://github.com/shadowsocks/shadowsocks-windows/releases 获取的SS客户端。
> 
> 另外，你的计算机是你自己的，还是属于一个机构（企业？学校？单位？）？。

我自己

**Comment by studentmain** [comment]
怀疑要重装netframework走起

**Comment by chenshaoju** [comment]
我记得好像要4.7.x才能支持，请尝试更新或者修复安装看看：
https://www.microsoft.com/net/download/dotnet-framework-runtime

**Comment by LEGENDMOUSE** [comment]
> 怀疑要重装netframework走起
我装了，但显示有更高版本，但我在程序里找不到.NET framework,只有底下图片两个路径，与之有关。怎么卸载现在的呀，好像得卸载以后重装。
![default](https://user-images.githubusercontent.com/46600009/51093953-7a658780-17e3-11e9-93f8-35122ef5db56.png)
![2](https://user-images.githubusercontent.com/46600009/51093956-7e91a500-17e3-11e9-84a8-1b0ec74f449d.png)
![3](https://user-images.githubusercontent.com/46600009/51093958-82bdc280-17e3-11e9-8d58-9a25d7a6b780.png)

**Comment by chenshaoju** [comment]
请尝试使用 .Net Framework Cleanup 清理一下，然后再重新安装看看：
https://blogs.msdn.microsoft.com/astebner/2008/08/28/net-framework-cleanup-tool-users-guide/

**Comment by LEGENDMOUSE** [comment]
我重置了一下电脑，用.NET 清除工具清除过了 又用 .NET repair 工具修复过了 在注册表里查了一下，应该有 .NET Framework 4.7.2 注册表图片在下面 然后又重下 shadowsocks 运行 还是不行 又弹出了对话框 图片在下面
![default](https://user-images.githubusercontent.com/46600009/51424625-581ca100-1c0b-11e9-979e-8a6c57496b77.png)
![2](https://user-images.githubusercontent.com/46600009/51424627-5a7efb00-1c0b-11e9-9568-528ef5e41542.png)
![3](https://user-images.githubusercontent.com/46600009/51424629-5bb02800-1c0b-11e9-9b7c-ecd99c28e370.png)
![4](https://user-images.githubusercontent.com/46600009/51424632-5d79eb80-1c0b-11e9-9746-9db8e8cd4bba.png)
