### ISSUE TITLE
Can it support multi session.Remote.BeginReceive and multi session.Remote.BeginSend?

### ISSUE THREAD

**Issue by skyduy** [shadowsocks/shadowsocks-windows#2153]
After established with client, ss-local relay data between client and ss-server, but there is only one channel forwarding or backwarding data simultaneously. To accelerate speed, we can use multi TCP channels between ss-local and ss-server and using a sliding window to manage data blocks transmitted by these channels to ensure the final data is continuous.

However, after exploring the file [TCPRelay.cs](https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/TCPRelay.cs#L790), I found it too hard for me  to modify the code to support multi thread. I have no idea about how to create multi session.Remote and manage them orderly(sorry to say I'm a newer to C#).

[Here](https://github.com/ihciah/go-shadowsocks-magic) is the ss-server supporting multi channel.

Is it feasible to integrate multi-thread or coroutine in your project? waiting for your reply, thanks.

**Comment by celeron533** [comment]
Thanks @skyduy 
One of the concerns is that too many TCP connections may also become a kind of signature for evil detectors to findout you are using ss
