### ISSUE TITLE
Non-UI Error: NullReferenceException on Startup

### ISSUE THREAD

**Issue by rxu18** [shadowsocks/shadowsocks-windows#2156]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.0.4

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10, .NET version 4.7.2.

### Steps you have tried / 操作步骤
Open Shadowsocks on startup.

Fixes I tried from related issues:
Disable statistics like #866. Statistics is already disabled.
Delete user-wininet.json like #1235. No effect.
Install latest version of .NET like #1199. Found 4.7.2 is already installed.

### What did you expect to see? / 期望的结果
Shadowsocks run with no error message.

### What did you see instead? / 实际结果
Error message below. Shadowsocks still runs and seems to function properly despite the error.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![error](https://user-images.githubusercontent.com/42388482/51075681-25980480-165d-11e9-8c90-9775b7787717.png)

**Comment by celeron533** [comment]
Plz update to 4.1.3.1
