### ISSUE TITLE
速度慢

### ISSUE THREAD

**Issue by RDSJC** [shadowsocks/shadowsocks-windows#2160]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
Shadowsocks-windows 4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows10 , .NET Framework 4.5

### Steps you have tried / 操作步骤
升级到4.1.3.1后速度明显变慢，换回旧版本后速度比新版本快但是相比之前慢很多，在安卓客户端速度正常，服务器端正常

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请使用Ping命令Ping你的服务器，如果延迟很高，请尝试与你的SS服务商取得联系，更换其他的服务器地址，如果是你自己搭的，请尝试换一个其他区域。
