### ISSUE TITLE
【求助】理论上SS是不是可以这样玩儿，匿名安全性是否会得到提高

### ISSUE THREAD

**Issue by qwertccc** [shadowsocks/shadowsocks-windows#2164]
今天中午才开始用SS，发现ss设置里有个”正向代理“

而且我发现ss可以多开

那么我买三个国家三个运营商的三个vps分别建立ABC三个服务端

本机开三个SS，采用正向代理，一个套一个，本机访问的是A，最终出口是C，A和C中间还有个B

那么理论上肯定还是可以溯源到我本机，但是需要首先拿到C的数据并且逆向分析C，然后才能看到B，最后才能发现A。。。分属三个国家三个运营商的三台VPS，而且都是强加密。。。从实际操作角度，是不是可以断定我已经实现了高度匿名

或者在C之后我再套一个TOR。。。

**Comment by studentmain** [comment]
可以上，无有力证据证明有明显收益。毕竟有的人上了之后翻车了，有的人原版翻车之后上了救回来了，只能说试试。

**Comment by qwertccc** [comment]
如果理论上可行，我感觉ss还可以演化成一个高匿的工具

我没开这个，我就原版，xchacha20-ietf-poly1305，主要是路由器的U没有v8指令集，就选这个了

**Comment by chenshaoju** [comment]
为什么不直接用Tor？
Tor over Shadowsocks

**Comment by qwertccc** [comment]
tor慢，我最后一句那意思是，实在不行，又或者套个tor

：）

**Comment by studentmain** [comment]
设计之初，ss仅仅就是为了糊弄墙，之所以加密，是为了混淆，之所以更新加密算法，是因为老加密混淆能力不够。ss的加密本身缺乏前向安全性，用来做匿名不够。要高度匿名，还得老老实实Tor走起。

**Comment by iAM261917** [comment]
但是简介不是说了keep secret 嘛

**Comment by studentmain** [comment]
keep (the fact that you can access google) secret

**Comment by oxoxoxox** [comment]
> 但是简介不是说了keep secret 嘛

Keep the data secret while transporting, not keep the data anonymous.

**Comment by williamxxy** [comment]
A如果是美国服务器直接套用tor然后把流量分到B，B用Shadowrocket over tor套用到C再用C开内核加速，用C搭arch用移动电脑分享到真实主机，除了麻烦，任何人都不可能找到真实ip除了有国际网警合作找你 😂，
