### ISSUE TITLE
关于腾讯上传ss服务配置，是否提供有效阻止方式

### ISSUE THREAD

**Issue by AziCat** [shadowsocks/shadowsocks-windows#2167]
如图：
![tim 20190119104712](https://user-images.githubusercontent.com/8189958/51421569-cf860c80-1bda-11e9-89ca-568a340ee1ea.png)

**Comment by studentmain** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2162#issuecomment-455615758
水过了，讨论过了
