### ISSUE TITLE
shadowsocks客户端报错 - Sysproxy.SetIEProxy

### ISSUE THREAD

**Issue by qtg451977252** [shadowsocks/shadowsocks-windows#2168]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.3

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10，.NET Framework4.7

### Steps you have tried / 操作步骤
打开软件报错，未将对象引用设置到对象实例
![default](https://user-images.githubusercontent.com/37928841/51437639-dfd1e080-1cdb-11e9-90a1-b0cc0b9bb80b.PNG)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
{
  "Calculations": {
    "AverageLatency": 0.0,
    "MinLatency": 0.0,
    "MaxLatency": 0.0,
    "AverageInboundSpeed": 0.0,
    "MinInboundSpeed": 0.0,
    "MaxInboundSpeed": 0.0,
    "AverageOutboundSpeed": 0.0,
    "MinOutboundSpeed": 0.0,
    "MaxOutboundSpeed": 0.0,
    "AverageResponse": 0.0,
    "MinResponse": 0.0,
    "MaxResponse": 0.0,
    "PackageLoss": 0.0
  },
  "StatisticsEnabled": false,
  "ByHourOfDay": true,
  "Ping": false,
  "ChoiceKeptMinutes": 10,
  "DataCollectionMinutes": 10,
  "RepeatTimesNum": 4
}
```

**Comment by studentmain** [comment]
换4.1.3.1

**Comment by studentmain** [comment]
不过话说回来，我记得4.1.3只当了24小时的最新（测试）版来着……为啥现在还有4.1.3版本流传

**Comment by AnyWAT** [comment]
也许24个月后仍然会有4.1.3版本流传，哈哈哈

**Comment by qtg451977252** [comment]
换了可以了- -，4.1.3就是在github上下的

**Comment by AnyWAT** [comment]
> 换了可以了- -，4.1.3就是在github上下的

在较短的时间内有更新，貌似前一版有不得不立马修复的 Bug 。。。

**Comment by celeron533** [comment]
@AnyWAT  所以4.1.3一直在pre-release状态
