### ISSUE TITLE
out.log 文件自动生成在D盘根文件夹

### ISSUE THREAD

**Issue by Falanke21** [shadowsocks/shadowsocks-windows#2169]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.0.10

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

### Steps you have tried / 操作步骤
删除文件

### What did you expect to see? / 期望的结果
out.log文件不再出现

### What did you see instead? / 实际结果
shadowsocks 放置于D盘内，D盘根文件夹会出现out.log 文件， 删除后out.log还会自动出现，并且大小在一直增加

打开out.log 之后：
![image](https://user-images.githubusercontent.com/39153483/51450975-ff2f3480-1d00-11e9-8153-2aa99df7b248.png)
![image](https://user-images.githubusercontent.com/39153483/51450999-1f5ef380-1d01-11e9-90ef-40fa2f303d50.png)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
这个日志不是 Shadowsocks 的一部分，搜了一下，你是否安装了一个叫 transocks （穿梭）的应用？

**Comment by Falanke21** [comment]
> 这个日志不是 Shadowsocks 的一部分，搜了一下，你是否安装了一个叫 transocks （穿梭）的应用？

是的。请问您搜索了什么网址？我可以借鉴一下吗？谢谢！

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/51453142-af8c4f80-1d78-11e9-90a0-04157f167a44.png)

**Comment by Falanke21** [comment]
谢谢！
