### ISSUE TITLE
 a suggestion - auto update gfwlist when startup

### ISSUE THREAD

**Issue by mhongreat** [shadowsocks/shadowsocks-windows#2170]
auto update pac  from gfwlist when startup

**Comment by chenshaoju** [comment]
It's maybe casing lot unnecessary request to Github ( gfwlist ).
Suggest at less 1 week?

**Comment by celeron533** [comment]
@chenshaoju then need a new persistent field to record the last updated time.

**Comment by database64128** [comment]
Close in favor of #3096.
