### ISSUE TITLE
win10 x64最近一次更新后提示端口已被占用

### ISSUE THREAD

**Issue by ShenWY** [shadowsocks/shadowsocks-windows#2171]
win10 x64最近一次更新后，Shadowsocks启动失败，提示：
端口已被占用 ---> System.Net.Sockets.SocketException: 以一种访问权限不允许的方式做了一个访问字的尝试。

通过netstat查看端口确实没有占用，换端口也无效。
换了多个版本的Shadowsocks-win都一样，启动Shadowsocks-win赋予管理员权限也不行。

**Comment by chenshaoju** [comment]
请尝试在编辑服务器界面右下角的代理端口更换一个新的端口看看，比如 10800 。

https://github.com/shadowsocks/shadowsocks-windows/issues/2035

**Comment by superqinwei** [comment]
任务管理器删掉obfs-local.exe

**Comment by qq4105195** [comment]
我也是啊 很奇怪啊 为什么端口没被占用 一直说端口被占用

**Comment by niubizi** [comment]
同样的问题，很奇怪，netstat 查看端口并没有占用，换1081、1082等端口都不行
试了10801可以了

**Comment by XueTeng2** [comment]
我今天也遇到了这个问题，shadowsocks和v2ray都因为端口占用报错，但是1080端口并没有被占用。

**Comment by XueTeng2** [comment]
我强行将本地端口改成了10800，没有再报错。是1080端口不能再使用了吗？

**Comment by chenshaoju** [comment]
这个可能和操作系统有关。

**Comment by XueTeng2** [comment]
很无奈，shadowsocks改了端口可以了，v2ray改端口还不行。

**Comment by chaosye0** [comment]
同样的问题，每次都得把占用端口的程序找到结束，占用端口的程序有 英伟达显卡驱动的一个程序，还有windows资源管理器，还有shadowsocks自己。。。

**Comment by XueTeng2** [comment]
> 同样的问题，每次都得把占用端口的程序找到结束，占用端口的程序有 英伟达显卡驱动的一个程序，还有windows资源管理器，还有shadowsocks自己。。。

我是根本找不到什么程序在占用，明明根本没有占用。

**Comment by chaosye0** [comment]
> > 同样的问题，每次都得把占用端口的程序找到结束，占用端口的程序有 英伟达显卡驱动的一个程序，还有windows资源管理器，还有shadowsocks自己。。。
> 
> 我是根本找不到什么程序在占用，明明根本没有占用。

你可以在cmd里试试这个命令netstat -ano|findstr "1080" 应该能输出占用1080端口的程序的pid

**Comment by XueTeng2** [comment]
> > > 同样的问题，每次都得把占用端口的程序找到结束，占用端口的程序有 英伟达显卡驱动的一个程序，还有windows资源管理器，还有shadowsocks自己。。。
> > 
> > 
> > 我是根本找不到什么程序在占用，明明根本没有占用。
> 
> 你可以在cmd里试试这个命令netstat -ano|findstr "1080" 应该能输出占用1080端口的程序的pid

我已经试过了，输入这个命令没有任何返回结果，说明1080端口没有被占用。

**Comment by SgAlice** [comment]
> > > > 同样的问题，每次都得把占用端口的程序找到结束，占用端口的程序有 英伟达显卡驱动的一个程序，还有windows资源管理器，还有shadowsocks自己。。。
> > > 
> > > 
> > > 我是根本找不到什么程序在占用，明明根本没有占用。
> > 
> > 
> > 你可以在cmd里试试这个命令netstat -ano|findstr "1080" 应该能输出占用1080端口的程序的pid
> 
> 我已经试过了，输入这个命令没有任何返回结果，说明1080端口没有被占用。

可以试试以管理员权限打开，我没有用管理员权限打开也未返回结果

**Comment by clanaid** [comment]
这个问题和 #1835 一样，我也是更新系统后发现端口被系统保留。

**Comment by celeron533** [comment]
系统保留端口在netstat是看不到有其他程序占用的，但你就是用不了。。。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。

**Comment by lzskyline** [comment]
管理员模式运行cmd:
netsh int ipv4 show dynamicport tcp
netsh int ipv4 set dynamic tcp start=49152 num=16384
重启即可

**Comment by zxh4well** [comment]
时间：2020/8/13
问题：win10更新后联网正常，浏览器访问网络被拒。win10更新后显示7890端口被svchost.exe程序占用。
之后使用win10自带的网络和internet->代理->手动设置代理->使用代理服务器（将其关闭后，可正常联网）。
这是为什么呢？！：D

**Comment by zxh4well** [comment]
时间：2020/8/13
问题：win10更新后联网正常，浏览器访问网络被拒。win10更新后显示7890端口被svchost.exe程序占用。
之后使用win10自带的网络和internet->代理->手动设置代理->使用代理服务器（将其关闭后，可正常联网）。
这是为什么呢？！：D

**Comment by zxh4well** [comment]
时间：2020/8/13
问题：win10更新后联网正常，浏览器访问网络被拒。win10更新后显示7890端口被svchost.exe程序占用。
之后使用win10自带的网络和internet->代理->手动设置代理->使用代理服务器（将其关闭后，可正常联网）。
这是为什么呢？！：D

**Comment by zxh4well** [comment]
时间：2020/8/13
问题：win10更新后联网正常，浏览器访问网络被拒。win10更新后显示7890端口被svchost.exe程序占用。
之后使用win10自带的网络和internet->代理->手动设置代理->使用代理服务器（将其关闭后，可正常联网）。
这是为什么呢？！：D

**Comment by zxh4well** [comment]
时间：2020/8/13
问题：win10更新后联网正常，浏览器访问网络被拒。win10更新后显示7890端口被svchost.exe程序占用。
之后使用win10自带的网络和internet->代理->手动设置代理->使用代理服务器（将其关闭后，可正常联网）。
这是为什么呢？！：D

**Comment by zxh4well** [comment]
时间：2020/8/13
问题：win10更新后联网正常，浏览器访问网络被拒。win10更新后显示7890端口被svchost.exe程序占用。
之后使用win10自带的网络和internet->代理->手动设置代理->使用代理服务器（将其关闭后，可正常联网）。
这是为什么呢？！：D

**Comment by zxh4well** [comment]
时间：2020/8/13
问题：win10更新后联网正常，浏览器访问网络被拒。win10更新后显示7890端口被svchost.exe程序占用。
之后使用win10自带的网络和internet->代理->手动设置代理->使用代理服务器（将其关闭后，可正常联网）。
这是为什么呢？！：D

**Comment by zhouinfo** [comment]
也出现了启动不了的问题
我是安装了Hyper-V
它会保留很多端口段
改了它的占用段就可以了
