### ISSUE TITLE
4.1.3.1与shadowsocks-libev不兼容，无法连接。

### ISSUE THREAD

**Issue by superqinwei** [shadowsocks/shadowsocks-windows#2172]
shadowsocks 4.1.3.1
shadowsocks-libev 3.2.3

windows10 64bit 1809 
操作系统版本17763.253
.net frameworkd版本4.7.2
无法连接

**Comment by superqinwei** [comment]
[2019-01-23 14:45:16] System.ArgumentException: 参数“host”不能是空字符串。
   在 System.Net.DnsEndPoint..ctor(String host, Int32 port, AddressFamily addressFamily)
   在 Shadowsocks.Util.Sockets.SocketUtil.GetEndPoint(String host, Int32 port)
   在 Shadowsocks.Controller.TCPHandler.OnAddressFullyRead(IAsyncResult ar)
[2019-01-23 14:45:16] System.ArgumentException: 参数“host”不能是空字符串。
   在 System.Net.DnsEndPoint..ctor(String host, Int32 port, AddressFamily addressFamily)
   在 Shadowsocks.Util.Sockets.SocketUtil.GetEndPoint(String host, Int32 port)
   在 Shadowsocks.Controller.TCPHandler.OnAddressFullyRead(IAsyncResult ar)
[2019-01-23 14:45:16] connect to :45334
[2019-01-23 14:45:16] System.ArgumentException: 参数“host”不能是空字符串。
   在 System.Net.DnsEndPoint..ctor(String host, Int32 port, AddressFamily addressFamily)
   在 Shadowsocks.Util.Sockets.SocketUtil.GetEndPoint(String host, Int32 port)
   在 Shadowsocks.Controller.TCPHandler.OnAddressFullyRead(IAsyncResult ar)
[2019-01-23 14:45:16] connect to :50000
[2019-01-23 14:45:16] System.ArgumentException: 参数“host”不能是空字符串。
   在 System.Net.DnsEndPoint..ctor(String host, Int32 port, AddressFamily addressFamily)
   在 Shadowsocks.Util.Sockets.SocketUtil.GetEndPoint(String host, Int32 port)
   在 Shadowsocks.Controller.TCPHandler.OnAddressFullyRead(IAsyncResult ar)
[2019-01-23 14:45:16] connect to :50000
[2019-01-23 14:45:16] System.ArgumentException: 参数“host”不能是空字符串。
   在 System.Net.DnsEndPoint..ctor(String host, Int32 port, AddressFamily addressFamily)
   在 Shadowsocks.Util.Sockets.SocketUtil.GetEndPoint(String host, Int32 port)
   在 Shadowsocks.Controller.TCPHandler.OnAddressFullyRead(IAsyncResult ar)
[2019-01-23 14:45:16] connect to :50000
[2019-01-23 14:45:16] System.ArgumentException: 参数“host”不能是空字符串。
   在 System.Net.DnsEndPoint..ctor(String host, Int32 port, AddressFamily addressFamily)
   在 Shadowsocks.Util.Sockets.SocketUtil.GetEndPoint(String host, Int32 port)
   在 Shadowsocks.Controller.TCPHandler.OnAddressFullyRead(IAsyncResult ar)

**Comment by studentmain** [comment]
问题在客户端侧，socks代理没有收到有效的地址。有意思。

**Comment by chenshaoju** [comment]
请尝退出SS，删除或重命名 Shadowsocks.exe 所在目录下的 gui-config.json ，然后重新配置一次。

如果仍然不行，请检查你的服务器使用的是IP还是域名。

如果是域名，请尝试Ping你的域名，确保域名能解析IP。

如果是IP，请检查是否输入了正确的IP地址，使用的半角数字和英文句点。

**Comment by studentmain** [comment]
@superqinwei 用啥程序测试的。没几个网站开在50000端口。

**Comment by celeron533** [comment]
和 #1907 相关？

**Comment by studentmain** [comment]
@celeron533 不像，日志来看是本地socks5服务器没有收到对端地址。

**Comment by qwertccc** [comment]
跟我昨天的环境一模一样，我没问题

今天windows update了，.net也更了，也没问题

**Comment by superqinwei** [comment]
@studentmain 我最终重新down的4.1.3.1版本，没事了，但是实际原因，我没找到。

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/blob/8ce4b3b8967be1df0409a5992bb9746cbbb155c2/shadowsocks-csharp/Controller/Service/TCPRelay.cs#L441#L471
相关代码。
但由于已经无法重现了，先暂时忽略

**Comment by imebeh** [comment]
> https://github.com/shadowsocks/shadowsocks-windows/blob/8ce4b3b8967be1df0409a5992bb9746cbbb155c2/shadowsocks-csharp/Controller/Service/TCPRelay.cs#L441#L471
> 
> 相关代码。
> 
> 但由于已经无法重现了，先暂时忽略

找到重现方法了：
安装 Resilio Sync (原BTSync)，设置中使用ss-windows的socks5代理，
钩上“使用代理服务器用于主机名查询”时一定触发：`dstAddr==""`，可以看到`_connectionRecvBuffer[1]=0`
不懂网络这块不会修…

log里面布满了参数“host”不能是空字符串，发现的时候接近2G…
