### ISSUE TITLE
隐藏gui-config.json后使用PAC代理模式报错

### ISSUE THREAD

**Issue by httpe** [shadowsocks/shadowsocks-windows#2173]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

### Steps you have tried / 操作步骤
将gui-config.json设为隐藏文件
启动Shadowsocks
选择“启动系统代理”
选择“系统代理模式->PAC模式"

### What did you expect to see? / 期望的结果
开启PAC模式代理

### What did you see instead? / 实际结果
报错
![annotation 2019-01-23 195022](https://user-images.githubusercontent.com/2939218/51604683-7dc9e300-1f48-11e9-97c9-f38965f2fe2a.jpg)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
测试了一下，没有问题，请确保请确保只选中了隐藏，而没有选中只读。

![image](https://user-images.githubusercontent.com/515763/51608258-e8335100-1f51-11e9-92b8-9c4716a122b3.png)

**Comment by HenryLiangzy** [comment]
是不是因为ROE会把配置文件扫描所以才选择隐藏？

**Comment by httpe** [comment]
> 是不是因为ROE会把配置文件扫描所以才选择隐藏？

不……仅仅只是不想看到它所以选了隐藏，没想到出现了问题

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/blob/e7f33e3b9d22fca832eacf7f0fa17c28ca255640/shadowsocks-csharp/Model/Configuration.cs#L115
https://github.com/shadowsocks/shadowsocks-windows/blob/a79bc04ec56a71d2e9552e1a7df6f88e13f2ace2/shadowsocks-csharp/Util/SystemProxy/Sysproxy.cs#L227
https://github.com/shadowsocks/shadowsocks-windows/blob/8ce4b3b8967be1df0409a5992bb9746cbbb155c2/shadowsocks-csharp/Controller/FileManager.cs#L14
FileMode:
```
        // Summary:
        //     Specifies that the operating system should create a new file. If the file already
        //     exists, it will be overwritten. This requires System.Security.Permissions.FileIOPermissionAccess.Write
        //     permission. FileMode.Create is equivalent to requesting that if the file does
        //     not exist, use System.IO.FileMode.CreateNew; otherwise, use System.IO.FileMode.Truncate.
        //     If the file already exists but is a hidden file, an System.UnauthorizedAccessException
        //     exception is thrown.
        Create = 2,
```
```
        // Summary:
        //     Specifies that the operating system should open a file if it exists; otherwise,
        //     a new file should be created. If the file is opened with FileAccess.Read, System.Security.Permissions.FileIOPermissionAccess.Read
        //     permission is required. If the file access is FileAccess.Write, System.Security.Permissions.FileIOPermissionAccess.Write
        //     permission is required. If the file is opened with FileAccess.ReadWrite, both
        //     System.Security.Permissions.FileIOPermissionAccess.Read and System.Security.Permissions.FileIOPermissionAccess.Write
        //     permissions are required.
        OpenOrCreate = 4,
```

**Comment by celeron533** [comment]
please try this build:
https://ci.appveyor.com/project/celeron533/shadowsocks-windows-3j4p4/builds/21889776/job/4qn5yydmwjrlc6wo/artifacts

**Comment by celeron533** [comment]
@httpe  抱歉让你的服务器信息丢失 

先暂时不要隐藏文件，使用标准版ss
