### ISSUE TITLE
电脑连接Wifi无效，连接手机热点可以上，防火墙已关闭，求原因

### ISSUE THREAD

**Issue by euhiduwu** [shadowsocks/shadowsocks-windows#2174]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by euhiduwu** [comment]
手机连同一wifi也无法上，是什么原因

**Comment by chenshaoju** [comment]
电脑和WiFi都是同一个网络吗？如果是，这意味着你的WiFi所在的网络屏蔽了你的服务器。

**Comment by euhiduwu** [comment]
> 电脑和WiFi都是同一个网络吗？如果是，这意味着你的WiFi所在的网络屏蔽了你的服务器。
是同一wifi，之前这个wifi是可以的，这几天才上不去的，可以解决吗？和运行商有关？

**Comment by euhiduwu** [comment]
> 电脑和WiFi都是同一个网络吗？如果是，这意味着你的WiFi所在的网络屏蔽了你的服务器。

电脑和WiFi都是同一个网络吗？如果是，这意味着你的WiFi所在的网络屏蔽了你的服务器。
是同一wifi，之前这个wifi是可以的，这几天才上不去的，可以解决吗？和运行商有关？

**Comment by chenshaoju** [comment]
可能和你的运营商有关。

如果你的SS是自己搭的，换一个端口或者IP看看。

如果你的SS是找机场买的，请与你的机场服务商联系，换一个IP／域名或者端口看看。

**Comment by euhiduwu** [comment]
> 可能和你的运营商有关。
> 
> 如果你的SS是自己搭的，换一个端口或者IP看看。
> 
> 如果你的SS是找机场买的，请与你的机场服务商联系，换一个IP／域名或者端口看看。

好的，谢谢
