### ISSUE TITLE
服务器能打开的网站在代理后无法打开

### ISSUE THREAD

**Issue by roadwide** [shadowsocks/shadowsocks-windows#2176]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
本地环境：win10
服务器端环境：Ubuntu 16.04.2 LTS (GNU/Linux 4.20.3-042003-generic i686)
服务器使用HENET提供的ipv6隧道获得ipv6地址

### Steps you have tried / 操作步骤
本地使用代理并开启全局代理打开npupt.com和bt.byr.cn（只能ipv6访问的网站）
测试在服务器端可以打开上述两个网站

### What did you expect to see? / 期望的结果
由于本地没有ipv6地址所以希望能通过服务器的代理访问上述ipv6网站。

### What did you see instead? / 实际结果
能打开bt.byr.cn但不能打开npupt.com

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
配置文件如下
```
{
  "version": "4.1.3.1",
  "configs": [
    {
      "server": "************",
      "server_port": ************,
      "password": "************",
      "method": "aes-256-cfb",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "portableMode": true,
  "pacUrl": "https://raw.githubusercontent.com/gfwlist/tinylist/master/tinylist.txt",
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": true,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}
```
日志文件
```
[2019-01-24 16:46:34] Shadowsocks started (4.1.3.1)
[2019-01-24 16:46:34] 

Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
```

**Comment by chenshaoju** [comment]
我这儿也打不开 npupt.com ，测了一下，好像挂了。

![image](https://user-images.githubusercontent.com/515763/51673225-6fdb9700-2008-11e9-905f-8b0c3f74af8e.png)

**Comment by AnyWAT** [comment]
隔壁的Socks5:1080 白名单可以打开 https://npupt.com

**Comment by roadwide** [comment]
> 我这儿也打不开 npupt.com ，测了一下，好像挂了。
> 
> ![image](https://user-images.githubusercontent.com/515763/51673225-6fdb9700-2008-11e9-905f-8b0c3f74af8e.png)

没有挂，我在服务器上能正常访问。
我尝试用ssh的方式代理也能正常访问。
我的手机卡支持ipv6，也能访问。
![chrome](https://user-images.githubusercontent.com/15831531/51674691-59373f00-200c-11e9-8afc-1b22b791ecef.png)
![firefox](https://user-images.githubusercontent.com/15831531/51674686-550b2180-200c-11e9-8b81-1203f681a174.png)
上面是我在全局代理的情况下chrome和firefox访问的截图。
访问其他网站，例如谷歌没有问题。

**Comment by roadwide** [comment]
> 隔壁的Socks5:1080 白名单PAC可以打开 https://npupt.com

什么意思，我没太明白。使用socks5代理也打不开，PAC模式也打不开

**Comment by AnyWAT** [comment]
XX-Net 的X-Tunnel，不是 SS。等下试试 SS。。。

**Comment by roadwide** [comment]
我通过Bitvise SSH Client客户端ssh连接服务器，使用软件的代理服务可以正常访问npupt.com
![ssh 1](https://user-images.githubusercontent.com/15831531/51675373-7a992a80-200e-11e9-8b78-431a82299ea9.gif)
![ssh](https://user-images.githubusercontent.com/15831531/51675377-7bca5780-200e-11e9-962c-c8ec6f9d24f8.gif)

**Comment by roadwide** [comment]
> SS下：bt.byr.cn npupt.com 都不能打开，而隔壁的都能。

隔壁是什么。恕我愚昧。ss服务器必须支持ipv6才能打开

**Comment by AnyWAT** [comment]
> 隔壁是什么。

XX-Net 的X-Tunnel，不是 SS。

**Comment by roadwide** [comment]
已经解决。问题的原因是服务器是ipv6和ipv4双栈的，要访问的网站也是ipv6和ipv4双栈的。在ss代理的时候，优先使用了ipv4的地址，然而我要访问的那个网站近期是ipv4通道维护，虽然能ping到ip地址但实际不能访问。另一个能访问是因为它的服务器只有ipv6地址，在ss代理时不会用ipv4地址访问。
所以解决方法是将ss服务器改为ipv6优先即可
参考：[怎样设置才能实现ipv6优先 ](https://github.com/shadowsocks/shadowsocks-libev/issues/113)
