### ISSUE TITLE
确定配置无误的情况下，为什么日志显示decryption error？

### ISSUE THREAD

**Issue by Glacelabd** [shadowsocks/shadowsocks-windows#2177]
### Shadowsocks version / 影梭版本
4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
日志显示有出入站流量，但是decryption error。
同样的服务器配置和混淆在手机的SS客户端上确认可以使用。合租的基友也表示服务器没有问题。
怀疑网络或者路由器有问题，用手机开热点，电脑连接网络以后依旧显示decryption error。
和我一起使用的基友表示obfs-local应该也没有问题。

**Comment by chenshaoju** [comment]
你用的插件是什么插件？

**Comment by celeron533** [comment]
类似于 #2070 ?

**Comment by Glacelabd** [comment]
> 你用的是什么版本的obfs-local？
0.0.5的

**Comment by chenshaoju** [comment]
请确保你填写在了插件选项（不是插件参数）里，并且使用的obfs协议（http或tls）和服务器端一致。

如果仍然不行，请尝试一下这个第三方的simple-obfs：
https://github.com/imgk/simple-obfs-Cygwin/releases/tag/v0.0.5-20180713

**Comment by Glacelabd** [comment]
> 请确保你的obfs参数填写在了插件选项（不是插件参数）里，并且使用的obfs协议（http或tls）和服务器端一致。
> 
> 如果仍然不行，请尝试一下这个第三方的simple-obfs：
> https://github.com/imgk/simple-obfs-Cygwin/releases/tag/v0.0.5-20180713

我检查过，参数没有填错，服务器协议也确定一致，因为我在手机上使用同样的混淆使用是没有问题的。第三方的obfs使用了，但是依旧没能解决问题。
我借了朋友一个不需要混淆的服务器，可以正常使用，我觉得问题应该就是出在混淆上面了……

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
