### ISSUE TITLE
最新版4.1.3.1，今天打开，提示处理代理设置时发生错误，是否重置当前带里设置并重试？点是以后日志里面报错

### ISSUE THREAD

**Issue by Jonny-china** [shadowsocks/shadowsocks-windows#2178]
[2019-01-25 11:52:41] Shadowsocks started (4.1.3.1)
[2019-01-25 11:52:41] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-01-25 11:52:41] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

试过的这个方法，还是不行，[#2100(commit)](https://github.com/shadowsocks/shadowsocks-windows/issues/2100#issuecomment-445434934)

**Comment by studentmain** [comment]
首先呢，我再重复一遍，那个方法呢，其实就是4.1.3.1。

其次呢，看样子你可能要重装系统。

**Comment by Jonny-china** [comment]
重装系统完美解决！！！ (大坑，程序员环境装的烦。。。)
