### ISSUE TITLE
chrome无法通过shadowsocks联网

### ISSUE THREAD

**Issue by Lbaron980810** [shadowsocks/shadowsocks-windows#2183]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows10

### Steps you have tried / 操作步骤
双击图标（之前修改过电脑和网页网络设置）

### What did you expect to see? / 期望的结果
正常翻墙

### What did you see instead? / 实际结果
开启后无法翻墙，部分不需翻墙的网页（如github）打不开，开启正向代理后电脑会变得很卡）

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
这个我不太知道改填什么，求大神指点一下

**Comment by chenshaoju** [comment]
你需要购买第三方的SS服务或者自行搭建，然后填入对应的信息。

**Comment by Lbaron980810** [comment]
感谢您的回复～我已经购买了，也用了一年多了，前几天能用，就最近我在学校的最后几天和回家了就用不了了。你需要我提供什么具体的情况吗？我现在在外面，具体信息可能得晚点回复您

Chen Shaoju <notifications@github.com>于2019年2月1日 周五11:16写道：

**Comment by chenshaoju** [comment]
请访问 https://ipcheck.need.sh/ 测试一下你的服务器是否被墙了。

这种情况看起来很像你的服务到期了，请访问你的SS服务商查看到期时间。

**Comment by Lbaron980810** [comment]
国内和国外的ICMP和TCP显示的都是红叉，我刚才下了蓝灯发现是可以翻墙的。

**Comment by Lbaron980810** [comment]
我开着蓝灯用那个网址检查也都是红叉呀

**Comment by Lbaron980810** [comment]
我开着蓝灯用那个网址检查也都是红叉呀

**Comment by chenshaoju** [comment]
这意味着你的SS服务商的服务器挂了，请与你的SS服务商联系。

如果你打不开你的SS服务商的网站，说明该服务商跑路了。

**Comment by Lbaron980810** [comment]
可是和我合用一个账号的朋友可以正常使用啊

Chen Shaoju <notifications@github.com>于2019年2月1日 周五20:14写道：

**Comment by chenshaoju** [comment]
请访问你的SS服务商的网站，更换服务器看看。

**Comment by Lbaron980810** [comment]
好的

Chen Shaoju <notifications@github.com>于2019年2月1日 周五20:46写道：

**Comment by chenshaoju** [comment]
是，说明国内TCP连接不上，国外没问题。

**Comment by sixuerain** [comment]
vultr 搭建的ss 用不了了 有解决办法吗

**Comment by chenshaoju** [comment]
请尝试更换端口，如果仍然不行，可能需要换IP了。

**Comment by NAVrasZ** [comment]
@chenshaoju 问下shadowsocks-windows是不是不支持ipv6的localhost (::1)，SwitchyOmega里填::1显示代理有误，127.0.0.1正常

**Comment by chenshaoju** [comment]
我用 `netstat -ano -p tcpv6` 看了一下，没有绑定，似乎是只绑定在 127.0.0.1 上的。
