### ISSUE TITLE
一会能连上外网，一会连不上 ？好奇怪

### ISSUE THREAD

**Issue by zengquanli** [shadowsocks/shadowsocks-windows#2184]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
最新版
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10
### Steps you have tried / 操作步骤
PAC模式，全局模式都试了，一会能连上一会连不上
### What did you expect to see? / 期望的结果
一直可以正常上网

### What did you see instead? / 实际结果

一会能，连上，重启后可以连上，过一段时间又连接不上了。
#####  日志：
```
[2019-02-01 10:32:23] * timed out
[2019-02-01 10:32:23* timed out
[2019-02-01 10:32:23] connect to www.google.com:443
[2019-02-01 10:32:24] connect to www.google.com:443
[2019-02-01 10:32:24] connect to www.google.com:443
[2019-02-01 10:32:24] * timed out
[2019-02-01 10:32:24] connect to www.google.com:443
[2019-02-01 10:32:24] * timed out
[2019-02-01 10:32:24] connect to www.google.com:443

[2019-02-01 10:32:29]* timed out
[2019-02-01 10:32:29] connect to www.google.com:443
[2019-02-01 10:32:29] * timed out
[2019-02-01 10:32:34] * timed out
```
#####  配置信息：
```
{
  "version": "4.1.3.1",
  "configs": [
    {
      "server": "****",
      "server_port": 443,
      "password": "**",
      "method": "aes-256-cfb",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 10100,  // 修改了这个之后还是一会可以，一会不可以
  "portableMode": false,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": false,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": true,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}
```

**Comment by zengquanli** [comment]
现在可以连上，不知道大家有没有遇到这种请求，是不是  服务器不太稳定。。

**Comment by zengquanli** [comment]
另外有个问题：我主要是想登陆  https://developer.android.com/ 现在是 PAC模式登陆不了，但是可以用google登陆其他的网站，比如youtube，facebook。。但是登陆不了https://developer.android.com

**Comment by chenshaoju** [comment]
这意味着你的SS服务器可能不稳定，如果你是购买的SS机场服务，请与你的服务商联系。如果你是自己搭建的SS服务，请迁移到其他地区或者换一个地区的服务器重新搭建试试。

请尝试右击托盘区的纸飞机图标，选择PAC，再选择“从GFWList更新本地PAC”看看。

**Comment by zengquanli** [comment]
好的，我也去感觉是服务器不稳定

**Comment by zengquanli** [comment]
我每次在电脑上面重启一下还凑合能用，只是手机上面的用不了。

**Comment by chenshaoju** [comment]
请尝试Ping你的服务器的域名或者IP，丢包吗？

**Comment by zengquanli** [comment]
`PS C:\WINDOWS\system32> ping 89.208.246.211

正在 Ping 89.208.*** 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

****** 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，`

> 请尝试Ping你的服务器的域名或者IP，丢包吗？

`PS C:\WINDOWS\system32> ping 89.208.246.211

正在 Ping 89.208.*** 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

****** 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，`

**Comment by zengquanli** [comment]
``PS C:\WINDOWS\system32> ping 89.208.****

正在 Ping 89.208.*** 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

****** 的 Ping 统计信息:
数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，``

**Comment by zengquanli** [comment]
最近两天彻底凉凉了，丢包！

**Comment by zengquanli** [comment]
刚才又ping了一下，可以ping通我的地址，可是ping不同google，可以ping百度
```
PS C:\WINDOWS\system32> ping 89.2****

正在 Ping 89.2**** 具有 32 字节的数据:
来自 89.**** 的回复: 字节=32 时间=146ms TTL=46
来自 89******的回复: 字节=32 时间=145ms TTL=46
来自 89.***** 的回复: 字节=32 时间=146ms TTL=46
来自 89.*****的回复: 字节=32 时间=145ms TTL=46

****** 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 145ms，最长 = 146ms，平均 = 145ms
PS C:\WINDOWS\system32> ping www.google.com

正在 Ping www.google.com [59.24.3.173] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

59.24.3.173 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，
```

**Comment by zengquanli** [comment]
![1](https://user-images.githubusercontent.com/36160945/52531948-2acd9980-2d58-11e9-9096-0c5fd93f4b1c.JPG)
检测ip地址显示：国内的全部能联通，国外的有的能联通，有的联通不了

**Comment by zengquanli** [comment]
@chenshaoju

**Comment by zengquanli** [comment]
我又重新安装了服务器上面的系统，还是不行

**Comment by chenshaoju** [comment]
简而言之，你的IP被墙了（间歇性的），怎么折腾都没用的。

如果你的服务器是自己搭建的，换IP看看。如果是找机场购买的，请与你的机场联系换一个服务器。
