### ISSUE TITLE
服务器正常但无法代理

### ISSUE THREAD

**Issue by Clivexxxx** [shadowsocks/shadowsocks-windows#2186]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本

4.1.3.1
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

windows 10
### Steps you have tried / 操作步骤

PAC和全局模式都无法翻墙
[IP检测](https://ipcheck.need.sh/) 检测IP是否可用，均通过

### What did you expect to see? / 期望的结果

可以正常翻墙
### What did you see instead? / 实际结果
PAC和全局模式都无法翻墙

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
配置文件
```
{
  "version": "4.1.3.1",
  "configs": [
    {
      "server": "******",
      "server_port": ****,
      "password": "*************",
      "method": "aes-256-cfb",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    },
    {
      "server": "*********",
      "server_port": *****,
      "password": "*********8",
      "method": "aes-256-cfb",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": false,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "portableMode": true,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}
```
日志文件
貌似出现了两种报错信息
```
[2019-02-05 09:47:22] * timed out
[2019-02-05 09:47:27] * timed out
[2019-02-05 09:47:27] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-02-05 09:47:27] * timed out
[2019-02-05 09:47:27] * timed out


Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
```

**Comment by chenshaoju** [comment]
Time out 意味着超时，请确保你配置的服务器IP和端口配置正确。

如果是域名，请确保你的域名正确的指向了你的服务器IP。

另外，请Ping你的服务器，延迟有多少？

**Comment by wdilb** [comment]
和其他几个朋友同样出现了这个问题，服务器肯定能访问，我还登陆上去改了几次配置和加密方式，ping的延迟在100ms左右，不知道是不是和我们服务器都租的搬瓦工有关系…

**Comment by nothinggift** [comment]
完全相同的情况，自己搭建的服务器，稳定使用了快两年，在昨天突然不能使用了，所有的终端都是如此，很自然判断是服务器问题，但服务器一切正常，重启，重新搭建都解决不了，最后修改服务器端口后，就恢复正常了，另外我们一开始就没用默认的服务器端口。

**Comment by peiqixin** [comment]
情况好像都一样，也是修改了下服务器端口就可以连了，感谢。

**Comment by a1bum** [comment]
我的修改了服务器端ip还是不行，用网上免费的也不行，

**Comment by wishprophet** [comment]
> 我的修改了服务器端ip还是不行，用网上免费的也不行，

我也这样了 可以ping通 端口也换了 ip也没被ban 电脑手机都上不了

**Comment by Sea-Monster** [comment]
> 完全相同的情况，自己搭建的服务器，稳定使用了快两年，在昨天突然不能使用了，所有的终端都是如此，很自然判断是服务器问题，但服务器一切正常，重启，重新搭建都解决不了，最后修改服务器端口后，就恢复正常了，另外我们一开始就没用默认的服务器端口。

一模一样的状况，按照你所说的还真解决了

**Comment by xuedongliu** [comment]
我昨天也是，换了端口就能用。。之前用的端口就不行。服务器搬瓦工

**Comment by voldikss** [comment]
我也是，DO服务器，可以 ssh，但是无法 fq

**Comment by zimocode** [comment]
> 和其他几个朋友同样出现了这个问题，服务器肯定能访问，我还登陆上去改了几次配置和加密方式，ping的延迟在100ms左右，不知道是不是和我们服务器都租的搬瓦工有关系…
> 
> 刚才又上去修改了一下服务器的端口就可以正常使用了 不知道是为什么

请问用的啥端口？

**Comment by caihindy** [comment]
我的情况也是如此。现在ss用的是server port 443,请问改成什么可以翻墙?

ps:搞笑的是，我在电脑上先打开商用vpn软件连接上，但是速度超慢，然后同时连接ss(server port 443)，结果ss是能用而且速度很好。

**Comment by voldikss** [comment]
你试试随便换一个其他的端口 @caihindy 不知道会不会管用，我最开始是8388，改成8389正常了

**Comment by caihindy** [comment]
> 你试试随便换一个其他的端口 @caihindy 不知道会不会管用，我最开始是8388，改成8389正常了

万分感谢。我把原来的server port从443改成6000，现在正常了。

**Comment by wishprophet** [comment]
> > 你试试随便换一个其他的端口 @caihindy 不知道会不会管用，我最开始是8388，改成8389正常了
> 
> 万分感谢。我把原来的server port从443改成6000，现在正常了。

哇 6000 很关键 有用了 没有改本地端口，之前443 444 445 都不行 就没试大的

**Comment by shawnyue** [comment]
之前ss不能连接，kcptun却可以。
然后改了server_port就好了，有人能解释一下原因吗

**Comment by celeron533** [comment]
1. 初犯封端口。能ping通（ICMP协议）换端口一般可解。
2. 再犯TCP阻断。能ping通，换端口无解。UDP协议和ICMP协议都能用。
3. 屡犯封IP。凉。

**Comment by Sea-Monster** [comment]
> 1. 初犯封端口。能ping通（ICMP协议）换端口一般可解。
> 2. 再犯TCP阻断。能ping通，换端口无解。UDP协议和ICMP协议都能用。
> 3. 屡犯封IP。凉。

什么初犯屡犯？ 指的是什么呢？

**Comment by celeron533** [comment]
>什么初犯屡犯

@Sea-Monster @AnyWAT 指的是被防火墙探测出来

**Comment by xylsjz** [comment]
> 什么初犯屡犯
> 
> @Sea-Monster @AnyWAT 指的是被防火墙探测出来
然后IP被封么

**Comment by Sea-Monster** [comment]
> > 什么初犯屡犯
> 
> @Sea-Monster @AnyWAT 指的是被防火墙探测出来

请问指的是服务端吗？那是不是说只能更换服务器了？

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history
