### ISSUE TITLE
想问release下载的只是单exe不是安装程序，客户端应该是哪一个啊？

### ISSUE THREAD

**Issue by cyk9944** [shadowsocks/shadowsocks-windows#2187]
https://github.com/shadowsocks/ShadowsocksX-NG/releases/    比如mac上应该是通过dmg安装程序，但这里下载直接打开就一个1.8.2版本的25m的应用程序，

win下https://github.com/shadowsocks/shadowsocks-windows/releases 也应该是一个安装程序，但这也只是个4.1.4的exe单文件， 

电脑上客户端实际安装程序该怎么下载啊？不好意思懵逼了，以前我记得下载是个完整的应用程序进行安装的。。。然后今天vultr 日本机房上不去了，ping通的，有大神知道该怎么办吗

**Comment by studentmain** [comment]
作为一个大小不过两张软盘的windows小程序，让它能够直接运行显然更简单也更加方便使用，于是就没做安装包。因此就不存在“应该是个安装包”的说法。以前没有，现在没有，以后如果没有一大群人提议，估计也不会有，你不能下载一个根本没写出来的程序。

你下载下来那个exe可以直接跑。但是如果非要一个能安装的，可以试试（画风完全不一样但是协议兼容的）outline-client。

**Comment by cyk9944** [comment]
> 作为一个大小不过两张软盘的windows小程序，让它能够直接运行显然更简单也更加方便使用，于是就没做安装包。因此就不存在“应该是个安装包”的说法。以前没有，现在没有，以后如果没有一大群人提议，估计也不会有，你不能下载一个根本没写出来的程序。
> 
> 你下载下来那个exe可以直接跑。但是如果非要一个能安装的，可以试试（画风完全不一样但是协议兼容的）outline-client。

明白啦，感谢！这样更方便！
