### ISSUE TITLE
同样的配置在一个wifi下能连上，在另一个wifi下不行。防火墙已关闭

### ISSUE THREAD

**Issue by indianmifan** [shadowsocks/shadowsocks-windows#2188]
### Shadowsocks version / 影梭版本
  服务器：ubuntu  3.0.0的ss      客户端windows10      4.1.3.1ss

在一个wifi环境下ss可以正常连接，
换了一个wifi就连不上
一直报这样的错误↓
[2019-02-06 23:31:10] connect to p35-buy.itunes.apple.com:443
[2019-02-06 23:31:10] System.Net.Sockets.SocketException (0x80004005): 向一个无法连接的网络尝试了一个套接字操作。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by indianmifan** [comment]
还有 我在腾讯云上租的一台vps  使用相同的ss配置 也没有办法成功连接

**Comment by chenshaoju** [comment]
１.如果你配置的是域名，请在有问题的WiFi下Ping你的域名，确保你的IP地址是正确的。
如果不正确，可在第三方网站上查询域名对应的IP，然后将服务器地址修改为IP看看：
https://ping.chinaz.com 或 https://www.ip.cn

２.不建议使用国内的云服务，你懂的。
https://github.com/shadowsocks/shadowsocks/issues/1180

**Comment by indianmifan** [comment]
> １.如果你配置的是域名，请在有问题的WiFi下Ping你的域名，确保你的IP地址是正确的。
> 如果不正确，可在第三方网站上查询域名对应的IP，然后将服务器地址修改为IP看看：
> https://ping.chinaz.com 或 https://www.ip.cn
> 
> ２.不建议使用国内的云服务，你懂的。
> [shadowsocks/shadowsocks#1180](https://github.com/shadowsocks/shadowsocks/issues/1180)

没有配域名，用的是vultr加州的节点，今天又试了一下  用手机开热点，联通的卡开的热点能连上，电信开的热点连不上，两张卡信号均没问题。。。有一点玄学了。。。

**Comment by chenshaoju** [comment]
请在有问题的WiFi下Ping你的IP，能通吗？

**Comment by indianmifan** [comment]
> 请在有问题的WiFi下Ping你的IP，能通吗？

能，我搭了两台vps，一个东京节点一个加州节点，都是一样的情况。。突然想起来会不会是跟我搭的梯子支持ipv6有关系.....

**Comment by indianmifan** [comment]
> 请在有问题的WiFi下Ping你的IP，能通吗？


服务器的配置是下面这样
{
    "server":"::",
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"mypassword",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": false
}





客户端配置的时候ip填的是服务器的ipv6地址（填ipv4地址连不上，这点跟教程里不一样 不知道是为什么）

**Comment by celeron533** [comment]
重启wifi ap或者路由器。我遇到过类似情况，发现廉价的（非企业级）的无线网关在长时间运行后真的会发生部分链路无法连接的情况。

**Comment by neveroldmilk** [comment]
vultr的ip早就上黑名单了，部分区域无法访问很正常。ipv6的话要这样设置监听端口：
 "server":["[::0]", "0.0.0.0"]

**Comment by indianmifan** [comment]
> vultr的ip早就上黑名单了，部分区域无法访问很正常。ipv6的话要这样设置监听端口：
> "server":["[::0]", "0.0.0.0"]

可是ping的通欸。。。监听这样设的话开启服务时会报错。。

**Comment by indianmifan** [comment]
> 重启wifi ap或者路由器。我遇到过类似情况，发现廉价的（非企业级）的无线网关在长时间运行后真的会发生部分链路无法连接的情况。

可能确实是路由器的问题。。。不是很懂为什么会这样
