### ISSUE TITLE
Bug: 全局模式下, 不退出软件, 直接重启电脑会导致开机无法正常上网. 需重新打开Shadowsocks才能解决.

### ISSUE THREAD

**Issue by LegendarYi** [shadowsocks/shadowsocks-windows#2189]
以下是Google Chrome浏览器报错:

No internet There is something wrong with the proxy server, or the address is incorrect.
Try:

Contacting the system admin
Checking the proxy address
Running Windows Network Diagnostics
ERR_PROXY_CONNECTION_FAILED
If you use a proxy server…
Check your proxy settings or contact your network administrator to make sure the proxy server is working. If you don't believe you should be using a proxy server: Go to the Chrome menu > Settings > Show advanced settings… > Change proxy settings… > LAN Settings and deselect "Use a proxy server for your LAN".

**Comment by studentmain** [comment]
滚更新

**Comment by LegendarYi** [comment]
> 滚更新
![image](https://user-images.githubusercontent.com/22711162/52354904-41c86f00-2a6c-11e9-8bcd-2049883cd964.png)

Win8

**Comment by studentmain** [comment]
啊……其实这早就是已知bug了，不过因为修起来动静太大了，一直没修。

4.1.4有点缓解措施：如果正在运行时系统重启了，ss会在重启后恢复运行，不过看样子只在win10上面有效。

**Comment by LegendarYi** [comment]
> 啊……其实这早就是已知bug了，不过因为修起来动静太大了，一直没修。
> 
> 4.1.4有点缓解措施：如果正在运行时系统重启了，ss会在重启后恢复运行，不过看样子只在win10上面有效。

了解, 谢谢你!
