### ISSUE TITLE
每次开启SS都有这个提示 “处理代理设置时发生错误，是否重置当前代理设置并重试？"

### ISSUE THREAD

**Issue by chaojoy** [shadowsocks/shadowsocks-windows#2191]
系统是Win10 1809，虽然不影响使用，但每次打开或切换设置都有这个提示，一直没找到原因
![screenshot_20190208153833](https://user-images.githubusercontent.com/37964882/52465255-e788f480-2bb8-11e9-973f-1dcadd3be866.png)

**Comment by studentmain** [comment]
日志

**Comment by chaojoy** [comment]
> 日志

sysproxy - SysproxyExitError:Error query options: 12178 (null)

**Comment by chaojoy** [comment]
系统代理也不能设置

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718

**Comment by chaojoy** [comment]
看了NET4.7框架是安装了的，重新解压新文件夹和管理员启动还是有这个问题。

**Comment by studentmain** [comment]
原厂镜像重装

**Comment by chaojoy** [comment]
升级到预览版就没问题了
![screenshot_20190208214221](https://user-images.githubusercontent.com/37964882/52485288-7adf1b80-2bf3-11e9-9575-5caa91355b80.png)

**Comment by caochikai** [comment]
[2019-02-12 23:16:02] Shadowsocks started (4.1.4)
[2019-02-12 23:16:02] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-02-12 23:16:03] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-02-12 23:16:07] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

**Comment by caochikai** [comment]
[2019-02-12 23:16:02] Shadowsocks started (4.1.4)
[2019-02-12 23:16:02] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-02-12 23:16:03] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-02-12 23:16:07] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

**Comment by fujungit** [comment]
我跟你一样啊,除了升级系统,怎么解决  我用的是win7*64

**Comment by chenshaoju** [comment]
请检查该服务是否启动了：
![image](https://user-images.githubusercontent.com/515763/60397916-d1d69480-9b84-11e9-8cc2-7d1b7a32e295.png)

**Comment by fujungit** [comment]
这个服务已经是开了的😥

Chen Shaoju <notifications@github.com> 于2019年6月30日周日 下午10:19写道：

**Comment by chenshaoju** [comment]
请看一下SS的日志，具体的错误代码是……？

**Comment by MichaelBananaBaBa** [comment]
我的也是这样 一打开就消失处理代理设置时发生错误是否重置当前代理并重试。实在是不想重装系统了，一个月前重装过，因为自己是做音乐的一些软件也还要重装，重装之后确实能用了，可是过不多久，又会这样。我好不容易装完了我其他软件他又不能用了，再重装真的是折腾死人了 有人能帮忙解决这个问题么

**Comment by chenshaoju** [comment]
日志中有任何提示吗？

**Comment by MichaelBananaBaBa** [comment]
我一會兒會兒把日誌發上來
