### ISSUE TITLE
Win7正常，Win10不能科学上网

### ISSUE THREAD

**Issue by 847086434** [shadowsocks/shadowsocks-windows#2192]
版本Shadowsocks-4.1.4，不知道是不是Win10那台电脑连的是Wifi原因。。打开软件提示“处理代理设置时发生错误...”，而且重置代理失败，以管理员权限打开的。

```
[2019-02-08 16:16:36] Shadowsocks started (4.1.4)
[2019-02-08 16:16:36] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-02-08 16:16:36] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-02-08 16:16:37] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)
```

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718

**Comment by 847086434** [comment]
不行，删除同文件夹下的`user-wininet.json，或者另用一个Shadowsocks.exe也是这样的

**Comment by 847086434** [comment]
> [#1185 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718)



> [#1185 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/1185#issuecomment-308097718)

不行，删除同文件夹下的`user-wininet.json，或者另用一个Shadowsocks.exe也是这样的

**Comment by chaojoy** [comment]
看来不是只有我遇到这个问题，哪怕手动去设置系统代理也不行，点确定后关掉再打开还是一片空白，不知道是否是1809这个系统版本的安全机制引起的
![screenshot_20190208192944](https://user-images.githubusercontent.com/37964882/52475986-32fecb00-2bd8-11e9-8d61-c5f477e352f3.png)

**Comment by celeron533** [comment]
可能某些安全助手、反病毒软件或者游戏反作弊系统会限制修改系统代理

**Comment by 847086434** [comment]
@chaojoy 
win10配合SwitchyOmega可以用，先用Shadowsocks配置好(启用系统代理，PAC模式)，有错误不用管他（提示“处理代理设置时发生错误...”）。然后装SwitchyOmega插件(我用的是谷歌浏览器)，新建情景模式(原本有两个情景模式的可以删除)，选择代理服务器，将代理服务器配置成SOCKS5 | 127.0.0.1 | 1080，然后【应用选项】（在左手边栏目倒数第二个），然后需要翻墙时就切换到那个情景模式就可以了

**Comment by abincai** [comment]
遇到一模一样的问题。新年才遇到的

**Comment by 847086434** [comment]
@abincai 
其实主要原因是win10那台电脑忘记在浏览器设置代理了，只开了Shadowsocks小飞机。。。
装个SwitchyOmega吧，挺好用的，设置好GFW会自动切换，感觉小飞机的PAC不好使。。

**Comment by abincai** [comment]
只能暂时这么用着了。
