### ISSUE TITLE
有种被针对的感觉

### ISSUE THREAD

**Issue by crurui** [shadowsocks/shadowsocks-windows#2193]
win10用酸酸，平时能ping通（连续10次丢一个包那种）
但只要用ss一开始连，比如打开一个google标签页，马上就ping不通，同时22端口也连不上
过一段时间又能ping通了，至少来回试了七八次都是这样
全程在国内的其他测试端口的网点都没问题，显示端口“开”
前几天把加密从aes256gcm改成cfb，能用了
今天又不行了，一样的问题，简单地改端口也不行。请问这种情况应该怎么办啊，谢谢！

**Comment by aweffr** [comment]
是的，有种被精确检测到的感觉

**Comment by chenshaoju** [comment]
请尝试套一个 Simple-obfs 或者 GoQuite 试试。

**Comment by chenshaoju** [comment]
请尝试套一个 Simple-obfs 或者 GoQuite 试试。

**Comment by crurui** [comment]
> 请尝试套一个 Simple-obfs 或者 GoQuite 试试。

Simple-obfs tls可以了……好神奇
十分感谢您！我再观察几天……
问个外行问题，请问是在插件选项用了插件肯定要通过它吗？

**Comment by qwertccc** [comment]
楼主哪里的网络？我这儿就原版没加插件，xchacha20-ietf-poly1305加密反正一直用着还行，不知道会不会有一天也得上个obfs插件

**Comment by crurui** [comment]
> 楼主哪里的网络？我这儿就原版没加插件，xchacha20-ietf-poly1305加密反正一直用着还行，不知道会不会有一天也得上个obfs插件

连同……

**Comment by zengquanli** [comment]
我前几天时不时打不开，然后过年了，没有登陆外网，今天回来一测，完全打不开了。

**Comment by zengquanli** [comment]
请问一下，怎么加你们说的这些插件

**Comment by cstmdzx** [comment]
> 请问一下，怎么加你们说的这些插件

同问，现在谷歌用不了啥都查不到了

**Comment by chenshaoju** [comment]
Simple-obfs: https://github.com/shadowsocks/simple-obfs-android/releases
GoQuite: https://github.com/cbeuw/GoQuiet/releases

**Comment by kainiu** [comment]
同楼主的情况
宽带：北京鹏博士
obfs还没调通。。TAT

**Comment by chenshaoju** [comment]
请尝试使用第三方的服务测试你的服务器：
https://ipcheck.need.sh/

**Comment by NicoKam** [comment]
xchacha20-ietf-poly1305方式确实可以，感觉有点不可思议，这么多加密算法都给破掉了么？还是有什么其他的特征被捕获了

**Comment by Var-iazioni** [comment]
vultr洛杉矶机房也遇到这种问题了。。
之前端口还被ban过一次。
现在换了gcp。。希望能用久一点。。

**Comment by w5423709** [comment]
啊 我也是这周开始这样了 气死了 一开始是前两周端口被封了 现在换端口就变成一连就整个IP都PING不通了 但是就只有我的电脑PING不通 其他主机都PING得通 服务器PING我的IP也是不通 应该是被针对了 真的好恶心
