### ISSUE TITLE
编辑本地pac文件时 不能打开pac目录，只打开win10库目录

### ISSUE THREAD

**Issue by snsnsjsn** [shadowsocks/shadowsocks-windows#2194]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
shadowsocks 4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 64

### Steps you have tried / 操作步骤

![image](https://user-images.githubusercontent.com/11435527/52522232-53ed1c00-2cbd-11e9-9e96-c50dc51d82c2.png)

![image](https://user-images.githubusercontent.com/11435527/52522201-f9ec5680-2cbc-11e9-86b0-91920c484940.png)

### What did you expect to see? / 期望的结果

shadowsocks不能在pac模式下运行，要么是全局代理，要么没有代理，很痛苦，以前能打开的，现在不知道为啥打不开了。退回老版本也是不能点击编辑本地pac文件，打开pac所在目录，应该是windows系统哪个软件修改了explorer的属性，2014年之前国外也有人遇到这个问题，他也安装了qttabbar，我也安装了，但是之前我使用是没有问题的，应该不是qbtabbar问题。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by celeron533** [comment]
检查ss所在的文件夹权限。

**Comment by snsnsjsn** [comment]
应该不是权限问题，我用管理员运行也是打不开pac目录。
应该是系统的某个属性被某个软件劫持或者被修改了。但是不知道怎么描述这个属性，不然google下也能找到解决方案

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 调用 Explorer.exe 打开目录：
https://github.com/shadowsocks/shadowsocks-windows/blob/f75ffc06fccac8292817763460f016f670a32465/shadowsocks-csharp/View/MenuViewController.cs#L345

请检查你的系统是否存在镜像劫持或者某些DLL HOOK改变了行为方式。

**Comment by snsnsjsn** [comment]
我是从github release下载的zip版本，系统没有你说这个文件啊？
![image](https://user-images.githubusercontent.com/11435527/52930500-a4cad780-3383-11e9-836c-2278f4ddce50.png)

**Comment by chenshaoju** [comment]
![9f8e99d37c0c77d9fb5626d89ff8f26f](https://user-images.githubusercontent.com/515763/52931045-de044700-3385-11e9-8288-1861ddb85759.jpg)

![image](https://user-images.githubusercontent.com/515763/52931052-e2c8fb00-3385-11e9-8035-b31e01879b61.png)

**Comment by snsnsjsn** [comment]
我不是要自己修改源码，我只会用已经编译好的可执行文件。
我下载windows版本zip包里面只有一个 shadowscosks.exe 执行文件啊。
![image](https://user-images.githubusercontent.com/11435527/52931650-16a52000-3388-11e9-9ad7-08a5be08a125.png)


运行后结果就大概生成这些目录文件。

![image](https://user-images.githubusercontent.com/11435527/52931674-291f5980-3388-11e9-88aa-ecfe834af087.png)

现在问题就是不像以前，从已经运行的 shadowscks 图标右键编辑本地pac文件，打不开pac的目录。
导致现在pac文件都没有调用，好像要么全局，要么是使用了几个默认的网站google.com youtube.com之类。
没法再调用自己的本地pac文件以pac模式访问自定义的网址。

**Comment by snsnsjsn** [comment]
刚下载了4.1.4版本，也是一样的问题，运行后都不能自动生成pac文件
，但是pac模式下访问google是美哟问题的。

**Comment by chenshaoju** [comment]
请做个测试，在运行中执行：
```
cmd /c explorer.exe D:\xxxx\xxx\xxx
```
请将 D:\xxxx\xxx\xxx 替换成你的 PAC 所在的目录，能否打开？

**Comment by snsnsjsn** [comment]
可以打开，没有问题，难道真是我的explorer 多标签插件qttabbar导致的？？我记得以前右键能打开pac目录的。

**Comment by chenshaoju** [comment]
你可能得试一下了，从目前提供的情况来看，就是由于 Shadowsocks.exe 调用 explorer.exe 打开目录时的参数被拦截了，导致行为变得和直接打开 explorer.exe 一样。

你可以尝试在运行里直接执行 `explorer.exe` ，也是打开我的文档或者库文件，这就是不带参数的行为。

**Comment by snsnsjsn** [comment]
是的，explorer默认行为打开库.

能调用pac文件就ok了，大不了每次从vim的MRU里面进入，或者通过listary快速查找，再编辑。

我不纠结这个问题了。

**Comment by Sh1noka** [comment]
我从刚开始用就有你说的这个问题，我也用的 QTTabbar。

SS 菜单选项效果是：

- 当文件浏览器窗口已经打开时，在最后打开的窗口中出现新的选项卡，路径是库，没有文件选定，并不会出现新的窗口。
- 若文件浏览器窗口中已经有路径为库的选项卡，该选项卡变成激活状态，并不会出现新的选项卡。
- 若文件浏览器窗口是最小化的，会先还原。

运行下面命令效果都是出现新的文件浏览器窗口，窗口中只有一个选项卡，路径是 ss 目录，该文件是选定的。

```cmd
C:\
λ cmd /c explorer.exe /select, "D:\PortableApps\Shadowsocks\pac.txt"

C:\
λ explorer.exe /select, "D:\PortableApps\Shadowsocks\pac.txt"

D:\PortableApps\Shadowsocks
λ explorer.exe /select, pac.txt
```

**Comment by celeron533** [comment]
@Sh1noka Current implementation is as same as point 2 you've mentioned:
https://github.com/shadowsocks/shadowsocks-windows/blob/f75ffc06fccac8292817763460f016f670a32465/shadowsocks-csharp/View/MenuViewController.cs#L390

**Comment by snsnsjsn** [comment]
> 我从刚开始用就有你说的这个问题，我也用的 QTTabbar。
> 
> SS 菜单选项效果是：
> 
> * 当文件浏览器窗口已经打开时，在最后打开的窗口中出现新的选项卡，路径是库，没有文件选定，并不会出现新的窗口。
> * 若文件浏览器窗口中已经有路径为库的选项卡，该选项卡变成激活状态，并不会出现新的选项卡。
> * 若文件浏览器窗口是最小化的，会先还原。
> 
> 运行下面命令效果都是出现新的文件浏览器窗口，窗口中只有一个选项卡，路径是 ss 目录，该文件是选定的。
> 
> ```batchfile
> C:\
> λ cmd /c explorer.exe /select, "D:\PortableApps\Shadowsocks\pac.txt"
> 
> C:\
> λ explorer.exe /select, "D:\PortableApps\Shadowsocks\pac.txt"
> 
> D:\PortableApps\Shadowsocks
> λ explorer.exe /select, pac.txt
> ```

你说这些命令运行都没有问题。

奇怪的是今天居然好了，我到服务里面把不用的服务关闭了，然后到任务计划里面把所有计划禁用，结果nvida 940M显卡驱动也禁用了，然后使用 nVidia GeForce exprience 下载最新的显卡驱动安装重启。

nVidia显卡菜单显示在桌面右键下面了。
然后右键shadowsocks的编辑pac文件，居然成功打开了，而且我是放置在中文目录都没有问题的





![dddd](https://user-images.githubusercontent.com/11435527/53234296-314e0080-36ca-11e9-92ef-afd4d18d67ea.png)


但是又有个新问题，那就是pac模式经常抽风，google搜索pac模式打不开，全局后立马打开。
好像现在pac模式失效。偶尔。

**Comment by chenshaoju** [comment]
失效的时候请检查一下IE的代理蛇代理设置（如果你没有使用拨号连接的话），PAC是否存在。
![image](https://user-images.githubusercontent.com/515763/53236998-999fe080-36d0-11e9-9a32-38f2756a3b64.png)

我使用的是10800端口，请忽略。
