### ISSUE TITLE
希望增加功能:允许局域网中无网络的设备通过连接Shadowsocks服务器正常上网(无论是否用代理)

### ISSUE THREAD

**Issue by huangjinshe** [shadowsocks/shadowsocks-windows#2195]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 . .Net 4.6

### Steps you have tried / 操作步骤
通过手机或者局域网中没有网络的设备通过代理地址或者PAC地址访问服务器中的Shadowsocks, 并通过服务器中的网络上网.

### What did you expect to see? / 期望的结果
Shadowsocks只能做代理, 不能分享服务器本身的本地网络资源给用户. 这样以来又只能下载一些代理软件跳转.

### What did you see instead? / 实际结果
希望增加一个选项:使用服务器网络来上网.  这样以来无论用任何一个没有网络的局域网中的电脑或者手机, 都可以直接通过装Shadowsocks那台电脑来访问网络(无论是否用到代理), 其实类似一种二级代理.  这样以来 局域网中的电脑或者手机可以使用Shadowsocks那台服务器的网络资源来上网. 如果没用Shadowsocks代理看, 则直接通过服务器的网络正常上网, 如果Shadowsocks有使用代理, 则通过装Shadowsocks的网络--->再使用代理--->再上网.
假如用的是PAC模式, 则只需要返回PAC时把:return direct; 替换为:return http://装Shadowsocks服务器的电脑IP:1080   即可.
有些朋友说你直接下载一个代理软件不就行了吗?  但是如果Shadowsocks集成了这个功能, 真的可能更是强大一些, 再说确实这个功能对很多人有用, 可以提高该软件是使用率.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by studentmain** [comment]
右键，允许局域网设备访问

**Comment by huangjinshe** [comment]
> 右键，允许局域网设备访问

你可能没理解我要表达的意思, 我要一个不能上网的设备通过安装Shadowsocks的服务器网络来上网, 而不用代理.

**Comment by huangjinshe** [comment]
咱可以在[便携模式]旁边新增[局域网用服务器网络]选项, 并实现该功能也行.

**Comment by celeron533** [comment]
>通过安装Shadowsocks的服务器网络来上网

你需要的是网关或者是代理服务器。

**Comment by huangjinshe** [comment]
@celeron533 虽然如此, 但是Shadowsocks不就是做了一个代理服务器吗? (只是没把资源从自己的网络, 而是做了一次二次跳转再转回局域网). 我感觉实现起来应该不会太困难.

**Comment by chenshaoju** [comment]
如果你对TCP/IP协议族了解的话，Shadowsocks for Windows 工作在传输层，负责处理TCP/UDP数据包，而不负责路由。

你的需求需要工作在网络层（负责IP路由等），也许你需要考虑购买一个支持梅林固件的路由器，并在路由器中部署SS。
