### ISSUE TITLE
打开时提示错误

### ISSUE THREAD

**Issue by zxj930057911** [shadowsocks/shadowsocks-windows#2197]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by zxj930057911** [comment]
![_20190210115728](https://user-images.githubusercontent.com/11910130/52529384-c4cb1d00-2d2b-11e9-9d03-30c59b66f317.png)

**Comment by zxj930057911** [comment]
win10 1809，ssS是4.1.4

**Comment by chenshaoju** [comment]
你是否使用了插件？或者，你是否是直接从其他人那里复制过来的？

请检查你的插件配置，确保你你的插件路径存在。

**Comment by zxj930057911** [comment]
谢谢你，速度好快，我直接从网址扫描二维码.冒昧问一下，插件从哪里下载。。。我知道安卓版好像两个都在谷歌商店

**Comment by chenshaoju** [comment]
Simple-obfs: https://github.com/shadowsocks/simple-obfs-android/releases
GoQuite: https://github.com/cbeuw/GoQuiet-android/releases

**Comment by zxj930057911** [comment]
谢谢你了，哈哈新年快乐
