### ISSUE TITLE
登不上去了

### ISSUE THREAD

**Issue by sinolulu** [shadowsocks/shadowsocks-windows#2199]
无法访问此网站 www.google.com 意外终止了连接。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_CLOSED
---------------------------------------
用了大半年，今天突然就上不了了，GOOGLE/YOUTUBE都打不开，版本是4.1.1.0

**Comment by chenshaoju** [comment]
请使用第三方服务测试你的服务器的连通性：
https://ipcheck.need.sh/

如果不通，若是自己搭建的服务器，请尝试更换端口，如果仍然不行，请尝试联系VPS服务商更换IP。

如果是你找机场购买的SS服务，请与你的SS服务商联系。

**Comment by chengshaohui** [comment]
我的问题和你一样   我的服务器都通 但还是访问不了

**Comment by chenshaoju** [comment]
请提供SS客户端的日志，记得隐藏你的服务器IP和端口。

**Comment by chengshaohui** [comment]
我觉得是服务器端口的问题  我的问题和你一样  我换了一个端口就好了

**Comment by sinolulu** [comment]
> 我觉得是服务器端口的问题 我的问题和你一样 我换了一个端口就好了

怎么换端口？我原来服务器端口28548，换哪个比较好

**Comment by chenshaoju** [comment]
比如换成443，如果你用的是一件脚本，应该有一个过程是让你输入端口的。

如果你是自己搭的，请检查 /etc/shadowsocks-libev/config.json 文件。

**Comment by sinolulu** [comment]
> 比如换成443，如果你用的是一件脚本，应该有一个过程是让你输入端口的。
> 
> 如果你是自己搭的，请检查 /etc/shadowsocks-libev/config.json 文件。

检查文件如下，还是不会弄：

{
  "Calculations": {
    "AverageLatency": 0.0,
    "MinLatency": 0.0,
    "MaxLatency": 0.0,
    "AverageInboundSpeed": 0.0,
    "MinInboundSpeed": 0.0,
    "MaxInboundSpeed": 0.0,
    "AverageOutboundSpeed": 0.0,
    "MinOutboundSpeed": 0.0,
    "MaxOutboundSpeed": 0.0,
    "AverageResponse": 0.0,
    "MinResponse": 0.0,
    "MaxResponse": 0.0,
    "PackageLoss": 0.0
  },
  "StatisticsEnabled": false,
  "ByHourOfDay": true,
  "Ping": false,
  "ChoiceKeptMinutes": 10,
  "DataCollectionMinutes": 10,
  "RepeatTimesNum": 4
}

**Comment by chenshaoju** [comment]
你这个文件是那里的？不是服务器上的把？应该类似这样：

https://github.com/shadowsocks/shadowsocks-windows/issues/2217#issuecomment-464413579

**Comment by sinolulu** [comment]
> 你这个文件是那里的？不是服务器上的把？应该类似这样：
> 
> [#2217 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2217#issuecomment-464413579)

就是电脑硬盘文件目录下的statistics-config文件，用记事本打开的

**Comment by chenshaoju** [comment]
我说的是服务端。

**Comment by sinolulu** [comment]
> 我说的是服务端。

编辑服务器端口吗？不好意思，这方面我是小白一个。
目前代理端口是1080，服务器端口是28548，地址类似hk2-ss.gmdns.net这样的，一共10个，香港/日本/美国啥的。
地址应该没错，端口可能被封了，按照你的443修改了，还不行，最好出个修改版本的。

压缩个能用的给我吧，谢谢了，现在用熊猫翻滚感觉没有这个速度快，39479547@qq.com

**Comment by chenshaoju** [comment]
请不要留你的私人联系方式，因为无法保证联系你的人是你所期望的那个。

如果你是找SS机场（服务商）购买的SS服务，请与你的服务商联系。

**Comment by SilverLustre** [comment]
我也遇到过这个问题，只要把服务器上的shadowsocks服务重启一下就好了

**Comment by Testsoso** [comment]
> 我也遇到过这个问题，只要把服务器上的2.6.8服务重启一下就好了

服务都连不上，但是能ping通又怎么回事呢？

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2252#issuecomment-468895264
