### ISSUE TITLE
同样的公司网络，手机wifi能上，公司pc不能上

### ISSUE THREAD

**Issue by thisloving** [shadowsocks/shadowsocks-windows#2200]
pc端之前用了3个月都是正常的，最近pc端突然不能用了，但是手机端（同一份配置）在公司wifi和4g下一切正常，目测pc没有更改什么配置。我重启代理服务器，偶尔pc能上几分钟，但是过了这几分钟就不能上了。shadowsocks版本是4.1.2。在ss代理服务器上netstat -antp 看了下，发现pc端的Send-Q不为0。ss端口也更换了，pc端还是用不了。有没有人知道这种情况怎么解决？
ss服务器：阿里云香港
ss:4.1.2

**Comment by chenshaoju** [comment]
你所谓的代理服务器是你公司内部的代理服务器，还是指SS的服务器？

**Comment by thisloving** [comment]
> 你所谓的代理服务器是你公司内部的代理服务器，还是指SS的服务器？

是我自己的ss服务器。

**Comment by chenshaoju** [comment]
如果是你自己搭建的服务器，套一个Simple-obfs或者GoQuite插件，是否会有改善？
https://github.com/shadowsocks/simple-obfs/releases
https://github.com/cbeuw/GoQuiet/releases

**Comment by thisloving** [comment]
> 如果是你自己搭建的服务器，套一个Simple-obfs或者GoQuite插件，是否会有改善？
> https://github.com/shadowsocks/simple-obfs/releases
> https://github.com/cbeuw/GoQuiet/releases

不是，是我手机用是正常的，所以可以排除ss代理服务器的问题

**Comment by chenshaoju** [comment]
手机使用公司的网络能否正常？可能你所在的公司网络存在某种限制或者过滤。

**Comment by thisloving** [comment]
> 手机使用公司的网络能否正常？可能你所在的公司网络存在某种限制或者过滤。

手机使用公司网络是正常的，这个我问过公司的网络人员，他们他们自己也用ss代理，他们没问题的

**Comment by kakamatong** [comment]
我也碰到了同样的问题，年前还能用，过了个年回来不行了

**Comment by kakamatong** [comment]
手机上也是可以的

**Comment by chenshaoju** [comment]
客户端的日志中有什么错误提示吗？请记得隐藏你的服务器IP。

**Comment by NicoKam** [comment]
我也遇到同样的问题。手机热点ok。公司网络不行。自己买的vps，看不少人有这种情况，怀疑是报文被分析出来了，只要发现有ss的连接，就掐断你一会儿。我现在现象和楼下 #2193 一个样。

**Comment by NicoKam** [comment]
猜测是分析IP了，我国内有一台阿里云，我开全局模式连国内的，就不会有这种情况。

**Comment by chenshaoju** [comment]
如果可能，请按照上面的网址套一个GoQuite或者Simple-obfs插件看看（包括服务端和客户端）。

**Comment by thisloving** [comment]
> 客户端的日志中有什么错误提示吗？请记得隐藏你的服务器IP。

[2019-02-12 14:01:54] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-02-12 14:03:46] Shadowsocks started (4.1.2)
[2019-02-12 14:03:46] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-02-12 14:04:23] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 连接被意外关闭。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)


这个我能找到的pc客户端日志，是你要的吗

**Comment by thisloving** [comment]
> 如果可能，请按照上面的网址套一个GoQuite或者Simple-obfs插件看看（包括服务端和客户端）。

我先试一试这个方法

**Comment by chenshaoju** [comment]
```
基础连接已经关闭: 连接被意外关闭。
```
这个就是连接突然被切断了，建议换一个端口或者套一个插件看看。

**Comment by thisloving** [comment]
> 这个就是连接突然被切断了，建议换一个端口或者套一个插件看看。

换端口已经试过了，不起作用的。我先在试插件。

**Comment by yutouwd** [comment]
遇到了同样的问题，一开始在电脑（win7）上突然上不了外网，用手机测试也上不了。更换了端口之后电脑上仍然上不了，手机却可以上了。

**Comment by NicoKam** [comment]
Simple-obfs装好了试过可以。不过每台设备都要加个插件好麻烦。大佬能不能下个版本集成进去，万分感谢

**Comment by NicoKam** [comment]
顺便说一下安装过程，给其他想尝试的朋友参考。emmm好像也没什么过程。
首先服务端安装shadowsocks-libev
https://github.com/shadowsocks/shadowsocks-libev
我的是CentOS7，按ReadMe里面说的，官方源里面没有，要添加一个ss源，大概就是在这里找
https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/
下载到 /etc/yum.repos.d/
接着安装就好了
```
yum update
yum install shadowsocks-libev
```

simple-obfs需要下载源码编译安装。按ReadMe里面的一路安装完就可以了。
https://github.com/shadowsocks/simple-obfs

接着服务端我使用插件方式启动`ss-server -c config.json --plugin obfs-server --plugin-opts "obfs=tls"
`
客户端，在release里面下载obfs-local.zip，解压以后和你的ss放在一起。
客户端的服务器配置中，插件程序写`obfs-local`，插件选项写`obfs=tls;obfs-host=www.bing.com`
参考https://www.jianshu.com/p/135e538164f5
大功告成

**Comment by chenshaoju** [comment]
Simple-obfs 可以从一些发行版的官方源下载到：
Ubuntu： https://launchpad.net/ubuntu/+source/simple-obfs
Debian： https://packages.debian.org/sid/simple-obfs

我没用过CentOS，这个我就不知道了……

**Comment by thisloving** [comment]
> 顺便说一下安装过程，给其他想尝试的朋友参考。emmm好像也没什么过程。
> 首先服务端安装shadowsocks-libev
> https://github.com/shadowsocks/shadowsocks-libev
> 我的是CentOS7，按ReadMe里面说的，官方源里面没有，要添加一个ss源，大概就是在这里找
> https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/
> 下载到 /etc/yum.repos.d/
> 接着安装就好了
> 
> ```
> yum update
> yum install shadowsocks-libev
> ```
> simple-obfs需要下载源码编译安装。按ReadMe里面的一路安装完就可以了。
> https://github.com/shadowsocks/simple-obfs
> 
> 接着服务端我使用插件方式启动`ss-server -c config.json --plugin obfs-server --plugin-opts "obfs=tls" `
> 客户端，在release里面下载obfs-local.zip，解压以后和你的ss放在一起。
> 客户端的服务器配置中，插件程序写`obfs-local`，插件选项写`obfs=tls;obfs-host=www.bing.com`
> 参考https://www.jianshu.com/p/135e538164f5
> 大功告成

我用的是go版本的ss，没有--plugin选项。按照你的方法，用ss-server启动貌似不起作用。还有个问题，我看了我的手机客户端，没有混淆这一个选项。

**Comment by chenshaoju** [comment]
For Android:
Simple-obfs: https://play.google.com/store/apps/details?id=com.github.shadowsocks.plugin.obfs_local&hl=en_US
GoQuite: https://github.com/cbeuw/GoQuiet-android/releases

**Comment by thisloving** [comment]
2019-02-12 17:03:24 ERROR: connect: Invalid argument
 2019-02-12 17:03:24 ERROR: connect: Invalid argument
 2019-02-12 17:03:28 ERROR: connect: Invalid argument
 2019-02-12 17:03:28 ERROR: connect: Invalid argument
 2019-02-12 17:03:30 ERROR: connect: Invalid argument
 2019-02-12 17:03:30 ERROR: connect error
 2019-02-12 17:03:32 ERROR: connect: Invalid argument
 2019-02-12 17:03:32 ERROR: connect: Invalid argument
 2019-02-12 17:03:36 ERROR: connect: Invalid argument
 2019-02-12 17:03:39 ERROR: connect: Invalid argument
 2019-02-12 17:03:39 ERROR: connect: Invalid argument

我看代理服务器一直报这个错误。

**Comment by thisloving** [comment]
> 2019-02-12 17:03:24 ERROR: connect: Invalid argument
> 2019-02-12 17:03:24 ERROR: connect: Invalid argument
> 2019-02-12 17:03:28 ERROR: connect: Invalid argument
> 2019-02-12 17:03:28 ERROR: connect: Invalid argument
> 2019-02-12 17:03:30 ERROR: connect: Invalid argument
> 2019-02-12 17:03:30 ERROR: connect error
> 2019-02-12 17:03:32 ERROR: connect: Invalid argument
> 2019-02-12 17:03:32 ERROR: connect: Invalid argument
> 2019-02-12 17:03:36 ERROR: connect: Invalid argument
> 2019-02-12 17:03:39 ERROR: connect: Invalid argument
> 2019-02-12 17:03:39 ERROR: connect: Invalid argument
> 
> 我看代理服务器一直报这个错误。

这个报错解决了， config.json中2个local删除就可以了

**Comment by thisloving** [comment]
加了Simple-obfs，pc端还是不能用。换了一个加州的vps，一切正常。这次长教训了，买云还是不能买阿里云。

**Comment by jjwong1991** [comment]
这几天也出现了类似的问题，手机移动数据下和在家里wifi环境下使用正常，在公司wifi下无法连通，win端报错信息如下
`System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)`

服务器端用的是shadowsocks-libev，然后刚才通过删除config.json中的两个local相关配置解决了= =不知道为什么

**Comment by NicoKam** [comment]
加了simple-obfs昨天还能用，现在也不行了。。有点麻烦额

**Comment by NicoKam** [comment]
> 加了Simple-obfs，pc端还是不能用。换了一个加州的vps，一切正常。这次长教训了，买云还是不能买阿里云。

老哥你是哪里买的vps

**Comment by liangpure** [comment]
配置好了obfs 手机可以用了，但是pc还是不可以，难道只有换服务器ip了嘛

**Comment by thisloving** [comment]
> > 加了Simple-obfs，pc端还是不能用。换了一个加州的vps，一切正常。这次长教训了，买云还是不能买阿里云。
> 
> 老哥你是哪里买的vps

搬瓦工

**Comment by NicoKam** [comment]
我猜测是把新·加 坡 日·本 米国这些地方的ip给屏蔽了，ICMP放行，然后其他协议的特别是ss特征的请求给拦截了，应该不是加密算法被破解了，一下子都给攻破了也太厉害了。

**Comment by yuanyuandige** [comment]
昨天上午十点左右开始，很多人都被TCP阻断了，包括我的两台VPS在内，能Ping通，但是无法连接到服务器，这个时候单纯的混淆已经没有意义了，没办法，SS加了KCPTUN…V2ray转成mKCP+DTLS后，正常出墙了。

**Comment by xho22** [comment]
我也上kcptun了，但现在还有一个问题不清楚，为毛家里是好的，公司就不行了

**Comment by chenshaoju** [comment]
我记得KCPTun其实就是UDP的？

很早以前我观察到过一个现象，如果UDP（不正常的？）数据包太多，会出现奇怪的UDP全局中断现象

也许你所在公司UDP流量大，所以容易被干扰？

https://twitter.com/chenshaoju/status/1002742933928456197

**Comment by ZhangHangbo** [comment]
坐标：高校教研室
问题：电脑端用着用着突然无法访问外网，前一秒还能刷新google，立马就不行了，但是手机端立即测试，一切正常。手机电脑端用的一个服务器，手机从来没出过问题，电脑端过个几个小时，或者一天就正常访问。
特点：1.两台电脑同时使用一个服务器，同时不能使用，不确定是否同时恢复，但是好的时候都可以用。
2.手机端一切正常，电脑端无法访问外网时仍然正常访问。
3.会自动恢复，过个几个小时或几天，突然就好了。
4.ping服务端，平均400ms，但是没有掉包。
5.两台电脑都是win7，宿舍win10没出现过问题，但是宿舍使用少而且几乎在晚上。
求大佬帮忙解决

**Comment by chenshaoju** [comment]
１.请提供Windows客户端的日志，请记得隐藏你的服务器其信息。
２.你的计算机和手机是同一个网络吗？手机用的和电脑同一个网络的WiFi还是独立的3G/4G连接？
３.是否有使用插件（混淆）？

**Comment by ZhangHangbo** [comment]
1、![image](https://user-images.githubusercontent.com/35086557/52847446-2b46a580-3147-11e9-8867-624be196e0da.png)
2、另一台电脑突然就可以使用了，就回信息的时候，但是其中一台不可以使用，两台电脑不是同一所学校，但是一个服务器，手机端一直正常使用
3、没有使用插件，就是原有的plain

**Comment by chenshaoju** [comment]
你这个是SSR，给你参考：
https://twitter.com/fupeisheng2002/status/1096214903273095168
https://twitter.com/fupeisheng2002/status/1096217062207217664

**Comment by ZhangHangbo** [comment]
好的 谢谢

**Comment by RedemptionC** [comment]
类似的问题，手机用的好好的
电脑打开速度特别慢

**Comment by liwenjie001** [comment]
我也遇到了 ，同一局域网 手机可以 电脑不行，但是 电脑上换另一个节点的可以，找了一天也没有解决到底是为什么。

**Comment by DylanMaeng** [comment]
@

> 1、![image](https://user-images.githubusercontent.com/35086557/52847446-2b46a580-3147-11e9-8867-624be196e0da.png)
> 2、另一台电脑突然就可以使用了，就回信息的时候，但是其中一台不可以使用，两台电脑不是同一所学校，但是一个服务器，手机端一直正常使用
> 3、没有使用插件，就是原有的plain

请问解决了吗
