### ISSUE TITLE
手机网络可以使用，电脑连路由器不能用是为什么?

### ISSUE THREAD

**Issue by maroonman** [shadowsocks/shadowsocks-windows#2201]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
这意味着你所在的网络可能有屏蔽，请先尝试重新启动一下路由器和光猫（如果有），看看是否会有改善。

**Comment by maroonman** [comment]
好的

**Comment by maroonman** [comment]
还是不可以  请问网络有屏蔽如何解决？？？？

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，请尝试套一个Simple-obfs或者GoQuite插件并更换端口试试。
