### ISSUE TITLE
公司内网能telnet通，但上不了网，求可能的原因

### ISSUE THREAD

**Issue by xho22** [shadowsocks/shadowsocks-windows#2202]
我的服务器，确定一定以及肯定可以telnet通，但公司内网就是上不了网，一旦切到手机流量立马就能上了。
问题肯定出来公司网络上了，明明可以telnet通，而且服务器上看日志已经收到我的请求了，难道是公司出站没封，入站封了？

用的是libev版本,换电脑，换系统（win or mac）都试过了

**Comment by chenshaoju** [comment]
客户端的日志是……？

**Comment by xho22** [comment]
`[2019-02-12 15:37:01] connect to www.baidu.com:443`
`[2019-02-12 15:37:01] connect to www.baidu.com:443`
`[2019-02-12 15:37:01] Socket connected to ss server: myserver(xx.xx.xx.xx:xx)`
`[2019-02-12 15:37:01] Socket connected to ss server: myserver(xx.xx.xx.xx:xx)`

**Comment by chenshaoju** [comment]
这个很难看出来问题，你的SS服务器在国内还是国外？

国外的话请尝试套一个Simple-obfs或GoQuite看看？今天又类似的报告： https://github.com/shadowsocks/shadowsocks-windows/issues/2200

**Comment by xho22** [comment]
那个我试一下。
我服务器肯定是国外的啊，关键我在家里和用手机流量上网就是好的，但公司内网就是不行，想问一下，可能的问题点

**Comment by studentmain** [comment]
或许你需要请你司网管吃一顿（

**Comment by chenshaoju** [comment]
根据目前的反馈来看，有问题的都是大量境外流量的出口IP（企业内这种多人共享一个IP的）。

某种流量识别？

**Comment by xho22** [comment]
我能补充一些细节，我的服务器只有我一个人用，没有给其他人。
另外我有2个国外服务器
当第一个不能用的时候，切到第2个还是能用的，但不到2分钟也被封了

**Comment by chenshaoju** [comment]
如果可能，我还是建议你套一个GoQuite或者Simple-obfs测试一下。

**Comment by Liv1020** [comment]
我遇到的问题一样，起初也以为是公司网络，最后换了服务器可以了。我是只要用ss连接，ssh一定登不上去，过一段时间就好了

**Comment by JacFrak** [comment]
蛋疼，我今天也遇到跟你类似的问题，而且只在公司出现了这个问题

**Comment by xho22** [comment]
更新一下，套了Simple-obfs也不行，后来换成其他运营商的服务器，目前看来是好的。不好的那2台都是阿里云。

**Comment by chenshaoju** [comment]
目前已经有两例阿里云的报告了。 https://github.com/shadowsocks/shadowsocks-windows/issues/2200#issuecomment-462723916

**Comment by OptSolution** [comment]
同样公司内网上不了，但是其他网络都可以用，而且年前公司网络是可以，年后回来突然就不行了

**Comment by chenshaoju** [comment]
请尝试更换端口看看？

如果仍然不行，且你的服务器是自己搭建的话，请尝试套一个simple-obfs或者GoQuite看看？

**Comment by JacFrak** [comment]
vultr被玩坏了，建议换服务提供商
