### ISSUE TITLE
服务可以联通，但是不能访问，相关端口都会停在SYN_RECV直到超时断开

### ISSUE THREAD

**Issue by hanj2270** [shadowsocks/shadowsocks-windows#2203]
昨天还可以正常使用，今天突然就不行了，服务器IP和端口都是通的，但是不知为什么服务端收不到握手的ack包。

**Comment by hanj2270** [comment]
补充：刚刚发现，我配置了监听多个端口，仅有某一端口（8383）出现了该情况.其余端口均为出现。
服务端版本：
4.1.2
服务器系统版本：
Centos 6
客户端版本：
win-2.3

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，请尝试套一个Simple-obfs或者GoQuite。

**Comment by celeron533** [comment]
看上去像是TCP特定端口阻断。

**Comment by aweffr** [comment]
不是特定端口,我每次出现这种time_out都会尝试换端口重启服务,没有用

**Comment by chenshaoju** [comment]
请楼上的做一个试验，如果你的服务器是自己搭建的，请尝试套一个GoQuite插件看看？如果包括SSH在内都已经无法访问，可能需要换一个IP地址。

**Comment by aweffr** [comment]
> 请楼上的做一个试验，如果你的服务器是自己搭建的，请尝试套一个GoQuite插件看看？如果包括SSH在内都已经无法访问，可能需要换一个IP地址。

我试过GoQuite,但是可能是我搭的方式不对, 一旦建立连接, CPU就会立刻100%, 用光所有fd.

Kcptun我也搭起来了, 效果也是时断时续, 问题原生ss类似, 而且传输效果不是很好(当然, 因为我没怎么调参).

原本我用的客户端是shadowsocks-windows, 不过为了现在调试方便我已经改用本地ss-local了(libev版本).

我的两台服务地址分别在美国和欧洲, 都是各起了5个端口, 来回切换.

可以确定的是当A服务器的Port1变成read time-out状态时, 切到其余4个端口也是相同的情况, 切到B服务会好一些.

目前先把DNS解析记录都下了, 减小目标

**Comment by chenshaoju** [comment]
如果出现同一个IP的一个端口被Block了，其他端口都无法访问的情况，Ping能通吗？

如果你有国内的其他网络（或者国内的VPS等），从这些服务器上发起连接，能连接上吗？

另外，这个GoQuite配置文件给你参考，注意更换密码。

服务端：
```
{
        "WebServerAddr":"104.80.250.61:443",
        "Key":"5vpV7DHfcxGRcTWd",
        "FastOpen":true
}
```
客户端：
```
{
	"ServerName":"www.huawei.com",
	"Key":"5vpV7DHfcxGRcTWd",
	"TicketTimeHint":3600,
	"Browser":"chrome",
	"FastOpen":true
}
```

**Comment by aweffr** [comment]
> 如果出现同一个IP的一个端口被Block了，其他端口都无法访问的情况，Ping能通吗？
> 
> 如果你有国内的其他网络（或者国内的VPS等），从这些服务器上发起连接，能连接上吗？
> 
> 另外，这个GoQuite配置文件给你参考，注意更换密码。
> 
> 服务端：
> 
> ```
> {
>         "WebServerAddr":"104.80.250.61:443",
>         "Key":"5vpV7DHfcxGRcTWd",
>         "FastOpen":true
> }
> ```
> 客户端：
> 
> ```
> {
> 	"ServerName":"www.huawei.com",
> 	"Key":"5vpV7DHfcxGRcTWd",
> 	"TicketTimeHint":3600,
> 	"Browser":"chrome",
> 	"FastOpen":true
> }
> ```

thanks!
GoQuiet通了~能正常上网了, 不过现在我原生的另一个端口也能通, 我再观察一下

**Comment by aweffr** [comment]
> 104.80.250.61:443

原生ss被block的时候, ssh端口通, ping端口通

**Comment by chenshaoju** [comment]
感谢回报，看起来还是端口屏蔽，换端口可以解决。
