### ISSUE TITLE
Cannot Use within some internet provider.

### ISSUE THREAD

**Issue by lilin19** [shadowsocks/shadowsocks-windows#2204]
### Shadowsocks version 
4.1.4

### Environment(Operating system, .NET Framework, etc)

Windows10 pro 1809

### Steps you have tried
Login to server, result in network error. Server side protocol header cannot recognize. Client side ssl or network abort. The vultur cloud server at the same time not stable and cannot login with ssh shell. 

### Config and error log in detail (with all sensitive info masked) 
![e_ a8wzk 3qe l8_6 c3](https://user-images.githubusercontent.com/24790773/52698998-ae34f800-2faf-11e9-8548-81a7c3b7abb3.jpg)

**Comment by chenshaoju** [comment]
Can you paste client logs to here plz?

Hide your server IP from logs of course.

**Comment by lilin19** [comment]
always timeout

![c_qk 5 w9bh71 fir k](https://user-images.githubusercontent.com/24790773/52776698-20bfd980-307d-11e9-8426-5c16a4febdc9.png)

![y3 xnew b v wo1f](https://user-images.githubusercontent.com/24790773/52776708-24536080-307d-11e9-873f-31ad6cfd8c33.png)

**Comment by chenshaoju** [comment]
I tested your server IP address, Port is open and Connectable.

Please open https://www.ip.cn, record current IP address and reboot your router and fiber optic modem(If so).

After reboot done, refresh webpage ( http://www.ip.cn ), If IP address has changed, Is able to connect?

**Comment by lilin19** [comment]
It is possible that the china com's great wall telecom is blocking all those IP, and also the vultur cloud or american cloud is blocking some of 4G ip belong to china mobile. Now i am trying to use IP address proxy, and with both IP address from other provider, i can finally connect to the shadowsocks server.

**Comment by celeron533** [comment]
Regional ISPs may have their own firewall rules as one of the nodes of distributed GFW.
