### ISSUE TITLE
一个奇怪的现象，找不到原因

### ISSUE THREAD

**Issue by Test-Jim** [shadowsocks/shadowsocks-windows#2205]
前置：
      去年我一个朋友给了我一个shadowsocks的客户端4.0.8和账号等信息，我【在公司里面可以正常翻墙】。今年过来的时候，我发现无法翻了，猜测可能是朋友关服务了。然后前两天我自己在vultr上买个虚拟机centos7，用python的最新shadowsocks包搭建了服务。
问题来了：
      手机用【V4.2.5的apk可以翻，仅限4G，wifi下无法上网；最新的apk的4G和wifi都无法翻】。【PC端用4.0.8和最新的客户端都无法上网】
PC端日志：
[2019-02-13 15:53:36] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-02-13 15:53:36] Shadowsocks started
[2019-02-13 15:53:42] 45.32.103.1:8888 timed out
[2019-02-13 15:53:42] 45.32.103.1:8888 timed out
[2019-02-13 15:53:42] 45.32.103.1:8888 timed out
[2019-02-13 15:53:47] 45.32.103.1:8888 timed out
请问我该怎么解决？

**Comment by chenshaoju** [comment]
你的服务器是自己搭的吗？请尝试换一个端口看看。

如果仍然不行，你可能需要套一个Simple-obfs或者GoQuite试试。

**Comment by Test-Jim** [comment]
> 你的服务器是自己搭的吗？请尝试换一个端口看看。
> 
> 如果仍然不行，你可能需要套一个Simple-obfs或者GoQuite试试。

是自己搭的。我开了3个端口，只有手机4G可以翻，而且还是V4.2.5的apk，最新的apk反而不行。真的是奇了怪了

**Comment by CoderBeanLiang** [comment]
我的情况和你很像，也是Vultr搭的（CentOS7），年前一切正常，然后今年来了发现
【只要使用公司网站】即无法FQ（不论手机还是PC）
【只要使用4G流量】即可正常FQ（电脑使用手机流量开的热点也是可以正常FQ的）

昨天在公司使用Wifi时IP无法Ping通；
昨天回到宿舍测试宿舍WiFi，刚开始可以正常访问，几分钟后就不行了；
今天来公司测试Wifi环境，Ping/Telnet/Tcping都是能通但容易丢包，Putty能连但容易卡断；
开启SS后日志显示和楼主相同。

尝试方案有：
尝试换IP，IP能百分百Ping通但SS依然无法FQ；
尝试换端口号，无效（防火墙已开启端口）；
换aes-256-cfb为aes-256-gcm，无效；
尝试套Simple-obfs，失败（估计我配置错误，很多配置信息不知道如何使用）

之前浏览器显示错误信息一直是“无法安全连接此页面”，改端口后变成“无法访问此页面”了，具体原因不明，反正直接切换成买的账号的服务器配置就可以正常FQ了，说明SS软件/浏览器/Vultr服务器都是没有问题的，估计就是运营商针对性处理了，但我不明白为什么SSH能连上

**Comment by Test-Jim** [comment]
> 你的服务器是自己搭的吗？请尝试换一个端口看看。
> 
> 如果仍然不行，你可能需要套一个Simple-obfs或者GoQuite试试。

我尝试使用kcptun后出现的日志：
[2019-02-13 18:44:37] connect to clients1.google.com:443
[2019-02-13 18:44:38] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-02-13 18:44:38] connect to clients1.google.com:443
[2019-02-13 18:44:38] connect to api.github.com:443
[2019-02-13 18:44:39] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-02-13 18:44:39] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-02-13 18:44:39] connect to api.github.com:443
[2019-02-13 18:44:40] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-02-13 18:44:40] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-02-13 18:44:44] connect to beacons.gvt2.com:443
[2019-02-13 18:44:45] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

![image](https://user-images.githubusercontent.com/25148209/52706217-d0367680-2fbf-11e9-888a-da70e787471b.png) 服务端的，服务已经启了
![image](https://user-images.githubusercontent.com/25148209/52706252-e5aba080-2fbf-11e9-8f6a-1d0e093e4163.png)客户端的

**Comment by chenshaoju** [comment]
你用的是kcptun？我很早观察到一个现象，给你参考：
https://twitter.com/chenshaoju/status/1002742933928456197

**Comment by aogutong** [comment]
同样无法翻墙，公司WiFi和家里WiFi都不行，但是手机开热点给电脑用，就可以。。。

**Comment by Test-Jim** [comment]
> 同样无法翻墙，公司WiFi和家里WiFi都不行，但是手机开热点给电脑用，就可以。。。

我尝试过很多网络和节点，我这边目前移动的不能用， 电信的4G和wifi，联通的4Gwifi都可以。公司网络不知道做了什么处理，始终不可以用

**Comment by chenshaoju** [comment]
我想问一下，你的服务器是你自己专用的吗？还是你们公司内部的人一起用？

**Comment by cokebar** [comment]
很简单 公司防火墙的问题。
比如可能会有端口白名单，协议白名单这种，最直接的就是用simple-obfs, goquiet,v2ray插件之类，伪装成https跑443端口

**Comment by CrazyBunQnQ** [comment]
开了 kcptun 之后，同一个局域网（家里）同样的参数同样的版本，mac 能用，windows 就不行，windows 报就报这个错。如果不开 kcptun 的话可以但是很慢，有人知道啥原因么？
看起来应该是 windows 上有什么东西没设置。

**Comment by ARSChenWei** [comment]
> 同样无法翻墙，公司WiFi和家里WiFi都不行，但是手机开热点给电脑用，就可以。。。

我也是同样的情况，你找到解决办法了吗

**Comment by CrazyBunQnQ** [comment]
试了很久都没有解决，不止 Windows，路由器上的装了 kcptun 之后也是要么无法联网要么没有加速效果。
半个月前给台式机安装了苹果系统...我放弃治疗了... @ARSChenWei

**Comment by gisscape** [comment]
同样问题，家里wifi可以FQ，公司wifi无法FQ。手机开4G，可以FQ。
Vultr自建的ss服务器

**Comment by tutukill** [comment]
同样问题4g可以wifi不可以。但是wifi时断时续。。。。

**Comment by tutukill** [comment]
> 你用的是kcptun？我很早观察到一个现象，给你参考：
> https://twitter.com/chenshaoju/status/1002742933928456197

我的问题和你一样，请问有解决办法吗？我在gcp上自己搭建都v2ray，换了n个IP都不行

**Comment by git0715** [comment]
问题解决了吗？

**Comment by ZHJ0125** [comment]
我用Vultr自建的SS服务器，在家里测试，手机4G可以FQ，WiFi就不行了

**Comment by ZHJ0125** [comment]
> 我用Vultr自建的SS服务器，在家里测试，手机4G可以FQ，WiFi就不行了

手机开热点，电脑可以FQ，我推测是路由器或移动运营商的问题

**Comment by Test-Jim** [comment]
现在时期网控




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZhangH.J."<notifications@github.com&gt;; 
发送时间: 2020年2月8日(星期六) 晚上7:33
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com&gt;; 
抄送: "苍白`草香"<305540786@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shadowsocks/shadowsocks-windows] 一个奇怪的现象，找不到原因 (#2205)



 
我用Vultr自建的SS服务器，在家里测试，手机4G可以FQ，WiFi就不行了
  
手机开热点，电脑可以FQ，我推测是路由器或移动运营商的问题

**Comment by VictorAlexanderMa** [comment]
> 我用Vultr自建的SS服务器，在家里测试，手机4G可以FQ，WiFi就不行了

我这边是CloudCone的VPS搭建的SS服务器和v2ray，最近发现的奇怪现象跟你相似。用WiFi连接常常会出现无法访问的情况，但此时WiFi 访问国内网站速度是很快的。切换到4G流量后就立即能访问，速度过得去。不知道是怎么回事，是不是最近宽带运营商对于访问外网做了限制。

**Comment by 752021113** [comment]
谷歌云建的ssr  233blog大神的教程  问题基本类似  4G 热点均可访问Google   一切WiFi就ping不通   手机电脑都不行   ssr日志显示time out    
但是网上现成的付费V***P**N*在WiFi环境下就可以用（如：佛跳墙），现在依然不知道问题出哪里了  好像一周前突然这样的。。。。以前没问题的。。。。

**Comment by hankhu1128** [comment]
> 谷歌云建的ssr 233blog大神的教程 问题基本类似 4G 热点均可访问Google 一切WiFi就ping不通 手机电脑都不行 ssr日志显示time out
> 但是网上现成的付费V_**P**N_在WiFi环境下就可以用（如：佛跳墙），现在依然不知道问题出哪里了 好像一周前突然这样的。。。。以前没问题的。。。。

我是用的v2ray+ws+tls也是这个情况，4g速度正常，wifi除了早晨5、6点外都是龟速。
用付费vpn速度也没问题。
请问你现在解决了吗？
