### ISSUE TITLE
Shadowsocks 无法打开国外网站

### ISSUE THREAD

**Issue by srxffcc1** [shadowsocks/shadowsocks-windows#2209]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

https://ipcheck.need.sh/ 检测过了全部绿勾
https://www.infobyip.com/tcpportchecker.php 返回success

### Shadowsocks version / 影梭版本
4.1.3.1
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows10
### Steps you have tried / 操作步骤
双击图标

### What did you expect to see? / 期望的结果
正常翻墙

### What did you see instead? / 实际结果
无法翻墙

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
{
  "version": "4.1.3.1",
  "configs": [
    {
      "server": "xxxx",
      "server_port": 443,
      "password": "xxxxx",
      "method": "aes-256-cfb",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": true,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "portableMode": true,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}
```

**Comment by srxffcc1** [comment]
补充下日志
[2019-02-14 10:48:01] Shadowsocks started (4.1.3.1)
[2019-02-14 10:48:01] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-02-14 10:48:09] IP:xxx timed out
[2019-02-14 10:48:14] IP:xxx timed out
[2019-02-14 10:48:14] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-02-14 10:48:17] IP:xxx timed out
[2019-02-14 10:48:18] IP:xxx timed out
[2019-02-14 10:48:18] IP:xxx timed out
[2019-02-14 10:48:18] IP:xxx timed out

**Comment by chenshaoju** [comment]
```由于远程方已关闭传输流，身份验证失败。```
这意味着你的服务器不通，请尝试使用第三方的服务测试你的服务器是否工作正常：
https://ipcheck.need.sh/

**Comment by srxffcc1** [comment]
> `由于远程方已关闭传输流，身份验证失败。`
> 这意味着你的服务器不通，请尝试使用第三方的服务测试你的服务器是否工作正常：
> https://ipcheck.need.sh/

测试了下都是通的4个全绿

**Comment by srxffcc1** [comment]
> `由于远程方已关闭传输流，身份验证失败。`
> 这意味着你的服务器不通，请尝试使用第三方的服务测试你的服务器是否工作正常：
> https://ipcheck.need.sh/

测试过了都是通过的4个绿色对勾

**Comment by chenshaoju** [comment]
请确保你本机的配置和服务器一致（IP，端口等），如果使用的是域名的话，请尝试直接使用IP看看。

如果日志中仍然显示 time out 且无法使用，请使用tcping 进行测试，看看端口是否能连通。

你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。

这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
```
tcping -t 123.45.67.89 9876
```
其中 123.45.67.89 替换为你的SS服务器地址， 9876 替换为你的你的SS端口，然后回车，此时，如果显示 Port is open ，这说明端口通，如果不通，则可能提示 No response 或 Port is close。

**Comment by x82423990** [comment]
我也是春节过后就一直这样啊， 服务器肯定没有问题， 手机端可以连接上去，就win 连接上去报timeout 啊。。有没有解决了的， 求助。。。。。

**Comment by YazidLee** [comment]
> `由于远程方已关闭传输流，身份验证失败。`
> 这意味着你的服务器不通，请尝试使用第三方的服务测试你的服务器是否工作正常：
> https://ipcheck.need.sh/

你好，请问如果测试的时候显示国内TCP是红叉是不是因为IP被限制了

**Comment by chenshaoju** [comment]
是的，说明你的服务器从国内无法连接。

**Comment by Lbaron980810** [comment]
全部都红叉是什么情况啊...

**Comment by chenshaoju** [comment]
你的服务器挂了。

**Comment by HeroMickeyYu** [comment]
> 请确保你本机的配置和服务器一致（IP，端口等），如果使用的是域名的话，请尝试直接使用IP看看。
> 
> 如果日志中仍然显示 time out 且无法使用，请使用tcping 进行测试，看看端口是否能连通。
> 
> 你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。
> 
> 这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
> 
> ```
> tcping -t 123.45.67.89 9876
> ```
> 其中 123.45.67.89 替换为你的SS服务器地址， 9876 替换为你的你的SS端口，然后回车，此时，如果显示 Port is open ，这说明端口通，如果不通，则可能提示 No response 或 Port is close。

Hi，如果自己家中网络都是Port is open，而公司的网络则是一会儿No response，一会儿port is open，请问发生这种问题该怎么解决？谢谢

**Comment by chenshaoju** [comment]
Port is open 和 No response 之间间隔短吗？比如只间隔２～３行？

如果是，这意味着你公司的网络不稳定或者存在过滤。

如果非常有规律（比如互相间隔十个以上）则说明可能是来自墙的间歇性干扰。

**Comment by Alwayslazydog** [comment]
兄嘚 我的情况是这样 改成443之后 tcping 一会儿NO response 一会is open 。www.infobyip.com/ 显示3389是Successfully的 。但是ipcheck.need.sh TCP 国内外都是俩红叉。tcping 3389no response。有得治么 aliyun der

**Comment by chenshaoju** [comment]
这说明你的服务被墙了。

另外，不建议使用国内的云服务：https://github.com/shadowsocks/shadowsocks/issues/1180#issuecomment-371008976

**Comment by srxffcc1** [comment]
> 如果不通，则可能提示 No response 或 Port is close

显示No response

**Comment by chenshaoju** [comment]
你的端口被墙了，或者你的防火墙（iptables/ufw等）未允许该端口通行，请尝试换一个端口或者检查你的防火墙配置是否正确。
