### ISSUE TITLE
插件怎么没有效果呢？

### ISSUE THREAD

**Issue by wyfang** [shadowsocks/shadowsocks-windows#2210]
![qq20190214-110001](https://user-images.githubusercontent.com/17900420/52759723-ec7df600-3047-11e9-80e3-67e7b8ba4b71.jpg)
如图，是哪里错了吗？

**Comment by chenshaoju** [comment]
你用的KCPTun是从哪里获取的？如果是官方（https://github.com/xtaci/kcptun）的话，请仔细阅读：
https://github.com/shadowsocks/shadowsocks-windows/wiki/%E4%BD%BF%E7%94%A8%E9%9D%9ESIP003%E8%A7%84%E8%8C%83%E7%9A%84%E6%8F%92%E4%BB%B6
