### ISSUE TITLE
shadowsocks + kcptun插件 上网失败

### ISSUE THREAD

**Issue by Yuan-ZW** [shadowsocks/shadowsocks-windows#2211]
### Shadowsocks version
Shadowsocks 4.1.4

### Environment
![win](https://user-images.githubusercontent.com/31435244/52767231-d3d00900-3064-11e9-8d65-4e8d78022651.png)

 .NET Framework 不知道是不是这么看。。
![net framework](https://user-images.githubusercontent.com/31435244/52767378-43de8f00-3065-11e9-8614-2afd5abb0c60.png)

##### ss 服务端
Shadowsocks: `-s 0.0.0.0 -p 6443 -m chacha20 -k mypasswd -u --fast-open`
kcptun: `-t 127.0.0.1:6443 -l :6500 -mode fast2`

##### 1、使用 Shadowsocks 直连 上网成功
![ss](https://user-images.githubusercontent.com/31435244/52768190-c10b0380-3067-11e9-9a6a-71b45194f8d8.png)

##### 2、使用 Shadowsocks + cmd 运行 kcptun 上网成功
![kcp](https://user-images.githubusercontent.com/31435244/52768333-34ad1080-3068-11e9-9391-52b11b55ec84.png)
![cmd](https://user-images.githubusercontent.com/31435244/52768314-2959e500-3068-11e9-9ae7-414748114972.png)

##### 3、使用 Shadowsocks + kcptun_gclient 上网成功
![kcp](https://user-images.githubusercontent.com/31435244/52768380-51e1df00-3068-11e9-89d2-5b71eabeae72.png)
![kcptun-gui](https://user-images.githubusercontent.com/31435244/52768388-57d7c000-3068-11e9-998c-7cc664e88c89.png)

##### 4、使用 安卓Shadowsocks + kcptun插件 上网成功
![android](https://user-images.githubusercontent.com/31435244/52768453-89508b80-3068-11e9-89db-7a1d24d93348.png)

##### 5、使用 Shadowsocks + kcptun插件 上网失败
![kcp](https://user-images.githubusercontent.com/31435244/52768510-ae44fe80-3068-11e9-95cc-c34a69912c6e.png)

任务管理器中能看到 client_windows_amd64.exe 的进程, 所以相对路径应该没错

kcptun的参数只有一个`--mode fast2` 其他都是默认,
根据前几个成功上网案例, 应该能够说明这里提供的参数也没错

插件参数填 `--mode fast2`
插件选项填 `mode=fast2`
两者都试过 都失败了

ss的错误日志如下
### Config and error log in detail
![log](https://user-images.githubusercontent.com/31435244/52768983-fa447300-3069-11e9-9592-b5cc3dd22c4d.png)

**Comment by chenshaoju** [comment]
积极拒绝提示，意味着你的KCPTun客户端的监听端口或者SS客户端的服务器端口配置可能有误。

**Comment by Yuan-ZW** [comment]
> 如果你用的是符合SIP003协议的插件，可能和官方原版的KCPTUN不兼容。

刚刚确认了一下, 我用的kcptun确实是官方原版的 [https://github.com/xtaci/kcptun/releases](https://github.com/xtaci/kcptun/releases)


>积极拒绝提示，意味着你的KCPTun客户端的监听端口或者SS客户端的服务器端口配置可能有误。

结合我上面提到的 2, 3, 4 三个成功使用kcp的方式, 我始终觉得我的端口配置的应该没有问题才对, 请问是否还有别的可能性.

**Comment by Yuan-ZW** [comment]
![tcping](https://user-images.githubusercontent.com/31435244/52770978-9624ad80-306f-11e9-8fbe-77cd5e0f27e1.png)

另外, 在浏览了其他的 issues 之后，我用 tcping.exe ping 了一下，发现ping不通。
原因很明显，kcptun走的是udp，不是tcp。
而我在服务端对于kcptun服务所占用的6500端口, 只对外开放了 6500/udp 而不是 6500/tcp

不知道这一点有什么影响
正如上面说的 我用其他方式是可以成功使用kcp加速的，只是shadowsocks客户端的插件功能不行

**Comment by chenshaoju** [comment]
请仔细看教程……你要输入环境变量的，教程里样例都有的。

**Comment by chenshaoju** [comment]
tcping 之所以叫 TCPing ，是测试TCP连通性的，KCPTun如果我没记错的是，是UDP协议，不能这样测试的。

**Comment by Yuan-ZW** [comment]
-l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT% --mode fast2

**Comment by Yuan-ZW** [comment]
感谢！ 解决了。。
自以为是地以为可以直接输入来代替环境变量。。。不好意思。。
