### ISSUE TITLE
感觉 阿里云香港 IP 全部gg

### ISSUE THREAD

**Issue by wanglong167** [shadowsocks/shadowsocks-windows#2214]
感觉 阿里云香港 IP 全部gg

**Comment by wanglong167** [comment]
我切到腾讯云 就好好的  阿里云ip  怎么都不行

**Comment by chenshaoju** [comment]
不建议使用国内的云服务。 https://github.com/shadowsocks/shadowsocks/issues/1180#issuecomment-371008976

**Comment by wanglong167** [comment]
国内厂商有加速
