### ISSUE TITLE
加了obfs也不通

### ISSUE THREAD

**Issue by litianyuhehe** [shadowsocks/shadowsocks-windows#2217]
[2019-02-16 18:54:31] connect to api.github.com:443
[2019-02-16 18:54:31] Socket connected to ss server: 45.32.81.124:12998
[2019-02-16 18:54:34] connect to apis.google.com:443
[2019-02-16 18:54:34] connect to www.gstatic.com:443
[2019-02-16 18:54:34] Socket connected to ss server: 45.32.81.124:12998
[2019-02-16 18:54:34] Socket connected to ss server: 45.32.81.124:12998
[2019-02-16 18:54:34] connect to www.google.com:443
[2019-02-16 18:54:34] Socket connected to ss server: 45.32.81.124:12998
[2019-02-16 18:55:09] connect to api.github.com:443
[2019-02-16 18:55:09] Socket connected to ss server: 45.32.81.124:12998
[2019-02-16 18:55:49] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by litianyuhehe** [comment]
C:\Users\Administrator>tcping -t 45.32.81.124 12998

** Pinging continuously.  Press control-c to stop **

Probing 45.32.81.124:12998/tcp - Port is open - time=246.079ms
Probing 45.32.81.124:12998/tcp - Port is open - time=246.777ms
Probing 45.32.81.124:12998/tcp - Port is open - time=231.456ms
Probing 45.32.81.124:12998/tcp - Port is open - time=232.785ms
Probing 45.32.81.124:12998/tcp - Port is open - time=225.498ms
Probing 45.32.81.124:12998/tcp - Port is open - time=209.684ms
Probing 45.32.81.124:12998/tcp - Port is open - time=228.593ms
Probing 45.32.81.124:12998/tcp - Port is open - time=207.660ms
Probing 45.32.81.124:12998/tcp - Port is open - time=248.650ms
Probing 45.32.81.124:12998/tcp - Port is open - time=226.471ms
Probing 45.32.81.124:12998/tcp - Port is open - time=213.558ms
Probing 45.32.81.124:12998/tcp - Port is open - time=207.557ms
Control-C

Ping statistics for 45.32.81.124:12998
     12 probes sent.
     12 successful, 0 failed.  (0.00% fail)
Approximate trip times in milli-seconds:
     Minimum = 207.557ms, Maximum = 248.650ms, Average = 227.064ms
tcp协议也是通的

**Comment by litianyuhehe** [comment]
C:\Users\Administrator>ping 45.32.81.124

正在 Ping 45.32.81.124 具有 32 字节的数据:
来自 45.32.81.124 的回复: 字节=32 时间=236ms TTL=43
来自 45.32.81.124 的回复: 字节=32 时间=227ms TTL=43
来自 45.32.81.124 的回复: 字节=32 时间=217ms TTL=43
来自 45.32.81.124 的回复: 字节=32 时间=246ms TTL=43
ping 也通

**Comment by chenshaoju** [comment]
测试了一下，端口的确是通的，请尝试换一个端口看看，比如８０或者４４３，然后再试。

如果可能，请复查一下你的simple-obfs配置是否正确。

**Comment by litianyuhehe** [comment]
"server": "45.32.81.124",
      "server_port": 12998,
      "password": "马赛克",
      "method": "aes-256-gcm",
      "plugin": "obfs-local",
      "plugin_opts": "obfs=tls;obfs-host=www.bing.com",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
客户端配置
    "server":"45.32.81.124",
    "server_port":12998,
    "password":"马赛克",
    "timeout":300,
    "user":"nobody",
    "method":"aes-256-gcm",
    "fast_open":true,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls"
服务端配置
obfs-local和Shadowsocks放到一个目录下了

**Comment by litianyuhehe** [comment]
ssh上去
[root@vultr ~]# iptables -L -n | grep 12998
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:12998 ctstate NEW
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:12998 ctstate NEW
端口都允许了

**Comment by litianyuhehe** [comment]
[root@vultr ~]# ps -ef | grep -v grep | grep "server"
nobody   14172     1  0 10:46 ?        00:00:00 /usr/local/bin/ss-server -v -c /etc/shadowsocks-libev/config.json -f /var/run/shadowsocks-libev.pid
root     14173 14172  0 10:46 ?        00:00:00 obfs-server
ss和obfs也都启动着

**Comment by litianyuhehe** [comment]
想问下 服务器上的 simple-obfs 要不要手动建配置文件 什么的 还是说启动起来就不用管了 @chenshaoju

**Comment by litianyuhehe** [comment]
我的 QQ 1249109453 如果有时间的话 请加下我 谢谢

**Comment by chenshaoju** [comment]
请不要留私人联系方式，因为无法保证联系你的人就是你所期望的那个人。

一般是写入 shadowsocks-libev 的配置文件 config.json 中的一行参数，给你参考：
```
{
    "server":"0.0.0.0",
    "server_port":443,
    "local_port":10800,
    "password":"pBpAXnvH2JhT",
    "timeout":20,
    "method":"aes-256-gcm",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls;failover=104.193.88.77:443"
}
```

客户端的话，在插件程序中指定插件的路径后，在插件选项中指定参数：
```
obfs=tls;obfs-host=www.baidu.com
```

**Comment by litianyuhehe** [comment]
通了通了 太感谢了 @chenshaoju

**Comment by gypjoy** [comment]
> 通了通了 太感谢了 @chenshaoju

您好，请问下，obfs-local是只要放在客户端shadowsockes.exe同个文件下，然后配置下插件就可以了吗？服务端需要配置吗？

**Comment by chenshaoju** [comment]
服务端也需要。

**Comment by aleckvivi** [comment]
我安装的ssserver 的版本是Shadowsocks 2.8.2
执行 ssserver -c /etc/ss-conf.json --plugin obfs-server --plugin-opts "obfs=http"
提示没有 --plugin 选项。是我的版本太低了？

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-libev

**Comment by aleckvivi** [comment]
谢谢，服务端配置好了。能否提供一下编译好的windows x64 obfs客户端

**Comment by chenshaoju** [comment]
@aleckvivi https://github.com/shadowsocks/simple-obfs/releases
![image](https://user-images.githubusercontent.com/515763/59079523-c641d600-8916-11e9-9986-ca0d7836edb5.png)

但是注意，这个官方版可能会遭遇奇怪的崩溃问题，如果你遇到了，可以考虑试一下这个**第三方**版本：
https://github.com/imgk/simple-obfs-Cygwin/releases

**Comment by aleckvivi** [comment]
已找到，配置上确认好用。

**Comment by White99** [comment]
@chenshaoju 请问有Ubuntu 18 的服务端吗？

**Comment by chenshaoju** [comment]
https://packages.ubuntu.com/search?keywords=simple-obfs

**Comment by prime51** [comment]
请问一下，加了obfs之后，只有出站流量，没有入站流量是怎么回事

**Comment by chenshaoju** [comment]
这意味着你的配置有误，请仔细检查你的配置（端口，协商协议等），以及端口是否能通（防火墙）。

**Comment by prime51** [comment]
> 这意味着你的配置有误，请仔细检查你的配置（端口，协商协议等），以及端口是否能通（防火墙）。

感谢，之前服务端没有启动obfs-server，现在调通了
