### ISSUE TITLE
  CentOS 服务器 求一个  ss   simple-obfs混淆安装程序 

### ISSUE THREAD

**Issue by maroonman** [shadowsocks/shadowsocks-windows#2218]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
我没有使用过CentOS，不知道能否使用Debian的安装包：
https://packages.debian.org/sid/simple-obfs

往下翻，下载在下面。

或者，你可能需要自行编译一个：
https://github.com/shadowsocks/simple-obfs/blob/master/README.md

**Comment by qwertccc** [comment]
https://github.com/teddysun/shadowsocks_install

**Comment by studentmain** [comment]
@chenshaoju CentOS用的是RPM包，换句话说，不能，反之亦然。Debian的包一般可以尝试在Ubuntu/Deepin上面跑。
