### ISSUE TITLE
服务器装BBR后本地无法接收数据

### ISSUE THREAD

**Issue by guclan** [shadowsocks/shadowsocks-windows#2223]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
docker 仓库镜像 版本shadowsocks-libev 3.2.3

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
客户端 Windows10   .NET 4.7.2
服务端 Debian 9.0
手机 IOS12  shadowpocket

### Steps you have tried / 操作步骤
第一次创建 服务器使用了BBR 客户端无法接收到返回的数据包，详细日志的流量显示发送成功，没接收到流量，用手机测试正常，确定服务器没问题
第二次创建 服务器未使用BBR 客户端一切正常

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
详细日志中没有任何异常，只有IP连接信息

**Comment by chenshaoju** [comment]
你好，我也使用使用了BBR，但是没有你这个现象。

如果你取消BBR，是否就正常了？

![image](https://user-images.githubusercontent.com/515763/52926507-00d83080-3371-11e9-88ec-b8d6d03d9828.png)

**Comment by guclan** [comment]
> 你好，我也使用使用了BBR，但是没有你这个现象。
> 
> 如果你取消BBR，是否就正常了？
> 
> ![图片](https://user-images.githubusercontent.com/515763/52926507-00d83080-3371-11e9-88ec-b8d6d03d9828.png)

我在15号测试的带有BBR的，今天重置为不带BBR的，15号的时候用手机wifi连接是可以使用的，但是电脑客户端不行，今天重置后电脑和手机都可用了

服务器是腾讯云首尔节点，客户端是最新的4.1.4

节点加密方式为aes-256-gcm

我的搬瓦工CN8一直使用的aes-256-cfb和BBR，是可用的，是否跟加密方式有关？

**Comment by chenshaoju** [comment]
通常不推荐使用国内的云服务。

理论上和加密方式无关，但是如果你的Windows客户端没有装VC++运行库的话（ https://www.microsoft.com/en-us/download/details.aspx?id=53840 ），可能会导致 aes-*-gcm 算法有问题。
