### ISSUE TITLE
Consolas 字体不适配导致闪退

### ISSUE THREAD

**Issue by ssrpanel** [shadowsocks/shadowsocks-windows#2226]
### Shadowsocks version / 影梭版本
4.1.4 及以下都存在

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 7

### Steps you have tried / 操作步骤
直接打开

### What did you expect to see? / 期望的结果
正常打开

### What did you see instead? / 实际结果
![IMG_7311.PNG](https://i.loli.net/2019/02/19/5c6b6c4f2f154.png)

**Comment by chenshaoju** [comment]
这个字体是系统自带的，如果你没有这个字体，情进入控制面板，字体，看看是否隐藏或者禁用了该字体。

如果删除了该字体，请从另一台Windows 7计算机上拷贝过来即可。

如果硬是不肯使用该字体，请使用Windows自带的记事本打开 Shadowsocks.exe 所在目录下的 gui-config.json 文件，找到 `    "Font": "Consolas, 8pt",` ，将 `Consolas`修改为其他字体，比如`    "Font": "宋体, 8.25pt",`，保存退出后即可。

**Comment by celeron533** [comment]
#1940
