### ISSUE TITLE
为什么昨天刚换的Ip，今天就被封

### ISSUE THREAD

**Issue by FernandoZhuang** [shadowsocks/shadowsocks-windows#2228]
### Shadowsocks version / 影梭版本
4.1.4

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
昨天更换Ip以后，搬瓦工内置界面重装了系统，SS，SSR
SS默认的配置，443端口，没有使用混淆插件，可以fq
SSR默认的配置，timeout
随后不想再倒腾，便使用SS浏览了Google，Ins
今天再用，就发现被封!

被封历史
第一次是在使用SS大概两个月，2018.12.20 左右被封
第二次是春节前，443端口time out，便根据issue中的回答换了6000
第三次就是前几天被封

想问的是，为什么会被封呢？春节这段时间，大家ss的情况怎么样呢？

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![default](https://user-images.githubusercontent.com/22760805/53001168-ff883000-3464-11e9-9b52-863b050c08ab.png)
![default](https://user-images.githubusercontent.com/22760805/53001290-3cecbd80-3465-11e9-9933-d099b7f28d23.png)

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭的，请尝试套一个Simple-obfs或者GoQuite试试：

Simple-obfs: https://github.com/shadowsocks/simple-obfs/releases
GoQuite: https://github.com/cbeuw/GoQuiet/releases

可能有点复杂，请仔细阅读说明。

配置文件可参考：
Simple-obfs: https://github.com/shadowsocks/shadowsocks-windows/issues/2217#issuecomment-464413579
GoQuite: https://github.com/shadowsocks/shadowsocks-windows/issues/2203#issuecomment-463896047

**Comment by reformdai** [comment]
想问一下，我的没有被封，可是都一直不能科学上网，弄了好久都不行。每次都是打开 SS 就断网，用360修复后能上网但是不能连上外网。都快愁死了~

**Comment by chenshaoju** [comment]
建议开个新 issue ，按照模板提供信息，以便于解决问题。

**Comment by chenshaoju** [comment]
建议开个新 issue ，按照模板提供信息，以便于解决问题。

**Comment by MakeWater** [comment]
有时候换换端口还是可以的，我配置的多用户，一个用户一个端口，如果有些端口不行，比如时而能上网时而不能，那你可以考虑换个数字开头的端口了，我这样试过，可以的。

**Comment by petitioner** [comment]
###

**Comment by WC12366** [comment]
> 想问一下，我的没有被封，可是都一直不能科学上网，弄了好久都不行。每次都是打开 SS 就断网，用360修复后能上网但是不能连上外网。都快愁死了~

360是流氓软件，会收集你的ss服务器信息，上报给gfw
