### ISSUE TITLE
开启后任何操作都会提示“处理代理设置时发生错误，是否重置当前代理设置并重试？”

### ISSUE THREAD

**Issue by Liomilo** [shadowsocks/shadowsocks-windows#2234]
此提示选择是的话，会出现“发生不可恢复的代理设置错误，查看日志以取得详情”。
然后无法连通。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-02-21 21:26:48] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-02-21 21:26:49] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

**Comment by chenshaoju** [comment]
```
ERROR_WINHTTP_AUTO_PROXY_SERVICE_ERROR
12178
Returned by WinHttpGetProxyForUrl when a proxy for the specified URL cannot be located.
```
https://docs.microsoft.com/en-us/windows/desktop/winhttp/error-messages

这个提示有点让人困惑，尝试查询代理设置时失败了。

请问是否有使用某些安全软件？

另外，是否使用的评估版系统？https://github.com/shadowsocks/shadowsocks-windows/issues/2191

**Comment by studentmain** [comment]
老问题了，某个系统服务挂了。最干脆的解决方法是重装。

**Comment by Liomilo** [comment]
系统win10专业版 17134，一直以来都是安全软件都是火绒，也没出现冲突，这是最近才出现的问题

**Comment by chenshaoju** [comment]
我这儿的Win10是 17763.316 （运行 winver 查看），你是不是很久没更新了？

**Comment by Liomilo** [comment]
winver查看是 17134.590 ，不对啊，我自动更新开着的，最近一次还是5天前

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/53254067-97a04680-36fd-11e9-9041-f171e9f9f771.png)

**Comment by Liomilo** [comment]
我手动更新上1809试试。

**Comment by Liomilo** [comment]
更新后问题解决，谢谢诸位的帮助:-)

**Comment by DSbajRv5Ol4X** [comment]
一样的问题，检查系统文件，WIN http服务也是灰色的，之后下载SSR一顿操作居然好了？？？我只是把里面的代理模式换成直连模式，然后SSR提示浏览器开启了代理上网。之后关掉SSR打开SS就没报错了,一头雾水。
SSR:https://github.com/shadowsocksrr/shadowsocksr-csharp/releases

**Comment by changyuqing** [comment]
一开始是识别二维码弹出提示框，退出shadowsocks后重新打开就没事了
