### ISSUE TITLE
插件使用kcptun时无法使用IPv6连通

### ISSUE THREAD

**Issue by sxlllslgh** [shadowsocks/shadowsocks-windows#2235]
### Shadowsocks version / 影梭版本
4.1.4

### Environment(Operating system, .NET Framework, etc) / 使用环境
Windows 10, .Net Framework 4.7, 原版kcptun 20190109

### Steps you have tried / 操作步骤
服务器为IPv4/IPv6双栈服务器，使用kcptun插件，分别设置两项除地址外参数均相同的服务器配置，地址分别为服务器IPv4地址和IPv6地址。

### What did you expect to see? / 期望的结果
IPv4和IPv6均可使用kcptun插件连通。

### What did you see instead? / 实际结果
IPv4可使用kcptun插件连通，IPv6无法使用kcptun插件连通，但在命令行开启kcptun后在Shadowsocks内使用127.0.0.1服务器可以连通，日志无报错。

### Config and error log in detail / 配置文件和日志文件
配置文件：
```
{
    "server": "服务器IPv4地址",
    "server_port": 服务器Shadowsocks端口,
    "password": "Shadowsocks密码",
    "method": "Shadowsocks加密方式",
    "plugin": "kcptun.exe",
    "plugin_opts": "",
    "plugin_args": "-l :%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT% --key kcptun密码 --crypt kcptun加密方式 --mode fast3",
    "timeout": 5
},
{
    "server": "服务器IPv6地址",
    "server_port": 服务器Shadowsocks端口,
    "password": "Shadowsocks密码",
    "method": "Shadowsocks加密方式",
    "plugin": "kcptun.exe",
    "plugin_opts": "",
    "plugin_args": "-l :%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT% --key kcptun密码 --crypt kcptun加密方式 --mode fast3",
    "timeout": 5
}
```
日志：

> Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================
[2019-02-21 21:46:54] connect to **************
[2019-02-21 21:46:54] Socket connected to ss server: ****** ([服务器IPv6地址]:服务器kcptun端口)

**Comment by chenshaoju** [comment]
搜了一下，请确保你的配置正确：
https://github.com/xtaci/kcptun/issues/173

**Comment by sxlllslgh** [comment]
> 搜了一下，请确保你的配置正确：
> [xtaci/kcptun#173](https://github.com/xtaci/kcptun/issues/173)

我和他情况不一样，我在客户端PC使用命令行开启kcptun后，在Shadowsocks内连接127.0.0.1是可以连通的：
![image](https://user-images.githubusercontent.com/11386258/53228792-3e182780-36bd-11e9-8e50-e857d18ecdcb.png)

就是直接使用Shadowsocks写入插件参数就连不上。
![image](https://user-images.githubusercontent.com/11386258/53228908-aebf4400-36bd-11e9-8c4c-ebc81c21c033.png)

反复检查参数都是一样的，除了本机地址和本机端口在使用插件时无须指定。

**Comment by chenshaoju** [comment]
你输入的IPv6地址是用方括号括起来的吗？比如： `[1234:5678:9012::3210]`？

**Comment by sxlllslgh** [comment]
> 你输入的IPv6地址是用方括号括起来的吗？比如： `[1234:5678:9012::3210]`？
![image](https://user-images.githubusercontent.com/11386258/53230418-96512880-36c1-11e9-827c-153b3d50a749.png)
不是的，括号会自动补上

**Comment by chenshaoju** [comment]
我知道，你试着输入看看？

**Comment by sxlllslgh** [comment]
> 我知道，你试着输入看看？

哇，成功了！真的十分感谢！

**Comment by celeron533** [comment]
Reopen this issue for tracking the ipv6 nested square brackets issue.

**Comment by celeron533** [comment]
>现在显示两层方括号，成功连接

插件程序对于IPv6地址的要求不尽相同，有的需要加入方括号，有的则不要。是否自动加方括号这个行为无法在程序中写死。还是建议在命令行参数中自行添加方括号


`foo.exe -remote %SS_REMOTE_HOST%`
-or-
`bar.exe -server [%SS_REMOTE_HOST%]`
