### ISSUE TITLE
请问pac里面已存在于GFWlish网站是删除不了的吗?

### ISSUE THREAD

**Issue by klikli234** [shadowsocks/shadowsocks-windows#2237]
手动删除后,重启程序发现又回来了.

**Comment by celeron533** [comment]
因为每次启动的时候会从网上自动更新gfwlist

**Comment by chenshaoju** [comment]
你选择的是使用本地PAC对吧？

如果你自己改了PAC，除非你手动点一下更新PAC，否则不会更新。

但是如果你从菜单中点击了“编辑 GFWList 的用户规则“，那么就会覆盖。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
