### ISSUE TITLE
ssh可以连接到ssr服务器，服务运行正常，开启代理不能访问外网，访问谷歌显示500

### ISSUE THREAD

**Issue by byeluliangwei** [shadowsocks/shadowsocks-windows#2238]
版本：4.1.4
日志信息：

[2019-02-25 20:34:18] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-02-25 20:34:18] Shadowsocks started (4.1.4)
[2019-02-25 20:34:18] 

我检查了我的IP，是可用的，但是就是自己连接之后，不能访问外网，访问谷歌就是500 Internal Privoxy Error错误，请问是什么原因呢？年前都用的好好的，试了许多办法都不行。

**Comment by chenshaoju** [comment]
```由于远程方已关闭传输流，身份验证失败。```
请仔细检查你所配置客户端的服务器IP、端口、加密方式和密码是否正确。

请确保你的服务器上的SS服务已经启动，IP、端口、加密方式和密码是否和客户端一致。

**Comment by byeluliangwei** [comment]
@chenshaoju 你说的这些操作我都仔细检查过，但是还是不行，之前我这个是可以用的。我用https://ipcheck.need.sh/检测了我的IP，有时候显示TCP被阻断，再检测一次又发现正常了，我换了几个IP都是这样。买的vultr上的服务器

**Comment by chenshaoju** [comment]
请不要到处发，移动到 https://github.com/shadowsocks/shadowsocks-windows/issues/2241
