### ISSUE TITLE
aws搭建ss服务shadowsocks日志提示time out

### ISSUE THREAD

**Issue by JordanZhangboy** [shadowsocks/shadowsocks-windows#2240]
### Shadowsocks version / 影梭版本
Shadowsocks-4.1.4

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Ubuntu 未安装.NET Framework/ windows7 .NET Framework 4.7.2

### Steps you have tried / 操作步骤
iptables -F 清空防火墙策略无用
添加安全组所有流量访问无用
shadowsocks客户端日志提示如下，5800端口提示在监听，各位大大麻烦帮看一下，感觉离成功很近了，谢谢~

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件

![image](https://user-images.githubusercontent.com/13427075/53399806-974ac880-39e7-11e9-8bf1-168e4739f369.png)
![image](https://user-images.githubusercontent.com/13427075/53399678-69658400-39e7-11e9-9364-43fddcdbf35a.png)
![image](https://user-images.githubusercontent.com/13427075/53399861-b47f9700-39e7-11e9-9787-f3abf3ebf63c.png)

**Comment by JordanZhangboy** [comment]
谢谢你，已经通过其他方式安装好啦~

**Comment by askwuxue** [comment]
你好，请问这个情况怎么解决了。
