### ISSUE TITLE
出站一直占着,入站速度莫名消失,访问失效,不定时恢复,

### ISSUE THREAD

**Issue by 299174105** [shadowsocks/shadowsocks-windows#2242]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
`4.1.4`

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 , .NET Framework v4.0.30319

### Steps you have tried / 操作步骤
昨天开始 ss入站速度莫名消失,小飞机一直有上传连接

### What did you expect to see? / 期望的结果
连接顺畅,没有入站速度,好像一直在请求什么东西

### What did you see instead? / 实际结果
入站数据会随机恢复,时间不确定,vps没问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![snipaste_2019-02-26_23-27-34](https://user-images.githubusercontent.com/17736127/53424406-1c50d480-3a1e-11e9-81b6-9556ebc90a46.png)
一直在连接图上2个地址,没有入站速度,全是出站.导致访问网站失败.

**Comment by chenshaoju** [comment]
这是Telegram位于新加坡的服务器，你是否在使用Telegram？

如果是，这不应该是导致访问失败的原因。

请问是否启用了系统代理，使用的是全局代理还是PAC模式？

**Comment by 299174105** [comment]
使用了telegram.
使用的全局和pac都是这样.
使用过程中一段时间间歇性的断开(只有出站没有入站).
不仅仅是telegram,其他需要梯子的都打不开,服务器是没有问题的.
![snipaste_2019-02-26_23-45-06](https://user-images.githubusercontent.com/17736127/53459130-a2e3d100-3a73-11e9-8312-6d70cb5f7b8d.png)

会不会是运营商的问题?

**Comment by chenshaoju** [comment]
日志中看不出什么问题，连接看起来也成功了，只能盲猜。

请问在第三方测试服务 https://ipcheck.need.sh 测试的话，你的服务器正常吗？

如果正常，请尝试重启一下你的服务器看看？

**Comment by 299174105** [comment]
第三方测试没有问题,
![snipaste_2019-02-27_09-55-25](https://user-images.githubusercontent.com/17736127/53459897-3e764100-3a76-11e9-8113-b4d2b00912a2.png)

我认为就是运营商的问题了,在公司同样的服务器没有任何问题,(使用的是不同的运营商)
到家就突然出现这个问题,可能就是这2天网络突然抽风了.

感谢回答.
