### ISSUE TITLE
同一个路由下，电脑连有线，手机连同一个路由的wifi，同一个节点，手机可以翻，电脑翻不了！

### ISSUE THREAD

**Issue by myvapour** [shadowsocks/shadowsocks-windows#2243]
同一个路由下，电脑连有线，手机连同一个路由的wifi，同一个节点，手机可以翻，电脑翻不了！

**Comment by chenshaoju** [comment]
请提供你所使用的SS版本号和日志。

**Comment by myvapour** [comment]
> 请提供你所使用的SS版本号和日志。
版本是 Shadowsocks started (4.1.4)
[2019-02-27 10:41:47] 68.183.173.127:17580 timed out
[2019-02-27 10:41:53] 68.183.173.127:17580 timed out
[2019-02-27 10:41:53] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-02-27 11:38:31] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

**Comment by chenshaoju** [comment]
测试了一下你的服务器，不通，但是在第三方检测服务显示正常 https://ipcheck.need.sh/ ，请确保你的其他设备使用的是相同的服务器和配置，尤其是端口配置正确。

**Comment by celeron533** [comment]
另外某些游戏的反作弊软件会干扰ss连接

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
