### ISSUE TITLE
升级下把 长城防火墙已经找到破解模式了

### ISSUE THREAD

**Issue by wanglong167** [shadowsocks/shadowsocks-windows#2244]
升级下把 长城防火墙已经找到破解模式了

**Comment by chenshaoju** [comment]
Shadowsocks协议本身已经基本固定了，但是可以通过插件来达成你想要的目的。
你可以从下列插件中选择你希望使用的：
Kcptun: https://github.com/xtaci/kcptun
Simple-obfs: https://github.com/shadowsocks/simple-obfs
GoQuite: https://github.com/cbeuw/GoQuiet
V2Ray-Plugin: https://github.com/shadowsocks/v2ray-plugin

**Comment by wanglong167** [comment]
3q
