### ISSUE TITLE
错误：无法安全地连接到此页面

### ISSUE THREAD

**Issue by CharlesUESTC** [shadowsocks/shadowsocks-windows#2245]
### Shadowsocks version / 影梭版本
客户端：Shadowsocks-4.1.4
服务器：Shadowsocks 2.8.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
本地环境：Win10, .NET Framework 4.0
服务器：Ubuntu 18.10 x64, iptables未启用，vultr服务器无前置防火墙

### Steps you have tried / 操作步骤
使用PAC模式访问外网，如www.google.com（使用IE，Microsoft Edge浏览器）

### What did you expect to see? / 期望的结果
正常访问

### What did you see instead? / 实际结果
仅可第一次第一次正常访问 https://www.google.com/ ，随后点击搜索按钮后页面打不开。关闭标签页后，以后再访问 https://www.google.com/ ，均无法访问。
浏览器显示信息如下：

>**无法安全地连接到此页面**
>这可能是因为该站点使用过期的或不安全的 TLS 安全设置。如果这种情况持续发生，请与网站的所有者联系。
>TLS 安全设置未设置为默认设置，这也可能导致此错误。

另外，IE使用http协议访问网址 http://www.google.com/ 时，会出现如下错误：
>**500 Internal Privoxy Error**
>Privoxy encountered an error while processing your request:
>**Could not load template file no-server-data or one of its included components.**
>Please contact your proxy administrator.
>If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

#### 配置文件 /etc/shadowsocks/config.json
```
{
    "server":"0.0.0.0",
    "server_port":port,
    "password":"your_password",
    "timeout":1000,
    "method":"aes-256-cfb",
    "fast_open":true
}
```

#### 日志文件
>[2019-02-28 20:57:08] connect to www.google.com:443
>[2019-02-28 20:57:08] Socket connected to ss server: 139.180.128.7:13527
>[2019-02-28 20:57:09] connect to adservice.google.com:443
>[2019-02-28 20:57:09] Socket connected to ss server: 139.180.128.7:13527
>[2019-02-28 20:57:41] connect to www.gstatic.com:443
>[2019-02-28 20:57:41] connect to www.gstatic.com:443
>[2019-02-28 20:57:48] connect to www.google.com:443
>[2019-02-28 20:57:48] connect to www.google.com:443
>[2019-02-28 20:57:48] connect to www.google.com:443
>[2019-02-28 20:57:48] connect to www.google.com:443
>[2019-02-28 20:57:48] connect to www.google.com:443
>[2019-02-28 20:57:48] connect to www.google.com:443
>[2019-02-28 20:57:48] connect to www.google.com:443
>[2019-02-28 20:57:51] 139.180.128.7:13527 timed out
>[2019-02-28 20:57:51] 139.180.128.7:13527 timed out
>[2019-02-28 20:57:51] connect to www.gstatic.com:443
>[2019-02-28 20:57:51] connect to www.gstatic.com:443
>[2019-02-28 20:57:58] 139.180.128.7:13527 timed out
>[2019-02-28 20:57:58] 139.180.128.7:13527 timed out
>[2019-02-28 20:57:58] 139.180.128.7:13527 timed out
>[2019-02-28 20:57:58] 139.180.128.7:13527 timed out
>[2019-02-28 20:57:58] 139.180.128.7:13527 timed out
>[2019-02-28 20:57:58] 139.180.128.7:13527 timed out
>[2019-02-28 20:57:58] 139.180.128.7:13527 timed out
>[2019-02-28 20:57:58] connect to www.google.com:443
>[2019-02-28 20:57:58] connect to www.google.com:443
>[2019-02-28 20:57:58] connect to www.google.com:443
>[2019-02-28 20:57:58] connect to www.google.com:443
>[2019-02-28 20:57:58] connect to www.google.com:443
>[2019-02-28 20:57:58] connect to www.google.com:443
>[2019-02-28 20:57:58] connect to www.google.com:443
>[2019-02-28 20:58:01] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:01] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:01] connect to www.gstatic.com:443
>[2019-02-28 20:58:01] connect to www.gstatic.com:443
>[2019-02-28 20:58:08] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:08] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:08] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:08] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:08] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:08] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:08] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:08] connect to www.google.com:443
>[2019-02-28 20:58:08] connect to www.google.com:443
>[2019-02-28 20:58:08] connect to www.google.com:443
>[2019-02-28 20:58:08] connect to www.google.com:443
>[2019-02-28 20:58:08] connect to www.google.com:443
>[2019-02-28 20:58:08] connect to www.google.com:443
>[2019-02-28 20:58:08] connect to www.google.com:443
>[2019-02-28 20:58:11] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:11] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:18] connect to www.google.com:443
>[2019-02-28 20:58:18] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:18] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:18] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:18] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:18] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:18] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:18] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:28] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:28] connect to www.google.com:443
>[2019-02-28 20:58:38] 139.180.128.7:13527 timed out
>[2019-02-28 20:58:38] connect to www.google.com:443
>[2019-02-28 20:58:48] 139.180.128.7:13527 timed out

**Comment by chenshaoju** [comment]
日志显示到你的服务器超时，如果相同的配置在手机上使用3G/4G网络没有问题的话，请尝试换一个端口看看，是否能解决，如果不能，你可能需要尝试套一个插件看看了：
https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by CharlesUESTC** [comment]
手机好像也连不上。我还是不太明白为什么浏览器一直提示什么不安全的TLS设置（详见上面）,可不可能是浏览器把连接断开了呢?

**Comment by CharlesUESTC** [comment]
换端口还是一样的效果。

**Comment by CharlesUESTC** [comment]
麻烦问一下有没有ss服务端安装和配置的步骤呢？会不会是我哪里没弄对？

**Comment by chenshaoju** [comment]
其实就是连不上（超时，time out），然后代理返回了一个错误页面，因此会提示无法建立安全的连接。

如果可能，请测试一下，请使用tcping 进行测试，看看端口是否能连通。

你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。

这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
```
tcping -t 123.45.67.89 9876
```
其中 123.45.67.89 替换为你的SS服务器地址， 9876 替换为你的你的SS端口，然后回车，此时，如果显示 Port is open ，这说明端口通，如果不通，则可能提示 No response 或 Port is close。

**Comment by CharlesUESTC** [comment]
> 其实就是连不上（超时，time out），然后代理返回了一个错误页面，因此会提示无法建立安全的连接。
> 如果可能，请测试一下，请使用tcping 进行测试，看看端口是否能连通。
> 你可以在 https://www.elifulkerson.com/projects/tcping.php 下载。
> 这是命令提示符应用，你需要在命令提示符（ｃｍｄ）或PowerShell下执行，格式为：
> tcping -t 123.45.67.89 9876
> 
> 其中 123.45.67.89 替换为你的SS服务器地址， 9876 替换为你的你的SS端口，然后回车，此时，如果显示 Port is open ，这说明端口通，如果不通，则可能提示 No response 或 Port is close。

我用了一下这个工具，发现连了一次google之后，把ss客户端退出，然后大约三分钟内 tcping 都是 No reponse，过了之后tcping又显示Port is open。这是被zf hacker攻击了吗？

**Comment by chenshaoju** [comment]
可能是间歇性干扰，建议换一个端口，或者套一个插件试试： https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836
