### ISSUE TITLE
电脑端shadowsocks联网问题，我开手机热点成功，宽带连接失败

### ISSUE THREAD

**Issue by NoBugNoPain** [shadowsocks/shadowsocks-windows#2251]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.4

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows10

### Steps you have tried / 操作步骤
开手机热点，电脑WiFi连接，shadowsocks可以使用，连接google有输出日志文件
电脑宽带连接（校园网）shadowsocks无法使用，并且连接google没有任何输入日志
chrome浏览器

**Comment by chenshaoju** [comment]
这意味着你的校园网可能有监控或者过滤，具体可阅读：https://github.com/shadowsocks/shadowsocks-windows/issues/2239

如果你的服务器是你自己搭建的，请尝试更换端口或者使用插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by NoBugNoPain** [comment]
> 这意味着你的校园网可能有监控或者过滤，具体可阅读：#2239
> 
> 如果你的服务器是你自己搭建的，请尝试更换端口或者使用插件看看：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

这个问题已经解决了，sorry，是之前有人提过的issus，我宽带连接的名字是中文，名称改为英文就有效了，不知道原理是什么
