### ISSUE TITLE
shadowsocks 突然无法使用；服务器端日志无更新

### ISSUE THREAD

**Issue by GasonW** [shadowsocks/shadowsocks-windows#2252]
### Shadowsocks version / 影梭版本
- 服务器端：2.8.2
- MAC客户端：ShadowsocksX-NG 1.7.1
- Windows 客户端： 4.1.4

### Steps you have tried / 操作步骤
1. 2019.02.28前正常使用， 2019.03.01后无法使用
2. 客户端使用其他服务器IP时可用
3. 不可用服务器可以正产ssh
4. 更换端口后仍然不可用
5. 重新安装服务器端ss后仍不可用
7. 检查服务器端日志，发现本地尝试连接的过程未上传到服务器端，即服务器端日志不更新
8. 本地日志显示timeout
9. https://ipcheck.need.sh/ 检查国内外ICMP通过， TCP均未通过。但因为我的服务器是插在路由器后面的一个树莓派，ssh以连接应该能反应TCP是畅通的

### What did you expect to see? / 期望的结果
正常翻墙

### What did you see instead? / 实际结果
无法使用

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
2019-03-02 05:53:24 INFO     starting server at :::38383
2019-03-02 05:56:07 INFO     starting server at :::8383
2019-03-02 06:08:01 INFO     starting server at :::8383
2019-03-02 06:23:55 INFO     starting server at :::443

**Comment by chenshaoju** [comment]
这意味着你的服务器被墙了，请尝试换一个IP看看。

这是一个陷阱，SSH能通，但是其他端口全部不通。

如果你能使用VPS服务商的控制台或VNC到服务器上，可以尝试停止SSH服务，然后将你的SS监听在 22 端口看看是否可以了。

请不要在SSH连接的情况下直接这样操作，会中断当前的SSH连接。

**Comment by Spectre-m** [comment]
> 这意味着你的服务器被墙了，请尝试换一个IP看看。
> 
> 这是一个陷阱，SSH能通，但是其他端口全部不通。
> 
> 如果你能使用VPS服务商的控制台或VNC到服务器上，可以尝试停止SSH服务，然后将你的SS监听在 22 端口看看是否可以了。
> 
> 请不要在SSH连接的情况下直接这样操作，会中断当前的SSH连接。

我也是从3.1开始连不上了，但是IP在CMD中能PING通，请问是什么原因？

**Comment by wxygouweibacao** [comment]
我的也突然连不上了，服务器跑的好好的

**Comment by chenshaoju** [comment]
请使用第三方的测试服务 https://ipcheck.need.sh 进行测试，如果国内TCP不通，说明遭遇了TCP屏蔽。

**Comment by GasonW** [comment]
> 请使用第三方的测试服务 https://ipcheck.need.sh 进行测试，如果国内TCP不通，说明遭遇了TCP屏蔽。

我的服务器是国内外TCP均不通

**Comment by GasonW** [comment]
> 请使用第三方的测试服务 https://ipcheck.need.sh 进行测试，如果国内TCP不通，说明遭遇了TCP屏蔽。

我的服务器是国内外TCP均不通
另外，如果22能通的话。我能否在此基础上添加obfs，继续使用此服务器？

**Comment by chenshaoju** [comment]
这意味着你的服务器可能配置不正确，请检查你的服务器的网络防火墙（iptables/ufw）设置，或者访问你的服务器的服务商网站，是否有前置网络防火墙。

**Comment by wxygouweibacao** [comment]
我的现在好了，之前是日本的，现在换成加拿大的好了，估计把我的ip给封了

**Comment by chenshaoju** [comment]
如果你的情况允许，建议套一个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by Spectre-m** [comment]
您好，TCP也是通的，到底发生了什么😭

**Comment by Spectre-m** [comment]
刚刚再次换了一个端口，现在好了。感动~还是非常谢谢您。

**Comment by yeah188** [comment]
很奇怪，146和8381，不能用了，换别的就好了

**Comment by chenshaoju** [comment]
是的，这种就是端口封锁，换一个端口可以缓解。

不过还是建议套一个插件。

**Comment by ziploe** [comment]
上周五下午 aes-256-cfb 加密算法被干扰了，服务端不能正常解析客户端的请求，换成aes-256-gcm之后恢复了。
之前听闻aes-256-cfb已可以被特征识别，最近又听闻防火墙升级到2.0了，不知到底如何。
各位可以切换下加密算法

**Comment by aaronkingdom** [comment]
哈哈哈， 突然上不了，服务器正常的话 不是端口就是协议被封了， 换一个吧~~~~ 我刚解决了， 揪心！！！！！！！！！！！！！！

**Comment by freeaswind** [comment]
请问如何通过22端口连接shadowsocks   就像是Navicat 的ssh那样使用

**Comment by chenshaoju** [comment]
目前Shadowsocks没有伪装成SSH的插件。

但是，你可以通过SSH的Socks代理来代理Shadowsocks，由于连接受限，可能会很卡。

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history

**Comment by zyh568879280** [comment]
我提供一个思路，我的ss是电脑和手机都上不去，所以我觉得是服务器的问题，可是根据上面的都试了一遍都不行，因为一直timed out，试着把timed out的时间加长到500，结果可以了。。

**Comment by lilalalala** [comment]
谢谢评论，这解决了我的问题
