### ISSUE TITLE
vultr搭建的，shadowsocks客户端始终连接不上，没有数据流

### ISSUE THREAD

**Issue by zchoas** [shadowsocks/shadowsocks-windows#2255]
### Shadowsocks version / 影梭版本
4.1.4

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### What did you see instead? / 实际结果

System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
之后不断 timed out
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
服务器端口是25，一尝试过8234，7777，47000，出的都是一个问题
本地的端口已改成2000，仍不通

**Comment by chenshaoju** [comment]
请使用第三方的测试服务测试你的服务器连通情况： https://ipcheck.need.sh/

**Comment by zchoas** [comment]
> 请使用第三方的测试服务测试你的服务器连通情况：[https](https://ipcheck.need.sh/)：//ipcheck.need.sh/[](https://ipcheck.need.sh/)

![image](https://user-images.githubusercontent.com/44110329/53706226-1ca8ff80-3e64-11e9-92d9-962b6543bb5d.png)

**Comment by chenshaoju** [comment]
请尝试换一个端口看看，是否可以连接。

**Comment by zchoas** [comment]
> 请尝试换一个端口看看，是否可以连接。
> 
> EDIT，我测试了一下，显示是这个样子的：
> ![image](https://user-images.githubusercontent.com/515763/53706744-bc678d00-3e66-11e9-866d-46e97cd1a1b2.png)
> 
> 如果更换端口后仍然不行，请尝试换一个IP，如果可能，请尝试安装一个混淆插件看看：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

请问有什么能用的vps或者IP推荐一下吗

**Comment by chenshaoju** [comment]
出于安全考虑，此处无法推荐可用的VPS。

但是不推荐国内服务商提供的云服务。

**Comment by zchoas** [comment]
> 出于安全考虑，此处无法推荐可用的VPS。
> 
> 但是不推荐国内服务商提供的云服务。

谢谢

**Comment by 78775546946** [comment]
可以考虑换成80端口然后加上http混淆，有的地区（比如我们校园网）端口和混淆，缺一个就会报500错误。可以用libev 版本的ss，插件设置成http混淆。端口80
