### ISSUE TITLE
非预期错误

### ISSUE THREAD

**Issue by lyw821** [shadowsocks/shadowsocks-windows#2256]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.4

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7, 4.5

### What did you see instead? / 实际结果
![image](https://user-images.githubusercontent.com/22490855/53709262-4832e680-3e72-11e9-8da2-9aa3332412c5.png)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
这意味着你的 Microsoft .NET Framework 损坏了，请先尝试使用修复工具进行修复：
https://www.microsoft.com/en-us/download/details.aspx?id=30135

如果仍然不行，请尝试安装／修复安装最新版本的 .NET Framework ：
https://dotnet.microsoft.com/download/thank-you/net472

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2014#issuecomment-423791778
