### ISSUE TITLE
IE代理 系统代理设置问题

### ISSUE THREAD

**Issue by helosky** [shadowsocks/shadowsocks-windows#2257]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.4

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

WIN 10
### Steps you have tried / 操作步骤
关团SS后，IE代理自动打勾，关了又自动打勾，是没恢复记录？跟#1128相似，记得之前也会，删注册表记录？

### What did you expect to see? / 期望的结果

找到原因
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1789#issuecomment-377741641

**Comment by helosky** [comment]
我知道去掉啊，但是它会反复自己自动勾上去的。

**Comment by helosky** [comment]
ipconfig /flushdns
这样应该解决了。
