### ISSUE TITLE
shadowsocks 2.5.2版本可以正常运行 但更新本地pac之后很多网站依然无法访问，求助！

### ISSUE THREAD

**Issue by isla3360** [shadowsocks/shadowsocks-windows#2258]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### What did you expect to see? / 期望的结果
可以快速正常的浏览各大新闻网站、YouTube之类的

### What did you see instead? / 实际结果
都不行 YouTube能打开，但是视频无法加载
再例如 www.bbc.com已经加入了本地PAC，但是仍然无法访问

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
今晚的运行日志……
[2019-03-04 23:33:27] Shadowsocks started
[2019-03-04 23:33:38] Shadowsocks started
[2019-03-04 23:33:40] Shadowsocks started
[2019-03-04 23:37:03] Shadowsocks started
[2019-03-04 23:48:25] Shadowsocks started
[2019-03-04 23:48:50] Shadowsocks started

计算机小白 求助各位前辈！！因为工作需要，上网不便真的很要命，求助！

**Comment by chenshaoju** [comment]
我记得旧版本的PAC地址已经过时了，且不再更新。

请使用新版本： https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by isla3360** [comment]
好的 已经更新啦，感谢博主！！问题解决了！

**Comment by isla3360** [comment]
您好，还想请问您一个问题，就是把shadowsocks退出之后，我连接了WiFi，但是打开浏览器却显示未连接到互联网，必须要开起shadowsocks才能正常上网，这是说完全被代理了吗……这样不会以后不开shadowsocks的话不就会很麻烦？

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/1917

**Comment by isla3360** [comment]
谢谢您！再次成功解决啦！
