### ISSUE TITLE
非预期性错误！谢谢

### ISSUE THREAD

**Issue by Betsyshi** [shadowsocks/shadowsocks-windows#2259]
![_20190305151206](https://user-images.githubusercontent.com/48236923/53787293-56a7fd80-3f59-11e9-8ee1-cdaf8116ff19.png)

**Comment by chenshaoju** [comment]
可能和你设置的快捷键有关，也可能你的配置文件损坏了。

你是否设置了快捷键？如果是，设置了什么？

请使用Windows的记事本打开 Shadowsocks.exe 所在目录下的 gui-config.json 文件，找到
```
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
```
如果可能，请复制你的配置文件中的上面这一段，粘贴上来，然后再删掉你配置文件中的这上面一部分，看看是否能解决。

**Comment by Betsyshi** [comment]
> 可能和你设置的快捷键有关，也可能你的配置文件损坏了。
> 
> 你是否设置了快捷键？如果是，设置了什么？
> 
> 请使用Windows的记事本打开 Shadowsocks.exe 所在目录下的 gui-config.json 文件，找到
> 
> ```
>   "hotkey": {
>     "SwitchSystemProxy": "",
>     "SwitchSystemProxyMode": "",
>     "SwitchAllowLan": "",
>     "ShowLogs": "",
>     "ServerMoveUp": "",
>     "ServerMoveDown": "",
>     "RegHotkeysAtStartup": false
>   }
> ```
> 如果可能，请复制你的配置文件中的上面这一段，粘贴上来，然后再删掉你配置文件中的这上面一部分，看看是否能解决。
我没有设置快捷键，我也不会设置。
我gui-config.json 文件打开是这样的，没有你的这段话
{
  "configs": [
    {
      "server": "",
      "server_port": 8388,
      "password": "",
      "method": "aes-256-cfb",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": "com.shadowsocks.strategy.balancing",
  "index": -1,
  "global": false,
  "enabled": false,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": null,
  "proxy": null,
  "hotkey": null
}

**Comment by chenshaoju** [comment]
你的这个配置文件看起来有点不一样。

请尝试从 https://github.com/shadowsocks/shadowsocks-windows/releases 下载最新版本的SS，单独放到一个新的目录，比如 D:\SS2\ ，然后重新配置一次看看？

**Comment by Betsyshi** [comment]
> 你的这个配置文件看起来有点不一样。
> 
> 请尝试从 https://github.com/shadowsocks/shadowsocks-windows/releases 下载最新版本的SS，单独放到一个新的目录，比如 D:\SS2\ ，然后重新配置一次看看？




现又是这样的了
![qq 20190306091235](https://user-images.githubusercontent.com/48236923/53848701-5149c200-3ff0-11e9-84ef-445a546df798.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2226
