### ISSUE TITLE
(0x80004005): 拒绝访问

### ISSUE THREAD

**Issue by gs666** [shadowsocks/shadowsocks-windows#2261]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.4

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win 10

### Steps you have tried / 操作步骤
正常连接

### What did you see instead? / 实际结果
无法连接。服务器可ping。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
日志报错如下：
```
[2019-03-06 11:15:06] System.Net.Sockets.SocketException (0x80004005): 拒绝访问。
   在 System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   在 Shadowsocks.Util.Sockets.WrappedSocket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   在 Shadowsocks.Proxy.DirectConnect.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.SendToServer(Int32 length, AsyncSession session)
   在 Shadowsocks.Controller.TCPHandler.StartPipe(AsyncSession session)
```

**Comment by chenshaoju** [comment]
请尝试双击托盘区的任务栏小图标，将右下角的代理端口换成 10800 看看？

**Comment by gs666** [comment]
> 请尝试双击托盘区的任务栏小图标，将右下角的代理端口换成 10800 看看？

无效额，日志显示socket 是 connected 的，然后就是日志报的错了。

**Comment by chenshaoju** [comment]
搜了一圈，好像和网络防火墙有关？请检查你计算机上的安全软件是否阻止了SS联网和建立本地监听端口。

**Comment by gs666** [comment]
> 搜了一圈，好像和网络防火墙有关？请检查你计算机上的安全软件是否阻止了SS联网和建立本地监听端口。

没搞定，放弃了

**Comment by chenshaoju** [comment]
方便的话，可以试一下：
https://github.com/shadowsocks/shadowsocks-windows/issues/2157#issuecomment-453891222

可能不太对症。

**Comment by gs666** [comment]
> 方便的话，可以试一下：
> [#2157 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2157#issuecomment-453891222)
> 
> 可能不太对症。

emmm，发现Android手机端没问题的，Windows 按照你的这个处理了还是没用，不知道咋办了==但是非常感谢你~
```
[2019-03-07 14:12:20] Socket connected to ss server: 140.82.52.68:443
[2019-03-07 14:12:20] System.Net.Sockets.SocketException (0x80004005): 拒绝访问。
   在 System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   在 Shadowsocks.Util.Sockets.WrappedSocket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   在 Shadowsocks.Proxy.DirectConnect.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.SendToServer(Int32 length, AsyncSession session)
   在 Shadowsocks.Controller.TCPHandler.StartPipe(AsyncSession session)
```

**Comment by gs666** [comment]
别的电脑，手机端都没问题，就我电脑有问题，继续求救一波。。。开发用的电脑，重装太麻烦了，不然就重装了。。。

**Comment by gs666** [comment]
有出站数据，无入站数据。

**Comment by chenshaoju** [comment]
基本上可以确认你计算机上有什么数据拒绝了SS的本地监听端口，但是具体是什么，可能得你自己慢慢挖掘……

对了，如果你是开发环境，有VS C#环境的话，你下源码以Debug模式启动调试看看？

**Comment by gs666** [comment]
![image](https://user-images.githubusercontent.com/16437749/54103085-ffe16e80-4405-11e9-82f8-e207fc98ad01.png)
@chenshaoju 1080端口使用情况，有没有什么问题~

**Comment by chenshaoju** [comment]
看不出什么问题。。。

**Comment by gs666** [comment]
> 看不出什么问题。。。

哥们，我重装系统了，然后竟然还是不行。和原来一样。。。啊啊啊啊啊啊啊啊

**Comment by gs666** [comment]
是不是存在封锁了我的硬件地址。。。。。。。。。。。。。。。

**Comment by chenshaoju** [comment]
能否做个测试，如果你有手机上，手机在当前网络的WiFi下，和使用3G/4G网络是否可以……？

**Comment by gs666** [comment]
> 能否做个测试，如果你有手机上，手机在当前网络的WiFi下，和使用3G/4G网络是否可以……？

手机可以，手机用电脑热点也可以，用同一个WiFi也可以。。。

**Comment by chenshaoju** [comment]
手机用电脑热点可以的话，说明不是网络问题。

你的电脑是WiFi还是有线？

是不是WiFi可以，但是有线不行？

**Comment by gs666** [comment]
都不行。。。公司有线无线，手机热点都不行。。。醉了，尤其这次重装系统之后不行，心态崩了555

**Comment by chenshaoju** [comment]
我建议你是一下其他的实现，看看能否试用……这个问题非常让人困惑。。。。


https://github.com/Dreamacro/clash

**Comment by celeron533** [comment]
或者是安装了某些特定软件造成。比如其他的代理或VPN，某些杀毒软件，网游反作弊工具，网速检测工具等

**Comment by gs666** [comment]
> 我建议你试一下第三方的实现，看看能否使用……这个问题非常让人困惑。。。。
> 
> https://github.com/Fndroid/clash_for_windows_pkg

感谢推荐，下载下来好一会没搞懂怎么用，把他的文档看完了还是不会用。。。

**Comment by gs666** [comment]
> 或者是安装了某些特定软件造成。比如其他的代理或VPN，某些杀毒软件，网游反作弊工具，网速检测工具等

感谢回答，我试试。。。

**Comment by chenshaoju** [comment]
你不是重装系统了吗……？你重装系统后是否可用？

**Comment by gs666** [comment]
> 你不是重装系统了吗……？你重装系统后是否可用？

前面和你说了，重装了也不能用。。。还是一样的日志，绝望==

**Comment by chenshaoju** [comment]
对了，你的Win10是正式版还是预览版？

**Comment by gs666** [comment]
![image](https://user-images.githubusercontent.com/16437749/54263896-df074d80-45ac-11e9-959d-c1f1c728ec3a.png)

**Comment by chenshaoju** [comment]
你没有装过任何补丁吗？1511？？现在已经是1809了。

![image](https://user-images.githubusercontent.com/515763/54264788-cef06d80-45ae-11e9-9858-6eb7210e3e3c.png)
