### ISSUE TITLE
UWP 应用pac模式下无法正确联网

### ISSUE THREAD

**Issue by KIRI-Z** [shadowsocks/shadowsocks-windows#2262]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本

4.1.4 / 4.1.3.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows 10 1809 Home / Pro

### Steps you have tried / 操作步骤

使用 checknetisolation 允许UWP应用loopback，开启ss，打开edge联网

### What did you expect to see? / 期望的结果

edge正常上网

### What did you see instead? / 实际结果

使用pac模式，edge无法访问如谷歌，可以访问百度；使用全局模式，可以正常使用

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请尝试右击任务栏托盘区的SS图标，选择PAC，再点击“从GFWList更新本地PAC”。

**Comment by KIRI-Z** [comment]
@chenshaoju 谢谢，更新后可以使用了。
问一下我原先的pac是whitelist，chrome可以正常用的，但是edge不行。请问有思路吗？

**Comment by chenshaoju** [comment]
我没有测试过whitelist，我用的也是edge+ss+gfwlist。

也许实现存在一些问题？

![2019-03-06](https://user-images.githubusercontent.com/515763/53860951-96d0b400-401d-11e9-8e5c-d7810d85b41c.png)
