### ISSUE TITLE
[求助]今天更新了新版本的ssr，却出现了如下问题

### ISSUE THREAD

**Issue by wxdalone** [shadowsocks/shadowsocks-windows#2264]
![image](https://user-images.githubusercontent.com/17250085/54067962-9cc6cf00-4281-11e9-9c26-d1612bd4355a.png)
在开启代理后出现了这个对话框，然后也无法访问墙外网站。
有解决方法吗

**Comment by chenshaoju** [comment]
从你的提示来看，你是否指定了插件？

是不是你升级的时候把插件也删掉了？

**Comment by wxdalone** [comment]
我没有指定插件。
然后新版本的软件是github上重新下载的...不知道为什么这样

**Comment by chenshaoju** [comment]
如果将 Shadowsocks.exe 单独移动到一个新目录，比如 D:\SS2\ ，然后手动重新配置一次，是否还会有此问题？

**Comment by wxdalone** [comment]
哎，还是不行。我改用clash算了
