### ISSUE TITLE
是不是可以添加一个订阅的选项？

### ISSUE THREAD

**Issue by chitungho81413** [shadowsocks/shadowsocks-windows#2265]
现在有很多购买的SS都支持订阅的，不知道可否添加上这个功能，但又不想用SSR这个软件。

**Comment by studentmain** [comment]
订阅从来不是shadowsocks标准的一部分，本项目作为标准客户端，应当是其他软件兼容本项目而不是本项目兼容其他软件

**Comment by faydanube** [comment]
1. 直接使用 SSR 订阅进行更新
2. 然后复制 SSR 的 `gui-config.json` 覆盖到 SS
3. 在 SS 直接支持订阅功能之前，使用此方法可以完美解决。
