### ISSUE TITLE
Feature Request: Small changes on context menu of shadowsock-windows

### ISSUE THREAD

**Issue by xuemind** [shadowsocks/shadowsocks-windows#2266]
### Shadowsocks version / 影梭版本
V4.1.5

### Current context menu / 现在的菜单
* Enable system proxy
* Mode
  * PAC
  * Global
...

## expected context menu / 期望的菜单
* disable system proxy / 关闭系统代理
* enable system proxy in PAC mode / 启用PAC模式系统代理
* enable system proxy in global Mode / 启用全局模式系统代理
...

## Why
1. 我帮几位小白朋友安装以后，需要花很多时间解释如何选择。他们经常被这几个选项搞晕，不知道怎么选。有次没有enable proxy就要去选mode，发现是灰色的，以为坏了。
2. 其实配置好以后，代理基本就在这三个状态间切换，1）disabled，2）pac，3）global。我自己在用的时候也觉得点两下才能切换mode也不是很方便，如果这样设置就更简洁，方便使用。

改动应该不大，但作为做过pm的同学有些时候就忍不住想提改进意见。
谢谢！

**Comment by celeron533** [comment]
included in 4.1.6
