### ISSUE TITLE
4.1.5版本，iphone开启自动代理无效，手动有效

### ISSUE THREAD

**Issue by yuxiao97** [shadowsocks/shadowsocks-windows#2267]
4.1.5版本，iphone开启自动代理无效，手动有效，自动配置为：http://192.168.x.x:1080/pac，请问自动时该如何配置？

**Comment by chenshaoju** [comment]
请确保没有选中“PAC”菜单下的“保护本地PAC”。

**Comment by yuxiao97** [comment]
> 请确保没有选中“PAC”菜单下的“保护本地PAC”。

哇，有效果了，感谢！！！
