### ISSUE TITLE
为什么我下载了没有SSR订阅的选项

### ISSUE THREAD

**Issue by karynhuang55** [shadowsocks/shadowsocks-windows#2268]

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2265

**Comment by celeron533** [comment]
因为这不是SSR

**Comment by faydanube** [comment]
1. 直接使用 SSR 订阅进行更新
2. 然后复制 SSR 的 `gui-config.json` 覆盖到 SS
3. 在 SS 直接支持订阅功能之前，使用此方法可以完美解决。
