### ISSUE TITLE
请求Windows客户端支持原生开启TFO（TCP Fast Open）

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [shadowsocks/shadowsocks-windows#2269]
客户端版本：4.1.5
客户端操作系统：Win10 LTSC 1809 Build17763.316
服务端操作系统：Liunx CentOS7 64bit

服务端使用Shadowsocks-libev+Simple-obfs
客户端使用Shadowsocks-Windows+Simple-obfs
服务端和Win10都开启了TCP Fast Open

服务端配置
"fast_open":true,
"plugin":"obfs-server",
"plugin_opts":"obfs=tls;fast-open"  

客户端设置
插件程序obfs-local
插件选项obfs=tls
插件参数obfs-host=github.com;fast-open

使用 grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 87-92 | column -t
测试后发现TFO确实生效了，但是因为使用了Simple-obfs导致网页打开速度变慢，得不偿失，而且一些游戏使用SOCKS5代理后无法正常运行（例：Kancolle），我希望放弃Simple-obfs后也能开启TFO，以达到更棒的延迟和速度。

所以请求Windows客户端支持原生开启TCP Fast Open

**Comment by ShoukakuChuuCC** [comment]
我得知了Microsoft Edge从Windows10 build14352开始支持TFO
但我现在比较习惯使用Google Chrome+Proxy SwitchyOmega
我不希望放弃它们，因为我太爱它们了

**Comment by chenshaoju** [comment]
simple-obfs 已经废弃了，虽然还能用。

你可以试试 v2ray-plugin : https://github.com/shadowsocks/v2ray-plugin

关于原生支持的问题，可移步：　https://github.com/shadowsocks/shadowsocks-windows/pull/1328

**Comment by ShoukakuChuuCC** [comment]
非常感谢你的帮助，我刚开始入门学习这些知识。
虽然我的能力还很弱，但我会继续努力研究。
如果有一天，Windows客户端能加入傻瓜式的一键开启TFO的选项 那么我会非常感激
