### ISSUE TITLE
Unable to connect to the target computer

### ISSUE THREAD

**Issue by wigl** [shadowsocks/shadowsocks-windows#227]
When I open  Client on my computer,the logs display:
System.Net.Sockets.SocketException: Because the target computer actively rejected unable to connect 127.0.0.1:1080
And all time like not networking,not open the browser the logs always display that.
The problem is produced only on the computer,when I use other computers the client is ok.
So my computer have some problems,but I do not know what is the specific problem。
Please help me,thanks.

**Comment by celeron533** [comment]
Hi wigl,
Please try to execute the following command in CMD to find out which process is occupying the port:
> netstat -a -n -o | findstr /r /c:"1080"

OR...
Try to change the port number in SS settings rather than default '1080'

**Comment by wigl** [comment]
Thank you.
When the problem  produced,I have executed the command, no process is occupying the port.
And I also change the port into 1081,8080,8081 etc, the problem still exist.

**Comment by celeron533** [comment]
Does your Windows user account has correct privilege?

**Comment by wigl** [comment]
多谢！我试试看。

**Comment by wigl** [comment]
多谢！我试试看。
