### ISSUE TITLE
相同网络环境,PC无法使用

### ISSUE THREAD

**Issue by k186** [shadowsocks/shadowsocks-windows#2270]
### Config and error log in detail (with all sensitive info masked) / 
日志文件一直显示  connect XXXXX 然后马上又Disconnect XXXXX

**Comment by chenshaoju** [comment]
你好，Shadowsocks和ShadowsocksR是两个东西。

请尝试确保开了系统代理，并且代理模式和PAC正常。

**Comment by k186** [comment]
原因查到了，特殊版本WIN10 抽风，关了防火墙就对了。。

**Comment by AnyWAT** [comment]
> 特殊版本WIN10

😱特供？
