### ISSUE TITLE
今天上午更新系统后，无法使用

### ISSUE THREAD

**Issue by cwjcharles** [shadowsocks/shadowsocks-windows#2271]
今天上午更新系统后。无法使用，显示0xc0000135，之前还是没问题的，我已经用.net修复工具进行了修复，仍然无法使用，我安装了两个更新 分别是KB4494195和kb4493541

**Comment by chenshaoju** [comment]
请问你的操作系统是……？

**Comment by cwjcharles** [comment]
> 请问你的操作系统是……？

奥 win10 版本号18351

**Comment by cwjcharles** [comment]
> 请问你的操作系统是……？
> 
> EDIT:搜了一下，你的是预览版的系统吗？
> https://www.ithome.com/0/414/476.htm
> 
> 如果是这个错误，意味着你的系统上的 .NET Framework 由于某种原因无法被找到，如果可能，请尝试重新安装一次看看？
> https://dotnet.microsoft.com/download/dotnet-framework-runtime/net472

嗯 是的 我是预览版系统  .net无法安装， 安装受阻，微软的解释是这样的 https://docs.microsoft.com/zh-cn/dotnet/framework/install/troubleshoot-blocked-installations-and-uninstallations

**Comment by chenshaoju** [comment]
应该是预览版的系统问题，如果你很着急，建议退回正式版系统。

**Comment by HeylionJackson** [comment]
> 今天上午更新系统后。无法使用，显示0xc0000135，之前还是没问题的，我已经用.net修复工具进行了修复，仍然无法使用，我安装了两个更新 分别是KB4494195和kb4493541

@cwjcharles 我也遇到了，请问您解决了吗

**Comment by cwjcharles** [comment]
> > 今天上午更新系统后。无法使用，显示0xc0000135，之前还是没问题的，我已经用.net修复工具进行了修复，仍然无法使用，我安装了两个更新 分别是KB4494195和kb4493541
> 
> @cwjcharles 我也遇到了，请问您解决了吗

没有 卸载更新后还是不行，设置了还原点，但是因为杀毒软件，还原失败了~~。

**Comment by cwjcharles** [comment]
> > 今天上午更新系统后。无法使用，显示0xc0000135，之前还是没问题的，我已经用.net修复工具进行了修复，仍然无法使用，我安装了两个更新 分别是KB4494195和kb4493541
> 
> @cwjcharles 我也遇到了，请问您解决了吗

用clash for windows吧 我已经切换了

**Comment by flintx** [comment]
已卸载KB44942123.。还是会报错T_T

**Comment by chenshaoju** [comment]
能否截个图？

**Comment by flintx** [comment]
> 能否截个图？

![](https://s2.ax1x.com/2019/04/04/A2J9SA.png)

ss版本是4.1.5，win10版本是1903（内部版本号18356.21）

近期安装的质量更新包括：
- KB4496796
- KB4494123

**Comment by chenshaoju** [comment]
你用的是不是预览版的系统？现在 1903 还没出正式版吧……？

**Comment by flintx** [comment]
> 你用的是不是预览版的系统？现在 1903 还没出正式版吧……？
> 
> ![2019-04-04 (3)](https://user-images.githubusercontent.com/515763/55543755-4459e480-56fc-11e9-840c-2277edcdc295.png)

嗯，我用的是慢速预览版，由于有安全更新的原因，已经无法回滚到正式版了。

推测是程序无法识别预览版带有的.NET 版本，类似的问题也在其他的一些应用里出现了：
- https://answers.microsoft.com/zh-hans/insider/forum/all/%E6%9B%B4%E6%96%B0kb4496796%E4%B9%8B%E5%90%8Enet/cd33b522-6f06-4aa6-8fda-805c00adf7a0
- https://answers.microsoft.com/zh-hans/windows/forum/all/win10%E7%89%88%E6%9C%AC%E5%8F%B71903%E6%93%8D/cf9cd4d7-f1f2-4b06-9428-f82f2470f5da

**Comment by chenshaoju** [comment]
这个估计得等微软修正了。。。

**Comment by Alnovekio** [comment]
新建bat，写入：
start /w pkgmgr /iu:Microsoft-Windows-NetFx3-OC-Package
start /w pkgmgr /iu:Microsoft-Windows-NetFx4-US-OC-Package
start /w pkgmgr /iu:Microsoft-Windows-NetFx3-WCF-OC-Package
start /w pkgmgr /iu:Microsoft-Windows-NetFx4-WCF-US-OC-Package
管理员身份运行，就能强行把那些.NET服务全开开
在windows反馈中心上有人分享的这个方法，我试着成功了
参考：https://www.cnblogs.com/buergege520/p/8532723.html
反正用bat是肯定能把.NET功能打开

**Comment by flintx** [comment]
> 新建bat，写入：
> start /w pkgmgr /iu:Microsoft-Windows-NetFx3-OC-Package
> start /w pkgmgr /iu:Microsoft-Windows-NetFx4-US-OC-Package
> start /w pkgmgr /iu:Microsoft-Windows-NetFx3-WCF-OC-Package
> start /w pkgmgr /iu:Microsoft-Windows-NetFx4-WCF-US-OC-Package
> 管理员身份运行，就能强行把那些.NET服务全开开
> 在windows反馈中心上有人分享的这个方法，我试着成功了
> 参考：https://www.cnblogs.com/buergege520/p/8532723.html
> 反正用bat是肯定能把.NET功能打开

perfect！十分感谢！

**Comment by cwjcharles** [comment]
> 新建bat，写入：
> start /w pkgmgr /iu:Microsoft-Windows-NetFx3-OC-Package
> start /w pkgmgr /iu:Microsoft-Windows-NetFx4-US-OC-Package
> start /w pkgmgr /iu:Microsoft-Windows-NetFx3-WCF-OC-Package
> start /w pkgmgr /iu:Microsoft-Windows-NetFx4-WCF-US-OC-Package
> 管理员身份运行，就能强行把那些.NET服务全开开
> 在windows反馈中心上有人分享的这个方法，我试着成功了
> 参考：https://www.cnblogs.com/buergege520/p/8532723.html
> 反正用bat是肯定能把.NET功能打开

困扰我好久了 还专门咋微软社区里反馈。太感谢了
