### ISSUE TITLE
Chrome+SS or Firefox+SS

### ISSUE THREAD

**Issue by Malerid** [shadowsocks/shadowsocks-windows#2275]
### Shadowsocks version / 影梭版本
Last version downloaded from here

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10 Pro 1809

### Steps you have tried / 操作步骤
I just reinstalled windows10 from the scrath, completely clean and new, nothing installed so far besides browsers:
win10+ss+Chrome = doesn't work
win10+ss+IE/Edge = works fine
win10+ss+Firefox=doesn't work

### What did you expect to see? / 期望的结果
To be able to connect to the internet - youtube, google, etc
baidu, douyu.. etc.. can browse w/o problem

### What did you see instead? / 实际结果
Can't connect, cannot find IP-addres of www.google.com server. 
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by chenshaoju** [comment]
It is your Chrome or Firefox installed 3rd proxy plugins?

Please open Settings in Chrome, Check here:
![image](https://user-images.githubusercontent.com/515763/54472466-c47ae180-4803-11e9-9881-b4c3e3af6f31.png)

**Comment by Malerid** [comment]
> It is your Chrome or Firefox installed 3rd proxy plugins?
> Please open Settings in Chrome, Check here:

Nothing installed, absolutely clean Chrome, as I downloaded it from google.com, I didn't add/change anything.

Also, can see your attached image

**Comment by chenshaoju** [comment]
Make sure you have Enabled "Enable System Proxy", Use "PAC" in "Switch system proxy mode", In PAC menu, Click "Update Local PAC from GFWList", And wait successfully message.

If Still not working, Please put this in the Chrome address bar and press ENTER:
```
chrome://net-internals/#proxy
```
Please take a screenshot and upload here.

PS: It looks like this:
![image](https://user-images.githubusercontent.com/515763/54472697-c181f000-4807-11e9-8b50-6df17fe486fd.png)

**Comment by Malerid** [comment]
I didn't have Proxyswitch Omega installed, but I just downloaded right now.
"Make sure you have Enabled "Enable System Proxy", Use "PAC" in "Switch system proxy mode", In PAC menu, Click "Update Local PAC from GFWList", And wait update successfully message."
I did this, still the same problem
![Image1](https://i.imgur.com/PBmvGcc.png）
![img2[(https://i.imgur.com/CsCGsic.png)

**Comment by Malerid** [comment]
Ethernet? I'm not sure, I just plugging in dorm's cabel in my PC, then using the university's providing connection tool, putting my account info and that's it - i'm connected to the internet

How do I even change it, though? Cause I believe it should be show Chinese characters but it doesn't, some "luan~ma"
![kek](https://i.imgur.com/Wov61q3.png)

**Comment by chenshaoju** [comment]
Your Internet connection type is Ethernet, This is fine.

But this issue still unable find out what happened in your system.

For now, you maybe need to use SwitchyOmega to take the Chrome or Firefox proxy control:
https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif?hl=en

For configure: 
https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList

**Comment by Malerid** [comment]
Jesus, kind of complicated, no way to let Google+SS work again as before? Because I was using these two without any problem, just yesterday after I reinstalled Windows everything's stopped working completely.

"But this issue still unable find out what happened in your system."
I mean, nothing happened from my side for sure: I reinstalled windows10 (format-erased everything), downloaded SS from here, put server/acc/password, etc; downloaded Chrome from official site, opened it. Literally that's all I did so far this today, didn't toggled on-off on system

**Comment by chenshaoju** [comment]
It's should be easy, But I don't know why Proxy settings not working in your system with the 3rd-party browser.

In my system ( Windows 10 x64 17763.379,  You can run `winver` to check version number ) with Chrome 73.0.3683.75, Everything is working correctly.

![2019-03-16 (1)](https://user-images.githubusercontent.com/515763/54473540-24798400-4814-11e9-843e-8ffe2f8b7d03.png)

BTW, Your Windows has updated to the latest?

**Comment by Malerid** [comment]
Yes, the same build as yours, 1809 OS Build 17763.379 Windows 10 Pro.
Damn, so what do you think about helping me out distantly through some app (qq, teamviewer, wechat)? I even willing to pay for it just to make it work again, so frustrated

**Comment by chenshaoju** [comment]
Please do not post personal contact information in here, It's not safe.

There is some case like your issue, but all unsolve: https://github.com/shadowsocks/shadowsocks-windows/issues/2068 https://github.com/shadowsocks/shadowsocks-windows/issues/1853 

Try this:
1. Exit Shadowsocks.
2. Delete ss_win_temp folder in Shadowsocks.exe current directory.
2. Close all browsers.
3. Open Registry edit (regedit.exe)
4. Go to: `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\`
5. Delete `AutoConfigURL` , `ProxyServer` and `ProxyEnable`.
6. Open Shadowsocks.
7. Open Chrome or Firefox again.

**Comment by Malerid** [comment]
I got only "ProxyEnable" optione there

**Comment by chenshaoju** [comment]
Another test:
Right-click Chrome shortcut, Click Properties, Add this line after `chrome.exe`:
```
--proxy-server="socks5://127.0.0.1:1080"
```
eg:  `E:\Chrome\chrome.exe --proxy-server="socks5://127.0.0.1:1080"`

![image](https://user-images.githubusercontent.com/515763/54474922-0ddc2880-4826-11e9-8829-7ecaca3f1842.png)

After restart Chrome, This should force chrome use proxy at 127.0.0.1:1080 .

PS: If you changed local proxy port  in shadowsocks, Change 1080 to your proxy port.

**Comment by Malerid** [comment]
am I stupid?
![da](https://i.imgur.com/6KvBjpq.png)

**Comment by AnyWAT** [comment]
"D:\Program Files\GoogleChromePortable\GoogleChromePortable.exe" --proxy-server="socks5://127.0.0.1:1080"

**Comment by chenshaoju** [comment]
Please do not leave personal contact information in here, No one can promise that person contact you is you wanted that.

In your case, The `Target` should be:
```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --proxy-server="socks5://127.0.0.1:1080"
```

**Comment by Malerid** [comment]
My friend, this worked so far!
Jesus, thank you very much, saved my day n life

**Comment by frei-x** [comment]
我是v2ray 全局pac  , ie  edge都可以访问  唯独chrome不行 ,
然后下载了switchyOmega插件 配置了一下就可以了
