### ISSUE TITLE
各个ss版本在win7,win10现象不一

### ISSUE THREAD

**Issue by fredzhu** [shadowsocks/shadowsocks-windows#2276]
主要说一下我碰到的问题。也许对别人有参考作用。

win7上用了一个早期版本2.3.2，工作正常

同样的2.3.2，同样的2台自架服务器，到win10上就不能用了。报 目标积极拒绝  127.0.0.1:8123

然后下载了最新版4.1.5，win 10上不能用，win7上也不能用，各种问题。（数据只有out 没有in）

然后，下载了3.4.2， win10又能用了....

所以，一是希望4.x的继续改进，二是提醒别人如果碰到问题不能用，就换个版本试试

**Comment by chenshaoju** [comment]
请尝试使用最新版，然后在编辑服务器界面右下角换一个端口看看，比如10800。
