### ISSUE TITLE
添加订阅功能

### ISSUE THREAD

**Issue by Hellogiantha** [shadowsocks/shadowsocks-windows#2277]
希望可以给shadowsocks-windows添加订阅功能，那样即可以通过ss订阅链接批量更新节点，手机端目前还不支持，有些遗憾。

**Comment by studentmain** [comment]
#1703 #1819 #2147 #2265 #2268

**Comment by Hellogiantha** [comment]
> #1703 #1819 #2147 #2265 #2268

好吧，抱歉，我提issue之前忘记搜索了

**Comment by faydanube** [comment]
1. 直接使用 SSR 订阅进行更新
2. 然后复制 SSR 的 `gui-config.json` 覆盖到 SS
3. 在 SS 直接支持订阅功能之前，使用此方法可以完美解决。
