### ISSUE TITLE
在一台电脑上可以访问，另一台不行

### ISSUE THREAD

**Issue by zhaVzha** [shadowsocks/shadowsocks-windows#2278]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
`shadowsocks 4.1.2`
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
`win 10`

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor

和朋友合用，他那里正常，我这里无法上google等网站。试过切换端口等，都没用

**Comment by chenshaoju** [comment]
请尝试右击托盘区的纸飞机小图标，确保启动了“启用系统代理”，代理模式选择了“PAC”。

如果还是不工作，请在PAC菜单下点击“从GFWList更新本地PAC”，如果成功，然后再试。

如果仍然不行，请尝试升级到最新版： https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by declife** [comment]
两台电脑用的同一个网络么，也有可能是网络问题

**Comment by chenshaoju** [comment]
你的日志中没有任何问题，菜单中的“从GFWList更新本地PAC“能工作吗？

**Comment by zhaVzha** [comment]
谢谢大家…尝试过切换pac和全局，也更新过GFWList还是不行，最后换了outline，就可以了，也不知道为啥…有大神能解释下吗

**Comment by chenshaoju** [comment]
不知道……你的日志看不出任何东西，感觉你的浏览器没有经过代理。

你启用了系统代理吗？

**Comment by zhaVzha** [comment]
启用了…操作应该没什么问题，和朋友都比对过

**Comment by chenshaoju** [comment]
你是普通的网线插入电脑就能上网，还是需要PPPoE拨号或者认证后才能上网的网络？

**Comment by zhaVzha** [comment]
校园网，有线接入后还有个软件身份验证下

**Comment by chenshaoju** [comment]
是不是edge浏览器就没问题？如果是，试一下：https://github.com/shadowsocks/shadowsocks-windows/issues/2279#issuecomment-473802569

**Comment by zhaVzha** [comment]
Edge也不行…昨天把这个issues里相关的都看了一遍，也都试了下 不行才提问的

**Comment by gsamful** [comment]
我家里的电脑一切正常，谷歌浏览器和edge都正常，工作地方的电脑不行，谷歌浏览器无法访问

**Comment by gsamful** [comment]
> outline

怎么换outline，什么是outline

**Comment by chenshaoju** [comment]
SS的第三方客户端，注意，好像是全局的：
https://github.com/Jigsaw-Code/outline-client

另外还有一个：
https://github.com/Fndroid/clash_for_windows_pkg
