### ISSUE TITLE
【暂时解决】win10系统下，Edge浏览器可以访问谷歌站点，但是谷歌浏览器无法访问谷歌站点

### ISSUE THREAD

**Issue by gsamful** [shadowsocks/shadowsocks-windows#2279]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请访问 chrome://settings/ ，检查你的Chrome代理是否被第三方插件接管。

![image](https://user-images.githubusercontent.com/515763/54511598-63cae080-498c-11e9-9a75-c77a402738b7.png)

**Comment by gsamful** [comment]
这个地方检查过，没有被接管。访问谷歌总是提示找不到谷歌的ip地址

> 请访问 chrome://settings/ ，检查你的Chrome代理是否被第三方插件接管。

这个地方检查过，没有被接管。访问谷歌总是提示找不到谷歌的ip地址

**Comment by chenshaoju** [comment]
你的上网方式是PPPoE/认证，还是直接插网线就能上网了？

如果是PPPoE或者校园网认证，请尝试将你的网络连接名修改为英文看看。

**Comment by gsamful** [comment]
> 你的上网方式是PPPoE/认证，还是直接插网线就能上网了？
> 如果是PPPoE或者校园网认证，请尝试将你的网络连接名修改为英文看看。

嗯，是校园网认证的，我修改成英文名称，还是提示相同的错误。可以留个邮箱或者其他方便的联系方式交流吗？谢谢

**Comment by gsamful** [comment]
> 你的上网方式是PPPoE/认证，还是直接插网线就能上网了？
> 如果是PPPoE或者校园网认证，请尝试将你的网络连接名修改为英文看看。
> 
> 嗯，是校园网认证的，我修改成英文名称，还是提示相同的错误。可以留个邮箱或者其他方便的联系方式交流吗？谢谢

这个问题困扰我好久了，还是谷歌浏览器好用，同步书签什么的方便，但是就是无法翻墙谷歌，而Edge和IE都可以正常访问，百思不得其解

**Comment by chenshaoju** [comment]
这个问题很奇怪，我没遇到过这个问题，但是有人跟你有相同的问题：https://github.com/shadowsocks/shadowsocks-windows/issues/2275

感觉是有什么东西阻碍了Chrome获得系统代理设置，如果你拨号前退出SS，拨号成功后再打开SS，然后再打开Chrome，能否正常工作？

**Comment by gsamful** [comment]
试过了，不行的，按照2275的方法也试了一遍不行。我觉得也是chrome跟shadowsocks之间的通信出了问题，无法取得代理。

**Comment by AnyWAT** [comment]
改用 ChromePortable 或 MyChrome ？

**Comment by gsamful** [comment]
> 改用 ChromePortable 或 MyChrome ？
谢谢，试过了，可还是不行

**Comment by gsamful** [comment]
我在谷歌安装了SwitchyOmega后，可以了，一开始觉得离线安装这个插件麻烦没弄，现在装了这个插件后，可以了

**Comment by AnyWAT** [comment]
> 现在装了这个插件后，可以了

即先前 Chrome 不认系统的全局或PAC代理？

**Comment by gsamful** [comment]
> 现在装了这个插件后，可以了
> 
> 即先前 Chrome 不认系统的全局或PAC代理？
嗯，用的shadowsocks，不认

**Comment by AnyWAT** [comment]
试试？https://github.com/shadowsocks/shadowsocks-windows/issues/1188#issuecomment-393520197

**Comment by gsamful** [comment]
> 试试？[#1188 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/1188#issuecomment-393520197)

试过不行，我之前用过xx-net，不知道哪个地方搞错了。现在用插件吧，还算顺利，谢谢

**Comment by chenshaoju** [comment]
这个地方是最奇怪的，如果IE/edge可以，说明代理设置成功了。

能否做个测试，启动SS后，工作在启用系统代理，PAC模式下，然后以管理员身份启动命令提示符或PowerShell，然后执行：
```
netsh winhttp import proxy source=ie
```
然后关闭所有Chrome窗口，再打开试试？如果仍然不行，可能需要重启计算机。

**Comment by gsamful** [comment]
> 这个地方是最奇怪的，如果IE/edge可以，说明代理设置成功了。
> 能否做个测试，启动SS后，工作在启用系统代理，PAC模式下，然后以管理员身份启动命令提示符或PowerShell，然后执行：
> netsh winhttp import proxy source=ie
> 
> 然后关闭所有Chrome窗口，再打开试试？如果仍然不行，可能需要重启计算机。

嗯，试过了，不行

**Comment by AnyWAT** [comment]
> 试过不行，我之前用过xx-net，不知道哪个地方搞错了

一直XX-Net、SS，都正常呢

**Comment by gsamful** [comment]
> > 试过不行，我之前用过xx-net，不知道哪个地方搞错了
> 
> 一直XX-Net、SS，都正常呢
我对网络这块内容不是很懂，ss都是看教程一键配置的，所以命令背后网络怎么实现的我不知道的

**Comment by AnyWAT** [comment]
> ss都是看教程一键配置的

👍
不会玩，仅用共享的路过😥

**Comment by funnypro** [comment]
话说 Chrome 下的代理设置是啥样的？

**Comment by chenshaoju** [comment]
Chrome没有独立的代理设置，只能经过系统（IE）的代理设置界面进行配置。

具体可在Chrome访问 chrome://settings/ ，最下面有一个打开代理设置，你点一下就知道了。

**Comment by funnypro** [comment]
> Chrome没有独立的代理设置，只能经过系统（IE）的代理设置界面进行配置。
> 
> 具体可在Chrome访问 chrome://settings/ ，最下面有一个打开代理设置，你点一下就知道了。

我的意思是，要不要看看在非校园网下是啥情况？（在LAN下使用代理）

**Comment by chenshaoju** [comment]
这个和Chrome关系不大，Chrome是直接调用Windows的IE代理的。

如果是拨号连接，那么就是以拨号连接的代理为准，如果是以太网（LAN），那么就是以下面那个局域网设置的为准。

![image](https://user-images.githubusercontent.com/515763/54833880-e8559000-4cf9-11e9-966d-43fe2a4b8733.png)

**Comment by funnypro** [comment]
> 这个和Chrome关系不大，Chrome是直接调用Windows的IE代理的。
> 
> 如果是拨号连接，那么就是以拨号连接的代理为准，如果是以太网（LAN），那么就是以下面那个局域网设置的为准。
> 
> ![image](https://user-images.githubusercontent.com/515763/54833880-e8559000-4cf9-11e9-966d-43fe2a4b8733.png)

我在想，假设这个配置没问题的话，那么这个问题是怎么出现的呢？

**Comment by chenshaoju** [comment]
不知道，只能说可能和系统／软件环境有关，但是具体是怎么回事，目前初步的判断可能和校园网有关。

**Comment by funnypro** [comment]
> 不知道，只能说可能和系统／软件环境有关，但是具体是怎么回事，目前初步的判断可能和校园网有关。

会不会与系统精简有关？

**Comment by chenshaoju** [comment]
不确定，这个很难说清楚。。。

**Comment by funnypro** [comment]
如果能知道Chrome在那时候做什么就好了

**Comment by jkeyvv** [comment]
我也是这个问题，edge可以使用系统代理，火狐和谷歌浏览器只能用代理插件才可以，不知道什么原因，希望可以早点查到问题所在

**Comment by jkeyvv** [comment]
我把拨号连接名称改为英文，然后重启ss客户端，解决了问题。原因不明。

**Comment by gsamful** [comment]
> 我把拨号连接名称改为英文，然后重启ss客户端，解决了问题。原因不明。

在我电脑上试过这方法，不行

**Comment by Armstrongzcl** [comment]
有没有试过将chrome的配置文件删除，或者更换低版本的chrome，我遇到过使用chrome72 和chrome73都无法使用ss代理(pac模式)，但是chrome71是可以的，chromium72、73版本是没有问题的

**Comment by chenshaoju** [comment]
请尝试在更新到最新版本的SS后，删除 Shadowsocks.exe 所在目录下的 pac.txt ，然后重新从 PAC菜单下的`从GFWList更新本地PAC` 看看？

**Comment by slxzh8800** [comment]
@chenshaoju 发现新版本的自带pac是带BOM的UTF-8格式，导致chrome解析js失败，报错PAC_JAVASCRIPT_ERROR，重新保存为正常UTF-8格式后，解决

**Comment by studentmain** [comment]
> 发现新版本的自带pac是带BOM的UTF-8格式

结合#2329 阅读更佳，或许我们需要设法避免提交gzip

**Comment by toolperson** [comment]
我遇到了同样的问题，除了Chrome其余浏览器都可以科学上网

**Comment by toolperson** [comment]
你好，我这个问题是通过删除Shadowsocks.exe所在目录下的所有其余文件，然后重新配置解决的，请作为参考。

**Comment by toolperson** [comment]
另附我遇到的另外部分奇怪情况  [（1）系统代理选择禁用模式的时候仍然可以正常翻墙。（2）在Chrome中使用SwitchyOmega并且配置如下时候，Chrome不能正常翻墙上网。

**Comment by toolperson** [comment]
> 另附我遇到的另外部分奇怪情况 [（1）系统代理选择禁用模式的时候仍然可以正常翻墙。（2）在Chrome中使用SwitchyOmega并且配置如下时候，Chrome不能正常翻墙上网。

不能上传图片，提示：Something went really wrong,and we can't process that file.
不能提供更多详细信息了，我的SwitchyOmega配置也正常

**Comment by zhanhongzhang** [comment]
目前下载了一个谷歌服务助手直接解决-- ,虽然不知道为什么。
![image](https://user-images.githubusercontent.com/43054178/62273658-a808da00-b470-11e9-9648-4bb4f9d49a98.png)
![image](https://user-images.githubusercontent.com/43054178/62273695-ba831380-b470-11e9-8510-3f438b4e80fe.png)

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。

**Comment by ipcjs** [comment]
貌似真的是中文问题。。。
直接对改名没用，删掉，重新拨号就正常了。。。

**Comment by HowardChau** [comment]
> 貌似真的是中文问题。。。
> 直接改名没用，删掉，重新拨号就正常了。。。
> 
> 偷次懒，不改默认名字，没想到踩到这样的坑_(:3」∠)_

一口老血吐出来，果然是这个毛病，先留个记录，我是chrome 80， win10 截至2020.02.27 的最新版本，按照这个方法解决问题，系统默认的名字叫“宽带连接”，删掉，新建一个英文名的，重启ss，解决。

**Comment by ccarol-Y** [comment]
> 我在谷歌安装了SwitchyOmega后，可以了，一开始觉得离线安装这个插件麻烦没弄，现在装了这个插件后，可以了

我也是 好奇怪哟 这是怎么回事儿🧐

**Comment by zhangyangeng** [comment]
貌似是你给chrome装了其他的扩展接管了代理设置，把那些插件卸载试试

**Comment by Codeczh** [comment]
> > 貌似真的是中文问题。。。
> > 直接改名没用，删掉，重新拨号就正常了。。。
> > 偷次懒，不改默认名字，没想到踩到这样的坑_(:3」∠)_
> 
> 一口老血吐出来，果然是这个毛病，先留个记录，我是chrome 80， win10 截至2020.02.27 的最新版本，按照这个方法解决问题，系统默认的名字叫“宽带连接”，删掉，新建一个英文名的，重启ss，解决。

我是v2ray，也这样，就校园网宽带的名称问题，删掉重建连接名为英文，重启v2ray成功。

**Comment by GoodbyeInvoker** [comment]
我没有拨号，就是家用宽带，也是win10下的chrome无法用edge就可以，命令行也翻不了。但是换到linux下所有浏览器包括命令行都可以用。想要知道原因，虽然edge能用就够了。

**Comment by 52sanmao** [comment]
问题了解决了没有，我也遇到同样的问题

**Comment by zWX239090** [comment]
在chrome下输全URL就可以了，比如google，直接google.com不行，但是google.com.hk就可以，同理youtube.com不行，输入www.youtube.com就可以，应该是和GFW规则有点关系，具体不清楚，我这边是这么解决的。

**Comment by Codeczh** [comment]
你好，邮件已收到。
