### ISSUE TITLE
PC端shadowsocks软件可以实现对特定域名/ip的REJECT访问达到去广告的目的嘛？

### ISSUE THREAD

**Issue by Hellogiantha** [shadowsocks/shadowsocks-windows#2281]
在ios平台上，有quantumult，surge类似的代理工具，可以加诸如domain-suffix ads.iqiyi.com reject类的规则，不知道大佬是否也可以利用shadowsocks实现这一功能，已有诸如clash for windows实现。

**Comment by 20051615** [comment]
这种事情用adblock之类的浏览器插件就能搞定了，何必在代理端上再添一层？你可以自己写个去广告sip003插件玩玩（笑）
