### ISSUE TITLE
用Vultr搭建的，手机可以用，电脑连不上

### ISSUE THREAD

**Issue by liuhaofei** [shadowsocks/shadowsocks-windows#2282]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
换了一台朋友的电脑可以连，我的电脑一直连不上，手机可以

**Comment by chenshaoju** [comment]
日志中看不到任何有用的信息，请确保已经启用了系统代理，且工作在PAC模式。

如果仍然不行，请尝试点击PAC菜单下的“从GFWList更新本地PAC”，然后再试。

**Comment by wellswl** [comment]
我也是这个问题

**Comment by chenshaoju** [comment]
请按照上面的帖子操作一下看看。

**Comment by liuhaofei** [comment]
试过了，还是不行

**Comment by chenshaoju** [comment]
更新PAC的时候能更新成功吗？（提示更新成功或者找不到更新），如果能，请尝试使用IE或Edge浏览器，是否能工作？

另外，你的操作系统版本是多少（运行 winver 命令）

**Comment by wellswl** [comment]
我昨天弄了一下，这个版本，路由器的无线网链接，连不上。用手机开的热点可以连上。

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: liuhaofei <notifications@github.com>
发送时间: 星期三, 三月 20, 2019 09:44
收件人: shadowsocks/shadowsocks-windows
抄送: wellswl; Comment
主题: Re: [shadowsocks/shadowsocks-windows] 用Vultr搭建的，手机可以用，电脑连不上 (#2282)


试过了，还是不行

―

**Comment by chenshaoju** [comment]
因为你没有提供日志，所以建议尝试套一个插件看看，可能是运营商的阻止。

https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by wellswl** [comment]
不过以前有个老版的SSR，就可以正常的通过路由器连接外网…这就是我觉得奇怪的地方…

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: Chen Shaoju <notifications@github.com>
发送时间: 星期三, 三月 20, 2019 09:54
收件人: shadowsocks/shadowsocks-windows
抄送: wellswl; Comment
主题: Re: [shadowsocks/shadowsocks-windows] 用Vultr搭建的，手机可以用，电脑连不上 (#2282)


因为你没有提供日志，所以建议尝试套一个插件看看，可能是运营商的阻止。

#2228 (comment)<https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836>

―

**Comment by chenshaoju** [comment]
如果SSR有混淆，可能会具有一些优势。

**Comment by wellswl** [comment]
您的ssr的客户端是否支持PPTP、L2TP、IPSec这三种穿透协议？

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: Chen Shaoju <notifications@github.com>
发送时间: 星期三, 三月 20, 2019 10:34
收件人: shadowsocks/shadowsocks-windows
抄送: wellswl; Comment
主题: Re: [shadowsocks/shadowsocks-windows] 用Vultr搭建的，手机可以用，电脑连不上 (#2282)


如果SSR有混淆，可能会具有一些优势。

―

**Comment by chenshaoju** [comment]
我没有具体研究过SSR，这个我不懂。

**Comment by liuhaofei** [comment]
更新PAC的时候提示：未发现更新，我的系统是win10
![微信图片_20190320163836](https://user-images.githubusercontent.com/30107153/54670645-0f139b00-4b2f-11e9-9866-e9163fdfae5c.png)
![微信图片_20190320163842](https://user-images.githubusercontent.com/30107153/54670651-12a72200-4b2f-11e9-9a00-94805447c43b.png)

**Comment by chenshaoju** [comment]
看起来没有问题，请确保启用了系统代理。

如果仍然不行，请问你是通过普通的LAN插上网线就能上网，还是需要PPPoE拨号或者经过一个认证程序才能正常使用？

**Comment by liuhaofei** [comment]
我用的无线，然后路由器是PPPoe拨号的，我换了一台电脑是可以连的

**Comment by chenshaoju** [comment]
如果已经启用了系统代理，且仍然不工作的话，初步怀疑和系统有关，请尝试升级到 1809 看看能否解决此问题。

**Comment by liuhaofei** [comment]
好吧，我再试试，谢谢

**Comment by liwenjie001** [comment]
我用ssr 今天也遇到了这个问题，不知道为什么。
第一同一局域网手机可以，电脑不行，也不是完全不能链接，使用速度超级慢，第二电脑换另一个节点速度就上来了。不知道为什么。

**Comment by qingwenZhang** [comment]
我也遇到了…… 然而解决顺序，在PAC模式下，进入Shadow的PAC菜单更新 本地PAC 
然后系统代理模式改成全局（这时候能上了）
上一会，然后再改回PAC……
以上是我自己……瞎试的

**Comment by evan667788** [comment]
http://w3.huawei.com/info/cn/doc/viewDoc.do?did=11543313&cata=21072

> 我也遇到了…… 然而解决顺序，在PAC模式下，进入Shadow的PAC菜单更新 本地PAC
> 然后系统代理模式改成全局（这时候能上了）
> 上一会，然后再改回PAC……
> 以上是我自己……瞎试的

靠谱，我就是按这样解决了的。要更新下pac文件

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。

**Comment by MurphyQT** [comment]
> 我也遇到了…… 然而解决顺序，在PAC模式下，进入Shadow的PAC菜单更新 本地PAC
> 然后系统代理模式改成全局（这时候能上了）
> 上一会，然后再改回PAC……
> 以上是我自己……瞎试的

试过了有用。
