### ISSUE TITLE
windows 10 SS在使用PAC模式时会偶尔失效，切换全局模式后回切后正常

### ISSUE THREAD

**Issue by sirstrone** [shadowsocks/shadowsocks-windows#2283]
SS在使用PAC模式时会偶尔失效，切换全局模式后回切后正常
由前一篇issue的经验 利用Process Monitor扫了一个晚上为并未发现可疑进程
![image](https://user-images.githubusercontent.com/30281719/54610082-36b32680-4a8f-11e9-8759-77e6320787da.png)

### Shadowsocks version / 影梭版本
4.1.5

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

**Comment by sirstrone** [comment]
补充 在PAC模式失效时，日志中未显示任何错误 但是日志建立（时间）终止
eg.
[2019-03-19 22:04:16] connect to accounts.google.com:443
[2019-03-19 22:04:16] connect to clients4.google.com:443
[2019-03-19 22:04:16] Socket connected to ss server: 

发现失效时间为 22:05

**Comment by Hellogiantha** [comment]
建议chrome里安装Switchyomega插件，设置本地socks代理 127.0.0.1:1080，这样不用启用shadowsocs的系统代理就可以方便分流，对于telegram也是一样。还有我想问一下，你用win10使用shadowsocks-win，后台不会冗余好多个auto-http-proxy-detection字眼之类的进程吗，我之前用就会遇到，现在使用windows8.1就没啥问题了。

**Comment by chenshaoju** [comment]
在未启用“保护本地PAC”的情况下，当出现问题的时候，浏览器访问 http://127.0.0.1:1080/pac ，能否下回来一个名为 pac 的文件？

**Comment by Hellogiantha** [comment]
![image](https://user-images.githubusercontent.com/44999051/54615378-f9539680-4a98-11e9-8c09-d7e430bd14bf.png)
我的好好的，没启用系统代理，也没保护本地pac，可以下载。

**Comment by chenshaoju** [comment]
那当然。。。你没这个问题的话当然是能下回来的。

现在需要判断这个问题是否是由于是本地代理端口被关闭了。

在出现问题的情况下如果能下回来一个名为 pac 的文件，说明SS的PAC和端口是正常的，可能是浏览器的PAC请求出了问题，也可能是代理地址被替换了（可能性不高，因为ProcMon没有检测到代理URL改变）。

如果下不回来，就说明可能是其他问题。

**Comment by Hellogiantha** [comment]
好吧，不大懂，我的没问题，提issue的来试试呀。

**Comment by chenshaoju** [comment]
我仔细看了一下你的ProcMon设置，你是放在Filter里的，还是放在Highlight里的？

应该是放在Filter里的：
![image](https://user-images.githubusercontent.com/515763/54616092-22285b80-4a9a-11e9-90cd-679a2dca1888.png)

如图所示：
![image](https://user-images.githubusercontent.com/515763/54616219-500da000-4a9a-11e9-889e-1f5b7039364e.png)

**Comment by sirstrone** [comment]
> 建议chrome里安装Switchyomega插件，设置本地socks代理 127.0.0.1:1080，这样不用启用shadowsocs的系统代理就可以方便分流，对于telegram也是一样。还有我想问一下，你用win10使用shadowsocks-win，后台不会冗余好多个auto-http-proxy-detection字眼之类的进程吗，我之前用就会遇到，现在使用windows8.1就没啥问题了。

是的我在进程中发现了许多http-auto-proxy的进程

**Comment by sirstrone** [comment]
> 我仔细看了一下你的ProcMon设置，你是放在Filter里的，还是放在Highlight里的？
> 
> 应该是放在Filter里的：
> ![image](https://user-images.githubusercontent.com/515763/54616092-22285b80-4a9a-11e9-90cd-679a2dca1888.png)
> 
> 如图所示：
> ![image](https://user-images.githubusercontent.com/515763/54616219-500da000-4a9a-11e9-889e-1f5b7039364e.png)

暂时没有出现异常情况，所以无法验证是否能够下载PAC
之前是放置在Highlight中，我放在Filter中试试

**Comment by sirstrone** [comment]
> 那当然。。。你没这个问题的话当然是能下回来的。
> 
> 现在需要判断这个问题是否是由于是本地代理端口被关闭了。
> 
> 在出现问题的情况下如果能下回来一个名为 pac 的文件，说明SS的PAC和端口是正常的，可能是浏览器的PAC请求出了问题，也可能是代理地址被替换了（可能性不高，因为ProcMon没有检测到代理URL改变）。
> 
> 如果下不回来，就说明可能是其他问题。

![image](https://user-images.githubusercontent.com/30281719/54620238-d4632180-4aa0-11e9-80dc-ef53ca56316b.png)
在出现问题时PAC是可以下载的
将AutoConfigURL放在Filter中，依旧没有扫除可疑进程。

**Comment by sirstrone** [comment]
> 那当然。。。你没这个问题的话当然是能下回来的。
> 
> 现在需要判断这个问题是否是由于是本地代理端口被关闭了。
> 
> 在出现问题的情况下如果能下回来一个名为 pac 的文件，说明SS的PAC和端口是正常的，可能是浏览器的PAC请求出了问题，也可能是代理地址被替换了（可能性不高，因为ProcMon没有检测到代理URL改变）。
> 
> 如果下不回来，就说明可能是其他问题。
![image](https://user-images.githubusercontent.com/30281719/54620636-6ec36500-4aa1-11e9-9ac7-94b2e5ee50b7.png)
![image](https://user-images.githubusercontent.com/30281719/54620683-80a50800-4aa1-11e9-9086-bf6800ba507a.png)

在出现问题时PAC是可以下载的
将AutoConfigURL放在Filter中，依旧没有扫除可疑进程。

**Comment by sirstrone** [comment]
> 那当然。。。你没这个问题的话当然是能下回来的。
> 
> 现在需要判断这个问题是否是由于是本地代理端口被关闭了。
> 
> 在出现问题的情况下如果能下回来一个名为 pac 的文件，说明SS的PAC和端口是正常的，可能是浏览器的PAC请求出了问题，也可能是代理地址被替换了（可能性不高，因为ProcMon没有检测到代理URL改变）。
> 
> 如果下不回来，就说明可能是其他问题。
![image](https://user-images.githubusercontent.com/30281719/54620770-a0d4c700-4aa1-11e9-9d2f-633ac2e1ba4e.png)
![image](https://user-images.githubusercontent.com/30281719/54620778-a3cfb780-4aa1-11e9-9da7-6d141a64b7e3.png)

在出现问题时PAC是可以下载的
将AutoConfigURL放在Filter中，依旧没有扫除可疑进程。

**Comment by chenshaoju** [comment]
这一切看起来都很正常。。。

你是否使用了某种拨号连接，比如PPPoE或者认证程序之类的？

**Comment by sirstrone** [comment]
> 这一切看起来都很正常。。。
> 
> 你是否使用了某种拨号连接，比如PPPoE或者认证程序之类的？

是的 由于我当前在校园网环境 因此使用了锐捷认证客服端。
我不确定这个认证器对影梭会产生什么影响

**Comment by chenshaoju** [comment]
请尝试断开锐捷，退出SS，关闭所有浏览器，进入网络连接中，找到锐捷的连接（如果有），检查名字是否为英文的，如果是，改成英文的然后再重试。

如果仍然不行，或者网络连接里没有，请尝试先启动锐捷，链接成功后再启动SS，最后再打开浏览器看看？

**Comment by sirstrone** [comment]
> 请尝试断开锐捷，退出SS，关闭所有浏览器，进入网络连接中，找到锐捷的连接（如果有），检查名字是否为英文的，如果是，改成英文的然后再重试。
> 
> 如果仍然不行，或者网络连接里没有，请尝试先启动锐捷，链接成功后再启动SS，最后再打开浏览器看看？

将链接名字改为英文后/且按照先启动锐捷认证后再启动SS，依然出现了这个问题。

**Comment by chenshaoju** [comment]
不知道了，可能你的系统里有什么东西在间歇性的干扰代理过程，但具体是什么很难说。

如果你使用手机提供的热点上网，不通过锐捷，是否也会有这个问题？

**Comment by sirstrone** [comment]
> 不知道了，可能你的系统里有什么东西在间歇性的干扰代理过程，但具体是什么很难说。
> 
> 如果你使用手机提供的热点上网，不通过锐捷，是否也会有这个问题？

是的 我曾经在非校园网环境中（家里的WiFi）依旧存在这个问题

**Comment by Hellogiantha** [comment]
> > 不知道了，可能你的系统里有什么东西在间歇性的干扰代理过程，但具体是什么很难说。
> > 如果你使用手机提供的热点上网，不通过锐捷，是否也会有这个问题？
> 
> 是的 我曾经在非校园网环境中（家里的WiFi）依旧存在这个问题

如果是这样的话，排除网络原因（你的校园网和非校园网都遇到过这个问题），排除软件问题（好多人正常使用，比如我...），也就是你设备（不确定是电脑系统问题还是别的）问题了，你可以让舍友也安装下下检验下，

**Comment by chenshaoju** [comment]
这个情况似乎和你的操作系统有关，也可能是你的计算机上有什么应用会阻止系统通过带来。

最近有人报告可能和Windows网络防火墙有关，请尝试禁用网络防火墙看看。

如果仍然不行，且很在意这个问题，建议尝试第三方的SS客户端看看，比如Outline（https://github.com/Jigsaw-Code/outline-client，使用TAP网卡），或者 Clash （https://github.com/Fndroid/clash_for_windows_pkg）。

或者，备份数据，重置系统看看了。

**Comment by sirstrone** [comment]
我在Android - Shadowsocks (google) 版的使用上也发现了这个问题。Android版使用的是GFW列表代理，在发生问题的时候无论任何网站都无法链接 （包括GFW之内的网站），同PC端一致，重新连接影梭时恢复正常。
我在怀疑是服务端出现的问题，请问要如何检查是否是服务端存在问题
安装Shadowsocks 的服务端操作系统的是Centos 6 x86 bbr

**Comment by sirstrone** [comment]
> 这个情况似乎和你的操作系统有关，也可能是你的计算机上有什么应用会阻止系统通过带来。
> 
> 最近有人报告可能和Windows网络防火墙有关，请尝试禁用网络防火墙看看。
> 
> 如果仍然不行，且很在意这个问题，建议尝试第三方的SS客户端看看，比如Outline（https://github.com/Jigsaw-Code/outline-client ，全局，使用TAP网卡），或者 Clash （ https://github.com/Fndroid/clash_for_windows_pkg ）。
> 
> 或者，备份数据，重置系统看看了。

我在Android - Shadowsocks (google) 版的使用上也发现了这个问题。Android版使用的是GFW列表代理，在发生问题的时候无论任何网站都无法链接 （包括GFW之内的网站），同PC端一致，重新连接影梭时恢复正常。
我在怀疑是服务端出现的问题，请问要如何检查是否是服务端存在问题
安装Shadowsocks 的服务端操作系统的是Centos 6 x86 bbr
