### ISSUE TITLE
为什么有的服务器用不了？

### ISSUE THREAD

**Issue by dictator2002** [shadowsocks/shadowsocks-windows#2284]
为什么有的服务器用不了？但手机端可以用？如：ss://YWVzLTI1Ni1jZmI6dTFyUldUc3NOdjBwQDE5OC4xOTkuMTAxLjE1Mjo4Mzg4
在android 4.5.7版下就可以用。导入windows 4.1.5版就不能用。

**Comment by chenshaoju** [comment]
Android和Windows在同一个网络下吗？还是属于不同网络？

请尝试换一个端口，不要使用默认的 8388 ，且建议使用 aes-***-gcm 的算法。

**Comment by dictator2002** [comment]
Android和Windows是在同一个网络下的。服务器不是我的，我无法配置端口，我只是用用而已，发现了这个问题，其实这个服务器，用android的高版本的客户端，也用不了。我也不知道是客户端有问题还是，服务器配置有问题。问过android版的管理员，他说是服务器配置问题。

**Comment by chenshaoju** [comment]
我看了一下你的这个配置（没测试），没有任何问题，原因不明。

如果确认客户端配置无误，我还是倾向于服务器配置有问题。

**Comment by dictator2002** [comment]
这个服务器很稳定的。不像别的服务器用两天就不行了。只可惜只能android的4.5.7版以下的才能用。

**Comment by chenshaoju** [comment]
现在伪装成TLS已经是趋势了，无论SS/SSR/V2ray都在往这个趋势发展。

如果是第三方提供的，没有办法，如果是你自己搭建的，建议考虑套个插件： https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history
