### ISSUE TITLE
WIN10每次开机提示shadowsocks错误：端口已经被占用

### ISSUE THREAD

**Issue by wyfang** [shadowsocks/shadowsocks-windows#2286]
![批注 2019-03-21 181021](https://user-images.githubusercontent.com/17900420/54745508-a139a300-4c04-11e9-8e4d-2235beeefed0.png)

每次win10开机都有这个弹窗，但是实际点击确定后都可以正常使用。没点击也能正常使用。

**Comment by chenshaoju** [comment]
请尝试在编辑服务器界面右下角的代理端口中切换一个端口看看，比如10800？

**Comment by oneone1995** [comment]
碰到了一样的问题，查看端口后是并没有程序占用1080端口
![图片](https://user-images.githubusercontent.com/12215935/54795153-08e40280-4c86-11e9-953d-b652817596f7.png)

**Comment by oneone1995** [comment]
@chenshaoju 换了1080

> 
> 
> ![批注 2019-03-21 181021](https://user-images.githubusercontent.com/17900420/54745508-a139a300-4c04-11e9-8e4d-2235beeefed0.png)
> 
> 每次win10开机都有这个弹窗，但是实际点击确定后都可以正常使用。没点击也能正常使用。

你可以正常使用吗？我提示报错之后虽然ss进程还在，但是代理是没法使用的

**Comment by chenshaoju** [comment]
这个问题和 https://github.com/shadowsocks/shadowsocks-windows/issues/1835 一样，是由于端口被系统保留导致的。

**Comment by wyfang** [comment]
我自己解决了。是因为我移动了ss文件夹目录，导致之前那个还在启动项。删除了启动项，没有再出现了。

**Comment by oneone1995** [comment]
@chenshaoju 非常感谢，我通过引用中的`netsh interface ipv4 show excludedportrange protocol=tcp`查看了之后确实是同样的问题。

**Comment by lwg0452** [comment]
改注册表,把ss的键值对全删掉
