### ISSUE TITLE
PAC只有在启动了系统代理的时候才有效？

### ISSUE THREAD

**Issue by xcjiang** [shadowsocks/shadowsocks-windows#2290]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.5

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7

### Steps you have tried / 操作步骤
不启用系统代理

### What did you expect to see? / 期望的结果
PAC生效

### What did you see instead? / 实际结果
PAC不生效，所有的网址都走了代理

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
PAC代理和全局是系统代理的一部分，如果不启用系统代理，就没有办法是用PAC代理或者全局代理。

**Comment by AnyWAT** [comment]
> 不启用系统代理

那就——浏览器扩展使用以白名单 PAC 为前提的Auto Switch https://github.com/MatcherAny/whitelist.pac
如法炮制，也可使用常用的黑名单。。。

**Comment by chenzhegodspeed** [comment]
@chenshaoju  我惊奇的发现。。edge浏览器可以。。。chrome不行。。。chrome我也没安装任何插件。。什么鬼。。刚才打开pdf时候无意间启动了edge浏览模式。点了谷歌主页登陆上去了。。。。

**Comment by Juexe** [comment]
![image](https://user-images.githubusercontent.com/26461438/60176119-fd394680-9847-11e9-99d0-45c3915220b3.png)

参考这篇 https://vimcaw.github.io/blog/2018/03/12/Shadowsocks(R)%E8%AE%BE%E7%BD%AE%EF%BC%9A%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F%E3%80%81PAC%E3%80%81%E4%BB%A3%E7%90%86%E8%A7%84%E5%88%99/

但是新版 Shadowsocks 中右键菜单已经没有「代理规则」这个东西了，大概更新后 PAC 只在系统代理中生效了。

**Comment by chenshaoju** [comment]
代理规则集成到系统代理里了 https://github.com/shadowsocks/shadowsocks-windows/issues/2390#issuecomment-499825102
