### ISSUE TITLE
500的内部错误

### ISSUE THREAD

**Issue by tomuGo** [shadowsocks/shadowsocks-windows#2291]
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by chenshaoju** [comment]
请提供你的操作系统版本、Shadowsocks for Windows 版本，以及你的Shadowsocks for Windows 日志（请记得隐藏你的服务器地址信息）。

**Comment by mghio** [comment]
我的电脑也是报这个错
操作系统版本： win10 专业版
Shadowsocks for Windows 的版本： 4.1.5，

下面是 Shadowsocks for Windows 的日志信息：

[2019-03-30 21:29:16] Shadowsocks started (4.1.5)
[2019-03-30 21:30:06] Shadowsocks started (4.1.5)
[2019-03-30 21:30:11] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-03-30 21:30:12] System.InvalidOperationException: 进程(3984)已退出，因此无法处理请求。
   在 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   在 System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   在 System.Diagnostics.Process.get_MainModule()
   在 Shadowsocks.Controller.PrivoxyRunner.IsChildProcess(Process process)
[2019-03-30 21:30:12] Shadowsocks started (4.1.5)

**Comment by chenshaoju** [comment]
分两个部分：
···
由于远程方已关闭传输流，身份验证失败。
···
这意味着从你的计算机到你的SS服务器的连接被切断了，请尝试换一个端口看看。

···
进程(3984)已退出，因此无法处理请求。
···
这意味着SS内置的Privoxy进程被结束了，请检查是否被安全软件杀掉了。

**Comment by tomuGo** [comment]
解决了，是服务器的ss down掉了
