### ISSUE TITLE
能ping通22开着上网极慢

### ISSUE THREAD

**Issue by verck** [shadowsocks/shadowsocks-windows#2292]
求助
自己的ss大半年一直很稳定。上个星期开始用不了（不行的时候关掉ss的话amazon和apple等外网也上不去），宽带是动态ip当时重启光猫后就能继续正常用ss。前几天开始ss变得很慢打开网页不会显示无法打开网页，google油管都能打开，就是页面显示不完全鼠标下滑也加载不了。同时如果用手机4g就能正常使用，改用家里宽带的话就会出现一样的状况，期间我也试过换ip重装ss也是遇到相同的问题。
（后来试了一下改装酸酸乳就可以正常上网了，可是用两天不到就完全上不了了，现在换了协议和混淆暂时正常了又）

**Comment by chenshaoju** [comment]
该问题已知，只能通过换IP端口＋混淆插件来使用。 https://github.com/shadowsocks/shadowsocks-windows/issues/2228

**Comment by verck** [comment]
> 该问题已知，只能通过换IP端口＋混淆插件来使用。 #2228

感谢回答，#2228我也看了可是我总共两个ip 能ping通22端口也开着的感觉和这个问题不太一样所以来问一下看看。

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2252#issuecomment-468895264

**Comment by Immueggpain** [comment]
Maybe try increase timeout?

**Comment by verck** [comment]
@chenshaoju 这个我看了一下两个服务器的国内外ICMP TCP都是正常的。我待会试试你说的方法看看怎么样  谢谢。

**Comment by verck** [comment]
@Immueggpain Thanks for the suggestion. I don't see any reason that increase timeout can fix the problem since I literally did nothing to the VPS before this happening.  Also the SS with same VPS works fine using 4g network from my phone.

**Comment by Immueggpain** [comment]
@verck You might get lots of dropouts AFTER tcp handshakes(during TLS handshakes)... just one possibility

**Comment by NAVrasZ** [comment]
加了插件，流量一大还是被限速了...

**Comment by MeziEe** [comment]
Github上已经不能下载了而且国内基本很难找到出处…你现在把软件发在哪呢?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: NAVrasZ <notifications@github.com>
发送时间: Thursday, March 28, 2019 12:39:20 AM
收件人: shadowsocks/shadowsocks-windows
抄送: Subscribed
主题: Re: [shadowsocks/shadowsocks-windows] 能ping通22开着上网极慢 (#2292)


加了插件，流量一大还是被限速了...

―

**Comment by verck** [comment]
换了端口正常了。

**Comment by MeziEe** [comment]
我搭建的服务器在美国芝加哥今天白天延迟350~500ms现在稳定230不知道白天会不会还那样

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: verck <notifications@github.com>
发送时间: Thursday, March 28, 2019 3:53:39 AM
收件人: shadowsocks/shadowsocks-windows
抄送: 陌子一; Comment
主题: Re: [shadowsocks/shadowsocks-windows] 能ping通22开着上网极慢 (#2292)


Closed #2292<https://github.com/shadowsocks/shadowsocks-windows/issues/2292>.

―
