### ISSUE TITLE
VirtualBox win8 stop working

### ISSUE THREAD

**Issue by v2boy** [shadowsocks/shadowsocks-windows#2293]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
Application Version:	4.1.5.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win8 en

### Steps you have tried / 操作步骤
install

### What did you see instead? / 实际结果
Shadowsocks has stoped working

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Shadowsocks.exe
  Application Version:	4.1.5.0
  Application Timestamp:	5c81fe96
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.3.9600.18666
  Fault Module Timestamp:	58f32841
  Exception Code:	e0434352
  Exception Offset:	00015608
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	5f25
  Additional Information 4:	5f2531ae070278f893fa99352dadd49e

**Comment by chenshaoju** [comment]
Please install Microsoft .Net Framework: https://dotnet.microsoft.com/download/thank-you/net472
Make sure you has Installed Microsoft Visual C++ 2015 Redistributable (x86) https://www.microsoft.com/en-us/download/details.aspx?id=53840
