### ISSUE TITLE
win10系统PPPOE拨号方式，pac模式下第三方应用不走代理

### ISSUE THREAD

**Issue by g495326** [shadowsocks/shadowsocks-windows#2294]
### Shadowsocks version / 影梭版本

4.1.5

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

win10版本
    企业版 1809
steam版本
     构建时间 ： Mar 5 2019, 15:39:35
      Steam API ：v018
     Steam 组建版本 ：1551832902

### Steps you have tried / 操作步骤

我尝试安装双系统来查找问题。结果如下：
当启动win7，无论PPPOE或者直连路由器的方式，ss在steam客户端下工作正常。
当启动win10，直连路由器，ss在steam客户端下工作正常。
                        PPPOE方式，ss在steam客户端下不走代理。

### What did you expect to see? / 期望的结果

可以在win10，PPPOE方式下，steam客户端能正常通过代理访问。

### What did you see instead? / 实际结果

然而，steam客户端就是不走代理。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

由于不通过ss，日志没有帮助。

**Comment by chenshaoju** [comment]
你的PPPoE连接是中文的吗？如果是，改成英文的看看。

**Comment by g495326** [comment]
> 你的PPPoE连接是中文的吗？如果是，改成英文的看看。

英文的。
![QQ拼音截图20190328185202](https://user-images.githubusercontent.com/41222130/55152214-d86efd80-518a-11e9-8a10-c2fae66bdc66.png)

**Comment by g495326** [comment]
> 你的PPPoE连接是中文的吗？如果是，改成英文的看看。

刚我又测试了下。
当我切换到全局模式时，Steam客户端可以正常工作的。我想是不是pac过滤文件的问题。图1
然而，切换到pac模式下，steam客户端又不能工作了 ，然而相同的网址，IE却能打开了，又说明pac过滤文件没有问题。见图2 ，这让我非常郁闷。
![2019-03-28_191713](https://user-images.githubusercontent.com/41222130/55153956-b1b2c600-518e-11e9-92db-d27191a1d92a.png)
![2019-03-28_191912](https://user-images.githubusercontent.com/41222130/55153959-b37c8980-518e-11e9-812e-2b282a08f67c.png)

**Comment by chenshaoju** [comment]
你的电脑上有Firefox或者Chrome这种第三方的浏览器吗？如果有，用这两个浏览器的任意一个测试一下看看？

我怀疑你的问题和这个类似，IE/Edge可以，但是其他浏览器都不行，也是拨号连接。https://github.com/shadowsocks/shadowsocks-windows/issues/2275

**Comment by g495326** [comment]
> 你的电脑上有Firefox或者Chrome这种第三方的浏览器吗？如果有，用这两个浏览器的任意一个测试一下看看？
> 
> 我怀疑你的问题和这个类似，IE/Edge可以，但是其他浏览器都不行，也是拨号连接。#2275

我测试了360chrome，在设置中启用IE代理，和steam客户端的表现相同，仅在全局模式下有效。pac模式无效。除非使用代理插件，否则pac模式无法使用。

我看了你给出的issue，但没有提到ss的pac模式。

**Comment by chenshaoju** [comment]
如果你先完成PPPoE拨号，然后再启动SS，是否能正常工作？

**Comment by g495326** [comment]
> 你的电脑上有Firefox或者Chrome这种第三方的浏览器吗？如果有，用这两个浏览器的任意一个测试一下看看？
> 
> 我怀疑你的问题和这个类似，IE/Edge可以，但是其他浏览器都不行，也是拨号连接。#2275

我又测试了几个第三方软件，都有相同的问题，
总结：在win10系统(1809)下，PPPOE拨号，pac模式无法使用（(系统自带的IE除外)），全局模式不受影响。
希望尽快修复下，非常感谢！

**Comment by g495326** [comment]
> 如果你先完成PPPoE拨号，然后再启动SS，是否能正常工作？

我已经多次实验了，仍然不行。

**Comment by chenshaoju** [comment]
在PPPoE拨号成功且启动SS后，启动命令提示符，进入你 Shadowsocks.exe 所在目录下的 ss_win_temp 文件夹中，然后执行 `sysproxy.exe query` ，能否看到 `http://127.0.0.1:1080/pac?t=xxxxxxxxxxxxxx` 的部分？如图所示：
![未命名](https://user-images.githubusercontent.com/515763/55162176-322ef200-51a2-11e9-9e16-13291463b361.png)

如果可能，请截个图。

**Comment by g495326** [comment]
> 在PPPoE拨号成功且启动SS后，启动命令提示符，进入你 Shadowsocks.exe 所在目录下的 ss_win_temp 文件夹中，然后执行 `sysproxy.exe query` ，能否看到 `http://127.0.0.1:1080/pac?t=xxxxxxxxxxxxxx` 的部分？如图所示：
> ![未命名](https://user-images.githubusercontent.com/515763/55162176-322ef200-51a2-11e9-9e16-13291463b361.png)
> 
> 如果可能，请截个图。

可以看到，如下所示
![2019-03-28_214603](https://user-images.githubusercontent.com/41222130/55162516-fcd6d400-51a2-11e9-9c37-c645ffd90365.png)

**Comment by chenshaoju** [comment]
因为IE和Edge可以，说明Shadowsocks正确的将代理传递给了系统。

但是Chrome、Firefox和Steam不行，说明这些第三方的应用可能未能正确获取或经过系统代理，这可能是微软的问题。

最后一个测试，请尝试在PPPoE拨号成功后，且启动SS的情况下，进入你的Internet设置，检查你的宽带拨号连接的设置（如下图）和局域网连接的设置，是否指定了自动配置脚本？

![2019-03-28 (1)](https://user-images.githubusercontent.com/515763/55163990-c6e71f00-51a5-11e9-9996-eabf021663b8.png)

![2019-03-28 (2)](https://user-images.githubusercontent.com/515763/55163985-c51d5b80-51a5-11e9-9d72-cb4c6b186ba2.png)

因为我这儿暂时不具备测试PPPoE的拨号，用PPTP连接举个例。

**Comment by g495326** [comment]
> 因为IE和Edge可以，说明Shadowsocks正确的将代理传递给了系统。
> 
> 但是Chrome、Firefox和Steam不行，说明这些第三方的应用可能未能正确获取或经过系统代理，这可能是微软的问题。
> 
> 最后一个测试，请尝试在PPPoE拨号成功后，且启动SS的情况下，进入你的Internet设置，检查你的宽带拨号连接的设置（如下图）和局域网连接的设置，是否指定了自动配置脚本？
> 
> ![2019-03-28 (1)](https://user-images.githubusercontent.com/515763/55163990-c6e71f00-51a5-11e9-9996-eabf021663b8.png)
> 
> ![2019-03-28 (2)](https://user-images.githubusercontent.com/515763/55163985-c51d5b80-51a5-11e9-9d72-cb4c6b186ba2.png)
> 
> 因为我这儿暂时不具备测试PPPoE的拨号，用PPTP连接举个例。

已经设置好的，如下图，希望能助您了解问题！
![2019-03-28_221733](https://user-images.githubusercontent.com/41222130/55165109-c8194b80-51a7-11e9-8c65-cf25032ec199.png)

**Comment by g495326** [comment]
@chenshaoju 我又来提供一些信息了，从表现来看chrome等应用没有把系统代理作为有效的代理。希望对修复问题有帮助。win7&win10对比，见下图

![2019-03-29_102107](https://user-images.githubusercontent.com/41222130/55205718-f0886080-520e-11e9-97cc-57404cab8468.png)
-----------------------------------
![2019-03-29_101825](https://user-images.githubusercontent.com/41222130/55205968-de5af200-520f-11e9-8c94-dc12fec87feb.png)

**Comment by chenshaoju** [comment]
查了一下Chromium的文档，是这么说的：
`
Note that the configured settings "Original proxy settings" may be different from the effective settings (how they are interpreted). This is due to fallbacks which can happen on failure, or proxy discovery.
`
https://www.chromium.org/developers/design-documents/network-stack/debugging-net-proxy

我猜测微软可能修改了什么系统参数，导致了这个问题。

**Comment by g495326** [comment]
@chenshaoju 
我在event标签下，看到大量的js语法错误，如下图，如果是别的语言，还好说，但对js了解不多。
我尝试着换到旧版本，Boom，一切正常了，如此看来，新版本的js脚本有问题。
![2019-03-29_111741](https://user-images.githubusercontent.com/41222130/55208119-f46cb080-5217-11e9-9411-e18f8fcf6ac3.png)

**Comment by chenshaoju** [comment]
这有点说不通，ＩＥ／ＥＤＧＥ可以。
看了一下ｃｈａｎｇｅｌｏｇ，可能和这个有关：
```
- Update the PAC javascript to support user rules in a better way
```

@celeron533

**Comment by g495326** [comment]
@chenshaoju 
经过我多次测试，发现4.1.5版本在根目录下，不存在pac.txt文件将导致pac模式无效，如果手动选择「编辑本地pac文件」或者「从gfwlist更新pac文件」会导致根目录下生成pac.txt文件。如此，ss4.1.5才正常工作。

在旧版本中，即使根目录下不存在pac.txt，浏览器并不会报PAC_JAVACRIPT_ERROR错误，并且可以正常工作。
![QQ拼音截图20190329135150](https://user-images.githubusercontent.com/41222130/55212272-166f2e80-522a-11e9-8a47-06aa7050c72d.png)
![QQ拼音截图20190329135224](https://user-images.githubusercontent.com/41222130/55212275-1838f200-522a-11e9-87fb-4b0519878602.png)

**Comment by chenshaoju** [comment]
理论上说，只要从GFWList更新了本地PAC，就会生成 pac.txt 文件。

但是，对于Windows系统带来说，普通权限的应用（非管理员身份运行），是没有能力在 C:\Program Files (x86)\ 目录下写入文件的。

**Comment by g495326** [comment]
@chenshaoju 
对的，如果选择了更新本地pac，会生成pac.txt文件。(几个版本都是这样)
但是，如果4.1.5版不手动更新，将导致脚本错误。而别的版本不会（即使没有pac.txt文件）。我想这才是问题的关键
当然，解决的办法也很简单，只要用户启用pac模式，将自动生成pac.txt就可以了。

关于权限的问题，我是放在D盘的，至于C盘是不是需要权限并没有测试。

ps：windows的权限设置有点乱糟糟，我研究了好久，也没弄太清。不像Linux的3段位权限。

**Comment by chenshaoju** [comment]
噢，我以为你的系统在D盘，所以……

比较奇怪的是，别的版本，如果没有 pac.txt 文件，那么IE/Edge也会不工作才对。

你是不是之前有用的是4.1.4的pac，升级到4.1.5后没有更新于是出了此问题？更新后就好了？

**Comment by g495326** [comment]
不是，我从来没有移动过pac.txt文件，而且对于win10系统，我是新下载的4.1.5版本。
@chenshaoju 
实际上，旧版本没有pac.txt仍然工作，如下图
![QQ拼音截图20190329142911](https://user-images.githubusercontent.com/41222130/55213829-8c29c900-522f-11e9-827d-c1537175f226.png)

**Comment by g495326** [comment]
@chenshaoju 
具体为什么，我就不清楚了。

**Comment by g495326** [comment]
@chenshaoju 
对了，自动更新系统代理，在4.1.4日志中，看到
Update the system proxy when user-rule.txt is changed

我测试了下，在改变user-rule.txt时，pac.txt文件确实添加了user-rule的内容，但其实并不能自动更新，chrome和IE都无法获取新的pac地址。除非手动「关-开」ss的系统代理，不知你那边可以吗？

**Comment by chenshaoju** [comment]
这个问题很复杂，是这个原因导致的： https://github.com/shadowsocks/shadowsocks-windows/issues/1979

**Comment by g495326** [comment]
@chenshaoju 
#1979 我看过的，但我想和这问题关系不大，看上去是url参数改变后，windows将启动一个pacjsworker.exe来处理，但即使如此，系统代理也并没有自动更新。

我在win7&win10上都测试了，并不能实现代理的自动更新。

当然如果通过curl改变参数的方式不能实现自动更新，还会导致新的问题，那么这种方式确实不可取。

**Comment by chenshaoju** [comment]
实际上就是末尾的那一串乱码，如果这一串乱码变了，那么系统就会从URL更新PAC。

但是每次切换都更新的话，就会多出来很多 pacjsworker.exe ，于是通过减少刷新，降低了更新频率。

**Comment by g495326** [comment]
@chenshaoju 
但是手动更新并没有减少pacjsworker.exe 的产生。

考虑下列情景，我添加了一个网站domain到user-rule中，但是它并不生效。需要我手动把系统代理关开。这种情况仍然会有pacjsworker.exe 进程的产生。

反正都要产生该进程，为何不让添加的规则实时生效呢？

**Comment by chenshaoju** [comment]
这个问题可能得等到微软的下一次更新……下一次更新后这个修改应该会撤回。

**Comment by g495326** [comment]
@chenshaoju 
既然手动更新和自动更新一样产生该pacj*.exe进程，为什么要关闭这个feature？

我只想让其自动更新系统代理，我不关心它是否产生多余的进程。但现在的ss不支持。it's sad!

**Comment by chenshaoju** [comment]
你不关心别人关心……你看那个帖子就知道了，一堆人吐槽。

如果你保存一次 user-rule.txt 就多出来一个 pacjsworker.exe ，对于上面的那些人会很困惑。

PS：我不是开发者，你 sad 也没用。 🌚

**Comment by g495326** [comment]
@chenshaoju 
问题的关键是，你就是手动更新，仍然会产生大量该进程，手动更新不会少，见下图，自动更新也不会多。
PS：我没说别人不应该关心。
![QQ拼音截图20190329182916](https://user-images.githubusercontent.com/41222130/55226711-9d370200-5250-11e9-9a9b-0394e0b12171.png)

**Comment by chenshaoju** [comment]
刚搜了一圈，这个自动更新的功能在今年1月份加入了的： https://github.com/shadowsocks/shadowsocks-windows/pull/2163

但是不知道为什么，后来没有了，我搜了一下合并的PR，没有看到后来取消的记录。

这是当时的讨论：https://github.com/shadowsocks/shadowsocks-windows/issues/2098

**Comment by g495326** [comment]
虽然问题没有完全解决。
@chenshaoju 
**但无论如何，还是感谢你的热心回复。多谢！**

**Comment by celeron533** [comment]
@g495326  thanks for the feedback, will check it soon.
