### ISSUE TITLE
version 4.1.5 QQ浏览器无效

### ISSUE THREAD

**Issue by caiqichang** [shadowsocks/shadowsocks-windows#2296]
version 4.1.5：QQ浏览器无效，Chrome、IE、Edge正常
version 4.1.4：上述浏览器均正常

**Comment by chenshaoju** [comment]
你的操作系统是Windows10吗？是否使用PPPoE拨号或者校园认证上网？

**Comment by caiqichang** [comment]
@chenshaoju 
win10家庭版，浏览器和操作系统都是最新版本，通过WiFi上网，路由器是PPPoE拨号，非校园网，一般家庭网络

**Comment by chenshaoju** [comment]
请测试一下旧版本（4.1.4）是否有该问题：
https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.1.4

**Comment by caiqichang** [comment]
@chenshaoju 
4.1.4 没有问题

**Comment by chenshaoju** [comment]
该问题已知，可能和：https://github.com/shadowsocks/shadowsocks-windows/issues/2294 类似。

**Comment by caiqichang** [comment]
@chenshaoju 
应该是，刚刚测试了一下，4.1.5版本在全局模式下可以，pac模式不行

**Comment by chenshaoju** [comment]
请尝试升级到最新的SS，然后删除 Shadowsocks.exe 所在目录下的 pac.txt ，然后启动SS，再点击PAC菜单下的”从GFWList更新本地PAC“看看？

**Comment by caiqichang** [comment]
> 请尝试升级到最新的SS，然后删除 Shadowsocks.exe 所在目录下的 pac.txt ，然后启动SS，再点击PAC菜单下的”从GFWList更新本地PAC“看看？

根据这个方法解决了，谢谢
