### ISSUE TITLE
各位老哥救命啊，我酸酸突然没速度了，其他人和我的手机都正常用

### ISSUE THREAD

**Issue by Jeyyo** [shadowsocks/shadowsocks-windows#2299]
[2019-04-02 12:20:44] Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 12178 (null)

   在 Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
[2019-04-02 12:20:49] Shadowsocks started
[2019-04-02 12:20:49] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
=========================

[2019-04-02 12:20:49] Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 12178 (null)

   在 Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/releases

请尝试使用最新版本。

**Comment by Jeyyo** [comment]
4.1.5就是处理代理时发生错误然后发生不可恢复的代理错误
[2019-04-02 12:31:52] Shadowsocks started (4.1.5)
[2019-04-02 12:31:52] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-04-02 12:31:52] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-04-02 12:31:53] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-04-02 12:31:54] connect to api.github.com:443
[2019-04-02 12:31:54] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2019-04-02 12:31:54] connect to api.github.com:443
[2019-04-02 12:31:54] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2019-04-02 12:31:54] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请双击任务栏托盘区域的纸飞机图标，在编辑服务器界面能看到你的服务器吗？

**Comment by Jeyyo** [comment]
能编辑添加服务器，还是处理代理时发生错误然后发生不可恢复的代理错误
[2019-04-02 15:23:17] Shadowsocks started (4.1.5)
[2019-04-02 15:23:17] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-04-02 15:23:18] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-04-02 15:23:19] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

**Comment by chenshaoju** [comment]
请退出 SS ，删除 Shadowsocks.exe 所在目录下的 ss_win_temp 目录后再试一下。

**Comment by Jeyyo** [comment]
不行，还是处理代理时发生错误然后发生不可恢复的代理错误

**Comment by Jeyyo** [comment]
4.0.8没有处理代理时发生错误

[2019-04-02 16:31:11] Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 12178 (null)

   在 Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
[2019-04-02 16:31:11] connect to github.com:443
[2019-04-02 16:31:11] Socket connected to ss server: 阿里云 (149.129.67.8:1111)
[2019-04-02 16:31:12] connect to github-production-release-asset-2e65be.s3.amazonaws.com:443
[2019-04-02 16:31:12] Socket connected to ss server: 阿里云 (149.129.67.8:1111)


就是没速度

**Comment by Jeyyo** [comment]
[2019-04-02 16:35:02] Shadowsocks.Util.SystemProxy.ProxyException: Error query options: 12178 (null)

   在 Shadowsocks.Util.SystemProxy.Sysproxy.ExecSysproxy(String arguments)
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)

**Comment by cnfanhua** [comment]
我这偶尔出现安卓和WIN10无法同时使用的问题。

**Comment by Jeyyo** [comment]
我这以前都是正常用的，昨天就突然上不去，更新了一下直接完犊子

**Comment by studentmain** [comment]
重装系统

**Comment by chenshaoju** [comment]
` [2019-04-02 15:23:19] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null) `

这个错误意味着在给您设置系统代理的时候遇到了问题。

如果你有Firefox的话，在Firefox中设置代理服务器为 127.0.0.1 端口 1080 （默认），能否使用？

**Comment by Jeyyo** [comment]
ok了，谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬谢谢大佬
