### ISSUE TITLE
手机能连接ss使用顺畅，但在win10中总是报异常，搞了好几天了,有人遇到过这种问题吗？

### ISSUE THREAD

**Issue by ACDC5** [shadowsocks/shadowsocks-windows#2305]
手机端配置后能正常访问外网，但我的win10不行
win10用的ss版本是4.1.5
ss配置好了后win10连接时一直报“积极拒接”错误，我认为是服务器端口的问题，所以把服务器端口从8877换成443，仍旧报同样的错误；随后把端口改回到原来的8877，则出现连接超时的问题，如下图:
![1](https://user-images.githubusercontent.com/43377515/55731878-8ca33a80-5a4d-11e9-9cf5-89d8dfd41185.PNG)
![2](https://user-images.githubusercontent.com/43377515/55731882-8d3bd100-5a4d-11e9-9e71-47efb3f71014.PNG)

服务地址能ping通

随后去确认了ss客户端的代理端口1080也没被占用，另外win10代理设置关掉后会自启动，代理脚本引用的是ss_win_temp\user-wininet.json中的pacUrl，不知这个是否会影响ss正常的使用？
不知到问题是出在服务器端还是客户端，或者配置的问题？
请大佬们帮忙看看，谢谢

**Comment by chenshaoju** [comment]
请使用第三方工具从有问题的计算机上测试到你的服务器看看是否能连接上：
https://github.com/chenshaoju/tcpportcheck

如果连不上，请尝试让计算机连接手机热点，看看是否能上。

**Comment by ACDC5** [comment]
使用第三方工具也能拼通；连接配置过ss的手机热点可以翻墙

**Comment by chenshaoju** [comment]
有可能你所在的网络存在某种屏蔽或者封锁，也可能是墙的干扰。

如果可能，请尝试套一个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by cuishen** [comment]
你的现象我也出现了，并且也偶尔这样。

**Comment by ACDC5** [comment]
你知道为什么会这样吗?

**Comment by JamosLi** [comment]
都通
持续这样  要疯了
套插件 套的实在米糊糊
装到./autogen.sh  
就configure.ac:4: error: Autoconf version 2.67 or higher is required
configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 63

找来找去都不行。。。。。。。。。。。。。。。。。。。。。

**Comment by chenshaoju** [comment]
如果你用的是Debian，可以以非常简单的命令来安装 simple-obfs （如果你用的是这个的话）：
`apt-get install simple-obfs`

https://packages.debian.org/buster/simple-obfs

**Comment by JamosLi** [comment]
感谢！目前用的contos，之前按照文档布置过，但是没有成功。可能姿势不对。




------------------ 原始邮件 ------------------
发件人: "Chen Shaoju"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 凌晨1:51
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>;
抄送: "黎国康"<910914563@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [shadowsocks/shadowsocks-windows] 手机能连接ss使用顺畅，但在win10中总是报异常，搞了好几天了,有人遇到过这种问题吗？ (#2305)




如果你用的是Debian，可以以非常简单的命令来安装 simple-obfs （如果你用的是这个的话）：
 apt-get install simple-obfs
 
https://packages.debian.org/buster/simple-obfs
