### ISSUE TITLE
编写GFWList用户规则不生效

### ISSUE THREAD

**Issue by 568285876** [shadowsocks/shadowsocks-windows#2307]
### Shadowsocks version / 影梭版本
4.1.5

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
.Net Framework 4.6.2

### Steps you have tried / 操作步骤
（由于这两个网站被公司屏蔽，所有想走pac模式代理链接）
1.编辑GFWList用户规则 添加 ||pan.baidu.com^ ||mail.qq.com^
2.Pac->从GFWList更新本地pac
3.Chrome输入这个两个地址，还是不能访问，全局模式下可以。

### What did you expect to see? / 期望的结果
走pac模式访问网络

### What did you see instead? / 实际结果
没有走pac模式访问网络
发现pac.txt 里面 userrules 这个参数后面跟的参数为乱码，不知道是不是这个原因。
![image](https://user-images.githubusercontent.com/11871366/55851434-24f30980-5b8b-11e9-835e-1f07eefc4b30.png)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by celeron533** [comment]
编码有问题，检查一下userrule文件编码

**Comment by 568285876** [comment]
好吧，中文GB2312，ok了。
