### ISSUE TITLE
蒲公英Ghost win7装机版，双击ss4.1.5版本后出现如下提示

### ISSUE THREAD

**Issue by ikki-hsiao** [shadowsocks/shadowsocks-windows#2308]
![非预期错误](https://user-images.githubusercontent.com/49477275/55920140-4efc0880-5c2b-11e9-8cbc-2d692a774172.jpg)

求解决办法，拜谢！

**Comment by ikki-hsiao** [comment]
win7旗舰版，64位。

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2226
