### ISSUE TITLE
待机后得重启才能连上

### ISSUE THREAD

**Issue by xianshanlai** [shadowsocks/shadowsocks-windows#2309]
版本是4.15，系统win10，每次中午吃饭电脑会自动待机，等回来后打开电脑代理就连不上了，得关掉SS后重新打开才行，记得之前版本从来没有这个问题，新版本得bug吗?

**Comment by chenshaoju** [comment]
请尝试 https://github.com/shadowsocks/shadowsocks-windows/issues/2043 或 https://github.com/shadowsocks/shadowsocks-windows/issues/1343
