### ISSUE TITLE
windows7 gui客户端 cpu单核心异常占满问题

### ISSUE THREAD

**Issue by uinux** [shadowsocks/shadowsocks-windows#231]
您好，我下载的这个软件，我是windows7 64bit 原版安装系统
http://sourceforge.net/projects/shadowsocksgui/files/dist/Shadowsocks-win-2.4.zip/download 

您好，我在使用Shadowsocks gui的时候，经常挂机，但第一天晚上用的好好的，到第二天早上就发现cpu异常占满的问题，是单核心占满，我看了一下Shadowsocks gui客户端是32位的，所以占不了多少核心。但这样足唉导致电脑无法正常使用，关闭后重新打开gui客户端cpu就恢复正常。占满cpu的状态占用了差不多20M内存。请问这个如何解决。或者会在后续版本中解决相关问题吗。

**Comment by chenshaoju** [comment]
以管理员身份运行命令提示符，然后：
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
在有问题的电脑上运行这两个命令，一行一个，运行后重新启动看看。
注意，IP地址会变回自动分配，如果你的电脑的IP地址是手动指定的话，重启后可能需要重新手动设置。

**Comment by uinux** [comment]
好的，感谢，我试下。
