### ISSUE TITLE
开了代理上不去网，不开代理也上不去，只能上github

### ISSUE THREAD

**Issue by jokezhao** [shadowsocks/shadowsocks-windows#2310]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.15

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

win10
### What did you see instead? / 实际结果

一旦开了代理谷歌浏览器就上不去网，不开代理还能上github，但还是上不了谷歌
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
2019-04-11 15:57:05] System.Net.Sockets.SocketException: 不知道这样的主机。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.Start(Byte[] firstPacket, Int32 length)
[2019-04-11 15:57:06] System.Net.Sockets.SocketException: 不知道这样的主机。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.Start(Byte[] firstPacket, Int32 length)
[2019-04-11 15:57:06] System.Net.Sockets.SocketException: 不知道这样的主机。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.Start(Byte[] firstPacket, Int32 length)

**Comment by chenshaoju** [comment]
```不知道这样的主机```
请检查你输入的服务器地址是否有问题，比如空格、中文字符、全角字符等。

如果退出SS也不能上网，请检查下列步骤：https://github.com/shadowsocks/shadowsocks-windows/issues/2040#issuecomment-429540937

**Comment by zhangmingjian180** [comment]
配置的问题，多次尝试，找到一个合适的配置
