### ISSUE TITLE
在便携模式下(Portable Mode)，仍在本程序目录外生成配置文件

### ISSUE THREAD

**Issue by MaxMadcc** [shadowsocks/shadowsocks-windows#2311]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.5

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
开启程序的便携模式(Portable Mode),打开程序的日志查看器(Log Viewer)，会在"%localappdata%\Shadowsocks\Shadowsocks.exe_Url_xxxxx"下生成配置文件

### What did you expect to see? / 期望的结果
1.建议将LogViewerWidth等参数写到本程序目录下的gui-config.json
2.应该是执行了Properties.Settings.Default.Save();方法导致的

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
此问题可在Windows 7上复现。

**Comment by celeron533** [comment]
Portable Mode是用来重定向gui-config.json等服务器相关配置文件的，
LogViewerWidth这种UI相关的内容没有与之关联。
重新推出portable mode是因为有的用户需要使用一些同步软件来同步文件夹数据

**Comment by MaxMadcc** [comment]
那就是说不打算修改了？

**Comment by celeron533** [comment]
目前没有计划
