### ISSUE TITLE
切换代理模式会修改浏览器代理设置

### ISSUE THREAD

**Issue by zl7261** [shadowsocks/shadowsocks-windows#2312]
切换代理系统模式会将浏览器代理设置-->局域网LAN设置,强制修改为pac脚本模式

莫名其妙的,这台机器在这个模式下无法使用chrome浏览器的翻译网页功能

将代理模式修改为代理服务器,改为127.0.0.1:1080,就能使用.

**Comment by chenshaoju** [comment]
我没看懂切换系统代理和Chrome翻译功能之间的关系，可能是你的本地PAC没有更新导致的：

请尝试退出SS，删除 Shadowsocks.exe 所在目录下的 pac.txt ，然后启动SS，再右击托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”看看。

**Comment by zl7261** [comment]
按你的操作做了,还是一样的问题,能翻墙,但是依然不能使用翻译网页(包括翻译插件)

这是wireshark在pac脚本 与 设置代理服务器下的抓包,都是刷新了网页,重置记录,发起翻译网页的请求,


![Snipaste_2019-04-12_14-15-05](https://user-images.githubusercontent.com/27967791/56017828-00399600-5d33-11e9-8817-82a31aa3b715.png)
![Snipaste_2019-04-12_14-16-05](https://user-images.githubusercontent.com/27967791/56017830-00399600-5d33-11e9-8938-93e63e58e589.png)

**Comment by zl7261** [comment]
问题在于切换系统代理模式,会修改浏览器的代理为默认的pac脚本模式.
导致我从全局切换回pac的话,又要去手动修改一次了.
能否切换模式,不去修改浏览器的代理呢

**Comment by chenshaoju** [comment]
如果需要使用系统代理，就必定会修改系统（IE浏览器）的代理设置。

如果你不希望修改系统代理设置，请不要使用（启用）系统代理，如果是只要Chrome用，可以使用第三方的代理插件，比如： https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif

**Comment by zl7261** [comment]
加了这个插件,设置全部代理到ss本地端口,ok了.

很奇怪这个问题,
墙是能翻,就是用了翻译网页功能.
就这台办公的有问题,家里的没问题.
