### ISSUE TITLE
我想把Fn注册成快捷键，但是不行。

### ISSUE THREAD

**Issue by JayHsiang** [shadowsocks/shadowsocks-windows#2313]
我想把F7注册成快捷键，但是不成功，其他的组合快捷键都是可以的。
只是个bug吗？如果是，能不能加一下这个功能。

**Comment by chenshaoju** [comment]
FN键一般是键盘物理层的独立按键，某些键盘可以将FN信号发送给系统，某些则只能响应组合键。

如果你的FN键无法识别，则说明你的键盘无法将FN按下的信号直接发给系统。
