### ISSUE TITLE
你好，我之前买了账户但是现在有点卡，想换个服务器但是shadowsocks之前的网站已经打不开了，所以想问一下有新的网站吗

### ISSUE THREAD

**Issue by AutoAVE** [shadowsocks/shadowsocks-windows#2316]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 不提供任何SS服务（机场），某些SS服务商可能只是使用了 Shadowsocks for Windows 的客户端。

如果你是在某个宣称自己是SS官网的网站上购买的服务，该网站和 Shadowsocks 项目。

Shadowsocks 项目的官方网站是 https://www.shadowsocks.org ，也不提供SS服务。

**Comment by celeron533** [comment]
Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
