### ISSUE TITLE
不好意思，请问这软件能否以UDP浏览网页？

### ISSUE THREAD

**Issue by 860git** [shadowsocks/shadowsocks-windows#2317]
可能我这个问题很白痴，但我还是想尝试问一下。
我知道对于使用UDP的网络游戏，可以通过proxycap将其网络流量转发到shadowsocks-windows。

现在我想问：
如果我在服务器启用-U选项(只开启UDP转发，同时禁用TCP)
那么我在本地这边能不能通过proxycap之类的工具让Chrome可以浏览网页呢？(也就是说通过upd流量访问网页)。

如果问题太白痴，请原谅我，谢谢你们。

**Comment by celeron533** [comment]
浏览器（TCP为主）---> 转化为UDP ---> Socks5 UDP部分 ---> ssclient ---> ssserver

如果只是为了减少TCP指纹，那么可以保持shadowsocks不变，在服务端和客户端套一层UDP隧道，比如kcptun

**Comment by 860git** [comment]
@celeron533 非常感谢，我在ss客户端和ss服务端之间套了kcptun，但是现在我ssh无法连接vps了。。你遇到过这种情况吗

**Comment by celeron533** [comment]
ssh里面操作过多，端口暂时被屏蔽

**Comment by 860git** [comment]
谢谢，希望你说的暂时是真的，我现在ssh和原来ss的端口都连不上了 Д
