### ISSUE TITLE
kcptun在windows端无法使用

### ISSUE THREAD

**Issue by xiebruce** [shadowsocks/shadowsocks-windows#2319]
系统版本：`windows 10 专业版 N 64位`
`shadowsocks.exe`版本：`4.1.5`

我的操作步骤：
1、下载kcptun压缩包，并把其中的`client_windows_amd64.exe`放到了`shadowsocks`所在文件夹，其中以下两个包的`client_windows_amd64.exe`我都试了：
[https://github.com/shadowsocks/kcptun/releases/download/v20170718/kcptun-windows-amd64-20170718.tar.gz](https://github.com/shadowsocks/kcptun/releases/download/v20170718/kcptun-windows-amd64-20170718.tar.gz)
[https://github.com/xtaci/kcptun/releases/download/v20190416/kcptun-windows-amd64-20190416.tar.gz](https://github.com/xtaci/kcptun/releases/download/v20190416/kcptun-windows-amd64-20190416.tar.gz)

2、在`shadowsocks.exe`的服务器配置中修改了以下配置：
- `服务器端口`：填写了远程服务器上的kcptun server的端口=> 4003；
- `插件程序`：填写了`client_windows_amd64.exe`全路径 =>`‪D:\shadowsocks\client_windows_amd64.exe`；
- `插件选项`：保留空白
- `插件参数`：填写的是这一串 => 
```
-l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT% --key gwcTaIa3eUIV7plug --crypt aes-192 --mode fast2 --mtu 512 --datashard 70 --parityshard 30 --sndwnd 1024 --dscp 46 --nocomp 0
```
这些参数在mac版的`shadowsocks-NG`都是可正常使用的，只不过在mac版里是`key=value`(SIP标准)的形式，而在win版是`--key value`(非SIP标准)的形式而已。

除此之外，其他参数填的都是未使用kcptun时的参数，并且未使用kcptun时能正常使用。

填写以上参数后，我点击`确定`，报以下错误：
![image](https://user-images.githubusercontent.com/13575500/56328396-61d58680-61b1-11e9-8111-b6430c2ae324.png)

查看任务管理器，没有启动`client_windows_amd64.exe`，因为报错了，所以没有启动也是正常。

`The System can not find the file specified`, 意思是无法找到`‪D:\shadowsocks\client_windows_amd64.exe`？可是这个路径我是右击→`属性`→`安全`里面复制的，我后面又重新复制了一次，不应该有错。

我都是按 [使用非SIP003规范的插件](https://github.com/shadowsocks/shadowsocks-windows/wiki/%E4%BD%BF%E7%94%A8%E9%9D%9ESIP003%E8%A7%84%E8%8C%83%E7%9A%84%E6%8F%92%E4%BB%B6)  中说的做的，不知道我漏了哪里？

**Comment by celeron533** [comment]
1 相对路径尝试一下
2 直接双击kcptun的可执行文件，看看文件在下载过程中有没有损坏
3 如果你的系统是32位，但程序文件是64位，那么也会有问题
4 查看kcptun可执行文件的权限
5 杀毒软件或安全防护软件干扰，尤其是启发式的防毒软件，一个程序调用另一个隧道程序可是高风险操作

**Comment by xiebruce** [comment]
@celeron533 谢谢，最终发现是权限的问题，右击shadowsocks.exe，选择`以管理员身份运行`即可，我再说一下我成功的经验，有其他人遇到问题可以参考：

1、kcptun的版本与shadowsocks无关，它们是完全独立的软件，在shadowsocks里填参数，只是用shadowsocks调用打开kcptun而已，所以完全可以在[kcptun官方](https://github.com/xtaci/kcptun/releases)下载最新版本即可（比如[kcptun-windows-amd64-20190416.tar.gz](https://github.com/xtaci/kcptun/releases/download/v20190416/kcptun-windows-amd64-20190416.tar.gz)）。

2、Windows端下载的kcptun压缩包里有两个文件，分别是：
```
client_windows_amd64.exe
server_windows_amd64.exe
```
其中我们要使用的是`client_windows_amd64.exe`这个文件，一般把它放在与`shadowsocks.exe`相同的目录下。

3、对于服务器端，一般都用linux吧，我这里以centos为例，在[kcptun官方](https://github.com/xtaci/kcptun/releases)下载最新版本的Linux版（比如：[kcptun-linux-amd64-20190416.tar.gz](https://github.com/xtaci/kcptun/releases/download/v20190416/kcptun-linux-amd64-20190416.tar.gz)）解压后，我们要使用的是其中的`server_linux_amd64`，而`client_linux_amd64`是客户端，在这里用不到。

保存以下内容为`kcptun.conf`，并放在与`server_linux_amd64`相同的目录下：
其中的`target`即为你的shadowsocks服务器端地址，把其中的`8082`改成你的shadowsocks服务器端的端口即可，其他都无需更改，`key`相当于密码，这个你可以改成你自己想要的，客户端填对应的值即可：
```
{
    "listen": ":4002",
    "target": "127.0.0.1:8082",
    "key": "gwcTaI3aeUIV7plug",
    "crypt": "aes-192",
    "mode": "fast2",
    "mtu": 512,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10,
    "log": "/var/log/kcptun.log"
}
```

进入到`server_linux_amd64`所在目录，以root权限运行以下命令即可启动(当然我自己是用supervisor来启动的)：
```
./server_linux_amd64 -c ./kcptun.conf &
```

4、shadowsocks Windows端配置大概如下：
![image](https://user-images.githubusercontent.com/13575500/56335903-e683cd00-61d0-11e9-94e9-80812c708f81.png)
首先要保证不使用kcptun的情况下能正常使用，然后我们在这上面来修改配置：
`端口号`：修改为上边`kcptun.conf` listen参数对应的值（即`4002`，冒号不用写）。
`插件程序`：粘贴上`client_windows_amd64.exe`的路径(右击→属性→安全 里面可以看到路径)。
`插件选项`：留空，不填。

然后勾选“需要命令行参数”后，会出来`插件参数`一项：
`插件参数`：填我给的这个参数即可：
```
-l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT% --key gwcTaI3eUIV7plug --crypt aes-192 --mode fast2 --mtu 512 --datashard 70 --parityshard 30 --sndwnd 1024 --dscp 46
```
这里的值，其实都是跟服务器端的值对应的，如果你不懂就不需要修改，只要保证`--key`后面的那个值与上边的`kcptun.conf`里`key`对应的值一样即可。

应用→保存，**右击`shadowsocks.exe`→`以管理员身份运行`**，如果没有报错，并且在任务管理器里有`client_windows_amd64.exe`这个进程，那么就可以试试能不能使用了。

以上是我的使用经验！

**Comment by chenshaoju** [comment]
理论上和管理员权限无关，如果你的SS放在 **非** `Program Files` 目录中的话。

**Comment by xiebruce** [comment]
@chenshaoju 好吧，我还真的放在非`Program Files`目录 🤣，不过用管理员权限肯定没错哈哈

**Comment by celeron533** [comment]
有时候从网上下载的可执行文件会被windows打上“不安全”标记，需要右键属性 解除锁定。

**Comment by xiebruce** [comment]
@celeron533 在哪个地方标记呢？我看属性里好像没有呀

**Comment by celeron533** [comment]
@xiebruce  https://www.chenyudong.com/wp-content/uploads/2013/01/office-open-file-fails2.png
如果没有，那就没有这个问题

**Comment by xiebruce** [comment]
@celeron533 哦哦，我这边没看到这个，那就是没有
