### ISSUE TITLE
如何通过插件同时使用kcptun、udpspeeder、udp2raw？

### ISSUE THREAD

**Issue by iaston** [shadowsocks/shadowsocks-windows#2321]
现在可以通过插件打开kcptun了，但如果遇到QOS的话，还需要同时使用udpspeeder、udp2raw。在本项目的issues里搜索了一下，作者只是说了“暂时只能用脚本的方式”。但我写的bat或者是exe文件，自己手工启动都正常运行，但放在“插件程序”项目框中，运行了都不成功，包括直接写程序的引用，或者用“cmd /c run.bat"这种方式，或者是把cmd写在插件程序中，将bat或exe写在”插件参数“中，都失败了。请问这里的脚本是指什么脚本语文，如何写呢？

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 支持以命令行的形式传递插件参数，具体请阅读： https://github.com/shadowsocks/shadowsocks-windows/wiki/%E4%BD%BF%E7%94%A8%E9%9D%9ESIP003%E8%A7%84%E8%8C%83%E7%9A%84%E6%8F%92%E4%BB%B6

**Comment by iaston** [comment]
谢谢，关键是插件调用似乎失败了。我在资源管理器中双击可以打开并运行相应的bat文件，但将文件放到ss目录下，再写到插件框中就启动不了。插件框中的程序是有什么要求吗？

**Comment by chenshaoju** [comment]
研究了一下UDPSpeeder，客户端的参数格式是：
` -c -l local_listen_ip:local_port -r server_ip:server_port  [options] `
因此格式为：
`-c -l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT%  [options] `
注意：这个事举例，你不能照搬。

**Comment by iaston** [comment]
这个不是问题的所在呢。因为写到bat中的，所以环境参数都没有用到，端口IP什么的都写死的。现在的问题是bat运行不起来……

**Comment by chenshaoju** [comment]
你可以在插件程序中直接调用 .exe 的，具体格式和说明请参考上面的wiki页面。

**Comment by iaston** [comment]
同学，问下你有没有成功在插件程序中调用其它的程序，比如说调用notepad.exe？你可以测试一下，直接调用会反复运行exe文件的，有可能是每次一个连接请求都会被传到插件中导致反复启动exe文件。
谢谢您的热心回复，但可能还不能解决这个问题。

**Comment by chenshaoju** [comment]
你是这样用的吗？

![未命名](https://user-images.githubusercontent.com/515763/56417620-0f868980-62c7-11e9-81d9-61ea4b5141b1.png)

**Comment by iaston** [comment]
是这样用的。当然，没有插件选项需要输入，我是把各个插件的启动写在一个bat中的，类似于：
a.bat
>start d:\client_windows_amd64-2.exe -l 各种参数
>start d:\udp2raw-win\udp2raw_mp_nolibnet  -c 各种参数
>start d:\udpspeeder\speederv2.exe -c -l0.0.0.0:各种参数

。然后每次一访问网络，ss就会启动N次插件，然后又关闭N次插件。弄得我桌面不断闪现各种kcpdun udp2raw udpspeeder的黑窗口。

**Comment by chenshaoju** [comment]
你这么做的目的是希望嵌套三层再通过你的服务器访问互联网吗……？
如果是这样，不能使用插件程序。

**Comment by iaston** [comment]
是嵌套三层再访问，kcpdun -> udpspeeder ->udp2raw，解决QoS问题。为什么不能用插件程序呢，其实就是不想每次手工点那一下BAT文件，想让ss切换过去时自动打开相应的BAT文件。其实插件与SS只是从属启动一下即可，没有数据交互也没关系的吧。

**Comment by chenshaoju** [comment]
这种建议手动运行，在客户端里指定 127.0.0.1 就行。

不要用插件程序去启动。

**Comment by iaston** [comment]
目前也只能这样了……

**Comment by colalan** [comment]
@iaston 我来回答你这个问题吧，要以插件方式同时开启多个辅助程序，其实是可以实现的，并且很简单！
首先你需要下载一个BAT封装成EXE的小软件，这里推荐用[Quick Batch File Compiler](http://www.dayanzai.me/quick-batch-file-compiler.html)。
这里以同时开如KCPTUN和UDP2RAW为例，打开软件，在“嵌入文件”中添加KCPTUN和UDP2RAW执行文件：
![image](https://user-images.githubusercontent.com/42578965/56454193-a3b42780-637f-11e9-9fb3-6cc6e41c84ba.png)
在“来源”中输入你的bat文件内容：
![image](https://user-images.githubusercontent.com/42578965/56454163-5637ba80-637f-11e9-98d6-17f060f0d725.png)
注意执行文件的路径这里是“%MYFILES%\"。
然后在软件选项中勾选”幽灵应用程序“，这样生成的程序在运行时就不会出现CMD命令窗口了。
![image](https://user-images.githubusercontent.com/42578965/56454232-2e952200-6380-11e9-8762-1c911738e8b2.png)
最后点击“构建”，生成封装后文件，比如这里是666.exe
然后在SS-WIN端添加服务器配置，比如：
![image](https://user-images.githubusercontent.com/42578965/56454325-65b80300-6381-11e9-8c36-12e7105edf35.png)
插件程序就是生成的666.exe，插件参数为空，运行就好了，并且在你切换到其他服务器后，台后中执行的KCPTUN和UDP2RAW程序也会自动退出，是不是很方便。

**Comment by iaston** [comment]
非常感谢@colalan的办法，提供了非常好的思路。不过在实践之后发现了一些问题：
1. 如果用嵌入程序的方式，每次运行时都会弹出防火墙提示，即使这次选择了下次还是会再弹出（估计是因为每次自动解压的路径不同导致的）
1. 这样的调用方式还是会运行很多个udp2raw.exe等文件，只是加了/b参数后看不见了，但在任务管理器中可以看见系统不断开启关闭新的exe进程，如果把/b参数关了，就更明显地看到不断开启新的黑窗口。事实上udp2raw的客户端启动后需要一点时间与服务器端握手，所以不断打开关闭进程后连接效率非常低，基本上无法正常使用。

**Comment by colalan** [comment]
首先可以不用嵌入，只保留bat文档内容，生成的exe与要调用的插件放在同一目录下即可，软件本身支持相对路径。
由于对非SIP003规范的插件提供了%SS_LOCAL_HOST%:%SS_LOCAL_PORT% 和%SS_REMOTE_HOST%:%SS_REMOTE_PORT%传值参数，可以在KCPTUN和UDP2RAW写参数时各用一个。
对于重复开启kcptun.exe或udp2raw.exe进程，这个无解，是SS-WIN自身的原因。
SS-WIN的代码写得一般也是有很多人吐槽的，原本不必区分“插件选项”和“插件参数”的，加个判断就可以知道是不是SIP003规范了。

**Comment by iaston** [comment]
好吧，看来手动运行插件还是最可靠的方法。谢谢。
