### ISSUE TITLE
从4.1.5版本开始，【启用系统代理】按钮消失。更新之后，系统代理默认是关闭状态，导致代理无法使用

### ISSUE THREAD

**Issue by asw3asw** [shadowsocks/shadowsocks-windows#2322]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
目前是这样的，“启用系统代理”整合到了“系统代理”中，禁用就是未选中“启用系统代理”，而PAC模式、全局模式，则是启用系统代理并工作在对应的代理模式。

![image](https://user-images.githubusercontent.com/515763/56452994-d4d72c80-636c-11e9-9dd4-775dfd1c460a.png)

**Comment by asw3asw** [comment]
谢谢！






------------------ 原始邮件 ------------------
发件人: "Chen Shaoju"<notifications@github.com>;
发送时间: 2019年4月20日(星期六) 中午1:08
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>;
抄送: "森木草微笑"<766059062@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shadowsocks/shadowsocks-windows] 从4.1.5版本开始，【启用系统代理】按钮消失。更新之后，系统代理默认是关闭状态，导致代理无法使用 (#2322)




目前是这样的，“启用系统代理”整合到了“系统代理”中，禁用就是未选中“启用系统代理”，而PAC模式、全局模式，则是启用系统代理并工作在对应的代理模式。
