### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by Flysky12138** [shadowsocks/shadowsocks-windows#2323]
我用SSR就能连接上，然而用SS连接上用了一下，过一会儿就连接不上了。但是SS+kcptun又能连接上。

日志信息：
[2019-04-21 20:22:51] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。

**Comment by Flysky12138** [comment]
现在kcptun+SS也连接不上了，只有用ssr才能连接上。

**Comment by Flysky12138** [comment]
找到问题了，是校园网对我的服务器ip进行了屏蔽。用手机热点就行。
这个有什么解决办法没

**Comment by Flysky12138** [comment]
想多了，重新连接后，又用不了了。明显是客户端的问题

**Comment by Flysky12138** [comment]
出现大量 HTTP Auto Proxy Detection Worker Process 进程，10个以上

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836
