### ISSUE TITLE
Conection failed

### ISSUE THREAD

**Issue by nongxi** [shadowsocks/shadowsocks-windows#2326]
Envirment:Windows10 x64+Shadowsocks4.16
Problem:How to make sure if IP blocked By GFW or the Shadowosks problem;Would you mind help me find some reasons?
Details:1. I dispaly shadowsocks-libev Server on Centos 7 x64;2.Installed shadowsocks client on my computer;3.Shadowsocks server works on Centos 7 Server,but when i config in client,connection always failed?I really don't whats the best choice.

**Comment by chenshaoju** [comment]
You can use 3rd-party service to test your server is blocked from China or not: https://ipcheck.need.sh/
