### ISSUE TITLE
Integrate CHNRoutes and ChinaDNS

### ISSUE THREAD

**Issue by clowwindy** [shadowsocks/shadowsocks-windows#233]

**Comment by hnboy2005** [comment]
DNS解析默认是所有的域名都走远程解析,还是只有被墙的网站走远程DNS解析?
PAC里通过黑名单+白名单+CHNRoutes的方式,是否可以缓解DNS污染,同时避免错误的CDN
比如流程是这样的  判断是否黑名单(如果是走代理)-->判断是否白名单(如果是走直连)-->判断是否国内网站(如果是走直连)
因为目标比较大的网站应该都在黑名单或是白名单里,能覆盖大多数情况, 其他的小网站目标小,被DNS污染的可能性小, 是不是就不用ChinaDNS了?

**Comment by clowwindy** [comment]
HTTP 代理本身就是远程解析 DNS 的，不需要再避免 DNS 污染了。这个 issue 和你说的问题无关，主要是用 CHNRoutes 代替 PAC。
