### ISSUE TITLE
电脑变得必须要连ss才能上网，不然就没有网络，求解答

### ISSUE THREAD

**Issue by bruceluo111** [shadowsocks/shadowsocks-windows#2331]
RT 电脑变得必须要连ss才能上网，不然就没有网络，求解答

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1917

**Comment by DengNan51** [comment]
win10系统设置网络里面有一个代理，把手动代理关了，自动检测设置打开就可以了

**Comment by DengNan51** [comment]
> RT 电脑变得必须要连ss才能上网，不然就没有网络，求解答

电脑设置了手动代理到127.0.0.1，当没有打开代理软件的时候肯定是连接不败的，所以手动代理关闭，正常来说使用自动的比较科学.....

**Comment by DengNan51** [comment]
> #1917

而且下次你打开ss的时候，只要你打开了自动检测设置，那么下面的脚本地址就会自动给你配置地址，

**Comment by bruceluo111** [comment]
> 
> 
> > #1917
> 
> 而且下次你打开ss的时候，只要你打开了自动检测设置，那么下面的脚本地址就会自动给你配置地址

感谢，已经解决！

**Comment by bruceluo111** [comment]
> 
> 
> #1917

感谢！已经解决！
