### ISSUE TITLE
严重BUG

### ISSUE THREAD

**Issue by william-abel** [shadowsocks/shadowsocks-windows#2332]
各位开发大哥，这几个版本的代码质量有点差了 用了那么多年了 这几个版本 全是问题
动不动就断线 动不动就错误异常 无法正常使用了已经

**Comment by chenshaoju** [comment]
请具体描述问题，提供日志等信息，以便解决问题。

**Comment by joviqiao** [comment]
@chenshaoju  window10 64位，经常出现 没有勾选启用那一行的情况啊！！

**Comment by chenshaoju** [comment]
你是指启用系统代理吗？

集成到了“系统代理”选项中。禁用就是禁用系统代理，PAC模式和全局模式就是启用系统代理并使用对应的代理模式。

**Comment by william-abel** [comment]
> 各位开发大哥，这几个版本的代码质量有点差了 用了那么多年了 这几个版本 全是问题
> 动不动就断线 动不动就错误异常 无法正常使用了已经

老版本的在哪里下载啊

**Comment by william-abel** [comment]
> 各位开发大哥，这几个版本的代码质量有点差了 用了那么多年了 这几个版本 全是问题
> 动不动就断线 动不动就错误异常 无法正常使用了已经

没有记录 本身我也是小程序 只是没想到这几个版本无法正常使用

**Comment by AnyWAT** [comment]
> 老版本的在哪里下载啊

🤣BUG严重。。。

**Comment by william-abel** [comment]
> > 老版本的在哪里下载啊
> 
> 🤣BUG严重。。。

无法正常使用还不是验证BUG么...

**Comment by AnyWAT** [comment]
😜找不到（各版本）下载BUG严重不？

**Comment by william-abel** [comment]
> 😜找不到（各版本）下载BUG严重不？

啥意思

**Comment by joviqiao** [comment]
@chenshaoju  完美  原来如此 我发现任何异常 只要 更新 net framework 就能够解决。。。

**Comment by chenshaoju** [comment]
所有 Shadowsocks for Windows 的发布版本均可在 https://github.com/shadowsocks/shadowsocks-windows/releases 找到。

**Comment by VOHeart** [comment]
服了，还有这么提交bug的？什么问题不说就说有问题，指着开发者靠魔力给你解决？

**Comment by william-abel** [comment]
1
