### ISSUE TITLE
win10 4.1.6版本在c盘无法开机自启

### ISSUE THREAD

**Issue by GODOFHOU** [shadowsocks/shadowsocks-windows#2333]
4.0.9及之前的版本放在C盘可以自启，之后的版本还有现在用的4.1.6放到C盘不能开机自启。

放到其它磁盘可以自启

**Comment by chenshaoju** [comment]
你好，我测试了一下，并没有问题。

请检查是否有安全软件进行拦截。

![2019-04-30 (1)](https://user-images.githubusercontent.com/515763/56960809-9d465c80-6b84-11e9-8eb2-f357375781d9.png)

**Comment by GODOFHOU** [comment]
> 你好，我测试了一下，并没有问题。
> 
> 请检查是否有安全软件进行拦截。
> 
> ![2019-04-30（1）](https://user-images.githubusercontent.com/515763/56960809-9d465c80-6b84-11e9-8eb2-f357375781d9.png)

解决了，C盘安装目录权限全部允许就好了
![image](https://user-images.githubusercontent.com/30817974/57004008-9f98cd00-6bfd-11e9-99b8-13cba4fc1338.png)
