### ISSUE TITLE
W7系统下 上传很慢

### ISSUE THREAD

**Issue by xiaorun1990** [shadowsocks/shadowsocks-windows#2334]
同一个节点，w7系统FACEBOOK YOUTUBE 上传只有50KB    W10平均500-1000KB
手机普遍也300-400KB 
W7系统是不是有问题。
用过一些机场的客户端 速度也比SS客户端高很多，怀疑W7的客户端有问题

**Comment by chenshaoju** [comment]
服务器在英国的测试结果：
![image](https://user-images.githubusercontent.com/515763/57061845-0519b600-6cf1-11e9-86e1-21722921b5fa.png)

请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。

重启后看看效果是否有改善。

**Comment by xiaorun1990** [comment]
按你的方法试了 没有用 还是老样子  现在用V2RAY  上传速度立刻恢复到800-1000KB  看来W7的SS客户端真的是有问题，试了公司里的W7电脑  也是只有50KB的上传

**Comment by chenshaoju** [comment]
我用的也是Win7，但是没这个问题，我又找了一个日本的服务器测试了一下：

![image](https://user-images.githubusercontent.com/515763/57083322-efc17d80-6d2a-11e9-86ba-72c027c17b8e.png)
