### ISSUE TITLE
Error: "Could not find file 'C:\...\Desktop\Shadowsocks-4.1.6\ss_win_temp'."

### ISSUE THREAD

**Issue by rchokr** [shadowsocks/shadowsocks-windows#2335]
### Shadowsocks version
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Microsoft 10 Home
.NET Framework 4.8

### Steps you have tried / 操作步骤
1) Previous Shadowsocks versions. 
2) Upgrade your .NET Framework to latest release and install all patches against it.
3) Reset the ipv4, ipv6 and winsock using the ```netsh reset``` command (sometimes the Winsock and TCP/IP protocol is corrupted for some reason)
4) Run Shadowsocks as administrator

### What did you expect to see? / 期望的结果
When I double-click on Shadowsocks.exe the expected behaviour is that Shadowsocks starts up and works. Instead, I get the error below.

### What did you see instead? / 实际结果
---------------------------
1. [Screenshot ](https://www.dropbox.com/s/mt3qypmm3n013gw/Shadowsocks_wVkpkqY3pj.png?dl=0)of the error message.

2. Error message

```
*Shadowsocks non-UI Error*
Unexpected error, shadowsocks will exit. Please report to https://github.com/shadowsocks/shadowsocks-windows/issues 

System.TypeInitializationException: The type initializer for 'Shadowsocks.Controller.AvailabilityStatistics' threw an exception. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\Robert\Desktop\Shadowsocks-4.1.6\ss_win_temp'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)

   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)

   at System.IO.Directory.CreateDirectory(String path)

   at Shadowsocks.Util.Utils.GetTempPath()

   at Shadowsocks.Util.Utils.GetTempPath(String filename)

   at Shadowsocks.Controller.AvailabilityStatistics..cctor()

   --- End of inner exception stack trace ---

   at Shadowsocks.Controller.AvailabilityStatistics.get_Instance()

   at Shadowsocks.Controller.ShadowsocksController..ctor()

   at Shadowsocks.Program.Main(String[] args)
---------------------------
OK   
---------------------------
```

### Config and error log in detail (with all sensitive info masked)
No log available.

**Comment by rchokr** [comment]
Update:
1) I created an empty folder called `ss_win_temp`
2) Shadowsocks now starts, but gives of the following error:
a) [Screenshot ](https://www.dropbox.com/s/a8w1gpzb44pvvxk/Shadowsocks_8HUSJxekLO.png?dl=0)of the error
b) Error message:

```
Shadowsocks Error: The system cannot find the file specified

System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified

   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)

   at System.Diagnostics.Process.Start()

   at Shadowsocks.Controller.PrivoxyRunner.Start(Configuration configuration)

   at Shadowsocks.Controller.ShadowsocksController.Reload()
---------------------------
OK 
```  

3) After clicking OK I get this message ([screenshot](https://www.dropbox.com/s/92s51d67q5ajawk/Shadowsocks_37G7Cy6Ugh.png?dl=0)):

```
Error occured when process proxy setting, do you want reset current setting and retry?

Yes   No
```

4) After clicking Yes I get this message ([screenshot](https://www.dropbox.com/s/bb8h4my8i34zkw7/Shadowsocks_qXgfj8C7Ig.png?dl=0)):
```
Unrecoverable proxy setting error occured, see log for detail
---------------------------
OK   

```
5) After I input a Server and try to connect, I get the same error message from point 2)

**Comment by AnyWAT** [comment]
貌似最好放在非系统盘。如一定要放在桌面，参考：https://github.com/shadowsocks/shadowsocks-windows/issues/2333#issuecomment-488182977 解决了，C盘安装目录权限全部允许就好了

**Comment by chenshaoju** [comment]
Please put Shadowsocks.exe to a new folder like D:\SS\ , By default, There is no permission to write temp files to C:\Program Files\ (and x86) folder.

**Comment by rchokr** [comment]
Putting Shadowsocks.exe in a different drive than the Windows one, worked. I would update the [Troubleshooting ](https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting) pages with this solution.
