### ISSUE TITLE
error occurred when process proxy setting

### ISSUE THREAD

**Issue by abirmoy** [shadowsocks/shadowsocks-windows#2336]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.6.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

### Steps you have tried / 操作步骤
system proxy->global/pac/disable

### What did you expect to see? / 期望的结果
Error 

### What did you see instead? / 实际结果
No error

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![1](https://user-images.githubusercontent.com/50194655/57060749-119c0f80-6ced-11e9-9c09-c203f28dde7f.PNG)
![2](https://user-images.githubusercontent.com/50194655/57060750-1234a600-6ced-11e9-8d16-eadbe10c3e36.PNG)

**Comment by chenshaoju** [comment]
Please check this service has been started.：
![image](https://user-images.githubusercontent.com/515763/56583369-015ca400-660c-11e9-950a-90694d028a9b.png)

If still not working, Maybe is your operation system has damaged：https://github.com/shadowsocks/shadowsocks-windows/issues/2234
