### ISSUE TITLE
关于w10下访问墙外网站日志打印由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by dyx18539489507** [shadowsocks/shadowsocks-windows#2337]
运行Shadowsocks之后，访问国外网站却上不去 日志打印
[2019-05-04 14:58:12] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
[2019-05-04 14:58:14] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
[2019-05-04 14:58:14] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 127.0.0.1:8123
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2019-05-04 14:58:16] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)

望大侠解答

**Comment by chenshaoju** [comment]
请使用第三方的测试软件测试你所使用的服务器是否能通：https://github.com/chenshaoju/tcpportcheck/

**Comment by dyx18539489507** [comment]
> 请使用第三方的测试软件测试你所使用的服务器是否能通：https://github.com/chenshaoju/tcpportcheck/

可以使用的

**Comment by chenshaoju** [comment]
` 127.0.0.1:8123 ` ，你的日志里有一个这个东西，你是否配置了正向代理？如果你上网不需要通过代理，则无需配置：
![image](https://user-images.githubusercontent.com/515763/57176069-ed276b00-6e85-11e9-8bed-38ab54be2873.png)

**Comment by dyx18539489507** [comment]
不好意思，我对于Shadowsocks一窍不通，只知道这个软件可以访问被墙的网站，所以您发的这段话还有这张图我没有明白，麻烦您可以讲的通俗一点吗

**Comment by dyx18539489507** [comment]
> `127.0.0.1:8123` ，你的日志里有一个这个东西，你是否配置了正向代理？如果你上网不需要通过代理，则无需配置：
> ![image](https://user-images.githubusercontent.com/515763/57176069-ed276b00-6e85-11e9-8bed-38ab54be2873.png)

不好意思，我对于Shadowsocks一窍不通，只知道这个软件可以访问被墙的网站，所以您发的这段话还有这张图我没有明白，麻烦您可以讲的通俗一点吗

**Comment by chenshaoju** [comment]
软件本身不能直接翻墙，你需要搭建或者寻找第三方购买SS的服务（端）且配置后才能使用。

**Comment by AnyWAT** [comment]
> 不好意思，我对于Shadowsocks一窍不通，只知道这个软件可以访问被墙的网站，所以您发的这段话还有这张图我没有明白，

右键托盘SS图标——左键“正向代理设置...”

**Comment by dyx18539489507** [comment]
> 软件本身不能直接翻墙，你需要搭建服务端或者寻找第三方购买SS的服务且配置后才能使用。

谢谢大侠 已经被我搞定了 可以翻墙访问谷歌了

**Comment by hadeschx** [comment]
怎么搞定的啊，我也是小白不懂，也卡住了

**Comment by dyx18539489507** [comment]
> 怎么搞定的啊，我也是小白不懂，也卡住了  还需要吗
