### ISSUE TITLE
手机端移动4G和校园网均可使用，PC端无法连接，无法访问外网

### ISSUE THREAD

**Issue by Andrew5c** [shadowsocks/shadowsocks-windows#2338]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10专业版

### Steps you have tried / 操作步骤
电脑连接有线端连接的路由器，校园网，打开shadowsocks之后，无法连接，也无法访问Google

### What did you expect to see? / 期望的结果
能够恢复正常

### What did you see instead? / 实际结果
无法访问Google

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-05-04 16:31:32] Shadowsocks started (4.1.6)
[2019-05-04 16:31:40] 45.77.144.118:16069 timed out
[2019-05-04 16:31:54] 45.77.144.118:16069 timed out
[2019-05-04 16:32:00] 45.77.144.118:16069 timed out
[2019-05-04 16:32:05] 45.77.144.118:16069 timed out
[2019-05-04 16:32:10] 45.77.144.118:16069 timed out
[2019-05-04 16:32:15] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请尝试使用第三方的软件在有问题的计算机上测试一下，是否能通？ https://github.com/chenshaoju/tcpportcheck/

**Comment by yfxiongda** [comment]
> 请尝试使用第三方的软件在有问题的计算机上测试一下，是否能通？ https://github.com/chenshaoju/tcpportcheck/

我出现的错误和他的一样，日志也一样，测试了，不通

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，请尝试套一个插件看看：
https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836
