### ISSUE TITLE
firefox esr pac模式无效

### ISSUE THREAD

**Issue by Shawshank01** [shadowsocks/shadowsocks-windows#2340]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10， Firefox 60.6.2esr (64 位)。

### Steps you have tried / 操作步骤
开启ss，选择pac模式；
开启Firefox，无任何proxy插件情况下，输入www.google.com，回车，无法连接；
开启Edge，输入www.google.com，回车，连接成功；
切换ss至全局模式，在Firefox中输入www.google.com，回车，连接成功。

### What did you expect to see? / 期望的结果
使ss pac模式可用于Firefox 60.6.2esr (64 位)。

### What did you see instead? / 实际结果
pac模式下，Edge可通过ss翻墙，Firefox不可用，因ss无流量通过，怀疑未监听。
全局模式下，以上浏览器均可通过ss翻墙。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
{
  "version": "4.1.6",
  "configs": [
    {
      "server": "",
      "server_port": ,
      "password": "",
      "method": "",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "portableMode": true,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}
```

**Comment by chenshaoju** [comment]
请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后右击托盘区的SS图标，选择PAC并点击“从GFWList更新本地PAC”看看？

**Comment by Shedivh** [comment]
> 
> 
> 请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后右击托盘区的SS图标，选择PAC并点击“从GFWList更新本地PAC”看看？

感谢提供解决方案，可惜无效。无论有无pac.txt，edge均可正常使用ss，Firefox则不可。

**Comment by chenshaoju** [comment]
你使用的是以太网直接上网，还是PPPoE/PPTP/拨号认证方式上网？

如果是后者，请检查拨号名是否是中文（如“宽带连接”），如果是中文，改成英文的试试。

**Comment by Shedivh** [comment]
> 
> 
> 你使用的是以太网直接上网，还是PPPoE/PPTP/拨号认证方式上网？
> 
> 如果是后者，请检查拨号名是否是中文（如“宽带连接”），如果是中文，改成英文的试试。

感谢回复，我使用的是以太网直接上网。

**Comment by chenshaoju** [comment]
1.请检查你的Firefox插件列表（about:addons）是否有第三方代理插件接管代理。

2.请检查这个地方，是否使用的是系统代理：
![image](https://user-images.githubusercontent.com/515763/57499584-d1ebae00-7312-11e9-9263-e5216365cbf9.png)

**Comment by Shedivh** [comment]
> 
> 
> 1.请检查你的Firefox插件列表（about:addons）是否有第三方代理插件接管代理。
> 
> 2.请检查这个地方，是否使用的是系统代理：
> ![image](https://user-images.githubusercontent.com/515763/57499584-d1ebae00-7312-11e9-9263-e5216365cbf9.png)

感谢回复。issue描述中已说，无任何第三方代理插件，为新安装Firefox，且未同步任何代理插件。
![TIM截图20190510110640](https://user-images.githubusercontent.com/25277886/57499953-1461ba80-7314-11e9-845e-3991b973f92d.png)
![TIM截图20190510110712](https://user-images.githubusercontent.com/25277886/57499961-19bf0500-7314-11e9-8e56-d2ed5b983a54.png)

**Comment by celeron533** [comment]
@Shedivh 
Edge works indicated that proxy is alive. I'm not quite sure what happened in FF.
1. It may read the registry or inet service to get the proxy settings. Different method may cause different behavior.
2. It may only read the system proxy during startup. After then, no more activities.

Possible workaround:
1. Restart FF after you changed the proxy.
2. Manually define a socks5 proxy in FF
