### ISSUE TITLE
建议取消shadowsocks.log的长期占用

### ISSUE THREAD

**Issue by Cheain** [shadowsocks/shadowsocks-windows#2341]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
Shadowsocks started (4.1.6)

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows10

### Steps you have tried / 操作步骤
shadowsocks.exe运行期间会一直占用shadowsocks.log文件？是不是应该释放掉需要写入日志的时候再打开文件比较合适呢

### What did you expect to see? / 期望的结果
运行期间不占用shadowsocks.log，需要写入日志的时候再打开文件

### What did you see instead? / 实际结果
shadowsocks.exe运行期间会一直占用shadowsocks.log文件

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by yindalei00** [comment]
帮顶一下, 希望解除长期占用  或者 可以更改 日志文件位置

**Comment by celeron533** [comment]
目前的log机制是比较简单的实现，如果用nlog可能会好一下但会增加一点点文件体积

**Comment by studentmain** [comment]
已经换nlog了
