### ISSUE TITLE
MAC、ios端都可以，就是PC挂了

### ISSUE THREAD

**Issue by ctc1991** [shadowsocks/shadowsocks-windows#2342]
[2019-05-10 10:08:58] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

以上是LOG
我的服务器是搬瓦工的，ios和mac上没问题，就是PC这里PAC还是全局都不行，连不上。
这是啥问题呢，嘤嘤嘤！

**Comment by chenshaoju** [comment]
iOS和Mac都在同一个局域网吗？

如果是，请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/2339

**Comment by chenzhegodspeed** [comment]
@chenshaoju  我也是mac能登陆，PC不行。能问下哪里能看到log信息。。我是小白

**Comment by chenshaoju** [comment]
右击任务栏托盘区的SS纸飞机图标，选择帮助，然后点击显示日志。

**Comment by chenzhegodspeed** [comment]
我选的模式和mac上一样都是全局模式  
日志没异常
[2019-05-10 10:54:45] Shadowsocks started (4.1.6)
[2019-05-10 10:55:12] Shadowsocks started (4.1.6)
[2019-05-10 10:55:23] Shadowsocks started (4.1.6)
[2019-05-10 10:55:23] Shadowsocks started (4.1.6)
但是PC上面就是上不去。mac可以。。

**Comment by chenzhegodspeed** [comment]
我的mac再老家和租房的地方WiFi都可以。pc是在公司里面。不知道和公司网络设置是否有关系？但是5 1前公司网络下我也翻墙出去过。。。

**Comment by chenshaoju** [comment]
请确保在系统代理选项中选择了PAC，如果仍然不行，请指向PAC，然后点击“从GFWList更新本地PAC”，更新成功后再试。

**Comment by chenzhegodspeed** [comment]
[2019-05-10 10:54:45] Shadowsocks started (4.1.6)
[2019-05-10 10:55:12] Shadowsocks started (4.1.6)
[2019-05-10 10:55:23] Shadowsocks started (4.1.6)
[2019-05-10 10:55:23] Shadowsocks started (4.1.6)
[2019-05-10 11:00:31] Shadowsocks started (4.1.6)
[2019-05-10 11:00:31] Shadowsocks started (4.1.6)
[2019-05-10 11:02:30] Shadowsocks started (4.1.6)
[2019-05-10 11:02:30] Shadowsocks started (4.1.6)
[2019-05-10 11:03:21] Shadowsocks started (4.1.6)
[2019-05-10 11:03:53] Shadowsocks started (4.1.6)
[2019-05-10 11:03:54] Shadowsocks started (4.1.6)
[2019-05-10 11:04:02] Checking GFWList from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
[2019-05-10 11:04:03] Detected: PAC file 'pac.txt' was created.
已经生成pac.txt  还是不行。
另外我的pac选项里面勾选的是  **使用本地PAC** 和 **保护本地PAC**

**Comment by chenshaoju** [comment]
你看一下你的 pac.txt 文件的尺寸大于150kb吗？如果是，说明SS没有问题。

这两个选项没有关系。如果你的企业部署了代理，有可能你的系统会优先使用系统代理而不是SS的代理。这种情况没有办法。

**Comment by chenzhegodspeed** [comment]
187kb。。。我买的服务代理 端口是443.。我去找找管理员看看是不是443端口占用

**Comment by hu93123** [comment]
客户端在哪里呢？

**Comment by chenzhegodspeed** [comment]
@chenshaoju 我惊奇的发现。。edge浏览器可以。。。chrome不行。。。chrome我也没安装任何插件。。什么鬼。。刚才打开pdf时候无意间启动了edge浏览模式。点了谷歌主页登陆上去了。。。。  看来是浏览器的锅。。我先用edge凑合看吧。估计chrome设置了什么东西阻断了

**Comment by ctc1991** [comment]
@chenshaoju 
pac.txt在哪里

上面有人用edge打开可以，我试了下依然不行，edge显示：
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:
Could not load template file no-server-data or one of its included components.
Please contact your proxy administrator.
If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by ctc1991** [comment]
> 客户端在哪里呢？

桌面上建立了一个文件夹

**Comment by ctc1991** [comment]
> 你看一下你的 pac.txt 文件的尺寸大于150kb吗？如果是，说明SS没有问题。
> 
> 这两个选项没有关系。如果你的企业部署了代理，有可能你的系统会优先使用系统代理而不是SS的代理。这种情况没有办法。

我的PAC180伛KB 我没有企业代理
#2157 (comment)我试过一次这个，重启后一开始好的，马上又不行了。

**Comment by ctc1991** [comment]
> 请确保在系统代理选项中选择了PAC，如果仍然不行，请指向PAC，然后点击“从GFWList更新本地PAC”，更新成功后再试。
> 
> 可能你所在公司做了什么网络调整，建议咨询网管。
> 
> 或者，请尝试将SS服务端端口更换为443或者80看看。

服务端自己架构的，那台服务器上只装了SS服务，其他没有。

**Comment by chenzhegodspeed** [comment]
@ctc1991  我确实是SS mac能用， win端只能edge登陆。 chrome登陆不了。 chrome我又检测了一下，只安装过ad block。 我也不懂啥情况。我的SS是直接下载到一个文件夹解压直接用的

**Comment by andychenkk** [comment]
我也出现这情况。PC连不上，IOS可以。谁知道是什么情况啊？

**Comment by chenshaoju** [comment]
@ctc1991 请尝试换一个路径看看，比如 D:\SS\ ，不确定路径中有空格或者中文名称时的状态。

@andychenkk 请问iOS和PC在同一个局域网吗？日志中有什么显示？

**Comment by andychenkk** [comment]
@chenshaoju 是在同一个局域网。日志都是这样：
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

**Comment by andychenkk** [comment]
@chenshaoju 是在同一个局域网。日志都是这样：
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

**Comment by andychenkk** [comment]
@chenshaoju  是同一个局域网。 
我知道原因了，是windows防火墙打开了（系统自动打开的。。。）导致。关掉后可以了。谢谢回复~

**Comment by AnyWAT** [comment]
貌似 windows 防火墙打开了（系统自动打开的。。。）SS也正常才对头😂

**Comment by OrangeKnife** [comment]
管理员权限打开ss试了下就可以了
你们试试

**Comment by ctc1991** [comment]
@chenshaoju 最新重装系统发现可以用
但是等我装完了Adobe PS PR等（盗版）之后就不能用了，这个会是什么原因

**Comment by chenshaoju** [comment]
我怀疑是系统有问题……

**Comment by sobriver** [comment]
> @chenshaoju 我惊奇的发现。。edge浏览器可以。。。chrome不行。。。chrome我也没安装任何插件。。什么鬼。。刚才打开pdf时候无意间启动了edge浏览模式。点了谷歌主页登陆上去了。。。。 看来是浏览器的锅。。我先用edge凑合看吧。估计chrome设置了什么东西阻断了

擦，我发现我也是。现在怎么解决的？

**Comment by xusuy** [comment]
手机ios要怎么装客户端
