### ISSUE TITLE
近几个版本的BUG

### ISSUE THREAD

**Issue by william-abel** [shadowsocks/shadowsocks-windows#2344]
近几个版本都是这个问题  ![K40B2PWFBMXCP)BMLOU _RI](https://user-images.githubusercontent.com/45378809/57593986-7e769b80-7570-11e9-996c-d349726ec0cf.png)
![A`1SGYG) @S(S `ST61)A9Y](https://user-images.githubusercontent.com/45378809/57593987-7e769b80-7570-11e9-86b8-18385e709dd1.png)
![DZIZ)WHFS%PYUZ~2 NMO4E9](https://user-images.githubusercontent.com/45378809/57593988-7f0f3200-7570-11e9-946a-3e80e2b52243.png)
![OX0{FEO(V7 VLJR1AIS $3D](https://user-images.githubusercontent.com/45378809/57593989-7f0f3200-7570-11e9-8bfc-4d445c31faec.png)

**Comment by chenshaoju** [comment]
请尝试将 Shadowsocks.exe 单独放到一个新的目录中，比如 D:\SS\ ，然后重新配置一次看看。

**Comment by william-abel** [comment]
> 请尝试将Shadowsocks.exe单独放到一个新的目录中，比如D：\ SS \，然后重新配置一次看看。

我一直放在单独的文件夹内

**Comment by chenshaoju** [comment]
如果你是放到 C:\Program Files\ 目录下，这个目录可能没有写入权限。如果你非要放这个目录，比你必须以管理员身份运行 Shadowsocks.exe 。

**Comment by william-abel** [comment]
> 如果你是放到 C:\Program Files\ 目录下，这个目录可能没有写入权限。如果你非要放这个目录，比你必须以管理员身份运行 Shadowsocks.exe 。

非也非也 不在C盘

**Comment by chenshaoju** [comment]
这些错误看起来是由于权限被阻止导致的。有可能是某些系统策略，也可能是某些安全软件。

请暂时退出你的安全软件看看。

PS：请尝试右击 Shadowsocks.exe ，选择属性，能看到一个叫做“解除锁定”的选项吗？

**Comment by celeron533** [comment]
以前的版本也会发生代理错误（主要是由于无法备份当前windows系统代理，备份失败的原因主要是里面有非法字符），只不过不提示而已。
privoxy每次启动都会有一个临时产生的配置文件，请检查是否有其他程序在扫描同一个文件夹（如同步工具、杀毒软件）或者你的文件夹位于不稳定设备（如劣质存储，网络共享等）

**Comment by william-abel** [comment]
> 以前的版本也会发生代理错误（主要是由于无法备份当前windows系统代理，备份失败的原因主要是里面有非法字符），只不过不提示而已。
> privoxy每次启动都会有一个临时产生的配置文件，请检查是否有其他程序在扫描同一个文件夹（如同步工具、杀毒软件）或者你的文件夹位于不稳定设备（如劣质存储，网络共享等）

固态硬盘 新盘不存在不稳定设备 文件夹未被任何程序占用 开发机

**Comment by celeron533** [comment]
发生代理设置错误的时候，请手动从internet选项中清除代理设置。一般情况下有可能是有其他软件设置了、接管了系统代理设置，并且设置了些奇怪的代理地址字符（尤其是加入了不可见的控制字符）
另外一些“主动防御”软件也会拒绝未授权的代理服务器更改请求。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
