### ISSUE TITLE
昨晚正常，今天开机启动直接提示 non-UI错误

### ISSUE THREAD

**Issue by RonsonNamek** [shadowsocks/shadowsocks-windows#2345]
### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
操作系统 Windows 10专业版 1803 17134.753

### Steps you have tried / 操作步骤
晚上回家开机突然出现，昨晚还正常

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-05-13 22:17:08] [E] System.TypeInitializationException: “Shadowsocks.Controller.PrivoxyRunner”的类型初始值设定项引发异常。 ---> System.UnauthorizedAccessException: 对路径“D:\Shadowsocks\ss_win_temp\ss_privoxy.exe”的访问被拒绝。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PrivoxyRunner..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Controller.PrivoxyRunner..ctor()
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main(String[] args)

**Comment by RonsonNamek** [comment]
补充一下，昨晚关机前修改了merlin路由器的设置，因为路由器更新增加了个 DNS-over_TLS 的功能，我开启了，但是貌似因为设置不对提示“Your router's DHCP server is configured to provide a DNS server that's different from your router's IP address. This will prevent clients from using the DNS Privacy servers.”
但是同一个局域网的另一台PC没出现这个问题，是正常的

**Comment by chenshaoju** [comment]
这个和你的路由器没关系，可能是你的计算机上的安全软件（杀毒软件）阻止了 Shadowsocks.exe 启动 ss_privoxy.exe 导致的。

请尝试添加到安全软件的例外或者白名单中看看？

**Comment by RonsonNamek** [comment]
谢谢，是杀毒软件avast的问题，现在已经解决了。真是很奇怪，什么都没动突然就这样了
