### ISSUE TITLE
Firefox 使用一段时间后再无法通过 Shadowsocks Windows 代理，即使后者设为全局模式也是如此

### ISSUE THREAD

**Issue by liusone** [shadowsocks/shadowsocks-windows#2346]
### Shadowsocks version / 影梭版本
Shadowsocks Windows 4.1.6，但之前的小版本也有此问题。

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1809
Firefox 66.0.5，但之前几个大版本也有此问题。浏览器为国际版，除了被禁用的 Adobe Arcobat 扩展外未安装任何第三方插件与扩展。

### Steps you have tried / 操作步骤
Firefox 的代理模式是"使用系统代理设置"，刚开始一切正常，在使用一段时间后会发生浏览器无法被代理，无法访问网站的情况。具体是 Shadowsocks Windows 无论设置为 PAC 代理或是全局代理都再无法通过代理访问网页。即使 Shadowsocks Windows 设置为全局代理，也不修改 Firefox 代理设置，依然可以看到访问百度查询 IP 时为我的本地 ISP 提供的 IP，而并非代理服务器的 IP。
我的解决方法一般是，重启 Firefox 即可解决。或者一旦出现此问题时在浏览器设置里的网络设置中点击其他代理方式 (例如无代理或自动检测两者任意一个) 后点击确定，之后再设置回使用系统代理设置后会恢复正常，但使用一段时间后又会如此。

无论何时，Edge 与 Chrome 使用 Shadowsocks Windows 代理依然一切正常。

该问题已经发生了好几个月，但之前一直没有引起我的重视，所以现在才发 issue。

### Hopes / 期望
这看起来不一定像是 Shadowsocks Windows 的问题，但由于看到这么久也没人提到这个问题，觉得这两者搭配使用的人应该也不少，那么我可能是个例外，我的想法是不排除是第三方软件导致的问题。如果是如此，我更希望了解到底是哪里出现的问题。也希望大家能够向我提供一些排查问题的思路。

**Comment by helloMickey** [comment]
我的shadowsocks-win每次刚开始用还可以连接上，过一会就不可以用了（chrome，edge都不可以用），重新打开软件也不行。系统代理设置为为禁用、PAC模式、全局模式都不管用。4.1.6以及之前的版本都有出现过，现在还不清楚什么原因。有时候不能用之后，过一会儿就又可以使用了。有时候则需要重启电脑。
Android和ios上没有出现过这种情况。。。。

**Comment by chenshaoju** [comment]
@liusone 这个问题看起来是你的系统里有什么东西修改了Firefox的代理导致的。

@helloMickey 如果你的服务器是自己搭建的，请尝试套个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by liusone** [comment]
@chenshaoju 
请问有什么办法可以监控这类修改操作吗？
我奇怪的是，每隔一段时间就修改了 Firefox。而且每次出故障后我去设置里重新设置恢复代理的使用时，代理的选项是没有变化的。也就是明明选项是使用系统代理，但就是没有使用这个代理。
由于只有 Firefox 出现这个问题而其他浏览器 Chrome 和 Edge 没有，想到这个浏览器代理设置比较特殊，默认是不跟随系统代理的。曾猜想是 Firefox 的 bug，但没见过有人提过这个问题。

**Comment by chenshaoju** [comment]
我没研究过这一块，但是你可以试试这样，取消Shadowscks右键菜单里的PAC子菜单目录下的“保护本地PAC”，然后参照下图设置Firefox：

![image](https://user-images.githubusercontent.com/515763/57747088-908a4280-7706-11e9-8c3f-3c3376177b58.png)

请将 10800 替换成你的SS代理端口（可在编辑服务器界面右下角看到）。

**Comment by dongqisheng520** [comment]
> ### Shadowsocks version / 影梭版本
> Shadowsocks Windows 4.1.6，但之前的小版本也有此问题。
> 
> ### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
> Windows 10 1809
> Firefox 66.0.5，但之前几个大版本也有此问题。浏览器为国际版，除了被禁用的 Adobe Arcobat 扩展外未安装任何第三方插件与扩展。
> 
> ### Steps you have tried / 操作步骤
> Firefox 的代理模式是"使用系统代理设置"，刚开始一切正常，在使用一段时间后会发生浏览器无法被代理，无法访问网站的情况。具体是 Shadowsocks Windows 无论设置为 PAC 代理或是全局代理都再无法通过代理访问网页。即使 Shadowsocks Windows 设置为全局代理，也不修改 Firefox 代理设置，依然可以看到访问百度查询 IP 时为我的本地 ISP 提供的 IP，而并非代理服务器的 IP。
> 我的解决方法一般是，重启 Firefox 即可解决。或者一旦出现此问题时在浏览器设置里的网络设置中点击其他代理方式 (例如无代理或自动检测两者任意一个) 后点击确定，之后再设置回使用系统代理设置后会恢复正常，但使用一段时间后又会如此。
> 
> 无论何时，Edge 与 Chrome 使用 Shadowsocks Windows 代理依然一切正常。
> 
> 该问题已经发生了好几个月，但之前一直没有引起我的重视，所以现在才发 issue。
> 
> ### Hopes / 期望
> 这看起来不一定像是 Shadowsocks Windows 的问题，但由于看到这么久也没人提到这个问题，觉得这两者搭配使用的人应该也不少，那么我可能是个例外，我的想法是不排除是第三方软件导致的问题。如果是如此，我更希望了解到底是哪里出现的问题。也希望大家能够向我提供一些排查问题的思路。

我现在用Firefox 74.0.1最新的版本也遇到这个问题了，无法用v2rayN客户端通过pac走代理，前几天还是可以使用的，全局也不可以了，chrome则完全没问题。

**Comment by diisskk** [comment]
鄙人的FireFox134.0.2也出现了类似的情况：我使用的是V2rayN的Shadowsock节点，打开GitHub界面，会出现只能加载提问者的提问，下面的回复一个都加载不出来；同样的，部分网站的图片加载不了。如果用 Chrome 和 Edge 在同样的代理环境下，就能加载完全。以bilibili为例(只是方便说明)，在FireFox浏览下报错:错误内容是
错误码：-1
SETTINGS_ERROR: NetworkError when attempting to fetch resource.
错误码：-1
UPINFO_ERROR: The next() called multiple times
错误码：-1
NAVNUM_ERROR: NetworkError when attempting to fetch resource.
目前鄙人找到关于这些报错的情况都不是使用代理的情况，请大佬能不吝惜赐教，如果我有哪些地方信息提供不完善或不妥当的地方，请及时指出。

**Comment by diisskk** [comment]
鄙人的FireFox134.0.2也出现了类似的情况：我使用的是V2rayN的Shadowsock节点，部分网站的图片加载不了。如果用 Chrome 和 Edge 在同样的代理环境下，就能加载完全。

但是，经过我的排查，是uBlock Origin插件在作祟，禁用它之后网络访问一切正常，三个浏览器加载出来的界面完全一样。目前尚不清楚uBlock插件哪个部分影响了在代理下的网络访问。
