### ISSUE TITLE
指定远端DNS

### ISSUE THREAD

**Issue by sdbzwangchao** [shadowsocks/shadowsocks-windows#2349]
ss连接之后，使用的DNS依然是本地网卡所获得的DNS，能不能在ss连接的之后手动指定远端DNS？

**Comment by chenshaoju** [comment]
这个取决于你的应用本身对代理的支持，如IE/edge/Chrome默认使用代理的远程DNS，而Firefox则需要用户指定：

![image](https://user-images.githubusercontent.com/515763/57932848-61362a00-78ee-11e9-8cf6-d2c63a4b2e07.png)

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
