### ISSUE TITLE
连上就time out

### ISSUE THREAD

**Issue by aiyuyao** [shadowsocks/shadowsocks-windows#2351]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
移动到 https://github.com/shadowsocks/shadowsocks-windows/issues/2350

**Comment by aiyuyao** [comment]
网络没问题的，服务端能收到前五条的请求，然后就没了，客户端第一个请求返回的数据不完全，然后抛出一个异常，之后一直超时，装上simpleobfs之后是能正常请求的，但很慢，视频没画面播放不了

**Comment by aiyuyao** [comment]
中间有过配置成功，但第二天就不行了，步骤一样的，重新配置也没用

**Comment by chenshaoju** [comment]
请尝试使用simple-obfs的tls模式，并指定一个未被封锁的海外大厂的域名看看。

**Comment by 1phalley** [comment]
我这两天也是因为这个问题一个电脑经常低速断线卡顿另一个电脑正常，最后发现新版ss在编辑服务器界面下方居然有个portable mode被我勾上了，取消勾选然后重启就正常了

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
