### ISSUE TITLE
手机能连上，pc端连接不上，ip 端口 密码 加密方式都看了，快绝望了- - ，报错信息如下

### ISSUE THREAD

**Issue by whyaza** [shadowsocks/shadowsocks-windows#2352]
[2019-05-19 21:21:13] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 System.Net.DownloadStringCompletedEventArgs.get_Result()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by whyaza** [comment]
大神们 求助啊- -

**Comment by chenshaoju** [comment]
这意味着从你的计算机掉你的服务器被重置了。
请尝试：
1.使用第三方的服务检测你的服务器是否正常：https://ipcheck.need.sh/
2.使用第三方的软件检测从你的计算机到服务器是否正常：https://github.com/chenshaoju/tcpportcheck

**Comment by lutixiaya** [comment]
> 这意味着从你的计算机掉你的服务器被重置了。
> 请尝试：
> 1.使用第三方的服务检测你的服务器是否正常：https://ipcheck.need.sh/
> 2.使用第三方的软件检测从你的计算机到服务器是否正常：https://github.com/chenshaoju/tcpportcheck

我的情况一样，经过测试是一会通，一会不通

**Comment by chenshaoju** [comment]
请不要到处发，移动到： https://github.com/shadowsocks/shadowsocks-windows/issues/2360#issuecomment-495974362
