### ISSUE TITLE
有关本地地址的例外

### ISSUE THREAD

**Issue by huyuxuab** [shadowsocks/shadowsocks-windows#2353]
### Shadowsocks version / 影梭版本
4.16

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 Insider Preview 18898
代理方案为kcptun+shadowsocks

### Steps you have tried / 操作步骤
正常启动shadowsocks

### What did you expect to see? / 期望的结果
\-

### What did you see instead? / 实际结果
无法建立连接
在设置->网络->代理中发现例外如下：
```
*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*;localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*
```
即，连接无法通过代理，由于第一个  \* 的存在导致全部流量被绕过
手动修改之后连接正常 
在老版本（4.0.10）中不存在此现象；可能从4.15版本开始出现。

正常来说这种情况不可能出现的 不知为什么会混乱

另外，4.0.10的user-winnet.json文件内容实际上也是存在相同问题的，但是在系统代理例外中表现正常

```
localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*
```

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
日志仅有ss成功启动的信息
```
[2019-05-19 21:10:18] HA switching to server: 127.0.0.1:8080
[2019-05-19 21:10:18] Shadowsocks started (4.1.6)
[2019-05-19 21:10:26] Shadowsocks started (4.1.6)
[2019-05-19 21:10:26] Shadowsocks started (4.1.6)
```
**user-winnet.json**
```
{
  "UserSettingsRecorded": true,
  "Flags": "1",
  "ProxyServer": "127.0.0.1:1080",
  "BypassList": "*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*;<local>",
  "PacUrl": "http://127.0.0.1:7478/pac/pdown.pac?t=1546693495884"
}
```

**Comment by chenshaoju** [comment]
1.请退出SS
2.使用注册表编辑器打开 HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ ，找到 Internet Settings 键值后删除。
3.使用注册表编辑器打开 HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ ，找到 ProxyOverride 键值后删除。
4.进入 Shadowsocks.exe 所在目录下的 ss_win_temp 目录，找到 user-wininet.json 并删除。
5.再次启动SS。

**Comment by huyuxuab** [comment]
解决问题了，感谢
