### ISSUE TITLE
PAC模式下Chrome浏览器使用插件可以正常代理上网，但Edge、steam均无法代理上网

### ISSUE THREAD

**Issue by sirstrone** [shadowsocks/shadowsocks-windows#2354]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.6.0

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

Chrome在使用SwitchyOmega插件的情况下，可以通过SS-windows 进行正常代理上网，但Steam、IE、Edge在有些时刻的PAC模式下依旧无法代理上网、需切换至全局（或关闭）在回切PAC后才能正常使用
关于我电脑的设置可以参照上一个上一个issue #2283 
关于steamcommunity的规则已经添加至PAC
![image](https://user-images.githubusercontent.com/30281719/57984642-6f23b080-7a90-11e9-8a4a-a7a3712a8d5a.png)
关于SwitchyOmega的配置如下:
![image](https://user-images.githubusercontent.com/30281719/57984673-bd38b400-7a90-11e9-9ff9-db697657f67a.png)
![image](https://user-images.githubusercontent.com/30281719/57984676-c4f85880-7a90-11e9-81e5-0a5840251422.png)

**Comment by chenshaoju** [comment]
这意味着可能你的系统代理被其他应用接管了。

通过监测代理变化（原帖），仍然无法发现异常？

SS的日志中有显示任何内容吗？

**Comment by sirstrone** [comment]
> 这意味着可能你的系统代理被其他应用接管了。
> 
> 通过监测代理变化（原帖），仍然无法发现异常？
> 
> SS的日志中有显示任何内容吗？

![image](https://user-images.githubusercontent.com/30281719/58022856-fa5c7f00-7b40-11e9-8577-b15c0231db2d.png)
同上个issue一致，监测代理变化依旧没有任何异常
SS日志与上个issue一致，不过在Edge/Steam无法代理、使用Chrome时SS-win日志有正常链接记录
e.g.
[2019-05-20 20:51:41] connect to user-images.githubusercontent.com:443
[2019-05-20 20:51:41] Socket connected to ss server: 
[2019-05-20 20:51:41] Socket connected to ss server:

**Comment by chenshaoju** [comment]
请看一下你的IE代理设置的“默认不使用代理服务器”这一项（你可能需要暂时选中“为LAN使用代理服务器”），默认为：
```
localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*
```

如果你的里面有任何一个 `;*;` 或者只有一个 `*` ，如果有，先删除看看？ `*` 意味着完全不使用。

![image](https://user-images.githubusercontent.com/515763/58023608-c6825900-7b42-11e9-9824-9a10806a7bf3.png)

参考：https://github.com/shadowsocks/shadowsocks-windows/issues/2353

**Comment by sirstrone** [comment]
> 请看一下你的IE代理设置的“默认不使用代理服务器”这一项（你可能需要暂时选中“为LAN使用代理服务器”），默认为：
> 
> ```
> localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*
> ```
> 
> 如果你的里面有任何一个 `;*;` 或者只有一个 `*` ，如果有，先删除看看？ `*` 意味着完全不使用。
> 
> ![image](https://user-images.githubusercontent.com/515763/58023608-c6825900-7b42-11e9-9824-9a10806a7bf3.png)
> 
> 参考：#2353

![image](https://user-images.githubusercontent.com/30281719/58030352-fc2e3e80-7b50-11e9-8456-c959812b3eb7.png)
与默认设置完全匹配

**Comment by chenshaoju** [comment]
你这是全局模式吗？

你使用的是以太网直接上网，还是通过一个拨号连接？

如果是拨号连接，请检查一下拨号的连接名是否是中文的，如果是，改成英文的看看。

**Comment by sirstrone** [comment]
> 你这是全局模式吗？
> 
> 你使用的是以太网直接上网，还是通过一个拨号连接？
> 
> 如果是拨号连接，请检查一下拨号的连接名是否是中文的，如果是，改成英文的看看。

上述提供的信息均为pac模式
我使用的是带认证的以太网上网 与原issue相同 已经将连接改为英文
但并不管用

**Comment by chenshaoju** [comment]
我仍然认为有什么东西让你的系统代理失效了，但是具体是什么，不知道。

可能是你的认证软件在修改代理设置。

**Comment by sirstrone** [comment]
> 我仍然认为有什么东西让你的系统代理失效了，但是具体是什么，不知道。
> 
> 可能是你的认证软件在修改代理设置。

我会尝试监控一下认证软件的
不过 在Procmon失效的情况下 如何监控单一软件呢

**Comment by fieldxy** [comment]
我也遇到了这个问题

**Comment by fieldxy** [comment]
通过关闭Windows10 下的使用代理服务器选项 就可以正常使用了

**Comment by sirstrone** [comment]
> 通过关闭Windows10 下的使用代理服务器选项 就可以正常使用了

这里的代理服务器选项指的是IE的代理服务器选项还是Window组策略里的代理服务器选项
如果是IE的代理服务器选项，不是代表了无法使用PAC模式吗

**Comment by fieldxy** [comment]
> > 通过关闭Windows10 下的使用代理服务器选项 就可以正常使用了
> 
> 这里的代理服务器选项指的是IE的代理服务器选项还是Window组策略里的代理服务器选项
> 如果是IE的代理服务器选项，不是代表了无法使用PAC模式吗

设置里面的网络 里面有一个代理  关闭代理服务器

**Comment by sirstrone** [comment]
事实上 这个代理服务器选项并没有启动

**Comment by sirstrone** [comment]
> 我仍然认为有什么东西让你的系统代理失效了，但是具体是什么，不知道。
> 
> 可能是你的认证软件在修改代理设置。


在PAC模式失效的情况下 我依然能从localhost:10800/pac 中下载到PAC文件
在系统 - 网络 - 代理 中的设置脚本中 其设置脚本依旧指向正确的PAC文件
而且检查了注册表AutoConfigURL 项 其键值依旧指向PAC文件
且Chrome的proxy switchyomega可以正常使用
我认为没有程序修改了代理设置 是否有别的程序/注册表选项会干扰SS的正常运行呢？

**Comment by uranusyu417** [comment]
我遇到的问题有点类似，就是访问bloomberg的时候，会被提示recaptcha人机验证，如果是pac模式，会重复出现验证，虽然可以验证通过，但会一直要求你验证，如果是全局模式，一次过后就能正常访问网站

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
