### ISSUE TITLE
System.Exception: 端口 1080 是系统保留端口 

### ISSUE THREAD

**Issue by cjb2667** [shadowsocks/shadowsocks-windows#2355]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
启动

### What did you see instead? / 实际结果
System.Exception: 端口 1080 是系统保留端口 ---> System.Net.Sockets.SocketException: 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   --- 内部异常堆栈跟踪的结尾 ---

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by cjb2667** [comment]
系统版本：Windows 10 专业版 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434)

**Comment by chenshaoju** [comment]
请尝试在编辑服务器界面右下角的代理端口界面换一个端口看看。

**Comment by cjb2667** [comment]
> 请尝试在编辑服务器界面右下角的代理端口界面换一个端口看看。

换了个8xxx开头的端口 可以使用了。 估计新版系统屏蔽了1xxx的端口   
才知道 原来端口不一定要用1080的哦
