### ISSUE TITLE
shadowsocks自定义pac规则无效

### ISSUE THREAD

**Issue by LittleFatHero** [shadowsocks/shadowsocks-windows#2356]
### Shadowsocks version / 影梭版本
shadowsocks 4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
.netframework 版本：4.0.30319
操作系统：Windows 10 1809
### Steps you have tried / 操作步骤
1.右击shadowsocks图标，选择编辑GFWList的用户规则
2.在user-rule.txt末尾添加如下文本后保存：
```
||ip138.com^
```
3.然后右击shadowsocks图标，选择从GFWList更新本地PAC
4.退出shadowsocks，然后重新打开
### What did you expect to see? / 期望的结果
希望访问www.ip138.com的时候经过shadowsocks代理访问，而不是直接访问。

### What did you see instead? / 实际结果
实际上，访问ip138.com时只有一次成功走了代理，当重新启动shadowsocks之后，再也没有走过代理。即配置的规则就生效过一次，经常失效。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后再在SS的PAC菜单下点击从GFWList更新本地PAC看看。

**Comment by LittleFatHero** [comment]
> 请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后再在SS的PAC菜单下点击从GFWList更新本地PAC看看。

试过了，在user-rule.txt文件里配置的代理规则还是没有生效，还是没有走代理。网上甚至说自定义访问修改的是PAC.txt文件，这个也不可以，因为shadowsocks更新PAC.txt的时候，会将自定义的规则覆盖抹掉。所以自定义规则应该是在user-rule.txt文件里，但是在里面配置的规则又不生效，这个是不是软件一个严重的bug？还是说我配置规则配错了？我想访问ip138.com的时候经过代理访问，在user-rule.txt里添加如下规则：
```
||ip138.com^
```
感觉也没错呀？这个是不是软件有bug？

**Comment by chenshaoju** [comment]
测试了一下， ip138.com 使用的是一个 iframe 进行调用显示IP的部分的，因此，你需要将 `http://2019.ip138.com/ic.asp` 加入代理列表。

或者，去掉末尾的 ^ 符号。

**Comment by LittleFatHero** [comment]
在另外一台电脑上，竟然生效了，完全没道理，可怕。没有去掉^号，原模原样的配置。
感谢大佬的解答。
