### ISSUE TITLE
托盘图标在 4K 200% 缩放下模糊

### ISSUE THREAD

**Issue by LIXiangChen** [shadowsocks/shadowsocks-windows#2357]
### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1903 x64

托盘图标在 4K 200% 缩放下模糊.

![shot](https://user-images.githubusercontent.com/8857634/58187670-d0928c00-7ce9-11e9-8112-2847a2b55c84.png)

**Comment by celeron533** [comment]
不是矢量图标，所以放的太大会有点问题
24x24@32bit png

**Comment by LIXiangChen** [comment]
@celeron533 给它增加一个大尺寸的图标呗, 我看 .exe 文件的图标 (蓝色飞机) 那个就不会糊, 那个应该是有对应尺寸的.

**Comment by celeron533** [comment]
updated in

https://github.com/shadowsocks/shadowsocks-windows/commit/148d3885ada8c0729af23cfd1d661438df542473
