### ISSUE TITLE
2015.07.26 新功能

### ISSUE THREAD

**Issue by benhon2008** [shadowsocks/shadowsocks-windows#236]
![untitled](https://cloud.githubusercontent.com/assets/12547424/8892719/8f831bc0-339c-11e5-9adc-0bc73764d1d8.png)

[local balance] & [high availability]

新增两项具体作用?

**Comment by voidmorn** [comment]
这个README里说了吧：
Server Auto Switching
Load balance: choosing server randomly
High availability: choosing the best server (low latency and packet loss)

就是在你的几个服务器之间自动切换，两种不同的策略。

**Comment by benhon2008** [comment]
噢，谢谢。 看到README 10多个小时之前更新，没仔细看。
