### ISSUE TITLE
配置 user rules 没有生效

### ISSUE THREAD

**Issue by bigbigbo** [shadowsocks/shadowsocks-windows#2361]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
Shadowsocks-4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
- 操作系统：win10 64位 版本号18362
-  .NET Framework：v4.0.30319

### Steps you have tried / 操作步骤
> 因为公司网络限制，禁止访问知乎、淘宝、京东等网站。

我启用了PAC模式，并且编辑了 user rules，如下：
![QQ图片20190531094834](https://user-images.githubusercontent.com/19587016/58676011-53ba7e80-8389-11e9-9aae-3390a85ef36d.png)

我检查了最终的PAC.txt，发现也有将user rules 添加进去：
![QQ图片20190531095108](https://user-images.githubusercontent.com/19587016/58676104-a300af00-8389-11e9-9a5a-3531770f5d94.png)

我也查看了相关的 issue，应该没有配置错...

### What did you expect to see? / 期望的结果
通过 PAC 的 user rules 能正常访问用户配置的经过代理的网站

### What did you see instead? / 实际结果
不能访问知乎、淘宝、京东网站，但是我**开全局代理模式又可以**。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt ，然后右击托盘区的SS纸飞机图标，指向PAC，再点击“从GFWList更新本地PAC”看看。

某些情况下修改 user-rule.txt 后，需要右击托盘区纸飞机图标，指向系统代理，并再点一下“PAC 模式”。

**Comment by bigbigbo** [comment]
@chenshaoju 谢谢，已经解决。
