### ISSUE TITLE
用了Advanced SystemCare 12 的网络加速功能以后报错

### ISSUE THREAD

**Issue by remodify** [shadowsocks/shadowsocks-windows#2362]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本

shadowsocks 4.1.6
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

### Steps you have tried / 操作步骤

使用了Advanced System 12 的pro网络加速功能以后报错了
加速功能的说明：“通过优化TCP/IP参数来调整数据包传输以获得最高网络速度”
报错：处理代理设置时发生错误，是否重置当前代理设置并重试
点“是”以后，
提示：“发生不可恢复的代理设置错误，查看日志以取得详情”
重启无效，
### What did you expect to see? / 期望的结果
恢复原状。。。

### What did you see instead? / 实际结果

没有改变
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
日志如下：
[2019-05-31 12:02:56] Shadowsocks started (4.1.6)
[2019-05-31 12:02:56] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-05-31 12:02:56] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-05-31 12:02:59] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

**Comment by chenshaoju** [comment]
可能和你的某个特定系统服务被停止有关： https://github.com/shadowsocks/shadowsocks-windows/issues/2325

**Comment by remodify** [comment]
![image](https://user-images.githubusercontent.com/50667500/58709009-c0fefb80-83eb-11e9-8172-9a463ffec90b.png)
这个服务显示的是已停止，但是为什么启用不了呢

**Comment by chenshaoju** [comment]
这意味着你此服务的关联服务可能被禁用了，请转到上图中的依存关系选项卡进行检查。

也可能你的系统遭受到了损坏，我这儿是好的：
![image](https://user-images.githubusercontent.com/515763/58741691-909c7900-844e-11e9-8eb7-d1df2c50b947.png)


如果你无法重置系统，你可能需要在浏览器安装第三方的代理插件进行代理。

**Comment by remodify** [comment]
重启电脑以后，又恢复正常了。。。多谢了。

> 这意味着你此服务的关联服务可能被禁用了，请转到上图中的依存关系选项卡进行检查。
> 
> 也可能你的系统遭受到了损坏，我这儿是好的：
> ![image](https://user-images.githubusercontent.com/515763/58741691-909c7900-844e-11e9-8eb7-d1df2c50b947.png)
> 
> 如果你无法重置系统，你可能需要在浏览器安装第三方的代理插件进行代理。
