### ISSUE TITLE
ss电脑端用校园网或公司网访问不稳定，经常连接超时，电脑用手机发射热点访问稳定

### ISSUE THREAD

**Issue by zxr11241** [shadowsocks/shadowsocks-windows#2363]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
Shadowsocks-4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 企业版 LTSC NET Framework(v4.0.30319)
chrome版本 74.0.3729.169（正式版本） （64 位）

### Steps you have tried / 操作步骤
手机ss连接校园网或者公司的网络WiFi不能访问，用流量可以访问稳定；电脑端ss用校园网无线（电信），公司的网有线（鹏博士），访问不稳定，时断时续
尝试过以下几种方法（因为本人不是程序员，看不懂代码啥的，以衡量一个方法能否用的方式是能否访问）
1.换服务商，从vultr到linode
2.换机房，从美国到日本
3.换端口
4.换系统，公司的是windows7 笔记本是windows 10
5.换翻墙的客户端，从ss ssr到v2ray
6.使用蓝灯
7.用另一台电脑连接校园网发射wifi，用这台电脑连接
8.用手机流量开热点，用电脑连接
9.电话问过学校网络中心的老师，得到的反馈是，学校并没有检测封端口或ip啥的，老师本身也在用，有时候也会出现超时的问题，建议我选用较近的香港机房

### What did you expect to see? / 期望的结果
使用校园网或者公司的网能够稳定访问谷歌 YouTube 维基等
（从上述的描述来看，感觉可能是网络的问题，但是又不知道问题具体出现在哪里。）

### What did you see instead? / 实际结果
1.问题依旧
2.问题依旧
3.问题依旧
4.问题依旧
5.问题依旧
6.可以稳定使用
7.可以使用（访问的时间不长，在校园网连不上时使用这种方式可以访问）
8.可以使用（访问的时间不长，在校园网连不上时使用这种方式可以访问）

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
不能访问时的日志（因没保存，网上找来类似的）
[2017-08-05 15:57:22] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-08-05 15:57:27] s2.x3x.bid:1024 timed out
[2017-08-05 15:59:04] Shadowsocks started
[2017-08-05 15:59:32] Shadowsocks started
[2017-08-05 15:59:42] Shadowsocks started
[2017-08-05 16:12:37] Shadowsocks started
[2017-08-05 16:13:25] Shadowsocks started
[2017-08-05 16:13:55] Shadowsocks started
[2017-08-05 16:14:21] Shadowsocks started
[2017-08-05 16:14:53] Shadowsocks started
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，情尝试套个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by zxr11241** [comment]
@chenshaoju 
![未命名图片](https://user-images.githubusercontent.com/36974705/58741882-6ac4a380-8451-11e9-9a39-ca05903f1068.png)
服务端：
Congratulations, Shadowsocks-libev server install completed!
Your Server IP        :  172.104.*** 
Your Server Port      :  443 
Your Password         :  *** 
Your obfs             :  http 
Your Encryption Method:  chacha20

**Comment by zxr11241** [comment]
问题依旧存在

[2019-06-01 09:13:19] Started SIP003 plugin for 172.104.:443 on 127.0.0.1:2500 - PID: 7256
[2019-06-01 09:13:19] Shadowsocks started (4.1.6)
[2019-06-01 09:20:35] Started SIP003 plugin for 172.104.:443 on 127.0.0.1:2745 - PID: 11224
[2019-06-01 09:20:35] Shadowsocks started (4.1.6)
[2019-06-01 09:38:39] Started SIP003 plugin for 172.104.:443 on 127.0.0.1:3493 - PID: 7948
[2019-06-01 09:38:39] Shadowsocks started (4.1.6)
[2019-06-01 09:44:41] Started SIP003 plugin for 172.104.:443 on 127.0.0.1:3657 - PID: 6132
[2019-06-01 09:44:42] Shadowsocks started (4.1.6)

**Comment by zxr11241** [comment]
我刚才看了校园无线的名称***-wlan，是这种的，不知道是不是中间的字符导致的？
![image](https://user-images.githubusercontent.com/36974705/58742272-1e2f9700-8456-11e9-8a93-33ba3ec5ffe4.png)

**Comment by chenshaoju** [comment]
你的服务端也安装并且配置了相同插件吧？

这个看起来没有任何访问，请尝试右击托盘区SS纸飞机图标，选择PAC，再点击从GFWList更新本地PAC看看，是否能成功？日志中有无任何提示？

**Comment by zxr11241** [comment]
上面显示的就是我在服务端配置了obfs的日志，但是刚才那个服务器已经被我删除了，我后续再试试。

**Comment by zxr11241** [comment]
@chenshaoju 
[2019-06-01 10:44:12] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-06-01 10:44:49] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-06-01 10:45:19] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by zxr11241** [comment]
#1297 这个我之前也试过，但是问题还是存在。

**Comment by YuJingwen757270** [comment]
> @chenshaoju
> ![未命名图片](https://user-images.githubusercontent.com/36974705/58741882-6ac4a380-8451-11e9-9a39-ca05903f1068.png)
> 服务端：
> Congratulations, Shadowsocks-libev server install completed!
> Your Server IP : 172.104.***
> Your Server Port : 443
> Your Password : ***
> Your obfs : http
> Your Encryption Method: chacha20

想问下你的这个服务端是在哪里弄得？我也想弄一个，获得稳定的网速

**Comment by zxr11241** [comment]
@YuJingwen757270 这个就是官方的客户端，插件是simple obfs，可以在网上找得到。

**Comment by zxr11241** [comment]
@chenshaoju “这个看起来没有任何访问，请尝试右击托盘区SS纸飞机图标，选择PAC，再点击从GFWList更新本地PAC看看，是否能成功？日志中有无任何提示？”按照你的操作，重新弄了个服务器配置了simple obfs，日志显示如下，刚开始可以上，又上不了了。
[2019-06-01 14:18:44] Started SIP003 plugin for 139..233:443 on 127.0.0.1:4400 - PID: 10008
[2019-06-01 14:18:44] Shadowsocks started (4.1.3)
[2019-06-01 14:18:44] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-06-01 14:18:52] Detected: PAC file 'pac.txt' was created.

**Comment by zxr11241** [comment]
@chenshaoju “这个看起来没有任何访问，请尝试右击托盘区SS纸飞机图标，选择PAC，再点击从GFWList更新本地PAC看看，是否能成功？日志中有无任何提示？”按照你的操作，重新弄了个服务器配置了简单的obfs，日志显示如下，刚开始可以上，又上不了了。
[2019-06-01 14:18:44]在127.0 上启动了13900的WEB003插件139..233：443。 0.1：4400 - PID：10008 
[2019-06-01 14:18:44] Shadowsocks开始（4.1.3）
[2019-06-01 14:18:44]
已注册
的加密器信息aes-128-cfb => StreamOpenSSLEncryptor 
aes-192-cfb => StreamOpenSSLEncryptor 
aes-256-cfb => StreamOpenSSLEncryptor 
aes-128-ctr => StreamOpenSSLEncryptor 
aes-192-ctr => StreamOpenSSLEncryptor 
aes-256-ctr => StreamOpenSSLEncryptor 
bf-cfb => StreamOpenSSLEncryptor camellia 
-128-cfb => StreamOpenSSLEncryptor camellia 
-192-cfb => StreamOpenSSLEncryptor 
camellia-256-cfb => StreamOpenSSLEncryptor 
rc4-md5 => StreamOpenSSLEncryptor 
salsa20 => StreamSodiumEncryptor 
chacha20 => StreamSodiumEncryptor 
chacha20-ietf => StreamSodiumEncryptor 
aes-128-gcm => AEADOpenSSLEncryptor 
aes-192-gcm => AEADOpenSSLEncryptor
aes-256-gcm => AEADOpenSSLEncryptor 
chacha20-ietf-poly1305 => AEADOpenSSLEncryptor 
xchacha20-ietf-poly1305 => AEADSodiumEncryptor
[2019-06-01 14:18:52]检测到：PAC文件'pac.txt'已创建

**Comment by zxr11241** [comment]
真的崩溃。。。最近一个多月都这样，难道没有其他好的方法解决这个问题？我看到好像很多人都反应这个问题。我记得之前用刷票软件刷高铁票的时候，用学校网络刷，公网ip，长时间低间隔被封过，过段时间又解封了，难道防火墙也是用类似的检测手段？

**Comment by chenshaoju** [comment]
你是否指定了正向代理？如果你上网不需要经过内部的代理服务器的话，不要选中下面任何一个选项，位于右键菜单，正向代理设置中。

![image](https://user-images.githubusercontent.com/515763/58745927-80a28a80-848a-11e9-89a6-46208c9030a8.png)

**Comment by zxr11241** [comment]
![image](https://user-images.githubusercontent.com/36974705/58745986-7b920b00-848b-11e9-8bc6-03e60d905c6b.png)
@chenshaoju 并没有指定正向代理。
刚才想通过蓝灯翻墙，安装蓝灯又卸载了，然后出现了下面的情况。
![image](https://user-images.githubusercontent.com/36974705/58746010-bc8a1f80-848b-11e9-9745-487ad9e0b808.png)

**Comment by chenshaoju** [comment]
从界面上来看，你用的好像是一个旧版本，请尝试更新一下看看： https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by zxr11241** [comment]
@chenshaoju 这个是4.1.3版本，看到有人说换到旧版本就不出现上述的问题，我试了试，还是会出现不稳定，换到4.1.6，不会出现非预期错误，但是翻墙还是不稳定。。。

**Comment by chenshaoju** [comment]
可能和这个有关： https://twitter.com/fdmove/status/1134665688478408704

**Comment by zxr11241** [comment]
@chenshaoju 这个推特链接打开看不到啥
![image](https://user-images.githubusercontent.com/36974705/58748853-bb1f1e00-84b0-11e9-8358-021c65fbe145.png)

**Comment by chenshaoju** [comment]
删了，简而言之，特殊时期，网络不稳定，没有办法。

**Comment by zxr11241** [comment]
@chenshaoju 我刚才重开了个服务器，linode的加拿大多伦多机房，然后服务端安装的是一键安装脚本（四合一）中的Shadowsocks-libev 版，配置了simple obfs，
Congratulations, Shadowsocks-libev server install completed!
Your Server IP        :  172.105.27.*** 
Your Server Port      :  17120 
Your Password         :  ****601 
Your obfs             :  tls 
Your Encryption Method:  chacha20-ietf-poly1305，
![未命名图片](https://user-images.githubusercontent.com/36974705/58749366-d17ca800-84b7-11e9-9f8a-02dba45abb0f.png)
服务端没有安装逗比的一键加速tcp-bbr
目前（大概半个小时）暂时能够稳定的访问
ss日志如下
[2019-06-01 21:54:26] connect to github-production-user-asset-6210df.s3.amazonaws.com:443
[2019-06-01 21:54:26] Socket connected to ss server: 172.105.27.***:17120
[2019-06-01 21:55:42] Checking GFWList from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
[2019-06-01 21:55:42] connect to raw.githubusercontent.com:443
[2019-06-01 21:55:42] Socket connected to ss server: 172.105.27.***:17120
[2019-06-01 21:55:53] connect to www.google.com:443
[2019-06-01 21:55:53] Socket connected to ss server: 172.105.27.***:17120
[2019-06-01 21:55:54] connect to www.google.com.hk:443
[2019-06-01 21:55:54] Socket connected to ss server: 172.105.27.***:17120
[2019-06-01 21:55:54] connect to www.gstatic.com:443
[2019-06-01 21:55:54] Socket connected to ss server: 172.105.27.***:17120
[2019-06-01 21:55:54] connect to apis.google.com:443
[2019-06-01 21:55:54] Socket connected to ss server: 172.105.27.***:17120
[2019-06-01 21:56:02] connect to zh.wikipedia.org:443
[2019-06-01 21:56:02] Socket connected to ss server: 172.105.27.***:17120
所以我推测：
第一可能是机房的位置（之前是美国新加坡日本居多）
第二可能是安装插件的原因
第三可能是安装一键tcp-bbr导致的（之前都有安装一键tcp-bbr）
第四，也可能是九点多过了高峰期，明天再看下情况。
由于精力有限，所以能否解释下是什么原因导致的，或者有其他人可以做下对比实验？

**Comment by chenshaoju** [comment]
不是你这么填的，请仔细阅读：https://github.com/shadowsocks/shadowsocks-windows/issues/2217#issuecomment-464413579

**Comment by zxr11241** [comment]
@chenshaoju 我昨天开的加拿大的服务器到今天，一直很稳定可以翻墙，我想问下插件这样是否是正确配置？还有这个是什么原因导致的？
我在服务端也配置了：
Starting Shadowsocks-libev success

Congratulations, Shadowsocks-libev server install completed!
Your Server IP        :  *** 
Your Server Port      :  1***
Your Password         :  **** 
Your obfs             :  tls 
Your Encryption Method:  chacha20-ietf-poly1305 
 

Welcome to visit: https://teddysun.com/486.html
Enjoy it!
![未命名图片](https://user-images.githubusercontent.com/36974705/58757634-3bda2a80-8542-11e9-8491-c5247c578912.png)
![123](https://user-images.githubusercontent.com/36974705/58757640-4694bf80-8542-11e9-9031-320a86770156.png)

**Comment by zxr11241** [comment]
可以稳定访问，但是速度比较慢，有改进的方法么？

**Comment by chenshaoju** [comment]
如果你不看字的话，那么沟通起来就会很费力。
![image](https://user-images.githubusercontent.com/515763/58758057-67601380-8548-11e9-85b3-a2f841202a05.png)

你可以尝试使用bbr拥塞算法来优化速度，具体需要修改服务端的 /etc/sysctl.conf 文件，仅供参考：
https://gist.github.com/chenshaoju/b0e20f23efabb8eb2cd4

**Comment by zxr11241** [comment]
@chenshaoju 好的，谢谢，不好意思，看漏眼了，之前看了其他教程错误的示范。因为配置了，但是并不清楚是否配置成功了，现已改正过来。加速也使用上去，但是感觉速度提升不上很明显，有可能跟网速有一定的关系。
![未命名图片](https://user-images.githubusercontent.com/36974705/58758537-3fc07980-854f-11e9-8704-85261c411245.png)
![123](https://user-images.githubusercontent.com/36974705/58758538-45b65a80-854f-11e9-94a5-568a75710875.png)
![未命名图片12](https://user-images.githubusercontent.com/36974705/58758552-5cf54800-854f-11e9-9948-2641af483f9e.png)
