### ISSUE TITLE
六一ip挂了，请告诉我我不是一个人

### ISSUE THREAD

**Issue by HyFun** [shadowsocks/shadowsocks-windows#2368]
![image](https://user-images.githubusercontent.com/17896692/58756136-ae3c1200-8524-11e9-8e50-6dfb69bb89eb.png)

请各位自行监测：https://ipcheck.need.sh/

**Comment by help12138** [comment]
原IP端口被禁，换了个ip好了，结果午夜十二点整时，又被封了

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭的，请尝试套一个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by cutecamel** [comment]
6.1上午先是所有端口被封，今天连ping都不通了，昨天重新开了几个还没咋用，今天也阵亡了

**Comment by haozhen315** [comment]
有谁知道该怎么办吗啊啊啊啊

**Comment by Yanxiaohu** [comment]
就在刚刚。。。全部阵亡。。。忽然就上不去了。

**Comment by JonnyTang** [comment]
又上不了了

**Comment by ShiiZhang** [comment]
IP能不能PING通呐？我换上了全新的IP，[https://ipcheck.need.sh/](这里)显示没问题，但还是不行(>_<)

**Comment by AnyWAT** [comment]
✌借助 https://github.com/Kisesy/gscan_quic 用原生的XX-Net 没感觉。XX-net/XX-Net#12477

**Comment by lisi2016** [comment]
我一直用搬瓦工服务器，6.1上午不能访问墙外的网站了，刚开始还能ping通，但是没有马上更换主机，结果过了十几分钟，不能ping通了。今天只有更换host的ip，然后后台重装系统，重装shadowsock服务，下午恢复正常访问了。

**Comment by NAVrasZ** [comment]
一个ip怎么折腾插件还是用一会就被封，请告诉我我不是一个人...

**Comment by Bilinico** [comment]
我是欸

**Comment by Bilinico** [comment]
我也是欸

**Comment by GODOFHOU** [comment]
嗯，差不多，大面积机场停机
![{K4$(GKJT2ZNRSX975V}B$0](https://user-images.githubusercontent.com/30817974/58786393-06087500-861a-11e9-8483-fc0a9a8140ea.png)

**Comment by leon0625** [comment]
我6.1这天也挂了，之前是用的搬瓦工，昨天刚换了vultr的主机，今天IP又被封了。。。。

**Comment by baronv5** [comment]
用libev版本，Python的容易被封

**Comment by pedoc** [comment]
我也是被封了今天，用朋友的服务器都不行，不知道如何做到的

**Comment by ygzhong000** [comment]
我的用得好好的呀，没有问题！！！

**Comment by JerryCheng1** [comment]
能ping 得通，但是挂9999端口不知道为何连不上

**Comment by DaveSteven** [comment]
> 能ping 得通，但是挂9999端口不知道为何连不上

我telnet完全没反应。

**Comment by Snowfish1994** [comment]
前一分钟刚搭好，下一分钟SS一连就挂了，ssh都上不去了

**Comment by snowtraces** [comment]
新换一个ip又挂了，看来只能==了

**Comment by jasonliul** [comment]
近來雕黨大大們的反饋是瓦刀是最重災區, CloudFlare倖免於難

**Comment by uncleniner** [comment]
各位尝试过更好ip了吗?可以使用了吗?

**Comment by chenshaoju** [comment]
理论上说，已经过去很久了，应该可以了。

我用的英国地区的服务器，自己搭建的SS-libev+GoQuite，没有任何问题。

非技术类的问题即将被关闭。

**Comment by Snowfish1994** [comment]
搞了个shockhosting的vps，测试可用

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history
