### ISSUE TITLE
删除所有服务器后点击“复制”按钮，提示错误。

### ISSUE THREAD

**Issue by wangtz0607** [shadowsocks/shadowsocks-windows#2371]
### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 x64 

### Steps you have tried / 操作步骤
1. 删除列表里的所有服务器
2. 点击“复制”按钮
3. 产生错误

**Comment by chenshaoju** [comment]
此问题已确认：
![image](https://user-images.githubusercontent.com/515763/58762475-ef630f00-8582-11e9-89ba-a03726d455b6.png)
