### ISSUE TITLE
Mac能用，window10下不能连接啊，哪个大佬帮忙看看

### ISSUE THREAD

**Issue by googlewant** [shadowsocks/shadowsocks-windows#2374]
![image](https://user-images.githubusercontent.com/32006417/58814525-79c97280-8658-11e9-95dc-7c6ea244d9b5.png)

**Comment by jinyumarine** [comment]
跟我一样，害我重装系统，还是连部上，我的手机和win7下都正常，就是win10连不了

**Comment by chenshaoju** [comment]
你的服务器地址是一个IPv6地址吗？还是你随便乱填的一个地址？

**Comment by googlewant** [comment]
ipv4 win10上也可以ping通

**Comment by chenshaoju** [comment]
1.如果你的服务器是自己搭的，情尝试换一个端口，比如443或者其他端口，已知8338被重点关照。
2.日志中显示了一个 fe80 开头的IPv6地址，这个地址是内网(本地)地址，不是公网IPv6地址，请确保你填写的服务器IP正确。

**Comment by DaveSteven** [comment]
尴尬的是ssh已经连不上我的服务器了。

**Comment by sobriver** [comment]
我现在也是。mac和手机都能连上，就是win10连接不上

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
