### ISSUE TITLE
求大神救小弟

### ISSUE THREAD

**Issue by arguslamgg** [shadowsocks/shadowsocks-windows#2375]
![WeChat 圖片_20190604003405](https://user-images.githubusercontent.com/51333638/58818419-7c2fca80-8660-11e9-850f-e0cf9a62a397.jpg)

**Comment by chenshaoju** [comment]
请尝试放到一个新目录中，比如 D:\SS\ 看看？

**Comment by arguslamgg** [comment]
之前試過 還是不行

**Comment by arguslamgg** [comment]
> 请尝试放到一个新目录中，比如 D:\SS\ 看看？
之前試過 還是不行

**Comment by chenshaoju** [comment]
请确保路径中都是英文，且没有空格。因为截图中的路径里有个问号，Windows不允许半角问号作为路径名。

**Comment by celeron533** [comment]
>Windows不允许半角问号作为路径名

尤其是系统没有开启非Unicode中文支持的情况下
