### ISSUE TITLE
系统可否支持自动重连？

### ISSUE THREAD

**Issue by Bigfoot0007** [shadowsocks/shadowsocks-windows#2376]
SS是一个很好的软件，我已经使用了一段时间，发现：
1. 无法自动重连，比如，当我本地的网络断了，再连接后，就无法重连了。这个时候重启SS可以解决问题，当有时还需要重启浏览器才可以。
2.本地SS到远程的SS Server，是否可以提供TLS？这样信息更安全，也不会被监测到。

**Comment by chenshaoju** [comment]
1.我没遇到过这个问题，日志中有显示什么东西吗？
2.你可以尝试套一个插件，目前v2ray-plugin、Cloak和GoQuite都提供伪装成TLS的选项，具体请阅读：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by JehoshuaLyu** [comment]
现在ss究竟能不能用？╰😩╮不能上Google身心难受…------------------ 原始邮件 ------------------
发件人: "Chen Shaoju"<notifications@github.com>
发送时间: 2019年6月4日(星期二) 上午9:51
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [shadowsocks/shadowsocks-windows] 系统可否支持自动重连？ (#2376)



1.我没遇到过这个问题，日志中有显示什么东西吗？
 2.你可以尝试套一个插&#x4EF6;，目前v2ray-plugin、Cloak和GoQuite都提供伪装成TLS的选项，具体请阅读：#2228 (comment)
 
&mdash;

**Comment by AnyWAT** [comment]
> 现在ss究竟能不能用？╰😩╮不能上Google身心难受…

如网络已有 IPv6，近些天也无异常的简单操作。。。https://github.com/XX-Net/XX-net/issues/12477

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
