### ISSUE TITLE
最近不能上网的先别上了，抽空多学学八荣八耻吧

### ISSUE THREAD

**Issue by lmshao** [shadowsocks/shadowsocks-windows#2378]
这阵子不能上外网的就别上了，shadowsocks仓库因为讨论的太多导致Issues都被停用了，别因为乱说话导致整个shadowsocks全部玩完。。。
我们一起来学习~
以热爱祖国为荣，以危害祖国为耻；
以服务人民为荣，以背离人民为耻；
以崇尚科学为荣，以愚昧无知为耻；
以辛勤劳动为荣，以好逸恶劳为耻；
以团结互助为荣，以损人利己为耻；
以诚实守信为荣，以见利忘义为耻；
以遵纪守法为荣，以违法乱纪为耻；
以艰苦奋斗为荣，以骄奢淫逸为耻。

**Comment by damao4123** [comment]
哎，一看整个shadowsocks主项目 removed

**Comment by esvvv** [comment]
封得好，希望是永久的。

**Comment by xiaolisheng** [comment]
有没有人知道shadowsocksr的情况

**Comment by chenshaoju** [comment]
Issues 是反馈软件问题的地方，请不要起哄。
