### ISSUE TITLE
是否shadowsocks流量特征已经被gfw识别了

### ISSUE THREAD

**Issue by xiaolisheng** [shadowsocks/shadowsocks-windows#2380]
从6.1开始断断续续换了4次ip了，每次都没坚持超过10个小时，而且看到issues里面有很多同好在别的vps提供商也是差不多的情况，所以不是我的vps提供商的问题，求解答。
另请问有人知道shadowsocksr的项目地址，以及那个项目之前声称的流量伪装，在这几天有出过问题吗？

**Comment by zk-123** [comment]
同问题，ip连续被封。

**Comment by chenshaoju** [comment]
是，如果你的服务器是你搭建的，请尝试套个插件： https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by jasonliul** [comment]
我手裡還有一枚國人節點, 需要host綁定域名, 不確定是否普遍現象.

**Comment by xiaolisheng** [comment]
@jasonliul 
host绑定域名是dns被劫持了，不是gfw的业务吧。
你说的vps的ip是连续的，是有可能的，不过vps也有大量正常业务非代理业务，不可能是这种方式来封ip，容易误伤。

**Comment by jasonliul** [comment]
@xiaolisheng
九評美國之後, 應該是完全不在意誤傷了, 當年與蘇聯反目, 也是這種腐臭的九評.

**Comment by xiaolisheng** [comment]
@jasonliul 
吾乃升斗小民，不论国事。

**Comment by jasonliul** [comment]
前几天股价出现64字样, 连带"股价"这类关键词, 全部成为敏感词.
无奈, 当下确实是高误杀模式.

**Comment by esvvv** [comment]
支持国家封杀github，根绝反动、反华翻墙软件的传播，消除github上的反动言论的煽动，维护伟大的社会主义制度，横扫这些资本主义的牛鬼蛇神！

**Comment by chenshaoju** [comment]
Issues 是提交和反馈软件问题的地方，请不要起哄，谢谢。

**Comment by WangDaLei** [comment]
不知道是识别的协议  还是 识别的加密方式。。 太坑了 直接封ip  ssh都上不了

**Comment by chenshaoju** [comment]
@WangDaLei 个人观点：https://github.com/shadowsocks/shadowsocks-windows/issues/2366#issuecomment-498899971
