### ISSUE TITLE
浏览器中无法使用本机IP及端口访问Web Server

### ISSUE THREAD

**Issue by cheng-github** [shadowsocks/shadowsocks-windows#2381]
### Shadowsocks version / 影梭版本
4.1.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10  无,Net framework

### Steps you have tried / 操作步骤
1.  使用shadowsocks连接远程vps
2.  vps ip被封，shadowsocks失效，关闭shadowsocks
3.  无法在浏览器中输入https://192.168.xx访问本地运行的server，提示Firefox can’t establish a connection to the server at 192.168.1.109:5001.  Chrome也是相似。

### What did you expect to see? / 期望的结果
输入https://192.168.xx期望出现本地Server的web页面

### What did you see instead? / 实际结果
浏览器中显示
Firefox can’t establish a connection to the server at 192.168.1.109:5001
&&
In Chrome
Your Internet access is blocked Firewall or antivirus software may have blocked the connection.
局域网中其他机器可以通过192.168.1.109:5001访问到本机起的Web Server，本机使用Fiddler作为代理可以访问，但所有的浏览器无法正常通过输入192.168.1.109:5001访问

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

[2019-06-05 01:25:45] 67.130.xxx.xxx:xxxx timed out
[2019-06-05 01:25:50] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-06-05 01:25:50] Shadowsocks started (4.1.2)
[2019-06-05 01:25:50] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/2040#issuecomment-429540937

**Comment by cheng-github** [comment]
按照说明重命名user-wininet.json 文件，重新启动又会再次生成该文件，按照步骤进行操作问题依然未解决。我猜测是因为SS修改了注册表某格地方导致的该问题，但我不知道具体改了哪些地方

**Comment by cheng-github** [comment]
![捕获](https://user-images.githubusercontent.com/24241010/58927903-fe181480-8782-11e9-9c88-398dfe83c081.PNG)

**Comment by cheng-github** [comment]
![捕获](https://user-images.githubusercontent.com/24241010/58927964-36b7ee00-8783-11e9-8390-e26a4b030338.PNG)

**Comment by cheng-github** [comment]
![捕获2](https://user-images.githubusercontent.com/24241010/58927974-40415600-8783-11e9-86c5-cc571099eaeb.PNG)

**Comment by cheng-github** [comment]
局域网中其他机器可以通过输入本机IP访问...
感觉问题很诡异

**Comment by AnyWAT** [comment]
貌似没使用浏览器代理扩展。https://github.com/shadowsocks/shadowsocks-windows/issues/2381#issuecomment-498922912 试试：BypassList 增加 127.0.0.1;localhost ？

**Comment by chenshaoju** [comment]
文件始终是会自动生成的，请确保已经在退出SS、删除 user-wininet.json 后，重新设置了系统代理。

另外，就是楼上所说，请尝试将你的局域网IP加入IE的bypas列表。

![image](https://user-images.githubusercontent.com/515763/58929829-71258900-878b-11e9-8a83-27fed0d468a6.png)

**Comment by cheng-github** [comment]
代理设置如下图:

![捕获2](https://user-images.githubusercontent.com/24241010/58931396-25c2a900-8792-11e9-9c0e-88acaeec9ba1.PNG)

在已推出SS,删除user-wininet.json 设置浏览器代理为自动检测模式下的情况重启SS，问题依然未解决。

**Comment by cheng-github** [comment]
我在FireFox中设置不使用任何代理，在Chrome中设置自动检测，都是同样的连接被重置。

**Comment by chenshaoju** [comment]
我仔细看了一下Chrome的错误提示，这个提示似乎和SS无关（ERR_NETWORK_ACCESS_DENIED）。

你的Chrome连接上了你的WebServer，但是WebServer返回了HTTP 403。

请尝试使用IE浏览器，或者wget/curl访问一下你的这个地址，看看是否返回的403错误。

可能是你的WebServer配置有问题，阻止了来自你本机的IP地址访问。

**Comment by cheng-github** [comment]
如图所示，应该是连接被拦截了，并没有得到服务器的反馈

![捕获](https://user-images.githubusercontent.com/24241010/58931785-a2a25280-8793-11e9-9df1-4049ec546b8f.PNG)

**Comment by cheng-github** [comment]
注册表配置:

![捕获](https://user-images.githubusercontent.com/24241010/58931864-e72dee00-8793-11e9-9fa6-80695ead7a61.PNG)

**Comment by cheng-github** [comment]
使用telnet 192.168.1.109 3000 显示正常

![捕获](https://user-images.githubusercontent.com/24241010/58931911-29572f80-8794-11e9-86fb-4dd4f3204c2c.PNG)

**Comment by chenshaoju** [comment]
如果Firefox被配置成不是用代理，那么SS本身也是不工作的。

Telnet能通只能说明端口是打开的，HTTP协议是否能连接上，不得而知。

请使用 curl 测试一下： https://curl.haxx.se/windows/

**Comment by cheng-github** [comment]
很抱歉这几天我身边没有电脑，等我回去就回复您。

**Comment by cheng-github** [comment]
curl 测试显示没有问题

![捕获](https://user-images.githubusercontent.com/24241010/59167064-ee714500-8b61-11e9-8344-54b66e3b6877.PNG)

这...浏览器中打不开是什么情况..

**Comment by chenshaoju** [comment]
请尝试使用 curl -vv <URL> ，我想看看HTTP头是如何请求与返回的。

另外，不是192.168.1.109:5001吗？

**Comment by cheng-github** [comment]
em...下面是测试结果:

![捕获](https://user-images.githubusercontent.com/24241010/59168786-def5fa00-8b69-11e9-8701-b156bf7d3c72.PNG)

**Comment by cheng-github** [comment]
And:

![捕获](https://user-images.githubusercontent.com/24241010/59169017-09948280-8b6b-11e9-9563-4c76063956e1.PNG)

**Comment by cheng-github** [comment]
IP变化是因为我在不同地方使用的机器，然后端口分别对应本地起的两个不同Web server.

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/59169481-29c54100-8b6d-11e9-9537-6c0f0f1d534d.png)

1.你是直连你的目标主机的目标端口的，没有经过代理，如果经过代理，会这样：
![image](https://user-images.githubusercontent.com/515763/59169519-51b4a480-8b6d-11e9-94e8-d704a4f49985.png)

2.你的目标服务器返回的是 401 未授权，这意味着你的服务器拒绝了你的访问，请仔细检查你的服务器的ACL（如果有）配置。

整个问题和SS没有任何关系，是你的服务器配置有误。

**Comment by cheng-github** [comment]
em...感觉很难解释清楚了现在...
401是未授权的拒绝，自己的代码逻辑自己还是比较清楚的，但是还是会重定向到提示未授权的html页面的，但是浏览器直接显示连接被拦截，这与预期的结果不符。
浏览器应该显示的内容如下图所示:


如果我访问登陆页面(不需要授权)，如之前的截图所示，就会出现使用localhost可以访问但无法直接使用ip地址替代localhost去访问。为验证我的说法，使用curl访问不需要权限页面如下图:


| |
cheng
|
|
cheng_deeplove@163.com
|
签名由网易邮箱大师定制
在2019年6月10日 10:51，Chen Shaoju<notifications@github.com> 写道：

1.你是直连你的目标主机的目标端口的，没有经过代理，如果经过代理，会这样：


2.你的目标服务器返回的是 401 未授权，这意味着你的服务器拒绝了你的访问，请仔细检查你的服务器的ACL（如果有）配置。

整个问题和SS没有任何关系，是你的服务器配置有误。

**Comment by cheng-github** [comment]
所以我的问题是，首次启动SS的时候是否修改了关于浏览器的某些注册表的配置，所以才会导致浏览器无法正常解析IP地址。
| |
cheng
|
|
cheng_deeplove@163.com
|
签名由网易邮箱大师定制
在2019年6月10日 10:51，Chen Shaoju<notifications@github.com> 写道：

1.你是直连你的目标主机的目标端口的，没有经过代理，如果经过代理，会这样：


2.你的目标服务器返回的是 401 未授权，这意味着你的服务器拒绝了你的访问，请仔细检查你的服务器的ACL（如果有）配置。

整个问题和SS没有任何关系，是你的服务器配置有误。

**Comment by chenshaoju** [comment]
1.curl 根本不会理会Shadowsocks（Windows）的PAC代理设置，无论Shadowsocks的系统代理如何设置，curl 都不会经过代理，我相信你能看懂下图：
![image](https://user-images.githubusercontent.com/515763/59173067-b8da5500-8b7d-11e9-9264-6a6bb43cfc8b.png)


2.Shadowsocks 只会修改IE浏览器的代理设置，在退出SS的情况下，只要手动清空了IE的代理设置，那么就不会经过代理。

3.现在的主流浏览器不一定会显示Web Server返回的错误页面，而是显示一个“友好的”错误页面，具体请参阅：
https://superuser.com/questions/202244/show-http-error-details-in-google-chrome
你 curl 返回的结果下面的那一堆包含HTML的乱码就是你的Web Server返回的错误信息，由于使用的是UTF-8编码，你可能得使用 wget 访问你的URL，将 .html 下载回来后，再用浏览器打开 .html 页面才能看到错误信息： `wget http://123.45.67.89:1234 -O ouput.htm`

这是你的Web Server的问题，我强烈建议你检查你的Web Server配置；你可以继续怪罪SS，但是这不是解决问题的方向。

**Comment by cheng-github** [comment]
很抱歉给您造成了困扰，经过这么久时间的排查，我发现是因为我下载了一个叫做净网大师的广告拦截软件，经鉴定流氓软件无疑，它将我浏览器对本地ip的http请求给拦截了，非常抱歉。:broken_heart:

**Comment by cheng-github** [comment]
顺带向您提个小问题，就是现在使用ss比较容易被识别导致封ip，有什么好的解决办法嘛

**Comment by chenshaoju** [comment]
目前建议套一个插件： https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836
