### ISSUE TITLE
顶置 不能连的较官方解释 底下那么多废话的真烦人

### ISSUE THREAD

**Issue by ingoSDwater** [shadowsocks/shadowsocks-windows#2383]
嗯，差不多，大面积机场停机
![{K4$(GKJT2ZNRSX975V}B$0](https://user-images.githubusercontent.com/30817974/58786393-06087500-861a-11e9-8483-fc0a9a8140ea.png)

_Originally posted by @GODOFHOU in https://github.com/shadowsocks/shadowsocks-windows/issues/2368#issuecomment-498156780_

**Comment by ingoSDwater** [comment]
1989.6.4事件，至今仍然造成中国民族运动的影响，所以每年6月是政治敏感期，故导致各种言论和言论运动的渠道封闭，故造成shadowsocks与国内弹幕功能的error，据传6号重点敏感时间后逐渐恢复。傻屌们，能不能脱离技术看到点问题背后的问题？shut the fuck up ，stopping nonsense talking，thx so so much

**Comment by Tweicx** [comment]
咋回事啊 那咋整啊 大佬你会不会啊

**Comment by AnyWAT** [comment]
✌借助 https://github.com/Kisesy/gscan_quic 用原生的XX-Net 没感觉。XX-net/XX-Net#12477

**Comment by ingoSDwater** [comment]
你们改用 ShadowsocksR-4.7.0 这个软件，百度搜索【shadowrocket 4.7.0】就有。   然后去网上找节点。
[image: 209835549614561491.png]
我这里先放一个节点 你们用着
[image: image.png]

Chen Shaoju <notifications@github.com> 于2019年6月5日周三 上午10:23写道：
