### ISSUE TITLE
有劳大大添加socks4前置支持

### ISSUE THREAD

**Issue by jasonliul** [shadowsocks/shadowsocks-windows#2384]
通常惯例, Socks5几乎都是商用 --虽然偶尔有一点试用节点.
而Socks4是免费, 近几年亚洲socks4节点明显增多, 表现也还稳定.

恕我直言, SS转型玩插件并不是出路.

几年前, 有阵番茄工具全盛, 我曾经邀请荷兰朋友测试过所有新出代理.

如果按照国际视角. 那么SS, Goflyway才是精品, 代理效率一流. 谷歌做个SS变种Outline就是明证.

而SSR实际并不高效, 因为添加混淆, 服务端还需要其他加速处理. 
V2ray从内核就不是高效代理.

印尼流行ssh, 不过现在有些服务商, 额外提供自家专用squid前置, 以备不虞. 这大概也是中国雕友的出路.

**Comment by celeron533** [comment]
然后所有的socks4代理连接全被阻断。。。
实际上前置代理也是一种特殊类型的插件，也是“玩插件”的内容。
