### ISSUE TITLE
请问一下，PAC文件和SSR的通用吗？SSR现在更新不了PAC，我想用SS的PAC替换，谢谢！

### ISSUE THREAD

**Issue by Linqing0808** [shadowsocks/shadowsocks-windows#2386]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
理论上是通用的，你可以试试。

你需要将 Shadowsocks.exe 所在目录下的 pac.txt 替换过去即可。

**Comment by lk-timeout** [comment]
问一下，现在可以了吗，不会封ip吗？

**Comment by chenshaoju** [comment]
不知道，理论上应该有个过渡期，猜测下周一可能就会恢复正常。

**Comment by tangmaosen** [comment]
问一下各位还会封IP吗/

**Comment by Linqing0808** [comment]
> 理論上是通用的，你可以試試。
> 
> 你需要將Shadowsocks.exe所在目錄下的pac.txt替換過去即可。

的确可以，我发现ss、ssr、v2ray都是用同一种pac文件

**Comment by Panseng** [comment]
ssr客户端在哪里下载？
或者ss for windows怎样配置ssr的插件？

**Comment by chenshaoju** [comment]
Shadowsocks 没有 SSR 的插件。

目前SSR有许多第三方维护的版本，请注意，这些版本由第三方维护，与 Shadowsocks for Windows 并无关联：https://github.com/shadowsocksrr/shadowsocksr-csharp/releases
