### ISSUE TITLE
求助大家，我的shadowsocks 4.0.10 昨天不能使用了，这是为什么呢，7月10几号才过期的，我监测我的ip被封了，怎样换一个新ip呢

### ISSUE THREAD

**Issue by bonniess** [shadowsocks/shadowsocks-windows#2388]
如题所示，谢谢各位大神热心帮助

**Comment by vibexie** [comment]
好像所有的VPN都被封了，我几台服务器都用不了

**Comment by bonniess** [comment]
我监测我的ip被封了，怎样换一个新ip呢

**Comment by chenshaoju** [comment]
请与你的VPS服务商联系，看能否更换IP。

**Comment by sleiqx** [comment]
最近别折腾了。儿童节大面积封了一波，昨天又封了一波。

**Comment by tuhang** [comment]
> 请与你的VPS服务商联系，看能否更换IP。

你好，请问有什么办法可以检测自己的IP是否被封？
我在服务器终端ping baidu、youtube可以ping通，但是ping现用主机ipA失败（国内电脑ping主机ipA能通）

**Comment by vmjcv** [comment]
把你服务器ip封掉了，你数据走不到自己的服务器，所以就凉了，你随便找一个测试联通性的网站事实你的服务器ip就可以了
可以用亚马逊云服务器，可以申请动态ip，凉了一个ip就换一个ip

**Comment by tuhang** [comment]
检测过了，通过国内外的端口扫描确定了是被封了。

**Comment by vmjcv** [comment]
最近一直在封，你需要换一个可以提供动态IP的云服务器商，比如亚马逊。或许还需要换个加密方式，比如V2ray

**Comment by bonniess** [comment]
@vmjcv 你好，请问怎样获得动态ip啊，要收费吗，我之前是自己弄了一个国外ip

**Comment by bonniess** [comment]
> 把你服务器IP封掉了，你数据走不到自己的服务器，所以就凉了，你随便找一个测试联通性的网站事实你的服务器IP就可以了
> 可以用亚马逊云服务器，可以申请动态IP，凉了一个IP就换一个IP

在哪里申请动态ip，要收费吗

**Comment by vmjcv** [comment]
> @vmjcv你好，请问怎样获得动态IP啊，要收费吗，我之前是自己弄了一个国外IP

这是亚马逊的官方文档，https://docs.aws.amazon.com/zh_cn/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html?icmpid=docs_ec2_console
其他的云服务平台没有深入了解
pa：申请完ip需要绑定实例，要不需要收费

**Comment by bonniess** [comment]
> > @vmjcv你好，请问怎样获得动态IP啊，要收费吗，我之前是自己弄了一个国外IP
> 
> 这是亚马逊的官方文档，https://docs.aws.amazon.com/zh_cn/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html?icmpid=docs_ec2_console
> 其他的云服务平台没有深入了解
> Pa：申请完IP需要绑定实例，要不需要收费

谢谢大神，我研究一下

**Comment by esvvv** [comment]
不会解封的，历史的车轮要来了，各位保重！

**Comment by AnyWAT** [comment]
✌借助 https://github.com/Kisesy/gscan_quic 用原生的XX-Net 没感觉。XX-net/XX-Net#12477
