### ISSUE TITLE
socks5 协议登录请求未根据 NMETHODS 计算长度，而是只检查了下第一个字节就抛弃了第一次收到的数据..

### ISSUE THREAD

**Issue by GameXG** [shadowsocks/shadowsocks-windows#239]
我用 ss 的socks5代理时意图降低延迟，直接同时发送登录及请求，结果只收到了登录回应...
检查代码发现了这个问题，先记录下。

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/TCPRelay.cs#L175

**Comment by clowwindy** [comment]
目前暂时只考虑普通的客户端如浏览器。
