### ISSUE TITLE
弹窗报错：1080是系统保留端口

### ISSUE THREAD

**Issue by Wings-Fantasy** [shadowsocks/shadowsocks-windows#2392]
### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1903 专业版。我的电脑中没有安装.net运行库，但是能正常使用，不知道是不是因为缺少运行库的原因。

### Steps you have tried / 操作步骤
打开ss软件

### What did you expect to see? / 期望的结果
正常使用

### What did you see instead? / 实际结果
弹窗报错：1080是系统占用端口。。。。。
报错的全文和#2355一致

这个问题不经常出现，差不多是10天左右出现一次。换任何一个端口都会报这个错误，cmd查询没有发现端口被占用。关闭软件再打开，这样重复几次就又好了，很奇怪的一个问题，请问这个怎么解决？

**Comment by chenshaoju** [comment]
换一个高位端口呢？比如 10800 ？
可能和 https://github.com/shadowsocks/shadowsocks-windows/issues/1835 一致。

**Comment by Wings-Fantasy** [comment]
10800这种高位端口我没有尝试过，等到如果再次出现这个问题的时候可以尝试一下。

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1835#issuecomment-453528715
