### ISSUE TITLE
更新了Windows 10 May 2019 Update以后Shadowsocks工作异常

### ISSUE THREAD

**Issue by phoenixgao** [shadowsocks/shadowsocks-windows#2393]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
.NETFramework 4.8 (528049)

### Steps you have tried / 操作步骤
重装 Shadowsocks

### What did you expect to see? / 期望的结果
可以正常连上Server

### What did you see instead? / 实际结果
连不上

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-06-09 22:43:56] Shadowsocks started (4.1.6)
[2019-06-09 22:43:59] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

考虑是.NET升级导致

**Comment by chenshaoju** [comment]
这看起来很像被墙了，请先测试一下：
1.请使用第三方的服务测试你的服务器的连通性：https://ipcheck.need.sh/
2.请使用第三方的软件测试你的服务器从你计算机的连通性：https://github.com/chenshaoju/tcpportcheck

如果境外境内都不通，请检查你的服务器是否死了。
如果境外通境内不通，说明你的服务器被墙了，请尝试换一个端口或者IP。
如果境内境外都通，请尝试在相同网络的其他设备上测试一下你的服务器是否能通。

**Comment by phoenixgao** [comment]
@chenshaoju 同样配置 Android 客户端，Mac 客户端都可以正常使用

**Comment by chenshaoju** [comment]
Windows和Android/Mac在同一个局域网（同一个网络出口）吗？

我这儿Windows 10 (18362.116) 没有任何问题。

![2019-06-06](https://user-images.githubusercontent.com/515763/59008107-efe9f700-885b-11e9-821b-7cde5c3737f2.png)

**Comment by phoenixgao** [comment]
唔。。不是windows更新的原因的话那就不知道了。。除了更新别的啥也没改过

是同一网络同一出口，同台Mac的bootcamp双系统

**Comment by chenshaoju** [comment]
对了，请确保配置正确（服务器IP、端口、加密方式、密码），如果有插件，请确保插件配置也正确。

**Comment by phoenixgao** [comment]
配置都是一致的。最后重装系统解决了。由于无法重现，先关掉这个issue。谢谢@chenshaoju
