### ISSUE TITLE
关闭软件或者系统代理为禁用后，无法正常访问网页(爱奇艺，优酷等正常网页)

### ISSUE THREAD

**Issue by MisterBowie** [shadowsocks/shadowsocks-windows#2394]

**Comment by MisterBowie** [comment]
网页 显示ERR_PROXY_CONNECTION_FAILED  软件版本为4.1.6

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2040#issuecomment-429540937

**Comment by awei78** [comment]
有时退出后，IE代理那里没有复原，手动去置一下就好了

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
