### ISSUE TITLE
当多个服务器+插件并选择高可用模式时，只有一个插件在运行

### ISSUE THREAD

**Issue by sbwtw** [shadowsocks/shadowsocks-windows#2395]
添加多个服务器配置，并且每个服务器都配置了使用 `v2ray-plugin.exe` 插件进行混淆，此时应该为每个配置启动一个 `v2ray` 转发进程，但是发现总共只启动了一个插件进程，并且实际测试也只有一个服务器能正常连接。

**Comment by chenshaoju** [comment]
试试负载均衡呢？

高可用理论上就是使用最可用的那一个。

当然，也可能有问题，我这儿测试环境有限。

**Comment by sbwtw** [comment]
@chenshaoju 负载均衡是正常的。不过我理解负载均衡应该是根据一定算法预先选择某个服务器，而高可用应该是向所有服务器请求连接，然后从连接成功的里面选择一个。

**Comment by sbwtw** [comment]
@chenshaoju 负载均衡是正常的。不过我理解负载均衡应该是根据一定算法预先选择某个服务器，而高可用应该是向所有服务器请求连接，然后从连接成功的里面选择一个。

**Comment by linguoliang** [comment]
> @chenshaoju 负载均衡是正常的。不过我理解负载均衡应该是根据一定算法预先选择某个服务器，而高可用应该是向所有服务器请求连接，然后从连接成功的里面选择一个。

我的高可用好像不能正常工作，我在服务器上设置了ipv6 和 ipv4 ，但是在网络环境只支持ipv4的时候，ss无法自动切换到ipv4

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
