### ISSUE TITLE
使用前置代理时插件是否走前置代理？

### ISSUE THREAD

**Issue by GainSury** [shadowsocks/shadowsocks-windows#2399]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 1903

### Steps you have tried / 操作步骤
勾选前置代理，前置代理为另外一个shadowsocks 4.1.6客户端。
使用前置代理的这个客户端使用v2ray-plugin插件连接网络。

### What did you expect to see? / 期望的结果
v2ray-plugin插件通过前置代理连接网络

### What did you see instead? / 实际结果
v2ray-plugin插件没有通过前置连接网络

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/59203935-2fa13d80-8bd2-11e9-955d-fa3ec19d325f.png)
