### ISSUE TITLE
求助，4.1.6版本报错，但在其他电脑可以正常使用

### ISSUE THREAD

**Issue by yuzunyue** [shadowsocks/shadowsocks-windows#2401]
[2019-06-11 09:14:13] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

请问是否为端口问题，这个配置在其他电脑可以正常使用

**Comment by chenshaoju** [comment]
请确保相同时间的情况下，其他可用。

请使用第三方的测试服务测试一下你所使用的服务器的连通情况：https://ipcheck.need.sh/

**Comment by yuzunyue** [comment]
![image](https://user-images.githubusercontent.com/32872977/59238103-35793c00-8c2f-11e9-81a6-8b4d55592d1a.png)
正常，经测试其他电脑也可以正常使用，唯独这台电脑无法连通

**Comment by chenshaoju** [comment]
这说明你的服务器工作正常，可能是本机的问题，请尝试使用这个小工具： https://github.com/chenshaoju/tcpportcheck ，在有问题的计算机上测试一下端口访问是否能通？

**Comment by yuzunyue** [comment]
测试结果为通

**Comment by yuzunyue** [comment]
![image](https://user-images.githubusercontent.com/32872977/59241591-dc170a00-8c3a-11e9-87c4-5ec287c744d7.png)
是在有问题的机器上测试的

**Comment by chenshaoju** [comment]
分三个地方检查。
1.请尝试在编辑服务器界面右下角的代理端口换一个看看，比如换成10800，然后再试。
2.如果不行，请检查Windows自带的网络防火墙，暂时关闭看看是否能正常。
3.请以管理员身份启动命令提示符或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重启计算机看看，如果有安全软件拦截，请点击允许。
如果是手动指定网卡IP，重启后可能如果无法上网，需要重新指定一次IP。

**Comment by yuzunyue** [comment]
都试过了，均不可以，是否为公司防火墙拦截了

**Comment by chenshaoju** [comment]
`从传输流收到意外的 EOF 或 0 个字节` 其实就是连接被重置。

如果电脑有WiFi或者USB，使用手机热点或手机共享上网，能使用吗？

**Comment by gys0000** [comment]
你好，我的ip都是通的，但是tcp检测时不通。是什么原因呢？

**Comment by chenshaoju** [comment]
是国内TCP不通还是国内国外TCP都不通？
如果是前者，意味着你的服务器所有端口被墙了（可能）。
如果是后者，请检查你的服务器的防火墙配置，比如 iptables、ufw等。

**Comment by gys0000** [comment]
https://ipcheck.need.sh/  这个测试都是通的，只是https://github.com/chenshaoju/tcpportcheck 这个测试，结果是不通。可能是一键ss失效了。

**Comment by caozhiyue** [comment]
@chenshaoju 我的是国内TCP不通，现在应该怎么办，大佬

**Comment by chenshaoju** [comment]
@caozhiyue 请不要到处发，移动到 https://github.com/shadowsocks/shadowsocks-windows/issues/2408#issuecomment-502354765
