### ISSUE TITLE
求助，新手小白，端口时通时不通，连接不上

### ISSUE THREAD

**Issue by chendejin123** [shadowsocks/shadowsocks-windows#2403]
### Shadowsocks version / 影梭版本
4.0.2
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win8.1
### What did you see instead? / 实际结果
![image](https://user-images.githubusercontent.com/51603810/59251362-396f8300-8c5c-11e9-8f1c-8c63fc9a92ec.png)
![image](https://user-images.githubusercontent.com/51603810/59251414-56a45180-8c5c-11e9-8f84-ca24fd700216.png)
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-06-11 15:03:35] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于意外的数据包格式，握手失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-06-11 15:04:09] Detected: User Rule file 'user-rule.txt' was created.
[2019-06-11 15:04:10] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于意外的数据包格式，握手失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-06-11 15:04:23] Shadowsocks started
[2019-06-11 15:04:28] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于意外的数据包格式，握手失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-06-11 15:09:41] Shadowsocks started
[2019-06-11 15:09:44] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2019-06-11 15:10:04] Shadowsocks started
[2019-06-11 15:11:02] Shadowsocks started
[2019-06-11 15:11:08] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2019-06-11 15:11:46] Shadowsocks started

**Comment by chenshaoju** [comment]
你使用的版本实在太旧了，请尝试更新到最新版。

另外，如果你的服务器是自己搭的，情尝试套一个插件看看是否会有所改善：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by 78775546946** [comment]
更新一下主程序，然后自建的话，更换一下服务的端口

**Comment by lucky8888** [comment]
看下防火墙开放的端口  
```
sudo firewall-cmd --zone=public --list-port
```

**Comment by bestinera** [comment]
测试IP是否墙ping.me
被墙了就要换IP。
没被墙，就是你ss搭建问题或者端口没打开。
一键脚本搭建ss。这是go版本的。不懂ss手动搭建用这个。
https://doubibackup.com/kd691l4o.html
用谷歌搜索端口扫描，看看ss的端口是否打开。
关闭就自己搜索自己VPS对应系统的打开防火墙的办法。
你提供的东西太少了，VPS系统，是否安装面板，手动搭建ss过程（脚本搭建一般没问题），是否测试ss端口开闭，IP是否被墙测试。这些才是需要的。

**Comment by chendejin123** [comment]
谢谢大家，这两天问题还是没解决。
ip:104.224.144.250;端口：26581，测了都没什么问题。
搭建是用putty，只是照着教程脚本搭的，重新弄了，还是老样子。
shadowsock已经改到了最新版，google打开报错ERR_SSL_PROTOCOL_ERROR
插件按照样式弄了，可能自己不太会，没有连接成功。
顺便问下sudo firewall-cmd --zone=public --list-port这种指令，用在哪里？
感谢大家！！
日志如下：
[2019-06-13 20:29:53] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于意外的数据包格式，握手失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请检查你的加密方式、密码是否正确。

如果你使用的是一件脚本，请仔细检查你的脚本使用的是SS还是SSR，这两者不一定通用。

**Comment by chendejin123** [comment]
加密方式和密码都是对的
之前一直用的脚本是ss
能问下xshell登录名和密码是啥嘛，是ip和对应的密码还是别的什么
谢谢 @chenshaoju

**Comment by chendejin123** [comment]
刚刚会用putty查些信息
![image](https://user-images.githubusercontent.com/51603810/59441357-07604b80-8e2b-11e9-8afa-11dc78d85c83.png)
这里面serve为0.0.0.0，这是对的吗？

**Comment by chenshaoju** [comment]
你用的是libev版还是python版？

0.0.0.0 是正确的，配置文件看不出什么问题。

你的VPS是否有网络防火墙？比如iptables或者ufw之类的？

**Comment by chendejin123** [comment]
怎么看libev还是python？
![image](https://user-images.githubusercontent.com/51603810/59479735-a0757d80-8e90-11e9-9ff8-43dd99132589.png)
看不懂图片上的含义，好像应该没有防火墙。
谢谢

**Comment by chenshaoju** [comment]
libev是`shadowsocks-libev`，你是如何安装SS的服务端程序的？

请使用 iptables -L 命令列出所有规则。

**Comment by chendejin123** [comment]
安装脚本：wget — no-check-certificate -O shadowsocks.sh https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks.sh
chmod +x shadowsocks.sh
./shadowsocks.sh 2>&1 | tee shadowsocks.log
![image](https://user-images.githubusercontent.com/51603810/59481156-c81b1480-8e95-11e9-96f0-edd2ebe3db6d.png)

**Comment by chendejin123** [comment]
现在电脑+无线、手机+无线、电脑+热点都连接不上 @chenshaoju 
@chenshaoju

**Comment by chenshaoju** [comment]
`Description: One click Install Shadowsocks-Python server` ，这是Python的，理论上也能用。

防火墙配置没有问题，我仍然倾向于你的客户端配置可能有问题，密码或者加密方式可能不对。

另外，如果可能，请尝试在双方使用aes-256-gcm加密算法看看。

**Comment by chendejin123** [comment]
![image](https://user-images.githubusercontent.com/51603810/59485969-63b68000-8eaa-11e9-8c27-037422bf71c3.png)
![image](https://user-images.githubusercontent.com/51603810/59485996-716c0580-8eaa-11e9-8604-b5024dd0c029.png)
![image](https://user-images.githubusercontent.com/51603810/59486048-9791a580-8eaa-11e9-9885-66037e07bbd2.png)
![image](https://user-images.githubusercontent.com/51603810/59486069-b5f7a100-8eaa-11e9-8f4b-f1364bdb07fd.png)
日志文件
![image](https://user-images.githubusercontent.com/51603810/59486124-eb03f380-8eaa-11e9-9b12-669d1703c509.png)
改成aes-256-gcm后还是无法登陆google，但是日志和google变得和之前不一样了，google之前错误是ssl什么的

**Comment by chendejin123** [comment]
改成aes-256-gcm，google报错ERR_CONNECTION_CLOSED，之前ERR_SSL_PROTOCOL_ERROR
![image](https://user-images.githubusercontent.com/51603810/59486838-4a630300-8ead-11e9-8711-63b45cce00e2.png)
日志变了

**Comment by chenshaoju** [comment]
我尝试从脚本作者的网站上获得具体信息，但是作者删博了。

无法确定发生了什么……

**Comment by chendejin123** [comment]
![image](https://user-images.githubusercontent.com/51603810/59493920-9e2a1800-8ebe-11e9-80df-c39ae562fe7b.png)
看了之前的帖子，您看这样正常吗

**Comment by chenshaoju** [comment]
感觉你的计算机上的网络组件好像有问题？理论上 `netsh interface tcp reset` 不应该出现这个错误提示的：

![image](https://user-images.githubusercontent.com/515763/59498587-47294080-8ec8-11e9-83e3-2ee6c3f0a27c.png)

**Comment by chendejin123** [comment]
问题已解决，换了个搭建脚本，顺便将端口改了，然后连接成功。
在此特别感谢 @chenshaoju @78775546946 @lucky8888 @bestinera
