### ISSUE TITLE
"Shadowsocks.Util.SystemProxy.ProxyException" in Shadowsocks.exe (PRIVOXY)

### ISSUE THREAD

**Issue by prvmskydev** [shadowsocks/shadowsocks-windows#2404]
### Environment(Operating system, .NET Framework, etc) Windows, .NET Framework 4.7.2
Windows 10 LTSC x64 ver.1809

### Steps you have tried
Compile app

### What did you expect to see? 
Working app....

### What did you see instead? 
1) WINDOWS WARNING:
Error occured when process proxy setting, do you want reset current and retry? (im click yes, if no - ss not working)
2) WINDOWS ERROR:
Unrecoverable proxy setting error occured, see log for detail.

LOG:
[2019-06-11 23:56:44] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

### Config and error log in detail (with all sensitive info masked)2019-06-11 23:56:44] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

USER-WININET deleting not working! All files without Shadowsocks.exe deleting - not working!

**Comment by chenshaoju** [comment]
Please check this service is running:
![image](https://user-images.githubusercontent.com/515763/56583369-015ca400-660c-11e9-950a-90694d028a9b.png)

If unable to start, This may case by system issue: https://github.com/shadowsocks/shadowsocks-windows/issues/2234

Please try rebooting the system.

**Comment by prvmskydev** [comment]
> Please check this service is running:
> ![image](https://user-images.githubusercontent.com/515763/56583369-015ca400-660c-11e9-950a-90694d028a9b.png)
> 
> If unable to start, This may case by system issue: #2234
> 
> Please try rebooting the system.

I can't start it. All buttons disabled, reboot not help.

**Comment by prvmskydev** [comment]
![изображение](https://user-images.githubusercontent.com/51052515/59342247-10a9c500-8d12-11e9-97bf-48aa536041ae.png)

**Comment by prvmskydev** [comment]
I fix it with regedit. Thanks all!

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinHttpAutoProxySvc and Start value = 2.
![изображение](https://user-images.githubusercontent.com/51052515/59342564-b826f780-8d12-11e9-8ea4-35df5fda2bbe.png)

**Comment by chenshaoju** [comment]
my pleasure.
