### ISSUE TITLE
明显标注密码首尾的空白字符

### ISSUE THREAD

**Issue by snakeysky** [shadowsocks/shadowsocks-windows#2406]
大家的报错基本都是
“System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。”
类似这样的，然后无论是远程还是本地端口测试也好，ip测试也好都是通的。我今天在一台新的电脑上部署客户端也发生了这个问题，然后我就在这里爬文，作者提供的各种方法都试了一次。最后都无效，最后的最后发现，问题出在密码上，由于密码都是复杂化的，每次都是偷懒复制黏贴进去，虽然开着显示密码确认，但其中有一个非常容易被忽视的，那就是空格。我发现空格是可以保存的。。。去掉空格后，一切正常了。。
所以希望作者是否可以在密码输入框对空格进行校验，免得再有相同的粗心人中招。

**Comment by hxy91819** [comment]
现在基本都是通过链接导入或者是通过二维码扫描导入的

**Comment by 211lc** [comment]
大写的卧槽，弄了半天，我还在琢磨要不要重装系统呢

**Comment by celeron533** [comment]
1. 所以后来加了显示密码的功能
2. 密码不限制字符，包括前导空格和末尾空格

**Comment by studentmain** [comment]
换成等宽字体了，先用着看看
