### ISSUE TITLE
请增加IPv6 本地监听地址的可选配置

### ISSUE THREAD

**Issue by Yifei0727** [shadowsocks/shadowsocks-windows#2407]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
`4.1.6`

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
`1809 17763.437  64bit`

### Steps you have tried / 操作步骤
请增加本地配置 
 `localHost`  让我能指定地址 例如 `[::1]`

### What did you expect to see? / 期望的结果
```shell
C:\Users\XXX>netstat -nao|find "1080"
  TCP    [::1]:1080         0.0.0.0:0              LISTENING       1868
  UDP    [::1]:1080         *:*                                    1868
C:\Users\Rui>telnet [::1] 1080
连接成功

```

### What did you see instead? / 实际结果
```shell
C:\Users\XXX>netstat -nao|find "1080"
  TCP    127.0.0.1:1080         0.0.0.0:0              LISTENING       1868
  UDP    127.0.0.1:1080         *:*                                    1868
```
```shell
C:\Users\XXX>telnet [::1] 1080
正在连接[::1]...无法打开到主机的连接。 在端口 1080: 连接失败
```

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by Yifei0727** [comment]
如果可以，后续在UI 界面增加一个 复选框用于影响配置 是否启用IPv6
1. 未勾选  默认，仅使用IPv4
2. 半勾选  仅使用IPv6
3. 全勾选  采用双栈（IPv4&IPv6)  【未实现】

**Comment by celeron533** [comment]
Mark IPv6 as experimental function. Currently, only allow "advanced" users to modify the config file directly.
