### ISSUE TITLE
配置正确，但是翻墙有时能行，有时不行

### ISSUE THREAD

**Issue by Stephen2252** [shadowsocks/shadowsocks-windows#2408]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本

最新版4.1.6
### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

符合要求
### Steps you have tried / 操作步骤
配置影梭账号，账号IP也没有被墙

### What did you expect to see? / 期望的结果
打开影梭之后立刻能翻墙

### What did you see instead? / 实际结果
将影梭关掉之后再打开有时就可以立刻翻墙，有时却不可以，有时要等好大一会儿才可以翻墙

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![image](https://user-images.githubusercontent.com/40737041/59510931-9468da80-8ee7-11e9-942b-32a8ac05b22b.png)
![微信截图_20190614205650](https://user-images.githubusercontent.com/40737041/59510938-9b8fe880-8ee7-11e9-9062-97cbb559feae.png)
![微信截图_20190614205709](https://user-images.githubusercontent.com/40737041/59510943-9df24280-8ee7-11e9-9973-775847a76f84.png)

**Comment by chenshaoju** [comment]
可能是间歇性干扰，如果你的服务器是自己搭的，请尝试套一个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by caozhiyue** [comment]
@chenshaoju 我的ip被墙了，现在是不是需要重新搭建一下了？大佬

**Comment by chenshaoju** [comment]
你可以使用 https://ipcheck.need.sh/ 进行测试，如果国内两个叉，那么说明完蛋了，请联系你的VPS服务商更换IP。

**Comment by caozhiyue** [comment]
@chenshaoju 有更换ip的教程吗？大佬

**Comment by chenshaoju** [comment]
请与你的服务商联系……

**Comment by caozhiyue** [comment]
@chenshaoju 我弄的是搬瓦工，有更换ip的教程么？大佬

**Comment by chenshaoju** [comment]
我没有使用BWG……

**Comment by zhanhb** [comment]
> 你可以使用 https://ipcheck.need.sh/ 进行测试，如果国内两个叉，那么说明完蛋了，请联系你的VPS服务商更换IP。

国内两个叉就说明不能搭桥么？我的两个叉，可以用哎。

**Comment by chenshaoju** [comment]
这是一个第三方的服务，无法保证其准确性，如果能用，那么就没问题。如果不能用，其结果可以作为参考。

**Comment by zhanhb** [comment]
不觉得这个结果可以作为参考

**Comment by Stephen2252** [comment]
·
![image](https://user-images.githubusercontent.com/40737041/59586127-be531480-9114-11e9-96d6-b0f07547ff0e.png)
如图，第一个服务器是经常使用的，但是自从6月中旬重新使用之后就时行时不行，用后面两个账号试了，能正常翻墙。第一个手机能够翻墙，链接电脑wifi也能够翻墙。但是电脑本身却经常不能翻墙。求解答

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，请尝试套一个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by Stephen2252** [comment]
是别人搭建的~~

**Comment by chenshaoju** [comment]
请与搭建服务的人联系，看他是否愿意加个插件。

**Comment by Stephen2252** [comment]
也就是这种时灵时不灵的情况只有通过套插件才可以解决了吗

**Comment by chenshaoju** [comment]
两种可能，要么你的网络不稳定，要么是间歇性封锁。

**Comment by Stephen2252** [comment]
请问这两种的应对之策分别都是啥？

**Comment by chenshaoju** [comment]
如果是前者，请先确定是国内线路问题还是国际线路问题。
如果是国内线路问题（不太可能），只能向运营商反应或者换宽带。
如果是国际线路问题，请尝试访问你的VPS服务商的网站，通常会有一个测速服务，提供该VPS服务商的所有测试节点，测试一下，选一个稳定的然后迁移过去。

如果是后者，请尝试套一个插件看看。

**Comment by Stephen2252** [comment]
还有个问题，就是当chrome和ie长时间失灵时，过段时间打开IE,取消选中网络设置里的自动配置脚本就能翻墙了，请问和这个有关系吗，具体是什么原因

**Comment by Stephen2252** [comment]
配置Simple-obfs插件时，你帮我看下我理解的对不对呗：
1 首先下载压缩包，解压到shadowsocks同目录下面
2 修改config.json文件，即在最后面加上：{
    "server":"0.0.0.0",
    "server_port":443,
    "local_port":10800,
    "password":"pBpAXnvH2JhT",
    "timeout":20,
    "method":"aes-256-gcm",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls;failover=104.193.88.77:443"
}
3 客户端插件程序处输入：obfs-local
插件选项处输入：obfs=tls;obfs-host=www.baidu.com

**Comment by chenshaoju** [comment]
这可能和你的代理和网络没关系，有可能是你的计算机上有什么东西接管了代理设置。

如果可能，请使用Firefox（如果有），手动指定代理看看，当出现问题的时候，指定代理的Firefox是否能工作？
![image](https://user-images.githubusercontent.com/515763/59654381-84dbe100-91c8-11e9-9a6d-740ed33e8902.png)

如果Firefox也不工作，SS的日志里显示什么？

**Comment by Stephen2252** [comment]
![QQ截图20190618192234](https://user-images.githubusercontent.com/40737041/59679140-a953af80-9200-11e9-932f-da13d7b79f18.png)
![QQ截图20190618192310](https://user-images.githubusercontent.com/40737041/59679141-a9ec4600-9200-11e9-8fa6-bc527ebf4c33.png)
![QQ截图20190618192329](https://user-images.githubusercontent.com/40737041/59679143-aa84dc80-9200-11e9-81c4-05462fbd5563.png)
![QQ截图20190618192206](https://user-images.githubusercontent.com/40737041/59679144-ab1d7300-9200-11e9-9691-8fe3e7f3ffa9.png)

**Comment by Stephen2252** [comment]
实在抱歉情况更正一下，校园网下，电脑，以及使用校园网热点的手机都无法翻墙。但是使用手机运营商或者手机运营商网络下给电脑开热点就可以正常翻墙。实在抱歉，您看这是因为什么原因

**Comment by chenshaoju** [comment]
很有可能是你的校园网有封锁。

请尝试联系服务器的管理人员切换到443端口看看，是否会好转。

**Comment by Stephen2252** [comment]
是服务器端口还是代理端口

**Comment by chenshaoju** [comment]
服务器端口。

**Comment by Stephen2252** [comment]
我会尝试一下的。刚才校园网下，在别人的机子上试了一下不能翻墙。但是回头来看发现我的电脑又可以翻墙了。。。真诡异

**Comment by Stephen2252** [comment]
还是不行，包括尝试了
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
![捕获](https://user-images.githubusercontent.com/40737041/59743863-d73e0000-92a3-11e9-9786-e5bfe664b91d.PNG)

**Comment by chenshaoju** [comment]
因为是间歇性的干扰，所以会出现这种奇怪的现象。。。高度看脸。

这不是你计算机的问题，所以重设tcpip和winsock没用。。。

**Comment by jasonliul** [comment]
by bluesky
https://pincong.rocks/article/2019

建议一定要使用AEAD加密算法，如GCM系列，AES-128-GCM,AES-192-GCM,AES-256-GCM和POLY1305系列　CHACHA20-IETF-POLY1305,XCHACHA20-IETF-POLY1305

也有其他用戶贊成這個提法

**Comment by Stephen2252** [comment]
> by bluesky
> https://pincong.rocks/article/2019
> 
> 建议一定要使用AEAD加密算法，如GCM系列，AES-128-GCM,AES-192-GCM,AES-256-GCM和POLY1305系列　CHACHA20-IETF-POLY1305,XCHACHA20-IETF-POLY1305
> 
> 也有其他用戶贊成這個提法

改一下加密方式就可以了？

**Comment by caozhiyue** [comment]
@chenshaoju 我买了新的ip后，kiwivm界面的kiwivm extras里就没有shadowsocks了，我该怎么办？

**Comment by zhanhb** [comment]
> @chenshaoju 我买了新的ip后，kiwivm界面的kiwivm extras里就没有shadowsocks了，我该怎么办？

You should visit [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev) or [shadowsocks-python](https://github.com/shadowsocks/shadowsocks/tree/master)

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
