### ISSUE TITLE
4.1.6

### ISSUE THREAD

**Issue by w261356723** [shadowsocks/shadowsocks-windows#2409]
![222](https://user-images.githubusercontent.com/25584753/59528686-84fe8700-8f11-11e9-8572-5813f8b74010.PNG)
[shadowsocks.log](https://github.com/shadowsocks/shadowsocks-windows/files/3291704/shadowsocks.log)
 我找了一圈没看到启动系统代理 的地方  ！！！！他在哪? 如果没有为何我上不了youtube？？？？？？？？？

**Comment by w261356723** [comment]
我的4.0.6版本就没问题！！就是4.1.6 根本就找不到开关！ 这是我4.0.6 的日志和截图
![33](https://user-images.githubusercontent.com/25584753/59529130-b6c41d80-8f12-11e9-83eb-f809db839d98.PNG)
[shadowsocks.log](https://github.com/shadowsocks/shadowsocks-windows/files/3291741/shadowsocks.log)

**Comment by AnyWAT** [comment]
右键图标——（最上）系统代理：
1、禁用
2、PAC 模式
3、全局模式

**Comment by w261356723** [comment]
> 右键图标 - （顶部）系统代理（从上到下，依次）：
> 禁用
> PAC模式
> 全局模式

没用 不管我是禁用也好全局也好还是pac 试过了！都无法 连接 谷歌打不开。 。同一个节点4.06 就没问题!

**Comment by chenshaoju** [comment]
两个版本是同时测试的吗？

如果是，请尝试删除最新版 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后再启动SS，右击托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。

**Comment by w261356723** [comment]
我把那个安装包拿出去用到别的硬盘 正常了！谢谢！至于什么问题我也不知道！



------------------ 原始邮件 ------------------
发件人: "Chen Shaoju"<notifications@github.com>; 
发送时间: 2019年6月18日(星期二) 上午9:14
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>; 
抄送: "923427173"<923427173@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shadowsocks/shadowsocks-windows] 4.1.6 (#2409)




两个版本是同时测试的吗？
 
如果是，请尝试删除最新版 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后再启动SS，右击托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。

**Comment by w261356723** [comment]
> 两个版本是同时测试的吗？
> 
> 如果是，请尝试删除最新版Shadowsocks.exe所在目录下的pac.txt文件，然后再启动SS，右击托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。

给你反馈下把！提升我更新我一直更新（他自动下载） 我也不理它 一直用的我的旧版本。最近想用新版本然后解压它自动下载的地方，然后发现任何节点都不能用。而老版本却正常。 所以反馈都你们这了！希望能帮到你们！

**Comment by chenshaoju** [comment]
多老的版本？

如果你的服务器用了OTA，这个功能在后来不支持了。
