### ISSUE TITLE
System.Exception: 端口已被占用(windows 7 64位)

### ISSUE THREAD

**Issue by archbishop** [shadowsocks/shadowsocks-windows#241]
客户端版本2.5.1，其实前几个版本也有这个问题，突然就出现了，查看了端口并没有被占用。

[2015-07-28 08:42:38] System.Exception: 端口已被占用 ---> System.Net.Sockets.SocketException: 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   --- 内部异常堆栈跟踪的结尾 ---

![1](https://cloud.githubusercontent.com/assets/3295903/8921250/c66e45e6-3505-11e5-9ec4-56aad6d8768d.PNG)

求助各位大神，谢谢。

**Comment by maxshine** [comment]
可能是outbound端口用光了，是不是在大并发时候出的？可以查一下修改windows注册表增加端口范围，tcpip/parameters下，修改MaxUserPort和TcpTimedWaitDelay来自我的华为手机-------- 原始邮件 --------主题：[shadowsocks-windows] System.Exception: 端口已被占用(windows 7 64位) (#241)发件人：Alacrity 收件人：shadowsocks/shadowsocks-windows 抄送：客户端版本2.5.1，其实前几个版本也有这个问题，突然就出现了，查看了端口并没有被占用。

[2015-07-28 08:42:38] System.Exception: 端口已被占用 ---> System.Net.Sockets.SocketException: 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   --- 内部异常堆栈跟踪的结尾 ---



求助各位大神，谢谢。

**Comment by archbishop** [comment]
@maxshine 刚开机的时候出现的

**Comment by imebeh** [comment]
同出现过，刚开机的时候好像是 explorer.exe 会用一会 1080 端口然后就释放了，原因不明

**Comment by nicholaslai** [comment]
禁用迅雷的 xlserviceplatform 进程

**Comment by geekyouth** [comment]
360tray.exe占用 1080 这个问题无法根治，每次开机都会恢复，求助
