### ISSUE TITLE
shadowsocks求助无法打开pinterest

### ISSUE THREAD

**Issue by lifang007** [shadowsocks/shadowsocks-windows#2412]
[**求助**]版本：shadowsocks4.0.6，环境Windows7。其他一且正常访问，唯独不能访问[Pinterest](https://www.pinterest.com/)。![](https://i.loli.net/2019/06/17/5d073ab86e4be68424.jpg)

**Comment by Skuyar** [comment]
P站先开全局，就能打开了，之后再切换到PAC就ok了，我之前很多次这样。

**Comment by chenshaoju** [comment]
请尝试更新PAC看看？确保使用的是最新的SS，然后右击托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。

**Comment by lifang007** [comment]
真的可以了！感谢楼上二位！
