### ISSUE TITLE
VULTR 2.5绝版日本机房，IP被封后有什么解救办法吗

### ISSUE THREAD

**Issue by JoySky** [shadowsocks/shadowsocks-windows#2413]
这次敏感时期之后，VPS一直无法使用，想要更换IP，却发现当初的日本节点已经没有2.5美元的选项了。客服无法帮忙改IP，特来问问各位兄弟，这种情况有没有解决办法。如果彻底没有解救办法，我换一家VPS。有好的推荐吗？万分感谢

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的话，请尝试套一个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by navono** [comment]
VULTR 大部分地区的 IP 都被封了。

**Comment by rainbow-cnay** [comment]
花点钱，添加第二个IP，先用着，等主IP解封后再恢复。

**Comment by navono** [comment]
just my socks
