### ISSUE TITLE
日志中，能否加入显示局域网中的客户端ip

### ISSUE THREAD

**Issue by oOtroyOo** [shadowsocks/shadowsocks-windows#2414]
我一般会把局域网中的设备都连入一个总代理，日志中有记录时间和目标地址，并不能知道是局域网中那个ip的正在请求访问，能否加入这个显示选项。

**Comment by chenshaoju** [comment]
目前如果你要做记录，可考虑加一个前置代理，比如在CCProxy中的二级代理里设置为127.0.0.1+SS的端口。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
