### ISSUE TITLE
PC下自动开机启动

### ISSUE THREAD

**Issue by sxyandapp** [shadowsocks/shadowsocks-windows#2415]
### 我不知道shadowsock怎么实现的，居然能在用户不允许的情况下开机启动，虽说这是一个开源软件，不应该被质疑，但在用户未经允许的情况下就开机启动，就像流氓软件和狗皮膏药一样，不免让人厌恶

已经尝试了注册表，计划任务，系统服务，开机启动目录，都没有找到shdowsock的开机启动项

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 不会擅自自动启动，除非在托盘区纸飞机图标右键菜单中选中了“开机启动”。

但是如果你用的是Windows 10，且最后一次关机/重启时没有退出SS，那么第二次开机的时候SS会随系统启动一次，如果下次关机/重启还没有退出，会再次随开机启动。

解决办法很简单，关机/重启前退出SS即可。

**Comment by sxyandapp** [comment]
我测试出了这种结果，我觉得这样设计不好，如果用户需要开机启动的话，他自己会勾选开机启动，否则用户肯定不希望下次开机后程序会自动启动。
还有shadowsock的开机启动是如何实现的？注册表？计划任务？或者其他的？

**Comment by Stzx** [comment]
shadowsock 的开机启动是通过注册表实现的。

具体的路径如下 `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`，你会看到一个以 `Shadowsocks` 开头的值。

😀

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/pull/2166

**Comment by bayllech** [comment]
我就不一样了，我勾选了开机启动，可是每次开机还要手动启动，并未生效

**Comment by Stzx** [comment]
考虑提供通过注册成服务启动？

**Comment by chenshaoju** [comment]
@bayllech 可能你的安全软件拦截了SS的开机注册表添加过程。

@Stzx 这个更复杂了。

**Comment by sxyandapp** [comment]
> shadowsock 的开机启动是通过注册表实现的。
> 
> 具体的路径如下 `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`，你会看到一个以 `Shadowsocks` 开头的值。
> 
> 😀

经过测试，发现注册表这个位置只是在勾选开机启动的时候会添加记录，程序自身的`维持上次的启动状态`功能如何实现的还未知

**Comment by Stzx** [comment]
> > shadowsock 的开机启动是通过注册表实现的。
> > 具体的路径如下 `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`，你会看到一个以 `Shadowsocks` 开头的值。
> > 😀
> 
> 经过测试，发现注册表这个位置只是在勾选开机启动的时候会添加记录，程序自身的`维持上次的启动状态`功能如何实现的还未知

`维持上次的启动状态` 就是 #2166 中通过 `RegisterApplicationRestart` 函数注册实现的。

**Comment by sxyandapp** [comment]
> > > shadowsock 的开机启动是通过注册表实现的。
> > > 具体的路径如下 `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`，你会看到一个以 `Shadowsocks` 开头的值。
> > > 😀
> > 
> > 
> > 经过测试，发现注册表这个位置只是在勾选开机启动的时候会添加记录，程序自身的`维持上次的启动状态`功能如何实现的还未知
> 
> `维持上次的启动状态` 就是 #2166 中通过 `RegisterApplicationRestart` 函数注册实现的。

调用了RegisterApplicationRestart这个WINAPI实现的，这就意味着没法关闭这个功能

**Comment by bayllech** [comment]
> @bayllech 可能你的安全软件拦截了SS的开机注册表添加过程。
> 
> @Stzx 这个更复杂了。

看了我的注册表，有注册此项，任务管理器开机启动也能看到，没有使用安全软件
![image](https://user-images.githubusercontent.com/22362346/59734159-e5c7ef80-9282-11e9-8a72-8cab671ac05a.png)

**Comment by chenshaoju** [comment]
请尝试放到硬腭新的目录看看，比如 D:\SS\ ？

**Comment by bayllech** [comment]
好了，全部删除，重新放到新建的目录下，正常工作了（公司电脑，只有C盘）
