### ISSUE TITLE
SS-windows 能否添加订阅功能？以及所有节点连通测试功能？

### ISSUE THREAD

**Issue by PS0123456** [shadowsocks/shadowsocks-windows#2417]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
The latest 4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

windows
### Steps you have tried / 操作步骤

None
### What did you expect to see? / 期望的结果

能否添加节点订阅功能，还是已经实现了？节点连通测试功能？
### What did you see instead? / 实际结果
添加节点订阅功能 And 节点连通测试功能!

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
None

**Comment by lonelam** [comment]
#1703 #1819 #2147 #2265 #2268 #2277 
------------------
仍希望添加，这个功能已经变成了我不得不用ssr的原因了，但是ssr好像已经没有官方开源实现了。另外，这个项目接受PR吗？

**Comment by shikkoku** [comment]
https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html
明明有标准支持订阅的。不知道官方为什么不推广。

**Comment by chenshaoju** [comment]
这不是订阅，这只是将SS的代理配置信息封装到URL里。

如果你是指这种URL，这个是可以导入的，你只需要在获得URL后复制，然后右击任务栏的SS图标，选择服务器，再点击从剪切板导入URL即可导入。

**Comment by shikkoku** [comment]
> 这不是订阅，这只是将SS的代理配置信息封装到URL里。
> 
> 如果你是指这种URL，这个是可以导入的，你只需要在获得URL后复制，然后右击任务栏的SS图标，选择服务器，再点击从剪切板导入URL即可导入。

不是这样的，是一个链接（下载回来是多个用base64加密过的sip002节点链接）

**Comment by chenshaoju** [comment]
的确不是，就是从页面上复制URL，然后粘贴到本地。

包括二维码，其实也是这个URL，你可以使用任何二维码进行测试。

**Comment by studentmain** [comment]
进一步讨论见#1703

**Comment by faydanube** [comment]
1. 直接使用 SSR 订阅进行更新
2. 然后复制 SSR 的 `gui-config.json` 覆盖到 SS
3. 在 SS 直接支持订阅功能之前，使用此方法可以完美解决。
