### ISSUE TITLE
v4.1.6 间隔性断开连接

### ISSUE THREAD

**Issue by Holmeyoung** [shadowsocks/shadowsocks-windows#2418]
### Shadowsocks version / 影梭版本
v4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
- Windows 7
- .NET Framework 4.0

### Steps you have tried / 操作步骤
shadowsocks `pac` 自动代理模式

### What did you expect to see? / 期望的结果
保持连接

### What did you see instead? / 实际结果
有时无法连接服务器

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
被我换回 `v4.1.5` 的时候，强迫症，源文件都删了...

### 格式外
问题是这样的，在我使用 `v4.1.5` 的时候，连接几乎是不断的。但是自从升级到 `v4.1.6` 有时候突然就不能访问 Google 了，然后我去检查服务器，或者通过手机端连接发现服务器是可用的。

**Comment by chenshaoju** [comment]
在升级后有无删除 pac.txt 文件，然后重新从GFWList下更新？

另外，手机和有问题的计算机使用的是同一个网络吗？（都位于同一个局域网吗？）

**Comment by oodzchen** [comment]
> 在升级后有无删除 pac.txt 文件，然后重新从GFWList下更新？
> 
> 另外，手机和有问题的计算机使用的是同一个网络吗？（都位于同一个局域网吗？）

你好，我也是升级4.1.6之后间歇性的断开连接，没删过pac.txt，没有更新GFWList。在同一个局域网下，同样的服务器配置，Windows客户端断开连接的时候Mac客户端却能正常连接。

**Comment by chenshaoju** [comment]
日志中有任何提示吗？

**Comment by oodzchen** [comment]
> 日志中有任何提示吗？

有提示，一直重复如下信息

> [2019-06-22 14:58:17] connect to www.google.com:443
[2019-06-22 14:58:17] System.Net.Sockets.SocketException (0x80004005): 这是在主机名解析时通常出现的暂时错误，它意味着本地服务器没有从权威服务器上收到响应。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by oodzchen** [comment]
禁用了一会儿，重新选pac模式又能连接了，大概两三分钟的样子

**Comment by chenshaoju** [comment]
`它意味着本地服务器没有从权威服务器上收到响应` 你所在的网络的DNS服务器有问题。

如果可能，请尝试Ping你的服务器的域名，获取IP后，直接将IP填写到配置里替换原有的域名，然后再观察看看？

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
