### ISSUE TITLE
windows客户端更新不能直接到最新版本

### ISSUE THREAD

**Issue by TanekLiang** [shadowsocks/shadowsocks-windows#242]
我的客户端更新之前是2.3。
今天提示我更新，点击之后下载的是2.4的，
运行2.4又提示更新，再次更新到2.5

希望可以一次更新到最新版本

**Comment by clowwindy** [comment]
原先检查更新用的是 sourceforge，最后上传的版本是 2.4，但是它挂了，无法上传。现在用的是 GitHub，所以从 2.3 升级会出现这种情况。
