### ISSUE TITLE
局域网上网使用方法

### ISSUE THREAD

**Issue by wzzjhc** [shadowsocks/shadowsocks-windows#2420]
### Shadowsocks version / 影梭版本

-----------> 4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

-----------> windows server 2012R

 
### What did you expect to see? / 期望的结果

 -----------> 希望增加新的功能，帮助局域网内的其他电脑上网。
我们局域网10个电脑就一个电脑有网线可以上网，我想帮助其他电脑上网。
所以我将其他9台电脑使用SS进行指向IP,跟1080端口，但是我的可以上网的电脑应该怎么设置，我不会。

**Comment by chenshaoju** [comment]
理论上可以，但是过于复杂，我建议你直接考虑CCProxy或者SyGate之类的软件。

**Comment by uscwifi** [comment]
应该是可以的吧，不过我只用过squid代理过，也挺简单的

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
