### ISSUE TITLE
How to add certain software to exclusion, such that they are not affected by Shadowsocks?

### ISSUE THREAD

**Issue by mikecjy** [shadowsocks/shadowsocks-windows#2421]
### Shadowsocks version / 影梭版本
4.9.2

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win 10

### What did you expect to see? / 期望的结果
For example, I'm using Whatsapp desktop and I don't want it to be affected by Shadowsocks, how should I do the setup? I'm still new to Shadowsocks so any help will be appreciated. Thanks and have a nice day.

**Comment by chenshaoju** [comment]
Current is no way an exception specific applications.
You may disable system proxy in shadowsocks menu when using those applications you don't want use proxy.

Or you can use a virtual machine.

**Comment by chenshaoju** [comment]
Since there has been no reply for a long time, this Issue has been closed.
