### ISSUE TITLE
如何配置按statistics切换服务器？

### ISSUE THREAD

**Issue by zjplab** [shadowsocks/shadowsocks-windows#2422]
我的设置如下:
![image](https://user-images.githubusercontent.com/16349466/59932330-85e76980-9479-11e9-94b4-852d7de059b7.png)
但是log里总是提示`no enough statistics data or all factors in calculations are 0`

**Comment by chenshaoju** [comment]
这个功能有问题，而且会引发随机崩溃，不建议使用。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
