### ISSUE TITLE
shadowsocks 的server在启动时遇到问题了

### ISSUE THREAD

**Issue by liuzigenius** [shadowsocks/shadowsocks-windows#2423]
shadowsocks 的server在启动时遇到问题了。

yum install python-setuptools && easy_install pip
pip install shadowsocks
安装正常

ssserver -p 443 -k password -m aes-256-cfb
启动时：

[root@vultr home]# ssserver -p 443 -k password -m aes-256-cfb
2019-06-22 04:40:38 INFO     loading libcrypto from libcrypto.so.10
2019-06-22 04:40:38 INFO     starting server at 0.0.0.0:443

一直卡在这里。。。求解啊，貌似也没有日志

操作系统：
[root@vultr ~]# cat /proc/version
Linux version 3.10.0-957.12.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Tue May 14 21:24:32 UTC 2019
[root@vultr ~]# cat /etc/issue
\S
Kernel \r on an \m

**Comment by chenshaoju** [comment]
客户端访问的时候提示什么？

**Comment by liuzigenius** [comment]
我刚刚搞了下，原来这样算是启动成功的。客户端连不上是因为防火墙，把firewalld停掉就好了

**Comment by chenshaoju** [comment]
:100:
