### ISSUE TITLE
SS的pac为什么不能生效？无法分流啊

### ISSUE THREAD

**Issue by fevv** [shadowsocks/shadowsocks-windows#2424]
SS的pac为什么不能生效？无法分流啊

**Comment by chenshaoju** [comment]
请尝试启动SS后，在位于任务栏托盘区的纸飞机图标上右击，选择系统代理，确定选中PAC莫时候，再次右击纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
