### ISSUE TITLE
Windows 10 1903上SS开机启动两次

### ISSUE THREAD

**Issue by ipcjs** [shadowsocks/shadowsocks-windows#2425]
### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1903

### Steps you have tried / 操作步骤
1. 打开SS
1. 取消勾选SS本身的“开机启动”选项
1. 将`Shadowsocks.exe`的快捷方式放到`C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`中
1. 重启计算机

### What did you expect to see? / 期望的结果
SS只启动一次

### What did you see instead? / 实际结果
SS启动了两次，显示了“Shadowsocks 已经在运行。”的弹窗

### Other/其他
怀疑是Windows的这个功能引起的：[win10 启动后会自动恢复上次关机前的应用](https://www.v2ex.com/t/425101)

**Comment by chenshaoju** [comment]
你好，Shadowsocks for Windows的自启动本身就会写入注册表，所以没有必要放入开始菜单中的启动文件夹中。

**Comment by celeron533** [comment]
Shadowsocks 内部有两种方式实现开机自动启动
1. 标准的开机自动运行，写入了注册表
2. 如果上次关机的时候没有退出，系统重新启动后会重新运行（系统api调用）

如果在一次系统启动时以上两者同时有效，会自动忽略掉其中一个。
但是你手动把快捷方式放在“启动”里，无异于重新双击运行了一次
