### ISSUE TITLE
能否提供切断连接功能

### ISSUE THREAD

**Issue by iKirby** [shadowsocks/shadowsocks-windows#243]
发现用一段时间后可能会速度变得很慢甚至连不上。
用第三方改版那个可以查看连接数，发现连接数高了就会出现问题，用那个改版，双击连接数统计可以断开，断开后再刷新页面速度就恢复正常了。
但是那个版本感觉有bug，不好用，所以希望能加一个切断连接的功能，或者在发生错误较多时候自动重连。

**Comment by clowwindy** [comment]
随便改一下配置就会切断连接了。

**Comment by chenshaoju** [comment]
试着使用高可用性模式。

**Comment by iKirby** [comment]
好吧那我就手动切配置，谢了。
高可用性的话感觉不太好，我加了几个服务器各地的都有，用高可用的话IP经常变...
