### ISSUE TITLE
目前只要打开ss就出错

### ISSUE THREAD

**Issue by invinciblehong** [shadowsocks/shadowsocks-windows#2430]
- Shadowsocks is an open source project for noneprofit. If you bought the service from a provider, please contact them. / 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们
- If you have questions rather than Shadowsocks Windows client, please go to / 如果你有非影梭Windows客户端相关的问题，请去 https://github.com/shadowsocks
- Please read Wiki carefully, especially / 提问前请先阅读wiki https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
- Or search from Issue Board / 或在Issue Board中搜索 https://github.com/shadowsocks/shadowsocks-windows/issues?utf8=%E2%9C%93&q=is%3Aissue
- Please answer the following questions before submission. Questions lack of details will be closed. / 请按照以下格式描述你的问题，描述不清的问题将会被关闭

### Shadowsocks version / 影梭版本
4.1.6 4.1.5 4.1.4   等等等

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 

### Steps you have tried / 操作步骤
在当前环境下只要打开 Shadowsocks.exe ，或者进行任何的操作，都会提示：处理代理设置时发生错误，是否重置当前代理设置并重置？

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

日志文件很简单，就一句：
[2019-06-26 15:10:25] [E] sysproxy - SysproxyExitError:Error query options: 87 参数错误。

**Comment by chenshaoju** [comment]
这意味着设置系统代理的时候遇到了问题，请先检查该服务是否启动了：
![image](https://user-images.githubusercontent.com/515763/60160892-ef27fd80-9828-11e9-8f9d-50484e1898d1.png)

**Comment by invinciblehong** [comment]
> 这意味着设置系统代理的时候遇到了问题，请先检查该服务是否启动了：
> ![image](https://user-images.githubusercontent.com/515763/60160892-ef27fd80-9828-11e9-8f9d-50484e1898d1.png)
显示正在运行，但是是灰色，没有可以操作的地方。注册表也看了 start=3

**Comment by chenshaoju** [comment]
请确保没有安全软件拦截的情况下退出SS，删除注册表的`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\` 项中的`AutoConfigURL` 、`ProxyEnable`键值，重启计算机后再试一次。

**Comment by hrpc** [comment]
我重启Shadowsocks就ok了     版本是4.1.6，重启之后系统代理是禁用状态，改一下就行了

**Comment by invinciblehong** [comment]
目前已恢复正常 操作是在internet设置-连接-局域网设置中将自动检测设置打上勾。如果有出现类似问题的朋友可以参考一下
