### ISSUE TITLE
Run TestUnit failed

### ISSUE THREAD

**Issue by yyk123** [shadowsocks/shadowsocks-windows#2431]
Utils.cs 
line 32: GetTempPath()
when Run Test, the StartupPath is not current Directory.
Suggest change "Application.StartupPath" to  "./"

**Comment by celeron533** [comment]
Appveyor looks no problem
https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/25585654

PS. sometimes appveyor cannot complete a build. Restart or kickoff a new build could solve it.

**Comment by yyk123** [comment]
> Appveyor looks no problem
> https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/25585654
> 
> PS. sometimes appveyor cannot complete a build. Restart or kickoff a new build could solve it.

I run test using vs2017, not appveyor. It seems when run the test in VS, Application.StartupPath is not  correct.

**Comment by celeron533** [comment]
Please try run vs2017 as Admin and then run tests.

**Comment by yyk123** [comment]
> Please try run vs2017 as Admin and then run tests.

It's a solution, but the directory "ss_win_temp" will be generated under  ***\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\TestPlatform\
If I use "./" rather then "Application.StartupPath", ss_win_temp  is  under \shadowsocks-windows\test\bin\x86\Release\
And  it works fine when I open log file by using menu button on logviewer.
So, I don't understand the meaning of this sentence " don't use "/", it will fail when we call explorer /select xxx/ss_win_temp\xxx.log"

**Comment by celeron533** [comment]
>So, I don't understand the meaning of this sentence " don't use "/"

`explorer.exe /select, "C:\Windows\regedit.exe"` it works.
`explorer.exe /select, "C:/Windows/regedit.exe"` it does not work.

**Comment by celeron533** [comment]
And update the code to
```
_tempPath = Directory.CreateDirectory("ss_win_temp").FullName;
```

will solve the problem.

Thank you @yyk123 for pointing it out.
