### ISSUE TITLE
Very High CPU Usage when Using AES-256-GCM / Poly1305

### ISSUE THREAD

**Issue by EletronicElephant** [shadowsocks/shadowsocks-windows#2436]
### Shadowsocks version / 影梭版本 
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Tested on Win 10 1903 / 1809 

![Annotation 2019-07-01 185933](https://user-images.githubusercontent.com/20351686/60431458-719e2c00-9c32-11e9-8cec-b92f2ad8b830.png)

CPU: i7-8750H
Method: AES-256-GCM / CC20-Poly1305. Other methods not tested because of security reason.
NOTHING Interesting in LOG.
The screen capture is shown above. I don't think ESET or FDM is anything related. It just occupies a lot CPU when large bandwith.

**Comment by chenshaoju** [comment]
Please use Process Explorer ( https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer), Select Shadowsocks.exe , Goto Threads tab, What is using most CPU?

Example:
![image](https://user-images.githubusercontent.com/515763/60432195-3c92d900-9c34-11e9-9470-3a0fc140a55f.png)

**Comment by EletronicElephant** [comment]
> Please use Process Explorer ( https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer), Select Shadowsocks.exe , Goto Threads tab, What is using most CPU?
> 
> Example:
> ![image](https://user-images.githubusercontent.com/515763/60432195-3c92d900-9c34-11e9-9470-3a0fc140a55f.png)

Here you are. Thank you very much!
![Annotation 2019-07-01 192108](https://user-images.githubusercontent.com/20351686/60432694-7ca68b80-9c35-11e9-9476-8475eb435211.png)

**Comment by chenshaoju** [comment]
Everything looks fine, This screenshot is taken when Shadowsocks.exe is high CPU load?

Or did you have a lot of request from your computer?

**Comment by EletronicElephant** [comment]
> Everything looks fine, This screenshot is taken when Shadowsocks.exe is high CPU load?
> 
> Or did you have a lot of request from your computer? You can go to TCP/IP tab check all TCP connection.

Yep. When this screenshot taken, SS was consuming 25% CPU reported by Taskmgr, while the network activity was only about 150Mbps. The number of TCP requests was around 30.

I don't think it's normal for SS to consume 25% of 8750H in order to handle only 150 Mbps network bandwith based on 30 TCP connections.

**Comment by chenshaoju** [comment]
I think 150Mbps is pretty high...🤔

**Comment by chenshaoju** [comment]
Since there has been no reply for a long time, this Issue has been closed.
