### ISSUE TITLE
正向代理没有按照预期工作

### ISSUE THREAD

**Issue by abc45628** [shadowsocks/shadowsocks-windows#2437]
### Shadowsocks version / 影梭版本
4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 1903

### What did you expect to see? / 期望的结果
我在内网环境需要先通过代理才能访问外网，10网段直接访问内网，普通网站通过代理，Google通过代理访问SS服务器。
我在PAC.txt设定了以下代码
``` javascript
var proxy = "__PROXY__";
var direct = 'DIRECT;';
function FindProxyForURL(url, host) {
    if (isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0"))
        return direct;
    if (userrulesMatcher.matchesAny(url, host) instanceof BlockingFilter) {
        return proxy;
    }
    if (userrulesMatcher.matchesAny(url, host) instanceof WhitelistFilter) {
        return direct;
    }
    if (defaultMatcher.matchesAny(url, host) instanceof BlockingFilter) {
        return proxy;
    }
    return "PROXY 10.1.249.61:3128";
}
```
设置了正向代理
![ss_forward](https://user-images.githubusercontent.com/9178345/60479940-4101d500-9cba-11e9-9bed-e08d406fb2e2.png)

当我用QQ进行测试时发现，QQ执行的是GOOGLE 的访问方式，而不是普通国内网站的访问方式，请问如果我要QQ只通过代理应该怎么设置
![ss_test](https://user-images.githubusercontent.com/9178345/60480069-c1283a80-9cba-11e9-8ab0-ce29bf081997.png)

![ss](https://user-images.githubusercontent.com/9178345/60479696-4dd1f900-9cb9-11e9-9f00-a4199c7deb2d.png)

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 的代理端口提供的是同等于全局代理的设置，如果你希望QQ能使用，请直接在QQ里指定你的内网代理即可，没有必要指向SS的代理端口。

SS使用的是PAC系统代理，而PAC是系统代理，即由系统按照PAC列表决定你所访问的代理是否经过SS，而不是由SS决定。

**Comment by abc45628** [comment]
> Shadowsocks for Windows 的代理端口提供的是同等于全局代理的设置，如果你希望QQ能使用，请直接在QQ里指定你的内网代理即可，没有必要指向SS的代理端口。
> 
> SS使用的是PAC系统代理，而PAC是系统代理，即由系统按照PAC列表决定你所访问的代理是否经过SS，而不是由SS决定。

意思是如果我直接指定SS的代理端口，就不会经过PAC来决定是否代理，而是必然会代理这次链接？

**Comment by chenshaoju** [comment]
是

**Comment by celeron533** [comment]
10.0.0.0/8 --> intranet
QQ --> 10.1.249.61 --> internet
google chrome --> ss --> 10.1.249.61 --> real internet

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
