### ISSUE TITLE
请提供 zip 文件的 hash

### ISSUE THREAD

**Issue by linsui** [shadowsocks/shadowsocks-windows#2438]
请问是否可以提供 zip 文件的 hash？提供 release 文件的 hash 是比较通用的做法。目前的方式对于下游，比如 scoop 来说难以进行校验，目前 scoop 只有校验直接下载文件的能力。谢谢

**Comment by linsui** [comment]
或者是否可以将 exe 文件直接发布？毕竟体积很小，压缩与否影响并不大

**Comment by chenshaoju** [comment]
这里有一个潜在问题：
Windows系统（浏览器），对于下载回来的文件有一个特殊的标识符，这个标识符可能会影响到某些注册表键值的访问：
![image](https://user-images.githubusercontent.com/515763/62213435-7989f100-b3d5-11e9-8bcb-982d0df90135.png)

如果是直接下回来的 .exe ，必定存在该标识符；但是如果下回来的zip，解压后的 .exe ，则不会带有此标识符。

**Comment by linsui** [comment]
这真是意想不到 😂 4.1.7 提供了 zip 的 hash，但 4.1.7.1 没有提供，请问是出现了什么问题吗？
