### ISSUE TITLE
手机流量可用，校园网不能用。检测ss服务器端口ok

### ISSUE THREAD

**Issue by wtjiang98** [shadowsocks/shadowsocks-windows#2439]
### Shadowsocks version / 影梭版本
Shadowsocks-4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
WIN10、北京某工信部直属高校校园网
ss服务器是微软Azure

### Steps you have tried / 操作步骤
如某issue下所示：

> 1. 使用第三方的工具测试一下你的服务器是否能从国内联上： https://ipcheck.need.sh/ 

不可以。不过后来了解到Azure的服务器没有开很多端口

> 2. 使用这个第三方的工具测试从你的校园网到你的SS服务器的端口是否能通： https://github.com/chenshaoju/tcpportcheck 。  

**可以通！而且在另一台Ubuntu机器上使用nc -zv 命令也可以通** 说明了学校没有墙这个端口？？

总结：使用校园网无法翻墙（偶尔间隙可以，大部分时间不行）；使用手机流量则完全无问题，非常快

### What did you expect to see? / 期望的结果

在校园网上翻墙

### What did you see instead? / 实际结果

即使测试似乎显示没有墙端口，但是只要是校园网则完全翻不了

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
这意味着你的学校可能有协议过滤，建议更换端口到443看看。

如果可能，请尝试套一个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836 （走TLS协议请尽量使用443，走HTTP/WebSocket建议使用80）。

**Comment by taogelose** [comment]
> 这意味着你的学校可能有协议过滤，建议更换端口到443看看。
> 
> 如果可能，请尝试套一个插件看看：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836) （走TLS协议请尽量使用443，走HTTP/WebSocket建议使用80）。

好的，非常感谢您

**Comment by P-DX** [comment]
BH？
请问换了端口解决了吗？

**Comment by wtjiang98** [comment]
> BH？
> 请问换了端口解决了吗？

好像还没解决
