### ISSUE TITLE
2.5.1似乎有内存泄漏的问题？

### ISSUE THREAD

**Issue by flintt** [shadowsocks/shadowsocks-windows#244]
![image](https://cloud.githubusercontent.com/assets/3394691/8950177/5abe4f80-35f0-11e5-9a93-ee299bae675e.png)
据观察估计是和服务器端口不可达（端口在网络出口被封锁）导致的

浏览器不使用socks代理后，内存一直稳定

**Comment by uinux** [comment]
这是什么工具，不是系统自带的任务管理器吧？

**Comment by chenshaoju** [comment]
@uinux https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx

@flintt 我暂时没观察到这个问题：
![screenshot](https://cloud.githubusercontent.com/assets/515763/8953338/38571a74-3610-11e5-8fd6-30c541d62e81.png)

**Comment by flintt** [comment]
​不是，https://technet.microsoft.com/en-us/sysinternals里面的process explorer
----------------
flintthuang@ymail.com

**Comment by uinux** [comment]
![Uploading 捕获.PNG…]()
感觉这个只会增多不会减少的样子。

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8954409/fb6cf5d6-3617-11e5-8be7-3e96d09d8426.PNG)
图坏了。....

**Comment by flintt** [comment]
@chenshaoju 有在上联口将目标端口丢包处理？
@uinux 是波动的，但我前天内存消耗达到了500多兆

**Comment by uinux** [comment]
![Uploading 捕获.PNG…]()
我被弄到了100M，求解释原因。.....2.5版本的..

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8973815/55b0fe3c-369c-11e5-9268-76d7bafb71ed.PNG)
唉，图又破了。

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8973827/83fb9f68-369c-11e5-8bc9-9889e8d95bdc.PNG)

**Comment by chenshaoju** [comment]
我的还是增长了一点点，但是并没有那么明显：

![screenshot](https://cloud.githubusercontent.com/assets/515763/8973870/40ffb4aa-369d-11e5-8e13-494c7ef35d4f.png)

我怀疑是不是和你的系统环境有关（比如，你安装了某些其他Bypass Wa11的软件）。
先重置TCP/IP和Winsocks看看，运行：
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset

重启后生效，IP会变回自动分配，如果是手动指定，记得重新设置。

**Comment by chenshaoju** [comment]
PS：你能用VMMap看一下内存都消耗在什么类型上了吗？

https://technet.microsoft.com/en-us/Library/dd535533.aspx

**Comment by uinux** [comment]
我照你说的命令已经打过了。没装Bypass Wa11......

**Comment by uinux** [comment]
话说github怎么@ 人。

**Comment by chenshaoju** [comment]
@uinux  直接打一个 @ 然后会有提示。

内存消耗继续上涨？你看一下VMMap呢？什么东西消耗了最多的内存？有必要截图发上来看看。

**Comment by uinux** [comment]
呃github自动ajax
![default](https://cloud.githubusercontent.com/assets/13487419/8974079/4f43b856-36a0-11e5-8d78-202e24538c63.PNG)

**Comment by uinux** [comment]
为什么一堆英文。......原因不明.......

**Comment by flintt** [comment]
命令重置后还是有内存上涨
是要看private这个区？
![image](https://cloud.githubusercontent.com/assets/3394691/8974101/8e843c5c-36a0-11e5-8a49-3bc0ff8e8151.png)

**Comment by uinux** [comment]
看着总计好像是300MB内存我。

**Comment by uinux** [comment]
@flintt 为什么你是两个条子，我是三个条子。

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8974144/f9c1bea4-36a0-11e5-8d07-21d766e288e9.PNG)

@chenshaoju 内存去哪儿了？？？

**Comment by flintt** [comment]
@uinux 什么两个条子？

**Comment by chenshaoju** [comment]
@flintt 点 File ，选择 Run as Administrator。另外，正常情况Private Data不应该消耗那么多内存。

@uinux 点一下Managed Heap，然后下面的列表都会变成绿色的，按Size排序，然后再发个图上来。

**Comment by chenshaoju** [comment]
@flintt @uinux 我怀疑和加密方式有关，你们用的什么加密方式？

**Comment by uinux** [comment]
@chenshaoju chacha20，据说这个效率高。

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8974231/000e7aee-36a2-11e5-898b-f1cfe321ef83.PNG)
传图。传完图后又不能@了，话说怎么报告这个bug给github全英文用起来很蛋疼。

**Comment by flintt** [comment]
使用的是aes-256-cfb，但是我估计和这个没有关系，一会儿返回2.4版本看看
![image](https://cloud.githubusercontent.com/assets/3394691/8974306/d2e5d228-36a2-11e5-9944-2ca6d428f23a.png)

**Comment by chenshaoju** [comment]
@uinux 有意思，垃圾收集消耗了最多的内存。

@flintt 基本看不出什么……

**Comment by uinux** [comment]
@flintt 是啊，加密应该不会消耗多少内存，最大消耗内存的可能在不稳定的网络.在最上面，我有三个条，你只有两个，这个很奇怪。

**Comment by uinux** [comment]
@chenshaoju 不明真相........

**Comment by uinux** [comment]
@chenshaoju 就是说已经分析出原因了，下一版会改进了对吗？

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8974528/25ebb508-36a5-11e5-999d-2e76d2ee89d5.PNG)
就在跟你们说话的时候它涨到130M了....

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8974577/ff8b9bd4-36a5-11e5-80f1-36fe9f94ef39.PNG)
又多了3MB，照这速度，几天就1GB了。

**Comment by flintt** [comment]
换了2.4版本的没有问题
更新了vmmap再贴个图
![image](https://cloud.githubusercontent.com/assets/3394691/8974614/5e2064ea-36a6-11e5-9eb6-1fb5e0069a92.png)

**Comment by uinux** [comment]
@flintt 这种情况，是要运行一天以上才会出现的吧。

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8974692/4effc4fa-36a7-11e5-990c-f7b2fe6e5197.PNG)
唉，要快没内存了。

**Comment by flintt** [comment]
@uinux 没有啊，打开立刻就可以出现。我是前天连接到一个端口有封锁的网络，系统提示内存不够了才发现的。

**Comment by uinux** [comment]
@flintt 我的日志里一直是异常中断。已经几MB了，才用了不到一个月

**Comment by uinux** [comment]
[2015-07-30 10:47:36] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-07-30 10:47:36] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-07-30 10:47:37] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-07-30 10:47:37] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-07-30 10:47:37] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-07-30 10:47:37] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-07-30 10:47:37] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2015-07-30 10:47:37] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)

**Comment by uinux** [comment]
跟这个有关？？？？

**Comment by uinux** [comment]
话说为什么这个只会增加，不会减少。大陆的网络环境已经非常恶劣了，大家要坚持下去。
![default](https://cloud.githubusercontent.com/assets/13487419/8974831/05444a96-36a9-11e5-94a6-11bafe8fccb7.PNG)

**Comment by chenshaoju** [comment]
等下，你们用的是 4.0 版本还是 2.0 版本？

**Comment by uinux** [comment]
@chenshaoju 3.21
![default](https://cloud.githubusercontent.com/assets/13487419/8974890/b0309130-36a9-11e5-9e71-92ac93e2f867.PNG)

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8974907/d7cd3518-36a9-11e5-836d-3fbbda244842.PNG)
2.5.1.0

**Comment by flintt** [comment]
.net版本？怎么看？

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8974920/f6c49a2e-36a9-11e5-8f67-2de8c37bfd98.PNG)

16.05

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/8974933/2488d04c-36aa-11e5-88fe-f2bb04cec6c4.PNG)
net和C++啥的，就这些了，4.0的

**Comment by flintt** [comment]
如果说的是.net版本，我的是4.5.1的，但是电脑里面也有安装了1.1的

**Comment by uinux** [comment]
@flintt 我们是不明真相的群众，如果说是客户端丢包，倒不如说是gwf找到了这东西的漏洞，在中间让我们的内存升高好让我们不用。仅是猜测。

**Comment by chenshaoju** [comment]
@flintt @uinux 这么说吧，你用的是 Shadowsocks-win-2.5.1.zip 还是 Shadowsocks-win-dotnet4.0-2.5.1.zip ？

**Comment by clowwindy** [comment]
用 Windows 任务管理器看呢？

**Comment by flintt** [comment]
哦，用的是没有dotnet的版本

**Comment by chenshaoju** [comment]
@flintt 我用的是4.0 的版本，你试试？

**Comment by flintt** [comment]
@clowwindy dotnet的版本任务管理器内存4~18M的样子
@chenshaoju dotnet的版本内存稳定，process explorer显示在28~38M左右

**Comment by clowwindy** [comment]
@flintt 我是指，出现问题的版本，出现问题的时候，Windows 自带任务管理器显示多少。

**Comment by flintt** [comment]
当process explorer显示100多M的时候，任务管理器的内存80多M的样子，切换服务器后任务管理器的内存会掉到4M，但是process explorer显示的没有掉

**Comment by flintt** [comment]
额，点错按钮了

**Comment by clowwindy** [comment]
用 dotnet 4.0 版本确认不存在这个问题？

**Comment by flintt** [comment]
@clowwindy 是的。我用了一段时间观察没有看到内存上涨的趋势。

**Comment by clowwindy** [comment]
既然 Windows 10 都发布了，我感觉也没有比较继续支持 .Net 2.0 了。

**Comment by flintt** [comment]
那以后就用dotnet4的版本
