### ISSUE TITLE
自定义 http 代理端口

### ISSUE THREAD

**Issue by xiaozhuai** [shadowsocks/shadowsocks-windows#2443]
希望添加自定义 http 代理端口的功能

当前 http 代理是通过 privoxy 实现的 socks5 转 http, 其中 http 代理的端口是随机的, 因此当我需要在控制台(wsl)中设置代理的时候会很麻烦, 我需要打开查看一下 privoxy 的配置以确定当前使用的 http 代理端口.

mac 版的 shadowsocks-ng 有自定义 http 代理端口的功能.
http 代理端口可默认设为 8118, 或默认情况下仍然使用随机端口, 但增加自定义 http 代理端口的选项.
感谢!!!

**Comment by xiaozhuai** [comment]
![QQ20190705-203953](https://user-images.githubusercontent.com/4773701/60723025-18513800-9f65-11e9-9564-065f07a80587.png)
找到代码如下, 红框处为获取随机端口, 本人不熟 c#, 希望有热心的小伙伴帮个忙, 谢谢!

**Comment by chenshaoju** [comment]
在编辑服务器界面右下角的代理端口中所指定的端口号是同时支持HTTP代理和SOCKS5代理的。

**Comment by xiaozhuai** [comment]
@chenshaoju 不好意思 你可能不知道我说的 上面我已经把具体的代码截图了， 确认了http代理的端口号是随机的而不是设置里指定的，设置里的端口号是socks5代理的端口号，而且http代理也不可能和socks5代理共用一个端口号的

**Comment by xiaozhuai** [comment]
@chenshaoju `GetFreePort` 这个方法的实现你可以去看一下

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1472

![image](https://user-images.githubusercontent.com/515763/60733093-8524fc00-9f7e-11e9-9c91-3e6668cfff05.png)

**Comment by xiaozhuai** [comment]
可以 了解了 不过这太隐晦了 还是希望加上我前面说的功能吧 mac版的就很清晰

**Comment by leonardwu** [comment]
同样希望可以自定义或者干脆取消默认的转换.

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
