### ISSUE TITLE
点显示日志的时候能不能打开文件夹并选中日志文件像pac那样。不然打开记事本会很慢。

### ISSUE THREAD

**Issue by uinux** [shadowsocks/shadowsocks-windows#245]
点显示日志的时候能不能打开文件夹并选中日志文件像pac那样。不然打开记事本会很慢。要十几秒忍受不住了。希望能改进。

**Comment by uinux** [comment]
另外问下，这什么情况。...一直可以正常上网来着。
[2015-07-29 14:54:21] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
[2015-07-29 14:54:43] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
[2015-07-29 14:54:43] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)

**Comment by celeron533** [comment]
那些exception主要是网络连接不畅或者是防火墙干扰引起的。

**Comment by uinux** [comment]
@celeron533 我想主要应该是国家级防火墙干扰引起的。

**Comment by 476210180** [comment]
是的，如果日志很长很长的话，调用记事本打开会卡死一段时间。

**Comment by clowwindy** [comment]
Fixed in 2.5.2
