### ISSUE TITLE
click download shadowsocks 4.17 error，url redirect others.... 

### ISSUE THREAD

**Issue by MasterYiLeng** [shadowsocks/shadowsocks-windows#2450]

**Comment by chenshaoju** [comment]
My here is fine.

Please try clean your browser cookies or change to another browser. 

![QQ截图20190711123521](https://user-images.githubusercontent.com/515763/61022447-5c669180-a3d8-11e9-8315-afa77dc688b6.png)

**Comment by celeron533** [comment]
Your DNS service may be hijacked.
