### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by bace1996** [shadowsocks/shadowsocks-windows#2451]
### Shadowsocks version / 影梭版本
4.1.7

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
.net4.7.2,vc2015
win10 1809 17763.615

### Steps you have tried / 操作步骤
启动程序

### What did you expect to see? / 期望的结果
在后台运行

### What did you see instead? / 实际结果
![image](https://user-images.githubusercontent.com/10097443/61047337-d8310000-a411-11e9-9b93-375f68b1be30.png)
出现图示报错后程序退出
清空所有配置文件和临时文件启动仍然得到此报错

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[gui-config.json.txt](https://github.com/shadowsocks/shadowsocks-windows/files/3381770/gui-config.json.txt)
[statistics-config.json.txt](https://github.com/shadowsocks/shadowsocks-windows/files/3381771/statistics-config.json.txt)
[shadowsocks.log](https://github.com/shadowsocks/shadowsocks-windows/files/3381772/shadowsocks.log)

**Comment by chenshaoju** [comment]
这看起来很像在处理 json 文件时遇到了错误，请尝试使用  https://www.microsoft.com/en-gb/download/details.aspx?id=30135 进行修复，如果仍然不行，请尝试安装最新的 .net framework 看看：https://dotnet.microsoft.com/download/thank-you/net48

**Comment by bace1996** [comment]
重新安装 .net 已解决
