### ISSUE TITLE
用腾讯电脑管家清完垃圾完无法翻墙

### ISSUE THREAD

**Issue by utyuu** [shadowsocks/shadowsocks-windows#2452]
### Shadowsocks version / 影梭版本
4.1.7

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win 10

### Steps you have tried / 操作步骤
1、手机上可以使用，电脑上换两个服务器都不行。
2、cmd中，ping部分国外网站能ping通。
3、chrome和IE都没法打开国外网页，显示检查Proxy服务器。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
###日志↓↓↓
[2019-07-12 11:32:09] Shadowsocks started (4.1.7)
[2019-07-12 11:32:09] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-12 11:32:13] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-12 11:32:33] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
###电脑代理设置↓↓↓
![image](https://user-images.githubusercontent.com/20180409/61100779-efb3cb80-a499-11e9-8666-5f98f6635320.png)

**Comment by chenshaoju** [comment]
请检查网络防火墙，以允许 Shadowsocks.exe 访问网络，参考：https://github.com/shadowsocks/shadowsocks-windows/issues/2445

**Comment by utyuu** [comment]
> 请检查网络防火墙，以允许 Shadowsocks.exe 访问网络，参考：#2445
是这样的 感谢
