### ISSUE TITLE
Release 页面 Shadowsocks-4.1.7 信息不一致

### ISSUE THREAD

**Issue by Archcy** [shadowsocks/shadowsocks-windows#2453]
Release 页面，4.1.7的release信息中 Info of Shadowsocks.exe 是否应改为 Info of Shadowsocks-4.1.7.zip ?
### Steps you have tried / 操作步骤
通过 联通/ 移动 / 代理 下载 [shadowsocks-4.1.7](https://github.com/shadowsocks/shadowsocks-windows/releases/download/4.1.7/Shadowsocks-4.1.7.zip)后，使用7zip解压并通过Power shell的Get-FileHash 函数校验 Shadowsocks.exe 文件完整性。

### What did you expect to see? / 期望的结果
SHA256:83C2966FE942B2B0A1E31EA84F6336C024CB57FF5C397B0D1CDDF050BB4E5B21

### What did you see instead? / 实际结果
SHA256:981BCA05B6E93C2EA839F75CF2D37E4BBBDA41701C8110EB9896D474FB4F4F40

但是直接对zip文件进行校验，得到的结果与期望一致。
如果确实提供的是zip文件的hash，希望能注意一下这个细节。

**Comment by celeron533** [comment]
已纠正。谢谢

**Comment by Archcy** [comment]
> 已纠正。谢谢

谢谢您的修改。
