### ISSUE TITLE
Shadowsocks UI Error - System.ComponentModel.Win32Exception (0x80004005): Application not found

### ISSUE THREAD

**Issue by gaorui84** [shadowsocks/shadowsocks-windows#2454]
### Shadowsocks version / 影梭版本
4.1.7

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 7 / .NET Framework 4.7.2

### Steps you have tried / 操作步骤
Right-click the icon -> Help -> About...

### What did you expect to see? / 期望的结果
Display the version of Shadowsocks client

### What did you see instead? / 实际结果
Shadowsocks UI Error
Unexpected error, shadowsocks will exit. Please report too
...
Exception Detail:
System.ComponentModel.Win32Exception (0x80004005): Application not found
...

**Comment by chenshaoju** [comment]
Odd, This looks like your system don't have any browser or something blocked shadowsocks request the browser .

**Comment by gaorui84** [comment]
This error occurs when I have [Brave ](https://www.brave.com/) ([Github](https://github.com/brave/brave-browser/)) as my default browser, which has Trackers & Ads Block feature embedded . Does it prevent the windows client from reading something? This has been an issue for a long time and I wish it be fixed ASAP.

**Comment by chenshaoju** [comment]
I'm using Firefox and Edge, But not have this issue.
Please try use system "Run" (Win+R) to open a URL, It's can work?
![image](https://user-images.githubusercontent.com/515763/61173505-e5432000-a5c6-11e9-95d4-8b85ce1d8fbe.png)

**Comment by gaorui84** [comment]
I've also tried other browsers including Chrome, Opera or even IE11 and all those browsers worked. Nevertheless, it doesn't work with Brave (even if http:// is added) and a dialog box would pop up with an 'Application not found' error.

**Comment by chenshaoju** [comment]
The source code is direct call `https://github.com/shadowsocks/shadowsocks-windows` to open browsers, I think is your system file association (or protocol association) is corrupted. Maybe need set another browser as default(eg. IE), And set Brave as default again.
https://github.com/shadowsocks/shadowsocks-windows/blob/72678c462dfba421f357e65c8f4dec3bc55f6057/shadowsocks-csharp/View/MenuViewController.cs#L609

**Comment by gaorui84** [comment]
Since I have no knowledge of C# so I don't know the details of its implement. However, I don't think it's an issue of system file association because when I switched the default browsers to some other browsers such as Vivaldi the URL can be opened from the Run window. When I switch the default browser back to Brave the issue is back. I think this issue may be exclusive to some brand new browsers with embedded Trackers & Ads Block e.g. Brave (latest Ver 0.66.99), which is known to have issues browsing trackers-n-ads-using websites like taobao.com. Nevertheless, it seems that from the ss-win client side, at the least level such non-fatal UI exceptions should be caught to prevent the app from breaking down.

**Comment by celeron533** [comment]
May caused by corrupted file association in register. When executing `Process.Start()`, windows will do the system's default behavior. There is nothing about ss-win itself.
