### ISSUE TITLE
4.1.7版本 编辑服务器页面【应用】按钮是灰的 不可用

### ISSUE THREAD

**Issue by aglent** [shadowsocks/shadowsocks-windows#2457]
之前的版本 在编辑服务器页面选择不同服务器时 可以随时点击【应用】按钮 使其生效而不离开配置页面
现在4.1.7版本 选择不同服务器时 【应用】按钮始终是灰色的 不可用

**Comment by chenshaoju** [comment]
Confirmed

**Comment by Stzx** [comment]
应用按钮需要对配置内容做修改才会启用。
