### ISSUE TITLE
4.1.7 删除按钮有严重的问题 / Delete button issue

### ISSUE THREAD

**Issue by imba-tjd** [shadowsocks/shadowsocks-windows#2458]
### Shadowsocks version / 影梭版本
4.1.7

现在的效果是点删除，会删掉选中的下面的那个，并且跳到最后一项。

`UpdateIndexToEnd();`前一行还是正常的，执行完这个函数后没有的就是选中的下面一项了。

应该是 https://github.com/shadowsocks/shadowsocks-windows/pull/2410/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.yml#diff-411c02bb9a33cb67be83f9fd7aa03dcc 引入的。

**Comment by chenshaoju** [comment]
Confirmed @celeron533

**Comment by Stzx** [comment]
你好，看起来是我疏忽造成的这个低级错误，非常抱歉。

😰

**Comment by celeron533** [comment]
Will release this fix ASAP.
