### ISSUE TITLE
使用proxifier失败，无法连接

### ISSUE THREAD

**Issue by MrPiglet** [shadowsocks/shadowsocks-windows#2462]
正常是可以使用代理的，但是使用proxifier进行全局代理的话就会出错，无法进行连接，包括如果只使用QQ中的代理的话，能登录但是无法进行聊天，求解决

**Comment by chenshaoju** [comment]
请在 proxifier 的代理进程排除列表中（如果有）排除 Shadowsocks.exe 和 ss_privoxy.exe 进程。

**Comment by MrPiglet** [comment]
Shadowsocks和ss_privoxy.exe为直连，我看到连接的那个列表中，只有发送但是没办法接收，不知道是ss的问题还是proxifier配置的问题，之前这个配置用是可以连接成功的，后来新搭了一个ss之后就没办法使用了，也不知道是版本更新的问题，变量有点多，不知道从哪里解决，还是谢谢您

**Comment by chenshaoju** [comment]
我倾向于proxifier 的问题，使用的版本是……？

**Comment by MrPiglet** [comment]
3.4.2
之前在没有新搭建ss的时候，是可以正常使用的

**Comment by chenshaoju** [comment]
我怀疑可能和你的Winsocks或TCP/IP协议栈受损有关。

请尝试以管理员身份启动命令提示符或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```

一行一会车，四行执行完毕后重新启动计算机看看。

**Comment by MrPiglet** [comment]
试了一下，还是不行

**Comment by chenshaoju** [comment]
出现问题的时候，尝试使用经过代理的软件访问一下网络（网站），SS的日志里有显示什么吗？

**Comment by MrPiglet** [comment]
![image](https://user-images.githubusercontent.com/26847115/61271475-4e997d80-a7d7-11e9-8b72-c274f54f196f.png)
这个是proxifier的截图
![image](https://user-images.githubusercontent.com/26847115/61271744-03339f00-a7d8-11e9-88b7-01a4045f77b5.png)
这个是ss的日志
在用chrome访问网站的时候，左下角的连接一直卡在`正在等待代理隧道的响应`
并且我用另外一台电脑测试了一次，也同样不行

**Comment by MrPiglet** [comment]
在配置proxifier服务器的时候，使用代理检查器，检查`www.youtube.com`的`80`端口是可以成功的，但是`443`端口就会失败

**Comment by chenshaoju** [comment]
为什么你的 Shadowosocks 在尝试连接 127.0.0.1:1080 ？你是不是设置了正向代理？

![image](https://user-images.githubusercontent.com/515763/61286253-10ab5200-a7f5-11e9-8fea-63e8608307a9.png)

**Comment by MrPiglet** [comment]
没有，我没有动那个正向代理

**Comment by chenshaoju** [comment]
如果我没理解错的话，你是希望是用proxifier让你计算机上的所有软件都经过Shadowsocks对吧？

看一下你的SS的系统代理设置，是关闭吗？

**Comment by MrPiglet** [comment]
对，我想让计算机的应用都通过Shadowsocks
我之前使用的是全局模式，然后我刚刚试了一下禁用，之后可以访问国内的网站，但是访问不了Youtube这些，然后我试着调成Pac模式，就可以访问Youtube了，并且proxifier里面的连接也都正常接收到了，这是为什么呢，是因为ss和proxifier的全局模式冲突了吗
如果是这样的话，为什么我在学校的时候使用校园网，两个可以正常的工作，是因为学校支持IPV6吗，因为之前没办法使用的时候我在proxifier里面也有时候会看到正在连接IPV6的节点
最后，还是谢谢您！！！感谢您花时间来解决我的问题，谢谢！！！

**Comment by chenshaoju** [comment]
我怀疑你的proxifier配置有问题……

**Comment by MrPiglet** [comment]
![image](https://user-images.githubusercontent.com/26847115/61294555-a69ca800-a808-11e9-9961-c10c139d2240.png)
这个是代理规则
![image](https://user-images.githubusercontent.com/26847115/61294568-b3b99700-a808-11e9-888f-59f09d723ec4.png)
这个是代理服务器的配置，都是没问题的啊，不过就变成pac模式就好了，我也不知道为什么，但是在学校的时候是好的，还有什么需要配置的地方吗

**Comment by chenshaoju** [comment]
我怀疑你的 proxifier 可能根本没有工作，请尝试退出 proxifier 看看？

**Comment by MrPiglet** [comment]
没有，现在已经解决掉了，我把Shadowsocks改成pac模式之后，就可以正常使用代理了，之后往proxifier里面添加规则也可以正常是用应用的代理
只是我不知道为什么在学校的网络环境下Shadowsocks可以在proxifier开启的情况下使用全局代理，在家里这样就不能正常访问

**Comment by chenshaoju** [comment]
OK，此Issue先关闭了。

**Comment by linruiand** [comment]
同样遇到

**Comment by chenshaoju** [comment]
你需要将 Shadowsocks.exe 或者你的SS服务器加入你的 Proxifier 的例外列表（不代理）。

不然会导致本地环回。

**Comment by linruiand** [comment]
这个我已经加了。服务端我用的openwrt的libev版本，客户端用的Windows版本，加密方式端口都不错，pac形式和全局形式都可以代理，但是用proxifiler连接shadowsocks-windows的本地端口就不行

**Comment by chenshaoju** [comment]
日志中有任何显示吗？

**Comment by linruiand** [comment]
proxifiler连接测试：
测试地址：www.baidu.com
shadowsocks-libev服务端日志： remote recv: Connection reset by peer

proxilifer日志：
[30:37] 正在开始: 测试 1: 连接到代理服务器
[30:37] IP 地址: 127.0.0.1
[30:37] 已建立连接
[30:37] 测试已通过。
[30:37] 正在开始: 测试 2: 通过代理服务器连接
[30:37] 身份验证成功。
[30:37] 已通过代理服务器与 baidu.com:80 建立了连接。
[30:39] 错误: 代理服务器的连接被意外关闭。
	请确保目标主机是 Web 服务器。
	此错误也可能表示代理服务器不能正常运行。
[30:39] 测试已失败。
[30:39] 测试已完成。
shadowssockswindows客户端日志：
[2019-08-24 11:30:23] Socket connected to ss server: 192.168.1.1:25
[2019-08-24 11:30:37] connect to baidu.com:80

**Comment by linruiand** [comment]
补充：proxilifer端连接shadowswindows代理的本地端口测试那种非https的页面，就可以成功。

**Comment by chenshaoju** [comment]
你的日志中看不出来任何问题。
你的SS的确是搭建在路由器上的25端口对吧？

**Comment by linruiand** [comment]
是的，用的路由器的25端口。另外pac模式和全局代理模式均无问题，只有与proxifiler连接才有问题

**Comment by chenshaoju** [comment]
不知道了……我没具体研究过proxifiler。

**Comment by linruiand** [comment]
怀疑跟这个遇到的问题一样。https://github.com/mritd/dockerfile/issues/49
暂时搞不明白，换了种方式妥协了。
非常感谢指导，谢谢！ @chenshaoju

**Comment by GeT1t** [comment]
也遇到了这个问题，要在proxifier里面设置ss 是直连的就解决了
