### ISSUE TITLE
发版建议

### ISSUE THREAD

**Issue by alphonsetai** [shadowsocks/shadowsocks-windows#2465]
现在我在正在用python版的ss服务端，和c#版的客户端。由于最近加班太多（我也在发版...）没来得及去把遇到的问题和现象具体q去看看并上报。

每次启动客户端的时候虽然客户端会主动提示有版本升级，并下好。但对于我这种不喜欢用pac直接开全局代理的人来说，最近一段时间的release changlog有点看不太明白了。比如有一些第四位小版本或第三位小版本的changlog看着好像都是在修改一些ui配置项相关。

可能每个人关注点不同，对于我来说，我更多关注的连接、速度、可靠性方面相关的优化，不晓得今后的changlog可否简单对这方面做个大概说明，这样我也好方便觉得是否覆盖文件。

或者提示一下该版本是否对协议相关做过优化和bug修改就好，我自己去看提交日志也行。

**Comment by celeron533** [comment]
抱歉。很忙。没时间。没精力。有能力的话可以发pull request。具体的改动可以看源码，change log只是简报。
