### ISSUE TITLE
建议增加纯代理服务器模式

### ISSUE THREAD

**Issue by alphonsetai** [shadowsocks/shadowsocks-windows#2466]
现在客户端有pac和全局模式。

我并不使用pac，更多的习惯是选择上全局模式，并到ie中将代理配置关掉。把ss客户端当作一个本地代理服务器来使用，对我这类需求的人来说，这样操作也稍微有些多此一举。

所以建议增加该模式，当时若各位提交者没时间的话，我自己在界面上加个按钮也行，只是对ui和c#可能不太熟悉，pr之后还望各位帮慢review。

看各位意下如何。

**Comment by chenshaoju** [comment]
系统代理 -> 禁用

**Comment by alphonsetai** [comment]
原来如此，我自己关闭了
