### ISSUE TITLE
手机正常使用，电脑无法使用

### ISSUE THREAD

**Issue by onecoc** [shadowsocks/shadowsocks-windows#2467]
### Shadowsocks version / 影梭版本
4.1.7

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows10

### Steps you have tried / 操作步骤

正常使用
### What did you expect to see? / 期望的结果

翻墙
### What did you see instead? / 实际结果

pc连接全局，pac模式所有被墙网站都无法上，但其他网站全局和pac模式都正常
使用手机连接所有网站都正常
pc连接已经翻墙的手机热点也无法上被墙网站

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-07-16 21:11:27] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-16 21:11:27] Shadowsocks started (4.1.7.1)
[2019-07-16 21:11:27] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-07-16 21:11:27] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
（一直都是上面这句Cannot get Windows 10 system theme mode, return default value 0 (dark mode).）

不知道是不电脑代理的问题，我的电脑代理脚本在启动后一直是空的

**Comment by chenshaoju** [comment]
请右击任务栏托盘区的纸飞机图标，选择PAC，再点击从GFWList更新本地PAC看看？

如果成功了，请确保系统代理在PAC模式下。

如果失败了，日志中有什么内容显示吗？

**Comment by onecoc** [comment]
[2019-07-16 21:52:57] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-16 21:53:01] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-16 21:53:09] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-16 21:53:20] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-16 21:53:30] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-16 21:53:30] Checking GFWList from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
[2019-07-16 21:53:30] connect to raw.githubusercontent.com:443
[2019-07-16 21:53:30] Socket connected to ss server: 45.32.158.98:10365
[2019-07-16 21:53:58] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-07-16 21:53:58] Checking GFWList from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt



没有效果

**Comment by chenshaoju** [comment]
然后没有出现任何提示吗？

**Comment by DiabolumFDU** [comment]
我和你遇到一样的情况，笔记本用学校的wifi原来可以用ss，但是突然就不可以了，时断时续。手机pad都正常ss，而且笔记本用手机的热点也能连接ss。主要问题我觉得可能教育网会有ip检测的，我教育网的IP出问题的时候都不能用putty登上vps

**Comment by onecoc** [comment]
我不是教育网，后面我用chrome的switchymoega插件，chrome可以连上，但是pc上其他的还是不能连。
我猜测可能是我电脑那个代理的问题，我用其他有效vpn软件时，都会自动更新代理脚本，但是使用ss时无法自动更新代理脚本

**Comment by liuziliangg** [comment]
我也是同样的问题，莫名其妙PC不能用了，IOS用的是Potatso客户端，正常的。

**Comment by chenshaoju** [comment]
日志中有任何显示吗？

**Comment by liuziliangg** [comment]
> 
> 
> 日志中有任何显示吗？

长时间连接不上后有报错日志，如下：

[2019-07-21 18:31:12] connect to clients4.google.com:443
[2019-07-21 18:31:13] Socket connected to ss server: AWS-新加坡 (13.229.123.19:6789)
[2019-07-21 18:32:45] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-07-21 18:33:40] connect to www.youtube.com:443
[2019-07-21 18:33:40] Socket connected to ss server: AWS-新加坡 (13.229.123.19:6789)
[2019-07-21 18:33:40] connect to www.youtube.com:443
[2019-07-21 18:33:41] Socket connected to ss server: AWS-新加坡 (13.229.123.19:6789)
[2019-07-21 18:33:41] connect to www.youtube.com:443
[2019-07-21 18:33:41] Socket connected to ss server: AWS-新加坡 (13.229.123.19:6789)

**Comment by chenshaoju** [comment]
```由于远程方已关闭传输流，身份验证失败。``` 要么超时时间太短，要么你的网络出于某种原因暂时切断了你的TCP连接。

**Comment by liuziliangg** [comment]
> 
> 
> `由于远程方已关闭传输流，身份验证失败。` 要么超时时间太短，要么你的网络出于某种原因暂时切断了你的TCP连接。
> 
> 如果你的服务器是自己搭的，情尝试套一个插件看看：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

还没搭插件，突然间就好了。感觉这个客户端还是有些问题。昨天好好的，就是睡了一觉今天就不行了，所以配置肯定不会有错；IOS手机正常连接，所以服务器配置也是没有问题。这突然又好了，，，

**Comment by chenshaoju** [comment]
我认为是墙切断了你的连接。。。或者你的计算机上有什么东西干扰了SS的连接。。。

当出现问题的时候，位于同一个局域网中的其他设备能用吗？（不包括手机使用3G/4G网络）。

**Comment by liuziliangg** [comment]
> 我认为是墙切断了你的连接。。。或者你的计算机上有什么东西干扰了SS的连接。。。
> 
> 当出现问题的时候，位于同一个局域网中的其他设备能用吗？（不包括手机使用3G/4G网络）。

手上没有其他电脑，但手机连的是局域网WiFi，正常使用

**Comment by chenshaoju** [comment]
有一些非常诡异的现象，在使用插件后就会消失，怀疑是墙封了端口，但是又无法验证。

**Comment by w2coder1227** [comment]
我也有这个问题，日志基本一样。重置网络无效，重装了vps服务器系统和ss也无效，新增端口无效。pc端能访问墙内访问不了墙外，手机同一wifi下访问毫无问题。另外一个安装顺序和配置完全一样的vps在pc端访问一点问题没有，也是醉了。

**Comment by YaoLongrui** [comment]
我也遇到了同样的问题，实验室电脑不可以使用shadowsocks，无论是pac还是全局都无法连接，同样的节点手机以及宿舍的笔记本可以用，头疼

**Comment by chenshaoju** [comment]
请示一下：将实验室的电脑连接上手机的共享WiFi，看看是否可用了？

如果可用了，说明你的实验室有网络封锁，请联系网管中心。

如果仍然不可用，请将SS的日志上传上来。

**Comment by JamosLi** [comment]
同样问题，服务器重启，重装，换了，1027,8083,8081,220,2201.。。。都没有用。但是手机都可以用。电脑连手机WiFi也用不了。

错误：

[2019-08-29 16:19:56] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by JamosLi** [comment]
插件太麻烦了。。。。

**Comment by chenshaoju** [comment]
如果确定计算机使用手机共享的WiFi也无法使用的话，可能和操作系统协议栈受损有关。

请以管理员身份启动命令提示符或者PowerShell，执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机看看。

**Comment by YaoLongrui** [comment]
我的问题通过更改电脑IP得到了解决。怀疑是学校的网络中心封锁了我上一个ip

**Comment by minggelucky** [comment]
> `由于远程方已关闭传输流，身份验证失败。` 要么超时时间太短，要么你的网络出于某种原因暂时切断了你的TCP连接。
> 
> 如果你的服务器是自己搭的，情尝试套一个插件看看：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

具体插件怎么用，小白一个

**Comment by minggelucky** [comment]
> 我认为是墙切断了你的连接。。。或者你的计算机上有什么东西干扰了SS的连接。。。
> 
> 当出现问题的时候，位于同一个局域网中的其他设备能用吗？（不包括手机使用3G/4G网络）。
![873B77CE-A4D6-4db9-BC6D-CDE7EC2784F4](https://user-images.githubusercontent.com/55421267/65006857-f39b1880-d936-11e9-9a58-d121d753f225.png)
日志一样问题，从GFWlist更新本地pac，直接弹出操作过程异常，结果无效。

**Comment by chenshaoju** [comment]
是的，这意味着从你当前的网络到你的SS服务器不通或者连接被切断了。

**Comment by minggelucky** [comment]
> 是的，这意味着从你当前的网络到你的SS服务器不通或者连接被切断了。

怎么办？笔记本，pc 换了几台电脑几个地方都不行

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，请尝试套一个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

如果你的服务器是找服务商买的，请与你的服务商联系。

**Comment by JamosLi** [comment]
我在想是不是使用的意见ssr安装包有问题 ：
我用的库：
https://github.com/flyzy2005/ss-fly.git

**Comment by JamosLi** [comment]
服务器用的搬瓦工

**Comment by chenshaoju** [comment]
这个……建议询问一下脚本的制作人。。。

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history

**Comment by oldtwotwo** [comment]
我的ssr是这个
[2019-10-11 21:18:03] [Error] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.IEProxyUpdate(Configuration config, Int32 sysProxyMode)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer

**Comment by xusuy** [comment]
手机ios的客户端包有吗

**Comment by yulchen** [comment]
> 如果确定计算机使用手机共享的WiFi也无法使用的话，可能和操作系统协议栈受损有关。
> 
> 请以管理员身份启动命令提示符或者PowerShell，执行：
> 
> ```
> netsh interface ipv4 reset
> netsh interface ipv6 reset
> netsh interface tcp reset
> netsh winsock reset
> ```
> 
> 一行一回车，四行执行完毕后重新启动计算机看看。

你好，按照这个方法重启后马上打开谷歌是可以的，不到一分钟电脑又连不上了，手机上还是可以连，请问还有什么办法可以用吗

**Comment by chenshaoju** [comment]
电脑和手机是同一个局域网吗？还是说电脑是局域网，手机是3G/4G？

**Comment by Candane** [comment]
我的也是这样，手机和电脑连的是同一个局域网。

**Comment by mptm436** [comment]
> > 如果确定计算机使用手机共享的WiFi也无法使用的话，可能和操作系统协议栈受损有关。
> > 请以管理员身份启动命令提示符或者PowerShell，执行：
> > ```
> > netsh interface ipv4 reset
> > netsh interface ipv6 reset
> > netsh interface tcp reset
> > netsh winsock reset
> > ```
> > 
> > 
> > 一行一回车，四行执行完毕后重新启动计算机看看。
> 
> 你好，按照这个方法重启后马上打开谷歌是可以的，不到一分钟电脑又连不上了，手机上还是可以连，请问还有什么办法可以用吗

我也是一样的情况，局域网内另外一台pc自动配置了代理脚本，去掉自动代理选择代理脚本就能翻墙了，但这一台pc代理脚本是空的，把另外那个pc的脚本贴上去也不行
脚本是http://127.0.0.1:10810/pac/?t=053759

**Comment by sansh8** [comment]
1.网卡设置：随机硬件地址—开
2.换个服务器端口号

**Comment by HarryReidx** [comment]
情况与楼主一致，自己搭的梯子手机Shadowsocks可以正常使用，电脑上小飞机怎么都不行，后来换成v2ray就行了...离谱 于是就把小飞机卸载了
