### ISSUE TITLE
新功能请求：测试代理服务器

### ISSUE THREAD

**Issue by wjx0912** [shadowsocks/shadowsocks-windows#2468]
想知道一系列服务器哪个最快，高可用或者负载均衡不一定能匹配最快的。

拍脑袋想的，恳请作者实现，感谢！

图片在这里：
http://101.200.50.71/test/ss_test_ui.png

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1649

**Comment by wjx0912** [comment]
ok, thanks
