### ISSUE TITLE
isIpv6Enabled is a confuse name

### ISSUE THREAD

**Issue by EXSERENS** [shadowsocks/shadowsocks-windows#2470]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1809

### Steps you have tried / 操作步骤
```"isIPv6Enabled": true,```

### What did you expect to see? / 期望的结果
Listen on v4/v6 port at same time.

### What did you see instead? / 实际结果
only listen on v6 port.

**Comment by celeron533** [comment]
In current implementation, ss cannot listening on both v4 and v6.
This configuration switch is in experimental and may be changed in the future.

**Comment by yzs981130** [comment]
Same problem. Any update?
