### ISSUE TITLE
4.1.7.1版本检查更新失败 The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by JackShu404** [shadowsocks/shadowsocks-windows#2471]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 7

### Steps you have tried / 操作步骤
帮助->更新->检查更新

### What did you expect to see? / 期望的结果
没有更新提示没有更新，有更新下载最新版本并提示有更新。

### What did you see instead? / 实际结果
报错。
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 请求被中止: 未能创建 SSL/TLS 安全通道。

The request was aborted: Could not create SSL/TLS secure channel

**Comment by chenshaoju** [comment]
比较奇怪，我也有这个错误，无法检查更新。
```
[2019-07-18 13:06:04] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 请求被中止: 未能创建 SSL/TLS 安全通道。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
```

但是访问 https://api.github.com/repos/shadowsocks/shadowsocks-windows/releases 并没有问题。

**Comment by imba-tjd** [comment]
4.7的改动。
用`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12|SecurityProtocolType.SystemDefault;`可以解决，不过我不知道加到哪里合适。

**Comment by celeron533** [comment]
https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5/36454717#36454717
