### ISSUE TITLE
在选择服务器界面支持鼠标滚轮滚动

### ISSUE THREAD

**Issue by loveqianool** [shadowsocks/shadowsocks-windows#2472]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 NET 4.8

### Steps you have tried / 操作步骤
![111.jpg](https://i.loli.net/2019/07/18/5d2ffba47956b93348.jpg)

### What did you expect to see? / 期望的结果
可以使用鼠标滚轮滚动。

### What did you see instead? / 实际结果
现在是只能点下面的小三角往下滚动，在笔记本小屏幕下很难点中，而且滚动速度很慢。

**Comment by celeron533** [comment]
这是系统默认的右键菜单行为

**Comment by zevmore-vip** [comment]
您好 !  q请问节点在哪里下载获取啊？ 谢谢
