### ISSUE TITLE
非预期错误，S-S将退出

### ISSUE THREAD

**Issue by 2427237507** [shadowsocks/shadowsocks-windows#2475]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
System：10.0.18362.175
Net Framework Version:4.8

### Steps you have tried / 操作步骤
以管理员方式打开

### What did you expect to see? / 期望的结果
能正常打开

### What did you see instead? / 实际结果
未能加载文件或程序集

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
 [E] System.IO.FileNotFoundException: 未能加载文件或程序集“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”或它的某一个依赖项。系统找不到指定的文件。
文件名:“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”
   在 GlobalHotKey.HotKeyManager..ctor()
   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   在 Shadowsocks.Program.Main(String[] args)

**Comment by chenshaoju** [comment]
请尝试更新或修复安装你的 .Net Framework: https://dotnet.microsoft.com/download/thank-you/net48
