### ISSUE TITLE
偶然不工作，没任何提示。重启软件后恢复正常

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-windows#2477]
Shadowsocks version / 影梭版本
4.1.7.1

Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows7     NET.Framework 4.7.2

问题描述：使用途中出现过不能代理的情况，没有任何提示。关闭浏览器，重启SS客户端后才恢复正常

**Comment by chenshaoju** [comment]
日志中有任何显示吗？

**Comment by celeron533** [comment]
Close due to no response
