### ISSUE TITLE
Problem with win10.

### ISSUE THREAD

**Issue by futurehome** [shadowsocks/shadowsocks-windows#248]
When I start ss, error occurs, a window pops up (the pic attached).  The version is 2.5.1 for win.

[2015-07-30 15:24:53] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.Configuration.ConfigurationErrorsException: 创建在“system.net/defaultProxy”配置节中指定的 Web 代理时出错。 ---> System.Net.Sockets.SocketException: 系统调用失败。
   在 System.Net.SafeCloseSocketAndEvent.CreateWSASocketWithEvent(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType, Boolean autoReset, Boolean signaled)
   在 System.Net.NetworkAddressChangePolled..ctor()
   在 System.Net.AutoWebProxyScriptEngine.AutoDetector.Initialize()
   在 System.Net.AutoWebProxyScriptEngine.AutoDetector.get_CurrentAutoDetector()
   在 System.Net.AutoWebProxyScriptEngine..ctor(WebProxy proxy, Boolean useRegistry)
   在 System.Net.WebProxy.UnsafeUpdateFromRegistry()
   在 System.Net.WebProxy..ctor(Boolean enableAutoproxy)
   在 System.Net.Configuration.DefaultProxySectionInternal..ctor(DefaultProxySection section)
   在 System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   在 System.Net.WebRequest.get_InternalDefaultWebProxy()
   在 System.Net.HttpWebRequest..ctor(Uri uri, ServicePoint servicePoint)
   在 System.Net.HttpRequestCreator.Create(Uri Uri)
   在 System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   在 System.Net.WebRequest.Create(Uri requestUri)
   在 System.Net.WebClient.GetWebRequest(Uri address)
   在 System.Net.WebClient.DownloadStringAsync(Uri address, Object userToken)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2015-07-30 15:24:55] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
[2015-07-30 15:49:29] System.InvalidOperationException: 进程已退出，因此无法处理请求。
   在 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.Process.Kill()
   在 Shadowsocks.Controller.PolipoRunner.Stop()
[2015-07-30 15:49:49] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
[2015-07-30 15:52:47] System.InvalidOperationException: 进程已退出，因此无法处理请求。
   在 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.Process.Kill()
   在 Shadowsocks.Controller.PolipoRunner.Stop()
[2015-07-30 15:52:47] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
![error_ss](https://cloud.githubusercontent.com/assets/6230304/8978289/536c2fe8-36d3-11e5-853a-c66a108d75e1.png)

**Comment by chenshaoju** [comment]
What is your shadowsocks .NET version? 4.0 or .NET 2.0?

![screenshot](https://cloud.githubusercontent.com/assets/515763/8979478/98d3c984-36dc-11e5-91c7-8930d29129c3.png)

**Comment by futurehome** [comment]
是4.0的。

**Comment by futurehome** [comment]
It works after I execute "netsh winsock reset". But I dont know why.

**Comment by celeron533** [comment]
2GB内存跑64位系统有点可怜啊。。。
昨天我也升级了win10，对于一般用户基本能够做到平滑升级。但是对于程序狗来说，开发环境多多少少出了些问题。所以后来我直接重置系统了。

**Comment by clowwindy** [comment]
无法重现。

**Comment by kylechenoO** [comment]
请问楼主最后如何解决的
同样的报错
运行netsh winsock reset之后依旧存在
重启后也无事于补

**Comment by celeron533** [comment]
@kylechenoO 目前最新版的SS-win 4.0.4 需要 .net framework 4.6.2

**Comment by kylechenoO** [comment]
@celeron533 win10系统选项里面安装的.net 4.7可以吗

**Comment by celeron533** [comment]
@kylechenoO 应该是没问题

**Comment by kylechenoO** [comment]
@celeron533 还是不行 在重置系统了
