### ISSUE TITLE
[DOCUMENTATION] Add instructions on how to make metro UI apps like edge work

### ISSUE THREAD

**Issue by Omoeba** [shadowsocks/shadowsocks-windows#2480]
Due to the AppContainer isolation in windows 8 and 10, metro apps like edge and MSN News are unable to access localhost. something like enable loopback utility available here https://www.telerik.com/fiddler/add-ons is needed to make shadowsocks work for metro apps.

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1004
