### ISSUE TITLE
[QUESTION] how to test if UDP traffic is being proxied?

### ISSUE THREAD

**Issue by Omoeba** [shadowsocks/shadowsocks-windows#2481]
I have installed proxycap and set it to route UDP traffic to the local SOCKS proxy. Is there any way to test if UDP traffic is correctly proxied?

**Comment by chenshaoju** [comment]
You may try SSTap: https://www.sockscap64.com/sstap-enjoy-gaming-enjoy-sstap/
Tips: This is 3rd-party software, It has nothing to do with Shadowsocks.

**Comment by Omoeba** [comment]
I am looking for a way to test if udp is tunneled properly

**Comment by chenshaoju** [comment]
You may try SocksCap64: https://www.sockscap64.com/homepage/
![QQ截图20190722103729](https://user-images.githubusercontent.com/515763/61602597-cd296b80-ac6c-11e9-8856-768bc6788d3c.png)

 Tips: This is 3rd-party software, It has nothing to do with Shadowsocks.

**Comment by Omoeba** [comment]
hmm it seems to be discontinued and unable to be downloaded though

**Comment by chenshaoju** [comment]
At page bottom: https://www.sockscap64.com/sockscap-64-free-download-zh-hans/

This is the final reply.

**Comment by Omoeba** [comment]
thanks

**Comment by Omoeba** [comment]
@chenshaoju SSTap worked great but are there similar programs that are still actively maintained?

**Comment by chenshaoju** [comment]
IDK, I'm not using this type of software for now.

**Comment by Omoeba** [comment]
guess I'll try something like wireguard
