### ISSUE TITLE
ping 正常，但总是很卡，是不是和软件有关

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-windows#2483]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

![图片](https://user-images.githubusercontent.com/48443653/61641182-422e8c80-acd1-11e9-97c8-0a712da9ba34.png)

**Comment by chenshaoju** [comment]
Ping延迟有多少？丢包率如何？
可以使用` ping 123.45.67.89 -n 10 `，检查到你的服务器延迟和丢包情况。
请记得将 123.45.67.89 替换成你的服务器IP。

**Comment by ming1221** [comment]
同样的问题，自从用了最新版本后就这样，延迟和丢包率都正常，就是连接速度上不去

**Comment by chenshaoju** [comment]
请问都正常具体是多少？请执行上面提到的Ping命令，将结果发上来即可。

**Comment by ming1221** [comment]
延迟160左右，丢包10%

**Comment by chenshaoju** [comment]
有点丢包，但是看起来没问题。

如果使用 speedtest.net ，速度如何？

我使用最新版测试了一下我位于英国的服务器，结果如下：
![image](https://user-images.githubusercontent.com/515763/61991667-0b1bfa80-b086-11e9-9180-0958c072c774.png)

**Comment by ming1221** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/45189767/61991755-9a75dd80-b087-11e9-83da-01544b57bd28.jpg)

**Comment by ming1221** [comment]
但最近上油管连接速度特慢

**Comment by ming1221** [comment]
![SharedScreenshot2](https://user-images.githubusercontent.com/45189767/61991802-1a9c4300-b088-11e9-96aa-c2751f0f0009.jpg)

**Comment by ming1221** [comment]
就像这样

**Comment by ming1221** [comment]
我想应该不是软件本身的问题了

**Comment by ming1221** [comment]
用的联通的网，是不是这个原因

**Comment by chenshaoju** [comment]
我测试了一下：
![1](https://user-images.githubusercontent.com/515763/61991944-25f06e00-b08a-11e9-84f6-eb76abae56d1.png)

你这个情况比较复杂，如果你的服务器是自己搭的，建议优化一下网络看看：
https://gist.github.com/chenshaoju/b0e20f23efabb8eb2cd4

另外，可以考虑尝试套一个插件，伪装成HTTPS或HTTP，跑在443或80，看看能否欺骗服务商的QoS：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by ming1221** [comment]
我的vps走的是电信的CN2 GIA，用联通的网会被Qos对吧

**Comment by chenshaoju** [comment]
不太确定，建议试一下。

**Comment by neutron9** [comment]
我也是升级到4.1.7.1后有时很慢且经常断，换回4.1.6就好多了，回复正常

**Comment by chenshaoju** [comment]
@neutron9 能否提供使用的加密方式？

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
