### ISSUE TITLE
这两天在全局模式的情况下也不能上Pinterest 几天前还是可以的 请问有人知道原因么

### ISSUE THREAD

**Issue by DingEW** [shadowsocks/shadowsocks-windows#2484]

**Comment by DingEW** [comment]
shadowsocksX
我是在搬瓦工自己买的vps 
电脑是Mac的 手机登的上pinterest 电脑登不上
如果有人能告知原因 真的感激不尽 这个网站对我的工作来说很重要

**Comment by chenshaoju** [comment]
请确保你的代理服务器没有被Pinterest屏蔽。

![QQ截图20190723000621](https://user-images.githubusercontent.com/515763/61646719-b7a05a00-acdd-11e9-834a-e0861d4b450f.png)

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
