### ISSUE TITLE
请问如何使用二维码功能将安卓版账号转移到Windows版上

### ISSUE THREAD

**Issue by maxuhang** [shadowsocks/shadowsocks-windows#2487]
当我用Windows版扫描安卓版生成的二维码后，却并没有自动配置。点击剪切版导入ss链接也什么也没有发生。
 我遗忘了我的密码，所以没法用手动的方式配置，也就无法在Windows版本上使用我的账号。

**Comment by chenshaoju** [comment]
好像不能，只能以URI方式传递过来。
Android： 分享-到出至剪切板
通过某种方式，如保存为文本文件再复制到电脑上，或者微信文件传输助理（不推荐）等。
Windows：右击任务栏托盘区的SS小图标，指向服务器，再点击从剪切板导入URI。

**Comment by maxuhang** [comment]
解决了。windows版是ssr。。下载ss后链接配置成功。
