### ISSUE TITLE
升级4.1.7.1新版本后出现了一些问题

### ISSUE THREAD

**Issue by vowor** [shadowsocks/shadowsocks-windows#2488]
没有升级之前使用全局代理只有微信不能接收发送文件和接收发送图片，升级之后QQ和微信都出现了这个情况，回退带4.1.6版本之后QQ就正常了，说明一下，我的网络是公司网，不用全局代理的话不能登录QQ和微信

**Comment by chenshaoju** [comment]
能否做个测试，如果手动配置代理，是否就可以了？

![image](https://user-images.githubusercontent.com/515763/61760591-a438e000-adfe-11e9-92d2-ea66e889312e.png)

**Comment by vowor** [comment]
这个必须设置的   不设置这个  我微信都登录不上去   QQ也设置了代理   不然也被公司路由拦截了

**Comment by vowor** [comment]
设置了代理的情况下    微信和QQ都可以正常登录和收发消息，但是不能收发文件和图片，4.1.6版本的QQ可以收发文件和图片，微信不能，4.1.7.1（4.1.7没用过不知道）QQ和微信都不能收发文件和图片，只能收发消息

**Comment by chenshaoju** [comment]
我测试了一下全局模式的代理功能，没有问题。

如果不设置代理，是否能用QQ和微信（或者默认的系统代理）？

![image](https://user-images.githubusercontent.com/515763/61761807-6b026f00-ae02-11e9-9587-2d6d6bb7dbbb.png)

**Comment by vowor** [comment]
网络设置   设置为  不适用代理    QQ  和  微信都不能登录   被公司的路由器策略  屏蔽了 ，   设置  使用浏览器设置和手动设置  127.0.0.1   1080    可以登录  QQ和微信  收发消息   但是    4.1.7.1  不能收发文件和图片（4.1.6微信也不能收发文件，QQ可以）

**Comment by imba-tjd** [comment]
你用的是win7吗，如果是的话可以考虑试一下自己build最新的版本。如果不是就算了

**Comment by vowor** [comment]
window 10  专业版  买的激活码

**Comment by chenshaoju** [comment]
不太确定问题，我这儿Win10全区代理，IE/Chrome/Edge都没问题。

请尝试一下这个版本：
https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/job/nian3mn3m51gy4qt/artifacts

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
