### ISSUE TITLE
客户端的全局代理，只有浏览器WEB生效，但是其他的软件连接为什么没有走代理？是还需要什么设置吗？

### ISSUE THREAD

**Issue by yorkyu** [shadowsocks/shadowsocks-windows#2489]
客户端的全局代理，只有浏览器WEB生效，但是其他的软件连接为什么没有走代理？是还需要什么设置吗？

**Comment by yorkyu** [comment]
用Proxifier结合用。要是能合并成一个软件就好了。

**Comment by chenshaoju** [comment]
如果你的软件本身不支持从系统读取代理并应用的话，那么是没有办法支持的。

SS的全局代理功能依赖软件本身的代理支持。

**Comment by yorkyu** [comment]
> 如果你的软件本身不支持从系统读取代理并应用的话，那么是没有办法支持的。
> 
> SS的全局代理功能依赖软件本身的代理支持。

谢谢回复。只能用Proxifier结合来用了。不过不知道有什么更好的开源类似软件。

**Comment by imba-tjd** [comment]
你可以用SSTap或者Outline

**Comment by yorkyu** [comment]
> 你可以用SSTap或者Outline

谢谢

**Comment by lssmoon2019** [comment]
除非软件本身支持代理设置。有的话选中“”使用系统代理“”

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
