### ISSUE TITLE
win10 ss_polipo.exe 存在一定概率 崩溃

### ISSUE THREAD

**Issue by uniquepengpeng** [shadowsocks/shadowsocks-windows#249]
win10024,64,ss(2.5.1)
碰到过几次ss_polipo.exe  崩溃
windows 错误日志如下:

错误应用程序名称: ss_polipo.exe，版本: 0.0.0.0，时间戳: 0x548d68ee
错误模块名称: ss_polipo.exe，版本: 0.0.0.0，时间戳: 0x548d68ee
异常代码: 0xc0000005
错误偏移量: 0x0000ca6b
错误进程 ID: 0x1f1c
错误应用程序启动时间: 0x01d0cb9e52f15d24
错误应用程序路径: C:\Users\pengpeng\AppData\Local\Temp\ss_polipo.exe
错误模块路径: C:\Users\pengpeng\AppData\Local\Temp\ss_polipo.exe
报告 ID: 493d5979-1438-4c36-be36-413f1829ee8e
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by nochater** [comment]
没错，我也经常遇到。WIN10

**Comment by clowwindy** [comment]
因为我没有遇到，需要遇到的人找出崩溃的条件。

**Comment by dawnchen** [comment]
windows 8.1， shadowsocks 2.5.1，启用系统代理，全局模式，用IE从MSDN直接下载VS2015 ISO，貌似两次都是接近2GB的时候就报此错误，下载中断。

日志名称:          Application
来源:            Application Error
日期:            2015/8/3 15:11:37
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           dawn-thinkpad
描述:
错误应用程序名称: ss_polipo.exe，版本: 0.0.0.0，时间戳: 0x548d68ee
错误模块名称: ss_polipo.exe，版本: 0.0.0.0，时间戳: 0x548d68ee
异常代码: 0x40000015
错误偏移量: 0x00002d9a
错误进程 ID: 0x31dc
错误应用程序启动时间: 0x01d0cdb16e896b9d
错误应用程序路径: C:\Users\Dawn\AppData\Local\Temp\ss_polipo.exe
错误模块路径: C:\Users\Dawn\AppData\Local\Temp\ss_polipo.exe
报告 ID: e09bb47d-39ae-11e5-82db-28d244f2cf27

**Comment by clowwindy** [comment]
可以尝试下载不同版本的 polipo，在 Shadowsocks 启动前手动启动它们，并无视 Shadowsocks 启动时提示 polipo 端口被占用，无法启动的错误。
http://www.pps.univ-paris-diderot.fr/~jch/software/files/polipo/

polipo 的配置文件，下面 1080 为你填的本地端口：
```
proxyAddress = "127.0.0.1"
proxyPort = 8123

socksParentProxy = "127.0.0.1:1080"
socksProxyType = socks5
diskCacheRoot = ""
localDocumentRoot = ""

allowedPorts = 1-65535
tunnelAllowedPorts = 1-65535
```

然后看看这些版本的 polipo 有没有问题。

**Comment by azraelrabbit** [comment]
这个问题遇到很多次,每次都是下载超过2Gb的档案, 每次都是刚刚好下载到 2G的时候,ss_polipo 就崩溃了..
目测是 ss_polipo 有内存泄漏造成的,ss_polipo又是32位应用程序,当缓存数据超过2Gb,就会崩溃.
可否考虑修改ss_polipo或者换个替代的?

**Comment by clowwindy** [comment]
@azraelrabbit 多谢指出，已经重现，将在下一版本中修正。

**Comment by clowwindy** [comment]
2.5.3 改为 Privoxy。
