### ISSUE TITLE
求教win7无法正常运行

### ISSUE THREAD

**Issue by miaomiaomiao34** [shadowsocks/shadowsocks-windows#2490]
源
Shadowsocks

摘要
已停止工作

日期
‎2019/‎7/‎24 15:09

状态
已发送报告

描述
错误的应用程序路径:	D:\Shadowsocks.exe

问题签名
问题事件名称:	APPCRASH
应用程序名:	Shadowsocks.exe
应用程序版本:	4.1.7.1
应用程序时间戳:	5d2b1b0b
故障模块名称:	KERNELBASE.dll
故障模块版本:	6.1.7601.24384
故障模块时间戳:	5c6e2226
异常代码:	e0434352
异常偏移:	0000c5af
OS 版本:	6.1.7601.2.1.0.256.1
区域设置 ID:	2052
其他信息 1:	0a9e
其他信息 2:	0a9e372d3b4ad19135b953a78882e789
其他信息 3:	0a9e
其他信息 4:	0a9e372d3b4ad19135b953a78882e789

关于该问题的额外信息
存储段 ID:	4157278935

**Comment by chenshaoju** [comment]
请确保已经安装了最新的 .NET Framework https://dotnet.microsoft.com/download/thank-you/net48

另外，我不太确定你的D盘根目录是否有写入权限，请尝试建立一个新目录，如 D:\SS\ 然后再把 Shadowsocks.exe 放进去看看。

**Comment by miaomiaomiao34** [comment]
多谢
