### ISSUE TITLE
shadowsocks在不使用的情况下有不小的网络流量开支

### ISSUE THREAD

**Issue by rhuang-astro** [shadowsocks/shadowsocks-windows#2491]
shadowsocks在浏览器关闭，系统代理为禁用的情况时，我任务管理器中能持续观察到有至少 2Mbps 左右的上行下行流量。 我在学校上网需要客户端登录，等我取消登陆后，，不能访问校外网络，流量变成 0.1Mbps。 所以我觉得能理解成一直有通往非局域网的流量。 我对这个现象不太安心。 请问有什么解释吗？
BTW， 最近我上网流量飙升(学校按照流量计费)，不知道是不是和这个有关。

**Comment by chenshaoju** [comment]
请确保没有启用”允许其他设备连入“的选项。

**Comment by rhuang-astro** [comment]
确实是这样， 谢谢！
