### ISSUE TITLE
window10 上不了，手机可以上。Google 报500 Internal Privoxy Error

### ISSUE THREAD

**Issue by grey5900** [shadowsocks/shadowsocks-windows#2492]
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   在 System.Net.TlsStream.CallProcessAuthentication(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   在 System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   在 System.Net.TlsStream.UnsafeBeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   在 System.Net.PooledStream.UnsafeBeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   在 System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
能使用的手机和电脑在同一个局域网吗？

**Comment by grey5900** [comment]
@chenshaoju 在同一局域网。手机可以。

**Comment by grey5900** [comment]
[2019-07-25 14:27:49] Socket connected to ss server: 112.47.15.161:35541
[2019-07-25 14:27:49] connect to www.youtube.com:443

又是可以的。但是chrome 就是访问不上。  @chenshaoju

**Comment by chenshaoju** [comment]
我不太明白你的最后一句话，你的意思是指电脑上用IE没问题，但是chrome不行吗？

**Comment by grey5900** [comment]
@chenshaoju 都不行。window 10 上任何浏览器都不行。

**Comment by grey5900** [comment]
搞了一天发现是自己电脑防火墙问题。谢谢。@chenshaoju

**Comment by opticaloptical** [comment]
请问改防火墙哪里？我关了360和windows防火墙都不成。

**Comment by chenshaoju** [comment]
你手机上有SS吗？如果有，手机上能用吗？这个需要测试一下你的服务器是否还能通。

请尝试Ping你的服务器，是否能通？

**Comment by opticaloptical** [comment]
手机上按了一个，用此app上的测试功能，能够显示有上下通信；但是用浏览器访问谷歌，还是不成。

**Comment by chenshaoju** [comment]
手机上测试的话，提示连接成功吗？

**Comment by opticaloptical** [comment]
对的，这个有。
另，我截屏的图怎么老不让贴上。

**Comment by opticaloptical** [comment]
问了vultr客服，说跟他们没关系，是local region的事情，是不是墙的技术升级了。

**Comment by chenshaoju** [comment]
如果手机和电脑在同一个局域网中，手机可以，电脑不可以的话，通常是由于你的配置错误导致的，请仔细检查你的配置情况。

另外，就是操作系统自带的网络防火墙（同题主）。
