### ISSUE TITLE
连接办公楼网络SS就用不了,自己开手机热点就可以用,还有救么

### ISSUE THREAD

**Issue by zelute** [shadowsocks/shadowsocks-windows#2494]
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-07-26 16:41:54] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2019-07-26 16:42:06] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
[2019-07-26 16:43:43] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)

**Comment by chenshaoju** [comment]
请尝试分别使用办公网络和4G网络Ping你的服务器IP，能通吗？格式为：`ping 123.45.67.89`，将 123.45.67.89 替换成你的服务器IP地址。

**Comment by zelute** [comment]
> 请尝试分别使用办公网络和4G网络Ping你的服务器IP，能通吗？格式为：`ping 123.45.67.89`，将 123.45.67.89 替换成你的服务器IP地址。

PING是都可以PING通的.

4G网络一切良好正常使用,我的VPS上同时搭建了WORDPRESS,4G网络不开SS也可以访问我自己的WP
办公网络也可以正常访问我的WP,但是SS就是一直报错,期间换过端口,加密协议和密码,都没有作用.

我笔记本的WIFI只要从办公WIFI切换到手机热点,瞬间就可以访问谷歌,换回来立刻就不行了,有线网络也是一样.

**Comment by chenshaoju** [comment]
我怀疑你的公司可能有网络防火墙进行了屏蔽。

如果可能，请尝试做一个测试，暂时停止你服务器上的WebServer，然后将SS修改为80端口看看？

**Comment by zelute** [comment]
> 我怀疑你的公司可能有网络防火墙进行了屏蔽。
> 
> 如果可能，请尝试做一个测试，暂时停止你服务器上的WebServer，然后将SS修改为80端口看看？

改用８０端口确实可以使用ＳＳ了，那么现在要怎样做才能正常使用ＳＳ呢？
非常感谢您的帮助！

**Comment by chenshaoju** [comment]
可能你所在的公司有端口封锁。

建议尝试一些常见端口，比如443。

**Comment by zelute** [comment]
> 可能你所在的公司有端口封锁。
> 
> 建议尝试一些常见端口，比如443。

443端口试过了不行。不过端口封锁的话为什么我SSH还是能连上呢，29516端口

**Comment by chenshaoju** [comment]
不知道，可能你得问一下你们公司的网管了。

**Comment by zelute** [comment]
> 不知道，可能你得问一下你们公司的网管了。

SS改用了8080，目前看是可行的，感谢您的帮助
