### ISSUE TITLE
4.1.7和4.1.7.1版本退出后不会恢复win 10系统的proxy设置

### ISSUE THREAD

**Issue by cbank8** [shadowsocks/shadowsocks-windows#2495]
4.1.7和4.1.7.1版本退出后不会恢复win 10系统的proxy设置，IE还是将127.0.0.1作为proxy，因此每次都需要手动改掉。之前的版本在quit之后会自动恢复IE的代理设置

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/2040#issuecomment-429540937

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
