### ISSUE TITLE
请问如何通过22端口连接shadowsocks 就像是Navicat 的ssh那样使用

### ISSUE THREAD

**Issue by freeaswind** [shadowsocks/shadowsocks-windows#2498]
当前的服务器直接ip连接不太稳定    服务商开放的加速域名只开放了22端口  好尴尬

**Comment by chenshaoju** [comment]
目前Shadowsocks没有伪装成SSH的插件。

但是，你可以通过SSH的Socks代理来代理Shadowsocks，由于连接受限，可能会很卡。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
