### ISSUE TITLE
windows 10开启程序弹出ss_polipo.exe窗口

### ISSUE THREAD

**Issue by magicdmer** [shadowsocks/shadowsocks-windows#250]
就是每次打开ss的时候都会弹出一个命令行程序ss_polipo.exe,然后一直显示，不退出
C:\Users\magicdmer\AppData\Local\Temp\/polipo.conf:6: unknown config variable diskCacheRoot
C:\Users\magicdmer\AppData\Local\Temp\/polipo.conf:7: unknown config variable localDocumentRoot
Established listening socket on port 8123.
上面是显示的内容，手工关闭就好了，不影响使用，我的是专业版

**Comment by chenshaoju** [comment]
１.打开任何浏览器，是否能上网。
２.检查你的DNS设置是否正确。
３.检查填写的域名是否正确。
４.尝试获得服务器的IP地址作为连接。

**Comment by clowwindy** [comment]
服务器 IP 一栏应该填 IP。

**Comment by magicdmer** [comment]
这个放心，这些低级错误我不是不会犯的，我在win10之外的系统都配置过shadowsocks。我确定我填写的都没问题，不同系统都是使用的相同的配置。而且刚才又试了一次，出现了新的问题，版本是donet版。我双击打开，会弹出cmd框框，是ss_polipo.exe命令行程序。 上面显示：
polipo.conf:6: unknown conifg variable diskcacheroot
polipo.conf:6: unknown conifg variable localdocumentroot
establelished listening socket on port 8132.
Couldn't write to server: Unknown error
Couldn't read from client: Unknown error

**Comment by magicdmer** [comment]
试了一下发现是dns的问题，无法解析我输入的域名。但是出来了一个新问题，那就是每次打开ss的时候都会弹出一个命令行程序ss_polipo.exe,然后一直显示，不退出
C:\Users\magicdmer\AppData\Local\Temp\/polipo.conf:6: unknown config variable diskCacheRoot
C:\Users\magicdmer\AppData\Local\Temp\/polipo.conf:7: unknown config variable localDocumentRoot
Established listening socket on port 8123.
上面是显示的内容

**Comment by torinkan** [comment]
我服务器ip填的就是 ip，但是也是报错，不知道的主机
Ps 手机用的正常

**Comment by zhongjingwei** [comment]
Win 10里边Shadowsocks速度有点慢，不知道是不是浏览器原因，反正没在Win 8.1下用的舒服

**Comment by clowwindy** [comment]
因为我没有遇到，需要遇到的人找出崩溃的条件。

**Comment by xiuluo** [comment]
我Windows 10 64位企业版，使用v2.5.1正常

**Comment by celeron533** [comment]
Windows 10 pro 64bit, all good

**Comment by aesean** [comment]
我的Windows 10 X64 PRO 正常

**Comment by magicdmer** [comment]
我的windows 10 专业版 改dns也正常了，就是除了上面那个新问题，那个命令行程序，需要手工关闭，不过不影响使用就是

**Comment by celeron533** [comment]
我当时在平滑升级完win10后发现很多运行库和开发环境都出了很多奇奇怪怪的问题，后来无奈进行系统复位，从头开始。题主可能也是这种情况，可以考虑复位win10

**Comment by clowwindy** [comment]
2.5.3 改为 Privoxy。
