### ISSUE TITLE
在切换代理模式时出现 “非预期错误，Shadowsocks将退出 ”

### ISSUE THREAD

**Issue by cmmdwl** [shadowsocks/shadowsocks-windows#2500]
### Shadowsocks version / 影梭版本
4.7.1.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows10 专业版 版本1803 os内部版本 17134.885 

### Steps you have tried / 操作步骤

切换代理模式到全局时
### What did you see instead? / 实际结果
---------------------------
Shadowsocks UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

Exception Detail: 

System.UnauthorizedAccessException: 对路径“C:\gui-config.json”的访问被拒绝。

   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)

   在 Shadowsocks.Model.Configuration.Save(Configuration config)

   在 Shadowsocks.Controller.ShadowsocksController.ToggleEnable(Boolean enabled)

   在 Shadowsocks.View.MenuViewController.EnableItem_Click(Object sender, EventArgs e)

   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)

   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()

   在 System.Windows.Forms.Command.Invoke()

   在 System.Windows.Forms.Command.DispatchID(Int32 id)

   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)

   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)

   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
确定   
---------------------------

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
{
  "version": "4.1.7.1",
  "configs": [
    {
      "server": "***********",
      "server_port": ***********,
      "password": "************",
      "method": "chacha20-ietf-poly1305",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "isIPv6Enabled": false,
  "localPort": 1080,
  "portableMode": true,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}

**Comment by cmmdwl** [comment]
Shadowsocks 直接放在c:\

**Comment by chenshaoju** [comment]
默认情况，C盘根目录没有写入权限，除非以管理员身份运行。

请尝试建立一个新的目录，如 C:\SS\ 或 D:\SS\ ，将 Shadowsocks.exe 放进去，然后再试。

关于在这种情况下退出SS后浏览器不工作的问题：https://github.com/shadowsocks/shadowsocks-windows/issues/2040#issuecomment-429540937

**Comment by cmmdwl** [comment]
修正了目录问题并将其放入了c:\ss 
同样的报错
---------------------------
Shadowsocks UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

Exception Detail: 

System.UnauthorizedAccessException: 对路径“C:\ss\gui-config.json”的访问被拒绝。

   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)

   在 Shadowsocks.Model.Configuration.Save(Configuration config)

   在 Shadowsocks.Controller.ShadowsocksController.ToggleEnable(Boolean enabled)

   在 Shadowsocks.View.MenuViewController.EnableItem_Click(Object sender, EventArgs e)

   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)

   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()

   在 System.Windows.Forms.Command.Invoke()

   在 System.Windows.Forms.Command.DispatchID(Int32 id)

   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)

   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)

   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
确定   
---------------------------

**Comment by chenshaoju** [comment]
请尝试检查 gui-config.json 是否被设置为只读了？

如果可能，请单独将 Shadowsocks.exe 放到桌面上一个新建的文件夹中（不要把其他文件也复制过来了），然后重新配置一次看看？

**Comment by cmmdwl** [comment]
gui-config.json并非只读
将Shadowsocks.exe放入桌面一个文件夹内不在出现此错误，可是为啥会出现不能安装在系统盘？

**Comment by chenshaoju** [comment]
感觉还是权限问题，可能你新建的哪个目录需要额外赋权，给予你自己的Windows账号完全访问权限。

**Comment by cmmdwl** [comment]
行吧，估计是win10权限问题
