### ISSUE TITLE
允许来自局域网的连接

### ISSUE THREAD

**Issue by blackcat003** [shadowsocks/shadowsocks-windows#2501]
### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

windows 7
### Steps you have tried / 操作步骤

我本来好好的，不小心点了一下这个“允许来自局域网的连接”然后就连不上ss了，ip一直是自己的ip，一直都连不上了，不管我重新下载，还是从别的电脑拷贝一个配置过来，也不行。
### What did you expect to see? / 期望的结果

我想恢复连接ss
### What did you see instead? / 实际结果

ss不能使用了

**Comment by chenshaoju** [comment]
这个应该和该选项无关，可能是凑巧你用的服务器出问题或者被墙了。

请尝试Ping你的服务器，能通吗？可以按下 Win+R ，在运行里输入：
`ping 123.45.67.89 -t`

请记得将 123.45.67.89 替换成你的服务器的IP地址。

**Comment by blackcat003** [comment]
不是的，我点击这个“允许来自局域网的连接”之前还是能用的，然后我不小心点了一下之后就用不了

**Comment by blackcat003** [comment]
版本2.5.6
4.0.4都是这样

**Comment by chenshaoju** [comment]
再说一次，这个和SS本身没关系，你尝试解决问题的方向就不对。

能否先测试一下能否Ping通？

**Comment by blackcat003** [comment]
我是在https://www.wcbab.net 购买的服务，没有ip

**Comment by chenshaoju** [comment]
Ping域名呢？

另外，Shadowsocks的日志中有显示什么吗？

**Comment by blackcat003** [comment]
我用另外一个软件sstap是能连接的，而且我在点击“允许来自局域网的连接”之前，也是能连上的。我跟你说过了啊，不是服务器的问题，我用另外一个软件已经连上了，愉快的上网了

**Comment by blackcat003** [comment]
我不知道为什么，我点了一下这个“允许来自局域网的连接”之后，哪怕我取消掉这个选项，也再也连不上我的ss服务器了，我遇到的问题就是这样。

**Comment by blackcat003** [comment]
日志最奇怪了，什么也没显示，我点击连接，他就显示started

**Comment by blackcat003** [comment]
我折腾了一个早上了，最后是用sstap解决了，不过还是谢谢你。
