### ISSUE TITLE
在目录C:\Program Files\下开机自动启动的问题

### ISSUE THREAD

**Issue by virgilchiou** [shadowsocks/shadowsocks-windows#2502]
系统版本为 Windows 10 Pro x64，超级管理员用户。

程序置放在C:\Program Files\目录下，程序内勾选了开机自动启动，程序设置中已勾选了已管理员身份运行。但开机并未自动启动该应用程序。

请问如果在**不更换**程序所处路径(C:\Program Files\)的情况下，如何实现开机自动启动？

**Comment by chenshaoju** [comment]
请右击 Shadowsocks.exe ，选择以管理员身份运行。

**Comment by virgilchiou** [comment]
> 请右击 Shadowsocks.exe ，选择以管理员身份运行。

已经在兼容性设置里勾选了以管理员身份运行，但仍然无法实现开机启动。

**Comment by chenshaoju** [comment]
你电脑里是否有运行某些安全软件，比如360、QQ电脑管家之类的？

可能此类软件会阻止应用设置为开机启动。

**Comment by virgilchiou** [comment]
> 你电脑里是否有运行某些安全软件，比如360、QQ电脑管家之类的？
> 
> 可能此类软件会阻止应用设置为开机启动。

感谢您迅速的答复！但是我的电脑中并未安装上述及类似的程序，系统也是前些天重装的MSDN的原版。

**Comment by chenshaoju** [comment]
这里有一些奇怪的现象，我暂时无法复现，如果很着急，请尝试创建快捷方式，并拖入开始菜单中的启动目录中即可。

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
