### ISSUE TITLE
开启本地ipv6后PAC更新仍使用127.0.0.1

### ISSUE THREAD

**Issue by klaaktu** [shadowsocks/shadowsocks-windows#2504]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 x64

### Steps you have tried / 操作步骤
gui-config.json 中 "isIpv6Enabled" `false` 改为 `true`

### What did you expect to see? / 期望的结果
Shadowsocks: Updated PAC file successfully. / No updates found.

### What did you see instead? / 实际结果
Failed to update PAC
启用 isIpv6Enabled 后，更新 PAC 时 SS 仍尝试连接本地 ipv4 地址
"isIpv6Enabled" 改回 `false` 可正常更新
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
> An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:1081

**Comment by chenshaoju** [comment]
1.你是否启用了正向代理？如果你上网不需要经过代理，请禁用看看。
![image](https://user-images.githubusercontent.com/515763/62842251-66372980-bce3-11e9-81f3-16b6910f8a10.png)

2.请尝试在编辑服务器界面右下角的代理端口中换一个端口看看，比如 10800 。

**Comment by klaaktu** [comment]
@chenshaoju 额... 确定不是 SS 的问题?
启用 isIpv6Enabled SS 只监听 ipv6 , PAC 更新却仍尝试 ipv4

**Comment by chenshaoju** [comment]
从源码来看，是从 localhost 进行连接的：
https://github.com/shadowsocks/shadowsocks-windows/blob/fdd068c414feae957ea6cf622d985ef5eef1eccf/shadowsocks-csharp/Controller/Service/GfwListUpdater.cs#L94

我想知道为什么更新PAC一定要走IPv6……？你用的不是GFWList？

**Comment by klaaktu** [comment]
因为更新 GFWList 也走代理
https://github.com/shadowsocks/shadowsocks-windows/pull/2419
> 纯IPv6，启用后不再监听IPv4
你能试下是否有相同问题吗? 我的两个 PC 独立设置，但都有这个问题，没有正向代理但有混淆插件

**Comment by chenshaoju** [comment]
是的。

具体情况请等待开发人员回复，欢迎提交 pull reuqests 。

**Comment by klaaktu** [comment]
thx f38205a8f82e6ad308697bdd34994db9d4012a44
