### ISSUE TITLE
第二次提问了额，这是什么征兆

### ISSUE THREAD

**Issue by 2427237507** [shadowsocks/shadowsocks-windows#2505]
只要一用SS访问谷歌，这边TCPing立马就不行了
Port is open - time=67.778ms
Port is open - time=69.252ms
Port is open - time=1097.087ms
No response - time=2000.559ms //开始访问谷歌，页面加载不出来
No response - time=2001.031ms
No response - time=2001.089ms
Port is open - time=108.943ms //停止访问谷歌，恢复
时好时坏，不知道是否被干扰或本机有什么软件上报IP？

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2503#issuecomment-520234512

**Comment by 2427237507** [comment]
好的，我试一下

**Comment by 2427237507** [comment]
原因找出来了，装插件没用，是本机系统问题.......
