### ISSUE TITLE
win7 下同样配置 4.1.6运行正常 ，4.1.7日志（由于远程方已关闭传输流，身份验证失败），原因是密码配置错误，重新下载 4.1.6参考4.1.7服务器配置的时候发现 

### ISSUE THREAD

**Issue by asvinvincent** [shadowsocks/shadowsocks-windows#2506]
### [2019-08-14 13:36:56] Socket connected to ss server: ip:port
[2019-08-14 13:36:56] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请检查防火墙：https://github.com/shadowsocks/shadowsocks-windows/issues/2492#issuecomment-514963710
