### ISSUE TITLE
南京电信开启代理后不起作用

### ISSUE THREAD

**Issue by muchuanhao** [shadowsocks/shadowsocks-windows#2507]
### Shadowsocks version /
 影梭版本 4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
操作系统win10

### Steps you have tried / 操作步骤
同一个vps，手机端就可以使用（两张卡电信，联通均可以），公司宽带是电信（南京）就不行，手机连公司无线网之后也不行了，找了朋友试了一下常州电信也是可以的，（在公司网下还可以登录vps，ping也没问题）

**Comment by chenshaoju** [comment]
可能你所在的网络存在封锁（因为有问题的网络手机WiFi也不行）。

请尝试联系网管开通端口，或者试一下常见端口，如443、80等。

**Comment by muchuanhao** [comment]
> 可能你所在的网络存在封锁（因为有问题的网络手机WiFi也不行）。
> 
> 请尝试联系网管开通端口，或者试一下常见端口，如443、80等。

谢谢回复，我又试了一下，应该是公司的网络问题，把端口换成80的就可以了，443也不行
