### ISSUE TITLE
同一局域网，其他电脑能连上，本机却连不上

### ISSUE THREAD

**Issue by svenjia** [shadowsocks/shadowsocks-windows#2509]
### Shadowsocks version / 影梭版本
4.1.7

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win 10 

### Steps you have tried / 操作步骤
其他电脑能连上，可以正常上Google，本机却上不了，查看日志，没有进站和出站的流量，之前用过坚果VPN，是不是我电脑的什么设置被串改了，防火墙我也关了

**Comment by svenjia** [comment]
请大佬们指点一下，真是头疼，不会让我重装系统吧

**Comment by chenshaoju** [comment]
请尝试右击任务栏托盘区的纸飞机图标，指向系统代理，再选择PAC模式。

然后再次右击，指向PAC，然后点击”从GFWList更新本地PAC“。

更新完毕后再试，如果提示错误，请将日志发送上来。
