### ISSUE TITLE
Save & restore system default proxy

### ISSUE THREAD

**Issue by celeron533** [shadowsocks/shadowsocks-windows#251]
When untick [Enable System Proxy], Shadowsocks will clear current proxy settings. Is it possible to save original proxy settings before enable Shadowsocks proxy and then restore the original settings when disable shadowsocks proxy?

**Comment by li3shiyi** [comment]
#257 is not perfect, but will not clear ProxyServer when PAC mod On.

**Comment by celeron533** [comment]
Duplicated to #257
