### ISSUE TITLE
win 7系统无法使用  提示非预期错误

### ISSUE THREAD

**Issue by a983859654** [shadowsocks/shadowsocks-windows#2510]
# Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7 64位  操作环境重新安装过

### Steps you have tried / 操作步骤
按照步骤进行操作

### What did you expect to see? / 期望的结果
正常使用

### What did you see instead? / 实际结果
无法使用

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![image](https://user-images.githubusercontent.com/54138290/63087533-0495ea00-bf85-11e9-9016-7bdfef591b73.png)

提示如图  求解

**Comment by a983859654** [comment]
无法运行  点击确定后提示停止工作

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2226

**Comment by chenshaoju** [comment]
由于太久没有回复，此Issue已关闭。
