### ISSUE TITLE
无法下载新版本怎么解决

### ISSUE THREAD

**Issue by x101x** [shadowsocks/shadowsocks-windows#2512]

**Comment by chenshaoju** [comment]
你可以在 https://github.com/shadowsocks/shadowsocks-windows/releases 下载。

**Comment by x101x** [comment]
下不下来 一直显示网络错误

**Comment by chenshaoju** [comment]
如果你是自己搭的服务器，你可以在服务器上使用 wget 命令下载到服务器上：
`wget https://github.com/shadowsocks/shadowsocks-windows/releases/download/4.1.7.1/Shadowsocks-4.1.7.1.zip`
然后再用SSH（SFTP）客户端下载到你的电脑上。

如果你是找服务商（机场）购买的，请与你的服务商联系以获取客户端。
