### ISSUE TITLE
PAC模式访问不了google,全局模式上不了网

### ISSUE THREAD

**Issue by HunterUUU** [shadowsocks/shadowsocks-windows#2515]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
服务端 centos7.4  客户端 windows

### Steps you have tried / 操作步骤
服务端安装并开启端口,客户端配置端口密码,PAC代理

### What did you expect to see? / 期望的结果
访问google

### What did you see instead? / 实际结果
![image](https://user-images.githubusercontent.com/38918146/63277420-dfccaa00-c2d7-11e9-8e3d-c00756f84470.png)
只有出站流量,没有入站

**Comment by HunterUUU** [comment]
在我关闭正向代理之后可以正常访问google了,请问下为什么开启正向代理会疯狂走出站的数据?我对这个不是很了解

**Comment by chenshaoju** [comment]
正向代理的目的是，当你处于特定需要通过代理才能上网的网络下，才需要配置该功能。

如果你不需要通过代理上网，则无需配置该功能。

**Comment by edica02** [comment]
> 在我关闭正向代理之后可以正常访问google了,请问下为什么开启正向代理会疯狂走出站的数据?我对这个不是很了解

不了解，但总是解决问题了。多谢。
