### ISSUE TITLE
当前最新版 看youtube时候出现了卡顿，中断的问题，日志如下

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-windows#2516]
![图片](https://user-images.githubusercontent.com/48443653/63435111-ea627d00-c458-11e9-8642-d56ad6ff53f4.png)

**Comment by chenshaoju** [comment]
你的日志没截全，“有关”后面还有东西，能否直接把这行内容复制出来？

**Comment by lssmoon2019** [comment]
> 
> 
> 你的日志没截全，“有关”后面还有东西，能否直接把这行内容复制出来？

已经重新上传图片

**Comment by chenshaoju** [comment]
`未能创建 SSL/TLS 安全通道`这个问题已知，只是影响到检查更新，不会影响到使用。

请尝试Ping你的服务器，丢包吗？延迟多少？ 可使用 `ping xxx.xxx.xxx.xxx -n 20` 命令进行测试。

如果不丢包，延迟也不高（300ms或以下），且你的服务器是你自己搭建的话，请尝试套一个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

如果丢包率在 5% 或以上，延迟也超过300ms，建议换一个地区的服务器试试。
