### ISSUE TITLE
挂起ss后网页无法访问，提示为：‘不安全的链接’ 或出现 ‘无网络连接’

### ISSUE THREAD

**Issue by WinstonLiu419** [shadowsocks/shadowsocks-windows#2517]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10 NET4.7 

### Steps you have tried / 操作步骤
曾照原   #1679   libsscrypto1-1.dll 问题尝试安装 NET4.8 但失败，也被告知已有c++2017 无需再安装 C++2015 （x86）
尝试运行 C++2017 修复

### What did you expect to see? / 期望的结果
希望能解决问题

### What did you see instead? / 实际结果
无任何变化，仍旧有同样的报错

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
System.TypeInitializationException: “Shadowsocks.Encryption.EncryptorFactory”的类型初始值设定项引发异常。 ---> System.TypeInitializationException: “Shadowsocks.Encryption.Sodium”的类型初始值设定项引发异常。 ---> System.DllNotFoundException: 无法加载 DLL“libsscrypto.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.Sodium.sodium_init()
   在 Shadowsocks.Encryption.Sodium..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Encryption.Sodium.get_AES256GCMAvailable()
   在 Shadowsocks.Encryption.EncryptorFactory..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Encryption.EncryptorFactory.DumpRegisteredEncryptor()
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()

**Comment by chenshaoju** [comment]
这个问题意味着 libsscrypto.dll 加载失败。

如果可能，请尝试安装一下VC Runtime 2015看看？ https://www.microsoft.com/zh-CN/download/details.aspx?id=53587

**Comment by WinstonLiu419** [comment]
> 
> 
> 这个问题意味着 libsscrypto.dll 加载失败。
> 
> 如果可能，请尝试安装一下VC Runtime 2015看看？ https://www.microsoft.com/zh-CN/download/details.aspx?id=53587

卸载 runtime 2017 后尝试安装 2015 均成功安装 仍然为相同报错

**Comment by chenshaoju** [comment]
如果你有某些安全软件，请暂时退出看看。

另外，如果可能，请单独将 Shadowsocks.exe 放到一个新的目录中，比如 D:\SS\ ，然后后再试。

已知某些情况下路径中有非英文的文字可能会出现问题。

**Comment by WinstonLiu419** [comment]
> 
> 
> 如果你有某些安全软件，请暂时退出看看。
> 
> 另外，如果可能，请单独将 Shadowsocks.exe 放到一个新的目录中，比如 D:\SS\ ，然后后再试。
> 
> 已知某些情况下路径中有非英文的文字可能会出现问题。

处理路径后软件正常，不确定是否需要重新安装 vc2017 [https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads](url)

**Comment by chenshaoju** [comment]
可以装的，2017接替了2015。

**Comment by WinstonLiu419** [comment]
> 
> 
> 可以装的，2017接替了2015。

感谢，close issue
