### ISSUE TITLE
Running SS-Windows with service WinHTTP Web Proxy Auto-Discovery Service disabled?

### ISSUE THREAD

**Issue by loxia01** [shadowsocks/shadowsocks-windows#2518]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1903

### Steps you have tried / 操作步骤
Running ShadowsSocks-Windows with service WinHTTP Web Proxy Auto-Discovery Service disabled AND System Proxy disabled.

### What did you expect to see? / 期望的结果
No error messages.

### What did you see instead? / 实际结果
Error message to click through at startup. But ShadowSocks is working fine. Is there a way to disable those error messages? I do not want to enable WinHTTP Web Proxy Auto-Discovery Service due to WPAD security concerns. ShadowSocks seems to work fine without the service  enabled. I just dont want to see that error message at startup. 

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-08-20 21:00:00] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

**Comment by chenshaoju** [comment]
If "WinHTTP Web Proxy Auto-Discovery Service" disabled, The System proxy may unable to set.

You still can use a browser plugin like SwitchOmega to use the proxy or direct set proxy in browser.

The error message may can optimizer, like add a "never show up again" checkbox. @celeron533

**Comment by loxia01** [comment]
> 
> 
> If "WinHTTP Web Proxy Auto-Discovery Service" disabled, The System proxy may unable to set.
> 
> You still can use a browser plugin like SwitchOmega to use the proxy or direct set proxy in browser.
> 
> The error message may can optimizer, like add a "never show up again" checkbox. @celeron533

Would be great to be able to disable the error massage!

**Comment by User486375** [comment]
Is there any ETA on this fix? Especially considering you still get the warning even when System Proxy is disabled, which is pretty redundant.

**Comment by loxia01** [comment]
Do you plan to fix this issue like you say "add a never show up again checkbox" for the warning message? It would be perfect.

**Comment by database64128** [comment]
No plan to do anything as it's not a bug.

**Comment by loxia01** [comment]
Hello,
no it is not a bug but an enhancement.
If you don't want to run the WinHTTP Web Proxy Auto-Discovery Service you are repeatedly getting this warning message. Please reconsider to make this warning maessage removable.


Best regards 
Loxia01


Oct 21, 2020, 12:29 by notifications@github.com:
