### ISSUE TITLE
新手，刚下载，解压后没有可执行程序，怎么启动？

### ISSUE THREAD

**Issue by qhdhjb** [shadowsocks/shadowsocks-windows#2519]
新手，刚下载，解压后没有可执行程序，怎么启动？任务栏右下角也没有小飞机图标！

**Comment by chenshaoju** [comment]
请确保是从 https://github.com/shadowsocks/shadowsocks-windows/releases 下载的。

**Comment by qhdhjb** [comment]
非感谢楼上帮忙，卡的太厉害了，我下的确实是code包，已下正式程序。
