### ISSUE TITLE
paraent proxy support?

### ISSUE THREAD

**Issue by bigbagboom** [shadowsocks/shadowsocks-windows#252]
i have a network enviroment there is no direct access to the internet. shadowsocks windows gui seems no support for accessing internet via another proxy(http/socks). i wonder if you guys can add this feature in the future?

**Comment by clowwindy** [comment]
You can use proxycap or sockscap to set parent proxy.

**Comment by bigbagboom** [comment]
i tried proxycap and sockscap, but they didn't work.

**Comment by clowwindy** [comment]
How they didn't work? Not having the function, or showing an error?
Did you see anything wrong in Shadowsocks log?
