### ISSUE TITLE
（有图）4.1.7.1真的有问题，刚用的4.1.6很流畅，然后用4.1.7.1测试，网页打开突然慢了，卡顿，过了一会儿才好。一看日志，有异常啊。。

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-windows#2520]
上图
![图片](https://user-images.githubusercontent.com/48443653/63520310-1815f780-c527-11e9-9805-5c5715e8b07c.png)

**Comment by lssmoon2019** [comment]
备注：手动搭建，ping 服务器地址，20个，平均延迟234ms,丢包0%

**Comment by chenshaoju** [comment]
该问题已知：https://github.com/shadowsocks/shadowsocks-windows/issues/2471

如果由于强迫症等原因，不愿意看到此错误提示，请启动SS后，右击托盘区图标，指向“帮助”，“更新”，并取消选择“启动时检查更新”。
