### ISSUE TITLE
window 无法使用是什么原因，如图

### ISSUE THREAD

**Issue by ChloeGrey** [shadowsocks/shadowsocks-windows#2522]
![5E5D3913-E5EA-4e65-8690-9D54C11AEF2F](https://user-images.githubusercontent.com/54563436/63734261-1abd7780-c8ae-11e9-8d29-88531de11775.png)

### Shadowsocks version / 影梭版本
4.1.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows7

### Steps you have tried / 操作步骤

解压打开
### What did you expect to see? / 期望的结果

正常运行
### What did you see instead? / 实际结果

如图所示

**Comment by chenshaoju** [comment]
你使用的版本实在太老了，建议使用最新版： https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by ChloeGrey** [comment]
> 你使用的版本实在太老了，建议使用最新版： https://github.com/shadowsocks/shadowsocks-windows/releases

最新版也是这样的报错，所以我就换了一个老版本试试来着

**Comment by rwecho** [comment]
@ChloeGrey  打开系统日志, 应用程序里面看看, error 信息, 把它贴上来比较有意义.

**Comment by ChloeGrey** [comment]
嗯，但是这个图标点了打不开，怎么能打开系统日志呀？原谅我是个小白T_T

**Comment by ChloeGrey** [comment]
> @ChloeGrey 打开系统日志, 应用程序里面看看, error 信息, 把它贴上来比较有意义.

对了，解压之后只有一个飞机图标，其他文件都没有

**Comment by chenshaoju** [comment]
请尝试将最新的压缩包中的 Shadowsocks.exe 解压到一个新目录，比如 D:\SS\ ，然后双击打开。

如果出错，位于 Shadowsocks.exe 所在目录下的 ss_win_temp 目录里，会有一个名为 shadowsocks.log 的文件，上传上来即可。

**Comment by zalen8451** [comment]
遇到同样问题，问题信息如下，大神帮忙解决

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	Shadowsocks.exe
  应用程序版本:	4.1.7.0
  应用程序时间戳:	5d25e00a
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7600.16385
  故障模块时间戳:	4a5bdaae
  异常代码:	e0434352
  异常偏移:	00009617
  OS 版本:	6.1.7600.2.0.0.256.48
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2490

**Comment by noparkinghere** [comment]
3.5 往后的都能用，你这个目测更老的版本。
