### ISSUE TITLE
log文件里面没有连接数据

### ISSUE THREAD

**Issue by DannyVim** [shadowsocks/shadowsocks-windows#2523]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
WIN10 1903

### Steps you have tried / 操作步骤
查看log文件发现里面只有`[2019-08-27 16:39:09] Shadowsocks started (4.1.7.1)`，没有网络连接信息，无法看到流量进出数据

### What did you expect to see? / 期望的结果
希望能看到网络连接的具体信息：直连，或是连接代理了

### What did you see instead? / 实际结果
没有log信息写入

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
请确保选中了系统代理模式下的PAC模式，如果仍然没有反应，请尝试点击PAC菜单下的“从GFWList更新本地PAC”选项。

**Comment by DannyVim** [comment]
1. 是的，我可以确定；
2. 尝试过，但并没有改善；
3. 尝试过重新启动；
4. 尝试过删除本地配置文件重启

**Comment by chenshaoju** [comment]
在选择更新PAC后，应该会出现一个提示，比如更新成功、没有找到更新或者更新失败。

有出现该提示吗？具体是上面三个中的哪个？

**Comment by DannyVim** [comment]
没有找到更新

**Comment by chenshaoju** [comment]
如果没问题的话，的确不会显示任何东西。

请尝试配置一个无效的服务器，然后再更新一下GFWList，是否会出现日志？
