### ISSUE TITLE
How to change DNS for Shadowsocks onwindows?

### ISSUE THREAD

**Issue by NikasZalias** [shadowsocks/shadowsocks-windows#2524]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10.0.18362 Build 18362, .NET Framework 4.6.1

### Steps you have tried / 操作步骤
Looking to code, looking for libs.

### What did you expect to see? / 期望的结果
Find hardcoded DNS addresses.

### What did you see instead? / 实际结果
No solution.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
No need for config for this issue.

The problem is, that on Shadowsocks for windows there is no possibility to change DNS addresses. Shadowsocks for Android has this feature, but windows doesn't... When it is expected to get this feature? Or maybe there is a workaround for the current version?

**Comment by Stzx** [comment]
Sorry, the currently released version does not implement DNS forwarding. 

You can try to use [Pcap_DNSProxy](https://github.com/chengr28/Pcap_DNSProxy) to forward DNS requests to the local shadowsocks proxy port.

**Comment by NikasZalias** [comment]
What about now?

**Comment by studentmain** [comment]
> What about now?

Still not.

**Comment by qwerttvv** [comment]
> > What about now?
> 
> Still not.

那么默认dns采用的哪个呢？

**Comment by studentmain** [comment]
> 
> 
> > > What about now?
> > 
> > 
> > Still not.
> 
> 那么默认dns采用的哪个呢？

We did nothing about DNS, so it's depend on your system config.

**Comment by qwerttvv** [comment]
> > > > What about now?
> > > 
> > > 
> > > Still not.
> > 
> > 
> > 那么默认dns采用的哪个呢？
> 
> We did nothing about DNS, so it's depend on your system config.

okay, i see
thx

**Comment by database64128** [comment]
The processing of incoming requests does not involve DNS, because it's not necessary. Shadowsocks for android has DNS settings because they have to implement a TUN interface for android's VPN APIs. Our project currently doesn't have any plan for that.
