### ISSUE TITLE
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效

### ISSUE THREAD

**Issue by javacaoyu** [shadowsocks/shadowsocks-windows#2527]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

win 10 家庭普通版.   .net 应该是系统自带的吧， 不知道什么版本
### Steps you have tried / 操作步骤
打开 用PAC代理
在公司网络内就这样
在家里一切正常

### What did you expect to see? / 期望的结果

连通 google 
### What did you see instead? / 实际结果
不通

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-08-29 09:56:30] Shadowsocks started (4.1.7.1)
[2019-08-29 09:56:50] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-08-29 09:56:50] Shadowsocks started (4.1.7.1)
[2019-08-29 09:56:52] Shadowsocks started (4.1.7.1)
[2019-08-29 09:56:53] Shadowsocks started (4.1.7.1)
[2019-08-29 09:56:55] Shadowsocks started (4.1.7.1)

以上是错误日志。。。。。

**Comment by javacaoyu** [comment]
.net  4.7.2

**Comment by chenshaoju** [comment]
这意味着你的网络可能封锁了你的服务器。

请尝试让电脑通过手机WiFi热点访问，是否就能正常工作？

**Comment by javacaoyu** [comment]
手机热点后可以正常工作
然后恢复到公司网络后又可以工作了

但是这样不稳定
公司网络偶尔可以用 偶尔不行 不知道具体为什么

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，建议套一个插件试试：
https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by javacaoyu** [comment]
@chenshaoju  好的， 感谢， 我尝试一下。

**Comment by javacaoyu** [comment]
我已经解决了。应该是公司内部有防火墙，直连不行。
我加了obfs插件后就可以正常使用了。
多谢大家。
