### ISSUE TITLE
Shadowsocks non-UI Error 非预期错误，Shadowsocks将退出。

### ISSUE THREAD

**Issue by 3297520446** [shadowsocks/shadowsocks-windows#2529]

**Comment by 3297520446** [comment]
![image](https://user-images.githubusercontent.com/54662381/63921115-cc0e0a00-ca74-11e9-8a14-d1298944a724.png)

**Comment by chenshaoju** [comment]
请安装最新的 .Net Framework https://dotnet.microsoft.com/download/thank-you/net48

如果已经安装，请使用上面的安装包修复安装。
