### ISSUE TITLE
win7 64位系统，启动shadowsocks后弹出窗口提示：“无法修改注册表”，ss无法正常代理

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-windows#253]
shadowsocks版本：2.5.1
![qq 20150803175450](https://cloud.githubusercontent.com/assets/10991795/9035258/e2b8356a-3a08-11e5-9f08-bb4417b6cb5c.png)

**Comment by Aniark** [comment]
附上错误日志

[2015-08-03 17:39:26] Shadowsocks started
[2015-08-03 17:39:26] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.CopyProxySettingFromLan()
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer

**Comment by uinux** [comment]
这个管理员权限运行就可以了吧。

**Comment by Aniark** [comment]
@uinux 

尝试过，无果
![qq 20150805230706](https://cloud.githubusercontent.com/assets/10991795/9089245/c01dbb82-3bc6-11e5-971d-5480a1108297.png)

**Comment by Aniark** [comment]
@clowwindy

**Comment by imebeh** [comment]
是不是被安全软件阻止了？
SS 要 Internet 选项 对应的注册表键值
shadowsocks-windows/shadowsocks-csharp/Controller/System/SystemProxy.cs

**Comment by Aniark** [comment]
@imebeh

请问具体操作是？

**Comment by imebeh** [comment]
@Aniark 只是一种猜测，要看你系统的具体情况
比如
1. 是否原版系统，有些修改过的盗版系统会做些匪夷所思的修改
2. 是否有安全软件弹出过提示并被阻止修改注册表，比如360有提示过并被阻止，而且是记住操作。这条可以试试关掉所有安全软件再开 ss 试试
3. 组策略是不是有些限制。这条是猜测，组策略里面有好多

还有很多其他情况

**Comment by li3shiyi** [comment]
把你的HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Connections导出来看一下，另外先自己看下这个注册表项的权限是不是当前用户可读写。

**Comment by Aniark** [comment]
@li3shiyi  

赋予该注册表用户everyone完全控制权限后，可以正常使用shadowsocks
谢谢

**Comment by tshawn2014** [comment]
我遇到了这个问题，后来发现是金山毒霸造成的！

**Comment by luyawen** [comment]
确实，金山毒霸卸载后，再用管理员权限进去就好了

**Comment by luyawen** [comment]
确实，金山毒霸卸载后，再用管理员权限进去就好了

**Comment by luyawen** [comment]
确实，金山毒霸卸载后，再用管理员权限进去就好了

**Comment by luyawen** [comment]
确实，金山毒霸卸载后，再用管理员权限进去就好了

**Comment by mudelos** [comment]
是金山毒霸问题，进去设置中心->安全防护->信任设置里面，把shadowsocks.exe添加上就可以了

**Comment by czgczg** [comment]
是不是360的问题

**Comment by miaomiaobiubiubiu** [comment]
我的情况是一开始用的好好的正常，我用360卫士清理后也出现了这个问题，我是重启之后，用兼容模式运行了下。程序正常了。猜测是360禁了某些权限，希望对你有帮助。

**Comment by miaomiaobiubiubiu** [comment]
我的情况是一开始用的好好的正常，我用360卫士清理后也出现了这个问题，我是重启之后，用兼容模式运行了下。程序正常了。猜测是360禁了某些权限，希望对你有帮助。

**Comment by koptoamto** [comment]
用的腾讯管家关掉了，然后照着上面的修改了注册表权限，还是设置不了开机启动，尴尬，win10系统

**Comment by qwer4301** [comment]
金山毒霸坑死了,不知道啥时候安装的

**Comment by liruiqi88** [comment]
没装任何杀软，用着用着，也就不行了。

**Comment by liruiqi88** [comment]
失败的程序集的区域是:
MyComputer
[2017-04-10 09:31:04] [E] Cannot find HKCU\Software\Microsoft\Windows\CurrentVersion\Run
[2017-04-10 09:31:47] Shadowsocks started
[2017-04-10 09:31:47] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Util.Utils.OpenRegKey(String name, Boolean writable, RegistryHive hive)
失败的程序集的区域是:
MyComputer
[2017-04-10 09:31:47] [E] Cannot find HKCU\Software\Microsoft\Windows\CurrentVersion\Run
[2017-04-10 09:32:08] System.InvalidOperationException: 进程(3748)已退出，因此无法处理请求。
   在 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   在 System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   在 System.Diagnostics.Process.get_MainModule()
   在 Shadowsocks.Controller.PrivoxyRunner.IsChildProcess(Process process)
[2017-04-10 09:32:10] Shadowsocks started
[2017-04-10 09:32:10] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Util.Utils.OpenRegKey(String name, Boolean writable, RegistryHive hive)
失败的程序集的区域是:
MyComputer
[2017-04-10 09:32:10] [E] Cannot find HKCU\Software\Microsoft\Windows\CurrentVersion\Run


注册表也给了权限，还是不行，怀疑是不是装的系统的原因。我装的这个系统是深度技术纯净版，昨天用老毛桃把这个系统给另一台电脑装上，运行ss也出现了同样的问题。

**Comment by chenshaoju** [comment]
这看起来的确是某种杀毒软件阻止了注册表的访问。请打开任务管理器检查一下是否有杀毒软件或者安全软件在后台运行。

**Comment by liruiqi88** [comment]
![01](https://cloud.githubusercontent.com/assets/19503219/24859964/11c72b52-1e25-11e7-9ec8-b99237661178.PNG)
![02](https://cloud.githubusercontent.com/assets/19503219/24859965/1203befa-1e25-11e7-957f-ee81e7c7db34.PNG)
![03](https://cloud.githubusercontent.com/assets/19503219/24859970/127c90dc-1e25-11e7-970d-7e1b41621b05.PNG)
![04](https://cloud.githubusercontent.com/assets/19503219/24859969/125adfbe-1e25-11e7-8be7-ffa197585715.PNG)
![05](https://cloud.githubusercontent.com/assets/19503219/24859966/1244a94c-1e25-11e7-9532-786eb24c25b8.PNG)
![06](https://cloud.githubusercontent.com/assets/19503219/24859968/12586c34-1e25-11e7-9eed-7d6c4152fafc.PNG)
![07](https://cloud.githubusercontent.com/assets/19503219/24859971/129ab5f8-1e25-11e7-9d36-adfc7a565d01.PNG)
哎呀！我看了一下应该没有呀！

**Comment by saltyzero** [comment]
> 没装任何杀软，用着用着，也就不行了。

 我也是这样 莫名其妙的  我做程序开发的  从来不会搞啥奇怪的东西在电脑上

**Comment by chenshaoju** [comment]
请尝试右击 Shadowsocks.exe ，点击属性，是否能看到下面这个选项？（图片为其他的，请忽略）。

![image](https://user-images.githubusercontent.com/515763/61764074-6fcb2100-ae0a-11e9-8440-08c30056392a.png)

另外，具体是什么提示？这个帖子太老了，可能不具有现实意义了。
