### ISSUE TITLE
pac.txt处理domain option的bug

### ISSUE THREAD

**Issue by szmcdull** [shadowsocks/shadowsocks-windows#2530]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows

### Steps you have tried / 操作步骤
在user-rule.txt中添加一条规则
||company.com^$domain=~wiki.company.com

### What did you expect to see? / 期望的结果
根据https://adblockplus.org/en/filter-cheatsheet, 访问wiki.company.com的时候应该不走代理

### What did you see instead? / 实际结果
走代理，domain option无效

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

经过debug，发现`pac.txt`中有bug，在第`7312`行的地方(`ActiveFilter.getDomains()`中)，没有将局部变量`domains`赋值给`this.domains`，导致domain options失效。按以下修改后，问题修复：
```
		this.domains = domains;
        	return domains;
```

**Comment by celeron533** [comment]
pac.txt 的判断逻辑来自adblockplus。可能是早些年的abp.js也有这个问题

**Comment by szmcdull** [comment]
估计是的

**Comment by celeron533** [comment]
@szmcdull 虽然这看起来像是一个小改动，但要确定是否会影响其他部分。

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Data/abp.js

**Comment by szmcdull** [comment]
> 
> 
> @szmcdull 虽然这看起来像是一个小改动，但要确定是否会影响其他部分。
> 
> source code
> https://github.com/shadowsocks/shadowsocks-windows/blob/36297b91320db0a40ebb214e3063187564339234/shadowsocks-csharp/Data/abp.js

这个代码里还是没有写this.domains吧

**Comment by celeron533** [comment]
@szmcdull 这是未经修改的代码。平时最终用户使用的pac都是基于这个文件混合gfwlist内容生成的

**Comment by szmcdull** [comment]
所以你们是要改吗，还是先提交到ABP去处理

**Comment by celeron533** [comment]
@szmcdull 如果你熟悉js并且能够测试大部分用例的话，欢迎提pullrequest

**Comment by szmcdull** [comment]
你说的测试用例是指哪里，这个应该很好验证啊

**Comment by studentmain** [comment]
gfwlist规则不是abp规则，因此不修，可以使用一条黑名单规则和一条白名单规则达成相同目的

**Comment by szmcdull** [comment]
黑名单白名单怎么配置
