### ISSUE TITLE
When do you add the kcp function?

### ISSUE THREAD

**Issue by lgd8069465** [shadowsocks/shadowsocks-windows#2531]
ShadowsocksX-NG already have supported SIP003 plugins. Embed kcptun and simple-obfs.

**Comment by chenshaoju** [comment]
You can use kcptun with shadowsocks:
https://github.com/shadowsocks/shadowsocks-windows/wiki/Working-with-non-SIP003-standard-Plugin

**Comment by lgd8069465** [comment]
Thank you so much!
