### ISSUE TITLE
kcptun插件启动了但是无效

### ISSUE THREAD

**Issue by azazjjyjjy** [shadowsocks/shadowsocks-windows#2533]
![image](https://user-images.githubusercontent.com/14151109/64006042-24600d00-cb44-11e9-8e7a-fb3ac7999c16.png)
启动参数在cmd中测试通过。
因为kcp是非SIP版本，采用参数方式加载。
插件程序 填写 C:\Shadowsocks-4.1.7.1\kcp_client.exe
插件参数填写 -l ":4444" -r "VPSIP:4000" --crypt none --mode manual --mtu 1378 --sndwnd 256 --rcvwnd 4096 --datashard 70 --parityshard 36 --dscp 46 --nocomp --quiet true --nodelay 0 --interval 40 --resend 0 --nc 1 --sockbuf 16777217

检查发现任务管理器中kcp_client.exe在进程中，但是无法联网

**Comment by chenshaoju** [comment]
你必须使用变量指定端口，请尝试：
```
-l "%SS_LOCAL_HOST%:%SS_LOCAL_PORT%" -r "%SS_REMOTE_HOST%:%SS_REMOTE_PORT%" --crypt none --mode manual --mtu 1378 --sndwnd 256 --rcvwnd 4096 --datashard 70 --parityshard 36 --dscp 46 --nocomp --quiet true --nodelay 0 --interval 40 --resend 0 --nc 1 --sockbuf 16777217
```

然后在SS的客户端里填写你的服务器的IP和你的服务器的kcptun监听端口。

具体请参考：https://github.com/shadowsocks/shadowsocks-windows/wiki/%E4%BD%BF%E7%94%A8%E9%9D%9ESIP003%E8%A7%84%E8%8C%83%E7%9A%84%E6%8F%92%E4%BB%B6

**Comment by azazjjyjjy** [comment]
> 你必须使用变量指定端口，请尝试：
> 
> ```
> -l "%SS_LOCAL_HOST%:%SS_LOCAL_PORT%" -r "%SS_REMOTE_HOST%:%SS_REMOTE_PORT%" --crypt none --mode manual --mtu 1378 --sndwnd 256 --rcvwnd 4096 --datashard 70 --parityshard 36 --dscp 46 --nocomp --quiet true --nodelay 0 --interval 40 --resend 0 --nc 1 --sockbuf 16777217
> ```
> 
> 然后在SS的客户端里填写你的服务器的IP和你的服务器的kcptun监听端口。
> 
> 具体请参考：https://github.com/shadowsocks/shadowsocks-windows/wiki/%E4%BD%BF%E7%94%A8%E9%9D%9ESIP003%E8%A7%84%E8%8C%83%E7%9A%84%E6%8F%92%E4%BB%B6
感谢，问题已经解决。直接使用环境变量这一串即可，不用替换成自己实际的IP和端口。

**Comment by wyfang** [comment]
为什么以前kcptun只要写：key=123456 就可以，现在需要填写：-l %SS_LOCAL_HOST%:%SS_LOCAL_PORT% -r %SS_REMOTE_HOST%:%SS_REMOTE_PORT% --key 123456 ？

**Comment by chenshaoju** [comment]
kcptun有很多个版本，其中比较主流的是官方（主线，https://github.com/xtaci/kcptun ）版本，该版本不支持Shadowsocks的SIP003规范，所以需要使用自定参数。

另一个则是Shadowsocks修改过后的版本（支线，https://github.com/shadowsocks/kcptun ），该版本符合Shadowsocks的SIP003规范，能自动识别地址端口等信息，所以没有这方面的问题。
