### ISSUE TITLE
win10移动了目录导致开机自启无法去除

### ISSUE THREAD

**Issue by wyfang** [shadowsocks/shadowsocks-windows#2534]
我从d盘移动到G盘后，发现开机自启无法去除，即使去掉勾，开机依然会自启动，问题是自启动的ss无法正常使用。需要退出后手动去启动才能正常使用。

**Comment by chenshaoju** [comment]
请打开注册表(regedit)，进入 `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` ，然后删掉带有 Shadowsocks 的键值即可。

**Comment by wyfang** [comment]
> 请打开注册表(regedit)，进入 `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` ，然后删掉带有 Shadowsocks 的键值即可。

进去没有看到 Shadowsocks 的键值，而且我发现正常双击运行的Shadowsocks也无法使用，要以管理员运行才可以。

**Comment by chenshaoju** [comment]
此问题不应该发生，请退出当前使用的SS，试将 Shadowsocks.exe 单独放到一个新的目录，比如 G:\SS\ ，重新配置一次看看？
