### ISSUE TITLE
Win10无法使用

### ISSUE THREAD

**Issue by charleypeng** [shadowsocks/shadowsocks-windows#254]
Win10一直无法使用 ， 此外， universal app在win8.1的时候也是无法翻墙的。错误信息如下
[2015-08-04 00:10:21] Shadowsocks started
[2015-08-04 00:10:21] System.Net.Sockets.SocketException (0x80004005): 不知道这样的主机。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.StartConnect(IAsyncResult ar)
[2015-08-04 00:10:21] System.Net.Sockets.SocketException (0x80004005): 不知道这样的主机。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.StartConnect(IAsyncResult ar)
[2015-08-04 00:10:21] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2015-08-04 00:10:29] System.Net.Sockets.SocketException (0x80004005): 不知道这样的主机。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.StartConnect(IAsyncResult ar)

**Comment by miniking0668** [comment]
我的也是同样的情况 只出现在我WIN10的系统里 
有没有人可以解决？
