### ISSUE TITLE
放弃配置可能导致配置被清空

### ISSUE THREAD

**Issue by imba-tjd** [shadowsocks/shadowsocks-windows#2542]
### Shadowsocks version / 影梭版本

4.1.7.1

---

添加一个空的配置，移动到非最后一项，点击最后一项，放弃配置点OK，报错，且原有所有配置都被清空：

![QQ截图20190904224024](https://user-images.githubusercontent.com/24759802/64265821-21ab5080-cf66-11e9-9f41-a9082d7b5bcd.png)

4.1.6的效果是不允许不正确的配置上下移动。这个我个人觉得可以不保持一致，只把现在的bug修了就行，不过如果麻烦的话就算了。

@Stzx

**Comment by Stzx** [comment]
秀啊 🤣， 我看看。

**Comment by chenshaoju** [comment]
已确认该问题，但是并不会真正导致先前的配置丢失，只是界面陷入不正常状态，点击取消后再次打开配置仍然在。
