### ISSUE TITLE
新手，服务器地址该怎么设置？

### ISSUE THREAD

**Issue by Hilary-Hsiao** [shadowsocks/shadowsocks-windows#2544]
不知道ServerAdd该写什么ip，求解

**Comment by chenshaoju** [comment]
你需要购买一台海外的VPS服务器，搭建服务端，然后再在客户端里填写你的服务器的IP地址。

或者，你需要自行寻找第三方的Shadowsocks服务商，购买服务来进行使用。

**Comment by Hilary-Hsiao** [comment]
> 你需要购买一台海外的VPS服务器，搭建服务端，然后再在客户端里填写你的服务器的IP地址。
> 
> 或者，你需要自行寻找第三方的Shadowsocks服务商，购买服务来进行使用。

多谢哈！
