### ISSUE TITLE
Cannot Install on Window 10 machin

### ISSUE THREAD

**Issue by jianweili0** [shadowsocks/shadowsocks-windows#2546]
![notworking](https://user-images.githubusercontent.com/31417181/64733653-24043200-d4b3-11e9-9533-98c6f5ca914c.JPG)

**Comment by chenshaoju** [comment]
Outline use Shadowsocks as part, But here unable slove Outline issue.
Please goto: https://github.com/outline/outline

**Comment by imba-tjd** [comment]
@chenshaoju 不是你发的这个outline啦XD

**Comment by chenshaoju** [comment]
@imba-tjd My bad，没仔细看。 😅
