### ISSUE TITLE
The Proxy switch missed 代理开关丢失

### ISSUE THREAD

**Issue by Jaydenyjd** [shadowsocks/shadowsocks-windows#2549]
### Shadowsocks version / 影梭版本
4.7.0
### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win 10 ,已安装net framework

问题：

如下图 ，菜单最顶端的开关选项丢失了，还望支持，谢谢！
![image](https://user-images.githubusercontent.com/55344594/64918859-8b352580-d7d6-11e9-8963-adb370158894.png)

**Comment by chenshaoju** [comment]
你好，你是用的ShadowsocksR，不是Shadowsocks。这两个不同的东西。

**Comment by Jaydenyjd** [comment]
请问Shadowsocks win 10 在哪里可以下载？ 谢谢

**Comment by Jaydenyjd** [comment]
下载了Shadowsocks 4.1.7.1,依然没有开关，
![image](https://user-images.githubusercontent.com/55344594/64919825-fdf7ce00-d7e1-11e9-9078-8f0a8ed27878.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2390#issuecomment-499825102

**Comment by Jaydenyjd** [comment]
好的，谢谢
