### ISSUE TITLE
代理设置错误？SysproxyExitError:Error query options: 12178 (null)

### ISSUE THREAD

**Issue by octopusmiu** [shadowsocks/shadowsocks-windows#2550]
### Environment (Operating system, .NET Framework, etc) / windows， .NET Framework 4.7.2 , Microsoft Visual C++ 2015 Redistributable (x86) 

打开shadowsocks后，跳出对话框：

> 处理代理设置时发生错误，是否重置当前代理设置并重试？

![1](https://user-images.githubusercontent.com/12268982/64933085-d8b49f80-d875-11e9-9abe-acba68daa855.png)

点击重置：

> 发生不可恢复的代理设置错误，查看日志以获得详情

![2](https://user-images.githubusercontent.com/12268982/64933082-d5211880-d875-11e9-9146-c7363418f9d3.png)

日志内容如下：

> [2019-09-16 11:27:22] Shadowsocks started (4.1.7.1)
> [2019-09-16 11:27:22] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)
> 
> [2019-09-16 11:27:38] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

不知道怎么修复，求助。

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2325

**Comment by octopusmiu** [comment]
> #2325

感谢！抱歉没搜重复问题……我先关问题了~
