### ISSUE TITLE
1080 端口于 20H1 被系统变为保留端口。

### ISSUE THREAD

**Issue by Mirr0ch1** [shadowsocks/shadowsocks-windows#2552]
![图片](https://user-images.githubusercontent.com/3250823/64950333-ab83e380-d8ad-11e9-8242-5221e82ef84e.png)

**Comment by Mirr0ch1** [comment]
![图片](https://user-images.githubusercontent.com/3250823/64950519-251bd180-d8ae-11e9-97dc-e57d24e62537.png)

**Comment by chenshaoju** [comment]
请尝试在编辑服务器界面右下角的代理端口选项中换一个端口，比如10800。

**Comment by Mirr0ch1** [comment]
@chenshaoju 感谢！
不过再请问一下，如果 Windows 以后真的在 2003 版把此端口保留了，ss-win 会决定改变默认端口吗？

**Comment by chenshaoju** [comment]
这个取决于开发人员/社区的决定。

不过1080是IANA指定的SOCKS端口：
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml

如果你想移除系统的保留端口，可参阅： https://github.com/shadowsocks/shadowsocks-windows/issues/1835#issuecomment-453528715

**Comment by Mirr0ch1** [comment]
![image](https://user-images.githubusercontent.com/3250823/65666046-6d39b180-e06f-11e9-8afb-40cccc5bccc4.png)
![image](https://user-images.githubusercontent.com/3250823/65666073-7aef3700-e06f-11e9-9edd-ef841bbd0bd6.png)

经测，目前 8635 前的端口大部分均已被 Windows Build. 18990.1 列为保留端口。 @chenshaoju

**Comment by chenshaoju** [comment]
感谢报告。

**Comment by database64128** [comment]
我从1903（18362）升级到18990以后正常，1080端口正常使用。但是今天从18990升级到18995以后，1080成了保留端口无法再使用了。下面是我的保留端口列表：
![image](https://user-images.githubusercontent.com/18757988/66217252-8c80b080-e6f9-11e9-8390-73363004bc73.png)

**Comment by database64128** [comment]
今天更新到18999以后，1080不再是保留端口了，如图所示：
![image](https://user-images.githubusercontent.com/18757988/66480039-5021cb80-ead0-11e9-88df-654c8b5e0b92.png)

**Comment by database64128** [comment]
18999网络功能出现问题（在有线和无线频繁切换几次后，WSL2的虚拟交换机造成所有UWP apps无法上网），重启卡死，强制重启后，端口1024-1123再次成为保留端口。。看来保留端口的选择还有一定的随机性。

**Comment by s1eke** [comment]
这个报错并不是一直在用的端口真的成为了系统保留端口，可能是重启的时候shadowsocks没有正常退出，遇到这种情况的时候可以尝试一下手动退出shadowsocks，然后再重启一下。

**Comment by database64128** [comment]
> 这个报错并不是一直在用的端口真的成为了系统保留端口，可能是重启的时候shadowsocks没有正常退出，遇到这种情况的时候可以尝试一下手动退出shadowsocks，然后再重启一下。

1. 我是用netsh看过了，确认1024-1123再次成为了保留端口。
2. ss是24小时开着，以往无数次系统崩溃从没有过ss因为非正常关闭而带来问题。

**Comment by s1eke** [comment]
我是技术菜鸟，所以只能从经验上说一下我的经历😂
我先是用1080，然后在一次开机后1080成为系统保留端口，我就换成1090继续用，不久后的莫一天，1090开机又成为系统保留端口，我就换成了10080。然而在今天，正常开机后10080又成为系统保留端口，所以我就产生了怀疑……
我试着正常退出shadowsocks，然后重启了一下，10080端口就可以继续使用了……



> ss是24小时开着，以往无数次系统崩溃从没有过ss因为非正常关闭而带来问题。

另外我说的没有正常退出的意思是软件bug产生的，像没有停止占用端口这样的。
当然，仅仅是我的个人猜测😂。

**Comment by lengthmin** [comment]
> 我是技术菜鸟，所以只能从经验上说一下我的经历😂
> 我先是用1080，然后在一次开机后1080成为系统保留端口，我就换成1090继续用，不久后的莫一天，1090开机又成为系统保留端口，我就换成了10080。然而在今天，正常开机后10080又成为系统保留端口，所以我就产生了怀疑……
> 我试着正常退出shadowsocks，然后重启了一下，10080端口就可以继续使用了……
> 
> > ss是24小时开着，以往无数次系统崩溃从没有过ss因为非正常关闭而带来问题。
> 
> 另外我说的没有正常退出的意思是软件bug产生的，像没有停止占用端口这样的。
> 当然，仅仅是我的个人猜测😂。

我觉得这个猜测和我的经历十分接近..

一旦端口报错之后 `netsh winsock reset` 重启又可以继续用了..

**Comment by database64128** [comment]
目前20H1最新的build 19041极有可能成为RTM。在该build中，行为和此前一致：**用户登录后（登录前不保留端口）**系统会随机保留一大段端口，被保留的端口将无法使用。可以通过`netsh interface ipv4 show excludedportrange protocol=tcp`查看被保留的端口。

系统的这一行为严重影响了需要bind本地端口的应用程序的正常使用，带来了极大不便（只能重启碰运气直到系统不再使用所需的端口），我相信是bug。对于在该版本的用户，理论上有个workaround，就是写一个服务，在用户登录前把所需端口拿下来，登录后再释放，就可以避免被系统吃了端口。

作为一个长期预览版用户，根据以往微软对这类bug的反应，我不指望微软会在20H1正式发布前修复它。在这里建议大家及时关注相关动态，如果20H1发布后没修复，就不要更新20H1。20H1还让组策略禁用自动更新失效了，在20H1下没有办法在不破坏系统组件的情况下真正意义上禁用自动更新（GUI的暂停几天不是禁用自动更新）。

**Comment by studentmain** [comment]
基于目前情况，锅先给微软，ss-windows继续使用IANA分配的标准端口

**Comment by chansonzhang** [comment]
只需要关闭hyper-v就可以啦
![free_port_1080](https://user-images.githubusercontent.com/12625869/109971726-813c1500-7d31-11eb-8b00-9c0b7ff18459.png)

**Comment by KevinZonda** [comment]
@chansonzhang 草
