### ISSUE TITLE
SS是不是又因为敏感因素瘫痪了？

### ISSUE THREAD

**Issue by Skuyar** [shadowsocks/shadowsocks-windows#2553]

**Comment by haireggs** [comment]
我的也用不了了

**Comment by Skuyar** [comment]
> 我的也用不了了

看来很有可能。。

**Comment by chenshaoju** [comment]
如果你的SS服务是自己搭的，请尝试套个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

如果你的SS服务是购买的，请与你的SS服务商联系。

**Comment by Skuyar** [comment]
> 如果你的SS服务是自己搭的，请尝试套个插件：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)
> 
> 如果你的SS服务是购买的，请与你的SS服务商联系。

好的，我看看，谢谢

**Comment by shujunxiong** [comment]
我也用不了了，电脑安卓都不行了 。

**Comment by jqqjj** [comment]
【2019年国家网络安全宣传周公益短信】2019年国家网络安全宣传周是9月16日-22日。没有网络安全就没有国家安全，就没有经济社会的稳定运行，广大人民群众利益也难以得到保障。网络安全为人民，网络安全靠人民，积极参与网络安全发展，提升网络安全意识，共筑网络安全防线。【工业和信息化部】

**Comment by qugang** [comment]
应该是被识别了，市面上的都不能用了

**Comment by Skuyar** [comment]
> 【2019年国家网络安全宣传周公益短信】2019年国家网络安全宣传周是9月16日-22日。没有网络安全就没有国家安全，就没有经济社会的稳定运行，广大人民群众利益也难以得到保障。网络安全为人民，网络安全靠人民，积极参与网络安全发展，提升网络安全意识，共筑网络安全防线。【工业和信息化部】

可以可以

**Comment by zry118** [comment]
我现在叶都上不了

**Comment by shintani7** [comment]
猪圈角落的那个小洞，也堵起来了。

**Comment by qwertccc** [comment]
从15号下午开始，到16号就开始一片哀嚎了

我的那个还活着，就是速度感人，以前走上海出口，现在变成广州了

**Comment by qwertccc** [comment]
我建议现在先不要折腾，如果挂了也先不要换ip，等国庆以后再说

胆儿大的接着玩儿，胆儿小的先关机保号

**Comment by mingcxb** [comment]
不要用默认的加密算法，在增加一个混淆器插件就可以了

**Comment by regulus92** [comment]
不能用谷歌学术了真的是很悲伤的事情

**Comment by imba-tjd** [comment]
> 
> 
> 不能用谷歌学术了真的是很悲伤的事情

百度一下“谷歌学术”有一堆的镜像网站，别登录就是。

**Comment by zry118** [comment]
我现在使用翻墙机场，顶一段时间：邀请码：0BKG  连接地址

**Comment by zry118** [comment]
http://www.vwall.gq/auth/register?code=0BKG

**Comment by shintani7** [comment]
我想知道V2R没影响吗？

**Comment by Alvin9999** [comment]
v2ray用ws+tls正常，能套cf最好

**Comment by asdfgh-sss** [comment]
试试可以这个http://www.vwall.gq/auth/register?code=eJ1P

**Comment by fish-404** [comment]
PC端浏览器还是可以用Firefox自带Proxy，就是无法全局

**Comment by CV03Saratoga** [comment]
没有梯子怎么联系运营商.....

**Comment by scherpe** [comment]
我用的是digitalocean，我连ping都ping不通

**Comment by fhwo13** [comment]
我自己搭建的ss节点前几天也被封了，上次6月也被封过一次，每次敏感时期就被封GFW是否已经能够识别ss协议了？

**Comment by Hinmo** [comment]
加密混淆方式的选择，端口号，流量多少我猜都有一些影响。我这边用过很久，在近一年的时间里面，无论什么会议，什么大事，都没有被封杀过，有过疑似限速的情况，但是拿捏不准到底是墙的问题，还是机器本身片区网络不佳。 
------------------
Hinmo Tsang
Shenzhen, China


 




------------------ 原始邮件 ------------------
发件人: "NeoCC"<notifications@github.com>; 
发送时间: 2019年9月20日(星期五) 下午3:18
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [shadowsocks/shadowsocks-windows] SS是不是又因为敏感因素瘫痪了？ (#2553)




我自己搭建的ss节点前几天也被封了，上次6月也被封过一次，每次敏感时期就被封GFW是否已经能够识别ss协议了？
 
&mdash;

**Comment by devon-ge** [comment]
V家的服务器基本上是开通-ssh连接-部署ss服务端-使用一分钟-被封。。。我试过好多个地方了，都是这样，欧洲的服务器会好一点，但也是不稳定。

**Comment by devon-ge** [comment]
> 我自己搭建的ss节点前几天也被封了，上次6月也被封过一次，每次敏感时期就被封GFW是否已经能够识别ss协议了？

就算不能识别，一刀切也是可以的。我感觉是IP段封锁，毕竟频繁访问一个固定ip，具体即使不清楚也干脆给你封了

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history

**Comment by XuruiPro** [comment]
不能用了，刚刚服务器启动了一下ss，可以用，然后配套个kcptun也可以用，但是没过多久，都不能用了，感觉直接屏蔽了ss相关的内容发送，ip没屏蔽，直接屏蔽的软件(kcptun加速网站可以用)
