### ISSUE TITLE
Autoconfig pac url is allways change after edit userrules!

### ISSUE THREAD

**Issue by xspeed1989** [shadowsocks/shadowsocks-windows#2554]
Autoconfig pac URL is always changed after edit user rules!
so browser or other application can not be proxied!

**Comment by chenshaoju** [comment]
Please make sure uncheck this option:
![image](https://user-images.githubusercontent.com/515763/65008576-678bef80-d93c-11e9-8857-6c88c35960de.png)

PS: In English, This options name is "Secure Local PAC".
