### ISSUE TITLE
Shadowsocks stop work and problem is "KERNELBASE.dll"

### ISSUE THREAD

**Issue by Penny22** [shadowsocks/shadowsocks-windows#2555]
### Shadowsocks version / 影梭版本
4.1.5.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

windows7 ,net framework 4.0.30319（安装要求要的此版本）

### Steps you have tried / 操作步骤
原本用的win10,重装成7之后再打开提示安装 .net framework,装完之后就跳出停止工作的窗口。
问题事件名称:	APPCRASH
  应用程序名:	Shadowsocks.exe
  应用程序版本:	4.1.5.0
  应用程序时间戳:	5c81fe96
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.24384
  故障模块时间戳:	5c6e2226
  异常代码:	e0434352
  异常偏移:	0000c5af
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

### What did you expect to see? / 期望的结果
本来以为是杀毒软件的问题，然后换了版本，把杀毒软件卸载之后又跳出了另一个问题。
问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	4.1.2.0
  问题签名 03:	5b9a6ac7
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	4ba1da6f
  问题签名 07:	11cd
  问题签名 08:	89
  问题签名 09:	System.TypeLoadException
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

### What did you see instead? / 实际结果
是 .net framework  安装的不正确吗？

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
  应用程序名:	Shadowsocks.exe
  应用程序版本:	4.1.5.0
  应用程序时间戳:	5c81fe96
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.24384
  故障模块时间戳:	5c6e2226
  异常代码:	e0434352
  异常偏移:	0000c5af
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by chenshaoju** [comment]
是，建议安装最新版本的.Net framework: https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by Penny22** [comment]
试了一下，好像可以了，太感谢！！

**Comment by kguang** [comment]
> 是，建议安装最新版本的.Net framework: https://dotnet.microsoft.com/download/dotnet-framework/net48

安装NET此崩溃已不再提示，应该已解决，谢谢
