### ISSUE TITLE
修改服务器ssh端口后,ss失效

### ISSUE THREAD

**Issue by kaito233** [shadowsocks/shadowsocks-windows#2557]
### Shadowsocks version / 影梭版本
2.5.8

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
unbuntu19

### Steps you have tried / 操作步骤
修改ssh端口后,xshell等都可以连接,但是ss失效

### What did you expect to see? / 期望的结果
xshell可以连接,ss也可以fq

### What did you see instead? / 实际结果
xshell可以连接,ss不可以fq

**Comment by chenshaoju** [comment]
请尝试换一个端口看看。

请注意：不要将你的SSH端口填写到SS客户端上，应该填写你的SS服务器的SS服务端口。

**Comment by kaito233** [comment]
> 请尝试换一个端口看看。
> 
> 请注意：不要将你的SSH端口填写到SS客户端上，应该填写你的SS服务器的SS服务端口。

也就是说理论上正确更改ssh端口是不影响ss的是吗

**Comment by chenshaoju** [comment]
不影响的，另外，可能是凑巧： https://github.com/shadowsocks/shadowsocks-windows/issues/2553

**Comment by kaito233** [comment]
> 不影响的，另外，可能是凑巧： #2553

谢谢><
