### ISSUE TITLE
Registry Value for Automatic startup 

### ISSUE THREAD

**Issue by amirrammari** [shadowsocks/shadowsocks-windows#2558]
Hello Shadowsocks team.
I enabled automatic startup.
![Shadowsocks System Tray Context Menu](https://user-images.githubusercontent.com/23485114/65062214-d135e900-d990-11e9-9e55-2a5adb333d9c.png)
On registry, I see a value-added named "Shadowsocks_88954241".
![Shadowsocks Windows Startup Registry Value](https://user-images.githubusercontent.com/23485114/65062182-bcf1ec00-d990-11e9-9bf7-e29c12a14636.png)
I think that's a bug, Please change "Shadowsocks_88954241" to "Shadowsocks"
Thanks.

**Comment by amirrammari** [comment]
![Shadowsocks Windows Startup Registry Values](https://user-images.githubusercontent.com/23485114/65075604-7f02c100-d9ac-11e9-845d-b3b3a6482691.png)

**Comment by ZLplLQc** [comment]
The trailing number is (kind of) hash code of current location.
So this is a feature for launching multiple shadowsocks instances at startup.
You should disable `Start on Boot` before moving shadowsocks to another location.

**Comment by amirrammari** [comment]
> The trailing number is (kind of) hash code of current location.
> So this is a feature for launching multiple shadowsocks instances at startup.
> You should disable `Start on Boot` before moving shadowsocks to another location.

OK, thanks you. 
I closing this issue.
