### ISSUE TITLE
怎么购买，二维码出不来？还要不要钱了

### ISSUE THREAD

**Issue by gyh0217** [shadowsocks/shadowsocks-windows#2559]
怎么购买，二维码出不来？还要不要钱了

**Comment by gyh0217** [comment]
![QQ图片20190918031000](https://user-images.githubusercontent.com/23291284/65146537-a4480b80-da4e-11e9-8798-bc55065d8542.png)

**Comment by gyh0217** [comment]
真是急死个人

**Comment by chenshaoju** [comment]
如果你是在某处购买的SS服务，请与你的服务商联系。

如果你的服务商提供的是SSR的二维码，SS很可能无法识别。

**Comment by 313231813** [comment]
不知道怎么购买呀？能不能给个地址

**Comment by chenshaoju** [comment]
处于信息/资金安全考虑，此处不提供SS服务商推荐。
