### ISSUE TITLE
无限超时，日志报错

### ISSUE THREAD

**Issue by LemonYu997** [shadowsocks/shadowsocks-windows#2562]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
WIN10 1903     .NET 4.8
手机也连不上
### Steps you have tried / 操作步骤
配置好后，无限超时，打不开google
改过两次端口也重新搭过
### What did you expect to see? / 期望的结果
怎么才能连上

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请尝试使用此第三方工具测试一下，从你的计算机到你的服务器能通吗？ https://github.com/chenshaoju/tcpportcheck

**Comment by LemonYu997** [comment]
> 请尝试使用此第三方工具测试一下，从你的计算机到你的服务器能通吗？ https://github.com/chenshaoju/tcpportcheck

不通

**Comment by chenshaoju** [comment]
你的服务器被墙了，请参考： https://github.com/shadowsocks/shadowsocks-windows/issues/2553#issuecomment-531736556
