### ISSUE TITLE
关于 PACList 规则匹配的问题讨论

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadowsocks-windows#2563]
### Shadowsocks version / 影梭版本

早期版本及 4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows 10 1903

### Steps you have tried / 操作步骤

具体见：[https://www.v2ex.com/t/601959](https://www.v2ex.com/t/601959)

### What did you expect to see? / 期望的结果

||blog.de 这条规则不应该匹配到 blog.dexxxx.xx 等域名

### What did you see instead? / 实际结果

所有de开头的主域名且子域名是blog的站点都会被匹配到，导致走了代理。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

无

**Comment by celeron533** [comment]
#2329
