### ISSUE TITLE
IP没被封，服务器配置OK，但是就是没法代理

### ISSUE THREAD

**Issue by hxy493045049** [shadowsocks/shadowsocks-windows#2564]
如题，连续用了一年多了，曾今由此被封了ip，然后花钱更换过。最近2天发现又不行了，这次ip没问题，服务器配置也是好的，但就是没法代理。
我尝试过

重装vps系统
重新安装ssr和ssr服务，尝试用ss替换ssr
更换端口和密码
尝试用网络上的节点（节点太多，但是没一个有效）
由于不是很懂网络和运维相关的，不懂如何查看日志，希望有了解的大佬指点下。
邮箱： shawn0729@foxmail.com,或者下方留言

另外，如果开发者看到的话，希望添加一个批量测试网络节点的功能，手动切换节点太痛苦了。

**Comment by foxdave** [comment]
一样，突然就不好用了，重做了一个还是不行

**Comment by chenshaoju** [comment]
请使用这个第三方的小工具检测从你的计算机到你的服务器端口是否能通。

![Uploading image.png…]()

**Comment by loyess** [comment]
或者试试搭配SS插件使用： [一键安装SS+Plugins](https://github.com/loyess/Shell)

**Comment by hxy493045049** [comment]
恩  我来自问自答一下  花了很多时间搞。。。
1.  ip没被封，但是端口被封了， 我通过http://ip100.info/check?ip=184.170.220.186&port=1333 做了测试
2.  直接变更vps中ss服务端的server_port就可以解决

期间我调研了其他翻墙方式，找到了v2ray 
可供小白使用的教程
https://github.com/233boy/v2ray/tree/master  
里面教程很详细
基本上傻瓜式

有几个注意点
1.  v2ray一键脚本中，自己集成了一个ss，所以原来vps中的ss可以删了
2. v2ray要求vps的时间和本地电脑的时间误差不能超过90s， 否则拒绝访问
其他没什么了
优点
最让我心动的优点，v2ray能跳过运营商的外网限制！
比方说
我拉的50m第三方宽带（熊博士），访问国内每秒下载速度 5m，但是通过ss下载外网，最多只有600k
而且经常会出现连接中断的问题

刚刚测试了下v2ray，它伪装后就没这个问题了，刚刚speedtest测试了下  5M!

恩，给遇到同样问题的同学参考下

**Comment by foxdave** [comment]
我按教程配置然后用V2RayN试了一下，还是不行
failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 52.243.x.x:port: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

有遇到吗？

**Comment by hxy493045049** [comment]
抱歉，没见过这个问题，建议你到一键脚本的作者那里发个issue
---原始邮件---
发件人:"Justin Liu"<notifications@github.com>;
发送时间:2019年9月21日(星期六) 上午9:42
收件人:"shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>;
抄送人:"shawn"<shawn0729@foxmail.com>;"State change"<state_change@noreply.github.com>;
主题:Re: [shadowsocks/shadowsocks-windows] IP没被封，服务器配置OK，但是就是没法代理 (#2564)


我按教程配置然后用V2RayN试了一下，还是不行
 failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 52.243.x.x:port: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
 
有遇到吗？
 
&mdash;

**Comment by luoyanghero** [comment]
使用的bandwagon的vps，换了2次ip都被封ip了。vps使用ss python版本和ss go版本。
另外有一个virmach的vps，封了端口，没有封ip。
发现virmach的vps默认防火墙都关了所有端口，你用哪个得手动打开。
而bandwagon的vps默认防火墙开了所有端口，这样会不会导致更容易封ip？
