### ISSUE TITLE
Installer for Shadowsocks

### ISSUE THREAD

**Issue by xmha97** [shadowsocks/shadowsocks-windows#2565]
I created an Installer for Shadowsocks.
If you like, add this installer to your project.
Or add below link to Shadowsocks README.md file:
https://github.com/xmha97/Shadowsocks-Installer/releases
I updating installer on a release published :)
Thanks.

Installer:
![image](https://user-images.githubusercontent.com/23485114/65320831-fce6e800-dbb7-11e9-8b1c-030ac9b65b30.png)

On StartMenu:
![image](https://user-images.githubusercontent.com/23485114/65320782-e476cd80-dbb7-11e9-9d61-7554c2969dc8.png)

**Comment by studentmain** [comment]
IMO, we already packed the program into zip, pack dependency into executable file doesn't make much sense. Other portable software also pack their dependency in zip. @celeron533 @chenshaoju

**Comment by chenshaoju** [comment]
I Preferred Portable version, So... 😅

**Comment by amirrammari** [comment]
> I Preferred Portable version, So...

Why you preferred portable version?

**Comment by studentmain** [comment]
> I Preferred Portable version, So...

You mean portable or single exe?

**Comment by chenshaoju** [comment]
Portable, All config with the exe.
Single exe or not is not important for me.

**Comment by studentmain** [comment]
@amirrammari By the way, would you like translate the program to your language? (#2750)

**Comment by studentmain** [comment]
You may need this, https://github.com/studentmain/shadowsocks-windows/tree/no-builtin-blob , this version no longer pack dependency in exe

**Comment by amirrammari** [comment]
> You may need this, https://github.com/studentmain/shadowsocks-windows/tree/no-builtin-blob , this version no longer pack dependency in exe

I can't see the executable file.
Please add the executable file to the **Releases** page

**Comment by studentmain** [comment]
> > You may need this, https://github.com/studentmain/shadowsocks-windows/tree/no-builtin-blob , this version no longer pack dependency in exe
> 
> I can't see the executable file.
> Please add the executable file to the **Releases** page

You need compile it by yourself for now... Some modification to CI build pipe may also needed.

**Comment by amirrammari** [comment]
> > > You may need this, https://github.com/studentmain/shadowsocks-windows/tree/no-builtin-blob , this version no longer pack dependency in exe
> > 
> > 
> > I can't see the executable file.
> > Please add the executable file to the **Releases** page
> 
> You need compile it by yourself for now... Some modification to CI build pipe may also needed.

Ok, Thank you.

**Comment by studentmain** [comment]
#1146 might be useful too. Because here's an installer now, register protocol handler by it seems resonable. Program itself only need handle protocol URL.

**Comment by studentmain** [comment]
@Stzx  How do you think about an installer?

**Comment by Stzx** [comment]
For simple and less complex applications, I'm used to using the install-free version. Larger software makes it easier to use the installer. But this does not affect some users who use the installer to install any application, which is easier for them.

So I choose to hold a reservation,  ( but it's better than nothing :smiley:

**Comment by Prajwal-Koirala** [comment]
Does this have TUN for windows??

**Comment by studentmain** [comment]
> Does this have TUN for windows??

No, considering current situation of this project (lack of developer, ancient codebase), we won't include TUN in forseeable future... If we finished refactor, and/or have more maintainer, we'll probably discuss it for next major release, but not now. You can use outline-client, at least they have TAP for all platform (Windows, Linux, Mac, Android, iOS).

**Comment by Prajwal-Koirala** [comment]
The problem with the outline client is that they don't support v2ray or any of these plugins that hide SS traffic, and if we are only concerned with Encryption than there are better projects like WireGuard, which has an amazing Encryption but if we use something like DPI we can easily tell it's a VPN tunnel, on the other hand DPI on SS will look like normal HTTP.

**Comment by amirrammari** [comment]
> The problem with the outline client is that they don't support v2ray or any of these plugins that hide SS traffic, and if we are only concerned with Encryption than there are better projects like WireGuard, which has an amazing Encryption but if we use something like DPI we can easily tell it's a VPN tunnel, on the other hand DPI on SS will look like normal HTTP.

You can use ClashForWindows client
https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.8.9/Clash.for.Windows.Setup.0.8.9.exe

**Comment by amirrammari** [comment]
> > > The problem with the outline client is that they don't support v2ray or any of these plugins that hide SS traffic, and if we are only concerned with Encryption than there are better projects like WireGuard, which has an amazing Encryption but if we use something like DPI we can easily tell it's a VPN tunnel, on the other hand DPI on SS will look like normal HTTP.
> > 
> > 
> > You can use ClashForWindows client
> > https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.8.9/Clash.for.Windows.Setup.0.8.9.exe
> 
> what in the world is this?
> 
> never even heard of this before.

a cross-platform client for Shadowsocks (like [Outline VPN](https://getoutline.org/))
For more information, read [documentation](https://docs.cfw.lbyczf.com/)
![image](https://user-images.githubusercontent.com/23485114/72518545-d6d20b80-386a-11ea-8f91-64a3af61f2e1.png)

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/75982441-93953000-5ede-11ea-9953-88d05b3fd2f4.png)

I removed Fody to generate exe without dll. Looks not bad.

**Comment by xmha97** [comment]
> 
> 
> ![图片](https://user-images.githubusercontent.com/17123090/75982441-93953000-5ede-11ea-9953-88d05b3fd2f4.png)
> 
> I removed Fody to generate exe without dll. Looks not bad.

Excellent, Do you have any plans for creating an installer now?

**Comment by studentmain** [comment]
> Excellent, Do you have any plans for creating an installer now?

Not yet, I won't merge it in to main repository, you can still create installer from my branch.

**Comment by xmha97** [comment]
> 
> 
> > Excellent, Do you have any plans for creating an installer now?
> 
> Not yet, I won't merge it in to main repository, you can still create installer from my branch.

Ok, I created installer for leaset version: (v4.1.9.2)
https://github.com/xmha97/Shadowsocks-Installer/releases/download/v4.1.9.2/Shadowsocks-4.1.9.2.exe
