### ISSUE TITLE
[AEAD Question] Why encrypt the tcp first request target address as an alone chunk ?

### ISSUE THREAD

**Issue by GreatFireWall** [shadowsocks/shadowsocks-windows#2566]
Why not encrypt target address with payload together like normal (non-AEAD) stream cipher ? 

![image](https://user-images.githubusercontent.com/4510984/65354291-c0e86d00-dc21-11e9-8c01-01b9f2bd26f8.png)

**Comment by wongsyrone** [comment]
Due to the initial behavior of libev variant.

**Comment by GreatFireWall** [comment]
> Due to the initial behavior of libev variant.

By the way, what are the benefits of doing this for libev ?
