### ISSUE TITLE
启动ss 就是代理设置时发生错误，而且我的电脑没有Web Proxy Auto-Discovery Service

### ISSUE THREAD

**Issue by ZserOmega** [shadowsocks/shadowsocks-windows#2568]
- [ ] 
![360截图20190921103008471](https://user-images.githubusercontent.com/54034530/65366774-d463fa00-dc5a-11e9-9f34-6fad19bdc8e8.jpg)

**Comment by chenshaoju** [comment]
请贴一下Shadowsocks的日志（位于托盘区纸飞机图标右击-帮助-显示日志），请记得隐藏你的服务器信息。

**Comment by ZserOmega** [comment]
> 请贴一下Shadowsocks的日志（位于托盘区纸飞机图标右击-帮助-显示日志），请记得隐藏你的服务器信息。

[2019-09-21 10:52:23] Shadowsocks started (4.1.5)
[2019-09-21 10:52:24] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-09-21 10:52:24] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-09-21 10:52:26] connect to api.github.com:443
[2019-09-21 10:52:31] 13.230.8.111:33997 timed out
[2019-09-21 10:52:31] connect to api.github.com:443
[2019-09-21 10:52:33] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-09-21 10:52:36] 13.230.8.111:33997 timed out
[2019-09-21 10:52:36] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-09-21 10:52:38] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-09-21 10:52:40] [E] sysproxy - SysproxyExitError:Error query options: 12178 (null)

[2019-09-21 11:21:26] Shadowsocks started (4.1.5)

**Comment by ZserOmega** [comment]
> 请贴一下Shadowsocks的日志（位于托盘区纸飞机图标右击-帮助-显示日志），请记得隐藏你的服务器信息。

根据你之前那提供·的方法  启动WinHTTP Web Proxy Auto-Discovery服务 奇怪但我电脑里 没有这项服务

**Comment by ZserOmega** [comment]
> 请贴一下Shadowsocks的日志（位于托盘区纸飞机图标右击-帮助-显示日志），请记得隐藏你的服务器信息。

我系统升级到专业版 就有了 但找不到指定文件

**Comment by chenshaoju** [comment]
这意味着你的系统可能损坏了。

家庭版/家庭高级版/专业版/企业版/都有这个服务的。

**Comment by ZserOmega** [comment]
> 这意味着你的系统可能损坏了。
> 
> 家庭版/家庭高级版/专业版/企业版/都有这个服务的。

很奇怪 我前天还好好的，今天就突然代理设置错误。需要重装系统吗？

**Comment by chenshaoju** [comment]
搜了一下，你可能需要将相同系统版本的注册表中的`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\WinHttpAutoProxySvc` 导出，再导入你的注册表看看能否修复。

参考：https://bbs.csdn.net/topics/392300070

**Comment by ZserOmega** [comment]
> 搜了一下，你可能需要将相同系统版本的注册表中的`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\WinHttpAutoProxySvc` 导出，再导入你的注册表看看能否修复。
> 
> 参考：https://bbs.csdn.net/topics/392300070

ok
