### ISSUE TITLE
希望使用公钥私钥进行匹配

### ISSUE THREAD

**Issue by wzzjhc** [shadowsocks/shadowsocks-windows#2570]
希望使用公钥私钥进行匹配
ss流量被阿里云识别了。现在不封ip直接禁止ss流量通行
本周周一至周五，只要开了ss的centos7服务器，再开bbr，马上就封ip。
今天周六2019年9月21日，阿里云不封ip了，改直接禁止ss流量通行。大陆以外的ip相互直接可以ss。但是大陆跟境外的ss流量，直接被拒绝通信。
-----------------------
目前来看，使用tor的onion没有受到影响。

**Comment by celeron533** [comment]
阿里云会监控实例的所有进程。和加密无关。

**Comment by wzzjhc** [comment]
我使用纯净centos 7  安装的阿里云。也一样使用不了

**Comment by 0mza987** [comment]
现在用啥都被秒封端口，IP倒是没封。SS的内容不是加密不能被识别吗？有没有网络大手子来解一下惑？

**Comment by chenshaoju** [comment]
SS加密的确没有办法被破解，但是有种东西叫流量分析，不需要知道你具体在传输什么内容，只需要分析流量特征。

对于你的问题，建议你套个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by JsonSong89** [comment]
进程分析的话,可以考虑使用docker试试

**Comment by wzzjhc** [comment]
自从阿里换下马云后，阿里云香港服务器也不能上被屏蔽的网站了。google跟youtube都不行。只是免域名备案。真的是天呐。

**Comment by icedream2linxi** [comment]
> 自从阿里换下马云后，阿里云香港服务器也不能上被屏蔽的网站了。google跟youtube都不行。只是免域名备案。真的是天呐。

我的香港服务器可以访问被屏蔽的网站。你可以换个服务器试试。

**Comment by icedream2linxi** [comment]
> 阿里云会监控实例的所有进程。和加密无关。

和阿里的监控无关，我这的ss服务器能正常用，只是我用OpenVPN加了一层。

**Comment by studentmain** [comment]
新的加密方式以及协议本身的内容可以在shadowsocks/shadowsocks-org继续讨论
