### ISSUE TITLE
突然超时无法使用，手机和别人的电脑均可使用，就我自己这台不行

### ISSUE THREAD

**Issue by chixiaome** [shadowsocks/shadowsocks-windows#2571]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7系统

### Steps you have tried / 操作步骤
阿里云的香港服务器，从几天前电脑端就无法使用，手机使用正常，其他人的电脑使用正常，自己电脑能ping通，但是无法访问谷歌等外部网站，已排除浏览器问题，换过网络环境，已排除网关限制端口等问题

### What did you expect to see? / 期望的结果
能够正常连接

### What did you see instead? / 实际结果
无法访问谷歌等

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
**配置信息：**
![image](https://user-images.githubusercontent.com/53245410/65373346-eff8f000-dcae-11e9-9e9b-d136af5c4c13.png)
**以下是日志信息：**

> [2019-09-21 20:03:48] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-09-21 20:03:49] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-09-21 20:03:49] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2019-09-21 20:03:49] connect to api.github.com:443
[2019-09-21 20:03:50] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-09-21 20:03:51] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-09-21 20:03:53] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-09-21 20:03:54] 47.240.47.72:8080 timed out
[2019-09-21 20:03:54] connect to api.github.com:443
[2019-09-21 20:03:59] 47.240.47.72:8080 timed out
[2019-09-21 20:03:59] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-09-21 20:04:04] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-09-21 20:04:06] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-09-21 20:04:06] Shadowsocks started (4.1.7.1)
[2019-09-21 20:04:06] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor

**Comment by chenshaoju** [comment]
别人正常的和你的是同一个服务器吗？

如果是，请使用这个第三方的测试软件测试从你的计算机到你的服务器端口是否能通：
https://github.com/chenshaoju/tcpportcheck

**Comment by chixiaome** [comment]
> 别人正常的和你的是同一个服务器吗？
> 
> 如果是，请使用这个第三方的测试软件测试从你的计算机到你的服务器端口是否能通：[https](https://github.com/chenshaoju/tcpportcheck) : 
> [//github.com/chenshaoju/tcpportcheck](https://github.com/chenshaoju/tcpportcheck)

![image](https://user-images.githubusercontent.com/53245410/65375990-83d9b480-dccd-11e9-8875-613a763b4658.png)
不通。。。。这样如何处理呢？？？

**Comment by chenshaoju** [comment]
请尝试联系你的服务商，更换IP后，套个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by chixiaome** [comment]
> 请尝试联系你的服务商，更换IP后，套个插件看看：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

好的，刚刚手机也连不上了，我试下换IP

**Comment by chixiaome** [comment]
还是不行。。。。。。。
服务器配置：
>{
    "server":"0.0.0.0",
    "mode":"tcp_and_udp",
    "server_port":8080,
    "local_port":1080,
    "password":"隐藏",
    "timeout":60,
    "method":"aes-256-cfb",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls;failover=104.193.88.77:443"
}
Windows配置：
![image](https://user-images.githubusercontent.com/53245410/65386461-922bdd00-dd6e-11e9-9b30-8b5b116ec28f.png)

**Comment by chixiaome** [comment]
日志：
![image](https://user-images.githubusercontent.com/53245410/65386467-a1ab2600-dd6e-11e9-8b3c-edad57541606.png)

**Comment by chenshaoju** [comment]
错了，不需要填写插件参数，以及不需要启用命令行参数。

在插件选项中填写 `obfs=http;obfs-host=www.bing.com` 即可。

**Comment by chixiaome** [comment]
> 错了，不需要填写插件参数，以及不需要启用命令行参数。
> 
> 在插件选项中填写 `obfs=http;obfs-host=www.bing.com` 即可。
那服务器配置用改嘛？
>{
"server":"0.0.0.0",
"mode":"tcp_and_udp",
"server_port":8080,
"local_port":1080,
"password":"隐藏",
"timeout":60,
"method":"aes-256-cfb",
"plugin":"obfs-server",
"plugin_opts":"obfs=tls;failover=104.193.88.77:443"
}
![image](https://user-images.githubusercontent.com/53245410/65387763-1a18e380-dd7d-11e9-989f-e4c171eb1102.png)

日志文件：
>[2019-09-22 21:00:14] Started SIP003 plugin for 47.240.36.2:8080 on 127.0.0.1:58482 - PID: 8048
[2019-09-22 21:00:14] Shadowsocks started (4.1.7.1)
[2019-09-22 21:01:06] Started SIP003 plugin for 47.240.36.2:8080 on 127.0.0.1:58518 - PID: 13552
[2019-09-22 21:01:06] Shadowsocks started (4.1.7.1)
[2019-09-22 21:04:42] Started SIP003 plugin for 47.240.36.2:8080 on 127.0.0.1:58572 - PID: 12644
[2019-09-22 21:04:42] Shadowsocks started (4.1.7.1)

**Comment by chenshaoju** [comment]
仔细看了一下，你的服务端配置是`obfs=tls`，所以你的客户端也得用TLS：`obfs=tls;obfs-host=www.bing.com`

**Comment by chixiaome** [comment]
> 仔细看了一下，你的服务端配置是`obfs=tls`，所以你的客户端也得用TLS：`obfs=tls;obfs-host=www.bing.com`

还是无法访问啊。。。。。。。。。。。。。。。。。。。我真的是醉了
![image](https://user-images.githubusercontent.com/53245410/65388649-6ca7cf00-dd80-11e9-8176-a0b16bdcf673.png)
![image](https://user-images.githubusercontent.com/53245410/65388652-729db000-dd80-11e9-8bff-7be731bdc6af.png)
![image](https://user-images.githubusercontent.com/53245410/65388658-8b0dca80-dd80-11e9-9b0b-a5eb728eac22.png)

**Comment by chenshaoju** [comment]
SS的日志中显示什么？

**Comment by chixiaome** [comment]
> SS的日志中显示什么？

SS日志：
>[2019-09-23 08:53:23] Started SIP003 plugin for 47.240.36.2:8080 on 127.0.0.1:50657 - PID: 11536
[2019-09-23 08:53:24] Shadowsocks started (4.1.7.1)
[2019-09-23 08:53:27] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 请求被中止: 未能创建 SSL/TLS 安全通道。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

>tcp通，但是还是访问不了网页

**Comment by chenshaoju** [comment]
请尝试将 mode 设置为 tcp_only 看看？

这个现象很奇怪，看起来都没问题，如果可能，请在浏览器访问你的服务器IP（ https://xxx.xxx.xxx.xxx ）能看到一个HTTPS证书错误的警告吗？

**Comment by chixiaome** [comment]
是的，能看到，然后点高级继续前往就跳转到了https://www.xxx.xxx/

**Comment by chenshaoju** [comment]
请尝试右击任务栏托盘区的纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”。
是否能提示更新成功或者没有新更新？（提示气泡应该是一个蓝底白色的惊叹号）。

如果提示错误（显示一个红底白色的叉），看一下日志里显示什么？

**Comment by chixiaome** [comment]
![image](https://user-images.githubusercontent.com/53245410/65398825-ff318800-ddeb-11e9-97ed-5451937be40c.png)
日志
>[2019-09-23 10:21:58] Checking GFWList from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
[2019-09-23 10:21:59] Detected: PAC file 'pac.txt' was created.
[2019-09-23 10:21:59] Detected: PAC file 'pac.txt' was changed.
[2019-09-23 10:21:59] System.IO.IOException: 文件“F:\VPN\Shadowsocks-4.1.7.1\ss_win_temp\user-wininet.json”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 Shadowsocks.Util.SystemProxy.Sysproxy.Save()

**Comment by chenshaoju** [comment]
这意味着你本机的SS工作没有任何问题，因为更新pac文件就是通过代理的。

如果你仍然无法上网，请尝试检查你的浏览器代理设置是否正确。

如果可能，请使用使用IE自带的浏览器访问 https://www.google.com/nrc ，看看能否打开。

**Comment by chixiaome** [comment]
你给的网址报404，但是....竟然真的能打开谷歌

**Comment by chenshaoju** [comment]
不好意思，错了……是 https://www.google.com/ncr 。

这说明你的SS目前工作是正常的，可能是由于你用的浏览器有问题。

可能是你的浏览器插件接管了代理，但是浏览器的插件设置并不正确。

**Comment by chixiaome** [comment]
我有使用浏览器代理插件SwitchyOmega，我看一下重置下，谢谢
