### ISSUE TITLE
搭好服务之后,测试软件可以使用,可是每次重启Windows10之后，就不能使用了

### ISSUE THREAD

**Issue by wangshouman** [shadowsocks/shadowsocks-windows#2572]
vultr vps ss bbr 加速 vps 正常使用 能curl youtube.com
系统：win10 
ss 客户端：最新版 
问题是：每次重启之后，就不能出去，但是在vps中能ping 通youtube.com

**Comment by chenshaoju** [comment]
请尝试使用这个第三方的工具测试从你的计算机到你的服务器端口的连通性：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836
