### ISSUE TITLE
连接不上，加了obfs还是不行

### ISSUE THREAD

**Issue by tangdouer** [shadowsocks/shadowsocks-windows#2573]
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请使用这个第三方的小工具测试从你计算机能否连接到服务器：
https://github.com/chenshaoju/tcpportcheck

如果你的服务器已经被墙了，必须得先换IP。

**Comment by tangdouer** [comment]
请问怎么更换IP呢

**Comment by chenshaoju** [comment]
你的服务器是自己搭的还是找SS服务商买的？

如果是前者，请与你的VPS服务商联系。

如果是后者，你单方面的添加一个插件是不会工作的，请与你的SS服务商联系。

**Comment by stone1222222** [comment]
刚刚让朋友帮忙搭建的服务器，10分钟就挂了
2019-09-24 02:14:58] connect to www.googleapis.com:443
[2019-09-24 02:14:59] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:14:59] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:00] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:00] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:01] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:01] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:02] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:02] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:02] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:02] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:02] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:02] 嗝 (45.63.70.214:8388) timed out
[2019-09-24 02:15:03] 嗝 (45.63.70.214:8388) timed out
下了ls的小工具显示不通，网络测试显示国内被禁，这种问题怎么办？是ip被封了吗

**Comment by Clannad-AfterStory** [comment]
这种节日封的最严还敢用啊

**Comment by chenshaoju** [comment]
请尝试不要使用 8388 默认端口，非常容易被封。

如果你的服务器是自己搭的，可以尝试套个插件：
https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by devon-ge** [comment]
> 这种节日封的最严还敢用啊

@Clannad-AfterStory 从网络安全周开始到现在，就没出去过。不知道这一次要到什么时候，至少也是10月2日了

**Comment by Clannad-AfterStory** [comment]
> > 这种节日封的最严还敢用啊
> 
> @Clannad-AfterStory 从网络安全周开始到现在，就没出去过。不知道这一次要到什么时候，至少也是10月2日了

几十块换了个新ip才用不到一个月就这么没了

**Comment by Hinmo** [comment]
这么坑，是搬瓦工吧 
------------------
Hinmo Tsang
Shenzhen, China


 




------------------ 原始邮件 ------------------
发件人: "L.R"<notifications@github.com>; 
发送时间: 2019年9月27日(星期五) 中午11:19
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [shadowsocks/shadowsocks-windows] 连接不上，加了obfs还是不行 (#2573)



  
这种节日封的最严还敢用啊
  
@Clannad-AfterStory 从网络安全周开始到现在，就没出去过。不知道这一次要到什么时候，至少也是10月2日了
  
几十块换了个新ip才用不到一个月就这么没了
 
&mdash;

**Comment by devon-ge** [comment]
> 这么坑，是搬瓦工吧 ------------------ Hinmo Tsang Shenzhen, China
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "L.R"<notifications@github.com>; 发送时间: 2019年9月27日(星期五) 中午11:19 收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [shadowsocks/shadowsocks-windows] 连接不上，加了obfs还是不行 (#2573) 这种节日封的最严还敢用啊 @Clannad-AfterStory 从网络安全周开始到现在，就没出去过。不知道这一次要到什么时候，至少也是10月2日了 几十块换了个新ip才用不到一个月就这么没了 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

找到一个小众的网站，一个月不到三刀，直接提供ss账号和动态ip，目前使用体验还不错

**Comment by Hinmo** [comment]
网速OK吗？稳不稳定，介绍下?


------------------
Hinmo Tsang
Shenzhen, China


 




------------------ 原始邮件 ------------------
发件人: "Devon Ge"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 晚上6:41
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>;
抄送: "Hinmo"<zengxw.chn@gmail.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [shadowsocks/shadowsocks-windows] 连接不上，加了obfs还是不行 (#2573)



 
这么坑，是搬瓦工吧 ------------------ Hinmo Tsang Shenzhen, China
 …
 ------------------ 原始邮件 ------------------ 发件人: "L.R"notifications@github.com; 发送时间: 2019年9月27日(星期五) 中午11:19 收件人: "shadowsocks/shadowsocks-windows"shadowsocks-windows@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [shadowsocks/shadowsocks-windows] 连接不上，加了obfs还是不行 (#2573) 这种节日封的最严还敢用啊 @Clannad-AfterStory 从网络安全周开始到现在，就没出去过。不知道这一次要到什么时候，至少也是10月2日了 几十块换了个新ip才用不到一个月就这么没了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
找到一个小众的网站，一个月不到三刀，直接提供ss账号和动态ip，目前使用体验还不错

**Comment by devon-ge** [comment]
> 网速OK吗？稳不稳定，介绍下?
> […](#)
> ------------------ Hinmo Tsang Shenzhen, China
> ------------------ 原始邮件 ------------------ 发件人: "Devon Ge"<notifications@github.com>; 发送时间: 2019年9月27日(星期五) 晚上6:41 收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>; 抄送: "Hinmo"<zengxw.chn@gmail.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [shadowsocks/shadowsocks-windows] 连接不上，加了obfs还是不行 (#2573) 这么坑，是搬瓦工吧 ------------------ Hinmo Tsang Shenzhen, China … ------------------ 原始邮件 ------------------ 发件人: "L.R"notifications@github.com; 发送时间: 2019年9月27日(星期五) 中午11:19 收件人: "shadowsocks/shadowsocks-windows"shadowsocks-windows@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [shadowsocks/shadowsocks-windows] 连接不上，加了obfs还是不行 (#2573) 这种节日封的最严还敢用啊 @Clannad-AfterStory 从网络安全周开始到现在，就没出去过。不知道这一次要到什么时候，至少也是10月2日了 几十块换了个新ip才用不到一个月就这么没了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 找到一个小众的网站，一个月不到三刀，直接提供ss账号和动态ip，目前使用体验还不错 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

网速不受限制，和访问国内网站一样。不是很稳定，我猜是定期换ip的，有时候需要握手两次才连上

**Comment by hwy-github** [comment]
介绍下，网站多少啊

**Comment by chenshaoju** [comment]
出于安全考虑（信息泄露、跑路、骗钱等原因），不建议交流机场服务商信息。

**Comment by Clannad-AfterStory** [comment]
> 这么坑，是搬瓦工吧 ------------------ Hinmo Tsang Shenzhen, China
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "L.R"<notifications@github.com>; 发送时间: 2019年9月27日(星期五) 中午11:19 收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [shadowsocks/shadowsocks-windows] 连接不上，加了obfs还是不行 (#2573) 这种节日封的最严还敢用啊 @Clannad-AfterStory 从网络安全周开始到现在，就没出去过。不知道这一次要到什么时候，至少也是10月2日了 几十块换了个新ip才用不到一个月就这么没了 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

是啊，你也用过？
