### ISSUE TITLE
更换IP后，还是连接失败，应该怎么解决呢

### ISSUE THREAD

**Issue by tangdouer** [shadowsocks/shadowsocks-windows#2576]
更换IP后，还是不行，应该怎么解决呢

**Comment by chenshaoju** [comment]
请使用这个第三方的服务测试你的服务器端口是否能通： http://ip100.info/check

**Comment by tangdouer** [comment]
国内测试：over time
国际测试：open

**Comment by chenshaoju** [comment]
说明你的新IP其实是别人用过的被墙掉的IP，你只能再换一次了。

**Comment by tangdouer** [comment]
> 说明你的新IP其实是别人用过的被墙掉的IP，你只能再换一次了。

那需要一直尝试新部署获取新IP吗

**Comment by tangdouer** [comment]
测试了多个IP都是国内 overtime 国外open

**Comment by chenshaoju** [comment]
很难说。

**Comment by tangdouer** [comment]
> 很难说。
> 
> 也可能这个IP段被墙了。

怎么判断自己加的混淆成功了呢
