### ISSUE TITLE
关于插件参数LOCAL_PORT的问题

### ISSUE THREAD

**Issue by ddgweb** [shadowsocks/shadowsocks-windows#2577]
### Shadowsocks version / 影梭版本
4.1.6

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

win10
### Steps you have tried / 操作步骤

1、编辑服务器
2、配置插件
3、配置参数
### What did you expect to see? / 期望的结果

配置的参数：-L :%SS_LOCAL_PORT% -F socks+kcp://admin:admin@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%

理论上应该根据我填写的 -L :%SS_LOCAL_PORT% 不是应该等于 我填写的 代理端口参数吗？
### What did you see instead? / 实际结果

实际上-L :%SS_LOCAL_PORT% 得到的是一个其他的端口信息，并非我在编辑服务器信息中填写的代理端口

**Comment by Stzx** [comment]
目前 `%SS_LOCAL_PORT%` 是随机获取的可用端口。

我检查了标准文档，发现应该是错误的实现了部分功能。

> Four MUST-HAVE environment variables are `SS_REMOTE_HOST`, `SS_REMOTE_PORT`, `SS_LOCAL_HOST` and `SS_LOCAL_PORT`. `SS_REMOTE_HOST` and `SS_REMOTE_PORT` are the hostname and port of the remote plugin service. `SS_LOCAL_HOST` and `SS_LOCAL_PORT` are the hostname and port of the local shadowsocks or plugin service.

或许稍后会提供 PR。

**Comment by ddgweb** [comment]
> 目前 `%SS_LOCAL_PORT%` 是随机获取的可用端口。
> 
> 我检查了标准文档，发现应该是错误的实现了部分功能。
> 
> > Four MUST-HAVE environment variables are `SS_REMOTE_HOST`, `SS_REMOTE_PORT`, `SS_LOCAL_HOST` and `SS_LOCAL_PORT`. `SS_REMOTE_HOST` and `SS_REMOTE_PORT` are the hostname and port of the remote plugin service. `SS_LOCAL_HOST` and `SS_LOCAL_PORT` are the hostname and port of the local shadowsocks or plugin service.
> 
> 或许稍后会提供 PR。

好吧，并不关心翻译的内容，我只想说，通过 -L :%SS_LOCAL_PORT%  创建了插件的进程，查看了启动参数，也能得到一个随机的代理端口，并且直接用系统127.0.0.1 代理是可以访问的。

但是用ss自己却无法访问，日志

=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

**Comment by chenshaoju** [comment]
日志中看不到任何有效内容。

你具体是用的是什么插件？

**Comment by ddgweb** [comment]
> 日志中看不到任何有效内容。
> 
> 你具体是用的是什么插件？

gost：https://github.com/ginuerzh/gost
我在手机上用别人做的插件可以使用，所以想在电脑上试试，结果一直没成功过
手机插件：https://github.com/xausky/ShadowsocksGostPlugin

**Comment by ddgweb** [comment]
> 日志中看不到任何有效内容。
> 
> 你具体是用的是什么插件？

另外，我用ss切换成全局代理，网页就会提示500，但是如果我直接用 IE代理127.0.0.1 + SS插件创建的端口，就可以正常访问

500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by chenshaoju** [comment]
我看了一下，这个的 `-L:1234` 参数提供的是一个标准的HTTP/SOCKS5代理，并不是提供一个通道（Tunnel）。

你应该在服务器上使用：
`gost -L=h2://:<你的服务器上的SS端口号>`

以及在SS客户端中启命令行参数并将插件参数设置为：
`-L:%SS_LOCAL_PORT% -F=h2://%SS_REMOTE_HOST%:%SS_REMOTE_PORT%`

**Comment by ddgweb** [comment]
> EDIT：不好意思，我还没研究清楚，和想象的不一样。

额。。我已经看到你的回复，并且想说，我测试了你说的方法，也并不奏效。
因为我手机上配置好了ss的插件以后，是可以正常访问的，但是到了pc上就不行了

**Comment by ddgweb** [comment]
> EDIT：不好意思，我还没研究清楚，和想象的不一样。

我来举个例子吧。 
服务器：
gost -L=socks+kcp://chacha20:123456@:1080

客户端：
SS，配置参数：
-L :%SS_LOCAL_PORT% -F socks+kcp://chacha20:123456@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%

**Comment by chenshaoju** [comment]
gost 好像是实现了一套属于自己的代理系统，虽然可以兼容Shadosocks，但是可能无法以插件方式运行。

我看了一下官方的文档，如果你的服务端使用的是 gost 搭建的服务端的话，那么你的客户端也得使用 gost 的客户端，而不能使用 Shadowsocks for Windows 作为插件方式使用。

就以你的服务器的命令行为例， socks （这个我没翻到具体是什么，socks5?）+kcp，代表你需要通过kcp传输socks协议。

既然你用的是 socks ，那么 Shadowsocks for Windows 是没有办法直接处理socks协议的。

所以，如果你的服务器是这样填写的话：
`gost -L ss+kcp://chacha20:123456@:8338`

那么客户端可以填写为：
`-L=:%SS_LOCAL_PORT% -F=kcp://%SS_REMOTE_HOST%:%SS_REMOTE_PORT%`

因为Shadowsocks会处理属于 ss 部分的协议。

**Comment by ddgweb** [comment]
> gost 好像是实现了一套属于自己的代理系统，虽然可以兼容Shadosocks，但是可能无法以插件方式运行。
> 
> 我看了一下官方的文档，如果你的服务端使用的是 gost 搭建的服务端的话，那么你的客户端也得使用 gost 的客户端，而不能使用 Shadowsocks for Windows 作为插件方式使用。
> 
> 就以你的服务器的命令行为例， socks （这个我没翻到具体是什么，socks5?）+kcp，代表你需要通过kcp传输socks协议。
> 
> 既然你用的是 socks ，那么 Shadowsocks for Windows 是没有办法直接处理socks协议的。
> 
> 所以，如果你的服务器是这样填写的话：
> `gost -L ss+kcp://chacha20:123456@:8338`
> 
> 那么客户端可以填写为：
> `-L=:%SS_LOCAL_PORT% -F=kcp://%SS_REMOTE_HOST%:%SS_REMOTE_PORT%`
> 
> 因为Shadowsocks会处理属于 ss 部分的协议。

如果用ss协议，不用插件，直接填写IP端口，参数都不用，就能连上了。
我的理解ss+插件，不是已经启动一个gost客户端，也能得到端口啊，ss不是代理插件的gost端口去访问吗。。

**Comment by ddgweb** [comment]
> gost 好像是实现了一套属于自己的代理系统，虽然可以兼容Shadosocks，但是可能无法以插件方式运行。
> 
> 我看了一下官方的文档，如果你的服务端使用的是 gost 搭建的服务端的话，那么你的客户端也得使用 gost 的客户端，而不能使用 Shadowsocks for Windows 作为插件方式使用。
> 
> 就以你的服务器的命令行为例， socks （这个我没翻到具体是什么，socks5?）+kcp，代表你需要通过kcp传输socks协议。
> 
> 既然你用的是 socks ，那么 Shadowsocks for Windows 是没有办法直接处理socks协议的。
> 
> 所以，如果你的服务器是这样填写的话：
> `gost -L ss+kcp://chacha20:123456@:8338`
> 
> 那么客户端可以填写为：
> `-L=:%SS_LOCAL_PORT% -F=kcp://%SS_REMOTE_HOST%:%SS_REMOTE_PORT%`
> 
> 因为Shadowsocks会处理属于 ss 部分的协议。

我查看了进程，gost已插件的方式，是能运行，并且有端口的，就是ss无法访问，如果换IE手动设置代理，就可以。很奇怪，不知道是不是BUG，所以来这里吐个槽

**Comment by chenshaoju** [comment]
这更让人困惑了……

切换到IE手动代理，具体是怎么切换的？

切换到了gost的本地端口，还是切换到了ss的本地代理端口？

**Comment by ddgweb** [comment]
> 这更让人困惑了……
> 
> 切换到IE手动代理，具体是怎么切换的？
> 
> 切换到了gost的本地端口，还是切换到了ss的本地代理端口？

就是用浏览器设置代理，切gost的本地端口就能访问，切ss代理端口就不行

**Comment by ddgweb** [comment]
> 这更让人困惑了……
> 
> 切换到IE手动代理，具体是怎么切换的？
> 
> 切换到了gost的本地端口，还是切换到了ss的本地代理端口？

令人困惑的是，gost是根据ss插件启动参数启动的，理论上，ss能正常启动插件，也能设置成功参数，咋SS自己的代理端口就不能用呢

**Comment by chenshaoju** [comment]
因为gost本地服务端口提供的是socks代理，而不是ss的协议。

所以当ss尝试连接gost的本地服务端口时，自然连接不上。

所以，你连接gost的端口可以工作，但是连ss的端口不工作。

**Comment by ddgweb** [comment]
> 因为gost本地服务端口提供的是socks代理，而不是ss的协议。
> 
> 所以当ss尝试连接gost的本地服务端口时，自然连接不上。
> 
> 所以，你连接gost的端口可以工作，但是连ss的端口不工作。

但是，我做了一些尝试，比如，在服务端更改协议为 ：gost -L ss://chacha20:123456@:8338
经测试，SS 可以直接以ip+端口配置加密方式就能连接成功；但是另外以单独的gost插件+命令参数的方式则无法连接，这样是什么原因呢？

**Comment by chenshaoju** [comment]
因为当你使用 ss:// 启动服务器时，此时你的服务端就是一个标准的Shadowsocks服务器。

插件理论上可以，但是你这个方法是在绕弯路，为什么客户端不直接使用 gost ？

**Comment by FlyFlame** [comment]
请问楼上的大佬，最后是怎么解决的呢？我现在也是类似的情况，VPS上用gost搭的，现在本地用gost + shadowsocks for windows一直报错。

- 系统代理：
`127.0.0.1:1080`

- ss配置：
```
{
  "version": "4.4.1.0",
  "configs": [
    {
      "server": "127.0.0.1",
      "server_port": 1984,
      "password": "Shadowsocks0123",
      "method": "aes-256-gcm",
      "timeout": 5,
      "warnLegacyUrl": false
    }
  ],
  "onlineConfigSource": [],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "firstRun": false,
  "localPort": 1080,
  "portableMode": true,
  "showPluginOutput": false,
  "pacUrl": "",
  "useOnlinePac": false,
  "secureLocalPac": true,
  "regeneratePacOnUpdate": true,
  "autoCheckUpdate": false,
  "checkPreRelease": false,
  "skippedUpdateVersion": "",
  "isVerboseLogging": true,
  "isIPv6Enabled": false,
  "generateLegacyUrl": false,
  "geositeUrl": "",
  "geositeSha256sumUrl": "",
  "geositeDirectGroups": [
    "private",
    "cn",
    "geolocation-!cn@cn"
  ],
  "geositeProxiedGroups": [
    "geolocation-!cn"
  ],
  "geositePreferDirect": false,
  "userAgent": "ShadowsocksWindows/$version",
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "127.0.0.1",
    "proxyPort": 1080,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  },
  "WebProxy": {
    "_BypassOnLocal": false,
    "_ProxyAddress": "http://127.0.0.1:1080",
    "_BypassList": null,
    "_UseDefaultCredentials": false
  }
}
```

- gost启动命令：
`.\gost_windows_amd64.exe -D -L ss://aes-256-gcm:Shadowsocks0123@:1984 -F 'https://wharf:Gost0123:barren.xyz:443'`

- 但是一直报错：
```

```
