### ISSUE TITLE
安装后出现这种情况

### ISSUE THREAD

**Issue by Gipsymoth6** [shadowsocks/shadowsocks-windows#2578]
新安装打开后出现这种情况

已经安装了.net

> 

System.ComponentModel.Win32Exception (0x8000405): 系统找不到指定的文件。

System.Diagnostic.process.StartWithCreateProcess(ProcessStartInfo StartInfo) at System.Diagnostic.Start() 
at shadowsocks.controller.service.sip003Plugin.startIfNeeded()
at shadowsocks.controller.shadowsocksController.GetPluginLocalEndPointIfConfigured(server server)
at .shadowsocks.controller.shadowsocksController.Reload()**

>

**Comment by Gipsymoth6** [comment]
加了一个v2ray plugin

**Comment by chenshaoju** [comment]
这意味着你的SS客户端找不到你的插件。

假设你的插件名叫 `ck-client.exe` ，如果你的插件放在 Shadowsocks.exe 的所在目录，那么直接在插件程序输入插件的文件名即可`ck-client.exe`，如果 `ck-client.exe` ，如果放置于 Shadowsocks.exe 的 plugins 目录下（举例），那么则填写为 `plugins\ck-client.exe`

**Comment by imba-tjd** [comment]
在保存设置的时候验证一下文件是否存在怎么样？

**Comment by Gipsymoth6** [comment]
> 这意味着你的SS客户端找不到你的插件。
> 
> 假设你的插件名叫 `ck-client.exe` ，如果你的插件放在 Shadowsocks.exe 的所在目录，那么直接在插件程序输入插件的文件名即可`ck-client.exe`，如果放置于 Shadowsocks.exe 的 plugins 目录下（举例），那么则填写为 `plugins\ck-client.exe`

和您说的一样。谢谢。
