### ISSUE TITLE
obfs安装过程

### ISSUE THREAD

**Issue by 0mza987** [shadowsocks/shadowsocks-windows#2579]
### Shadowsocks version / 影梭版本
客户端：Shadowsocks Windows 4.1.6

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
服务器端： Ubuntu 18.04
客户端： Win10

### Steps you have tried / 操作步骤
**服务器端：**
1) 安装obfs
![image](https://user-images.githubusercontent.com/2572521/65593644-7ff6ac80-dfc3-11e9-8f55-64e3ad9430e0.png)

2) 修改 ss json配置文件，添加下面两行：
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls;failover=104.193.88.77:443"

3) 重启ss服务：
`sudo /etc/init.d/shadowsocks restart`

**客户端**
1) 下载 obfs-local并解压至shadowsocks.exe目录下：
![image](https://user-images.githubusercontent.com/2572521/65593813-e4b20700-dfc3-11e9-9165-02dd99c14db1.png)

2) 配置插件参数：
![image](https://user-images.githubusercontent.com/2572521/65593856-fc898b00-dfc3-11e9-94be-0642bb6bf186.png)

结果：
依然连不上外网，这个IP是我新换的而且ssh连接中才能进行上述的服务器端的操作，所以ip应该是没问题的，不知道是不是插件配置哪步出了问题？请教

**Comment by chenshaoju** [comment]
1.服务器上的shadowsocks-libev是否已经启动？
2.请使用第三方的服务测试你的端口 http://ip100.info/check 。

**Comment by 0mza987** [comment]
![image](https://user-images.githubusercontent.com/2572521/65597578-09aa7800-dfcc-11e9-98cf-02f9dda2510a.png)

看起来应该是开放的

服务器端是开启状态因为我已经restart过了，我的shaodowsocks 服务器是用秋水逸冰的一键搭建脚本搭建的，不知道这个有没有影响，我一直用的这个版本，只是最近端口不停被封，就想说加个插件试试

**Comment by 0mza987** [comment]
**成功了**！我把参数位置换了下，使用命令行参数就成功了

`ss-local -c config.json --plugin obfs-local --plugin-opts "obfs=tls;obfs-host=www.baidu.com"`

![image](https://user-images.githubusercontent.com/2572521/65601825-69595100-dfd5-11e9-844e-82c99b856709.png)

**Comment by 0mza987** [comment]
不对，好像只是单纯的插件没起作用，用了一会儿端口又被封了，晕了

**Comment by chenshaoju** [comment]
我没看懂你这样配置的目的……

你先看一下你的服务端，确定进程列表里有个叫 obfs-server 的进程？

如果有，你能把你的服务端的 config.json 贴上来吗？记得隐藏密码和IP。

**Comment by chenshaoju** [comment]
另外，如果你用的是Debian，你一行命令就能安装 simple-obfs：
`sudo apt-get install simple-obfs`

**Comment by 0mza987** [comment]
1. 我想要安装插件，但不确定安装的步骤对不对，具体我的步骤写在第一楼了

2. 我看了下服务端确实没有 obfs-server这个进程，所以如何启动这个进程呢？
![image](https://user-images.githubusercontent.com/2572521/65604363-eab2e280-dfd9-11e9-9df3-b1e7ce15c5b6.png)

3. 我使用的是 Ubuntu 18.04

4. 我运行了你说的 `sudo apt-get install simple-obfs`， 然后再查看包含shadowsocks的进程，结果如下
![image](https://user-images.githubusercontent.com/2572521/65604448-1c2bae00-dfda-11e9-96e8-1a6fd350557b.png)

5. 在我运行 sudo apt-get install simple-obfs 之前，我只有上图中的第一条进程，没有第二条

6. 我以前（上图第一条进程）的配置文件( /etc/shadowsocks.json)：
![image](https://user-images.githubusercontent.com/2572521/65604735-89d7da00-dfda-11e9-91f6-f91b839efdf9.png)

运行sudo apt-get install simple-obfs 之后出现的进程的配置文件( /etc/shadowsocks-libev/config.json):

![image](https://user-images.githubusercontent.com/2572521/65604860-ba1f7880-dfda-11e9-9b5c-4314f4a588c9.png)

所以感觉好像是两个不同的ss-server，所以我之前的无法work么？

**Comment by chenshaoju** [comment]
是，你的服务器上运行了两个ss，一个是python的，另一个是libev的。

你需要确定你目前使用的是哪个版本的SS，再进行配置。

个人推荐使用libev。

**Comment by 0mza987** [comment]
好的谢谢，那我还是想确认一下，我在客户端的配置是对的吗？ 也就是再ss客户端设置设置插件程序和插件选项的步骤

以及那个命令行参数是要同时设置还是和上面那种二选一？

**Comment by chenshaoju** [comment]
顶楼的第二张图是对的。

**Comment by 0mza987** [comment]
还有个问题是我现在貌似已经运行着两个 ss-server了，但是也没有出现obfs-server 的进程，这个进程是要手动启动么？

**Comment by chenshaoju** [comment]
不，是自动的，前提是你的 ss-server 的 config.json 配置文件需要正确配置。

如果你搞不清这个配置文件在哪里，且你的系统是Debian的话，你可以查看`/etc/default/shadowsocks-libev` 文件中的 `CONFFILE` 字段。

**Comment by 8x8-64** [comment]
不要装python版的，早不更新了，会被重放攻击检测出来的
