### ISSUE TITLE
The autostart function of SS winclient 2.5.2&2.5.1 cannot work properly.

### ISSUE THREAD

**Issue by yuan78** [shadowsocks/shadowsocks-windows#258]
The autostart function of SS winclient 2.5.2&2.5.1 cannot work properly.
Even you choose autostart option, But it doesn't work when your PC actually restarted.

**Comment by clowwindy** [comment]
Can anyone else confirm this problem?

**Comment by chenshaoju** [comment]
Can't confirm.
Please make sure your registry key "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run\" is writable.
Some security software may block this action.

![reg](https://cloud.githubusercontent.com/assets/515763/9163573/f8404a20-3f7c-11e5-8f0b-e785a054494f.png)

**Comment by 476210180** [comment]
Autostart works good on Windows 7 with administrator rights.
But recently I tired using SS on Windows 8.1 Pro, the autostart did not function.

Pls excuse my poor English.

**Comment by chenshaoju** [comment]
My Windows 7 is UAC Enable,And using Password authentication (not just click Allow,Need password).

I Don't have Windows 8.1 system,So I test in Windows 10 (UAC Enabled),Not have this issue.

Maybe is your directory have non-English character,Try use a full English directory name?

![screenshot](https://cloud.githubusercontent.com/assets/515763/9168933/1f8a7fd8-3f8c-11e5-9935-e5d33700ee13.png)

**Comment by yuan78** [comment]
Now the autostart function of SS winclient recovered on my win7 today!  Just like a miracle!
I don't know what's the reason, it seems that it's not the problem of SS win client.
