### ISSUE TITLE
不能连接节点

### ISSUE THREAD

**Issue by dhueys** [shadowsocks/shadowsocks-windows#2581]
请按照以下格式描述你的问题，描述不清的问题将会被关闭。
-->

### Shadowsocks version / 影梭版本
4.1.7.1

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

一直无法翻墙，不知道哪里出现问题了。

**Comment by chenshaoju** [comment]
有日志吗？

请右击托盘区的纸飞机图标，选择帮助，显示日志。

**Comment by dhueys** [comment]
> 
> 
> 有日志吗？
> 
> 请右击托盘区的纸飞机图标，选择帮助，显示日志。

![圖片](https://user-images.githubusercontent.com/38090383/65814810-6d75b080-e219-11e9-8285-56caf1333667.png)

謝謝回復，查過了，是節點的問題，換過節點就可以翻墻了，但是Firefox瀏覽器卻怎麽也不能瀏覽外網

**Comment by chenshaoju** [comment]
请维持Firefox的“使用系统 Proxy 设定”。

请右击任务栏托盘区的纸飞机图标，指向系统代理，并选中“PAC模式”，然后再次右击，选择PAC，再点击“从GFWList更新本地PAC”。

然后再试。

**Comment by dhueys** [comment]
> 
> 
> 请维持Firefox的“使用系统 Proxy 设定”。
> 
> 请右击任务栏托盘区的纸飞机图标，指向系统代理，并选中“PAC模式”，然后再次右击，选择PAC，再点击“从GFWList更新本地PAC”。
> 
> 然后再试。

pac更新成功，但是不行呢，還是Firefox瀏覽器不能上外網，電報和Email都可以
![圖片](https://user-images.githubusercontent.com/38090383/65816048-b9305600-e229-11e9-8018-4f195f7ef888.png)
![圖片](https://user-images.githubusercontent.com/38090383/65816075-ec72e500-e229-11e9-9d3f-79363be017b4.png)
![圖片](https://user-images.githubusercontent.com/38090383/65816067-d2d19d80-e229-11e9-8d4f-dba07d9a6ded.png)
![圖片](https://user-images.githubusercontent.com/38090383/65816083-00b6e200-e22a-11e9-92e8-a96fa7f23aa1.png)

**Comment by chenshaoju** [comment]
你需要退出你的Firefox，然后重新开启。

**Comment by dhueys** [comment]
> 
> 
> 你需要退出你的Firefox，然后重新开启。

已重啓，還是不行。

![圖片](https://user-images.githubusercontent.com/38090383/65816201-6c4d7f00-e22b-11e9-8c79-ba82fec2bb92.png)

**Comment by chenshaoju** [comment]
此问题未知，你是通过拨号连接连接互联网的（如PPPoE），还是通过普通的局域网直接上网？

如果是前者，请检查你的拨号连接名称，是否为“宽带网络”之类的中文，如果是，请修改为英文看看。

**Comment by dhueys** [comment]
> 
> 
> 此问题未知，你是通过拨号连接连接互联网的（如PPPoE），还是通过普通的局域网直接上网？
> 
> 如果是前者，请检查你的拨号连接名称，是否为“宽带网络”之类的中文，如果是，请修改为英文看看。

中文英文有關係嗎？

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2041

**Comment by dhueys** [comment]
> 
> 
> #2041

謝謝，還真是這個問題，可以翻墻了。
