### ISSUE TITLE
windows版本哪个AES算法支持硬件加速？

### ISSUE THREAD

**Issue by 0x112** [shadowsocks/shadowsocks-windows#2584]
我知道服务端的libev版的AEAD系的加密算法只有AES-256-GCM是支持硬件加速的，客户端的windows版会不会也是这样？

**Comment by chenshaoju** [comment]
AES-xxx-GCM均支持硬件加速，相见：https://github.com/shadowsocks/shadowsocks-windows/commit/5d75e19c269bee61c47324c33a85b00bf2528579
