### ISSUE TITLE
IP没有被封，已更改端口，但是进入网页显示“此网站无法提供安全连接，发送的响应无效”

### ISSUE THREAD

**Issue by Stephen2252** [shadowsocks/shadowsocks-windows#2586]
### Shadowsocks version / 影梭版本
最新版本
### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10, 有相应的.NET框架

### Steps you have tried / 操作步骤
输入SS账号，Pac模式科学上网

### What did you expect to see? / 期望的结果
能够科学上网

### What did you see instead? / 实际结果

![image](https://user-images.githubusercontent.com/40737041/65825926-7913b680-e2af-11e9-8e82-726be78b73be.png)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![image](https://user-images.githubusercontent.com/40737041/65825936-8e88e080-e2af-11e9-8190-6b729854e988.png)

![image](https://user-images.githubusercontent.com/40737041/65825944-a5c7ce00-e2af-11e9-965f-f1be14e9d92d.png)

![image](https://user-images.githubusercontent.com/40737041/65825954-b24c2680-e2af-11e9-87fd-150b9c8cfab5.png)

**Comment by chenshaoju** [comment]
请尝试使用这个第三方的服务测试你的服务器端口是否能通：http://ip100.info/check

请尝试使用这个第三方的小工具测试从你的计算机到你的服务器是否能通： http://ip100.info/check

**Comment by Stephen2252** [comment]
![image](https://user-images.githubusercontent.com/40737041/65948508-fc2e3b80-e46c-11e9-889a-4902bd3d6fbb.png)
![image](https://user-images.githubusercontent.com/40737041/65948541-08b29400-e46d-11e9-820b-5c03c707011d.png)
![image](https://user-images.githubusercontent.com/40737041/65948610-2849bc80-e46d-11e9-8334-5de4185e3dbe.png)

**Comment by chenshaoju** [comment]
请确保你的加密方式、密码等信息正确。

请仔细检查你的服务端配置和客户端配置。

**Comment by Stephen2252** [comment]
额，只是配置不正确的问题吗

**Comment by chenshaoju** [comment]
从你的情况来看，有很高的可能性是配置不正确，或者和你的服务器的配置不一致导致的。

比如，密码、加密方式等。

**Comment by Stephen2252** [comment]
额，影梭账号的密码和使用KiwiVM登录ubuntu终端的密码一样啊，
如何检查密码、加密方式是否正确。

**Comment by chenshaoju** [comment]
如果你用的是Shadowsocks-libev，请检查 /etc/shadowsocks-libev/config.json 文件。

你可以在登陆后，使用这个命令查看：
`cat /etc/shadowsocks-libev/config.json`

**Comment by maplehsu** [comment]
![image](https://user-images.githubusercontent.com/4917754/66249369-b3c09780-e764-11e9-827d-d97f9dd9851d.png)
qing'wen请问这个是什么情况被墙了吗 请求超时，但是22端口 和ip测试都没有问题

**Comment by Stephen2252** [comment]
> 如果你用的是Shadowsocks-libev，请检查 /etc/shadowsocks-libev/config.json 文件。
> 
> 你可以在登陆后，使用这个命令查看：
> `cat /etc/shadowsocks-libev/config.json`

我用的是win10系统啊，不是 Linux

**Comment by chenshaoju** [comment]
*你可以再登陆你的服务器后，使用上面的命令查看你的配置情况。

**Comment by aleafboat** [comment]
me to

**Comment by bianheng** [comment]
> > 如果你用的是Shadowsocks-libev，请检查 /etc/shadowsocks-libev/config.json 文件。
> > 你可以在登陆后，使用这个命令查看：
> > `cat /etc/shadowsocks-libev/config.json`
> 
> 我用的是win10系统啊，不是 Linux

服务器：检查端口，检查ip，检查配置，检查服务
客户端：检查配置，检查开启状态
