### ISSUE TITLE
vultr的服务器安装了shadwsocks服务端，但是中国国内的客户端连接不上

### ISSUE THREAD

**Issue by zhuerzhuer** [shadowsocks/shadowsocks-windows#2587]
在vultr上买了个服务器，安装了shadowsocks服务端，但是从国内连接不上，一直timeout，试了一下发现也ping不通服务器，但是服务器能ping通国内的网站，我想问一下，是不是ping不通的服务器，shadowsocks是不是就一定不能建立连接。下面是连接服务器报错的日志：

[2019-09-29 18:37:11] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请尝试使用这个第三方的服务测试你的服务器的连通情况：http://ip100.info/check

如果国内不通国外通，说明你的服务器被墙了；如果国内国外都不通，说明你的配置有误。

**Comment by Pantr0y** [comment]
恩，9月底那会儿我也出现了这样的情况，基本和你的现象一致，猜测可能和过节有关系，被墙了。

昨天我又在V站上建了两个服务器，阿姆斯特丹和硅谷的，到现在了一直都还能用，youtube什么的速度也都很好。

**Comment by zhuerzhuer** [comment]
问一下，是不是必须要从国内ping得通的地址才能搭建ss吗



------------------ 原始邮件 ------------------
发件人: "PC"<notifications@github.com>; 
发送时间: 2019年10月5日(星期六) 中午11:38
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>; 
抄送: "gzl"<897242796@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shadowsocks/shadowsocks-windows] vultr的服务器安装了shadwsocks服务端，但是中国国内的客户端连接不上 (#2587)




恩，9月底那会儿我也出现了这样的情况，基本和你的现象一致，猜测可能和过节有关系，被墙了。
 
昨天我又在V站上建了两个服务器，阿姆斯特丹和硅谷的，到现在了一直都还能用，youtube什么的速度也都很好。

**Comment by zhuerzhuer** [comment]
我刚刚在阿姆斯特丹建了一个vps，能ping通了，非常感谢你哈




------------------ 原始邮件 ------------------
发件人: "PC"<notifications@github.com>; 
发送时间: 2019年10月5日(星期六) 中午11:38
收件人: "shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com>; 
抄送: "gzl"<897242796@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shadowsocks/shadowsocks-windows] vultr的服务器安装了shadwsocks服务端，但是中国国内的客户端连接不上 (#2587)




恩，9月底那会儿我也出现了这样的情况，基本和你的现象一致，猜测可能和过节有关系，被墙了。
 
昨天我又在V站上建了两个服务器，阿姆斯特丹和硅谷的，到现在了一直都还能用，youtube什么的速度也都很好。

**Comment by yang8301000** [comment]
請問若是使用snapshot重建一個server，那麼原本終端機內通過ssh root@的客戶端設置是否需要卸載再跑一次腳本?

**Comment by nth2say** [comment]
sometimes try another port will also help.
