### ISSUE TITLE
SS开始能wifi win10能连接上 过会就断了 然后换手机热点又可以了一直这样怎么救

### ISSUE THREAD

**Issue by miller0926** [shadowsocks/shadowsocks-windows#2588]
![image](https://user-images.githubusercontent.com/31638550/65845308-52678580-e36c-11e9-8381-f8cd2ab659da.png)

**Comment by chenshaoju** [comment]
你的服务端是自己搭建的，还是找服务商（机场）购买的？

如果是你自己搭建的，请尝试套个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836
