### ISSUE TITLE
目前项目中的代码编译不通过, 报错来自于`View\QRCodeForm.cs`, line 72

### ISSUE THREAD

**Issue by xqin** [shadowsocks/shadowsocks-windows#259]
`https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/View/QRCodeForm.cs`

line 72: `GenQR((sender as ListBox)?.SelectedValue.ToString());`

去掉`?`号后, 编译通过.

谁能解释一下这个`?`号在这里的意思是?  @JeffreyZhang105

**Comment by septs** [comment]
https://msdn.microsoft.com/en-us/library/1t3y8s4s.aspx

**Comment by xqin** [comment]
编译错误信息截图: http://g.hiphotos.baidu.com/image/pic/item/e850352ac65c103895866eb2b4119313b17e89c2.jpg

很明显这里的 `?` 号不是用于声明 `Nullable` 类型的变量的.

**Comment by JeffreyZhang105** [comment]
这个不同于Nullable Types，而是空值判断操作符，C#6.0引入的。
https://msdn.microsoft.com/en-us/magazine/dn802602.aspx
不好意思，只顾自己省事，害得大家编译不过了

**Comment by code2u** [comment]
同样问题，不改一下吗？还是要换VS版本才行？

**Comment by icylogic** [comment]
[Null-conditional Operators](https://msdn.microsoft.com/en-us/library/dn986595.aspx) 需要 c#6.0
vs2013 可能需要安装 Roslyn
建议换到 vs2015

**Comment by code2u** [comment]
太新的东西感觉还是不要引入为好，vs2015才出来没几天啊。而且这种功能也没影响到性能、可读性什么的吧？
如C++最新标准，gcc之类的编译器都是很长时间过后才支持的啊

**Comment by clowwindy** [comment]
VS2015 和 C# 6.0 好像到目前还没发现明显的问题，大家有发现什么问题吗？

**Comment by icylogic** [comment]
@code2u 我倒是觉得无所谓，这个"太新的东西"是为开发者服务的，提高开发效率，而且像 Null-conditional Operators 这种明显能减少 BUG，(目前 DEBUG OUTPUT 还能看到一些 Null Pointer Exception 不影响用户平台兼容性，我觉得 TCPRelay 里使用这个特性应该能避免一些)，工程文件已经写死 target 是 .Net 4.0 Client。

C++最新标准以及编译器，对应在这里是 C# 和 Roslyn，我们不是在写 Roslyn，而是在主流编译器 Roslyn (g++/clang++) 已经完整支持 c#6.0 (c++11) 情况下使用这些特性提高效率和减少 BUG。

**Comment by code2u** [comment]
追新这种，反正除非功能重大升级，一般不追，利弊很难说，对C#不熟，不好说。
还好vs2015com版本不要钱，否则就惨了。

**Comment by icylogic** [comment]
嗯。我觉得根据实际情况，看一下代码的主要贡献者的意见吧，主要是他们方便就好。然后最好在项目属性和 Readme 里说明一下。

**Comment by code2u** [comment]
@icylogic 说到你刚给的例子，请教下，”?“表达式不行吗？
 (_currentServer == null)?_currentServer:null
这样。
没看出优势嘛

**Comment by icylogic** [comment]
@code2u 请看先我给的两个链接，有更多例子。
`int? count = customers?[0]?.Orders?.Count();`
`PropertyChanged?.Invoke(e)`
..

**Comment by code2u** [comment]
@icylogic 后面那个例子倒是比较有用，代码确实简洁不少。对C#不熟，哈，学习了。

**Comment by clowwindy** [comment]
如果没有其它的原因，环境就定为 VS2015 了。
