### ISSUE TITLE
校园网用网线直连宿舍端口ss无法翻墙，连接学校wifi

### ISSUE THREAD

**Issue by doothdusi** [shadowsocks/shadowsocks-windows#2595]
本人用的vultr，选的日本服务器。
使用宿舍端口后pac模式国内网页畅通，翻墙的都打不开。使用校园网wifi能翻墙。
请问是我使用端口时的IP被封了吗。
谢谢。

**Comment by doothdusi** [comment]
> 本人用的vultr，选的日本服务器。
> 使用宿舍端口后pac模式国内网页畅通，翻墙的都打不开。使用校园网wifi能翻墙。
> 请问是我使用端口时的IP被封了吗。
> 谢谢。

使用xshell能连接vultr服务器

**Comment by chenshaoju** [comment]
看起来是的，手机共享热点也可以的话，那么说明是你的宿舍端口存在屏蔽。

**Comment by doothdusi** [comment]
> 看起来是的，手机共享热点也可以的话，那么说明是你的宿舍端口存在屏蔽。

请问有什么办法绕开这种屏蔽吗，比如在服务器设置些针对措施什么的。

**Comment by chenshaoju** [comment]
你可以尝试换一个端口看看，比如 443 。

**Comment by doothdusi** [comment]
> 你可以尝试换一个端口看看，例如443。

感谢，换成443成功使用校园网的宿舍接口上网。
不过同时也发现手机用的移动数据上不了了- -，这是运营商的某些策略封了我的IP吗。

**Comment by chenshaoju** [comment]
有可能，也可能是你没有修改你的配置……请仔细检查配置情况。

**Comment by yegram** [comment]
我的也是，一会能一会不能
