### ISSUE TITLE
为什么SS连校园网无法翻墙，一切成手机热点就可以？

### ISSUE THREAD

**Issue by MurphyQT** [shadowsocks/shadowsocks-windows#2596]
手机shadowrocket不连V*PN的情况下开热点，电脑连上手机热点就可以翻，电脑一切回校园网就不行？一开始还觉得是校园网的问题，后来发现iPad上shadowsorcket+校园网可以上。。。请问这是什么情况？

**Comment by chenshaoju** [comment]
你好，Shadowrocket不是Shadowsocks for Windows的一部分。

**Comment by MurphyQT** [comment]
> 你好，Shadowrocket不是Shadowsocks for Windows的一部分。

嗯嗯，我知道。只是想强调下V*PS应该是没被墙的。

**Comment by chenshaoju** [comment]
你的意思是，电脑上用不了 Shadowsocks for Windows吗？

如果是，日志中显示什么？你可以右击托盘区的纸飞机图标，选择帮助，再点击显示日志。

**Comment by MoYiai** [comment]
路过表示我也没办法连校园网用电脑翻墙。
