### ISSUE TITLE
Edit Pac File menu not works for me

### ISSUE THREAD

**Issue by yfdyh000** [shadowsocks/shadowsocks-windows#26]
It always to open explorer (an Library window).
I use QTTabBar 1024 Beta 2 on Win8.1, maybe it blocked the (hook explorer), but I suspect that is unstandard implementation cause this.

**Comment by snsnsjsn** [comment]
i have encounter same problem，my system is win10 and have qttabbar
![image](https://user-images.githubusercontent.com/11435527/51322744-3dc6b400-1aa1-11e9-9879-70cdf92a063c.png)

**Comment by chenshaoju** [comment]
It's your Shadowsocks.exe in non-English character name folder

**Comment by snsnsjsn** [comment]
> It's your Shadowsocks.exe in non-English character name folder?

no ,have change directory to d: disk , in english folders ,still have this problem 
![image](https://user-images.githubusercontent.com/11435527/51363347-879bb280-1b12-11e9-9b70-ea5183fc1161.png)


maybe need reboot windows?? i will try to test.

**Comment by snsnsjsn** [comment]
我用你上面的命令是没有问题的：
explorer.exe D:\ThinkPad\Download\program\网络工具\Shadowsocks-4.1.2
![image](https://user-images.githubusercontent.com/11435527/52931325-edd05b00-3386-11e9-9ad4-569e01f8b60a.png)
![image](https://user-images.githubusercontent.com/11435527/52931330-f032b500-3386-11e9-8e46-cb135bc3b6c2.png)

 但是从 shadowsokcs 编辑本地pac还是跳转到 win10的库目录
![image](https://user-images.githubusercontent.com/11435527/52931394-1d7f6300-3387-11e9-9589-81b3ec18afef.png)


上面我演示是中文目录，但问题不是中文目录引起的，因为我之前一直用中文目录是没有问题的。
