### ISSUE TITLE
Shadowsocks error message.

### ISSUE THREAD

**Issue by Bdl-1989** [shadowsocks/shadowsocks-windows#2600]
Hi,

I meet these messages. what can i do for them?

Thanks

![image](https://user-images.githubusercontent.com/48614612/66271915-149bbd00-e896-11e9-9991-35927bfed6a4.png)

**Comment by chenshaoju** [comment]
What your shadowsocks version?

Please try newest: https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by Bdl-1989** [comment]
> What your shadowsocks version?
> 
> Please try newest: https://github.com/shadowsocks/shadowsocks-windows/releases

Hi,
I use the latest version.
I think it is fine now after I re-boot my system and it might be blocked by 360.
Thx.
