### ISSUE TITLE
Hope release native 64-bit program

### ISSUE THREAD

**Issue by Vndroid** [shadowsocks/shadowsocks-windows#2601]
### Shadowsocks version / 影梭版本

v4.1.6

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows 10 Pro for Workstations 

### Steps you have tried / 操作步骤

None

### What did you expect to see? / 期望的结果

I hope to use native 64-bit production as soon as possible.

### What did you see instead? / 实际结果

None

**Comment by chenshaoju** [comment]
There are some external libraries that are 32-bit, It unable compiling as 64-bit.

For more info: https://github.com/shadowsocks/shadowsocks-windows/issues/1662
