### ISSUE TITLE
No Network in Shadowsocks, long time...

### ISSUE THREAD

**Issue by PerseusAT** [shadowsocks/shadowsocks-windows#2602]
I was so happy with Shadowsocks until the end of September. I live and work in China and saw Netflix. Nothing works anymore ... When will Shadowsocks work again? Or am I doing something wrong. Please help.

**Comment by chenshaoju** [comment]
Please try using this 3rd-party tool to check your server connectivity: https://ip100.info/check

If not working from inland, Maybe is your server has been blocked.

And if your server is built by yourself, you can try to add a plugin on your both site: https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

If you buy the service from somewhere, Please contact your service provider.
