### ISSUE TITLE
xshell搭建ss相关

### ISSUE THREAD

**Issue by lawlawlawJ** [shadowsocks/shadowsocks-windows#2603]
请教各位大神，我是小白一个，之前用代码“wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocksR.sh”直接复制粘贴，可以搭建ss，然后用windows的ss客户端科学上网。可是最近用相同的代码搭建的时候，出现如下信息，是VPS的原因还是代码出现了问题？提示【libsodium安装失败】，但是我网上找了相关的安装代码，但仍不能顺利安装，请问应该如何解决？谢谢！

[Info] firewall set start...
[Info] firewall set completed...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) no
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports the include directive... no
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/root/libsodium-1.0.17':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
[Error] libsodium install failed!

**Comment by chenshaoju** [comment]
我建议你联系该脚本的作者咨询……这个脚本看起来是SSR的，不是SS的。

**Comment by lawlawlawJ** [comment]
> 我建议你联系该脚本的作者咨询……这个脚本看起来是SSR的，不是SS的。
找到的也是二手传播，很难找到原作者是谁......我想问一下你有ss搭建的代码可以使用吗？

**Comment by chenshaoju** [comment]
我用的是 https://github.com/shadowsocks/shadowsocks-libev ，手动搭建的，比较复杂……

你可以考虑使用第三方插件作者的一件脚本：
https://github.com/HirbodBehnam/Shadowsocks-Cloak-Installer/blob/master/Cloak2-Installer.sh

请注意：这是第三方提供的插件脚本，无法提供任何保证。

**Comment by lawlawlawJ** [comment]
谢谢！
