### ISSUE TITLE
Official Website

### ISSUE THREAD

**Issue by LayJustDoIt** [shadowsocks/shadowsocks-windows#2604]
Please tell me what's your official website, and the change of your official website address sent me only an email, and then did not send it again.

**Comment by chenshaoju** [comment]
The Shadowsocks official website is: https://www.shadowsocks.org

Please note: The Shadowsocks is opensource software, It does not sell any services.

Some Shadowsocks service provider claims he is official Shadowsocks service provider, This's not true.

There is no "Official Shadowsocks service provider".
