### ISSUE TITLE
加密方式增加国密算法

### ISSUE THREAD

**Issue by Hawkeyes0** [shadowsocks/shadowsocks-windows#2608]
加密方式希望可以增加国密加密方式，以降低被封的可能

**Comment by chenshaoju** [comment]
现在已经是流量分析，不再是加密方式的问题了。

具体请参阅：
https://www.zybuluo.com/sixijinling/note/594694
https://zhuanlan.zhihu.com/p/30104498

**Comment by luoye0905** [comment]
看这文章，感觉自建服务器套一个混淆插件也没啥用啊，总归又一定规律，难道要经常换一下插件？

**Comment by Hawkeyes0** [comment]
所以还是要经常换IP和端口么？

**Comment by chenshaoju** [comment]
加密方式和混淆是两回事。

这里的混淆，是伪装成TLS（以 v2ray-plugin 为例），从而迷惑观测者，认为你在进行正常的HTTPS通信。
