### ISSUE TITLE
一段时间后断连

### ISSUE THREAD

**Issue by KX-1126** [shadowsocks/shadowsocks-windows#2609]
### Shadowsocks version / 影梭版本
shadowsocks 4.1.6

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
![image](https://user-images.githubusercontent.com/52236249/66483333-6d0dcd00-ead7-11e9-8b5f-e98f9601187e.png)

### Steps you have tried / 操作步骤
1. 电脑连接校园网下，一段时间后断连
2. 电脑改为连接手机热点后，无法打开的网页可以加载，也就是可以翻墙

### What did you expect to see? / 期望的结果
连接校园网情况下不断连

### What did you see instead? / 实际结果
连接校园网10分钟左右后断连

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
日志文件没有记录

**Comment by chenshaoju** [comment]
出现问题的时候，请右击任务栏的SS托盘图标，选择PAC，再点击“从GFWList更新本地PAC”，是否能看到一个更新成功或者没有更新的提示？

如果提示错误，日志里显示什么？

**Comment by KX-1126** [comment]
![image](https://user-images.githubusercontent.com/52236249/66486595-86197c80-eadd-11e9-9f06-1d2305937f5b.png)

**Comment by KX-1126** [comment]
![image](https://user-images.githubusercontent.com/52236249/66492538-24f6a680-eae7-11e9-9106-8bd7d2e75ffd.png)
SS没有显示更新的提示

**Comment by KX-1126** [comment]
电脑断连后，连接上手机热点一段时间，再接上校园网宽带又可用

**Comment by chenshaoju** [comment]
这看起来并没有问题。

你确定是在出现问题的时候尝试更新的吗？

**Comment by sblniujf** [comment]
一样，昨天可以上去网，现在又不行了。而且shadowsocks.org也上不去了。。。

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，请尝试套个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by KX-1126** [comment]
用的是搬瓦工的just my socks,不是自己搭建的

**Comment by KX-1126** [comment]
最近一次开机连上了几分钟又断连了，这一次有一次报错
![image](https://user-images.githubusercontent.com/52236249/66540241-c1f42680-eb5d-11e9-949b-6e55b4463e1e.png)

**Comment by chenshaoju** [comment]
`从传输流收到意外的 EOF 或 0 个字节“其实就是被墙了。

由于流量分析（ https://github.com/shadowsocks/shadowsocks-windows/issues/2608 ）等原因，如果你不用插件的话，很容易被墙：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by KX-1126** [comment]
可以在手机端使用并没有问题，应该没有被墙吧

**Comment by KX-1126** [comment]
最近一次开机无法使用，还是一样，可以连接手机热点使用
![image](https://user-images.githubusercontent.com/52236249/66547666-49e42b80-eb72-11e9-853d-15d1639b7327.png)

**Comment by chenshaoju** [comment]
极高的可能性是你的校园网存在更加严重的封锁。
