### ISSUE TITLE
pac模式和全局模式切换时会断开连接一下

### ISSUE THREAD

**Issue by xiaoyuhong** [shadowsocks/shadowsocks-windows#261]
win10  x64 pro , shadowsocks 2.5.2

由pac模式切换到全局模式，或者由全局模式切换到pac模式，会有短暂的时间无法连接。
下面的日志是切换模式之后的，shadowsocks一直都在运行，但切换模式之后日志里会有“Shadowsocks started” (下面的日志第一行)，这代表切换模式时Shadosocks重启吗？不知道这个算feature还是bug.
(以前用win7+shadowsocks 2.4 没有此问题，切换模式不会断开连接)

[2015-08-09 09:32:23] Shadowsocks started
[2015-08-09 09:32:26] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:8123
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2015-08-09 09:32:32] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:8123
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)

**Comment by li3shiyi** [comment]
看了下流程，模式切换时更新系统代理之后会保存配置，保存配置时又会reload一次配置。尝试给SaveConfig加个是否Reload的参数，在类似不必要的情况不Reload或许能行。

**Comment by li3shiyi** [comment]
请试下这个不reload的版本会不会有问题： https://d.docs.live.net/85315d5a1891c64c/公开/Shadowsocks.exe

**Comment by clowwindy** [comment]
这是故意这样设计的，之前没有强行切断所有连接的时候很多人反馈改了怎么不生效。
