### ISSUE TITLE
配置成功之后无法连接，不能科学上网，求助

### ISSUE THREAD

**Issue by wattcher44** [shadowsocks/shadowsocks-windows#2610]
[2019-10-12 00:53:40] Shadowsocks started (4.1.7.1)
[2019-10-12 00:54:14] Shadowsocks started (4.1.7.1)
[2019-10-12 00:54:16] Shadowsocks started (4.1.7.1)
[2019-10-12 00:54:21] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-10-12 00:54:22] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-10-12 00:54:22] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check

**Comment by wattcher44** [comment]
> 请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check

测过了，国内和国外都显示open，这应该是连通的吧

**Comment by chenshaoju** [comment]
你测试的是你的服务器上的SS端口对吧？

如果是，请仔细检查你的服务器和客户端的配置是否一致，尤其是密码、加密方式等。

**Comment by wattcher44** [comment]
> 你测试的是你的服务器上的SS端口对吧？
> 
> 如果是，请仔细检查你的服务器和客户端的配置是否一致，尤其是密码、加密方式等。

我又按照教程重新搭建了一遍，端口选的8080。设置确认无误。还是不行。
日志：
[2019-10-12 14:01:53] Shadowsocks started (4.1.7.1)
[2019-10-12 14:01:57] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
如果用手机4G网络，是否能正常使用？

如果可能，请尝试使用这个小工具测试从你的计算机到你的服务器的连通性。

**Comment by wattcher44** [comment]
> 如果用手机4G网络，是否能正常使用？
> 
> 如果可能，请尝试使用这个小工具测试从你的计算机到你的服务器的连通性。

手机4g试了也不行。请问是哪个小工具啊，没看到啊

**Comment by chenshaoju** [comment]
我还是认为是你的配置有误……

PS：所谓的4G是指手机上的Shadowsocks客户端，不是指电脑上的客户端。

小工具地址：https://github.com/chenshaoju/tcpportcheck

**Comment by wattcher44** [comment]
![image](https://user-images.githubusercontent.com/56449704/66701689-7eeaac80-ed31-11e9-9d57-856ce8766bff.png)
![image](https://user-images.githubusercontent.com/56449704/66701713-e274da00-ed31-11e9-8ac5-8774e1aad236.png)
配置就是这样啊，密码也不可能错，能有什么问题呢。
是用手机客户端试过，也不行。

**Comment by chenshaoju** [comment]
如果相同配置手机也不行，意味着你的服务端的确有问题。

PS：看起来你用的是第三方的脚本搭建的，无法确认这个脚本目前的有效性，Python版SS服务端已经很久没有维护了。

**Comment by wattcher44** [comment]
> 如果相同配置手机也不行，意味着你的服务端的确有问题。
> 
> PS：看起来你用的是第三方的脚本搭建的，无法确认这个脚本目前的有效性，Python版SS服务端已经很久没有维护了。

好的，我再重新搭建试试，多谢了

**Comment by You00** [comment]
@wattcher44 @chenshaoju
我这边也是vultr用第三方脚本搭建的ssr，是电脑连接可以用，但是手机上不能用，请问大佬们后面怎么处理的呢？

**Comment by yongdaimi** [comment]
> 如果相同配置手机也不行，意味着你的服务端的确有问题。
> 
> PS：看起来你用的是第三方的脚本搭建的，无法确认这个脚本目前的有效性，Python版SS服务端已经很久没有维护了。

你好，我使用https://ip100.info/check 这个检测国内国外都显示open, 在iphone的ss客户端上测试也ok, 唯独在公司电脑用ss客户端无法翻樯，错误日志和楼上的一样

**Comment by chenshaoju** [comment]
请检查你的配置是否正确，客户端配置的服务器IP、端口、加密方式、密码。

如果有使用插件，请检查插件配置是否正确。

**Comment by yongdaimi** [comment]
> 请检查你的配置是否正确，客户端配置的服务器IP、端口、加密方式、密码。
> 
> 如果有使用插件，请检查插件配置是否正确。
端口，IP，加密方式，密码都没有问题，因为我在iphone上使用相同的IP，密码用Shadowrocket App访问Google/Twitter已经成功了, 就是公司的电脑不行，插件的话没有安装。

**Comment by yongdaimi** [comment]
> 有可能你的公司存在限制。
> 
> 你的手机使用的是和公司电脑相同的WiFi吗？如果可能，让电脑通过手机4G上网试试？

我也觉得是这样。我手机使用的是4G网络，公司电脑使用的是公司的网络
