### ISSUE TITLE
怎么让git push 走代理啊

### ISSUE THREAD

**Issue by baddate** [shadowsocks/shadowsocks-windows#2615]
用了
```bash
git config --global http.proxy sock5:127.0.0.1:1080
git config --global https.proxy sock5:127.0.0.1:1080
和
git config --local http.proxy sock5:127.0.0.1:1080
git config --local https.proxy sock5:127.0.0.1:1080
```
都不行

**Comment by imba-tjd** [comment]
链接要是http协议的就有效，如果是ssh的就无效。后者可以设置ssh的代理，或者用虚拟网卡类软件

**Comment by hathlife** [comment]
可以用WSL的git 然后用proxychain强制代理

谭九鼎 <notifications@github.com> 于 2019年10月15日周二 20:52写道：

**Comment by chenshaoju** [comment]
Windows的话，执行：
```
set http_proxy=http://127.0.0.1:1080
set https_proxy=http://127.0.0.1:1080
```
然后再在当前命令提示符下执行git命令。

**Comment by baddate** [comment]
> 
> 
> 链接要是http协议的就有效，如果是ssh的就无效。后者可以设置ssh的代理，或者用虚拟网卡类软件

ssh协议怎么设置啊？

**Comment by imba-tjd** [comment]
https://www.zhihu.com/question/27159393

**Comment by celeron533** [comment]
>ssh协议怎么设置啊？

git官方的ssh不能使用代理。建议还是使用http
想要强制ssh都代理，基本上也就做虚拟网卡，这差不多就是VPN，复杂所以极不推荐
