### ISSUE TITLE
购买的shadowsocks服务，国庆期间以来，好久都无法访问了

### ISSUE THREAD

**Issue by yessicaChen** [shadowsocks/shadowsocks-windows#2617]

**Comment by yessicaChen** [comment]
刚刚更新了PAC，虽然显示没有更新成功，但突然又可以访问了

**Comment by chenshaoju** [comment]
你好，如果你的SS服务是购买的，请与你的SS服务商联系。

Shadowsocks for Windows 是开源软件，本身不销售服务。

**Comment by songge94** [comment]
> 刚刚更新了PAC，虽然显示没有更新成功，但突然又可以访问了

你是哪里买的服务，我这边也想买

**Comment by chenshaoju** [comment]
出于安全考虑（线路问题、跑路、泄露隐私等），不建议在此交流服务商的联系方式。
