### ISSUE TITLE
使用cloudflare无论是否经过cdn都会显示decryption error，直连vps则正常使用

### ISSUE THREAD

**Issue by galgamerer** [shadowsocks/shadowsocks-windows#2618]
### Shadowsocks version / 影梭版本
服务端：shadowsocks-libev 3.3.2
客户端：shadowsocks-windows 4.171

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
服务端：centos7
客户端：win10

### Steps you have tried / 操作步骤
正确填写配置→选择目标服务器→确认

### What did you expect to see? / 期望的结果
[2019-10-16 12:31:53] connect to duckduckgo.com:443
[2019-10-16 12:31:53] Socket connected to ss server: xxxxx

### What did you see instead? / 实际结果
[2019-10-16 12:32:57] connect to duckduckgo.com:443
[2019-10-16 12:32:57] Socket connected to ss server: xxxxx
[2019-10-16 12:32:58] [E] decryption error

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
服务端配置：
{
    "server":["[::0]","0.0.0.0"],
    "server_port": 2052,
    "local_port": 1080,
    "password": "xxxxxx",
    "timeout": 1000,
    "method": "chacha20-ietf-poly1305",
    "fast_open": false,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}
客户端配置
![tempsnip](https://user-images.githubusercontent.com/56198758/66888948-180c1280-f013-11e9-85be-6955bda9ef4b.png)

如果我把图中域名换成vps的ip就能正常连接使用，只要用域名，不论开不开cdn都会一直报decryption error。
不知道这是什么问题，请大佬们帮忙看看。

**Comment by chenshaoju** [comment]
你好，这是插件的配置问题，请参阅：https://github.com/shadowsocks/simple-obfs/issues/245

**Comment by galgamerer** [comment]
> 你好，这是插件的配置问题，请参阅：[shadowsocks/simple-obfs#245](https://github.com/shadowsocks/simple-obfs/issues/245)

嗯，这个我之前就看到了，按照
https://github.com/shadowsocks/simple-obfs/issues/245#issuecomment-507839078
这个回复设置配置文件，可以看到我的配置跟他几乎一样，但是并不起作用，所以才到这里来问问

**Comment by galgamerer** [comment]
> 你好，这是插件的配置问题，请参阅：[shadowsocks/simple-obfs#245](https://github.com/shadowsocks/simple-obfs/issues/245)

抱歉抱歉，是我自己不仔细！！！这个主题我关闭了！感谢帮忙！
