### ISSUE TITLE
新手 请问添加服务器是添加什么服务器啊 希望详细讲解下怎么使用

### ISSUE THREAD

**Issue by GCPD123** [shadowsocks/shadowsocks-windows#2619]
Shadowsocks version / 影梭版本

4.1.7.1

Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

win 10

Steps you have tried / 操作步骤

安装后，点开飞机图标，让我添加服务器地址，我不知道填什么呀，麻烦讲讲应该怎么使用，我是新手，谢谢了

What did you expect to see? / 期望的结果

可以用google

What did you see instead? / 实际结果

不添加服务器无法运行

Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
仅供参考：
https://cn.bing.com/search?q=%E6%90%AD%E5%BB%BA+SS

**Comment by GCPD123** [comment]
谢谢 现在问题解决了 可是现在 我想收集也能用 请问如何操作呢？

**Comment by chenshaoju** [comment]
![Uploading image.png…]()

**Comment by GCPD123** [comment]
我的是苹果手机啊 这个是安卓的啊

**Comment by GCPD123** [comment]
请问苹果手机怎么操作啊

**Comment by chenshaoju** [comment]
仅供参考：
https://cn.bing.com/search?q=%E8%8B%B9%E6%9E%9C+SS+%E6%95%99%E7%A8%8B

**Comment by GCPD123** [comment]
我想问下 使用后可以看外网的视频 可是有点卡 正常情况下是这样的吗

**Comment by chenshaoju** [comment]
取决于从你的计算机到你的服务器的稳定程度（丢包）和延迟情况，通常来说，是的。

**Comment by GCPD123** [comment]
想问下，会不会突然有一天现在这个能用的服务器的IP突然就被墙了，听说可以装什么插件能减小概率，请问如何操作呢，求个详细点的教程，谢谢啦！

**Comment by chenshaoju** [comment]
仅供参考：
https://github.com/loyess/Shell
