### ISSUE TITLE
WIN7 64位下出现 拒绝访问错误

### ISSUE THREAD

**Issue by emiaven** [shadowsocks/shadowsocks-windows#262]
今天早上忽然出现的。以前一直好的。没有过任何软件更新或者安装过。请问这个是什么问题？
![img_20131113_223642](https://cloud.githubusercontent.com/assets/13724879/9159220/ffe21a18-3f56-11e5-9e7d-0c2d7e79aefd.jpg)

**Comment by cholerae** [comment]
同出现这个问题，版本是2.5.2，现在回退到2.5.1就没有问题了。

**Comment by icylogic** [comment]
- 在任务管理器里如果有 ss_polipo.exe，强制结束。
- 删除 %TEMP%\文件夹下的 ss_polipo.exe，重启 shadowsocks。
尝试一下？

**Comment by LockGit** [comment]
why win7 64bit system only frist connect google succes , if close browser , then open browser connect fail . but in unbuntu14.04 system ,use shadownsockts connect google success  always ! why ? address:shanghai  china . network :GreatWall Broadband . help me !!! Thanks
