### ISSUE TITLE
Startup error - (Installed from Chocolatey)

### ISSUE THREAD

**Issue by amirrammari** [shadowsocks/shadowsocks-windows#2624]
Hello
I Installed Shadowsocks using Chocolatey.
`choco install shadowsocks`
Then I enabled Start Startup:
![Shadowsocks system tray content menu](https://user-images.githubusercontent.com/23485114/67160244-b376ed80-f35b-11e9-8ed6-82478a9dc17b.png)
After log-in Shadowsocks not starting and showing an error:
![image](https://user-images.githubusercontent.com/23485114/67160274-0a7cc280-f35c-11e9-8ed8-e59205cb1c10.png)
---
Shadowsocks not working in normally open and must run as administrator:
![2019-10-20_16-54-07](https://user-images.githubusercontent.com/23485114/67160296-40ba4200-f35c-11e9-8532-9c6ca6c8962f.gif)

**Comment by chenshaoju** [comment]
Yes, That normal if you running Shadowsocks.exe from `C:\ProgramData\`, This folder only can write if running as Administrator.

On the Chocolatey platform version is made by 3rd-party. 

The Shadowsocks for Windows is portable by default, You can download binary at https://github.com/shadowsocks/shadowsocks-windows/releases, Please try put a new non-system folder, Like D:\SS\

PS: If you want to use Chocolatey, You need to change the C:\ProgramData\chocolatey\bin folder permission, It's not recommended, May cause secure issue.

**Comment by amirrammari** [comment]
Ok, Thanks for your guide.
But I don't have any issues with other apps.
For example, you can see that ss-qt5 working fine.
I think this issue can be resolved.
Thanks.
![SS QT](https://user-images.githubusercontent.com/23485114/67162826-e2e62400-f374-11e9-993d-9d7a9d3c378c.gif)

**Comment by studentmain** [comment]
> ss-qt5

It's more 'portable' and lacks some feature than this one. So it has no problem.

ss-csharp use external programs (privoxy, modified abp.js, sysproxy.exe) to provide some feature (PAC, proxy setting, HTTP proxy). To make ss-csharp portable, we packed them in exe and unpack it during runtime, it requires write permission to current directory.

If you want, ss-csharp can do it by remove packed programs(I will personally do it for you if you really want), but those feature won't works too.

**Comment by studentmain** [comment]
FYI: #1998
