### ISSUE TITLE
老手反哺路过，推荐优质VPN

### ISSUE THREAD

**Issue by AmbroseRen** [shadowsocks/shadowsocks-windows#2625]
优质好用，反哺推荐！（需要个临时梯子先翻下墙，建议“佛跳墙”做临时梯子，虽不稳定，临时够用）需要google浏览器+google账号+windscribe账号+google商店windscribe插件（也可在windscribe下客户端，不过本人喜欢轻量化插件），开启临时梯子初始化登录windscribe账号后就不用临时的梯子了，网速很稳定，有免5G/15G（需推特做推广升级到15G）月流量。用的好回来给个回复就很开心，亲。
![image](https://user-images.githubusercontent.com/35362717/67180365-027c5b80-f40c-11e9-9208-bfeb717560d8.png)

**Comment by chenshaoju** [comment]
请不要发广告……
