### ISSUE TITLE
开启代理后，电脑鼠标指针间隔性繁忙，在转圈，关闭后正常，什么情况？

### ISSUE THREAD

**Issue by hanxiaofeng** [shadowsocks/shadowsocks-windows#2626]
开启代理后，电脑鼠标指针间隔性繁忙，在转圈，关闭后正常，什么情况？

后台在执行什么任务？

版本：4.1.7.1

**Comment by chenshaoju** [comment]
请看一下代理设置是否成功了：
![image](https://user-images.githubusercontent.com/515763/67352760-755c1280-f583-11e9-96d1-94104ebf2a4f.png)


如果没有成功，可能有什么安全软件拦截了代理设置过程。

**Comment by hanxiaofeng** [comment]
@chenshaoju 设置成功了，此时鼠标指针就间隔性转圈了

![QQ截图20191024153949](https://user-images.githubusercontent.com/10582931/67469144-5bebc100-f67e-11e9-8335-cf0ec6664d52.png)
)

**Comment by chenshaoju** [comment]
我猜测可能和你的系统中某些后台程序有关。

如果可能，请尝试尽可能的退出后台程序，或者在不启动任何开机启动的应用的情况下（可通过 msconfig - 启动 暂时停用），测试一下使用SS是否还会出现这个现象。
