### ISSUE TITLE
shadowsocks系统找不到指定文件

### ISSUE THREAD

**Issue by lyclc331** [shadowsocks/shadowsocks-windows#2627]
![1571818607(1)](https://user-images.githubusercontent.com/19278726/67372520-9ab34580-f5b0-11e9-96f0-4634ad5fc6af.jpg)
请问这个是问题？（没有安装任何插件，直接从github上下载然后运行的）

**Comment by chenshaoju** [comment]
你的配置是否包含了插件？如果是，可能会遇到该问题。

如果你不需要用插件的话，不要配置插件即可。

如果需要，请务必要将相同的插件放在所在或者指定的目录下。

**Comment by weyeee** [comment]
> ![1571818607(1)](https://user-images.githubusercontent.com/19278726/67372520-9ab34580-f5b0-11e9-96f0-4634ad5fc6af.jpg)
> 请问这个是问题？（没有安装任何插件，直接从github上下载然后运行的）
请问你有解决这个问题吗？我也有相同的问题。

**Comment by binaijing** [comment]
> > ![1571818607(1)](https://user-images.githubusercontent.com/19278726/67372520-9ab34580-f5b0-11e9-96f0-4634ad5fc6af.jpg)
> > 请问这个是问题？（没有安装任何插件，直接从github上下载然后运行的）
> > 请问你有解决这个问题吗？我也有相同的问题。

看下服务器配置，肯定是导入了含有插件的服务器信息。
OBFS到这里下载https://github.com/shadowsocks/simple-obfs/releases，解压到SS根目录就可以。
V2RAY的自行搜索下
