### ISSUE TITLE
4.1.7.1 客户端 日志窗口 崩溃 和解决办法。

### ISSUE THREAD

**Issue by zprood** [shadowsocks/shadowsocks-windows#2628]
### Steps you have tried /
升级到最新的客户端，打开日志窗口会崩溃。

### What did you see instead? / 实际结果
看了下错误日志，然后找到打开提示的目录：
C:\Users\XXX\AppData\Local\Shadowsocks\Shadowsocks.exe_Url_yglpt1ace1fij4hzqdntzuxkwtj3avzl\4.1.7.1
把下面的文件user.config，删除。再日志窗口就正常了。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![image](https://user-images.githubusercontent.com/692206/67451746-d5ba8500-f653-11e9-83e2-8c246b5f2725.png)

![image](https://user-images.githubusercontent.com/692206/67451111-14e7d680-f652-11e9-9be9-faeed7792974.png)

**Comment by chenshaoju** [comment]
可能是由于 dotNET 的用户配置文件损坏导致的，我看了一下我这儿正常。

**Comment by celeron533** [comment]
日志窗口的大小、位置和字体是保存在appdata的config文件下的，微软的标准xml。但由于不明原因，文件损坏了。
