### ISSUE TITLE
sharing shadowsocks connection to ps4 via LAN cable (Win10)

### ISSUE THREAD

**Issue by satan51** [shadowsocks/shadowsocks-windows#2629]
Hi, can anyone help me, I'm new to shadowsocks and just manage to get it working.
I was wondering I can share the shadowsocks connection to my ps4, unlike the VPN app that there is a TAP adapter where I can just share the connection but the SS app doesn't have one.

There is an option that Allows other device to connect but I don't know where to connect.
Please if anyone knows, please help.

Thank you!

**Comment by celeron533** [comment]
tray icon, right click, share over LAN

**Comment by satan51** [comment]
Is there a newer ver of SS app?
I don't have the share over LAN option.

![SS](https://user-images.githubusercontent.com/56967771/67568969-3c2cc980-f760-11e9-8dbc-0bddee3c98f8.png)

**Comment by celeron533** [comment]
@satan51 as your screenshot. "share over LAN" is the caption in old versions.

**Comment by satan51** [comment]
@celeron533 can you specify which older version is it. Thank you!

**Comment by satan51** [comment]
@celeron533, I would like to ask, is it normal that FB and FB messenger won't connect, when using the SS app on Android?

**Comment by satan51** [comment]
@celeron533 I've downloaded ver 3.4.2.1 and it has the share over LAN, I've enabled it but still don't how to share the SS to my ps4?  I've already connected my ps4 to my laptop via LAN cable.

**Comment by chenshaoju** [comment]
I don't have PS4,  Here is a Screenshot from https://www.yuntif.xyz/public/ps4%E4%BD%BF%E7%94%A8shadowsocks%E6%95%99%E7%A8%8B/
![3](https://user-images.githubusercontent.com/515763/67636081-b8addc80-f907-11e9-8fff-19ffa12789e6.jpg)

You need Set your PS4 Proxy to your computer LAN IP Address and Port number.

**Comment by celeron533** [comment]
And point the proxy address to your PC

**Comment by satan51** [comment]
@chenshaoju 
Thanks, will try this

**Comment by studentmain** [comment]
> older version

Actually you needn't it, we just changed **the string** 'Share over LAN' to 'Allow other Devices to connect' for readability here, they're same thing. Just use new version and allow other devices to connect.

> to my laptop via LAN cable

Just make sure your laptop and PS4 is under same router. In another word: connect both PS4 and laptop to your router, you needn't connect PS4 and laptop directly (it introduce some complexity).

> LAN IP Address and Port number

You can find your LAN IP Address by execute command `ipconfig` and find it in output, typically they start with `10`, `172` or `192.168` and ends with a number larger than 1. e.g. `192.168.1.4`
Port number here is 1080 by default. You can find it at the bottom of server config window.

**Comment by satan51** [comment]
@studentmain

Thanks will your suggestion
