### ISSUE TITLE
对端口被系统保留的测试

### ISSUE THREAD

**Issue by sailtao** [shadowsocks/shadowsocks-windows#2630]
我的一台PC安装了windows 10 预览版，经常推送内部版本更新，在初次更新后shadowsocks使用的端口会被系统保留。
第二次出现端口被保留的时，也是安装内部版本补丁后，重启PC后提示端口被系统保留，查看保留端口显示第一次被保留的端口释放了。
第三次提示内部版本补丁更新时，我进行了一些操作，更新补丁之前去除shadowsocks的开机启动，并关闭程序，清除系统代理设置中的代理脚本，然后进行补丁更新，系统重启后没有提示端口被系统保留，之后数次更新都进行相同操作，均没有被系统保留端口。
今天提示更新内部版本补丁：Windows 10 Insider Preview 19008.1 (vb_release)，我没有按以上方式操作，系统重启后，提示端口10801被系统保留。
因为没有查到windows保留端口的机制，但希望以上测试能够帮助解决端口被系统保留的问题。

**Comment by celeron533** [comment]
谢谢@sailtao
所以根据你的观察，系统更新的时候似乎会对开机启动的程序保留最后一次使用过的端口？
此时如果再重启一次能释放吗？

**Comment by sailtao** [comment]
普通使用过程不会释放端口，直到下次更新补丁，可以肯定端口被系统保留是shadowsocks的某项设置让windows产生了误会

**Comment by KexyBiscuit** [comment]
Thanks to [Dandini](https://dandini.wordpress.com/2019/07/15/administered-port-exclusions-blocking-high-ports/), who contacted Microsoft Support and got a workaround for this problem.

## Enable workaround (Select one from below, run as administrator)

```powershell
New-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\hns\State -Name EnableExcludedPortRange -PropertyType String -Value 0 -Force
```

```cmd
reg add HKLM\SYSTEM\CurrentControlSet\Services\hns\State /v EnableExcludedPortRange /d 0 /f
```

## Disable workaround (Select one from below, run as administrator)

```powershell
Remove-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\hns\State -Name EnableExcludedPortRange -Force
```

```cmd
reg delete HKLM\SYSTEM\CurrentControlSet\Services\hns\State /v EnableExcludedPortRange /f
```

**Comment by KexyBiscuit** [comment]
After installing a new graphics card, the workaround no longer works. No idea why.

**Comment by yobome** [comment]
是否安装了Hyper-V
