### ISSUE TITLE
Chrome模式不正常，切换到IE浏览模式则正常

### ISSUE THREAD

**Issue by hrkkid** [shadowsocks/shadowsocks-windows#2633]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows10 1903 18362.449

### Steps you have tried / 操作步骤
Chrome模式浏览油管视频等无法访问，切换到IE模式后可以正常访问。

### What did you expect to see? / 期望的结果
浏览器中Chrome模式和IE模式均可访问

### What did you see instead? / 实际结果
浏览器中只有IE模式可以访问

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
日志查看器中，Chrome模式下没有滚动日志，IE模式下使用正常则有滚动日志。

**Comment by chenshaoju** [comment]
你是通过PPPoE宽带拨号上网的吗？

**Comment by hrkkid** [comment]
不是，直接接在路由器上不用拨号

**Comment by chenshaoju** [comment]
你的Chrome是否使用了某些第三方的代理插件？如果是，请暂时禁用看看？

你可以在Chrome的设置-高级里看到。

![image](https://user-images.githubusercontent.com/515763/67854943-614c7e00-fb4c-11e9-853f-383c3cf6dc47.png)

**Comment by hrkkid** [comment]
看了你的图片，我下载安装了谷歌浏览器，发现是正常的，不行的是我那个QQ浏览器，QQ浏览器chrome模式不行，IE模式行。

**Comment by wengdajie** [comment]
> 看了你的图片，我下载安装了谷歌浏览器，发现是正常的，不行的是我那个QQ浏览器，QQ浏览器chrome模式不行，IE模式行。

chrome安装SwitchyOmega，添加SS的pac链接即可。
