### ISSUE TITLE
请问我已经删除了SS这些代理软件，这里的地址还是无法删除修改。

### ISSUE THREAD

**Issue by shintani7** [shadowsocks/shadowsocks-windows#2634]
![批注 2019-10-30 173122](https://user-images.githubusercontent.com/54657217/67845858-2f7eeb80-fb3b-11e9-8ad6-04ac53dd793e.png)

**Comment by chenshaoju** [comment]
你需要启动“使用代理服务器”才能修改下面的设置。

**Comment by shintani7** [comment]
> 您需要启动“使用代理服务器”才能修改以下的设置。

这个我知道，启动“使用代理服务器”，修改或者删除然后保存，后退在进来，还是一样的没用变化。

**Comment by chenshaoju** [comment]
下面的那些内容，是系统本身就有的。

如果你坚持要清空，可以运行注册表编辑器（regedit.exe），定位到：`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings`，有个名为`ProxyOverride`的字符串，清空内容即可。

![image](https://user-images.githubusercontent.com/515763/67854458-56451e00-fb4b-11e9-91fc-3e2380451667.png)

**Comment by shintani7** [comment]
> 下面的那些内容，是系统本身就有的。
> 
> 如果你坚持要清空，可以运行注册表编辑器（regedit.exe），定位到：`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings`，有个名为`ProxyOverride`的字符串，清空内容即可。
> 
> ![image](https://user-images.githubusercontent.com/515763/67854458-56451e00-fb4b-11e9-91fc-3e2380451667.png)

知道了，感谢。
