### ISSUE TITLE
能否支持goflyway?

### ISSUE THREAD

**Issue by jinwyp** [shadowsocks/shadowsocks-windows#2636]
一个建议 能否支持goflyway ? 尤其是goflyway 的cdn模式?

https://github.com/coyove/goflyway

goflyway真是太好用了.

**Comment by chenshaoju** [comment]
Shadowsocks 的协议基本固定了，不过得益于插件的支持，目前可以使用各种各样的插件。

其中 v2ray-plugin 也支持CDN模式，更多详情请阅读：https://github.com/shadowsocks/v2ray-plugin

**Comment by jinwyp** [comment]
希望能开发一个goflyway的插件, v2ray不好用, 而且被x的厉害

**Comment by chenshaoju** [comment]
v2ray-plugin和v2ray是两回事。
