### ISSUE TITLE
全局模式部分应用不通过代理

### ISSUE THREAD

**Issue by theone0316** [shadowsocks/shadowsocks-windows#2639]
### Shadowsocks version / 影梭版本
Shadowsocks-4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
全局代理，yy语音火狐浏览器不通过代理，打开路由器的ss可以正常通过代理

### What did you expect to see? / 期望的结果
yy语音地区限制不能说话，只想yy语音通过代理，全局代理也不行，pac 不知道yy客户端使用的域名

### What did you see instead? / 实际结果
目前火狐浏览器 yy语音等不通过代理

**Comment by chenshaoju** [comment]
你是通过PPPoE拨号上网的吗？如果是，请检查你的拨号名字，是否为“宽带连接”或者其他非英文的名称？

如果是，请修改为英文的，然后再试。
