### ISSUE TITLE
win10连接异常

### ISSUE THREAD

**Issue by GrandArth** [shadowsocks/shadowsocks-windows#2642]
### Config and error log in detail (with all sensitive info masked) 
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。

### 备注：手机端连接正常，且处于同一网络下

**Comment by chenshaoju** [comment]
请使用这个第三方服务测你的计算机的国内连通性：
https://ip100.info/check

请使用这个第三方的小工具测试你的计算机到你的服务器是否能连接：
https://github.com/chenshaoju/tcpportcheck
