### ISSUE TITLE
间歇性无法连接

### ISSUE THREAD

**Issue by CoderYellow** [shadowsocks/shadowsocks-windows#2643]
### Shadowsocks version / 影梭版本
4.1.7.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
* SOCKS5 communication to www.google.com.tw:443
* SOCKS5 connect to IPv4 172.217.4.131 (locally resolved)
* SOCKS5 request granted.
* Connected to localhost (127.0.0.1) port 1080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS change cipher, Client hello (1):
* (304) (OUT), TLS Unknown, Certificate Status (22):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using unknown / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.google.com.tw
*  start date: Oct 10 20:59:13 2019 GMT
*  expire date: Jan  2 20:59:13 2020 GMT
*  subjectAltName: host "www.google.com.tw" matched cert's "*.google.com.tw"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* (304) (OUT), TLS Unknown, Unknown (23):
* (304) (OUT), TLS Unknown, Unknown (23):
* (304) (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x7fffb8a42580)
* (304) (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: www.google.com.tw
> User-Agent: curl/7.58.0
> Accept: */*
>
* Unexpected EOF
* Connection #0 to host localhost left intact
curl: (56) Unexpected EOF

**Comment by CoderYellow** [comment]
感觉流量被识别了，解析，握手阶段都好着

**Comment by chenshaoju** [comment]
SS的日志中显示什么？

**Comment by ZjzMisaka** [comment]
> 
> 
> SS的日志中显示什么？

[2019-11-07 10:44:51] connect to www.google.com:443
[2019-11-07 10:44:51] Socket connected to ss server: xxx.xxx.xxx.xxx:xxx

我这也是间歇性连得上, 相关log的也就这么些, 网页也只是单纯的显示空白页, 想不出是什么原因...

**Comment by chenshaoju** [comment]
间歇性能连接上的话，我怀疑是你的服务器被干扰了。

如果你的服务器是自己搭的，你可以尝试套个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

如果你是买的机场服务，请与你的服务商联系。

**Comment by ZjzMisaka** [comment]
> 
> 
> 间歇性能连接上的话，我怀疑是你的服务器被干扰了。
> 
> 如果你的服务器是自己搭的，你可以尝试套个插件：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)
> 
> 如果你是买的机场服务，请与你的服务商联系。

感谢指路, 还想请教两个问题: 一是我目前使用corntab定时一天换一次ss端口, 这种操作是不是属于没有必要的瞎折腾? 二是我看到simple-obfs被弃用并且很久没更新了, 那为什么要继续推荐使用这个插件, 有什么说法么, 还是说后继的v2ray-plugin或者GoQuiet更稳一些?

**Comment by chenshaoju** [comment]
是，之所以保留simple-obfs，是因为有些路由器内置的是simple-obfs。

**Comment by adamhuang666** [comment]
好像我这里的搬瓦工的机场，现在也是经常性断链，每次都需要切换一次才可以，日志文件里面没有任何异常
