### ISSUE TITLE
软件语言切换

### ISSUE THREAD

**Issue by wazamono** [shadowsocks/shadowsocks-windows#2644]
由于公司电脑的系统是英文的, 方便使用SSR怎么切换成中文？如果语言是跟随系统决定的，如何在软件内修改？

**Comment by chenshaoju** [comment]
你好，SSR和SS是两个不同的东西。

请尝试：
![image](https://user-images.githubusercontent.com/515763/68103153-9cfe9380-ff10-11e9-9335-ecb4e17faee2.png)

**Comment by shikkoku** [comment]
管理员不允许你把系统切换成简体中文吗？

**Comment by studentmain** [comment]
Locale Emulator
