### ISSUE TITLE
勾选“允许局域网的连接”后无法上网

### ISSUE THREAD

**Issue by MyLifeKoro** [shadowsocks/shadowsocks-windows#2645]
### Shadowsocks version / 影梭版本

4.1.8.0或者以前
### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows10

### Steps you have tried / 操作步骤
就勾选“允许局域网的连接”后无法上网这个话题我搜查了一下，都没有我的问题。我的问题是，我的笔记本电脑关闭防火墙后勾选“允许局域网的连接”，移动端无法科学上网。但在同一局域网内台式电脑（也是Windows10）不需要关闭防火墙直接勾选“允许局域网的连接”，移动端是可以科学上网。我排查了很久笔记本电脑到底哪里阻碍了通信仍没有结果。这有点怪啊。

### What did you expect to see? / 期望的结果
移动端能够通过局域网连接科学上网。

### What did you see instead? / 实际结果
无法连接科学上网。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
日志里只有开启信息，没有后续信息。查了下端口监听，1080是0.0.0.0的。

**Comment by chenshaoju** [comment]
你好，只开启”允许其他设备连入“是无法让你局域网中的其他设备自动的通过你的计算机上网的。

你需要配置你的移动设备，将代理指向你的计算机的局域网IP地址和代理端口号。

**Comment by MyLifeKoro** [comment]
你好，我是按照你的要求做了，我的台式电脑上允许其他设备接入后，它的ip地址和代理端口号填写在移动设备上配置，填写好后是可以正常上网的；但是同样的局域网下我自己的笔记本电脑同样允许其他设备接入后，同样它的ip地址和代理端口号同样填写在移动设备上的配置，很可惜，无法上网，这点很奇怪，我的笔记本电脑关掉防火墙仍然无法上网，ss日志上不提示任何，只有开启信息。

**Comment by chenshaoju** [comment]
如果你使用的是Android，请尝试这个小工具：
https://play.google.com/store/apps/details?id=ua.com.streamsoft.pingtools&hl=en_US

安装后，填写你的计算机的局域网IP地址，以及SS代理端口，看看能否能通。

请注意，下图是举例，你需要按照你的实际情况填写：
![Screenshot_20191104-224145_PingTools_Pro](https://user-images.githubusercontent.com/515763/68129432-82e6a480-ff54-11e9-9c20-1fe60c213b91.png)

![Screenshot_20191104-224155_PingTools_Pro](https://user-images.githubusercontent.com/515763/68129450-8b3edf80-ff54-11e9-80c1-ea8248a1ddee.png)

**Comment by MyLifeKoro** [comment]
![1](https://user-images.githubusercontent.com/37872133/68207892-f3e89380-000a-11ea-8c5c-f52eb02cca96.jpg)
奇怪，扫不出端口。

**Comment by chenshaoju** [comment]
扫描端口界面右上角有个菜单按钮，点一下，有个设置，第二个选择 Specify manually ，然后输入你计算机上的SS代理端口号，确定后再扫一次看看。

**Comment by MyLifeKoro** [comment]
输入端口号确定扫不出来，会显示已扫描1，找到0。

**Comment by chenshaoju** [comment]
请尝试以管理员身份启动命令提示符或者powershell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机后再看看是否可以了。

**Comment by MyLifeKoro** [comment]
重置仍然无效，这见鬼了。关于端口我搜索了很多都没有我这个奇怪的问题。

**Comment by chenshaoju** [comment]
可能你所在的WiFi启用了AP隔离，导致WiFi设备之间无法通信？

能用的那个机器是有线网络还是无线网络？

**Comment by MyLifeKoro** [comment]
我刚尝试了一下，连有线网络是可以正常扫到端口。如你所说，是路由器设置了AP隔离，感谢你，解决了这个问题。

**Comment by chenshaoju** [comment]
😇
