### ISSUE TITLE
China white-list feature

### ISSUE THREAD

**Issue by Anduin2017** [shadowsocks/shadowsocks-windows#2647]
### Shadowsocks version

4.1.7.1

### Environment (Operating system, .NET Framework, etc)

Windows 10 1903
 .NET Framework 4.7.2

### Steps you have tried

No repro steps

### What did you expect to see?

I expect a China-white-list feature.

* For all websites in China, connect directly.
* For others, connect via proxy.

For connecting to some websites is faster if using proxy than connect directly. For example:

Downloading files from GitHub. GitHub is not blocked in China. But if I turn my client to PAC mode, connection to GitHub will not via proxy, which may be very slow.

For there already exist many projects which provide a China servers list. For example https://github.com/felixonmars/dnsmasq-china-list/blob/master/accelerated-domains.china.conf. Why not provide this China white-list feature?

### What did you see instead?

Enable this feature in a future release.

### Config and error log in detail (with all sensitive info masked)

Hidden.

**Comment by chenshaoju** [comment]
You may try:
https://github.com/neko-dev/gfw_whitelist

**Comment by studentmain** [comment]
More conversation at #2671
