### ISSUE TITLE
扫描需要插件的二维码会有问题

### ISSUE THREAD

**Issue by 0x112** [shadowsocks/shadowsocks-windows#2648]
比如这个二维码：https://www.go2free.xyz/2019/11/04/%e5%85%8d%e8%b4%b9shadowsocksss%e8%8a%82%e7%82%b92019-11-03t1829530000/
需要obfs-local插件，但是我本地又没有这个插件的时候，会提示这个错误：

![image_2019-11-05_18-02-36](https://user-images.githubusercontent.com/37543118/68198079-55523780-fff6-11e9-968b-7bccb7c7ad78.png)

**Comment by chenshaoju** [comment]
你好，这是正常的，如果你本机没有这个插件，则会出现问题。

请将插件放到 shadowsocks.exe 所在目录下。

https://github.com/shadowsocks/simple-obfs/releases

**Comment by 0x112** [comment]
这种异常最好还是能处理一下 :)

**Comment by studentmain** [comment]
在4.1.9.0处理了
