### ISSUE TITLE
window 10 成功连接，但是无法上去外网

### ISSUE THREAD

**Issue by 956632862** [shadowsocks/shadowsocks-windows#2649]

**Comment by chenshaoju** [comment]
请尝试右击任务栏托盘区的纸飞机图标，指向系统代理，再选中PAC。

然后再次右击任务栏托盘区的纸飞机图标，指向PAC，再点击从GFWList更新本地PAC即可。

**Comment by 956632862** [comment]
> 请尝试右击任务栏托盘区的纸飞机图标，指向系统代理，再选中PAC。
> 
> 然后再次右击任务栏托盘区的纸飞机图标，指向PAC，再点击从GFWList更新本地PAC即可。

我已经尝试过了，但是还是连接不上，另外是我的手机使用是没有问题的，我用了另外一个软件之后，也可以连接上去

**Comment by chenshaoju** [comment]
在更新PAC的时候，是否有提示成功或者失败，或者没有更新？

如果失败，日志中显示什么？

**Comment by wuweijian1997** [comment]
> 在更新PAC的时候，是否有提示成功或者失败，或者没有更新？
> 
> 如果失败，日志中显示什么？

您好，我是手机流量能正常使用，用WiFi就不行，手机和电脑在连WiFi的时候都连不上去。
系统代理选择pac的时候报错的是：有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
更新GFWlist的时候也是这个错：请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。

**Comment by chenshaoju** [comment]
这看起来很像你所在的网络有拦截或者过滤。

如果可能，请做个测试，让电脑通过手机4G上网，是否可以？

如果可以，确定是你的网络有封锁。

**Comment by wuweijian1997** [comment]
> 这看起来很像你所在的网络有拦截或者过滤。
> 
> 如果可能，请做个测试，让电脑通过手机4G上网，是否可以？
> 
> 如果可以，确定是你的网络有封锁。

我用笔记本连了手机流量的热点就可以正常访问了。这个有什么办法能解决吗？

**Comment by beathahahaha** [comment]
遇到一模一样的问题，跟上述的回复的一样，无法修复问题

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭的，请尝试使用一些常见端口，如80、443、3389。

如果可能，请尝试套个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

若你是找SS机场购买的，请联系你的服务商。

**Comment by beathahahaha** [comment]
> 如果你的服务器是自己搭的，请尝试使用一些常见端口，如80、443、3389。
> 
> 如果可能，请尝试套个插件：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)
> 
> 若你是找SS机场购买的，请联系你的服务商。

谢谢朋友，我找我的classmate调通了，是因为centos有防火墙，把端口给屏蔽了，设置一下防火墙以后能成功

**Comment by chenshaoju** [comment]
💯
