### ISSUE TITLE
求助，能正常浏览其他外网，唯独pinterest无法访问，

### ISSUE THREAD

**Issue by ShuHaiH** [shadowsocks/shadowsocks-windows#2650]
之前是可以访问的，前几天网络抽风了下，突然就无法访问pinterest了，求大佬施舍下援助，找了很多解决办法，都不行，修改代理模式 DNS 都没用

**Comment by chenshaoju** [comment]
请尝试 https://github.com/shadowsocks/shadowsocks-windows/issues/2412

**Comment by ShuHaiH** [comment]
问题已经解决，昨天晚上莫名其妙自己就 连接上了 ，谢谢大大热心解答
