### ISSUE TITLE
windows7 链接提示错误，求助

### ISSUE THREAD

**Issue by ningkexin** [shadowsocks/shadowsocks-windows#2651]
![image](https://user-images.githubusercontent.com/17719524/68277142-8b042880-00a9-11ea-9c1d-b8b8ac2f45c4.png)

**Comment by chenshaoju** [comment]
请尝试将 Shadowsocks.exe 单独放到一个新的目录中，比如 D:\SS\ ，然后再是。

**Comment by ningkexin** [comment]
@chenshaoju 还是不行 提示错误是一样的

**Comment by chenshaoju** [comment]
你是否有使用某些安全软件？

**Comment by ningkexin** [comment]
@chenshaoju 关闭了 还是不可以 很奇怪

**Comment by chenshaoju** [comment]
不知道。。。这看起来就是 Privoxy 启动失败。

**Comment by yingwu-zhang** [comment]
看看你的.net framework是不是要重装一下？
