### ISSUE TITLE
why upgrade to .net framework 4.7.2?

### ISSUE THREAD

**Issue by johnx7271** [shadowsocks/shadowsocks-windows#2652]
Usually, it is best to stick with the lowest MS supported framework version, unless the project needs some new API or features that are absent in old version.
Is it because the better TLS feature in 4.7

**Comment by chenshaoju** [comment]
`Upgrade nuget packages to .Net framework 4.7.2 as the target framework`
https://github.com/shadowsocks/shadowsocks-windows/commit/cd4595ad696fcae68ae191096b6bc1d3e777a1d5
