### ISSUE TITLE
chrome 无法使用代理，edge、chrome无痕模式、手机端均正常

### ISSUE THREAD

**Issue by liulinsmu** [shadowsocks/shadowsocks-windows#2655]
chrome无法访问墙外站点，墙内的没问题；
使用edge、chrome无痕模式以及手机端均正常
猜测原因是曾经安装过“谷歌访问助手”。
2个月前因为SS服务器被封无法使用，就去安装“谷歌访问助手插件”，现在服务器修复了，而且该插件劫持主页还不稳定，就卸载了“谷歌访问助手插件”，就无法访问墙外网站了；
再次重新安装“谷歌访问助手插件”又可以访问，但是不稳定，不想用
请问如何解决该问题？谢谢

**Comment by chenshaoju** [comment]
可能你的用户配置文件或者Chrome被破坏了。

请尝试右击Chrome的快捷方式，然后在目标结尾加一个 ` --user-data-dir=D:\Chrome` 参数（注意： --  前面有个空格），这会让你的Chrome新起一个空白的配置文件启动全新的空白Chrome。

举例：
![image](https://user-images.githubusercontent.com/515763/68522114-8e362900-02e2-11ea-8e4d-db1c2b830a47.png)

请注意：若你的Chrome目标路径中包含引号，请在引号末尾空格然后再加上上面的参数。
若你没有D盘，清修改为一个存在的盘符，但是不能是C盘。
如果没有问题，你想回到原有的配置，只需要清除快捷方式中的 ` --user-data-dir=D:\Chrome` 参数即可。

请试一下，这个Chrome是否可以正常使用？

**Comment by liulinsmu** [comment]
> 可能你的用户配置文件或者Chrome被破坏了。
> 
> 请尝试右击Chrome的快捷方式，然后在目标结尾加一个 ` --user-data-dir=D:\Chrome` 参数（注意： -- 前面有个空格），这会让你的Chrome新起一个空白的配置文件启动全新的空白Chrome。
> 
> 举例：
> ![image](https://user-images.githubusercontent.com/515763/68522114-8e362900-02e2-11ea-8e4d-db1c2b830a47.png)
> 
> 请注意：若你的Chrome目标路径中包含引号，请在引号末尾空格然后再加上上面的参数。
> 若你没有D盘，清修改为一个存在的盘符，但是不能是C盘。
> 如果没有问题，你想回到原有的配置，只需要清除快捷方式中的 ` --user-data-dir=D:\Chrome` 参数即可。
> 
> 请试一下，这个Chrome是否可以正常使用？

问题解决了，非常感谢！！！

**Comment by 8aus1R** [comment]
神医！！！ 有用 修好了

**Comment by xuanhuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。 
  
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ccy2019** [comment]
您的邮件已收到，感谢您对我们活动的支持。
