### ISSUE TITLE
电脑可以用ipv4，但是ipv6不能用

### ISSUE THREAD

**Issue by liyi980116** [shadowsocks/shadowsocks-windows#2656]
作者您好，我过去一年一直都是在用DO的vps,由于想达到校园网免流的效果，因此基本都是使用ipv6 to ipv4，之前一直都能用，但是从5天前开始，因为DO流量问题，我暂停使用了一天，第二天重新开启，就发现没办法用IPV6转ipv4了，手机能正常用流量连ipv4翻墙，就是电脑用不了，我重装过几次，还换了两次vps,都是IPV4能用，ipv6不能用。
目前的情况是，手机可以直接连v4翻墙，电脑可以在登陆校园网的情况下连v4翻墙，但是一旦想用v6转v4,就完全不行，切换到v6服务器的情况下，右下角软件处没有流量下载上传的红绿标志，端口测试都能通，也能ping通地址，就是没有流量进出。
这是日志：
[2019-11-09 13:51:59] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
IPv6的端口能通吗？你可能需要使用这个第三方的小工具测试你的端口的连通性：
https://www.elifulkerson.com/projects/tcping.php

命令行参考：
![image](https://user-images.githubusercontent.com/515763/68524504-ba61a200-0302-11ea-8305-0e5397b73fbf.png)

**Comment by liyi980116** [comment]
Probing 2604:a880:400:d0::ec0:a001:45667/tcp - No response - time=2001.336ms
Probing 2604:a880:400:d0::ec0:a001:45667/tcp - No response - time=2001.165ms
Probing 2604:a880:400:d0::ec0:a001:45667/tcp - No response - time=2000.205ms
Probing 2604:a880:400:d0::ec0:a001:45667/tcp - No response - time=2000.279ms

Ping statistics for 2604:a880:400:d0::ec0:a001:45667
     4 probes sent.
     0 successful, 4 failed.  (100.00% fail)
Was unable to connect, cannot provide trip statistics.

IPV4 4个都能通，IPV6不行

**Comment by chenshaoju** [comment]
如果你的地址和端口没有修改，可能是你的服务端配置出错了。
你的端口不通，你可以使用这个第三方的服务测试你的端口是否能通：
http://www.ipv6scanner.com/cgi-bin/main.py

**Comment by liyi980116** [comment]
这个测试的也是closed,如果是服务器配置错的话，请问我需要重装vps吗，还是应该怎么弄

**Comment by chenshaoju** [comment]
我没有办法指导你搭建服务端，你可能需要搜索一下这方面的教程了。。。

**Comment by liyi980116** [comment]
好的，感谢
