### ISSUE TITLE
BugFix win10 1903 黑色主题下， trayIcon 会消失的问题；

### ISSUE THREAD

**Issue by ayanmw** [shadowsocks/shadowsocks-windows#2657]
### Shadowsocks version / 影梭版本
v4.1.7 ~4.1.8

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows 10 1903  (黑色主题 )；

### Steps you have tried / 操作步骤

- windows10 下，外接显示器，然后（Win+P） 切换投影为 “复制” 或 仅“第二屏幕” ，会发现任务栏的图标消失，点击右键又出来了。 

- 上述只是 必现方法 而已，实际情况跟两个屏幕没有关系，会莫名其妙的出现，导致任务栏空了一个位置；

### What did you expect to see? / 期望的结果
如同 4.1.6 版本一样，图标都在。

### What did you see instead? / 实际结果
由于在 4.1.6 版本还没有此问题，所以我专门进行了git 二分定位，查找到是下面的提交的BUG

> 版本: 6f71e6cca67e2a39cebcb0bdf7aae1b5b7f1db0f
> 作者: TGSAN <tt.go@163.com>
> 日期: 2019/6/4 17:15:25
> 信息:
> Support Windows 10 1903 Light Theme
> 
> Support Windows 10 1903 Light Theme (Menu icon color)
> ----
> 已修改: shadowsocks-csharp/View/MenuViewController.cs
> 已修改: shadowsocks-csharp/shadowsocks-csharp.csproj

我以找到修复问题，虽然不知道为何出现，但是可以解决，先提交一个pull先；

**Comment by studentmain** [comment]
抄送：@TGSAN

**Comment by ayanmw** [comment]
应该不是 TGHSAN 的问题，是一个alpha 问题，我对 RGB 不太懂，稍后提交一个 pull request ~ 发现 @celeron533  重构了一次，还有问题，直接在master提交了；

**Comment by ayanmw** [comment]
解决方法，就是 去掉默认的alpha 设置，我还是不太懂为什么会在某种情况下 taryIcon会隐藏掉。 但是这很管用，因为4.1.6 以前就是这么设置的。
很简单的提交，接触一下 pull request 流程~
