### ISSUE TITLE
手机流量能访问，连上WiFi就不能访问.500 internal privoxy error

### ISSUE THREAD

**Issue by wuweijian1997** [shadowsocks/shadowsocks-windows#2659]
按网上教程，服务器是某云的轻量服务器，创建好后手机用流量能访问成功，连上WiFi就不行。
windows 访问会报500 internal privoxy error

**Comment by chenshaoju** [comment]
请不要到处发，移动到：https://github.com/shadowsocks/shadowsocks-windows/issues/2649#issuecomment-552090776
