### ISSUE TITLE
Statistics Strategy Configuration UI Design

### ISSUE THREAD

**Issue by clowwindy** [shadowsocks/shadowsocks-windows#266]
https://github.com/shadowsocks/shadowsocks-windows/pull/265

**Comment by icylogic** [comment]
目前想到的

- 选项:
  - 代理选择缓存时间
  - 分数评估方式。简单的比如提供 " [ ] * 总平均丢包率 + [ ] * 在当前时段的平均丢包率 + [ ] * 平均响应时间+ [ ] * 最大响应时间 ..." (用户在 [ ] 内输入整数，负值表示越小越好，绝对值越小影响越小，不输入视为0)。（也可以做一个Listbox, 用户选择需要的参数）
  - 地理位置是否影响选择

- 图表: 
  - 横轴: 时间
  - 纵轴
    - 响应时间
    - 丢包率
    - 实际传输流量

**Comment by clowwindy** [comment]
我觉得可以，可能做成一个窗口，在菜单上加个入口就可以了。

**Comment by icylogic** [comment]
先设计了一下。大概就是这样。配色什么的实在不会。
<img width="385" alt="2015-08-12_21-22-11" src="https://cloud.githubusercontent.com/assets/2814357/9224857/3c7842b2-4138-11e5-87ac-081ac67792d2.png">

（还没有加载数据）
<img width="409" alt="2015-08-12_21-20-12" src="https://cloud.githubusercontent.com/assets/2814357/9224832/13a9083a-4138-11e5-9ab0-c1015c0c2800.png">
（折腾了一会可以在高分屏下显示正常，字体不模糊了）

**Comment by clowwindy** [comment]
我感觉没有问题。

**Comment by icylogic** [comment]
OK，我先继续做吧。我还有一些想要调整的地方，比如 I18N，代理选择什么的。

有一个问题是，我原来的想法是做一个Service来统计，提供数据，然后提供一个简单的示例Strategy，不过现在这个Strategy已经复杂化，配置界面既有Service的设置也有Strategy的设置，那是维持现状继续分离还是干脆合并到一个单独的Strategy？

**Comment by clowwindy** [comment]
可以先放到一起，以后如果发现统计可以复用的时候再重新设计 strategy 的 API。

**Comment by icylogic** [comment]
请问加入微软出的 Microsoft.Bcl.Async ([Microsoft.Bcl.Async is Now Stable](http://blogs.msdn.com/b/bclteam/archive/2013/04/17/microsoft-bcl-async-is-now-stable.aspx)) 可以么，在 .Net 4.0 引入了 async/await 关键字和全套扩展 Async 方法。加一个 packages.config 文件以后，Visual Studio 在 Build 的时候会自动调用 Nuget 下载这些依赖。

<img width="274" alt="2015-08-13_11-19-27" src="https://cloud.githubusercontent.com/assets/2814357/9241978/344ceeec-41ad-11e5-8414-87c92cd8f06e.png">

**Comment by clowwindy** [comment]
会增加 binary 运行时的依赖么？

**Comment by icylogic** [comment]
嵌入进去还是单文件，体积有增加，目前编译 Release 是 510KB，压缩一个zip是377KB，然后Github Release页面的2.5.2 的 zip是187KB，可以接受么？

**Comment by clowwindy** [comment]
那我觉得应该没有问题，省了很多代码。

**Comment by icylogic** [comment]
好的，在 appveyor 上也编译成功了。
https://ci.appveyor.com/project/icylogic/shadowsocks-windows/build/job/ab7c8uorohi21ily/artifacts
vs 会自动下载依赖，appveyor 需要在 before build script 里加一行 nuget restore。

还有个问题，是否可以提供实际传输速率/流量统计的API。

**Comment by clowwindy** [comment]
我觉得可以，但是这个是为了什么而加呢？是统计总流量，还是每个服务器的流量？

**Comment by icylogic** [comment]
嗯，主要还是传输速率。流量对于选择没什么意义，加不加都可以。

**Comment by dangelization** [comment]
这里面有一个多代理如何测试的问题。
我最近试用了一下shadowsocksR，他那个软件就有一个类似的统计功能，在实际使用时可以先设置负载均衡，然后打开一些网页，再检查统计数据。
但是他那个也有问题，负载均衡的方式是以很快的速率转换代理，那么其实不能测出一个代理的稳定传输速率。而且ping值什么的也体现不出一个计算过的期待值。

**Comment by clowwindy** [comment]
先把目前的发布到 2.5.3 里了。

**Comment by icylogic** [comment]
额，好的。那么我先继续做没有传输速率的版本。
目前这个版本 Service 和 Strategy 是分开的，需要先打开那个 Availability Statistics，否则 Strategy 就只是个随机选择，这一点最好补充到 Readme 里。

**Comment by clowwindy** [comment]
好，已加。

**Comment by dangelization** [comment]
读了一下IStrategy，有点想法：

其实Strategy服务的还是用户的需求，那么是不是可以根据不同的需求做出不同的Strategy呢？

我现在想到的有：
看视频：这个需要high data transfer speed，package loss在一定范围内可以接受，不看重latency
玩游戏：这个需要minimum package loss，latency在一定范围内可以接受，不看重data transfer speed
看网页：主要是图片的loading，那么三项都不用很好，但是都有一定的要求
那么这样的话，就需要用户先打开自己需要的服务（例如打开游戏，打开twitch视频。。），然后再让客户端根据strategy选择server

目前就想到这些。
那么一个做法是直接开发出几个固定的Strategy model，然后用户根据需求自己选择。
第二个是直接把data transfer speed，package loss 和 latency 三项的标准交给用户自己选择

希望大家能贡献下意见。如果能有个成熟的思路/方案，就可以试试implement

**Comment by clowwindy** [comment]
有用户在 Twitter 上反馈这个策略效果不错：
 https://twitter.com/Justso_CN/status/633997690032947200

说明高可用这样仅根据当前时间点来做选择的算法还是有很大局限性。基于统计的策略可以作为接下来研究的重点。

**Comment by dangelization** [comment]
继续提供一些思路：

我记得前两天增加multiple client instances就是因为有个哥们需要不同的服务器服务不同的程序（游戏，网页什么的），现在的付费vps，shadowsocks服务什么的也是基本往多服务器多节点的方向靠。

那么SS client将来的发展方向肯定是不同类型，不同目的地的数据流量分配给不同的SS server，一个办法是通过proxycap/sockscap加用户手动设置的方法来完成，但是长远的讲如果客户端本身就能智能性的完成这个任务那就很NB了。

**Comment by icylogic** [comment]
@dangelization "第二个是直接把data transfer speed，package loss 和 latency 三项的标准交给用户自己选择" 这个就是我在做的事情啊, 看上面的讨论

**Comment by GangZhuo** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/266#issuecomment-132631370 中的推特内容设置了保护，谁能帮发一份？

**Comment by icylogic** [comment]
@GangZhuo 上次看过，就是说变快了什么的。我现在觉得单纯靠 Ping 还是不靠谱，应该把实际延迟和网速加进去

**Comment by librehat** [comment]
我在qt版本里的做法是对socket的连接进行计时。

因为服务器有可能禁止ping了

**Comment by Xorcerer** [comment]
似乎这个issue已经很久没更新了，却没有关闭。如果我想对贡献这个Feature，我可以做点什么？有谁可以分派任务吗？我熟悉C#和数据分析。
