### ISSUE TITLE
没有添加订阅的地方吗

### ISSUE THREAD

**Issue by Zachary9321** [shadowsocks/shadowsocks-windows#2667]

**Comment by chenshaoju** [comment]
移动到：https://github.com/shadowsocks/shadowsocks-windows/issues/2417

**Comment by faydanube** [comment]
1. 直接使用 SSR 订阅进行更新
2. 然后复制 SSR 的 `gui-config.json` 覆盖到 SS
3. 在 SS 直接支持订阅功能之前，使用此方法可以完美解决。
