### ISSUE TITLE
新建服务器默认使用AEAD加密

### ISSUE THREAD

**Issue by studentmain** [shadowsocks/shadowsocks-windows#2668]
### Shadowsocks version / 影梭版本
v4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
All

### Steps you have tried / 操作步骤
新建服务器

### What did you expect to see? / 期望的结果
新建服务器默认使用AEAD加密

### What did you see instead? / 实际结果
默认使用AES-256-CFB

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
N/A

建议将默认加密由aes-256-cfb替换到aes-256-gcm/chacha20-ietf-poly1305。

同时可将rc4-md5等标记为不建议使用。

**Comment by celeron533** [comment]
其实这个是由服务器决定的。。。最好的情况就是服务器刚好设置了aes-256-gcm，这样用户在配置的时候能少一次点击

**Comment by studentmain** [comment]
修改默认加密是为了反映新技术和新的最佳实践，主要不是为了减少点击。（不过能够和服务器端的默认设置一致那当然最好）

**Comment by studentmain** [comment]
另供参考，ss-libev, ss-go2, ss-rust都默认使用chacha20-ietf-poly1305，outline-ss-server文档使用chacha20-ietf-poly1305

https://github.com/shadowsocks/shadowsocks-libev/blob/e95c02b0d65812981a68e1a4d2b46e64db37d70d/debian/config.json#L7

https://github.com/shadowsocks/go-shadowsocks2/blob/3ebf4506d479f51f83bf934c513943adb42ab6b7/main.go#L46

https://github.com/shadowsocks/shadowsocks-rust/blob/39c544652436ea8dfca5ed91c79273352a5e5002/debian/config.json#L8

https://github.com/Jigsaw-Code/outline-ss-server/blob/76edca1e44933857f2cefefe1ed9be58940d100a/config_example.yml#L4

**Comment by celeron533** [comment]
OK 可以改一改
`server.cs`

```
        public Server()
        {
            server = "";
            server_port = 8388;
            method = "aes-256-cfb";
            plugin = "";
            plugin_opts = "";
            plugin_args = "";
            password = "";
            remarks = "";
            timeout = DefaultServerTimeoutSec;
        }
```
