### ISSUE TITLE
Feature Request: Allow to connect to multiple servers at the same time.

### ISSUE THREAD

**Issue by aaomidi** [shadowsocks/shadowsocks-windows#267]
Hello, I'd like to be able to connect to multiple servers at the same time and configure the connection to one server go through another server as a proxychain.

Thank you :)

**Comment by clowwindy** [comment]
You shouldn't do that. It's wasting CPU and network.

You should use this method to set up a relay: https://github.com/shadowsocks/shadowsocks/wiki/Setup-a-Shadowsocks-relay

**Comment by aaomidi** [comment]
I'm actually currently using stunnel to do this :P But i'll take a look
