### ISSUE TITLE
配置本机代理地址的模式连接局域网中的shadowsocks

### ISSUE THREAD

**Issue by leo2430** [shadowsocks/shadowsocks-windows#2670]
### Shadowsocks version / 影梭版本
4.1.8

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10/Windows server 2016

### Steps you have tried / 操作步骤
1.  服务器2016安装Shadowsocks 4.1.8 客户端，正常连接到服务器，启用PAC模式。开启它的代理功能1080端口；开启允许其他设备连入；本地测试外网正常，大陆网站正常。
2.  另外一台Windows 10 计算机，不安装Shadowsocks 软件，仅使用internet代理。
     a.  使用手动设置代理模式，地址服务器IP，端口 1080 。可以正常科学上网，但是访问大陆网站 
          缓慢，所有流量都走代理从国外饶了一圈回来
     b.  使用自动设置代理模式，脚本地址 http://IP:1080/pac .无法访问任何地址

### What did you expect to see? / 期望的结果

查看了server端的脚本地址是 http://127.0.0.1:1080/pac?t=20191115132628198&secret=ZvCeXR/NY5bSTuyB8tdNbmNDjL+n0pP9jDphcs7wjFg=

pac?后面的地址是动态变化的，那么windows 10客户端如何设置使用服务器的PAC模式？谢谢

**Comment by chenshaoju** [comment]
在未勾选保护本地PAC的情况下，在其他计算机上设置代理为 `http://192.168.1.xxx:1080/pac` 即可。
