### ISSUE TITLE
windows crash

### ISSUE THREAD

**Issue by xzzhang131** [shadowsocks/shadowsocks-windows#2672]
### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows 10

### Steps you have tried / 操作步骤 
随便点，一点就崩溃，第一步就崩溃

### What did you expect to see? / 期望的结果 
![错误提示](https://user-images.githubusercontent.com/39792011/68944541-0328c780-07e9-11ea-879b-484dfa5f6b85.png)
解决软件崩溃

**Comment by chenshaoju** [comment]
请尝试将 Shadowsocks.exe 单独放到一个新的目录中，比如 D:\SS\ 看看？
