### ISSUE TITLE
如果使用git的时候， 用socket代理， 如何对一些服务器区别对待

### ISSUE THREAD

**Issue by maikebing** [shadowsocks/shadowsocks-windows#2673]
如果使用git的时候， 用socket代理， 如何对一些服务器区别对待，比如对github.com 进行翻墙， 但是对 国内的gitee.com 就不翻墙。

**Comment by chenshaoju** [comment]
你可能得写个脚本，设置不同的环境变量了：
https://www.zhihu.com/question/27159393

**Comment by maikebing** [comment]
但是我觉得通过pac 会不会好点？要不然很麻烦。

**Comment by chenshaoju** [comment]
git不支持pac……这个没办法。

**Comment by maikebing** [comment]
有没有办法 从shadowsocks下手

**Comment by chenshaoju** [comment]
你可能得试试 Proxifier 或者 sockscap64 了。

注意：这是第三方的软件。
