### ISSUE TITLE
一直提示err_connection_closed

### ISSUE THREAD

**Issue by okeehou** [shadowsocks/shadowsocks-windows#2675]
# Shadowsocks version / 影梭版本
4.1.6, 4.1.7.1, 4.1.8.0...

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10, Windows 7

### Steps you have tried / 操作步骤
更新版本，重启电脑，更新PAC，开全局，更换加密方式，等等等等。。。

### What did you expect to see? / 期望的结果
正常连接

### What did you see instead? / 实际结果
经常提示err_connection_closed

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
其实我查看了客户端日志，一切正常。但就是连不上，一直提示err_connection_closed。我尝试用libev版，obfs插件，tls，chacha20-ietf-poly1305就可以用。同个服务器，切换 到python版就无法连了。电信，联通，移动（最常见的是移动）都出现过。

有时候过一段时间刷新就能连上了，但几秒后或者几分钟后就再出现这种情况。

但是python版又不支持插件。libev版又不能设置多端口。我太难了！感觉这应该跟网络有关吧？求助！

**Comment by chenshaoju** [comment]
你的服务器如果是自己搭的，请尝试在更换IP后套个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by okeehou** [comment]
> 你的服务器如果是自己搭的，请尝试在更换IP后套个插件：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

问题的是我的IP没有被封。大部分用户可以用。只有几个人出现这个问题。再说，我用libev版ofbs插件是可以的，切换到python版（意味着没有插件）就不行。

**Comment by chenshaoju** [comment]
我怀疑是你所在的网络存在某种监控系统，或者过滤系统，干扰了你的网络访问。
