### ISSUE TITLE
为何这个软件没有服务器订阅啊！需要服务器订阅啊！求添加功能啊！

### ISSUE THREAD

**Issue by FisherTsou** [shadowsocks/shadowsocks-windows#2676]

**Comment by studentmain** [comment]
#1703 #1819 #2147 #2265 #2268 #2277 #2417 #2667

**Comment by faydanube** [comment]
1. 直接使用 SSR 订阅进行更新
2. 然后复制 SSR 的 `gui-config.json` 覆盖到 SS
3. 在 SS 直接支持订阅功能之前，使用此方法可以完美解决。
