### ISSUE TITLE
shadowshosks进行了正确的配置后可以科学上网了，但是无法上wiki

### ISSUE THREAD

**Issue by Viceeee** [shadowsocks/shadowsocks-windows#2677]
### Shadowsocks version / 影梭版本

4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1903 version

### Steps you have tried / 操作步骤
1、打开shadowsocks，连接服务器，连接成功后可以上Google
2、上Google后无法打开wiki

### What did you expect to see? / 期望的结果
能上wiki

### What did you see instead? / 实际结果

不能上wiki.en

**Comment by chenshaoju** [comment]
你访问的是 https://en.wikipedia.org/wiki/Main_Page 吗？我这儿没有问题。

**Comment by Viceeee** [comment]
是的，我在国内，并不能访问

**Comment by chenshaoju** [comment]
请确保你的SS工作在PAC模式，如果仍然不行，请尝试在PAC菜单中点击从GFWList更新本地PAC。

**Comment by Viceeee** [comment]
SS是在PAC模式下运行，试了一下您说的从GFWList更新，也还是上不了https://en.wikipedia.org/ 
错误显示 ERR_CONNECTION_RESET

**Comment by Viceeee** [comment]
SS是在PAC模式下运行，试了一下您说的从GFWList更新，也还是上不了https://en.wikipedia.org/ 
错误显示 ERR_CONNECTION_RESET

**Comment by chenshaoju** [comment]
请尝试用IE浏览器看看能否访问？

**Comment by Viceeee** [comment]
IE浏览器可以上，但是我经常用的Chrome上不了，请问可以解决么

**Comment by Viceeee** [comment]
现在可以上了，谢谢您
