### ISSUE TITLE
以一种访问权限不允许的方式做了一个访问套接字的尝试。

### ISSUE THREAD

**Issue by tpkeeper** [shadowsocks/shadowsocks-windows#2679]
System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.PipeRemoteReceiveCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2547
