### ISSUE TITLE
公司内网+http代理环境能否使用shadowsocks

### ISSUE THREAD

**Issue by liangchengzhi** [shadowsocks/shadowsocks-windows#2681]
我的shadowsocks可以在家使用，使用PC上google没有问题。
但是在公司不行。公司是使用内网+http代理来上网。
如果不连公司代理，本身是无法上网的。假设公司的内网代理是 http://10.20.1.91:8080。
我安装完shadownsocks，启动系统代理后，连baidu也无法上了。

请问有什么办法？

**Comment by liangchengzhi** [comment]
![image](https://user-images.githubusercontent.com/18716151/69063282-2e185300-0a57-11ea-8609-e10a10b561b5.png)

我尝试使用正向代理，但是配置代理后，仍然无法上google，甚至连baidu也无法上网

**Comment by chenshaoju** [comment]
请在公司的计算机上启动SS后，右击托盘区的纸飞机图标，选择正向代理设置，然后参考下图：
![image](https://user-images.githubusercontent.com/515763/69063396-63bd3c00-0a57-11ea-9140-8cbc9c28c831.png)

请注意：你的代理必须支持HTTP CONNECT，如果仍然不行，说明你的代理不支持，无法使用。
