### ISSUE TITLE
突然无法启动程序

### ISSUE THREAD

**Issue by Zebartin** [shadowsocks/shadowsocks-windows#2682]
### Shadowsocks version / 影梭版本
4.1.8

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win 10，.NET Framework 4.8

### Steps you have tried / 操作步骤
打开程序
在出错后重新安装.NET Framework，也使用官方.NET Framework修复工具，仍然报错

### What did you expect to see? / 期望的结果
正常运行

### What did you see instead? / 实际结果
报错

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
![20191120143410.png](https://i.loli.net/2019/11/20/RNFfDgkZeYpA3h8.png)

**Comment by chenshaoju** [comment]
你的 .NET 可能损坏了，请尝试安装/修复看看：https://dotnet.microsoft.com/download/dotnet-framework/net48
