### ISSUE TITLE
连接意外关闭

### ISSUE THREAD

**Issue by zhhaochen** [shadowsocks/shadowsocks-windows#2683]
### Shadowsocks version / 影梭版本
4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows10

### Steps you have tried / 操作步骤
连接vultr服务器，pac模式，总会自己断开

### What did you expect to see? / 期望的结果
正常上网

### What did you see instead? / 实际结果
经常性访问外网错误

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 连接被意外关闭。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
看起来很像是被屏蔽了：https://github.com/shadowsocks/shadowsocks-windows/issues/2551
如果你的服务器是自己搭建的，请尝试套个插件看看看： https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by zhhaochen** [comment]
> 看起来很像是被屏蔽了：#2551
> 如果你的服务器是自己搭建的，请尝试套个插件看看看： [#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

用台式机就没有出现这种情况，用笔记本经常性断掉，还要再重开

**Comment by chenshaoju** [comment]
笔记本和台式机在同一个网络吗？

如果是，请尝试在笔记本上以管理员身份启动命令提示符或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机看看·。
