### ISSUE TITLE
我这是被GFW盯上了吗

### ISSUE THREAD

**Issue by yadex** [shadowsocks/shadowsocks-windows#2684]
很奇怪，我只要一运行v2ray或者ss, 一分钟内与服务器自动断开，并且ping不通了，ssh连不上，搬瓦工vultr和阿里云皆是如此。把程序关了，大概过了五分钟又好了，重复如此，已经进入一个死循环。

**Comment by fairytaleTY** [comment]
昨天开始出现，最近局势紧张

**Comment by chenshaoju** [comment]
如果你使用的是SS，请尝试套一个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

如果你用的是V2Ray，请尝试工作在TLS模式。

**Comment by xwlcn** [comment]
同样的情况，间接性断开，不是服务器网络原因，应该又是什么紧张时刻。

**Comment by matrixknight** [comment]
> 昨天开始出现，最近局势紧张

最近有什么局势?

**Comment by maxiaolin9495** [comment]
上面四个自卑，你能怎么办

**Comment by chenshaoju** [comment]
Issues 是反馈软件问题的地方，不建议进行其他方面的讨论，此Issue即将被关闭。
