### ISSUE TITLE
检测IP和端口正常，但是timed out无法科学上网

### ISSUE THREAD

**Issue by sunflowering** [shadowsocks/shadowsocks-windows#2685]
### Shadowsocks version / 影梭版本
4.1.80

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
1. ping可以通

正在 Ping 手动隐藏 具有 32 字节的数据:
来自 手动隐藏 的回复: 字节=32 时间=154ms TTL=49
来自 手动隐藏 的回复: 字节=32 时间=148ms TTL=49
来自 手动隐藏 的回复: 字节=32 时间=163ms TTL=49
来自 手动隐藏 的回复: 字节=32 时间=157ms TTL=49

手动隐藏 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 148ms，最长 = 163ms，平均 = 155ms
***
2. 检查IP和端口正常
用站长工具等从国内和国外显示IP和端口正常，
用搬瓦工官方检测也显示IP没有被封。

### What did you expect to see? / 期望的结果
科学上网

### What did you see instead? / 实际结果
不能上网

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-11-21 10:12:14] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
[2019-11-21 10:12:14] Checking GFWList from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
[2019-11-21 10:12:14] connect to raw.githubusercontent.com:443
[2019-11-21 10:12:19] 手动隐藏 timed out
[2019-11-21 10:12:19] connect to raw.githubusercontent.com:443
[2019-11-21 10:12:21] connect to www.googleapis.com:443
[2019-11-21 10:12:24] 手动隐藏  timed out
[2019-11-21 10:12:24] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-11-21 10:12:26] 手动隐藏  timed out

**Comment by sioulisn** [comment]
If someone can speak english here,
since yesterday China vblocks the ports. 

that happens in all my servers Korea, HK, TW  in 3 different ISPs 

I change the ports and immediatly get blocked after 2-3 minutes

I use SS for many years but this time it seems is seriously getting blocked

**Comment by sunflowering** [comment]
> If someone can speak english here,
> since yesterday China vblocks the ports.
> 
> that happens in all my servers Korea, HK, TW in 3 different ISPs
> 
> I change the ports and immediatly get blocked after 2-3 minutes
> 
> I use SS for many years but this time it seems is seriously getting blocked

Oh, what happened?
The wall has been upgraded again?
It's terrible. How can I use google?

**Comment by sioulisn** [comment]
everything i have tried until now is getting blocked instantly, i am not expert. I wait if anyone can help.
v2ray also not working to me

**Comment by sunflowering** [comment]
> everything i have tried until now is getting blocked instantly, i am not expert. I wait if anyone can help.
> v2ray also not working to me

So sad.I tried to find the problem, but it seems that everything is normal, except that I can't get online for google.

我尝试去找到问题，但一切看起来都很正常——只是我不能科学上网。太悲伤了

**Comment by chenshaoju** [comment]
The log looks like your connection has been cutoff.

If your server is built by yourself, Please try install a plugin: https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by sioulisn** [comment]
Can you write is a guide step by step how to add the plugins?

**Comment by sioulisn** [comment]
@chenshaoju 
Can you write is a guide step by step how to add the plugins?

**Comment by sunflowering** [comment]
> The log looks like your connection has been cutoff.
> 
> If your server is built by yourself, Please try install a plugin: [#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

thanks, I will try it after work.
谢了，下班后我捣腾下

**Comment by sioulisn** [comment]
@chenshaoju 
it worked!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
thanks!!!!!!!!!!!!!!!!!!!!!!

**Comment by sunflowering** [comment]
忘了来反馈了，还没装套件之前，突然又恢复正常了。真是迷
