### ISSUE TITLE
WSL Support

### ISSUE THREAD

**Issue by florianmonfort** [shadowsocks/shadowsocks-windows#2686]
### Shadowsocks version / 影梭版本

4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows 10 latest release

### Steps you have tried / 操作步骤

- Using Proxifier
- Setting Shadowsocks client as "Global"
- Using Outline client

### What did you expect to see? / 期望的结果

WSL command lines can go through Shadowsocks proxy

### What did you see instead? / 实际结果

WSL ignores Shadowsocks proxy even if set as "Global"

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

Seems no errors to show, Shadowsocks connects successfully.

**Comment by chenshaoju** [comment]
In WSL, Please set your proxy info by useing these command:
```
export http_proxy=http://127.0.0.1:1080
export https_proxy=http://127.0.0.1:1080
```
If your shadowsocks local proxy is not 1080, Change it before use.

For example:
![image](https://user-images.githubusercontent.com/515763/69303805-4d7ece00-0c59-11ea-8909-4d1adc3811f1.png)

**Comment by florianmonfort** [comment]
> In WSL, Please set your proxy info by using these command:
> 
> ```
> export http_proxy=http://127.0.0.1:1080
> export https_proxy=http://127.0.0.1:1080
> ```
> 
> If your shadowsocks local proxy is not 1080, Change it before use.
> 
> For example:
> ![image](https://user-images.githubusercontent.com/515763/69303805-4d7ece00-0c59-11ea-8909-4d1adc3811f1.png)

@chenshaoju it seems to be working, how to turn it off afterwards if want to turn it off?

**Comment by chenshaoju** [comment]
You can simply simply shutdown your WSL by using `wslconfig.exe -t ubuntu`, This will clean all environment variable.

Or, You can use these command to set proxy environment variable to null.
```
export http_proxy=
export https_proxy=
```

Example:
![Screenshot2](https://user-images.githubusercontent.com/515763/69408646-657e4c80-0d42-11ea-923e-9f43454f943b.png)

**Comment by florianmonfort** [comment]
@chenshaoju that's great, thanks so much for the tip! I'd suggest you guys add that to your FAQ somewhere or documentation, it's very useful to know for those who are not very familiar with the internals of WSL but still would like to use it with the proxy.

**Comment by florianmonfort** [comment]
@chenshaoju sometimes I try and it doesn't work:

But I have checked my port config and it's correct:

![image](https://user-images.githubusercontent.com/1446429/70298294-1cdb8e80-182c-11ea-93ed-53613740c699.png)
![image](https://user-images.githubusercontent.com/1446429/70298307-2a911400-182c-11ea-8f66-2e3d51d445ca.png)

**Comment by chenshaoju** [comment]
The `ping` command is ICMP protocol, It's unable through proxy.

Try `curl` or `wget`.

**Comment by florianmonfort** [comment]
@chenshaoju when I access gitlab through browser it's super fast using proxy with shadwsocks. Even if shadowsocks is working well and I can curl google.com successfully, doing a git clone is still very very slow:

![image](https://user-images.githubusercontent.com/1446429/70372808-d61a9100-191e-11ea-94e9-86a720fe8beb.png)

**Comment by chenshaoju** [comment]
maybe try socks5 protocol:
```
export http_proxy=socks5h://127.0.0.1:1080
export https_proxy=socks5h://127.0.0.1:1080
```

**Comment by florianmonfort** [comment]
@chenshaoju same result:

![image](https://user-images.githubusercontent.com/1446429/70384712-357bae00-19be-11ea-86d3-bb2e75fbe9b3.png)

**Comment by chenshaoju** [comment]
If using SSH, may try this:
https://github.com/shadowsocks/shadowsocks-windows/issues/2686

After `set ssh proxy` line.

**Comment by studentmain** [comment]
Maybe add some documents after WSL2 become stable

**Comment by DeepDarkOdyssey** [comment]
On WSL2 it's not working.
Because WSL can't see windows as `localhost`, so I have to get the proxy ip as described in `/etc/resolv.conf`:
![image](https://user-images.githubusercontent.com/37280638/71095052-eec05c00-21e6-11ea-8d22-7fbc26ea01fb.png)

Then I set the proxy env variable:
![image](https://user-images.githubusercontent.com/37280638/71095132-0d265780-21e7-11ea-930e-2a8b24b00e8b.png)

But curl to google.com still doesn't work:
![image](https://user-images.githubusercontent.com/37280638/71095275-43fc6d80-21e7-11ea-8ec8-b97f4ee7eccf.png)
Of course I have already set the shadowsocks properly and can acess to google on windows side.
![image](https://user-images.githubusercontent.com/37280638/71095416-84f48200-21e7-11ea-9464-0872b53e2f8a.png)
So what's the problem? Did something went wrong with WSL2?

**Comment by chenshaoju** [comment]
From your curl log, The proxy looks set Successfully, But the proxy no responding.

![image](https://user-images.githubusercontent.com/515763/71139545-6d4de580-2249-11ea-9972-7995c73c8874.png)

If your WSL2 and Shadowsocks are on same computer, try 127.0.0.1?

If not are on the same computer, maybe is your Shadowsocks computer Windows Firewall settings not correct. Please check your Windows Firewall port allow list, is allowed your Shadowsocks proxy port?
