### ISSUE TITLE
求助，昨天还用的好好的，半夜突然就time out 无法翻墙了。

### ISSUE THREAD

**Issue by wattcher44** [shadowsocks/shadowsocks-windows#2687]
-->

### Shadowsocks version / 影梭版本
4.1.8.0

### Steps you have tried / 操作步骤
在ip100.info检测搬瓦工的IP和端口都是open
我一开始以为SS端口被封（原端口8080），然后换了几个端口都不行。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
错误日志：
[2019-11-21 15:52:17] Shadowsocks started (4.1.8.0)
[2019-11-21 15:52:18] Shadowsocks started (4.1.8.0)
[2019-11-21 15:53:15] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-11-21 15:54:00] 176.122.132.131:18361 timed out
[2019-11-21 15:54:36] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-11-21 15:56:27] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-11-21 15:56:47] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-11-21 15:56:48] 176.122.132.131:18361 timed out
[2019-11-21 15:56:49] 176.122.132.131:18361 timed out
[2019-11-21 15:56:51] 176.122.132.131:18361 timed out

**Comment by chenshaoju** [comment]
测了一下，可能是你的服务器挂了。

你可以使用这个第三方的服务测试一下：https://ip100.info/check

如果你的服务器是自己搭的，国内和国外都不通的话，请访问你的VPS的控制台，看看是不是欠费了或者服务没启动。

**Comment by wattcher44** [comment]
> 测了一下，可能是你的服务器挂了。
> 
> 你可以使用这个第三方的服务测试一下：https://ip100.info/check
> 
> 如果你的服务器是自己搭的，国内和国外都不通的话，请访问你的VPS的控制台，看看是不是欠费了或者服务没启动。

这个我测过了啊，国内国外都是open。VPS那边也是正常的

**Comment by chenshaoju** [comment]
我不知道为什么，你的日志最后显示的IP和端口测试出来都是Closed。

请尝试在有问题的计算机上使用这个第三方的小工具测试你的服务器是否能从有问题的计算机上连接上：https://github.com/chenshaoju/tcpportcheck

**Comment by wattcher44** [comment]
> 我不知道为什么，你的日志最后显示的IP和端口测试出来都是Closed。
> 
> 请尝试在有问题的计算机上使用这个第三方的小工具测试你的服务器是否能从有问题的计算机上连接上：https://github.com/chenshaoju/tcpportcheck

这个小工具下载不了啊。我试了下，日志里面这个SS的端口确实是closed，但我用VPS的SSH端口测试都是open  
这是为什么，本人比较白，搞不太清楚这两个端口具体的区别

**Comment by wattcher44** [comment]
> 我不知道为什么，你的日志最后显示的IP和端口测试出来都是Closed。
> 
> 请尝试在有问题的计算机上使用这个第三方的小工具测试你的服务器是否能从有问题的计算机上连接上：https://github.com/chenshaoju/tcpportcheck

这个小工具我试了，很奇怪，测试IP和SSH端口，一会通一会又不通，十次里面大概六七次是通的。

**Comment by chenshaoju** [comment]
你的网络可能遭遇了间歇性干扰。

如果你懂命令提示符，可以用 tcping 测试以进行确定，不过有点复杂：https://github.com/shadowsocks/shadowsocks-windows/issues/2016#issuecomment-424193695

**Comment by matrixknight** [comment]
同样问题, 自己在国外虚机上搭的ss也不能用了

**Comment by chenshaoju** [comment]
如果可能，请在更换IP后，套个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836
