### ISSUE TITLE
怎么获取到Shadowsocks.exe文件啊？

### ISSUE THREAD

**Issue by huangwuzhao** [shadowsocks/shadowsocks-windows#2689]
怎么获取到Shadowsocks.exe文件啊？

**Comment by Stzx** [comment]
https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by huangwuzhao** [comment]
> https://github.com/shadowsocks/shadowsocks-windows/releases
多谢，不过下载下来一直没法启动，我找找看原因。
