### ISSUE TITLE
Shadowshocks 错误：系统找不到指定的文件

### ISSUE THREAD

**Issue by PengruiXu** [shadowsocks/shadowsocks-windows#2690]
### Shadowsocks version / 影梭版本
4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
4.7.2

### Steps you have tried / 操作步骤

添加节点 adding the server
### What did you expect to see? / 期望的结果
添加成功 sussfully add the server

### What did you see instead? / 实际结果

Shadowsocks错误:系统找不到指定的文件.
System.ComponentModel.Win32Exception (0x80004005):系统找不到指定的文件.
在System.Diagnostics. Process. StartWithCreateProcess(ProcessStartinfo startinfo)在System.Diagnostics. Process. Start()
在Shadowsocks.Controller. Service. Sip003Plugin. StartifNeeded()
在Shadowsocks.Controller.ShadowsocksController.GetPluainLocalEndPointifConfio ured(Server server)在Shadowsocks. Controller. ShadowsocksController.Reload()

**Comment by chenshaoju** [comment]
你是否从什么地方导入的 SS:// 的地址？如果是，你的这个地址可能依赖某个插件。

请仔细阅读提供者的信息，如果你的是购买的服务，请与你的SS服务商取得联系。

**Comment by PengruiXu** [comment]
> 你是否从什么地方导入的 SS:// 的地址？如果是，你的这个地址可能依赖某个插件。
> 
> 请仔细阅读提供者的信息，如果你的是购买的服务，请与你的SS服务商取得联系。

是从Dler Cloud倒入的，谢谢

**Comment by studentmain** [comment]
可能与#2648 重复
