### ISSUE TITLE
针对这两天时断时续的情况，说一说我观察到的一些规律以及临时解决办法

### ISSUE THREAD

**Issue by qwerttvv** [shadowsocks/shadowsocks-windows#2691]
写在最开始，我声明一下儿，我爱党爱国，我翻墙就是看youtube国外美食视频，还有野外生活，别的啥都不干……

首先我是自己租的vps，自己搭的ss，除了ss，没有跑别的服务，而且这个ss只有我自己一个人用，设备的话就是两个路由器，一个手机，一个笔记本电脑

这几天的症状就是时断时续，一会儿好，一会儿就不行了，我估计大伙儿都这样儿吧？

最早是干掉ip，后来整段ip段封锁，再后来是干掉你端口号，不会干你的ip，那会儿只要重新配置服务端，改端口号就可以复活

然而这两天开始，墙变了，不会封你的服务端ip和端口了，会在你本地ip封锁干扰你，时断时续的

我可能没说明白……我的意思就是封锁方式变成了你本地的ip不能访问服务端的ip

我是怎么发现的呢？

pc端不好用的时候儿，我在pc端发现服务端的ip不通了，然后我用在线ping工具，发现全国各地绝大多数地区返回结果是服务端ip是通的，我再次确认了本地pc不能访问服务端

然后我直截了当用手机4g流量连接服务端，发现是正常的！

我重启光猫，重新获取了本地ip地址，瞬间好了！

然而用了大半天儿，发现又断断续续了

我这次试了试ping -t，发现干扰是无规律的，断的短的5分钟，长的20多分钟，存活时间也是没规律的……

不说了，反正闹清楚原理了，我也不可能一出毛病就重新拨号吧？

那我是怎么临时性接解的呢？

我撸的超便宜的国内的vps，我也开了ss，你知道ss客户端有个正向代理功能吧，嗯，用上了……

目前看起来，墙可能盯上的只有民用拨号宽带……

还有一个思路，费钱一些，搞n个ss服务端，选高可用性试试？一个人十个线路，你干扰一个，我用别的，你干扰到那个了，这个说不定放出来了……思路而已，没有尝试

**最后，大伙儿集思广益，看看纯在ss范畴，还有没有别的解决方案呢？**

**Comment by Nikolay-Jiang** [comment]
居然还有不封IP的，我这边直接封IP的都是...好悲催

**Comment by advancing-king** [comment]
我也遇上了同样的问题。。

**Comment by StephenChips** [comment]
可以试一下混淆，但是这玩意要搭配Ngnix使用

**Comment by bensonwind** [comment]
从两天前开始，每次连接后不出一分钟必被封锁，换了服务器ip、端口、加密算法都没用。今天试了试楼主的方法，在国内的VPS搭了ss-local做sock5跳板，好了，现在改跳板被封锁了。。。生活好难啊
想知道楼主的超便宜国内vps在哪儿撸的？

**Comment by gavinyueng** [comment]
我也是 我用的谷歌云ssr 就是用一会就断 过一会就能连上了 用的电信宽带
换了好多次IP和端口也是这样的问题 可能墙又升级了 就看有没有高手能解决

**Comment by qwerttvv** [comment]
那个跳板被封，我也发现了……最新情况是搭别的连接国内vps

反正现在vps到国外ss服务端，一直是好的

**Comment by xhqpp** [comment]
就是这几天开始的 墙学会了tcp闪断技能

**Comment by szwifi** [comment]
> 那个跳板被封，我也发现了……最新情况是搭别的连接国内vps
> 
> 反正现在vps到国外ss服务端，一直是好的

可以讲一下具体的做法吗？
@qwerttvv

**Comment by jiangliu2u** [comment]
这几天 我也是 看YOUTUBE看一会就断了, 主机ping不通  过个十分钟又好了 两个vps也这样 我用的brook...

**Comment by nshen** [comment]
太恐怖了，还让不让人活了

**Comment by LovageIO** [comment]
我的也是，我已经试过好几个不同ip， 加密方式。直接ping ip 地址也是时断时续。 简直令人发指!

**Comment by xunzhaoderen** [comment]
看来大家都遇到了相同的问题

**Comment by chenshaoju** [comment]
如果各位的服务器是自己搭建的，请尝试更换IP后套个插件：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

个人推荐V2Ray-Plugin或Cloak，建议配置为工作在TLS模式下。

**Comment by claford-v-lawrence** [comment]
This has nothing to do with shadowsocks.
If I'm not too much mistaken, this is due to the GFW sniffing ( or possibly spoofing ) your dns queries. I've experienced the same problems on Chrome, but when I use firefox and proxy my dns traffic through socksv5 tunnel, everything still works find. So this is not the problem of shadowsocks. I'd suggest you either switch to firefox ( all hail the great firefox ) or use something like simplednscrypt.

**Comment by jiangliu2u** [comment]
貌似现在好了?

**Comment by forever8938** [comment]
你自我审查也没用，抓到了一样牢底坐穿

**Comment by suosui** [comment]
我的是限速。

**Comment by ITTroy** [comment]
好烦啊，跟楼主一样的情况，求解决啊啊 啊啊啊啊

**Comment by V-zhangyunxiang** [comment]
换成 book 会不会好点

**Comment by qwerttvv** [comment]
> 如果各位的服务器是自己搭建的，请尝试更换IP后套个插件：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)
> 
> 个人推荐V2Ray-Plugin或Cloak，建议配置为工作在TLS模式下。

cloak我在服务端弄好了，win下客户端也弄好了，已经通了，路由器我一个k3，为了这玩意儿刷了几个固件了，怎么都不行，另一个路由新3刷的hiboy老毛子，也弄不好……求助一下儿……

**Comment by chenshaoju** [comment]
我从来没有在路由器上搭建过SS……

**Comment by qwerttvv** [comment]
我再鼓捣鼓捣看看……

**Comment by hzmabin** [comment]
我的也一样，ping的时候时断时续 。。。。

**Comment by fankangsong** [comment]
深圳电信，遇到的情况跟po 主一样。暂时还不知道如何解决。

**Comment by UNlax913** [comment]
小白刚搭好，遇到比较离奇的事情了，绕过局域网和大陆就懒得关。结果一两天之后，ip都能ping通的，还挺稳的，结果就是上不去

**Comment by zhengyuchuan** [comment]
我这比较奇葩，就是用大概30分钟，就断5分钟。过5分钟就又能用了。。。。

**Comment by wenshitaiyi** [comment]
现在已经2026年了，这个问题依旧存在，之前用的移动，没啥感觉，换到电信之后就时不时的会断。

**Comment by xuanhuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。 
  
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ccy2019** [comment]
您的邮件已收到，感谢您对我们活动的支持。

**Comment by wenshitaiyi** [comment]
这个问题我后来也遇到乱，换了一个思路处理，重启路由器换到一个可用的 IP 上开始开发，使用 codex 辅助修改软件发送位置的代码，调整头部字节都发送的节奏，稍微慢一点，碎一点，后续就可以正常发送数据。
