### ISSUE TITLE
Do we have the source of "privoxy.exe" & "sysproxy.exe"?

### ISSUE THREAD

**Issue by mingtong** [shadowsocks/shadowsocks-windows#2692]
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

I want to port this project to .NET Core (I am working on macOS and target Linux), but I found the title mentioned "exe" files are stored as Resouces file in "data" folder and to be executed as process.

So, do we have the source of "privoxy.exe" & "sysproxy.exe"?
If not, are they optional?

**Comment by studentmain** [comment]
privoxy is used for convert socks5 proxy to http proxy. sysproxy is used for modify windows http proxy config. (you can implement them by your self)

critical problem is livsscrypto.dll, it's crypto lib used in ss-csharp.

privoxy is that famous http proxy server, you can find it's source code easily by searching.

sysproxy and libsscrypto is maintained by shadowsocks project. you can find them by check repositories under shadowsocks organization.

> port this project to .NET Core

By the way, PR is always welcome.

**Comment by imba-tjd** [comment]
.NET Core supports Winform only when it's on Windows. You cannot use this project even if it's on .NET Core

**Comment by mingtong** [comment]
> .NET Core supports Winform only when it's on Windows. You cannot use this project even if it's on .NET Core

It's doesn't matter, I currently just want to make it run as a server and to be deployed on Linux, so I would drop all the UI related code.
And sure, I need to do some changes on the (Windows Only)code to make it happen.

**Comment by chenshaoju** [comment]
Why not using libev version?
https://github.com/shadowsocks/shadowsocks-libev

**Comment by mingtong** [comment]
> Why not using libev version?
> https://github.com/shadowsocks/shadowsocks-libev

libev version OK for use.
I just want to try .net core.

**Comment by johnx7271** [comment]
I dont think privoxy is needed any more, maybe needed for very early version of IE, which only support socks4.
I have a version (check my fork of this project) that hase privoxy removed .
The privoxy is a left-over that are both useless and cumbersome. It add costs to both performance and code maintainance. 
I dont like privoxy  from the begining, this shadowsocks is a security sensitive tool, it should expose to external codes as little as possible.
