### ISSUE TITLE
[询问] 好奇知道shadowsocks-windows是怎么让本地流量走代理的呢？

### ISSUE THREAD

**Issue by StephenChips** [shadowsocks/shadowsocks-windows#2693]
比如说，我开了个Chrome上谷歌，我开了小飞机之后，浏览器是怎么让流量转发到shadowsocks-windows客户端，而不是直接把数据包发出去呢？

**Comment by chenshaoju** [comment]
https://en.wikipedia.org/wiki/Proxy_auto-config

**Comment by studentmain** [comment]
ss调整系统代理设置，各应用程序自愿遵守系统代理设置
