### ISSUE TITLE
有什么办法在重启电脑后，未输入密码之前让SS运行起来？

### ISSUE THREAD

**Issue by xspeed1989** [shadowsocks/shadowsocks-windows#2696]
有什么办法在重启电脑后，未输入密码之前让SS运行起来？也就是还没有进入桌面之前
ss支不支持 evertyhing的那种业务其实在service ，ui只用来显示和配置用呢！

**Comment by chenshaoju** [comment]
SS本身不支持，但是有第三方的应用可以做到。
第三方链接，仅供参考，风险自担：
https://www.google.com/search?q=run+any+program+as+a+service

**Comment by xspeed1989** [comment]
> SS本身不支持，但是有第三方的应用可以做到。
> 第三方链接，仅供参考，风险自担：
> https://www.google.com/search?q=run+any+program+as+a+service

估计是不行的，重启之后会话都没建立！GUI无法显示

**Comment by chenshaoju** [comment]
如果你不了解服务方式运行的话，我建议你启用Windows的自动登录。

按Win+R，在运行对话框中输入：`rundll32 netplwiz.dll,UsersRunDll`，然后回车，并取消“要使用本机，用户必须输入用户名和密码”，再输入想要自动登陆的Windows用户名和密码即可。
