### ISSUE TITLE
Firefox 41.0b1 x64 下PAC不稳定

### ISSUE THREAD

**Issue by Gzxhwq** [shadowsocks/shadowsocks-windows#270]
使用PAC模式，不稳定，用着用着很快就失效了。全局走Shadowsocks-windows，暂时没这问题。

自家和公司两台不同的机子上都是如此，换回32位Firefox正常。
刚开始以为是64位Firefox的bug，但是换成cow手动指定PAC则没这个问题，很稳定。

希望作者也测试一下，看看是否能重现？

环境如下：
Shadowsocks-windows 2.52，
Firefox 41.0b1 x64，
Windows 10 x64

**Comment by icylogic** [comment]
失效具体是指什么

**Comment by Gzxhwq** [comment]
失效就是不走代理了，“连接被重置”，撞墙了

**Comment by icylogic** [comment]
嗯。。我这里没有重现。我想到的几条可能的测试手段，不知道你尝试过没有。因为简单的连接被重置不好判断是哪里的问题。

- Firefox 会缓存 PAC 一段时间，可能是 Firefox 获取新的 PAC 出现问题，所以在你认为遇到了 PAC 失效的情况时：
  - 在 Preference->Advanced->Network->Settings 里 Reload，然后刷新页面尝试
  - 手动访问你在 Firefox 中填的 PAC 地址，是否会下载一个有效的 PAC 文件
  - 用 Pactester 之类的软件测试一下
- 其他浏览器，比如 IE，Firefox Stable，Chrome 是否有这个问题

**Comment by Gzxhwq** [comment]
看样子应该是64位firefox的问题，失效期间，edge、ie、chrome都是没问题可以正常工作的。谢谢了。
