### ISSUE TITLE
Chrome无法使用 但Chrome无痕模式和Edge可以

### ISSUE THREAD

**Issue by Coegle** [shadowsocks/shadowsocks-windows#2700]
### Shadowsocks version / 影梭版本
4.0.9

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

### Steps you have tried / 操作步骤
使用WiFi连接，重装了Chrome和SS，并且暂停了所有插件，没有第三方代理。
![image](https://user-images.githubusercontent.com/43529970/69558276-e491b000-0fe2-11ea-88f8-05c9163224ce.png)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

左为正常，右为无痕模式

![image](https://user-images.githubusercontent.com/43529970/69558128-abf1d680-0fe2-11ea-858f-fa627eb3e216.png)

分别查看了chrome://net-internals/#proxy 都是空白

![image](https://user-images.githubusercontent.com/43529970/69557988-70efa300-0fe2-11ea-9e61-5b459b4ec13b.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2655
