### ISSUE TITLE
为什么用“负载均衡”比不用“负载均衡”慢？

### ISSUE THREAD

**Issue by okudayukiko** [shadowsocks/shadowsocks-windows#2702]
我在一个SS服务器上开了多个SS端口
V2Ray有多端口通讯功能，那么SS的“负载均衡”算不算SS客户端的多端口功能？
我把SS服务器的多个SS端口都加入到SS服务器列表中，为什么用“负载均衡”反而比只用某个固定的SS服务器慢？

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

**Comment by chenshaoju** [comment]
负载均衡是针对你的应用发起的连接请求，随机的分配服务器进行连接。
因此，如果凑巧你的某个服务器挂了，那么某条连接就会一直卡着直到超时。
