### ISSUE TITLE
未正常关闭之后，出现了问题。

### ISSUE THREAD

**Issue by itsok228** [shadowsocks/shadowsocks-windows#2708]
### Shadowsocks version

4.1.8.0

### 使用环境

操作系统win10，.NET Framework版本4.8

### Steps you have tried

有一次没有关闭shadowsocks，就关闭了电脑，之后就出现浏览器无法打开墙内网站，只有运行shadowsocks，才能正常打开墙内网站。

### What did you expect to see? 

未运行shadow socks的情况下，不影响墙内网站的正常打开。

### What did you see instead? 

未运行shadow socks的情况下，墙内网站无法打开，或者时不时掉线。

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2040#issuecomment-429540937

**Comment by itsok228** [comment]
> [#2040 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2040#issuecomment-429540937)

谢谢，我试一下。

**Comment by itsok228** [comment]
还是不行，每次开机系统还是会自动开代理，导致墙内网站无法打开，必须运行shadowsock才能打开。
![QQ截图20191201155844](https://user-images.githubusercontent.com/58379383/69911251-ac132b80-1453-11ea-861e-4afc324efff3.png)

**Comment by chenshaoju** [comment]
确保在重启前退出了SS，并且没有启动开机自动启动SS。

确认以上无误后，退出SS，再执行一次 https://github.com/shadowsocks/shadowsocks-windows/issues/2040#issuecomment-429540937 的操作看看？

**Comment by itsok228** [comment]
> 确保在重启前退出了SS，并且没有启动开机自动启动SS。
> 
> 确认以上无误后，退出SS，再执行一次 [#2040 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2040#issuecomment-429540937) 的操作看看？

重启之前退出了SS，而且没有开机自启动。好像还是不行，算了。
还是谢谢！
