### ISSUE TITLE
shadowsocks server as a http proxy

### ISSUE THREAD

**Issue by willzhang** [shadowsocks/shadowsocks-windows#2709]
i use docker to pull google image in centos,:
```
cat  /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://192.168.0.102:1080"
```
192.168.0.102 is my windows10's ip addresss , and 1080 port is my shadowsocks client default proxy port.

my question is can i use my shadowsocks server as proxy directory? just replace http://192.168.0.102:1080 as my shadowsocks server' s ip and port?

**Comment by studentmain** [comment]
No, shadowsocks server itself can't serve HTTP.

**Comment by willzhang** [comment]
ok thanks ,but it is so strange, the client support ,the server not support.

**Comment by studentmain** [comment]
Thing is clear, SS client has a built-in HTTP/SOCKS5 server. SS server hasn't

**Comment by chenshaoju** [comment]
UNTESTED:
You may try https://github.com/rofl0r/proxychains-ng on your server by manual start ss-server.
