### ISSUE TITLE
Shadowsocks 已停止工作

### ISSUE THREAD

**Issue by asdfj2381k** [shadowsocks/shadowsocks-windows#2710]
[Window Title]
![image](https://user-images.githubusercontent.com/56584082/69948105-ff57ad80-1529-11ea-86d0-c099bb40c0e8.png)
![image](https://user-images.githubusercontent.com/56584082/69948660-fddab500-152a-11ea-9acb-a67a90aa9095.png)

Shadowsocks

[Main Instruction]
Shadowsocks 已停止工作

[Content]
Windows 可以联机检查该问题的解决方案。

[^] 隐藏问题详细信息  [联机检查解决方案并关闭该程序] [关闭程序]

--------------------
虚拟机里面新安装的msdn原版win7 32位，我就好奇为什么会打不开了。。

**Comment by chenshaoju** [comment]
请安装最新版本的 .Net Framework https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by asdfj2381k** [comment]
> 请安装最新版本的 .Net Framework https://dotnet.microsoft.com/download/dotnet-framework/net48

安装后，问题解决了；

但是，我觉得程序在此种情况下应该能给出正确的提示，而不是直接提示崩溃；

PS： 如果我不是知道怎么来github提问，就一直死循环了；

【希望得到的结果】更新程序，给出正确的提示；

**Comment by chenshaoju** [comment]
如果你的操作系统是Win10，则会提示要求安装 .NET （不过Win10自带，可能不会触发这个对话框）。
