### ISSUE TITLE
why a plethora of encryption algorithms  and implementations?

### ISSUE THREAD

**Issue by johnx7271** [shadowsocks/shadowsocks-windows#2714]
This is not a bug, but I'd like to raise this issue for a discussion.
1. why so many encryption algorithms?
if only for the purpose of encryption, one algorithm is more than enough, e.g. aes256. 
Or maybe some plugins need additional algorithms? even so, I believe it is best to limit the algorithms to those that are really needed, unless this multitude of algorithms has a real benefit of making the gfw programmer's life harder.

2. why many implementations for the same algorithm?
Also, why multiple implementations of some algorithms? I mean you have Sodium, MbedTLS, OPENSSL.  Shouldn't the different implementations for a algorithm under the same name be all the same? If so, then choosing one implementation and cutting out the rests would make the code easier and simpler than having many dupes.

Could someone explain? @wongsyrone pls?

3. btw, someone want to have aes256cgm on shadowsocksrr/shadowsocksr-csharp,   see https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/305

**Comment by wongsyrone** [comment]
I no longer maintain this project, please ask others.

**Comment by chenshaoju** [comment]
Shadowsocks and ShadowsocksRR is a different project.

About GFW, is not an algorithm issue, it is traffic analysis.

So, the key point is moving to obfuscate.

For now, there are few plugins that can pretend Shadowsocks as HTTP/WebSocket/TLS/UDP protocol.

For more info:
https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by johnx7271** [comment]
I know plugins can be good for tunneling through gfw.
but plugins are external program to ss, so ss need not to know the specifics of how those plugins work. In another words, the algorithm required by plugins need not be be known by ss.

**Comment by chenshaoju** [comment]
Shadowsocks protocol is control by the community, include plugins standard:
http://shadowsocks.org/en/spec/AEAD-Ciphers.html
http://shadowsocks.org/en/spec/Protocol.html
http://shadowsocks.org/en/spec/Plugin.html

Discussion:
https://github.com/shadowsocks/shadowsocks-org/issues

**Comment by studentmain** [comment]
Q1 is a historical question:

https://github.com/shadowsocks/shadowsocks-windows/blob/421554f8ecda46026aa0a083eee582cfbdbfb787/shadowsocks-csharp/Encrypt/OpensslEncryptor.cs#L12-L16

> but having multiple encryption algorithms?

Why putting all eggs in one basket? TLS1.3 has at least 5 algorithm. ss-windows only has 4 (other is not supported).

**Comment by wongsyrone** [comment]
> 1. you introduced openssl implementations into this project

Due to hardware acceleration.

**Comment by studentmain** [comment]
Q1 is question about standard, if you still have problem, you can ask in shadowsocks-org
And Q2 has an answer
So I'll close this issue now
