### ISSUE TITLE
Remove bf-cfb, chacha20, salsa20, rc4-md5

### ISSUE THREAD

**Issue by studentmain** [shadowsocks/shadowsocks-windows#2715]
According to spec:

> Implementors are advised to remove them as soon as possible.

移除 bf-cfb, chacha20, salsa20, rc4-md5

按照标准：实现应当尽快移除它们。

**Comment by chenshaoju** [comment]
这些协议仍然被服务端支持：
https://github.com/shadowsocks/shadowsocks-libev/blob/71cc0fb362c5c02cff585c210a292d033a8b3223/src/stream.c#L98

**Comment by studentmain** [comment]
也有某些服务端不再支持这些加密，更有甚者只支持AEAD

我认为现在把它们在下拉菜单中明确标记为弃用比较合适

**Comment by JerryCheng1** [comment]
什么标准？

**Comment by studentmain** [comment]
https://shadowsocks.org/en/spec/Stream-Ciphers.html

**Comment by celeron533** [comment]
可以保留这些项目但在后面加上[不推荐]字样
