### ISSUE TITLE
Add an option for hiding Shadowsocks error message

### ISSUE THREAD

**Issue by amirrammari** [shadowsocks/shadowsocks-windows#2716]
Please add an option for hiding Shadowsocks error message
![image](https://user-images.githubusercontent.com/23485114/70358875-99538900-188f-11ea-8446-db10116ba170.png)

**Comment by studentmain** [comment]
But why?

**Comment by amirrammari** [comment]
This error message shows on startup but I don't have any problem and Shadowsocks works fine.

**Comment by studentmain** [comment]
I think it's a possible bug

**Comment by chenshaoju** [comment]
This issue is still unknown.
https://github.com/shadowsocks/shadowsocks-windows/issues/2552

**Comment by studentmain** [comment]
Yes, program shouldn't work here, as it can't accept inbound connection

**Comment by database64128** [comment]
Are you on Windows Insider builds?

**Comment by amirrammari** [comment]
> Are you on Windows Insider builds?

No, I use the stable build of Windows 10.
![System Information](https://user-images.githubusercontent.com/23485114/71240179-b66f6980-231d-11ea-8e9c-9dea495370bd.png)

**Comment by database64128** [comment]
Can you run `netsh interface ipv4 show excludedportrange protocol=tcp` and attach the results?

**Comment by amirrammari** [comment]
> Can you run `netsh interface ipv4 show excludedportrange protocol=tcp` and attach the results?

![PowerShell](https://user-images.githubusercontent.com/23485114/71263788-df145500-2357-11ea-8883-d4c5ee300655.png)
