### ISSUE TITLE
无法下载啊，，，就这最后一步了，这么难的吗？求大佬给我个能下载的链接

### ISSUE THREAD

**Issue by Sunyunn** [shadowsocks/shadowsocks-windows#2717]

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by Sunyunn** [comment]
> https://github.com/shadowsocks/shadowsocks-windows/releases

现在在尝试下载，发现可以。谢谢您。
