### ISSUE TITLE
只使用shadowsocks可以正常使用，套了simple-obfs后无法使用

### ISSUE THREAD

**Issue by wuweijian1997** [shadowsocks/shadowsocks-windows#2723]
### Shadowsocks version / 影梭版本
最新版本

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
CentOS

### Steps you have tried / 操作步骤
服务端json
```
{
"local_address":"127.0.0.1",
"local_port":1080,
"port_password":{
"1997":"xxxxx"
},
"timeput":3000,
"method":"aes-256-cfb",
"fast_open":false,
"plugin":"obfs-server",
"plugin_opts":"obfs=http"
}

```

windows:
![image](https://user-images.githubusercontent.com/29529286/70689163-75a89c80-1cee-11ea-9c3a-d8f69f055c3b.png)

### What did you expect to see? / 期望的结果
正常使用

### What did you see instead? / 实际结果
无法翻墙

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
服务端json
```
{
"local_address":"127.0.0.1",
"local_port":1080,
"port_password":{
"1997":"xxxxx"
},
"timeput":3000,
"method":"aes-256-cfb",
"fast_open":false,
"plugin":"obfs-server",
"plugin_opts":"obfs=http"
}

### 日志
```
[2019-12-12 14:43:22] Started SIP003 plugin for 47.240.45.91:1997 on 127.0.0.1:57858 - PID: 19080
[2019-12-12 14:43:23] Shadowsocks started (4.1.8.0)
[2019-12-12 14:43:26] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2019-12-12 14:43:46] Started SIP003 plugin for 47.240.45.91:1997 on 127.0.0.1:57886 - PID: 20060
[2019-12-12 14:43:46] Shadowsocks started (4.1.8.0)
[2019-12-12 14:43:47] Started SIP003 plugin for 47.240.45.91:1997 on 127.0.0.1:57893 - PID: 14640
[2019-12-12 14:43:47] Shadowsocks started (4.1.8.0)

```

**Comment by chenshaoju** [comment]
请尝试将服务端的 127.0.0.1 修改为 0.0.0.0 或者 :: 后，重新启动服务看看。

另外，请确保密码无误。

**Comment by wuweijian1997** [comment]
> 请尝试将服务端的 127.0.0.1 修改为 0.0.0.0 或者 :: 后，重新启动服务看看。
> 
> 另外，请确保密码无误。
> 
> PS：
> 仔细看了一下，为什么你的服务器是 `local_address` 和 `local_port` ？
> 
> 不应该是 `server` 吗？
> 
> 这是我的配置，给你参考：
> {
> "server":"::",
> "mode":"tcp_only",
> "server_port":80,
> "local_port":10800,
> "password":"xxxxxxxxxxxxxxxxxxxx",
> "timeout":300,
> "method":"aes-256-gcm",
> "plugin":"obfs-server",
> "plugin_opts":"obfs=http;failover=www.baidu.com:80"
> }

你是shadowsocks 还是 shadowsocks shadowsocks-libev?
我的是shadowsocks python版的，和这个应该没关系吧？
我把本地插件配置删了就又可以连Google了，现在都不知道是哪里的问题了，我试一下你这个

**Comment by chenshaoju** [comment]
Python版的Shadowsocks不支持插件，请使用libev版或ss-rust版，详见：
https://shadowsocks.org/en/spec/Implementations.html

**Comment by wuweijian1997** [comment]
> Python版的Shadowsocks不支持插件，请使用libev版或ss-rust版，详见：
> https://shadowsocks.org/en/spec/Implementations.html

thx,我试试 libev，大佬辛苦了

**Comment by Luow7** [comment]
各位大佬有没有ios的下载包呢?

**Comment by wuweijian1997** [comment]
> 各位大佬有没有ios的下载包呢?

https://github.com/shadowsocks/shadowsocks-iOS 
这个？

**Comment by chenshaoju** [comment]
iOS只有第三方的客户端，官方的已经死了很久了。

为了避免广告嫌疑，此处无法推荐，请理解。

**Comment by Luow7** [comment]
这个里面没有内容呢

**Comment by Luow7** [comment]
方便私发吗?大佬

**Comment by wuweijian1997** [comment]
> 这个里面没有内容呢

没有用过iOS，不是很清楚，只用过mac的ss客户端

**Comment by Luow7** [comment]
感谢大佬
