### ISSUE TITLE
ubuntu18.04下ss可以正常连接，但浏览器和terminal无法翻墙

### ISSUE THREAD

**Issue by gongyue666** [shadowsocks/shadowsocks-windows#2724]
### Shadowsocks version / 影梭版本
shadowsocks-qt5在ubuntu18.04下，可以如图正常连接server，但是浏览器与terminal均无法正常翻墙。
### Steps you have tried / 操作步骤
![1](https://user-images.githubusercontent.com/15926228/70707894-3a20c900-1d14-11ea-85a4-fc100e805ff7.jpg)
shadowsocks配置如下：
![2](https://user-images.githubusercontent.com/15926228/70708460-86203d80-1d15-11ea-9ec5-407d831f5fa0.jpg)
系统代理设置如下：
![3](https://user-images.githubusercontent.com/15926228/70707975-6d635800-1d14-11ea-8522-e077bf13e8bd.jpg)
Chrome switchOmega设置如下：
![4](https://user-images.githubusercontent.com/15926228/70708411-612bca80-1d15-11ea-9a47-af1e116074f8.jpg)
在.bashrc中已经添加如下几句：
export http_proxy=http://127.0.0.1:1234
export https_proxy=http://127.0.0.1:1234
export SOCKS_SERVER=127.0.0.1"1234

试过选择http(s)，同时修改想要配置，浏览器和terminal也同样无法正常翻墙

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/70709577-17bb8b00-1cd5-11ea-8e99-e68b1eb95208.png)

**Comment by studentmain** [comment]
鉴于ss-qt5停止维护了，建议转到outline-client（有图形界面，第三方项目）或者ss-libev
