### ISSUE TITLE
shadowsocks-libev运行报错

### ISSUE THREAD

**Issue by wuweijian1997** [shadowsocks/shadowsocks-windows#2725]
### Shadowsocks version / 影梭版本
最新

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Ubuntu 18.4

### Steps you have tried / 操作步骤
安装
```
$ sudo apt install shadowsocks-libev
```
配置文件
```
sudo vim /etc/shadowsocks-libev/config.json
```
config.json
```
{
    "server":"127.0.0.1",    # 改为VPS的外网IP
    "server_port":8388,        # 客户端连接这个端口
    "local_port":1080,
    "password":"xxxxxx",    # 密码不要轻易告诉别人
    "timeout":60,            # 默认60既可
    "method":"aes-256-cfb"    # 推荐加密使用
}
```
启动服务
```
 /etc/init.d/shadowsocks-libev start
```
### What did you expect to see? / 期望的结果
正常使用

### What did you see instead? / 实际结果
Http proxy 500
使用  /etc/init.d/shadowsocks-libev status 查看的时候刚开始是启动成功了，过不久他就error了

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
{
    "server":"127.0.0.1",    # 改为VPS的外网IP
    "server_port":8388,        # 客户端连接这个端口
    "local_port":1080,
    "password":"xxxxxx",    # 密码不要轻易告诉别人
    "timeout":60,            # 默认60既可
    "method":"aes-256-cfb"    # 推荐加密使用
}
```

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/70709577-17bb8b00-1cd5-11ea-8e99-e68b1eb95208.png)

**Comment by studentmain** [comment]
ss-libev在隔壁

**Comment by wuweijian1997** [comment]
> ss-libev在隔壁

不都是一家人么。。

**Comment by chenshaoju** [comment]
的确是同一个项目，但是是不同的人负责的。

你可以理解成百盛餐饮集团，旗下有肯德基和必胜客，但是肯德基和必胜客没有直接关联。

我建议你在作者的博客下面留言询问，或者阅读libev项目中的说明文件以重新部署：
https://github.com/shadowsocks/shadowsocks-libev/blob/master/README.md
