### ISSUE TITLE
求大佬提供一个iphone的Shadowsocks 使用

### ISSUE THREAD

**Issue by Luow7** [shadowsocks/shadowsocks-windows#2727]

**Comment by chenshaoju** [comment]
你好，这里是 shadowsocks-issue 的 issue 板块，用于反馈 Windows 版本的 Shadowsocks 问题的。

目前没有官方版的 Shadowsocks for iOS 客户端，只有第三方的。

为了避免广告嫌疑，请自行搜索：
https://lmgtfy.com/?q=iOS+Shadowsocks+%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by studentmain** [comment]
自己找个港区账号上Appstore搜

**Comment by Luow7** [comment]
> 你好，这里是 shadowsocks-issue 的 issue 板块，用于反馈 Windows 版本的 Shadowsocks 问题的。
> 
> 目前没有官方版的 Shadowsocks for iOS 客户端，只有第三方的。
> 
> 为了避免广告嫌疑，请自行搜索：
> https://lmgtfy.com/?q=iOS+Shadowsocks+%E5%AE%A2%E6%88%B7%E7%AB%AF

大佬.你这个链接打开看不到图片,求指点

**Comment by Luow7** [comment]
> 自己找个港区账号上Appstore搜

好的,我试试
