### ISSUE TITLE
Win32Exception when adding plugin on shadowsocks

### ISSUE THREAD

**Issue by mathieu001** [shadowsocks/shadowsocks-windows#2729]
### Shadowsocks version / 影梭版本
4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 7 Professional(32-bit), .Net Framework 4.7.2

### Steps you have tried / 操作步骤
I am tring to add obfs plugin on shadowsocks and always get a Win32Exception

### What did you expect to see? / 期望的结果
The obfs plugin can be added successfully on my Windows 7 Professional(32-bit)

### What did you see instead? / 实际结果
The obfs plugin can be added on Windows 7 Professional(64-bit), however, it can't be added on Windows 7 Professional(32-bit)

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.

**Comment by chenshaoju** [comment]
If your OS is 32-bit, Please using 32-bit plugin.
