### ISSUE TITLE
2.5.2 任务管理器占内存60MB ，虚拟内存接近1GB，能否做下内存回收，让内存占少一些。

### ISSUE THREAD

**Issue by uinux** [shadowsocks/shadowsocks-windows#273]
![default](https://cloud.githubusercontent.com/assets/13487419/9289983/c4a151a6-43b3-11e5-8c07-8fac1470c8a4.PNG)
![Uploading 捕获.PNG…]()
2.5.2 任务管理器占内存60MB ，虚拟内存接近1GB，能否做下内存回收，让内存占少一些。不然，一直涨下去内存都被用光了。

**Comment by chenshaoju** [comment]
理论上 .NET 4.0 版本的Shadowsocks不会出现该问题。

看起来你会用ProcXP，应该是高级用户。

用 VMMap 看一下内存占用情况，是什么线程消耗了这么多内存：
https://technet.microsoft.com/en-us/Library/dd535533.aspx

请记得按照私有内存消耗排序。

![screenshot](https://cloud.githubusercontent.com/assets/515763/9290183/86b55bb4-43bb-11e5-9ab1-9485f32f6564.png)

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/9290219/dc614d4c-43bc-11e5-8ea7-c1cc7e5ad6af.PNG)
这个是之前看到你们在讨论，下载的软件....但我这内存占的也太多了。

**Comment by uinux** [comment]
![default](https://cloud.githubusercontent.com/assets/13487419/9290224/16088984-43bd-11e5-8dcc-842cb0856231.PNG)

**Comment by uinux** [comment]
等这个问题解决了，我把这软件关了，换.net4.0，这个内存消耗好多呢。

**Comment by chenshaoju** [comment]
和之前遇到的问题一样，也是GC占用了大多数内存。

初步猜测和.NET 4.0 Framework 有关，建议下载：
http://www.microsoft.com/en-us/download/details.aspx?id=30135

修复，然后可能需要（或该修复程序）重装.NET 4.0 Framework。

**Comment by uinux** [comment]
嗯，换.net 4.0了，运行一段时间看下吧。

**Comment by clowwindy** [comment]
目前还有观察到这个问题么？
