### ISSUE TITLE
The program does not start

### ISSUE THREAD

**Issue by chentianci123** [shadowsocks/shadowsocks-windows#2734]
I tried to open 4.1.8, 4.1.7 and 4.1.5, and they all failed to open.
![1576546271(1)](https://user-images.githubusercontent.com/49859313/70957199-4f994880-20b0-11ea-8488-0a2a041677f8.png)

**Comment by chentianci123** [comment]
应用程序时间戳:	5d2b1b0b
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.24408
  故障模块时间戳:	5c92f101
  异常代码:	e0434352
  异常偏移:	0000c5af
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	1077

**Comment by chenshaoju** [comment]
Please install newest .Net Framework.
https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by chentianci123** [comment]
应用程序时间戳:	5d2b1b0b
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.24408
  故障模块时间戳:	5c92f101
  异常代码:	e0434352
  异常偏移:	0000c5af
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	1077

> Please install newest .Net Framework.
> https://dotnet.microsoft.com/download/dotnet-framework/net48

ok thanks
