### ISSUE TITLE
Q: Win10. Will "netsh winhttp" proxy setting makes torrenting traffic goes through SS?

### ISSUE THREAD

**Issue by bokemanoh** [shadowsocks/shadowsocks-windows#2735]
Win10. 
Will "netsh winhttp" proxy setting makes torrenting(utorrent, bittorrent alike) traffic goes through SS?
Does "netsh winhttp" proxy setting makes all windows programs's internet traffics go through SS?
If so, is there anyways to let torrenting programs bypass it?

**Comment by chenshaoju** [comment]
This depends on your BitTorrent client.

If your BitTorrent client there is an option like "Use proxy settings from the system", may through your local Shadowsocks when using Global Mode.

But most BitTorrent client don't have this function,Like tixati:
![image](https://user-images.githubusercontent.com/515763/71092186-bcf8c680-21e1-11ea-80f0-c00d5fb43392.png)
