### ISSUE TITLE
关于节点报错的问题

### ISSUE THREAD

**Issue by china736707221** [shadowsocks/shadowsocks-windows#2736]
dlercloud的节点扫描二维码加入后会报错，然而手动安装了simple-obfs依然会报错，个人水平较低所以来发帖询问了，图中报错弹窗是安装了simple-obfs插件后的弹窗
![1576689661(1)](https://user-images.githubusercontent.com/33253708/71108874-f7249100-21fe-11ea-93e4-16510aace263.png)

![1576689953(1)](https://user-images.githubusercontent.com/33253708/71108863-effd8300-21fe-11ea-961c-1d85b56bb601.png)

**Comment by studentmain** [comment]
自行咨询运营商

**Comment by chenshaoju** [comment]
你的服务商的二维码包含了一个插件，请使用你的服务商提供的SS客户端，或者仔细阅读你的服务商提供的帮助文件以获取插件。
