### ISSUE TITLE
[feature request] 允许用户指定privoxy端口

### ISSUE THREAD

**Issue by hjk41** [shadowsocks/shadowsocks-windows#2737]
目前privoxy端口是随机找一个可用端口，所以每次重启shadowsocks都可能会变。但是一些软件需要HTTP代理（比如teamviewer），而我又不想开一直开全局代理。

希望能允许用户指定privoxy端口。端口可以默认为0，这样行为跟以前一致，只有当用户手动指定了端口时才用指定端口

**Comment by chenshaoju** [comment]
你好，位于Shadowsocks for Windows的编辑服务器界面右下角的代理端口是双协议，同时支持HTTP和SOCKS5代理。

你只需要直接设置为你的代理端口即可。

更多信息请阅读：https://github.com/shadowsocks/shadowsocks-windows/issues/2443

**Comment by hjk41** [comment]
赞！
这个端口设置的确需要加点说明
