### ISSUE TITLE
4.1.9.0 保护PAC 设置似乎出现了混乱

### ISSUE THREAD

**Issue by giftzn** [shadowsocks/shadowsocks-windows#2739]
### Shadowsocks version / 影梭版本
4.1.9.0 (Pre-release)

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1909 (18363.535)
NET Framework v4.0.30319

### Steps you have tried / 操作步骤
关闭保护PAC选项，启动客户端，PAC模式无法正常工作
访问 http://127.0.0.1:1080/pac 提示：ERR_EMPTY_RESPONSE
打开保护PAC选项可恢复正常，但不带 secret 也可获得PAC（保护无效）

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
无异常日志

**Comment by studentmain** [comment]
[Shadowsocks-4.1.8.0-debug-unofficial.zip](https://github.com/shadowsocks/shadowsocks-windows/files/3992030/Shadowsocks-4.1.8.0-debug-unofficial.zip)

试试这个

**Comment by giftzn** [comment]
> [Shadowsocks-4.1.8.0-debug-unofficial.zip](https://github.com/shadowsocks/shadowsocks-windows/files/3992030/Shadowsocks-4.1.8.0-debug-unofficial.zip)
> 
> 试试这个

**It Works!**

**Comment by studentmain** [comment]
好的，等4.1.9.1

**Comment by studentmain** [comment]
https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/29702284/job/km0q4ce29q17skth/artifacts

**Comment by celeron533** [comment]
4.1.9.1 released
