### ISSUE TITLE
WinForms .Net Core 3

### ISSUE THREAD

**Issue by Lorymi** [shadowsocks/shadowsocks-windows#2742]
Please update project to .net core 3

**Comment by studentmain** [comment]
We haven't enough developer to do this

**Comment by Stzx** [comment]
After .NET 5 is released next year, I might migrate it. :)


Merry Christmas !

**Comment by studentmain** [comment]
Shadowsocks-Qt5 is no longer maintained. So there's no GUI client for Linux users now. After update to .NET Core, maybe we can do something for them.

**Comment by studentmain** [comment]
#2756
