### ISSUE TITLE
建议增加订阅功能

### ISSUE THREAD

**Issue by realhuyang** [shadowsocks/shadowsocks-windows#2744]
建议：希望可以添加订阅功能，方便我直接一键更新服务器。
不然每次都手动一个一个添加服务器，太麻烦了。
谢谢

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2676

**Comment by faydanube** [comment]
1. 直接使用 SSR 订阅进行更新
2. 然后复制 SSR 的 `gui-config.json` 覆盖到 SS
3. 在 SS 直接支持订阅功能之前，使用此方法可以完美解决。
