### ISSUE TITLE
ss 什么时候能像ssr那样提供国内外分流的功能呢？pac文件需要非常非常频繁的手动编写更新，很不友好

### ISSUE THREAD

**Issue by darrenliuwei** [shadowsocks/shadowsocks-windows#2745]

**Comment by studentmain** [comment]
SSR向下兼容SS，因此可以用SSR

**Comment by darrenliuwei** [comment]
所以ss还不准备做国内外分流功能吗？

只能用全局了？

**Comment by chenshaoju** [comment]
讨论中，请移动到：https://github.com/shadowsocks/shadowsocks-windows/issues/2746

**Comment by studentmain** [comment]
用全局。

国内外分流不是“程序员说要有国内外分流，便有了国内外分流”这么简单……首先要有足够的程序员，这是所有开源软件包括本项目不得不面临的事实。

**Comment by darrenliuwei** [comment]
> 用全局。
> 
> 国内外分流不是“程序员说要有国内外分流，便有了国内外分流”这么简单……首先要有足够的程序员，这是所有开源软件包括本项目不得不面临的事实。

那 ssr 的国内外分流功能可以移植到 ss 上吗？

**Comment by studentmain** [comment]
同样的原因，移植不是“程序员说要移植，便有了移植”这么简单……首先要有足够的程序员，这是所有开源软件包括本项目不得不面临的事实。换句话说，没人，不空。

**Comment by darrenliuwei** [comment]
好吧

**Comment by studentmain** [comment]
说点私货，成百上千万人在使用本软件，甚至可能还有成百上千的人在贩卖本软件，我国的IT巨头们无一例外大规模使用着本软件（例外的都追不上最新技术被淘汰了），当然本软件的协议允许这样做。

而软件呢？别看它用户可能上千万，有着46万star，是很多用户上Github打开的第一个项目，比某些商业软件还风光。其实闲暇时间有空过来看一眼，解决一下问题的人估计一只手都数得出来……

开源软件开发本来意味着谁行谁上，人人为我我为人人。现实不这样，巨头们都去发大财赚大钱了，哪管他们每天用着的软件的死活。普天之下莫非用户的OpenSSL的日常维护情况和Heartbleed漏洞就是这个现实的体现。或许“穷者兼济天下，达者独善其身”才是潮流？

**Comment by 1phalley** [comment]
> 说点私货，成百上千万人在使用本软件，甚至可能还有成百上千的人在贩卖本软件，我国的IT巨头们无一例外大规模使用着本软件（例外的都追不上最新技术被淘汰了），当然本软件的协议允许这样做。
> 
> 而软件呢？别看它用户可能上千万，有着46万star，是很多用户上Github打开的第一个项目，比某些商业软件还风光。其实闲暇时间有空过来看一眼，解决一下问题的人估计一只手都数得出来……
> 
> 开源软件开发本来意味着谁行谁上，人人为我我为人人。现实不这样，巨头们都去发大财赚大钱了，哪管他们每天用着的软件的死活。普天之下莫非用户的OpenSSL的日常维护情况和Heartbleed漏洞就是这个现实的体现。或许“穷者兼济天下，达者独善其身”才是潮流？

打扰一下，是4万6千个star

**Comment by studentmain** [comment]
> 打扰一下，是4万6千个star

Fixed

**Comment by iBug** [comment]
给我的网站打一波小广告，国内外分流这个功能我自己编写了一个 PAC 脚本，可以访问 <https://ibugone.com/project/pac-generator> 从两个既定的数据源生成。原理就是把所有已知的天朝大陆的 IP 加入白名单，然后不在白名单里的 IP 地址才走 SS。已知缺点是不支持 IPv6。
