### ISSUE TITLE
1.支持txt或其他方式的批量导入。2.扫描屏幕二维码、从URL导入支持快捷键。

### ISSUE THREAD

**Issue by chwxn** [shadowsocks/shadowsocks-windows#2747]
### 1.支持txt或其他方式的批量导入。2.扫描屏幕二维码、从URL导入支持快捷键。

**Comment by studentmain** [comment]
My opinion:

About import from txt or other format: which format? List of URL? gui-config.json? Also see #1703 

About hotkey: Why do you need scan QR code so often, it doesn't make sense.

**Comment by studentmain** [comment]
#1727
