### ISSUE TITLE
unauthorizedaccessexception

### ISSUE THREAD

**Issue by killbill920** [shadowsocks/shadowsocks-windows#2748]
### Shadowsocks version / 影梭版本
4.1.8

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
WIN10 .NET 4.7.2

### Steps you have tried / 操作步骤
可以正常使用，但是切换服务器或打开日志等会被关闭，ss已经放在根目录的文件夹下

### What did you expect to see? / 期望的结果
正常切换服务器

### What did you see instead? / 实际结果
无法切换服务器

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
Shadowsocks Ul ErrorX
©
非预期错误，Shadowsocks将退出。请提交此错误到
https://github.com/shadowsocks/shadowsocks-windows/issues 
Exception Detail:
System.UnauthorizedAccessException:对路径"E:\ss\gui-config.json 
"的访问被拒绝。
在 System.lO._Error.WinlOError(lnt32 errorCode, String 
maybeFullPath)
在 System.lO.FileStream.lnit(String path, FileMode mode, 
FileAccess access, Int32 rights, Boolean useRights, FileShare share, 
Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES 
secAttrs, String msgPath, Boolean bFromProxy, Boolean 
useLongPath, Boolean checkHost)
在 System.lO.FileStream..ctor(String path, FileMode mode, 
FileAccess access, FileShare share)
Shadowsocks.Model.Configuration.Save(Configuration config) 
Shadowsocks.View.ConfigForm.SaveValidConfiguration〇 
在 Shadowsocks.View.ConfigForm.OKButton_Click(Object 
sender, EventArgs e)
在 System.Windows.Forms.Control.OnClick(EventArgs e)
在 System.Windows.Forms.Button.OnClick(EventArgs e)
在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs 
mevent)
在 System.Windows.Forms.Control.WmMouseUp(Message8i m, 
MouseButtons button, Int32 clicks)
在 System.Windows.Forms.Control.WndProc(Message8i m)
在 System.Windows.Forms.ButtonBase.WndProc(Message8t m)
在 System.Windows.Forms.Button.WndProc(Message8t m)
在
System.Windows.Forms.Control.ControlNativeWindow.OnMessage 
(Messaged m)
在
System.Windows.Forms.Control.ControlNativeWindow.WndProc(M 
essage8t m)
在 System.Windows.Forms.Nat丨veWindow.Callback(lntPtr hWnd, 
Int32 msg, IntPtr wparam, IntPtr Iparam)

**Comment by chenshaoju** [comment]
1.请确保文件没有被设置为只读：
![image](https://user-images.githubusercontent.com/515763/71571879-7aa38380-2b17-11ea-8e0f-389adc4e2647.png)

2.请确保你的文件权限正确，你所在的用户名/用户组位于安全选项卡中，并且具有写入权限。
![image](https://user-images.githubusercontent.com/515763/71571897-99a21580-2b17-11ea-92b0-f9067626d4b8.png)

3.某些安全软件的文件保护功能可能会拒绝 Shadowsocks.exe 的写入，请将其加入例外列表。

**Comment by killbill920** [comment]
将gui-config.json的只读取消后，没有出现问题了，谢谢
