### ISSUE TITLE
关于高可用

### ISSUE THREAD

**Issue by realhuyang** [shadowsocks/shadowsocks-windows#2749]
### Shadowsocks version / 影梭版本
4.1.9.1

查阅了关于服务器中高可用的说明：根据延迟和丢包率自动选择服务器。

但是实际使用情况下，很多时候并不能自动选择最优服务器。
访问速度很慢。
或者第一次干脆打不开网页，需要等一会，再次刷新网页才能正常浏览。

感觉有点问题，望改进此功能。

**Comment by studentmain** [comment]
#499

**Comment by bbq69** [comment]
i am very new to this ss and a noob who doesnt have any idea about computers much. please can anyone guide me how can i use this shadow socks here in china.

**Comment by realhuyang** [comment]
> 我对这个SS非常陌生，一个对计算机没有太多了解的菜鸟。请任何人指导我如何在中国这里使用这种阴影袜。

shadowsocks is just a software, you need to purchase another ss account to use.

**Comment by bbq69** [comment]
> 
> 
> > 我对这个SS非常陌生，一个对计算机没有太多了解的菜鸟。请任何人指导我如何在中国这里使用这种阴影袜。
> 
> shadowsocks is just a software, you need to purchase another ss account to use.

i bought ss server but it stops working after every few mins. what should i do to resolve thsi?
my provider told to add a plugin called obfs i did it but still its same issue
