### ISSUE TITLE
Win7 64bit System Can't Connect ,Can't  Use  Proxy , Help Me , Thanks !

### ISSUE THREAD

**Issue by LockGit** [shadowsocks/shadowsocks-windows#275]
why win7 64bit system only frist connect google succes , if close browser , then open browser connect fail . but in unbuntu14.04 system ,use shadownsockts connect google success  always ! why ? address:shanghai  china . network :GreatWall Broadband . help me !!! Thanks

**Comment by LockGit** [comment]
tray again , possible network question 。

**Comment by LockGit** [comment]
try again , possible network question 。

**Comment by chenshaoju** [comment]
Can you give us log?
You can right click shadowsocks task icon,and click "Show logs."

Here is Chinese Interface screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/515763/9292882/daaa745c-4442-11e5-8a37-d00335f4dd47.png)

**Comment by LockGit** [comment]
Log Viewer display : 
[2015-08-16 20:13:34] 106.187.93.10:1443 timed out
[2015-08-16 20:13:37] 106.187.93.10:1443 timed out
[2015-08-16 20:13:37] 106.187.93.10:1443 timed out
[2015-08-16 20:13:37] 106.187.93.10:1443 timed out

Some times display:
[2015-08-16 20:17:35] 106.187.93.10:1443 timed out
[2015-08-16 20:17:36] 106.187.93.10:1443 timed out
[2015-08-16 20:17:36] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()
[2015-08-16 20:17:38] 106.187.93.10:1443 timed out
[2015-08-16 20:17:38] 106.187.93.10:1443 timed out

Browser  dispaly :
502 Read from server failed: Unknown error

But some times connect normal ,why ?

@chenshaoju

**Comment by celeron533** [comment]
What web browser you using? And ISP? And have you installed 360安全卫士 or similar software?

**Comment by LockGit** [comment]
360 browser ,but use webkit kernel  mode ,webkit Kernel , same as Chrome kernel 。 In My system, Installed 360 safe , safe software possible shadownsockts ? ISP is 上海市 长城宽带
@celeron533  Thanks!

**Comment by celeron533** [comment]
@LockGit , please refer to: https://www.v2ex.com/t/173545
I never install 360 and/or related 'safety guard', broswer, service on my system

**Comment by chenshaoju** [comment]
I Check your server,The IP is work,And port is work too.
Maybe is your Browser Proxy setting is not correct?
Please check your Browser Proxy is your Shadowsocks port,And use SOCKS5 protocol.

![1](https://cloud.githubusercontent.com/assets/515763/9293589/89737c02-4463-11e5-96cb-e6c3ae92dd98.png)

**Comment by LockGit** [comment]
My Browser Proxy use SwitchyOmega .Thanks , @chenshaoju @celeron533

**Comment by chenshaoju** [comment]
Please make sure your settings is use SOCKS5 and IP address is correct:
![screenshot](https://cloud.githubusercontent.com/assets/515763/9294647/24a6a3a8-4486-11e5-946d-db7197f298a8.png)
PS: The port 10800 is my port setting,Check your Shadowsocks Port and make sure your proxy settings is same port.

**Comment by chenshaoju** [comment]
Can you ping your server,And packet loss percent is?
Look's like your using server have a bad link (network) quality.

**Comment by gy199445** [comment]
Hi, @LockGit , I encountered the same issue with yours. Is your problem solved yet?

**Comment by LockGit** [comment]
@gy199445 ,now ,shadowsockts can't use  .

**Comment by gy199445** [comment]
I have 3 servers running shadowsocks-python. I checked their /var/log/shadowsocks.log, everything  goes fine, maybe. The glitch may well lie in the local client.
@LockGit You may want to try the following cmd client. I download it from a commercial proxy provider from whom I bought service long time ago. I've used it for a few hours, no problem so far.

> http://pan.baidu.com/s/1mgIHv9A（提取密码：91i6，解压密码：boafanx）

**Comment by LockGit** [comment]
@gy199445  Thanks

**Comment by didila** [comment]
这是被干扰了，这两个月都是这样的

**Comment by RiceZhang** [comment]
please close the safe software such as 360 etc.,  at the end , please opne your proxy, and then will be success.
