### ISSUE TITLE
Translation help wanted

### ISSUE THREAD

**Issue by studentmain** [shadowsocks/shadowsocks-windows#2750]
Recently we improved localization support. It is known that our users are from all over the world, so we need more language for them to have a better experience. But our ability is limited, therefore we could use some help with translation, including the following language:

- Persian (فارسی)
- Hindi (हिन्दी)
- Urdu (اُردُو)
- Spainish (Español)
- Arabic (العربية)
- Germany (Deutsch)
- Portuguese (Português)
- Polish (polski)
- Italian (Italiano)
- Esperanto
- etc.

You can edit [source code](https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Data/i18n.csv) and send a Pull Request.
Or you can just follow [the instruction](https://github.com/shadowsocks/shadowsocks-windows/wiki/How-to-translate) then send edited CSV to us.

Your effort will be appreciated by the people.

----------------

We already have following language translation, thanks:

- French (français) by @nerekihs (#2861)
- Korean (한국어) by @Seia-Soto (#2835), @RekonChan (#2871)
- Russian (русский) by @rockenren (#2767)
- Japanese (日本語) by @JonasGao (#1059), @Ninedyz (#1138), @kingofotaku (#2920)

**Comment by iMasoud** [comment]
Hey, I'll be glad to help with Persian translation.

**Comment by studentmain** [comment]
> Hey, I'll be glad to help with Persian translation. 

Just go ahead, if you have any problem, let us know.

**Comment by iMasoud** [comment]
> > Hey, I'll be glad to help with Persian translation.
> 
> Just go ahead, if you have any problem, let us know.

Where do I start? 🤔

**Comment by rockenren** [comment]
> 
> 
> > > Hey, I'll be glad to help with Persian translation.
> > 
> > 
> > Just go ahead, if you have any problem, let us know.
> 
> Where do I start? 🤔

Here: https://github.com/shadowsocks/shadowsocks-windows/wiki/How-to-translate
I've used LibreOffice Calc for CSV editing.
