### ISSUE TITLE
PAC do not work in 4.1.9.2

### ISSUE THREAD

**Issue by cpyb** [shadowsocks/shadowsocks-windows#2752]
PAC do not work in 4.1.9.2, I have to use Global mode

it works in old 4.1.8.0 version

thank you.

**Comment by chenshaoju** [comment]
Please try to delete or rename `pac.txt` in the `Shadowsocks.exe` folder.

After deleting `pac.txt`, Right-click Shadowsocks icon in the Taskbar tray, Select `PAC`, And click `Update Local PAC from GFWList`.

**Comment by studentmain** [comment]
try delete pac.txt and restart program

**Comment by chyanog** [comment]
Run Shadowsocks.exe as administrator for the first time.

**Comment by HerbinZYH** [comment]
> Please try to delete or rename `pac.txt` in the `Shadowsocks.exe` folder.
> 
> After deleting `pac.txt`, Right-click Shadowsocks icon in the Taskbar tray, Select `PAC`, And click `Update Local PAC from GFWList`.

it is work！thanks

**Comment by chenshaoju** [comment]
🥂

**Comment by cpyb** [comment]
Thank you all. It works now.

**Comment by caesun** [comment]
4.1.9.2 does not work while 4.1.7.1 works fine.

I tried setting 4.1.9.2 as global mode, del local pac.txt and updating from GFWList, but it failed with errors as below:

[2020-03-23 16:51:43] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2020-03-23 16:51:43] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2020-03-23 16:51:43] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2020-03-23 16:51:43] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2020-03-23 16:51:54] Cannot get Windows 10 system theme mode, return default value 0 (dark mode).

**Comment by chenshaoju** [comment]
Your SS server may not work, maybe due by the wrong config or blocked server.
