### ISSUE TITLE
4.1.9.2版本被杀毒软件报病毒

### ISSUE THREAD

**Issue by lhn1989** [shadowsocks/shadowsocks-windows#2754]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10

### Steps you have tried / 操作步骤
下载最新4.1.9.2版本，运行会被McAfee当作病毒处理，而4.1.8.0版本正常

### What did you expect to see? / 期望的结果
像4.1.8.0版本一样正常运行

### What did you see instead? / 实际结果
被McAfee当作病毒删除

**Comment by chenshaoju** [comment]
请检查你的 Shdowsocks.exe （4.1.9.2）是否符合以下散列结果：
```
MD5
A564B74220352817C80DC097342F5338
SHA-1
BBB9F9251C16B311C6C1B4A18F493EC48B6849F2
SHA-256
4C9D8A8375BC5B86E8018E6779374BF6B22B5636EFAD40060FC9D36F00475767
SHA-512
09D84508C6DC1037CCCAE626E6F44DC0F8FA4CB011E625F38DB04FF610F6FA08C378858462376AB0FC6EE4A52E51BF2B888E9FFD6B4DAD13EABD4261BE88E14F
```

如果是，该文件截至目前未被全球绝大多数杀毒软件报告为病毒：
https://www.virustotal.com/gui/file/4c9d8a8375bc5b86e8018e6779374bf6b22b5636efad40060fc9d36f00475767/detection

请尝试更新你的杀毒软件病毒库看看是否解决了该问题。

**Comment by DuckDuckWhale** [comment]
Also affected by this. Only occurs when trying to run the executable. Windows says that it can't find the file and it shows up in the quarantined items.

**Comment by SinGirl** [comment]
更新到4.1.9.2后就不能用了，不报错，就是不能打开网站。更新之前没有问题。手机的正常使用，配置没问题

**Comment by studentmain** [comment]
@SinGirl 试试删除pac.txt重开

**Comment by SinGirl** [comment]
> @SinGirl 试试删除pac.txt重开

回到4.1.8.0立马就能用了

**Comment by EricCaoHZ** [comment]
我也是一样，4.1.9.2被McAfee杀掉了，4.1.8.0正常

**Comment by celeron533** [comment]
4.1.9释放PAC文件的行为发生了改变，被杀毒软件误判
