### ISSUE TITLE
Collect UI/UX improvement proposals for the next major release

### ISSUE THREAD

**Issue by Stzx** [shadowsocks/shadowsocks-windows#2755]
_Used to gather ideas for UI/UX improvements in the next major release._

**Comment by studentmain** [comment]
(We can include UX improvement too)

**Comment by c1316580081** [comment]
![批注 2020-01-26 143558](https://user-images.githubusercontent.com/56654011/73131608-3ee1d800-4049-11ea-96cc-ba70866bf70c.png)

如果这个功能使用之前的自定义功能的话，那样我们可以通过二维码分享其他`ss`链接,然后就不会局限于本系统的SS链接！
