### ISSUE TITLE
Add abillity to notice breaking change

### ISSUE THREAD

**Issue by studentmain** [shadowsocks/shadowsocks-windows#2758]
Prepare for v5, so we can inform user how to migrate to new version at that time.

Possible way to detect breaking change:
- Add &lt;!--__BREAKING_CHANGE__--&gt; in release note
- Add a INSTRUCTION.txt to download

Possible way to inform user:
- Navigate to release page
- Show INSTRUCTION.txt

**Comment by database64128** [comment]
Closed in #2991
