### ISSUE TITLE
4.1.9.2版本win7启动报错（此实现不是Windows平台FIPS验证的加密算法的一部分）

### ISSUE THREAD

**Issue by Leynakindle** [shadowsocks/shadowsocks-windows#2759]
### Shadowsocks version / 影梭版本
4.1.9.2

### Operating system / 操作系统
Windows7 64bit

### What did you see instead? / 实际结果
管理员权限启动报错，如图

![截屏2020-01-0809 42 15](https://user-images.githubusercontent.com/3469381/71943426-997ed580-31fb-11ea-83b2-bd358e20f828.png)

**Comment by chenshaoju** [comment]
你好，你的 .Net Framework 好像损坏了，请尝试下载最新版的安装包重新安装一下看看：
https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by studentmain** [comment]
> 你好，你的 .Net Framework 好像损坏了，请尝试下载最新版的安装包重新安装一下看看：
> https://dotnet.microsoft.com/download/dotnet-framework/net48

翻了一下文档，系统MD5实现的确和FIPS不兼容，下个版本换SHA1或者用其他MD5实现

**Comment by studentmain** [comment]
https://www.soft2005.com/Web/NewsInfo-183.html

**Comment by chenshaoju** [comment]
我看了一下我的注册表，这个`Enabled`键值的确是0，可能我什么时候改过注册表……

**Comment by studentmain** [comment]
> 我看了一下我的注册表，这个`Enabled`键值的确是0，可能我什么时候改过注册表……

也可能是他什么时候改过，毕竟目前只有这一则报告

**Comment by studentmain** [comment]
https://ci.appveyor.com/api/buildjobs/x75x8pr27opolsm6/artifacts/Shadowsocks-4.1.9.0-67-master.zip 试试这个

**Comment by Leynakindle** [comment]
> https://ci.appveyor.com/api/buildjobs/x75x8pr27opolsm6/artifacts/Shadowsocks-4.1.9.0-67-master.zip 试试这个
@chenshaoju 
谢谢，刚才先用改注册表的方式解决了。这台Win7是公司的电脑，估计是被什么预装软件改了键值。

**Comment by studentmain** [comment]
> > 我看了一下我的注册表，这个`Enabled`键值的确是0，可能我什么时候改过注册表……
> 
> 也可能是他什么时候改过，毕竟目前只有这一则报告

好的，现在有两则了……
