### ISSUE TITLE
The pac rule in 4.1.9 is not compatible with old ones

### ISSUE THREAD

**Issue by imba-tjd** [shadowsocks/shadowsocks-windows#2761]
4.1.9:

```
var __PROXY__ = '127.0.0.1:1080'
var proxy = __PROXY__;
```

While the old version is:

```
var proxy = '__PROXY__';
```

This change will cause all of the old pac.txt broken 😕. I personally don't think it's appropriate. At least a **breaking change** notice should be announced.

**Comment by chenshaoju** [comment]
Maybe is this change:
https://github.com/shadowsocks/shadowsocks-windows/commit/ad36bf6d4d0ac73b37b7b722b5d5d13996bef906

**Comment by studentmain** [comment]
> Maybe is this change:
> [ad36bf6](https://github.com/shadowsocks/shadowsocks-windows/commit/ad36bf6d4d0ac73b37b7b722b5d5d13996bef906)

Yes, my mistake, haven't tested with custom PAC. It's impratical to roll back, so we need document this now.

For breaking change notification see #2758.

We need design and document PAC rule API, see #2746 

（考虑AFK一阵子，最近代码质量不行）

**Comment by studentmain** [comment]
Another reason is resource management, every resource file has two copy: exe builtin one, and one in file system. I'm planning remove builtin one to simplify this problem, but the project only in my fork now, not sure it's a good idea.

https://github.com/studentmain/shadowsocks-windows/tree/no-builtin-blob

**Comment by SinGirl** [comment]
改好就能用了3Q

**Comment by imba-tjd** [comment]
Close as expected.
