### ISSUE TITLE
切换系统代理模式后，设置的代理白名单被重置

### ISSUE THREAD

**Issue by magina2019** [shadowsocks/shadowsocks-windows#2763]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 1909 专业版

### Steps you have tried / 操作步骤
1. Shadowsocks 软件上使用 系统代理 - 全局模式
2. 点击 “win 开始“ - 点击 “设置” 按钮 - 点击 “网络和internet” - 点击 “代理” - 在 手动设置代理 标题下输入需要过滤的地址 - 点击 “保存”
![示例图](https://user-images.githubusercontent.com/50958023/72058377-f4ebb900-330a-11ea-86c9-c0c61ccab6a0.png)
3. 切换 Shadowsocks 软件的 系统代理 至 PAC 模式
4. 切换 Shadowsocks 软件的 系统代理 至 全局模式
5. 查看 步骤 2 设置的白名单，发现被重置了
![image](https://user-images.githubusercontent.com/50958023/72058596-5449c900-330b-11ea-9f2c-6a6cb29ed684.png)

### What did you expect to see? / 期望的结果
切换系统代理模式后，白名单设置不会被重置；
或者 Shadowsocks 提供白名单设置功能

**Comment by RottenPi** [comment]
同样的问题，头疼。每次都把 192.168.* 给加进去了。只好开着代理，选择禁用，手动把系统的代理打开。

**Comment by freydou** [comment]
在shadowsocks客户端关闭的情况下重新设置例外（白名单），然后再开启客户端即可。

**Comment by zhaoaaaaa5** [comment]
> 在shadowsocks客户端关闭的情况下重新设置例外（白名单），然后再开启客户端即可。

老哥 强的，我用clash也这样，关闭后在添加白名单重启也还存在，感谢~
