### ISSUE TITLE
4.1.9.1/4.1.9.2无法代理。同等操作4.1.8.0没问题

### ISSUE THREAD

**Issue by flyarong** [shadowsocks/shadowsocks-windows#2764]
.Net Framwork 4.7.2,删除ss_win_temp重启4.1.9.1/4.1.9.2都服务代理。同样操作4.1.8.0代理没问题。window10 pro版。

**Comment by chenshaoju** [comment]
请删除 Shadowsocks.exe 所在目录下的 pac.txt ，然后右击任务栏托盘区的纸飞机图标，选择PAC，再点击`从GFWList更新本地PAC`后，再试。

**Comment by flyarong** [comment]
可以了，谢谢！
