### ISSUE TITLE
4.1.9.0及之后的

### ISSUE THREAD

**Issue by zero2442** [shadowsocks/shadowsocks-windows#2765]
打开就提示

Shadowsocks non-UI Error 

非预期错误, Shadowsocks将退出。请提交此错误到
https://github.com/shadowsocks/shadowsocks-windows/issues 
System Reflection. TargetInvocation Exception:调用的目标发生了异
第。…> System InvalidOperationException:此实现不是 Windows 
平台FPS验证的加密算法的一部分。
在
System Security. Cryptography. MD5 Crypto Service Provider.ctor()
内部异常堆栈跟踪的结尾
在 If System. RuntimeMethod Handle Invoke Method(object target,
ObjectO[] arguments, Signature sig, Boolean constructor)
在 
System Reflection. Runtime ConstructorInfo Invoke(Binding Flags 
invoke Attr, Binder binder, ObjectO parameters, CultureInfo 
culture)
在
System Security.Cryptography.Cryptography.CreateFromName(String name, ObjectD args)
 在 System Security. Cryptography. MD5. Create0
 在 Shadowsocks Controller PACServer. GetHash(String content 
在
Shadowsocks. Controller. PACServer Update PACURL(Configuration config)
 在Shadowsocks Controller Shadowsocks Controller Reload()
 在Shadowsocks Program Main(String[] args)

**Comment by studentmain** [comment]
#2759
