### ISSUE TITLE
4.1.9.2无法正常使用

### ISSUE THREAD

**Issue by sz-lining** [shadowsocks/shadowsocks-windows#2766]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10，.net Framework 4.7.2

### Steps you have tried / 操作步骤
更新到4.1.9.2后，使用google cloud platform搭建的服务

### What did you expect to see? / 期望的结果
可以正常使用

### What did you see instead? / 实际结果
无法正常使用，切换回4.1.8.0后，配置完全一样的情况下恢复正常，开始还以为是IP被ban了，换了几个一直都不行，最后发现是这个的问题

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
无

**Comment by studentmain** [comment]
试试全局模式

**Comment by sz-lining** [comment]
> 试试全局模式

我已经换回4.1.8.0了，之前包括现在都用的是PAC模式，全局模式有时会比较慢
难道是PAC的问题？

**Comment by studentmain** [comment]
那把pac.txt删了试试

**Comment by sz-lining** [comment]
> 那把pac.txt删了试试

刚试了一下，把pac.txt删掉就可以了，起码目前看起来正常了，看来真的是pac的问题，找了快1个星期的原因。。。。。。

**Comment by studentmain** [comment]
先挂起来吧，当个参考

**Comment by studentmain** [comment]
技术细节见 #2761 ，如果是自己写的PAC，把`"__PROXY__"`替换成`__PROXY__`

**Comment by ohsorry** [comment]
我从4.1.8.0升级到4.1.9.2也不行了。换回4.1.8.0就好了。

![360截图20200111124523526](https://user-images.githubusercontent.com/6219683/72199007-a821f280-3470-11ea-9e09-8eba6dea756f.png)

**Comment by ohsorry** [comment]
> 技术细节见 #2761 ，如果是自己写的PAC，把`"__PROXY__"`替换成`__PROXY__`

智能兼容下旧版本吧，一般都用规则代理，平时很少用全局模式的。

**Comment by studentmain** [comment]
> > 技术细节见 #2761 ，如果是自己写的PAC，把`"__PROXY__"`替换成`__PROXY__`
> 
> 智能兼容下旧版本吧，一般都用规则代理，平时很少用全局模式的。

事实上ss并不能得知一个PAC使用的哪个版本的API...

**Comment by ohsorry** [comment]
我看#2761了，就一行代码的事。不可能让所有人都去学习代码改代码吧。
判断下pac 版本，要不就其他规则过滤智能把pac导入。我是不习惯每次打开记事本去添加新规则。

**Comment by studentmain** [comment]
> 我看#2761了，就一行代码的事。不可能让所有人都去学习代码改代码吧。
> 判断下pac 版本，要不就用其他规则模板过滤，智能把pac导入。我是不习惯每次打开记事本去添加新规则。

4.1.9.2现在是正式版，这意味着如果直接回滚，会破坏4.1.9.2版本新用户的兼容性。

解决方法也不是要自己改代码，删除pac.txt重新生成就可以。

**Comment by ohsorry** [comment]
兄弟你在开玩笑么，这是ss精神么，让别人去操作什么pac。再说哪有什么正式版，永远是bug版。

**Comment by studentmain** [comment]
> 兄弟你在开玩笑么，这是ss精神么，让别人去操作什么pac。再说写程序哪有什么正式版，永远是bug版。

PR is always welcome

**Comment by ohsorry** [comment]
把整体的工程重构、精简下，我乐意维护这个项目。

**Comment by studentmain** [comment]
> 把整体的工程重构、精简下，我乐意维护这个项目。

#2755

**Comment by ohsorry** [comment]
发现我之前的issus还开着#1230。
ss本身就应该是个很精简的工具类的小程序。代码太难读了。

**Comment by flyarong** [comment]
我前面删掉pac.txt，通过4.1.9.2从GFWList更新pac.txt可以代理。然后关机了再重新打开4.1.9.2，通过更新GFWList没法代理。删掉目录下ss_win_temp再开4.1.9.2也没法代理。插件使用obfs。

**Comment by chenshaoju** [comment]
@flyarong 你这可能是另外的问题，如果可能，请发一个新的帖子，贴上日志什么的，以便分析。

**Comment by teigao** [comment]
更新下PAC文件就可以了

**Comment by bbq69** [comment]
![image](https://user-images.githubusercontent.com/56699851/72443634-8d8da780-37e9-11ea-8c71-d106efd2988d.png)
should i delete PAC file from here? can anyone help me please, even my paid ss server is also very unstable after recent update.

**Comment by studentmain** [comment]
> ![image](https://user-images.githubusercontent.com/56699851/72443634-8d8da780-37e9-11ea-8c71-d106efd2988d.png)
> should i delete PAC file from here? can anyone help me please, even my paid ss server is also very unstable after recent update.

yes

**Comment by bbq69** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/56699851/72443634-8d8da780-37e9-11ea-8c71-d106efd2988d.png)
> > should i delete PAC file from here? can anyone help me please, even my paid ss server is also very unstable after recent update.
> 
> yes

i deleted but its automatically installing again when i restart ss and also i am using global mode now.

**Comment by studentmain** [comment]
> 
> 
> > > ![image](https://user-images.githubusercontent.com/56699851/72443634-8d8da780-37e9-11ea-8c71-d106efd2988d.png)
> > > should i delete PAC file from here? can anyone help me please, even my paid ss server is also very unstable after recent update.
> > 
> > 
> > yes
> 
> i deleted but its automatically installing again when i restart ss and also i am using global mode now.

Regenerated one should works

**Comment by xiaojigugujiao** [comment]
话说pac里面可以获取到版本号么？能的话写的判断不就完事了

**Comment by studentmain** [comment]
> 话说pac里面可以获取到版本号么？能的话写的判断不就完事了

不能

**Comment by celeron533** [comment]
gui-config 文件里有版本号

**Comment by studentmain** [comment]
从shadowsocks获取pac版本：几乎不可能，首先用户可以自定义PAC，其次JavaScript解析器是很昂贵的东西

从pac获取shadowsocks版本：没必要，问题并不是取不到版本号，而是没法部署更改后的pac

**Comment by Zhwt** [comment]
像这样的 breaking change 是否应该考虑将版本号跳到 5.0 呢?

**Comment by studentmain** [comment]
> 
> 
> 像这样的 breaking change 是否应该考虑将版本号跳到 5.0 呢?

v5现在是给换NET Core准备的，这个还不够breaking……考虑再攒点PR滚到4.2

**Comment by JaynLau** [comment]
我在 `PAC模式` 里 `从GWFList更新本地PAC` 后重启 `ss` 解决了

**Comment by okudayukiko** [comment]
建议换浏览器，如Firefox。

**Comment by 4331599** [comment]
“如果是自己写的PAC，把"__PROXY__"替换成__PROXY__ ”
It work for me! Thank you！

**Comment by ngnl333** [comment]
点击‘’从GFWList更新本地PCA‘’
我是这样修好的

**Comment by ddknight** [comment]
我原始运行路径为C:\Apps\Shadowsocks
将此路径重命名为C:\Apps\Shadowsocks.old之后,重新创建了C:\Apps\Shadowsocks路径
随后将Shadowsocks-4.1.9.2.zip直接解压后放入其中.直接运行,依然无法正常工作.

**Comment by studentmain** [comment]
@ddknight 另开issue

**Comment by HannibalCJH** [comment]
我今天刚搭的shadowsocks，服务端搭在Azure Ubuntu上，客户端下的4.1.9.2但是无法正常工作

1. 手机Android客户端实测可用
2. Windows客户端不论是PAC还是全局都不能直接使用，比如打开google不行。但是用PAC或者全局然后在Chrome用SwitchyOmega做浏览器代理可以使用。

请问这个是什么情况呢？我也试着删除了PAC文件和使用了4.1.8.0版本都不行

**Comment by chenshaoju** [comment]
请尝试右击任务栏托盘区的纸飞机图标，选择PAC，再点击”从GFWList更新本地PAC“。

是否能看到一个错误提示？如果能看到，请将日志中的内容粘贴上来。

请记得隐藏你的服务器信息。

**Comment by HannibalCJH** [comment]
第一次PAC文件更新成功了，第二次是未发现更新

**Comment by HannibalCJH** [comment]
> 请尝试右击任务栏托盘区的纸飞机图标，选择PAC，再点击”从GFWList更新本地PAC“。
> 
> 是否能看到一个错误提示？如果能看到，请将日志中的内容粘贴上来。
> 
> 请记得隐藏你的服务器信息。

第一次PAC文件更新成功了，第二次是未发现更新

**Comment by chenshaoju** [comment]
这意味着你的客户端连接没有问题。

请再试一下（如PAC模式能否访问Google）。

**Comment by HannibalCJH** [comment]
> 这意味着你的客户端连接没有问题。
> 
> 请再试一下（如PAC模式能否访问Google）。

还是不行，尴尬。现在就拿SwitchyOmega做代理了

**Comment by chenshaoju** [comment]
你是不是用的是（宽带）拨号连接？如果是，请检查一下你的宽带拨号连接名是不是中文的，如果是，修改为英文的再试。
