### ISSUE TITLE
StatisticsStrategyConfigurationForm is untranslatable

### ISSUE THREAD

**Issue by rockenren** [shadowsocks/shadowsocks-windows#2768]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10, latest .NET Framework

### Steps you have tried / 操作步骤
Write translation to disk
Translate generated csv

### What did you expect to see? / 期望的结果
StatisticsStrategyConfigurationForm is translated

### What did you see instead? / 实际结果
StatisticsStrategyConfigurationForm string is missing in i18n.csv

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
None

**Comment by studentmain** [comment]
Statistic feature is not actively maintained, and we never changed default window title.😅

We will rename window title to "Statistic configuration" in next release

**Comment by studentmain** [comment]
You can simply add a line manually in i18n.csv to translate it.
