### ISSUE TITLE
 一使用UU加速器，就无法使用自己的ss代理进行科学上网了

### ISSUE THREAD

**Issue by 0mza987** [shadowsocks/shadowsocks-windows#2769]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10

### Steps you have tried / 操作步骤
打开UU加速器加速游戏，shadowsocks代理失效，退出UU，ss马上恢复

我记得在使用UU后系统有提示我：~~是否应用网络设置到同局域网下，我选择了是。可能是这个操作导致了这个效果~~“是否让相同网络的设备发现此计算机”之类的设置，应该无关。但在我控制台输入 netsh winsock reset 重启后，依然没有得到改善，如果是我本地网络设置问题的话，如何复原呢？

### What did you expect to see? / 期望的结果
两者可以同时使用，uu代理游戏，ss继续科学上网。事实上一直以来我就是这样用的，最近突然变得无法兼容了，不确定是不是uu什么更新导致还是我本地网络设置问题

### What did you see instead? / 实际结果
两者无法同时使用

**Comment by chenshaoju** [comment]
我记得UU加速器有多个模式可以切换。

如果可能，切换一下工作模式看看？

**Comment by 0mza987** [comment]
我这游戏的加速节点清一色全是模式3，没有其他模式的

**Comment by chenshaoju** [comment]
应该和“是否应用网络设置到同局域网下”有关。

我没有使用网易UU，你做个测试，启动加速后，退出SS，然后再重新打开SS，看看是否可以了？

**Comment by 0mza987** [comment]
我将网络设置全部重置，复现了一下那个提示，看来是我记错了，并没有应用网络设置到同局域网下的提示，而是“是否让相同网络的设备发现此计算机”之类的设置，而且不管选哪个，都不影响uu和ss无法同时使用的事实，应该是和这个设置无关了

我照你说的，加速之后退出ss重新打开ss, 发现确实可以同时使用了，uu还是加速游戏，ss科学上网，看来是uu新版本搞了什么骚操作导致ss使用无效，需要再启动ss覆盖操作？

**Comment by chenshaoju** [comment]
有这个可能。

也可能是有冲突，但是具体怎么回事，目前尚未定论。

**Comment by chokaka** [comment]
我跟你一样的问题，加速器是奇游，很烦恼!
