### ISSUE TITLE
增加一个选项以便禁用内置的HTTP代理（Privoxy）

### ISSUE THREAD

**Issue by chenshaoju** [shadowsocks/shadowsocks-windows#277]
目前Shadowsocks for Windows内置的HTTP代理已经从polipo切换到了Privoxy。而我自己已经在使用Privoxy，用于代理分流和过滤。因此在启动后，任务栏托盘区出现两个Privoxy，比较让人困惑。

请考虑增加一个选项，允许用户启用或禁用Shadowsocks for Windows内置的Privoxy。

**Comment by source2git** [comment]
额，是新版本换了代理方式所有托盘区多了个P的图标么？能不能隐藏那个图标呢？我托盘区东西太多了，看着好碍眼。

**Comment by clowwindy** [comment]
Privoxy 并没有隐藏图标的选项，看来只能改一下了。

**Comment by clowwindy** [comment]
好了，直接把 Privoxy 改了下。

**Comment by source2git** [comment]
感谢，么么哒~

**Comment by reaCodes** [comment]
@source2git 怎么解决的？

**Comment by reaCodes** [comment]
@clowwindy Privoxy这个进程，电脑管家清理内存不通知就把它结束掉了，不能和shadowsocks做在一起吗？现在感觉好不方便

**Comment by clowwindy** [comment]
升级到 2.5.4 即可。勿使用国产电脑安全类软件： https://www.v2ex.com/t/173545
