### ISSUE TITLE
ipv6配置问题

### ISSUE THREAD

**Issue by caopengfei** [shadowsocks/shadowsocks-windows#2772]
# Shadowsocks version / 影梭版本
4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows Server 2016 Standard

### Steps you have tried / 操作步骤
服务器地址填写ipv6地址，如：2001:19f0:6001:3606:5400:02ff:fe3d:ed2a，其他配置项跟ipv4一致。

### What did you expect to see? / 期望的结果
访问ipv6上的Shadowsocks服务

### What did you see instead? / 实际结果
连接超时（time out）

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

请问如果要使用ipv6提供的Shadowsocks服务，本地服务器是否需要支持ipv6呢？

**Comment by chenshaoju** [comment]
本地计算机（或者本地计算机所在的路由器）和远程服务器都需要具有有效的IPv6地址和路由能力。

Shadowsocks本身支持IPv6访问：
https://twitter.com/chenshaoju/status/1043793175280844801
