### ISSUE TITLE
最新版打不开exe文件 让我提交错误到这

### ISSUE THREAD

**Issue by yangchaoyue101** [shadowsocks/shadowsocks-windows#2773]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 7 Ultimate with Service Pack 1 (x64) 
.NET Framework 4.7.2

### Steps you have tried / 操作步骤
双击shadowsocks.exe

### What did you expect to see? / 期望的结果
进入主界面

### What did you see instead? / 实际结果
显示如图对话框
![a676e69327454d5505ef6163f38336a](https://user-images.githubusercontent.com/16345320/72487108-dffdb100-3847-11ea-92f0-81e46ac65763.png)

Shadowsocks non-UI Error
      非预期错误, Shadowsocks将退出。请提交此错误htts://github.com/shadowsocks/shadowsocks-windows/issues
       System.ArgumentException:字体"Consolas"不支持样式”Regular”。
      在System.Drawing.Font.CreateNativeFont()
      在System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet,Boolean gdiVerticalFont)
      在System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet,Boolean gdiVerticalFont)
      在System.Drawing.Font..ctor(String familyName, Single emSize)
      在Shadowsocks.ModelLogViewerConfig..ctor()
      在Shadowsocks.Model.Configuration.Load()
      在Shadowsocks.Util.Utils.GetTempPath()
      在Shadowsocks.Controller.Logging.OpenLogFile()
      在Shadowsocks.Program.Main(String[] args)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1958

**Comment by yangchaoyue101** [comment]
谢谢 安装consolas之后解决
