### ISSUE TITLE
Always generate SIP002 URL

### ISSUE THREAD

**Issue by studentmain** [shadowsocks/shadowsocks-windows#2774]
### Shadowsocks version / 影梭版本
v4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
N/A

### Steps you have tried / 操作步骤

1. Create server with following config:
```json
{
      "server": "127.0.0.1",
      "server_port": 8388,
      "password": "123456",
      "method": "chacha20-ietf-poly1305",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
}
```
2. Share server link

### What did you expect to see? / 期望的结果
`ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNToxMjM0NTY@127.0.0.1:8388` (generated by ss-android)

### What did you see instead? / 实际结果
`ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNToxMjM0NTZAMTI3LjAuMC4xOjgzODg=`

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
N/A

**Comment by celeron533** [comment]
Does the user have choice to select the legacy uri format? If not, it is a "significant" change for the target release. We need to tell users the change.

**Comment by studentmain** [comment]
> Does the user have choice to select the legacy uri format?

A hidden field in gui-config.json can be added (I don't want to touch GUI), but I'm not sure it's enough.

> a "significant" change

Yes, but I wonder how many user still use old version which doesn't support SIP002.

Current plan is do it after #2758, in v4.2.x, so we can notice them.
