### ISSUE TITLE
新电脑在win10下4.1.8.0无法正常使用

### ISSUE THREAD

**Issue by Jinli012** [shadowsocks/shadowsocks-windows#2775]
### Shadowsocks version / 影梭版本
4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
.NET Framework

### Steps you have tried / 操作步骤
更改pac

### What did you expect to see? / 期望的结果
正常使用

### What did you see instead? / 实际结果
无法连接，pac更新失败

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
配置日志内容：
操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。  
 在System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---

**Comment by chenshaoju** [comment]
你好，这个提示意味着从你的服务器的连接中断了。

可能是IP、端口、加密方式或者密码不正确。

也可能是被墙了。

请尝试右击任务栏托盘区的纸飞机图标，选择PAC，再点击从GFWList更新本地PAC，能否看到更新成功或者没有更新的提示？

如果提示错误，日志中显示什么？

**Comment by Jinli012** [comment]
> 你好，这个提示意味着从你的服务器的连接中断了。
> 
> 可能是IP、端口、加密方式或者密码不正确。
> 
> 也可能是被墙了。
> 
> 请尝试右击任务栏托盘区的纸飞机图标，选择PAC，再点击从GFWList更新本地PAC，能否看到更新成功或者没有更新的提示？
> 
> 如果提示错误，日志中显示什么？

您好，在更新pac的时候提示：
操作过程中出现异常，结果无效。有关异常的详细信息，请查看innerexception。   

我的服务器的是我自己搭建的，我在我win7的旧电脑和手机的纸飞机上还可以正常使用，在win10上我就搞不清楚是什么原因了，谢谢您

**Comment by chenshaoju** [comment]
如果你确定相同的网络下，只有Win10不能用，很有可能是你的配置有误，请仔细检查。

如果仍然不行，请尝试重置TCP/IP和Winsock网络栈看看：

请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。

重启后看看效果是否有改善。

**Comment by Jinli012** [comment]
> 如果你确定相同的网络下，只有Win10不能用，很有可能是你的配置有误，请仔细检查。
> 
> 如果仍然不行，请尝试重置TCP/IP和Winsock网络栈看看：
> 
> 请尝试以管理员身份启动命令提示符或者PowerShell，然后执行：
> 
> ```
> netsh interface ipv4 reset
> netsh interface ipv6 reset
> netsh interface tcp reset
> netsh winsock reset
> ```
> 
> 一行一回车，四行执行完毕后重新启动计算机再看看。如果你的计算机是手动指定IP的，重启后可能需要再手动设置一次。如果是自动分配（DHCP）则无此问题。
> 
> 重启后看看效果是否有改善。

显示的日志内容：
在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

依然还是错误无法更新pac，会是https的影响么？

**Comment by chenshaoju** [comment]
如果可能，请尝试换一个端口看看（包括服务器）。

如果情况允许，建议套个插件（包括服务端和客户端）：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by Jinli012** [comment]
> 如果可能，请尝试换一个端口看看（包括服务器）。
> 
> 如果情况允许，建议套个插件（包括服务端和客户端）：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

好的，谢谢您  我试一下

**Comment by Jinli012** [comment]
> 如果可能，请尝试换一个端口看看（包括服务器）。
> 
> 如果情况允许，建议套个插件（包括服务端和客户端）：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

问题已解决，给服务器换一个端口就可以上网了，感谢您的解答。
