### ISSUE TITLE
Use weblate.org or other providers to facilitate the translation

### ISSUE THREAD

**Issue by celeron533** [shadowsocks/shadowsocks-windows#2776]
https://weblate.org/

sample (switchyomega):
https://hosted.weblate.org/engage/switchyomega/

**Comment by studentmain** [comment]
Netrual on using third party platform. But I want make sure:

- User can translate software with notepad
- User can directly open PR for translate

So when some thing bad happened, we can still update translate.

**Reminder**: Update instruction after we finish this

**Comment by celeron533** [comment]
This is just a scope or assumption, not the real release target right now.
