### ISSUE TITLE
使用kcptun不能上网的问题

### ISSUE THREAD

**Issue by shadylyf321** [shadowsocks/shadowsocks-windows#2777]
连接设置：
![image](https://user-images.githubusercontent.com/31873593/72658593-137a4000-39ee-11ea-863a-65c9f5e09c47.png)
![image](https://user-images.githubusercontent.com/31873593/72658648-b468fb00-39ee-11ea-8988-3f0f842dac38.png)

windows上查看9527端口状态正常
![image](https://user-images.githubusercontent.com/31873593/72658643-9a2f1d00-39ee-11ea-9ab6-265c20b96bd0.png)
shadowsocks连接本地9527端口 可以发现udp stream opened和closed频繁变化
抓包显示 有udp包发送至服务器 也有来自服务器的udp包 
感觉连接正常，但就是不能上网 不知道有朋友遇到过吗

**Comment by chenshaoju** [comment]
这意味着你的配置有误，请检查加密算法（包括SS和kcp）、密码、模式是否正确。

**Comment by shadylyf321** [comment]
感谢回答！ 的确ss密码写成kcp key了。
