### ISSUE TITLE
2.5.4老出错！

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-windows#278]
---------------------------
Privoxy Error
---------------------------
Fatal error: can't check configuration file 'C:\Users\LisonFan\AppData\Local\Temp\/privoxy.conf':  (error number 2)

---------------------------
确定   
---------------------------

**Comment by clowwindy** [comment]
2.5.3 有这个问题么？

**Comment by clowwindy** [comment]
在 Windows 7 和 10 上都没有遇到这个问题。

**Comment by chenshaoju** [comment]
查了一下， Error 2 = 系统找不到指定的文件。 

我怀疑有没有可能和文件名的那个斜杠 （\/） 有关。

不过我的Windows 7 x64也没有遇到这个问题问题。

建议楼主检查一下 %temp% 文件夹（按Win+R，输入 %temp%，然后回车），找一下有没有叫 privoxy.conf 的文件。

**Comment by LisonFan** [comment]
@clowwindy 就是从2.5.3开始出这个问题的，我也是Win10 x64 企业版

**Comment by LisonFan** [comment]
@chenshaoju  没有这个文件！

**Comment by LisonFan** [comment]
@clowwindy 还有一个问题，shadowsocks.availability.csv 保存在这个文件里的中文乱码

**Comment by LisonFan** [comment]
@chenshaoju ![](http://ww3.sinaimg.cn/large/71fb307agw1ev4zzfzy1pj208602xq3a.jpg)

**Comment by chenshaoju** [comment]
乱码可能和中文编码有关，这个是一个BUG。

![screenshot1](https://cloud.githubusercontent.com/assets/515763/9294717/0d7ad102-4488-11e5-86ad-2f9171c5f5ed.png)

**Comment by icylogic** [comment]
没有指定编码时c#默认保存的是 UTF8 无 BOM，dos line-ending，可以用 vim 或者 notepad++ 之类的打开确认一下。

**Comment by clowwindy** [comment]
你用的系统是什么语言的呢？

**Comment by reaCodes** [comment]
@LisonFan 你用了什么清理垃圾的工具了吗？我也遇到这个问题，电脑管家很容易会把这个小文件视为垃圾清理掉，再生成一次就好。

**Comment by icylogic** [comment]
为什么视为垃圾。。
为了应对电脑管家类软件，是不是应该把这个 log 从 %TEMP% 移到别的地方，比如和 shadowsocks.exe 同一个目录？

**Comment by reaCodes** [comment]
@icylogic 能合并的文件最好合并管理，这样好处多一点

**Comment by clowwindy** [comment]
以前这些文件是放当前目录的，然而有些用户喜欢把 Shadowsocks 放 Dropbox 里，造成不停的同步。

**Comment by icylogic** [comment]
合并？你想合并到什么文件里

**Comment by LisonFan** [comment]
@clowwindy 简体中文

**Comment by LisonFan** [comment]
@reaCodes CCleaner

**Comment by clowwindy** [comment]
Fixed in 2.5.5
