### ISSUE TITLE
关闭首次运行的编辑服务器窗口后无法正确选择服务器

### ISSUE THREAD

**Issue by reizhi** [shadowsocks/shadowsocks-windows#2782]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7 7601 & win10 1809

### Steps you have tried / 操作步骤
运行 shadowsocks.exe 后，点击取消或x关闭首次弹出的编辑服务器窗口，随后使用扫描二维码方式添加服务器。并在服务器中勾选刚刚添加的服务器。

### What did you expect to see? / 期望的结果
正常使用 ss 服务

### What did you see instead? / 实际结果
实际此时使用的仍然是首次弹出的“未配置的服务器”，尽管右键菜单中显示刚刚扫码添加的服务器已选中。
打开相关网站时会提示“Could not load template file no-server-data or one of its included components.”
再次打开编辑服务器窗口，删除“未配置的服务器”并保存后，恢复正常。
或在首次运行时，不关闭编辑服务器窗口，手动填写服务器信息也可以避免此错误。
该问题在旧版本（如4.0.8）中不存在。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2020-01-27 14:00:44] Current language is: zh-CN
[2020-01-27 14:00:45] Shadowsocks started (4.1.9.2)
[2020-01-27 14:01:08] Shadowsocks started (4.1.9.2)
[2020-01-27 14:01:11] Shadowsocks started (4.1.9.2)
[2020-01-27 14:01:14] Shadowsocks started (4.1.9.2)
[2020-01-27 14:01:17] Shadowsocks started (4.1.9.2)
[2020-01-27 14:01:17] Shadowsocks started (4.1.9.2)
[2020-01-27 14:02:11] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2020-01-27 14:02:11] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2020-01-27 14:02:11] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2020-01-27 14:02:11] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2020-01-27 14:02:11] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
```

**Comment by chenshaoju** [comment]
1.双击 Shadowsocs.exe
2.点击编辑服务器界面的红叉。
3.右击托盘区的纸飞机图标，选择服务器，再点击扫描屏幕上的二维码。
4.再次叉掉编辑服务器对话框。
5.右击任务栏托盘区的纸飞机图标，选择服务器，再选择刚才添加的服务器。

无法复现，请尝试重命名 Shadowsocks.exe 所在目录下的 gui-config.json 文件后再试一次？

**Comment by reizhi** [comment]
> 1.双击 Shadowsocs.exe
> 2.点击编辑服务器界面的红叉。
> 3.右击托盘区的纸飞机图标，选择服务器，再点击扫描屏幕上的二维码。
> 4.再次叉掉编辑服务器对话框。
> 5.右击任务栏托盘区的纸飞机图标，选择服务器，再选择刚才添加的服务器。
> 
> 无法复现，请尝试重命名 Shadowsocks.exe 所在目录下的 gui-config.json 文件后再试一次？

请注意第四步是点击确定来添加服务器。
这个问题在我自己的电脑上，虚拟机中，以及其他人的电脑上都有遇到过。关掉首次弹出的编辑服务器后，是没有 gui-config.json 文件的。扫描并添加服务器时，可以看到窗口中有一个“未配置的服务器”。
点击确定后， gui-config.json 中也有这个不存在的服务器
`{
  "version": "4.1.9.2",
  "configs": [
    {
      "server": "",
      "server_port": 8388,
      "password": "",
      "method": "chacha20-ietf-poly1305",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    },
    {
      "server": "161.117.*****",
      "server_port": 52617,
      "password": "576******",
      "method": "aes-256-gcm",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5
    }
  ],`

![Ht1j.png](https://ooo.0x0.ooo/2020/01/27/Ht1j.png)

**Comment by chenshaoju** [comment]
请看一下我的操作步骤，不动戳大。

![GIF](https://user-images.githubusercontent.com/515763/73167616-1f26de80-4133-11ea-8726-bef4a5326781.gif)

**Comment by reizhi** [comment]
> 请看一下我的操作步骤，不动戳大。
> 
> ![GIF](https://user-images.githubusercontent.com/515763/73167616-1f26de80-4133-11ea-8726-bef4a5326781.gif)

和我所指的操作步骤完全相同

**Comment by celeron533** [comment]
修改服务器后，`gui-config.cfg`文件中"index"值是多少？此时你一共有多少服务器？

**Comment by reizhi** [comment]
> 修改服务器后，`gui-config.cfg`文件中"index"值是多少？此时你一共有多少服务器？

index 是0，此时右键菜单仅有刚刚扫码添加的服务器，但 config 文件中有两个，如前所示。
如打开分享服务器配置窗口，也可以看到“未配置的服务器”和扫码添加的服务器
![20200127203249](https://user-images.githubusercontent.com/9074228/73175166-839e6980-4144-11ea-9a96-7dab03b6c613.png)

![20200127203309](https://user-images.githubusercontent.com/9074228/73175171-87ca8700-4144-11ea-89b6-b3d913ca0740.png)

![20200127203830](https://user-images.githubusercontent.com/9074228/73175421-1b03bc80-4145-11ea-87eb-ba077922affc.png)

**Comment by celeron533** [comment]
已确认问题，其实不仅仅是第一次使用时出现，而是只要服务器列表里有非法内容（未配置的服务器）时，其后续服务器都会错位。

**Comment by tomac4t** [comment]
@reizhi 二维码那张截图泄露了你的IP地址，自行编辑并删除历史记录吧。

**Comment by reizhi** [comment]
> @reizhi 二维码那张截图泄露了你的IP地址，自行编辑并删除历史记录吧。

Thanks, 不过几天后就要扔掉了
