### ISSUE TITLE
ss-Windows部分情况无法运作

### ISSUE THREAD

**Issue by zealothunter** [shadowsocks/shadowsocks-windows#2785]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10 1909，.net Framework 4.7.2

### Steps you have tried / 操作步骤
配置了新的ss-server，在ss-Android中已经确定这台新的server配置正常且由于安卓机和电脑在同一网络环境下，可判断并没有被上一级block掉；ss-Windows中填写的密码和加密方式无误但无法连接，Google Chrome显示ERR_CONNECTION_CLOSED。原先配置的ss-server使用ss-windows能正常连接。新server能被ping通，telnet能连接到ss-server服务端口

### What did you expect to see? / 期望的结果
在Windows中正常使用

### What did you see instead? / 实际结果
无法连接，有出站流量但没有入站流量

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

eg：
[2020-01-28 04:03:58] connect to android.clients.google.com:443
[2020-01-28 04:03:58] connect to mtalk.google.com:5228
[2020-01-28 04:03:58] connect to update.googleapis.com:443
[2020-01-28 04:03:58] Socket connected to ss server: xxxx
[2020-01-28 04:03:58] Socket connected to ss server: xxxx
[2020-01-28 04:03:58] Socket connected to ss server: xxxx
[2020-01-28 04:03:59] Socket connected to ss server: xxxx
[2020-01-28 04:03:59] connect to www.googleapis.com:443
[2020-01-28 04:03:59] Socket connected to ss server: xxxx
[2020-01-28 04:03:59] connect to www.googleapis.com:443
[2020-01-28 04:03:59] Socket connected to ss server: xxxx
[2020-01-28 04:04:00] connect to www.googleapis.com:443
[2020-01-28 04:04:00] Socket connected to ss server: xxxx
[2020-01-28 04:04:00] connect to clients2.google.com:443

看起来很正常但就是没有入站流量

**Comment by chenshaoju** [comment]
请尝试右击任务栏托盘区的SS纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”，是否能提示更新成功或者没有找到更新？

如果提示错误，错误内容是什么？

**Comment by zealothunter** [comment]
> 请尝试右击任务栏托盘区的SS纸飞机图标，选择PAC，再点击“从GFWList更新本地PAC”，是否能提示更新成功或者没有找到更新？
> 
> 如果提示错误，错误内容是什么？

能更新，提示成功

**Comment by chenshaoju** [comment]
这意味着请求过程没有问题。

能否做个测试，在更新PAC后，系统代理使用PAC，然后使用系统自带的IE浏览器试试看，能否访问Google？

**Comment by zealothunter** [comment]
不能，ie也是无法访问状态

**Comment by celeron533** [comment]
老版本和新版本基本没改过核心加密连接部分，有点奇怪

**Comment by chenshaoju** [comment]
我记得GFWList的更新是通过代理更新的，如果代理无效，那么会无法更新：
![image](https://user-images.githubusercontent.com/515763/73268935-d5172900-4216-11ea-98f6-c9d7a9a5e1dd.png)

你有Firefox吗？如果用Firefox指定代理设置，能否正常工作？
![image](https://user-images.githubusercontent.com/515763/73269049-07c12180-4217-11ea-8d7a-ded6f0e36146.png)

**Comment by zealothunter** [comment]
> 我记得GFWList的更新是通过代理更新的，如果代理无效，那么会无法更新：
> ![image](https://user-images.githubusercontent.com/515763/73268935-d5172900-4216-11ea-98f6-c9d7a9a5e1dd.png)
> 
> 你有Firefox吗？如果用Firefox指定代理设置，能否正常工作？
> ![image](https://user-images.githubusercontent.com/515763/73269049-07c12180-4217-11ea-8d7a-ded6f0e36146.png)

我在用firefox 72和chrome 79，我Firefox原来默认的就是这种设置，依旧不行，我怀疑server端设置有什么问题导致ss-Android能连而ss-Windows不能，我再试试重新配置下server。

**Comment by zealothunter** [comment]
> 老版本和新版本基本没改过核心加密连接部分，有点奇怪

我怀疑server端设置有什么问题导致ss-Android能连而ss-Windows不能，我再试试重新配置下server。

**Comment by chenshaoju** [comment]
这个和服务端没有关系。

如果你能通过PAC菜单下的“通过GFWList更新本地PAC”功能成功更新，说明你的代理配置并没有问题，因为更新本地PAC这个动作是通过你本机的SS代理的。

如果可能，请尝试按照上图配置一下Firefox，看看手动指定代理的情况下是否可以正常工作。

**Comment by zealothunter** [comment]
> 不好意思，没仔细看，滚动到下面了。
> 
> 但是能更新本地PAC，说明连接应该是正常的。
> 
> ~这个和服务端没有关系。~
> 
> ~如果你能通过PAC菜单下的“通过GFWList更新本地PAC”功能成功更新，说明你的代理配置并没有问题，因为更新本地PAC这个动作是通过你本机的SS代理的。~
> 
> ~如果可能，请尝试按照上图配置一下Firefox，看看手动指定代理的情况下是否可以正常工作。~

我重新安装了下ss-server竟然能让ss-Windows正常使用了，感觉是碰到了玄学情况，毕竟server的配置文件用的是同一个，我再观察下syslog看到底是什么出的问题……
