### ISSUE TITLE
Can a server has more than one server_port? 能否支持单个server多端口配置

### ISSUE THREAD

**Issue by okhowang** [shadowsocks/shadowsocks-windows#2786]
I have setup ss-server with multiple port
but config in client is duplicate because a server has only one server_port.

### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10 1909

### What did you expect to see? / 期望的结果
some configure like below
```json5
    {
      "server": "example.org",
      "server_port": [8383,8384,8385],
      //or
      "server_port": "8383-8385"
      ...
    },
```
### What did you see instead? / 实际结果
i have to set multiple server
```json5
    {
      "server": "example.org",
      "server_port": 8383,
      ...
    },    {
      "server": "example.org",
      "server_port": 8384,
      ...
    },    {
      "server": "example.org",
      "server_port": 8385,
      ...
    },
```

**Comment by chenshaoju** [comment]
目前的方案是这样的：
配置多个服务器，不同的端口
然后使用负载均衡模式。

**Comment by studentmain** [comment]
多端口使用面比较狭窄，支持代价太大，从里到外全部要修改，不咋想加
而且前面还有一堆其他计划，即使要加也要猴年马月去了……
