### ISSUE TITLE
同一个服务器，手机端（安卓，iPad）ss比电脑端ss速度慢，如何解决？

### ISSUE THREAD

**Issue by luhalipeng** [shadowsocks/shadowsocks-windows#2788]
电脑端的能跑7m-13m，iPad端ss只能跑300多kb

**Comment by studentmain** [comment]
联系手机端提供方

**Comment by luhalipeng** [comment]
> 联系手机端提供方

朋友，我手机端(安卓)和iPad端都是这种情况，跟什么有关系呢？配置？

**Comment by studentmain** [comment]
那难说，电脑比手机慢的也多，电脑和手机都慢的也有，查得出来原因的没几个，计算机网络是玄学……我只能说本项目没有任何特殊的加速或者减速手段，速度完全取决于环境……

**Comment by luhalipeng** [comment]
> 网



> 那难说，电脑比手机慢的也多，电脑和手机都慢的也有，查则来原因的没几个，计算机网络是玄学……我只能说本项目没有任何特殊的加速或减速手段，速度完全肯定环境……

我都郁闷了，怎么差这么多，服务器是vultr的，配置BBR PLUS,电脑起飞，手机直接废了
