### ISSUE TITLE
不能用了？

### ISSUE THREAD

**Issue by zhaoyi1025** [shadowsocks/shadowsocks-windows#2789]
最近不能用了？

**Comment by DLzZ2013** [comment]
这两天一直连接超时，重新装了连上了马上又time out 不知道什么情况

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，请尝试套个插件。

https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by wuweijian1997** [comment]
> 如果你的服务器是自己搭建的，请尝试套个插件。
> 
> [#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

大佬有没有博客教程什么的？之前配置了simple-obfs用不了，不知道那里出问题了

**Comment by chenshaoju** [comment]
具体是如何配置的？请去掉IP、密码，然后把配置发上来。

**Comment by alsdonsen** [comment]
目前根据抓包来看，流量是发的出去，但是收不回来

**Comment by chenshaoju** [comment]
是，通俗点说就是被墙了，请更换IP后，按照上面的回复套个插件看看。

**Comment by alsdonsen** [comment]
你恢复了？

**Comment by yegram** [comment]
我也是
