### ISSUE TITLE
Is there a way to switch between pac and global mode by command line or shortcut? 

### ISSUE THREAD

**Issue by woshichuanqilz** [shadowsocks/shadowsocks-windows#2791]
### Shadowsocks version / 影梭版本
4.1.9

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10 

### Steps you have tried / 操作步骤
I need to change between pac mode and global mode frequently, so I prefer a easy way to do this instead of find the tray icon right click and etc. So boring. 

So is there a better to switch it?

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/73671383-c14e4580-46a2-11ea-93ae-a0092fdaaf6f.png)
