### ISSUE TITLE
win10下强制开启“手动设置代理”

### ISSUE THREAD

**Issue by NP-Prob** [shadowsocks/shadowsocks-windows#2792]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
关闭开机自启动，且选择了禁用后，退出了shadowsocks
关闭了win10系统设置里的手动设置代理的“使用代理服务器”

### What did you expect to see? / 期望的结果
彻底退出，正常使用网络，不走代理，或使用其他代理

### What did you see instead? / 实际结果
win10系统设置里的手动设置代理的“使用代理服务器”每隔一段时间就会自动打开
关掉又打开，如此反复
若设置了其他代理地址和端口，又会被改变

**Comment by chenshaoju** [comment]
不开 Shadowsocks.exe 也会这样吗？

**Comment by NP-Prob** [comment]
> 不开 Shadowsocks.exe 也会这样吗？

对，我说的就是退出之后会发生这个情况，退出后重启电脑似乎也没用，我可以再试试重启一下，我记得是没用…

**Comment by chenshaoju** [comment]
如果你没有启动SS也会自动改代理，可能和你计算机的软件有关。

请不要开启SS，用这个方法跟踪一下：https://github.com/shadowsocks/shadowsocks-windows/issues/1527

**Comment by NP-Prob** [comment]
> 如果你没有启动SS也会自动改代理，可能和你计算机的软件有关。
> 
> 请不要开启SS，用这个方法跟踪一下：#1527

我后来用各种方式查出来了，不是SS的问题，是WeChat和OneDrive会定时修改“使用代理服务器”，之前因为我一直开着SS用电脑的，从没关过，然后最近关掉SS才发现这个问题，所以我以为是SS的问题，是我弄错了。
就是还没有找到好的解决方案……

**Comment by chenshaoju** [comment]
👌
