### ISSUE TITLE
SSR obfs-local 混淆模式，shadowsocks-windows客户端无法链接

### ISSUE THREAD

**Issue by hoticebeijing** [shadowsocks/shadowsocks-windows#2793]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

windows 7
### Steps you have tried / 操作步骤
服务器配置完成，并且 启动 
ShadowsocksR SSRR 3.2.2
使用ASUS路由器配置，科学上网，SSR，路由器可以正常链接，电脑可以通过路由器正常上网。
使用Shadowsocks  windows客户端，同目录下解压了obfs-loca.exe以及动态链接文件，配置完成后，无法上网。报错!

![image](https://user-images.githubusercontent.com/60657387/73945048-a3951080-492e-11ea-8af1-d946af28cb13.png)

### What did you expect to see? / 期望的结果

Shadowsocks  windows 可上网。

### What did you see instead? / 实际结果
采用混淆模式，windows客户端 无法链接。插件报错信息：
simple-obfs  invalid obfuscating
windows 客户端 无法链接。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
服务器配置信息：

![QQ截图20200206221117](https://user-images.githubusercontent.com/60657387/73944618-da1e5b80-492d-11ea-9e27-5fa568efaa4e.jpg)
windows client 端配置
![image](https://user-images.githubusercontent.com/60657387/73944590-d12d8a00-492d-11ea-9059-4482078dbf63.png)
![image](https://user-images.githubusercontent.com/60657387/73944741-0cc85400-492e-11ea-92da-85be787f9a8e.png)

**Comment by studentmain** [comment]
仅仅提醒一下，simple-obfs停更了，ssrr更新也很慢，他们比我们还缺开发者……

你可以使用标准的ssrr客户端，不用在这边绕一圈，吃力不讨好

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/73966416-dbd82700-490d-11ea-9e69-c01c968527b3.png)
protocol设成plain试试？

**Comment by hoticebeijing** [comment]
谢谢，已经解决。换了一个客户端软件 。
https://github.com/shadowsocksrr/shadowsocksr-csharp/releases
就不用再下载obfs-local了。最新版的ssrr完全够用。谢谢！
另外：我这样设计架构了我的科学上网，
先在国内用一台vps构建了OPENVPN 服务器A，在国外构建一台SSR服务器B。
SSR仅对 A开放访问，客户端通过登录 OpenVpn可以访问B，这样可以访问外网。
看看这样有B，还会不会被扫描到，测试一下生命周期，能活几天。

**Comment by sickneet** [comment]
> 

你好，请问你是怎么解决的？我一直用的就是你链接所放的那个软件，但是obfs节点都连接不上。下载obfs-local也不行，软件自身就没有obfs这个选项。。。
