### ISSUE TITLE
IP能PING通 连不上SS

### ISSUE THREAD

**Issue by champion2113** [shadowsocks/shadowsocks-windows#2794]
最近忽然连不上搬瓦工上的SS了，
年前还能用，最近一直连不上。
用PING.PE发现能PING通，什么配置也没改过。
有大佬能帮忙吗，谢谢！

**Comment by RushFTK** [comment]
你好！我只是路过的
请按照如下模版填写问题，并提供更多的详细信息，这样有助于你的问题更有机会得到解答
````
### Shadowsocks version / 影梭版本

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

### Steps you have tried / 操作步骤

### What did you expect to see? / 期望的结果

### What did you see instead? / 实际结果

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

````
请复制上面的代码来修改你的主题帖，并**尽可能的**在每一个副标题下提供**尽可能多的信息**。

**Comment by chenshaoju** [comment]
请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check

**Comment by zhaos92** [comment]
我最近也遇到这个问题了。
ss 的端口被封，其他端口正常。换 ss 的端口能正常翻墙，但是过不了一刻钟又被封了。

**Comment by chenshaoju** [comment]
如果你的服务器是自己搭建的，请尝试套个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836
