### ISSUE TITLE
服务器一直time out是怎么回事

### ISSUE THREAD

**Issue by FRenzyneedhairs** [shadowsocks/shadowsocks-windows#2796]
### Shadowsocks version / 影梭版本
4.1.2.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
按照教程配置好了服务器，和PAC文件，查看日志的时候全部服务器都显示time out

### What did you expect to see? / 期望的结果
让我成功地登上google吧

### What did you see instead? / 实际结果
目前什么外网都上不了

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[pac.txt](https://github.com/shadowsocks/shadowsocks-windows/files/4176792/pac.txt)
[shadowsocks.log](https://github.com/shadowsocks/shadowsocks-windows/files/4176793/shadowsocks.log)
配置文件就不放了，那个没问题

**Comment by studentmain** [comment]
服务器疑似被墙了

**Comment by chenshaoju** [comment]
请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check

**Comment by FRenzyneedhairs** [comment]
> 服务器疑似被墙了

被墙了怎么解决呀，刚买的连不上真就枯了

**Comment by FRenzyneedhairs** [comment]
> 请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check

测试过了，腾讯云的是overtime，AWS的可以

**Comment by chouxianyu** [comment]
> > 请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check
> 
> 测试过了，腾讯云的是overtime，AWS的可以

我的ss昨天晚上开始也是一直timeout。
如果用[https://ip100.info/check](https://ip100.info/check)检测，我检测端口的话也是这样（腾讯云结果是over_time，AWS结果是open），只检测IP的话两个结果都是over_time。
如果用[https://www.vps234.com/ipchecker/](https://www.vps234.com/ipchecker/)检测的话，我的服务器IP都通的呀，自己ping我的服务器也是可以通的。

**Comment by chouxianyu** [comment]
> > > 请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check
> > 
> > 
> > 测试过了，腾讯云的是overtime，AWS的可以
> 
> 我的ss昨天晚上开始也是一直timeout。
> 如果用https://ip100.info/check检测，我检测端口的话也是这样（腾讯云结果是over_time，AWS结果是open），只检测IP的话两个结果都是over_time。
> 如果用https://www.vps234.com/ipchecker/检测的话，我的服务器IP都通的呀，自己ping我的服务器也是可以通的。

刚刚给VPS换了IP，现在好了，没有timeout了。
目前检测情况如下：
用[https://ip100.info/check](https://ip100.info/check)检测，我检测端口的话两个结果都是open，只检测IP的话两个结果都是closed。

**Comment by FRenzyneedhairs** [comment]
> > > > 请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check
> > > 
> > > 
> > > 测试过了，腾讯云的是overtime，AWS的可以
> > 
> > 
> > 我的ss昨天晚上开始也是一直timeout。
> > 如果用[https://ip100.info/check检测，我检测端口的话也是这样（腾讯云结果是over_time，AWS结果是open），只检测IP的话两个结果都是over_time。](https://ip100.info/check%E6%A3%80%E6%B5%8B%EF%BC%8C%E6%88%91%E6%A3%80%E6%B5%8B%E7%AB%AF%E5%8F%A3%E7%9A%84%E8%AF%9D%E4%B9%9F%E6%98%AF%E8%BF%99%E6%A0%B7%EF%BC%88%E8%85%BE%E8%AE%AF%E4%BA%91%E7%BB%93%E6%9E%9C%E6%98%AFover_time%EF%BC%8CAWS%E7%BB%93%E6%9E%9C%E6%98%AFopen%EF%BC%89%EF%BC%8C%E5%8F%AA%E6%A3%80%E6%B5%8BIP%E7%9A%84%E8%AF%9D%E4%B8%A4%E4%B8%AA%E7%BB%93%E6%9E%9C%E9%83%BD%E6%98%AFover_time%E3%80%82)
> > 如果用[https://www.vps234.com/ipchecker/检测的话，我的服务器IP都通的呀，自己ping我的服务器也是可以通的。](https://www.vps234.com/ipchecker/%E6%A3%80%E6%B5%8B%E7%9A%84%E8%AF%9D%EF%BC%8C%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8IP%E9%83%BD%E9%80%9A%E7%9A%84%E5%91%80%EF%BC%8C%E8%87%AA%E5%B7%B1ping%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B9%9F%E6%98%AF%E5%8F%AF%E4%BB%A5%E9%80%9A%E7%9A%84%E3%80%82)
> 
> 刚刚给VPS换了IP，现在好了，没有timeout了。
> 目前检测情况如下：
> 用https://ip100.info/check检测，我检测端口的话两个结果都是open，只检测IP的话两个结果都是closed。

你好，我这边还是不行，具体获取ip的方法如下：
在cmd输入：tracert 服务器地址->获取服务器ip
然后在[https://ip100.info/check]检测，输入ip和端口，国内还是overtime

**Comment by FRenzyneedhairs** [comment]
> 请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check



> > > > 请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check
> > > 
> > > 
> > > 测试过了，腾讯云的是overtime，AWS的可以
> > 
> > 
> > 我的ss昨天晚上开始也是一直timeout。
> > 如果用[https://ip100.info/check检测，我检测端口的话也是这样（腾讯云结果是over_time，AWS结果是open），只检测IP的话两个结果都是over_time。](https://ip100.info/check%E6%A3%80%E6%B5%8B%EF%BC%8C%E6%88%91%E6%A3%80%E6%B5%8B%E7%AB%AF%E5%8F%A3%E7%9A%84%E8%AF%9D%E4%B9%9F%E6%98%AF%E8%BF%99%E6%A0%B7%EF%BC%88%E8%85%BE%E8%AE%AF%E4%BA%91%E7%BB%93%E6%9E%9C%E6%98%AFover_time%EF%BC%8CAWS%E7%BB%93%E6%9E%9C%E6%98%AFopen%EF%BC%89%EF%BC%8C%E5%8F%AA%E6%A3%80%E6%B5%8BIP%E7%9A%84%E8%AF%9D%E4%B8%A4%E4%B8%AA%E7%BB%93%E6%9E%9C%E9%83%BD%E6%98%AFover_time%E3%80%82)
> > 如果用[https://www.vps234.com/ipchecker/检测的话，我的服务器IP都通的呀，自己ping我的服务器也是可以通的。](https://www.vps234.com/ipchecker/%E6%A3%80%E6%B5%8B%E7%9A%84%E8%AF%9D%EF%BC%8C%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8IP%E9%83%BD%E9%80%9A%E7%9A%84%E5%91%80%EF%BC%8C%E8%87%AA%E5%B7%B1ping%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B9%9F%E6%98%AF%E5%8F%AF%E4%BB%A5%E9%80%9A%E7%9A%84%E3%80%82)
> 
> 刚刚给VPS换了IP，现在好了，没有timeout了。
> 目前检测情况如下：
> 用https://ip100.info/check检测，我检测端口的话两个结果都是open，只检测IP的话两个结果都是closed。



> > > > > 请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check
> > > > 
> > > > 
> > > > 测试过了，腾讯云的是overtime，AWS的可以
> > > 
> > > 
> > > 我的ss昨天晚上开始也是一直timeout。
> > > 如果用[https://ip100.info/check检测，我检测端口的话也是这样（腾讯云结果是over_time，AWS结果是open），只检测IP的话两个结果都是over_time。](https://ip100.info/check%E6%A3%80%E6%B5%8B%EF%BC%8C%E6%88%91%E6%A3%80%E6%B5%8B%E7%AB%AF%E5%8F%A3%E7%9A%84%E8%AF%9D%E4%B9%9F%E6%98%AF%E8%BF%99%E6%A0%B7%EF%BC%88%E8%85%BE%E8%AE%AF%E4%BA%91%E7%BB%93%E6%9E%9C%E6%98%AFover_time%EF%BC%8CAWS%E7%BB%93%E6%9E%9C%E6%98%AFopen%EF%BC%89%EF%BC%8C%E5%8F%AA%E6%A3%80%E6%B5%8BIP%E7%9A%84%E8%AF%9D%E4%B8%A4%E4%B8%AA%E7%BB%93%E6%9E%9C%E9%83%BD%E6%98%AFover_time%E3%80%82)
> > > 如果用[https://www.vps234.com/ipchecker/检测的话，我的服务器IP都通的呀，自己ping我的服务器也是可以通的。](https://www.vps234.com/ipchecker/%E6%A3%80%E6%B5%8B%E7%9A%84%E8%AF%9D%EF%BC%8C%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8IP%E9%83%BD%E9%80%9A%E7%9A%84%E5%91%80%EF%BC%8C%E8%87%AA%E5%B7%B1ping%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B9%9F%E6%98%AF%E5%8F%AF%E4%BB%A5%E9%80%9A%E7%9A%84%E3%80%82)
> > 
> > 
> > 刚刚给VPS换了IP，现在好了，没有timeout了。
> > 目前检测情况如下：
> > 用[https://ip100.info/check检测，我检测端口的话两个结果都是open，只检测IP的话两个结果都是closed。](https://ip100.info/check%E6%A3%80%E6%B5%8B%EF%BC%8C%E6%88%91%E6%A3%80%E6%B5%8B%E7%AB%AF%E5%8F%A3%E7%9A%84%E8%AF%9D%E4%B8%A4%E4%B8%AA%E7%BB%93%E6%9E%9C%E9%83%BD%E6%98%AFopen%EF%BC%8C%E5%8F%AA%E6%A3%80%E6%B5%8BIP%E7%9A%84%E8%AF%9D%E4%B8%A4%E4%B8%AA%E7%BB%93%E6%9E%9C%E9%83%BD%E6%98%AFclosed%E3%80%82)
> 
> 你好，我这边还是不行，具体获取ip的方法如下：
> 在cmd输入：tracert 服务器地址->获取服务器ip
> 然后在[https://ip100.info/check检测，输入ip和端口，国内还是overtime](https://ip100.info/check%E6%A3%80%E6%B5%8B%EF%BC%8C%E8%BE%93%E5%85%A5ip%E5%92%8C%E7%AB%AF%E5%8F%A3%EF%BC%8C%E5%9B%BD%E5%86%85%E8%BF%98%E6%98%AFovertime)



> > > > 请使用这个第三方的服务测试你的服务器的连通性：https://ip100.info/check
> > > 
> > > 
> > > 测试过了，腾讯云的是overtime，AWS的可以
> > 
> > 
> > 我的ss昨天晚上开始也是一直timeout。
> > 如果用[https://ip100.info/check检测，我检测端口的话也是这样（腾讯云结果是over_time，AWS结果是open），只检测IP的话两个结果都是over_time。](https://ip100.info/check%E6%A3%80%E6%B5%8B%EF%BC%8C%E6%88%91%E6%A3%80%E6%B5%8B%E7%AB%AF%E5%8F%A3%E7%9A%84%E8%AF%9D%E4%B9%9F%E6%98%AF%E8%BF%99%E6%A0%B7%EF%BC%88%E8%85%BE%E8%AE%AF%E4%BA%91%E7%BB%93%E6%9E%9C%E6%98%AFover_time%EF%BC%8CAWS%E7%BB%93%E6%9E%9C%E6%98%AFopen%EF%BC%89%EF%BC%8C%E5%8F%AA%E6%A3%80%E6%B5%8BIP%E7%9A%84%E8%AF%9D%E4%B8%A4%E4%B8%AA%E7%BB%93%E6%9E%9C%E9%83%BD%E6%98%AFover_time%E3%80%82)
> > 如果用[https://www.vps234.com/ipchecker/检测的话，我的服务器IP都通的呀，自己ping我的服务器也是可以通的。](https://www.vps234.com/ipchecker/%E6%A3%80%E6%B5%8B%E7%9A%84%E8%AF%9D%EF%BC%8C%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8IP%E9%83%BD%E9%80%9A%E7%9A%84%E5%91%80%EF%BC%8C%E8%87%AA%E5%B7%B1ping%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B9%9F%E6%98%AF%E5%8F%AF%E4%BB%A5%E9%80%9A%E7%9A%84%E3%80%82)
> 
> 刚刚给VPS换了IP，现在好了，没有timeout了。
> 目前检测情况如下：
> 用https://ip100.info/check检测，我检测端口的话两个结果都是open，只检测IP的话两个结果都是closed。


刚刚到ss官网上重新下载了gui-config.json文件，然后给换上去了，还是timeout
![1581319369(1)](https://user-images.githubusercontent.com/40153439/74128892-3d073f80-4c19-11ea-982c-0e41f9fd943e.jpg)

**Comment by studentmain** [comment]
> 官网上重新下载了gui-config.json文件

本项目官网（https://shadowsocks.org）并没有提供gui-config.json下载或者任何类似的服务。

影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们。

**Comment by FRenzyneedhairs** [comment]
> > 官网上重新下载了gui-config.json文件
> 
> 本项目官网（ https://shadowsocks.org ）并没有提供gui-config.json下载或者任何类似的服务。
> 
> 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务。如果你是从服务提供商购买的服务，请联系他们。

好的，谢谢你
