### ISSUE TITLE
[Feature Request]建议采取措施保护配置文件

### ISSUE THREAD

**Issue by WC12366** [shadowsocks/shadowsocks-windows#2798]
前几天看到的一篇文章[https://ssr.tools/929](https://ssr.tools/929) 谷歌也搜索出了多篇类似的文章，基本都是说腾讯有游戏收集Shadowsocks配置文件，严重侵犯了用户隐私权。以后怕会报告GFW，导致梯子连不上

**Comment by chenshaoju** [comment]
这个事情有点老了：
https://www.freebuf.com/news/194724.html
https://www.solidot.org/story?sid=59369

但是目前没有办法，就算加密了配置文件，内存中一样可以读取到。

你可以选择将 Shadowsocks.exe 放到一个USB存储设备里，用的时候插上，要玩游戏了就拔下来。

**Comment by windstander** [comment]
确实是个问题。

**Comment by robot-dot-win** [comment]
> 前几天看到的一篇文章https://ssr.tools/929 谷歌也搜索出了多篇类似的文章，基本都是说腾讯有游戏收集Shadowsocks配置文件，严重侵犯了用户隐私权。以后怕会报告GFW，导致梯子连不上

如果有证据，就到法庭去告，国内告不了可以在国外告，因为腾讯是全球运营；如果没有证据。。。
