### ISSUE TITLE
关闭SS后无法访问墙外网址

### ISSUE THREAD

**Issue by CosineA** [shadowsocks/shadowsocks-windows#2799]
### Shadowsocks version / 影梭版本
4.1.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows10

### Steps you have tried / 操作步骤
家中的路由有SS插件，电脑在外边上网开着ss后，回到家关了并连上路由器，发现上不了墙外的网址(其他网址可正常访问)，例如youtube，谷歌等，但手机连接路由可正常访问，网上的方法试了很多，都没有效果

**Comment by chenshaoju** [comment]
你的路由器是工作在透明代理，还是PAC代理？

**Comment by CosineA** [comment]
> 你的路由器是工作在透明代理，还是PAC代理？

路由器是k3c，用的gfw代理模式

**Comment by shikkoku** [comment]
路由插件和本项目无关。

**Comment by shikkoku** [comment]
是不是系统代理还依然开着？手动关掉系统代理看看。Windows10的设置-网络-代理
