### ISSUE TITLE
2.5.4勾选可用统计时老是“已停止工作”

### ISSUE THREAD

**Issue by ytf4425** [shadowsocks/shadowsocks-windows#280]
[2015-08-17 08:42:59] Shadowsocks started
[2015-08-17 08:43:14] System.IO.IOException: 文件“C:\Users\Yu\AppData\Local\Temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()

**Comment by ytf4425** [comment]
然而日志会不会没有把错误写入。。
Windows7 SP1 x64

**Comment by chenshaoju** [comment]
你好，请尝试重新启动计算机，然后再试。

另外，当出现该错误的时候，请看一下任务管理器，是否有两个 ss_privoxy.exe 。

**Comment by ytf4425** [comment]
重启无效，没有两个ss_privoxy.exe ，删除后再次启动依然还是已停止工作
莫非这个错误来不及写入日志？

**Comment by chenshaoju** [comment]
从提示来看，可能什么东西阻止你访问 ss_privoxy.exe ，任务管理器里一个 ss_privoxy.exe 都没有吗？

**Comment by ytf4425** [comment]
有一个

**Comment by icylogic** [comment]
终结掉所有 ss_privoxy.exe 再启动？

**Comment by ytf4425** [comment]
终结后删除再启动问题依旧

**Comment by chenshaoju** [comment]
我也是Windows 7 x64，但是没有遇到该问题，无法复现。

![screenshot](https://cloud.githubusercontent.com/assets/515763/9296803/3a87f9b0-44c7-11e5-9afd-8a274c00a280.png)

**Comment by ytf4425** [comment]
取消可用统计后或者旧版都是没有问题的
莫非是我服务器太多？或者不可用的太多？

**Comment by icylogic** [comment]
应该是勾选统计以后触发 Reload，在 Reload 里启动 ss_privoxy 的时候有问题。

**Comment by icylogic** [comment]
你的日志里有关于 statistics 的 exception 吗

**Comment by ytf4425** [comment]
貌似没有，我重试了一遍，10:10:56出错关闭，日志里没有这个时间，10:11:20左右取消勾选又出错关闭一次，日志里就是[2015-08-17 10:11:15] Shadowsocks started
[2015-08-17 10:11:21] System.IO.IOException: 文件“C:\Users\Yu\AppData\Local\Temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()
重新启动后再无错误

**Comment by icylogic** [comment]
再无错误，是取消勾选再勾选没有问题了吗？还是依然会闪退？如果还有闪退，能否尝试一下取消然后再勾选"允许 LAN 连接"选项（就是统计下面那个选项），看一下是否会崩溃？

**Comment by ytf4425** [comment]
是取消勾选**不**勾选再次启动没有问题了
删除其他服务器（可能含有不可用连接或慢速连接）只保留当前在用的并勾选可用统计就**没有问题**了
恢复其他服务器（可能含有不可用连接或慢速连接）并勾选允许 LAN 连接和可用统计**依然有问题**
可见不是“允许 LAN 连接”的问题

**Comment by ytf4425** [comment]
要不你们试试加几个无法连接的服务器看看能不能复现

**Comment by ytf4425** [comment]
删除四个不可用的服务器之后勾选统计，崩溃，重启程序，正常了，不再出错

**Comment by icylogic** [comment]
额，允许 LAN 连接没有问题，只是勾这个会同样触发 Reload， stop 和 start ss_privoxy。

关于这个，不可用指的是什么？我自己在测试这个版本的时候确认如果在一个新的目录打开shadowsocks.exe，在第一次弹出的 Edit Servers 里直接点击 cancel，这样会在 servers 列表里保留一个 Server IP 为空的服务器，然后会崩溃。这个我在自己 repo 里修复了，下一次更新应该会合并。

**Comment by ytf4425** [comment]
不可用就是连不上呗。。比如IP超时比如端口错误比如加密方式错误

**Comment by icylogic** [comment]
连不上应该没有问题，我这里一堆连不上的服务器，还有随便编的内网 IP，都测试过了，只是会直接显示 Timed Out 而已。刚才我说的那个 Bug 只是 servers 为空的情况。

**Comment by ytf4425** [comment]
仔细排查了一下又试验了几次，是有一个域名的dns解析已经被我删了，你们可以试试添加一个不存在的二级域名、三级域名

**Comment by clowwindy** [comment]
ss_privoxy 的错误是结果，不是原因。异常退出导致 ss_privoxy 没有被正确关闭，所以下次启动的时候报错。

**Comment by ytf4425** [comment]
嗷，所以从日志分析是没啥用的咯？你试试添加一个不存在的二级域名、三级域名

**Comment by icylogic** [comment]
我尝试添加了不能解析的域名也没有报错。

**Comment by ytf4425** [comment]
添加之后重启程序，启动之前杀死所有有关进程

**Comment by ytf4425** [comment]
然后不能是解析到运营商404页面，也不能有泛域名解析
比如你试试usss.ytf4425.com

**Comment by icylogic** [comment]
好的，我复现问题了，PingReply 的  "No such host is known" Exception 没有 catch。

@clowwindy 我是紧急打一个 patch 到 master 还是在后续版本里修复

**Comment by clowwindy** [comment]
@icylogic 可以先打个 patch。
