### ISSUE TITLE
Tray icon doesn't appear upon boot or resume

### ISSUE THREAD

**Issue by HankAviator** [shadowsocks/shadowsocks-windows#2802]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 Pro 1909 18363.657

### Steps you have tried / 操作步骤
1. Set SS as Start on boot.
2. Start or resume OS.
3. ss tray icon disappears, while running in background.

### What did you expect to see? / 期望的结果
The tray icon remains

### What did you see instead? / 实际结果
The tray icon disappears

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
N/A

**Comment by chenshaoju** [comment]
测试了一下 Windows 10 1909 18363.657 ，在休眠和重启的情况下，均能正常启动并出现在任务栏托盘区。

![Screenshot](https://user-images.githubusercontent.com/515763/74428183-7ba82e80-4e93-11ea-871b-41ccd2b2731b.png)

请仔细看一下任务栏区域，是有一个透明的图标，还是根本就不出现？

**Comment by HankAviator** [comment]
在解除任务栏锁定后，调整任务栏宽度会重新显示。可能是Windows的问题。
