### ISSUE TITLE
[QUESTION] Can I use Shadowsocks on Windows XP?

### ISSUE THREAD

**Issue by xmha97** [shadowsocks/shadowsocks-windows#2804]
Hello,
Can I use Shadowsocks on Windows XP?
Is there another client for Shadowsocks that works on Windows XP?

**Comment by studentmain** [comment]
Try v2.x

**Comment by xmha97** [comment]
Ok, But it's doesn't support `chacha20-ietf-poly1305` encryption.

**Comment by studentmain** [comment]
Yes, when we dropped WinXP support (3417a984fa81dc89d984aa3fd3728e90a92d79fb at 2016/08/17), there's even no AEAD proposal (SIP004 at 2017/01/12) at that time.
