### ISSUE TITLE
最新小飞机用不了。。

### ISSUE THREAD

**Issue by 15189611** [shadowsocks/shadowsocks-windows#2805]
请问下是最近小飞机用不了？？我app上电脑上都用不了。。。然后我的服务器外部ip--->34.84.203.247 是这个，请帮忙确认下是ip问题还是小飞机问题。

**Comment by chenshaoju** [comment]
请尝试使用这个服务检查你的服务器工作是否正常：http://ip100.info/check

如果你的服务器是自己搭建的，请尝试更换IP后套个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

如果你的服务器是找机场购买的，请与你的机场服务商联系。
