### ISSUE TITLE
代理设置错误，PAC模式下系统代理设置自动跳转到全局代理

### ISSUE THREAD

**Issue by GrayXu** [shadowsocks/shadowsocks-windows#2810]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1909 18363.592

### Steps you have tried / 操作步骤
正常流程安装，代理也可以正常使用，日志无报错，也尝试了删除PAC后重新通过GFWlist更新本地PAC。

### What did you expect to see? / 期望的结果
对系统的代理设置修改正常，如无代理即关闭系统代理，PAC代理则为“自动设置代理->设置脚本”，全局代理则为“手动设置代理->使用代理服务器”

### What did you see instead? / 实际结果
在客户端使用PAC模式下，系统代理跑到全局代理状态下。切换代理模式后，系统代理设置就又可以回到正常情况。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
..

**Comment by GrayXu** [comment]
发现好像是Windows系统的问题…microsoft community有很多类似的[相关讨论](https://answers.microsoft.com/zh-hans/windows/forum/all/%E6%89%8B%E5%8A%A8%E8%AE%BE%E7%BD%AE%E4%BB%A3/e1f2b783-7187-4f08-a841-d4d98000d9fc)。。sad

**Comment by studentmain** [comment]
先标记为third party bug... 他们总是能搞出些新花样...

**Comment by GrayXu** [comment]
Solution: 安全模式下，进入注册表编辑器，删除所有含有"127.0.0.1"字段的项。
