### ISSUE TITLE
Shadowsocks被Avast報告為病毒

### ISSUE THREAD

**Issue by okudayukiko** [shadowsocks/shadowsocks-windows#2815]
Shadowsocks.exe被Avast軟件報告為IDP.Generic病毒。
![屏幕截图(83)](https://user-images.githubusercontent.com/17502357/75094284-beb97e80-55c4-11ea-9730-ca21e7c09488.png)

### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 1909

**Comment by okudayukiko** [comment]
另外Shadowsocks客戶端能否增加選擇TCP/UDP協議的功能？

**Comment by chenshaoju** [comment]
目前最新的测试显示并没有任何一款杀毒软件报毒：
https://www.virustotal.com/gui/file/4c9d8a8375bc5b86e8018e6779374bf6b22b5636efad40060fc9d36f00475767/

从提示来看，可能是你的Avast使用了某种启发式杀毒并进行了拦截，请加入白名单即可。

**Comment by okudayukiko** [comment]
> 目前最新的测试显示并没有任何一款杀毒软件报毒：
> https://www.virustotal.com/gui/file/4c9d8a8375bc5b86e8018e6779374bf6b22b5636efad40060fc9d36f00475767/
> 
> 从提示来看，可能是你的Avast使用了某种启发式杀毒并进行了拦截，请加入白名单即可。

可以了，另外建议Shadowsocks加入手动选择语言功能。

**Comment by richardalpes** [comment]
我自动升级的4.1.9.2会自己请求一些网站和端口，我在这里下载了一个，然后从头来了一次，就好了。
