### ISSUE TITLE
会有arm版本嘛

### ISSUE THREAD

**Issue by tiny1990** [shadowsocks/shadowsocks-windows#2818]
大佬们，马上surface pro x 国内上了

会考虑出 arm 平台的嘛 

买不买取决于 ss  有没有arm版本 
当然还有钱包

**Comment by studentmain** [comment]
会有，但不是现在。不过windows arm可以跑x86，直接用x86版问题不算太大。

**Comment by studentmain** [comment]
之所以不是Any CPU，是有以下组件平台相关：
privoxy，HTTP转Socks5，如果你只用Socks代理，可以先去掉给你单独编译一份
sysproxy.exe，提供设置系统代理的能力，如果你愿意手动设代理，同样可以去掉然后单独编译一份
libsscrypto，x86限定的加密库，不过现在有实验性的跨平台加密库，如果你只使用AEAD，也可以特供

**Comment by tiny1990** [comment]
> 之所以不是Any CPU，是有以下组件平台相关：
> privoxy，HTTP转Socks5，如果你只用Socks代理，可以先去掉给你单独编译一份
> sysproxy.exe，提供设置系统代理的能力，如果你愿意手动设代理，同样可以去掉然后单独编译一份
> libsscrypto，x86限定的加密库，不过现在有实验性的跨平台加密库，如果你只使用AEAD，也可以特供

感谢，感谢，等我买了 试试 x86正常不
