### ISSUE TITLE
2.5.4默认网址缺的很多啊

### ISSUE THREAD

**Issue by ahillgian** [shadowsocks/shadowsocks-windows#282]
甚至连Youtube频道的头像和banner都看不到呢...  和之前的pac文件比较下,发现缺少了ggpht.com这个网址.  除了youtube还有其他网站跟之前相比少了很多默认走代理的. 希望能添加上. 谢谢!

**Comment by clowwindy** [comment]
![image](https://cloud.githubusercontent.com/assets/1073082/9297214/461cd564-44ce-11e5-8a08-741010c1bcee.png)

mei gai guo没改过。
