### ISSUE TITLE
扫描屏幕二维码总是提示格式不无法解析，但是用mac的好像是好的

### ISSUE THREAD

**Issue by debug6699** [shadowsocks/shadowsocks-windows#2821]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win 10

### Steps you have tried / 操作步骤
扫描屏幕二维码

### What did you expect to see? / 期望的结果
自动增加服务器配置

### What did you see instead? / 实际结果
二维码格式不对，但用mac版本的可以扫

**Comment by debug6699** [comment]
我感觉跟尺寸有关，只有一种尺寸可以识别

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/75685286-402ea200-5c92-11ea-9770-66b67f6aab62.png)

试试这个
