### ISSUE TITLE
希望添加能像SSR一样改变路由模式(全局、绕过大陆、绕过大陆及局域网等)的功能

### ISSUE THREAD

**Issue by tomchristopherperez** [shadowsocks/shadowsocks-windows#2822]

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1873 https://github.com/shadowsocks/shadowsocks-windows/issues/1685 https://github.com/shadowsocks/shadowsocks-windows/issues/1358 https://github.com/shadowsocks/shadowsocks-windows/issues/1270 https://github.com/shadowsocks/shadowsocks-windows/issues/762
