### ISSUE TITLE
shadowsocks 没有记录请求日志

### ISSUE THREAD

**Issue by Kunsect** [shadowsocks/shadowsocks-windows#2823]
服务端是没有问题的，其他机子都可以上。
现在是有一台机子开了全局之后（代理设置没有问题）上不了网，只有连接服务端成功的日志，没有后续记录请求的域名记录。
PAC 模式内网可以上，外网也不行。
怀疑是其他的安全软件（公司电脑）拦截了代理请求，这个要怎么排查呢？
感谢回复。

**Comment by studentmain** [comment]
开详细记录日志

**Comment by Kunsect** [comment]
@studentmain 开了，没有记录

**Comment by studentmain** [comment]
那就是没有收到请求

**Comment by Kunsect** [comment]
@studentmain 是的，但是不知道该怎么排查起在哪个地方被拦截了

**Comment by studentmain** [comment]
事实上你能做的不多……系统代理上面发生的怪事挺多的，很多都没调查出来为什么……可以先拿switchyomega将就一下

**Comment by Kunsect** [comment]
@studentmain 感谢回复
