### ISSUE TITLE
自定义用户规则的问题

### ISSUE THREAD

**Issue by fqqdc** [shadowsocks/shadowsocks-windows#2825]
### Shadowsocks version / 影梭版本
4.1.9.2

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows10，.Net v4.0.30319

### Steps you have tried / 操作步骤
1、编辑user-rule.txt，并保存
2、重启Shadowsocks
3、浏览器访问网址

### What did you expect to see? / 期望的结果
我希望能在PAC模式下访问以下地址：`https://wikimedia.org/api/rest_v1/media/math/render/svg/20aab59b427a50d2b06bbef9cee551cd4d9a44d3`

### What did you see instead? / 实际结果
如果不编辑user-rule.txt文件，在PAC模式中无法访问，但是全局模式中可以访问
在user-rule.txt中添加`||wikimedia.org/api/rest_v1/media/math/*`，无法访问
在user-rule.txt中添加`||wikimedia.org/*`，可以访问，但是这样不符合我的需要，我只希望部分无法访问的网址通过SS访问。

**Comment by studentmain** [comment]
PAC的局限性，在HTTPS下PAC脚本只能得知域名不能得知路径

**Comment by fqqdc** [comment]
原来是这样啊，非常感谢
