### ISSUE TITLE
4.1.9.2 clowwindy PAC 失效

### ISSUE THREAD

**Issue by EricMzky** [shadowsocks/shadowsocks-windows#2827]
### Shadowsocks version / 影梭版本
4.1.9.2

手动更新PAC到本地地址，使用本地PAC，clowwindy的PAC已经找不到hub相关页面，现在该如何使用？谢谢

**Comment by studentmain** [comment]
#2766 

程序内置的PAC能够满足需求

**Comment by celeron533** [comment]
https://github.com/gfwlist/gfwlist 倒是自去年年底起就没有再更新过

**Comment by studentmain** [comment]
找到一个根本不兼容shadowsocks的shadowsocks规则集：https://github.com/Hackl0us/SS-Rule-Snippet

或许我们应该寻找替代品

**Comment by celeron533** [comment]
> 或许我们应该寻找替代品

可能直接在shadowsocks-net上做新版的filter更好一些

**Comment by studentmain** [comment]
就性能和维护的简便程度来说是的，但是使用系统PAC相比于代理层过滤对TLS支持可能更好（ss-android有类似的情况），而且可以对其他主机提供服务。

**Comment by EricMzky** [comment]
> 找到一个根本不兼容shadowsocks的shadowsocks规则集：https://github.com/Hackl0us/SS-Rule-Snippet
> 
> 或许我们应该寻找替代品

windows端的小飞机如何使用这个规则PAC导入？这个不仅仅是支持移动端吧？ 谢谢，有没有 其他可以用的好的PAC ，谢谢

**Comment by studentmain** [comment]
> windows端的小飞机如何使用这个规则PAC导入？

如我所说，这东西是

> > 根本不兼容shadowsocks的

你得写点代码或者等我写点代码把它转换成GFWList格式

**Comment by EricMzky** [comment]
> > windows端的小飞机如何使用这个规则PAC导入？
> 
> 如我所说，这东西是
> 
> > > 根本不兼容shadowsocks的
> 
> 你得写点代码或者等我写点代码把它转换成GFWList格式

嗯哼，多谢辛苦您了哈

**Comment by EricMzky** [comment]
> > windows端的小飞机如何使用这个规则PAC导入？
> 
> 如我所说，这东西是
> 
> > > 根本不兼容shadowsocks的
> 
> 你得写点代码或者等我写点代码把它转换成GFWList格式

还有一个问题，什么时候能发布一个最新集成更改过的 release的压缩包或者安装包呢。谢谢！

**Comment by studentmain** [comment]
> 什么时候

不确定，这个真的没法确定

**Comment by studentmain** [comment]
但是写个转换工具还是问题不大，只是你要每次自己转换，没有一键更新了。

**Comment by studentmain** [comment]
[index.zip](https://github.com/shadowsocks/shadowsocks-windows/files/4334100/index.zip)

里面的 index.html 就是转换工具。

**Comment by tagaga** [comment]
就已经近1个月都不能用了，所有的服务器都连不上，官网也连不上了，只是我的网络问题吗？

**Comment by caesun** [comment]
> 就已经近1个月都不能用了，所有的服务器都连不上，官网也连不上了，只是我的网络问题吗？

try close ss, del local pac.txt, and run ss again.

**Comment by studentmain** [comment]
> > 或许我们应该寻找替代品
> 
> 可能直接在shadowsocks-net上做新版的filter更好一些

好处：
- 更快（至少比跑JS快）
- 省去维护PAC脚本及其服务器的麻烦（这个理由对我来说已经足够了）

坏处：
- 作为VPN工作时（ss-android 的情况），socks服务器无法正常得知域名
- 需要自己执行域名解析以实现按IP分流
- 显然地破坏了兼容性（不过可以用ClearScript跑PAC将就一下）
