### ISSUE TITLE
禁用状态和PAC模式的图标都是灰色的, 不易区分. 建议把PAC模式换成绿色图标.

### ISSUE THREAD

**Issue by AnnDad** [shadowsocks/shadowsocks-windows#2828]
### Shadowsocks version / 影梭版本
4.1.9.2
RT

**Comment by studentmain** [comment]
顺便一提，在蓝色主题下，窗口图标可见性不佳。或许我们需要重新设计图标来同时根治这两个问题。

![图片](https://user-images.githubusercontent.com/17123090/76383779-d9298100-6354-11ea-9fb9-3c0983d8f7ce.png)

**Comment by celeron533** [comment]
> 在蓝色主题下，窗口图标可见性不佳

Option A. Contour
Option B. Add background color
Option C. Use at least  two color theme and let user to select

**Comment by studentmain** [comment]
选项B可能太像Telegram了（虽然现在就很像，ss-android 也有这毛病，公共素材小飞机……）
C代价太大，单纯的显示问题我认为还用不着这么干

**Comment by AnnDad** [comment]
那就A

**Comment by tompotter00** [comment]
建议把图标加个边，或者加些渐变色

**Comment by rolle33** [comment]
增加调色板以防止颜色的冲突

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/77531362-b2a63280-6e8a-11ea-9ced-6d12a4222753.png)
![图片](https://user-images.githubusercontent.com/17123090/77531528-fd27af00-6e8a-11ea-9862-6f155213f715.png)

用勾边也比较瞎眼……

C选项如果是自动选择倒是不错，不过得和win32 api打交道，https://docs.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-getthemesyscolorbrush

**Comment by Zhwt** [comment]
在不重新设计图标的情况下, 建议可以留一个选项来读取自定义 .ico 或者 png 文件, 像 SSR 一样, 用户可以配置使用自定义图标

**Comment by AnnDad** [comment]
> 在不重新设计图标的情况下, 建议可以留一个选项来读取自定义 .ico 或者 png 文件, 像 SSR 一样, 用户可以配置使用自定义图标

这个主意好

**Comment by lssmoon2019** [comment]
淡灰色和深灰色颜色还是很好区分的。建议不要绿色，换其他色。

**Comment by GamenRoll** [comment]
has wished new pac color for  a long long time

**Comment by database64128** [comment]
We are not planning to implement a tray icon (`NotifyIcon`) in the upcoming version 5.

**Comment by GamenRoll** [comment]
there has already been 3 colors for all the time, 
plz change the pac gray into black with white sideline (means empty inside, when it doesn't work), or
half white half blue

if you would
thanx
