### ISSUE TITLE
Support multiple proxies simultaneously 

### ISSUE THREAD

**Issue by ysn2233** [shadowsocks/shadowsocks-windows#2829]
I have multiple shadowsocks servers and  I want to use different addresses for different website respectively.  I think the client can bind these servers to different local port and start them together. Will the software is going to support this feature? 

我有多个ss服务器，希望可以同时启动绑定到不同的本地端口，我可以选择为不同的网站或者应用选择不同的代理服务器。

**Comment by studentmain** [comment]
现在你得多开程序来解决。
