### ISSUE TITLE
是否可以加入 ssh 前置代理 自动登录？

### ISSUE THREAD

**Issue by maikebing** [shadowsocks/shadowsocks-windows#2832]
由于部分账号被封， 无法访问， 只能每次打开一个 ssh进行前置代理然后才能使用ss， 可否增加一个功能， 自动登录前置 ss， 然后再pac ？

**Comment by studentmain** [comment]
盲猜，把SSH配置为插件

创建SSH隧道是ssh -Llocalport:127.0.0.1:remoteport user@server-address 来着？

**Comment by maikebing** [comment]
我是 手动登录了一个xshell  。 我买的所有 ss账号全部废了。 惆怅。

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/76699553-6434af00-66a6-11ea-9d38-131596acaf1e.png)

参数填 `-L %SS_LOCAL_PORT%:127.0.0.1:%SS_REMOTE_PORT% root@%SS_REMOTE_HOST%` 自行替换用户名，自行配置公钥认证。你得先安个OpenSSH或者putty之类的。如果提示找不到文件，把ssh.exe丢到ss目录下面。可能要把私钥一起丢过来。

**Comment by studentmain** [comment]
鉴于可以拿SSH当插件用，先won't fix

**Comment by maikebing** [comment]
感谢大神
