### ISSUE TITLE
感觉ssr客户端里那个代理绕过大陆和局域网的功能挺不错的 不知道ss能不能添加到类似功能

### ISSUE THREAD

**Issue by Godlike-Yu** [shadowsocks/shadowsocks-windows#2834]
这样的类似白名单的机制就不必每次遇到一个网站打不开还要先切换到全局看看是不是墙的问题 再编辑pac的本地规则了 感觉使用起来会方便很多

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1873 https://github.com/shadowsocks/shadowsocks-windows/issues/1685 https://github.com/shadowsocks/shadowsocks-windows/issues/1358 https://github.com/shadowsocks/shadowsocks-windows/issues/1270 https://github.com/shadowsocks/shadowsocks-windows/issues/762
