### ISSUE TITLE
[非Issue]关于在windows版使用libpcap/npcap的讨论。

### ISSUE THREAD

**Issue by ohsorry** [shadowsocks/shadowsocks-windows#2836]
使用libpcap：
1. 可以代理DNS。
2. 可以使用全局统一的URL/IP过滤，一处配置，全局使用，不再依赖繁重、低效的PAC来设置系统代理。android版目前使用ACL做过滤。[全局过滤规则的构想](https://github.com/shadowsocks/shadowsocks-android/issues/2452#issuecomment-591539755)。
3. 支持其他需要raw socket的场景如让windows支持tcp_bbr。

**Comment by studentmain** [comment]
另一个候选项是tun2socks

**Comment by ohsorry** [comment]
tun2socks不错，成功圈粉。

**Comment by studentmain** [comment]
一个可能的麻烦：这类工具工作在IP层，对上层应用使用的域名一无所知，也就无从提供域名给SOCKS服务器。

**Comment by maikebing** [comment]
我觉得能让git 通过 pac之类的技术代理， 就真的太好了。 
现有条件下太麻烦了， 国内国外不一样， 有些地方屏蔽的厉害， 或者网速太慢。 很不方便

**Comment by chenshaoju** [comment]
git之类的需要他们本身支持pac才行。

但是，如果你使用的是命令行（cmd.exe）版本的git，可以使用设置环境变量来让git走代理：
```
set http_proxy=http://127.0.0.1:1080
set https_proxy=http://127.0.0.1:1080
```

更多参考：https://gist.github.com/yougg/5d2b3353fc5e197a0917aae0b3287d64

**Comment by imgk** [comment]
> 一个可能的麻烦：这类工具工作在IP层，对上层应用使用的域名一无所知，也就无从提供域名给SOCKS服务器。（这是PAC目前少有的好处，它也在应用层）
> 
> ss-android（也可能是ss-libev，忘了）一度试图通过解析 HTTP 流和 TLS SNI 来解决这个问题，不过可以预见在 ESNI 广泛部署后，或者在使用没有实现解析器的协议时，这个方案会失效。
> 
> 另外的解决方案还包括实现一个本地 DNS 代理，对每一个域名 `n` 返回一个唯一的假 IP 地址 `i` 作为标识。当SOCKS服务器收到IP地址为 `i` 的请求时，查表得到实际的域名 `n` 。

我用 WinDivert 实现了一个这样的工具，可以作为 Windows 上的透明代理。

https://github.com/imgk/shadowsocks-windivert

**Comment by ohsorry** [comment]
WinDivert不错。只需要一个dll和一个sys驱动。能直接拦截包，而且驱动签名了。

**Comment by studentmain** [comment]
@imgk 假IP地址段可以考虑用 198.18.0.0/15 ，这个地址段被RFC2544保留，用于网络测试。

**Comment by imgk** [comment]
> @imgk 假IP地址段可以考虑用 198.18.0.0/15 ，这个地址段被RFC2544保留，用于网络测试。

目前这么用着也没什么问题，以后有必要再改吧

**Comment by maikebing** [comment]
> git之类的需要他们本身支持pac才行。
> 
> 但是，如果你使用的是命令行（cmd.exe）版本的git，可以使用设置环境变量来让git走代理：
> 
> ```
> set http_proxy=http://127.0.0.1:1080
> set https_proxy=http://127.0.0.1:1080
> ```
> 
> 更多参考：https://gist.github.com/yougg/5d2b3353fc5e197a0917aae0b3287d64

我们是不是可以考虑让 http://127.0.0.1:1080   这个端口 作为一个中间端口， 任何地方都使用 这个， 
但是 ss内部 通过支持pac  来实现让git这些 也能pac

**Comment by chenshaoju** [comment]
我估计你的要求只有SocksCap32或者Proxifier才能满足了……
