### ISSUE TITLE
4.1.92 connected timeout

### ISSUE THREAD

**Issue by superbigdog** [shadowsocks/shadowsocks-windows#2837]
### Shadowsocks version / 影梭版本
4.1.92
### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 ;
.net framework 4.7.2

### What did you expect to see? / 期望的结果
could be connected 

### What did you see instead? / 实际结果
connect timeout

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2020-03-28 20:50:58] connect to api.github.com:443
[2020-03-28 20:50:59] connect to clients1.google.com:443
[2020-03-28 20:51:00] connect to api.github.com:443
[2020-03-28 20:51:03] serverIP:serverPort timed out
[2020-03-28 20:51:03] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2020-03-28 20:51:03] connect to www.google.com:443

**Comment by Ares-cz** [comment]
请问还有可以使用的ssr一键安装脚本嘛 已经很长一段时间 ssr的登录都成问题 经常一个ip搭建好 刚刚可以登上google 一会儿就又不行了 去查ip情况 也是通的 大家又和我一样问题的嘛



在 2020-03-28 20:58:25，"superbigdog" <notifications@github.com> 写道：

Shadowsocks version / 影梭版本

4.1.92

Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows 10 ;
.net framework 4.7.2

Steps you have tried / 操作步骤
What did you expect to see? / 期望的结果

could be connected

What did you see instead? / 实际结果

connect timeout

Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor

[2020-03-28 20:50:58] connect to api.github.com:443
[2020-03-28 20:50:59] connect to clients1.google.com:443
[2020-03-28 20:51:00] connect to api.github.com:443
[2020-03-28 20:51:03] serverIP:serverPort timed out
[2020-03-28 20:51:03] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
--- 内部异常堆栈跟踪的结尾 ---
在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- 内部异常堆栈跟踪的结尾 ---
在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2020-03-28 20:51:03] connect to www.google.com:443

**Comment by chenshaoju** [comment]
@superbigdog https://ip100.info/check 请尝试使用这个第三方的服务测试一下你所使用的服务器工作是否正常，是否能从国内连接上。

@Ares-cz 请不要到处发，这儿是Shadowsocks的问题列表，不是ShadowsocksR的，这是两个不同的东西。

**Comment by superbigdog** [comment]
@chenshaoju  over_time,是我防火墙没开端口?

**Comment by superbigdog** [comment]
> @superbigdog https://ip100.info/check 请尝试使用这个第三方的服务测试一下你所使用的服务器工作是否正常，是否能从国内连接上。
> 
> @Ares-cz 请不要到处发，这儿是Shadowsocks的问题列表，不是ShadowsocksR的，这是两个不同的东西。

我检查了防火墙，防火墙没有运行。

**Comment by chenshaoju** [comment]
如果国内和国外两个都是 over_time 意味着三种可能：
1.你输入的IP或者端口不对。
2.你服务器上的SS服务没有启动。
3.你的服务器上有网络防火墙且没有允许你的端口。

**Comment by superbigdog** [comment]
> @superbigdog https://ip100.info/check 请尝试使用这个第三方的服务测试一下你所使用的服务器工作是否正常，是否能从国内连接上。
> 
> @Ares-cz 请不要到处发，这儿是Shadowsocks的问题列表，不是ShadowsocksR的，这是两个不同的东西。

我检查了防火墙，防火墙没有运行。

> 如果国内和国外两个都是 over_time 意味着三种可能：
> 1.你输入的IP或者端口不对。
> 2.你服务器上的SS服务没有启动。
> 3.你的服务器上有网络防火墙且没有允许你的端口。

1/ IP和端口是正确的，我再次检查了一遍。并且端口我重新设置了
2/ SS服务已经启动了
3/ 防火墙是关闭状态的

**Comment by chenshaoju** [comment]
请仔细检查你的服务器的配置，尤其是服务端上的`"server"`，确保IP正确或者设置为 0.0.0.0 。

因为国内外都 over_time ，意味着你的服务端有问题，而不是客户端（这儿是客户端的issue列表）。

**Comment by superbigdog** [comment]
已经定位到问题了。
一个是端口被GFW墙掉了，另一个是阿里云的服务器端口开放不在firewall设置，而是在阿里云自己控制台。
