### ISSUE TITLE
shadowsocks 4.1.9.3 non-UI Error

### ISSUE THREAD

**Issue by Zark-Y** [shadowsocks/shadowsocks-windows#2839]
Shadowsocks version / 影梭版本
4.1.9.3

Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win10，.net Framework 4.7.2

Steps you have tried / 操作步骤
安装完4.1.9.3后，运行程序

What did you expect to see? / 期望的结果
可以正常运行程序

What did you see instead? / 实际结果
无法正常使用，弹出窗口提示信息：
https://github.com/Zark-Y/Hello-World/blob/master/shadowsocks%20non-UI%20Error.PNG
![image](https://user-images.githubusercontent.com/3608762/78122221-08f11380-743f-11ea-8be2-880fb9ebe7ac.png)

Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
无

**Comment by chenshaoju** [comment]
请尝试新建一个目录，比如 D:\SS\ 然后单独将 Shadowsocks.exe 放到这个目录中，然后再试试？

**Comment by Zark-Y** [comment]
感谢您的答复，按照您说的尝试后，已经可以成功运行。谢谢你


| |
usefulmail
|
|
thisisauselessmail@163.com
|
签名由网易邮箱大师定制
On 4/1/2020 09:15，Chen Shaoju<notifications@github.com> wrote：

请尝试新建一个目录，比如 D:\SS\ 然后单独将 Shadowsocks.exe 放到这个目录中，然后再试试？

**Comment by chenshaoju** [comment]
👏
