### ISSUE TITLE
shadowsocks是否可以避免dns污染呢？

### ISSUE THREAD

**Issue by 604542720** [shadowsocks/shadowsocks-windows#284]
我试了下好像部分域名还是会被屏蔽(上海电信，其它站正常，nico，P站全局下都不能访问)。有什么简单有效的办法可以避免dns污染呢？

**Comment by icylogic** [comment]
https://github.com/clowwindy/ChinaDNS

Firefox之类的可以尝试开启远程解析 DNS。

目前没有内置 DNS ，可以去 #233 下提需求。

**Comment by chenshaoju** [comment]
在Firefox中输入： about:config ，确认后搜索 extensions.foxyproxy.socks_remote_dns ，设置为 true 即可。

![1](https://cloud.githubusercontent.com/assets/515763/9298451/64af65aa-44e2-11e5-950f-38277c5e58cd.png)

如果你想要搭建一个DNS服务器，提供远程解析，可以使用DNS2SOCKS：
http://sourceforge.net/projects/dns2socks/

**Comment by chenshaoju** [comment]
修正，应该是 network.proxy.socks_remote_dns ，不是 extensions.foxyproxy.socks_remote_dns ，这个是我的另一个插件的。

![2](https://cloud.githubusercontent.com/assets/515763/9298473/de86d3a4-44e2-11e5-9ce5-7b6ee621e1fb.png)

**Comment by clowwindy** [comment]
设置使用 HTTP 代理即可。

**Comment by bigZ-again** [comment]
shadowsocks-windows 在“全局模式”下，不会出现 DNS 污染的情况。
但在PAC模式下，当访问的网址不在PAC list中时，不可避免的会受到DNS污染的影响。
比如我在PAC模式下，Gmail基本正常，但是邮件中嵌入的图片无法正常显示，估计是某些被污染的google域名不再PAC list中，这时强制转换到全局模式下，问题得到解决。
