### ISSUE TITLE
4.1.9.3 autostart issue

### ISSUE THREAD

**Issue by vanyaindigo** [shadowsocks/shadowsocks-windows#2841]
The app doesn't start with the system while autostart is switch on.

**Comment by chenshaoju** [comment]
Please check registry `\HKCU\Software\Microsoft\Windows\CurrentVersion\Run`,There is a `Shadowsocks_xxxxxxxx` entry?

**Comment by vanyaindigo** [comment]
Yes, there is such entry

**Comment by chenshaoju** [comment]
I tested on my Windows 10 1909 (18363.720), But it can't be repeated.

It's your computer install some computer manager software, Like 360 Security Center or Tencent PC Manager?

**Comment by vanyaindigo** [comment]
Nothing installed and with ver. 4.1.9.2 all was fine.

**Comment by chenshaoju** [comment]
Odd, Please quit Shadowsocks,Open registry and delete `Shadowsocks_xxxxxx` from `\HKCU\Software\Microsoft\Windows\CurrentVersion\Run`, And start Shadowsocks again and set it to auto start again?

**Comment by vanyaindigo** [comment]
Still not starting

**Comment by chenshaoju** [comment]
This should not happen. 

If you manually create an entry name something else like `test` with your Shadowsocks path, It's can work?

example:
![image](https://user-images.githubusercontent.com/515763/78229745-f50ee580-7502-11ea-9814-d727f62a2c04.png)

**Comment by vanyaindigo** [comment]
I think this is somehow refer with new localization

**Comment by chenshaoju** [comment]
What is your operating system language or location settings?

**Comment by vanyaindigo** [comment]
Russian

**Comment by studentmain** [comment]
> Russian, is it possible to switch back to english?

Help-> Write translate template, then delete Russian column in generated file.

**Comment by studentmain** [comment]
Is there anything in logfile?

**Comment by vanyaindigo** [comment]
> Is there anything in logfile?

Nothing

**Comment by celeron533** [comment]
tag as `bug` for tracking.
It is possible that this new binary release is not trusted by the anti-virus and does not allowed to be added in startup?

**Comment by vanyaindigo** [comment]
There is an error in system log:
```
Контейнер ошибки , тип 0
Имя события: CLR20r3
Отклик: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: Shadowsocks.exe
P2: 4.1.9.3
P3: 5e835a75
P4: mscorlib
P5: 4.8.4150.0
P6: 5e176d21
P7: 1693
P8: 12e
P9: System.UnauthorizedAccess
P10: 
```

**Comment by vanyaindigo** [comment]
And another:
```
Приложение: Shadowsocks.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.UnauthorizedAccessException
   в System.IO.__Error.WinIOError(Int32, System.String)
   в System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   в System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   в System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)
   в System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean)
   в System.IO.File.InternalWriteAllText(System.String, System.String, System.Text.Encoding, Boolean)
   в System.IO.File.WriteAllText(System.String, System.String)
   в Shadowsocks.Model.NLogConfig.TouchAndApplyNLogConfig()
   в Shadowsocks.Program.Main(System.String[])

```
Имя сбойного приложения: Shadowsocks.exe, версия: 4.1.9.3, метка времени: 0x5e835a75
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.18362.719, метка времени: 0x4061c730
Код исключения: 0xe0434352
Смещение ошибки: 0x00114192
Идентификатор сбойного процесса: 0x1280
Время запуска сбойного приложения: 0x01d608cae86c08b2
Путь сбойного приложения: E:\Downloads\Shadowsocks\Shadowsocks.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: 19675f09-69a5-4833-b542-d9cafa01c016
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
```
```

**Comment by studentmain** [comment]
I think problem is in NLog

**Comment by snakefoot** [comment]
The exception comes from your own code:

https://github.com/shadowsocks/shadowsocks-windows/blob/6893af10b5e5da9391e041c705abade9716e55f4/shadowsocks-csharp/Model/NlogConfig.cs#L109-L116

Maybe add some exception handling like this:

```c#
 public static void TouchAndApplyNLogConfig() 
 { 
     try
     {
         if (File.Exists(NLOG_CONFIG_FILE_NAME))
             return;   // NLog.config exists, and has already been loaded

         File.WriteAllText(NLOG_CONFIG_FILE_NAME, Properties.Resources.NLog_config);
     }
     catch (Exception ex)
     {
         NLog.Common.InternalLogger.Error(ex, "Failed to setup default NLog.config: {0}", NLOG_CONFIG_FILE_NAME)
         return;
     }

     LogManager.LoadConfiguration(NLOG_CONFIG_FILE_NAME); // Load the new config-file
 } 
```

**Comment by ningsibuqu** [comment]
我也有一样的问题，Windows 10 1809 x64

**Comment by xfspace** [comment]
Hello, 

> OS 名称:          Microsoft Windows 10 专业版 Insider Preview
> OS 版本:          10.0.19592 暂缺 Build 19592
> 系统区域设置:     zh-cn;中文(中国)

Have the same problem.

**Comment by billysingo** [comment]
same problem on windows10x64 1903

**Comment by chenshaoju** [comment]
Sorry for my fault, I'm using the wrong version.

The 4.1.9.3 have some issue, It's unable auto-start.

```
错误应用程序名称: Shadowsocks.exe，版本: 4.1.9.3，时间戳: 0x5e835a75
错误模块名称: KERNELBASE.dll，版本: 10.0.18362.719，时间戳: 0x4061c730
异常代码: 0xe0434352
错误偏移量: 0x00114192
错误进程 ID: 0x2a10
错误应用程序启动时间: 0x01d6097a24e57d83
错误应用程序路径: C:\Software\Shadowsocks\Shadowsocks.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: b8fa373a-eca2-4f99-9bfc-fc6d25fc2ec2
错误程序包全名: 
错误程序包相对应用程序 ID: 
```

```
应用程序: Shadowsocks.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.UnauthorizedAccessException
   在 System.IO.__Error.WinIOError(Int32, System.String)
   在 System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   在 System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   在 System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)
   在 System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean)
   在 System.IO.File.InternalWriteAllText(System.String, System.String, System.Text.Encoding, Boolean)
   在 System.IO.File.WriteAllText(System.String, System.String)
   在 Shadowsocks.Model.NLogConfig.TouchAndApplyNLogConfig()
   在 Shadowsocks.Program.Main(System.String[])
```

```
故障存储段 1613589829736366270，类型 5
事件名称: CLR20r3
响应: 不可用
Cab ID: 0

问题签名:
P1: Shadowsocks.exe
P2: 4.1.9.3
P3: 5e835a75
P4: mscorlib
P5: 4.8.4150.0
P6: 5e176d21
P7: 1693
P8: 12e
P9: System.UnauthorizedAccess
P10: 
```

**Comment by basten1899** [comment]
the same problem

**Comment by celeron533** [comment]
Hi All,
Just need to confirm, manual start still works when auto start has problem?

**Comment by chenshaoju** [comment]
yes

**Comment by studentmain** [comment]
https://www.codeproject.com/Questions/262575/Start-on-windows-logon-results-in-System-Unauthori


> Does your app open or create a file using relative path?
> If so, the cause of the problem is a difference of current directory.
> 
> If you run the app yourself, the current directory is the directory where the app is located.
> 
> If you use either HKLM\...\Run or HKCU\...\Run the current directory is the root of your login account.
> 
> The solution: set a proper current directory before accessing any file or always use absolute path.

**Comment by studentmain** [comment]
move this line to the top of Main() may solve our problem

https://github.com/shadowsocks/shadowsocks-windows/blob/6893af10b5e5da9391e041c705abade9716e55f4/shadowsocks-csharp/Program.cs#L85

**Comment by ningsibuqu** [comment]
既然修复了，可以发个版本吗

**Comment by studentmain** [comment]
@ningsibuqu  https://ci.appveyor.com/project/celeron533/shadowsocks-windows-3j4p4/builds/31946869/job/r9wyrr944ykga4el/artifacts try this

**Comment by ningsibuqu** [comment]
> @ningsibuqu https://ci.appveyor.com/project/celeron533/shadowsocks-windows-3j4p4/builds/31946869/job/r9wyrr944ykga4el/artifacts try this

这个版本可以开机启动了，谢谢你

**Comment by vanyaindigo** [comment]
After all done check also verbose logging, there may to be issues.

**Comment by studentmain** [comment]
yes, verbose logging is too verbose in release config.

**Comment by celeron533** [comment]
I'll adjust the "verbose" from `Trace` to `Debug`

```
config.nLogConfig.SetLogLevel(config.isVerboseLogging? NLogConfig.LogLevel.Trace: NLogConfig.LogLevel.Info);
```

Then prepare a new release with autostart code fix

**Comment by studentmain** [comment]
> 
> 
> I'll adjust the "verbose" from `Trace` to `Debug`
> 
> ```
> config.nLogConfig.SetLogLevel(config.isVerboseLogging? NLogConfig.LogLevel.Trace: NLogConfig.LogLevel.Info);
> ```
> 
> Then prepare a new release with autostart code fix

Some log is at wrong level, like AEADEncryptor's internal state logging, they're at Debug level.

I suggest use this, in Debug config, log level is Trace, in Release it is Debug. Also adjusted some log's level.

 [0001-adjust-log-level.zip](https://github.com/shadowsocks/shadowsocks-windows/files/4442295/0001-adjust-log-level.zip) (My computer is broken, I'm working on public device, so I can't push at this moment...)

**Comment by celeron533** [comment]
Hi @studentmain , your patch has been applied on 23ce58aa34103051e514b38834a9f3dc84331e88 .
`LogForm.cs` is not changed. I think it is useful for normal end-user

**Comment by studentmain** [comment]
@celeron533 got it

**Comment by vanyaindigo** [comment]
All is working with 4.1.10.0. Many thanks!
