### ISSUE TITLE
提供SOCKS4代理或者ss-tunnel

### ISSUE THREAD

**Issue by zhangjint5** [shadowsocks/shadowsocks-windows#2842]
提供SOCKS4代理以供socat使用，或者提供ss-tunnel

原内容：

shadowsocks-windows 使用 privoxy 提供进行 Socks5 转换 http proxy 功能这本身很好，但是能不能不要共用一个端口，或者增加一个 privoxy 的开关？
共用一个端口浏览器是没啥问题，但是还是会造成有些软件的兼容性问题！
例如 socat ，调用影梭的 socks5 死活不能工作，只能调用 http proxy 来使用！

**Comment by studentmain** [comment]
这样，我明天给你专门编译一份只有socks5代理的，你看看能用不。

当然，你如果有wireshark，抓包看看发生了什么那更好了。

**Comment by celeron533** [comment]
@studentmain 我也有把http和socks拆开的想法
更进一步，pac也能丢到http的那个监听端口上，毕竟协议相同

**Comment by studentmain** [comment]
拆开倒不用，毕竟一个端口所有服务的使用习惯已经形成了……

**Comment by studentmain** [comment]
[Shadowsocks-4.1.9.3-test-unofficial.zip](https://github.com/shadowsocks/shadowsocks-windows/files/4422197/Shadowsocks-4.1.9.3-test-unofficial.zip)


试试这个，把pac和http代理简单阉割了。

**Comment by zhangjint5** [comment]
> 这样，我明天给你专门编译一份只有socks5代理的，你看看能用不。
> 
> 当然，你如果有wireshark，抓包看看发生了什么那更好了。

感谢回复！重新研究发现问题所在！

socat使用的协议是 SOCKS4！而 SS 和 SSR 测试只有 SOCKS5 可以链接成功！

另外测试成功的 v2rayN 和 passwall 软路由他们 SOCKS 4和5都可以链接！

##################################################

使用 socat 是为了实现 ss-tunnel 的功能
socat TCP4-LISTEN:<本地端口>,reuseaddr,fork SOCKS:<代理服务器IP>:<远程地址>:<远程端口>,socksport=<代理服务器端口>

如果 ss 也能像 ssr 那样内置 ss-tunnel 功能就更好了:)

感谢！
