### ISSUE TITLE
更新到4.1.9.3后无法开机启动

### ISSUE THREAD

**Issue by freakinyy** [shadowsocks/shadowsocks-windows#2844]
### Shadowsocks version / 影梭版本
4.1.9.3

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
windows10专业版1909，.NET Framework 3.5

### Steps you have tried / 操作步骤
1）4.1.9.2版本的C:\proxy\shadowsocks\0\shadowsocks.exe开启开机启动
2）将4.1.9.2版本的C:\proxy\shadowsocks\0\shadowsocks.exe替换为4.1.9.3
3）删除C:\proxy\shadowsocks\0\下除shadowsocks.exe的所有文件后，重新配置，开启开机启动
4）将4.1.9.3版本的C:\proxy\shadowsocks\0\shadowsocks.exe替换为4.1.9.2

### What did you expect to see? / 期望的结果
1）2）3）4）开机时可以启动

### What did you see instead? / 实际结果
1）开机时可以启动
2）开机时无法启动
3）开机时无法启动
4）开机时可以启动

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
{
  "version": "4.1.9.3",
  "configs": [
    {
      "server": "xxx_server",
      "server_port": xxx,
      "password": "xxx",
      "method": "rc4-md5",
      "plugin": "../v2ray-plugin/v2ray-plugin.exe",
      "plugin_opts": "host=cloudflare.com",
      "plugin_args": "",
      "remarks": "xxx",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 2,
  "global": false,
  "enabled": false,
  "shareOverLan": true,
  "isDefault": false,
  "isIPv6Enabled": false,
  "localPort": 1080,
  "portableMode": true,
  "showPluginOutput": false,
  "pacUrl": null,
  "gfwListUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}

**Comment by studentmain** [comment]
#2841
