### ISSUE TITLE
使用obfs-local报错

### ISSUE THREAD

**Issue by ACDC5** [shadowsocks/shadowsocks-windows#2845]
ss版本为4.1.9.3
点击应用或者启动程序的时候就会报这个错误。
![image](https://user-images.githubusercontent.com/43377515/78470604-78c40e80-775d-11ea-861c-79cd6d77197d.png)

android 端的最新客户端配置了插件后就无法访问外网了，请问是我配置错了吗？
![微信图片_20200405165657](https://user-images.githubusercontent.com/43377515/78470824-dc9b0700-775e-11ea-9102-560be996d6ce.png)

请问除了obfs-local还有别的混淆插件吗？ 谢谢

**Comment by chenshaoju** [comment]
你双击 obfs-local.exe 能打开吗？这个看起来很像被你的安全软件给阻止了。

有：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by ACDC5** [comment]
是的双击之后打不开。我电脑除了win10自带的安全中心 没有别的安全软件了。
安全中心也没有给类似的警告:
![image](https://user-images.githubusercontent.com/43377515/78502073-ba6eac80-7791-11ea-8e3b-b804bd13f85c.png)

**Comment by chenshaoju** [comment]
请尝试启动命令提示符（cmd.exe），进入 obfs-local.exe 所在的目录，然后执行：`obfs-local.exe`，能否看到如下图所示的帮助信息？

![image](https://user-images.githubusercontent.com/515763/78521377-3998ca80-77fc-11ea-887a-19ccdb46682c.png)

**Comment by ACDC5** [comment]
可以看到
![image](https://user-images.githubusercontent.com/43377515/78532302-93f45400-7819-11ea-85fa-e9c43d49d04b.png)

**Comment by chenshaoju** [comment]
看起来没问题，再试一下？

**Comment by ACDC5** [comment]
win10现在配置完后确认没有弹出报错信息了，估计是在填路径的时候没有加.exe；
不过配置完后上不了网了：

![微信图片_20200407095123](https://user-images.githubusercontent.com/43377515/78621528-66f57f00-78b5-11ea-9186-43f0266cfbd6.png)

**Comment by chenshaoju** [comment]
这意味着你的配置可能有误，请仔细检查IP、端口、密码、加密方式、插件选项。

比如obfs=http还是obfs=tls，请结合服务端进行检查。

**Comment by ACDC5** [comment]
好的，谢谢
