### ISSUE TITLE
Linux命令行和其他操作系统版本的实现大家有考虑过嘛？

### ISSUE THREAD

**Issue by maikebing** [shadowsocks/shadowsocks-windows#2847]
### What did you expect to see? / 期望的结果
无论在Linux或是Windows 是否考虑过以服务方式运行？或者命令行的方式？ 
或者说 把 现在的UI  拆开？我记得 之前有一个 issue 提到过这个!

**Comment by maikebing** [comment]
@studentmain  @celeron533

**Comment by chenshaoju** [comment]
Linux：https://github.com/shadowsocks/shadowsocks-libev
MacOS：https://github.com/shadowsocks/ShadowsocksX-NG

**Comment by celeron533** [comment]
最简核心可以无GUI运行那是最好的了，就像v2ray核心搭配各种UI一样。
隔壁 https://github.com/shadowsocks/shadowsocks-net 已经在net core上的实现

**Comment by ohsorry** [comment]
速来围观。

**Comment by maikebing** [comment]
这个项目才注意到。

**Comment by ohsorry** [comment]
来看看吧，我为了可玩性做了些设计，windows端以后可以[配合libpcap](https://github.com/shadowsocks/shadowsocks-windows/issues/2836)，花点时间还是可以写一个即小巧又强大的ss的。

**Comment by nerekihs** [comment]
[https://github.com/shadowsocks/shadowsocks-libev#windows-mingw](https://github.com/shadowsocks/shadowsocks-libev#windows-mingw)
This is a ss-server and ss-local core written in pure C. 
Why don't you just simple compile and make this according to your platform.

**Comment by maikebing** [comment]
虽然我非常熟悉C语言和linux 下的编程， 但是我更希望 shadowsocks-windows  能真正的跨平台， 实现真正完全跨平台。 理由很简单， 为了让.Net 更伟大。

**Comment by a764934018** [comment]
不是有shadowsocks-libev么

**Comment by hanhongju** [comment]
![图片](https://user-images.githubusercontent.com/63781648/85929494-f83e2580-b8e7-11ea-9195-a1b29877cace.png)

**Comment by hanhongju** [comment]
#shadowsocks客户端使用脚本@Debian 10
#安装shadowsocks
apt      update
apt      install     -y    shadowsocks-libev  net-tools
#写入服务器信息
echo   '
{
  "server": "<serverdomain>",
  "server_port": 10086,
  "local_port": 9000,
  "password": "lllll",
  "timeout": 60,
  "method": "aes-256-gcm"
}
'         >        /etc/shadowsocks-libev/root.json
#启动服务
systemctl   enable      shadowsocks-libev-local@root
systemctl   restart     shadowsocks-libev-local@root
sleep 5s
systemctl   status      shadowsocks-libev-local@root
netstat  -plunt | grep 'ss-local'
#回显ss-local监听端口

**Comment by database64128** [comment]
`shadowsocks-cli` is now available for Linux and Windows. It can be used as Shadowsocks client and server config converter. Get artifacts from https://github.com/shadowsocks/shadowsocks-windows/actions/runs/627431775.

Currently the client is limited to the legacy backend and SOCKS5. The converter is feature complete and supports conversion between ss:// links, SIP008 JSON, and V2Ray JSON.

- CPU: i5-7400
- OS: Arch Linux 5.11.1-arch1-1
- Protocol: Shadowsocks AEAD AES-256-GCM & ChaCha20-Poly1305
- Setup: loopback proxychains-ng TCP single connection

| AES-256-GCM | ss-rust client | ss-cli client |
| --- | ---: | ---: |
| ss-rust server | 8.68Gbps | 4.88Gbps |

| ChaCha20-Poly1305 | ss-rust client | ss-cli client |
| --- | ---: | ---: |
| ss-rust server | 6.75Gbps | 3.31Gbps |
