### ISSUE TITLE
4.1.9.2升级到4.1.9.3后无法正常开机启动

### ISSUE THREAD

**Issue by Eyn-C** [shadowsocks/shadowsocks-windows#2848]
### Shadowsocks version / 影梭版本
4.1.9.3

### Environment (Operating system, .NET Framework, etc) / 
Windows 10 Workstation, .NET Framework OK

### Steps you have tried / 操作步骤
通过客户端正常升级到4.1.9.3版本

### What did you expect to see? / 期望的结果
工作正常，开机登录后自动启动客户端。

### What did you see instead? / 实际结果
无法正常开机启动，须手动启动。尚未尝试以手动添加服务或计划任务的形式设置开机启动项。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
沿用上个版本，正常无须提供。

**Comment by chenshaoju** [comment]
此问题已知道，且已修复。

请尝试此版本：https://github.com/shadowsocks/shadowsocks-windows/issues/2841#issuecomment-609375382

**Comment by Eyn-C** [comment]
> 此问题已知道，且已修复。
> 
> 请尝试此版本：[#2841 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2841#issuecomment-609375382)

谢谢告知！
