### ISSUE TITLE
4.1.9.2版本的PAC不正常工作

### ISSUE THREAD

**Issue by mikifuns** [shadowsocks/shadowsocks-windows#2849]
### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows10

### Steps you have tried / 操作步骤
我从4.1.2升级到了4.1.9.2（关闭程序，替换文件过去，启动程序），发现Chrome81，Firefox 57dev Edge以及其他第三方软件在pac模式下无法工作。检查系统设置后发现正常。设定为全局后正常。重置浏览器重装未解决，遂怀疑是版本问题，降级后恢复正常。

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
配置文件未涉及更改，且升级前降级后都正常，遂排除配置文件问题

压缩包信息
Shadowsocks.exe
MD5
A564B74220352817C80DC097342F5338
SHA-1
BBB9F9251C16B311C6C1B4A18F493EC48B6849F2
SHA-256
4C9D8A8375BC5B86E8018E6779374BF6B22B5636EFAD40060FC9D36F00475767
SHA-512
09D84508C6DC1037CCCAE626E6F44DC0F8FA4CB011E625F38DB04FF610F6FA08C378858462376AB0FC6EE4A52E51BF2B888E9FFD6B4DAD13EABD4261BE88E14F

**Comment by chenshaoju** [comment]
升级后请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后右击任务栏托盘区的纸飞机小图标，选择`PAC`，再点击`从GFWList更新本地PAC`即可。
