### ISSUE TITLE
2.5.4 win10 KERNELBASE.dll

### ISSUE THREAD

**Issue by bigbird1985** [shadowsocks/shadowsocks-windows#285]
错误应用程序名称: Shadowsocks.exe，版本: 2.5.4.0，时间戳: 0x55d16120
错误模块名称: KERNELBASE.dll，版本: 10.0.10240.16384，时间戳: 0x559f3b2a
异常代码: 0xe0434352
错误偏移量: 0x000b3e28
错误进程 ID: 0x3514
错误应用程序启动时间: 0x01d0d8a2763ddfd0
错误应用程序路径: C:\Users\linhong.BEINGMATE\Downloads\Shadowsocks-win-dotnet4.0-2.0.11\Shadowsocks.exe
错误模块路径: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
报告 ID: 09ba1b1a-ecf3-42e3-a12b-5ca57713692b
错误程序包全名: 
错误程序包相对应用程序 ID: 

应用程序: Shadowsocks.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.Net.NetworkInformation.PingException
堆栈:
   在 System.Net.NetworkInformation.Ping.Send(System.String, Int32, Byte[], System.Net.NetworkInformation.PingOptions)
   在 System.Net.NetworkInformation.Ping.Send(System.String, Int32)
   在 Shadowsocks.Controller.AvailabilityStatistics.Evaluate(System.Object)
   在 System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.TimerQueueTimer.CallCallback()
   在 System.Threading.TimerQueueTimer.Fire()
   在 System.Threading.TimerQueue.FireNextTimers()
   在 System.Threading.TimerQueue.AppDomainTimerCallback()

麻烦帮助看一下, 非常感谢!

**Comment by icylogic** [comment]
在刚才的 Pull Request 应该解决了, https://github.com/shadowsocks/shadowsocks-windows/pull/283

**Comment by bigbird1985** [comment]
看起来是已经解决了. 谢谢.
