### ISSUE TITLE
间断性出现不能正常使用，怀疑是没有读取pac文件

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-windows#2852]
Shadowsocks version / 影梭版本:
4.1.9.2

 Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）:
Window10,PAC模式,开机自动启动。
 
Steps you have tried / 操作步骤:
访问youtube。

What did you expect to see? 期望的结果：
正常打开。

What did you see instead? / 实际结果：
打开网页没有响应，一直等待。查看ss客户端日志，未出现youtube.com等网址跳动信息。重启ss客户端后恢复正常。过一小时时间不等又出现同样问题。在不能访问的情况下，马上切换为全局代理，则正常打开youtube网页。

Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）：
{
  "version": "4.1.9.2",
  "configs": [
    {
      "server": "（这里是一个域名网址）",
      "server_port": 443,
      "password": "（设置的密码）",
      "method": "aes-256-gcm",
      "plugin": "v2ray-plugin_windows_amd64",
      "plugin_opts": "tls;host=（这里是一个域名网址）",
      "plugin_args": "",
      "remarks": "LA",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": true,
  "shareOverLan": true,
  "isDefault": false,
  "isIPv6Enabled": false,
  "localPort": 1080,
  "portableMode": true,
  "showPluginOutput": false,
  "pacUrl": null,
  "gfwListUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": true,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}

**Comment by chenshaoju** [comment]
此问题似乎无解，但是有人能解决，请尝试从此处寻找线索：https://github.com/shadowsocks/shadowsocks-windows/issues/2732

**Comment by lssmoon2019** [comment]
我是公司办公室的新买的联想电脑，windows10系统出现的这个问题。但是家里的的组装台式机也是windows10,版本都一样却一切正常。

**Comment by lssmoon2019** [comment]
Windows10 打开系统-代理设置里，正常使用时脚本地址是【http://127.0.0.1:1080/pac?hash=YblyR-05MT2UzJktppo1fQ2&secret=UaPfBeuDyIwiNQN9-X_w3FbZ3f3HyKN7RvXBhGR6-501】，过一会儿不可用时查看代理，脚本地址变成了【http://127.0.0.1:21998/PacProxyScript.pac/?t=1587370156634】。很是奇怪！！

**Comment by lssmoon2019** [comment]
> 
> 
> 此问题似乎无解，但是有人能解决，请尝试从此处寻找线索：#2732

我看到了你发的这个链接，有的说是公司的电脑出现这个问题。家里的电脑却一切正常。我也这个情况。公司联想台式机，附加安的联想杀毒软件都删了的。
