### ISSUE TITLE
代理突然不能使用，PAC文件更新失败

### ISSUE THREAD

**Issue by GNY001** [shadowsocks/shadowsocks-windows#2854]
### Shadowsocks version / 影梭版本
：4.1.10.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 7

### Steps you have tried / 操作步骤
前几日使用的好好地，今天突然就不能连接Youtube之类的网站，我尝试从代理商获取新的服务器地址，但更新PAC文件一直失败
手机能使用代理，电脑端不行
### What did you expect to see? / 期望的结果

能恢复代理正常使用
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
  --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
2020-04-18 01:23:50.7572|WARN|Shadowsocks.View.MenuViewController|System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
2020-04-18 01:23:50.7572|WARN|Shadowsocks.View.MenuViewController|System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
2020-04-18 01:23:50.7762|WARN|Shadowsocks.View.MenuViewController|System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
2020-04-18 01:23:50.7762|WARN|Shadowsocks.View.MenuViewController|System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()

**Comment by GNY001** [comment]
![image](https://user-images.githubusercontent.com/63871436/79597809-83938180-8115-11ea-9ab8-4e07c726fc43.png)
wocha我查询了一下IP，有点令我迷惑

**Comment by zazitufu** [comment]
请教一下如何使用订阅地址？找不到输入的地方

**Comment by chenshaoju** [comment]
这意味着你的服务器被墙了。

**Comment by GNY001** [comment]
> ~这意味着你的服务器被墙了。~
> 
> 这意味着你的服务器可能有问题，比如网络防火墙可能屏蔽了所有的访问。

那我应该先检查自己网络防火墙还是找代理商解决问题？我电脑可以正常上网打游戏就是不能链接代理

**Comment by chenshaoju** [comment]
如果你的服务器是是自己搭的，请尝试检查你的服务器状态。

如果你的服务器是找SS服务商（机场）租用的，请与你的机场服务上联系。

如果你是找的免费的，这意味着可能失效了，请换一个。

**Comment by GNY001** [comment]
> 请教一下如何使用订阅地址？找不到输入的地方
我是他们直接发送一个二维码就自动填写了

**Comment by GNY001** [comment]
> 如果你的服务器是是自己搭的，请尝试检查你的服务器状态。
> 
> 如果你的服务器是找SS服务商（机场）租用的，请与你的机场服务上联系。
> 
> 如果你是找的免费的，这意味着可能失效了，请换一个。

emmm，我手机和电脑是使用同一账号和配置，但就是电脑不能使用，使用clash for Windows也出现不能切换节点状况

**Comment by GNY001** [comment]
> 如果你的服务器是是自己搭的，请尝试检查你的服务器状态。
> 
> 如果你的服务器是找SS服务商（机场）租用的，请与你的机场服务上联系。
> 
> 如果你是找的免费的，这意味着可能失效了，请换一个。

我现在使用了另一台PC测试发现另一台PC可以正常使用代理，但是原有的电脑关闭了防火墙，依旧不能更新PAC文件一直显示失败

**Comment by GreatV** [comment]
我也出现同样的问题，手机端是好的，pc端不行，手机端使用的ip地址，pc端使用的是域名，最后发现是域名忘了续费导致解析异常，解析到了错误的ip地址。

**Comment by lssmoon2019** [comment]
Windows10 打开系统-代理设置里，正常使用时脚本地址是【http://127.0.0.1:1080/pac?hash=YblyR-05MT2UzJktppo1fQ2&secret=UaPfBeuDyIwiNQN9-X_w3FbZ3f3HyKN7RvXBhGR6-501】，过一会儿不可用时查看代理，脚本地址变成了【http://127.0.0.1:21998/PacProxyScript.pac/?t=1587370156634】。很是奇怪！！
