### ISSUE TITLE
ShadowSocks only focuses on browsers or the whole network?

### ISSUE THREAD

**Issue by ShadowSocks12** [shadowsocks/shadowsocks-windows#2856]
Hi Does ShadowSocks only focuse on browsers or the whole network?
I mean is it only for browsers?
I am asking this because I have read this https://www.tipsforchina.com/how-to-setup-a-fast-shadowsocks-server-on-vultr-vps-the-easy-way.html The “Limited support” Section I mean.
and Also because of this: When I downloaded Windscribe VPN to my desktop, it shows my real IP instead of ShadowSocks IP although ShadowSocks was on.
Thank You Very Much.

**Comment by chenshaoju** [comment]
Is the software need support PAC ( https://en.wikipedia.org/wiki/Proxy_auto-config ) or can load proxy config from system.

**Comment by ShadowSocks12** [comment]
I am sorry sir, but can you please give me the summary of what is written in that wiki page?

**Comment by studentmain** [comment]
shadowsocks-windows is only a proxy server, not a VPN. That means it can't take over your network connection by itself. We set system-wide proxy server automatically, browsers and some other programs are following this config (in most situation), but not all program.

You can try Outline-Client, it works like traditional VPN and use shadowsocks protocol.

**Comment by vanyaindigo** [comment]
You can try Proxifier as system-wide VPN with Shadowsocks.

**Comment by ShadowSocks12** [comment]
Which one is better outline VPN or ShadowSocks Proxy?

**Comment by vanyaindigo** [comment]
As for me I don't trust Outline

**Comment by ShadowSocks12** [comment]
Why?

**Comment by vanyaindigo** [comment]
They collect some personal data

**Comment by ShadowSocks12** [comment]
Thank You Sir, definitely I won't use it,
I am currently using Windscribe VPN with shadowsocks by selecting (Auto-Detect) in Windscribe.
![image](https://user-images.githubusercontent.com/63942376/79697700-c330a980-828c-11ea-8383-00316fab8315.png)
