### ISSUE TITLE
download后怎么安装？

### ISSUE THREAD

**Issue by eastbr00k** [shadowsocks/shadowsocks-windows#2859]

**Comment by studentmain** [comment]
解压直接跑，不用安装

**Comment by eastbr00k** [comment]
> 
> 
> 解压直接跑，不用安装

跑哪个啊，抱歉不太懂

**Comment by studentmain** [comment]
不要直接下载源代码，去release页面下载编译好的：https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by eastbr00k** [comment]
嗷嗷整好了！后面自己买个服务器就行对吧？

**Comment by studentmain** [comment]
对，当然那不是这个项目的覆盖范围了。记得加密用aes-256-gcm或者chacha20-ietf-poly1305，如果教程推荐你用aes-256-cfb，那是教程太旧。端口号不要用8388。
