### ISSUE TITLE
2.5.4频繁崩溃

### ISSUE THREAD

**Issue by logtee** [shadowsocks/shadowsocks-windows#286]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	Shadowsocks.exe
  问题签名 02:	2.5.4.0
  问题签名 03:	55d16120
  问题签名 04:	System
  问题签名 05:	4.0.30319.34238
  问题签名 06:	53e450ed
  问题签名 07:	1eb8
  问题签名 08:	12
  问题签名 09:	EHUV40BMNNYOS3MGFCGHJZ0FLIBLBASQ
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by icylogic** [comment]
shadowsocks.log 里是否有日志？开启了 Availability Statistics 吗

**Comment by logtee** [comment]
[2015-08-17 12:25:59] System.IO.IOException: 文件“C:\Users\logtee\AppData\Local\Temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()

**Comment by logtee** [comment]
开启了 Availability Statistics,关掉似乎就OK了!

**Comment by icylogic** [comment]
看来都是 PingReply 的问题。
http://jianguoyun.com/p/DW7iHscQ-_nfBRiEqA0 这个在 log 里记录了 PingException，能否测试一下看 log 里是什么问题？（打开 Availability Statistics）

**Comment by StevenFang** [comment]
同，开启了Availability Statistics后一直崩溃，右键小飞机也没反应，怎么恢复呀

**Comment by StevenFang** [comment]
傻了，忘了config的存在了

**Comment by clowwindy** [comment]
Fixed in 2.5.5
