### ISSUE TITLE
Shadowsocks.Controller.TCPHandler|xxx.xxx.xxx.xxx:xx timed out

### ISSUE THREAD

**Issue by 5ispy** [shadowsocks/shadowsocks-windows#2860]
### Shadowsocks version / 影梭版本
4.1.10.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
购买了vultr服务，连上机器，PAC模式，使用本地PAC

### What did you expect to see? / 期望的结果
连接速度正常，网速正常

### What did you see instead? / 实际结果
这两天出现的情况，连接远程机器的时候很慢，连接后访问的网速也很慢，查看日志显示：Shadowsocks.Controller.TCPHandler|xxx.xxx.xxx.xxx:xx timed out
这种情况从前两天开始的，今天试了一下，网速有所提升但是还是比较慢。

**Comment by chenshaoju** [comment]
这意味着连接超时，可能是由于线路问题或者连接被QoS了。

通常没有较好的方法，可以尝试套个插件看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836
