### ISSUE TITLE
add an auto launch on startup button? | Using shadowsocks for gaming with friends?

### ISSUE THREAD

**Issue by ShadowSocks12** [shadowsocks/shadowsocks-windows#2862]
Hi Can you add a button for Shadowsocks to make it auto launch on startup please?
I think this is a great idea instead of every time I run shadowsocks manually when I start my PC.
///////////
Now the second part,
if me and my friend use same URL or QRCode, will it be possible to play game together?

**Comment by chenshaoju** [comment]
When Shadowsocks is started, Right-click Shadowsocks icon in the taskbar icon tray area, Check `Start on Boot`.

**Comment by studentmain** [comment]
> if me and my friend use same URL or QRCode, will it be possible to play game together?

Depend on your game. Most time you need a real VPN to do this.

**Comment by ShadowSocks12** [comment]
Ok Thank You Very Much. chenshaoju and studentmain.
