### ISSUE TITLE
Port blocking even using obfs

### ISSUE THREAD

**Issue by sioulisn** [shadowsocks/shadowsocks-windows#2863]
### Steps you have tried / 操作步骤
Today started cnfirewall to block ports. i use  aes-256-cfb + tls1.2_ticket_auth_compatible obfs
The only port working but slow and not always is 443
I have tried in three server I have Korea, HK, SG.
It happens the same to all

### What did you expect to see? / 期望的结果
i expect lshadowsocks to work properly and fast like always but it seems since today cannot

### What did you see instead? / 实际结果
I can ping servers but ports are keep getting blocked, I change ports and work for some minutes then immediately blocked again

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

**Comment by chenshaoju** [comment]
Looks your using ShadowsocksR, Please note Shadowsocks and ShadowsocksR (or ShadowsocksRR)  is not the same.

**Comment by sioulisn** [comment]
does shadowsocks work without plugin?  I remember before I had the same problem with port blocking

**Comment by chenshaoju** [comment]
Shadowsocks  can working without plugins, But maybe can get blocked.

The tls1.2_ticket_auth_compatible is not compatible with simple-obfs or other plugins: https://github.com/shadowsocks/shadowsocks-windows/issues/2714#issuecomment-562403383
