### ISSUE TITLE
无法正常使用且更新pac文件失败

### ISSUE THREAD

**Issue by Latomoyocarl** [shadowsocks/shadowsocks-windows#2864]
### Shadowsocks version / 影梭版本
4.1.10.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10.net4.8

### Steps you have tried / 操作步骤
删了ss重新试

### What did you expect to see? / 期望的结果
正常使用

### What did you see instead? / 实际结果
木大（安卓端可以使用，pc不行）

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
2020-04-23 20:00:50.9260|WARN|Shadowsocks.View.MenuViewController|System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---

**Comment by Latomoyocarl** [comment]
补充一点，想连咕咕噜时出现500和502

**Comment by chenshaoju** [comment]
这意味着你的服务器可能被墙了，或者配置有误。

请尝试使用这个第三方的服务测试你的服务器的连通性： https://ip100.info/check

**Comment by Latomoyocarl** [comment]
> 这意味着你的服务器可能被墙了，或者配置有误。
> 
> 请尝试使用这个第三方的服务测试你的服务器的连通性： https://ip100.info/check

服务器没问题，就是配置不知道怎么看

**Comment by chenshaoju** [comment]
如果你是购买的SS服务，请与你的服务商联系。

如果你是自己搭的，服务端的配置文件可能位于 /etc/shadowsocks-libev/config.json 。

**Comment by mylovefan007** [comment]
国内overtime、国外open是啥意思？

**Comment by Latomoyocarl** [comment]
> 如果你是购买的SS服务，请与你的服务商联系。
> 
> 如果你是自己搭的，服务端的配置文件可能位于 /etc/shadowsocks-libev/config.json 。

从哪里看呐？

**Comment by Latomoyocarl** [comment]
> 国内overtime、国外open是啥意思？

我也不清楚。。。
