### ISSUE TITLE
有没有自动更新代理服务器的功能？？还是我不会用呀？？

### ISSUE THREAD

**Issue by ruixiwu** [shadowsocks/shadowsocks-windows#2867]
各位大神， 
只有当找资料时才翻到外面去， 所以下次再再启时， 就要重要找代理服务器,了。
（1）每次从一个一个的代理服务器去验证，挺蛮烦麻的，能不能自动验证服务器， 并自动选择响应最快的服务器上？哪怕弄个半自动的一键验证， 也是不错的。
（2）能不能搞个RSS一样的东西， 自动的更新到最新的服务器列表？

知道的怎么做的同学，请告诉我：ruixiwu@163.com

**Comment by studentmain** [comment]
> 影梭（Shadowsocks）是一个开源非盈利项目，不提供任何托管服务

**Comment by ruixiwu** [comment]
大老， 没有解决我的问题呀
