### ISSUE TITLE
切换线路后无法正常连接

### ISSUE THREAD

**Issue by williamszey** [shadowsocks/shadowsocks-windows#2868]
### Shadowsocks version / 影梭版本
4.1.10
### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10.net4.8

### Steps you have tried / 操作步骤

切换线路后无法连接上网，查看日志后发现：
[2020-04-26 11:05:22] [Error] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:443
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
### What did you expect to see? / 期望的结果
可以正常使用

### What did you see instead? / 实际结果
无法使用

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2020-04-26 11:05:22] [Error] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:443
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

**Comment by studentmain** [comment]
如果你是从服务提供商购买的服务，请联系他们。

**Comment by chenshaoju** [comment]
你是否配置了一个正向代理？如果是，请取消：

![image](https://user-images.githubusercontent.com/515763/80444260-d7873d00-8943-11ea-8fc8-17ba88791f79.png)
