### ISSUE TITLE
windows客户端使用了ss代理退出后浏览器的系统代理不会恢复

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/shadowsocks-windows#287]
谷歌浏览器（我基本就用这个）发现系统代理在用了ss客户端后会自动更改，但是ss客户端退出后浏览器的系统代理不会恢复原状也就是还是使用之前ss客户端设置的代理。

**Comment by AnyoeDove** [comment]
chrome建议使用https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif

**Comment by hdstar2009** [comment]
以前版不会这样。另外不喜欢安装这类东西。

**Comment by clowwindy** [comment]
正常退出是不会不清除设置的。

**Comment by LockGit** [comment]
I Not find this condition , also shdownsockts proxy ,use 1080 port , select global mode , when exit shadownsockts , browser display normal .

**Comment by AnyoeDove** [comment]
试了一下我也会
日志
[2015-08-18 19:28:37] System.Net.Sockets.SocketException (0x80004005): 请求的名称有效，但是找不到请求的类型的数据。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.StartConnect()

[2015-08-18 19:29:52] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:8123
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)

基本就这两条内容
