### ISSUE TITLE
How I can Disable Logs?

### ISSUE THREAD

**Issue by xmha97** [shadowsocks/shadowsocks-windows#2870]
Hello, I'm using Shadowsocks on Windows 10.
In order to sync the data, I put Shadowsocks in OneDrive.
![Windows File Explorer](https://user-images.githubusercontent.com/23485114/80527586-d4bf3300-89a9-11ea-8d99-4c67ebb137e1.png)
Now I want to disable the `ss_privoxy.exe` log files because I don't need it.
Also, it disrupts the synchronization function of OneDrive.
![OneDrive](https://user-images.githubusercontent.com/23485114/80528309-fbca3480-89aa-11ea-819b-16dfcaa30c14.png)
Please help me.

**Comment by xmha97** [comment]
Can I change `gui-config.json` path?

**Comment by chenshaoju** [comment]
You can choose not to sync `ss_win_temp` folder in OneDrive.

Or you can Uncheck `Portable Mode` in `Edit Server` window

**Comment by ShadowSocks12** [comment]
Sorry for the question, but i am curious , What do these logs contain? Some information about the user ? or what?

**Comment by xmha97** [comment]
> 
> 
> Sorry for the question, but i am curious , What do these logs contain? Some information about the user ? or what? and why does shadowsocks keep logs?

You can see log files on below picture:
![Windows File Explorer](https://user-images.githubusercontent.com/23485114/80527586-d4bf3300-89a9-11ea-8d99-4c67ebb137e1.png)
```
ss_win_temp\privoxy_*.conf
ss_win_temp\shadowsocks.conf
ss_win_temp\ss_privoxy.log
```

**Comment by ShadowSocks12** [comment]
3 logs only?
ss_win_temp\privoxy_*.conf
ss_win_temp\shadowsocks.conf
ss_win_temp\ss_privoxy.log
Ok,  what is inside those logs? and why does shadowsocks make logs?

**Comment by studentmain** [comment]
> 
> 
> 3 logs only?
> ss_win_temp\privoxy_*.conf
> ss_win_temp\shadowsocks.conf
> ss_win_temp\ss_privoxy.log
> Ok, what is inside those logs? do they have details about the user's system or what? and why does shadowsocks make logs?

Just open them and you'll know, log file is plain text.

Yes, OS info, language, server address, etc. If you open verbose logging, there's also connection trace. But they won't be uploaded, we don't make money with this project.

When something wrong, you can check the log to figure why.

**Comment by ShadowSocks12** [comment]
What do you mean by "They won't be uploaded", you mean the users' logs won't be seen by the authors or developers of shadowsocks? only the user of shadowsocks can see the logs?

**Comment by studentmain** [comment]
They just stay on your machine, if you don't paste them here, we can't see it.

**Comment by ShadowSocks12** [comment]
Ok, if you were making money from this project, why would you need logs?

**Comment by xmha97** [comment]
> 
> 
> Can I change `gui-config.json` path?

@studentmain Please answer to this question.

**Comment by studentmain** [comment]
> 
> 
> > Can I change `gui-config.json` path?
> 
> @studentmain Please answer to this question.

You can't do it now. There's a plan to use command line argument to set `gui-config.json` path, but no ETA for it.

**Comment by ShadowSocks12** [comment]
studentmain, May I know what would happen to the logs if this project wasn't for free?
And how would you need them or use them?
Please.

**Comment by studentmain** [comment]
> 
> 
> studentmain, May I know what would happen to the users' logs if this project wasn't for free?
> And how would you need them or use them?
> Please.

It's hard too say: If this project wasn't free, I'll not been there...

**Comment by ShadowSocks12** [comment]
ah, I understand ok thank you very much.
