### ISSUE TITLE
Anti Virus Detected ss_privoxy.exe as a virus.

### ISSUE THREAD

**Issue by ShadowSocks12** [shadowsocks/shadowsocks-windows#2873]
This is the first time my Anti Virus detects ss_privoxy.exe as a virus, Why is that?
![image](https://user-images.githubusercontent.com/63942376/80613706-4baa0980-8a46-11ea-8725-ad281b44f779.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2815

**Comment by ShadowSocks12** [comment]
aha, false positive, Ok. 
By the way the language of the discussion was Chinese , so I translated it.
Ok thank you very Much.
