### ISSUE TITLE
What is the server address and password

### ISSUE THREAD

**Issue by wuyuehong** [shadowsocks/shadowsocks-windows#2878]
### Environment (Operating system, .NET Framework, etc) 
System：windows10
Version:：shadowsocks-4.1.10.0

### Steps you have tried

Click the shadowsocks icon to prompt me to configure the server address and password

### What did you expect to see?

Want to know the server address and password

**Comment by studentmain** [comment]
You need setup one by yourself or buy one, we don't provide tech support for server.
