### ISSUE TITLE
2.5.4为何一直联网，而且速率不低。

### ISSUE THREAD

**Issue by ilihai** [shadowsocks/shadowsocks-windows#288]
![-1](https://cloud.githubusercontent.com/assets/5362880/9300429/6c7b1fca-44f8-11e5-9e41-03d9f6d12136.png)

系统win10，今天换的2.5.4，就发现我不用网络的时候ss这边就没有停歇过，没有开系统代理，但是有开allow cilent from lan，但是我lan里其它机器都没开机啊。可以看到tcp connections里面若干来自外网的ip，这些都怎么来的？

之前2.5.2的时候没发现这个问题。

**Comment by icylogic** [comment]
能否看一下log有没有什么异常

**Comment by ilihai** [comment]
![-1](https://cloud.githubusercontent.com/assets/5362880/9300779/1e1c21d6-44fc-11e5-9556-3ff207719026.png)

以上log的几分钟内，我并未使用ss。
如果关掉allow cilent from lan，一切都安静了，如果打开，流量就上来了。
一种肉鸡的即视感...

**Comment by chenshaoju** [comment]
你是公网IP？

**Comment by ilihai** [comment]
@chenshaoju 是啊，我路由是公网ip，我这主机做了dmz，虽然是10.0.0.10，但也算公网吧..
我不清楚是我的ss在连他们还是他们在连我， 但这个local port不对啊，8123根本不是我给ss设置的 proxy port.

![-1](https://cloud.githubusercontent.com/assets/5362880/9300890/f951c436-44fc-11e5-9f5f-9a0760d3ea60.png)

**Comment by ilihai** [comment]
我重启了路由，拿了一个新ip，这个问题就没有了，晕。
看来是我之前自动拨号获得那个ip，有人做过公众代理吧...伤不起啊伤不起...

sorry，浪费你们时间了。

**Comment by ilihai** [comment]
我重启了路由，拿了一个新ip，这个问题就没有了，晕。
看来是我之前自动拨号获得那个ip，有人做过公众代理吧...伤不起啊伤不起...

sorry，浪费你们时间了。

**Comment by chenshaoju** [comment]
8123 是内置的HTTP代理的端口，被人扫到了然后变成了公共代理。

用DMZ如果没有配置好防火墙，容易引发各种安全问题，谨慎使用。

**Comment by clowwindy** [comment]
没有想到有什么办法可以很好的区分 LAN 还是 DMZ。
