### ISSUE TITLE
客户端报错，离线安装包异常

### ISSUE THREAD

**Issue by Tasty-Warning** [shadowsocks/shadowsocks-windows#2885]
### 环境

- Shadowsocks客户端版本：4.1.10.0
- 操作系统版本：win 10
- .NET版本：v4.0.30319

### 操作步骤
打开就报错

### 实际结果
**
![image](https://user-images.githubusercontent.com/44464598/81492473-92132a00-92ca-11ea-81f3-6dcac90f518f.png)
**

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

还有离线安装包以前下面都有字的，现在打开直接是黑乎乎的，什么都没有。版本是4.2.2
db
![error-1](https://user-images.githubusercontent.com/44464598/81492505-da324c80-92ca-11ea-8f52-5ca6dc0ce15f.png)

**Comment by chenshaoju** [comment]
1.请尝试将 Shadowsocks.exe 放到一个非 Program Files 的目录中，比如 D:\SS\ ，然后再试。
2.这个看起来不像是Shadowsocks的一部分。

**Comment by Tasty-Warning** [comment]
> 1.请尝试将 Shadowsocks.exe 放到一个非 Program Files 的目录中，比如 D:\SS\ ，然后再试。
> 2.这个看起来不像是Shadowsocks的一部分。

换了个路径，确实正常了。
路由器的那个离线包有问题就有问题吧。暂时先用客户端。
