### ISSUE TITLE
Statistics工作异常

### ISSUE THREAD

**Issue by xiaoas** [shadowsocks/shadowsocks-windows#2886]
### 简要描述问题
![image](https://user-images.githubusercontent.com/14904657/81495278-ce9e5000-92e1-11ea-8c62-fb2808b47a1d.png)
昨天刚开始用这个版本的ss，但是statistics功能似乎没法正常工作。如上图。
大概开启统计超过24h了。
### 环境

- Shadowsocks客户端版本：4.1.10.0
- 操作系统版本：Microsoft Windows 10 Pro	Version 10.0.19041 Build 19041

- .NET版本：无

### 期望的结果
statistics页面展示折线图

### 实际结果
只有两个点和一个块块

### 配置文件和日志文件（请隐去敏感信息）

```

```

**Comment by studentmain** [comment]
因为没人维护，统计功能是残废的……

下个大版本要么重做要么丢弃
