### ISSUE TITLE
用校园网（移动）vpn拨号客户端上网后，再挂代理，能连国外的平台（如steam）吗

### ISSUE THREAD

**Issue by 41albatros** [shadowsocks/shadowsocks-windows#2888]
用的VPN和设置如下
![QQ图片20200512134616](https://user-images.githubusercontent.com/65212780/81643008-4346cb00-9457-11ea-8588-9ddfe02d9ffe.png)
![QQ图片20200512134621](https://user-images.githubusercontent.com/65212780/81642988-3a55f980-9457-11ea-9311-1782c2cb8b47.png)
![QQ截图20200508193746](https://user-images.githubusercontent.com/65212780/81642992-3aee9000-9457-11ea-9f2a-4ecbd044f5d5.png)
现在只能网页端用proxy来访问外网，但像steam这样平台上的个人主页之类的还是连不上。
第一次接触vpn，如果行得通的话，萌新希望大佬们指教一番。万分感谢。

**Comment by studentmain** [comment]
v2rayN在这里：https://github.com/2dust/v2rayN

**Comment by DuckSoft** [comment]
这不是 v2rayN 吗……怎么跑来 shadowsocks-windows 了……
