### ISSUE TITLE
Online PAC Onedrive support

### ISSUE THREAD

**Issue by maddhin** [shadowsocks/shadowsocks-windows#2889]
Hi, 
I am not sure where you maintain your PAC list but for me it is very difficult to put this list on a server to have direct access to it (I literally do not know how to do this even I managed to set up a Outline V-Server).
Therefore I would like to just use a Onedrive Link to link to my PAC list. That is easy and that link is also not blocked in the country where I live. But Onedrive is not providing a direct link to the PAC.txt file so the usually generated link does not work together with Shadowsocks:(

Would that be possible or are there other simple ways to host the PAC.txt?

**Comment by imba-tjd** [comment]
1. The pac list is not maintained by this org
2. ss-win can (and by default) set up a local http server hosting the pac.txt
3. https://gist.github.com
4. You must define `__PROXY__` in the online pac.txt by yourself because it's essential and ss-win can't modify it in this way

**Comment by maddhin** [comment]
thank you for the fast and competent response! 

I will try to use gist, thank you for this tip!

Could you elaborate on "You must define __PROXY__ in the online pac.txt by yourself because it's essential and ss-win can't modify it in this way" - I do not understand what I need to do here in order to make it work together with gist. Sorry and thank you for your patience.

**Comment by imba-tjd** [comment]
Basically by adding `var proxy='PROXY 127.0.0.1:1080;'` on the top of pac.txt if your pac.txt is generated by ss 4.1.9+ from gfwlist. If not, the solution may be different accroding to the js code in pac.txt

**Comment by maddhin** [comment]
thank you - my PAC.txt is generated from the latest ss from gfwlist... 

A last stupid question: if using gist, can I just put the gist link (literally https://gist.github.com/maddhin/0dc908eb6e980516ffa850a458b8c18c) in the online PAC url?

**Comment by imba-tjd** [comment]
https://gist.githubusercontent.com/maddhin/0dc908eb6e980516ffa850a458b8c18c/raw/PAC.txt

**Comment by maddhin** [comment]
ah, I was about to say "you are my hero!" but as gist is blocked here, it doesn't seem to work this way:((( ss is not connecting to the PAC.txt through a ss server, or?

**Comment by imba-tjd** [comment]
You can create a github repo. If github is blocked then use gitlab or bitbucket

**Comment by maddhin** [comment]
the gitrepo seems to work, eureka! Thank you very much! 

Now the hopefully last question: when will the PAC.txt be updated once I commited changes? I just tested and changes does not seem to have an effect. 

And then there is another question: from an practical standpoint, maintaining a PAC.txt on Github is not ideal as sometimes one finds a page that is blocked and quickly want to unblock it - ideally with something like super easy "right mouse -> add to PAC.txt" :)) Did anybody come across something like that? Would that be technically achievable? Maybe via a script or browser extension that adds to github PAC.txt? Would be a dream!

**Comment by maddhin** [comment]
actually, Github is not working as this then also seem to lead to a https://raw.githubusercontent.com URL which is blocked

**Comment by maddhin** [comment]
I am using the github repo now but I have the weird problem that there are lines cut at the end of the PAC.txt after I edited saved the file. So, instead of 7000+ lines there is only 5000 or sometimes only 200 lines. Does anybody understand that problem?

Would it be possible to leave the gfwlist PAC.txt locally and just have a user rules list online?

Would it be possible to point ss to a PAClist.txt? That file could then be in a folder that is synchronized between computers and wouldn't need github etc

Sorry for all the questions but I think something like this is a problem a number of people have.
