### ISSUE TITLE
【建议】socks5代理也走PAC

### ISSUE THREAD

**Issue by a764934018** [shadowsocks/shadowsocks-windows#2890]
我用浏览器通过ss的socks5代理来实现浏览器翻墙，但是发现ss的socks5代理不走PAC，很不方便。

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 的本地SOCKS5代理只提供代理功能。

如果你需要PAC，以Firefox+SwitchyOmega的情况来说，你需要手动配置PAC代理：
![Screenshot from 2020-05-14 10-22-14](https://user-images.githubusercontent.com/515763/81885379-d5241480-95cc-11ea-9574-92bad5e74ac9.png)

**Comment by a764934018** [comment]
> Shadowsocks for Windows 的本地SOCKS5代理只提供代理功能。
> 
> 如果你需要PAC，以Firefox+SwitchyOmega的情况来说，你需要手动配置PAC代理：
> ![Screenshot from 2020-05-14 10-22-14](https://user-images.githubusercontent.com/515763/81885379-d5241480-95cc-11ea-9574-92bad5e74ac9.png)

感谢回复，我目前就是用SwitchyOmega，socks5如果支持pac最好哈，只是建议
