### ISSUE TITLE
Switching "System Proxy" closes active connections

### ISSUE THREAD

**Issue by klaaktu** [shadowsocks/shadowsocks-windows#2903]
### Describe the bug
First PC: Running Shadowsocks and Cloak with "Allow other devices to connect" checked.
Second PC: Configured to use Shadowsocks on the first PC via Manual proxy setup in Windows settings.
Switching between "Disable" & "Global" System Proxy in Shadowsocks on the first PC disconnects my Steam client on the second PC. 
### Environment

- Shadowsocks client version: 4.1.10.0
- Cloak client version: 2.2.0
- OS version: Windows 10 1909
- .NET version: 4.8

### Steps you have tried
Log in Steam on the second PC. Steam seems to use the proxy setting bc gfw censored sections are accessible.
Switching between "Disable" & "Global" System Proxy in Shadowsocks on the first PC.

### What did you expect to see?
The second PC not being affected, since System Proxy setting only changes the setting of the first PC.

### What did you see instead?
Steam force Alt-Tab full screen game to desktop (very annoying but they don't seem to be planning on changing that soon...) with a pop up asking to re-enter credentials, saying something about credential has changed or being disconnected.

### Config and error log in detail (with all sensitive info masked)
"Allow other devices to connect" checked, Cloak as plugin program and its config file as plugin option.
Shadowsocks and Cloak didn't show any error in log.
Steam "your credential has changed", however no abnormal login activity and my password logs in just fine.

**Comment by klaaktu** [comment]
Actually an easier way to reproduce this problem: initiate a download on the second PC, while it's downloading, switch Shadowsocks to Global mode on the first PC, now the download should be "failed, network error".

**Comment by chenshaoju** [comment]
Sorry for my English.

Global system proxy on or off is not affected another computer when using "Allow other devices to connect".

But if you Switching Shadowsocks configure (e.g change server, Enable or Disable System Proxy or Switching Proxy mode, The current connection will disconnect.

**Comment by klaaktu** [comment]
@chenshaoju I see, thx. Tho it'd be nice if Shadowsocks could keep the connections when changing "System Proxy" only.
