### ISSUE TITLE
shadowsocks使用过程中失效

### ISSUE THREAD

**Issue by Wangnibaba** [shadowsocks/shadowsocks-windows#2905]
系统 Windows10 1909 家庭版 
shadowsocks版本：4.1.10.0

之前shadowsocks一直没问题，直到前两天更新了kk联机加速器之后shadowsocks失效了，用了netsh ipv4 /ipv6/winsock Reset几个命令重启之后又好用了，但是有的时候shadowsocks用一段时间又就失效了，还得重置网络，重启电脑，不知道有没有什么解决办法。

附上错误日志
`2020-06-07 
 19:44:57.5518|WARN|Shadowsocks.Controller.UpdateChecker|System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
`

**Comment by chenshaoju** [comment]
可能此类加速器影响到了SS的工作。

如果可能，做个测试，暂时卸载加速器和腾讯会议，该问题是否就不再出现？

**Comment by Wangnibaba** [comment]
> 可能此类加速器影响到了SS的工作。
> 
> 如果可能，做个测试，暂时卸载加速器和腾讯会议，该问题是否就不再出现？

我又试了几次，用过kk联机加速器之后shadow socks就不能正常工作了，需要重置网络再重启

**Comment by chenshaoju** [comment]
👌
