### ISSUE TITLE
PAC 更新

### ISSUE THREAD

**Issue by EricMzky** [shadowsocks/shadowsocks-windows#2908]
什么时候可以更新一个新版本的飞机，把PAC源重新替换一下？现在GWF已经很久不更新了，而且好多都出不去，只能全局。是不是可以换一个源？感谢！

**Comment by chenshaoju** [comment]
下个释出版本就能看到了，已经使用V2Ray的geosite 来替代GFWList：https://github.com/shadowsocks/shadowsocks-windows/pull/2875 。

**Comment by EricMzky** [comment]
> 下个释出版本就能看到了，已经使用V2Ray的geosite 来替代GFWList：#2875 。

大佬 预计几号能出新版啊~~~

**Comment by EricMzky** [comment]
> 不知道……取决于社区什么时候发新版。。。如果你很着急，可以试试一下自动编译的版本：https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/32784764/job/22lcct2wh86s241a/artifacts

和之后的Release版本无区别吧？

**Comment by chenshaoju** [comment]
有，这个是基于使用 geosite 自动编译的版本，和释出会有区别。

**Comment by EricMzky** [comment]
> 有，这个是基于使用 geosite 自动编译的版本，和释出会有区别。

坐等新版Release~thanks~~~~

**Comment by git10135405** [comment]
Pre-release 4.2.0.0
从GeoSite更新pac报错
![image](https://user-images.githubusercontent.com/35558611/93964026-2a4d0f80-fd91-11ea-85f8-02bf733e6390.png)

**Comment by chenshaoju** [comment]
请尝试升级到最新的 .NET Framework 4.8 https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer

如果仍然不行，可能是由于你的  .NET Framework 损坏导致的，启动命令提示符，进入下载目录后，执行：
```
ndp48-web.exe /repair
```

或者直接使用 `/nosetupversioncheck` 忽略版本检查。

**Comment by git10135405** [comment]
@chenshaoju 升级到最新的 .NET Framework 4.8 可以正常更新了 谢谢！

**Comment by git10135405** [comment]
@chenshaoju 请教下，下载下来pac怎么应用到SwitchyOmega上呢

**Comment by chenshaoju** [comment]
请移步：https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList
