### ISSUE TITLE
请问可以在编辑服务器窗口增加上移下移功能么

### ISSUE THREAD

**Issue by wenliyang** [shadowsocks/shadowsocks-windows#291]
之前使用的是那个修改版本客户端，除了随机选择服务器功能，觉得很方便就是这个可以在编辑服务器窗口上移下移服务器功能，手动修改gui-config.json文件容易出错，如果官方版本也能增加这个功能就好了

另，现在改用官方版本了，增加高可用、负载均衡等功能后，连接稳定性比修改版本更好

**Comment by clowwindy** [comment]
这个功能应该很简单，有人有兴趣的话可以发个 pull request。如果没有的话我过几天加一下。

**Comment by clowwindy** [comment]
Thanks to @kimw 
Fixed in https://github.com/shadowsocks/shadowsocks-windows/pull/296
