### ISSUE TITLE
给定关键字不在字典中

### ISSUE THREAD

**Issue by wangg9722** [shadowsocks/shadowsocks-windows#2913]
### 简要描述问题
任何需要代理的的请求都会被终止
### 环境

- Shadowsocks客户端版本：
- 操作系统版本：Windows 10
- .NET版本：4.8

### 配置文件和日志文件（请隐去敏感信息）

```
2020-06-16 14:09:01.4207|WARN|Shadowsocks.Controller.TCPHandler|System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()

```

**Comment by studentmain** [comment]
客户端版本号？

**Comment by wangg9722** [comment]
客户端 发现问题是 4.1.10.0 昨天退回到 4.1.8 也不行了 依然提示这个错误
![image](https://user-images.githubusercontent.com/19620526/84843745-4dbe3b00-b07b-11ea-8e37-e73e40ba3b30.png)

**Comment by chenshaoju** [comment]
我注意到你的加密方面什么都没选。

你是不是从什么地方复制（下载）过来的配置文件？

PS：请记得隐藏你的服务器的IP。

**Comment by wangg9722** [comment]
"method" : "rc4",
朋友给的

**Comment by chenshaoju** [comment]
Shadowsocks 没有 `rc4` 这个加密算法，只有 `rc4-md5` ，你是不是弄错了客户端？请注意，Shadowsocks和ShadowsocksR是两个不同的东西。

**Comment by wangg9722** [comment]
哦 好的 ,我对这个不是太了解呢,以前一直用的Shadowsocks ,不好意思哟
