### ISSUE TITLE
win10下载之后打开客户端就显示错误

### ISSUE THREAD

**Issue by wochen001** [shadowsocks/shadowsocks-windows#2914]
双击打开显示：处理代理设置时发生错误，是否重置当前代理设置并重试
点击是以后显示：发生不可恢复的代理设置错误，查看日志以取得详情
日志部分：
2020-06-16 21:15:51.8332|WARN|Shadowsocks.Controller.UpdateChecker|System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
2020-06-16 21:16:34.8683|ERROR|Shadowsocks.Controller.SystemProxy|sysproxy - SysproxyExitError:Error setting options: 123 文件名、目录名或卷标语法不正确。

但是我在安卓上面可以正常使用，在win7电脑上面也可以正常使用

**Comment by wochen001** [comment]
![9ce1b28212754bc518b1713c860a0ac](https://user-images.githubusercontent.com/18026259/84781041-e96a8f80-b018-11ea-8980-2fe243c1cf6f.png)
![180f59184678529defd0e5d517efb03](https://user-images.githubusercontent.com/18026259/84781050-eb345300-b018-11ea-986c-aec0914bfd1e.png)
![62f6a381002c1745d8c95ab6f8906a6](https://user-images.githubusercontent.com/18026259/84781058-ec658000-b018-11ea-8451-e03389556fdf.png)

**Comment by wochen001** [comment]
![180f59184678529defd0e5d517efb03](https://user-images.githubusercontent.com/18026259/84781104-fd15f600-b018-11ea-8a73-4de85597ee37.png)

**Comment by studentmain** [comment]
系统版本？ss-windows所在路径？把user-wininet.json内容发出来看看？

**Comment by wochen001** [comment]
> 系统版本？ss-windows所在路径？把user-wininet.json内容发出来看看？

系统版本：win10 家庭版1903
ss-windows所在路径为D:\Shadowsocks-4.1.10.0
user-wininet.json内容为：
{
  "UserSettingsRecorded": false,
  "Flags": "1",
  "ProxyServer": "8.208.103.20:7976",
  "BypassList": "0\u0007",
  "PacUrl": "http://127.0.0.1:1080/pac?hash=nRBlD-SPEADIocnyzFIPZA2&secret=he_vouLmgUl7Q6fHu45doxSiESBS3KYC9pCXnwb_wuM1"
}

**Comment by studentmain** [comment]
退出ss，删除user-wininet json，找到ss_win_temp/sysproxy.exe，从命令行执行`sysproxy set 1 "" "" ""`，然后重新打开ss试试还有没有错误

**Comment by wochen001** [comment]
> 退出ss，删除user-wininet json，找到ss_win_temp / sysproxy.exe，从命令行执行`sysproxy set 1 "" "" ""`，然后重新打开ss试试还有没有错误

还是这个错误，生成的user-wininet json还是之前的

**Comment by studentmain** [comment]
找到系统的代理设置，把"不对以下地址使用代理"中的内容全部清除，再试试。

**Comment by wochen001** [comment]
系统里面代理设置全部都是关闭状态

**Comment by wochen001** [comment]
> 找到系统的代理设置，把"不对以下地址使用代理"中的内容全部清除，再试试。
系统里面代理设置全部都是关闭状态

**Comment by chenshaoju** [comment]
请尝试做个测试，新建一个目录，比如 D:\SS\ ，然后单独将 shadowsocks.exe 放进去，双击看看？

**Comment by wochen001** [comment]
> 请尝试做个测试，新建一个目录，比如 D:\SS\ ，然后单独将 shadowsocks.exe 放进去，双击看看？

试过了，还是同样的问题

**Comment by studentmain** [comment]
怀疑是系统问题，最快捷的方法是重置或者重装系统……

**Comment by wochen001** [comment]
> 怀疑是系统问题，最快捷的方法是重置或者重装系统……

您说的重置是重置什么C盘吗

**Comment by veryspicy** [comment]
我也遇到了同样的问题，现在window版的ss用不了，手机的还能用

**Comment by wochen001** [comment]
> 我也遇到了同样的问题，现在window版的ss用不了，手机的还能用

不知道，怎么搞了，别人电脑是可以的-。-

**Comment by studentmain** [comment]
这种问题一般归结为系统或者其他应用错误的设置了系统代理，因为实在是难以排查，推荐从系统设置里面重置Windows，注意保存好数据。

**Comment by wochen001** [comment]
> 这种问题一般归结为系统或其他应用错误的设置了系统代理，因为实在是很难排查，推荐从系统设置里面重置Windows，注意保存好数据。

要是能直接充值系统那就简单了，很多东西都不知道在在哪里-。-没发重做

**Comment by veryspicy** [comment]
我的问题解决了， 因为server节点不可以用，所以更新pac时候就会报这个错误，100%复现。但是手机上可以使用，就没怀疑是服务端的问题，后来借了同事的server，后可以正常上墙，然后更新pac，不会报这个错误了，他说可能是我域名的ssl证书过期了。。。

**Comment by wochen001** [comment]
> 我的问题解决了， 因为server节点不可以用，所以更新pac时候就会报这个错误，100%复现。但是手机上可以使用，就没怀疑是服务端的问题，后来借了同事的server，后可以正常上墙，然后更新pac，不会报这个错误了，他说可能是我域名的ssl证书过期了。。。

借的server是啥-。-啥域名ssl证书

**Comment by studentmain** [comment]
这样，打开注册表编辑器，找到`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\`，将`ProxyOverride`设为`localhost`，重启电脑，再试试。

还是不行，而且不能重装的话，可以设置各个软件自己的代理设置（不同软件设置方法不一样，无法一一说明，Chrome浏览器需要使用SwitchyOmega插件）先用着，或者试试Outline-Client。

**Comment by veryspicy** [comment]
> > 我的问题解决了， 因为server节点不可以用，所以更新pac时候就会报这个错误，100%复现。但是手机上可以使用，就没怀疑是服务端的问题，后来借了同事的server，后可以正常上墙，然后更新pac，不会报这个错误了，他说可能是我域名的ssl证书过期了。。。
> 
> 借的server是啥-。-啥域名ssl证书

server就是ss的服务端， 我用的v2ray+tls+nginx 的方式搭建的，用的acme.sh 的dns验证的证书，根据acme.sh 官方得知，这种方式没办法自动续签证书，所有重新更新下证书就能用了。  这个报错就是server不可用，无法从pac的服务器上更新pac。 手机可用，可能是ios系统会忽略ssl。。。不太清楚
