### ISSUE TITLE
最新版4.1.10.0的有问题，使用一段之后就没法使用了

### ISSUE THREAD

**Issue by 5536086** [shadowsocks/shadowsocks-windows#2916]
win10最新版，ss更新最新版之前使用好好的，更新到4.1.10.0之后，使用一段时间，就不能用了，直接打不开被Q网站了，但是本地sock5和http代理还能正常连接，删除所有配置文件重新打开就恢复正常了，一上午出现两次这个问题，我就很郁闷了！

**Comment by caesun** [comment]
大概去年下半年开始ss就一直有这个问题，启动连不上，必须删配置，或者切换到全局模式再切回PAC就可以。

**Comment by chenshaoju** [comment]
出现问题的时候，请尝试做个测试，右击任务栏的小图标，选择服务器，再点一下正在使用的服务器，是否就正常了？

**Comment by 5536086** [comment]
> 出现问题的时候，请尝试做个测试，右击任务栏的小图标，选择服务器，再点一下正在使用的服务器，是否就正常了？

试了，没用，这明显是bug。换回了4.1.7.1，现在一切正常了

**Comment by 5536086** [comment]
> 大概去年下半年开始ss就一直有这个问题，启动连不上，必须删配置，或者切换到全局模式再切回PAC就可以。

换回了4.1.7.1，现在一切正常了

**Comment by myneodream** [comment]
的确是，退回到4.1.7.1，恢复正常

**Comment by chenshaoju** [comment]
能否测试一下从 4.1.8.0 和之后的版本，具体是哪个版本开始就出问题了？
https://github.com/shadowsocks/shadowsocks-windows/releases

比较奇怪的是，我用的是 4.1.10.0 ，但是没有此类问题。。。

**Comment by huyi51462** [comment]
4.18以后的版本一直就不能正常使用 不知道什么原因
