### ISSUE TITLE
使用shadowsocks会使得windows search（就是按windows键再serach）非常卡，一方面搜索速度慢，另一方面在search的时候打字也会卡住，关掉就好了。

### ISSUE THREAD

**Issue by ljhshuai** [shadowsocks/shadowsocks-windows#2917]
### 环境

- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by ljhshuai** [comment]
win10专业版64位

**Comment by ljhshuai** [comment]
shadowsocks版本是4.1.10.0

**Comment by chenshaoju** [comment]
请尝试切换到PAC模式看看？

**Comment by ljhshuai** [comment]
就是pac模式，global模式也一样的问题

**Comment by chenshaoju** [comment]
也就是说，如果禁用系统代理，那么就没有问题了对吧？

如果是这样，请尝试禁用系统代理，然后通过插件的方式为浏览器单独配置代理（如SwitchyOmega+GFWList）。

**Comment by ljhshuai** [comment]
我现在换了个代理软件，就可以了，禁用代理确实可以，但是希望能解决一下这个bug

**Comment by chenshaoju** [comment]
推测和GFWList有关。
