### ISSUE TITLE
求windows和android的64位二进制打包客户端.

### ISSUE THREAD

**Issue by ACG-MM** [shadowsocks/shadowsocks-windows#2918]
就是可以直接cmd用参数运行的 要求支持v2ray-plugin. 或者大佬加好友教教我解码编码打包也行. 绕弯路好痛苦

**Comment by ACG-MM** [comment]
支持plugin（插件）就可以了

**Comment by chenshaoju** [comment]
你可以使用cygwin或mingw自行编译，或者使用第三方编译的版本，如：https://github.com/DDoSolitary/shadowsocks-libev-win，请注意，这是第三方的版本，风险自担。

**Comment by studentmain** [comment]
shadowsocks-rust，有windows二进制
