### ISSUE TITLE
im request the binary packeted-exe 64bit client. would running on windows/android.

### ISSUE THREAD

**Issue by ACG-MM** [shadowsocks/shadowsocks-windows#2919]
that would allow to execute -c parameter in windows cmd. and need for ss plugin support. i would also like to learn how to encode/decode common software or game convert to single executable binary exe. if that is possible and there anyone like to teach me. i get stuck sucks. pls

**Comment by studentmain** [comment]
Please follow the issue template, so we can understand what happened to you.

请按照 issue 模板填写，以更清楚地传达意思，另外我们接受中文 issue。
