### ISSUE TITLE
C大，2.5.5清理了系统临时文件之后又报错了。

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-windows#292]
![](http://ww1.sinaimg.cn/large/71fb307agw1ev6385svp6j20d405fmxp.jpg)
privoxy.conf 这个文件会被清理，我觉得让这个文件一直被 ss_privoxy.exe 或者 Shadowsocks.exe 调用吧，这样就不会被清理了

**Comment by LisonFan** [comment]
@clowwindy

**Comment by AnyoeDove** [comment]
感觉其实可以不用放在temp下，如果放在shadowsocks同级文件夹下好点

**Comment by clowwindy** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/293
