### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by ThumperTi** [shadowsocks/shadowsocks-windows#2921]
![Shadowsocks nonUI Error](https://user-images.githubusercontent.com/39796461/87487465-91f91880-c5f2-11ea-9c7d-bd738dc344c1.png)

I have received this message for the last two days while logging into my PrivateVPN account, using their app on my Windows 10 machine

Machine: 
Processor: Intel Core i&-7700T CPU @2.90GHz
RAM: 64.0 GB
Windows 10 Pro
Version 1909
OSBuild 18363.900

**Comment by chenshaoju** [comment]
This issue looks like `ss_privoxy.exe` has been blocked by your security software.

Or it's a folder permission issue, Can you try move `shadowsocks.exe` alone to another folder lke `D:\SS\` ?

**Comment by Stzx** [comment]
There seems to be no more reply. If there are other problems, please reopen it.
