### ISSUE TITLE
插件在哪下载

### ISSUE THREAD

**Issue by lijing89** [shadowsocks/shadowsocks-windows#2922]
插件在哪下载？添加的地址有插件，但是在下载的shadowsocks里没有插件

**Comment by chenshaoju** [comment]
不完全列表：https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by lijing89** [comment]
> 不完全列表：[#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

谢谢
