### ISSUE TITLE
4.1.10.0 PAC模式与Steam冲突

### ISSUE THREAD

**Issue by VCStardust** [shadowsocks/shadowsocks-windows#2923]
### 简要描述问题
在ShadowSocks以PAC模式运行时，若steamwebhelper.exe同时运行，则后者会以>1GB/s的速率(有时会慢一些)占据空闲RAM，直至占满。
全局模式无此现象

### 环境

- Shadowsocks客户端版本：4.1.10
- 操作系统版本：19041.329
- .NET版本：4.0（VS卸了，之前应该是4.8，不过两种现象一样）

### 操作步骤
ShadowSocks调至PAC模式
启动Steam
(不分先后，都能触发)

### 期望的结果
正常代理社区

### 实际结果
RAM占用在十秒内(也可能更长，不超过一分钟)提升至95%以上
亦有可能造成以下一个或多个现象：应用程序崩溃/故障，严重卡顿或系统界面缺失

### 配置文件和日志文件（请隐去敏感信息）

不适用
SS日志有关内容仅有OutOfMemory的异常
PAC是“从 GFWList 更新本地PAC”后的

### 其他
(不知道有没有用)
占用的那大半个内存在任务管理器上的“内存组合”中显示的基本都是“已修改“

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/87908548-29e67e80-ca99-11ea-9301-d8ee10dfc3a6.png)

测试了一下，无法复现，看看有无其他人能复现该问题。

**Comment by aizhihuxiao** [comment]
我也遇到一样的问题，导致steamwebhelper内存使用率爆满，steam库页面打不开，改成全局模式就好了

**Comment by aizhihuxiao** [comment]
我以为是系统问题，重装后问题依旧，看到这个帖子后尝试全局模式和关闭客户端，问题解决

**Comment by aizhihuxiao** [comment]
同样，如果开着steam, pac模式下无流量，也无法打开任何的pac列表页面

**Comment by aizhihuxiao** [comment]
问题解决了，把老的pac列表删除，重新更新一下列表就好了，可能老的列表含有冲突域名之类的

**Comment by chenshaoju** [comment]
@VCStardust 也请试着删除 pac.txt 然后重新更新看看？

**Comment by VCStardust** [comment]
@chenshaoju @aizhihuxiao 谢了，已解决

**Comment by chenshaoju** [comment]
👌

**Comment by VCStardust** [comment]
![image](https://user-images.githubusercontent.com/36991796/89609574-deaad900-d8aa-11ea-8498-4ddacc9a20d9.png)
刚才Beta版更新了，修的应该就是这个（未测试）
