### ISSUE TITLE
增加订阅服务器功能

### ISSUE THREAD

**Issue by IlO0OlI** [shadowsocks/shadowsocks-windows#2928]
**Is your feature request related to a problem? Please describe.**
shadowsocks安卓版添加了订阅功能，希望订阅服务器功能，这样可通过局域网同步电脑上的服务器。

**Comment by chenshaoju** [comment]
有这个计划，但是工作量很大：https://github.com/shadowsocks/shadowsocks-org/issues/89#issuecomment-663653507

**Comment by studentmain** [comment]
如果想把 ss-windows 的配置作为订阅分发，可以考虑直接使用一个 HTTP 服务器托管 gui-config.json 。

> https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/doc-json.md#parsingimporting-json
> ...which should support all reasonable formats of JSON files containing Profiles, including gui-config.json used by shadowsocks-windows.

**Comment by faydanube** [comment]
1. 直接使用 SSR 订阅进行更新
2. 然后复制 SSR 的 `gui-config.json` 覆盖到 SS
3. 在 SS 直接支持订阅功能之前，使用此方法可以完美解决。
