### ISSUE TITLE
AppData & temp & 当前目录

### ISSUE THREAD

**Issue by clowwindy** [shadowsocks/shadowsocks-windows#293]
文件列表：
- Shadowsocks.exe
- 配置文件
- 临时文件

用户需求：
- 要 [放 Dropbox 里要求里面的文件不经常变](https://www.v2ex.com/t/144934?p=2#r_1487094)
- 要 [用电脑管家清理临时文件](https://github.com/shadowsocks/shadowsocks-windows/issues/292)
- 要 [多开](https://www.v2ex.com/t/208311?p=1#r_2334051)
- 要 [放 Program Files 里且不需要管理员权限运行](https://github.com/shadowsocks/shadowsocks-windows/issues/268)

之前已经尽可能满足各方需求了。还有什么想法，请畅所欲言。

**Comment by dangelization** [comment]
为什么我有一种吹毛求疵的感觉。。

dropbox那个，几kb的log也嫌sync麻烦吗。。。

Program Files那个也是。。。一个小exe你要放进Program Files里这是什么样的逻辑。。。既然自己折腾就自己开uac或者手动管理员好了。。

多开的那哥们，要求不大的话可以再下个别的ss客户端同时运行就解决了。然后chrome用switchyomega配置个规则就行了。
关键是多开的需求是不是很大

临时文件那个，只能说顶三楼，都放在一个目录下完事。。。

**Comment by kxjhlele** [comment]
配置文件、临时文件 都放程序目录 ok了，这些都是小问题，
更好的是功能性的建议，比如 增加cow类似的自动化功能。

**Comment by chenshaoju** [comment]
比较中立的意见是，增加一个选项，便携模式。

如果启用该模式，则所有文件都放在程序当前目录。

如果禁用该模式，就到处乱丢，比如 %TEMP%、 %APPDATA% ， etc...etc...

许多软件，比如AIMP3 ( www.aimp.ru )，都这样，安装的时候让你选，Portable 模式就全部放在一起。

**Comment by AnyoeDove** [comment]
虽然那个ShadowsocksR不开源的行为很不对，不过它在软件功能的修改也有可取之处。
它把log之类的放在ss.exe同级temp文件夹中，便于管理也不会太杂乱。

**Comment by clowwindy** [comment]
那是自然的咯。这边加了什么功能，它马上扒过去合并了。它那边加了什么却不会贡献出来给其他人用，久而久之，不就是它那边功能更多了吗。

一直以来我什么都没说是因为我对他还有点希望，所以得给他一点面子不是。一开始我还只是纳闷他为什么不发 pull request，过了一段时间我才明白，这个世界上也有这一类的人。不尊重 GPL 就算了，把作者名字换成自己的，还在主页上加上官方的字样。为什么我们这边反而不说官方呢？因为我希望这个项目是没有官方的，人人都是贡献者。想不到这个社会人人都围着官转，人人都巴不得当官 。

既然他没有尊重别人劳动成果的意愿，那他那些不开源的理由想必也只是借口。说因为加了一些试验性功能会不兼容所以暂不开源。他弄了一个混淆 TCP 协议头功能，在界面上标注提升安全性，吸引用户打开，然后安装他自己的不兼容服务端。然而我分析了一下之后发现这个功能的设计就是想当然，用得多了以后反而会增加特征。如果你真有什么试验性功能，不是更应该开放出来让所有人帮你分析么，大家一起讨论么？在加密算法领域，只有经过足够多人和机构的审视的算法，才能视作是安全的，闭门造出来的怎么能用。。

当然啦，大部分用户才不会管这些，他们不会分析你是不是真的安全，也不会做道德判断，只要他们觉得好用就行。所以可以看到，这种环境下开源其实并没有什么优势，只不过为一些人抄袭提供了便利。这种环境下最后留下来的都是这些人。

我一直想象的那种大家一起来维护一个项目的景象始终没有出现，也没有出现的迹象。维护这个项目的过程中，遇到 @chenshaoju 这样主动分享的同学并不多。很多来汇报问题的人是以一种小白求大大解决问题，解决完就走人的方式来的，然而既不愿提供足够的信息，也不愿写一些自己尝试的过程供后人参考。互帮互助的气氛就是搞不起来。对比下国外的社区差好远。

最适合这个民族的其实是一群小白围着大大转，大大通过小白的夸奖获得自我满足，然后小白的吃喝拉撒都包给大大解决的模式。通过这个项目我感觉我已经彻底认识到这个民族的前面为什么会有一堵墙了。没有墙哪来的大大。所以到处都是什么附件回帖可见，等级多少用户组可见，一个论坛一个大大供小白跪舔，不需要政府造墙，网民也会自发造墙。这尼玛连做个翻墙软件都要造墙，真是令人叹为观止。这是一个造了几千年墙的保守的农耕民族，缺乏对别人的基本尊重，不愿意分享，喜欢遮遮掩掩，喜欢小圈子抱团，大概这些传统是改不掉了吧。

现在维护这些项目已经越来越让我感到无趣。我还是努力工作，好好养家，早日肉翻吧。

**Comment by starrify** [comment]
[off-topic] @clowwindy 大概了解情况以后顺手去提了个issue(虽然不清楚会不会被直接关掉 > < ) https://github.com/breakwa11/shadowsocks-rss/issues/28

**Comment by bigzhu** [comment]
为国人悲哀，也为自已悲哀。
一直在用你的软件，向你说声谢谢。
像你说的，努力肉翻才对

**Comment by exat500g** [comment]
就连上github的国人都这样吗，真是没救了

**Comment by crackevil** [comment]
除了管理员权限是真的需要，别的都是扯淡。对于需求的管理，也是开源力量之一，真的那么需要，总有人会来实现的。

**Comment by shadowofsun** [comment]
原作者加油，之前通过对比觉得R的功能的确多，用了R，今天看到这些，我觉得还是用回原版吧，刚删了R，用回原版，我仅仅是个小白，大概也算伸手党吧，能对原作者表示支持的也仅仅只能做到卸载了不开源不遵守协议的软件，支持原版，谢谢各位的付出~

**Comment by source2git** [comment]
@clowwindy 我觉得一群小白围着大大转是一个客观存在的问题，国外技术论坛或许高手更多，但同样存在那些什么都不明白上来就伸手要解决方案的。你看就算是github这种技术氛围相对高的社区，甚至还有老外得到了答复还要手把手教他操作的。
再说那个ssR的作者，你根本不需要什么留面子，直接联系他交涉，如果他不配合就向github申诉要求撤掉他的项目。这种人不需要评价，人各有志，没必要被他影响心情。
这个项目没有像你预期的那样能有很多人一起来维护，我觉得或许有这样的原因：ss本身就是一个简单易用的工具所以用户群中小白的比例会偏高，他们只关心这个工具能否正常工作，所以无事不登三宝殿，上来留言也肯定是求debug的。而有一定的写代码能力的用户，翻墙工具这种项目可能根本不会引起他们来参与开发的兴趣。
最后，我对像你这些无私无偿维护这个项目的程序员只有敬佩和感谢，我没有能力去汇钱资助你，只有真诚的表达谢意。我也在业余时间学习前端和python，未来会朝着你们为目标迈进的，希望我们都能在各自认同的选择中坚持下去！
祝好！

**Comment by xlz** [comment]
@clowwindy 执行GPL的时候到了 https://help.github.com/articles/dmca-takedown-policy/

**Comment by somebird** [comment]
@clowwindy以前只是潜水，看了你才发的信息后，我只想表达一下感谢。这个项目本身就是一种付出，不过小白太多，可能老兄会有点受不了。解决办法：1、不理会就行了，你不是太阳，不可能无限地放出能量。2、对于真正的反应过的问题和bug再去解决。
再次向你表达感谢之情，还是希望你能继续做下去，尽一分力所能及的心力。

**Comment by xdqi** [comment]
SS-R 这种东西，拿 .NET Reflector 反编译一下，然后把代码合并进主分支吧，别人不仁我们也可以不义嘛

**Comment by teddysun** [comment]
我曾在[博客] [1]表达了对作者 @clowwindy 的谢意。
我也在无意间制作了 Shadowsocks 多个版本服务端的[一键安装脚本][2]，如同作者所说：

> 很多来汇报问题的人是以一种小白求大大解决问题，解决完就走人的方式来的，然而既不愿提供足够的信息，也不愿写一些自己尝试的过程供后人参考。

还有曾经说过的：

> 我觉得这是一个社会常识，花一分钟写的问题，不能期待一个毫无交情的陌生人花一个小时耐心地问你版本和操作步骤，模拟出你的环境来帮你分析解决。

不能同意更多。
眼下的环境确实是越来越糟糕，但也有不少技术人是愿意分享的。
作者所遇到的，我也能感同身受。
祝福作者。同时也感谢作者，能把这个世界变得美好一点。

[1]: http://teddysun.com/399.html
[2]: http://teddysun.com/342.html

**Comment by dangelization** [comment]
支持作者。虽然说水平有限不足以做出对SS多大的帮助，但是还是表示感谢！因此也觉得像文件目录之类的琐碎功能其实可以不要那么重视，毕竟意义不大又耗费时间。开发者的时间也是时间啊。另外在用的SS服务器的qq群里也宣传了一下～
后面有时间打算研究下服务器规则的问题

**Comment by wszf5560** [comment]
我的问题是，可否分享下捐助账号呢。说再多感谢也不如给你们买点酒喝来的实际。

**Comment by saintdan** [comment]
一直在用ss，真心感谢你为抵抗愚民运动做出的贡献……
另外，该维权还是维权，对于ssR那种人，就该要求撤销他的项目。

**Comment by saintdan** [comment]
@clowwindy 
就像@wszf5560 说的，能否分享下捐助账号呢，在技术还不足以贡献之前
也能尽点绵薄之力……

**Comment by ahnan4arch** [comment]
@clowwindy  一直以为作者在国外呢,眼前的形势要小心啊,当心当局找你麻烦.

**Comment by 5sq** [comment]
向你说声谢谢。

**Comment by ARwMq9b6** [comment]
ShadowsocksR 作者已将其开源： <https://github.com/breakwa11/shadowsocks-rss/commit/6623ad7806839562055bf7894320e8e628e88f94#diff-0730bb7c2e8f9ea2438b52e419dd86c9R56>

**Comment by zjgood** [comment]
必须对@clowwindy 说声谢谢，不论这个项目最后的生死，毕竟他陪伴我度过了2年的时光，这两年，shadowsocks的成长，也是我的成长。
谢谢你，clowwindy

**Comment by hdstar2009** [comment]
作者加油，我这样的不会写代码只能使用现成的了。不过也算是推广了给几十个玩家使用。

**Comment by jianminLee** [comment]
这就象goagent，一样被某人称作自己的翻wall软件，并且出售！这种人是可耻的！但是既然开源就避免不了这种人。谢谢@clowwindy的劳动成果，让我海阔天空！

**Comment by jannson** [comment]
看到这番话，我是来顶作者的。如果以后我有机会修改SS部分代码，绝不会自己留着。

**Comment by logdns** [comment]
感谢作者，辛苦了。 有句话（抱怨是没用的，一切靠自己） 不要因为其他人和事影响到自己的情绪和判断。加油！！！

**Comment by wanliang1221** [comment]
开放后比较再合并的方法有生命力，闭门造车不可取。

**Comment by azgh** [comment]
尊重作者的劳动成果，鄙视无耻的抄袭，感谢为这个悲催民族提供看世界的丁点曙光。用作者的作品搭建了两个服务器，只给身边的朋友免费使用，改变不了大多数也改变不了大环境，但我还是愿意做睁眼看世界的极少数。这是我所用过软件最稳定的一个，更重要的是这是开源软件，作为一个小白，我一直使用，从未说过感谢，但这次真心说声谢谢，希望作者能继续维护这个项目，不要受老鼠屎影响，做真实的自己。不知作者最初做这个项目的动力是什么，但希望作者，不忘初心。再次对作者的努力与付出表示感谢。

**Comment by zidane1980** [comment]
关键是国内的大部分小白根本就没有要脱离小白程度的这种自觉,简单说就是不求上进,
谁管得了啊,老老实实被人当猪圈养就行了

**Comment by Lazyjason** [comment]
衷心向clowwindy表示感谢。其他的很多事情确实是看在眼里但说了也没什么用，希望不要影响您的心情。

**Comment by azgh** [comment]
刚去看了shadowsocksR，也开源了，也有其自己的说辞，但坚决认为抄袭是断不可取的。无论如何，希望大家多包容，多开放，一定不要闭门造车，既然大家做事情的目标是一致的，那就把大家最好的想法和改进放在一起，服务于更多的人。对于新功能的增加，没必要拒绝，完全可以做分支版本，进行AB测试，哪个版本更受欢迎，就加大努力去做，如果用户的需求是存在的，那强需求会体现出来，那就可以将测试的新功能加入到正式的稳定版本，这样这个项目才会有更长久的生命力。希望作者考虑，现在是集合众人之力，去反抗这堵墙，也希望这些反抗墙的力量能统一起来，而不是相互对抗。

**Comment by clowwindy** [comment]
@azgh 

之前在 [一些 pull request](https://github.com/shadowsocks/shadowsocks-windows/pull/222) 里提过，有一些功能拿不准是改加还是不该加，建议先作为 mod 发布看看用户反响，如果反响好就合并。这样就是一种良性的循环。

也需要大家多反馈，多评论。就拿这个 issue 而言，用户的需求相互产生了冲突，我也很无奈，也想不到如何满足所有的人。如果没有更多的建议和反馈，到最后可能就是加个参数。

**Comment by ljsrzc007** [comment]
看到上面的讨论专门注册了个账号，来对作者说一声感谢的，用了SS大概小半年了，非常赞的程序！同时谴责一下一些人：我们都是支持开源的，我们有共同的强大的敌人，一定程度上我们还是处于明处，我们应该团结起来好吗？

**Comment by schuetzexu** [comment]
@clowwindy 

首先要对你表示衷心感谢，ss对我来说是到现在最为好用的爬墙工具，没有之一。

对于看到的这些现象也确实深感无奈，对于一个文科狗来说，对于这个社区及源代码和编程技术实在是一窍不通，也算是个伸手党，只知道使用，所以还是注册了一个号来对作者表示感谢。但是对你的佩服还是毋庸置疑的，只能之后尽量的多多参与进来，也多一些自己使用中的反馈来表达支持。

再次感谢。

**Comment by fanmli** [comment]
别动不动就整个民族，请问你是那个高贵民族呀！鄙视

**Comment by ahnan4arch** [comment]
凡有五毛存在的民族一定不高贵.

**Comment by fanmli** [comment]
那就赶紧从新投胎换一个民族吧！

**Comment by Acris** [comment]
fanmli 五毛拿好

**Comment by menghan** [comment]
@clowwindy 首先表达感谢，ss项目对大家的帮助有目共睹无须再言。

我觉得你说的问题存在，但这类问题在国外社区也很多。
我之前给一个软件服务端写了 dockerfile 放 github 几个月没管，然后就发现几个其它的代码级 clone 的 repo 出来了，添加了自己的 LICENSE 也没有对我项目的引用。我得承认我没有加 LICENSE 一开始，所以那些 repo 的作者谈不上有错，但他们的道德水平也就是这么回事了。

**Comment by fanmli** [comment]
Acris  作者发泄不满不要把整个民族都带上，现在是不是只要有不同声音，没有和你们一起歌颂就是五毛吧，弱智，现在五毛已经是一些让拿来给发出不同声音的人扣的帽子了！

**Comment by chenshaoju** [comment]
讨论有些离题了。

就针对Portable模式，我还是建议参考其他软件，比如 Tixati （一款BT下载软件），启动的时候会检查程序所在目录有无 tixati_portable_mode.txt 文件，如果有就都往程序自己的目录放。

当然，也可以放在当前目录下的某个新建的目录里，比如 ./bin/ 或 ./tmp/ 等等。

如果要防止是 Dropbox 同步，让用户自己取消一个勾即可：

https://www.dropbox.com/help/175

![screenshot](https://cloud.githubusercontent.com/assets/515763/9352132/6c873e00-4691-11e5-9061-4e2ba2ba2d21.png)

**Comment by clowwindy** [comment]
那么这样是否可行：
1. 存在 shadowsocks_portable_mode.txt，则所有文件都放当前目录（及子目录）下
2. 如果不存在，则保持现在的路径

**Comment by cmheia** [comment]
@chenshaoju 我有些担心检测程序所在目录有没有portable_mode.txt 文件方案的可实现性。之前做MFC的时候试过几个可以获取exe路径的API，它们给出的结果字符串会因为启动exe的方式而不同：在资源管理器里面启动，结果“正确”；添加到注册表的Run，结果错误。我比较倾向使用启动参数：“Shadowsocks.exe -t "dpath"”，这样可以保证结果无差错。使用资源管理器启动的话可以写个批处理，使用注册表/计划任务(可以绕过UAC)也都可以使用参数。

**Comment by Yves-X** [comment]
@clowwindy 

shadowsocks 很顺手，曾经我有过别的需求，但是现在已经得到了满足。
我想说点偏离主题的话。

即使在灯塔国，也是少部分人创造出了大部分价值，然后这些财富造福了公众。
shadowsocks 帮助的人越多，你所可能面对的小白就越多。shadowsocks 越易用，这些小白可能就越不了解我们看来理所当然的规则。

这个世界本来就有各种各样的人，好的坏的，善的恶的，大公无私的匪夷所思的，他们不会因为老了 / 当教师了 / 接触到互联网了，就瞬间变得伟大光荣正确。
很多人受益于你的贡献，他们并不全都那么好。你也明白吧 :)

你看，即使是在此处，你上升到民族的言论，也能引出许多辩论时只会扣帽子的人。
shadowsocks 的用户里，有想捞名利的技术人员，有对开源社区根本不了解的人，有只管自己使用的用户，有只知道照着教程安装好这个就能玩日本页游的玩家，甚至还有首次绕过屏蔽就能向同学讲一周故事的小学生。
他们有的离你近，可以直接抄袭你。有的远，只能靠百度找到图文教程一步一步地使用你的产品，连“大大”在哪儿都不会知道。
影响力越大，就越是形形色色。

但是你正在做的事情正在让一切变好。
门曾经开过，他们想把它关回去。灯一盏一盏地灭掉，但这个项目一直都在。
既然你认为我们落后，那么这个项目让更多人看到了更大的世界，给人进步的可能。
shadowsocks 对我们很重要。

Thank you anyway.
感谢你无私的奉献。

**Comment by schuetzexu** [comment]
@fanmli 民族劣根性和五毛的存在是众人皆知的，否则作者也无需开发这样的软件。连一些简单的批评都不能容忍，只能把你归为墙内权贵的同类。自己要让别人重新投胎，还真把这个国当成你自己的了，你国还真是适合你。

**Comment by AnyoeDove** [comment]
shadowsocks_portable_mode.txt可以一试 或者config里面portable_mode“1”指定为便携模式如何？

另外楼上的谈政治谈民族劣根性的自己有想法请去其他场所 这里是Github

**Comment by thundery1** [comment]
@clowwindy  必须来感谢下,虽然用的很少..没有你们的付出,追求自由将需要更大的努力.

**Comment by Bronts** [comment]
@fanmli 看了下你的资料发现你是刚注册的账号，你这个来源真是让人遐想。

另外感谢@clowwindy所做的开源工作，祝好。

**Comment by jaywen** [comment]
只是来说下谢谢。作为小白只能做到不伸手，问问题描述清楚，感谢回复者，解决后把方法下出来。其他的帮不上

**Comment by fanmli** [comment]
s@chuetzexu @Bronts  动不动就民族劣根性有意思吗？，我是在墙内，我是从V2EX 看帖子来的，就因为用作者开发的软件他就可以动不动整个民族劣根性我就要听吗？

**Comment by dangelization** [comment]
你可以不听，但是随便用投胎来骂人？妈妈教我们要懂礼貌的：)现在没什么人提鲁迅了，是消失还是被消失了？什么也好，都有缺点，民族有劣根性就不让提了，那也就不用翻墙了。况且这也不是作者提出的。
投胎这个说法其实就是无理搅三分，假定所谓天堂佛国真的存在，谁不愿意投胎过去？即便差一些，喊一喊我的爸爸是李刚也是很爽的。我话说在这，你要告诉人现在自杀立刻投胎美帝中产阶级，中国多少人都要自杀的。中国富人多移民，你是不是也要叫他们去投胎？最看不惯你这种胡乱骂人的。
On Aug 19, 2015 7:06 PM, fanmli <notifications@github.com> wrote:s@chuetzexu @Bronts  动不动就民族劣根性有意思吗？，我是在墙内，我是从V2EX 看帖子来的，就因为用作者开发的软件他就可以动不动整个民族劣根性我就要听吗？

**Comment by AnyoeDove** [comment]
@clowwindy 建议重开issue然后把这个close吧

**Comment by Junzki** [comment]
@wszf5560 赞！

**Comment by chenshaoju** [comment]
@cmheia 这么说我倒想起一个事情，一些软件在Portable模式下，是无法设置为开机启动或文件关联的。

估计就是这个原因，可以借鉴一下，如果是Portable模式，则禁用开机自动启动。

**Comment by clowwindy** [comment]
测试了一下 portable 模式下自动启动没有问题，启动后也确实是 portable 模式。

**Comment by clowwindy** [comment]
2.5.6 已发。

我在工作中得到的全部经验告诉我，没有 QA 团队就意味着很差的稳定性。不像 Python 版那样每个功能都有完整的单元测试，这个版本因为以 GUI 为主，几乎只能靠每次发版前手工测一遍，所以我一直没有敢频繁的发版。

然而现在发现，很多用户其实不在意这一点。只要功能多，稳定性差一点也没关系。所以以后发版前可能就简单的测一下能不能开关翻墙，其它的就靠大家反馈了。感谢各位。

另一个问题是检查更新可能会打扰到不想频繁更新的用户。所以可能会加一个是否检查更新的开关。

**Comment by myliyifei** [comment]
建议增加一个 检查是否更新的开关。我现在就停留在2.4的版本，因为我感觉大版本引入新的功能之后，一般都是过一段时间才会稳定

在 2015年8月19日 下午10:32，clowwindy <notifications@github.com>写道：

**Comment by netroby** [comment]
能不能自带更新下载功能啊。每次手动下载，好烦躁，好繁琐。

**Comment by netroby** [comment]
或者开不同的channel， stable channel, beta channel, alpha channel.

**Comment by clowwindy** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/301

**Comment by w2jmoe** [comment]
用SS大半年多、很喜欢，感谢clowwindy兄做了这么久... :P
国内是这样了...尊重和共享大多围绕利益转...
不能决定他人...这是个运气问题。

**Comment by zhiopi** [comment]
@clowwindy 这种抄袭小人是无处不在的，他的目的就是想靠这软件发财，C大完全不用在意这种人，您只要知道您做的是一件造福国人的好事就行了。如果您不更新软件，他那边闭源又不断更新软件，到时候用户转过他那边去这软件迟早被他拿来卖钱，您就中他计了。只要您更新一天软件他就不敢把软件拿来卖钱，像他这种人时间长了搞不到钱他还会有动力follow这项目？自然就滚蛋了。我刚开始学编程，等我学成了我也希望能加入这项目为大家出力。另外必要的手段还是要有的，他闭源您就向GITHuB反应关他站，他抄您的源码加功能您也可以扒拉他的源码加同样的功能，搞个BETA版就是了，绝对不能让这种小人占了上风。

**Comment by Big-Fool** [comment]
别那么心灰意冷啊, 你的项目惠及了那么多人, 你做的肯定是一件好事.
不了解这个圈子, 不过哪里都一样, "有人的地方就有江湖", 江湖里的事, 就那么回事吧...

说到国内的绝大部分论坛(各种类别的), 印象中是10几年前就开始坏了风气的, 起因大概是因为争相凑人气点击回帖什么的拉广告拉风投之类的.
折腾到现在, 大都没有正经交流的氛围, 然后一拨又一拨新晋的网民认为这就是正常的, 然后就不断继承下来了, 估计能算特色文化了, 也就这样了.
横向看国外的论坛, 干湿货的比例, 跟国内是反着来的(有想喷我的,先自己搞清楚去验证下), 这也是为什么我要翻墙去查资料/翻墙给手机挂g邮箱, 不是想反谁反谁的, 我就草了这墙...没事都要折腾出有事来...

另外, 
"...
然而现在发现，很多用户其实不在意这一点。只要功能多，稳定性差一点也没关系。所以以后发版前可能就简单的测一下能不能开关翻墙，其它的就靠大家反馈了。感谢各位。
..."
这个么, 个人感觉哈, 这种兴趣项目,能照顾到部分的重要需求就足够了. 目前又不是在做商用产品, 没必要比这个比那个的, 你的优势在于,核心功能是你的. 
时间/精力/兴趣/心情限制的话, 那就想法调整下呗, 还是那句话, 别心灰意冷. 
(我现在升到v2.6.2就没动过了, 不管糙不糙, 自己这里好用就行)

术业有专攻, 可惜自己对这行什么都不懂,帮不上忙, 只好嘴上支持下...期望能给你打打气.  
对你这个项目一直心存感激, 不管未来如何吧, 还是谢谢你了.

**Comment by yaoguaishou** [comment]
我来地图炮：小白就是小白，大大说了几句话你们就是一边倒。还开始撕逼了
这才是民族的根劣性！

**Comment by koy1619** [comment]
没有SS我的工作就没法顺利进行，再次感谢作者@clowwindy 支持！希望你能早日肉翻！

**Comment by yangyaofei** [comment]
@clowwindy  其实很想贡献点什么，但是确实能力有限，现在连源码还没读懂………

**Comment by yanlinlin82** [comment]
看了上面的评论，不管是大牛的还是其它小白的，感触颇多！我个人没资格批评大环境，但我确实还是向往一个好的大环境的，所以觉得：总要有人前仆后继，那就先从自己开始提升，让自己先具备去前仆后继的资格。

**Comment by CzBiX** [comment]
@cmheia 你提到的这个问题应该是由于依赖起始位置的原因，参考 http://stackoverflow.com/a/15334757/2806903 。

**Comment by hypogaea** [comment]
一直在找原版啊，以前不怎么熟悉Github，不太了解这个branch是个什么意思，现在明白点儿了。一般来说我是不怎么喜欢用各种软件的所谓修改版和MOD的，因为ShadowsocksR比较好找，一下子就找到了，于是用了好久。今天既然终于找到原版了，我就不会再去用R版了。

**Comment by hldh214** [comment]
早日肉翻, 共勉

**Comment by TestSmirk** [comment]
满一年了快

**Comment by hkvsak** [comment]
早日肉翻 ！

**Comment by tomgeniewang** [comment]
看了下来龙去脉，首先当初SSR闭源肯定是不对的，对于作者在创作以及维护原本ss的贡献衷心感谢。但是当初 @breakwa11 似乎有发过pull request 要求在PC端加什么UDP被作者以不如在路由端加而拒绝的经历，而作者在牢骚贴中未予提及事后也未予确认。而且作者在发现 @breakwa11 当初违反GPL时既没有跟GitHub要求下撤，也没有联系 @breakwa11要求其开源，只是在这里发了一些挖苦讽刺的言语，这也属奴性思维之一，也是助长独裁的重要因素之一。现在SSR还在继续，而且似乎成为了流传最广的版本，确实出于一个经济学专业的女大学生，说来也不得不觉得讽刺。我觉得这事件里有一点我觉得对于许多专业人员（不仅限于编程），很不对的一点就是许多专业人士并没有注重用户需求，或者说本身并没有嗅探用户需求的能力还自以为是的认为这没必要那没必要，这就很不好。我觉得在自己收到PR时如果觉得没必要可以说自己无需使用这种功能，而且也无兴趣开发此功能，而且也应该鼓励别人开发此功能，如果忙也可以直接无视不回复，一定不可以用自己的需求代表别人的需求而说没必要，况且作者既然已经选择花费时间回复，选择positive的回复岂不是会更好。

**Comment by wongsyrone** [comment]
It's a well-discussed topic, locked for historic interest.
