### ISSUE TITLE
OneDrive windows客户端支持

### ISSUE THREAD

**Issue by zjt9101** [shadowsocks/shadowsocks-windows#2930]
### 简要描述问题
OneDrive似乎不走shadowsocks，即便设置成全局模式、或者使用proxifier也不行。无法sync。请问怎么解决？
### 环境

- Shadowsocks客户端版本：4.1.10.0
- 操作系统版本：Windows 10
- .NET版本：4.8

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by studentmain** [comment]
怪，我的 OneDrive 就走

**Comment by chenshaoju** [comment]
请确保使用了PAC模式，且更新GFWList到最新。

如果仍然不行，请尝试自定义PAC用户规则，增加以下域名的代理：
https://docs.microsoft.com/en-us/onedrive/required-urls-and-ports

**Comment by GHumorBS** [comment]
Good question!

**Comment by zjt9101** [comment]
Already solved. Thank you!
