### ISSUE TITLE
TIME OUT CONNECTIONS ON WINDOWS SERVER 2012 #2744

### ISSUE THREAD

**Issue by javadb76** [shadowsocks/shadowsocks-windows#2932]
What version of shadowsocks-libev are you using?
LATEST

What operating system are you using?
WINDOWS SRVER 2012

What did you do?
clean install shadowsocks server

What did you expect to see?
working fine!

What did you see instead?
connections in log says : 2020-08-10 06:12:18 INFO connecting ip:port from
but it stays connecting and wont finish and given a time out at the end.

What is your config in detail (with all sensitive info masked)?
no changes, clean install

**Comment by chenshaoju** [comment]
Please using these 3rd-party services check your server connectability: http://ip100.info/check

**Comment by javadb76** [comment]
Domestic test
Connect via Tencent Cloud: 176.9.178.61: closed
International test
Through foreign connections: 176.9.178.61: closed


what is this and how can i fix it?

**Comment by javadb76** [comment]
already checked another ip that is working fine but the website given says ip: closed too.

**Comment by chenshaoju** [comment]
That meaning your server is unusable, usually is your server not configure firewall (e.g. iptables) or Shadowsocks services not started.

It should look like this:
![image](https://user-images.githubusercontent.com/515763/89969951-3b7f0880-dc8a-11ea-9a56-450b5f2eecbd.png)

PS: This is an example.

**Comment by javadb76** [comment]
connections from clients are accepted at my server. but my server cannot connect to the servers that client requests!

connections from my server wont get established and i get timed out in server

the port that client connects to server is open and working there is something wrong in server end.

firewall Off. antivirus off. WONT WORK!

**Comment by chenshaoju** [comment]
Please using tcping.exe ( https://www.elifulkerson.com/projects/tcping.php ) test the connectability from your windows server.

this is a command-line tool,you need run it under cmd.exe or powershell. example:
```
tcping -t 123.45.67.89 9876
```
