### ISSUE TITLE
加密协议不支持none

### ISSUE THREAD

**Issue by MapleHousezz** [shadowsocks/shadowsocks-windows#2936]
### 环境

- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1780

**Comment by MapleHousezz** [comment]
好的，谢谢解答。
