### ISSUE TITLE
校园网环境服务器丢包严重，延迟高

### ISSUE THREAD

**Issue by Wangnibaba** [shadowsocks/shadowsocks-windows#2938]
### 简要描述问题
在校园网中，我的vps延迟超过5s，丢包率最大50%以上，如果是VPN网络则正常使用，而vps服务器则存在问题。
### 环境

- Shadowsocks客户端版本：4.1.10.0
- 操作系统版本：Windows10 1909
- .NET版本：4.x

### 操作步骤
shadowsocks加simple-obfs插件，手机电脑延迟都高，换成其他网络则正常

### 期望的结果
降低服务器延迟和丢包

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
你好，Shadowsocks需要依赖互联网本身传递数据，如果网络本身极端不稳定，那么可能没有较好的方法来优化网络。

你可以尝试在服务端配置以下 sysctl.conf ，不一定有效：https://gist.github.com/chenshaoju/b0e20f23efabb8eb2cd4 。

**Comment by DuckSoft** [comment]
世界加钱可及，不行就套个 kcptun、试试楼上老兄的方法，再不行应该就没救了。
