### ISSUE TITLE
4.1.9.3版本的windows如何添加订阅地址

### ISSUE THREAD

**Issue by Draven-1** [shadowsocks/shadowsocks-windows#2939]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2928

**Comment by samshum2** [comment]
HI ,  I want to know linux client how to connect the ss server?
你好,想請教一下linux 客戶端如何連伺服器端？
我試不過同相同  config 去試 （ server ip換成server ip），但報錯：
    server_socket.bind(sa)
OSError: [Errno 99] Cannot assign requested address

**Comment by chenshaoju** [comment]
Linux（libev？）请移步：https://github.com/shadowsocks/shadowsocks-libev/issues
