### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

### ISSUE THREAD

**Issue by Ramon403** [shadowsocks/shadowsocks-windows#294]
System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.PortForwarder.Handler.Start(Byte[] firstPacket, Int32 length, Socket socket, Int32 targetPort)

**Comment by chenshaoju** [comment]
查了一下，0x80004005 的含义是“未指定的错误”。
在 Shadowsocks.Controller.PortForwarder.Handler.Start 出现问题的话，可能和Windows网络栈有关，建议尝试：
https://github.com/shadowsocks/shadowsocks-windows/issues/247#issuecomment-131392491

看看是否可以解决。

**Comment by Ramon403** [comment]
看了#247 在想有可能的原因是 安装了其它代理工具,或者有其它网络程序影响了系统的网络设置

后来发现卸载了迅雷快鸟后恢复正常了

我是win10 x64
