### ISSUE TITLE
关于SS和L2TP不能同时启用

### ISSUE THREAD

**Issue by AHikari** [shadowsocks/shadowsocks-windows#2941]
### 简要描述问题
近几日我通过L2TP连接服务器后发现SS不能正常工作， 在9.1号之前印象里是可以的但是自从那天我收到关于本地运营商崩溃后紧急修复这个消息后就不行了，不知是SS本身出bug还是我的电脑有问题，虽然已经重装过三次了，希望能指点一下问题。
### 环境

- Shadowsocks客户端版本：
- 操作系统版本：2004 win10
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
请尝试使用最新版本的SS，同时将你的L2TP拨号连接设置为英文，连接成功后再启动SS试试。

**Comment by AHikari** [comment]
> 请尝试使用最新版本的SS，同时将你的L2TP拨号连接设置为英文，连接成功后再启动SS试试。

非常感谢，问题已经解决
