### ISSUE TITLE
讨论交流一下： 有没有人知道怎么在tor浏览器里面连接shadowsocks?

### ISSUE THREAD

**Issue by asdfj2381k** [shadowsocks/shadowsocks-windows#2943]
tor的流量有特征，访问很多网站会受到特殊的干扰。

所以我想打开tor之后，在末尾，再加一层shadowsocks节点，以用于加速。

我想要的是： tor+ss 而不是ss+tor，   ss是放在最后面的。

不知道各位能听明白我的意思吗？ 

如果有人知道怎么做，希望可以指点一下，谢谢。

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/92303176-0355a780-ef62-11ea-9eb8-3a10cfe98324.png)

**Comment by asdfj2381k** [comment]
@studentmain  老哥， 搞反了。
   你截图的这个设置，是把ss作为前置代理。  而我需要的是把ss作为**后置**代理

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/92303362-85929b80-ef63-11ea-9306-8126809014b4.png)

**Comment by KevinZonda** [comment]
tor listens 127.0.0.1:9050 as socks5.

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/92304407-3161d880-efb0-11ea-8ca1-d8f483e9b3a2.png)

我测试了一下， 9150这个端口好像不通，这是为什么呢。
 9050也试了，不行。
