### ISSUE TITLE
Windows SS client log shows errors System.Net.Sockets.SocketException (0x80004005)

### ISSUE THREAD

**Issue by slrslr** [shadowsocks/shadowsocks-windows#2944]
Last days it worked, but since today not.
I click to connect the server (Ubuntu 16) in Windows's 10 ShadowSocks 4.x . The client log says "Shadowsocks started", server log adds no entries into /var/log/shadowsocks.log
On server and client i do not see any established SS connection.
When i try to browse internet page, the client log always add new entry:
```
System.Net.Sockets.SocketException (0x80004005): Operace, o níž jste se pokusili, není podporována pro tento typ odkazovaného objektu
   v System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e)
   v System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   v Shadowsocks.Util.Sockets.WrappedSocket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   v Shadowsocks.Proxy.DirectConnect.BeginConnectDest(EndPoint destEndPoint, AsyncCallback callback, Object state)
   v Shadowsocks.Controller.TCPHandler.ProxyConnectCallback(IAsyncResult ar)
```

the non english text free translation: "The operation you attempted is not supported for this type of referenced object"

What i tried:
- restarting SS client and SS server app.
- Disabling firewall on client and flushing firewall on server
- trying to use different local port 108x
- tried to stop all client network interfaces & start these again

**Comment by chenshaoju** [comment]
This issue maybe case by TCP/IP Protocol stack or Winsock, Please start CMD or PowerShell in Administrator, And execute these command:
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
And reboot the computer.

**Comment by slrslr** [comment]
Thanks so much for help. That worked, shutdown shadowsocks client, click windows button in bottom bar, type "cmd" right click the found Command line entry and select to open it with admin rights. Paste your commands one by one. I was warned i must reboot, but shadowsocks started working right away. I guess there is no way to prevent this or let the SS client detect this issue and post some more noob friendly guide on what to do...
