### ISSUE TITLE
最新4.2.0.0 PAC模式失效，所有流量走的国外。

### ISSUE THREAD

**Issue by LovElizabeth** [shadowsocks/shadowsocks-windows#2947]
已经更新pac文件等等，分流失效了，希望作者解决一下

**Comment by chenshaoju** [comment]
测试了一下，无法复现。

请尝试退出SS，删除 Shadowsocks.exe 目录下的 pac.txt 文件，然后再启动SS即可，会自动重新下载 pac.txt 。

**Comment by LovElizabeth** [comment]
> 测试了一下，无法复现。
> 
> 请尝试退出SS，删除 Shadowsocks.exe 目录下的 pac.txt 文件，然后再启动SS即可，会自动重新下载 pac.txt 。

应该是原文件没删干净，现在正常了，感谢回复。

**Comment by chenshaoju** [comment]
👌
