### ISSUE TITLE
Shadowsocks 错误：端口1080是系统保留端口

### ISSUE THREAD

**Issue by EricMzky** [shadowsocks/shadowsocks-windows#2948]
windows10 2004v 企业版，4.2.0.0版本小飞机，重启电脑后经常报该错误。
![Snipaste_2020-09-13_10-18-41](https://user-images.githubusercontent.com/37823382/93008736-e1d06d80-f5aa-11ea-9764-54f3a999bd29.png)

**Comment by chenshaoju** [comment]
你是不是装了Hyper-V？https://github.com/shadowsocks/shadowsocks-windows/issues/2630#issuecomment-549660292

**Comment by EricMzky** [comment]
> 你是不是装了Hyper-V？https://github.com/shadowsocks/shadowsocks-windows/issues/2630#issuecomment-549660292

不是很明白！

**Comment by chenshaoju** [comment]
以管理员身份运行这个命令，重启即可：
```
reg add HKLM\SYSTEM\CurrentControlSet\Services\hns\State /v EnableExcludedPortRange /d 0 /f
```

**Comment by EricMzky** [comment]
> 以管理员身份运行这个命令，重启即可：
> 
> ```
> 
> reg add HKLM\SYSTEM\CurrentControlSet\Services\hns\State /v EnableExcludedPortRange /d 0 /f
> 
> ```

十分thank油！

**Comment by EricMzky** [comment]
> 以管理员身份运行这个命令，重启即可：
> 
> ```
> 
> reg add HKLM\SYSTEM\CurrentControlSet\Services\hns\State /v EnableExcludedPortRange /d 0 /f
> 
> ```

哈咯，尝试过你发的命令。但是现在又出来啦，没有用啦。该怎么解决！谢谢！

**Comment by chenshaoju** [comment]
换个端口吧，在编辑服务器界面右下角，有个代理端口，换一个看看，比如 10800 ？

**Comment by EricMzky** [comment]
> 换个端口吧，在编辑服务器界面右下角，有个代理端口，换一个看看，比如 10800 ？

好嘞，晚上回去试一下。谢谢～

**Comment by xxxifan** [comment]
之前用的好好的，今天突然弹了这个提示

**Comment by chshch** [comment]
> 你是不是装了Hyper-V？[#2630 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2630#issuecomment-549660292)

我也是装了hyper-v后出现的这个弹出窗口
通过在编辑服务器界面右下角，有个代理端口，换成10800后搞定
