### ISSUE TITLE
shadowsocks无法使用

### ISSUE THREAD

**Issue by a506534997** [shadowsocks/shadowsocks-windows#2949]
### 简要描述问题
校园网环境，一开始可以使用，但是昨天我修改了系统hosts想试一试不通过ss直接用ipv6连接YouTube等网页，发现无法使用后恢复了hosts，但是发现shadowsocks不能使用了，更新过版本，重置过网络，各种方法，现在是就算打开全局模式，网络也不经过shadow socks，只有更新pac的时候任务栏的图标才会有网络使用的样子。
### 环境

- Shadowsocks客户端版本：4.2.0.0
- 操作系统版本：win10
- .NET版本：4.0.30319

**Comment by studentmain** [comment]
手动设置一下系统代理？

**Comment by a506534997** [comment]
> 手动设置一下系统代理？

怎么弄呀

**Comment by chenshaoju** [comment]
请检查一下你校园网的拨号连接是不是中文的名字（如：“宽带连接”），如果是，请改个英文的，比如改成“PPPoE”。

**Comment by a506534997** [comment]
> 请检查一下你校园网的拨号连接是不是中文的名字（如：“宽带连接”），如果是，请改个英文的，比如改成“PPPoE”。

我看过之前有个issue里那些方法了，都试过，不太行，我已经改成英文也不可以。
之前是没问题的，但是我昨天改了下hosts之后怎么弄都不可以了，弄成全局模式也不经过代理。

**Comment by chenshaoju** [comment]
理论上Hosts不太可能导致该问题，如果删除Hosts呢？

另外，SS的日志中有什么提示吗？

**Comment by a506534997** [comment]
> 理论上Hosts不太可能导致该问题，如果删除Hosts呢？
> 
> 另外，SS的日志中有什么提示吗？

我去试试，不过我今天删过好几次ss重装了

**Comment by a506534997** [comment]
> 理论上Hosts不太可能导致该问题，如果删除Hosts呢？
> 
> 另外，SS的日志中有什么提示吗？

2020-09-13 14:23:41.0009|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=7yphzTT5xnF7k9IjFrUCqA2&secret=ERaZo7-mI-G2kO83Qf8c466rmn3zF162mlh1MCXhytg1
2020-09-13 14:23:41.1459|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.2.0.0)
2020-09-13 14:23:41.1459|DEBUG|Shadowsocks.Encryption.Sodium|sodium: AES256GCMAvailable is True
2020-09-13 14:23:41.1459|DEBUG|Shadowsocks.Controller.Listener|
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

2020-09-13 14:23:43.8750|INFO|Shadowsocks.Controller.UpdateChecker|Checking updates...
2020-09-13 14:23:43.8960|DEBUG|Shadowsocks.Controller.TCPHandler|connect to api.github.com:443
2020-09-13 14:23:44.2223|DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: us-1.v2speed.net:60411
2020-09-13 14:23:47.0339|INFO|Shadowsocks.Controller.UpdateChecker|No update is available
2020-09-13 17:02:41.8027|DEBUG|Shadowsocks.Controller.AutoStartup|Register restart after system reboot, command line:
2020-09-13 17:02:41.9758|INFO|Shadowsocks.Controller.I18N|Current language is: zh-CN
2020-09-13 17:02:42.1758|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=7yphzTT5xnF7k9IjFrUCqA2&secret=uq8JgwXoRnpNJKszCHIHg5TmjjfQ1M3wEzXPWgW9xrw1
2020-09-13 17:02:42.3398|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.2.0.0)
2020-09-13 17:02:42.3398|DEBUG|Shadowsocks.Encryption.Sodium|sodium: AES256GCMAvailable is True
2020-09-13 17:02:42.3398|DEBUG|Shadowsocks.Controller.Listener|
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

2020-09-13 17:02:45.0163|INFO|Shadowsocks.Controller.UpdateChecker|Checking updates...
2020-09-13 17:02:45.0373|DEBUG|Shadowsocks.Controller.TCPHandler|connect to api.github.com:443
2020-09-13 17:02:45.0854|DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: us-1.v2speed.net:60411
2020-09-13 17:02:46.2203|DEBUG|Shadowsocks.Controller.TCPHandler|connect to api.github.com:443
2020-09-13 17:02:46.5317|DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: us-1.v2speed.net:60411
2020-09-13 17:02:48.6817|INFO|Shadowsocks.Controller.UpdateChecker|No update is available
2020-09-13 17:03:27.4314|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.2.0.0)

**Comment by a506534997** [comment]
> 理论上Hosts不太可能导致该问题，如果删除Hosts呢？
> 
> 另外，SS的日志中有什么提示吗？

把hosts删了又试了试 还是不可以 感觉和我看的那个问题差不多 也是校园网拨号 但是他们的方法我弄了都不行。奇怪的是全局模式打开网站都不走ss

**Comment by chenshaoju** [comment]
你有Firefox吗？如果有，手动指定代理看看？

请注意，下图中的10800是距离，需要修改为本地的实际代理端口，默认为1080：

![image](https://user-images.githubusercontent.com/515763/93041733-d8fd9b80-f67f-11ea-9c6a-70c0773adbff.png)

**Comment by a506534997** [comment]
> 你有Firefox吗？如果有，手动指定代理看看？
> 
> 请注意，下图中的10800是举例，需要修改为本地的实际代理端口，默认为1080：
> 
> ![image](https://user-images.githubusercontent.com/515763/93041733-d8fd9b80-f67f-11ea-9c6a-70c0773adbff.png)

我现在是chrome 等我下一个试试

**Comment by a506534997** [comment]
> > 你有Firefox吗？如果有，手动指定代理看看？
> > 请注意，下图中的10800是举例，需要修改为本地的实际代理端口，默认为1080：
> > ![image](https://user-images.githubusercontent.com/515763/93041733-d8fd9b80-f67f-11ea-9c6a-70c0773adbff.png)
> 
> 我现

> 你有Firefox吗？如果有，手动指定代理看看？
> 
> 请注意，下图中的10800是举例，需要修改为本地的实际代理端口，默认为1080：
> 
> ![image](https://user-images.githubusercontent.com/515763/93041733-d8fd9b80-f67f-11ea-9c6a-70c0773adbff.png)

我用俩节点都试过了，用火狐打开百度显示无法连接

**Comment by chenshaoju** [comment]
在上图Firefox配置的情况下，SS的日志里显示什么？

**Comment by a506534997** [comment]
> 在上图Firefox配置的情况下，SS的日志里显示什么？

![image](https://user-images.githubusercontent.com/57380415/93348558-f3469d80-f868-11ea-92dc-cf87155b51e0.png)

**Comment by chenshaoju** [comment]
日志中什么都没有，看起来就像你的Firefox并没有走代理。

如果你的Firefox没有安装代理插件接管代理的话，可能和你的协议栈或网络栈受损有关。

请以管理员身份启动命令提示符（cmd.exe）或PowerShell，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重启计算机看看。

**Comment by a506534997** [comment]
> 日志中什么都没有，看起来就像你的Firefox并没有走代理。
> 
> 如果你的Firefox没有安装代理插件接管代理的话，可能和你的协议栈或网络栈受损有关。
> 
> 请以管理员身份启动命令提示符（cmd.exe）或PowerShell，然后执行：
> 
> ```
> netsh interface ipv4 reset
> netsh interface ipv6 reset
> netsh interface tcp reset
> netsh winsock reset
> ```
> 
> 一行一回车，四行执行完毕后重启计算机看看。

之前看您在别的贴子也这样建议过 我之前就试过，刚才又试了一遍，还是不行啊。而且我还换过v2ray什么的，也是不可以

**Comment by chenshaoju** [comment]
如果在编辑服务器界面右下角代理端口更换一个端口看看呢？比如更换为10800？

**Comment by a506534997** [comment]
> 如果在编辑服务器界面右下角代理端口更换一个端口看看呢？比如更换为10800？

也试过了 不行 哎

**Comment by chenshaoju** [comment]
换了端口以后，Firefox还是不行？

如果可能，检查一下系统自带的网络防火墙？

**Comment by a506534997** [comment]
> 换了端口以后，Firefox还是不行？
> 
> 如果可能，检查一下系统自带的网络防火墙？

我把防火墙全关掉了也不行，我真晕掉了，不知道该怎么办了，要不您远程帮我弄一下？真的好烦

**Comment by chenshaoju** [comment]
出于安全考虑，我无法提供远程支持。。。只能猜测可能和系统有关。

**Comment by a506534997** [comment]
> 出于安全考虑，我无法提供远程支持。。。只能猜测可能和系统有关。

谢谢谢谢，真的好烦，也不舍得重新装一遍系统

**Comment by a506534997** [comment]
> 出于安全考虑，我无法提供远程支持。。。只能猜测可能和系统有关。

我重装了边系统，又遇到问题了，现在是用edge，需要全局模式才能翻墙，如果用chrome，全局模式也翻不了，打开百度等网页，ss也没有上下流量的动画，说明它什么都没经过ss

**Comment by chenshaoju** [comment]
请尝试做个测试，右击任务栏的纸飞机图标，选择PAC，再点击 从GFWList（Geosite）更新本地PAC，是否能提示更新成功？

如果是出错，错误是什么？日志中显示什么？

**Comment by a506534997** [comment]
> 请尝试做个测试，右击任务栏的纸飞机图标，选择PAC，再点击 从GFWList（Geosite）更新本地PAC，是否能提示更新成功？
> 
> 如果是出错，错误是什么？日志中显示什么？

我重装系统后印象里是更新过的，更新成功了，我明天再试试！真的谢谢

**Comment by a506534997** [comment]
> 请尝试做个测试，右击任务栏的纸飞机图标，选择PAC，再点击 从GFWList（Geosite）更新本地PAC，是否能提示更新成功？
> 
> 如果是出错，错误是什么？日志中显示什么？

我印象里是昨天更新成功过的，今天又点了下更新，虽然没提示但是看见纸飞机有上下流量的箭头

**Comment by a506534997** [comment]
> 你有Firefox吗？如果有，手动指定代理看看？
> 
> 请注意，下图中的10800是举例，需要修改为本地的实际代理端口，默认为1080：
> 
> ![image](https://user-images.githubusercontent.com/515763/93041733-d8fd9b80-f67f-11ea-9c6a-70c0773adbff.png)

你好，非常抱歉，我当时理解错端口的意思，以为是服务器端口代码。我后来看了别的issue才知道是代理端口代码，所以我又试了下火狐，发现修改端口后可以打开谷歌等。

**Comment by a506534997** [comment]
> 你有Firefox吗？如果有，手动指定代理看看？
> 
> 请注意，下图中的10800是举例，需要修改为本地的实际代理端口，默认为1080：
> 
> ![image](https://user-images.githubusercontent.com/515763/93041733-d8fd9b80-f67f-11ea-9c6a-70c0773adbff.png)

所以现在是，firefox按照您说的方法，可以访问谷歌，edge必须开全局模式才能访问谷歌，chrome开全局模式也访问不了谷歌。

**Comment by chenshaoju** [comment]
你确定你的拨号连接使用的是英文名字吗？
![image](https://user-images.githubusercontent.com/515763/93553401-72d98700-f9a5-11ea-8b4d-9577071beb45.png)

**Comment by a506534997** [comment]
> 你确定你的拨号连接使用的是英文名字吗？
> ![image](https://user-images.githubusercontent.com/515763/93553401-72d98700-f9a5-11ea-8b4d-9577071beb45.png)

![image](https://user-images.githubusercontent.com/57380415/93553589-eed3cf00-f9a5-11ea-85ba-728c0992a34b.png)
就那个以太网，我改成了英文的，我也是校园网

**Comment by chenshaoju** [comment]
那应该不是这个问题，我以为你的校园网是那种需要拨号的校园网。

请尝试做个测试，将这个文件覆盖到 shadowsocks.exe 所在的目录，然后切换到PAC模式（已经是PAC模式了也再点一下）。

然后用系统自带的IE浏览器看能否访问 google.com ？
[pac.txt](https://github.com/shadowsocks/shadowsocks-windows/files/5243341/pac.txt)

注意：请确保 Shadowsocks.exe 的代理端口是 10800 端口。

**Comment by loyess** [comment]
@a506534997  

电脑进入安全模式，卸载Chrome浏览器，然后重启开机，正常安装Chrome 「 最好官网下载Chrome 离线包，这样不必依赖外网环境 」，应该就能使用SS的代理了。

另一方案是，搭配Chrome的代理插件 SwitchyOmega    ，直接走本地的1080端口设置socks5或http代理使用。

**Comment by a506534997** [comment]
> 那应该不是这个问题，我以为你的校园网是那种需要拨号的校园网。
> 
> 请尝试做个测试，将这个文件覆盖到 shadowsocks.exe 所在的目录，然后切换到PAC模式（已经是PAC模式了也再点一下）。
> 
> 然后用系统自带的IE浏览器看能否访问 google.com ？
> [pac.txt](https://github.com/shadowsocks/shadowsocks-windows/files/5243341/pac.txt)
> 
> 注意：请确保 Shadowsocks.exe 的代理端口是 10800 端口。

按照你说的还是不可以，代理端口也改成10800了。

**Comment by a506534997** [comment]
> @a506534997
> 
> 电脑进入安全模式，卸载Chrome浏览器，然后重启开机，正常安装Chrome 「 最好官网下载Chrome 离线包，这样不必依赖外网环境 」，应该就能使用SS的代理了。
> 
> 另一方案是，搭配Chrome的代理插件 SwitchyOmega ，直接走本地的1080端口设置socks5或http代理使用。

问题是现在edge也是开全局才能到谷歌，pac也不可以

**Comment by chenshaoju** [comment]
请打开 Internet Explorer ，点击齿轮，再点击 Internet 选项，然后按照下图红色箭头的指示打开代理对话框。

蓝色箭头所指的部分是什么样子的？

![image](https://user-images.githubusercontent.com/515763/93556425-49235e80-f9ab-11ea-8b32-5d91cad7f4d5.png)

**Comment by a506534997** [comment]
> 请打开 Internet Explorer ，点击齿轮，再点击 Internet 选项，然后按照下图红色箭头的指示打开代理对话框。
> 
> 蓝色箭头所指的部分是什么样子的？
> 
> ![image](https://user-images.githubusercontent.com/515763/93556425-49235e80-f9ab-11ea-8b32-5d91cad7f4d5.png)

![image](https://user-images.githubusercontent.com/57380415/93556667-d8c90d00-f9ab-11ea-9225-cc4affcdd242.png)
http://127.0.0.1:10800/pac?hash=PD44uNABWVqmYsX3r_hk4w2&secret=VRBfFg7lXZthFGJbN8I4swjG8r0VSdjeFjtBxT1EtdQ1

**Comment by chenshaoju** [comment]
这种情况下，IE浏览器也不能访问 Google ？

**Comment by a506534997** [comment]
> 这种情况下，IE浏览器也不能访问 Google ？

不能，开了全局模式也不可以，改了代理端口也不行。现在只有edge开全局模式可以，firefox用你说的方法也可以。

**Comment by chenshaoju** [comment]
请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt ，然后右击任务栏托盘区的纸飞机图标，选择PAC，再点击从Geosite更新本地PAC看看？

这个问题看起来好像未知，我这儿两台Win10的机器都没有问题。。。

**Comment by a506534997** [comment]
> 请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt ，然后右击任务栏托盘区的纸飞机图标，选择PAC，再点击从Geosite更新本地PAC看看？
> 
> 这个问题看起来好像未知，我这儿两台Win10的机器都没有问题。。。

还是不可以呀。我也是之前一点问题也没有，然后改了下hosts就变成这样了，也是刚开学。

**Comment by a506534997** [comment]
> 请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt ，然后右击任务栏托盘区的纸飞机图标，选择PAC，再点击从Geosite更新本地PAC看看？
> 
> 这个问题看起来好像未知，我这儿两台Win10的机器都没有问题。。。

![image](https://user-images.githubusercontent.com/57380415/93562053-de2c5480-f9b7-11ea-9489-0d72fdaad0be.png)
跟这个校园网客户端有关系吗

**Comment by chenshaoju** [comment]
你看一下，拨号连接上后，网络连接里是否会多出来一个PPPoE连接？如果有，是中文的名字吗？

**Comment by a506534997** [comment]
> 你看一下，拨号连接上后，网络连接里是否会多出来一个PPPoE连接？如果有，是中文的名字吗？

没有，一直是只有两个，就我刚才给你截图的那俩。我刚才谷歌搜了下别人也有同样的问题，但是他们是chrome挂代理了。
https://bbs.pku.edu.cn/v2/post-read.php?bid=35&threadid=15532025
https://answers.microsoft.com/zh-hans/windows/forum/all/用shadowsocks/19956da9-3163-48de-bb03-8b7afcbfddfe

**Comment by a506534997** [comment]
> 你看一下，拨号连接上后，网络连接里是否会多出来一个PPPoE连接？如果有，是中文的名字吗？

和这些设置有关系吗
![image](https://user-images.githubusercontent.com/57380415/93562909-7d9e1700-f9b9-11ea-9a45-f35a5078ab7b.png)

**Comment by a506534997** [comment]
> 你看一下，拨号连接上后，网络连接里是否会多出来一个PPPoE连接？如果有，是中文的名字吗？

![image](https://user-images.githubusercontent.com/57380415/93563089-c950c080-f9b9-11ea-89b6-dd0e0d173bec.png)
我又打开一次怎么发现设置不一样了，我没有动都

![image](https://user-images.githubusercontent.com/57380415/93563139-dff71780-f9b9-11ea-9bed-5b9ded0ea3f5.png)

**Comment by chenshaoju** [comment]
第二张图应该是对的。

感觉是你的PPPoE拨号软件修改了系统代理设置。

你可能得使用第三方插件来代理你的浏览器了。

**Comment by a506534997** [comment]
> 第二张图应该是对的。
> 
> 感觉是你的PPPoE拨号软件修改了系统代理设置。
> 
> 你可能得使用第三方插件来代理你的浏览器了。

那为什么edge 开pac模式也上不了，想不明白，而且之前我用的也好好的，就上次手贱改了下hosts

**Comment by chenshaoju** [comment]
我倾向于是你的PPPoE连接的名字是中文的导致的，请做个测试：

拨号成功后，启动命令提示符（cmd.exe），然后执行： ipconfig （回车）。

你会看到很多顶行开头的诸如“以太网适配器”、“无线局域网适配器”等。

有没有其他的？如果有，跟着的后面是什么（蓝色箭头所指的）？

![image](https://user-images.githubusercontent.com/515763/93565139-6eb96380-f9bd-11ea-9a05-49db21c84bc9.png)

**Comment by a506534997** [comment]
> 我倾向于是你的PPPoE连接的名字是中文的导致的，请做个测试：
> 
> 拨号成功后，启动命令提示符（cmd.exe），然后执行： ipconfig （回车）。
> 
> 你会看到很多顶行开头的诸如“以太网适配器”、“无线局域网适配器”等。
> 
> 有没有其他的？如果有，跟着的后面是什么（蓝色箭头所指的）？
> 
> ![image](https://user-images.githubusercontent.com/515763/93565139-6eb96380-f9bd-11ea-9a05-49db21c84bc9.png)

![image](https://user-images.githubusercontent.com/57380415/93565976-d1f7c580-f9be-11ea-98d8-ca179442a9de.png)
![image](https://user-images.githubusercontent.com/57380415/93565998-db812d80-f9be-11ea-99f2-5e0b57ed3ea5.png)
是不是就是因为他这个是有汉字所以

**Comment by chenshaoju** [comment]
对。。。。就是因为有中文。

**Comment by a506534997** [comment]
> 对。。。。就是因为有中文。
> 
> 你可以尝试将你的系统或者应用语言（比较复杂，我忘了）切换回英文，看看是否会显示英文。
> 
> 如果是英文，应该就没问题了，如果还是中文，就没办法了。。。

我试一下，那为啥之前好好的，晕了

**Comment by a506534997** [comment]
> 对。。。。就是因为有中文。
> 
> 你可以尝试将你的系统或者应用语言（比较复杂，我忘了）切换回英文，看看是否会显示英文。
> 
> 如果是英文，应该就没问题了，如果还是中文，就没办法了。。。

![image](https://user-images.githubusercontent.com/57380415/93567602-7bd85180-f9c1-11ea-923c-3a9b0bf3e8d4.png)
还是中文，那这个没办法改吗

**Comment by chenshaoju** [comment]
没办法，你只能为你的浏览器单独配置代理了，比如搭配 SwitchyOmega 使用：https://github.com/FelisCatus/SwitchyOmega 。

请注意：这是一个第三方的插件，和Shadowsocks项目无关。

**Comment by a506534997** [comment]
> 没办法，你只能为你的浏览器单独配置代理了，比如搭配 SwitchyOmega 使用：https://github.com/FelisCatus/SwitchyOmega 。
> 
> 请注意：这是一个第三方的插件，和Shadowsocks项目无关。

只能这样了 哎 谢谢你了

**Comment by a506534997** [comment]
> 没办法，你只能为你的浏览器单独配置代理了，比如搭配 SwitchyOmega 使用：https://github.com/FelisCatus/SwitchyOmega 。
> 
> 请注意：这是一个第三方的插件，和Shadowsocks项目无关。

我下了itunes发现打开itunes全部都是走的ss，开的pac

**Comment by chenshaoju** [comment]
不知道。。。目前已知就是拨号名如果是中文，就会不工作。
