### ISSUE TITLE
Shadowsocks 2.5.5版本在Windows10下导致暴雪战网游戏无法运行

### ISSUE THREAD

**Issue by simonfeng007** [shadowsocks/shadowsocks-windows#295]
更新Shadowsocks 2.5.5版本之后会导致暴雪国服风暴英雄游戏无法登陆（只要曾经运行过一次2.5.5版本， 即便是以后重启后从未运行过shadowsocks，或者运行游戏的时候是否开否shadowsocks均出现此bug），另外也测试了台服其他暴雪游戏如星际争霸2均出现同样的无法登陆的问题，卡在认证中不动， 即便是卡过去了也完全无法游戏， 无论是通过battle.net
客户端或者直接运行游戏均无法正常登陆，因为我不玩其他网游，所以其他网游的情况尚不清楚。为此已经格式化重装win10测试，问题依旧，解决方法是把shadowsocks客户端更换回2.5.4旧版即可马上解决问题。

具体原因我还不知道，期待各位开发人员测试和修正。

PS：Windows7下使用2.5.5版本的shadowsocks和相同游戏客户端不会触发问题，一切正常，估计问题是只会出现在win10

**Comment by clowwindy** [comment]
禁用 Shadowsocks 的启用系统代理选项以后呢？

**Comment by simonfeng007** [comment]
即便是开机未运行过shadowsocks都不行，只要曾经运行过一次2.5.5版本就会出现问题，禁用代理没测试我现在可以试试不过要付出死机一次的代价T_T

只要换回去2.5.4版本运行一次马上正常。

**Comment by simonfeng007** [comment]
2.5.5版本选择不启用系统代理没触发bug，点击启用系统代理后关闭shadowsocks也没有再次触发bug，不知道会不会重启后再出现问题。

**Comment by clowwindy** [comment]
那么 2.5.4 和 2.5.5 的设置是否一样呢？因为从表现上来看，似乎就是因为游戏客户端走了代理以后，连接不上造成的。

**Comment by simonfeng007** [comment]
一样，我只更新了主程序，用了同一个配置文件

**Comment by simonfeng007** [comment]
win7用相同的设置和版本却没问题（客户端是绿色软件）

**Comment by chenshaoju** [comment]
我也玩风暴英雄，但是没遇到这个问题。

我怀疑和PAC有关，楼主做个测试，使用本地PAC，然后删除或重命名 Shadowsocks.exe 所在目录下的 pac.txt ，然后再启动 Shadowsocks.exe 看看？

**Comment by clowwindy** [comment]
那么问题是否是： 2.5.5 启动系统代理后游戏无法登陆；2.5.4 启用系统代理后游戏还是可以登录？

**Comment by simonfeng007** [comment]
PAC我用的是GFWList的, 没自己再搞, 我认真测试一次再答复各位.

**Comment by simonfeng007** [comment]
更新到2.5.6之后未出现问题, 如有问题会再反馈, 感谢大家的帮忙.

**Comment by CTKnight** [comment]
我在ss 3.0.0 版本也遇到这个问题，只有打开ss才能更新战网客户端，@chenshaoju 您的方法我试了也未能解决，暂时的解决办法是先开着ss连上战网，然后再关掉ss打开游戏

**Comment by chenshaoju** [comment]
@CTKnight 截至目前，我的两台计算机（Windows 7 x64 炉石、风暴、魔兽、守望和 Windows 10 x64 炉石）均未遇到该问题……这个看起来真奇怪。。。

**Comment by James-Z** [comment]
我现在也遇到这个问题，
win10, shadowdsocks 4.0.4

**Comment by James-Z** [comment]
我貌似找到一些线索了，是因为127.0.0.1:1080代理端口的问题，我把shadowsocks端口更改为1090后不论启用不启用ss，暴雪游戏平台都无法正常工作。问题依然没有解决 但是范围缩小了。希望大家帮助解决跟进。

**Comment by James-Z** [comment]
我找原因啦 啊哈哈哈哈哈！
打开IE的LAN代理设置把它关掉就好了！
