### ISSUE TITLE
shadowsocks被Windows的uac识别为未受信任软件

### ISSUE THREAD

**Issue by Wangnibaba** [shadowsocks/shadowsocks-windows#2951]
### 简要描述问题
   电脑上为了安全开启了uac，但是这个软件被识别为不信任，打开后有一个黄色的警告窗，有无办法将其添加为信任软件
### 环境

- Shadowsocks客户端版本：4.2.00
- 操作系统版本：18363.1082
- .NET版本：4.8

### 期望的结果
  将shadowsocks添加为uac信任

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by Leetroch** [comment]
用旧版试试

**Comment by DuckSoft** [comment]
有。请给微软写 complaint letter。

**Comment by studentmain** [comment]
我们没有，也无法为此软件签名，因此遇到"未验证的发布者"提示是正常现象。

**Comment by chenshaoju** [comment]
请尝试右击 Shadowsocks.exe ，选择属性，然后选中解除锁定，再点击确定即可。

举例：
![image](https://user-images.githubusercontent.com/515763/93096897-85b73780-f6d7-11ea-8dfc-57603e8f0a00.png)
