### ISSUE TITLE
How to use Shadowsocks with applications that do not support proxies?

### ISSUE THREAD

**Issue by wodim** [shadowsocks/shadowsocks-windows#2955]
I am sorry for using the issue tracker to ask for help but I don't know where to post this.

I want to use Shadowsocks on Windows with an application that does not support setting a proxy. Is there some software that allows me to do that?

This would be similar to what tsocks can do: https://linux.die.net/man/8/tsocks

**Comment by studentmain** [comment]
Try Outline or Netch (both are third party), they're easiest way to do that.
