### ISSUE TITLE
#2952 之后还有其他问题

### ISSUE THREAD

**Issue by eebssk1** [shadowsocks/shadowsocks-windows#2957]
前面的issue关闭了，重开一个。。
粗略测试了一下只有 "xxxxx.xxx" "|xxx.xxx“会被代理，"||xxxxx.xxx"就不会，麻烦看下。
#2952
话说只有我在用最新预发布版吗。。

**Comment by studentmain** [comment]
https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/job/c5vcyiimoukxfgyq/artifacts

**Comment by eebssk1** [comment]
现在好像是变成"xxxxx.xxx"不被代理了，，我再看看

**Comment by eebssk1** [comment]
测试的||telegram.org依旧没有被代理

**Comment by eebssk1** [comment]
我先换回旧版本摸鱼了，，

**Comment by studentmain** [comment]
我这边看||telegram.org是走代理，更新PAC了吗

**Comment by eebssk1** [comment]
欸，，我把整个ss目录删掉重新配置之后就好了，现在都行了。。。omfg

**Comment by studentmain** [comment]
因为没法复现，先关了
