### ISSUE TITLE
user-rule自定义后，pac中的var __USERRULES仍然为空

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-windows#2958]
主要问题：
更新后user-rule自定义后，pac中的var __USERRULES仍然为空

- Shadowsocks客户端版本：4.2.0.0
- 操作系统版本：WIN10
- .NET版本：4.5+
操作：
在user-rule按规则定义了自定义网址

期望的结果：
期望能代理访问自定义网址

实际结果：
没有通过代理访问自定义网址

配置文件和日志文件：
 {
      "server": "my.**.site",
      "server_port": 443,
      "password": "Ls******",
      "method": "aes-256-gcm",
      "plugin": "v2ray-plugin_win_amd64_v131",
      "plugin_opts": "tls;host=my.**.site",
      "remarks": "Bwh-LA",
      "timeout": 5
    }

**Comment by studentmain** [comment]
it works on my machine

**Comment by chenshaoju** [comment]
我这儿也正常：
![image](https://user-images.githubusercontent.com/515763/93561092-264a7780-f9b6-11ea-94ca-f9b5632eb2bf.png)


请尝试删除 pac.txt ，然后右击任务栏图标托盘区的纸飞机图标，选择PAC，再点击从Geosite更新本地PAC，更新结束后再试？
