### ISSUE TITLE
4.1.0 和4.2.0 无法在win10下运行，启动即报错

### ISSUE THREAD

**Issue by ipconfiger** [shadowsocks/shadowsocks-windows#2960]
### 环境

- Shadowsocks客户端版本：4.1.0 / 4.2.0
- 操作系统版本：Win10
- .NET版本：Win10自带

### 操作步骤
启动

### 期望的结果
成功启动

### 实际结果
报错

![IMG_2302](http://ww1.sinaimg.cn/large/578b198bgy1givqj7dbp4j22c0340nph.jpg）

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
这个现象看起来很奇怪。

请尝试将 Shadowsocks.exe 放到一个新目录中，比如 D:\SS\ 然后再试试。

**Comment by database64128** [comment]
Not enough information is provided.
