### ISSUE TITLE
Clean up stale branches?

### ISSUE THREAD

**Issue by Stzx** [shadowsocks/shadowsocks-windows#2963]
branches:
- [x] `compare_crypto`
- [x] `fix_polarssl`
- [x] `debug`
- [ ] `rm`
- [x] `with_online_config`
- [x] `x64`

ping @chenshaoju  @celeron533  @studentmain

**Comment by studentmain** [comment]
Just keep `rm` branch, it's not stale at all.

**Comment by studentmain** [comment]
`compare_crypto` and `fix_polarssl` is merged. `debug` is output system proxy log to console, we have better log system now. `x64` is replaced by `v5/master` (it's AnyCPU, except privoxy.exe), `with_online_config` is replaced by SIP008. So we can delete them.

About `rm`, yes, technically it's useless at the moment, but we have many non-technical reason to keep it for past, present, and future.

**Comment by studentmain** [comment]
I deleted them, you may still find them in some forks.
