### ISSUE TITLE
我的电脑打开pac模式后没有生效

### ISSUE THREAD

**Issue by q1980361267** [shadowsocks/shadowsocks-windows#2965]
shadowsocks client 打开后打开pac模式后，访问任何网站包括百度等，都是走的代理

- Shadowsocks客户端版本：4.2.0.0
- 操作系统版本：windows10

![image](https://user-images.githubusercontent.com/53589571/93746461-b7745500-fc27-11ea-91e8-073bee5e9e2e.png)

**Comment by chenshaoju** [comment]
此问题已知，请尝试此版本：https://github.com/shadowsocks/shadowsocks-windows/issues/2952#issuecomment-693272728

**Comment by q1980361267** [comment]
嗯嗯，切换到4.1.10.0版本了， 现在一切ojbk
