### ISSUE TITLE
Discussion of UI in v5

### ISSUE THREAD

**Issue by Stzx** [shadowsocks/shadowsocks-windows#2966]
This discussion is used to determine whether to rewrite the UI in v5 and the choice of UI technology.

#### Current candidate list:
- `WinForms` (Keep)
- `WPF`
  - [Avalonia](https://github.com/AvaloniaUI/Avalonia)
  - [UNO](https://github.com/unoplatform/uno)

Welcome to discuss and put forward your own ideas.

cc @celeron533 @studentmain @database64128 @chenshaoju

**Comment by database64128** [comment]
Related discussion: #2962.

Related PR: #2959.

[AvaloniaUI/Avalonia](https://github.com/AvaloniaUI/Avalonia) is a cross-platform XAML-based UI framework. It's quite similar to WPF in regards to XAML syntax. And it works with [ReactiveUI](https://www.reactiveui.net/). It's currently under active development for an upcoming release v0.10. I think AvaloniaUI would be a good choice if we want to target other platforms.

**Comment by Stzx** [comment]
Does @celeron533 @studentmain @chenshaoju have any suggestions for v5's UI?

Let's choose between `UNO` and `Avalonia`, if that's okay. (and start the migration process as soon as possible)

**Comment by chenshaoju** [comment]
My programming is bad... :(

**Comment by database64128** [comment]
The Uno platform looks promising to me. But since our project is currently based on WinForms, choosing Uno would mean a complete rewrite of the UI, and a massive cleanup of the backend code. I'm not sure we have the necessary resources for that.

Having said that, I'm all for radical changes. So I vote for the Uno platform. 😄

**Comment by Stzx** [comment]
For `UNO` I feel it is too "heavy" and requires a lot of SDK and the project is currently focused on Windows platform only. 

I think `Avalonia` or a similar library might be better for us.

**Comment by database64128** [comment]
Well then, let's stick with WPF. Many of us already have experience with it.

**Comment by studentmain** [comment]
Stick with WPF for now, once we want cross platform, migrate to Avalonia should be easy.
