### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by Jeff-Tew** [shadowsocks/shadowsocks-windows#2967]
Shadowsocks 4.1.10.0, 客户端尝试连接时出现以下报错:
```
2020-09-21 22:12:51.4801|INFO|Shadowsocks.Controller.TCPHandler|*.*.*.*:9549 timed out
2020-09-21 22:12:51.6249|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
```

已经确认，IP地址可达，Port open, 状态为listening, 通过nmap嗅探，IP+port状态正常， 防火墙规则设定正确。SSH可以正常连接22端口。

Port状态:
```
root@ubuntu:~# sudo netstat -ntlp | grep LISTEN 
tcp        0      0 0.0.0.0:9549            0.0.0.0:*               LISTEN      31160/ss-server   
```
UFW状态为关闭:
```
root@ubuntu:~# ufw status
Status: inactive
```
iptable 已经放通：
```
root@ubuntu:~# sudo iptables -L INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8388 /* Shadowsocks server listen port */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9549 /* Shadowsocks server listen port */
```
嗅探截图就不贴了， 总之是open的。

想不通为什么会连不上呀。

**Comment by chenshaoju** [comment]
你没有隐藏你的服务器的IP。

我测试了一下，你的服务器22 端口能通，但是ss的服务端口不通。

请尝试使用第三方的IP测试服务测试你的服务器的连通性：http://ip100.info/check 。

**Comment by Jeff-Tew** [comment]
> 你没有隐藏你的服务器的IP。
> 
> 我测试了一下，你的服务器22 端口能通，但是ss的服务端口不通。
> 
> 请尝试使用第三方的IP测试服务测试你的服务器的连通性：http://ip100.info/check 。

我嗅探过的，用的是自己电脑上的nmap，还有whatsmyip.com，结果是open。但你的网站给的结果是closed。![IMG_20200922_102455.jpg](https://user-images.githubusercontent.com/71669849/93859546-0d93d780-fcbe-11ea-99d6-ec40da9525d2.jpg)

**Comment by Stzx** [comment]
你的服务器运营商是不是提供了单独配置的防火墙。非系统配置的。

**Comment by chenshaoju** [comment]
我又测试了一下，端口的确不通，但是22是通的。

![image](https://user-images.githubusercontent.com/515763/93865683-3ab1ab80-fcf9-11ea-9cf7-cdd45a225c39.png)

你可以使用这个第三方的小工具 tcping.exe 测试从你计算机到端口的连通性：
https://elifulkerson.com/projects/tcping.php

**Comment by Jeff-Tew** [comment]
> 我又测试了一下，端口的确不通，但是22是通的。
> 
> ![image](https://user-images.githubusercontent.com/515763/93865683-3ab1ab80-fcf9-11ea-9cf7-cdd45a225c39.png)
> 
> 你可以使用这个第三方的小工具 tcping.exe 测试从你计算机到端口的连通性：
> https://elifulkerson.com/projects/tcping.php
从我家（我在欧洲）tcping，端口是开的
![image](https://user-images.githubusercontent.com/71669849/93934962-2df67d00-fd24-11ea-8e8b-50fc22cf9090.png)
![image](https://user-images.githubusercontent.com/71669849/93935048-50889600-fd24-11ea-8dd1-4dbe5efd6a2a.png)

**Comment by Jeff-Tew** [comment]
不知道发生了什么，在我没有做任何修改的情况下， 莫名其妙的好了 

你们说我要不要关闭这个问题呢？到最后也没明白发生什么了。

**Comment by chenshaoju** [comment]
Odd，我这儿测试还是不行。。。如果可以了就可以了吧，我倾向于是你的服务器或者线路有问题。

![image](https://user-images.githubusercontent.com/515763/93975222-ad7a5f80-fda9-11ea-91d0-f036af890b96.png)
