### ISSUE TITLE
未能加载文件或程序集PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

### ISSUE THREAD

**Issue by notal** [shadowsocks/shadowsocks-windows#2969]
打开程序即报错

### 环境

- Shadowsocks客户端版本：4.2.0.0
- 操作系统版本：windows10
- .NET版本：官网尝试更新后提示已经是最新版

下载了多个PresentationCore.dll文件尝试均无效

以下为日志：
2020-09-22 13:50:01.9262|ERROR|Shadowsocks.Program|System.IO.FileNotFoundException: 未能加载文件或程序集“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”或它的某一个依赖项。系统找不到指定的文件。
文件名:“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”
   在 GlobalHotKey.HotKeyManager..ctor()
   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)
   在 Shadowsocks.Program.Main(String[] args)

**Comment by chenshaoju** [comment]
请尝试升级到最新的 .NET Framework 4.8 https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer

**Comment by notal** [comment]
> 请尝试升级到最新的 .NET Framework 4.8 https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer

4.8已经安装

**Comment by chenshaoju** [comment]
我也是2004，但是没这个问题。

一般来说，这是由于你得系统的 .NET framework 损坏了导致的。

请尝试使用 .NET framework 得安装程序修复一下看看？

**Comment by Stzx** [comment]
使用 PowerShell 执行
```
Get-ChildItem -Path C:\Windows -Force -Recurse -Filter presentationcore* -EA 0
```
看看这个文件是否真的不在。

**Comment by notal** [comment]
已经尝试使用修复工具，工具只是进行了安装服务重启，没有效果，使用4.8安装包安装提示已经安装最新版，在设置的程序和功能中关闭4.8 Advanced Services后重新打开，无效，其中还有一个3.5的功能无法启用，报错0x8007371B。PowerShell运行命令显示有很多个presentationcore文件，有我复制进去的，也有之前就有的

**Comment by Stzx** [comment]
修复工具对你没用，那只能扫描试试：
```
SFC /SCANNOW
```

虽然有其他卸载工具，但是风险比较高，不建议尝试。

而且出现了 `0x8007371B`，当前系统多半有些问题。

**Comment by notal** [comment]
SFC /SCANNOW  未找到任何完整性冲突

看来只有重装了

**Comment by chenshaoju** [comment]
应该可以启动修复模式，ndp48-web.exe下载回来后，启动命令提示符，进入下载目录后，执行：
```
ndp48-web.exe /repair
```

或者直接使用 `/nosetupversioncheck` 忽略版本检查。

参考：
![Uploading image.png…]()
