### ISSUE TITLE
Geosite包含大量国内地址，未来有改进计划吗？

### ISSUE THREAD

**Issue by Nukme** [shadowsocks/shadowsocks-windows#2971]
### 简要描述问题
新版采用的geosite domain list中包含大量国内地址，自动生成pac时会被包含在规则内，导致不必要的代理。
例如，所有暴雪/网易游戏相关的地址。目前可以用user-rule把所有相关的地址都单独拎出来设成例外，但是geosite里面包含的所有其他大陆地址对于国内用户来说也太不方便了吧，有什么改进计划吗？

### 环境

- Shadowsocks客户端版本：
4.2.0.1
- 操作系统版本：
Windows 10
- .NET版本：
4.8

### 操作步骤
1. 升级SS至4.2.0.1
2. 删除并重生成pac
3. 打开魔兽世界客户端wow.exe并尝试登陆

### 期望的结果
快速登陆至人物界面

### 实际结果
卡在“正在连接”很久，然后登陆至人物界面

### 配置文件和日志文件（请隐去敏感信息）
无

### 临时解决办法
在user-rule.txt中将所有相关的地址全部标记为例外。
```
@@||blizzard.cn
@@||blzstatic.cn
@@||battlenet.com.cn
@@||bnet.163.com
@@||wowchina.com
@@|http://wow.nosdn.127.net
@@|https://wow.nosdn.127.net
@@|http://blz.nosdn.127.net
@@|https://blz.nosdn.127.net
@@|http://di.res.netease.com
@@|https://di.res.netease.com
@@|http://heroes.nos.netease.com
@@|https://heroes.nos.netease.com
@@|http://diablo3.nosdn.127.net
@@|https://diablo3.nosdn.127.net
@@|http://hearthstone.nosdn.127.net
@@|https://hearthstone.nosdn.127.net
@@|http://overwatch.nosdn.127.net
@@|https://overwatch.nosdn.127.net
@@|http://sc2.nosdn.127.net
@@|https://sc2.nosdn.127.net
```

**Comment by studentmain** [comment]
Geosite数据库由v2fly项目维护，请联系 https://github.com/v2fly/domain-list-community 以寻求支持
