### ISSUE TITLE
启用shadowsocks之后uwp应用无法联网(无法连接互联网，不是不走代理)

### ISSUE THREAD

**Issue by Wangnibaba** [shadowsocks/shadowsocks-windows#2973]
### 环境

- Shadowsocks客户端版本 4.2.0.1
- 操作系统版本：18363.1082
 .NET版本：4.7

### 操作步骤
启用shadowsocks之后，无论是pac模式还是全局模式，uwp应用都提示无法连接到互联网，关闭后回复正常。

### 期望的结果
shadowsocks代理不影响uwp应用

### 配置文件和日志文件（请隐去敏感信息）
"日志没有记录相关信息"

**Comment by chenshaoju** [comment]
请尝试删除 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后右击任务栏托盘区的纸飞机图标，选择PAC，再点击 `从Geosite更新本地PAC` 后再试。

**Comment by database64128** [comment]
Duplicate of #897.
