### ISSUE TITLE
新版本使用geosite导致winstore无法加载

### ISSUE THREAD

**Issue by ZeddG93** [shadowsocks/shadowsocks-windows#2974]
### 简要描述问题

更新版本后使用新版的geosite数据，在pac模式下无法正常打开winstore，并且大略的查询几个常见的地址都并非被墙网站。
希望能换回之前的gfwlist或者提供选项。

### 环境

- Shadowsocks客户端版本：4.2.0.1
- 操作系统版本：Win10 2004
- .NET版本：

### 操作步骤

1. 更新ss-win + 使用geosite更新本地pac
1. 设置为pac模式
1. 打开winstore

### 期望的结果

正常打开

### 实际结果

疑似因为通过代理请求导致winstore无法正常加载

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by database64128** [comment]
According to your description, I think it's an intended behavior that traffic to certain Windows Store sites are routed to the proxy. The problem you encountered is actually due to UWP loopback restrictions. Please use https://github.com/tiagonmas/Windows-Loopback-Exemption-Manager to allow Windows Store and other store apps access to localhost.

**Comment by chenshaoju** [comment]
测试了一下，的确是本地环回的问题，按照楼上提供的方法可以解决。

如果不希望使用本地环回（或代理商店），可采取下面的临时方案：

临时方案1：
  请尝试退出SS，将此文件保存到 Shadowsocks.exe 所在目录，然后再启动SS即可。
[pac.txt](https://github.com/shadowsocks/shadowsocks-windows/files/5321846/pac.txt)

临时方案2：
  请尝试退回到 4.1.10.0 版本：https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.1.10.0

**Comment by studentmain** [comment]
https://github.com/v2fly/domain-list-community/issues/235

**Comment by ZeddG93** [comment]
@studentmain 

我不认为这是简单的第三方bug。在你ref的issue里原contributor有提到一个关键内容

> 似乎自 v2fly/domain-list-community#215 起开始生成新文件供其它项目使用了？缓兵之计或许是在生成文件时去除标记有@cn的域名。但geolocation-!cn与gfwlist的定位似乎相差较大。

这里原作者的说法与我的想法基本一致，即便不考虑启动uwp loopback带来的安全隐患，也需要考虑大部分属于微软和xbox的域名并不需要代理的情况。譬如，微软商店的内容实际上有大陆的CDN，xbox亦如此。

**Comment by database64128** [comment]
1. Allowing loopback access for UWP apps is not a security concern. In fact, most 3rd party proprietary software is way worse than you think regarding security.
2. shadowsocks-windows now uses dlc directly instead of using the generated txt file.

**Comment by ZeddG93** [comment]
@database64128 我认为替换回gfwlist或者保留可选项是相对更好的方式。无论在uwp需要额外设置回环，还是domain-list的设计用途上，直接使用替代gfwlist都不是一个很合适的方案。

或者更进一步的采取类似v2rayN那样通过用户自行设置路由来满足不同场景的需要。

**Comment by database64128** [comment]
`gfwlist` has been poorly maintained for too long. It's not coming back. As for routing, PR is always welcome.

**Comment by carica** [comment]
Win 10 Store was inaccessible with fresh installation of 4.2.1.0, neither did Win 10 Mail app.

**Comment by kid1412621** [comment]
😂 almost 2021 now

**Comment by chenshaoju** [comment]
请不要到处发，移动到：https://github.com/shadowsocks/shadowsocks-windows/issues/3020#issuecomment-747166973

**Comment by ZeddG93** [comment]
> 请不要到处发，移动到：[#3020 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/3020#issuecomment-747166973)

呵呵
