### ISSUE TITLE
Why did we change PAC source to `geosite`?

### ISSUE THREAD

**Issue by StephenChips** [shadowsocks/shadowsocks-windows#2981]
### Describe the bug
The new PAC source proxy some domains that can be accessed without shadowsocks in China, probably because the new source's PAC list isn't as complete as the old one.

The domains that are mistakenly proxyed I found:
1. Microsoft official website.
2. Bizzard Battle.net's downloading source. (when I turned off Shadowsocks, the game download speed raised to 3MB/s, whereas only 30KB/s with the PAC mode opened.)

### Environment

- Shadowsocks client version: 4.2.0.1
- OS version: windows 10
- .NET version:

**Comment by amano0-0** [comment]
I found so many .cn domains in the pac list. Like volvo.com.cn, volvo.cn, tesla.cn, bridgestone.cn. These domains are not likely to be blocked in mainland China. Migrating from gfwlist to geosite might be a bit hurry, in the circumstance that a complete walk through of the new paclist is not conducted?
