### ISSUE TITLE
GeoSite PAC interfere with Windows Store/Windows Feedback/Windows Mail, etc

### ISSUE THREAD

**Issue by ziruizhuang** [shadowsocks/shadowsocks-windows#2984]
### Describe the bug
After updating to the latest version, 4.2.0.1, the PAC rules switched to GeoSite, and it seems now it would proxy Microsoft Services to remote server as well. However, I do believe this is not in need in most cases, as MS services generally have localized CDNs. And more importantly, these MS services may no longer work properly behind a remote proxy without MS-based authentication mechanisms. 

### Environment

- Shadowsocks client version: 4.2.0.1
- OS version: Windows 10
- .NET version:

### What did you expect to see?
Whitelist a few MS services from GeoSite PAC

**Comment by ziruizhuang** [comment]
Or maybe add a choice of switching between rule-based PAC and Geo-based PAC?

possibly related #2746

**Comment by database64128** [comment]
Not all Microsoft services have CDNs in China. We have already excluded domain names in `geolocation-!cn` with the `cn` attribute from the proxied list in #2982. You can use https://swiss.xuann.wang/dlc-explorer to check if a domain name has the `cn` attribute. If the information is incorrect, you can contribute to the [dlc repo](https://github.com/v2fly/domain-list-community) to resolve your issues.

**Comment by ziruizhuang** [comment]
A few more comments on this issue. 

I am using local PAC mode. 

I see that @2982 is trying to exclude records with `cn` attributes from the PAC rule. However, the PAC rules are not updated. Even if manually select update local PAC from GeoSite, the application would assume the PAC rules do not need modification since GeoSite DB is already up-to-date. 

There is a quick work around. Close the application, delete the dlc.dat file, start the application again, and select update PAC from GeoSite. 

Further, this may mean that the conversion check could be improved. Since there are three parts here:
  GeoSite DB <= conversion algorithm => PAC 
So an up-to-date GeoSite DB dose not necessarily equal to an up-to-date PAC rule set.

**Comment by database64128** [comment]
> Even if manually select update local PAC from GeoSite, the application would assume the PAC rules do not need modification since GeoSite DB is already up-to-date.

This assumption can only cause issues when the PAC generation logic changes. I'm aware of that and that's why I mentioned to manually delete `pac.txt` in the release notes.

Since a version update can bring changes to the PAC generation logic, I'm working on a change to regenerate `pac.txt` on the first run of a new version.
