### ISSUE TITLE
[Question] Can shadowsocks give free internet?

### ISSUE THREAD

**Issue by ShadowSocks12** [shadowsocks/shadowsocks-windows#2985]
Hi, I have been using shadowsocks for 1 or 2 years maybe, and sometimes a question comes to my mind, 
can shadowsocks for PC and shadowsocks for android be used to get free internet instead of using my (paid internet)? 
I mean can I use free internet with shadowsocks instead of paying to get internet?
Sorry for my english and I hope you understood what I mean and thank you.

**Comment by studentmain** [comment]
@ShadowSocks12 You can get free (in "free speech") internet, not free (in "free beer") internet.

**Comment by ShadowSocks12** [comment]
I am sorry, what do you mean by "free speech" and "free beer" internet?

**Comment by database64128** [comment]
@ShadowSocks12 https://www.google.com/search?q=free+speech+free+beer

**Comment by ShadowSocks12** [comment]
ok, so after some reading, 
do I understand that shadowsocks is free speech software?
And does that mean shadowsocks can give free internet?

**Comment by ShadowSocks12** [comment]
ok, so after some reading about "free speech" and "Free beer"...
Do I understand that shadowsocks is "free speech"?
and does that mean it can give free internet?

**Comment by database64128** [comment]
Shadowsocks gives you access to the free internet by circumventing your local ISP's censorship. The _free_ as in the phrase _free speech_. But you still have to pay the ISP for Internet access.
