### ISSUE TITLE
请问最新版能否继续支持.net 2.0？

### ISSUE THREAD

**Issue by aglent** [shadowsocks/shadowsocks-windows#299]
win7的系统，又不想装.net 4.0，能否做个版本继续支持.net 2.0呢？
另外为何用Privoxy代替Polipo，好像网上说速度是Polipo的快。

**Comment by 476210180** [comment]
请注意看介绍，新版本已经不支持.NET 2.0了。

**Comment by clowwindy** [comment]
.Net 2.0 有一些问题暂时不想去解决了，毕竟现在装很多游戏都会要求 .Net 4.0。再说 Windows 10 也出了。

Polipo 和 Privoxy 速度一样。Polipo 下载 2GB 以上文件会崩溃，所以换掉了。
