### ISSUE TITLE
Geosite functionality ignores user-rule.txt

### ISSUE THREAD

**Issue by 20051615** [shadowsocks/shadowsocks-windows#2993]
### Describe the bug
@@|| exemption rules in user-rule.txt are not working and are still being proxied
### Environment

- Shadowsocks client version: 4.2.1.0

In addition, I am wondering if it is still possible to opt out of geosite and revert back to gfwlist, should the user wish to. I do not want the default behavior to be that all non-cn websites get proxied.

**Comment by database64128** [comment]
You should update first: https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.3.0.0

**Comment by 20051615** [comment]
> You should update first: https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.3.0.0
> 
> Make sure to read the release notes. And `gfwlist` is not coming back.

Thanks. The update seems to have resolved my issues.
