### ISSUE TITLE
[Question] How to use"Allow other devices to connect" option?

### ISSUE THREAD

**Issue by ShadowSocks12** [shadowsocks/shadowsocks-windows#2996]
Hi I would like to know how to connect other devices after enabling the option "Allow other devices to connect".
And, just to be sure, does this option make my other devices -like phones- use my computer's IP if shadowsocks is on, Or what? 
I can't understand what it does exactly.
Thank You Very Much.

**Comment by chenshaoju** [comment]
This means that other devices can access the proxy port of the current computer.

You need to configure proxy settings on your devices.
