### ISSUE TITLE
新版本PAC会代理局域网地址

### ISSUE THREAD

**Issue by w123456w30w** [shadowsocks/shadowsocks-windows#3002]
### 简要描述问题
启用PAC模式后，会代理私网地址
如10.*.*.*./172.16.*.*/192.168.*.*的网段
手动在user-rule.txt中添加
@@||10.*.*.*.
@@||172.16.*.*
@@||192.168.*.*
问题解决
### 环境

- Shadowsocks客户端版本：4.3.0.0
- 操作系统版本：Windows10 2004 19041.572

### 期望的结果
希望PAC文件中自动添加对于IPv4/IPv6相关的私网地址规则规避

**Comment by chenshaoju** [comment]
此问题可能需要移步 https://github.com/v2fly/domain-list-community/issues 。

**Comment by Loyalsoldier** [comment]
v2fly/domain-list-community 项目没有与 IP 地址相关的规则。

**Comment by chenshaoju** [comment]
@Loyalsoldier 感谢，刚仔细研究了一下，的确和IP无关。

@w123456w30w 请退出SS，使用Windows自带的记事本打开 Shadowsocks.exe 所在目录下的 gui-config.json 文件，然后将文件中的 ` "geositePreferDirect": false,` 修改为 `"geositePreferDirect": true,` 保存退出后删除同目录下的  pac.txt 文件，再启动SS并更新一下PAC看看。

![image](https://user-images.githubusercontent.com/515763/97131113-3c4e1380-177e-11eb-8fea-156bd0aa6651.png)

**Comment by w123456w30w** [comment]
> @Loyalsoldier 感谢，刚仔细研究了一下，的确和IP无关。
> 
> @w123456w30w 请退出SS，使用Windows自带的记事本打开 Shadowsocks.exe 所在目录下的 gui-config.json 文件，然后将文件中的 ` "geositePreferDirect": false,` 修改为 `"geositePreferDirect": true,` 保存退出后删除同目录下的 pac.txt 文件，再启动SS并更新一下PAC看看。
> 
> ![image](https://user-images.githubusercontent.com/515763/97131113-3c4e1380-177e-11eb-8fea-156bd0aa6651.png)

感谢，修改后确实解决了问题
请问该项作用是什么？为什么不是默认启用的状态呢？

**Comment by chenshaoju** [comment]
有点复杂，但是可以理解成代理黑/白名单。

https://github.com/shadowsocks/shadowsocks-windows/blob/master/README.md#pac

**Comment by EricMzky** [comment]
> 有点复杂，但是可以理解成代理黑/白名单。
> 
> 
> 
> https://github.com/shadowsocks/shadowsocks-windows/blob/master/README.md#pac

确实很难理解啊。讲的不同俗

**Comment by database64128** [comment]
Please check out the build artifacts from #3008: https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/35972165/job/bqhmte099yl41sjb/artifacts. It's a nasty workaround, but it should work on most occasions.

The GeoSite database is meant to be used together with GeoIP in whitelist mode. But our PAC infrastructure can't support GeoIP rules. In fact, the whole PAC infrastructure has been in an unmaintainable state. No active developers are using the PAC mode. We are looking to deprecate PAC in favor of routing solutions. Personally I'm planning on adding support for v2ray-core.

**Comment by w123456w30w** [comment]
> Please check out the build artifacts from #3008: https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/35972165/job/bqhmte099yl41sjb/artifacts. It's a nasty workaround, but it should work on most occasions.
> 
> The GeoSite database is meant to be used together with GeoIP in whitelist mode. But our PAC infrastructure can't support GeoIP rules. In fact, the whole PAC infrastructure has been in an unmaintainable state. No active developers are using the PAC mode. We are looking to deprecate PAC in favor of routing solutions. Personally I'm planning on adding support for v2ray-core.

thanks for the help:D

**Comment by v2cn** [comment]
我也发现同一个问题，升级到4.3.1.0还是不行。
终于找到解决方法了。

**Comment by xqdoo00o** [comment]
更新之后，不仅仅是局域网的地址，
5173网站也会被代理。https://images001.5173cdn.com/view/images/v0/passport/root1/wechat_ac.png
怪不得最近访问5173变慢了。
但是我查了一下pac.txt里面没这个5173的网址啊。
按照 @chenshaoju 的方法改之后就没问题了，pac.txt从110k变成393k了.

**Comment by fa6ca** [comment]
我说怎么更新后局域网内的群辉怎么访问不了控制页面 …………找了半天原因……发现是

**Comment by database64128** [comment]
We have released version [4.3.2](https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.3.2.0) that addressed the issue. It's currently a pre-release due to the lack of testing and feedback. Please update and leave your feedback so I can make it a stable release.
