### ISSUE TITLE
[Question] Which is better, shadowsocks or ShadowsocksR?

### ISSUE THREAD

**Issue by ShadowSocks12** [shadowsocks/shadowsocks-windows#3003]
Hi I have read that shadowsocksR has stronger anti-blocking and anti-interference capabilities...but I still can't know which one of these 2 softwares is more better to use....
other questions please, 
can shadowsocks use SSR IPs or only SS IPs? and Can shadowsocksR use SS IPs or only SSR IPs?

**Comment by chenshaoju** [comment]
It's hard to say who is better.

SS/SSR/V2ray/Trojan each has its own merits and demerits.
