### ISSUE TITLE
程序启动失败

### ISSUE THREAD

**Issue by kele9527** [shadowsocks/shadowsocks-windows#3004]
### 简要描述问题

更新4.3.0.0后运行一直弹如图的提示，覆盖旧版安装的。

![img](https://www.picnew.org/images/2020/10/24/121f68.png)

### 环境

- Shadowsocks客户端版本：4.3.0.0
- 操作系统版本：win7
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by Stzx** [comment]
请更新你的 `.NET` 版本。

**Comment by kele9527** [comment]
> 请更新你的`.NET`版本。

请问更新到那个版本？

**Comment by Stzx** [comment]
> > 请更新你的`.NET`版本。
> 
> 请问更新到那个版本？

升级到最新版本吧。

**Comment by kele9527** [comment]
> > > 请更新你的`.NET`版本。
> > 
> > 
> > 请问更新到那个版本？
> 
> 升级到最新版本吧。

好的，谢谢
