### ISSUE TITLE
[Feature request] GUI 界面上放宽服务器设定中超时上限为 20 秒的限制以适应长连接

### ISSUE THREAD

**Issue by KobeArthurScofield** [shadowsocks/shadowsocks-windows#3007]
**Is your feature request related to a problem? Please describe.**

有的通讯程序（如 Telegram 等）使用长连接 + 心跳包的方式与服务器进行联系，通过 Shadowsocks-Windows 连接时超时上限为 20 秒并不够，虽然可以修改 ```gui-config.json``` 中对应的服务器选项来达到目的（并且能如预期正常连接），但修改后会造成在 GUI 中选择服务器及编辑服务器选项中带来不便（服务器设置在服务器菜单中被隐藏而需要修改 ```gui-config.json``` 来选择服务器，以及修改时因超时数值过大无法直接保存设置）。

**Describe the solution you'd like**

将服务器设置中的超时设置放宽至 60 秒（足以应对大部分情况，如果当初设计上有所考虑可以针对较长超时设置予以二次确认），同时对应服务器能在服务器列表菜单中正常呈现和选择。

**Describe alternatives you've considered**

设置上可以参照原来的设定，但可以允许长超时设定的服务器呈现在菜单列表中。

**Additional context**

无

**Comment by database64128** [comment]
You may have confused the `timeout` field in shadowsocks-windows with some other implementations. Shadowsocks-windows doesn't actively close connections that hasn't transmitted any data based on any arbitrary timeout. And we are removing the connection timeout option in v5.

You might be interested to read my recent write-up of the situation: shadowsocks/shadowsocks-org#164.

**Comment by KobeArthurScofield** [comment]
感谢回复。可能有的地方本人描述可能不太清晰，见谅。

从那段文字来看 Timeout 的问题似乎在各版本实现上有些令人混淆，而在 Shadowsocks-Windows 4.1.9.x 和 4.1.10 中似乎就有按照超时设定切断连接的行为（观察到心跳包的时间间隔被缩短到和设定一致，在客户端日志也会有出现对应连接到服务器的输出），因此通过修改其配置文件将其修改到大于 20 秒解决问题。  
但因为修改后会导致被修改的服务器配置不会在服务器菜单列表中呈现，而且也会阻碍在 GUI 中修改设置后保存，因为似乎在程序原本的设计中超过 20 秒的 Timeout 是不正确的。这个问题直到 4.3.1 依然存在而不便使用（不过即使很短的 Timeout 也没有在 4.3.1 上观察到疑似切断长连接的行为了，这很好）。

因此还是希望可以移除这个有点麻烦的认为这个 Timeout 不正确就不在服务器菜单中呈现对应服务器配置设定，谢谢。
