### ISSUE TITLE
4.3.128  win10运行不了

### ISSUE THREAD

**Issue by suxiaojin** [shadowsocks/shadowsocks-windows#3016]
### 环境

- Shadowsocks客户端版本：4.3.1.128
- 操作系统版本：win10
- .NET版本：

### 操作步骤
双击没有任何反应，程序出不来

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
请安装最新的 .Net framework ：https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer

**Comment by suxiaojin** [comment]
> 请安装最新的 .Net framework ：https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer

win10 已经是4.8了

**Comment by chenshaoju** [comment]
请尝试使用这个工具修复一下：https://www.microsoft.com/en-us/download/details.aspx?id=30135，如果仍然不行，请使用上面的.Net framework安装程序修复安装看看？

**Comment by suxiaojin** [comment]
> 请尝试使用这个工具修复一下：https://www.microsoft.com/en-us/download/details.aspx?id=30135 ，如果仍然不行，请使用上面的 .Net framework安装程序修复安装看看？

都没用

**Comment by chenshaoju** [comment]
最新的正式版仍然不行吗？ https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.3.1.0

如果单独将 Shadowsocks.exe 放到一个新目录中，比如 D:\SS\ ，是否能启动？

**Comment by suxiaojin** [comment]
> 最新的正式版仍然不行吗？ https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.3.1.0
> 
> 如果单独将 Shadowsocks.exe 放到一个新目录中，比如 D:\SS\ ，是否能启动？

新版的，放新目录中也不行。是不是win10 的问题。我win7是没有问题的

**Comment by chenshaoju** [comment]
我用的也是Windows 10 (20H2)，但是没这个问题。

我怀疑是不是你的系统损坏了，请尝试以管理员身份启动命令提示符（cmd.exe），然后执行 `sfc /scannow` 看看？

**Comment by suxiaojin** [comment]
> `sfc /scannow`

![image](https://user-images.githubusercontent.com/12642225/98210321-573d3680-1f7b-11eb-9b3b-610a605037f9.png)

**Comment by suxiaojin** [comment]
> 我用的也是Windows 10 (20H2)，但是没这个问题。
> 
> 我怀疑是不是你的系统损坏了，请尝试以管理员身份启动命令提示符（cmd.exe），然后执行 `sfc /scannow` 看看？

![image](https://user-images.githubusercontent.com/12642225/98210383-76d45f00-1f7b-11eb-98ad-6c8028a69ca4.png)

**Comment by suxiaojin** [comment]
> 我用的也是Windows 10 (20H2)，但是没这个问题。
> 
> 我怀疑是不是你的系统损坏了，请尝试以管理员身份启动命令提示符（cmd.exe），然后执行 `sfc /scannow` 看看？

谢谢了，重装系统吧
