### ISSUE TITLE
有没有docker healthcheck的方案

### ISSUE THREAD

**Issue by darkflame0** [shadowsocks/shadowsocks-windows#3017]
我现在在docker swarm 上使用ss-local，隔一段时间会出现无论如何都连不上，重启容器之后就又可以了的情况
所以想找一个不用重新构建容器就可以用的healthcheck方案

本来想用容器内的wget来进行，但是发现wget并不支持socks5……

**Comment by darkflame0** [comment]
好像发错repo了

**Comment by database64128** [comment]
https://github.com/shadowsocks/shadowsocks-rust is what you’re looking for.
