### ISSUE TITLE
请问目前订阅更新是通过本地网络还是通过当前选中的节点进行的？

### ISSUE THREAD

**Issue by LeslieYon** [shadowsocks/shadowsocks-windows#3019]
根据自己观察，目前订阅更新功能好像是会在刚启动软件时通过本地网络更新，
之后如果手动点击更新订阅，就是通过当前选中的节点更新了。

如果可以话，能否添加可以控制通过哪个网络更新订阅的选项呢。
非常感谢

**Comment by database64128** [comment]
It simply follows your system proxy settings. IMO an extra option would be over-engineering.
