### ISSUE TITLE
对http://开头的下载文件没有走代理

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-windows#3021]
简要描述问题
    我使用 IDM 下载资源，IDM已设置成使用系统代理
该资源路径为 http://168.***.***.55:6818/api/public/dl/RoOo4p9k/***.mp4，PAC模式发现下载速度极慢，通过查看详细日志，发现并没走代理流量。开启全局代理后，下载流量才开始走代理，且速度很快。
PAC模式下浏览器访问 hhttp://168.***.***.55:6818/  管理界面，在走代理。

 Shadowsocks客户端版本：4.3.2.0
- 操作系统版本：WIN10
- .NET版本：4.5+

操作步骤：
    使用IDM下载，上述资源，没走代理
期望的结果：
    PAC模式走代理
实际结果： 
    没走代理

配置文件和日志文件（请隐去敏感信息）
配置文件没问题
在此粘贴日志
（略）

**Comment by chenshaoju** [comment]
该问题一般是IDM或者网址本身没有经过代理导致的，请检查你的PAC文件中是否包含（代理了）这个地址。

**Comment by database64128** [comment]
![image](https://user-images.githubusercontent.com/18757988/98458015-4c76e180-21c7-11eb-99a4-8b275b6620e6.png)
