### ISSUE TITLE
请问在线配置下发的服务器端返回格式是什么

### ISSUE THREAD

**Issue by brave-orange** [shadowsocks/shadowsocks-windows#3023]
想使用在线配置下发的功能，发现没有相应的文档

**Comment by database64128** [comment]
I just started the work to draft the official standard document for SIP008 Online Configuration Delivery. It should be out in a day or so.

**Comment by database64128** [comment]
- Draft document: https://github.com/shadowsocks/shadowsocks-org/wiki/SIP008-Online-Configuration-Delivery
- Discussion thread: shadowsocks/shadowsocks-org#89

**Comment by brave-orange** [comment]
think you

**Comment by brave-orange** [comment]
thank you

**Comment by brave-orange** [comment]
must use `https`?

**Comment by database64128** [comment]
> must use `https`?

What protocol do you intend to use?

**Comment by brave-orange** [comment]
Can I use `http`?

**Comment by DuckSoft** [comment]
> Can I use `http`?

You can, but your traffic can be easily censored, since it's in cleartext.

**Comment by brave-orange** [comment]
emmm...  ok , I know

**Comment by brave-orange** [comment]
emmm... ok , Thank you very much!
