### ISSUE TITLE
`gui-config.json` 中无法保存 `geositeSha256sumUrl` 键值，导致自定义 `geosite` 来源时，因为 sha256 无法匹配更新失败

### ISSUE THREAD

**Issue by IceCodeNew** [shadowsocks/shadowsocks-windows#3024]
### 简要描述问题
`gui-config.json` 中无法保存 `geositeSha256sumUrl` 键值，导致自定义 `geosite` 来源时，因为 sha256 无法匹配更新失败。

### 环境

- Shadowsocks客户端版本：4.3.2.0
- 操作系统版本：Windows 10
- .NET版本：4.8

### 操作步骤
0. 在源代码中搜索关键词找到 `gui-config.json` 中应当对应的键值对：https://github.com/shadowsocks/shadowsocks-windows/blob/d37600231f8b331f7f12aa2b83a9596bdcb44522/shadowsocks-csharp/Controller/Service/GeositeUpdater.cs#L78-L79

1. 删除 `gui-config.json` 中所有同名的键值对，手动添加如下键值对：
```diff
  "isVerboseLogging": true,
  "isIPv6Enabled": false,
  "generateLegacyUrl": false,
+ "geositeUrl": "https://github.com/IceCodeNew/v2ray-rules-dat/raw/release/geosite.dat",
+ "geositeSha256sumUrl": "https://github.com/IceCodeNew/v2ray-rules-dat/raw/release/geosite.dat.sha256sum",
  "geositeDirectGroups": [
    "apa",
    "cambridge",
```

2. 退出客户端。删除 `ss_win_temp` 目录；删除 `pac.txt` 文件。

3. 重新启动客户端，可以观察到`geositeSha256sumUrl` 键值对被自动删除。

4. 尝试更新 pac 文件，提示 sha256 哈希不匹配。
![image](https://user-images.githubusercontent.com/32576256/98634904-fe94e180-235e-11eb-914c-08cf635dfe5e.png)

### 期望的结果
`gui-config.json` 增加 `geositeSha256sumUrl` 键值对供用户设置。自定义 geosite 来源后可以正常更新 pac 文件。

### 实际结果
`gui-config.json` 没有保留用户对 `geositeSha256sumUrl` 键值对的设置。自定义 geosite 来源后因为 sha256 missmatch 无法更新 pac 文件。

### 配置文件和日志文件（请隐去敏感信息）

相关配置已在上方给出。

**Comment by database64128** [comment]
Thank you for the bug report! Please try the build artifacts and see if it's fixed. https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/36287172/job/yikqg30qvf1gqpsf/artifacts

**Comment by IceCodeNew** [comment]
> Thank you for the bug report! Please try the build artifacts and see if it's fixed. [ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/36287172/job/yikqg30qvf1gqpsf/artifacts](https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/36287172/job/yikqg30qvf1gqpsf/artifacts)

I can confirm this problem has been fixed by #3026. Thanks for your work!
