### ISSUE TITLE
Windows10 下无法开机自启

### ISSUE THREAD

**Issue by LenKiMo** [shadowsocks/shadowsocks-windows#303]
系统版本为 Windows10 专业版 64 位，非超级管理员用户。每次运行 ShadowSocks 程序时都需要允许对硬盘上文件的修改。
程序内勾选了开机自动启动，程序属性中勾选了所有用户均已管理员身份运行，任务管理器内启动项中有 ShadowSocks 程序并已允许。
也曾经尝试过将快捷方式发送到开始的“启动”文件夹中，这时任务管理器启动项里会有两个 ShadowSocks 项目，但实际上依旧没有自启。
日志里没有尝试启动的记录，只是从程序被手动启动后才开始记录 “Shadowsocks started”。

粗略翻了一下其他的 Issues 记录没有发现有类似的问题，自觉也比较难复现……所以想请教还有什么方式能够排查问题或者能将其成功启用。

**Comment by chenshaoju** [comment]
你好，你是不是把 Shadowsocks.exe 放到 C:\Program Files\ 下？

理论上不需要UAC权限也可以正常运行。

如果是，请尝试使用便携（Portable）模式：https://github.com/shadowsocks/shadowsocks-windows/releases

即，创建一个空的文本文件，并命名为 shadowsocks_portable_mode.txt ，然后再启动 Shadowsocks.exe 看看。

**Comment by LenKiMo** [comment]
@chenshaoju 
并非如此。我的目录是D:\ShadowSocks，也就是一个外置的目录。
目前使用的程序，包括PAC与配置文件，是我从Win8,1系统中直接迁移过来的。是否与相关文件并非于 Win10 下重新创建有关？

**Comment by clowwindy** [comment]
非管理员用户还没有测过，不知道会不会有权限问题。

**Comment by simonfeng007** [comment]
win10自启动无问题, 不要放在系统盘, 非管理员用户没试过.

**Comment by LenKiMo** [comment]
似乎表述有些问题。
我的账户是以Microsoft账户登陆的管理员账户，但是不是以“Administrator”为名的超级管理员或其他名字的“本地账户”。
不知道并未使用本地账户是否也构成影响权限的因素。

**Comment by chenshaoju** [comment]
我测试过Windows 10的自动启动，没有问题： https://github.com/shadowsocks/shadowsocks-windows/issues/258

我想问下，手动双击能启动？

**Comment by LenKiMo** [comment]
@chenshaoju 
手动双击能够启动，需要允许“应用对你的电脑进行更改”。

**Comment by chenshaoju** [comment]
Shadowsocks默认不需要UAC权限，你可以在属性里取消那个。

然后，写一个批处理，放在 Shadowsocks.exe 的目录下，然后创建快捷方式：

ping 127.0.0.1 -n 60
start Shadowsocks.exe

并将该快捷方式拖放到启动里，看看能否启动？

这个批处理就是启动后等待60秒。

**Comment by imebeh** [comment]
截图看一下 `D:\ShadowSocks` 的属性 -> 安全 选项卡，把自己的机器名、用户名涂掉

或者试一下 在 `D:\` 新建一个文件夹 把 `D:\ShadowSocks` 内的文件复制过去，再打开看看

**Comment by chenshaoju** [comment]
@imebeh 这么说也有可能，目录的权限不对。

**Comment by LenKiMo** [comment]
在 @imebeh 提醒下，截图时发现 ShadowSocks 目录下 Authenticated Users 未赋予“完全控制”权限。
尝试勾选“完全控制”后，取消了 ShadowSocks.exe 以管理员权限运行勾选框。
完成以上工作后重启，ShadowSocks 已经可以开机自启。

看来问题似乎就归结于未对目录赋予足够的权限。

问题已经解决，感谢各位的帮助。

**Comment by imebeh** [comment]
@chenshaoju 重装系统经常碰到这样的问题
@LenKiMo 我的 Win7 环境，Authenticated Users 默认没有完全控制权限；原因可能是其他权限不全或者是其他机器上带过来的用户权限设置（可能会有带问号的显示为 SID 的用户），不知道给予 Authenticated Users 完全控制的权限会不会有什么漏洞，而且对带子文件夹的可能会操作失败，具体没有深入研究过；但是移动到新建的文件夹基本都可解决权限问题，系统默认子文件（夹）会继承父文件夹权限。

**Comment by YXH-YXH** [comment]
> 你好，你是不是把 Shadowsocks.exe 放到 C:\Program Files\ 下？
> 
> 理论上不需要UAC权限也可以正常运行。
> 
> 如果是，请尝试使用便携（Portable）模式：https://github.com/shadowsocks/shadowsocks-windows/releases
> 
> 即，创建一个空的文本文件，并命名为 shadowsocks_portable_mode.txt ，然后再启动 Shadowsocks.exe 看看。

我想问一下，如果我坚持要将其放在C:\Program Files\目录下（有些强迫症，不这样方不舒服），有什么方法可以解决无法开机启动的问题吗？
提前感谢！

**Comment by Pursue-Nymph** [comment]
我打开360安全管家全部的开机启动项，包括那些系统安全服务和应用软件服务，重启了两次，才看到Shadowsocks的开机启动项，然后Shadowsocks提示更新4.16版本（之前的是4.08），再次重启了之后就能用了。。。。  然后用360关掉那些没用的就行了

**Comment by Eric6137** [comment]
按下Win+R，输入 regedit ，然后进入 HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/Windows/CurrentVersion/Run 目录，在空白区点击右键，新建->字符串值(S)，输入一个名字，这里就取ShadowsocksR吧。然后点击刚才新建的项，右键修改， 在“数据数值”文本框中输入SSR应用程序的绝对路径，就可以了。
