### ISSUE TITLE
win10 shadowsocks-4.1.9.2 open error, and the other new version cannot open!

### ISSUE THREAD

**Issue by onezyb** [shadowsocks/shadowsocks-windows#3031]
error wind :
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.IO.FileNotFoundException: 未能加载文件或程序集“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”或它的某一个依赖项。系统找不到指定的文件。

文件名:“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”

   在 GlobalHotKey.HotKeyManager..ctor()

   在 Shadowsocks.Controller.Hotkeys.HotKeys.Init(ShadowsocksController controller)

   在 Shadowsocks.Program.Main(String[] args)

警告: 程序集绑定日志记录被关闭。

要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。

注意: 会有一些与程序集绑定失败日志记录关联的性能损失。

要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2969
