### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by ignorantshr** [shadowsocks/shadowsocks-windows#3032]
### 简要描述问题
无法启动 shadowsocks

### 环境

- Shadowsocks客户端版本：Shadowsocks-4.3.2.146
- 操作系统版本：win10
- .NET版本：4.8

### 操作步骤
双击应用程序

### 期望的结果
正常启动

### 实际结果
发生错误

### 配置文件和日志文件（请隐去敏感信息）

![image](https://user-images.githubusercontent.com/34914892/100031903-bd5a0280-2e31-11eb-906b-ea9d3693f11b.png)

**Comment by database64128** [comment]
Your OS's network stack is broken or misconfigured. You might want to reset all network settings or reinstall Windows.

**Comment by chenshaoju** [comment]
初始化本地接口时遇到错误，请尝试以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一个，都执行完毕后重启后再看看。
