### ISSUE TITLE
Support for changing geositePreferDirect via shortcut

### ISSUE THREAD

**Issue by rhwcu** [shadowsocks/shadowsocks-windows#3036]
**Is your feature request related to a problem? Please describe.**

I need to switch proxy on/off to see if either choice makes connection to a certain website better, but switch it off break connection to known banned hosts like google or youtube. 

I hope I can keep using proxy to known banned websites and keep using direct connection to Chinese websites, and in the meantime, be able to fastly switch proxy on / off for other websites. I think this can be done by implementing a shortcut to change geositePreferDirect between true and false. 

> Here I describe websites that certainly does not require proxy as white (e.g. baidu), and websites that certainly require proxy as black (e.g. google). Other website is described as **grey** .

**Describe the solution you'd like**

A configurable shotcut that change geositePreferDirect. 
(or other solutions toi my problem above)

**Describe alternatives you've considered**

1. Keep a white list and frequently switch proxy on/off,  or keep a black list and frequently switch proxy PAC/global. 
    This could be the most efficient way I can come up with. But this disable connections to blacklist websites or force proxy to whitelist websites. 
1. Modifing the pac file to include grey website. If is better to use proxy, add it to blacklist, otherwise add it to white list.
    This is really time consuming because most grey websites are visited for the first time. Modifying pac every time to a new website is unaffordable. More badly, connection quality is highly random, sometimes it is better to use a proxy, sometimes it is better to use direct connection, which means universally applicable rule does not exist for a certain number of websites and pac for such websites need to be changed time by time. 
1. Changing `geositePreferDirect` in `gui-config.json`
    But I met another [issue](https://github.com/shadowsocks/shadowsocks-windows/issues/3035)

**Additional context**

**Comment by database64128** [comment]
1. To make your changes to PAC rules take effect, the PAC URL has to change. This will always break existing connections for applications that use system proxy settings.
2. PAC is no longer being actively maintained. Version 5 might still provide some limited support for PAC. But we don't commit to that.
3. As I mentioned in #3035, feel free to implement features you want. We encourage and accept contributions from the community.
