### ISSUE TITLE
[FEATURE] Silent mode (autorun without notifications) in settings

### ISSUE THREAD

**Issue by itz0** [shadowsocks/shadowsocks-windows#3039]
Hi 

during autoload, a pop-up message about the network connection unavailability often appears, which is very annoying, perhaps the my router or windows 10 does not have time to load the network/dns settings properly before ss-windows autorun, i very ask you to make the silent mode option (tick in the settings) autorun without notifications..

thank you very much for your work!

**Comment by chenshaoju** [comment]
can you take a screenshot of the pop-up message?

**Comment by itz0** [comment]
i re-check, after autorun ss-windows i have this message: **Error occured when process proxy setting, do you want reset current setting and retry?** it's strange, on another computer with same settings ss-windows autorun work without this error.. hmm
as you can see from the log, this is some error with system proxy but system proxy in this configuration is not used.. 
![ss-windows-error-log](https://user-images.githubusercontent.com/75608529/101457490-830e5c00-392d-11eb-970c-072a969c19a7.jpg)

p.s. in general, everything works, above error messages just pop-up only 2 times, maybe somewhere in the configuration of ss-windows i need some disable?

**Comment by database64128** [comment]
Does the error only occur on system startup? Does manually opening shadowsocks-windows after Windows finished loading everything trigger the error?

Unfortunately, errors like these are critical and should not happen on a normal system. Therefore, we won't introduce any option to silence the error. The most likely cause I can think of is that you OS has probably been heavily modified and has critical services disabled.

Running multiple instances is never officially supported, and will be prevented in version 5.

**Comment by chenshaoju** [comment]
This error code looks your `WinHTTP Web Proxy Auto-Discovery Service` service is not running.

https://github.com/shadowsocks/shadowsocks-windows/issues/2953

**Comment by itz0** [comment]
Yes, you wrote everything correctly, this service is disabled, I enable it and error disappeared, everything is ok 👍
