### ISSUE TITLE
Shadowsock non-UI Error

### ISSUE THREAD

**Issue by vanyaindigo** [shadowsocks/shadowsocks-windows#3042]
### Describe the bug
Every time I start the app it shows this
![image](https://user-images.githubusercontent.com/34334385/101594384-9d663980-3a02-11eb-96e3-891713056c87.png)

### Environment

- Shadowsocks client version: 4.3.1.128-4.3.3.170
- OS version: 19042.662
- .NET version: 
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084

### Config and error log in detail (with all sensitive info masked)

```
PASTE LOG HERE
```

**Comment by database64128** [comment]
Thanks for reporting the problem! Unfortunately, none of the maintainers can understand the error message in your screenshot. Please change your OS language to English and reproduce.

**Comment by vanyaindigo** [comment]
I can translate to you:
"System.NullReferenceException: Object reference does not point to an instance of an object.
 in
Shadowsocks.Model.Configuration.Process(Configuration&
config)
 in Shadowsocks.Controller.ShadowsocksController...ctor()
 in Shadowsocks.Program.Main(String[] args)"
An unhandled exception is thrown anyway

**Comment by database64128** [comment]
Can you post the content of `gui-config.json` with sensitive information redacted? The `NullReferenceException` was mostly likely thrown during configuration loading.

**Comment by vanyaindigo** [comment]
At that moment it was like:
NULL NULL NULL NULL NULL....

**Comment by database64128** [comment]
What do you mean by `NULL`? It's impossible to have it serialized into anything like `NULL`.

**Comment by DuckSoft** [comment]
Did you mean that there are all `\0` bytes in your JSON file?

**Comment by vanyaindigo** [comment]
I meant that the configuration file was corrupted and instead of data with settings there was only this data

**Comment by DuckSoft** [comment]
> 
> 
> I meant that the configuration file was corrupted and instead of data with settings there was only this data

Take care and farewell to your data. Your `gui-config.json` is swallowed by Microsoft glitches and won't be back.

**Comment by database64128** [comment]
Did the file corruption happen after a reboot/shutdown? There have been similar reports related to that. It's most likely a Windows bug. I'm afraid there's nothing we can do about it.

**Comment by vanyaindigo** [comment]
Indeed this happen after a reboot/shutdown. I would like to understand how to avoid this in the future

**Comment by DuckSoft** [comment]
Gracefully shutdown Shadowsocks before shutting down your computer.

> 
> 
> Indeed this happen after a reboot/shutdown. I would like to understand how to avoid this in the future

**Comment by vanyaindigo** [comment]
Well, I'll try, even though it's not very convenient. I wonder why the program itself stopped closing correctly at shutdown?

**Comment by DuckSoft** [comment]
That will be a Makro$h1t Bugbooms specific question. Sorry but we know nothing about it.
> 
> 
> Well, I'll try, even though it's not very convenient. I wonder why the program itself stopped closing correctly at shutdown?

**Comment by chenshaoju** [comment]
This issue looks like your .Net Framework is corrupted. https://github.com/shadowsocks/shadowsocks-windows/issues/2969

**Comment by database64128** [comment]
Notepad++ fixed this with some black magic: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a1031517742c7ef600b825bf9f193b3f2740dff6

Unfortunately, we are unable to implement any of their fixes due to framework restrictions.
