### ISSUE TITLE
新版本导致内网域名网址访问出错。

### ISSUE THREAD

**Issue by Songxwn** [shadowsocks/shadowsocks-windows#3043]
### 环境

- Shadowsocks客户端版本：4.3.3.0
- 操作系统版本：Windows 10  10.0.19042.685
- .NET版本：4.8

### 操作步骤

模式为 PAC

通过域名访问内网网址，会经过shadowsocks。从而导致无法访问。
使用IP访问则不会。

### 期望的结果

希望可以选择之前的PAC源

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/3002#issuecomment-716281981

**Comment by Songxwn** [comment]
![image](https://user-images.githubusercontent.com/21145071/101867691-c2031280-3bb6-11eb-88dc-e960680499f1.png)
我按照要求更改了，选项，删除了旧的PAC文件，但是依旧如此。

**Comment by chenshaoju** [comment]
具体的错误提示是什么？以及内网地址是域名对吧？具体是个什么域名方便告知吗？
