### ISSUE TITLE
关于多插件使用

### ISSUE THREAD

**Issue by PotZedd** [shadowsocks/shadowsocks-windows#3044]
### 简要描述问题
无法同时使用两个插件
### 环境

- Shadowsocks客户端版本：4.3.3.0
- 操作系统版本：Windows 7 64-bit 旗舰版
- .NET版本：4.0

### 操作步骤
打开SS，在插件栏填入两个插件v2ray-plugin和kcptun的绝对路径，尝试用分号隔开但是没有效果。但是启用kcptun插件的路径和参数，端口填kcptun服务端的端口。SS可以连接但是只有微弱的上传流量。

### 期望的结果
能同时使用v2ray-plugin插件和kcptun插件。

### 实际结果
只能同时使用一个插件。只用v2ray-plugin可以连接但没有kcptun加速效果。只用kcptun只有微弱上传流量，没法上网。

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
目前不支持多插件，如果一定要支持的话，你得手动启动多个插件并配置对应的串联关系（第二个插件通过127.0.0.1:xxxx1指定），然后SS客户端里再指定到第二个插件的监听地址（127.0.0.1:xxxx2）。

PS：这么做没有任何意义，既不会提升速度，也不会提升隐匿性。

**Comment by database64128** [comment]
Using multiple plugins together is not part of the SIP003 specification.
