### ISSUE TITLE
use custom rules from v2ray

### ISSUE THREAD

**Issue by fsheidaiee** [shadowsocks/shadowsocks-windows#3045]
Hi
i had a certain rule set in v2ray.
I want to use geoip directing for a country other than china 
and use a geosite.dat file which is customized and block ads accrding to this file as described here for v2ray.
https://github.com/Loyalsoldier/v2ray-rules-dat
can I do this for shadowsocks?
thanks

**Comment by database64128** [comment]
Hi, @fsheidaiee. We are working to add support for using v2ray-core as the backend in version 5. Stay tuned for updates in the v5/master branch.
