### ISSUE TITLE
希望更新添加none/plain加密方式

### ISSUE THREAD

**Issue by bishiping** [shadowsocks/shadowsocks-windows#3050]
作者，您好。`shadowsocks-android`版本现已添加了`none`加密方式，服务/客户端有`shadowsocks-rust`支持，希望可以考虑添加`none或者plain`等加密方式。

**Comment by L-sent** [comment]
.

**Comment by database64128** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2882#issuecomment-747952318
