### ISSUE TITLE
Windows客户端要比ss其它客户端慢很多

### ISSUE THREAD

**Issue by octww** [shadowsocks/shadowsocks-windows#3052]
发现Windows客户端要比ss其它客户端慢很多，这是清晨用Windows客户端和我家路由器的ss在speednet测速的结果，Windows客户端的下载速率为4.1Mbps，只有走路由器代理的十分之一。

IP_ADDRESS | TEST_DATE | TIME_ZONE | DOWNLOAD_MEGABITS | UPLOAD_MEGABITS | LATENCY_MS | SERVER_NAME | DISTANCE_MILES | CONNECTION_MODE | SERVER_COUNT
98.x.x.x | 12/23/2020 6:00 | GMT | 4.1 | 0.74 | 203 | Los Angeles | CA | 0 | multi | 4
98.x.x.x | 12/23/2020 5:57 | GMT | 43.57 | 3.85 | 165 | Los Angeles | CA | 0 | multi | 4

我研究了一下这个贴https://github.com/shadowsocks/shadowsocks-windows/issues/1875 ，不过似乎对改善Win10的情况无效。

### 环境

- Shadowsocks客户端版本：4.3.3.0
- 操作系统版本：Win10家庭版，19042.685
- .NET版本：4.8.04084

**Comment by studentmain** [comment]
@octww 那就用ss其它客户端

**Comment by chenshaoju** [comment]
请尝试重置一下你的TCP/IP和Winsocks看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2944


另外，SS的速度很大程度上取决于你所在的网络的连接情况：
![image](https://user-images.githubusercontent.com/515763/102960729-8b65ba00-451d-11eb-9fee-b87b56fc4116.png)

**Comment by database64128** [comment]
Hi, @octww 

Thank you for sharing your experience with the community. However, this is not the proper way to benchmark the performance of a Shadowsocks client. I also noticed you were testing on different hardware with different operating systems and different client implementations. If you want to compare the performance between different client implementations, use `iperf3` and test on your computer.
