### ISSUE TITLE
4.4版本Microsoft todo无法同步

### ISSUE THREAD

**Issue by wujiechn** [shadowsocks/shadowsocks-windows#3057]
### 环境

- Shadowsocks客户端版本：4.4.0.185
- 操作系统版本：20H2 19042.685
- .NET版本：.NET4.0-.NET4.8全装了

### 操作步骤
我是从 Shadowsocks客户端4.1版本升级到4.4的，4.1可以正常使用Microsoft todo，发现在升级到4.4之后，Microsoft todo就无法同步了。使用PAC模式和全局模式都不行，PAC是文件是删除之后重新自动生成的。

### 期望的结果
4.4版本可以正常同步Microsoft todo

### 实际结果
4.4版本，Microsoft todo无法同步

**Comment by chenshaoju** [comment]
请试一下：https://github.com/shadowsocks/shadowsocks-windows/issues/3002#issuecomment-716281981

**Comment by database64128** [comment]
Hi, @wujiechn 

Please also read the [release notes](https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.4.0.0). Make sure you are not using the removed stream ciphers. An easy way to check is to click _Edit Servers_ and see if your server's encryption method is still in the drop-down list.

**Comment by wujiechn** [comment]
> 请试一下：[#3002 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/3002#issuecomment-716281981)
试过了，Microsoft todo仍然连接不上服务器，无法同步。现在已经换到4.1.10.0版本了，目前一切正常。打算这个版本养老了。

**Comment by wujiechn** [comment]
> Hi, @wujiechn
> 
> Please also read the [release notes](https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.4.0.0). Make sure you are not using the removed stream ciphers. An easy way to check is to click _Edit Servers_ and see if your server's encryption method is still in the drop-down list.

checked it. there is no problem here, i used aes-256-gcm encryption.
