### ISSUE TITLE
升级到4.4.0.0就无法连上

### ISSUE THREAD

**Issue by jakezen** [shadowsocks/shadowsocks-windows#3058]
升级到4.4.0.0就无法连上，回滚到4.3.3.0就OK，服务器设置和PAC都未改动。

### 环境

- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by studentmain** [comment]
@jakezen 服务端加密换成aes-256-gcm，换不了加密就换服务商
