### ISSUE TITLE
windows 7 家庭普通版本不能运行些软件，程序崩溃，如下

### ISSUE THREAD

**Issue by kguang** [shadowsocks/shadowsocks-windows#3060]
### 环境

- Shadowsocks客户端版本：Shadowsocks-4.4.0.185
- 操作系统版本：windows 7 家庭普通版本
- .NET版本：unknow

### 操作步骤

下载后，以管理员权限运行，程序不能运行。
版本：Shadowsocks-4.4.0.185

> 

- [ ]  #@

### 期望的结果
正常正常运行，正常使用VPN软件

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
请提供详细的信息以便解决问题。

你可以在选中错误窗口的情况下按下 Alt+Print Screen ，然后回到Github的输入框，按下Ctrl+V粘贴上来。

**Comment by kguang** [comment]
崩溃如下图

**Comment by kguang** [comment]
> 你可以在选中错误窗口的情况下按下 Alt+Print Screen ，然后回到Github的输入框，按下Ctrl+V粘贴上来。

试了，还是贴不上去，能不能留下邮箱地址，我发给你

**Comment by chenshaoju** [comment]
上传到图床吧，出于安全考虑，不建议通过其他方式联系：https://imgur.com/

**Comment by kguang** [comment]
![image](https://user-images.githubusercontent.com/24998607/103892261-46997000-5126-11eb-8928-dae40117b44d.png)
或地址：https://imgchr.com/i/smaniR

**Comment by kguang** [comment]
> 上传到图床吧，出于安全考虑，不建议通过其他方式联系：https://imgur.com/

https://imgchr.com/i/smaniR      这里可以上到，你给的那个地址，打不开。

**Comment by chenshaoju** [comment]
请点击查看问题详细信息，然后将内容复制并粘贴上来。

**Comment by kguang** [comment]
> 请点击查看问题详细信息，然后将内容复制并粘贴上来。

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	Shadowsocks.exe
  应用程序版本:	4.4.0.0
  应用程序时间戳:	5fee3b64
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.24384
  故障模块时间戳:	5c6e221e
  异常代码:	e0434352
  异常偏移:	0000845d
  OS 版本:	6.1.7601.2.1.0.768.2
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2555#issuecomment-532041034
