### ISSUE TITLE
关于 #3059 请求恢复不安全算法，个人的一些看法

### ISSUE THREAD

**Issue by fakeboboliu** [shadowsocks/shadowsocks-windows#3061]
这个问题很好地体现了翻墙社区通常的风格，可能是面对小白太多的缘故，总是难免变得粗暴而且激进

当然我还是想吐槽：无论是 des 用费斯妥还是 camellia 用费斯妥而且性能屌差这种事，都是很容易得到的常识，不值得为之提出一个问题

我们都是激进的，在什么都在最新的环境中，总是想要用最新的技术来建造自己🐮逼的软件，只是希望各位不要做晋惠帝。程序员可以轻易地推动 ie6 的死亡，并且名正言顺地为一个 eol 的产品盖上棺材板，但是不支持 aes 的低性能内网设备并不是 ie6，它们仍然存在并且正一直存在下去，在这里 aes 会卡到爆炸，camellia 更不用提，哪怕开个 chacha20-ietf 都会卡到怀疑人生。

我们是以自我为中心的，当给产品做出了定性之后便认为一切只能按自己的想法前进。当 ss 作为一个翻墙项目，它的确需要更多的安全性。但是当它被作为其他的功能使用，某些需求便发生了改变。如果设计要包容所有用户，便不能如此做出决定。

我们的文化是 diy 没错，但是关于 revert 这种事情，如果 diy 然后 pr 就显得太过于打脸了一些，对于这一点，我认为原 issuer 即使不是我的朋友，也依然做得足够有礼。

当然我也明白，小白用户总是到处都是，总是可以完美的绕过所有的限制，忽略所有警告来作死，对于删掉不安全的加密这件事作为翻墙的用户群来讲肯定是认同的，只是希望各位在做出决定的时候更加深思熟虑一点。就像将这些算法 deprecated 的那个 issue 中所说的一样：服务端还在支持，对于是否要在客户端删除就要三思

（所以还是想拱火把所有 impl 里的 rc4 都下了

本是 #3059 的 comment，那个 lock 了，就单独发一个 issue 吧

**Comment by fakeboboliu** [comment]
我也是瞎了，毕竟team页面都写了 designed to protect your Internet traffic

**Comment by MoeGuoH** [comment]
> 我也是瞎了，毕竟team页面都写了 designed to protect your Internet traffic

其实嘛，觉得得看场景情况，像古代还有**棍子加密**这类，在现在看来，简直闹着玩.

有许多设备嵌入式设备都在跑这类老旧的服务，并且在当前并不会增加当前项目维护工作量情况下（指为了更安全把代码删掉这种简单做法），原先告知加隐藏的方式是最妥当的。

**Comment by U-v-U** [comment]
同为相关软件开发者，我认为你可以 fork 一个自己维护

**Comment by MoeGuoH** [comment]
> 同为相关软件开发者，我认为你可以 fork 一个自己维护

已照做.🤝

**Comment by nov30th** [comment]
Oh, god. 更新了版本发现rc4md5不见了。搜索了下真的去掉了。作为一个懒人只能简单用回老版本。
