### ISSUE TITLE
新版（4.4.0.185）没有aes-256-cfb

### ISSUE THREAD

**Issue by zhouxiaofu** [shadowsocks/shadowsocks-windows#3063]
新版（4.4.0.185）没有aes-256-cfb
好像只有4种加密方式，然后我下载了4.1.6版本就可以了

忘记截图了，然后下载4.1.6能用后就把4.4.0.185删掉了

**Comment by DuckSoft** [comment]
你已不应再使用不安全的 Shadowsocks 流密码。这是其中的一个原因：https://www.solidot.org/story?sid=63529
请换用安全的加密算法，例如 aes-xxx-gcm 系列或者 chacha20-ietf-poly1305 系列。
