### ISSUE TITLE
update.googleapis.com wrongly tagged with 'cn' attribute

### ISSUE THREAD

**Issue by ziruizhuang** [shadowsocks/shadowsocks-windows#3065]
### Environment

- Shadowsocks client version: 4.4.0.0, prefer direct mode. 
- OS version: Windows 10 20H2
- .NET version:

### Steps you have tried
Check update in Google Chrome.

### What did you expect to see?
Successfully checking and updating Google Chrome

### What did you see instead?
Checking failed. 
An error occurred while checking for updates: Unable to connect to the Internet. If you use a firewall, please whitelist GoogleUpdate.exe
Error code 0x80072F7D

Gone through the traffic logs and found out a possible cause:
Domain 'update.googleapis.com' is with 'cn' attribute in DLC data. While in fact 'update.googleapis.com' is not reachable directly.

**Comment by DuckSoft** [comment]
issue transfer request: https://github.com/v2fly/domain-list-community

**Comment by ziruizhuang** [comment]
Hi, @DuckSoft , thank you for replying. Should I do something for this 'issue transfer request'? Or should I leave it as is and wait for moderators to handle it?

**Comment by DuckSoft** [comment]
You can close this issue, copy and paste to https://github.com/v2fly/domain-list-community if you think they have wrongly tagged the attribute. The geosite database is not provided by Shadowsocks-Windows project.

**Comment by kslr** [comment]
ref https://github.com/v2fly/domain-list-community/commit/8097c5a52d2cf281a38659de3879a1a92c5b13fa #571

http://www.17ce.com/site/http/20210111_5a01a5a053dc11eba7135ba6f70ad643:1.html
