### ISSUE TITLE
Telling user even if there is no newer PAC list available

### ISSUE THREAD

**Issue by alu-7-24** [shadowsocks/shadowsocks-windows#3066]
**Is your feature request related to a problem? Please describe.**
No, I am not sure it is a feature or bug, but I preferred it as a feature, so I am submitting the feature request.

**Describe the solution you'd like**
In the previous version (4.3.x.x), it always sends notification after clicking " Update Local PAC from GFWList" whether there is an updated PAC or not, but in the latest version, I guess the mechanism has been changed to that sending notification when existing updated PAC only.
I checked the log, it will fetch the hashsum of the latest one and compare with the local, keep silent when the result is true. But from the perspective of users, it is very confusing that not sure what happened.

**Describe alternatives you've considered**
Always sending notification even if there is no newer version of PAC list, telling users explicitly.

**Comment by database64128** [comment]
Artifacts available from https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/37942597/job/hl1rlq3rqk2rx6f4/artifacts
