### ISSUE TITLE
订阅出来的节点无中文描述，全是ip和端口，请问下是否为节点服务商问题？

### ISSUE THREAD

**Issue by mooyun** [shadowsocks/shadowsocks-windows#3067]

**Comment by zonyitoo** [comment]
At least you should provide a link or something else for us. What can we do for you if you don't provide anything related.

**Comment by DuckSoft** [comment]
No further information is given, no help can be reached.

![图片](https://user-images.githubusercontent.com/7822648/104295798-db6fe500-54fb-11eb-8de5-7497bcb4b28e.png)
