### ISSUE TITLE
Shadowsocks PAC mode is blocking the working of UWP applications

### ISSUE THREAD

**Issue by alu-7-24** [shadowsocks/shadowsocks-windows#3068]
### Describe the bug
It seems that happening in the latest version of Shadowsocks, I prefer using PAC mode instead of Disable and Global. I trust the pac list could help me decide the traffic direction well. After updating to the latest version, and switched to the PAC mode, UWP applications, like Microsoft Store, Weather can't run correctly, the MS account cannot be signed in, and other resources cannot be loaded normally. No web debugger tool installed. It never happens in the previous version.

 I read the release note of the latest version, it mentioned that removed some encryptions, but I am using chacha20-ietf-poly1305, which is still being supported.

But there is the other sentence that said 'Yes, we have finally removed support for all stream ciphers, almost 4 years after the proposal of Shadowsocks AEAD. Stay safe!', I am not sure the case is caused by this or not.

### Environment

- Shadowsocks client version: 4.4.0.0
- OS version: Windows 10 20H2 with the latest update
- .NET version: 4.8

### Steps you have tried
1. Switch to PAC mode.
2. Open any preinstalled UWP application.
3. See what's happening

1. Switch to Disable
2. Open any preinstalled UWP application.
  3. All work fine.

### What did you expect to see?
All UWP applications are working normally. 

### What did you see instead?
MS account cannot be signed in successfully, most of the resources of the app can't load.

### Config and error log in detail (with all sensitive info masked)

```
PASTE LOG HERE
```

**Comment by DuckSoft** [comment]
Here's some hint from [Qv2ray documentation](https://qv2ray.net/en/getting-started/step4.html#using-system-proxy) (CC-BY-SA):

> By default, UWP applications are prohibited from using a proxy with a loopback address (127.0.0.1), so the system proxy settings will probably cause your UWP applications cease to work normally.
>
> According to [an article by Microsoft](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/loopback), you can resolve the problem by running the following command in a **Command Prompt** (NOT a Powershell) with admin privileges:
> ```batch
> FOR /F "tokens=11 delims=\" %p IN ('REG QUERY "HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Mappings"') DO CheckNetIsolation.exe LoopbackExempt -a -p=%p
> ```
>
> Or, You can just simply use some third-party tools. We here present you [this program](https://qv2ray.net/EnableLoopback.zip) from [Fiddler](https://www.telerik.com/fiddler) project.

**Comment by Artaherzadeh** [comment]
Tried that CMD method and still can't connect

**Comment by chenshaoju** [comment]
please download `Windows 8 AppContainer Loopback Utility` from: https://www.telerik.com/fiddler/add-ons

Click `Exempt All`, and click `Save Changes`.

![image](https://user-images.githubusercontent.com/515763/195543951-f1a9f2ac-2d3c-45e7-8836-2a15c3bb8407.png)

**Comment by Artaherzadeh** [comment]
> please download `Windows 8 AppContainer Loopback Utility` from: https://www.telerik.com/fiddler/add-ons
> 
> Click `Exempt All`, and click `Save Changes`.
> 
> ![image](https://user-images.githubusercontent.com/515763/195543951-f1a9f2ac-2d3c-45e7-8836-2a15c3bb8407.png)

I did this too and still WhatsApp cant connect to the proxy.
System proxy is global and PAC is local

**Comment by chenshaoju** [comment]
This looks like WhatsApp can't pass through the proxy.

**Comment by Artaherzadeh** [comment]
> This looks like WhatsApp can't pass through the proxy.

Any solution?
