### ISSUE TITLE
"encryption method aes-256-cfb not exist" error after upgrade

### ISSUE THREAD

**Issue by lhy-loveworld** [shadowsocks/shadowsocks-windows#3069]
Hi,

It seems my windows client suddenly lost support for aes-256-cfb encryption method after upgrade. Error message starts with "encryption method aes-256-cfb not exist". Any idea about how to solve this problem?

你好,上次自动更新完以后再打开显示"encryption method aes-256-cfb not exist",请问是否有解决办法?

**Comment by lhy-loveworld** [comment]
After rolling back to 4.3.0, the missing encryption methods came back but most of them are labeled as "deprecated". It seems ssserver doesn't support the undeprecated methods. What should I do?

**Comment by DuckSoft** [comment]
You should refrain from using them. Here's one of the reasons: https://www.solidot.org/story?sid=63529

**Comment by database64128** [comment]
> It seems ssserver doesn't support the undeprecated methods.

Use [shadowsocks-rust](https://github.com/shadowsocks/shadowsocks-rust) or [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server).
