### ISSUE TITLE
MUST Restart firefox after launch shadowsocks

### ISSUE THREAD

**Issue by lsq93325** [shadowsocks/shadowsocks-windows#3070]
## description
I use Firefox to explore the Internet, and for somereason I have to use shadowsocks. However, if I open Firefox before launching shadowsocks, ss will not forward my packet to remote server. In this case, I have to close all the tabs to exit Firefox entirely and then can I normally use shadowsock. This is not convenient. because I want to keep the opend web pages. Can someone help out?

**Comment by database64128** [comment]
Use [Discussions](https://github.com/shadowsocks/shadowsocks-windows/discussions) for questions.
