### ISSUE TITLE
请问怎么办

### ISSUE THREAD

**Issue by F1nnWu** [shadowsocks/shadowsocks-windows#3091]
### 简要描述问题
![507251bda3b9b264ff216340392ce9f](https://user-images.githubusercontent.com/77992017/105758252-03465a80-5f8a-11eb-940d-62296c2c78f5.png)

### 环境

- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
请尝试改名或删除 Shadowsocks.exe 所在目录下的 gui-config.json 文件，并重新配置一下看看？
