### ISSUE TITLE
请教4.4.4.0的使用方法！

### ISSUE THREAD

**Issue by chensh555** [shadowsocks/shadowsocks-windows#3092]
我是一个小白，以前一直使用4.1.8，加密方式为aes-256-cfb.今天下载了新的版本，没有了这种加密方式，请教如何配置，谢谢！

**Comment by cpdyj** [comment]
@chensh555 更换其他算法（

**Comment by chensh555** [comment]
请教如何更换？

**Comment by chensh555** [comment]
@ @cpdyj 请教如何更换？

**Comment by chenshaoju** [comment]
有两个方法解决此问题：
1.如果你的SS服务端不是自己搭建的，是买的SS服务，请尝试与你的SS服务商联系，推动升级到AEAD加密算法。
  如果你的SS服务是自己搭建的，请编辑服务端的 shadowsocks-libev 的 config.json ，将method修改为 aes-256-gcm 或 chacha20-ietf-poly1305 。

2.你仍然可以使用旧版本的SS客户端：https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.3.3.0

**Comment by chensh555** [comment]
@chenshaoju 多谢大咖的指点，谢谢！

**Comment by DuckSoft** [comment]
https://www.solidot.org/story?sid=63529

**Comment by database64128** [comment]
Questions like this one should use [Discussions](https://github.com/shadowsocks/shadowsocks-windows/discussions).
