### ISSUE TITLE
failed to update pac file

### ISSUE THREAD

**Issue by F1nnWu** [shadowsocks/shadowsocks-windows#3094]
![屏幕截图 2021-01-28 051657](https://user-images.githubusercontent.com/77992017/106055230-12fba580-6128-11eb-87ec-c182d2b268c1.png)

### 环境

- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
看起来很像是你配置的服务器连接不上或者信息不正确导致的。

你需要提供更加详细的信息以确认此问题。

请右击任务栏右下角的纸飞机小图标，选择帮助，再点击显示日志，然后将日志中的错误信息发送上来。

**Comment by database64128** [comment]
The Geosite updater uses system proxy. The issue you encountered is most likely due to DNS pollution or GitHub being blocked by your ISP. You might want to set _system proxy_ to _global_ before updating Geosite.
