### ISSUE TITLE
更新到 v4.4.0 后局域网不能访问

### ISSUE THREAD

**Issue by chuoke** [shadowsocks/shadowsocks-windows#3098]
### 简要描述问题
一直在用，一直没问题，最近更新到最新版，也就是 v4.4.0 ，频繁出一些小问题，最大的一个问题是，升级后，本地环境的自定义域名以及局域网内的自定义域名，都不能访问，报 500 Internal Privoxy Error，升级前都是正常的，外网都可正常访问，国外的访问速度有明显的感觉下降，出现卡顿，也没报错。更新pac也成功了。
### 环境

- Shadowsocks客户端版本：4.4.0
- 操作系统版本：Win 10 专业版 1909
- .NET版本：不知

### 操作步骤
更新到 4.4.0

### 期望的结果
正常使用

### 实际结果
本地或局域网不能访问
```
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
```

**Comment by chuoke** [comment]
另外，我将原来的ss软件相关内容全部删除，系统里的代理删除，确定能正常访问局域网后，再重新下载ss，该问题依然，外网不受影响

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/3002#issuecomment-716281981

**Comment by database64128** [comment]
Configure user rules to use direct connection for your domain names.
