### ISSUE TITLE
geoip可能对有的域名无法判断

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-windows#3103]
由于最近几个月在**内带谷歌卫星地图网页或app基本都无法再正常访问了，转而使用谷歌地球PC版。地球里没有代理设置选项，只能每次使用时开全局，用完了得切换回PAC模式(白名单模式)，这样很麻烦，有时会忘记切换。通过观察日志发现，刚开启地球时，会访问 hk.google.com,于是在pac中添加 ||hk.google.com后PAC模式可正常使用地球。这是什么原因呢，geoip没识别到？
- Shadowsocks客户端版本：4.4.0.0
- 操作系统版本：WIN10
- .NET版本：4.6+

虽然这个没什么影响，也不算问题，自己添加一个规则就行了，但是不知道其他软件会不会有类似问题，希望能准确判断。

**Comment by chenshaoju** [comment]
我试了一下，这个域名压根就不存在？

![image](https://user-images.githubusercontent.com/515763/108302026-1db4d200-71de-11eb-9bc1-cbaf3ddaf341.png)

**Comment by lssmoon2019** [comment]
真还有点奇怪了，第一个连接就是hk.google.com,不然地球无法显示出来。
![2021-02-18_141305](https://user-images.githubusercontent.com/48443653/108313640-9f632a80-71f3-11eb-878f-9963c1dcfb98.jpg)

**Comment by lixingcong** [comment]
kh.google.com不是hk

**Comment by chenshaoju** [comment]
请尝试再更新一下看看，应该可以了。

**Comment by lssmoon2019** [comment]
kh原来是keyhole,第一眼看以为是HK,我把自定义那条错误的域名去了。现在PAC模式下也能正常使用地球了。
