### ISSUE TITLE
使用加密保护 gui-config.json 文件

### ISSUE THREAD

**Issue by aa656044f0e81367** [shadowsocks/shadowsocks-windows#3108]
**Is your feature request related to a problem? Please describe.**
鉴于目前某些软件在 windows 上会收集 shadowsocks 配置信息，现提议在读写 gui-config.json 让用户给出密码。用密码对 gui-config.json 文件进行加密。密码为空就是明文，明文还是加密可以让用户自己决定。

可能麻烦是的每次启动加载 json 时都需要输入密码。

**Describe the solution you'd like**
直接用 AES-256-GCM 加密后写入 gui-config.json 就可以了。
或者也可以考虑使用 scrypt 或 gpg 工具

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by chenshaoju** [comment]
此问题已有讨论，请移步：https://github.com/shadowsocks/shadowsocks-windows/issues/2162。
