### ISSUE TITLE
TenonVPN错误，打不开。

### ISSUE THREAD

**Issue by le5083** [shadowsocks/shadowsocks-windows#3117]
System.DlIlNotFoundException：无法加载DLL"dll.dll：找不到指定的模块。
（异常来自HRESULT：0×8007007E）。
在Shadowsocks.LipP2P.P2pLib.initNetwork（IntPtr local_ip，Ulnt16
local_port，IntPtr bootstrap，IntPtr path，IntPtr version，IntPtr prikey）
在Shadowsocks.LipP2P.P2pLib.InitNetworkO在Shadowsocks.Program.Main（Stringl]args）

**Comment by database64128** [comment]
#3022
