### ISSUE TITLE
Encryption method not exists for `aes-256-cfb`

### ISSUE THREAD

**Issue by hasanparasteh** [shadowsocks/shadowsocks-windows#3120]
Hi

While there are other clients that support a variety of Encryption methods and some servers use `aes-256-cfb` please consider adding more encryption methods to match-up with more servers configs.

Thanks

**Comment by Stzx** [comment]
#3069

**Comment by DuckSoft** [comment]
I hope you read these first:
* https://gfw.report/blog/ss_advise/en/#proper-authentication
* https://gfw.report/blog/ss_tutorial/en/#q-should-i-use-any-stream-cipher-in-shadowsocks
