### ISSUE TITLE
Shadowsocks 错误: 端口已被占用

### ISSUE THREAD

**Issue by Explorare** [shadowsocks/shadowsocks-windows#314]
系统环境：
Windows 8.1 Enterprise x64
.NET Framework 4.5
Chrome 45 64bit

问题描述：
经常遇到开机启动时提示如图
![Error](https://hime.io/images/2015/09/17/10151595869141887.jpg)

没有防火墙提示，没有杀软拦截提示，using `netstat -aon|findstr 1080` but found nothing.
重启之后问题自然又修复了。尝试更换端口为1085和1081，问题依旧。求可能的解决办法。
THX

**Comment by lixingcong** [comment]
win10下各种bug。。。
算了没人维护的、、、刷openwrt吧

**Comment by Explorare** [comment]
16个contributors总有人会帮忙解决一下的吧，其实这个问题已经遇到至少一个月了，在某论坛技术版讨论了好久，没有发现特定进程占用1080端口的现象，感觉是SS client自身的问题，目前鉴于支持windows平台的SS客户端就这一个是开源的，我只能先这样忍受一下了。另外在win10平台遇到过SwitchyOmega全局模式无效的情况，PAC模式倒是能用，一直无解。
Openwrt的话，有刷过，但是我不能总带个路由器出门，所以在考虑购入一台RPi做加密设备用。

**Comment by wenliyang** [comment]
本地端口换掉就行了吧，2xxxx这样的

**Comment by GangZhuo** [comment]
See https://github.com/shadowsocks/shadowsocks-windows/issues/241

**Comment by Explorare** [comment]
更换端口治标不治本，还是会随机出现这个问题，每次更换端口都得重新设定好几个软件的代理设定，很是麻烦。另外感谢 @GangZhuo 提供的提示，我看到有人提到explorer.exe会占用1080端口，下次遇到此问题出现，我会尝试重启explorer.exe进程，释放1080端口。

**Comment by chenshaoju** [comment]
运行这个命令：

netstat -ano -p tcp

会列出TCP端口的使用情况，找一下1080到底是被哪个进程占用了，然后打开任务管理器，点击查看，选择选择列，然后选中PID，再找到底是哪个进程占用了这个端口。

![screenshot](https://cloud.githubusercontent.com/assets/515763/9976046/2290fb7c-5f07-11e5-8ced-1609d33b7bb8.png)

被第三方占用那么就只能修改第三方软件，如果是被系统占用了，那么最好还是换端口。

**Comment by Explorare** [comment]
多谢帮助，我是Windows 8.1 企业版，任务管理器找到了PID，下次遇到问题看看。

**Comment by Explorare** [comment]
刚才重启时又遇到此问题，先关掉报错窗口，开Console或者Powershell，执行 `netstat -aon|findstr "local port"`，按照 @chenshaoju 提供的方法，在任务管理器按PID排序，一个一个排除，排除到`NVIDIA Home Streaming` 这个进程（名字大概没写对，但就是类似的一个进程），发现它占用了1080端口，造成了问题，结束了就好了。

**Comment by chenshaoju** [comment]
这是N卡驱动内置的一个东西：
http://shield.nvidia.com/game-stream

简单地说，就是可以将游戏画面流式传输到其他设备上，的确没啥用。

**Comment by Explorare** [comment]
多谢帮助，我已禁用 `NVIDIA Streamer Service`，继续观察是否会出现端口占用问题。

**Comment by nicholaslai** [comment]
禁用迅雷的 xlserviceplatform 进程

**Comment by colorlight** [comment]
可以使用tcpview来观察每个进程的端口号，然后关闭1080端口的程序

**Comment by Sdlearn** [comment]
> 禁用迅雷的 xlserviceplatform 进程

试过了，这条管用

**Comment by TuoLe** [comment]
恰巧碰见这个问题，我把代理端口从1080换成10801或者10802，我这边就解决了
