### ISSUE TITLE
启动时报错。软件建议提交到ISSUES

### ISSUE THREAD

**Issue by lyflyflxf** [shadowsocks/shadowsocks-windows#3140]
### 环境

- Shadowsocks客户端版本：4.4.0
- 操作系统版本：Win 10 企业版 1809 LTSC，已打最新补丁
- .NET版本：4.8.03761

### 操作步骤
开机使用计划任务自动启动SS时，直接弹出报错弹窗，建议提交到。

### 期望的结果
正常且无声的启动。

### 实际结果
![1](https://user-images.githubusercontent.com/20678485/112474219-4a927100-8daa-11eb-982d-068a35c50519.png)

### 配置文件和日志文件（请隐去敏感信息）
![2](https://user-images.githubusercontent.com/20678485/112474080-1e76f000-8daa-11eb-8d2a-83c1d663aab4.png)

未找到相关错误日志。

**Comment by DuckSoft** [comment]
以管理员身份运行下看看？

**Comment by Stzx** [comment]
你可以将软件换个位置安装，或者尝试将 `便携模式` 取消勾选。

**Comment by lyflyflxf** [comment]
用管理员身份重启成功，谢谢
