### ISSUE TITLE
failed to import. Please check if the link is valid

### ISSUE THREAD

**Issue by joezhou099** [shadowsocks/shadowsocks-windows#3141]
shadowsocks-4.4.0.185.zip

when I import URL from Clipboard, it shows 'import from URL:https://adblockplus.org/en/filter-cheatsheet?'. 
After clicking 'yes', it shows 'failed to import. Please check if the link is valid.' 
May I know how to solve it, please? Thanks

**Comment by database64128** [comment]
What are you trying to import?
