### ISSUE TITLE
黑白名单设置不起作用!

### ISSUE THREAD

**Issue by hzmnet** [shadowsocks/shadowsocks-windows#3143]
### 简要描述问题
黑白名单设置不起作用!   
@@|| 都无法断绝网站调用SS

### 环境
WIN 10
- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
我测试了一下，没有这个问题。

请尝试更新本地Geosite，然后打开 Shadowsocks.exe 所在目录下的 pac.txt 文件，你在 user-ruletxt 中所添加的内容是否出现在了 pac.txt 文件中的 `__USERRULES__` 变量中？

**Comment by hzmnet** [comment]
你有看SS 日志? 添加名单没问题 也是最新你根本,就是只要SS开启就会一直以SS代理访问
