### ISSUE TITLE
[Bug]复制分享链接到剪贴板程序奔溃

### ISSUE THREAD

**Issue by zhaoweih** [shadowsocks/shadowsocks-windows#3149]
### 简要描述问题
复制分享链接到剪贴板程序奔溃

### 环境

- Shadowsocks客户端版本：4.4.0.0
- 操作系统版本：19042.630
- .NET版本：
 ```
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084
```

### 操作步骤
右键-》服务器-》分享服务器配置-》复制按钮 崩溃了

### 期望的结果
正常复制

### 实际结果
崩溃

### 配置文件和日志文件（请隐去敏感信息）
只留了一个弹窗，我截图了
![屏幕截图 2021-04-02 215132](https://user-images.githubusercontent.com/25500786/113422358-20baf900-93ff-11eb-8bb2-3592c46384d3.png)

**Comment by database64128** [comment]
Thank you for reporting the problem. Opening the clipboard somehow failed on your system. I’m not sure what caused it, but I’m fairly certain it has nothing to do with ss-windows.

**Comment by zhaoweih** [comment]
补充：发现关闭**迅雷**后再点复制不会触发崩溃

**Comment by zhaoweih** [comment]
@database64128 感谢🙇‍
