### ISSUE TITLE
使用 v4 仓库中的sysproxy64.exe  命令行 sysproxy64.exe  pac http://127.0.0.1:xxxx/my.pac 代理没有生效 

### ISSUE THREAD

**Issue by ShenFeng312** [shadowsocks/shadowsocks-windows#3167]
### 环境

- Shadowsocks客户端版本：
- 操作系统版本：WIN10
- .NET版本：

### 操作步骤
使用 v4 仓库中的sysproxy64.exe  命令行 sysproxy64.exe  pac http://127.0.0.1:xxxx/my.pac 代理没有生效 
pac 文件内容
function FindProxyForURL(url, host) {
  return "PROXY 127.0.0.1:8080";
}
### 期望的结果
正常走8080 端口

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志


```

**Comment by chenshaoju** [comment]
执行命令后，在IE浏览器的代理设置中能看到你设置的代理吗？
![image](https://user-images.githubusercontent.com/515763/116033839-c0814500-a694-11eb-924e-e1499667d286.png)

**Comment by ShenFeng312** [comment]
已经解决~  浏览器代理忘记关了
