### ISSUE TITLE
2.5.7 总是提示有更新

### ISSUE THREAD

**Issue by chenshaoju** [shadowsocks/shadowsocks-windows#317]
版本：Shadowsocks-Windows 2.5.7

现象：每次启动时，均会提示发现更新，但是更新下载回来的更新仍是 2.5.7 版本。

**Comment by iKirby** [comment]
程序显示版本号还是2.5.6，可能是忘记改了

**Comment by icylogic** [comment]
@iKirby 你的版本号指的是右键属性里的吗？
<img width="167" alt="2015-09-19_17-01-09" src="https://cloud.githubusercontent.com/assets/2814357/9975479/1aa4248c-5ef0-11e5-849b-f9140cecd23a.png">

**Comment by icylogic** [comment]
找到问题了。。我用的是自己编译的没有问题，Appveyor 上的 VS 编译不更新版本号。
我以后还是用自己编译的发布吧。
