### ISSUE TITLE
2.5.7 及之后版本是否可以信任?

### ISSUE THREAD

**Issue by logtee** [shadowsocks/shadowsocks-windows#318]
以后发布的时候是不是顺便把hash值也公布下?刚才2.5.7的更新好多人都会觉得来路不正!

**Comment by shuangzhijinghua** [comment]
本来就不是原作者开发，只是合并到了主分支

logtee <notifications@github.com>于2015年9月19日周六 下午9:42写道：

**Comment by icylogic** [comment]
理解你们不信任我, 不过 hash 似乎不能解决这个问题啊？建议自行下载源代码用 vs2015 编译, 没有的话可以用 appveyor 上[自动编译的版本](https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe), 每次更新时到项目主页点击那个 build passing 图标即可跳转. 也可以在 appveyor 自建一个免费的, 很简单的.  目前 appveyor 上编译的版本有个小问题就是它没有正确更新版本号, 所以会不停地提示更新 #317 

我改了一下标题, 这个 issue 常开在这里用于解答质疑 2.5.7 及之后版本可靠性的问题.

**Comment by AnyoeDove** [comment]
不信任的建议自行编译 这就是开源的好处啊 源码摆在那里

**Comment by mlxzlas** [comment]
下载 2.5.7 时被chrome 自动拦截了......   当然有人能继续跟进这个项目是非常好的事情,从这个出发点上来讲,我愿意信任 icylogic ,能不能查找一下被chrome 拦截的原因呢?

**Comment by icylogic** [comment]
用的 Firefox 没有这问题. 我安装个 Chrome 看一下.

其实倒是没有必要信任我, 我建议有 VS2015 的完全可以提示更新的时候检查一下 commits 然后下载下来自己编译. 万一我也没有办法更新了, 还可以继续自己动手.

**Comment by icylogic** [comment]
试了一下 chrome 确实有这个问题, 2.5.6 就没问题. 两者的实际链接也是一样的格式, 不知道为什么..

<img width="425" alt="2015-09-19_23-42-28" src="https://cloud.githubusercontent.com/assets/2814357/9976943/3f137768-5f28-11e5-84a6-17a710878d0a.png">

文件是 Github 自己上传到 s3 的, 这我可解决不了, chrome 和 aws 之间的问题.

**Comment by AnyoeDove** [comment]
= =我canary和dev无此问题

**Comment by mlxzlas** [comment]
用 virustotal 检测, 只有Bkav 报 HW32.Packed.A74F,其他都通过

**Comment by mlxzlas** [comment]
似乎是 chrome 认为 aws 上有很多不常被下载的文件中携带危险文件导致的?

**Comment by Vertebrae** [comment]
Windows SmartScreen也进行了拦截

**Comment by qqlinhai** [comment]
private static readonly int Interval = 10 * 60 * 1000;  //evaluate proxies every 15 minutes
是注释错了？

**Comment by icylogic** [comment]
@qqlinhai 原来是15分钟, 改参数的时候忘记改注释了.

**Comment by fleetingoo** [comment]
这频率略快啊, 才更完2.5.7又来2.5.8...

**Comment by qhfls** [comment]
2.5.8还真贴了hash值了。。。
原来也有更新很频繁的时候，
无论如何希望此项目继续，感谢！

**Comment by crystoneme** [comment]
服务器段也是否在继续开发更新呢？

**Comment by liyan1972** [comment]
为什么我下的2.5.8版本hash值和标的不同？

**Comment by GangZhuo** [comment]
@liyan1972 给出的好像是 Shadowsocks.exe 文件的 Hash，不是压缩包的 Hash 。

**Comment by icylogic** [comment]
<img width="548" alt="2015-09-21_15-24-00" src="https://cloud.githubusercontent.com/assets/2814357/9986944/d36deaea-6074-11e5-8f37-e4006ed76b73.png">

**Comment by wudimenghuan** [comment]
@icylogic 这是什么linux程序？可以校验的

我用Visual Studio 2015 Release出来的和你的md5/SHA1都不一样啊

这是发布的：

```
文件: Shadowsocks.exe
大小: 466944 字节
文件版本: 2.5.8.0
修改时间: 2015年9月20日, 11:48:00
MD5: B0CB363CE581F870ED324A995190C06E
SHA1: AD708735F460DA83F239649C4B7D4FAF87704CC2
CRC32: 1C0D21C2
```

我编译的：

```
文件: Shadowsocks.exe
大小: 466944 字节
文件版本: 2.5.8.0
修改时间: 2015年9月21日, 11:23:01
MD5: 1048BBAD7321A02AF04D1475AFD8B60A
SHA1: F50E2554CB0C24A4D5186B77ABF16C52051DEF73
CRC32: 13579498
```

**Comment by wudimenghuan** [comment]
@mlxzlas 我使用我编译的检测是F-PROT查到W32/Felix:compiler:.NET!Eldorado
我不知道为什么编译之后hash不一样

**Comment by wudimenghuan** [comment]
哦，实验出来了，每次hash都是不一样的

**Comment by wudimenghuan** [comment]
@icylogic 貌似原来也是这个项目的，我看提交记录里面有

**Comment by icylogic** [comment]
fciv 是微软发布的校验工具。你自己重新编译当然 hash 不一样。

**Comment by rebiu** [comment]
HashTab，相当简单的软件，右键属性就能hash
http://implbits.com/products/hashtab/

**Comment by duchunyu** [comment]
感谢@icylogic的工作
如果版本更新频繁的话，能否加入关闭检测更新的选项？别每次开机都弹出消息要更新啊

**Comment by ljl024** [comment]
比较期待自动下载、校验更新
让用户自行替换/全自动更新

duchunyu <notifications@github.com>于2015年9月21日周一 20:09写道：

**Comment by icylogic** [comment]
自动更新在这里 #122 讨论过
关闭检测更新的选项 #301 由 clowwindy 提出过，最近可以加进去
这里只讨论可信的问题，其他问题不再回复，有新问题和想法请提出 issue
似乎两次更新不到一天让很多人觉得困扰，除了紧急修复，我不会再频繁更新版本了。
当然，这个 repo 不只我有权限 release，其他人也可以。

**Comment by malthae** [comment]
Version 45.0.2454.99 m 在这里好像没有报错

**Comment by alresvor** [comment]
![2015-09-23_14-02-17](https://cloud.githubusercontent.com/assets/5843694/10038733/47824d1c-61fc-11e5-8886-108d254714f6.png)
@icylogic 这里加个分割符吧

**Comment by t123yh** [comment]
@icylogic 更新的Shadowsocks我怎么没能找到呢？另外希望一起合作进行Shadowsocks-windows的开发，我对C#和git还是比较熟。

**Comment by t123yh** [comment]
@icylogic 好吧，发现我搞错分支了。

**Comment by wongsyrone** [comment]
如果想要使用AppVeyor自动编译的，可以参考下面的 `appveyor.yml`，将会打包两个exe，配置分别为Debug和Release，其中Debug版本输出信息更多，有利于定位问题。
```yml
version: 1.0.{build}
image: Visual Studio 2015
configuration:
- Debug
- Release
platform: x86
clone_depth: 50
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: normal
artifacts:
- path: shadowsocks-csharp\bin\x86\Release\Shadowsocks.exe
  name: Shadowsocks-release.exe
- path: shadowsocks-csharp\bin\x86\Debug\Shadowsocks.exe
  name: Shadowsocks-debug.exe
```
