### ISSUE TITLE
版本4.4.0.0 PAC模式，国内速度变慢，旧版本4.1.9.3没有问题

### ISSUE THREAD

**Issue by Roll-Down** [shadowsocks/shadowsocks-windows#3182]
### 新版本4.4.0.0 PAC模式，国内速度变慢2s页面开始现实内容，一二十秒完全打开，旧版本4.1.9.3没有问题。

- Shadowsocks客户端版本：4.4.0.0
- 操作系统版本：win10 LTSC
- .NET版本：4.7

服务器

- Shadowsocks服务端：shadowsocks-libev, 3.2.5+ds-1 
- 操作系统版本：debian 10, linux kernel 5.4.0-rc6
- 简单的aes-192-gcm配置

**Comment by chenshaoju** [comment]
请退出 Shadowsocks ，用Windows自带的记事本打开 Shadowsocks.exe 所在目录下的 gui-config.json 文件，找到 `"geositePreferDirect": false,` 修改为 `"geositePreferDirect": true,`，保存退出后删除同目录下的 pac.txt 文件。

然后启动 Shadowsocks ，右击任务栏托盘区的纸飞机图标，选择 PAC ，再点击 从Geosite更新本地PAC 即可。

**Comment by Roll-Down** [comment]
感谢您的回复，按照前文意思操作，效果很明显，与旧版本大致上差不多，个别网站上可能出现慢半拍的情况。
