### ISSUE TITLE
如何批量导入节点

### ISSUE THREAD

**Issue by hbbdzry** [shadowsocks/shadowsocks-windows#3184]
请问如何批量导入节点，之前的shadowsocksR可以通过连接导入，而最新版的shadowsocks-4.4.0.185-->服务器-->从剪贴板导入URL显示连接错误（连接是同一个）

**Comment by chenshaoju** [comment]
Shadowsocks 使用的是 ss:// 的协议，如果是 ssr:// 则不支持，这两种协议并不兼容。
