### ISSUE TITLE
同一个服务器，同一个网络，有的页面 win10 可以正常访问，win7无法完全加载页面，页面显示错乱

### ISSUE THREAD

**Issue by xiaomn** [shadowsocks/shadowsocks-windows#3189]
### 

- Shadowsocks客户端版本：4.4.0.0
- 操作系统版本：win10、win7

### win7 访问 kaggle Console 输出的信息

```
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT    css:1 
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT    fonts.googleapis.com/icon?family=Google+Material+Icons:1
```

**Comment by chenshaoju** [comment]
全局模式也这样吗？有可能网站上某些元素所使用的CDN拉黑了你的服务器的IP地址。

**Comment by xiaomn** [comment]
> 全局模式也这样吗？有可能网站上某些元素所使用的CDN拉黑了你的服务器的IP地址。

全局模式没有出现这样的问题了，但是我用同样的服务器在我笔记本 win10 系统上面用同样的网络设置 PAC 模式是可以正常打开 kaggle，没有出现这样的情况，这是为啥呢？是因为系统版本的问题吗？

**Comment by chenshaoju** [comment]
请尝试更新到最新版本的Shadowsocks，删除 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后再更新一下本地PAC看看？

**Comment by xiaomn** [comment]
> 请尝试更新到最新版本的Shadowsocks，删除 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后再更新一下本地PAC

**Comment by xiaomn** [comment]
> 请尝试更新到最新版本的Shadowsocks，删除 Shadowsocks.exe 所在目录下的 pac.txt 文件，然后再更新一下本地PAC看看？

更新后可以了，多谢。

**Comment by chenshaoju** [comment]
👌
