### ISSUE TITLE
PAC rule not working for YouTube

### ISSUE THREAD

**Issue by pundoo** [shadowsocks/shadowsocks-windows#3194]
Rule (direct access) in pac.txt :
```
var __USERRULES__ = [
  "@@||www.youtube.com/youtubei/v1/*"
];
```
I've also tried adding under `__RULES__` but no luck.

Platform: Windows 10 20H2

**Comment by chenshaoju** [comment]
please try to delete pac.txt and user-rule.txt in the shadowsocks.exe folder, And right-click shadowsocks icon in Icon tray area, select PAC Mode and click update local PAC from geosite.

**Comment by pundoo** [comment]
@canbingzt Still no luck :( Thing is, other sites are working correctly. So I guess no issues with the pac file but the particular rule just not getting applied. But I don't see what could be wrong with the rule. It looks fine to me (according to abp filter guide).

Any idea?

**Comment by aries15** [comment]
Chrome won't send path when visiting https websites, which they did deliberately.

**Comment by pundoo** [comment]
@aries15 I see. Thanks for the info.
