### ISSUE TITLE
windows10自动更新之后，就不能用了。Mac 下的依旧可以用。

### ISSUE THREAD

**Issue by hi-iwi** [shadowsocks/shadowsocks-windows#3200]
### 简要描述问题
一周前好好的，windows 自动更新了（含.net）之后，忽然就不能用了。 Mac 下的可以正常用，windows下就不行了。无论是PAC模式，还是全局模式，日志都没有访问记录。

### 环境

- Shadowsocks客户端版本：4.4.0.0
- 操作系统版本：windows 10
- .NET版本：3.5  4.8
![微信图片_20210609202844](https://user-images.githubusercontent.com/15135723/121354489-7eb90f00-c961-11eb-9fc3-a656bf8da386.png)

### 配置文件和日志文件（请隐去敏感信息）

```
2021-06-09 17:27:11.9208|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN
2021-06-09 17:27:11.9208|DEBUG|Shadowsocks.Controller.PACServer|Set PAC URL:http://127.0.0.1:1080/pac?hash=aP9esBdy1Q_7XzF69LAkKQ2&secret=cJzyfVZkO1H2oMGG454RDmt0H5J2zS4ms34371YWxHw1
2021-06-09 17:27:12.0359|DEBUG|Shadowsocks.Controller.Strategy.HighAvailabilityStrategy|server: *****
 latency:00:00:00.0100000 score: 29999912.2562326
2021-06-09 17:27:12.0608|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.4.0.0)
2021-06-09 17:27:12.0608|DEBUG|Shadowsocks.Controller.Listener|
=========================
Registered Encryptor Info
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================
```

**Comment by chenshaoju** [comment]
测试了一下，并没有问题。

请尝试修改模式为PAC模式，并再次更新一下本地PAC看看。

![image](https://user-images.githubusercontent.com/515763/121483566-ef633880-ca00-11eb-8d87-00791f76630a.png)

**Comment by hi-iwi** [comment]
> 测试了一下，并没有问题。
> 
> 请尝试修改模式为PAC模式，并再次更新一下本地PAC看看。

更新PAC失败。无论是PAC模式，还是全局模式，访问Google 都失败，且都没有访问记录。

![5](https://user-images.githubusercontent.com/15135723/121496663-43741a00-ca0d-11eb-9733-1ec75185e64a.png)

> 
> ![image](https://user-images.githubusercontent.com/515763/121483566-ef633880-ca00-11eb-8d87-00791f76630a.png)

![1](https://user-images.githubusercontent.com/15135723/121496543-263f4b80-ca0d-11eb-9609-971efe6d2804.png)
![2](https://user-images.githubusercontent.com/15135723/121496551-28090f00-ca0d-11eb-9e8b-8ff84c143950.png)
![3](https://user-images.githubusercontent.com/15135723/121496559-293a3c00-ca0d-11eb-81ee-fa1b9ce47d71.png)
![4](https://user-images.githubusercontent.com/15135723/121496566-2a6b6900-ca0d-11eb-9bbb-41023b27b0ca.png)

**Comment by chenshaoju** [comment]
请看一下这个地方，有显示一个 127.0.0.1:xxxx （其中xxxx是你的SS的代理端口）的PAC脚本URL吗？

![image](https://user-images.githubusercontent.com/515763/121524758-36195880-ca2a-11eb-8ffa-c5bf3e7c64a0.png)

**Comment by hi-iwi** [comment]
卸载360，之后就可以了。
