### ISSUE TITLE
无法加载DLL“libsscrypto.dll”

### ISSUE THREAD

**Issue by xpgdgit** [shadowsocks/shadowsocks-windows#3202]
### 简要描述问题
启动ss的时候报错
### 环境

- Shadowsocks客户端版本：4.4.0.185
- 操作系统版本： 10.0.18363.1440
- .NET版本：4.8

### 实际结果
![image](https://user-images.githubusercontent.com/30492998/121488677-e0cb5000-ca05-11eb-905e-c5f95c645318.png)

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```2021-06-10 16:00:04.0587|INFO|Shadowsocks.Controller.I18N|Current language is: zh-CN
2021-06-10 16:00:04.4972|INFO|Shadowsocks.Controller.ShadowsocksController|WPF Localization Extension|Current culture: zh-CN
2021-06-10 16:00:04.6757|ERROR|Shadowsocks.Program|System.DllNotFoundException: 无法加载 DLL“libsscrypto.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Shadowsocks.Encryption.MbedTLS.md5_ret(Byte[] input, UInt32 ilen, Byte[] output)
   在 Shadowsocks.Encryption.MbedTLS.MD5(Byte[] input)
   在 Shadowsocks.Controller.PACServer.GetHash(String content)
   在 Shadowsocks.Controller.PACServer.UpdatePACURL(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Controller.ShadowsocksController.Start(Boolean systemWakeUp)
   在 Shadowsocks.Program.Main(String[] args)

**Comment by chenshaoju** [comment]
请安装32位的适用于 Visual Studio 2015、2017 和 2019 的 Microsoft Visual C++ 可再发行软件包。

https://support.microsoft.com/zh-cn/topic/%E6%9C%80%E6%96%B0%E6%94%AF%E6%8C%81%E7%9A%84-visual-c-%E4%B8%8B%E8%BD%BD-2647da03-1eea-4433-9aff-95f26a218cc0

![image](https://user-images.githubusercontent.com/515763/121522061-509e0280-ca27-11eb-85b1-bad85a70d242.png)

**Comment by xpgdgit** [comment]
安装过了还是提示同样的错误
![image](https://user-images.githubusercontent.com/30492998/121534045-6fa29180-ca33-11eb-8088-5d48ed1c235c.png)

**Comment by chenshaoju** [comment]
请先重启计算机，如果仍然不行，请将 Shadowsocks.exe 单独放到一个新的英文路径的目录中，如 D:\SS\ ，然后再试。

**Comment by xpgdgit** [comment]
换到新的路径下后解决了，谢谢！

**Comment by chenshaoju** [comment]
👌
