### ISSUE TITLE
Shadowsocks non-Ul Error

### ISSUE THREAD

**Issue by NioYookerr** [shadowsocks/shadowsocks-windows#3207]
### 简要描述问题
![155](https://user-images.githubusercontent.com/86479180/123435099-c2697500-d5ff-11eb-99ca-97867d4eb07b.png)
![156](https://user-images.githubusercontent.com/86479180/123435103-c39aa200-d5ff-11eb-804b-166938f39528.png)
![157](https://user-images.githubusercontent.com/86479180/123435109-c4333880-d5ff-11eb-9daa-98aec83f132f.png)
![158](https://user-images.githubusercontent.com/86479180/123435110-c4333880-d5ff-11eb-8025-7a4d3d07d549.png)

### 环境

- Shadowsocks客户端版本：4.3.3.0
- 操作系统版本：Windows 10 家庭中文版，21H1，19043.1055
- .NET版本：v4.0.30319

### 操作步骤
最开始发现这个问题，是开机后浏览器上不了网，但其他软件运行正常。后来在“internet选项--连接--局域网设置--代理服务器”取消勾选“为LAN使用代理服务器”才能正常上网，但ss没法用了。然后才发现是ss出了问题。
不知为什么，ss4.3.3.0关不掉，电脑桌面右下、工具栏最右侧找不到ss图标（有截图），任务管理器也找不到ss。ss没有设置为开机自动启动，“任务管理器--启动”里没有ss。

1、删掉ss的exe软件并重启，4.3.3.0依然在运行；查看到ss依然在运行的路径是：
“个性化--任务栏--通知区域--选择哪些图标显示在任务栏上--Shadowsocks”，有截图。
2、双击ss的exe软件，会提示（有截图）：

> Shadowsocks non-Ul Error
> 非预期错误，Shadowsocks将退出。请提交此错误到https://github.com/shadowsocks/shadowsocks-windows/issues System.NullReferenceException: 未将对象引用设置到对象的实例。
> 在Shadowsocks.Model.Confiauration.Process(Confiquration&config)
> 在Shadowsocks.Controller.ShadowsocksController..ctor()
> 在Shadowsocks.Program.Main(String[] args)

3、如果再次双击ss的exe软件，会提示：

> Shadowsocks已经在运行。
> 请在任务栏里寻找Shadowsocks图标。
> 如果想同时启动多个，可以另外复制一份到别的目录。

### 期望的结果
希望能关掉或删掉那个正在运行的ss，不然1、我根本找不到ss在哪里关掉，2、我也没法再用ss，只要双击exe就报错或提示已经在运行。

### 实际结果
拜托帮帮忙，非常感谢！

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
请做个测试，先重启计算机，然后将 Shadowsocks.exe 单独放到一个新的目录中，比如 D:\SS\ ，请问还会出现该问题吗？

**Comment by NioYookerr** [comment]
> 请做个测试，先重启计算机，然后将 Shadowsocks.exe 单独放到一个新的目录中，比如 D:\SS\ ，请问还会出现该问题吗？

您回复得真快，谢谢了…
shadowsocks以下简称为ss。
1、重启，把ss.exe剪切到G:\sss\，之后：
a、“个性化……选择哪些图标显示在任务栏上“，ss还是”4.3.3.0正在运行“
b、双击G:\sss\ss.exe，弹出了ss的编辑服务器对话框，桌面右下角出现了小飞机。
c、重新填信息之后可以用了。
太感谢了！🌹🌹🌹

**Comment by chenshaoju** [comment]
👌
