### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by oceanzsg** [shadowsocks/shadowsocks-windows#3208]
打开最新版本的Shadowsocks-4.4.0.185提示报错，如何解决
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

	System.IO.FileNotFoundException: 未能加载文件或程序集“System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。

文件名:“System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”

   在 Shadowsocks.Controller.ShadowsocksController..ctor()

   在 Shadowsocks.Program.Main(String[] args)

警告: 程序集绑定日志记录被关闭。

要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。

注意: 会有一些与程序集绑定失败日志记录关联的性能损失。

要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

**Comment by chenshaoju** [comment]
请安装最新的 .Net framework：https://dotnet.microsoft.com/download/dotnet-framework/net48

若提示已经安装，请按照提示修复，并重启计算机后再试。

**Comment by oceanzsg** [comment]
可以正常使用了， 需要安装那个版本的.net framework 可以在提供的更新程序注明一下 ，要不然还是登陆不上
