### ISSUE TITLE
更新pac为gfwlist错误

### ISSUE THREAD

**Issue by GVousiu** [shadowsocks/shadowsocks-windows#3209]
下载的是官网上的提供的新版本
在根据教程中更新pac时遇到了错误
<img width="264" alt="DB8F48FF-6D8E-47fc-B5F2-8DE430FFA021" src="https://user-images.githubusercontent.com/50329380/124060212-6af14d80-d9e1-11eb-887d-ea608d15c008.png">
<img width="410" alt="9F58D6B1-EF3D-4584-950B-58E2EDABAA15" src="https://user-images.githubusercontent.com/50329380/124060225-70e72e80-d9e1-11eb-911c-cde5c85932ba.png">

**Comment by chenshaoju** [comment]
你好，Shadowsocks和ShadowsocksR，是两个不同的东西。

如果你从你的SS服务商（或机场）获得的客户端，请与你的服务商联系。
