### ISSUE TITLE
Digital Certificate ?

### ISSUE THREAD

**Issue by icylogic** [shadowsocks/shadowsocks-windows#321]
Since people worry about verification of the binary file, a digital signature may be helpful. And according to Microsoft, providing digital signature with well reputation could prevent Smartscreen blocking in Win 10. I'm not sure whether it could deal with the warning in latest Chrome.

I've not found a free and trustworthy Code Signing signature provider. We may use a self-signed certificate.

So what's your opinions about this?

**Comment by chenshaoju** [comment]
自签名并不是好主意，任何人都可以自签名，相对于MD5和SHA1校验，数字证书或GPG也算不上简单。

大量的开源软件都是用MD5或其他方法校验，比如CyanogenMod（ https://download.cyanogenmod.org/?device=mako ）或一些下载站点（ https://www.androidfilehost.com/?fid=24052804347779835 ）。

建议同时提供MD5和SHA1校验即可。

**Comment by icylogic** [comment]
@chenshaoju 那对于我来说是更方便的 ... 只是这个不能解决 Win10 出现的 Smartscreen 问题以及最新版 Chrome 提示"下载自非常见软件". 其实我现在对于后者还是没有弄清楚原因.

先提供这两个校验. 这两个问题我再研究一下.

**Comment by chenshaoju** [comment]
猜测是下载量问题，如果下载量过少，就会认为存在风险。

**Comment by printempw** [comment]
Agree with @chenshaoju ,you have only to provide both `MD5` and `SHA1` verification.

**Comment by ljl024** [comment]
自签名证书在被作为根证书发行机构信任后，如果泄漏会带来很严重的后果
建议不要使用这种方式

土間うまる <notifications@github.com>于2015年9月20日周日 14:07写道：

**Comment by icylogic** [comment]
@chenshaoju 如果是那样的话就没什么我可以做的了.

从 2.5.8 开始会在 Release 页面加 exe 文件的 hash 值供比对.
