### ISSUE TITLE
求助，无法使用，提示一直超时

### ISSUE THREAD

**Issue by KevinClair** [shadowsocks/shadowsocks-windows#3215]
### 环境

- Shadowsocks客户端版本：最新版
- 操作系统版本：windows10
- .NET版本：最新版Python

### 操作步骤
连接一直提示timeout
一开始使用OK，之后开始连接超时
重装之后一段时间内有效，之后又开始超时
![image](https://user-images.githubusercontent.com/37257651/125185619-7998f980-e258-11eb-97fd-2a086e1750a0.png)

### 配置文件和日志文件（请隐去敏感信息）

```
2021-07-11 14:57:45.2536|INFO|Shadowsocks.Controller.TCPHandler|xx:xx:xx:xx:xxxxx timed out
2021-07-11 14:57:49.1446|INFO|Shadowsocks.Controller.TCPHandler|xx:xx:xx:xx:xxxxx timed out
2021-07-11 14:57:50.2719|INFO|Shadowsocks.Controller.TCPHandler|xx:xx:xx:xx:xxxxx timed out
2021-07-11 14:58:28.1271|INFO|Shadowsocks.Controller.TCPHandler|xx:xx:xx:xx:xxxxx timed out
2021-07-11 14:58:33.1502|INFO|Shadowsocks.Controller.TCPHandler|xx:xx:xx:xx:xxxxx timed out
```

**Comment by KevinClair** [comment]
服务器端口已开，进程一直都在。

**Comment by chenshaoju** [comment]
请使用海外第三方的工具测试你的端口是否能通：https://www.yougetsignal.com/tools/open-ports/

如果能通，说明你的服务器配置正确，请使用第三方本地工具，测试你的端口是否能通：https://github.com/chenshaoju/tcpportcheck/releases/

如果不通（很高可能性不通），说明你的端口被墙了，请尝试换一个端口看看。

**Comment by KevinClair** [comment]
你好，请问一下如果海外第三方工具测试端口不通，是不是需要联系服务器供应商解决问题？

**Comment by chenshaoju** [comment]
如果你是自己搭建的服务器，请检查配置是否正确，端口是否开放。

如果你是购买的机场服务（SS服务商），请与你的SS服务商取得联系，发个工单进行咨询。

**Comment by darkcorn1997** [comment]
> 如果你是自己搭建的服务器，请检查配置是否正确，端口是否开放。
> 
> 如果你是购买的机场服务（SS服务商），请与你的SS服务商取得联系，发个工单进行咨询。

感谢，我换了个端口就好了

**Comment by CarryOnHxy** [comment]
> 工具测试端口不通，是不是需要联系服务器供应



> 请使用海外第三方的工具测试你的端口是否能通：https://www.yougetsignal.com/tools/open-ports/
> 
> 如果能通，说明你的服务器配置正确，请使用第三方本地工具，测试你的端口是否能通：https://github.com/chenshaoju/tcpportcheck/releases/
> 
> 如果不通（很高可能性不通），说明你的端口被墙了，请尝试换一个端口看看。

都通了还是超时怎么办

**Comment by WJC-POG** [comment]
我也是一直超时，很离谱

**Comment by yeluoyunfei** [comment]
> 请使用海外第三方的工具测试你的端口是否能通：https://www.yougetsignal.com/tools/open-ports/
> 
> 如果能通，说明你的服务器配置正确，请使用第三方本地工具，测试你的端口是否能通：https://github.com/chenshaoju/tcpportcheck/releases/
> 
> 如果不通（很高可能性不通），说明你的端口被墙了，请尝试换一个端口看看。

海外的第三方工具测试结果准确吗？
