### ISSUE TITLE
怎么没有服务器订阅功能了

### ISSUE THREAD

**Issue by yn333** [shadowsocks/shadowsocks-windows#3218]
### 环境

- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/126886370-3d895783-9297-4dc3-82a0-29376dcc171f.png)
