### ISSUE TITLE
请问内置的privoxy怎么显示图形界面来代理单独的应用程序啊？

### ISSUE THREAD

**Issue by source2git** [shadowsocks/shadowsocks-windows#322]
在appdata里面能找到ss_privoxy但是打不开啊
有什么办法可以用ss来代理任意一个程序么？

**Comment by CLE** [comment]
windows下可以使用proxifier这个软件来指定代理任意程序

**Comment by shuangzhijinghua** [comment]
sockscap泪流满面，这可以打LOL但是proxifier不能代理LOL。proxifier好处就是无需设置就可以代理大部分程序，但是对UDP支持度不佳。

CLE Chen <notifications@github.com>于2015年9月21日周一 下午3:49写道：
