### ISSUE TITLE
之前正常的配置如今访问google.com页面空白 （有时候隔一段时间/换一台电脑 就好了，同子网下其他电脑可访问）

### ISSUE THREAD

**Issue by 598807302** [shadowsocks/shadowsocks-windows#3220]
### 简要描述问题
使用SS代理 全局代理 访问外网如google.com, youtube.com. 网页一片空白
![example1](https://user-images.githubusercontent.com/25704070/127088008-18a9a7cf-fc5e-44fd-8cb0-7288ef8ef1dc.png)
 
这种情况经常发生，有时候过一段时间就好了，有时候就抽风无法访问。

### 环境

- Shadowsocks客户端版本：4.4.0.185
- 操作系统版本：win 10
- .NET版本：v4.0.30319

### 操作步骤
PC端打开ShadowSocks（已经配置好且相同配置手机端可以正常访问谷歌），启用全局代理。访问google.com。 

### 期望的结果
正常进入谷歌搜索界面

### 实际结果
网页title正常，网页一片空白，没有什么报错信息。

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by 598807302** [comment]
同子网其他电脑可访问，但是他们使用的代理服务器和我不一样。

**Comment by 598807302** [comment]
已经尝试过的方法：
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
无用

**Comment by chenshaoju** [comment]
Shadowsocks的日志里有任何内容吗？

**Comment by 598807302** [comment]
> Shadowsocks的日志里有任何内容吗？

或许已经回复正常，我怀疑是提供商那么的问题，我给他们发了邮件。
感谢！
