### ISSUE TITLE
请求更新python版服务端支持新的加密方式

### ISSUE THREAD

**Issue by waitsaber** [shadowsocks/shadowsocks-windows#3221]
### 简要描述问题
在最新版本（4.4.0.185）的windwos客户端中只支持aes-256-gcm、aes-128-gcm、chacha20-ietf-poly1305、xchacha20-ietf-poly1305，但是python版的服务端2.9.1 无法直接使用以上加密方式，希望能够更新版本支持新的加密方式。
### 环境

- Shadowsocks客户端版本：4.4.0
- 操作系统版本：windows 10
- .NET版本：4.8

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
由于安全问题，这些加密算法已经被废弃。
方案1：切换到Shadowsocks-libev：https://github.com/shadowsocks/shadowsocks-libev
方案2：使用旧版客户端：https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.3.3.0

讨论详见：https://github.com/shadowsocks/shadowsocks-windows/issues/3059
