### ISSUE TITLE
ss最近不能用了吗？前几个月一直好用，突然就不能用了。。。。2021.8

### ISSUE THREAD

**Issue by taoorange** [shadowsocks/shadowsocks-windows#3222]
### 环境

- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
如果你是从某SS服务商（或称为机场）的地方购买的服务，请与你的机场服务商联系。
