### ISSUE TITLE
最新版无法用pac模式

### ISSUE THREAD

**Issue by dolaham** [shadowsocks/shadowsocks-windows#3223]
### 简要描述问题
我选择pac模式就无法打开google.com，只有全局模式才能打开google.com。这个问题持续好几个版本了，每次更新都失望，我只好选择继续使用旧版本，比如4.1.0，就可以正常使用pac模式。

### 环境
win10

- Shadowsocks客户端版本：4.4.0.185
- 操作系统版本：win10家庭中文版 21H1
- .NET版本：4.0.30319

### 操作步骤
shadowsocks使用pac模式
浏览器打开google.com

### 期望的结果
能正常访问google.com

### 实际结果
不能打开google.com网页

**Comment by dolaham** [comment]
发出此bug报告后我研究了下。发现也许是pac文件导致的。
以前版本是从gfw列表更新，现在的版本是从geosite更新。使用旧版的pac文件，就会无法在pac模式下访问google.com。从geosite更新本地pac后，可以正常访问google了。

**Comment by WaniRain** [comment]
怎么从geosite更新本地pac啊
