### ISSUE TITLE
非预期性错误Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by guanidine** [shadowsocks/shadowsocks-windows#3225]
### 简要描述问题

您好，shadowsocks几年来在我电脑上一直运行良好，然而在最近启动时却会报如下错误，希望能得到解决，谢谢：
![image](https://user-images.githubusercontent.com/58496879/129703257-a980eba3-abbe-4cd7-88b9-bb6ab923ba28.png)

### 环境

- Shadowsocks客户端版本：4.4.0.0
- 操作系统版本：Windows 10 专业版 64 位（10.0，内部版本 19042）
- .NET版本：5.0.203

**Comment by chenshaoju** [comment]
你是否经常性的在未推出 Shadowsocks.exe 的情况下从开始菜单中关机或重启？

如果是，请退出 Shadowsocks ，将 Shadowsocks.exe 所在目录下的 gui-config.json 文件改名，然后重新打开 Shadowsocks ，手动再次设置一次看看，是否还会有该问题？

如果该问题已消失，请在重启或关闭计算机前先退出Shadowsocks。

参考：https://github.com/shadowsocks/shadowsocks-windows/issues/3042

**Comment by guanidine** [comment]
根据您的指导，问题已解决。
感谢您的回复。
