### ISSUE TITLE
为什么访问不了这个网站？？？急急急

### ISSUE THREAD

**Issue by luo01** [shadowsocks/shadowsocks-windows#323]
VOA都可以访问。可是就是访问不了BBC中文网。为什么呢？

http://www.bbc.com/zhongwen/simp/

**Comment by GangZhuo** [comment]
确认全局模式是否能够访问。如果能的话，检查自己的 PAC 文件，如果使用其他代理工具的话，检查其他代理工具的设置。如果不能的话，请确认 Shadowsocks 的服务器配置和检查下 Shadowsocks 的日志。
