### ISSUE TITLE
日志查看器中字体选择没有去除非TureType字体

### ISSUE THREAD

**Issue by AnyoeDove** [shadowsocks/shadowsocks-windows#324]
![bug](https://cloud.githubusercontent.com/assets/10519576/9998909/2b46e176-60c6-11e5-9dbc-d994f661f436.png)

建议排除非TureType字体

**Comment by GangZhuo** [comment]
你使用的字体名字是什么？

**Comment by AnyoeDove** [comment]
是我选用了非TureType字体才会有的报错 与当前字体无关

**Comment by icylogic** [comment]
麻烦你提供一下导致崩溃的字体名称，我们可以尝试复现

**Comment by AnyoeDove** [comment]
Hiragino Sans GB W3
Hiragino Sans GB W6
字体已上传
https://drive.google.com/file/d/0B3WQsb8rrN8lajRvcm1rdkxSSG8/view?usp=sharing

**Comment by GangZhuo** [comment]
做了一些搜索，除了了引入第三方自定义 FontDialog，其他没有较好的办法。引入第三方控件，太重了。 按照 https://github.com/shadowsocks/shadowsocks-windows/commit/2ec13402619bd4e2106f6c2a63c0c7929091f169 的修改，本机测试也能工作，那就先这样，或者等有更好的解决办法的时候再修改。

**Comment by icylogic** [comment]
我觉得可以接受。 @AnyoeDove 你的意见?

**Comment by AnyoeDove** [comment]
好的 我理解了 请close issue吧@icylogic
