### ISSUE TITLE
新版客户端速度有所下降

### ISSUE THREAD

**Issue by Fyllan** [shadowsocks/shadowsocks-windows#3240]
### 简要描述问题

新版客户端4.4.0.0相比旧版客户端4.2.0.1速度有所下降。

### 环境

- Shadowsocks客户端版本：4.2.0.1 和 4.4.0.0
- 操作系统版本：windows 10 21h1
- .NET版本：5.0
- 服务端 ss-libev最新版本
- 均使用firefox sock5代理
- 测速服务器使用的SS服务器提供商自己的测速服务

### 操作步骤

使用同一个gui-config.json分别运行两个版本的程序进行速度测试，结果表明4.4.0.0速度相对较慢，请问是否加入了某种安全机制从而出现了这种情况？

这个是4.4.0.1的测试结果
![4 2 0 1](https://user-images.githubusercontent.com/42598456/133920474-edafb1e1-d732-4b3d-86b3-65e05467c8ed.png)

这个是4.2.0.1的测试结果
![4 4 0 0](https://user-images.githubusercontent.com/42598456/133920475-ec9ecdd1-06b7-4ff8-8d2c-86ae3277625c.png)

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/3182
