### ISSUE TITLE
一直只有出站流量，没有入站流量

### ISSUE THREAD

**Issue by liuh82** [shadowsocks/shadowsocks-windows#3244]
### 环境

- Shadowsocks客户端版本：4.4.0
- 操作系统版本：win10 1909
- .NET版本：4.8

### 操作步骤
同一局域网内，台式电脑之前能够正常使用，突然一天开机后，无法正常使用ss，查日志后发现只有出站流量，没有进站流量。过一会儿后ss就报错（报错内容见图片）。笔记本电脑的ss客户端和台式电脑的配置一样，能正常使用。用tcpporcheck和tcping都测了，服务器端口正常。也检查了台式电脑无端口占用情况。

### 期望的结果
正常使用

### 配置文件和日志文件（请隐去敏感信息）
![错误截图](https://user-images.githubusercontent.com/33415295/136760547-70be52f1-2be3-4f94-9e30-f3e72f8de78d.jpg)
[
![错误截图1](https://user-images.githubusercontent.com/33415295/136760971-8a158b49-d11b-4a09-b02e-73ec4a6f6f9d.jpg)
](url)
```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
用tcping测试的时候，连接失败严重吗？

**Comment by liuh82** [comment]
> 用tcping测试的时候，连接失败严重吗？

不严重，而且包括笔记本和手机都能正常使用

**Comment by chenshaoju** [comment]
比如游戏代理加速器之类的。

这个提示意味着连接到你的服务器出现了中断或者超时，但是一般不会引发程序错误。

可能有什么东西主动切断了你的SS连接或者SS的线程，如果相同配置在同局域网的其他Windows计算机上也是正常的，可能是有问题的计算机系统上有什么东西存在干扰。
