### ISSUE TITLE
gfw已经能识别ss协议，换ip都没用了

### ISSUE THREAD

**Issue by xiedeacc** [shadowsocks/shadowsocks-windows#3247]
请问是我配置问题，还是大家都不能用了？

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836

**Comment by xiedeacc** [comment]
> [#2228 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2228#issuecomment-465047836)

感谢
