### ISSUE TITLE
geositePreferDirect 无法修改成true

### ISSUE THREAD

**Issue by xpgdgit** [shadowsocks/shadowsocks-windows#3259]
### 简要描述问题
geositePreferDirect 修改成true后，启动pac后会自动修改成false
### 环境

- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
请先退出SS再修改。

**Comment by xpgdgit** [comment]
好的
