### ISSUE TITLE
CAMELLIA 256 CFB无法使用，希望加入

### ISSUE THREAD

**Issue by HornCopper** [shadowsocks/shadowsocks-windows#3264]
这边有个木棍，是香港的，只能使用CAMELLIA 256 CFB连接，手机可以正常使用，但是电脑端貌似不支持此协议，请求加入。

**Comment by chenshaoju** [comment]
请使用该版本：https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.3.3.0
