### ISSUE TITLE
High CPU consumption

### ISSUE THREAD

**Issue by randef1ned** [shadowsocks/shadowsocks-windows#3265]
### Describe the bug

The Shadowsocks-Windows client consumes a significant amount of CPU resources when downloading files or watching videos. However, I am unable to reproduce the bug on my laptop which runs Windows 10 20H2 and my 21H2 virtual machine. 

### Environment

- Shadowsocks client version: 4.3.3.0 & 4.4.0.0
- OS version: Windows 10 1809 Enterprise LTSC
- .NET version: 4.8.3761.0

### Steps you have tried

1. Run Shadowsocks-Windows client
2. Download a file or watch a YouTube video. An example: [Octave](https://ftpmirror.gnu.org/octave/windows/octave-6.4.0-w64-installer.exe)
3. Open the task manager and I can see Shadowsocks utilize a great amount of CPU resources. 

### What did you expect to see?

Reduction of CPU usage

### What did you see instead?

Shadowsocks utilize a great amount of CPU resources. 

![Download Octave](https://user-images.githubusercontent.com/46381867/144778832-a237d8d4-3cdc-4a2b-bae0-bb4af17579ae.png)
![Watch a YouTube video](https://user-images.githubusercontent.com/46381867/144778853-8510eef7-0bf3-44d3-95c7-eb04b2aad405.png)

### Config and error log in detail (with all sensitive info masked)

```
"configs": [
    {
      "method": "chacha20-ietf-poly1305",
    }
  ],
  "onlineConfigSource": [],
  "strategy": null,
  "index": 3,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "firstRun": false,
  "localPort": 1080,
  "portableMode": false,
  "showPluginOutput": false,
  "pacUrl": "",
  "useOnlinePac": false,
  "secureLocalPac": true,
  "regeneratePacOnUpdate": true,
  "autoCheckUpdate": false,
  "checkPreRelease": false,
  "skippedUpdateVersion": "",
  "isVerboseLogging": true,
  "isIPv6Enabled": false,
  "generateLegacyUrl": false,
  "geositeUrl": "",
  "geositeSha256sumUrl": "",
```

```
DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
DEBUG|Shadowsocks.Controller.TCPHandler|connect to ftpmirror.gnu.org:443
DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server
DEBUG|Shadowsocks.Controller.TCPHandler|connect to ftpmirror.gnu.org:443
DEBUG|Shadowsocks.Controller.TCPHandler|connect to ftpmirror.gnu.org:443
DEBUG|Shadowsocks.Controller.TCPHandler|connect to ftpmirror.gnu.org:443
DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: 
DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: 
DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: 
DEBUG|Shadowsocks.Controller.TCPHandler|connect to ftpmirror.gnu.org:443
DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: 
DEBUG|Shadowsocks.Controller.TCPHandler|connect to ftpmirror.gnu.org:443
DEBUG|Shadowsocks.Controller.TCPHandler|connect to ftpmirror.gnu.org:443
DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: 
```

**Comment by chenshaoju** [comment]
Please download Process Explorer from https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer and follow the picture to take a screenshot of when this issue happened.

![Snipaste_2021-12-07_15-04-54](https://user-images.githubusercontent.com/515763/144982439-b0ed819d-576b-49fb-83ff-d19a3c7e5b42.png)

**Comment by randef1ned** [comment]
Yes I've already had checked it in Process Explorer. 

The screenshot is obtained while watching YouTube video. 

Shadowsocks.exe's starting address: clr.dll!CoUninitializeEE+0x135a0
![Shadowsocks](https://user-images.githubusercontent.com/46381867/144991330-73ffb883-af19-43df-9a7c-93c5cd276856.png)

ss_privoxy.exe's starting address: msvcrt.dll!endthread+0x40
![ss_privoxy](https://user-images.githubusercontent.com/46381867/144991934-41025f41-e528-4fb0-a387-2ebad792e70d.png)

**Comment by chenshaoju** [comment]
I tested on my Shadowsocks, The CPU usage was less than 5%.

![Snipaste_2021-12-08_14-53-41](https://user-images.githubusercontent.com/515763/145162562-ea1a1d07-3992-4394-9de5-07b8d320411d.png)


This issue may cause by your .NET Framework damage, Please try to repair or reinstall .NET Framework: https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by Wwh0429** [comment]
你发的邮件我已收到,我会尽快给你回复 !

**Comment by ccy2019** [comment]
您的邮件已收到，感谢您对我们活动的支持。

**Comment by randef1ned** [comment]
Reinstalled but the problem exists. 
I'm going to reproduce it on my virtual machine and record the detailed steps.

**Comment by randef1ned** [comment]
Thanks for your waiting and I've made a fresh installation of Windows 10 LTSC 2019, then, the fresh installed Windows 10 has some msu patches installed. 

Next, I visited [fast.com](https://fast.com). The CPU usage of Shadowsocks client was significantly higher than 5%, and the overall occupancy is nearly 100%. 

The list of *.msu files:

- [kb4486153](http://download.windowsupdate.com/d/msdownload/update/software/ftpk/2020/01/windows10.0-kb4486153-x64_43ee33b302bfdba470542a128a9ee0b58faa5412.msu)
- [kb5006366](http://download.windowsupdate.com/c/msdownload/update/software/updt/2021/09/windows10.0-kb5006366-x64-ndp48_efb89eb8650e3e6502d4e366e310dca651420678.msu)
- [kb5006368](http://download.windowsupdate.com/c/msdownload/update/software/updt/2021/09/windows10.0-kb5006368-x64_a456b267d022e2fb0e96c3d75fb1911ea0d97d5a.msu)

I installed them one by one on my VM and reproduce the bug. Once there is an active network connection, I can do nothing but waiting for the connection close, so there is an inconvenience of my normal work. 
Windows 10 LTSC 2019 was installed on my work PC, so it was uneasy to upgrade to a newer version or a different branch. My working time is 9 am to 9 pm, about 6 or 7 days per week (996 / 997), and Visual Studio is hard to install because offline installer is not provided by Microsoft. 

So, can you help me identify the problem?

**Comment by chenshaoju** [comment]
This is strange, I tested on Windows 10 Pro 21H2  and Windows 10 LTSC 1809, This issue can't reproduce.

![捕获](https://user-images.githubusercontent.com/515763/145666313-28fc2ec7-920d-4f1c-b4c6-daf8b9f8a6cd.PNG)


(The LTSC is running Intel Pentium G2020, may not so fast)

**Comment by randef1ned** [comment]
Truly strange. Did you installed the three patches? My virtual machine can reproduce the bug exactly..

**Comment by chenshaoju** [comment]
I searched on my 1809 and 21H2, I don't have these patchs.

**Comment by randef1ned** [comment]
It is the patches causes the problem. 
May be I should make a clean reinstall of Windows 10. 
Thanks.

**Comment by randef1ned** [comment]
After being successfully installed the Sep 2021 cumulative update for .NET Framework 4.8 (KB5004332), the CPU usage is lowered to about 10% to 20%. 

May be it is the patch KB5006366 / KB5006368 (Nov 2021 cumulative update) that causes the problem. 

I don't know why I can install Sep 2021 update after Nov 2021 update installed, because the former patch is replaced by the latter. 
Bug 10. 

And thanks for your follow up.

**Comment by chenshaoju** [comment]
This is very helpful information, Thanks for the feedback.
