### ISSUE TITLE
Add plain/none when plugin enabled.

### ISSUE THREAD

**Issue by fernvenue** [shadowsocks/shadowsocks-windows#3269]
**Is your feature request related to a problem? Please describe.**
We all know that `plain/none` doesn't encrypt traffic, but when we use plugin, our traffic can be protected in another way, for example, we can use [v2ray-plugin](https://github.com/shadowsocks/v2ray-plugin) to protect our traffic using TLS. In this case, it is completely meaningless for us to use AEAD, and it will increase the burden on the device, especially for mobile devices. 

**Describe the solution you'd like**
When we want to ensure the safety of more users at the same time, we may be able to provide plugin users with more choices alone.

**Describe alternatives you've considered**
Just add `plain/none` for everyone who use plugin or not use plugin, that's understandable, people may not be able to tell the difference between encryption methods, but they must be able to know the difference between encryption and non-encryption.

**Comment by eebssk1** [comment]
If you really need this you can simply fork the project and reverse the changes that deletes the method. As this is a c# project which should really to do.

**Comment by fernvenue** [comment]
> If you really need this you can simply fork the project and reverse the changes that deletes the method. As this is a c# project which should really to do.

Of course I can, just like what I'm doing now. But there are so many people who need this feature, that's why I recommend adding it to the main branch. As I said above, people may not be able to tell the difference between encryption methods, but they must be able to know the difference between encryption and non-encryption. Last, I think [shadowsocks-rust](https://github.com/shadowsocks/shadowsocks-rust#supported-ciphers) is a great example.

**Comment by eebssk1** [comment]
> > If you really need this you can simply fork the project and reverse the changes that deletes the method. As this is a c# project which should really to do.
> 
> Of course I can, just like what I'm doing now. But there are so many people who need this feature, that's why I recommend adding it to the main branch. As I said above, people may not be able to tell the difference between encryption methods, but they must be able to know the difference between encryption and non-encryption. Last, I think [shadowsocks-rust](https://github.com/shadowsocks/shadowsocks-rust#supported-ciphers) is a great example.

I think this won't happen in this port. If you check the old release information you'll find they specifically removed the legacy method on purpose.

**Comment by fernvenue** [comment]
> > > If you really need this you can simply fork the project and reverse the changes that deletes the method. As this is a c# project which should really to do.
> > 
> > 
> > Of course I can, just like what I'm doing now. But there are so many people who need this feature, that's why I recommend adding it to the main branch. As I said above, people may not be able to tell the difference between encryption methods, but they must be able to know the difference between encryption and non-encryption. Last, I think [shadowsocks-rust](https://github.com/shadowsocks/shadowsocks-rust#supported-ciphers) is a great example.
> 
> I think this won't happen in this port. If you check the old release information you'll find they specifically removed the legacy method on purpose.

Okay, but I still wanna know why we need AEAD cipher when we already have TLS by plugin?

**Comment by eebssk1** [comment]
> > > > If you really need this you can simply fork the project and reverse the changes that deletes the method. As this is a c# project which should really to do.
> > > 
> > > 
> > > Of course I can, just like what I'm doing now. But there are so many people who need this feature, that's why I recommend adding it to the main branch. As I said above, people may not be able to tell the difference between encryption methods, but they must be able to know the difference between encryption and non-encryption. Last, I think [shadowsocks-rust](https://github.com/shadowsocks/shadowsocks-rust#supported-ciphers) is a great example.
> > 
> > 
> > I think this won't happen in this port. If you check the old release information you'll find they specifically removed the legacy method on purpose.
> 
> Okay, but I still wanna know why we need AEAD cipher when we already have TLS by plugin?

I'm wondering too..

**Comment by fernvenue** [comment]
So glad to see that `plain/none` cipher added in the [4.4.1.0](https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.4.1.0) update, thanks for dev team and I am gonna close this issue for now.
