### ISSUE TITLE
ubuntu系统，tanpopo客户端无法修改代理模式（默认本地模式）

### ISSUE THREAD

**Issue by liuminsong** [shadowsocks/shadowsocks-windows#3286]
### 简要描述问题
ubuntu系统，tanpopo客户端无法修改代理模式（默认本地模式）
### 环境
ubuntu
- Shadowsocks客户端版本：tanpopo 0.3.1
- 操作系统版本：ubuntu16.04
- .NET版本：

### 操作步骤
tanpopo已按教程正常安装，但是在修改系统代理步骤卡住，在客户端图标右键的选项中，没有系统代理模式选择的选项

### 期望的结果
能够科学上网

### 实际结果
在客户端图标右键的选项中，没有系统代理模式选择的选项

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by liuminsong** [comment]
![Uploading 微信图片_20220218171614.png…]()

**Comment by liuminsong** [comment]
![微信图片_20220218171619](https://user-images.githubusercontent.com/49279684/154653589-3b5bcb84-51cd-4647-9bff-e16739e1d469.png)

**Comment by liuminsong** [comment]
![微信图片_20220218171614](https://user-images.githubusercontent.com/49279684/154653659-2942292e-49d5-41ae-9475-ac6e978d3cb4.png)

**Comment by chenshaoju** [comment]
请移步 https://github.com/TanpopoApp/tanpopo ，这是两个不同的项目。
