### ISSUE TITLE
貌似加密方式没有aes-126-ctr的啊，还有认证方式也没找到

### ISSUE THREAD

**Issue by 18855441015** [shadowsocks/shadowsocks-windows#3287]
### 环境

- Shadowsocks客户端版本：4.4.10
- 操作系统版本：window10
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```
![image](https://user-images.githubusercontent.com/64298323/155113909-23efe607-382c-4317-a0c7-69b1f4f2d432.png)

**Comment by chenshaoju** [comment]
该加密方法不安全。

另外，SS不兼容SSR协议，如果你所使用的服务是SSR的，你需要使用SSR客户端。
