### ISSUE TITLE
非预期错误, Shadowsocks将退出。System.ArgumentException:字体"Consolas"不支持样式“ Regular"。

### ISSUE THREAD

**Issue by xghs** [shadowsocks/shadowsocks-windows#3292]
### 环境

- Shadowsocks客户端版本：4.4.1.0
- 操作系统版本：Win 7 旗舰版
- .NET版本：4.7

### 操作步骤

1、启动电脑
2、运行程序

### 期望的结果

正常使用

### 实际结果

更新NET版本后，启动Shadowsocks就一直提示以下对话框，请问怎么样才可以解决呢？
![image](https://user-images.githubusercontent.com/101251487/157412492-2c0443af-3864-4d46-9727-912298c2f68f.png)

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1940

**Comment by xghs** [comment]
> #1940

问题已经解决，非常感谢！
