### ISSUE TITLE
错误弹窗：Privoxy Error

### ISSUE THREAD

**Issue by a8181811** [shadowsocks/shadowsocks-windows#330]
Fatal error: can't check configuration file 'C:\Users\my\AppData\Local\Temp\privoxy.conf':  (error number 2)
![1](https://cloud.githubusercontent.com/assets/2673145/10035294/20c9b862-61cb-11e5-9a6b-a0e550802f41.png)
该问题在2.5.6版本中已经存在，2.5.8中依然有这个错误弹窗，如需提供其他信息，请留言，谢谢~

**Comment by Arnaud-Github** [comment]
另外出现"注册表无法修改"弹窗，可以给个解决方法

**Comment by bigtan** [comment]
楼上二位是不是开了什么杀软，试试管理员权限运行和杀软放行

**Comment by Arnaud-Github** [comment]
@bigtan 这个我没试过，出现"注册表无法修改"是我在网吧的，在家正常，不过也有部分用户反馈会这样

**Comment by GangZhuo** [comment]
估计是安装了什么系统清理工具。可以试试 Portable Mode。 https://github.com/shadowsocks/shadowsocks-windows/blob/master/README.md#portable-mode

**Comment by a8181811** [comment]
@GangZhuo 好的，我刚刚尝试Portable Mode，有问题再反馈。

**Comment by renjie45** [comment]
我用CCleaner清理后就会有这个提示，不清理就没问题。

**Comment by icylogic** [comment]
清理软件一般会删除%TEMP%下的文件，默认情况 ss_privoxy.exe, dll, 统计数据等文件都在那。

**Comment by a8181811** [comment]
@icylogic 多谢解答，受教了。

**Comment by nmgwddj** [comment]
经排查发现我这里不是什么清理工具导致，而是快播播放器在退出时执行了清理 temp 目录的操作。导致程序报错。
![2016-03-21_094612](https://cloud.githubusercontent.com/assets/13995319/13909244/4ffa35f0-ef4a-11e5-826a-2fc86addf68a.png)

**Comment by szwuzy** [comment]
重启shadowsockets主程序，自动重新生成privoxy.conf即可。
