### ISSUE TITLE
Unable to start Shadowsocks

### ISSUE THREAD

**Issue by AlexWayfer** [shadowsocks/shadowsocks-windows#3301]
### Describe the bug

Everything has been worked for weeks.

But today I'vefaced this error after Windows 11 startup.

And get it every attempt to launch it manually.

![image](https://user-images.githubusercontent.com/6510020/162474272-0ea2aa43-9d5c-4fb3-b043-0bb5d3bc2287.png)

### Environment

- Shadowsocks client version: 4.4.1.0
- OS version: Windows 11
- .NET version: don't know how to check.

### Steps you have tried

Nothing. There is no new versions of SS.

### What did you expect to see?

Correct work.

### What did you see instead?

Crash on launch.

### Config and error log in detail (with all sensitive info masked)

```
Where should I take it?
```

**Comment by chenshaoju** [comment]
This issue looks like your shadowsocks config file is corrupted.

Please rename or delete `gui-config.json` file from your shadowsocks.exe folder, and re-config again.

for more info: https://github.com/shadowsocks/shadowsocks-windows/issues/3042

**Comment by AlexWayfer** [comment]
Thank you.

It's sad that any reboot (I haven't done any emergency shutdowns) can corrupt configuration files.

Probably they should be closed (unload from RAM) when data is loaded.

BTW, re-installation of SS helped.

**Comment by SeyyedKhandon** [comment]
I have this error after upgrading to windows 11. It keeps showing error on each port I've tested...
![image](https://user-images.githubusercontent.com/59599950/163537821-41e5f7b2-703d-45c2-873d-9123ecab593c.png)

**Comment by chenshaoju** [comment]
It's not a same issue,but you can start command prompt as Administrator, and run this command:
`reg add HKLM\SYSTEM\CurrentControlSet\Services\hns\State /v EnableExcludedPortRange /d 0 /f`

After success, reboot.

**Comment by Nessssss11** [comment]
> This issue looks like your shadowsocks config file is corrupted.
> 
> Please rename or delete `gui-config.json` file from your shadowsocks.exe folder, and re-config again.
> 
> for more info: #3042

How to re-config gui-config.json ? I deleted all shadowsocks files , but my proxy don’t work now

**Comment by Nessssss11** [comment]
![Uploading 020F31B7-1C6F-4736-BE0C-16EEC606FB41.jpeg…]()

**Comment by Nessssss11** [comment]
![640E7C48-BBF4-404E-97AE-ADD3164FED6F](https://github.com/user-attachments/assets/e25e5024-c6bb-45c4-a713-1e4430e4acb4)
![168655CF-5E24-4E7C-8EAB-4093BA9FA094](https://github.com/user-attachments/assets/ec5e9f26-f917-4afc-9df2-673dbb8b17d6)
![2A8D740A-825A-4CA9-8241-38F8CDBA64A1](https://github.com/user-attachments/assets/75383d91-7bac-4586-b334-25ca7957df45)
