### ISSUE TITLE
Support for url server addres

### ISSUE THREAD

**Issue by 0xCA** [shadowsocks/shadowsocks-windows#3302]
**Is your feature request related to a problem? Please describe.**
Servers defined as url are not working. If I manually resolve the url to IP, then replace url with IP in settings, it works normally.

**Describe the solution you'd like**
Built-in support for setting server address as url

**Comment by chenshaoju** [comment]
Shadowsocks for Windows support domain name resolution, The domain name should look like `ss.example.com`.

If your domain name looks like `http://ss.example.com/abcdefg`, then not working.

for example:
![image](https://user-images.githubusercontent.com/515763/162695724-faded2a2-a72f-4b31-8a80-72483a89ce9f.png)

**Comment by 0xCA** [comment]
My url looks like `aa-bb-cc-d41.xy-z.eu`
Could it be that - is not supported?

**Comment by chenshaoju** [comment]
This looks like your ISPs IP reverse domain name or hostname, which may not using as a domain name. can you use the `ping` command for this domain name from another network node or computer?

![image](https://user-images.githubusercontent.com/515763/162860666-bae515d4-077b-4db4-b9a8-0e8f3b87bc81.png)

**Comment by chenshaoju** [comment]
for now, if you want to prefer IPv4 over IPv6, may try: https://docs.microsoft.com/en-AU/troubleshoot/windows-server/networking/configure-ipv6-in-windows

**Comment by 0xCA** [comment]
After reboot, that helped! So it's indeed a no-fallback issue. Thanks!
I hope built-in fallback will be added in future versions
