### ISSUE TITLE
Unable to use Shadowsocks - System.TypeInitializationException and port 1080 is reserved error

### ISSUE THREAD

**Issue by SeyyedKhandon** [shadowsocks/shadowsocks-windows#3304]
### Describe the bug

Everything has been worked for weeks. But today I've faced this error after Windows 11 Installation (Clean installation) 
and get it every attempt to launch it manually.

### Environment

Shadowsocks client version: 4.4.1.0
OS version: Windows 11
.NET version: don't know how to check.

![image](https://user-images.githubusercontent.com/59599950/163546377-57baa6c9-1935-4c3b-af10-86956edefe34.png)

![image](https://user-images.githubusercontent.com/59599950/163547040-028eb827-4bce-4ecb-a92b-fcef198e6044.png)

**Comment by chenshaoju** [comment]
Frist image, please run the "non-Program files" folder, Like `D:\SS\`.
Second image: https://github.com/shadowsocks/shadowsocks-windows/issues/3301#issuecomment-1100598413

**Comment by SeyyedKhandon** [comment]
Thank you, My problem has been fixed.

**Comment by SeyyedKhandon** [comment]
After hibernating windows 11 and then turning it on, this error happens again which tells me the port is reserved😐
![image](https://user-images.githubusercontent.com/59599950/163700500-319ea89c-4803-44c1-a530-989e3cd8dcb8.png)

**Comment by chenshaoju** [comment]
May I ask, are you using Hyper-V? this issue looks like only happens when installed Hyper-V.

**Comment by SeyyedKhandon** [comment]
No, the HyperV is disabled by default in Windows 11.
![image](https://user-images.githubusercontent.com/59599950/163713654-c038b37a-cf64-4a65-a048-2775db91c356.png)

**Comment by chenshaoju** [comment]
Odd, maybe you need to change a port in Shadowsocks at the `Edit Servers` interface.
![image](https://user-images.githubusercontent.com/515763/163719330-8d009e40-000a-4b93-9c52-6c1aff88699f.png)

**Comment by SeyyedKhandon** [comment]
Thanks, but I need to fix this.

**Comment by SeyyedKhandon** [comment]
the problem has been fixed😑
and i don't know how.
