### ISSUE TITLE
即使用了PAC模式，国内常用网站会莫名被拖慢……

### ISSUE THREAD

**Issue by Loyalsoldier** [shadowsocks/shadowsocks-windows#332]
2.5.7 以及 2.5.8 都有一个问题就是：
即使使用的是 PAC 模式，打开国内的常用网站都会被拖慢。
而如果往用户规则里手动过滤该网站，才能恢复正常打开速度。
具体是什么问题？特别好奇。

**Comment by chenshaoju** [comment]
此问题可能和GFWList有关，请前往 https://github.com/gfwlist/gfwlist 咨询。

我是手动写的PAC文件，给你参考：

https://gist.github.com/chenshaoju/52c7555acc65ec98423f

**Comment by icylogic** [comment]
你可以使用 [pactester](https://github.com/manugarg/pactester) 或者 [pacparser](http://pacparser.manugarg.com/) 等工具测试你的 pac 文件针对指定 url 会给出直连还是代理.

**Comment by Loyalsoldier** [comment]
解决方案貌似是这个：https://github.com/gfwlist/gfwlist/issues/25#issuecomment-143316555
