### ISSUE TITLE
The settings in the "gui-config.json" file are reset when Shadowsocks is enabled or disabled

### ISSUE THREAD

**Issue by preegnees** [shadowsocks/shadowsocks-windows#3323]
### Describe the bug
When I changed the "user-agent" in the "gui-config.json" file and started Shadowsocks, then settings reset. The same thing happens when you disable the app. I mean that I can't change the default settings. I couldn't find where exactly in the code this happens. 
At the same time, after changing the source code, I noticed that in order for the settings to change, you also need to change the name of the configuration file "gui-config.json" (for example, to "gui_config.json"). I don't know why it happens, but it's not the main bug.

### Environment
- Shadowsocks client version: 4.4.1.0
- OS version: Windows 10
- .NET version: v3.5

### Steps you have tried
1. Opened the file "gui-config.json".
2. Registered custom "user-agent".
3. Saved the file.
4. Launched Shadowsocks.
5. Then I opened the file "gui-config.json" and saw the default settings there.

### What did you expect to see?
I expected the settings to be saved.

### What did you see instead?
I saw the default settings.

**Comment by chenshaoju** [comment]
Where did you add this line?
In my case, looks fine:
![image](https://user-images.githubusercontent.com/515763/174430442-2e60398a-486b-400f-bfd2-b46bb9ef5dad.png)

**Comment by preegnees** [comment]
![gth](https://user-images.githubusercontent.com/65036687/174431079-3f4861f5-188c-4dd3-a868-961ee3d44ae0.PNG)
This is what my config looks like, I have now done everything again, and it is also reset. I don't understand why this is happening, it's weird.
That is, it generates it again at startup and does not remember my changes.

**Comment by chenshaoju** [comment]
It should be `User-Agent`, not `useragent`.

**Comment by preegnees** [comment]
Are you using version 4.4.1.0 and running it creates a "gui-config.json" file with a "User-Agent" field?
It's just that I have a "userAgent" field created and I can't change it, because the application updates "gui-config.json" with default values on every launch.

**Comment by chenshaoju** [comment]
I think I figured out what had happened here: I'm still using 4.3.3.0 version.

Can you try this version? https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.3.3.0

**Comment by preegnees** [comment]
Lol doesn't work either. I don't understand how such an error can occur. I have also tried older versions and nothing has changed.

**Comment by chenshaoju** [comment]
Can you try this? 
```
  "User-Agent":"Shadowsocks/$",
```

![GIF 2022-06-20 13-09-56](https://user-images.githubusercontent.com/515763/174529424-b6db3fa2-91b8-4401-aa29-4ec38a89ef1c.gif)

**Comment by preegnees** [comment]
Thank you very much, it worked, I just disabled "Shadowsocks" through another button.
![HeM-q2Nrmm0](https://user-images.githubusercontent.com/65036687/174532091-077177e8-acfc-4d02-9857-ae3a26532929.jpg)
