### ISSUE TITLE
win客户端添加订阅，从未成功读取订阅。

### ISSUE THREAD

**Issue by thjw81** [shadowsocks/shadowsocks-windows#3324]
在Windows系统，使用代理订阅、不使用代理订阅、订阅内容转成base64加密、订阅内容直接使用节点字符，都试过，也没有成功。甚至订阅链接使用http、https都试过，还是没有成功。同样的订阅链接，添加到winray、v2ray的Windows客户端都能成功订阅，这样，排除了订阅链接的问题。后来，在shadowsocks安卓客户端，添加订阅链接，同样没有成功读取订阅，从来没有订阅成功过。

### 环境

- Shadowsocks客户端版本：
- 操作系统版本：
- .NET版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
如果你的配置是自己写的，请检查配置格式是否正确。

如果你的配置文件是脚本生成的，请与脚本作者联系。

如果你是购买的机场服务，请与你的机场服务商联系。
