### ISSUE TITLE
ss无法进行在线配置

### ISSUE THREAD

**Issue by Keiichi0** [shadowsocks/shadowsocks-windows#3325]
### 简要描述问题
打开ss在线配置之后更新url显示下列来源更新失败，但是同样的url在别的电脑和手机上都是可用的
### 环境
win10家庭中文版
- Shadowsocks客户端版本：4.4.0.0
- 操作系统版本：win10家庭中文版 x64 
- .NET版本：4.8.03928

### 操作步骤
打开ss——在线配置——填写url——选中填写的url——点击更新

### 期望的结果
更新成功 ss正常使用
### 实际结果
更新失败，请查看日志获取更多信息
### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Shadowsocks.Controller.ShadowsocksController.<UpdateOnlineConfig>d__110.MoveNext()

**Comment by chenshaoju** [comment]
提供的日志没有显示具体的详细信息，在在线配置界面手动点击更新，日志里提示什么？

**Comment by Keiichi0** [comment]
> 提供的日志没有显示具体的详细信息，在在线配置界面手动点击更新，日志里提示什么？

**Comment by GrimmYun** [comment]
我也遇到这个问题，怎么回事啊

**Comment by chenshaoju** [comment]
`The request was aborted: Could not create SSL/TLS secure channel.` 这意味着无法连接你的在线配置的服务器，请将你的配置地址放到浏览器里打开，能下载回来吗？如果下载不了，说明不行。

**Comment by GrimmYun** [comment]
配置地址指的是订阅链接吗，订阅链接在浏览器里打开后，显示的就是所有一堆节点的信息。现在这个问题怎么弄啊？

**Comment by chenshaoju** [comment]
如果能打开的话，我认为应该没有问题，如果你是买的机场服务，请与你的机场服务商取得联系以获得具体的配置方法。

**Comment by GrimmYun** [comment]
买的机场，那就是订阅链接用不了，只能手动添加服务器了吗
