### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by a8181811** [shadowsocks/shadowsocks-windows#333]
[2015-09-24 08:45:05] Shadowsocks started
[2015-09-24 08:45:07] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:8123
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.PortForwarder.Handler.ConnectCallback(IAsyncResult ar)
[2015-09-24 08:58:11] System.IO.IOException: 文件“D:\Program Files (x86)\Shadowsocks\temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()

**Comment by chenshaoju** [comment]
试一下便携模式：
https://github.com/shadowsocks/shadowsocks-windows/blob/master/README.md#portable-mode

**Comment by a8181811** [comment]
@chenshaoju 现在就是便携模式。

**Comment by chenshaoju** [comment]
“D:\Program Files (x86)\Shadowsocks\temp\”　？？？

你新建一个目录，比如 D:\Shadowsocks\ 放进去看看？

**Comment by GangZhuo** [comment]
应该是非正常关闭shadowsocks导致的，如果使用正常的话，可以无视。使用不正常的话，打开任务管理器，强制结束 ss_privoxy.exe，然后再启动shadowsocks。

**Comment by a8181811** [comment]
@chenshaoju @GangZhuo 再出此问题的时候我再试试你们的办法。

**Comment by MichealKong** [comment]
我也遇到这样的情况  请问您是怎解决的？ 另外您可否解释一下便携模式是什么？我电脑只有一个C盘，在进程中没找到ss_privoy.exe，只有privoxy。希望您有空能给一个回复，谢谢！

**Comment by falseen** [comment]
便携模式是指把临时文件写入当前目录下的temp文件夹内，默认是写入系统的临时目录内。没有ss_privoy.exe的话就把privoxy结束了，可能是后来的版本改用privoxy了。

**Comment by a8181811** [comment]
@MichealKong Shadowsocks最新版2.5.8也是有ss_privoy.exe的
![1](https://cloud.githubusercontent.com/assets/2673145/10719485/709f8dc2-7bc4-11e5-9748-010c6430252f.png)

**Comment by chenshaoju** [comment]
你好，的确是有 ss_privoxy.exe 的。你是不是自己开了一个 privoxy.exe ？只要端口不同，是可以并行运行的。

**Comment by MichealKong** [comment]
找到了，嘿嘿   楼主解决方法是什么？

**Comment by is1and** [comment]
把服务端 端口配置成其他端口 原来是8838  换成443解决

**Comment by laishanhai1040** [comment]
是因为服务端开的端口和客户端的端口对不上，把客户端的端口改为服务端设定的端口就可以了。

**Comment by Guolighting** [comment]
现在解决了？

**Comment by Guolighting** [comment]
@MichealKong
