### ISSUE TITLE
由于未经处理的异常，进程终止。

### ISSUE THREAD

**Issue by gouduyao** [shadowsocks/shadowsocks-windows#3332]
### 简要描述问题

打开提示报错
![image](https://user-images.githubusercontent.com/48701703/178198374-5a934bba-e426-4a6e-8bd6-cb977cb6fa8e.png)
尝试.net 4.8安装
![image](https://user-images.githubusercontent.com/48701703/178198709-206a52ea-967f-4a10-941a-24543ce0060a.png)
并且已经使用NetFxRepairTool进行修复，还是无解

### 环境

- Shadowsocks客户端版本：4.1.9.2
- 操作系统版本：windows 10 21H1
- .NET版本：.net 4.8

### 配置文件和日志文件（请隐去敏感信息）

```
应用程序: Shadowsocks.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.Configuration.ConfigurationErrorsException
   在 System.Web.Configuration.RuntimeConfig.GetSection(System.String, System.Type, ResultsIndex)
   在 System.Web.Configuration.RuntimeConfig.get_HttpRuntime()
   在 System.Web.Util.HttpEncoder.GetCustomEncoderFromConfig()
   在 System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   在 System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   在 System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   在 System.Web.Util.HttpEncoder.get_Current()
   在 Shadowsocks.Controller.PACServer.get_PacSecret()
   在 Shadowsocks.Controller.PACServer.UpdatePACURL(Shadowsocks.Model.Configuration)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Program.Main(System.String[])

```

**Comment by chenshaoju** [comment]
有点奇怪，请尝试将 Shadowsocks.exe 单独放到一个新建的目录下，如 D:\SS\ ，然后重新配置试试？

**Comment by gouduyao** [comment]
尝试过，不起作用

**Comment by chenshaoju** [comment]
请先退出SS，然后打开 Internet Explorer 设置，然后找到连接，并点击局域网设置。

然后删除下图中地址中的内容，然后取消选中使用自动配置脚本，然后连续确定直到关闭对话框。

![image](https://user-images.githubusercontent.com/515763/178290690-5d8d5ea5-a501-4fda-af13-a32e739d909f.png)

**Comment by gouduyao** [comment]
不起作用

**Comment by chenshaoju** [comment]
odd……暂时想不出可能的原因了，这个问题可能得先放在这里了。。。

**Comment by juanyilxc** [comment]
看了代码，问题出在System.Web.dll中的   
`internal HttpRuntimeSection HttpRuntime => (HttpRuntimeSection)GetSection("system.web/httpRuntime", typeof(HttpRuntimeSection), ResultsIndex.HttpRuntime);`这一行   
读取system.web/httpRuntime 运行时配置时出错   

所以猜测可能还是运行时的问题     
可以试着在程序和功能里右击.NET Framework 4.8修复     
![Snipaste_2022-08-05_15-14-30](https://user-images.githubusercontent.com/20871492/183023565-c0a8cfd7-a687-433c-abca-815634aad811.png)   
 或者安装其他版本的[dotnet](https://dotnet.microsoft.com/zh-cn/download/dotnet-framework) 并检查系统更新

**Comment by kapaez** [comment]
同样的问题，kcptun插件不行，开启后没有数据传入和传出。但是奇怪的是，我不用插件模式，用kcptunGUI+ss就可以正常转发，所以设置什么的都没有问题。感觉是windows系统某个环节直接切断了通讯。

**Comment by gouduyao** [comment]
最终还是重装了系统解决

**Comment by KislitsaEA** [comment]
The problem occurs when "**System.Net.ComNetOS**" deserializes the configuration file: `"C:\Windows\Microsoft.NET\Framework\v4.*.*\Config\machine.config"`

**Solve:** open the file with  administrator permissions and delete the following lines
```
    <configuration>
        <runtime>
          ....
       </runtime>
    </configuration>
```

**Comment by lalakii** [comment]
**我的解决办法是把配置文件 全部删掉~**
