### ISSUE TITLE
shadowsocks在windows上能用，iPhone上不能用

### ISSUE THREAD

**Issue by mendax1234** [shadowsocks/shadowsocks-windows#3340]
### 简要描述问题

shadowsocks的服务器在Windows上能用，但是在iPhone上却不能用

### 环境

- Shadowsocks客户端版本：4.4.1
- 操作系统版本：windows 10
- .NET版本：

### 期望的结果

在手机iPhone上也能使用shadowsocks

### 实际结果

手机上不能使用shadowsocks

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by mendax1234** [comment]
我用的是azure的服务器，然后ping服务器的IP，ping不通，但是windows上确实能用，而ios端上不行。请问如何解决？

**Comment by chenshaoju** [comment]
请仔细检查你的配置是否一致，如果仍然不行，请与你的iOS上的应用的开发或支持人员联系。
