### ISSUE TITLE
Issue with running on Windows 11 with AMD  ryzen 7

### ISSUE THREAD

**Issue by nandakumarcs** [shadowsocks/shadowsocks-windows#3343]
### Describe the bug
![2022-08-10_14h11_34](https://user-images.githubusercontent.com/15925876/183877096-81143c05-ab61-4b1c-a064-8dd7c7502260.png)

### Environment

- Shadowsocks client version: 4.4.10
- OS version: windows 11 pro
- .NET version:  4.8.04161

### Steps you have tried
When starting the shadowsocks, we are seeing this error in screenshot.

### Config and error log in detail (with all sensitive info masked)

```
PASTE LOG HERE
```

**Comment by chenshaoju** [comment]
Your config is missing v2ray plugin.
Please download here: https://github.com/shadowsocks/v2ray-plugin/releases

**Comment by nandakumarcs** [comment]
Thanks, this worked well!!

**Comment by deadskull77** [comment]
> Thanks, this worked well!!

Hi
I have the same problem what did u do that solve the issue?

**Comment by deadskull77** [comment]
> Your config is missing v2ray plugin. Please download here: https://github.com/shadowsocks/v2ray-plugin/releases

can u elaborate where to put these files please?
