### ISSUE TITLE
Shadowsocks ono-UI error

### ISSUE THREAD

**Issue by ZL-Su** [shadowsocks/shadowsocks-windows#3345]
### Describe the bug
Details of the bug attached below.
![issue-shadowsocks](https://user-images.githubusercontent.com/23275328/185555121-3ea57b9e-a6ba-4bc4-bb03-6d4298063388.png)
vironment

- Shadowsocks client version: 4.4.1.0
- OS version: Windows 11
- .NET version:

### What did you expect to see?
How to make the Showsocks works normally?

### Config and error log in detail (with all sensitive info masked)

```
PASTE LOG HERE
```

**Comment by chenshaoju** [comment]
Please try put `shadowsocks.exe` to a new folder like D:\SS\ ,and try again.

**Comment by ZL-Su** [comment]
> Please try put `shadowsocks.exe` to a new folder like D:\SS\ ,and try again.

THX, I have addressed the issues by replacing the file gui-config.json, cause the old one was corrupted with a sequence of null value.
