### ISSUE TITLE
套个kcptun，浏览器可以访问谷歌，但命令窗口ping google.com 失败

### ISSUE THREAD

**Issue by jingyuLin1999** [shadowsocks/shadowsocks-windows#3367]
### 简要描述问题
套个kcptun，浏览器可以访问谷歌，但ping google.com 失败
小飞机已开启 系统代理->pac模式
### 环境

- Shadowsocks客户端版本：Shadowsocks-4.4.1.0
- 操作系统版本：win10
- .NET版本：未知

### 期望的结果
希望能代理整个电脑的流量，能ping 通谷歌

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
你好，Ping使用的ICMP协议，这个协议无法经过代理。

如果你一定要能Ping，请考虑常规VPN，比如PPTP、L2TP、IPSec等。
