### ISSUE TITLE
一个建议 建议用不同颜色的托盘图标来区分当前是PAC模式还是全局模式

### ISSUE THREAD

**Issue by wildtang** [shadowsocks/shadowsocks-windows#338]
一个建议 建议用不同颜色的托盘图标来区分当前是PAC模式还是全局模式。
现在通过图标颜色，只能区分出是否启用了代理，但区分不出是PAC模式还是全局模式。

我做软件开发的时候，一般用PAC模式，偶尔有某个网站访问不了，我会临时开启全局模式，
不过有的时候会忘了切换回来，只有发现某个国内网址访问特别慢的时候，才会想起来，哦，是开启了全局模式后没有切换回来导致的。

**Comment by fleetingoo** [comment]
建议使用Chrome+SwitchOmega

**Comment by wenliyang** [comment]
Firefox + FoxyProxy 也能做到这点

**Comment by diemus** [comment]
我觉得白色挺好，换了颜色变来变去会很难看，火狐那个插件就是。你可以用楼上说的SwitchyOmega

**Comment by GangZhuo** [comment]
无此计划
