### ISSUE TITLE
clash连接超时，无法访问google

### ISSUE THREAD

**Issue by EllenAdams** [shadowsocks/shadowsocks-windows#3392]
![image](https://user-images.githubusercontent.com/30849347/226074966-d531ea52-b87c-4cb7-aedf-dd451d2d680f.png)

### 简要描述问题
麻烦问下，如何来正确连接到vpn，谢谢 ~

**Comment by xuanhuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。 
  
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Wwh0429** [comment]
你发的邮件我已收到,我会尽快给你回复 !

**Comment by ccy2019** [comment]
您的邮件已收到，感谢您对我们活动的支持。

**Comment by chenshaoju** [comment]
你好，Clash for Windows 的项目地址在 https://github.com/Fndroid/clash_for_windows_pkg/issues 。

这儿是 Shadowsocks for Windows 的。
