### ISSUE TITLE
Unable to set more than one instance start up with windows (2.5.8)

### ISSUE THREAD

**Issue by RadarNyan** [shadowsocks/shadowsocks-windows#341]
It seems like the option is global even if I have shadowsocks_portable_mode.txt created for both copy.

**Comment by GangZhuo** [comment]
You should specify a different proxy port.

**Comment by RadarNyan** [comment]
The two instances are on different ports, I have no problem if I run them manually after boot (strangely, they won't work if I create shortcuts for them in the startup folder, do you know why?)

The problem is, if I check/uncheck the option "Start on Boot" for either instance and restart both, the option would be checked/unchecked for both instances. And even if they're both checked, only one instance would work on next boot.

Last working version for me is 2.5.6, not sure about 2.5.7 though.

**Comment by GangZhuo** [comment]
fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/092d1168ff1c1690c1e627650b4b029430ff5feb
