### ISSUE TITLE
【急！速回！】关于账单莫名其妙消失了且无法使用服务的询问

### ISSUE THREAD

**Issue by MIA123MIA321** [shadowsocks/shadowsocks-windows#3411]
使用服务中发现所有地区都显示timeout，摸到官网发现之前的订购账单不见了。
有订阅截图为证。

![793861686214225_ pic](https://github.com/shadowsocks/shadowsocks-windows/assets/77086531/4b589abc-821a-47c4-b70f-9e82f67ef017)
![793871686214288_ pic](https://github.com/shadowsocks/shadowsocks-windows/assets/77086531/a8740d84-3636-4919-9bb4-71bb8238df48)
![793881686214373_ pic](https://github.com/shadowsocks/shadowsocks-windows/assets/77086531/4e09a079-1476-4133-94d7-59842fcdcd18)
邮箱是zayforever@163.com 订阅了一年

**Comment by MIA123MIA321** [comment]
![794091686214737_ pic](https://github.com/shadowsocks/shadowsocks-windows/assets/77086531/d8fa17d8-3724-4b02-b62f-6803e1f0f170)
 在有效期内 但是全都超时并且登录官网显示没有任何订阅记录

**Comment by LYCX2015** [comment]
您好，请去商家官网找商家，这里只是shadowsocks-windows开发及维护的地方，并未与您所描述的商家有任何合作关系。

**Comment by MARVEL001** [comment]
🤣👉🤡

**Comment by Just-Prog** [comment]
李鬼网站坑钱还请找李鬼算账，与李逵无关
还有，拿着 Clash for Windows 的截图来 shadowsocks-windows 求助？
🤣👉🤡

**Comment by Steve-337** [comment]
驴唇不对马嘴🤣👉🤡

**Comment by MBRjun** [comment]
![IMG_4938](https://github.com/shadowsocks/shadowsocks-windows/assets/55020690/8be97fff-3e85-437f-bb9d-42d9f67b3f7c)

**Comment by aaa-aa-a** [comment]
邮箱贴这么明显，小伙子真的勇。

**Comment by chenshaoju** [comment]
OK, the fun time is over. 👏

**Comment by aldington-david** [comment]
能抢到这域名可真牛，卖这么贵能赚不少钱

**Comment by MIA123MIA321** [comment]
十分抱歉 出了乌龙  账户记差了

**Comment by MARVEL001** [comment]
> 十分抱抱出来了乌龙 账号记差了

账号记对了你也不应该找到这啊🤣

**Comment by aldington-david** [comment]
做代理客户端的一般都不会有自己的鸡场，有的都是套皮，域名相关纯属抢注🤣能买到60多一个月纯属域名加成，一般10就可以买500g了

**Comment by Huaxidesu** [comment]
来晚了，乐子没了😓

**Comment by Aloento** [comment]
谁有原始消息*
