### ISSUE TITLE
SS fails to handle new Google Drive Windows Desktop by proxy.

### ISSUE THREAD

**Issue by MCOAB152** [shadowsocks/shadowsocks-windows#342]
Google Drive new version 1.25.
The problem that has been reported to Google Support Team is under processing,
but can you developers resolve this problem ahead of what may NOT be done by GST？
The reason is GST refuses to provide any further support for PROXY which is not promoted by them.

**Comment by shuangzhijinghua** [comment]
in google drive desktop program settings, use Auto Detect Proxy Setting, and enable shadowsocks System proxy it will be work fine.

**Comment by MCOAB152** [comment]
@shuangzhijinghua I confirm much that all the settings are fine.
The problem has been tested on few computers(3).
If your GD operates functionally, you should check version tag that may below 1.25+(1.24).

**Comment by shuangzhijinghua** [comment]
tested on GD v1.25, with shadowsocks system proxy enabled. it work fine.

MCOAB152 <notifications@github.com>于2015年10月3日周六 上午12:25写道：

**Comment by MCOAB152** [comment]
@shuangzhijinghua with ShadowSocks 2.5.6 released by clowwindy?

**Comment by shuangzhijinghua** [comment]
no, I use breakwa11's client, up to date GFW List.

MCOAB152 <notifications@github.com>于2015年10月3日周六 上午12:37写道：

**Comment by MCOAB152** [comment]
@shuangzhijinghua Thanks, but this problem is not with a variation verison.

**Comment by shuangzhijinghua** [comment]
I dont think this problem caused by the shadowsocks version, because
shadowsocks system proxy set the IE proxy setting to PAC mode or
proxy-all-trafic. maybe your PAC file is not latest, or your system's proxy
setting cannot be modified.

MCOAB152 <notifications@github.com>于2015年10月3日周六 上午12:43写道：

**Comment by MCOAB152** [comment]
@shuangzhijinghua I did check PAC working normally, and i can connect to any Google Serive using IE at the same time.

**Comment by Marvin-D** [comment]
Same issue happens on my system, googledrivesync after v1.25 does not work with shadowsocks, but when I rollback to the GDS v1.24, it works just fine.
you may find a trustable distribution via http://dl.google.com/drive/1.24.9931.5480/gsync.msi

**Comment by icylogic** [comment]
Does this happen on previous Shadowsocks versions ? Could you provide relevant logs?

**Comment by chenshaoju** [comment]
This issue may case by Google Drive,Not shadowsocks.
After I update to Google Drive 1.25 ,The PAC is working in IE,But not work in Google Drive.
Rollback Google Drive to 1.24 is work again.

Here is Google Driver about this issue discuss page: https://productforums.google.com/forum/#!msg/drive/iKtE7z0VV_Q/MADXZreHBgAJ

**Comment by MCOAB152** [comment]
@chenshaoju @icylogic @Marvin-D @shuangzhijinghua
This issue has now been officially resolved.
A new version of Google Drive will include a hostfix sent by GST.
Due to trust principles, i will not send it out.

PS, it the latest version of GD will be released soon, GST said(1-2 weeks).
