### ISSUE TITLE
pac模式http400错误

### ISSUE THREAD

**Issue by better0332** [shadowsocks/shadowsocks-windows#343]
勾选允许局域网连接，
不能用域名的方式访问局域网中地址http://域名:1080/pac?t=201510091554385936，返回http 400

**Comment by GangZhuo** [comment]
设计就是这样的

**Comment by better0332** [comment]
我觉得应该判断remoteip是否来自本局域网，而不是看Host
局域网shadowsocks作为服务，当然可以有域名

**Comment by GangZhuo** [comment]
有域名的话，就要解析域名，然后才能判断此域名是否指向本机，这会拖慢速度。

**Comment by better0332** [comment]
恩，有道理。但启动时获得本机的IP列表就可以

**Comment by GangZhuo** [comment]
判断来自局域网是不行的，别人使用你的http代理时，也是来自局域网的ip.
