### ISSUE TITLE
手机端Google软件无法连接

### ISSUE THREAD

**Issue by mifia** [shadowsocks/shadowsocks-windows#3434]
### 简要描述问题
最近突然手机端Google系软件无法连接了，IP端口都正常，PC端正常使用。手机端chrome可以使用，chrome内使用youtube也没有问题，就是软件无法联网，例如youtube ,photos等等。Reboot可以短暂的使用几分钟，然后就不行了。同一台机器的AMD一模一样的配置，手机端就没有这个问题。

### 环境
甲骨文ARM的机器，Ubuntu20的系统，SS+V2ray plugin，手机：荣耀V30Pro,鸿蒙3.0
- Shadowsocks客户端版本：5.2.6
- 操作系统版本：
- .NET版本：

### 操作步骤
切换端口也没有用。手机重启也不行。

### 期望的结果
是ARM需要特别的设置吗？可是之前一直使用都没有这样的问题，正常使用快一年了，最近一周出现的问题

### 配置文件和日志文件（请隐去敏感信息）
没找到怎么调取日志文件，请大佬告知。
```
在此粘贴日志
```

**Comment by chenshaoju** [comment]
你用的是 shadowsocks-android 吗？如果是，请移步： https://github.com/shadowsocks/shadowsocks-android/issues 。

**Comment by mifia** [comment]
好的
