### ISSUE TITLE
请求大佬帮助

### ISSUE THREAD

**Issue by jiaohuadenaitang** [shadowsocks/shadowsocks-windows#3459]
第一次使用ssr遇到了诸多问题 目前按照教程使用无法访问外网 如图
<img width="659" alt="屏幕截图 2024-01-22 162908" src="https://github.com/shadowsocks/shadowsocks-windows/assets/155887736/23bd32de-2dd2-40d0-9bc3-82afbcf49203">
<img width="729" alt="屏幕截图 2024-01-22 163135" src="https://github.com/shadowsocks/shadowsocks-windows/assets/155887736/2477c9ae-c9b2-45f0-b78e-53a318262eaa">
<img width="511" alt="屏幕截图 2024-01-22 163219" src="https://github.com/shadowsocks/shadowsocks-windows/assets/155887736/2432b42d-6914-4e62-86de-edb5bc97bbd2">

**Comment by chenshaoju** [comment]
你这是ShadowsocksR，这和Shadowsocks是不同的东西……

另外，不排除FreeSSR所提供的服务器有问题，如果可能，请与FreeSSR联系。
