### ISSUE TITLE
编译报错，System.Net.Http找不到？

### ISSUE THREAD

**Issue by huhu2207** [shadowsocks/shadowsocks-windows#346]
各位大神好，

我这环境是Win10 RTM, Visual Studio 2015 Community，已安装所有补丁更新。

这是直接用git clone下来的代码，没改动任何配置直接编译的结果。

刚试了下最新版本编译会报错，结果见图：

![1](https://cloud.githubusercontent.com/assets/4463497/10413883/d9cf1c4a-7007-11e5-8b6b-f97f788cefc4.png)
![2](https://cloud.githubusercontent.com/assets/4463497/10413884/d9d19dee-7007-11e5-8398-de849212938c.png)
![3](https://cloud.githubusercontent.com/assets/4463497/10413885/d9d1ad0c-7007-11e5-8896-5b1b7907e8c7.png)

**但是如果编译稍早些时候的版本却能通过，也就是我上回给pull request的那个版本:**（ https://github.com/shadowsocks/shadowsocks-windows/commit/b4699492ad3c54a4dab3d0ca60bea4d587b73d3b  ）。

**后来我又用System.Net.Http写了个小程序，一切正常。请问这是我环境配置有问题？还是代码有问题？**

先谢谢了！

Jackson

**Comment by everyx** [comment]
需要安装对应版本的 System.Net.Http
![使用 NuGet 安装](http://i11.tietuku.com/0438746d38f9761a.png)
![选择对应的版本](http://i11.tietuku.com/37607b413e7c6629.png)

**Comment by huhu2207** [comment]
回复楼上everyx，
试过得到以下输出：
```
Attempting to gather dependencies information for package 'System.Net.Http.4.0.0' with respect to project 'shadowsocks-csharp', targeting '.NETFramework,Version=v4.0,Profile=Client'
Attempting to resolve dependencies for package 'System.Net.Http.4.0.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'System.Net.Http.4.0.0'
Resolved actions to install package 'System.Net.Http.4.0.0'
Install failed. Rolling back...
Package 'System.Net.Http 4.0.0' does not exist in project 'shadowsocks-csharp'
Package 'System.Net.Http 4.0.0' does not exist in folder 'C:\Users\hu\Desktop\shadowsocks-windows-master\shadowsocks-csharp\3rd'
Could not install package 'System.Net.Http 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========
```

**后来重装了VS，然后又重置了系统，依然报错，醉了**

**Comment by huhu2207** [comment]
再次测试，上回使用的是github的zip打包下载，怀疑可能有问题，于是直接用git clone，
然后尝试编译，安装System.Net.Http报错，得到结果跟之前一次完全一样，

```
Attempting to gather dependencies information for package 'System.Net.Http.4.0.0' with respect to project 'shadowsocks-csharp', targeting '.NETFramework,Version=v4.0,Profile=Client'
Attempting to resolve dependencies for package 'System.Net.Http.4.0.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'System.Net.Http.4.0.0'
Resolved actions to install package 'System.Net.Http.4.0.0'
Install failed. Rolling back...
Package 'System.Net.Http 4.0.0' does not exist in project 'shadowsocks-csharp'
Package 'System.Net.Http 4.0.0' does not exist in folder 'C:\Users\hu\Documents\projects\shadowsocks-windows\shadowsocks-csharp\3rd'
Could not install package 'System.Net.Http 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========
```

另有个错误信息：
```
Could not install package 'System.Net.Http 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by everyx** [comment]
你的版本选错了，默认是安装最新版本的 'System.Net.Http 4.0.0' 的，请安装我上图中标注的版本，要不然会安装不成功

**Comment by everyx** [comment]
你的版本选错了，默认是安装最新版本的 'System.Net.Http 4.0.0' 的，请安装我上图中标注的版本，要不然会安装不成功

**Comment by huhu2207** [comment]
![capture](https://cloud.githubusercontent.com/assets/4463497/10420165/09cd8af0-70d8-11e5-8e2c-ebf2ce6f8fb2.png)

**确实是4.0.0，但依然报错……**

**Comment by huhu2207** [comment]
另外，用学校电脑的VS2013 pro @ win7也是一样的……但编译别的项目却正常。

**Comment by huhu2207** [comment]
好吧，刚试了下装System.Net.Http 2.0，居然装上了，一切正常，但要更新到4.0时就报错。原因不明，在学校电脑上试了试也是这样，不知咋回事……

**Comment by everyx** [comment]
这不是原因不明，这些事和项目选择的 .Net Framework 版本有关系的，请注意之间的依赖关系

**Comment by huhu2207** [comment]
可是我都按原来默认的选了.NET Framework 4 Client profile啊，为何不能装4.0.0呢？

**Comment by CpkH** [comment]
安装Microsoft.Net.Http这个包就可以了

**Comment by everyx** [comment]
@huhu2207 这个版本号和 .Net Framework 的版本不是一样的，你自己搜索搜索就知道了

**Comment by huhu2207** [comment]
@everyx 哦明白了，仔细看了下依赖关系只有2.x的才支持.NET Framework 4，多谢指教！
