### ISSUE TITLE
Shadowsocks client won't start

### ISSUE THREAD

**Issue by MimoSno** [shadowsocks/shadowsocks-windows#3464]
### Environment

- Shadowsocks client version: 4.4.1.0
- OS version: Windows 10 Pro 22H2
- .NET version: 7.0.305

### Steps you have tried
I tried restarting shadowsocks

### What did you expect to see?
I was expecting the shadowsocks icon to appear in the tray so I could use it

### What did you see instead?
![image](https://github.com/shadowsocks/shadowsocks-windows/assets/91504469/79e2a25c-c18e-4d3b-9f8b-f4735a040088)

### Config and error log in detail (with all sensitive info masked)
I don't know where to get the logs

P.S Shadowsocks was working fine before this, no system upgrades

**Comment by chenshaoju** [comment]
please install https://www.microsoft.com/en-us/download/details.aspx?id=17718 ,if has been installed, please repair.

**Comment by MimoSno** [comment]
A newer version is installed so I can't repair it, should I uninstall .NET?

**Comment by chenshaoju** [comment]
Try this: https://www.microsoft.com/en-us/download/details.aspx?id=30135

**Comment by MimoSno** [comment]
![image](https://github.com/shadowsocks/shadowsocks-windows/assets/91504469/a8ec61e4-5a78-427e-8347-4cf1c3e66011)
Well, i have this

**Comment by MimoSno** [comment]
And I found that if you click the delete button in programs and components in the control panel when selecting the current .NET, a window will appear where you can both delete and restore .NET

**Comment by MimoSno** [comment]
restore did not help, the error also appears, I will try reinstalling .NET

**Comment by MimoSno** [comment]
I uninstalled everything related to .NET and the error is the same, probably I need to reinstall the client itself

**Comment by MimoSno** [comment]
Reinstalling the client fixed the issue

**Comment by chenshaoju** [comment]
👏
