### ISSUE TITLE
Shadowsocks stopped working

### ISSUE THREAD

**Issue by VanVanddd** [shadowsocks/shadowsocks-windows#3470]
Hi, did anyone have such a problem: the glass stopped loading on the Khabarovsk proxy, out of the blue, with the computer turned on (it worked yesterday, not today) the proxy itself is normal-80ms, the server is active, the exchange's fapi has been checked and even changed, the CScalp terminal itself works without a proxy, but there is a connection error when it connects via Shadowsocks. Nothing at all. I didn't touch anything and stopped working. What could be the problem?
does the provider ban you? I wasn't the only one with a problem.
![еее](https://github.com/shadowsocks/shadowsocks-windows/assets/171024823/a82e5caf-9450-4b30-acd1-0831c91843d5)
![е](https://github.com/shadowsocks/shadowsocks-windows/assets/171024823/060f18b6-8988-4e8b-a320-3e867dbe653e)

**Comment by xuanhuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。 
  
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ccy2019** [comment]
您的邮件已收到，感谢您对我们活动的支持。

**Comment by chenshaoju** [comment]
Пожалуйста, попробуйте изменить "Порт прокси" на другой порт в интерфейсе "Редактирование сервера", например, на порт 1081.

**Comment by VanVanddd** [comment]
> Пожалуйста, измените формат «Порт прокси» на другой порт в интерфейсе «Редактирование сервера», например, на порт 1081.

подскажите, а саму настройку сервера тоже тогда нужно изменить под новый порт? потому что я их связывал как то при покупке и настройке прокси

**Comment by chenshaoju** [comment]
Эта проблема может быть вызвана тем, что порт 1080 занят другим приложением. Настройка "прокси-порта" является глобальной, поэтому нет необходимости изменять номер порта сервера, достаточно изменить номер порта прокси-порта.

![Snipaste_2024-05-28_21-32-07](https://github.com/shadowsocks/shadowsocks-windows/assets/515763/2d867cde-aecc-44f6-b5b7-fd6ff2a7a4d1)

**Comment by VanVanddd** [comment]
> Эта проблема может быть вызвана тем, что порт 1080 занят другим приложением. Настройка "прокси-порта" является глобальной, поэтому нет необходимости изменять номер порта сервера, достаточно изменить номер порта прокси-порта.
----Спасибо за попытку, но не помогло, изначально когда я пытался понять че случилось, я возможно пытался запустить вторую программу эту, поэтому в журнале так и отобразилось : "порт уже используется"
Так же уточню, что это проблема не только у меня, сейчас нас пока трое кто объявился за 2 часа.

**Comment by chenshaoju** [comment]
Если прокси внезапно перестал работать без изменения настроек программного обеспечения, высока вероятность, что это связано с тем, что поставщик услуг прокси-сервера прекратил обслуживание вашего аккаунта. Возможные причины включают, но не ограничиваются окончанием срока действия аккаунта или исчерпанием трафика. Рекомендуем связаться с вашим поставщиком услуг прокси-сервера.

**Comment by VanVanddd** [comment]
> Если прокси внезапно перестанет работать без изменения настроек программного обеспечения, высока вероятность, что это связано с тем, что поставщик услуг прокси-сервера ограничит обслуживание вашего аккаунта. Возможные причины включают, но не ограничивают срок действия окон счета или исчерпание трафика. Рекомендуем связаться с вашим поставщиком услуг прокси-сервера.

Друг, с ними все в порядке, и прокси отлично пингуется, до места назначения, антивируса нет, все проверил что мог, осталось выяснить что за ошибка 443 или перенастроить сам сервер(хотя понятия не имею что там могло и КАК слететь)

**Comment by VanVanddd** [comment]
Восстановили старый канал работы через 3 дня. Благодарю за время и советы как можно было исправить мою ситуацию. Возможно пригодиться в будущем!

**Comment by chenshaoju** [comment]
👏
