### ISSUE TITLE
System.NullReferencesException

### ISSUE THREAD

**Issue by praisesunsei** [shadowsocks/shadowsocks-windows#3472]
### Describe the bug
![image](https://github.com/shadowsocks/shadowsocks-windows/assets/98443925/9fa7d209-dce7-495e-b11e-67e9f25641b5)

### Environment

- Shadowsocks client version:
- OS version: Windows 10
- .NET version: 2.0.50727.4927
### Config and error log in detail (with all sensitive info masked)

```
PASTE LOG HERE
```

**Comment by chenshaoju** [comment]
Please install: https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-offline-installer

**Comment by EntityinArray** [comment]
> Please install: https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-offline-installer

does not help, only removing `gui-config.json` works.
this is a bug in your code

**Comment by HDYA** [comment]
Hit the same issue, removing `gui-config.json` did work. Which is weird as it seems to be an empty file.
Windows 11 23H2 22631.4317
