### ISSUE TITLE
The app does not redirect all traffic through the remote server

### ISSUE THREAD

**Issue by atellmer** [shadowsocks/shadowsocks-windows#3482]
### Describe the bug
After enabling System Proxy as global, this changes the real IP in Chrome, but the system itself does not pass all traffic through the remote server.
`curl ifconfig.me` gives the real IP.

### Environment
- Shadowsocks client version: 4.4.1.0
- OS version: 11
- .NET version: 4.8.1

### Steps you have tried
- Run Shadowsocks.exe
- System Proxy -> Global
- Run `curl ifconfig.me` in git bash (git for windows)

### What did you expect to see?
remote server IP

### What did you see instead?
real IP

------

Also if I run `curl ifconfig.me` in windows PowerShell it prints remote server IP, but git bash prints real IP. 
Due to this behavior, I cannot trust now this software because it has unpredictable behavior. What am I doing wrong?

**Comment by chenshaoju** [comment]
Try setting the environment variables, refer to: https://github.com/shadowsocks/shadowsocks-windows/issues/2686#issuecomment-556913520

**Comment by atellmer** [comment]
Thanks! That works fine.

Solution:

in your `.bashrc`
```
export http_proxy=http://127.0.0.1:1080
export https_proxy=http://127.0.0.1:1080
```
