### ISSUE TITLE
推荐个靠谱梯子

### ISSUE THREAD

**Issue by aishang5wpj** [shadowsocks/shadowsocks-windows#3501]
目前最靠谱的梯子，直接买永久流量，用完为止，上次买了半年才用了 5%，1T流量用个几年都没什么问题

https://www.starlinkcloud.club/#/register?code=Ap1Vrrq2

![image](https://github.com/user-attachments/assets/0f469a07-8c97-4338-99e7-f2022327c867)

![image](https://github.com/user-attachments/assets/ac0f9aae-55f6-4d51-bc4f-b0d97178c7a9)

**Comment by zslqhua** [comment]
一买就是一年180，有没按月买的。

**Comment by aishang5wpj** [comment]
> 一买就是一年180，有没按月买的。

有按月买，25一个月，不过这个不是一年180，而是1T永久流量180，我7月份买的现在才用了5G多，感觉能用好几年了
