### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sergb163** [shadowsocks/shadowsocks-windows#3502]
![image](https://github.com/user-attachments/assets/68887451-827a-4289-b974-06edf8f6c82f)

### Environment

- Shadowsocks client version:
- OS version:
- .NET version:

### Config and error log in detail (with all sensitive info masked)

```
PASTE LOG HERE
```

**Comment by chenshaoju** [comment]
Этот совет может означать, что файл конфигурации gui-config.json поврежден. Попробуйте удалить файл gui-config.json в каталоге, где находится Shadowsocks.exe, и повторите попытку.

**Comment by Sergb163** [comment]
Спасибо. Помогло.
