### ISSUE TITLE
请问一下 $"\"{country} {city}\"") 这个$是什么意思

### ISSUE THREAD

**Issue by xWuliou** [shadowsocks/shadowsocks-windows#352]
只见过@字符串，没见过$字符串，vs2013编译报错
avaiabilityStatistics.cs文件里面的

**Comment by xWuliou** [comment]
是不是索引属性？怎么网上都搜不到

**Comment by GangZhuo** [comment]
https://msdn.microsoft.com/en-us/library/dn961160.aspx
