### ISSUE TITLE
one-time authentication

### ISSUE THREAD

**Issue by tkisme** [shadowsocks/shadowsocks-windows#356]
这个在安卓版本里面已经有了，希望能解决

**Comment by chenshaoju** [comment]
曾经有一个 shadowsocks-win-2.5.8-beta.zip 具备该功能，但是编译者移除了。

**Comment by tkisme** [comment]
那么怎么解决呢，2.5.9里会解决么

**Comment by GangZhuo** [comment]
master分支中已经支持了，自己编译一下。

**Comment by tkisme** [comment]
能不能出个发行版，这样实在纠结。vs2015实在是大了点

**Comment by icylogic** [comment]
@tkisme 你可以在 https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/6p7q5o918bxhl3js/artifacts 下载最新版，当然，有可能会有问题。

**Comment by andronoob** [comment]
已经从appveyor上下载了，启用one-time-authentication后看起来还正常。
@icylogic 不知道有没有关于这个特性的科普？
很期待正式的release。

**Comment by GangZhuo** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/428

**Comment by librehat** [comment]
https://shadowsocks.org/en/spec/one-time-auth.html

**Comment by myliyifei** [comment]
既然OTA 有特别的标志位，那么发起带OTA的连接，不是又带来了特征？

2015-11-14 21:43 GMT+08:00 Symeon Huang <notifications@github.com>:

**Comment by GangZhuo** [comment]
和原来一样的，重复利用了ATYP。
