### ISSUE TITLE
能否通过托盘图标颜色指示连接是否成功

### ISSUE THREAD

**Issue by kodexor** [shadowsocks/shadowsocks-windows#357]
关于是否连接成功没有一个明确的指示，每次要看log才知道一直处于timeout状态。
虽然有高可用那个选项，但那个似乎是通过尝试连接每一个服务器来决定使用哪一个？
但是有的时候，我的服务器列表中大部分不可用，这样高可用的选项就显得不太实用。

希望开发者考虑一下这个建议。

**Comment by icylogic** [comment]
因为网络情况比较恶劣，有时候可以 Ping 但是仍然不可用，即使是实际可用的连接也可能会出现 exception 或者 timedout，因此现在比较难判断是否真的可用。另外高可用这个策略也因为同样的原因，只能根据实时的几次连接判断，所以实际上不太可靠。

**Comment by kodexor** [comment]
网络状况确实恶劣，即使已建立的连接都有可能被随时中断。
不过还是希望能够粗略估计服务器列表中每个服务器的可用程度。
shadowsocks-qt5中能够通过探测服务器列表中每个服务器的ping值来粗略估计可用度。
“累积丢包率”是用来提供类似功能的吗？

**Comment by icylogic** [comment]
是的，可以参考 https://github.com/shadowsocks/shadowsocks-windows/issues/266
因为我现在考虑到 Ping 也不能反映真实链接质量，所以会加入实际使用时的记录，目前不打算主动测试。

**Comment by kodexor** [comment]
好的，谢谢

**Comment by shizongger** [comment]
ubuntu下如何判断是否连接工程？不是gui版本的，是pathy版本的！
