### ISSUE TITLE
Bug Report JIT Crashing

### ISSUE THREAD

**Issue by ShadyNinja** [shadowsocks/shadowsocks-windows#359]
![ss bug](https://cloud.githubusercontent.com/assets/9124786/10577974/bee26f7c-76a1-11e5-89f4-7cf41770325e.PNG)

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 Shadowsocks.View.ConfigForm.ServersListBox_SelectedIndexChanged(Object sender, EventArgs e)
   在 System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   在 System.Windows.Forms.ListBox.set_SelectedIndex(Int32 value)
   在 Shadowsocks.View.ConfigForm.AddButton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.6.106.0 built by: NETFXREL2STAGE
 基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Shadowsocks
    程序集版本:2.5.8.0
    Win32 版本:2.5.8.0
 基本代码:file:///D:/Program%20Files/Shadowsocks/Shadowsocks.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.6.79.0 built by: NETFXREL2
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.6.79.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.6.93.0 built by: NETFXREL2STAGE
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.6.79.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.6.79.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.6.79.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.79.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.79.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

=================================我是分割线==============================

复现步骤：
1. 删除当前所有服务器节点至左边服务器列表List为空
2. 点击“添加”按钮

备注：虽说不是致命BUG……但这个应该很好测到吧……囧……要是你的源码还开放的话我就帮你改好了……点击添加的时候做一下 SelectedIndex 的判断哟~~

**Comment by icylogic** [comment]
https://github.com/shadowsocks/shadowsocks-windows/pull/345 已经修复了，只是还没发布。

**Comment by everyx** [comment]
master 分支已经修复了，具体请看 #345

**Comment by ShadyNinja** [comment]
哎呀，还真是，好吧，没看到已经提了，还以为是刚刚凑巧发现的……话说一整个月没更新了……好吧，这个Close掉咯~~
