### ISSUE TITLE
pc连不上，但手机却可以连上啊

### ISSUE THREAD

**Issue by zhangchenkai** [shadowsocks/shadowsocks-windows#360]
[2015-10-20 13:14:51] System.Net.Sockets.SocketException (0x80004005): 请求的名称有效，但是找不到请求的类型的数据。
   在 System.Net.Dns.GetAddrInfo(String name)
   在 System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   在 System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   在 Shadowsocks.Controller.Handler.StartConnect()

每次打开页面就是出错  ie显示：已取消网页导航 
但手机端的却稳稳的

**Comment by zhangchenkai** [comment]
墙外的所有网站都是这种反应

**Comment by GangZhuo** [comment]
检查配置文件。或者把服务器换为 IP 地址试试。

**Comment by zhangchenkai** [comment]
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

而且经常出现这个

**Comment by zhangchenkai** [comment]
已解决，为何配置换成ip地址就好了？？

**Comment by falseen** [comment]
把迅雷卸掉试试

**Comment by GangZhuo** [comment]
DNS 解析问题，可以在命令行中使用 "nslookup 你的域名" 试看看。
