### ISSUE TITLE
需要切换一下系统代理模式才能连接

### ISSUE THREAD

**Issue by pengkai** [shadowsocks/shadowsocks-windows#361]
每次开机后，自动启动，连接不上。手动切换一下“系统代理模式”为“全局模式”再切换回“PAC模式”，就可以正常链接了。
---------------------------------
>
[2015-10-23 13:35:44] System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   在 System.Diagnostics.Process.Kill()
   在 Shadowsocks.Controller.PolipoRunner.Start(Configuration configuration)
[2015-10-23 13:35:44] Shadowsocks started

**Comment by chenshaoju** [comment]
尝试使用 portable 模式看看？方法：退出SS，然后在 Shadowsocks.exe 所在目录放一个名为 shadowsocks_portable_mode.txt 的文件，然后在启动SS看看？

**Comment by shikkoku** [comment]
有自动编译打包的网站可以下载吗？
