### ISSUE TITLE
Win10+chrome+switchyomega  SS兼容性问题

### ISSUE THREAD

**Issue by KyonCN** [shadowsocks/shadowsocks-windows#362]
升级win10有一段时间了。SS一直使用正常。前两天打了几个补丁之后SS就连不上了。chrome升级过几次，不过升级之后还是能用。
试了好久发现只有HTTP下可以用，socks5完全用不了。一开始以为VPS崩了，就重启了一下，还是没用。换了win7的笔记本一切正常，chrome版本相同 46.0.2490.80。
还有备用梯子Goagent居然也是同一时间不能用了，但是在win7上一切正常。
win10下开系统代理，两个工具都间歇性失效。
不知道是不是win10的问题。

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/247#issuecomment-131392491

**Comment by KyonCN** [comment]
感谢楼上的兄弟，试了下没用。

**Comment by chenshaoju** [comment]
“不能用”具体是什么表现？

**Comment by KyonCN** [comment]
系统代理模式下有大约百分之三十的几率Internet 500错误。
不开系统代理，只能用http模式，而且不太稳定。

**Comment by GangZhuo** [comment]
Shadowsocks 什么版本？
能否贴出部分日志？

**Comment by KyonCN** [comment]
shadowsocks 2.5.8
win10 10565
chrome 46.0.2490.80

[2015-10-27 09:51:46] Shadowsocks started
[2015-10-27 10:40:00] Shadowsocks started
[2015-10-27 10:41:17] /select, "C:\Users\****\AppData\Local\Temp\shadowsocks.log"
[2015-10-27 10:41:46] Shadowsocks started
[2015-10-27 10:44:31] Shadowsocks started
日志上看一切正常，前两天把shadowsocks的sever端和client端全重装了，之前服务器端的日志都丢失了，抱歉。

**Comment by Cloverr0** [comment]
可能是pac文件的问题，你试试shadowsocksr吧

**Comment by GangZhuo** [comment]
测试 PAC 没有问题， Windows10 + Chrome + SwitchyOmega 中测试也没有问题，先关闭吧，以后再遇到的时重新 Open。

**Comment by ysguoqiang** [comment]
我也有问题。重装完系统（win10），英文版chrome没有问题，卸载安装了中文版chrome就无法使用了。其他电脑上都正常（同一台VPS，chrome和switcheomega的配置都是从google服务器同步的）。在win10系统上，用firefox+autoproxy代理正常，唯独chrome不能用。代理方式换成了http就能上了，但是感觉http没有socks稳定。chrome版本为48.0.2564.116.系统和chrom都是64位。希望这个问题能解决

**Comment by mpc2008cn** [comment]
win10下进`windows防火墙`-`允许的应用`,把找到的`shadowsocks.exe`都打上勾试试.

**Comment by ysguoqiang** [comment]
确认是迅雷的问题，卸载迅雷就好了

2016-02-24 17:50 GMT+08:00 Felix <notifications@github.com>:

**Comment by ljl024** [comment]
先运行ss，再安装迅雷就没事了
