### ISSUE TITLE
开启日志报错

### ISSUE THREAD

**Issue by Tk-archer** [shadowsocks/shadowsocks-windows#366]
版本2.5.8
打开日志是会报错
![image](https://cloud.githubusercontent.com/assets/5762459/10901966/59d725fe-8232-11e5-8414-8ca5fe2de068.png)

**Comment by chenshaoju** [comment]
Portable模式没有测试出该问题。

这是Windows 8还是Windows 10？

**Comment by Tk-archer** [comment]
win10
然而我重新下载覆盖2.5.8又可以了orz

**Comment by GangZhuo** [comment]
编译时需选择为Release。

Fsz <notifications@github.com>于2015年11月3日周二 下午2:07写道：

**Comment by Tk-archer** [comment]
嗯。。。我逗比了
谢指导
我关掉他了
