### ISSUE TITLE
win10电脑用2.5.8版的Shadowsocks，只能用全局模式，pac模式连不上

### ISSUE THREAD

**Issue by FQFQzzy** [shadowsocks/shadowsocks-windows#367]
前几周本地pac还能用（也是win10）

**Comment by ertcds** [comment]
你不勾选  启用系统代理。 Microsoft Edge能上网吗？
我的不勾选不能，勾选才可以。 chrome不影响。

**Comment by nmgwddj** [comment]
我也是一样的问题,使用pac模式连部山个,必须要切换成全局模式.

**Comment by FQFQzzy** [comment]
@ertcds edge没试过 启用系统代理是一定要勾选的吧？

**Comment by everyx** [comment]
我以前碰到这个问题是因为 PAC 生成的是使用严格模式的，如果使用 gfwlist2pac 中的简单模式就能使用了，你可以尝试一下我便宜的 shadowsocks 版本，提供了 pac 生成模式的切换（点击我的资料查看），不过最近发现一个问题，使用一段时间后，程序会 crash，我抽空在解决，谢谢，希望对你有帮助

**Comment by ertcds** [comment]
@FQFQzzy 不勾选启用系统代理 会在8123端口有http代理。方便配合Proxy SwitchyOmega使用，主要是添加网址方便。但是我win10不勾选，会造IE不能上网，所以默认使用IE代理的软件也不能上网了。好郁闷

**Comment by FQFQzzy** [comment]
@everyx 好的谢谢！

**Comment by FQFQzzy** [comment]
@ertcds 不太会用Omega插件，不过我这两天有时候pac模式又能恢复使用

**Comment by ertcds** [comment]
@FQFQzzy 嗯，不知道什么问题。前一段时间没事，突然出现

**Comment by GangZhuo** [comment]
尝试最新 Master 分支的代码。

**Comment by FQFQzzy** [comment]
@GangZhuo 怎么操作？

**Comment by GangZhuo** [comment]
到 https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/history 下载自动编译的可执行文件或者自己编译。

**Comment by FQFQzzy** [comment]
@GangZhuo 太麻烦了，算了

**Comment by FQFQzzy** [comment]
@GangZhuo 问题还没解决呢怎么就关了？我不懂技术所以没有明白要去链接里下载哪个。没有别的解决方法么

**Comment by GangZhuo** [comment]
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.54/job/is02oalq52ogc976/artifacts

**Comment by FQFQzzy** [comment]
@GangZhuo 我下了那个EXE 这是改进版么？

**Comment by GangZhuo** [comment]
是基于最新master编译的，其中有修复了一个能导致http代理不可用的错误。

**Comment by FQFQzzy** [comment]
@GangZhuo 谢谢。目前正在用您编译的SS，感觉比原版好用。原版每次都要手动把电脑代理设置改成127.0.0.1和1080才行。

**Comment by GangZhuo** [comment]
这个本来就是原版，只不过未发布而已，你下载的是自动编译的，不是我编译的。

**Comment by gaojice** [comment]
如果是使用本地pac有可能是本地pac.txt被编辑后格式不正确导致,注意冒号,逗号等

**Comment by kimw** [comment]
It's maybe caused by pac engine. Some new pac engine, eg firefox x64, didn't understand the pac file.

**Comment by FQFQzzy** [comment]
@gaojice @kimw 谢谢回复。我现在不用原版了，再用shadowsocksR，感觉这个好些
