### ISSUE TITLE
maximum number of open connections reached

### ISSUE THREAD

**Issue by sukui** [shadowsocks/shadowsocks-windows#370]
连接数多的时候容易爆这个错误！
maximum number of open connections reached
不知道是C#的并发限制还是浏览器的限制？

**Comment by GangZhuo** [comment]
操作系统本身的限制，可以搜索一下 "MaxUserPort".

**Comment by monkeyyeyy** [comment]
今天也遇到了这个问题，调整服务器那边还是客户端呢？
