### ISSUE TITLE
使用 pac 模式会导致 Battle.net Launcher 无法更新，且 WinHttpAutoProxySvc 服务 CPU 占用很高

### ISSUE THREAD

**Issue by imebeh** [shadowsocks/shadowsocks-windows#371]
Pac 为默认的从 gfwlist 更新的
ss版本：2.5.8.0
Battle.net 是国服
WinHttpAutoProxySvc 服务全名 WinHTTP Web Proxy Auto-Discovery Service
Win7 64位

使用全局代理或者关掉代理都正常

**Comment by chenshaoju** [comment]
我也是Windows 7 64位，但是没有这个问题。
我的PAC是自己写的。

将showsocks目录下的 pac.txt 备份，然后清空，并粘贴该内容试试：
https://gist.github.com/chenshaoju/52c7555acc65ec98423f
PS：记得修改端口号。

这只保证基本的能访问Google，观察一下是否会影响到战网。

**Comment by imebeh** [comment]
@chenshaoju 谢谢，周末我测试一下具体是哪里的问题。

**Comment by reaCodes** [comment]
@chenshaoju 你写的这个PAC访问Google会比GFWlist更快吗？

**Comment by chenshaoju** [comment]
@reaCodes 我习惯自己写，这个是为Google Drive编写的。

**Comment by imebeh** [comment]
测试了一下，发现战网下载不了可能是我的网络问题，下载进度也不是实时更新的
WinHttpAutoProxySvc 服务 CPU 占用升高暂时没找到原因，等下次出更新的时候才能测试

战网的 pac 请求次数比较多，而且请求头很简单，只有 Host 和 Accept
` Host: 127.0.0.1:8080
 Accept: */*`

ps: 是不是可以关了这个 issue 了

**Comment by imxieke** [comment]
WIN32位  未遇到该情况！

**Comment by imxieke** [comment]
@chenshaoju 你好 'google.com',这个算是 google.com下所以域名还是仅仅google.com一个？亦或者等于*.google.com?    非常希望您的解答！谢谢

**Comment by chenshaoju** [comment]
@imxieke 是所有以 .google.com 结尾的域名。

**Comment by imxieke** [comment]
@chenshaoju 好的  谢谢哈
