### ISSUE TITLE
server ip 那个输入框没有进行trim操作

### ISSUE THREAD

**Issue by gonejack** [shadowsocks/shadowsocks-windows#374]
导致网页上复制来的地址可能因首位带有空格而连接失败

**Comment by GangZhuo** [comment]
可以提交一个PR吗？

**Comment by GangZhuo** [comment]
fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/1097d4fc5baf6f3deaf6725a98f03d7e059028fe
