### ISSUE TITLE
现在的master分支上ServerIP的一个疑问

### ISSUE THREAD

**Issue by SuperHentai** [shadowsocks/shadowsocks-windows#375]
我想着手做一个小的功能性修改，所以拉取了master上的代码，直接测试之后发现，当IP为IPv6地址时，会引发“System.InvalidOperationException”异常，而2.5.8的release则不会。
我想问一下原因，是一个bug呢，还是我在某些地方处理不好，疏忽了什么。
![qq 20151115173311](https://cloud.githubusercontent.com/assets/5331336/11168158/f197d88a-8bbe-11e5-88c9-715a42dd179a.jpg)

**Comment by GangZhuo** [comment]
未测试，粗略估计是ipv6执行ping的问题，https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Model/StatisticsStrategyConfiguration.cs#L17 修改为false或关闭High Availability后试试。
