### ISSUE TITLE
Win10 TH2 下 SS 连接反复出现超时与错误

### ISSUE THREAD

**Issue by LenKiMo** [shadowsocks/shadowsocks-windows#379]
Windows10 TH2 (10.0.10586.0) Pro 64-Bit & Chrome 48.0.2560.0 dev-m (64-bit) & Shdowsocks-Libev 2.4.1 & ShdowSocks 2.5.8 & SwitchyOmega 2.3.16

全局模式。
从服务端采用 lsof -i 命令查看，电脑端与服务端通过 IPV6 连接已经建立并且处于 ESTABLISHED 状态。
手机端 SS 可以正常使用，所以暂时判断不是服务端的问题，因此发来这里寻求帮助。

本地 Ping 服务端 IPV6 地址可以正常响应。
在 IPV6 通道下，本地与服务端的连接近乎停滞。查看日志，基本上是如下内容的循环：

    [2015-11-17 12:50:12] [server]:[port] timed out
    [2015-11-17 12:50:12] [server]:[port] timed out
    [2015-11-17 12:50:12] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
       在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
       在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
       在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
       在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
       在 Shadowsocks.Controller.Handler.StartConnect()
    [2015-11-17 12:50:12] [server]:[port] timed out
    [2015-11-17 12:50:12] [server]:[port] timed out
    [2015-11-17 12:50:12] [server]:[port] timed out
    [2015-11-17 12:50:12] [server]:[port] timed out

切换到 IPV4 线路连接后，虽然顺畅了许多，但是依旧存在大量 Time Out 与无效参数，部分日志如下：

    [2015-11-17 15:19:59] Shadowsocks started
    [2015-11-17 15:23:24] [server]:[port] timed out
    [2015-11-17 15:23:24] [server]:[port] timed out
    [2015-11-17 15:23:24] [server]:[port] timed out
    [2015-11-17 15:23:27] [server]:[port] timed out
    [2015-11-17 15:23:27] [server]:[port] timed out
    [2015-11-17 15:23:27] [server]:[port] timed out
    [2015-11-17 15:23:27] [server]:[port] timed out
    [2015-11-17 15:23:27] [server]:[port] timed out
    [2015-11-17 15:23:30] [server]:[port] timed out
    [2015-11-17 15:23:30] [server]:[port] timed out
    [2015-11-17 15:23:30] [server]:[port] timed out
    [2015-11-17 15:23:30] [server]:[port] timed out
    [2015-11-17 15:23:30] [server]:[port] timed out
    [2015-11-17 15:23:30] [server]:[port] timed out
    [2015-11-17 15:23:30] [server]:[port] timed out
    [2015-11-17 15:23:30] [server]:[port] timed out
    [2015-11-17 15:23:33] [server]:[port] timed out
    [2015-11-17 15:23:36] [server]:[port] timed out
    [2015-11-17 15:23:36] [server]:[port] timed out
    [2015-11-17 15:23:36] [server]:[port] timed out
    [2015-11-17 15:23:38] [server]:[port] timed out
    [2015-11-17 15:23:39] [server]:[port] timed out
    [2015-11-17 15:23:39] [server]:[port] timed out
    [2015-11-17 15:23:39] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
       在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
       在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
       在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
       在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
       在 Shadowsocks.Controller.Handler.StartConnect()
    [2015-11-17 15:23:39] [server]:[port] timed out
    [2015-11-17 15:23:39] [server]:[port] timed out
    [2015-11-17 15:23:39] [server]:[port] timed out
    [2015-11-17 15:23:41] [server]:[port] timed out
    [2015-11-17 15:23:41] [server]:[port] timed out
    [2015-11-17 15:23:41] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
       在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
       在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
       在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
       在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
       在 Shadowsocks.Controller.Handler.StartConnect()
    [2015-11-17 15:23:41] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
       在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
       在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
       在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
       在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
       在 Shadowsocks.Controller.Handler.StartConnect()
    [2015-11-17 15:23:42] [server]:[port] timed out
    [2015-11-17 15:23:42] [server]:[port] timed out
    [2015-11-17 15:23:42] [server]:[port] timed out
    [2015-11-17 15:23:42] [server]:[port] timed out

此前，已卸载迅雷，尝试过 https://github.com/shadowsocks/shadowsocks-windows/issues/247#issuecomment-131392491 提出的方法并进行重启，尝试过修改 SwitchyOmega 的 SOCKS5 为 HTTP ，但是并没有什么效果。
在升级至 TH2 之前已经偶发此类情况，但不至于不能用。昨晚刚升级完毕时虽然刚开始有较明显的卡顿现象但稍后也已恢复，今天则完全陷入无法使用的状态。虽然网页标题或部分元素能够读取但是速度十分之慢。
由于我正在使用的是校内网络，无法排除校园网的干扰因素。
时而 Time Out 次数会减少从而也能够达到可以使用的级别，但是频繁如此下去似乎也不是个事。所以姑且将其视作一个 Bug 提交至此请求诸位帮助与解答。

另附服务端（通过 IPV6 与服务端后台 SSH 直连是顺畅的）通过  TCPDUMP 抓取的部分针对 SS 工作端口的数据：
    16:40:26.936973 IP6 *[localIP]*.57992 > *[ServerIPandPort]*: Flags [.], ack 4202, win 256, length 0
    16:40:27.306370 IP6 *[localIP]*.58042 > *[ServerIPandPort]*: Flags [.], ack 84769, win 258, length 0
    16:40:27.306411 IP6 *[ServerIPandPort]* > *[localIP]*.58042: Flags [.], seq 96289:99169, ack 811, win 238, length 2880
    16:40:27.457684 IP6 *[localIP]*.58042 > *[ServerIPandPort]*: Flags [.], ack 86209, win 258, length 0
    16:40:27.713332 IP6 *[localIP]*.58042 > *[ServerIPandPort]*: Flags [.], ack 87649, win 258, length 0
    16:40:27.713363 IP6 *[ServerIPandPort]* > *[localIP]*.58042: Flags [.], seq 99169:103489, ack 811, win 238, length 4320
    16:40:27.899876 IP6 *[localIP]*.58056 > *[ServerIPandPort]*: Flags [.], ack 1, win 258, length 0
    16:40:27.906857 IP6 *[localIP]*.58056 > *[ServerIPandPort]*: Flags [P.], seq 1:477, ack 1, win 258, length 476
    16:40:27.906873 IP6 *[ServerIPandPort]* > *[localIP]*.58056: Flags [.], ack 477, win 234, length 0
    16:40:27.912929 IP6 *[localIP]*.58057 > *[ServerIPandPort]*: Flags [.], ack 1, win 258, length 0
    16:40:27.913961 IP6 *[localIP]*.58057 > *[ServerIPandPort]*: Flags [P.], seq 1:741, ack 1, win 258, length 740
    16:40:27.913977 IP6 *[ServerIPandPort]* > *[localIP]*.58057: Flags [.], ack 741, win 237, length 0
    16:40:27.913991 IP6 *[localIP]*.58059 > *[ServerIPandPort]*: Flags [.], ack 1, win 258, length 0
    16:40:27.914757 IP6 *[localIP]*.58059 > *[ServerIPandPort]*: Flags [P.], seq 1:749, ack 1, win 258, length 748
    16:40:27.914766 IP6 *[ServerIPandPort]* > *[localIP]*.58059: Flags [.], ack 749, win 237, length 0
    16:40:27.926147 IP6 *[localIP]*.58060 > *[ServerIPandPort]*: Flags [.], ack 1, win 258, length 0
    16:40:27.927020 IP6 *[localIP]*.58060 > *[ServerIPandPort]*: Flags [P.], seq 1:759, ack 1, win 258, length 758
    16:40:27.927032 IP6 *[ServerIPandPort]* > *[localIP]*.58060: Flags [.], ack 759, win 237, length 0
    16:40:27.927155 IP6 *[localIP]*.58061 > *[ServerIPandPort]*: Flags [.], ack 1, win 258, length 0
    16:40:27.927659 IP6 *[localIP]*.58061 > *[ServerIPandPort]*: Flags [P.], seq 1:33, ack 1, win 258, length 32
    16:40:27.927667 IP6 *[ServerIPandPort]* > *[localIP]*.58061: Flags [.], ack 33, win 225, length 0
    16:40:28.008570 IP6 *[localIP]*.58064 > *[ServerIPandPort]*: Flags [.], ack 1, win 258, length 0
    16:40:28.011160 IP6 *[localIP]*.58064 > *[ServerIPandPort]*: Flags [P.], seq 1:746, ack 1, win 258, length 745
    16:40:28.011176 IP6 *[ServerIPandPort]* > *[localIP]*.58064: Flags [.], ack 746, win 237, length 0
    16:40:28.022043 IP6 *[localIP]*.58065 > *[ServerIPandPort]*: Flags [.], ack 1, win 258, length 0
    16:40:28.023045 IP6 *[localIP]*.58065 > *[ServerIPandPort]*: Flags [P.], seq 1:773, ack 1, win 258, length 772
    16:40:28.023055 IP6 *[ServerIPandPort]* > *[localIP]*.58065: Flags [.], ack 773, win 238, length 0
    16:40:28.046027 IP6 *[localIP]*.58061 > *[ServerIPandPort]*: Flags [P.], seq 33:444, ack 1, win 258, length 411
    16:40:28.046047 IP6 *[ServerIPandPort]* > *[localIP]*.58061: Flags [.], ack 444, win 234, length 0
    16:40:28.825833 IP6 *[ServerIPandPort]* > *[localIP]*.58056: Flags [P.], seq 1:2065, ack 477, win 234, length 2064
    16:40:28.825851 IP6 *[ServerIPandPort]* > *[localIP]*.58056: Flags [P.], seq 2065:4113, ack 477, win 234, length 2048
    16:40:28.825862 IP6 *[ServerIPandPort]* > *[localIP]*.58056: Flags [P.], seq 4113:5809, ack 477, win 234, length 1696
    16:40:28.826756 IP6 *[ServerIPandPort]* > *[localIP]*.58065: Flags [P.], seq 1:2065, ack 773, win 238, length 2064
    16:40:28.826765 IP6 *[ServerIPandPort]* > *[localIP]*.58065: Flags [P.], seq 2065:2132, ack 773, win 238, length 67
    16:40:28.962051 IP6 *[ServerIPandPort]* > *[localIP]*.58059: Flags [P.], seq 1:961, ack 749, win 237, length 960
    16:40:28.962386 IP6 *[ServerIPandPort]* > *[localIP]*.58059: Flags [P.], seq 961:3009, ack 749, win 237, length 2048
    16:40:28.962404 IP6 *[ServerIPandPort]* > *[localIP]*.58059: Flags [P.], seq 3009:5057, ack 749, win 237, length 2048
    16:40:28.962411 IP6 *[ServerIPandPort]* > *[localIP]*.58059: Flags [P.], seq 5057:5844, ack 749, win 237, length 787
    16:40:29.021151 IP6 *[ServerIPandPort]* > *[localIP]*.58056: Flags [P.], seq 5809:7857, ack 477, win 234, length 2048
    16:40:29.021182 IP6 *[ServerIPandPort]* > *[localIP]*.58056: Flags [P.], seq 7857:9905, ack 477, win 234, length 2048
    16:40:29.242753 IP6 *[ServerIPandPort]* > *[localIP]*.58060: Flags [P.], seq 1:1488, ack 759, win 237, length 1487
    16:40:29.242935 IP6 *[ServerIPandPort]* > *[localIP]*.58060: Flags [P.], seq 1488:3536, ack 759, win 237, length 2048
    16:40:29.242950 IP6 *[ServerIPandPort]* > *[localIP]*.58060: Flags [P.], seq 3536:4384, ack 759, win 237, length 848

**Comment by LenKiMo** [comment]
2015年11月19日确认是校园网环境的问题。

**Comment by chenshaoju** [comment]
你可以关闭这个Issue，如果确认该问题并非Shadowsocks引起。

**Comment by LenKiMo** [comment]
closes #379

**Comment by LenKiMo** [comment]
fix #379

**Comment by Skefei** [comment]
可是我不是校园网，我新安装windows，神毛软件也没有安装，只有一个firefox和shadowsocks，和这个楼主的问题是一样的， 提供了一个无效的参数，而且总是timed out，国内网站能上github能上 但是谷歌，facebook都不行

**Comment by SCLeoX** [comment]
问题一模一样，不是校内网问题

**Comment by chenshaoju** [comment]
@SCLeoX 请尝试： https://github.com/shadowsocks/shadowsocks-windows/issues/591
