### ISSUE TITLE
Win7 32位下  设置为开机自启，在重启后，改变系统代理模式为无效

### ISSUE THREAD

**Issue by imxieke** [shadowsocks/shadowsocks-windows#380]
问题如下：
                Win7 32位下  设置为开机自启，在重启后，改变系统代理模式为无效（重启前位全局模式），
将程序关闭后再次打开该问题便消失了。

不知这个问题算不算Bug，但不影响使用，仅提交该问题！

**Comment by GangZhuo** [comment]
能否贴出日志？

**Comment by imxieke** [comment]
@GangZhuo   抱歉  我刚刚看了下日志只有19日下午的  其他的没了

**Comment by GangZhuo** [comment]
此问题不再出现了？如果还出现的话，就贴一下最近的。

**Comment by imxieke** [comment]
@GangZhuo 好的  这个不是啥大问题  不会影响使用！

**Comment by GangZhuo** [comment]
测试了几次没有发现这个问题。

**Comment by imxieke** [comment]
@GangZhuo 哦  那可能是我这环境问题

**Comment by GangZhuo** [comment]
这个配置是存在配置文件中的，除非配置文件被改了，才会出现这个情况。

**Comment by imxieke** [comment]
@GangZhuo  哦哦
