### ISSUE TITLE
FIPS启用时存在兼容问题

### ISSUE THREAD

**Issue by riverai** [shadowsocks/shadowsocks-windows#381]
最近至少部分Win10因为突然自动（或说未知）启用的FIPS模式不能正常使用shadowsocks客户端 。

日志会提示 ”此实现不是 Windows 平台 FIPS 验证的加密算法的一部分“ 。

我也有遇到，然后关闭了FIPS的启用，之后正常，同时受影响的还有3DMark。

https://github.com/shadowsocks/shadowsocks/issues/466#issuecomment-158274560

更改注册表（或组策略参数）来启用和关闭FIPS，之后再重启shadowsocks客户端，可以马上复现和消除问题。

连接的服务器使用的RC4-MD5方式。
日志的具体错误模板:

  --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.Handler.CreateRemote()
   在 Shadowsocks.Controller.Handler.StartConnect()
[2015-11-20 22:34:21] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()

**Comment by GangZhuo** [comment]
fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/dd0d0474023d652edb4d03e5c3bf04e7cebcdca4
