### ISSUE TITLE
请问现在有没有支持mono的计划？

### ISSUE THREAD

**Issue by huhu2207** [shadowsocks/shadowsocks-windows#382]
各位大神好，

小弟是个OSX+Windows用户，ss-osx平台目前停止维护了，替代品只有ss-libev，但敲命令行挺麻烦的。
之前我在OSX下面搞了一次试试，改了改能编译，但一开就崩溃，因为polipo起不来，而且GC的那个函数不兼容OSX（Windows的专属API吧）。打算圣诞节放假再试试。

现在主要问题大概有：

1. polipo。 应该可以再编译打包一个unix/linux下面的polipo可执行文件；
2. P/Invoke那些库，mono给出这个方案：http://www.mono-project.com/docs/advanced/pinvoke；
3. 据说mono自带的AES库性能稀烂，所以得调用第三方库解决（MbedTLS就行吧？）

希望能再给点建议，谢谢了！

**Comment by soyet** [comment]
ss-libev可以作为service开机自动运行

**Comment by septs** [comment]
由于dotNet不支持AES CFB模式导致使用了native实现因此平台锁定windows
如果理解有误请指出

**Comment by huhu2207** [comment]
@soyet OSX好像不行吧？

@septs 不是吧？mono和.NET都支持啊，
见：https://msdn.microsoft.com/en-us/library/system.security.cryptography.rijndael(v=vs.110).aspx

**Comment by soyet** [comment]
@huhu2207 那就写一个脚本让它开机自动启动

**Comment by huhu2207** [comment]
@soyet 那就没意思了。我折腾这个不是为了开机启动，而是为了更方便的图形界面和稳定性，而且能保持有上游大神负责维护。

**Comment by soyet** [comment]
@huhu2207 那你也可以看一下shadowsocks-qt5能不能在osx下编译，它那些依赖包不知道有没有osx版。mono实现这个感觉会有点麻烦

**Comment by GangZhuo** [comment]
无此计划，使用https://github.com/shadowsocks/shadowsocks-qt5
