### ISSUE TITLE
如何添加 URL 到 shadowsocks 的列表，让其使用代理访问？

### ISSUE THREAD

**Issue by nmgwddj** [shadowsocks/shadowsocks-windows#383]
如题，我有一些自己整理的网址，这些网址国内基本无法访问，我改如何把这些网址添加到 shadowsocks 维护列表让其使用代理去访问那些网址？谢谢！

**Comment by XhstormR** [comment]
Chrome 请使用 ProxySwitchyOmega 扩展

**Comment by soyet** [comment]
PAC模式有个user-rule.txt(用户规则)。其他模式请使用浏览器插件实现此功能

**Comment by nmgwddj** [comment]
@soyet `user-rule.txt`编辑的格式是什么样的？有案例吗？

**Comment by mpc2008cn** [comment]
直接编辑pac.txt就可以啊,按照现有的格式添加就可以了

**Comment by nmgwddj** [comment]
@mpc2008cn 我使用的时mac os x，我的规则文件 `user-rule.txt` 目前是空的，如果自定义添加，网址前要添加 http:// 吗？要完整的二级域名还是一级域名？规则是什么样的？这些都没具体的说明。希望能提供一个 example。谢谢！

<img width="567" alt="2015-11-25 10 24 56" src="https://cloud.githubusercontent.com/assets/13995319/11386819/101eb334-9360-11e5-9ff1-79452a3e30bd.png">

**Comment by soyet** [comment]
@nmgwddj 参见[https://adblockplus.org/zh_CN/filters](https://adblockplus.org/zh_CN/filters)

**Comment by nmgwddj** [comment]
@soyet 写在 user-rule.txt 里面吗？

**Comment by soyet** [comment]
@nmgwddj 是的

**Comment by nmgwddj** [comment]
感谢，我需要自己尝试。
