### ISSUE TITLE
提供了一个无效的参数。

### ISSUE THREAD

**Issue by zuosc** [shadowsocks/shadowsocks-windows#384]
初步认定是华为的VPN工具的锅

手贱安装了一下华为的VPN工具，然后卸载提示重启。  重启之后就不能用了。

日志信息：
System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()
然后下面是一堆TimeOut

在浏览器中显示是这样的

500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

然后再CMD中运行了   netsh winsock reset  

重启之后还是不行，求帮助如何解决

**Comment by zuosc** [comment]
好吧  问题解决了。  应该是卸载华为VPN客户端的时候   重置网络了。  但是我电脑里又装着迅雷。重置之后被迅雷坑了。    卸载迅雷之后就好了！

也是坑

**Comment by yeszao** [comment]
我的情况是 服务器和我的电脑可以正常ping通，但是就是不能用，一直超时。。。。
经过研究才知道，当初开启在 showdowsocks.json 里面加了端口后，服务器防火墙并没有开放这个端口，所以打死都连不上，关了之后马上连上了

**Comment by Frank2020** [comment]
你好我这边和你的情况是一样的， 但是我的端口都是开放的，在客户端这边检测到端口OK的，可以telnet连，但是就是连不到服务器怎么破？
