### ISSUE TITLE
Mac 下全局模式无法访问本地 localhost 内容

### ISSUE THREAD

**Issue by nmgwddj** [shadowsocks/shadowsocks-windows#385]
使用自动代理模式可以访问本地的 http://localhost 建立的网站，而使用全局模式就无法显示网页了，请问该如何处理这种情况？

**Comment by soyet** [comment]
localhost不能使用代理访问

**Comment by GangZhuo** [comment]
要在代理工具中设置绕过本地地址。

**Comment by nmgwddj** [comment]
@GangZhuo 请问要如何设定？

**Comment by GangZhuo** [comment]
不同的工具方法应该是不同的，最好自己搜索一下。参考
* https://support.apple.com/en-us/HT202232
* https://support.sightcall.com/hc/en-us/articles/201994738-My-browser-connects-to-the-internet-through-a-proxy-What-do-I-need-to-know-

**Comment by nmgwddj** [comment]
@GangZhuo Thank you！

**Comment by xiguaaxigua** [comment]
![wechatimg14](https://cloud.githubusercontent.com/assets/17041370/24179239/ebfbda44-0ee8-11e7-936c-b27683bfc738.jpeg)

**Comment by celeron533** [comment]
@xiguaaxigua 截图上看起来像是中文顿号

**Comment by bambooom** [comment]
@xiguaaxigua 亲测设置有效~
但是 过段时间再打开, `忽略这些主机与域的代理设置` 中填的值被清空了....
求问是否了解这是怎么回事? 有什么办法吗?

**Comment by GogoKM** [comment]
![image](https://user-images.githubusercontent.com/14171260/34187499-a4cfae7e-e56c-11e7-9884-512dccae1363.png)

**Comment by icedream2linxi** [comment]
@GangZhuo 请教！有什么办法通过本地代理客户端程序访问 localhost 的？
