### ISSUE TITLE
Win 10 Edge浏览器加载不出被墙网页的icon图标

### ISSUE THREAD

**Issue by reaCodes** [shadowsocks/shadowsocks-windows#386]
我用IE所有被墙的网页icon图标都能加载出来，用VPN的时候Edge也没问题，唯独用shadowsocks的时候Edge就不行了。小问题不影响，但是很好奇是什么原因。

**Comment by mpc2008cn** [comment]
你把shadowsocks改成全局也会看到的,估计你用的是pac模式.加载不了是没把这个图片的url添加到pac.txt里吧.

**Comment by reaCodes** [comment]
@mpc2008cn 改为全局代理还是不行，而且pac模式ie是可以加载出icon的，一度怀疑这是Edge的一个bug，可是为什么用VPN连接Edge就能加载出这些图片呢，前后矛盾所以很好奇

**Comment by everyx** [comment]
@reaCodes 你直接通过URL访问icon看能不能显示，另外最好把不能显示icon的网站地址给出来

**Comment by reaCodes** [comment]
@everyx 比如google.com、twitter.com、wikipedia.org

**Comment by everyx** [comment]
@reaCodes我猜测是由于 Edge 对 PAC 解析执行存在 bug，你可以手写一个最简单的 pac 测试看看是不是这个问题

**Comment by reaCodes** [comment]
@everyx 我不太会这个东西，你能帮我一下吗

**Comment by everyx** [comment]
@reaCodes 今天外出，不可以Google一下，或者在 GitHub 上搜 pac，找一个pac替换shadowsocks生成的试试试

**Comment by GangZhuo** [comment]
应该是edge的问题，使用IE打开就能显示图标了

**Comment by reaCodes** [comment]
@GangZhuo 我也就的是这样，等更新吧

**Comment by icylogic** [comment]
global 模式下，直接访问 {domain}/favicon.ico 都是可以的，stackoverflow, github, baidu 等本来没有被墙的网站可以显示图标。猜测 Edge 在获取 favicon.ico 时没有使用代理 （VPN 和 ss 不同，一般全局 route 时，几乎所有流量都会走 VPN）
