### ISSUE TITLE
局域网共享功能的bug

### ISSUE THREAD

**Issue by seanlvjie** [shadowsocks/shadowsocks-windows#387]
我这边的环境必须使用HTTP才能上Internet，目前已经搞定本机（本地PC-01）通过SS+HTTP代理翻墙。
现在开启了PC-01的SS的局域网共享功能，希望实现局域网内其他计算机（PC-02)，通过PC-01的SS实现翻墙。 
测试中发现以下问题
1，如果开启PAC模式，PC-02以 http://SS_IP:1080/pac的方式配置代理，PC-02可以上墙外的网站，但国内的无法访问。 =>  原因： 由于PAC文件定义，国内的走直连，而PC-02本身上网需要配置本地HTTP代理才可以。
2，于是，将PC-01上的pac文件，复制出一份，并改名为 HPpac，修改 var direct参数为本地http代理的参数，IP:8080。 但是，在PC-02上修改代理参数为 http://SS_IP:1080/HPpac，仍未解决问题。 并在PC-02上直接访问，http://SS_IP:1080/HPpac， 发现下载下来的HPpac文件，并非修改过的，而是与PC-01上的pac文件内容一致。 猜测，当PC-02访问 http://SS_IP:1080/HPpac时，下载的文件是被重定向的。 请问如何解决此问题，另外，发现PC-01上的pac文件中是 var proxy = "__PROXY__";  ， 而PC-02下载后的pac文件，其中var proxy = "__PROXY__";部分被替换为PC-01运行SS的具体信息，所以可知__PROXY__是一个变量，但不清楚这个变量是如何被转换的。

使用的SS为 2.5.8版本。

谢谢

**Comment by GangZhuo** [comment]
SS 没有提供网页服务的功能，当检查到下载 PAC 请求的时候，读取 pac.txt 文件，并替换其中的变量后返回。参考 https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/PACServer.cs#L127 。而且，即使你的 HPpac 能够工作，也会是所有的流量都走国外绕一圈。

**Comment by seanlvjie** [comment]
我现在的临时方案是，把修改后的pac文件，即HPpac文件，放到PC-02的本地，然后在浏览器中，设置代理为 file:///C:/Documents%20and%20Settings/Administrator/Desktop/HPpac。  可以正常工作，而且国内流量确实没有走SS，而是走HPPac我修改的代理，即LAN中的HTTP代理。
想问下，SS的配置文件中，可否指定为来自LAN的其他客户端请求不同的pac文件吗？ 如果目前不行，可否考虑增加这个功能。

对于PROXY变量的返回，看代码已经明白，非常感谢。

另外，请教一下，在PC-01上我看到浏览器中的代理，被自动设置为 http://127.0.0.1:1080/pac?t=20151130073653xxxx , 想问下?t= 这些参数有什么具体用途吗？

谢谢~~

**Comment by GangZhuo** [comment]
目前，不支持多pac文件。t 参数的目的是防止浏览器缓存pac。

**Comment by seanlvjie** [comment]
考虑加一下这个功能吧，谢谢喽大神

**Comment by everyx** [comment]
@seanlvjie 这种需求建议你找一个简单的 HTTP 服务器来 host 各个 pac 来解决

**Comment by seanlvjie** [comment]
@everyx 解决方法目前倒不是难点了，file:/// 的方式既然都ok，那么把他放在一个http服务上自然也是ok的。 只是觉得既然SS提供了局域网共享的功能，却没有考虑针对LAN中访问外网必需HTTP代理的环境，所以希望能加入这个功能吧。 

个人感觉，针对此种场景，并不需要多个PAC，因为保持多个PAC与GFWList同步还需要更多代码吧。本人对coding不太了解，呵呵，只是随便乱说。  刚才 @GangZhuo 提供的代码可知，SS在处理局域网请求pac时，可以对本地pac.txt进行处理，那么个人觉得，可以考虑对ShareOverLAN这个功能，增加一个附加选项，即可以替换pac.txt中 var direct 的值为LAN中的代理信息即可，相应的在GUI下也增加一下。

**Comment by everyx** [comment]
@seanlvjie 这个功能有时间我实现一下吧，的确是有这个需求，届时可以关注我的 fork

**Comment by seanlvjie** [comment]
@everyx 谢谢神。 

另外，今天发现一个与之相关的问题，在coding时可能需要考虑。 仅仅将var direct的值改为环境的PROXY信息，可能会带来另外一个问题是，访问LAN中不需要代理的内部HTTP/S服务时（也就是 应该设置在IE代理设置的排除里的那些内容）应该使用direct直连，否则通过代理可能无法连接。  所以，PAC文件应该又多了一些判断，具体还不知道怎么改。

**Comment by icylogic** [comment]
对于你的原始问题 (内网代理), 可以参考 https://github.com/icylogic/Flora_Pac 生成 pac
proxy 填国外, iproxy 填内网代理.
然后 ss 选择 online pac
