### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。

### ISSUE THREAD

**Issue by ngrict** [shadowsocks/shadowsocks-windows#388]
PC端日志显示
 System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()
访问被墙网站显示
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
但是在手机上使用并没有影响…
求助这个该怎么解决。

**Comment by ngrict** [comment]
忘了说了，系统是win10 64位，浏览器是edge /IE11. shadowsocks客户端试用了2.5.6/2.5.8，都出现一样的情况。

**Comment by chenshaoju** [comment]
你是不是装了迅雷？

如果是，看这里： https://github.com/shadowsocks/shadowsocks-windows/issues/334#issuecomment-143189456

**Comment by ngrict** [comment]
是安装了迅雷，不过已经卸载，而且按照https://github.com/shadowsocks/shadowsocks-windows/issues/247#issuecomment-131392491 的方法做了一遍，还是无法解决。

**Comment by wenliyang** [comment]
本地端口换个试下，不用默认的1080

**Comment by ngrict** [comment]
服务商确认域名被污染，已经更换域名。

**Comment by pickView** [comment]
我和你出现同样的问题，但是手机和mac都能翻，就是win10出现问题，怎么解决的

**Comment by pickView** [comment]
[2016-06-10 23:52:53] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
求助

**Comment by chenshaoju** [comment]
@pickView 请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/524

**Comment by wupengfei1236** [comment]
问下，如果域名被污染了，手机端不受影响吗？
