### ISSUE TITLE
电脑重装后shadowsocks没办法关闭系统代理

### ISSUE THREAD

**Issue by LeungHEX** [shadowsocks/shadowsocks-windows#390]
其实问题不止这一点，我是用的校园网，用了vpn的方式去到外网（为了速度），以前两种模式（内外网）都是可以正常使用shadowsocks的，因为某些原因重装了电脑，因为安装包都是以前保留的所以个人认为不会有软件冲突。无论用什么浏览器在用内网的时候只要打开了shadowsocks就会自动开始进入系统代理模式（无论系统代理选项是开还是关），用外网的时候shadowsocks直接不工作，显示日志的时候偶尔出现failed to recv data in handshakeReceive2Callback 这个提示，其他的都没出现 连time out都没有。网上说是和迅雷冲突但是以前一直用迅雷也没什么问题……望大神指教

**Comment by GangZhuo** [comment]
请检查Shadowsocks 目录的文件权限

**Comment by LeungHEX** [comment]
现在内外网问题貌似可以了 现在就是关闭系统代理那个选项失效了 无论是不是启用都会进到系统代理 这个貌似和文件权限无关吧？

**Comment by icylogic** [comment]
手动开一次关一次该选项, 系统代理无变化?

**Comment by LeungHEX** [comment]
对的 用的是win7 下的2.5.6一直用这个版本 其他电脑没这个问题

**Comment by LeungHEX** [comment]
关之前说一句吧……系统几次更新之后就没有这个问题了 估计是系统架构原来有bug……更新完就ok了
