### ISSUE TITLE
服务器列表清空后再添加导致程序崩溃

### ISSUE THREAD

**Issue by LewisLee75267** [shadowsocks/shadowsocks-windows#393]
编辑服务器界面下，如果先删除列表中所有的服务器，再点击添加按钮，程序会直接崩溃。
![ss](https://cloud.githubusercontent.com/assets/12710540/11682826/34f76b54-9ea2-11e5-86b7-ce1f58fa7e7a.png)

**Comment by icylogic** [comment]
在 #345 已修复，尚未发布，可以在 https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.56/job/xrf4e3ahi4e6af1c/artifacts 找到自动编译的版本
