### ISSUE TITLE
不打勾系统代理,也可以直接用这个ss吗?

### ISSUE THREAD

**Issue by mtvktvcn** [shadowsocks/shadowsocks-windows#397]
不打勾系统代理,也可以直接用这个ss吗?

**Comment by mtvktvcn** [comment]
用shadowsocks+switchyomega,我没有打勾系统代理这个,也一样可以用.

**Comment by mtvktvcn** [comment]
http://sneakupsneakers.blog.jp/
这个网站 用ss之后 打开是空白页 用goagent可以.

**Comment by chenshaoju** [comment]
１.可以
２.这个网站我用日本的SS能打开。

![unnamed qq screenshot20151213213918](https://cloud.githubusercontent.com/assets/515763/11767231/fa95bdf6-a1e1-11e5-8ed8-42b98abab824.png)

**Comment by mtvktvcn** [comment]
这就有点奇怪了. 我的换了几个浏览器都不会.
一换成GOAGENT就OKAY.

[img]http://chuantu.biz/t2/22/1450014735x-1376440141.png[/img]

**Comment by mtvktvcn** [comment]
这就有点奇怪了. 我的换了几个浏览器都不会.
一换成GOAGENT就OKAY.
http://chuantu.biz/t2/22/1450014735x-1376440141.png

**Comment by chenshaoju** [comment]
如果这是你的VPS，你用SSH打开看看。
如果这是你的SS服务商，请写信或使用服务商的工单系统报告你的这个问题。

**Comment by mtvktvcn** [comment]
可以打开.我是用WIN2008做的. 在VPS可以打开这个网页的.

**Comment by GangZhuo** [comment]
@mtvktvcn 不打勾系统代理的话，必须手动设置系统代理或和其他工具配合使用，例如：SwitchyOmega, sockscap等
