### ISSUE TITLE
启用系统代理的作用是什么？

### ISSUE THREAD

**Issue by shenhuabuluo** [shadowsocks/shadowsocks-windows#398]
启用系统代理的作用是什么？  仅仅是IE启用代理 还是开启后 所有的软件业都是走代理的？

**Comment by chenshaoju** [comment]
系统代理，是指让系统可以通过指定的PAC文件进行代理。

前提是你的软件需要支持PAC代理。

**Comment by icylogic** [comment]
<img width="639" alt="2015-12-14_22-55-40" src="https://cloud.githubusercontent.com/assets/2814357/11784152/da4fc9fe-a2b5-11e5-8e7c-f62def098506.png">
改变这里的设置, 改变自动代理 (PAC) 还是手动代理看你选择的 Mode.
