### ISSUE TITLE
关于ServerIP为IPv6地址时读取配置出错的Bug

### ISSUE THREAD

**Issue by SuperHentai** [shadowsocks/shadowsocks-windows#399]
当配置文件中存在形如“2400:8500:1301:744:a133:130:109:18f”的IPv6地址时，程序会抛出异常
“System.InvalidOperationException
Message: “System.InvalidOperationException”类型的未经处理的异常在 System.Threading.Tasks.dll 中发生 
其他信息: 序列不包含任何匹配元素
”

经过测试，该bug似乎在commit [4684af0](https://github.com/shadowsocks/shadowsocks-windows/commit/4684af053e996399b3a6aec17c84773016df4a30) 中引入，暂时不太有时间所以就没有详细看问题出在哪里，各位有空修复的话就修复一下吧~
如果你们也没有时间的话，过一段时间等我有空了去检查并试图修复一下。

**Comment by everyx** [comment]
你可以在 Statistics Config 中将 Enable Statistics 的选项去掉勾选并保存。

另外你已经提提过了这个问题 #375

**Comment by GangZhuo** [comment]
估计是这一行 https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/AvailabilityStatistics.cs#L126 ，你可以调试看看。

**Comment by GangZhuo** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/87c5b23e2151f3113f6832de01dd1bc01f6c3b77
