### ISSUE TITLE
请问2.5.8之后还会有新版吗？

### ISSUE THREAD

**Issue by cntel18217223380** [shadowsocks/shadowsocks-windows#402]
请问2.5.8之后还会有新版吗？

**Comment by chenshaoju** [comment]
有，目前还在测试阶段。

截止到本回复时，你可以在 https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/40ld47ne008owe05/artifacts 下载到最新的测试版。

**Comment by cntel18217223380** [comment]
加了更新检查还有另外一个英文的东西，不过我发现这真的是测试版...如图。。。已挂。


![default](https://cloud.githubusercontent.com/assets/15363978/11829641/f0140538-a3d8-11e5-8d6a-86aa0b440ce7.PNG)

**Comment by cntel18217223380** [comment]
![default](https://cloud.githubusercontent.com/assets/15363978/11829765/f70dd2d2-a3d9-11e5-941c-a9c937b71313.PNG)


暂时还是不碰测试版了，挂太快。。。

**Comment by GangZhuo** [comment]
问题详细信息能截全一点吗？

**Comment by cntel18217223380** [comment]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	2.5.8.0
  问题签名 03:	566fdd9e
  问题签名 04:	System
  问题签名 05:	4.0.30319.17929
  问题签名 06:	4ffa5c88
  问题签名 07:	1eb7
  问题签名 08:	12
  问题签名 09:	System.Net.Sockets.Socket
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by chenshaoju** [comment]
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.61/job/40ld47ne008owe05/artifacts

请试一下这个版本，这是17小时前的版本。

不知道为什么，最新版本反而是９天前的。

**Comment by cntel18217223380** [comment]
![default](https://cloud.githubusercontent.com/assets/15363978/11832097/dd6fe20a-a3ef-11e5-9e00-32648b63dffb.PNG)

它还是挂了。

**Comment by cntel18217223380** [comment]
![default](https://cloud.githubusercontent.com/assets/15363978/11832119/0f4cb8ac-a3f0-11e5-94f6-b403b120a40a.PNG)


目前用这个死循环脚本能坚持一下。

**Comment by cntel18217223380** [comment]
![default](https://cloud.githubusercontent.com/assets/15363978/11832140/4220adba-a3f0-11e5-993f-b9d23232af1d.PNG)

问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	2.5.8.0
  问题签名 03:	566fdd9e
  问题签名 04:	System
  问题签名 05:	4.0.30319.17929
  问题签名 06:	4ffa5c88
  问题签名 07:	1eb7
  问题签名 08:	12
  问题签名 09:	System.Net.Sockets.Socket
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by cntel18217223380** [comment]
我能做些什么来判断出程序挂掉的原因吗。一直在挂，死循环启动之后几十秒之后就挂了，挂太快了
。![default](https://cloud.githubusercontent.com/assets/15363978/11832167/823f8380-a3f0-11e5-8026-02319aa4ed75.PNG)

**Comment by GangZhuo** [comment]
有点不像是程序问题，是不是系统设置了什么安全策略？

**Comment by cntel18217223380** [comment]
没有设置安全策略，使用其它版本的shadowsocks是正常的，不过也会挂，只是时间长短的问题。

**Comment by SuperHentai** [comment]
@chenshaoju 这个项目的规则是这样的，每次有发起对master的pull request时，检查过程中会提交编译一遍，所以最新的自动编译版本很多时候都来自于pull request，对方的项目过期就会导致编译出来的程序是过期的.

**Comment by cntel18217223380** [comment]
呃，我能否使用微软的VS手动编译？

**Comment by chenshaoju** [comment]
@SuperHentai :+1:

**Comment by AnyoeDove** [comment]
那个测试版本我也是打开statistics-config就崩溃 用@wongsyrone 同学编译的就可以正常使用https://twitter.com/SyroneWong/status/677111201285799936

**Comment by wongsyrone** [comment]
我使用的是VS 2015 社区版，其他的并没有什么改动。
顺便我说一个off-topic的事，在 https://github.com/shadowsocks/shadowsocks-libev/commit/5c3ed5c9c17b07f77620a1b0a0e5bc55db1f79a4 里添加的 chacha20-ietf 加密方式如果有兴趣的话可以参考 https://github.com/wongsyrone/libsscrypto 和 https://github.com/wongsyrone/shadowsocks-windows 的相关commit 进行修改，主要升级libsodium为1.0.7（增加了对SSSE3指令集优化的chacha20实现）和mbedtls为2.1.3（由于libev删掉了自有的sha1-hmac，使用了mbedtls的相关函数）对于libsscrypto来说，目前ss-libev的submodule也可以删掉了。
对于android版本，应该一个commit https://github.com/wongsyrone/shadowsocks-android/commit/43b63dcbb8905061aa79d5e7a5f167b2cb75f10b 就够了

**Comment by GangZhuo** [comment]
@wongsyrone Can you open a PR?

**Comment by wongsyrone** [comment]
@GangZhuo  Sure. I will prepare a PR this evening.

**Comment by cntel18217223380** [comment]
不过我有个更严重的问题，我们这样讨论不会被有关当局请去喝茶吗。

**Comment by soyet** [comment]
@cntel18217223380 不要怕
伟大的无产阶级自由斗士***夏明翰***几十年前就告诉我们：
>砍头不要紧
>只要主义真
>杀了***你***一个
>还有后来人

---
哈哈哈，开个玩笑。当局只顾着自己喝茶，哪有闲工夫理你啊。

**Comment by GangZhuo** [comment]
@cntel18217223380 此问题应该不是软件的问题，自行搜索解决吧。

**Comment by GangZhuo** [comment]
@cntel18217223380 可以试试便携模式。

**Comment by cntel18217223380** [comment]
便携模式怎么开？

**Comment by soyet** [comment]
@cntel18217223380 在shadowsock-win.exe同一目录下，新建名为 `shadowsocks_portable_mode.txt` 的文件，然后重启ss，即可获得***便携版ss***一枚

**Comment by cntel18217223380** [comment]
以前不知道，现在才发现这软件原来有这么多文件要生成。

**Comment by WLZLCX** [comment]
同问，不更新 不习惯啊，哈哈

**Comment by CNMan** [comment]
https://ci.appveyor.com 上自动编译的最新版不能运行
OS:winsrv 2012r2+.NET:4.6.1

.NET 4.6.1已经在windows update里了
http://blogs.msdn.com/b/dotnet/archive/2016/01/26/microsoft-net-framework-4-6-1-is-available-on-windows-update-and-wsus.aspx

```
- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2016-02-05T13:57:05.000000000Z 
 
   EventRecordID 20320 
 
   Channel Application 
 
   Computer WIN-96O46B6LQH7 
 
   Security 
 

- EventData 

   Shadowsocks.exe 
   2.5.8.2 
   56b47429 
   KERNELBASE.dll 
   6.3.9600.18091 
   561fd8af 
   e0434352 
   00015b68 
   13a4 
   01d1601d189dbea1 
   D:\Downloads\Shadowsocks.exe 
   C:\Windows\SYSTEM32\KERNELBASE.dll 
   5692e5a1-cc10-11e5-8132-60eb6974dfc0 
```

```
- System 

  - Provider 

   [ Name]  .NET Runtime 
 
  - EventID 1026 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2016-02-05T14:01:12.000000000Z 
 
   EventRecordID 20321 
 
   Channel Application 
 
   Computer WIN-96O46B6LQH7 
 
   Security 
 

- EventData 

   应用程序: Shadowsocks.exe Framework 版本: v4.0.30319 说明: 由于未经处理的异常，进程终止。异常信息: System.InvalidProgramException 在 Costura.AssemblyLoader.LoadStream(System.String) 在 Costura.AssemblyLoader.LoadStream(System.Collections.Generic.Dictionary`2<System.String,System.String>, System.String) 在 Costura.AssemblyLoader.ReadFromEmbeddedResources(System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Reflection.AssemblyName) 在 Costura.AssemblyLoader.ResolveAssembly(System.String) 在 Costura.AssemblyLoader.<Attach>b__0(System.Object, System.ResolveEventArgs) 在 System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String) 异常信息: System.IO.FileLoadException 在 Shadowsocks.Model.Configuration.Load() 在 Shadowsocks.Controller.ShadowsocksController..ctor() 在 Shadowsocks.Program.Main()  
```
