### ISSUE TITLE
Shadowsocks和ADSafe去广告软件冲突怎么解决？

### ISSUE THREAD

**Issue by reaCodes** [shadowsocks/shadowsocks-windows#404]
ADSafe一开，shadowsocks就停止工作了

**Comment by chenshaoju** [comment]
禁用Shadowsocks的系统代理功能看看？

**Comment by reaCodes** [comment]
@chenshaoju 我一起都是PAC模式，是不是ADSafe抢占了代理端口？不过我看了一下设置里，代理没有变呀

**Comment by reaCodes** [comment]
@chenshaoju 把你的意思理解错了，你是叫我禁用系统代理吗，那shadowsocks不是更不起作用了？ADSafe一直是能用的

**Comment by reaCodes** [comment]
![0j7v9 kr i m38 pdho83](https://cloud.githubusercontent.com/assets/13817254/11836683/3da85b80-a417-11e5-9b15-089a5aed7bb8.png)
打开Google就是这个状况 @chenshaoju

**Comment by chenshaoju** [comment]
ADSafe等软件的原理，是拦截HTTP请求并重定向，也会取消PAC代理。这两者没有办法兼容。

详见：https://www.zhihu.com/question/21697354

**Comment by reaCodes** [comment]
@chenshaoju 那如何广告过滤？麻烦的是我还没用chrome，用的edge

**Comment by GangZhuo** [comment]
可以自己编辑 PAC 文件，参考： https://github.com/fulicat/hosts.pac

**Comment by reaCodes** [comment]
@GangZhuo 我不太会用这个，这是过滤广告用的?

**Comment by GangZhuo** [comment]
@reaCodes 自己搜索吧
