### ISSUE TITLE
Git怎么走SS代理向github提交代码呢？

### ISSUE THREAD

**Issue by mikicomo** [shadowsocks/shadowsocks-windows#407]
假如我现在有gitosc和github两个地方的repo，我只想github的域名走代理，该怎么设定呢？搜索引擎搜索过了，不过总感觉不是很清晰流程，新人求教，谢谢了。

**Comment by lixingcong** [comment]
修改pac.txt添加github.com

**Comment by mikicomo** [comment]
@lixingcong  谢谢了，已成功，不过应该不要直接修改pac.txt吧，不然下次升级就被覆盖了，还是编辑user-rule.txt 比较妥当吧，下次升级也不会覆盖~

**Comment by mikicomo** [comment]
@lixingcong  不知道是否是错觉，设置了一次代理之后我关闭ss，速度依旧.....（以前100K/S上下，现在1M/S上下）

**Comment by soyet** [comment]
`git config http.proxy http://127.0.0.1:1080`

**Comment by mikicomo** [comment]
@soyet 这样好像不行咦.....
@lixingcong  白天好像疏忽了，貌似是因为校园网的缘故变快了，现在回了寝室又只有2、30k了，貌似没代理成功

**Comment by soyet** [comment]
@mikicomo 这是为项目单独设置http proxy
你可以参考一下[这篇帖子](http://segmentfault.com/q/1010000000118837)

**Comment by mikicomo** [comment]
@soyet  这帖子我看了，不过我刚才在“老高的博客”里看到了git本身支持socks5了，
git config --local http.proxy 'socks5://127.0.0.1:1080' 
git config --local https.proxy 'socks5://127.0.0.1:1080'
可惜断网了，没法试了，热点跑不出速度，比较不出来是否走了代理

**Comment by mikicomo** [comment]
@soyet  如果你能帮我试一下的话就最好啦 :)

**Comment by mikicomo** [comment]
@soyet  刚才试了下，
git config --local http.proxy 'socks5://127.0.0.1:1080' 
git config --local https.proxy 'socks5://127.0.0.1:1080'
如此设置可行

**Comment by ycjcl868** [comment]
设置不了，ss走的是 1086

![a25aecf4-ae14-4d7b-8223-3ff5db2b77dc](https://cloud.githubusercontent.com/assets/13595509/23573697/eef03c34-00b2-11e7-9a5c-9180fcee9fe4.png)

**Comment by ChouUn** [comment]
@ycjcl868 字面意思，请看报错。还有请搞清楚自己输入的命令在做什么。比如这个 --local

**Comment by pexcn** [comment]
```
git config --global http.proxy "http://127.0.0.1:Privoxy 监听的端口"
git config --global https.proxy "http://127.0.0.1:Privoxy 监听的端口"
```

**Comment by xpzouying** [comment]
首先查看shadowsocks监听的端口，

这里是socks5协议的，
![image](https://user-images.githubusercontent.com/3946563/35546586-cad6caf4-05af-11e8-9889-f6114c668e40.png)

这里是HTTP协议的，
![image](https://user-images.githubusercontent.com/3946563/35546620-f09e64f4-05af-11e8-89c4-d5f936943217.png)

修改成正确的端口，执行命令：
```bash
# 使用socks5协议
HTTP_PROXY="socks5://127.0.0.1:1086" HTTPS_PROXY="socks5://127.0.0.1:1086" git clone git@github.com:sirupsen/logrus.git

# 使用http协议
HTTP_PROXY="http://127.0.0.1:1087" HTTPS_PROXY="http://127.0.0.1:1087" git clone git@github.com:sirupsen/logrus.git
```
![image](https://user-images.githubusercontent.com/3946563/35546671-2bbc40ce-05b0-11e8-9bdc-74cf7ad22a2c.png)

![image](https://user-images.githubusercontent.com/3946563/35546717-68d03dda-05b0-11e8-91e2-2100a6164663.png)

**Comment by YSZYCF** [comment]
为啥走代理的时候,用git协议只有,几十kb,而用http协议1m多,不走代理的情况下，都是几十kb.?
mac电脑
配置:
         git config --global http.proxy  'socks5://127.0.0.1:1087'
         git config --global https.proxy 'socks5://127.0.0.1:1087"

**Comment by longshilin** [comment]
@YSZYCF 实际测试结果，git上传资源的时候**走ssh协议**，下面这行代码生效，以下是我的测试：
```
~/UnityProject/TankBattle (master)
$ HTTP_PROXY="socks5://127.0.0.1:1080" HTTPS_PROXY="socks5://127.0.0.1:1080" git push -u origin master
Counting objects: 679, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (678/678), done.
Writing objects:  88% (599/679), 65.41 MiB | 847.00 KiB/s
```
对于200MB以上的资源，全速上传还是至关重要的！（gitlab可以支持直接存储100MB以上的项目）

**Comment by robinvanyang** [comment]
google keyword: ssh ProxyCommand  shadowsocks,  I use this ssh ProxyCommand config to access github.com, it works.

~/.ssh/config:
`
    host github.com
    HostName github.com
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/github
    ProxyCommand connect -S 127.0.0.1:1080 %h %
`
