### ISSUE TITLE
高CPU占用

### ISSUE THREAD

**Issue by Heartsong1** [shadowsocks/shadowsocks-windows#409]
今天开机以后，发现机器特别卡，打开任务管理器以后，情况如图所示：版本是2.5.8，开机自启，操作系统：win10专业版10.0.10240。CPU：i7-2720QM
![qq 20151225100839](https://cloud.githubusercontent.com/assets/13311467/11999123/90e076da-aaf1-11e5-8fa1-edcd8329b5b9.png)

**Comment by chenshaoju** [comment]
１.下载： https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx 
２.以管理员身份运行。
３.在Process Explorer窗口中找到Shadowsocks.exe，双击。
４.点击Threads选项卡，然后截图发上来。（类似下图）。

![unnamed qq screenshot20151225104043](https://cloud.githubusercontent.com/assets/515763/11999217/188b1692-aaf4-11e5-9139-afe5ffac46f4.png)

**Comment by Heartsong1** [comment]
无法重现描述的问题...
![image](https://cloud.githubusercontent.com/assets/13311467/12013710/6eedf8a0-ad57-11e5-902c-3c1d916b9649.png)

**Comment by chenshaoju** [comment]
请继续观察，有问题的时候再进行测试。

**Comment by gakkiyui** [comment]
同样的问题。重新启动Shadowsocks后又恢复正常。版本是2.5

**Comment by chenshaoju** [comment]
@gakkiyui 当出现问题的时候，请按照上面的描述测试一下。

**Comment by blueyi** [comment]
这个问题我也遇到多次了，可能会跟WINDOWS的系统更新有关，今天又出现了

**Comment by lyhper** [comment]
同遇到这个问题，关掉重开就好了

**Comment by wangdaqiao** [comment]
此问题确实会不时出现，已经遇到很多次了，每次杀掉重启就好了。我前些日子抓了个dump https://drive.google.com/file/d/0BxOhLC6qm-umSENBUG1DUVpWRU0/view?usp=sharing 敬请参考。

**Comment by GangZhuo** [comment]
@wangdaqiao Thanks.

Fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/ea43e2a72dcfea423b2c95adbd030291231b12c1

**Comment by blueyi** [comment]
最新版本是2.5.8吗？我在2.5.8版本下遇到的该问题，谢谢 @GangZhuo

**Comment by chenshaoju** [comment]
@blueyi  https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/k1vckk5jh3khn4yi/artifacts

**Comment by blueyi** [comment]
@chenshaoju 请问这个是新版本的发布地址吗？或者最新版本的发布地址在哪里，谢谢

**Comment by blueyi** [comment]
@chenshaoju 明白了，谢谢
