### ISSUE TITLE
最新的测试版在系统休眠恢复后报错退出了

### ISSUE THREAD

**Issue by islercn** [shadowsocks/shadowsocks-windows#410]
一堆的
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2015-12-28 12:51:47] System.Net.Sockets.SocketException (0x80004005): 套接字操作尝试一个无法连接的主机。 xxx.xxx.xxx.xxx:xxxx
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

还有两段：

   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2015-12-28 12:51:49] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: 未能解析此远程名称: 'ip-api.com'
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   在 Shadowsocks.Controller.AvailabilityStatistics.<GetInfoFromAPI>d__28.MoveNext()
[2015-12-28 12:51:49] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: 未能解析此远程名称: 'www.telize.com'
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   在 Shadowsocks.Controller.AvailabilityStatistics.<GetInfoFromAPI>d__28.MoveNext()

   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2015-12-28 12:57:45] System.IO.IOException: 文件“C:\Users\Isler\AppData\Local\Temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()
[2015-12-28 12:57:45] Shadowsocks started

**Comment by islercn** [comment]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	Shadowsocks.exe
  问题签名 02:	2.5.8.0
  问题签名 03:	56729283
  问题签名 04:	Microsoft.Threading.Tasks
  问题签名 05:	1.0.12.0
  问题签名 06:	5342fb37
  问题签名 07:	2f
  问题签名 08:	31
  问题签名 09:	FOPL4MYEJCHQ4QUDLY5M1JG1EE1KJYWU
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by renziyao** [comment]
同休眠后报错
重启ss可解决
[2016-02-06 00:19:11] Shadowsocks started
[2016-02-06 00:19:42] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
[2016-02-06 00:19:43] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
[2016-02-06 00:19:52] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
[2016-02-06 00:21:38] Shadowsocks started

**Comment by chenshaoju** [comment]
Windows 7 x64 笔记本没有遇到该问题，但是请尝试使用此版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/2c9wh09tealdsyaa/artifacts

**Comment by GangZhuo** [comment]
使用的是修改版，请汇报到他那里去。
