### ISSUE TITLE
在更新本地PAC时用户自定义条目能不能放在最前面？

### ISSUE THREAD

**Issue by islercn** [shadowsocks/shadowsocks-windows#411]
因为网络等的原因，自定义条目和ss更新的gfwlist有重叠，所以希望能自动把user-rule.txt的放在pac里rules的最前面，毕竟用户自定义的优先级应该最高吧？

**Comment by GangZhuo** [comment]
adblock 的规则是顺序无关的。

**Comment by GangZhuo** [comment]
ref: https://adblockplus.org/en/faq_basics#ordering
