### ISSUE TITLE
是否有方法多开客户端？

### ISSUE THREAD

**Issue by leviathangirl** [shadowsocks/shadowsocks-windows#412]
我在内网环境下搭了ss服务器，并且做了端口映射到外网，想依靠ss服务来访问内网的资源。
但是shadowsocks-windows在win7上只能开一个客户端。

是否有方法多开客户端？

PS：qt版的我用过了，会很频繁的出现页面被reset的问题，不知道原因（因为都是墙内资源和本地自家服务器的资源，所以应该不存在干扰）

**Comment by GangZhuo** [comment]
portable 模式可以多开： https://github.com/shadowsocks/shadowsocks-windows/tree/master#portable-mode

**Comment by leviathangirl** [comment]
@GangZhuo 实测可用，非常感谢。
