### ISSUE TITLE
 “……由于目标计算机积极拒绝，无法连接……”朋友帮我看看日志问题

### ISSUE THREAD

**Issue by reaCodes** [shadowsocks/shadowsocks-windows#417]
朋友帮我看看这份日志，看youtube几分钟就卡死了，几分钟后网络就恢复，就这么卡来卡去，网速是很快的，就是卡。主机用的DigitalOcean-512M

   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2016-01-12 13:38:10] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 45.55.13.103:8388
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2016-01-12 13:52:15] Shadowsocks started

**Comment by chenshaoju** [comment]
换一个端口看看，不要用默认的8388端口

**Comment by reaCodes** [comment]
@chenshaoju 为什么最好不要使用默认？

**Comment by GangZhuo** [comment]
@reaCodes 代理端口一般都是8388，容易被阻断。
