### ISSUE TITLE
SS时而链接时而断链问题（迅雷）

### ISSUE THREAD

**Issue by James-Z** [shadowsocks/shadowsocks-windows#419]
各位不知道有没有遇到过非SS服务器故障但是windows就是打不开网页的问题
排除windows防火墙，杀毒软件和浏览器故障等问题。我发现还有一种情况就是迅雷的XLServicePlatform服务。
有时候不得不使用迅雷下载美剧、电影等（原因你懂的）。所以直接卸载迅雷外还有一种办法就是禁用此服务就OK了。
原帖如下：http://www.gznf.net/thread-544318-1-1.html
在资源管理器右击“计算机”图标，选管理 然后在“服务和应用程序”中选择“服务” 在服务列表中停用和禁止XLServicePlatform 打开注册表定位到以下路径，删除XLServicePlatform项，这个服务即可在服务中消失。 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\XLServicePlatform 打开文件夹C:\Program Files\Common Files\Thunder Network\ServicePlatform，找到文件XLSP.dll 【64位win7为C:\Program Files (x86)】 删除XLSP.dll，并新建一个0字节的txt文件，将其改为XLSP.dll 至此已经解决开机弹出出错信息的问题了。 但是，迅雷这个流氓，每次启动还是会将服务重新启动的。不过由于核心文件已经被清0，所以就避免了出错信息的出现。 再次概叹中国人除了做事不循正道之外，连写软件也如此不要脸，实在无语。

**Comment by James-Z** [comment]
XLServicePlatform很特殊就是你无法用普通手段关闭它。

**Comment by XhstormR** [comment]
国产软件一直都很不要脸，都称其`流氓软件`。

**Comment by reaCodes** [comment]
我用CCleaner清理过注册表了，好像被清理掉了，当时安装了个迅雷极速版，卸载了之后还能在好多地方看到迅雷相关的文件夹，太流氓

**Comment by kimw** [comment]
The ``XLServicePlatform`` is a windows service. You can stop it in ``Windows Services`` by type command
````
services.msc
````
in ``Command Prompt``.

**Comment by joyang1** [comment]
公司的shadowsocks在公司可以用 在家里偶尔可以连上 经常timed out，大家知道什么问题嘛？

**Comment by joyang1** [comment]
在连不上的时候 可以telnet通服务器 也可以ping通

**Comment by chenshaoju** [comment]
怀疑和协议栈有关，请尝试以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh interface tcp reset
netsh winsock reset
```
一行一回车，四行执行完毕后重新启动计算机看看。

注意：如果你的计算机是手动指定IP地址上网的话，重启后需要再手动设置一次IP，如果是自动分配，则无影响。

**Comment by joyang1** [comment]
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
昨天在家运行了这三行 运行完之后能上个20多分钟的外网 但是过一会又不能上了

晚上回去再加上这一行试试
netsh interface tcp reset

谢谢@chenshaoju(https://github.com/chenshaoju)的回复 有问题再向你请教一下

**Comment by joyang1** [comment]
Probing 172.104.118.192:2001/tcp - No response - time=2010.256ms
Probing 172.104.118.192:2001/tcp - No response - time=2013.466ms
Probing 172.104.118.192:2001/tcp - No response - time=2001.341ms
Probing 172.104.118.192:2001/tcp - No response - time=2000.433ms

不能连接的时候tcp ping不通 什么原因

**Comment by YolineWu** [comment]
用qbittorrent下载不行吗？

**Comment by chenshaoju** [comment]
@joyang1 在不通的时候请使用海外的TCP测试服务（如： https://www.infobyip.com/tcpportchecker.php ）测试你的端口是否能通，如果能通，说明被墙了。

如果不能通，请检查服务端程序是否崩溃了。

**Comment by joyang1** [comment]
好的 谢谢老哥

**Comment by joyang1** [comment]
@chenshaoju 海外的TCP测试服务可以通 Successfully connected to 172.104.118.192:2001
端口被封 可以怎么搞呀

**Comment by joyang1** [comment]
@chenshaoju server端也要装这个插件嘛

**Comment by chenshaoju** [comment]
@joyang1 是的。

**Comment by joyang1** [comment]
@chenshaoju  将obfs-local.exe拷贝到ss根目录下，然后在
plugins(插件选项):obfs-local
plugins-opts(插件参数): obfs=http;obfs-host=www.bing.com
插件程序那一栏不用填 对吧

**Comment by chenshaoju** [comment]
插件程序 obfs-local
插件选项 obfs=http;obfs-host=www.bing.com

**Comment by joyang1** [comment]
server端配置 帮忙看下有问题吗
$ ssserver --version 
Shadowsocks 3.0.0 

Ubuntu 16.04.5
python 版本 shadowsokcs

{
    "server": "0.0.0.0",
    "local_port": 1080,
    "port_password": {
      ...
    },
    "timeout": 300,
    "method": "chacha20-ietf-poly1305",
    "fast_open": false,
    "mode": "tcp_and_udp",
    "plugin": "obfs-server --obfs http"
}

**Comment by joyang1** [comment]
@chenshaoju 

server端配置 帮忙看下有问题吗
$ ssserver --version
Shadowsocks 3.0.0

Ubuntu 16.04.5
python 版本 shadowsokcs

{
"server": "0.0.0.0",
"local_port": 1080,
"port_password": {
...
},
"timeout": 300,
"method": "chacha20-ietf-poly1305",
"fast_open": false,
"mode": "tcp_and_udp",
"plugin": "obfs-server --obfs http"
}

**Comment by chenshaoju** [comment]
我不确定Python版能这样用……我的服务端是libev，客户端是windows，也许你需要到Python版问问？

**Comment by joyang1** [comment]
好的 谢谢啊

**Comment by joyang1** [comment]
@chenshaoju  libev版本是这样设置的嘛
ss-server -c config.json --plugin obfs-server --plugin-opts "obfs=http"

**Comment by joyang1** [comment]
@chenshaoju  
插件程序 obfs-local
插件选项 obfs=http;obfs-host=www.bing.com
本地设置好了这两个选项就连不上网了 什么情况呢
log是下面这个:
[2018-09-04 10:44:02] Started SIP003 plugin for tokyo-fast.larryzhao.com:2001 on 127.0.0.1:59279 - PID: 4276
[2018-09-04 10:44:02] Shadowsocks started (4.1.1)
[2018-09-04 10:44:02] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

**Comment by joyang1** [comment]
@chenshaoju
插件程序 obfs-local
插件选项 obfs=http;obfs-host=www.bing.com
本地设置好了这两个选项就连不上网了 什么情况呢
log是下面这个:
[2018-09-04 10:44:02] Started SIP003 plugin for tokyo-fast.larryzhao.com:2001 on 127.0.0.1:59279 - PID: 4276
[2018-09-04 10:44:02] Shadowsocks started (4.1.1)
[2018-09-04 10:44:02]
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor

**Comment by celeron533** [comment]
客户端需要obfs-local.exe程序

**Comment by joyang1** [comment]
@celeron533 我客户端里面有obfs-local.exe程序 我下载了的

**Comment by chenshaoju** [comment]
你的服务是买的还是自己搭的？

所有的插件都需要服务端的支持，如果你的服务器本身没有这个插件，你使用这个插件也没有用的。

**Comment by joyang1** [comment]
@chenshaoju  服务器是买的 服务器端装了插件

**Comment by chenshaoju** [comment]
你能否看一下你服务端的插件启动了吗？

另外，配置是否正确？

**Comment by chenshaoju** [comment]
刚搜了一下Python的服务端，好像Python的服务端不支持插件，你需要以独立运作的方式运行插件：
https://github.com/shadowsocks/shadowsocks/issues/1028

**Comment by joyang1** [comment]
{
    "server": "0.0.0.0",
    "local_port": 1080,
    "port_password": {
      ...
    },
    "timeout": 300,
    "method": "chacha20-ietf-poly1305",
    "fast_open": false,
    "mode": "tcp_and_udp",
    "plugin": "obfs-server"
    "plugin_opts": "obfs=http"
}

怎么看服务端有没有启动插件呢

**Comment by joyang1** [comment]
@chenshaoju 
{
"server": "0.0.0.0",
"local_port": 1080,
"port_password": {
...
},
"timeout": 300,
"method": "chacha20-ietf-poly1305",
"fast_open": false,
"mode": "tcp_and_udp",
"plugin": "obfs-server"
"plugin_opts": "obfs=http"
}

怎么看服务端有没有启动插件呢

**Comment by chenshaoju** [comment]
使用 ps -A 命令看。

**Comment by joyang1** [comment]
好的

**Comment by joyang1** [comment]
@chenshaoju 
帮忙看下这个 我按照shadowsocks-libev启动了但是出现下面的问题 帮忙看一下：
https://github.com/shadowsocks/shadowsocks-libev/issues/2166

**Comment by chenshaoju** [comment]
这种情况意味着你的配置文件或者启动参数有误，请检查服务配置文件中的参数是否正确，以及配置文件是否正确。

我的是自己编译的，可能和你的情况不一样。
