### ISSUE TITLE
使用PAC文件后IE的UA被更改。

### ISSUE THREAD

**Issue by zcgkiller** [shadowsocks/shadowsocks-windows#420]
用PAC文件的时候，IE的User Agent会被更改
我用的IE11，不用PAC脚本的时候，UA是：User-Agent: Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko
用了PAC之后，ＵＡ是：User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; SLCC2; Media Center PC 6.0)
但是直接用SS全局代理是正常的。
请问有方法不改变UA吗？浏览一些网站的时候会排版错乱。

**Comment by chenshaoju** [comment]
你好，我我运行了一下测试，并没有该问题。

有可能是你的代理服务器修改的？请尝试不用PAC，使用Firefox或Chrome，手动指定代理服务器地址测试看看。

![screenshot](https://cloud.githubusercontent.com/assets/515763/12313074/7d4bd908-ba9f-11e5-8272-bb913cedc63c.png)

**Comment by zcgkiller** [comment]
![default](https://cloud.githubusercontent.com/assets/16483652/12314896/2e34c292-bab0-11e5-8033-a6b0f912c567.png)
这是不用代理的UA
![default](https://cloud.githubusercontent.com/assets/16483652/12314901/3aecc386-bab0-11e5-9d5f-fa8b4546c5e1.png)
这是全局代理的UA
![use pac](https://cloud.githubusercontent.com/assets/16483652/12314910/4833b414-bab0-11e5-8181-743e8cb8050f.png)
这是使用自动配置脚本文件后的UA，前后只是使用PAC的不同，并没有其他的变化。所使用的PAC是shadowsocks windows客户端自动生成的，并没有做任何改动。

**Comment by chenshaoju** [comment]
请尝试使用这个PAC：https://gist.github.com/chenshaoju/52c7555acc65ec98423f

这个PAC是我自己编写的，仅能保证访问Google和这个What's my user agent。

**Comment by zcgkiller** [comment]
奇怪了，我用在线PAC，填入你给的网址后，打不开Google等国外网站。
我自己生成的pac文件填入也不行。只有用shadowsocks客户端自带的那个可以。使用本地PAC功能后，自动配置脚本那里显示“http://127.0.0.1:1080/pac?t=201601141452117349”，我怀疑是这个功能的问题。

**Comment by wongsyrone** [comment]
https://github.com/browscap/browscap/issues/113
