### ISSUE TITLE
System.Net.Sockets.... MSG... ERROR?

### ISSUE THREAD

**Issue by charliechan** [shadowsocks/shadowsocks-windows#423]
[2016-01-15 18:21:17]  ss-node1 timed out
[2016-01-15 18:21:17] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()

//NOTE: OS IS WINDOWS 2008 SVR2

**Comment by chenshaoju** [comment]
Check this out: https://github.com/shadowsocks/shadowsocks-windows/issues/247#issuecomment-131392491
