### ISSUE TITLE
如果想顺利访问Youtube，PAC文件中必须要有那些网址？

### ISSUE THREAD

**Issue by reaCodes** [shadowsocks/shadowsocks-windows#425]
我添加了：

youtu.be
youtube.com
ytimg.com
googlevideo.com
ggpht.com

发现有些视频打开要好一小会才能播放，并不是网速的原因，因为开始播放后加载很快，看来就是跳转链接慢，还缺什么网址

更新：最后我加了一个youtube-nocookie.com，问题完美解决了

**Comment by wenliyang** [comment]
ggpht.com

**Comment by reaCodes** [comment]
@wenliyang 忘了说了，我已经加上去了，头像图片的链接

**Comment by XhstormR** [comment]
GFWLIST

**Comment by reaCodes** [comment]
@XhstormR 我知道，我先把它简化一下，做一个我需要的PAC

**Comment by everyx** [comment]
@reaCodes https://github.com/everyx/shadowsocks-csharp 也可以参考我修改的版本 README 中提供的一个 PAC 自定义的说明，比较简短，应该一看就懂
