### ISSUE TITLE
win7 64位系统，启动shadowsocks后，无法使用pac模式，默认全局模式

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-windows#428]
![360 -6788133](https://cloud.githubusercontent.com/assets/10991795/12537274/fab615e4-c2f5-11e5-87b4-738f91814e7d.jpg)
![default](https://cloud.githubusercontent.com/assets/10991795/12537275/fabe89a4-c2f5-11e5-8fac-ad7912f61cf6.jpg)
以上，图一为360极速浏览器，开启ss后默认全局
图二，开启了pac（尝试过本地和在线），但是没有奏效，在别人的电脑里是会有个pac地址的

之前出现过无法修改注册表问题，提交过issues，已通过修改注册表修复，不知到是不是这个问题https://github.com/shadowsocks/shadowsocks-windows/issues/253

**Comment by renziyao** [comment]
我也没法用。可能是PAC文件的问题。我用shadowsocks2.5.7下载的PAC放到shadowsocks2.5.8上可以使用。

**Comment by chenshaoju** [comment]
图二你应该设置为HTTP代理的端口。而且图二也只是手动配置代理，并不是PAC。

**Comment by Aniark** [comment]
@chenshaoju 这是启动ss后的默认设置

**Comment by renziyao** [comment]
@Aniark 系统代理模式->PAC模式

**Comment by chenshaoju** [comment]
应该是这样的：
![screenshot](https://cloud.githubusercontent.com/assets/515763/12999047/c749d026-d185-11e5-9acd-378dff5894eb.png)

请尝试一下这个版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/2c9wh09tealdsyaa/artifacts

**Comment by renziyao** [comment]
PAC不能完全兼容所有浏览器

**Comment by Aniark** [comment]
@chenshaoju 解决pac问题 

但是ss被限速严重，同样是广西电信，在家里能跑满4m带宽，这里却只有几十k

**Comment by renziyao** [comment]
@Aniark 不一定吧。ss开源的

**Comment by Aniark** [comment]
@renziyao 并非 @chenshaoju 提供的ss有问题，原版也是非常慢

**Comment by chenshaoju** [comment]
关于PAC的问题，请试一下这个：
https://github.com/shadowsocks/shadowsocks-windows/issues/439#issuecomment-183404206

**Comment by Aniark** [comment]
@chenshaoju 啊，使用http://www.speedtest.net/测试了网速，只有1m
使用http://ah.189.cn/support/speed/测试网速，有22m
广西电信
用ss卡成狗
为何会有这种现象？

**Comment by chenshaoju** [comment]
是两个测速网站都翻墙的情况吗？

**Comment by Aniark** [comment]
@chenshaoju 不是，是直连。如果翻墙的话更慢

**Comment by chenshaoju** [comment]
这个可能是你当地运营商的限制。

**Comment by YiFenZ** [comment]
问题0：我是用英文还是中文？开发者看中文么？
1.win7 64  2.5.8版本  不打开系统代理，自动就启动了全局代理模式。系统代理没有打勾，灰色的，也可以正常使用
2.切换到PAC，还是全局模式。无论什么网站都走ss。

**Comment by GangZhuo** [comment]
@YiFenZ Shadowsocks通过修改注册表的方式来设置代理选项。代理模式有两种，一种是全局代理，另一种是 PAC，这两种模式的切换都是通过修改注册表来实现的。
系统代理切换无效或者全局和PAC模式切换无效的话，应该是Shadowsocks未能正常修改注册表，一般是没有权限导致的，请检查Shadowsocks的日志。

**Comment by dfxyz** [comment]
最近重装了Win7，发现这个无法切换代理模式的问题
把该死的IE升级到11之后就解决了

**Comment by yh371174229** [comment]
这个帖子真香，我的pac好像好了
![image](https://user-images.githubusercontent.com/5948456/71889059-503b7100-317c-11ea-8fec-9b3fc81e790e.png)
