### ISSUE TITLE
Why Privoxy?

### ISSUE THREAD

**Issue by dci39384** [shadowsocks/shadowsocks-windows#429]
Hi guys.

I just wanted to ask what made you decide to use Privoxy instead of the old method?

I'm currently using an old version, just want to make sure there's any benefits in upgrading to the version with Privoxy.

Thank you

**Comment by GangZhuo** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/249

**Comment by dci39384** [comment]
Thank you. The new version for Privoxy is out, any plans on adding it ?
