### ISSUE TITLE
Multiple instances causes problem for system proxy.

### ISSUE THREAD

**Issue by RadarNyan** [shadowsocks/shadowsocks-windows#430]
In short: System proxy always goes through the port of the last instance, regardless if it has the "system proxy" option checked.

Say I have two instances running, ShadowsocksA at port 1081 as the main proxy ("system proxy" option checked with my custom pac) and ShadowsocksB at port 1082 as the backup proxy ("system proxy" uncheced)

Normally, I'll run ShadowsocksB first, then ShadowsocksA. Everything works fine, system proxy goes through port 1081 and I can use port 1082 to backup proxy server, however if I restart or switch server for ShadowsocksB ("system proxy" unchecked), my system proxy will go through port 1082 until I switch proxy / uncheck-and-check "system proxy" for ShadowscocksA or restart ShadowsocksA.

Strangely, If I check the pac settings from both IE settings and Registry after system proxy goes through port 1082, it doesn't change at all - still points to port 1081 (```http://127.0.0.1:1081/pac?t=201601301403299604```) and the contents stays unchanged (showing port 1081). If I use other program, say SwitchOmega extension for chrome to enforce using port 1081, I can confirm it is connected to proxy server A not B.

Is this a bug or by-design? If so, how can I make my system proxy always goes through the port 1081 - the instance with "system proxy" option checked (ShadowsocksA)?

**Comment by RadarNyan** [comment]
Ok, the problem is caused by ss_privoxy always forward-socks5 to the last reloaded instance of shadowsocks regardless if the instance has "system proxy" option enabled. Currently I got a workaround by editing the privoxy.conf of ShadowsocksB to forward to port 1081 and make it read only.

**Comment by celeron533** [comment]
I think SS was originally designed for single instance. Although nowadays users are able to launch multiple instances from separated folders, the _system proxy_ and _provixy_ still unable to handle this scenario.
BTW, if you mostly want to use SS for browsing webpages, you could disable all system proxy settings,  install Chrome with an extension called [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega#chromium-extension) (also hosted on GitHub) to manage the Chrome's own proxy settings.

Note:
* SwitchyOmega only manage the proxy settings in __Chrome scope__, the system proxy (including IE, desktop, other internet apps such as IDM) are not affected by the change.
* SwitchyOmega has a great feature that you could set your own proxy rules to decide which host should be accessed via SS.
![image](https://cloud.githubusercontent.com/assets/3608762/17462919/32e25918-5cee-11e6-9ef5-8e7007460679.png)

**Comment by wongsyrone** [comment]
According to [existing code](https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/PolipoRunner.cs#L47-L51), Shadowsocks will find out all processes called "ss_privoxy.exe" and killed them, that's why we have only one Privoxy instance.

In my opinion, it is painful to handle multiple external programs. I prefer to keep it as-is. If you can implement this, please send a PR.

**Comment by wongsyrone** [comment]
Added via #665, still have some issues to be solved
