### ISSUE TITLE
自己尝试了一下编辑出错了

### ISSUE THREAD

**Issue by Tourin** [shadowsocks/shadowsocks-windows#431]
![20160201112031](https://cloud.githubusercontent.com/assets/6489673/12708016/e5226260-c8d5-11e5-8e80-9c135ec7f765.png)

**Comment by lixingcong** [comment]
干嘛自己编译，作者项目的
[Appveyor](https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/ygvxp7wl35uj9ejn)
右侧的ARTIFACTS可以下载exe

**Comment by Tourin** [comment]
@lixingcong 是想自己fork了改改学习学习的。

**Comment by wenxiao** [comment]
不太懂msbuild，不过vs直接打开sln应该可以正常使用？不知道是不是build的路径没有配置或者不对什么的？@Tourin

**Comment by Tourin** [comment]
我下载release中2.5.8的source编译倒是没问题，也算解决了。
