### ISSUE TITLE
win 10无法正常使用ss 已卸载迅雷

### ISSUE THREAD

**Issue by ans4ever** [shadowsocks/shadowsocks-windows#432]
在 Shadowsocks.Controller.Handler.CreateRemote()
   在 Shadowsocks.Controller.Handler.StartConnect()
[2016-02-01 14:16:36] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   在 System.Security.Cryptography.MD5.Create()
   在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   在 Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   在 Shadowsocks.Encryption.PolarSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.Handler.CreateRemote()
   在 Shadowsocks.Controller.Handler.StartConnect()
[2016-02-01 14:16:38] Shadowsocks started

求各大神帮忙~

**Comment by chenshaoju** [comment]
你好，请试一下这个版本： https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/ygvxp7wl35uj9ejn/artifacts

**Comment by ans4ever** [comment]
@chenshaoju 还是不行
以下为日记的一部分
[2016-02-01 14:29:45] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2016-02-01 14:29:45] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

以下为浏览器显示
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by chenshaoju** [comment]
0x80004005 错误，试一下，右击开始菜单，选择命令提示符（管理员），然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
三条命令都运行完毕后，重新启动计算机再试。

**Comment by ans4ever** [comment]
@chenshaoju IT WORKS 谢谢 谢谢 非常感谢

**Comment by liaoran** [comment]
运行那三个命令后，如果使用其他的网络加速器，再次使用时还会报上述错误，请作者进一步解决3.0版本在win10下出现的指针调用问题

**Comment by missqso** [comment]
@chenshaoju 我按这个方式操作并且重启之后，就好了。谢谢。请问这个有可能是什么原因造成的呢？
