### ISSUE TITLE
键盘快捷键

### ISSUE THREAD

**Issue by smilinger** [shadowsocks/shadowsocks-windows#433]
提个建议，能否加上快捷键支持。
比如切换系统代理，全局模式和PAC模式，或者更换服务器。

**Comment by NanaLich** [comment]
好想法，不过弄起来会比较耗时间

**Comment by GangZhuo** [comment]
这些操作都不是经常使用的，我认为没有必要添加快捷键。

**Comment by hellodigua** [comment]
真是可惜啊，因为gfwlist的不全面，我也经常有切换全局模式和PAC模式的需求

**Comment by yihuaxiang** [comment]
经常遇到需要切换自动模式和全局模式，😔

**Comment by miaogen123** [comment]
我也需要啊，经常需要切换的人加1
i need too, this is a necessary part of my daily use.

**Comment by chenshaoju** [comment]
你可以右击任务栏托盘区的纸飞机图标，选择编辑快捷键来设定：
![image](https://user-images.githubusercontent.com/515763/38796969-afb4310a-418f-11e8-8094-33f6e9162737.png)

每次启动后必须手动设置一次，这是为了暂时解决热键冲突的问题。

**Comment by miaogen123** [comment]
**超级感谢**
之前试这个的时候，不知道为什么不管用，刚又试了一下，好使了！
非常感谢 @chenshaoju
