### ISSUE TITLE
PAC失效

### ISSUE THREAD

**Issue by renziyao** [shadowsocks/shadowsocks-windows#439]
用PAC模式速度变得非常慢，而且总是会掉线，打开全局模式可以正常连接，没有问题。自从升级到了2.5.8就出现了这个问题
[2016-02-06 21:09:27] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)

**Comment by renziyao** [comment]
应该是firefox更新到44所导致的，望开发者改进

**Comment by chenshaoju** [comment]
该问题及有可能是由于你的服务端速度太慢引起的，请尝试Ping你的服务器IP，看看丢包和延迟。

**Comment by renziyao** [comment]
时间=184ms TTL=52
只要开了全局代理就不会出现这个问题。
IE上使用PAC正常，firefox上无法使用PAC，更新firefox之前一直可以正常使用PAC

**Comment by chenshaoju** [comment]
你可以在 https://ftp.mozilla.org/pub/firefox/releases/ 找到所有版本的Firefox，可以尝试一下哪个版本的Firefox没有问题，以便确认到底是Shadowsocks的问题，或系统问题或Shadowsocks的问题。

**Comment by renziyao** [comment]
我已经回滚到了firefox43，但是依然无法解决PAC无法使用的问题，希望能提供解决方案。（现在依然是IE完全正常，firefox只能使用全局代理，我firefox代理设置为使用系统代理）

**Comment by chenshaoju** [comment]
我刚看了一下我用的Firefox 42.0 是没有问题的，一切正常，我稍后升级到 43.0.1试试。如果你很着急，可以先退回 42.0 看看能否解决。

![screenshot](https://cloud.githubusercontent.com/assets/515763/12921788/b8cb29d0-cf89-11e5-9c8e-32d3484768d5.png)

**Comment by renziyao** [comment]
和你的配置是一样的，但是回滚了firefox44的前几个版本都不行。还有什么能影响PAC的？

**Comment by renziyao** [comment]
莫名其妙的解决了

**Comment by renziyao** [comment]
发现shadowsocks2.5.7的PAC文件可以使用，2.5.8的PAC文件无法使用。

**Comment by renziyao** [comment]
已解决，部分PAC文件无法兼容firefox 64位，有的甚至firefox 32位都无法兼容，希望解决。

**Comment by everyx** [comment]
现在已经支持自定义 PAC 文件，可以自己找一个 PAC 文件用着

**Comment by chenshaoju** [comment]
请尝试一下这个PAC文件：
https://gist.github.com/chenshaoju/52c7555acc65ec98423f
仅能保证Google等服务访问。

**Comment by renziyao** [comment]
@everyx 我现在就在用自己找的，旧版本ss的pac拷过来用就行。但是就是默认的PAC好多浏览器不支持，用着不爽。

**Comment by renziyao** [comment]
@chenshaoju 这个可以用，我就是想知道为啥一个PAC能不兼容firefox

**Comment by chenshaoju** [comment]
Shadowsocks的PAC是基于GFWList，请与GFWList联系。 https://github.com/gfwlist/gfwlist

**Comment by renziyao** [comment]
好的

**Comment by happmaoo** [comment]
![image 1](https://cloud.githubusercontent.com/assets/3744636/13142722/0b0cdb5c-d67a-11e5-81ea-0d006775f0ae.png)
设置成这样就好了！

**Comment by GangZhuo** [comment]
这应该是Firefox 的Bug，当PAC文件中规则数量很多的时候，Firefox无法使用PAC，此时可以让Firefox使用PAC文件来解决。
![pac](https://cloud.githubusercontent.com/assets/1397462/13276205/d7c38ff6-da8a-11e5-8e1c-abf9e67de998.jpg)

**Comment by zzzfinal** [comment]
感谢。搜狗也遇到了类似的问题，原因也是pac文件出现了错误，选择从gfwlist更新本地pac解决了。

**Comment by xeonchen** [comment]
我想要从 Firefox 这边来看这个问题，但是我不知道如何配置 shadowsocks，请问是否有人可以帮忙呢？

**Comment by yfdyh000** [comment]
@xeonchen 启动后配置为 http://127.0.0.1:1080/pac 应该就可以。遇到什么问题吗？

**Comment by xeonchen** [comment]
@yfdyh000 我目前使用是没有问题的

Windows 10 64-bit
Firefox 45.0.2, 48.0a1
Shadowsocks 3.0

所以这个问题还存在吗？

**Comment by yfdyh000** [comment]
@xeonchen https://github.com/breakwa11/shadowsocks-csharp/releases 的版本仍有这个问题。这里的版本好像没这个问题了，pac.txt有一定差别。

**Comment by xeonchen** [comment]
@yfdyh000 我使用了 https://github.com/breakwa11/shadowsocks-csharp/releases/tag/3.7.4.1 仍然无法重现问题，是否有标准步骤呢？

**Comment by xeonchen** [comment]
这个问题目前在 Firefox 49 应该已经修正了，请使用 2016-05-04 之后的版本测试。

**Comment by gggin** [comment]
thunderbird 也有同样的问题， 最新版已经解决了

**Comment by xeonchen** [comment]
@gggin 请问你指的是 Thunderbird 的 nightly 已经没有这个问题了吗？方便的话可以试试 Firefox 吗？

**Comment by chenshaoju** [comment]
@xeonchen 你好，我测试了：

firefox-49.0a1.en-US.win32.installer.exe	36M	04-May-2016 13:56

版本的Firefox，没有遇到问题。

**Comment by gggin** [comment]
![image](https://cloud.githubusercontent.com/assets/3293064/15042316/52780a40-12f5-11e6-98ea-40cc6fb64196.png)

使用全局pac+系统代理
之前的版本是不好使的. firefox显然已经有人测试过了

**Comment by GangZhuo** [comment]
最新版 Firefox 修复了这个问题。

**Comment by foyangyu** [comment]
最新版Firefox 现在又出现了这个问题，PAC不可用

<img width="694" alt="firefox updates" src="https://user-images.githubusercontent.com/24937594/36709284-07290c34-1bb2-11e8-8c87-0fc93fcb2c5b.png">


<img width="284" alt="shadowsocksx-ng-r" src="https://user-images.githubusercontent.com/24937594/36709380-89398d84-1bb2-11e8-8062-aa673257970d.png">
