### ISSUE TITLE
Using Caseless.Fody causes the program unable to run

### ISSUE THREAD

**Issue by NanaLich** [shadowsocks/shadowsocks-windows#442]
raises FileLoadException, it seems that AppVeyor may have problem dealing with Caseless.Fody 0.4

**Comment by NanaLich** [comment]
until i figure out what's really happened, please use this as temp solution:
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.101/job/5k4oyaefqh1u659c/artifacts

**Comment by NanaLich** [comment]
@chenshaoju check this

**Comment by NanaLich** [comment]
hmmmm
it seems to be a bug from Caseless.Fody, let me check

**Comment by NanaLich** [comment]
fixed by #438 
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.102/job/q27q4upqv80qx3oc/artifacts

**Comment by Licshee** [comment]
reported Fody/Caseless#5
