### ISSUE TITLE
谁来更新下mac的版本，好多新的加密方式不支持

### ISSUE THREAD

**Issue by lioliy** [shadowsocks/shadowsocks-windows#448]

**Comment by chenshaoju** [comment]
我没有Mac，但是我记得Mac有Python的运行环境，你可以试着使用Python的Mac：
https://pypi.python.org/pypi/shadowsocks

**Comment by matsuz** [comment]
mac可用libev版

**Comment by lioliy** [comment]
嗯知道libev版，但全局代理不太好设置
