### ISSUE TITLE
无法使用,500错误

### ISSUE THREAD

**Issue by RenneXV** [shadowsocks/shadowsocks-windows#449]
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

运行日志
[2016-02-21 02:35:06] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   在 System.Security.Cryptography.MD5.Create()
   在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   在 Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   在 Shadowsocks.Encryption.PolarSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.Handler.CreateRemote()
   在 Shadowsocks.Controller.Handler.StartConnect()
[2016-02-21 02:39:37] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   在 System.Security.Cryptography.MD5.Create()
   在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   在 Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   在 Shadowsocks.Encryption.PolarSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.Handler.CreateRemote()
   在 Shadowsocks.Controller.Handler.StartConnect()
[2016-02-21 02:39:39] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   在 System.Security.Cryptography.MD5.Create()
   在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   在 Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   在 Shadowsocks.Encryption.PolarSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.Handler.CreateRemote()
   在 Shadowsocks.Controller.Handler.StartConnect()

**Comment by chenshaoju** [comment]
请尝试该版本：https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.105/job/2c9wh09tealdsyaa/artifacts

**Comment by RenneXV** [comment]
有效.感谢回复.

**Comment by soulomoon** [comment]
使用这个版本 在win7下出现，
shadowsocks 已停止工作

**Comment by soulomoon** [comment]
安装.net 4.5 后问题解决
