### ISSUE TITLE
win10 64位中启动显示无法修改注册表

### ISSUE THREAD

**Issue by wowudi** [shadowsocks/shadowsocks-windows#451]
日志：
[2016-02-22 02:01:29] Shadowsocks started
[2016-02-22 02:01:29] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Controller.SystemProxy.IEAutoDetectProxy(Boolean set)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
已经给注册表项
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Connections]赋予了everyone完全控制权限

**Comment by chenshaoju** [comment]
右击 Shadowsocks.exe ，点击属性，然后点击“解除锁定”按钮。

**Comment by wowudi** [comment]
@chenshaoju 属性里没有解除锁定按钮啊

**Comment by chenshaoju** [comment]
那么可能是某些安全软件锁定了浏览器的代理。

**Comment by luhaining** [comment]
自测并证实，是端口占用的问题。
常用的软件如[迅雷极速版]，会占用1080端口，建议安装迅雷之前，先启动Shadowsocks再安装就没事了。

**Comment by stuxnet** [comment]
@luhaining 没必要重装了吧，直接把ss本地代理端口换了就是了

**Comment by wowudi** [comment]
@stuxnet 试了一下，改端口还是弹出无法修改注册表

**Comment by luhaining** [comment]
@stuxnet 是哦，我怎么没想到[斜眼笑]

**Comment by wongsyrone** [comment]
看起来问题已经解决了。
