### ISSUE TITLE
Shadowsocks 错误：系统调用失败

### ISSUE THREAD

**Issue by Ansonyi** [shadowsocks/shadowsocks-windows#452]
[2016-02-23 23:11:54] System.Net.Sockets.SocketException (0x80004005): 系统调用失败。
   在 System.Net.Sockets.Socket.InitializeSockets()
   在 System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections()
   在 System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveTcpListeners()
   在 Shadowsocks.Controller.PolipoRunner.GetFreePort()
[2016-02-23 23:11:54] System.Net.Sockets.SocketException (0x80004005): 系统调用失败。
   在 System.Net.Sockets.Socket.InitializeSockets()
   在 System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections()
   在 System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveTcpListeners()
   在 Shadowsocks.Controller.Listener.CheckIfPortInUse(Int32 port)
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
————————————
[2016-02-23 23:14:58] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.Configuration.ConfigurationErrorsException: 创建在“system.net/defaultProxy”配置节中指定的 Web 代理时出错。 ---> System.Net.Sockets.SocketException: 系统调用失败。
   在 System.Net.Sockets.Socket.InitializeSockets()
   在 System.Net.NetworkAddressChangePolled..ctor()
   在 System.Net.AutoWebProxyScriptEngine.AutoDetector.Initialize()
   在 System.Net.AutoWebProxyScriptEngine.AutoDetector.get_CurrentAutoDetector()
   在 System.Net.AutoWebProxyScriptEngine..ctor(WebProxy proxy, Boolean useRegistry)
   在 System.Net.WebProxy.UnsafeUpdateFromRegistry()
   在 System.Net.WebProxy..ctor(Boolean enableAutoproxy)
   在 System.Net.Configuration.DefaultProxySectionInternal..ctor(DefaultProxySection section)
   在 System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   在 System.Net.WebRequest.get_InternalDefaultWebProxy()
   在 System.Net.HttpWebRequest..ctor(Uri uri, ServicePoint servicePoint)
   在 System.Net.HttpRequestCreator.Create(Uri Uri)
   在 System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   在 System.Net.WebRequest.Create(Uri requestUri)
   在 System.Net.WebClient.GetWebRequest(Uri address)
   在 System.Net.WebClient.DownloadStringAsync(Uri address, Object userToken)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
![截图](https://ooo.0o0.ooo/2016/02/23/56cc7aed93b00.png)

补充：windows10 64位

**Comment by chenshaoju** [comment]
右击开始菜单，选择以命令提示符（管理员），然后输入：
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
三条命令一行一个，回车结束，都执行完毕后，重启计算机。
注意，IP会变回自动分配，如果是手动指定，记得重新指定一下。

**Comment by Ansonyi** [comment]
谢谢 @chenshaoju 
万分感谢。
 ————————
这是我自己的电脑的问题。
 ——————
在安全模式下使用 `netsh winsock reset catalog`命令解决了。
