### ISSUE TITLE
Using http proxy without any 3rd party tools?

### ISSUE THREAD

**Issue by dci39384** [shadowsocks/shadowsocks-windows#453]
Hi guys,

Is that possible to implement http proxy somehow? 

I tried to use socks5 via PAC file in IE and Edge on Win10 but can't get them to work.., any ideas?

Thank you

**Comment by happmaoo** [comment]
set the auto proxy url:http://127.0.0.1:1080/pac
then make sure you select mode: global

**Comment by dci39384** [comment]
Thank you but global mod requires Privoxy, i just don't want to use any 3rd party apps.

**Comment by GangZhuo** [comment]
No Plan

**Comment by xbb123** [comment]
I don't see any problem using privoxy since it's a open source project. First version was released about 15 years ago, so it is a stable and safe implementation. Again, if you have doubts, you may review the source code and compile the executable yourself.
