### ISSUE TITLE
升级3.0后不能用了，换回去又可以

### ISSUE THREAD

**Issue by zhou92** [shadowsocks/shadowsocks-windows#459]
[2016-03-02 13:12:15] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

**Comment by GangZhuo** [comment]
移除 gui-config.json 文件后，重新添加服务器试试

**Comment by zhou92** [comment]
删除原来所有文件重新添加服务器以后仍然存在问题
[2016-03-02 13:38:22] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
请尝试：
https://github.com/shadowsocks/shadowsocks-windows/issues/247#issuecomment-131392491

如果你使用迅雷，请升级到最新版本。

**Comment by loveproe** [comment]
同样的问题。
[2016-03-02 14:33:12] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()

**Comment by chenshaoju** [comment]
@loveproe 请尝试楼上的方法。

**Comment by cpjp** [comment]
我这里更新后没问题

ss的任何更新，都给人一种诈尸的感觉

**Comment by GangZhuo** [comment]
一个同样的问题 https://github.com/shadowsocks/shadowsocks-windows/issues/432#issuecomment-177803390

**Comment by loveproe** [comment]
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
重启有效。
这真的是个奇怪的问题，好像只有用win10才有吗？第一次遇到。

**Comment by chenshaoju** [comment]
@loveproe 该问题是由于某些网络下载软件、加速软件、第三方VPN或类似的软件修改了Windows的TCP/IP协议和（或）Winsocks导致的。这三个命令会恢复Windows的网络设置到初始值。

**Comment by loveproe** [comment]
@chenshaoju 我有点奇怪的是为何之前旧版本或者是shadowsockR和sscap之类改版都可以兼容，只有这个版本要求那么严格必须全部参数默认。。。不过，还是很开心，那么久有更新了

**Comment by wtlusvm** [comment]
Windows 7 更新3.0后一打开就出错：
  问题事件名称:CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	3.0.0.0
  问题签名 03:	56d65064
  问题签名 04:	Shadowsocks
  问题签名 05:	3.0.0.0
  问题签名 06:	56d65064
  问题签名 07:	1a7
  问题签名 08:	0
  问题签名 09:	System.IO.FileLoadException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789
使用重置命令也不可以。然而在Windows Server 2012 R2 Standard上却可以正常使用。两者除了系统版本区别外，就是.NET Framework版本区别了，7上是4.0，Server 上是4.5+4.6(装了VS2015.1)，怀疑是.NET Framework版本问题？

**Comment by wtlusvm** [comment]
是的，我遇到的确实是版本问题，安装.NET Framework **4.5**后问题解决。

**Comment by seers** [comment]
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
重启有效。

**Comment by cool5** [comment]
楼主你编译的版本怎么提交到自动更新的？ 所有客户端都提升更新到这个版本？

**Comment by zhou92** [comment]
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
亲测有效，我没有用迅雷用的是EagleGet

**Comment by gengjiawen** [comment]
win10, 我有遇到这个问题了

**Comment by gbaoye** [comment]
me tooooooooooooooooooooooooooooooo
看这架势，你是打不算更新了吗

**Comment by GangZhuo** [comment]
到 https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe 下载最新版，帮忙测试一下是否修好了这个错误

**Comment by linkdesu** [comment]
悄悄来发个感谢~~win10 64位一切安好~~

**Comment by PatrickHuang888** [comment]
win10 遇到同样问题

用以下命令重置
netsh interface ipv4 reset
 netsh interface ipv6 reset
 netsh winsock reset
似乎前面两个命令无效
重启可以用了

**Comment by wongz** [comment]
@GangZhuo 最新版正常，不会运行就出错了

**Comment by zhuyingteng** [comment]
重启有效！不知道久了会不会又这样

**Comment by ergouge** [comment]
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
重启有效。(win10,64bit，升级系统后出现的问题)
