### ISSUE TITLE
ipv6地址显示不规范

### ISSUE THREAD

**Issue by AnyoeDove** [shadowsocks/shadowsocks-windows#465]
如果服务器填的ipv6地址，右键菜单显示应该是 [1:2:3:4:5:6:7:8]:9000 ，即 [ipv6地址]:端口 的格式。
而ss直接显示成 1:2:3:4:5:6:7:8:9000
虽然是个小问题，但是希望修正。

**Comment by Mygod** [comment]
+1 in ss urls.

**Comment by AnyoeDove** [comment]
@Mygod ss urls is ss://encrypt_method:password@ip:port, so the number in the end portion is the proxy port no matter what. 
i think that the ss url shuold be simple, but the format showed in the shadowsocks should be correct。

**Comment by Mygod** [comment]
Correct. However it's good to stay uniform with other URLs.

**Comment by wongsyrone** [comment]
This should be fixed in https://github.com/shadowsocks/shadowsocks-windows/pull/647, please test.
Download from CI build or build it yourself.

**Comment by AnyoeDove** [comment]
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.173
CI Build error...
![sp160808_181931](https://cloud.githubusercontent.com/assets/10519576/17476875/cd2bf9b0-5d94-11e6-8ba3-81df77946b66.png)

**Comment by wongsyrone** [comment]
加了一个[配置文件项](https://github.com/wongsyrone/shadowsocks-windows/commit/fb3fcdb90d68ad6e8c582ecb5d70c26103017fe4)，旧配置文件因为没有这个可能空引用，尝试删掉现有的重新配置一下。

**Comment by AnyoeDove** [comment]
v6地址显示正确了 感谢
![sp160808_184735](https://cloud.githubusercontent.com/assets/10519576/17477574/9ea0173a-5d98-11e6-8dbc-32504dc08604.png)

**Comment by wongsyrone** [comment]
Okay, I will merge this into master branch.
