### ISSUE TITLE
关于3.0不能用的问题分析

### ISSUE THREAD

**Issue by cnccav** [shadowsocks/shadowsocks-windows#466]
我测试了添加两个一样的服务器IP和端口，密码不一样，然后点“确定”程序就死了，再次打开也不行了，
在此之前的版本这样测试是没问题的。
我猜测程序是在读服务器时遇到相同的服务器IP和端口时出问题的。

**Comment by chenshaoju** [comment]
该问题已经确认，并且可以复现：

>描述
错误的应用程序路径:	D:\Software\Shadowsocks\Shadowsocks.exe

>问题签名
问题事件名称:	CLR20r3
问题签名 01:	Shadowsocks.exe
问题签名 02:	3.0.0.0
问题签名 03:	56d65064
问题签名 04:	mscorlib
问题签名 05:	4.6.1055.0
问题签名 06:	563c0eac
问题签名 07:	321
问题签名 08:	10
问题签名 09:	System.ArgumentException
OS 版本:	6.1.7601.2.1.0.768.3
区域设置 ID:	2052
其他信息 1:	0a9e
其他信息 2:	0a9e372d3b4ad19135b953a78882e789
其他信息 3:	0a9e
其他信息 4:	0a9e372d3b4ad19135b953a78882e789


此问题正在处理中。

**Comment by hitrust** [comment]
在 Shadowsocks.Controller.PolipoRunner..cctor()
[2016-03-04 21:36:46] Shadowsocks started
[2016-03-04 21:37:17] 128.xxx.xxx.xxx:1433 timed out
[2016-03-04 21:42:34] Shadowsocks started
[2016-03-04 21:43:45] System.IO.IOException: 文件“C:\Documents and Settings\Administrator\Local Settings\Temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()
[2016-03-04 21:43:45] Shadowsocks started
[2016-03-04 21:45:51] System.IO.IOException: 文件“C:\Documents and Settings\Administrator\Local Settings\Temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()

**Comment by GangZhuo** [comment]
@hitrust 如果需要多开的话，使用 portable-mode ( https://github.com/shadowsocks/shadowsocks-windows/tree/master#portable-mode )。如果不是多开的话，打开任务管理器，强制结束 ss_privoxy.exe 后再打开 shadowsocks。

PS: 如果不影响使用的话，可以无视这个错误。

**Comment by GangZhuo** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/4325b7f6f9d706f8893feb32efbc9c36a60876d1
