### ISSUE TITLE
3.0 rising报毒

### ISSUE THREAD

**Issue by hetykai** [shadowsocks/shadowsocks-windows#468]
https://www.virustotal.com/zh-cn/file/7c6503452fed1640edb7464a9125bbadcf9790b6a15214aa4b114312f9282f87/analysis/

**Comment by chenshaoju** [comment]
该问题已知，属于瑞星误报，已经提交瑞星进行复审。

引起该问题的原因是 libsscrypto.dll 文件：
https://www.virustotal.com/en/file/eb65867b5871a123e8db88669da1a4825e82691a257fac184c72a203cfe02bff/analysis/1456884107/

**Comment by cool5** [comment]
这类软件最后不要提交给瑞星，瑞星是金盾工程的合作伙伴的

**Comment by chenshaoju** [comment]
截至2016-04-06，已经无杀毒软件对 libsscrypto.dll 报毒：
https://www.virustotal.com/en/file/eb65867b5871a123e8db88669da1a4825e82691a257fac184c72a203cfe02bff/analysis/
