### ISSUE TITLE
3.0自动退出

### ISSUE THREAD

**Issue by NiaNingXue** [shadowsocks/shadowsocks-windows#469]
用着用着进程死掉了，需要重新启动。环境win10.

**Comment by chenshaoju** [comment]
“死掉了”是什么表现？弹出停止工作还是没有反应？

**Comment by NiaNingXue** [comment]
自己消失了，右下角图标没有了，需要重新开启

**Comment by chenshaoju** [comment]
请尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/sec22spsfxbr64ef/artifacts

**Comment by NiaNingXue** [comment]
ok，我试下

**Comment by mapleshadow** [comment]
@chenshaoju 哥们，你的版本也闪退。打开就自动没了。我是win10 x64

**Comment by sdvdxl** [comment]
我的也闪退，win10 x64，打开后，过段时间后自动退出了

**Comment by GangZhuo** [comment]
能按照 https://github.com/shadowsocks/shadowsocks-windows/issues/461#issuecomment-191320256 安装更新试试吗？

**Comment by reaCodes** [comment]
我也遇到了进程被杀死的情况了，好几次了

**Comment by GangZhuo** [comment]
统计配置中先设置为关闭吧，等修复。

**Comment by andronoob** [comment]
2.5.6好像还是正常的，后来就开始有这个问题了，似乎是连不上服务器的时候更容易这样。也不知道有没有办法找到原因？

**Comment by hitrust** [comment]
statistics-config.json
"StatisticsEnabled": false
问题解决

**Comment by GangZhuo** [comment]
See https://github.com/shadowsocks/shadowsocks-windows/issues/459
