### ISSUE TITLE
清空的日志下次查看还会有

### ISSUE THREAD

**Issue by NiaNingXue** [shadowsocks/shadowsocks-windows#470]
如题

**Comment by chenshaoju** [comment]
该问题已经确认。

临时解决办法：手动删掉 shadowsocks.log 文件。

**Comment by GangZhuo** [comment]
设计就是这样的，只是清空了日志窗口中的日志。如果要完全删除，则像 @chenshaoju 说的，需要手动删除 shadowsocks.log 文件。
