### ISSUE TITLE
sandboxie 沙盒内 运行卡死，原因未知 3.0 版本

### ISSUE THREAD

**Issue by catcat520** [shadowsocks/shadowsocks-windows#471]
sandboxie 沙盒内 运行卡死，原因未知 3.0 版本
原版的 2.5.6 也卡死
表现为一打开就卡死，什么也设置不了
能否解决这个问题呢

**Comment by mikicomo** [comment]
在沙盒内运行SS...嗯...是有什么特殊的需求么....？

**Comment by catcat520** [comment]
珍爱沙盒 远离喝茶

**Comment by devillaws** [comment]
请问客户端已经支持UDP转发了吧，默认不需要设置的

**Comment by chenshaoju** [comment]
可能和注册表权限有关。

**Comment by catcat520** [comment]
是可能跟注册表有关系，没有跟踪，QT5 版本的是可以正常在沙盒运行的

**Comment by wongsyrone** [comment]
Then use qt5 version.

**Comment by celeron533** [comment]
fixed in release https://github.com/shadowsocks/shadowsocks-windows/releases/tag/3.4.2.1
