### ISSUE TITLE
运行了最新的3.0程序，发现一个小问题

### ISSUE THREAD

**Issue by King66** [shadowsocks/shadowsocks-windows#472]
在托盘区右键点小飞机，然后我按CTRL+ALT+A想截图来着，然后因为ss的菜单消失了就按了esc放弃了截图。之后发现任务栏有了小飞机的程序，如果将鼠标移到任务栏的飞机上，再移到程序里面的叉号点击，则托盘区的ss小飞机图标也没了。这时如果再次运行ss，会提示已经有ss再运行，这时必须要在任务管理器里结束掉ss的进程，才能重新启动ss。我的系统是win10，不知道其他系统是否也有这个问题。

**Comment by chenshaoju** [comment]
请点击托盘区的三角形符号，展开隐藏的图标。

**Comment by King66** [comment]
有人还会连这个都不懂吗？真逗！你看明白了吗？

**Comment by zzhhbyt1** [comment]
我觉得你说的还是很有道理，我确实应该杜绝装逼，多谢提醒。

**Comment by King66** [comment]
目前最新的QQ8.2体验版版本，已经没有了此bug

**Comment by Jackgqf** [comment]
确实有这个问题
