### ISSUE TITLE
反馈一个bug

### ISSUE THREAD

**Issue by iamsweet** [shadowsocks/shadowsocks-windows#474]
3.0版本的ss，扫描重复的二维码之后会导致ss崩溃，重启ss或者电脑都不能恢复，启动就会报错，只能手动编辑配置文件，删掉重复的服务器文件才能恢复启动。

**Comment by cqhtyi** [comment]
同时，该版本设置开机自动启动后，注册表上的名字为：Shadowsocks_-1813322791
强迫症表示不能忍。。。

**Comment by chenshaoju** [comment]
@iamsweet 的问题类似： https://github.com/shadowsocks/shadowsocks-windows/issues/466 ，可手动清除重复行解决，该问题已经修正，请使用该版本测试： https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/8p40uvv64pvmmgsm/artifacts

@cqhtyi 你可以手动创建快捷方式，拖放到开始菜单的启动里。

**Comment by GangZhuo** [comment]
@cqhtyi 注册表名字加一串数字是在便携模式下，用于区分不同目录下的 shadowsocks的。

@iamsweet Fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/4325b7f6f9d706f8893feb32efbc9c36a60876d1

**Comment by chchuj** [comment]
请问 https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/8p40uvv64pvmmgsm/artifacts
的版本是否支持推送后续版本的更新？

**Comment by chenshaoju** [comment]
@chchuj 理论上可以。

**Comment by GangZhuo** [comment]
@chchuj 支持后续版本的更新。
