### ISSUE TITLE
mac客户端什么时候更新？

### ISSUE THREAD

**Issue by justintseng** [shadowsocks/shadowsocks-windows#475]
mac客户端什么时候更新？

**Comment by chenshaoju** [comment]
你好，这儿是Windows版本的问题反馈，Mac可以尝试使用libev版本：
https://github.com/shadowsocks/shadowsocks-libev

**Comment by everfly** [comment]
@chenshaoju Mac版本的ShadowsocksX那么好用，能不能麻烦你们帮忙继续维护下呢。毕竟用Mac的人群也非常多的吧。。感谢好人

**Comment by chenshaoju** [comment]
我没有Mac……VC的Windows EXE程序不可能直接在Mac上跑……
