### ISSUE TITLE
系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

### ISSUE THREAD

**Issue by gbaoye** [shadowsocks/shadowsocks-windows#476]
Microsoft Windows [版本 10.0.10586]
(c) 2015 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>netsh interface ipv4 reset
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
重新启动计算机来完成此操作。

C:\WINDOWS\system32>netsh interface ipv6 reset
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
重新启动计算机来完成此操作。

C:\WINDOWS\system32>netsh winsock reset

成功地重置 Winsock 目录。
你必须重新启动计算机才能完成重置。

**Comment by gbaoye** [comment]
OK 好了 我的经验是最好重新启动机器输入
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
这三个命令，并保证上诉反馈的信息相同

**Comment by gbaoye** [comment]
另问 支持UDP不？

**Comment by chenshaoju** [comment]
记忆中不支持，你可以试试。

**Comment by GangZhuo** [comment]
请尝试 https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe

**Comment by islercn** [comment]
1.0.128

[2016-03-04 23:17:03] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.StartConnect()


[2016-03-04 23:17:19] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by GangZhuo** [comment]
@islercn 一直出现吗？应该是和你的实时网络环境有关。

**Comment by islercn** [comment]
@GangZhuo 是的，前几天网络比较差，而且只出现过一次，这两天网络很好，还没再遇到

**Comment by yanxijian** [comment]
今晚我也遇到了，在公司还是好的。看来是跟网络环境有关吧。暂时换回2.5.8了。

**Comment by yanxijian** [comment]
[2016-03-07 20:50:19] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by islercn** [comment]
@GangZhuo 昨晚重启后没多久，就又出现一次

[2016-03-07 22:46:27] Shadowsocks started
[2016-03-07 22:46:58] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by xuanzai89757** [comment]
同样的问题，还是换回老版本了

**Comment by feeeei** [comment]
使用了netsh reset之后，还是一样的问题链接不上去...
win10 64位
使用3.0亦或是2.5.8都连接不去...

**Comment by chenshaoju** [comment]
错误提示一样吗？如果一样，你是否安装了迅雷？请尝试升级到最新版本。

如果错误提示不一样，请检查你的服务器IP、加密方式、端口、密码是否正确。

**Comment by feeeei** [comment]
3.0版本
安装了迅雷，尝试卸载之后netsh reset，问题依旧
又安装了新版迅雷，问题依旧
尝试从GFWList更新本地PAC
错误提示
[2016-05-28 13:51:30] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)


服务器配置填写的是正确的，相同配置的mac本子没有问题

**Comment by chenshaoju** [comment]
这个提示真的是因为配置不正确导致的。。。请仔细复查包括IP、端口、密码、加密方式、OTA选项等。
另外，你可以试一下该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/i94vdu9n8mq4q89g/artifacts

**Comment by wongsyrone** [comment]
Please try latest release.

**Comment by raykin** [comment]
3.2 works on wins 10

**Comment by wupengfei1236** [comment]
@feeeei 问题解决了吗？我也遇到相同的情况了

**Comment by posedge123** [comment]
@feeeei 问题解决了么？我也是相同的问题， @wupengfei1236

**Comment by boolyahoo** [comment]
同样的问题，换了服务器后ss连接失败。将一次性验证取消勾选后，重新连接成功；
