### ISSUE TITLE
你们解决不了的问题就直接关闭是吗

### ISSUE THREAD

**Issue by King66** [shadowsocks/shadowsocks-windows#479]
你们解决不了的问题就直接关闭是吗
无语了

**Comment by chenshaoju** [comment]
请描述你的问题，或提供被关闭的地址或问题编号。

**Comment by chenshaoju** [comment]
该问题 https://github.com/shadowsocks/shadowsocks-windows/issues/472 无法在Windows 10上复现。

![unnamed qq screenshot20160305164816](https://cloud.githubusercontent.com/assets/515763/13546738/0c1c8f2c-e2f2-11e5-8127-ccdb02890737.png)

**Comment by Jack-Kingdom** [comment]
1. 这是软件配合的问题，跟SS没多大关系吧。
2. 推荐使用`prt sc`屏幕截图，再用画板进行剪辑。

**Comment by zzhhbyt1** [comment]
没逼着你用。。人家辛辛苦苦开发开源软件给你使用，不要就觉得自己比别人高一等了。软件有问题请礼貌的过来反馈。这里是GitHub，请表现正常点。Ctrl+Alt+A，qq截屏吧。。

**Comment by loarland** [comment]
老兄你当这是客服吗？不尊重作者的话请不要来这里发言

**Comment by King66** [comment]
楼上的两位，你们还知道是开源，我也是无语了，这个bug又没有影响到我的使用，如果不是想让软件更好，想贡献自己的力量，谁跑到这里提bug？
还不尊重作者，您老挑拨离间是一绝啊！

**Comment by King66** [comment]
不过我发现这应该是QQ的原因，不是shadowsocks的原因。我试了一下QQ自己也会出现这种情况。运行了一个另外的c#写的的托盘区程序也出现了这种情况。

**Comment by King66** [comment]
辛辛苦苦提个bug，什么都没反映直接给你关了，下次谁还给你提bug，我说句话还刺激到楼上那两位的玻璃心了，也是无语

**Comment by chenshaoju** [comment]
@King66 这篇文章有点长，但是仍然建议你阅读一下：
http://doc.zengrong.net/smart-questions/cn.html

**Comment by King66** [comment]
呵呵，刚开始怎么回答的

**Comment by GangZhuo** [comment]
@King66  对不起，我的错。此问题是否可以关闭？

**Comment by King66** [comment]
关闭吧...
谢谢你继续维护此程序

**Comment by zzhhbyt1** [comment]
我觉得我说的话还算是中立而平和的，如果您觉得不适请指出。我个人并不适应这种不遵守科学反馈模式的issues，以及“有人还会连这个都不懂吗？真逗！你动点脑子看行吗？”“是吗”“无语了”挑拨离间“等等激进的说辞。本来在局域网里活着就这么难，何苦还要互相为难呢？

**Comment by zzhhbyt1** [comment]
用QQ截图会涉及到alt键，这个键用来在窗口主题和菜单栏菜单间切换焦点。所以你的ss“小飞机”的菜单会没有了。如果你感兴趣真正原生的win截图方法，请查询“print screen”的作用。

**Comment by zzhhbyt1** [comment]
你之前的问题之所以没能得到解决，还是描述的不够确切。你可以选择描述的准确些，或者如果你还能在自己的电脑上重现，选择一些屏幕录制软件记录下来整个过程，这样可以防止因为对系统UI部件的命名不统一导致的误会。

**Comment by zzhhbyt1** [comment]
我希望也愿意相信你是“想让软件更好，想贡献自己的力量”，所以请你努力描述自己的问题，以便于他人重现潜在的bug。“呵呵”、“你不用心，还想让我用心”这样的易被理解为富攻击性、富指责意味的交流方式，不是说不能用，是不要轻率使用。最后一遍，局域网生活已经如此艰难，请不要再互相为难了。

**Comment by King66** [comment]
@zzhhbyt1 还alt切换焦点，别出来丢人现眼了。
你活的艰难，不代表别人活的艰难。
你活的艰难，你可以出来喷，我管不了。
继续喷吧。

**Comment by zzhhbyt1** [comment]
是，你说的对tab切换焦点，alt去选单和组成快捷键。我不多说，反正大家在看。

**Comment by King66** [comment]
@zzhhbyt1 别在秀下限了好吗，都说了这是QQ在win'10上的bug，就算是把QQ截图的快捷键设成其他的，比如说F3，这个bug还是存在。你非要跟切换焦点联系上，显示你的学识渊博吗？还有，只有你知道ctrl+alt+a是QQ截图吗？只有你知道print screen是干嘛的吗？ 没了QQ别人都不会截图了吗？ 别人都是小白，就你是大神是吗？我的重点在说这个吗？
