### ISSUE TITLE
win10安装系统更新后无法使用

### ISSUE THREAD

**Issue by moonmicro** [shadowsocks/shadowsocks-windows#481]
最新3.0及老版本都试过，显示timed out

更新前可用

目前手机仍然可以使用

**Comment by chenshaoju** [comment]
你好，该问题无法复现，请问是安装了那个补丁导致的？你可以在 控制面板->程序->程序和功能->已安装的更新 中查到最近安装过的补丁。

![unnamed qq screenshot20160306130904](https://cloud.githubusercontent.com/assets/515763/13552417/a1ab3764-e39c-11e5-94af-f3af89a7c9c1.png)

**Comment by moonmicro** [comment]
Windows 10 Version 1511 累积更新 (KB3140743)
Windows 10 Version 1511 更新程序 (KB3139907)

**Comment by chenshaoju** [comment]
卸载这两个补丁，是否就正常了？

**Comment by moonmicro** [comment]
系统还原也不行，好奇怪，难道是服务器的问题？但是手机通过wifi能上啊

500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by chenshaoju** [comment]
这样，做一个测试：
你的Shadowsocks是便携模式吗？如果是，先退出Shadowsocks，删除 Shadowsocks.exe 所在目录下的 temp 目录然后再试。
如果不是便携模式，请先退出Shadowsocks，删除 %temp% （按Windows徽标键+R，然后粘贴，并回车）目录里的所有文件，然后再试。

如果仍然不行，删除 Shadowsocks.exe 所在目录的 gui-config.json 文件，然后重新配置服务器信息，并再试。

**Comment by moonmicro** [comment]
是服务器的问题，换了个账号就能上了。但是之前手机能上PC不能上，这服务器也真是醉了
