### ISSUE TITLE
无法访问微博

### ISSUE THREAD

**Issue by KalinaRain** [shadowsocks/shadowsocks-windows#483]
我的电脑无法访问微博，几遍刷新好久也都未必进得去（网速正常），而别人的电脑确实秒进，所以我想知道是不是代理的问题，我在网上搜索了，也都尝试过那些解决方法，但是没用。

**Comment by chenshaoju** [comment]
你好，你用的是什么代理？如果不用代理能打开微博吗？

**Comment by KalinaRain** [comment]
使用的是shadowssocks客户端，从win2.5.8开始就不行了，当时也没在意。要用到微博的时候才发现这个问题。即使退出代理一样不行。

2016-03-06 14:01 GMT+08:00 Chen Shaoju <notifications@github.com>:

**Comment by GangZhuo** [comment]
@KalinaRain 这应该不是 Shadowsocks 的问题，检查你的 HOSTS 文件，或检查你的 DNS。
