### ISSUE TITLE
server recv: Connection reset by peer

### ISSUE THREAD

**Issue by tea1111980** [shadowsocks/shadowsocks-windows#485]
前几天用着蛮好的，就今天出现了 server recv: Connection reset by peer 这个提示的错误。不知道什么原因。
把服务器重启后，只能正常使用几分钟，然后又会出现 上述提示，并且下载速度立马蛮慢，慢到只有几KB 或 0KB 再又10几KB 就这样跳变。

请问是怎么回事？ SS客户端 3.0  服务端 ss-libev-2.4.5

**Comment by chenshaoju** [comment]
请尝试更换服务端的加密方式以及密码，必要请更换端口。

不建议使用默认端口。

**Comment by tea1111980** [comment]
谢谢你的回答！  请问一下，salsa20 和 aes-256-cfb 这两个加密方式哪个更安全 速度更快？

**Comment by chenshaoju** [comment]
具体情况，请参阅知乎： https://www.zhihu.com/question/28252105

**Comment by tea1111980** [comment]
谢谢！
