### ISSUE TITLE
3.0 无法正常使用的可以试试这个方法

### ISSUE THREAD

**Issue by Jarvanh** [shadowsocks/shadowsocks-windows#486]
更新到3.0后出现了这样一个问题，使用代理无法打开任何网站

```
[2016-03-06 23:35:36] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
```

**可以通过重设TCP/IP和Winsocks堆栈解决：**

以管理员身份运行命令提示符（cmd），执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```

参照[#432 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/247#issuecomment-131392491)，感谢 @chenshaoju

**Comment by livc** [comment]
有效，多谢了。

**Comment by zzhhbyt1** [comment]
我发现我的电脑出这样的问题后做这三条命令不用重启，直接在ss里面开启代理再关闭就好了。然而有时重启后又不正常，又需要再做这三条命令才能正常。会和我的电脑里的emule启动项有关系吗？

**Comment by chenshaoju** [comment]
你是不是装了迅雷？如果是，请升级到最新版。 http://yangtai.xunlei.com/?p=10120

**Comment by zzhhbyt1** [comment]
没有安装迅雷，只安装了emule最新的官方beta版。

**Comment by zzhhbyt1** [comment]
白天我再看一下什么被这几条reset掉了，看看可能是哪个条目的问题。晚上宿舍断网了。如果您觉得提供些什么信息会有用请指出，我会尽力。

**Comment by linfengyes** [comment]
`System.Net.Sockets.SocketException (0x80004005): The system detected an invalid pointer address in attempting to use a pointer argument in a call
   at System.Net.Sockets.Socket.get_RemoteEndPoint()
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)`
我发现3.0版本的这个错误和"腾讯游戏平台"的“腾讯游戏云加速下载引擎(旋风Inside)”有关。
关闭腾讯游戏平台并且结束腾讯游戏云加速下载引擎，ss3.0恢复正常。

**Comment by linfengyes** [comment]
@GangZhuo 关于ss和加速器冲突的这类问题，是不是共用某些系统资源导致的冲突，如果是的话，能否提供个教程：如何在源码中修改占用的系统资源，比如修改端口之类的。

或者是ss能否优化一下，申请系统资源时，先检测下是否被占用？

**Comment by GangZhuo** [comment]
并不是共用系统资源导致的。在编辑服务器的窗口中就可以设置代理的端口。基于我的理解，加速器一般都是用了 LSP 技术，应该处于 .NET 的底层，所以在 SS 中应该是没有办法解决的。

**Comment by GangZhuo** [comment]
@linfengyes  你可以搜索看看，如果找到解决方案的话，告诉我一下。

**Comment by jackxiao17** [comment]
@linfengyes 好像确实是和腾讯游戏平台冲突，具体原因不太清楚，暂时没找到解决办法，同时用的话只能换回2.5.8

**Comment by Jarvanh** [comment]
@zzhhbyt1 我这也是经常重启之后就不行，又要重新执行这几行命令，换回2.5.8就完全没事了。

**Comment by jackxiao17** [comment]
@Jarvanh 似乎和迅雷、腾讯游戏平台都有端口冲突，每次退出这两个程序就好了，也不用reset winsock，至于前面说的emule不知道是否也影响，但是同样的情况换回2.5.8就是正常的，郁闷

**Comment by pickView** [comment]
好烦，过个几天就不能用，都要重新运行下这些代码

**Comment by pickView** [comment]
好烦，过个几天就不能用，都要重新运行下这些命令

**Comment by GangZhuo** [comment]
master 分支中已经修复了

**Comment by pickView** [comment]
@GangZhuo 您是说作者已经解决并更新了这个问题吗，请给我地址，谢谢，期待您的回复。

**Comment by GangZhuo** [comment]
Master 中修好了，不过还未发布

**Comment by Jarvanh** [comment]
@pickView 

应该是 @GangZhuo 修复的，感谢。

**Comment by pickView** [comment]
@GangZhuo good job ！ 期待发布，一直被这个问题纠缠着。

**Comment by liminjun** [comment]
今天同事那里出了老半天的问题，切回到2.5.8，就ok。
