### ISSUE TITLE
请问PAC失效的问题在3.0版本中是否已解决了？ 

### ISSUE THREAD

**Issue by mycwcgr** [shadowsocks/shadowsocks-windows#487]
请问PAC失效的问题在3.0版本中是否已解决了？ 谢谢！

**Comment by chenshaoju** [comment]
你是指Firefox的问题吗？详见：https://github.com/shadowsocks/shadowsocks-windows/issues/439#issuecomment-188074090

**Comment by mycwcgr** [comment]
对

**Comment by mycwcgr** [comment]
我现在回滚用 2.5.7 没有问题

**Comment by mycwcgr** [comment]
我已看过https://github.com/shadowsocks/shadowsocks-windows/issues/439#issuecomment-188074090，不过没有一个认可的解决方案

**Comment by mycwcgr** [comment]
3.0 + PAC(2.5.7) 只要不更新本地PAC 文件 是不是就OK

**Comment by GangZhuo** [comment]
@mycwcgr 应该可以的，未测试。 PAC失效的问题，当时做了一些测试，应该是 firefox 的问题见 https://bugzilla.mozilla.org/show_bug.cgi?id=1250776

**Comment by mycwcgr** [comment]
谢谢！ 你的意思是FireFox已修正了 Bugs, PAC失效的问题在3.0版本不会出现了？

**Comment by GangZhuo** [comment]
我的意思是这个问题应该不是 Shadowsocks 的问题，要等 firefox 来修复。

**Comment by mycwcgr** [comment]
我刚测试: 如果不更改FireFox(44.0.2)的设置
1、3.0的程序 + PAC(2.5.7) ， PAC不工作
2、3.0的程序 + PAC(从GFWList更新本地) ，PAC不工作

**Comment by chenshaoju** [comment]
@mycwcgr 请尝试此PAC：
https://gist.github.com/chenshaoju/52c7555acc65ec98423f

这个PAC是我自己写的，仅能访问Google相关的服务，请先试一下使用后是否可以访问Google。

**Comment by mycwcgr** [comment]
谢谢！ chenshaoju 你的Pac涉及的网站太少
看来还得等FireFox修正错误的啊！

**Comment by mycwcgr** [comment]
不过，有点奇怪，为什么2.5.7版本的PAC能在FireFox 44.0.2下正常使用？

**Comment by GangZhuo** [comment]
基于我的测试，当PAC中规则比较少的时候，文件大小大概小于112KB的时候，Firefox 是工作的。2.5.7使用的是托管在 Google Code 上的已经不维护的 GFW List，规则比较少，整个PAC 文件在107KB左右。

**Comment by chenshaoju** [comment]
其实我主要想反复测试一下这问题是否真的是Firefox的问题……

比较难以置信，Firefox有这个问题？

**Comment by GangZhuo** [comment]
@chenshaoju  在汇报的bug中( https://bugzilla.mozilla.org/show_bug.cgi?id=1250776 )，提供了两个PAC文件，一个是工作的，一个不工作。两个文件的区别只是多了一些注释，也可能是我测试的不对，你可以试看看。

**Comment by mycwcgr** [comment]
谢谢！ To GangZhuo
V2.5.7+PAC 2.5.7 工作
V3.0  + PAC 2.5.7 不工作
基于上面的测试，我认为 "基于我的测试，当PAC中规则比较少的时候，文件大小大概小于112KB的时候，Firefox 是工作的"的结论似乎有点问题

**Comment by chenshaoju** [comment]
@GangZhuo 我尝试了两个PAC，的确存在该问题，而无论无何，IE工作都是正常的。
于是，我又做了一个测试，在 work 的pac里逐步加入注释，每增加一个字节就启动Firefox测试一下。
测试结果是：当PAC文件的字节数达到 115,780 ~ 115,779 字节时，Firefox无法工作（通过PAC的配置访问互联网）。一旦减少到 115,779 ~ 115,778 字节或以下时，则正常。

测试时的操作系统是Windows 7 x64，Firefox版本为 43.0.1 。

**Comment by mycwcgr** [comment]
我的PAC(2.5.7)文件在115779以下，我的两台计算机都是Windows 7 64 +FirFox 44.0.2，但是在 V3.0 + PAC 2.5.7 均不工作, 
你可以下载测试
https://www.dropbox.com/s/xt9a85wqd69c858/mypac.PNG?dl=0
https://www.dropbox.com/s/1rpddov5sy1k9pg/pac.txt?dl=0

**Comment by mycwcgr** [comment]
我认为是V2.5.8~V3.0的程序问题！
因为同一个PAC(2.5.7)文件,同样的运行环境Windows 7 x64+FireFox 44.0.2，V2.5.7能正常工作，但V2.5.8-V3.0不能工作！

**Comment by GangZhuo** [comment]
我把2.5.7的PAC复制到3.0下是工作的。2.5.7到2.5.8只是换了个 GFW List 更新地址，其他都未动。

**Comment by GangZhuo** [comment]
@mycwcgr 下载你的 PAC 文件，在我这是工作的。

**Comment by mycwcgr** [comment]
你确认在FireFox 44.0.2中PAC模式是有效的？ 当你用 V3.0+我上传的PAC(2.5.7)文件？

**Comment by breakwa11** [comment]
119,471字节的PAC表示正常，FF版本44.0.2

**Comment by xeonchen** [comment]
@chenshaoju, @GangZhuo  您好，我正在处理 https://bugzilla.mozilla.org/show_bug.cgi?id=1250776
请问这个问题是否仍然存在？或是有没有方法让我可以重现问题呢？

**Comment by xeonchen** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/439

**Comment by 279838089** [comment]
使用自动配置
http://127.0.0.1:1080/pac
填入以上地址，就可以使用pac，跟版本没关系，只是2.5版本会自动更改插件以上的配置，3.0不会更改

**Comment by GangZhuo** [comment]
最新 Firefox 已经修复了这个问题。
