### ISSUE TITLE
XP系统3.0运行后出现闪退

### ISSUE THREAD

**Issue by ximuzunyue** [shadowsocks/shadowsocks-windows#488]
XP系统3.0运行后出现闪退，现换回2.5.8又出现问题原先能顺利的翻出去，但换回来后不能运行了打不开翻出去的网页。。。

**Comment by GangZhuo** [comment]
2.5版本后仅支持 .net 4.0。

**Comment by ximuzunyue** [comment]
那就是说3.0不能在Xp上运行了吗？

**Comment by GangZhuo** [comment]
正常来说是的，因为 xp 无法安装.net4。不过似乎有黑方法可以在xp中安装.net4，具体未测试。

**Comment by ximuzunyue** [comment]
2.5.8在XP能运行，3.0就变闪退了

**Comment by GangZhuo** [comment]
Seehttps://github.com/shadowsocks/shadowsocks-windows/issues/489

**Comment by ximuzunyue** [comment]
APPVEYAR : shadowsocks-windows  
请教一下，这个是不是下载，没看到下载按钮。

**Comment by GangZhuo** [comment]
点击最下边的 Configuration:Release，然后在新页面中点击 ARTIFACTS，然后在新页面中下载基于最新master 自动编译的版本

**Comment by ximuzunyue** [comment]
好的下载了，打开XP可以运行3.0了，THK

**Comment by Licshee** [comment]
Windows XP 是可以用正常方式安装 .NET Framework 4.0 的，不能安装的是 4.5。
据我所知目前客户端没有对 4.5 的强依赖，所以如果不能运行应该是 bug。

**Comment by GangZhuo** [comment]
@ximuzunyue  如果你明确知道 Appveyor 编译的版本中都包含些什么的话，可以到这里下载。正式发布的程序也是从这里下载的。

@Licshee 应该是修好了，但是还未合并到 master 中。

**Comment by Licshee** [comment]
最好在合并且测试之后再关闭，要不然跟踪起来可能会麻烦。
另外如果在提交时已经可以确认问题修复，编写 commit message 时直接引用 issue 编号更好，GitHub 可以识别特定的关键字在合并入主要分支时自动关闭 issue，详见：https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by GangZhuo** [comment]
好的

**Comment by ximuzunyue** [comment]
@GangZhuo 小白一个不知道 Appveyor 编译的内容。用来翻个墙上个网
现在3.0就是不会闪退了，但网速打不开网页，又换到2.5.8去了

**Comment by CNMan** [comment]
@GangZhuo .net 4.0是支持XP with SP3的，还有近20个.net 4.0的补丁
https://github.com/CNMan/MicrosoftHotfixesList/tree/master/winxp_with_sp3_x86

**Comment by GangZhuo** [comment]
@CNMan 嗯，看到官网中系统需求有 XP SP3了

**Comment by ximuzunyue** [comment]
@CNMan 请问这个补丁如何下载，用XP自带浏览器提示不能下载

**Comment by CNMan** [comment]
@ximuzunyue 都是直接链接，随便用什么工具都能下载
部分https:// 开头的链接用IE6下载需要开启TLS 1.0

**Comment by ximuzunyue** [comment]
@CNMan  更新一下打开3.0好像又是闪退，看样子XP只能用2.5.8

**Comment by Licshee** [comment]
请打开事件查看器看一下有关的错误消息

**Comment by jerryshao4u** [comment]
如果没有应用4.0以后的新特性，可以使用脚本编译不同fw版本的exe出来。

**Comment by Licshee** [comment]
技术上讲，.NET Framework 4.0 和 .NET Framework 2.0 的系统要求没本质差异，所以选哪个目标框架版本的这个话题讨论下去意义不是很大……

**Comment by chenshaoju** [comment]
但是在cloudwwy编译期间，2.0版本的 .NET 编译有诡异的内存溢出问题，该问题只在特定计算机上出现，很难复现，换用 4.0 版本没有该问题。最后该问题无法解决，怀疑是 .NET 本身（内存回收？）的问题： https://github.com/shadowsocks/shadowsocks-windows/issues/244

**Comment by yangyaofei** [comment]
在win7上3.0也出现闪退情况，刚刚装的系统，只加装了net4

**Comment by chenshaoju** [comment]
@yangyaofei 请尝试该版本是否可以使用：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/h189bju1e18bukk7/artifacts

**Comment by ximuzunyue** [comment]
@chenshaoju 好的，去试一下。

**Comment by chenshaoju** [comment]
@ximuzunyue 该网址提供的版本为最新的测试版本，可能会存在其它问题。但是该版本仍然可以使用自动更新功能，可在未来升级到正式版。

**Comment by ximuzunyue** [comment]
@chenshaoju  用了这个测试版本速度比原来的快点？

**Comment by chenshaoju** [comment]
@ximuzunyue 并没有这方面的优化，可能是心理作用。

**Comment by yangyaofei** [comment]
@chenshaoju  此版本可用 win7 .NET4

**Comment by wongsyrone** [comment]
看起来已经修复了
