### ISSUE TITLE
系统错误！

### ISSUE THREAD

**Issue by czd890** [shadowsocks/shadowsocks-windows#489]
系统环境：win10

System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by GangZhuo** [comment]
try  https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe

**Comment by czd890** [comment]
good job!

**Comment by dista** [comment]
same problem. 
win10,   3.0

**Comment by chenshaoju** [comment]
@dista 请使用二楼回复的版本。
