### ISSUE TITLE
软件改进新建议

### ISSUE THREAD

**Issue by ahchoooo** [shadowsocks/shadowsocks-windows#490]
我有个shadowsock的建议，就是在window右下角的小飞机用颜色来显示系统代理模式，如绿色的小飞机代表全局模式，黄色的小飞机代表PAC模式，红色代表没打开等，我就不需要常常进去检查代理模式了，谢谢你们。

**Comment by mycwcgr** [comment]
我认为他的建议很好！只需要更改下面的代码。

private void UpdateTrayIcon()
        {
            int dpi;
            Graphics graphics = Graphics.FromHwnd(IntPtr.Zero);
            dpi = (int)graphics.DpiX;
            graphics.Dispose();
            Bitmap icon = null;
            if (dpi < 97)
            {
                // dpi = 96;
                icon = Resources.ss16;
            }
            else if (dpi < 121)
            {
                // dpi = 120;
                icon = Resources.ss20;
            }
            else
            {
                icon = Resources.ss24;
            }
            Configuration config = controller.GetConfigurationCopy();
            bool enabled = config.enabled;
            bool global = config.global;
            if (!enabled)
            {
                Bitmap iconCopy = new Bitmap(icon);
                for (int x = 0; x < iconCopy.Width; x++)
                {
                    for (int y = 0; y < iconCopy.Height; y++)
                    {
                        Color color = icon.GetPixel(x, y);
                        iconCopy.SetPixel(x, y, Color.FromArgb((byte)(color.A / 1.25), color.R, color.G, color.B));
                    }
                }
                icon = iconCopy;
            }
            else
            {
                if (global)
                {
                    Bitmap iconCopy = new Bitmap(icon);
                    for (int x = 0; x < iconCopy.Width; x++)
                    {
                        for (int y = 0; y < iconCopy.Height; y++)
                        {
                            Color color = icon.GetPixel(x, y);
                            iconCopy.SetPixel(x, y, Color.FromArgb((byte)(color.A / 1.1), 0,119,255));
                        }
                    }
                    icon = iconCopy;
                }               
            }
            _notifyIcon.Icon = Icon.FromHandle(icon.GetHicon());

            string serverInfo = null;
            if (controller.GetCurrentStrategy() != null)
            {
                serverInfo = controller.GetCurrentStrategy().Name;
            }
            else
            {
                serverInfo = config.GetCurrentServer().FriendlyName();
            }
            // we want to show more details but notify icon title is limited to 63 characters
            string text = I18N.GetString("Shadowsocks") + " " + UpdateChecker.Version + "\n" +
                (enabled ?
                    I18N.GetString("System Proxy On: ") + (global ? I18N.GetString("Global") : I18N.GetString("PAC")) :
                    String.Format(I18N.GetString("Running: Port {0}"), config.localPort))  // this feedback is very important because they need to know Shadowsocks is running
                + "\n" + serverInfo;
            _notifyIcon.Text = text.Substring(0, Math.Min(63, text.Length));
        }

**Comment by ahchoooo** [comment]
如果也可以点一下这小飞机就可以改变模式，如从PAC模式改到全局模式，就更好了！！

**Comment by 1608637229** [comment]
这个建议确实不错

**Comment by jerryshao4u** [comment]
既然代码都有，可以测试下，然后提个PR啊~

**Comment by Taoist1996** [comment]
资词！

**Comment by reaCodes** [comment]
因为我需要经常切换代理模式，咱们好不好加一个切换代理模式的快捷键啊，这样就很方便了

**Comment by wongsyrone** [comment]
This feature has already been merged into master branch, but not released yet.
Please try https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.163/job/9ubrdla6b609f4n2/artifacts or build latest master branch yourself.
