### ISSUE TITLE
3.0 版 Could not load template file no-server-data or one of its included components.

### ISSUE THREAD

**Issue by bdqlaccp** [shadowsocks/shadowsocks-windows#491]
500
Could not load template file no-server-data or one of its included components.
怎么回事?用2.5.8 就没事!!!!

**Comment by chenshaoju** [comment]
你的Shadowsocks是工作在便携模式，还是工作在普通模式？请先退出Shadowsocks。
如果是便携模式，删除Shadowsocks所在目录的 temp 文件夹，然后再试。
如果是普通模式，请删除 %temp% 目录下的所有文件。

**Comment by bdqlaccp** [comment]
感谢，按你的方法解决了！我清了一下 %temp%,然后 Shadowsocks.exe换了新目录，而不是放在老版目录里，完事重新配制了一下就OK了

**Comment by siaimes** [comment]
@arnbunchen 你好， %temp%在哪里呢？

**Comment by keenwon** [comment]
@siaimes 打开我的电脑，地址栏输入 `%temp%` 就行了

**Comment by xx0508** [comment]
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by xx0508** [comment]
我用的4.0.7的客户端，访问google 报这个错误
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

求大神指点怎么搞

**Comment by chenshaoju** [comment]
@xx0508 SS的日志里有什么提示吗？
这个现象通常是你的服务器挂了，或者服务器地址、端口、加密方式、密码不正确。

**Comment by doonny** [comment]
kiwiVM上看远程服务器都ok，用户名密码都是复制粘贴的也不可能错，会是怎么回事
