### ISSUE TITLE
Website does not exist.

### ISSUE THREAD

**Issue by lynszixan** [shadowsocks/shadowsocks-windows#492]
ishadowsocks 没了.... 哭...

**Comment by chenshaoju** [comment]
这儿是Shadowsocks for Windows的问题报告区域，iShadowsocks与Shadowsocks for Windows没有任何关系。

**Comment by jerryshao4u** [comment]
ishadowsocks还可以打开，不过那个站和shadowsocks没有任何关系~

**Comment by GangZhuo** [comment]
见 @chenshaoju 回复。
