### ISSUE TITLE
统计配置里的分数如何计算？

### ISSUE THREAD

**Issue by hardbone12** [shadowsocks/shadowsocks-windows#493]
3.0版本的统计配置里的分数后面X的系数是正比还是反比？得分是越高越有限还是越低越优先？
比如我需要优先使用PackageLoss低的，其次使用平均AvgLatency低的，应该如何配置？

**Comment by hardbone12** [comment]
另外每个指标的计算单位是什么？延时和丢包率这完全不是一个数量级的

**Comment by Diluka** [comment]
完全看不懂这个，也没有给一个默认配置，也没有配置说明

**Comment by GangZhuo** [comment]
@hardbone12 

- 乘号后边的数字是权重，这个数字可以是正数也可以是负数。
- 选择服务器时，得分越高越优先。
- 优先使用 PackageLoss 低的，其次使用 AverageLatency 低的，可以参考设置为 Final Score = AverageLatency X  (-0.01) + PackageLoss X (-2.50)。

@hardbone12  @hardbone12 @Diluka 这里的设置我也感觉不合理，另开一个 https://github.com/shadowsocks/shadowsocks-windows/issues/499 讨论一下应该如何设置？

**Comment by wongsyrone** [comment]
dup #499
