### ISSUE TITLE
Win 10 64位 SS3.0闪退

### ISSUE THREAD

**Issue by chchuj** [shadowsocks/shadowsocks-windows#494]
从2.5.8推送地址下载的，扫码添加了几个配置文件之后就出错，提示停止运行，然后再点运行就是不断退。清空配置文件，再配置一下又可以用，添加2个节点时可以运行使用。但添加了四个节点之后再添加又崩溃。
感觉还是不稳定，坐等更新改进。

**Comment by chenshaoju** [comment]
该问题是由于你添加了重复的服务器导致的。

如果你坚持要加入重复的服务器，可以在：

https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/6b398cc7eupp76na/artifacts

下载到截止目前最新的版本。

**Comment by chchuj** [comment]
我使用的已经是github上面的最新版本了。
难道这个版本不允许添加重复？我的扫描添加的，有时会不小心扫到上一个，就重复了，这都会崩溃？再等下一个版本吧。每次崩溃都得重新添加服务器，好烦的

**Comment by chenshaoju** [comment]
Github上的版本存在该问题，该文已知，并且在截至目前最新（上面网址中）的版本中修正了。

具体情况详见： https://github.com/shadowsocks/shadowsocks-windows/issues/474
