### ISSUE TITLE
WIN10 R1 14279 开机时间长了会崩溃！

### ISSUE THREAD

**Issue by devyangyi** [shadowsocks/shadowsocks-windows#497]
WIN10 R1 14279 开机时间长了会崩溃！

**Comment by chenshaoju** [comment]
请提供崩溃时的Dump，具体操作如下：
http://stackoverflow.com/questions/4992569/how-do-i-obtain-a-crash-dump

建议暂时修改你的服务器密码，避免Dump泄漏信息。

**Comment by wongsyrone** [comment]
No responses from origin reporter, closing.
