### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by asdyjd** [shadowsocks/shadowsocks-windows#498]
建议开放2个本地端口提供代理.
比如1个1080提供全局代理,另1个1081代理pac代理.
这样可以满足不同的软件的需要.

**Comment by GangZhuo** [comment]
@asdyjd 没有搞明白你的需求，如果是需要多开的话，可以使用 https://github.com/shadowsocks/shadowsocks-windows/tree/master#portable-mode

**Comment by asdyjd** [comment]
我有个需求,我的浏览器和IDM下载工具的代理需要设置为http://127.0.0.1:1080/pac.
但是我的QQ旋风需要设置为全局用SHADOWSOCKS代理下载,因为我们学校把QQ旋风和迅雷都禁了.只有代理才能下载.
那如果我设置shadowsocks全局模式,但是浏览器和下载工具设置http://127.0.0.1:1080/pac.
QQ旋风代理为127.0.0.1:1080.
这样能行吗?
我还需要有时发现一个被墙的网站时,修改user-rule.txt,这样能即时地改变浏览器和IDM的PAC文件吗?

**Comment by asdyjd** [comment]
firefox怎么不停地提示我"确定代理服务应该使用的主机时发生异常"

**Comment by GangZhuo** [comment]
如果你使用的是IE浏览器的话，应该是可以在选择全局模式后，为浏览器单独设置 PAC 模式的。

看看 http://verihy.me/posts/foxyproxy-pac/  是否能解决Firefox出错的问题？

**Comment by dpast** [comment]
“但如果全局代理不使用 PAC 就没有警告，所以问题可能出在 PAC 文件里面。” from http://verihy.me/posts/foxyproxy-pac/ 

切换 Tab 时我也是不停地提示“确定代理服务 应该使用的主机时发生异常”，全局模式也是同样的问题。对 Firefox 失望极了。

**Comment by GangZhuo** [comment]
最新版 Firefox 修复了 PAC 的问题
