### ISSUE TITLE
shadowsocks.availability.csv - Seriously?

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-windows#500]
This file is now 87M on my PC (it started from 2016-01-14) and no wonder it is consuming so much memory and disk usage. >:-(

Switch to SQLite or something like that plz. Also clean up statistics that are >7-30 days old and >100-1000 entries.

**Comment by Mygod** [comment]
Actually cleaning up old entries is optional (some users might want that).

**Comment by chenshaoju** [comment]
For now ,You can write a batch file ( .bat ) and add to scheduled task.
example:

```
taskkill /f /im shadowsocks.exe
taskkill /f /im ss_privoxy.exe
del temp\shadowsocks.log
del temp\shadowsocks.availability.csv
start shadowsocks.exe
```

and running every 24 hours by scheduled task.

**Comment by Mygod** [comment]
I'm serious. Using csv can cause a lot of string instantializations and lead to huge memory usage and heavy GCs. Please consider switching to SQLite, etc.
