### ISSUE TITLE
请问shadowsocks3.0的源代码和提供的exe程序里面的代码不一致，请问是否源代码没有上传呢？

### ISSUE THREAD

**Issue by shirh19910112** [shadowsocks/shadowsocks-windows#503]
请问shadowsocks3.0的源代码和提供的exe程序里面的代码不一致，请问是否源代码没有上传呢？ @GangZhuo

**Comment by GangZhuo** [comment]
Release 中 3.0 的代码，在 master 分支中， 后来部分修改的代码在 Pull Request https://github.com/shadowsocks/shadowsocks-windows/pull/478 中，还未合并到 master 分支中，计划等统计配置部分全部弄完再合并的，不过最近有点忙。

**Comment by shirh19910112** [comment]
谢谢，您先忙。感谢大大的不断完善，向您学习^_^ @GangZhuo

**Comment by shirh19910112** [comment]
@GangZhuo 请问可以先发我一份完整的您的修改代码吗？

**Comment by GangZhuo** [comment]
All in my repository https://github.com/GangZhuo/shadowsocks-windows
