### ISSUE TITLE
pac现在是强制开启了？

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [shadowsocks/shadowsocks-windows#504]
我的意思是，你做ss就做ss，pac不是你负责的事，让浏览器负责就行了。如果非要做，也不要做强制开启。。。。

**Comment by GangZhuo** [comment]
默认不开启系统代理，系统代理提供两种模式：PAC模式和全局模式。右击图标，并启用系统代理后，PAC和全局两种模式必须选择一项，默认使用PAC模式。

**Comment by chenshaoju** [comment]
取消这个：

![unnamed qq screenshot20160317101731](https://cloud.githubusercontent.com/assets/515763/13834374/738e719e-ec29-11e5-9399-15111f763991.png)

**Comment by GreatBigWhiteWorld** [comment]
刚看到启用系统代理后有全局选项。

说实话，不知道是不是更难实现。还是觉得把pac在ss上弄这么复杂有点方向不对。

**Comment by GangZhuo** [comment]
只是为了简化使用，否则的话对于不懂的人配置太复杂了。

**Comment by oudioppa** [comment]
这个功能很好用，否则自己去折腾一个PAC，现在直接就可以用了。

**Comment by GreatBigWhiteWorld** [comment]
多谢。
