### ISSUE TITLE
Fatal error: can't check configuration file 'privoxy.conf' (error number 2)

### ISSUE THREAD

**Issue by nmgwddj** [shadowsocks/shadowsocks-windows#505]
如下图，经常出现。然后代理就无效了。

![2016-03-18_155300](https://cloud.githubusercontent.com/assets/13995319/13872244/0319c25a-ed24-11e5-9f93-c9034fd85057.png)

**Comment by GangZhuo** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/330

**Comment by szwuzy** [comment]
重启shadowsockets主程序，程序会自动在临时目录生成privoxy.conf配置文件。即可正常。

**Comment by jmszwzr** [comment]
换一个账号试试

**Comment by WeskerC** [comment]
路径不可以有中文名字，包括文件夹名，请重新检查一下

**Comment by WeskerC** [comment]
文件路径不可以出现中文字，请重新检查一下文件路径
