### ISSUE TITLE
求助：504 Connect to www.google.com:80 failed: SOCKS protocol error

### ISSUE THREAD

**Issue by Noilit** [shadowsocks/shadowsocks-windows#506]
shadowsocks打开之后开网页，一直是这样的状态..系统是win10
在其它的电脑上尝试没问题，记录如下
[2016-03-18 16:48:35] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   在 System.Security.Cryptography.MD5.Create()
   在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   在 Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   在 Shadowsocks.Encryption.PolarSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.Local.Handle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-03-18 16:48:44] System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-03-18 16:48:46] System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)
[2016-03-18 16:48:48] Shadowsocks started
——————————————————————————
上google之后显示
504 Connect to www.google.com:80 failed: SOCKS protocol error
The following error occurred while trying to access http://www.google.com/:
504 Connect to www.google.com:80 failed: SOCKS protocol error

**Comment by GangZhuo** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/449

**Comment by zcc973784075** [comment]
The  same  to yours,need help
