### ISSUE TITLE
ss连接不上求解

### ISSUE THREAD

**Issue by jing8263xiao** [shadowsocks/shadowsocks-windows#510]
刚买的搬瓦工的vps，自己按教程搭的梯子，可是ss却连不上，日志如下。
求大神详解！

[2016-02-25 12:53:53] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 System.Net.DownloadStringCompletedEventArgs.get_Result()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-02-25 12:53:53] Shadowsocks started
[2016-02-25 12:55:23] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 System.Net.DownloadStringCompletedEventArgs.get_Result()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-02-25 12:55:24] Shadowsocks started
[2016-02-25 12:56:08] Shadowsocks started
[2016-02-25 12:56:21] Shadowsocks started
[2016-02-25 13:17:37] System.ComponentModel.Win32Exception: 拒绝访问。
   在 System.Diagnostics.Process.Kill()
   在 Shadowsocks.Controller.PolipoRunner.Start(Configuration configuration)
[2016-02-25 13:17:38] Shadowsocks started
[2016-02-25 13:17:52] System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。
203.*.*.*:433
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult ar)
[2016-02-25 13:17:52] System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 *.*.*.*:433

**Comment by ljl024** [comment]
你好，根据日志来看，存在的问题是服务器与客户端配置不一致
根据现有信息无法看出配置存在的错误
我相信，通过搜索和仔细阅读官方文档，你能够轻易的修正你的配置文件
我个人不建议你将IP地址发在公开页面上

**Comment by ljl024** [comment]
你好，**首先**我个人不建议你将IP地址发在公开页面上

根据日志来看，存在的问题可能是
- 服务器与客户端的端口配置不一致

或
- 未在服务器防火墙上打开该端口

我相信，通过仔细阅读官方文档和搜索相关资料，你能够轻易的修正你的配置文件

**Comment by GangZhuo** [comment]
请检查配置，包括 IP 、端口、加密方式、密码。

**Comment by jing8263xiao** [comment]
@ljl024 首先谢谢你的建议
根据我的搜索也可能是端口问题，据说可能是端口被用了？请问ss上的服务器端口填vps的ssh端口还是配置时设置的端口号？
另外那个代理端口都是1080不变吗还是填其他的什么？如果能推荐相关的文档不胜感激。纯小白谢谢了～

**Comment by MKFons** [comment]
如果是用chrome浏览器的话，需要使用代理插件才能搭梯子

**Comment by jing8263xiao** [comment]
@MKFons 不是调到全局模式就可以直接翻了吗？

**Comment by MKFons** [comment]
不是的，我的就是得用个做代理的插件，启用了才能出去。

**Comment by MKFons** [comment]
switchomega 我用的是这个

**Comment by ljl024** [comment]
需要填写的是**配置时**填写的端口号
如果你有搭建Nginx、apache等网站程序并**开启SSL**的话，443端口就会被占用
个人建议使用4000以上端口，不会和常用业务冲突

**Comment by jing8263xiao** [comment]
@ljl024 
`service supervisord start`
执行之后好了，好像是个低级错误。。

**Comment by Huxingyu** [comment]
@jing8263xiao 您好，我和你遇到了相同的问题（日志报错一致），请问问题出在哪里呢？

**Comment by derboys** [comment]
我之前用的是另外的ss  搭的服务器， 现在在HK  自己搭了台出现这个错误。
出现了同样的错误 rerest ipv4  和 ipv6  然后重启了电脑都不行。  
然后我用回以前的代理 ss  就可以访问Google  ， 一换回我自己搭的就不可以了， 但是我用我的自己搭的ss  在公司用就可以， 肯定本机哪里配置出了问题。
