### ISSUE TITLE
关于开机启动写注册表

### ISSUE THREAD

**Issue by King66** [shadowsocks/shadowsocks-windows#511]
我看到3.0版本把注册表的Key由Shadowsocks改成了"Shadowsocks_" + Application.StartupPath.GetHashCode()。这样会有问题，以下情况都是在选中开启启动的情况下。
1、如果用户有多个shadowsocks.exe在不同目录下，只要其中有一个是3.0版本的，那么开机启动时就会运行多于一个shadowsocks，也就会报错，如果是以前的写法，则不会有问题。
2、如果用户将2.5.8版本的shadowsocks，替换了3.0版本（我就是这么做的，因为前天我发现3.0翻不出去，上google报500 internal privoxy error的错，上facebook无响应），那么开机时就会运行两次shadowsocks，也就是会报错....

**Comment by GangZhuo** [comment]
便携模式下，这允许启动时多开。如果覆盖升级应该不会出现这个问题，如果是新建目录，则需要启动旧版，在旧版中取消开机启动。

**Comment by King66** [comment]
还是原来的那样写比较好

**Comment by wongsyrone** [comment]
As mentioned above.
