### ISSUE TITLE
64位WIN7无法切换系统代理模式

### ISSUE THREAD

**Issue by hijakke** [shadowsocks/shadowsocks-windows#512]
程序启动后在全局模式和PAC模式之间切换无效，注册表值无变化，但是重启一下shadowsocks，注册表值会更新。导致每次切换模式都要重启shadowsocks。
这个问题目前只在64位WIN7上出现。

**Comment by seraph333** [comment]
我也发生了这个问题，搜索出来的方法都不能解决。
System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   at System.Diagnostics.Process.Kill()
   at Shadowsocks.Controller.PolipoRunner.Start(Configuration configuration)

**Comment by chenshaoju** [comment]
请检查是否使用了某些安全软件，目前已知金山毒霸、卡巴斯基等可能会在特定情况下拦截修改。

另外，请尝试便携模式（ shadowsocks_portable_mode.txt ）。

**Comment by seraph333** [comment]
安装了电脑管家，加入白名单并退出电脑管家无效。
尝试了便携模式也不行

**Comment by chenshaoju** [comment]
请尝试暂时卸载安全软件然后重启后再看看？
也可能是注册表键值的权限问题：
HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ 下的 AutoConfigURL 。

![unnamed qq screenshot20160531151659](https://cloud.githubusercontent.com/assets/515763/15666337/e6d7a216-2742-11e6-953f-eb582495fbb8.png)

**Comment by seraph333** [comment]
已卸载安全软件重启再试问题依旧。
权限也有，但就是每次切换模式需要重启shadowsocks才能生效，并且无法关闭代理，需要手动删除注册表键值才能关闭。如果直接退出软件会导致不能上网。
![qq 20160531231253](https://cloud.githubusercontent.com/assets/19536425/15679767/a1b03fd4-2785-11e6-9b0f-93ef093ee2cf.png)

**Comment by chenshaoju** [comment]
这个问题的确很像权限出错（没有权限写注册表），但是具体是如何导致的，不知道。
如果非常在意该问题，重新安装操作系统可能是最快的解决办法。

或者，写一个批处理，自动删除和创建此注册表键值并停用SS内置的系统代理功能。

**Comment by seraph333** [comment]
好的，非常感谢您的耐心解答

**Comment by hijakke** [comment]
我的电脑没有另外安装任何安全软件，新安装的系统也无效

**Comment by chenshaoju** [comment]
你的系统可能有某些自动设置PAC的东西。
或者，你是不是在一个受控的网络中，比如商业网络或者企业网络？

**Comment by wongsyrone** [comment]
Please test latest commit.

**Comment by wongsyrone** [comment]
Please try latest release.

**Comment by seraph333** [comment]
此问题依旧

**Comment by wongsyrone** [comment]
Check error log, and try to upgrade you IE to IE11.
I can't reproduce this on Win10 x64.
