### ISSUE TITLE
[Suggestion] Add a "verbose logging" option

### ISSUE THREAD

**Issue by hexchain** [shadowsocks/shadowsocks-windows#513]
It would be great if every single connection or DNS query can be logged for e.g. debug purposes.

**Comment by wongsyrone** [comment]
similar to #566

**Comment by wongsyrone** [comment]
Added to master branch, done in https://github.com/shadowsocks/shadowsocks-windows/commit/fb3fcdb90d68ad6e8c582ecb5d70c26103017fe4 and https://github.com/shadowsocks/shadowsocks-windows/commit/d3acb3e681b12085e5a4399547aee074853aa66f.

You need to reset configurations from scratch.
