### ISSUE TITLE
 System.ComponentModel.Win32Exception (0x80004005): 拒绝访问

### ISSUE THREAD

**Issue by potina** [shadowsocks/shadowsocks-windows#514]
错误提示：[2016-03-27 09:20:39] System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   在 System.Diagnostics.Process.Kill()
   在 Shadowsocks.Controller.PolipoRunner.Start(Configuration configuration)
[2016-03-27 09:28:27] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)
请问故障原因？如何解决？

**Comment by chenshaoju** [comment]
请检查你的服务器IP、端口等配置是否正确。

**Comment by chungguo** [comment]
同样的问题，windows7 professional 64位系统。服务器也ping的通。

**Comment by chenshaoju** [comment]
请检查端口是否正确。
你可以使用 TCPing.exe 检查你的SS的服务器的端口是否开放：
http://www.elifulkerson.com/projects/tcping.php

**Comment by HarveyTei** [comment]
我 也出现了此问题、公司默认安装了360、我把360关了就好了，哦哈哈哈，建议你把其他杀毒软件关了试下、我在家用卡巴斯基是不需要关杀毒软件的
