### ISSUE TITLE
为什么要使用http方式连接

### ISSUE THREAD

**Issue by njzhenghao** [shadowsocks/shadowsocks-windows#515]
搞不懂为什么这个版本的ss要用http才能连接。用socks5无法连接上

**Comment by chenshaoju** [comment]
我用的就是SOCKS5方式，没有问题。
请检查是否选择了SOCKS5协议，以及是否启用了远程DNS解析。

**Comment by njzhenghao** [comment]
远程dns解析在哪里？

**Comment by chenshaoju** [comment]
你用的什么浏览器？

![unnamed qq screenshot20160328165812](https://cloud.githubusercontent.com/assets/515763/14074793/42c5d24c-f506-11e5-94cd-f3022956cafc.png)

**Comment by njzhenghao** [comment]
chroome+switchyomega就必须使用http
Firefox+foxpoxy就选socks5没有问题

**Comment by GangZhuo** [comment]
我用的是 Chrome+SwitchyOmega，一直都是 SOCKS5，正常没有问题。

**Comment by GangZhuo** [comment]
使用SOCKS5时，是否有什么错误日志？

**Comment by njzhenghao** [comment]
[2016-03-28 16:54:48] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.StartConnect()

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/247#issuecomment-131392491 请跳转到第三步

**Comment by GangZhuo** [comment]
@njzhenghao 这个应该是网络质量问题，和你说的问题无关的。另外， https://github.com/FelisCatus/SwitchyOmega/issues/557 中说卸载迅雷就正常了，你可以卸载迅雷或升级到最新版迅雷试看看。

**Comment by njzhenghao** [comment]
@GangZhuo 想起了！果然是迅雷的问题，之前我试过，有这么个问题，我一个一个排除的，现在你一说我就想起了！！！
@chenshaoju 谢谢解答
