### ISSUE TITLE
Latest version cannot be download in China

### ISSUE THREAD

**Issue by Efforto** [shadowsocks/shadowsocks-windows#518]
You know,S3 Amazon seems blocked by GFW. So, I think you can upload to some others servers or make a file in master branch to save......
= =有错轻喷谢谢...没有翻译

**Comment by Efforto** [comment]
然而，好像是有中国人在项目里呢，这就好办了，加一下度娘盘，文件名全部重置就好233333
并没有代理怎么破qwq

**Comment by chenshaoju** [comment]
请通过代理下载……

**Comment by GangZhuo** [comment]
无此计划。代码仓库只应该存储源码。发布放国内，估计要不停换地方才行。
