### ISSUE TITLE
最新版本支持udp转发吗？

### ISSUE THREAD

**Issue by ron159** [shadowsocks/shadowsocks-windows#519]
配合proxifier类软件，steam等客户端还是没法连接到ipv6地址的服务端。是因为不支持udp吗

**Comment by GangZhuo** [comment]
支持 UDP  的。

**Comment by ron159** [comment]
但是steam这类udp协议的软件为什么不能下载等操作

**Comment by GangZhuo** [comment]
如果软件不支持系统代理，那么就不能使用了。请搜索 ProxyCap, Proxifier 。
