### ISSUE TITLE
BUG：同一二维码扫描添加两次后停止工作，重新启动后依旧停止工作

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-windows#522]
问题签名:
问题事件名称: CLR20r3
问题签名 01: shadowsocks.exe
问题签名 02: 3.0.0.0
问题签名 03: 56d65064
问题签名 04: mscorlib
问题签名 05: 4.0.0.0
问题签名 06: 4d92ee5e
问题签名 07: 226
问题签名 08: 10
问题签名 09: System.ArgumentException
OS 版本: 6.1.7601.2.1.0.256.1
区域设置 ID: 2052
其他信息 1: 0a9e
其他信息 2: 0a9e372d3b4ad19135b953a78882e789
其他信息 3: 0a9e
其他信息 4: 0a9e372d3b4ad19135b953a78882e789

有个二维码之前lz扫描过，但不小心又误扫了一次，然后ss立即停止工作
手动进入gui-config.json，将重复的ss信息删除后解决

**Comment by GangZhuo** [comment]
Dup https://github.com/shadowsocks/shadowsocks-windows/issues/502
