### ISSUE TITLE
System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by charliechan** [shadowsocks/shadowsocks-windows#523]
[2016-04-07 09:02:42] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.StartConnect()

**Comment by chenshaoju** [comment]
请尝试：
https://github.com/shadowsocks/shadowsocks-windows/issues/476
