### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。

### ISSUE THREAD

**Issue by charliechan** [shadowsocks/shadowsocks-windows#524]
[2016-04-07 09:02:02] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.StartConnect()

**Comment by chenshaoju** [comment]
请尝试：
https://github.com/shadowsocks/shadowsocks-windows/issues/476

**Comment by charliechan** [comment]
thanks

**Comment by GangZhuo** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/523

**Comment by peimin** [comment]
解决了 是配置文件的问题 我把可以用的配置文件拷贝一份过来就可以了

**Comment by LeoStark** [comment]
请问是什么配置问题？

我在手机端可以，但是在电脑就异常

**Comment by chenshaoju** [comment]
@LeoStark 请看二楼。

**Comment by wudihzh** [comment]
刚发现如果设置了阿里云的公共DNS地址，也会导致这种问题
