### ISSUE TITLE
win7 64bit 系统全局代理是不是不是所有程序都有效?

### ISSUE THREAD

**Issue by lostsnow** [shadowsocks/shadowsocks-windows#530]
![2](https://cloud.githubusercontent.com/assets/220461/14379536/ff6fc3f4-fdac-11e5-94fd-d1c1b61c9b7e.png)

如图, 开了系统全局代理 获取到的还是本地 IP, shadowsocks 版本 3.0

哈市我哪里姿势不对?

**Comment by chenshaoju** [comment]
不是，需要你的程序支持PAC代理。

**Comment by lostsnow** [comment]
不是我的程序啊 试了下 cmd/git/python 等等好像都不行, 像这些也没法让他支持 PAC 吧, 另外我选的是全局, 按说也和 PAC 无关啊

不知道 windows 下有没有 http_proxy 这种东西, 有的话转一下 http 代理也行

**Comment by lostsnow** [comment]
```
set http_proxy=http://host:port
set https_proxy=http://host:port
```

找到这个, 试了下 cmd 可以用

**Comment by ikkyusan123** [comment]
这个全局代理只针对使用IE代理的程序才全局，不是像VPN那样的全局，要实现VPN那样的功能，好像要用provixy

**Comment by kingzoler** [comment]
可以用Proxifier做全局

**Comment by lostsnow** [comment]
有些 app 貌似 Proxifier 也没办法, 比如上面说的 cmd 或者 win10 下系统自带的邮件程序, 不知道有什么好办法

**Comment by GangZhuo** [comment]
如果 proxifier 类型的软件也不行，只能联系 app 开发者了。

**Comment by NewdawnALM** [comment]
你好，请问一下怎么在windows的cmd下使用shadowsocks的代理呢？只输入
set http_proxy=http://127.0.0.1:1080
set https_proxy=http://127.0.0.1:1080
这两条命令就行了吗？我试过了并不行哦，求教~

**Comment by burningmyself** [comment]
不是这样的window没有这个环境变量。你要在ie浏览器里面设置使用代理服务器

**Comment by GreatFireWall** [comment]
做全局代理可以试试 [Win2Socks](https://win2socks.com)

**Comment by GreatFireWall** [comment]
试试 win2socks 吧, 指哪个程序哪个就走代理.
