### ISSUE TITLE
在云盘中使用可能会有临时文件冲突的问题

### ISSUE THREAD

**Issue by VincentChiu** [shadowsocks/shadowsocks-windows#532]
在某云盘中使用ss，并且配置有shadowsocks_portable_mode.txt文件的情况下，
多台机器的临时文件同时写入会有冲突，产生大量重命名的临时文件，
建议允许在配置文件中自行指定临时文件的路径，谢谢！

**Comment by chenshaoju** [comment]
请不要同步Shadowsocks.exe 所在的 temp/ 文件夹里的内容即可。

**Comment by wongsyrone** [comment]
exclude temp/ folder before syncing files

**Comment by riophae** [comment]
你好，我使用的云同步服务是 OneDrive，官方表示不支持禁用对某个子文件夹的同步。
https://answers.microsoft.com/en-us/onedrive/forum/odwork-odfiles/is-it-possible-to-exclude-a-folder-from-being/7abe74f8-57b9-4c28-8c28-9824d30081b2

而现在默认开启便携模式，似乎没办法把便携模式关掉……

**Comment by chenshaoju** [comment]
@riophae ？？？

![2017-01-13 1](https://cloud.githubusercontent.com/assets/515763/21918810/2d68faea-d990-11e6-9b6f-0a02aa22d12d.png)

**Comment by riophae** [comment]
@chenshaoju 我也是这样设置的，然而还是会同步上去。。

**Comment by chenshaoju** [comment]
@riophae Hmmmm....
目前没有比较好的解决方案了，不过你仍然可以使用旧版本……
https://github.com/shadowsocks/shadowsocks-windows/releases/tag/3.4.2.1

**Comment by wongsyrone** [comment]
OneDrive没有按照声称的功能去实现，这应该是个bug吧。为啥不给伟大的MS回报bug

**Comment by riophae** [comment]
@wongsyrone 似乎有很多人反映过这个问题了，据说这是故意设计成这样的，不是 bug
https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/6988070-use-a-file-to-ignore-exclude-files-or-folder

**Comment by chenshaoju** [comment]
试试Dropbox把。

**Comment by riophae** [comment]
@chenshaoju 其实我一直在用 Dropbox，之所以用 OneDrive 同步就是因为免翻墙……
不打算修的话，那就这样吧。

**Comment by wongsyrone** [comment]
个人或者是少量的需求自己改temppath的设置函数吧，自己决定临时文件夹放在哪里

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Util/Util.cs#L31

**Comment by dobetter** [comment]
@chenshaoju Dropbox 如果设置不同步的话也会从Dropbox文件夹删除，不会再本地保留

**Comment by chenshaoju** [comment]
@dobetter 这儿是暂时的方案： https://github.com/shadowsocks/shadowsocks-windows/issues/1022#issuecomment-277148956

PS：刚才有人提交了新的代码，用于解决该问题，目前正在review： https://github.com/shadowsocks/shadowsocks-windows/pull/1023

**Comment by riophae** [comment]
@chenshaoju 感谢！

**Comment by GongT** [comment]
OneDrive这个问题很早以前就有人提了，并且据说ms确实要加类似的功能。。。然而一点回应都没有= =
