### ISSUE TITLE
最新安装windows10 shadowsocks3.0 timed out

### ISSUE THREAD

**Issue by Skefei** [shadowsocks/shadowsocks-windows#534]
今天刚安装windows10 并在更新完驱动后装上了shadowsocks3.0
但是折腾了半天发现不能FQ，手机可以，mac也可以
日志：
[2016-04-12 22:05:59] 23.105.192.226:443 timed out
[2016-04-12 22:05:59] 23.105.192.226:443 timed out
[2016-04-12 22:05:59] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2016-04-12 22:05:59] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2016-04-12 22:06:02] 23.105.192.226:443 timed out
[2016-04-12 22:06:02] 23.105.192.226:443 timed out
[2016-04-12 22:06:02] 23.105.192.226:443 timed out
[2016-04-12 22:06:10] 23.105.192.226:443 timed out
[2016-04-12 22:06:13] 23.105.192.226:443 timed out
[2016-04-12 22:06:14] 23.105.192.226:443 timed out
[2016-04-12 22:06:17] 23.105.192.226:443 timed out
[2016-04-12 22:06:17] 23.105.192.226:443 timed out
[2016-04-12 22:06:17] System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2016-04-12 22:06:20] 23.105.192.226:443 timed out
[2016-04-12 22:06:20] 23.105.192.226:443 timed out
[2016-04-12 22:06:20] 23.105.192.226:443 timed out

**Comment by chenshaoju** [comment]
请尝试：
https://github.com/shadowsocks/shadowsocks-windows/issues/476

**Comment by Skefei** [comment]
试过了按照帖子里说的做了一遍，而且输出内容和帖子一致，现在重启，问题依旧...

**Comment by Skefei** [comment]
另外，我上一周的时候用的debian系统还勉强可以用shadowsocks-qt5客户端，（真是很勉强的再用）
今天装了windows10后，google Y2B 都不能访问了 但是某些如 developer.android.com 还能勉强

**Comment by chenshaoju** [comment]
我试了一下，你的这个服务器根本无法访问，TCP端口不通。请检查你的VPS的防火墙以及服务端的Shadowsocks色绘制。

**Comment by Skefei** [comment]
不好意思，我刚切换了机房..用的搬瓦工，我想试试换ip
能不能解决.

结果是：没有用

**Comment by Skefei** [comment]
另外，vps防火墙应该正常配置了，因为用Mac和android手机都能FQ。
现在就是在windows10上访问不能..

**Comment by chenshaoju** [comment]
我这儿看还是不行。你可以在 http://tool.chinaz.com/port/ 测试你的服务器端口开放情况。

**Comment by Skefei** [comment]
443 已开放

80关闭8080关闭3128关闭

8081关闭9080关闭1080关闭

21关闭23关闭443开放

69关闭22关闭25关闭

110关闭7001关闭9090关闭

3389关闭1521关闭1158关闭

2100关闭1433关闭

**Comment by chenshaoju** [comment]
我现在开４４３也是开放的了，还是不行吗？

**Comment by garywzh** [comment]
我换回2.5.8版本用的443端口也经常timeout，可能是vps被针对了

**Comment by Skefei** [comment]
VPS 被针对？这个太吓人了吧，以后何去何从？

**Comment by Skefei** [comment]
现在有Mac下的日志：
访问Y2B 默认240p

16/4/13 下午1:37:07.749 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:07.749 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:08.285 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:08.285 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:08.285 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:08.285 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:08.669 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:08.669 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:08.669 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:08.669 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:08.989 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:08.989 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:08.989 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:08.989 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:09.205 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:09.206 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:09.206 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:09.206 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:09.261 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:09.261 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:09.261 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:09.261 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:10.272 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:10.272 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:10.272 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:10.272 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:10.749 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:10.749 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:10.749 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:10.749 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:25.845 WindowServer[183]: _CGXRemoveWindowFromWindowMovementGroup: window 0x38 is not attached to window 0x3e
16/4/13 下午1:37:27.095 WindowServer[183]: _CGXRemoveWindowFromWindowMovementGroup: window 0x38 is not attached to window 0x3e
16/4/13 下午1:37:27.160 ShadowsocksX[802]: Connecting clients1.google.com
16/4/13 下午1:37:34.129 WindowServer[183]: _CGXRemoveWindowFromWindowMovementGroup: window 0x38 is not attached to window 0x3e
16/4/13 下午1:37:34.405 ShadowsocksX[802]: Connecting r11---sn-a5m7lne7.googlevideo.com
16/4/13 下午1:37:34.432 ShadowsocksX[802]: Connecting s.youtube.com
16/4/13 下午1:37:34.454 ShadowsocksX[802]: Connecting www.youtube-nocookie.com
16/4/13 下午1:37:34.465 ShadowsocksX[802]: Connecting r17---sn-5hnednez.googlevideo.com
16/4/13 下午1:37:36.742 ShadowsocksX[802]: Connecting r11---sn-a5m7lne7.googlevideo.com
16/4/13 下午1:37:36.814 ShadowsocksX[802]: Connecting r11---sn-a5m7lne7.googlevideo.com
16/4/13 下午1:37:36.815 ShadowsocksX[802]: Connecting r11---sn-a5m7lne7.googlevideo.com
16/4/13 下午1:37:46.894 com.apple.WebKit.WebContent[1097]: [13:37:46.893] fragManifold_PushBytes signalled err=-16046 (kFigManifoldError_UnexpectedInitData) (Second 'ftyp' atom encountered) at /Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-1731.15.202/Prototypes/FormatHandlers/Movie/FigMovieFragmentManifold.c line 1680
16/4/13 下午1:37:53.567 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:53.567 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:53.567 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:53.567 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:54.382 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:54.382 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:54.382 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:54.382 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:54.831 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:54.831 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:54.831 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:54.831 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:55.592 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:55.592 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:55.592 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:55.592 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:58.447 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:58.447 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:58.447 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:58.447 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:58.585 launchservicesd[80]: SecTaskLoadEntitlements failed error=22
16/4/13 下午1:37:59.079 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:59.079 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:37:59.079 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:37:59.079 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:38:01.055 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:38:01.055 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:38:01.055 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:38:01.055 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:38:01.711 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:38:01.711 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:38:01.711 Dock[313]: CGSConnectionByID: 0 is not a valid connection ID.
16/4/13 下午1:38:01.711 Dock[313]: Invalid Connection ID 0
16/4/13 下午1:38:03.776 launchservicesd[80]: SecTaskLoadEntitlements failed error=22
16/4/13 下午1:38:10.981 WindowServer[183]: _CGXRemoveWindowFromWindowMovementGroup: window 0x38 is not attached to window 0x3e
16/4/13 下午1:38:15.043 Console[1095]: Type selection took over 1.000 seconds. Stopping early....

**Comment by chenshaoju** [comment]
请尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.133/job/h189bju1e18bukk7/artifacts

**Comment by Skefei** [comment]
it dosenot work..
觉得要放弃了..

**Comment by chenshaoju** [comment]
看起来很像加密方式或者密码不对……

我不知道了。。。看起来很像服务器的问题。

**Comment by GangZhuo** [comment]
是否是防火墙阻止了？

**Comment by Skefei** [comment]
可是服务器没更改，Mac和debian都能连接的，，
我已然放弃windows10，今天晚上回去再装debian吧，虽然慢很多，至少能FQ，windows10没法用目前开来windows限制颇多就不折腾了

**Comment by garywzh** [comment]
这些日子丢包率太高了，不知道是ISP的问题，还是GFW的问题，还是ISP和GFW是同一个问题。

**Comment by Skefei** [comment]
debian 8.4 连接不能，，，
单位Mac可以连接，，
宿舍windows10，debian8.4 只能连接developer.android.com；
谷歌，Y2B都是访问不能，，
上回看到有人说是因为大家都有finalspeed  搞的普遍网速差..
不明真相
