### ISSUE TITLE
家里断网，但是ss还在连接状态，试图上网时fan

### ISSUE THREAD

**Issue by Iluvenis** [shadowsocks/shadowsocks-windows#535]

**Comment by Iluvenis** [comment]
（抱歉不小心按了Enter键）
家里断网，但是ss还在连接状态，试图上网时提示Proxy Error页面，能不能加入检查网络连接的功能，在断网时返回正确的页面
就是ERR_INTERNET_DISCONNECTED这个代码

**Comment by wongsyrone** [comment]
Restart the program should be better.
