### ISSUE TITLE
win10 无法设置开机自启动

### ISSUE THREAD

**Issue by yanglw** [shadowsocks/shadowsocks-windows#540]
系统版本：Windows 10 64-bit Pro
Shadowsocks 版本：`2.2.1` 、`2.5.2` 、`3.0`

Shadowsocks 一直固定放在一个文件夹中，之前的开机自启动没有问题，而且电脑平时很少关机。几次升级 Shadowsocks 之后，发现电脑开机之后，Shadowsocks  不会自启动。来回更换了几个版本的 Shadowsocks  发现没有任何效果。

每次打开 Shadowsocks  ，勾选 `开机启动` ，然后退出 Shadowsocks 并重新打开。发现 `开机启动` 项为未勾选状态。

ps: 每次切换 Shadowsocks  版本之前，都清除了注册表中的以 `shadowsocks` 为关键字的搜索结果。

**Comment by chenshaoju** [comment]
该问题无法复现，请检查是否有安全软件拦截了Shadowsocks的注册表修改。
请尝试最新的测试版：　https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/n9w50mit2v1ds52f/artifacts

**Comment by yanglw** [comment]
我的问题，我关掉金山卫士之后，在设置 `开机启动` 就可以了。

然而，我记得，我一直都是设置金山卫士为 Shadowsocks 放行的。实际上，金山卫士，依旧拦截了 Shadowsocks ，现在已经把金山卫士卸载了。

**Comment by Pursue-Nymph** [comment]
我打开360安全管家全部的开机启动项，包括那些系统安全服务和应用软件服务，重启了两次，才看到Shadowsocks的开机启动项，然后Shadowsocks提示更新4.16版本（之前的是4.08），再次重启了之后就能用了。。。。  然后用360关掉那些没用的就行了
![TIM截图20190609021255](https://user-images.githubusercontent.com/51444480/59150830-2b531400-8a5c-11e9-9ebf-f7c3e7979454.png)
