### ISSUE TITLE
3.0版本是否支持直接游戏和软件的加速？

### ISSUE THREAD

**Issue by zaiweijian** [shadowsocks/shadowsocks-windows#541]
还需要其他软件吗？比如Proxifier

**Comment by GangZhuo** [comment]
应该需要看游戏是否支持代理吧

**Comment by zaiweijian** [comment]
@GangZhuo 意思就是不是所有游戏都能只有ss客户端加速？不支持的游戏就必须使用其他软件了吗？

**Comment by GangZhuo** [comment]
SS 只是提供了代理。如果游戏不支持使用代理的话，就需要其他软件来让游戏流量通过代理转发，如果游戏支持代理的话，应该是在游戏中设置一下就行了。

**Comment by GangZhuo** [comment]
SS 本身是支持 tcp 和 udp 的。

**Comment by zaiweijian** [comment]
@GangZhuo 谢谢
