### ISSUE TITLE
一次性认证（实验性）的作用是什么？

### ISSUE THREAD

**Issue by reaCodes** [shadowsocks/shadowsocks-windows#542]
没有搜索到相关资料，所以来这边问问。

一次性认证有什么作用？又如何正确使用，需要和服务器端配置改动么？

**Comment by qhfls** [comment]
https://shadowsocks.org/en/spec/one-time-auth.html

**Comment by hahahahahuo** [comment]
英文读完真心含糊

2016-04-24 18:18 GMT+08:00 lefty <notifications@github.com>:

**Comment by lixingcong** [comment]
我是自学《加密学》才知道，这个one-time auth选项开启可以抵抗CCA攻击

> 跟我一起学Coursera的[斯坦福公开课Crypto](https://www.coursera.org/learn/crypto/home/welcome)！

**Comment by reaCodes** [comment]
读完了只了解了大概原理作用，还是没有使用方法啊

**Comment by qhfls** [comment]
https://zhaoting.li/archives/3.html
2016年4月24日 下午8:19，"reaCodes" <notifications@github.com>写道：

**Comment by Mygod** [comment]
"auth": true

**Comment by reaCodes** [comment]
@qhfls Python版ss有ota功能吗，如何开启？

**Comment by qhfls** [comment]
@reaCodes https://github.com/shadowsocks/shadowsocks/wiki/Feature-Comparison-across-Different-Versions
先阅读一遍wiki，善用google
