### ISSUE TITLE
新版本(v3)有时候会卡掉啊!

### ISSUE THREAD

**Issue by kxmp** [shadowsocks/shadowsocks-windows#543]
有时候用着用着突然就啪! 进程自动退出了!!
也没错误提示.
不过系统留下了dump.
[1596.dmp.zip](https://github.com/shadowsocks/shadowsocks-windows/files/234528/1596.dmp.zip)

**Comment by chenshaoju** [comment]
请尝试禁用右键菜单中的服务器项目中的 Enable Statistics 。

**Comment by kxmp** [comment]
@chenshaoju 好像没这个菜单啊. 只有一个统计配置

**Comment by chenshaoju** [comment]
打快了……
