### ISSUE TITLE
C#版编译好的有鬼吗？搬瓦工

### ISSUE THREAD

**Issue by bdqlaccp** [shadowsocks/shadowsocks-windows#544]
C#版编译好的有鬼吗？
搬瓦工被搞死了...搬瓦工一年就能复活三次。第一没看细看，直接重启了，第二次发现是垃圾邮件。禁了25端口。结果还是无效，又被停了，第三次直接重装系统了！！还是垃圾邮件，又被封了！！这下死彻底了！！

按理说！！我系统都重装了，密码都换了。服务端不可能有问题啊！！那就是客户端出鬼了？

**Comment by chenshaoju** [comment]
１.不要用默认端口。
２.使用至少８位的强密码。
３.建议使用AES-256-CBF或RC4-MD5加密方式。

你不会在服务器上同时部署了服务端和客户端把？

**Comment by GangZhuo** [comment]
可以检查代码后，自行编译。

**Comment by kimw** [comment]
In my opinion, it's maybe an email service issue normally.

As a relay-able service, your server relay emails from others in SMTP protocol unless your server listen on localhost.

In short, a un-configured smtp service will almost relay emails world wild. It's spam.

To solve this problem you can stop your SMTP service, or just listen on localhost, or config your SMTP service.

FYI, [Simple Mail Transfer Protocol](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol) wikipedia.

**Comment by bdqlaccp** [comment]
@chenshaoju  客户端 不可能装服务器上啊！不许期负我小白......
-----------------------------------------------------------------------------------------------------------
貌似找到原因了！问题应该是出在了 wordpress 我想着 SS 服务 浪费资源了，搭了个 个人博客，用的wordpress！
新买了一个 没装wordpress,运行一天了 目前没事。既续观察。

**Comment by kimw** [comment]
@bdqlaccp 
How many services are here in your VPS? Dose SMTP listen on the public IP of your VPS?

You can find the services running on your VPS by type `sudo netstat -alptun | grep LISTEN` in your VPS. And it'll report something like following.

```
$ sudo netstat -alptun | grep LISTEN
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      7270/nginx -g daemo
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3557/sshd
tcp        0      0 0.0.0.0:8388            0.0.0.0:*               LISTEN      5576/python
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      7270/nginx -g daemo
tcp6       0      0 :::443                  :::*                    LISTEN      7270/nginx -g daemo
tcp6       0      0 :::22                   :::*                    LISTEN      3557/sshd
tcp6       0      0 :::80                   :::*                    LISTEN      7270/nginx -g daemo
```

The 4th column shows up the IPv4/IPv6 address and port the services listen on, last column is the application which is listening.

In your VPS, there should *NOT* be any service listen on port 25. For example, if your VPS reports like,

```
$ sudo netstat -alptun | grep LISTEN
...
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      364/master
tcp        0      0 :::25                   0.0.0.0:*               LISTEN      364/master
...
```

There must something wrong.

**Comment by bdqlaccp** [comment]
@kimw  thank you answer!!
===
现在已确定 问题出在了 wordpress 身上！ 我用的 (lnmp一键环境安装 )lnmp.org 。然后布署了一个 wodepress  4.5版 个人站点。  正查看 wodepress  。 伤了个心
