### ISSUE TITLE
[已解决]win7 SP1 64位 版本3.0一打开就提示SS已停止工作

### ISSUE THREAD

**Issue by chnp101** [shadowsocks/shadowsocks-windows#545]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	3.0.0.0
  问题签名 03:	56d65064
  问题签名 04:	Shadowsocks
  问题签名 05:	3.0.0.0
  问题签名 06:	56d65064
  问题签名 07:	1a7
  问题签名 08:	0
  问题签名 09:	System.IO.FileLoadException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by chnp101** [comment]
用 @chengshaoju 提供的3.0可以成功运行

**Comment by chenshaoju** [comment]
如果你的配置文件为旧Shadowsocks的，可能会存在该问题，最简单的方法是重命名或删掉后再启动Shadowsocks即可。

**Comment by chnp101** [comment]
这招试过了，没用┐(－_－)┌
必须得用你发的那个版本

**Comment by chenshaoju** [comment]
／安抚
此页面末尾有一个Close的按钮，按一下就会自动关闭此帖。

**Comment by liucongvg** [comment]
请问如何完全卸载之前安装的shadowsocks呢？win7，谢谢。

**Comment by liucongvg** [comment]
@chenshaoju ，非常感谢能告知卸载shadowsocks的方法，win7，shadowsocks版本：2.5.6，谢谢。

**Comment by studylinus** [comment]
@chenshaoju 怎么办，求助？
问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	4.0.7.0
  问题签名 03:	5a2b6f10
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	4d92ee5e
  问题签名 07:	1204
  问题签名 08:	89
  问题签名 09:	System.TypeLoadException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by chenshaoju** [comment]
@studylinus 请确保安装了 Microsoft .NET Framework https://www.microsoft.com/net/download/dotnet-framework-runtime ，以及32位（x86）版的Microsoft Visual C++ 2015 Redistributable https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by studylinus** [comment]
我是win7 64位系统，怎么要安装32位Microsoft Visual C++ 2015 Redistributable ？

**Comment by chenshaoju** [comment]
![image](https://user-images.githubusercontent.com/515763/41498341-b10ec96e-719d-11e8-938e-a9e031b1e8cb.png)

下载完成后按照提示安装。

**Comment by studylinus** [comment]
糟糕，安装了64位Microsoft Visual C++ 2015 Redistributable ，仍无法启动？

问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	4.0.7.0
  问题签名 03:	5a2b6f10
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	4d92ee5e
  问题签名 07:	1204
  问题签名 08:	89
  问题签名 09:	System.TypeLoadException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by chenshaoju** [comment]
请确保安装了 Microsoft .NET Framework https://www.microsoft.com/net/download/dotnet-framework-runtime

**Comment by studylinus** [comment]
刚才卸载了64位又安装了32位Microsoft Visual C++ 2015 Redistributable，还不行？是不是因为安装了64位的Microsoft .NET Framework 4.0.30319？

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 需要至少 4.6.2 版本的Microsoft .NET Framework，个人建议安装最新版以避免安全问题。

**Comment by studylinus** [comment]
@chenshaoju 谢谢，真乃大师大神大侠！问题已经解决。

**Comment by kkk8574990** [comment]
太牛逼 感谢分享

**Comment by cheneyz1127** [comment]
太牛逼嗷感谢分享
