### ISSUE TITLE
win10 上面 3.0 各种崩溃 你也不不要叫我去debug了你们自己看原因吧！

### ISSUE THREAD

**Issue by devyangyi** [shadowsocks/shadowsocks-windows#546]
win10 上面 3.0 各种崩溃 你也不不要叫我去debug了你们自己看原因吧！

**Comment by chenshaoju** [comment]
右击任务栏托盘区的纸飞机图标，选择服务器、统计配置，然后取消“Enable Statistics”和“Ping Test”，然后点击OK。

**Comment by orvice** [comment]
Removed according to regulations.

**Comment by timchen1974** [comment]
是的，很慢的。

**Comment by rayzi4hu** [comment]
我也是WIN10.3.0是上不了..

**Comment by GangZhuo** [comment]
See https://github.com/shadowsocks/shadowsocks-windows/issues/550
