### ISSUE TITLE
Please introduce statistics feature

### ISSUE THREAD

**Issue by zyf0330** [shadowsocks/shadowsocks-windows#547]
Please introduce statistics feature. How does it work and for what?

**Comment by GangZhuo** [comment]
There are some issues on statistics feature, please do not use it until next release.

**Comment by zyf0330** [comment]
oh，I know.

On Thu, Apr 28, 2016, 21:36 Gang Zhuo <notifications@github.com> wrote:

> There are some issues on statistics feature, please do not use it until
> next release.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/shadowsocks/shadowsocks-windows/issues/547#issuecomment-215424434>
>
-- 

追随
