### ISSUE TITLE
ss 在windows 上我基本都是用来设置代理哦。但是有个需求。

### ISSUE THREAD

**Issue by heartacker** [shadowsocks/shadowsocks-windows#548]
就是我不能添加其他的http 或者socks 5 代理。。只能添加ss代理。这导致我使用ss服务器很方便，但是使用http 或者socks 的时候，就得去系统设置里面设置了。

非常不方便。希望能够增加一个feature就是ss可以直接添加上述（http socks）的服务器。这样我就方便在系统通知栏切换了。

![qq 20160429132841](https://cloud.githubusercontent.com/assets/1876302/14908790/60dc718e-0e0e-11e6-9257-54bdd2dec63a.png)
![qq 20160429132748](https://cloud.githubusercontent.com/assets/1876302/14908789/60da16be-0e0e-11e6-843e-10a3052e41a4.png)

不知道是否明白我的意思。我不单单用ss，如果增加我说的功能的话。这个工具同样就方便我设置其他代理了。谢谢谢谢

**Comment by chenshaoju** [comment]
你好，你可以通过在 user-rule.txt 文件里添加自己的PAC来实现这个功能。
右击->PAC->编辑 GFWList 的用户规则

**Comment by heartacker** [comment]
不懂rule的就不知道如何写了。要是可以直接添加http sock服务器就好了，而不是只能添加ss服务器。

**Comment by GangZhuo** [comment]
No plan
