### ISSUE TITLE
由于目标计算机积极拒绝，无法连接.

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-windows#549]
win7 64位。shadowsocks2.5.6 chrome使用 proxyswitchsharp

但是总是断断续续。一会能用一会不能用的。总得来回换服务器。日志上要么显示time out 要么就是显示由于目标计算机积极拒绝，无法连接。怎么办。

**Comment by huangziwen** [comment]
电脑上没有迅雷昨天刚重装的系统

**Comment by chenshaoju** [comment]
请尝试Ping你的服务器，看看延迟情况。

**Comment by huangziwen** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\hs>ping www.google.com

正在 Ping www.google.com [216.58.197.100] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

216.58.197.100 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

是这样的。谢谢

**Comment by chenshaoju** [comment]
你的服务器Ｇｏｏｇｌｅ吗？

**Comment by huangziwen** [comment]
字节=32 时间=90ms TTL=45
字节=32 时间=85ms TTL=45
: 字节=32 时间=99ms TTL=45
请求超时。

的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 3，丢失 = 1 (25% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 85ms，最长 = 99ms，平均 = 91ms

这个是服务器地址。刚才不会ping。感觉线路应该是没有问题的。但是不知道是哪里的问题。我选的是pac模式，chrome用了插件创建了一个情景模式。跟官网上一样

**Comment by chenshaoju** [comment]
你的服务器丢包率在25%左右。很一般。
可能是线路问题。你可以在Ping参数末尾后加上 -t 参数，一直Ping，比如：
ping 123.45.67.89 -t
看看丢包率多少。

**Comment by huangziwen** [comment]
一直在ping啊。还没停。目前看着是七八个丢一个的水平吧

**Comment by huangziwen** [comment]
一共276 丢了19个

**Comment by chenshaoju** [comment]
看起来也不是很严重。

你的服务器是你自己搭建的，还是第三方的服务？如果是你自己搭建的，详见：

https://gist.github.com/chenshaoju/b0e20f23efabb8eb2cd4

**Comment by huangziwen** [comment]
第三方，买的一年的那种。断断续续的吧。我感觉线路没问题。好的时候720p是流畅的。就是不持续。

**Comment by chenshaoju** [comment]
可能是服务器负载问题。

**Comment by huangziwen** [comment]
哦。谢谢你

**Comment by lowboy** [comment]
我和朋友最近也都出现了这个问题，服务器都是RamNode 128M的方案，服务端是pip安装的ss，问题的原因是**`服务器端ssserver自动关闭`**，目前不知道如何解决，只能不断手动开启了。

**Comment by wongsyrone** [comment]
线路问题SS也没有办法

**Comment by is1and** [comment]
把服务端 端口配置成其他端口 原来是8838 换成443重启服务解决

**Comment by kyan001** [comment]
`由于目标计算机积极拒绝，无法连接。`

出现这个提示的原因是你本机的 shadowsocks 连接的远程服务器不可用。
因此不是你本机的问题，是远程服务器的问题！！

**Comment by 198994** [comment]
你可以重新设置一个端口，在服务器端，就可以了。
