### ISSUE TITLE
Privoxy Error

### ISSUE THREAD

**Issue by Fezreal** [shadowsocks/shadowsocks-windows#553]
![qq 20160502191433](https://cloud.githubusercontent.com/assets/6703674/14953245/5c99ae64-109a-11e6-96eb-82c1880a8161.png)

用的是最新的1.0.137
我记得这个错误最开始是出现在2.5.4还是2.5.6来着。。

**Comment by chenshaoju** [comment]
你是不使用了什么清理系统垃圾的东西？如果是，并且你不愿意停止此类功能，请让Shadowsocks工作在便携模式（Portable）。

**Comment by Fezreal** [comment]
@chenshaoju    请问怎么开启便携模式？

**Comment by chenshaoju** [comment]
在 shadowsocks.exe 所在目录新建一个文本文件，将其命名为 shadowsocks_portable_mode 。
如果你显示了扩展名，则是 shadowsocks_portable_mode.txt ，然后重试。

**Comment by Fezreal** [comment]
@chenshaoju 请问大概是什么文件被清理了才会出现这样的错误？

**Comment by cqhtyi** [comment]
@Fezreal 你的图片上已经写了：privoxy.conf

**Comment by Fezreal** [comment]
@cqhtyi  有什么办法让shadowsocks.exe再次释放一个privoxy.conf？

**Comment by wongsyrone** [comment]
Try portable mode or check `%TEMP%` folder before cleaning.
