### ISSUE TITLE
配置文件中出现两个ip,密码等信息完全一致，备注不一样的时候，每次都报停，算是毕现的bug吧

### ISSUE THREAD

**Issue by inmyfree** [shadowsocks/shadowsocks-windows#554]
配置文件中出现两个ip,密码等信息完全一致，备注不一样的时候，每次都报停，算是毕现的bug吧

**Comment by GangZhuo** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/502

**Comment by wongsyrone** [comment]
建议还是重新tag一个3.0，许多重复的issue报告

**Comment by kimw** [comment]
#551
