### ISSUE TITLE
V3存在的自动退出问题

### ISSUE THREAD

**Issue by 772807886** [shadowsocks/shadowsocks-windows#556]
就在最近偶尔出现，用着用着就用不了了，程序自动退出了，右下角的图标还缓存在那，但鼠标移过去就没了。
点开日志会有这样的异常：
[2016-05-04 18:33:44] System.IO.IOException: 文件“C:\Users\Liming\AppData\Local\Temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()

**Comment by chenshaoju** [comment]
请尝试让Shadowsocks工作在便携模式(Portable)。
详见： https://github.com/shadowsocks/shadowsocks-windows/issues/553 四楼

**Comment by wongsyrone** [comment]
Try portable mode or terminate ss_privoxy.exe before restarting shadowsocks-windows.
