### ISSUE TITLE
3.0版本用那三行代码重置后重启后能用，过了几天又不行了。

### ISSUE THREAD

**Issue by whateding** [shadowsocks/shadowsocks-windows#557]
3.0版本用那三行代码重置后重启后能用，过了几天又不行了，电脑上装了迅雷极速版

**Comment by chenshaoju** [comment]
请尝试升级到最新版的迅雷。或者停止 XLPlatform 服务。

详见： http://yangtai.xunlei.com/?p=10120

**Comment by mk6012** [comment]
同样的问题，之前安装过迅雷，卸载了的也要安装一下最新版？

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/476

**Comment by GangZhuo** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/620
