### ISSUE TITLE
[2016-05-08 20:03:10] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败

### ISSUE THREAD

**Issue by luniard** [shadowsocks/shadowsocks-windows#562]
V2.5.8 win7/10
mac 下可以使用

[2016-05-09 20:40:24] Shadowsocks started
[2016-05-09 20:41:00] lu (**:1080) timed out

**Comment by chenshaoju** [comment]
请检查你的客户端的服务器配置是否正确（IP、加密方式、密码端口 etc... ）

**Comment by SherlockLee** [comment]
把Shadowsocks关闭再重新打开就好了，不清楚具体原因，这样可以解决这个问题。

**Comment by LeoStark** [comment]
楼主解决问题了吗？

**Comment by kghch** [comment]
尝试重启ss似乎没什么用，气急败坏下重启了本本，发现连接已正常。（ping 服务器一直是没问题的）
