### ISSUE TITLE
SS怎么支持网游？

### ISSUE THREAD

**Issue by LeungHEX** [shadowsocks/shadowsocks-windows#563]
有人说要有UDP转发，但是我买的服务器是支持的，用了proxifier开启战地 NFS系列游戏失败，不知道是什么原因造成的？

**Comment by chenshaoju** [comment]
Proxifier好像不支持UDP代理：
https://www.google.com/#newwindow=1&safe=off&q=UDP+site:proxifier.com

**Comment by cicku** [comment]
Proxifier doesn't support UDP protocol, please use ProxyCap.

**Comment by LeungHEX** [comment]
然而用cap 战地4会提示请打开3459(udp)服务器被禁了？还是udp转发不成功？

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-windows/tree/master#udp

**Comment by haodong** [comment]
> 而Shadowsocks代理虽然服务器支持udp relay但是目前所有的Shadowsocks客户端都不支持UDP.
> http://www.sockscap64.com/en/help

This issue is still unsolved.

**Comment by pexcn** [comment]
OpenWrt版支持UDP
