### ISSUE TITLE
Shadowsocks 错误: 端口已被占用

### ISSUE THREAD

**Issue by Tzwcard** [shadowsocks/shadowsocks-windows#564]
今天使用SS发现以下提示
netstat查过了 没有程序在listen我设置的默认端口(1080)
将SS的listen端口换了一下还是出现这个提示 看起来是跟端口占用无关

上个星期的时候SS还能正常使用的
用另一台正在正常使用SS的电脑上的config.json还是出错
SS是2.5.8,换成3.0和2.5.2都是出这个提示 应该跟SS本身无关

不知道会不会跟Win10的自动升级有关
有没有人遇到过然后解决掉的？

> ---------------------------
> Shadowsocks 错误: 端口已被占用
> ---------------------------
> System.Exception: 端口已被占用 ---> System.Net.Sockets.SocketException: 以一种访问权限不允许的方式做了一个访问套接字的尝试。
> 
>    在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
> 
>    在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
> 
>    在 Shadowsocks.Controller.Listener.Start(Configuration config)
> 
>    在 Shadowsocks.Controller.ShadowsocksController.Reload()
> 
>    --- 内部异常堆栈跟踪的结尾 ---
> ---------------------------
> 确定   
> ---------------------------
>

**Comment by chenshaoju** [comment]
该问题高度可能是由于你的 1080 端口被其他程序使用了，请仔细检查 netstat 信息：
netstat -ano -p tcp
```
netstat -ano -p tcp >list.txt
findstr 1080 list.txt
```

**Comment by chenshaoju** [comment]
你是不是装了迅雷？
https://github.com/shadowsocks/shadowsocks-windows/issues/241

**Comment by Tzwcard** [comment]
并没有安装迅雷
切换到另一个网卡 重启电脑 重装协议 什么都试一次之后就忽然又能用了 原因还是不明

**Comment by celeron533** [comment]
记得苹果也有两个服务在使用时会临时占用1080口，我也曾遇到过。最后还是推荐换一些大一点的端口号

**Comment by vincentdd** [comment]
我今天也遇到了，查出来的pid并没有在任务管理器里找到，状态显示close wait，系统是win7 64位的
