### ISSUE TITLE
shadowsoks 3.0 does't work on IPv6

### ISSUE THREAD

**Issue by Jiaogniao** [shadowsocks/shadowsocks-windows#568]

**Comment by chenshaoju** [comment]
Is not support IPv6 Shadowsocks server IP address,or not support access IPv6 website?

![unnamed qq screenshot20160515233105](https://cloud.githubusercontent.com/assets/515763/15275112/4d0ffe8e-1af5-11e6-84a1-f50d09b9ac2f.png)

**Comment by wongsyrone** [comment]
No response from origin reporter, closing.
