### ISSUE TITLE
部分windows系统代理失败，无法实现FQ

### ISSUE THREAD

**Issue by msls** [shadowsocks/shadowsocks-windows#570]
部分windows系统启动客户端后，浏览器无法打开网页，以下为详细的日志，哪位帮忙给看看
![qq 20160515094050](https://cloud.githubusercontent.com/assets/16952161/15283907/832e6f60-1b80-11e6-84a4-acbb0158f976.png)
![qq 20160515094142](https://cloud.githubusercontent.com/assets/16952161/15283906/81fce2c0-1b80-11e6-908d-62e43468fa3f.png)

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/476
