### ISSUE TITLE
3.0突然出现这种情况

### ISSUE THREAD

**Issue by charshine** [shadowsocks/shadowsocks-windows#572]
[2016-05-18 10:21:39] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()

**Comment by chenshaoju** [comment]
请尝试： https://github.com/shadowsocks/shadowsocks-windows/issues/571#issuecomment-219605828

**Comment by wongsyrone** [comment]
Please test https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe
