### ISSUE TITLE
用一段时间后会无法连接，需要连一下目标机器的ssh

### ISSUE THREAD

**Issue by eromoe** [shadowsocks/shadowsocks-windows#574]
RT，经常出现用了一段时间，就出现500 proxy 什么什么的错
然后我用putty连一下 ss服务器，就又好了
这是什么问题？

**Comment by chenshaoju** [comment]
可能是你的服务器死了。
请检查服务端的程序情况。

**Comment by eromoe** [comment]
服务器死了？
ss服务端用supervisor 挂着的，不可能死的啊，我还挂一个个人用的网站呢

**Comment by chenshaoju** [comment]
可能是进程死了？
你能用putty一直连着，然后用 htop 或 top 检测你的SS服务端进程情况吗？

**Comment by eromoe** [comment]
putty 连一段时间也会死的。。。网络不稳定。。。
我想说的是shadowsocks 客户端连接失败了，重新发起请求应该能连接成功
为什么一定要ssh连接成功了，才能触发 shadowsocks连接成功。。。很奇怪

**Comment by eromoe** [comment]
PS:如果开启 finalspeed 这样的双向加速软件实时保持连接，倒是不会断

**Comment by chenshaoju** [comment]
所以可能是你的服务端的问题。
也可能是网络问题，客户端问题的可能性很小，这么多人都在用，如果是广泛问题的话，Issues早就刷爆了。

**Comment by eromoe** [comment]
我在家里win7 就没有这个问题。。。在公司win8.1 跟系统有关系么？

**Comment by chenshaoju** [comment]
你公司有网络审查系统吗？我怀疑有某种过滤。

**Comment by eromoe** [comment]
不知道啊。。。。

**Comment by chenshaoju** [comment]
╮（╯＿╰）╭  不知道了，要么是你公司的网络有过滤，要么网络有问题。

**Comment by wongsyrone** [comment]
看看ss主程序的属性，是不是有个解除锁定的按钮或者复选框

**Comment by eromoe** [comment]
真有解除锁定。。。以前碰到有解除锁定的是个炉石挂，不解除就开不起来
这个不解除居然能运行。。。我先解除试试

**Comment by eromoe** [comment]
跟解除锁定没关系就是了。。

**Comment by Musecanyang** [comment]
解决了吗，我也遇到了这个问题。 连接SSH上网正常，关闭后也是正常的。但是一段时间不使用，在上网就会报超时。重新连接下SSH，不做任何操作。在上网就正常了

**Comment by eromoe** [comment]
没有至今都会这样，用ssr的客户端就没问题

**Comment by niko-liu** [comment]
一样的问题，现在真的没有什么办法，开始以为是socket回收的问题，是不是timeout设置过长，端口设置太高，密码没有频繁变化。后来发现根本不关事，就是ssh连一下，然后断开又可以正常用了，应该是触碰到了防火墙某个策略
