### ISSUE TITLE
更新到3.0以后无法Firefox浏览器没办法通过ss上网了

### ISSUE THREAD

**Issue by fhzheng** [shadowsocks/shadowsocks-windows#575]

**Comment by chenshaoju** [comment]
你好，手动指定代理呢？

**Comment by fhzheng** [comment]
@chenshaoju 用各种方法切换代理都不行。
在ff浏览器中有【使用系统代理】【无代理】【自动检测代理】【手动指定代理】四种方法，但是现在全都无法使用。
我重装了系统，还是不行。

**Comment by chenshaoju** [comment]
这个样仍然不行？请注意，1080为示例，你需要按照你的实际端口来看。

![unnamed qq screenshot20160519212342](https://cloud.githubusercontent.com/assets/515763/15394901/fe1272d8-1e07-11e6-8a00-d33973c094e9.png)

**Comment by fhzheng** [comment]
@chenshaoju 这样可以，但是有个问题就是，无法自动切换PAC上的域名列表了…

**Comment by chenshaoju** [comment]
该问题已知，是Firefox的问题。
如果你很着急要解决，请使用该版本的Firefox（测试版）：
https://nightly.mozilla.org/

**Comment by sparks11** [comment]
我linux系统，Chrome和opera都可以正常使用，只有firefox不行。
看来是firefox的问题
