### ISSUE TITLE
System.Reflection.TargetInvocationException: 调用的目标发生了异常。

### ISSUE THREAD

**Issue by jiangrushe1205** [shadowsocks/shadowsocks-windows#577]
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   在 System.Security.Cryptography.MD5.Create()
   在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   在 Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   在 Shadowsocks.Encryption.PolarSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.Local.Handle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
请尝试该版本： https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/hfas52l8mphj8h65/artifacts

**Comment by DearTanker** [comment]
@chenshaoju 你这个链接是不是放错了？

**Comment by wongsyrone** [comment]
这个链接是CI，如果你不放心可以自己编译

**Comment by chenshaoju** [comment]
@DearTanker 请自行编译。

**Comment by DearTanker** [comment]
@wongsyrone @chenshaoju 然而我技术盲，根本不会编译

**Comment by GangZhuo** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/381
