### ISSUE TITLE
3.0的速度问题

### ISSUE THREAD

**Issue by Moriaty911** [shadowsocks/shadowsocks-windows#578]
自从更新到3.0之后整个速度就变得异常慢，手机、mac端都能跑到1.5m左右而win端只有400kb。一开始以为是服务器问题，后来发现换成2.5.8之后速度立即提上来了。请尽早修复。

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/476

**Comment by GangZhuo** [comment]
禁用 Statistics 试试， 方法见 https://github.com/shadowsocks/shadowsocks-windows/issues/594#issuecomment-230434894 。

**Comment by wongsyrone** [comment]
Please test https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe
