### ISSUE TITLE
Windows 命令行提示符或者 Git Bash 怎么使用 PAC 模式？

### ISSUE THREAD

**Issue by Loyalsoldier** [shadowsocks/shadowsocks-windows#582]
SS 使用的是 PAC 模式。而命令行下操作，只有设置使用代理，流量才会自动走代理。而在命令行中设置了代理之后，好像并不会根据 PAC 规则，国内服务器直连……

请问，SS 在 PAC 模式下，命令行如何根据连接的服务器在国内和国外，分别直连和走代理？

BTW，我一般常用的命令行命令是 npm。npm 用的是国内淘宝提供的源，所以需要直连。但是很多链接需要到亚马逊云服务器上下载文件，这时候需要代理……由于我的 SS 服务在频繁网络 I/O 情况下不太稳定 ，所以希望不同情况下，能实现不同的自动连接方式。

**Comment by chenshaoju** [comment]
请查阅： https://github.com/shadowsocks/shadowsocks-windows/issues/407

**Comment by Loyalsoldier** [comment]
@chenshaoju 
我想确认一点：SS 是不是只有 Socks5 协议才会走 PAC？（如果是，那么假如命令行代理是支持 socks5 协议的，那么设置为 socks5 协议的代理后，就很方便）

另外，我是做前端的，经常使用到 Node 的包管理工具 npm。npm 设置 SS 的 http 代理后，所有网络 I/O 都会走 http 代理，不管我 PAC 里面有没有该 IP 的规则（我确定没有写错 PAC 规则）。

**Comment by chenshaoju** [comment]
我没有用过 npm ，请尝试：
https://docs.npmjs.com/misc/config#https-proxy

**Comment by GangZhuo** [comment]
通过 PAC 来选择是否通过代理来访问目标网络是由操作系统的系统代理部分来实现的。 软件是否支持代理也是由软件开发者自己实现，和 SS 无关。
