### ISSUE TITLE
用过迅游加速器后，3.0版似乎也会出问题，2.5.8一切正常

### ISSUE THREAD

**Issue by dragon100a** [shadowsocks/shadowsocks-windows#587]
#476 提到netsh winsock reset，这个命令倒是可以解决问题，但每次都这样就不太科学了。
新装电脑，使用3.0版一切正常。安装迅游后，启动加速，玩游戏，然后关闭迅游，再尝试3.0版，就无法访问了。使用2.5.8正常。

迅游使用的是模式4，客服给的说明如下：

> 模 式四，穿透能力强指的是能更快的通过防火墙等的限制 连接上迅游。由于模式四是采用的Socks 协议 TCP 与其他模式的网络协议不同，指在加速时的效 果也不会不同。考虑到每个用户的电脑环境和网络环境 不同，使用模式四在对某款游戏加速时，系统完成加速 的时间更快（不用模式三安装虚拟网卡之类的准备时间 ）迅游模式一、二、三基于VPN原理，模式四采用代 理的方式。

> 模式四会监听LSP，如果要清除迅游使用模式四对系统的影响，请右击开始菜单，选择“命令提示符（管理员）”，在命令提示符中输入netsh winsock reset（请参考附件）回车，成功后会提示“成功重置Winsock目录，您必须重启计算机才能完成重置”，重启电脑即可，感谢您的支持！

迅游用模式4之后，3.0版才会出问题。
和#476涉及到的方法一样。因此希望3.0是不是能改进一下。毕竟2.5.根本没这个问题。

**Comment by chenshaoju** [comment]
如果很着急要解决该问题，请尝试使用网易UU：http://uu.163.com/

**Comment by dragon100a** [comment]
看起来 已经知道/清楚 当前这个问题的 具体情况是 吗？
如果已知，那么我暂时换用258 好了。。等待你们解决问题就是了。

**Comment by chenshaoju** [comment]
LSP的问题目前没有解决方案。

**Comment by Noisyfox** [comment]
其实只要把打印Log的代码里所有涉及到socket.RemoteEndPoint的都注释掉就可以了。
不知道底层哪里有问题导致用了LSP会获取不到RemoteEndPoint

**Comment by Noisyfox** [comment]
其实就是
`Logging.Debug($"Socket connected to {remote.RemoteEndPoint}");`
这句话的问题。

**Comment by Noisyfox** [comment]
不过最新的代码已经用条件编译把这句话从Release版里去掉了，所以等下个版本发布就应该没有这个问题了

**Comment by dragon100a** [comment]
谢谢告之。目前一直用258版，但是每次都弹提示说有更新。。应该有个选项规定是否检测并提示更新的。

**Comment by RoachJoey** [comment]
跟进这个问题中……等新版本解决

**Comment by GangZhuo** [comment]
via https://github.com/shadowsocks/shadowsocks-windows/commit/a486514afb34d8045e714632f014399e45814a1b
