### ISSUE TITLE
3.0 不支持ipv6的服务器了吗

### ISSUE THREAD

**Issue by yiqixiaoxixi** [shadowsocks/shadowsocks-windows#588]
我所有的ipv6的服务器ip均不能正常使用

**Comment by chenshaoju** [comment]
理论上是支持的，你是如何配置的？ https://github.com/shadowsocks/shadowsocks-windows/issues/465

**Comment by yiqixiaoxixi** [comment]
jp01-1.ssv6.net 类似这样的ip

**Comment by chenshaoju** [comment]
我试了一下，这个IP不通。

![unnamed qq screenshot20160613100524](https://cloud.githubusercontent.com/assets/515763/15995461/567d7b08-314e-11e6-8d3b-12dfc27fd528.png)

**Comment by yiqixiaoxixi** [comment]
好吧，我也试了其他的，都ping不通了

**Comment by yiqixiaoxixi** [comment]
@chenshaoju  感谢你指出问题，应该是服务器的问题
