### ISSUE TITLE
3.0启动系统代理提示无法修改注册表

### ISSUE THREAD

**Issue by yesorno** [shadowsocks/shadowsocks-windows#589]
![qq 20160613122501](https://cloud.githubusercontent.com/assets/1220524/15997102/59e758d6-3162-11e6-88e5-a529133df78d.png)
![qq 20160613122929](https://cloud.githubusercontent.com/assets/1220524/15997107/7d1f41a6-3162-11e6-9024-8e10bdac7139.png)
![qq 20160613122935](https://cloud.githubusercontent.com/assets/1220524/15997109/7e4a9288-3162-11e6-909d-ce4093b172a8.png)

**已经设置为便携模式**

[2016-06-13 12:13:38] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.AutoStartup.Check()
失败的程序集的区域是:
MyComputer
[2016-06-13 12:13:43] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1080
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-06-13 12:13:45] Shadowsocks started
[2016-06-13 12:13:45] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.AutoStartup.Check()
失败的程序集的区域是:
MyComputer
[2016-06-13 12:22:02] Shadowsocks started
[2016-06-13 12:22:02] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.AutoStartup.Check()
失败的程序集的区域是:
MyComputer
[2016-06-13 12:22:11] Shadowsocks started
[2016-06-13 12:22:11] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.AutoStartup.Check()
失败的程序集的区域是:
MyComputer
[2016-06-13 12:22:28] Detected: PAC file 'pac.txt' was created.
[2016-06-13 12:22:45] Shadowsocks started
[2016-06-13 12:22:45] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.AutoStartup.Check()
失败的程序集的区域是:
MyComputer
[2016-06-13 12:23:24] Shadowsocks started
[2016-06-13 12:23:24] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.AutoStartup.Check()
失败的程序集的区域是:
MyComputer
[2016-06-13 12:23:32] Shadowsocks started
[2016-06-13 12:23:32] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.AutoStartup.Check()
失败的程序集的区域是:
MyComputer
[2016-06-13 12:23:42] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)

**Comment by chenshaoju** [comment]
在常规选项卡中，是否有一个解除锁定按钮？如果是，按一下解除锁定后再试？

**Comment by yesorno** [comment]
@chenshaoju 没有这个接触锁定按钮 右键“以管理员身份运行”也不行

**Comment by chenshaoju** [comment]
你是否使用了某些安全软件，比如金山毒霸？

**Comment by celeron533** [comment]
由于SS有自动释放 polipo/privoxy 代理程序的行为，且会修改启动项。很多时候一些安全软件会判定为疑似病毒或木马，进而阻止这种行为。

PS。
如果系统里安装了360那是作死。

**Comment by yesorno** [comment]
没有啊…没有装任何管家之类的安全软件，唯一的杀毒软件是MSE。

Allen Zhu <notifications@github.com>于2016年6月14日周二 下午10:41写道：

**Comment by wongsyrone** [comment]
检查用户权限及安全软件设置，使用原版系统。
