### ISSUE TITLE
使用电信校园网，看了几个YouTube视频被封

### ISSUE THREAD

**Issue by sunnoy** [shadowsocks/shadowsocks-windows#590]
使用ssh连接配置后，看了几个YouTube视频被封，于是更换vps机房以便换ip，并更新到3.0版本，现在还在使用中不知道会不会被封，这期间手机端安卓利用移动4g ss客户端都可以顺利上网，不知道怎么回事儿

**Comment by chenshaoju** [comment]
可能是你所在学校的流量或者人为监控。

**Comment by sunnoy** [comment]
貌似找到原因了，原来使用默认一键安装ss 现在自己安装ss - libev 并且配制端口，暂时还没有被封

**Comment by breakwa11** [comment]
@sunnoy 肯定不是安装方式的原因

**Comment by celeron533** [comment]
大流量ssh会被切断。
ssh隧道如果仅仅是用来做tty命令操作的话，一般不会有事。但你若是在隧道里传输大量内容，比如基于http的各种媒体，不但会产生巨大的流量，也会产生一些流量上的特征。然后就被方教授GG

**Comment by sunnoy** [comment]
那是我用默认配置的原因
