### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。

### ISSUE THREAD

**Issue by peimin** [shadowsocks/shadowsocks-windows#591]
System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   在 Shadowsocks.Controller.Handler.StartConnect()
[2016-06-13 22:46:41] 175.126.148.22:39632 timed out

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/524
