### ISSUE TITLE
[自娱自乐] 添加实时流量统计

### ISSUE THREAD

**Issue by celeron533** [shadowsocks/shadowsocks-windows#594]
可能有bug，有兴趣的朋友可以试试：（没开CI，需手工编译）
https://github.com/celeron533/shadowsocks-windows/tree/Traffic_Chart_and_Traffic_Icon

![image](https://cloud.githubusercontent.com/assets/3608762/16084060/ddb276f8-3349-11e6-95b7-3dde07f80fff.png)

增加：
60秒实时流量折线图。和log文字区装在一个splitcontainer，可调整大小。

系统托盘的纸飞机图标可动态显示流量状态：
* 黄块： 近1秒内有outbound流量发生
![image](https://cloud.githubusercontent.com/assets/3608762/16084539/c93d6f46-334b-11e6-8bb1-0a8c4fafc73e.png)

* 绿块： 近1秒内有inbound流量发生
![image](https://cloud.githubusercontent.com/assets/3608762/16084538/c699ec4c-334b-11e6-9f50-5d3f06fe137f.png)

**Comment by chenshaoju** [comment]
Interesting，你可以发一个Pull requests。

**Comment by celeron533** [comment]
图标的Y轴标识做了些许改进，稍后提交pull request
部分代码可能需要改进

![image](https://cloud.githubusercontent.com/assets/3608762/16106752/e153040a-33c9-11e6-8c34-7670924206a1.png)

**Comment by skyqty** [comment]
```
[2016-06-17 17:12:19] System.IO.IOException: 文件“C:\Users\XXXX\AppData\Local\Temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()
```

异常退出，包括3.0版本一样有同样错误

**Comment by chenshaoju** [comment]
@skyqty 请尝试使用便携版，你的TEMP文件夹可能存在某种保护：
在你的Shadowsocks.exe所在目录增加一个名为 shadowsocks_portable_mode.txt 的空文件（不是 shadowsocks_portable_mode.txt.txt），然后重启Shadowsocks。

**Comment by celeron533** [comment]
@skyqty 这应该还是现存的服务器统计的问题, 这次的流量统计应该不会有进程上的问题, 禁用服务器统计试试

**Comment by skyqty** [comment]
@chenshaoju 试过后 这段时间没有遇到问题

**Comment by hypogaea** [comment]
@chenshaoju 那个，还要麻烦你一下，两个Program Files，ProgramData，Windows，还有整个用户文件夹扫荡了个遍，也没找到临时文件在什么地方，我还没设置便携模式呢。。。

**Comment by celeron533** [comment]
用户的appdata下的temp文件夹

**Comment by hypogaea** [comment]
@celeron533 谢谢，原来是散落在文件夹里的啊，TEMP里一大堆文件和文件夹，怪不好找的

**Comment by skyqty** [comment]
又来了。。。，temp也已经在dropbox里面排除了
崩溃时出现时的操作：打开日志--关闭--崩溃
```
System.IO.IOException: 文件“F:\Sync File\Dropbox\Tools\Proxy\Shadowsocks-win-dotnet4.0-2.0.11\temp\ss_privoxy.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 Shadowsocks.Controller.FileManager.UncompressFile(String fileName, Byte[] content)
   在 Shadowsocks.Controller.PolipoRunner..cctor()
```

**Comment by celeron533** [comment]
@skyqty 这个问题是由于服务器可靠性统计引起的，不是由于这次的功能而引起的。

禁用服务器可靠性统计即可

![image](https://cloud.githubusercontent.com/assets/3608762/16580752/a094adf6-42d8-11e6-8858-0d72538f9328.png)

![image](https://cloud.githubusercontent.com/assets/3608762/16580765/aca357d2-42d8-11e6-883d-6187dcba26d6.png)

**Comment by celeron533** [comment]
Bug found in #639, fixed in PR #641
