### ISSUE TITLE
3.0版本突然不能使用，又用回2.5.8

### ISSUE THREAD

**Issue by kn007** [shadowsocks/shadowsocks-windows#596]
Windows 10 Pro Release系统，最近一次更新后，不行。
```
KB3149135
KB3163018
KB890830
```
服务端返回reset by peer。用回2.5.8正常。

找一台电脑新装Windows 10 Build 14342，用3.0正常。

搞不明白了，有什么debug方法么？

**Comment by kn007** [comment]
尝试用
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
3.0又可以正常用，但重启后就又挂了。。

**Comment by kn007** [comment]
把LOL的网游加速助手卸掉后正常了。我晕。

**Comment by chenshaoju** [comment]
我在我的Win10上测试了一下，没有该问题，补丁列表如图……

![2016-06-18](https://cloud.githubusercontent.com/assets/515763/16171345/246b315a-359f-11e6-9b56-f5719b062814.png)

你试试这里下载的版本（测试版）：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/9fe2hd4yre1wxc3x/artifacts

**Comment by kn007** [comment]
@chenshaoju 谢谢，我一会试试~

**Comment by chenshaoju** [comment]
已知某些网游加速器，比如劫持SLP来进行加速的可能会有问题，建议试试网易UU，模式１和模式４都是常规模式，不劫持。
http://uu.163.com

**Comment by kn007** [comment]
@chenshaoju 3.1正常，没有问题！非常感谢。
