### ISSUE TITLE
为什么不能连接developer.android.com

### ISSUE THREAD

**Issue by dreamcc0817** [shadowsocks/shadowsocks-windows#598]

**Comment by chenshaoju** [comment]
你好，经过测试，没有问题。请与你的SS服务商取得联系。

![unnamed qq screenshot20160623103615](https://cloud.githubusercontent.com/assets/515763/16290239/5488912e-392e-11e6-8191-b51a4d677498.png)

**Comment by hypogaea** [comment]
@chenshaoju Shadowsocks从哪里可以获取最新版呀？这里可以吗？https://shadowsocks.org

**Comment by chenshaoju** [comment]
@hypogaea 你可以在 https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/9fe2hd4yre1wxc3x/artifacts 获得最新版本，注意，这是基于最新代码的自动编译版本，可能有BUG。

**Comment by hypogaea** [comment]
@chenshaoju 非常感谢。。。这个版本也是基于@clowwindy 的版本开发的吗？

**Comment by chenshaoju** [comment]
@hypogaea 这个我就不知道了……我并不是该项目的任何成员……

**Comment by hypogaea** [comment]
啊哈哈哈，没事，谢谢
