### ISSUE TITLE
扫描自己生成的二维码会停止运行

### ISSUE THREAD

**Issue by JaySun1314** [shadowsocks/shadowsocks-windows#599]
显示二维码
扫描屏幕上的二维码
崩溃
就是这么无聊。

**Comment by chenshaoju** [comment]
该问题已知，是由于添加了重复项导致的。
请使用最新版的测试版看看：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/9fe2hd4yre1wxc3x/artifacts

**Comment by GangZhuo** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/4325b7f6f9d706f8893feb32efbc9c36a60876d1
