### ISSUE TITLE
3.0 版 Could not load template file no-server-data or one of its included components.

### ISSUE THREAD

**Issue by tanxunrong** [shadowsocks/shadowsocks-windows#600]
当密码中多了个空白(tab)的时候
没有提示无法连接，
而是在wall外访问时出现这个问题，
还好咱看了下gui配置文件。
能给密码加个过滤吗?

**Comment by chenshaoju** [comment]
你好，最新版的测试版会自动将 tab 转义成 \t ，而关于密码过滤，由于SS的分支太多（libev、python等等），无法统一协调，暂时还不能确认。

关于最新版，你可以在 https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/9fe2hd4yre1wxc3x/artifacts 获取。
