### ISSUE TITLE
Cannot access to Tumblr.com

### ISSUE THREAD

**Issue by semonwu** [shadowsocks/shadowsocks-windows#602]
Hi Support,

I cannot access to Tumblr.com under VPN running. Could you put tumblr.com in FWG list by default because i failed to add it by manual. 

Thanks a lot.

**Comment by chenshaoju** [comment]
Hello.The PAC file is power by GFWList.You can put your issue to here:
https://github.com/gfwlist/gfwlist/issues

**Comment by wongsyrone** [comment]
Try global mode or report it to gfwlist project.
