### ISSUE TITLE
怎么开启支持UDP呢？

### ISSUE THREAD

**Issue by Chadwick97** [shadowsocks/shadowsocks-windows#607]
你好，
升级最新版的3.0客户端，客户端应该已经支持UDP了。但是我用SocksCap64对ss代理进行UDP检测，依然不行。是我的服务器端没有开启UDP吗？怎么查看服务器端是否开启和开启UDP呢？麻烦你了

**Comment by GangZhuo** [comment]
libev 版服务端的话，增加参数 -u, 默认应该已经开启了。

Chadwick97 <notifications@github.com>于2016年7月1日周五 上午12:56写道：

**Comment by Chadwick97** [comment]
我的服务端版本是Python 2.6，需要更新新的版本吗？

**Comment by Chadwick97** [comment]
我卸载了python重装了libev版，并且在启动配置文件的时候增加了-u，为什么还是不支持udp呢？

**Comment by Chadwick97** [comment]
[root@chadwick ~]# ss-server -c config.json -f /tmp/ss.pid -u
[root@chadwick ~]# netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name   
tcp        0      0 0.0.0.0:26670               0.0.0.0:*                   LISTEN      560/sshd            
tcp        0      0 2607:****:***:**22:::2280   :::*                        LISTEN      688/ss-server       
tcp        0      0 :::26670                    :::*                        LISTEN      560/sshd            
udp        0      0 0.0.0.0:53476               0.0.0.0:*                               570/ss-server       
udp        0      0 :::26670                    :::*                                    610/./server_linux_ 
udp        0      0 2607:****:***:**22:::2280   :::*                                    688/ss-server       
udp        0      0 2607:****:***:**22:::2280   :::*                                    570/ss-server       
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING     492663962 1/init              @/com/ubuntu/upstart

**Comment by chenshaoju** [comment]
如果你是用 deb (apt-get) 安装的libev版本，不支持，你需要自行下载源码编译，详见： https://github.com/shadowsocks/shadowsocks-libev

**Comment by Chadwick97** [comment]
我是在centos下yum安装的

**Comment by chenshaoju** [comment]
那是一个非常老道版本……你可以运行 ss-server -h 命令看看你的SS版本是多少，我的是2.4.6，如果是1.x.x肯定是不支持的。

**Comment by Chadwick97** [comment]
还真不是，我的版本是2.4.7
[root@chadwick ~]# ss-server -h

shadowsocks-libev 2.4.7

  usage:

    ss-server

       -s <server_host>           Host name or IP address of your remote server.
       -p <server_port>           Port number of your remote server.
       -l <local_port>            Port number of your local server.
       -k <password>              Password of your remote server.
       -m <encrypt_method>        Encrypt method: table, rc4, rc4-md5,
                                  aes-128-cfb, aes-192-cfb, aes-256-cfb,
                                  bf-cfb, camellia-128-cfb, camellia-192-cfb,
                                  camellia-256-cfb, cast5-cfb, des-cfb,
                                  idea-cfb, rc2-cfb, seed-cfb, salsa20,
                                  chacha20 and chacha20-ietf.
                                  The default cipher is tables.

       [-a <user>]                Run as another user.
       [-f <pid_file>]            The file path to store pid.
       [-t <timeout>]             Socket timeout in seconds.
       [-c <config_file>]         The path to config file.
       [-n <number>]              Max number of open files.
       [-i <interface>]           Network interface to bind.
       [-b <local_address>]       Local address to bind.

       [-u]                       Enable UDP relay,
       [-U]                       Enable UDP relay and disable TCP relay.
       [-A]                       Enable onetime authentication.
       [-6]                       Resovle hostname to IPv6 address first.
       [-w]                       Enable white list mode (when ACL enabled).

       [-d <addr>]                Name servers for internal DNS resolver.
       [--fast-open]              Enable TCP fast open.
                                  with Linux kernel > 3.7.0.
       [--acl <acl_file>]         Path to ACL (Access Control List).
       [--manager-address <addr>] UNIX domain socket address.

       [-v]                       Verbose mode.
       [-h, --help]               Print this message.

**Comment by chenshaoju** [comment]
那 -u 肯定可以生效，请检查你的防火墙（ iptables ）。

**Comment by Chadwick97** [comment]
我在防火墙里添加了udp的端口，不管用。
然后我把防火墙直接关了，依然不管用。

**Comment by wongsyrone** [comment]
Try latest libev fork and double check your configurations.
For C# version, check https://github.com/shadowsocks/shadowsocks-windows/tree/master#udp

**Comment by luokuning** [comment]
@Chadwick97 请问你有找到问题的原因吗？

我的 vps 是 ubuntu 16.04 (默认没有开启防火墙)，使用[安装脚本](https://shadowsocks.be/11.html)配置的 shadowsocks-libev (版本 3.1.0)。然后我看启动脚本 `/etc/init.d/shadowsocks-libev` 中启动 `ss-server` 也确实带了 `-u` 参数。

运行 `netstat -lnp | grep 9193` 输出结果是 (9193 是我设置的端口号):
```
tcp        0      0 0.0.0.0:9193            0.0.0.0:*               LISTEN      3981/ss-server  
udp        0      0 0.0.0.0:9193            0.0.0.0:*                           3981/ss-server  
```
发现 `udp` 并没有 LISTEN，请问会是什么原因呢？

**Comment by chenshaoju** [comment]
UDP是无状态的，Linux下都不会显示LISTEN。
```
udp        0      0 10.12.0.7:123           0.0.0.0:*                           804/ntpd
udp        0      0 0.0.0.0:123      0.0.0.0:*                           804/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           804/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           804/ntpd
udp        0      0 0.0.0.0:50663           0.0.0.0:*                           732/ss-server
udp        0      0 127.0.0.1:2083          0.0.0.0:*                           732/ss-server
```

**Comment by luokuning** [comment]
@chenshaoju 原来是这样，学习了👍。不过我在 windows 下用 NatTypeTester 测试发现是 UdpBlocked, 不知道是什么原因导致没有开启 udp 转发的？

**Comment by chenshaoju** [comment]
NatTypeTester原生支持SOCKS5代理吗？我这个不支持。。。

**Comment by luokuning** [comment]
@chenshaoju 我把 NatTypeTester 拖到了 SocksCap64 里，显示是 udpblocked 的 - -

**Comment by chenshaoju** [comment]
不确定这样能否使用STUN检测……你有别的UDP应用测试吗？

**Comment by luokuning** [comment]
@chenshaoju 没有了。。。怀疑是我的网的问题，毕竟现在是长城宽带。。。

**Comment by chenshaoju** [comment]
@luokuning pat pat

**Comment by chenshaoju** [comment]
@luokuning https://www.reddit.com/r/China/comments/76hjrm/lol_china_just_blocked_all_unregistered_udp/

**Comment by luokuning** [comment]
@chenshaoju 如果是这样的话，不知道等开完情况会不会好点😢

**Comment by relei1988** [comment]
@luokuning 我觉得也没有全部屏蔽不认识的UDP啊，KCPTUN开着使用正常的嘛

**Comment by luokuning** [comment]
@relei1988 昨天晚上我尝试着把 Ubuntu 的 `ufw` 打开，然后运行 `ufw enable 2000:3000/udp`, 附带换了个联通的网，在 windows 下用 sstap 链接服务器。最后发现用测试软件测试是支持 udp 转发的。。。

**Comment by chenshaoju** [comment]
１.https://twitter.com/chenshaoju/status/919543017488261120

２. https://twitter.com/chenshaoju/status/920461618034524160

**Comment by byewind** [comment]
求助，CentOS 7 x64系统的ss服务器开启UDP转发和查询是否支持的完整命令是什么？

**Comment by Subdue0** [comment]
我用NatTypeTester测试出udpblocked了，但是我的sstap测试udp转发是通过的，为什么会这样的，哪个才是对的？

**Comment by Subdue0** [comment]
@luokuning 是网络的问题，我也是这样的，网络封锁了udp

**Comment by Subdue0** [comment]
@luokuning 不知道你会不会用sstap是可以通过的，但是nat类型检测不通过
