### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by qqtesthacker** [shadowsocks/shadowsocks-windows#608]
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

一直是这个问题，无论任何版本【3.0以下】，任何浏览器都是这个报错，有时也有502错误 504错误

抓狂中。。。已尝试诸如netsh 那个reset命令，以及重置LSP

**Comment by chenshaoju** [comment]
请尝试便携模式：
在你的 Shadowsocks.exe 所在目录建立一个名为 shadowsocks_portable_mode.txt 的空文本文件（不是 shadowsocks_portable_mode.txt.txt ），然后重新启动 SS 看看。

**Comment by soulomoon** [comment]
still not fixing

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/449#issuecomment-230401982

**Comment by Little-Blue-Hat** [comment]
我想是因为跟防火墙有关系，我使用service iptables stop关闭以后就可以上网了，但是我service iptables start 开启以后还是不能上网， 我把80,443,53,8388端口都accept还是不能使用。我也不知道为什么了。

**Comment by Noisyfox** [comment]
你开放了SS的端口了么
