### ISSUE TITLE
如何编辑PAC规则禁止访问谷歌云盘

### ISSUE THREAD

**Issue by libin525308160** [shadowsocks/shadowsocks-windows#609]
只允许访问谷歌搜索，或者不允许访问谷歌云盘，这两个任意达成一个条件都行  该如何编辑PAC规则？

**Comment by chenshaoju** [comment]
仅允许 www.google.com 即可。

**Comment by libin525308160** [comment]
@chenshaoju  测试成功  非常感谢

**Comment by dragon9001** [comment]
有两个问题请教。
1.具体应该编辑哪个文件，增加/删除哪些条目
2.是否这样编辑后就可以使用桌面版的google drive了？

**Comment by chenshaoju** [comment]
@dragon9001 默认的PAC已经可以让桌面版Google Drive访问了。
