### ISSUE TITLE
意外发现3.0自动退出解决方法 

### ISSUE THREAD

**Issue by bluecodecat** [shadowsocks/shadowsocks-windows#611]
直接下载的3.0 会出错退出
但是
下载到源码 本地编译一下运行 一切正常 不知道为啥。。编译出的exe文件比直接下载的大了20kb

**Comment by Noisyfox** [comment]
因为现在的源码是3.1版本的:)

**Comment by bluecodecat** [comment]
@Noisyfox  原来是这样 真好笑 哈哈

**Comment by verbamboo** [comment]
@bluecodecat 源码哪里下，怎么编译？

**Comment by GangZhuo** [comment]
@verbamboo 源码在 master 分支
