### ISSUE TITLE
连不上···

### ISSUE THREAD

**Issue by feiyaowoquyingwen** [shadowsocks/shadowsocks-windows#612]
[2016-07-03 19:10:24] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/591

**Comment by GangZhuo** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/620
