### ISSUE TITLE
端口被占用问题

### ISSUE THREAD

**Issue by littleyuan** [shadowsocks/shadowsocks-windows#613]
**端口被占用**

![  ](http://o7zexjaw4.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160705093636.jpg?e=1467686840&token=X78Vp1I3qQ3IHZGUanT0JBMrpLRI3-FCOKMKSYlA:tlRae0QbaRC-bAlZQyz2BeNszQk)

今天早上打开后就出现这个对话窗口，不知道应该怎么解决~~求助

**Comment by chenshaoju** [comment]
右击托盘区的纸飞机图标，选择服务器、编辑服务器，然后修改代理端口即可。

**Comment by littleyuan** [comment]
不行呢，我重新换了代理端口还是有这个问题。直接扫描屏幕上的二维码就会先弹出这个对话框，然后再扫描一下，接着还是连不上~~~我有点懵逼了~~求大神再解答一下~

**Comment by littleyuan** [comment]
我现在用的客户端一直是2.5.2版本的，3.0的总是下载不成功，难道和这个有关系吗？

**Comment by littleyuan** [comment]
重启了一下电脑问题解决了。

**Comment by lethelimited** [comment]
这是一般是因为你多开了一个shadowsocks（双击完以为没打开又双击了一次就又打开一个之类的），在托盘里面可能会看到两个，关掉一个就好了。改端口是不能解决问题的，服务端端口固定的，改了会导致服务不可用，那位仁兄很淘气。重启大法好。。重启属于暴力解决问题
