### ISSUE TITLE
命令行启动shadowsocks

### ISSUE THREAD

**Issue by moqiaoduo** [shadowsocks/shadowsocks-windows#614]
我想让外部程序通过命令启动ss并自动连接，比如说利用外部程序执行 shadowsocks.exe ip port pass method 或者shadowsocks ss://xxxx这样的方式启动ss

**Comment by chenshaoju** [comment]
你可以尝试Python版本的SS：
https://github.com/shadowsocks/shadowsocks

**Comment by wongsyrone** [comment]
No plan for this now. Please send a PR if you have interest.
