### ISSUE TITLE
URI and QR code did not add "-auth"

### ISSUE THREAD

**Issue by cs17899219** [shadowsocks/shadowsocks-windows#615]
According to [document](https://shadowsocks.org/en/config/quick-guide.html)

URI should be:
ss://method[-auth]:password@hostname:port

current version (3.0) did not add -auth when I switch on OTA.

**Comment by wongsyrone** [comment]
try latest master branch, this has been fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/9c7b100f2b03cbbed38ba86f1c2f7fb03af47c61
