### ISSUE TITLE
c版本的服务端，windows客户端无法使用

### ISSUE THREAD

**Issue by ynhzzu** [shadowsocks/shadowsocks-windows#616]
用c部署了一个服务，结果windows客户端无法使用，而mac和android可以使用，有遇到这个问题的吗？

**Comment by suicuneyuheng** [comment]
我也是，在win上速度跟稳定性明显下降（基本上算是不能用了），在linux跟安卓上没有问题。

**Comment by wongsyrone** [comment]
Cannot reproduce, double check your configuration files.
