### ISSUE TITLE
Chrome 下可正常使用，Firefox 下无法连接

### ISSUE THREAD

**Issue by wavierwister** [shadowsocks/shadowsocks-windows#617]
系统是 Windows 10 64bit，SS 版本为 3.0。

Chrome（50.0.2661.102） 下可正常使用，但在 Firefox（47.0.1） 下无法连接。

不知可能是何原因造成。谢谢解答。

**Comment by chenshaoju** [comment]
此问题已知，是Firefox的问题，如果很着急要解决该问题，请使用Nightly版本的Firefox：
https://nightly.mozilla.org/

**Comment by wavierwister** [comment]
谢谢 @chenshaoju ！

**Comment by jonefeewang** [comment]
使用新版firefox依旧存在这个问题,
firefox : 54.01
mac osx: 10.9.5

**Comment by kzwr** [comment]
安裝foxyproxy 可以解決

**Comment by chenshaoju** [comment]
Shadowsocks for Windows 的 PAC 列表来自 GFWList ，无法控制。
Firefox 就更无法控制了……这是Firefox在处理大量PAC时失效的问题，从Shadowsocks角度来说，无法解决。。。

**Comment by jonefeewang** [comment]
这个问题解决了，就是@kzwr 说的,  安装firefox  froxyproxy starndard插件, port端口号设置为1080，网上有个帖子说的比较详细: 搜索 firefox proxy + shadow socks
