### ISSUE TITLE
迅游国际版会导致3.0出现500错误

### ISSUE THREAD

**Issue by monster-bear** [shadowsocks/shadowsocks-windows#618]
突然就不能用了，永远都是500
排查了一下，手机是正常的，电脑是win10，最近的系统改动就只有装了迅游国际版，估计就是它了，卸载之后，果然正常了，这些国产流氓。。。
_ps：迅游国际版现在正在测试免费阶段，因为自己在玩外服战网，随手下了试试，效果很好_

错误日志以下两类
`[2016-07-09 05:07:52] System.Net.Sockets.SocketException (0x80004005): 在一个非套接字上尝试了一个操作。
   在 System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   在 System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)`

`[2016-07-09 07:18:12] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)`

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/591

**Comment by wongsyrone** [comment]
Please test version from https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe
