### ISSUE TITLE
如何调试pac user-rule？

### ISSUE THREAD

**Issue by moondigi** [shadowsocks/shadowsocks-windows#619]
例如这个地址
`http://vd.clip-studio.com/clipcontent/lib/clipstudio/paint/data/156/CSP_156w_setup.exe`
我在user-rule添加的是
`||vd.clip-studio.com`
发现无效后取消pac使用全局模式就能正常下载，我应该用什么方法去debug？

**Comment by chenshaoju** [comment]
这是我用的PAC，给你参考：
https://gist.github.com/chenshaoju/52c7555acc65ec98423f

你可以按照你自己的要求修改。

**Comment by moondigi** [comment]
谢谢，在你的这个pac上加入后是有效的，但是自动获取回来的那个pac上却无效不知道为什么
自己维护这个列表的话比较麻烦，不知道有没有方法像自动获取gfwlist+用户自定义这种方式生成？

**Comment by chenshaoju** [comment]
gfwlist 是由 https://github.com/gfwlist/gfwlist 提供的，你可以在 https://github.com/gfwlist/gfwlist/issues 提交你的问题。

**Comment by moondigi** [comment]
经测试与gfwlist无关，是获取后自动生成的那个pac有问题，使用SwitchyOmega生成的或者你提供的pac正常，希望下个版本有改进

**Comment by chenshaoju** [comment]
你看一下你的SS所在目录有无 user-rule.txt 如果没有，右击SS的托盘区图标，PAC，编辑 GFWList 用户规则。
用这个把。

**Comment by moondigi** [comment]
检查过了的，修改user-rule.txt后会自动更新pac，我也检查过pac里面最下面有我添加的那一条规则，但是就不能正常使用
然后清掉pac所有内容后换上SwitchyOmega生成的就能正常下载那个文件了，或者能帮忙测试一下？

**Comment by moondigi** [comment]
以下载`http://vd.clip-studio.com/clipcontent/lib/clipstudio/paint/data/156/CSP_156w_setup.exe`这个文件为目的

这个是自动生成的pac，在5293行有添加`||vd.clip-studio.com`这个规则，使用这个pac下载失败
https://gist.github.com/moondigi/d310b9d72b7ed8f23920aaab7b8989cb#file-auto-pac-L5293

这个是omega生成的pac，使用正常
https://gist.github.com/moondigi/a1ba299ca4cd6661e883ca7cea1e2cf2#file-omega-pac-L14
![default](https://cloud.githubusercontent.com/assets/8404678/16754060/a8def982-4821-11e6-8af2-c13a00f6c8db.jpg)

**Comment by dariner** [comment]
||clip-studio.com

**Comment by dariner** [comment]
另外需要点击一下 “从gfw更新本地pac” 刷新
