### ISSUE TITLE
系统检测到在一个调用中尝试使用指针参数时的无效指针地址

### ISSUE THREAD

**Issue by we1559** [shadowsocks/shadowsocks-windows#620]
System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

上述错误日志无限刷屏

**Comment by chenshaoju** [comment]
请尝试 https://github.com/shadowsocks/shadowsocks-windows/issues/591

**Comment by GangZhuo** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/a486514afb34d8045e714632f014399e45814a1b
