### ISSUE TITLE
Shadowsocks与Windows 10问题排查指南

### ISSUE THREAD

**Issue by SCLeoX** [shadowsocks/shadowsocks-windows#621]
声明：本文不保证能够解决问题，毕竟可能会有很多不同的原因都会造成问题。win10碰上Shadowsocks出错不是个案但是并不是人人会发生，所以请不要在评论刷“win10一切正常的言语”。另外，由于版本不同，可能有些错误提示内容不同，所以建议**每一个办法都尝试下看看效果**。

本文不会讨论卸载迅雷或者管理员模式这类常规办法，以下内容纯属个人摸索的玄学。如果不信，可以不用看了。

另外在尝试这些方法前，**请先使用手机连接或者是使用别的设备连接确保不是节点的问题**。

一般情况下，使用这些办法后可能会**莫名奇妙工作一段时间**，但是过了一段时间又出现别的错误。

1.	不要使用“负载均衡”，“高可用”或者“根据统计”（玄学）
纯属猜测，使用这个可能会导致发起过量请求而被DNS难看掉，然后拼命刷“不知道这样的主机”错误。
典型症状：“不知道这样的主机。”
解决办法：指定一个具体的版本而不是选择按照统计得出的。

2.	频繁切换服务器（玄学）
注意不是“不要频繁切换”，而是“要频繁切换”。我确定这个一定有用，因为我靠这个办法苟延残喘了好几天，后来突然失效了，就是切换了也不会恢复。其症状为每次切换服务器20秒有效，然后就断了，这时切换服务器可以+20s。

3.	启用Portable Mode（玄学）
默认情况下Shadowsocks会将其核心文件ss_privoxy释放在%temp%目录。可能有一些原因导致无法成功在%temp%目录释放。
典型症状：“ss_privoxy已停止工作。”
启用办法：在ss目录下新建一个空的文件，名字取“shadowsocks_portable_mode.txt”，然后彻底关闭正在运行的ss，然后重新启动。

4.	使用老版本（玄学）
没有任何证据表明使用老版本可以解决问题，但是真的有奇效，似乎3.0在win10上面几乎无法流畅工作。考虑使用老版本，比如2.5.8或者Source Forge上的版本。我其实尝试了十多个版本，越老的版本似乎越稳定。
 
5.	清理temp文件夹（玄学）
虽然你可能已经启用了Portable Mode，但是依然很有可能有些Privoxy的文件去了%temp%文件夹，清空就好。
具体方法是：在资源管理器里输入%temp%，进去后删除所有文件。

6.	关闭一切防火墙/杀毒软件（玄学）
我一直是裸机所以杀毒软件我不敢说，但是由于杀毒软件很可能对这种网络相关的事情做出拦截，强烈建议关闭。防火墙的话，基本上解决网络问题第一个就要关了。

7.	清空所有网络设置（玄学）
这个是我在github上看到的，似乎没有什么卵用，但是还是试一下吧。
首先以管理员身份运行cmd，然后依次输入以下三个命令：
```cmd
netsh int ipv4 reset all
netsh int ipv6 reset all
netsh winsock reset all
```

8.	重启路由器（玄学）
这个东西我没有任何的理由，但是总是一个思路吧。

9.	重装系统（玄学）
为什么这个也属于玄学呢，因为事实证明，就算你断定是你的电脑问题，就算重装了也不一定能解决。我就是重装了也没解决，唉。不过重装了可能会解决一些问题吧。

如果你尝试了以上办法依然没有解决问题，或者问题解决了，但是过了几个小时又出现新的问题（比如我），请尝试下面这个终极解决方案（超级玄学）：

在房间内关上门，大声咒骂Shadowsocks开发人员以及在汇报Shadowsocks和win10不兼容的Issue下刷“我win10 pro，可以使用”而导致问题被忽略的傻逼或者刷“dup of #xxx”和“请尝试#xxx”然后过去看了发现完全不是一个问题的逗逼。

然后你可能会发现你的问题解决了。我就是这样骂了一通以后莫名其妙就一切正常了。（可能只是临时性的恢复，我确定我不是节点的问题，因为首先我的节点来自三个供应商，同时全部爆炸的可能性微乎其微，而且是反复同时爆炸+同时恢复。另外我的手机连接从来就没有出现过任何问题。）

最后说几句，不要觉得你没有问题就代表别人也没有问题。我们摊开说，Shadowsocks一定和win10有着什么不兼容的地方，你没碰到是你运气好，别人碰到了请不要刷“我很正常”之类的信息，一来，这种话对问题的解决毫无帮助；二来，反而导致问题被忽略；三来，会让碰到问题的人十分沮丧。

**Comment by breakwa11** [comment]
1和2是相互矛盾的，1没有根据，2像是你的ip被盯上或软件有bug，而重启路由是为了获得新的ip，重装系统是如果系统权限配置有错，或被安装的软件劫持时有效

**Comment by SCLeoX** [comment]
@breakwa11 我现在此时此刻就是如果启用高可用或者根据统计就死命报错。关闭后一切正常。所以是玄学嘛。

选择具体服务器，一切正常。
![image](https://cloud.githubusercontent.com/assets/13428807/16893131/32b4276c-4b61-11e6-80e1-84e50c37f91d.png)

选择根据统计，刷报错。
![image](http://i68.tinypic.com/y04m.png)

另外，我的所有节点全部单独nslookup过，所以排除是域名填写错误造成的。

另外，重启路由器和重装系统其实使用了对我来说效果一点也没有，就是这台电脑中了邪。同一个局域网我爸的win10就没问题。

**Comment by chenshaoju** [comment]
这个问题可能和IPv6有关。
你在你的网卡属性里，停用IPv6协议看看。

**Comment by SCLeoX** [comment]
@chenshaoju 
我已经莫名其妙恢复了，我这边列的这些方法讲真的，或多或少曾经有点作用，所以希望能够帮助别的碰到问题的人。

**Comment by maoziliang** [comment]
我的更神奇，刚发现是服务端的加密方式为rc4，客户端是rc4-md5，但是之前一直工作正常，升级3.0就不行，然后回退老版本也不行。刚把服务端改为rc4-md5就正常工作了。

**Comment by SCLeoX** [comment]
@maoziliang 
！！你这么一说提醒了我！我也是一开始正常，然后升级 3.0 就不正常，然后退回去还是不正常。然后悲剧就开始了的。3.0肯定改了什么配置导致炸了

**Comment by ZacharyTech** [comment]
今天弄了一会发现不行，直接删掉！再路由器里面装了一个

**Comment by SCLeoX** [comment]
@ZacharyTech 快把我的办法都尝试一遍啦，总有适合的吧

**Comment by cutewalker** [comment]
使用 3.0.0 各种尝试无效（日志显示连接 服务器超时， 服务器端显示 reset by peer)， 换做 2.5.8 后一切正常

**Comment by CircularDNA** [comment]
方法3可用，已验证。

**Comment by CircularDNA** [comment]
GG，没有5分钟又挂了！

**Comment by wxyzh** [comment]
win10上没碰到客户端原因导致的问题，关于负载均衡，感觉用hparoxy做要好些，直接踢掉高延迟的服务器。缺点是不支持UDP，玩游戏的时候可能会频繁断线

**Comment by ZacharyTech** [comment]
@SCLeoX Win10上不太稳定，一会行一会不行

**Comment by SCLeoX** [comment]
@CircularDNA 哈哈我就说了玄学，这玩意确实一直有问题。。
我这边供应商建议我换Shadowsocks-Qt5，换了以后一切正常了就，
https://github.com/shadowsocks/shadowsocks-qt5/releases
这个shadowsocks-windows确实有问题...

**Comment by SCLeoX** [comment]
@ZacharyTech 供应商建议我换Shadowsocks-Qt5，换了就正常了。
https://github.com/shadowsocks/shadowsocks-qt5/releases

**Comment by SCLeoX** [comment]
@cutewalker 
如果之后再出问题，换Shadowsocks-Qt5
https://github.com/shadowsocks/shadowsocks-qt5/releases

**Comment by cutewalker** [comment]
@SCLeoX 
好，回头我试试看

**Comment by giuem** [comment]
@SCLeoX 玄学啊。。我下载 Shadowsocks-Qt5 用了一会，再换回这个就莫名其妙的好了

**Comment by SCLeoX** [comment]
@giuem 233 shadowsocks 似乎把一个配置改坏了，然后qt5又改回来了，然后就能用了。。

**Comment by blacksigh** [comment]
win10也是用过一段会坏掉。一直刷什么指针被占用的报错。重启路由器就好了。

奇怪的是我SS3.0能用，而楼上各位说的QT5却用不了。。。

**Comment by wongsyrone** [comment]
Most of solutions talked above has been moved to wiki: https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting

**Comment by xudongding** [comment]
Win10 x64专业版，4.x的用得好好的，早上突然发现托盘右键弹不出来了，但代理可以照常使用，关闭只能任务管理器结束，把临时文件配置文件全删了，打开主程序后弹出配置服务器窗口就没有响应了。尝试过n种办法，折腾了一上午，直到看到此贴：

> 4. 使用老版本（玄学）

遂换到3.4.3版本，一切正常。

**Comment by CNSDHH** [comment]
不想找了，就是Windows10系统的问题，没更新系统前我手机能用，但电脑不能用，我现在把系统更新到了最新（2019.03.11）的1809-2版本，重启系统后问题解决，再或者你可以把系统版本还原到以前没问题的时候也行，但最好还是把系统更新到最新。我现在用的是1809-02版本，ss用的是4.1.5。

**Comment by CNSDHH** [comment]
> 这个问题可能和IPv6有关。
> 你在你的网卡属性里，停用IPv6协议看看。

不想找了，就是Windows10系统的问题，没更新系统前我手机能用，但电脑不能用，我现在把系统更新到了最新（2019.03.11）的1809-2版本，重启系统后问题解决，再或者你可以把系统版本还原到以前没问题的时候也行，但最好还是把系统更新到最新。我现在用的是1809-02版本，ss用的是4.1.5。

**Comment by CNSDHH** [comment]
> 声明：本文不保证能够解决问题，毕竟可能会有很多不同的原因都会造成问题。win10碰上Shadowsocks出错不是个案但是并不是人人会发生，所以请不要在评论刷“win10一切正常的言语”。另外，由于版本不同，可能有些错误提示内容不同，所以建议**每一个办法都尝试下看看效果**。
> 
> 本文不会讨论卸载迅雷或者管理员模式这类常规办法，以下内容纯属个人摸索的玄学。如果不信，可以不用看了。
> 
> 另外在尝试这些方法前，**请先使用手机连接或者是使用别的设备连接确保不是节点的问题**。
> 
> 一般情况下，使用这些办法后可能会**莫名奇妙工作一段时间**，但是过了一段时间又出现别的错误。
> 
> 1. 不要使用“负载均衡”，“高可用”或者“根据统计”（玄学）
>    纯属猜测，使用这个可能会导致发起过量请求而被DNS难看掉，然后拼命刷“不知道这样的主机”错误。
>    典型症状：“不知道这样的主机。”
>    解决办法：指定一个具体的版本而不是选择按照统计得出的。
> 2. 频繁切换服务器（玄学）
>    注意不是“不要频繁切换”，而是“要频繁切换”。我确定这个一定有用，因为我靠这个办法苟延残喘了好几天，后来突然失效了，就是切换了也不会恢复。其症状为每次切换服务器20秒有效，然后就断了，这时切换服务器可以+20s。
> 3. 启用Portable Mode（玄学）
>    默认情况下Shadowsocks会将其核心文件ss_privoxy释放在%temp%目录。可能有一些原因导致无法成功在%temp%目录释放。
>    典型症状：“ss_privoxy已停止工作。”
>    启用办法：在ss目录下新建一个空的文件，名字取“shadowsocks_portable_mode.txt”，然后彻底关闭正在运行的ss，然后重新启动。
> 4. 使用老版本（玄学）
>    没有任何证据表明使用老版本可以解决问题，但是真的有奇效，似乎3.0在win10上面几乎无法流畅工作。考虑使用老版本，比如2.5.8或者Source Forge上的版本。我其实尝试了十多个版本，越老的版本似乎越稳定。
> 5. 清理temp文件夹（玄学）
>    虽然你可能已经启用了Portable Mode，但是依然很有可能有些Privoxy的文件去了%temp%文件夹，清空就好。
>    具体方法是：在资源管理器里输入%temp%，进去后删除所有文件。
> 6. 关闭一切防火墙/杀毒软件（玄学）
>    我一直是裸机所以杀毒软件我不敢说，但是由于杀毒软件很可能对这种网络相关的事情做出拦截，强烈建议关闭。防火墙的话，基本上解决网络问题第一个就要关了。
> 7. 清空所有网络设置（玄学）
>    这个是我在github上看到的，似乎没有什么卵用，但是还是试一下吧。
>    首先以管理员身份运行cmd，然后依次输入以下三个命令：
> 
> ```batchfile
> netsh int ipv4 reset all
> netsh int ipv6 reset all
> netsh winsock reset all
> ```
> 
> 1. 重启路由器（玄学）
>    这个东西我没有任何的理由，但是总是一个思路吧。
> 2. 重装系统（玄学）
>    为什么这个也属于玄学呢，因为事实证明，就算你断定是你的电脑问题，就算重装了也不一定能解决。我就是重装了也没解决，唉。不过重装了可能会解决一些问题吧。
> 
> 如果你尝试了以上办法依然没有解决问题，或者问题解决了，但是过了几个小时又出现新的问题（比如我），请尝试下面这个终极解决方案（超级玄学）：
> 
> 在房间内关上门，大声咒骂Shadowsocks开发人员以及在汇报Shadowsocks和win10不兼容的Issue下刷“我win10 pro，可以使用”而导致问题被忽略的傻逼或者刷“dup of #xxx”和“请尝试#xxx”然后过去看了发现完全不是一个问题的逗逼。
> 
> 然后你可能会发现你的问题解决了。我就是这样骂了一通以后莫名其妙就一切正常了。（可能只是临时性的恢复，我确定我不是节点的问题，因为首先我的节点来自三个供应商，同时全部爆炸的可能性微乎其微，而且是反复同时爆炸+同时恢复。另外我的手机连接从来就没有出现过任何问题。）
> 
> 最后说几句，不要觉得你没有问题就代表别人也没有问题。我们摊开说，Shadowsocks一定和win10有着什么不兼容的地方，你没碰到是你运气好，别人碰到了请不要刷“我很正常”之类的信息，一来，这种话对问题的解决毫无帮助；二来，反而导致问题被忽略；三来，会让碰到问题的人十分沮丧。

不想找了，就是Windows10系统的问题，没更新系统前我手机能用，但电脑不能用，我现在把系统更新到了最新（2019.03.11）的1809-2版本，重启系统后问题解决，再或者你可以把系统版本还原到以前没问题的时候也行，但最好还是把系统更新到最新。我现在用的是1809-02版本，ss用的是4.1.5。

**Comment by RayTao** [comment]
多谢 安装2.3.0版本就OK了
