### ISSUE TITLE
3.0无法添加两个ss服务器

### ISSUE THREAD

**Issue by J-J-J** [shadowsocks/shadowsocks-windows#623]
win10+ss3.0，在使用扫描屏幕二维码添加第二个ss server时候退出，无法添加第二个server进去

**Comment by chenshaoju** [comment]
请检查你添加的第二个二维码的服务器是否已经添加过了。
如果一个服务器已存在，再次尝试添加的时候会崩溃。
如果你坚持要添加重复的服务器，可以尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/2c0gn4obp765b4df/artifacts

**Comment by J-J-J** [comment]
感谢回答。
我这边试过了，只是加了一个，并没有加第二个。到配置文件中确认过。
崩溃后，只好进到配置文件将第二个server删除掉才能重启ss客户端。

……分割线

用一个server也行，速度不受影响，: )

**Comment by GangZhuo** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/502
