### ISSUE TITLE
我想知道shadowsocks-rss相对于shadowsocks for windows有什么优势

### ISSUE THREAD

**Issue by reaCodes** [shadowsocks/shadowsocks-windows#624]
我不是来砸场子的，我专业知识很少，但是对这个还是有点好奇心的，有见解的朋友还请告知

**Comment by breakwa11** [comment]
只有劣势，没有什么优势，而且已经不更新了，用原版吧

**Comment by reaCodes** [comment]
@breakwa11 别这么说，很多付费的shadowsocks服务都使用的是你的版本，自然有它的优势。

他们会对我说R版本比原版更稳定，我体验了很长时间，两者都很稳定，速度上也没区别，至少我感受不到。

两边都不更新了，为什么呢

**Comment by breakwa11** [comment]
你感受不到，所以这只是心理上的感觉而已

**Comment by wxyzh** [comment]
没啥优势吧，貌似R版不开源了。关于更新，没啥大的bug，协议上又没事变化，为啥要更新呢
