### ISSUE TITLE
3.0版在Windwos 10上有一点小问题

### ISSUE THREAD

**Issue by starrychou** [shadowsocks/shadowsocks-windows#626]
Windows 10 x64 上3.0版本有一点小问题，这个问题似乎有人说过了，但是描述不是很清楚。
我的本地系统是Windows10 x64，DigitalOcean 上用的纽约节点，服务器端的系统是CentOS 7.2，安装了shadowsocks-libev 2.4.7，在本地使用3.0版本时候，ipv6能正常使用，ipv4不行。日志里一直重复报同一个错误：
**[2016-07-19 22:58:46] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   在 System.Net.Sockets.Socket.get_RemoteEndPoint()
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)**
换回以前的版本就能用了，使用同一个配置文件，大概八成不是我配置的问题。
如果错误不能重现就算了，估计是哪抽风，做这个还是挺幸苦的，以前的版本也能用。

**Comment by chenshaoju** [comment]
请尝试：https://github.com/shadowsocks/shadowsocks-windows/issues/620

**Comment by starrychou** [comment]
@chenshaoju 非常感谢
