### ISSUE TITLE
2.5.8在64位Win7下无法正常使用暴雪战网客户端

### ISSUE THREAD

**Issue by tetsuchou** [shadowsocks/shadowsocks-windows#627]
新装的系统本来想装3.0，结果在64位Win7下闪退，重装了.NET Framework也没办法只能用2.5.8
结果现在要用战网就必须开着SS，而且必须得开全局模式，不开SS就用不成，玩国内网游翻出去再回来速度可想而知，就跟吸了一次毒戒不掉了一样，SS一关掉就断。
PAC里也没找到跟战网相关的条目。

**Comment by chenshaoju** [comment]
这个问题已经有好几位报告过了，但是并不知道原因，我自己使用的战网，以及魔兽世界、风暴英雄、炉石传说、守望先锋都没有问题。

另外，Win7 64位下闪退的问题，请尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/2c0gn4obp765b4df/artifacts

**Comment by yjd** [comment]
NDP40-KB2468871-v2
这个补丁打完试试。

**Comment by CTKnight** [comment]
先开全局进站网，然后关掉ss 即可

**Comment by wongsyrone** [comment]
请测试https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.184/job/ltqduk0sj8e3d02r/artifacts

**Comment by wongsyrone** [comment]
Reopen if you still have this issue.
