### ISSUE TITLE
3.0、3.1版本，最近这几天，为啥开全局模式墙外的网站也都没法上了

### ISSUE THREAD

**Issue by AlyciaHathaway** [shadowsocks/shadowsocks-windows#628]
最近这两个月，先是封了我3次端口，最后把ip也封了，我又联系的VPS服务商更换的ip，可以上了，过了几天，现在是SS可以用，全局模式下访问国内网站是通过境外服务器访问的，但是墙外的网站google、youtube都无法访问呢？

**Comment by AlyciaHathaway** [comment]
PS：手机安卓端没问题~可以通过服务器正常访问google，应该是PC端的SS哪里堵塞了

**Comment by breakwa11** [comment]
你的网络服务商是电信吗？手机的是联通吗？

**Comment by cqhtyi** [comment]
额，层主是不是安装了360全家桶之类的软件？

（惊现破娃酱）

**Comment by AlyciaHathaway** [comment]
@breakwa11 @cqhtyi  宽带网络是电信，手机连接的wifi。因为电信有NAT转发，投诉几百次改成公网ip，但每次改了没几天又给我变回内网，翻墙也没做非法的事，但隔段时间端口封了，也不知道是哪里出了问题。PS：360很早就不用了，现在裸奔。PPS：你们都用哪个版本？目前访问都很畅通吗？

**Comment by mengskysama** [comment]
既然全局模式能访问国内站正常情况下国外站点一定也可以，PAC比较容易和其他使用PAC的工具产生冲突，你试试Client+SwitchyOmega

**Comment by DBLobster** [comment]
我想问问, 3.1 版有没有 build 好的?

**Comment by AlyciaHathaway** [comment]
感谢各位，今天网络自己恢复了，好神奇

**Comment by 772807886** [comment]
这个情况应该检查DNS的吧。。。
