### ISSUE TITLE
为什么从Polipo换成了Privoxy？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-windows#629]
https://github.com/shadowsocks/shadowsocks-windows/issues/277

请问有什么好处吗？

**Comment by breakwa11** [comment]
polipo有明显bug没修好

**Comment by pexcn** [comment]
@breakwa11 具体...?

**Comment by GangZhuo** [comment]
See https://github.com/shadowsocks/shadowsocks-windows/issues/249
