### ISSUE TITLE
Failed to update PAC from GFWList

### ISSUE THREAD

**Issue by RunningCool** [shadowsocks/shadowsocks-windows#630]
For shadowsocks-windows 2.5.6 & 3.0, I failed to update PAC from GFWList with the log:

> [2016-07-27 20:02:15] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
>    at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
>    --- End of inner exception stack trace ---
>    at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
>    at Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
> [2016-07-27 20:08:24] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
>    at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
>    --- End of inner exception stack trace ---
>    at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
>    at Shadowsocks.Controller.GFWListUpdater.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

I'm using shadowsocks under Windows 10 Version 10.0.10586. Server's encryption method is aes-256-cfb. Using Chrome + PAC Mode for visiting blocked sites.

I have also tried the following commands mentioned in #476, which is of no use eventually.

> netsh interface ipv4 reset
> netsh interface ipv6 reset
> netsh winsock reset

**Comment by GangZhuo** [comment]
Shadowsocks 2.5.6 update PAC from Google Code, which have been closed. Please update your shadowsocks.

**Comment by wongsyrone** [comment]
As mentioned above, you should update your shadowsocks.
ref: https://github.com/gfwlist/gfwlist

**Comment by wendingp** [comment]
I am using the latest dotnet-4.0 version, still got this error?

**Comment by chenshaoju** [comment]
please try using the latest version: https://github.com/shadowsocks/shadowsocks-windows/releases
