### ISSUE TITLE
不能同时开启多个 HTTP 代理（无法同时存在多个 ss_privoy）

### ISSUE THREAD

**Issue by RadarNyan** [shadowsocks/shadowsocks-windows#631]
同时运行两个 shadowsocks-windows 客户端可以实现在不同本地端口分别提供连接不同服务器的 Socks5 代理，但 HTTP 代理永远是中转后启动的（或者最后通过托盘右键菜单切换过服务器的）一个客户端的代理。

**Comment by LannSoros** [comment]
同样有分流多开的需求

**Comment by wongsyrone** [comment]
Similar to #430

**Comment by wongsyrone** [comment]
Close due to duplicate.

**Comment by celeron533** [comment]
既然有人提到分流，有没有可能使用haproxy windows（cygwin）来做负载均衡？
