### ISSUE TITLE
安卓模拟器内不能翻出去

### ISSUE THREAD

**Issue by ouzhou** [shadowsocks/shadowsocks-windows#632]
想玩pockmon go 网上找了个安卓模拟器，开了之后pc是可以上youtube的但是在模拟器内部没翻出去，但是肯定有网，ps 我pc连的wifi

**Comment by 772807886** [comment]
安卓模拟器里可以上play商店安装“影梭”

**Comment by ouzhou** [comment]
我在模拟器里面安装了影梭，然后开启 然后模拟器内部就连不上网了，关闭影梭后模拟器又可以连上

**Comment by GangZhuo** [comment]
检查你的安卓模拟器是否支持系统代理，如果不支持的话，可以通过 Proxifier 等类型软件使其通过代理访问网络。

**Comment by wongsyrone** [comment]
You can try this link, not verified yet.

ref: http://stackoverflow.com/questions/1570627/how-to-setup-android-emulator-proxy-settings

**Comment by wongsyrone** [comment]
No responses from issue reporter, closing.
