### ISSUE TITLE
3.0 版本 如果扫描 二维码大于 192X192 像素 有可能提示找不到

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-windows#633]
可能是WIN 10 下面才会发生。

**Comment by wongsyrone** [comment]
扫了一个587*580的，好像并没有问题，能否提供出问题的二维码（隐去信息）或者尝试最新master分支。

**Comment by myliyifei** [comment]
我这边反复做过实验了，不是100%出现，但是一旦出现问题的二维码，只要缩小像素就没问题。我一会找找。 另外最新的编译版本在哪里呢

**Comment by chenshaoju** [comment]
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/81frqylaa9lb7rm9/artifacts

点开后往下翻，有个 Shadowsocks.exe 。

**Comment by wongsyrone** [comment]
Please try latest release.
