### ISSUE TITLE
如何代理UDP数据流？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-windows#634]
例如Youtube的视频，用openwrt版的shadowsocks并开始UDP代理会流畅很多，可以达到9000kbps，但是用windows版的shadowsocks则最快只能2000kbps左右。

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/wiki/Shadowsocks-Windows-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#udp
