### ISSUE TITLE
目前使用shadowsocks 2.5.6，是否有必要更新到3.0版本？

### ISSUE THREAD

**Issue by vh2h** [shadowsocks/shadowsocks-windows#635]
目前使用shadowsocks 2.5.6，很稳定，也没出现过什么大问题。（小问题就是youtube有时网页打开了视频打不开要刷新一次，google map输入地址后按下enter没反应要重新加载一次。若有解决方法求告知，谢谢。）

请问是否有必要更新到最新版本？更新到最新版本有什么好处？最新版本是否更加稳定？

win7， ipv6， firefox最新版， autoproxy插件  ，vps自建ss python版 chacha20

谢谢大家！

**Comment by chenshaoju** [comment]
如果你不需要OTA支持（不记得什么版本开始支持的），可以考虑继续使用现有版本。

**Comment by wongsyrone** [comment]
在新版的libsscrypto里面更新了libsodium，它从1.0.7开始提供了针对SSSE3指令集优化的chacha20实现。
如果使用新版本没有什么问题的话，建议升级。

**Comment by vh2h** [comment]
@wongsyrone 谢谢，但我现在的加密方式已经是chacha20 了，你的意思是更新的话可以优化指令吗？只需要客户端更新不需要服务端更新吗？

**Comment by wongsyrone** [comment]
服务端的libsodium更新到1.0.7之后就行了

**Comment by vh2h** [comment]
@wongsyrone  好，谢谢你的建议。
