### ISSUE TITLE
3.0版本，如果里面含有多个同ip、同端口、不同密码的服务器会出错退出

### ISSUE THREAD

**Issue by terryxuwen** [shadowsocks/shadowsocks-windows#637]
我的shadowsocks里面设有两个服务器，ip 和端口都一样，但是密码不一样，备注当然不一样，升级到新版本3.0后，不断出错退出。后来修改其中一个服务器的ip或者端口，都可以正常运行。
老版本没有这个问题。

解释一下为什么会在shadowsock里面设有同ip同端口的服务器：因为我在不同vps服务器上都使用finalspeed，按照finalspeed的设置，在shadowsock端的服务器设置都是一样的，比如ip 都是127.0.0.1 端口都是 20000，但是密码不一样，备注当然也不一样。

**Comment by wongsyrone** [comment]
Please try https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.163/job/9ubrdla6b609f4n2/artifacts
