### ISSUE TITLE
新版退出实时流量统计界面时的错误(显示日志的界面)

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-windows#639]
![err](https://cloud.githubusercontent.com/assets/4590439/17426439/44735c58-5b0a-11e6-9721-7109f7204796.png)

**Comment by chenshaoju** [comment]
你使用的是appveyor上的 1.0.166 版本吗？我没有遇到该问题。

请问你是怎么退出流量统计的？点击小红叉？

**Comment by wongsyrone** [comment]
I cannot reproduce this on Windows 10 10586 x64, do you have any idea?  @celeron533

**Comment by pexcn** [comment]
奇怪了，我现在也无法复现刚才的异常了

**Comment by pexcn** [comment]
刚才又触发了这个异常，就是过一会儿关闭这个界面，就崩溃了

**Comment by pexcn** [comment]
也是 Windows 10 10586 x64

**Comment by celeron533** [comment]
![image](https://cloud.githubusercontent.com/assets/3608762/17436431/7ff6bbdc-5b49-11e6-90df-2ce6729f398b.png)

由于这个chart是放在LogForm上的，由于多线程的关系，很有可能在释放的瞬间，线程还是尝试去访问Chart。

目前我还在尝试重现问题，@pexcn 能否先尝试关闭可靠性统计？

![image](https://cloud.githubusercontent.com/assets/3608762/17436382/274caf5a-5b49-11e6-88f2-088219f6a56a.png)
![image](https://cloud.githubusercontent.com/assets/3608762/17436392/3e87a7d8-5b49-11e6-8017-8f1fddeaf397.png)

**Comment by pexcn** [comment]
以上的测试都已经关闭了可靠性统计了

**Comment by wongsyrone** [comment]
我测试的时候也没有开可靠性统计，尝试过
1. 打开之后立即关闭
2. 打开等待5分钟关闭
3. 打开观看YouTube影片（时间不等）后关闭
均没有重现。这里的关闭方法是右上角点叉，实在想不到还有其他关闭方法

**Comment by pexcn** [comment]
我也是点右上角的交叉关闭的，出现了两次，也不知道怎么重现的...

**Comment by celeron533** [comment]
基本确定是使用Invoke的时候产生竞争（race），正在修改代码

**Comment by celeron533** [comment]
PullRequest #641

**Comment by wongsyrone** [comment]
@pexcn 
Please test https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.168/job/8jugp1vtm569d72u/artifacts

**Comment by pexcn** [comment]
测试了多次，没有崩溃了

**Comment by wongsyrone** [comment]
PR merged.

**Comment by celeron533** [comment]
@wongsyrone @pexcn 真的是非常抱歉，犯了如此简单的错误。

**Comment by wongsyrone** [comment]
淡定

**Comment by pexcn** [comment]
淡定……
