### ISSUE TITLE
我有个很弱弱的请求，关于提供旧版但取消更新提醒

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadowsocks-windows#640]
是这样的，看到很多Issues里面有提到一些3.0的错误，评论也有好心人给了一些特别修改版，但是我试过所有的版本，都有问题，包括万恶的迅雷，我卸载的情况下依然都有问题，但是怪异的是，用2.5.8版本，我不管安装不安装迅雷都能正常使用了，1年多来我都是用2.5.8版，但是每次开机的更新提醒让我很难受。不知道有没有开发者愿意在2.5.8分支上单独再出一个不会检测和提醒更新的版本。

拜谢了。

我知道我的需求很奇怪，但是希望有好心的开发者可以帮我一下。

**Comment by yqy6611** [comment]
然而我这用3.0毫无问题，也在用迅雷

**Comment by DearTanker** [comment]
@yqy6611 电脑环境差别比较大，我公司的电脑一模一样的系统，但是3.0也是用的很high。但是家里电脑的3.0死活就是用不了啊。

**Comment by chenshaoju** [comment]
请尝试升级到最新版迅雷，以及使用测试版Shadowsocks：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/i7x7hu2k3bvfry5t/artifacts

**Comment by DearTanker** [comment]
@chenshaoju 我肯定是试过最新的迅雷9，迅雷7，迅雷极速版的。我试试看这个测试版吧。

**Comment by celeron533** [comment]
@DearTanker 试试看先卸掉迅雷（应该会自动清除服务），然后重新安装

目前我在使用迅雷9，和SS 3.1 dev没有冲突
![image](https://cloud.githubusercontent.com/assets/3608762/17462439/bbde1b12-5cdf-11e6-9b4e-b4aae8af2e52.png)

**Comment by DearTanker** [comment]
@celeron533 必须是试过了，而且还默认关掉了关联浏览器那些选项。
@chenshaoju 目前为止用最新的测试版没有问题。
