### ISSUE TITLE
3.0版本无法使用了

### ISSUE THREAD

**Issue by Leetroch** [shadowsocks/shadowsocks-windows#643]
经过排除后我确认不是服务器问题也不是自己网络问题，WINDOWS的QT5版本的客户端可以正常使用，而C#版本则不行。
**chorome浏览器提示：**
无法访问此网站
连接已重置。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_RESET

**日志一直显示：**

> [2016-08-06 19:15:57] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:15:57] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:15:57] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:15:58] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:15:58] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:15:58] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:15:58] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:15:58] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:15:59] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:15:59] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>    在 System.Net.Sockets.Socket.get_RemoteEndPoint()
>    在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
> [2016-08-06 19:16:00] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
>

**Comment by wongsyrone** [comment]
你是从Release的3.0里面下载的吗

**Comment by yqy6611** [comment]
@wongsyrone 还可以从哪下？虽然用release里的没问题。

**Comment by chenshaoju** [comment]
请尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/i7x7hu2k3bvfry5t/artifacts

**Comment by Leetroch** [comment]
谢了大神，只不过今天ss 3.0又正常了

2016-08-07 9:58 GMT+08:00 Chen Shaoju <notifications@github.com>:

**Comment by XADlwx** [comment]
安装Microsoft .NET Framework 4.5 解决了 SS 3.0 version 崩溃问题。

**Comment by wongsyrone** [comment]
Please test https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe

**Comment by Ezrea** [comment]
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset

这个对我有效果
