### ISSUE TITLE
是否会增加内置kcptun支持的计划吗？

### ISSUE THREAD

**Issue by Anyfc** [shadowsocks/shadowsocks-windows#644]
目前android已经内置了kcptun，想问问windows版有内置的计划吗？

**Comment by wongsyrone** [comment]
因为android版要使用VpnService且要交叉编译kcptun，全部留给用户不太友好，所以才内置了。win有现成的教程，而且在kcptun更新的时候，更新内置版本比较费事。所以wontfix

教程比如https://www.fanyueciyuan.info/fq/kcptun_ss.html，难点只在于启动客户端

**Comment by ipfans** [comment]
其实考虑只进行协议支持：https://github.com/limpo1989/kcp-csharp

**Comment by celeron533** [comment]
能否在服务器配置页面下加一个“启动特定程序”以及“启动参数”，并“切换服务器时杀掉特定托管进程”
> 教程比如https://www.fanyueciyuan.info/fq/kcptun_ss.html ，难点只在于启动客户端

**Comment by chenshaoju** [comment]
@celeron533 实际上写一个批处理反而比较简单。。。

**Comment by celeron533** [comment]
各种混淆器、前置后置代理也可以通过一个批处理启动~
> @celeron533 实际上写一个批处理反而比较简单。。。

**Comment by gengjiawen** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG Mac版也有这个Feature了，Windows版也可以考虑加这个Feature。

**Comment by celeron533** [comment]
虽然kcp能够增加稳定性和有效带宽，但是在配置不当的情况下会导致双倍甚至3 4 5 6倍的发送占用带宽，加剧国际出口拥堵。

**Comment by breakwa11** [comment]
不好意思，即使是默认配置在最理想的局域网环境下效率也才59%，非局域网下至少是双倍发包，较好线路的VPS是3倍发包，较差的时候是4倍以上

**Comment by celeron533** [comment]
@breakwa11 我使用了最保守的normal并且还微调了部分参数力图减少重发，网络较好时，实际带宽好像是逻辑带宽的1.5倍，可能有误，有机会再测测

**Comment by breakwa11** [comment]
给你一组数据，我很早就测试出来的：


kcptun 20160725版有效负载率测试 
节点地址香港沙田，测试使用游戏方式 
模式   实测平均 
Normal 43% 
Fast  38% 
Fast2 34% 
Fast3 31% 
具体结果可能因节点不同产生差异


kcptun 20161031版，网络有效利用率测试：
环境：本地千兆（1Gbps）局域网
服务端操作系统：ubuntu 14.04 server x86
客户端操作系统：windows 8.1
配置采用默认
测试方式：通过FDM无限速方式下载本地一个3.84G大小的文件
结果：
平均下载速度:7.8Mb/s
下载完1G时，
    下载使用总流量：1.75G
    有效流量57%
下载完时，
    下载使用总流量：6.46G
    有效流量59%


20160809测试
BWG los测试FinalSpeed（默认配置，UDP方式）
非高峰时段（中午）：
下载300M文件：总流量357M，有效负载84%
3线程各下载1G文件：总流量3.58G，有效负载84%
高峰时段（21:00）：
2线程各下载300M文件：总流量806M，有效负载74%


“暴力”的FS上搬瓦工这种垃圾线路都比KCP在本地局域网的效率高得多，谁才是暴力之王一眼便知
其实如果低于50%，还不如直接上那个啥双倍发包工具呢。。。又省内存而且只是单边双倍
不过我也好久没测试新版本了，如果新版本的效率高很多的话，欢迎来打我脸

**Comment by celeron533** [comment]
感谢@breakwa11 提供的测试数据。
刚刚简单测了一下，上海电信的国际出口，周六晚高峰

随意访问youtube页面，和直接下载文件相比，请求数量比较零碎。
服务器实际开销：24M，接收端15.5M，64%效率。

下载virtualbox
服务器：263M，接收端118M，45%效率，确实比较惨。

其实KCP“效率底下”有个重大因素就是向前纠错，比如我的服务端向前纠错设置 datashard=10, patityshard=3，相当于往原始数据里面添加了30%的校验来减少重传。（所以理论速度是10/(10+3)=77%，不带压缩，未计算各种包头损耗）
另外网页jpeg图片，MP4影片和软件安装包本身就已经是被压缩过的格式，所以kcptun的压缩功能几乎无用，估计在浏览文字或bmp图片的时候性能会有较大提高。

没有对比就没有伤害，要考虑换FinalSpeed了。。。

**Comment by gengjiawen** [comment]
即使kcp效率低下,但是对速度的提升还是巨大的,有的场景还是挺需要的,Windows客户端不实现还是有所缺憾.

**Comment by celeron533** [comment]
@gengjiawen ，其实也就是手工再开一个kcptun的事情而已，然而一旦普及，这个东西在配置不当的情况下非常可怕。

**Comment by hhding** [comment]
@breakwa11 不知道你提供的测试数据相关参数是什么？我的理解是 datashard, partyshard, dscp 这些参数是影响传输带宽效率以及成功率的，一般而言冗余越高，成功率越高，但是效率越低。如果以上额外传输校验的内容能够刚好抵消掉丢包率的话，理论上来说两者传输的流量是相等的，并没有浪费，在某些极端情况下（譬如 TCP 由于丢包比较早，重传所有丢包之后发送的包），可能 KCP 效率还会更高。

最后，我们到国外的带宽是不是真的是个瓶颈，这个问题还真不清楚。

**Comment by chinawrj** [comment]
@celeron533 选择权交给用户
