### ISSUE TITLE
3.0版本 运行后 崩溃 出现bug 

### ISSUE THREAD

**Issue by XADlwx** [shadowsocks/shadowsocks-windows#648]
3.0版本 运行后 崩溃 出现bug

**Comment by ABlice** [comment]
win10 X64专业版。原来正常使用时shadowsocks版本号1.0.172。
下载覆盖更新1.0.178后，提示非预期错误。见 附图1
![1](https://cloud.githubusercontent.com/assets/17591336/17488742/59c2d9ba-5dcd-11e6-8331-a0a3011c4e16.png)

因为看不懂提示，用了下面的处理办法；换文件路径，重新添加节点。提示错误，见图2
![2](https://cloud.githubusercontent.com/assets/17591336/17488904/15560c24-5dce-11e6-976e-1734611d9b83.png)

结果是无法添加节点配置参数
下面这些算错误日志？
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Model.Server.FriendlyName()
   在 Shadowsocks.View.MenuViewController.UpdateServersMenu()
   在 Shadowsocks.View.MenuViewController.LoadCurrentConfiguration()
   在 Shadowsocks.View.MenuViewController.controller_ConfigChanged(Object sender, EventArgs e)
   在 System.EventHandler.Invoke(Object sender, EventArgs e)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.View.ConfigForm.OKButton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Shadowsocks
    程序集版本:3.1.0.0
    Win32 版本:3.1.0.0
    基本代码:file:///D:/Program%20Files/Browser/Shadowsocks/Shadowsocks.exe
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:8.0.0.0
    Win32 版本:3.1.0.0
    基本代码:file:///D:/Program%20Files/Browser/Shadowsocks/Shadowsocks.exe
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

调取shadowsocks程序自带的日志，如下：

[2016-08-09 00:30:26] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2016-08-09 00:30:27] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2016-08-09 00:30:27] System.ArgumentException: No server configured
   在 Shadowsocks.Controller.TCPHandler.CreateRemote()
   在 Shadowsocks.Controller.TCPHandler.StartConnect()
[2016-08-09 00:30:32] Shadowsocks started
[2016-08-09 00:30:32] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Model.Server.FriendlyName()
   在 Shadowsocks.View.MenuViewController.UpdateServersMenu()
   在 Shadowsocks.View.MenuViewController.LoadCurrentConfiguration()
   在 Shadowsocks.View.MenuViewController.controller_ConfigChanged(Object sender, EventArgs e)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Controller.ShadowsocksController.AddServerBySSURL(String ssURL)
[2016-08-09 00:30:40] Shadowsocks started
[2016-08-09 00:30:40] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Model.Server.FriendlyName()
   在 Shadowsocks.View.MenuViewController.UpdateServersMenu()
   在 Shadowsocks.View.MenuViewController.LoadCurrentConfiguration()
   在 Shadowsocks.View.MenuViewController.controller_ConfigChanged(Object sender, EventArgs e)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Controller.ShadowsocksController.AddServerBySSURL(String ssURL)
[2016-08-09 00:31:22] Shadowsocks started
[2016-08-09 00:31:22] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Model.Server.FriendlyName()
   在 Shadowsocks.View.MenuViewController.UpdateServersMenu()
   在 Shadowsocks.View.MenuViewController.LoadCurrentConfiguration()
   在 Shadowsocks.View.MenuViewController.controller_ConfigChanged(Object sender, EventArgs e)
   在 System.EventHandler.Invoke(Object sender, EventArgs e)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Controller.ShadowsocksController.AddServerBySSURL(String ssURL)
[2016-08-09 00:31:29] Shadowsocks started
[2016-08-09 00:31:29] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Model.Server.FriendlyName()
   在 Shadowsocks.View.MenuViewController.UpdateServersMenu()
   在 Shadowsocks.View.MenuViewController.LoadCurrentConfiguration()
   在 Shadowsocks.View.MenuViewController.controller_ConfigChanged(Object sender, EventArgs e)
   在 System.EventHandler.Invoke(Object sender, EventArgs e)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Controller.ShadowsocksController.AddServerBySSURL(String ssURL)
[2016-08-09 00:31:43] [E] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Model.Server.FriendlyName()
   在 Shadowsocks.View.MenuViewController.UpdateTrayIcon()
   在 Shadowsocks.View.MenuViewController..ctor(ShadowsocksController controller)
   在 Shadowsocks.Program.Main()
[2016-08-09 00:32:00] [E] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Model.Server.FriendlyName()
   在 Shadowsocks.View.MenuViewController.UpdateTrayIcon()
   在 Shadowsocks.View.MenuViewController..ctor(ShadowsocksController controller)
   在 Shadowsocks.Program.Main()


解决办法，怀疑是1.0.178问题或电脑权限问题，下载1.0.173到1.0.178，挨个覆盖更新或换文件路径或右键管理员运行，都遇到相同问题。换回1.0.172后能恢复正常使用。

希望专业人员帮看看我的问题出在哪，如何解决。谢谢！
如果日志不够详细，麻烦指出。我会回帖补齐。

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/465#issuecomment-238201668

**Comment by wongsyrone** [comment]
Use 1.0.174 in Appveyor, don't use builds belong to PR.

**Comment by XADlwx** [comment]
这个不是SS 3.0 version 问题 是 win7 OS没有安装Microsoft .NET Framework 4.5 解决了 SS 3.0 version 崩溃问题。

**Comment by ABlice** [comment]
shadowsocks文件夹换到D盘，shadowsocks1.0.180 第一次运行，手动添加配置参数，点击确定后 如图
![default](https://cloud.githubusercontent.com/assets/17591336/17524460/4c1f580a-5e91-11e6-834d-8263396472e9.png)

日志
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Model.Server.FriendlyName()
   在 Shadowsocks.View.MenuViewController.UpdateServersMenu()
   在 Shadowsocks.View.MenuViewController.LoadCurrentConfiguration()
   在 Shadowsocks.View.MenuViewController.controller_ConfigChanged(Object sender, EventArgs e)
   在 System.EventHandler.Invoke(Object sender, EventArgs e)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.View.ConfigForm.OKButton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Shadowsocks
    程序集版本:3.1.0.0
    Win32 版本:3.1.0.0
    基本代码:file:///D:/Shadowsocks/Shadowsocks.exe
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:8.0.0.0
    Win32 版本:3.1.0.0
    基本代码:file:///D:/Shadowsocks/Shadowsocks.exe
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

换1.0.174结果是一样。

**Comment by wongsyrone** [comment]
贴gui-config内容

**Comment by ABlice** [comment]
{
  "configs": [
    {
      "server": "",
      "server_port": 8388,
      "password": "",
      "method": "aes-256-cfb",
      "remarks": "",
      "auth": false
    },
    {
      "server": "马赛克",
      "server_port": 马赛克,
      "password": "马赛克",
      "method": "rc4-md5",
      "remarks": "",
      "auth": false
    }
  ],
  "strategy": null,
  "index": 1,
  "global": false,
  "enabled": false,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "pacUrl": null,
  "useOnlinePac": false,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "isVerboseLogging": false,
  "logViewer": null,
  "useProxy": false,
  "proxyServer": null,
  "proxyPort": 0
}

![default](https://cloud.githubusercontent.com/assets/17591336/17537265/c579ba88-5ecd-11e6-8225-0fcb79917aae.png)

**Comment by ABlice** [comment]
{
  "configs": [
    {
      "server": "马赛克",
      "server_port": 马赛克,
      "password": "马赛克",
      "method": "rc4-md5",
      "remarks": "",
      "auth": false
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": false,
  "shareOverLan": false,
  "isDefault": false,
  "localPort": 1080,
  "pacUrl": null,
  "useOnlinePac": false,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "isVerboseLogging": false,
  "logViewer": null,
  "useProxy": false,
  "proxyServer": null,
  "proxyPort": 0
}

**Comment by wongsyrone** [comment]
从CI下载1.0.180，使用便携模式，按照截图中的配置文件，无法复现你的问题，环境win10 10586 x64.

**Comment by rebiu** [comment]
win 10最新版，昨天才重装的，网络软件只安装了steam和FDM5，1.0.180，使用便携模式，手动输入配置，全新目录，点击确定一样崩溃，1.0.174开始的版本都是崩溃的，现在用1.0.170没问题。另外二维码有扫描不到的情况，前面有个issue提到

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Shadowsocks.Model.Server.FriendlyName()
   在 Shadowsocks.View.MenuViewController.UpdateServersMenu()
   在 Shadowsocks.View.MenuViewController.LoadCurrentConfiguration()
   在 Shadowsocks.View.MenuViewController.controller_ConfigChanged(Object sender, EventArgs e)
   在 System.EventHandler.Invoke(Object sender, EventArgs e)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.View.ConfigForm.OKButton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Shadowsocks
    程序集版本:3.1.0.0
    Win32 版本:3.1.0.0
    基本代码:file:///F:/downloads/a/Shadowsocks.exe
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:8.0.0.0
    Win32 版本:3.1.0.0
    基本代码:file:///F:/downloads/a/Shadowsocks.exe
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1586.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

二维码例子：https://www.mianvpn.com/#free，点击通用配置出来的二维码不能扫描

**Comment by wongsyrone** [comment]
你那个二维码的例子是SSR的，不是SS标准格式，所以不能识别。如果有标准格式二维码不能扫描的，贴出样例。

**Comment by wongsyrone** [comment]
使用便携模式在exe同目录找到temp，贴出里面shadowsocks.log的内容，用1.0.180版本的来测。

**Comment by rebiu** [comment]
[2016-08-10 11:00:33] Shadowsocks started
[2016-08-10 11:00:58] Shadowsocks started
[2016-08-10 11:00:58] [E] Invalid server IP Address
[2016-08-10 11:07:37] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 无法从传输连接中读取数据: 连接已关闭。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-08-10 11:07:47] System.InvalidOperationException: 进程已退出，因此无法获得所请求的信息。
   在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.get_MainWindowHandle()
   在 System.Diagnostics.Process.CloseMainWindow()
   在 Shadowsocks.Controller.PolipoRunner.KillProcess(Process p)

@wongsyrone

**Comment by wongsyrone** [comment]
[E] Invalid server IP Address
IP地址无效，你用的是域名吧

**Comment by ABlice** [comment]
win10 X64 10.0.14393.0 。同样的路径D盘shadowsocks文件夹，使用便携模式，比较了一下1.0.180和1.0.172。
先说结果1.0.172没有问题，1.0.180问题依旧。（高于1.0.173的版本有同1.0.180一样的问题）

分别录制了2个gif，记录了操作过程 。

先贴1.0.180的MD5和gif
![1 0 180](https://cloud.githubusercontent.com/assets/17591336/17542669/7d22567a-5efd-11e6-821d-73dd85262e6f.png)

![1 0 180](https://cloud.githubusercontent.com/assets/17591336/17542672/824fcbf0-5efd-11e6-910c-a7498817a65f.gif)

再贴1.0.172的MD5和gif
![1 0 172](https://cloud.githubusercontent.com/assets/17591336/17542688/aedffd2a-5efd-11e6-8393-8ab1c6f37d12.png)

![1 0 172](https://cloud.githubusercontent.com/assets/17591336/17542693/b6b51738-5efd-11e6-8e38-418b70364769.gif)

**Comment by wongsyrone** [comment]
Please try 1.0.181

**Comment by ABlice** [comment]
谢谢！已正常，直接下载的1.0.182

**Comment by wongsyrone** [comment]
OK, closing.

**Comment by rebiu** [comment]
1.0.182 这里也正常了，多谢修复
