### ISSUE TITLE
3.1版本频繁异常退出

### ISSUE THREAD

**Issue by lyhper** [shadowsocks/shadowsocks-windows#650]
![image](https://cloud.githubusercontent.com/assets/13343726/17542588/b02f85f2-5efc-11e6-9fa7-5b7924721bf4.png)
![image](https://cloud.githubusercontent.com/assets/13343726/17542616/ea5699e6-5efc-11e6-8869-1222c7c68a20.png)

**Comment by wongsyrone** [comment]
能否提供问题复现步骤

**Comment by lyhper** [comment]
没有任何操作，打开一段时间就会出现

**Comment by wongsyrone** [comment]
Please test latest commit.

**Comment by celeron533** [comment]
LogForm的Chart争用。。。
最新编译版应该已修复，参见#639

**Comment by wongsyrone** [comment]
Reopen if you still have this issue.
