### ISSUE TITLE
升级到3.2版本之后开启一次性认证就不能使用了

### ISSUE THREAD

**Issue by zhou960405** [shadowsocks/shadowsocks-windows#659]
以前一直用的都是2.5.8版本，因为有次升级到3.0版本时，发现跟我的网游加速器有冲突，每次开关网游加速器，ss就不能使用了，必须要重新启动电脑才能正常使用，就换回来2.5.8版本，今早升级到3.2版本后发现多了一个一次性认证功能，勾选上之后发现ss无法使用了，每次进google都会提示502 proxy error，取消勾选后恢复正常，这是怎么了？

**Comment by wongsyrone** [comment]
If your server or service provider doesn't support OTA, don't enable it.
