### ISSUE TITLE
v3.2.0版本中新增的socks5代理设置选项是做什么的？

### ISSUE THREAD

**Issue by leohxj** [shadowsocks/shadowsocks-windows#672]
默认socks5的端口是1080，这个是修改这个的吗？
如要要修改，设置127.0.0.1:xxxx,  xxxx为想要设置的端口？

**Comment by wongsyrone** [comment]
前置代理

**Comment by leohxj** [comment]
@wongsyrone 
是为了让shadowsocks.exe走这个指定的代理吗？
不太理解实际应用场景有哪些？
3q

**Comment by wongsyrone** [comment]
是的，有些企业网络需要通过代理才能访问外部网络

**Comment by leohxj** [comment]
@wongsyrone got it.
类似proxifier的作用。

**Comment by huayuanp** [comment]
可以把socket5转成http代理？

**Comment by leohxj** [comment]
@huayuanp 允许局域网内连接的那个选项，就是开启一个http代理。

这个前置代理，应该是给 shadowsocks.exe 本身的代理设置，使得 它 自己走某个代理。因为有些公司，内网环境下需要代理才可以访问外网。

**Comment by BiyuHuang** [comment]
正向代理设置，设置成公司的代理服务器，日志报错：代理请求失败。 是需要加上用户与密码吗？

**Comment by ijunfly** [comment]
大神们,  公司MAC电脑装的有shadowsocks, 账号并且能使用, 浏览器正常访问外网,  我现在使用一些APP时 需要SS开全局才能访问外网, 请问怎么设置socks5 代理, 谢谢
