### ISSUE TITLE
编辑用户规则的时候出现的问题

### ISSUE THREAD

**Issue by 772807886** [shadowsocks/shadowsocks-windows#674]
编辑用户规则之后，保存时偶尔会出现。
![default](https://cloud.githubusercontent.com/assets/10294977/17853443/0b2b4abc-689f-11e6-90fc-f403ea05bfd7.PNG)

**Comment by 772807886** [comment]
不是100%重现。

版本：master分支自己Release编译的版本。
本地版本库最后一次commit log:
commit a1eef6eac1499ad9baf985bb5d6fa3a6c2b4246c
Author: Noisyfox <timemanager.rick@gmail.com>
Date:   Thu Aug 18 21:31:01 2016 +1000

**Comment by wongsyrone** [comment]
你是在开启PAC模式系统代理的情况下保存PAC的吗？

**Comment by 772807886** [comment]
@wongsyrone 是的

**Comment by wongsyrone** [comment]
我今天白天试了一下，并没有重现。

**Comment by 772807886** [comment]
@wongsyrone 经过我的测试，找到了原因：就是在浏览器正在请求的同时，这时如果同时按下ctrl+s就有很大几率复现了。
复现步骤（比较粗暴）：
首先断网，然后本地创建一个html文档并包含jquery，然后Chrome浏览器打开，然后在Chrome的控制台里输入setInterval("$.ajax('https://www.google.com');",100)，然后回车执行【频繁模拟请求，所以最好先断网】。然后打开user-rule.txt文件进行保存操作，就会出现这个异常了。
并且经过测试，只有服务器地址是ip形式才会出现，服务器地址如果是域名形式，在测试的时候不会出现异常（应该是断网状态无法解析域名）。

**Comment by 772807886** [comment]
同步到最新版本后，测试发现暂时没有再现了。
