### ISSUE TITLE
SS是否有针对下载进行优化？提高国外软件的下载速度？

### ISSUE THREAD

**Issue by msls** [shadowsocks/shadowsocks-windows#675]
使用SS版本：shadowsocks-manyuser
最近需要使用ss翻到国外更新Android7，但是速度非常慢。
SS有没有针对于下载的相关优化，提高Android7等国外软件的更新速度？

**Comment by wongsyrone** [comment]
Shadowsocks-libev is recommended as server-side, others depend on various aspects.
