### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。

### ISSUE THREAD

**Issue by posedge123** [shadowsocks/shadowsocks-windows#678]
之前的方法都不管用，还有别的方法吗？

**Comment by chenshaoju** [comment]
请尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/uvu9en8tpxn5c2pe/artifacts

**Comment by posedge123** [comment]
还是不行，同样的错误

**Comment by chenshaoju** [comment]
请检查你的服务器IP、端口、加密协议、OTA等选项是否正确，如果你是复制粘贴的，有时候会复制一个空格过来。

**Comment by posedge123** [comment]
我是扫描二维码方式添加的。。。。

**Comment by chenshaoju** [comment]
不知道了，可能是服务器关闭了或者其他原因。
如果你有Android设备，可以试试手机版是否好用。

**Comment by Noisyfox** [comment]
升级或者卸载你的迅雷，或者禁用 XLServicePlatform 服务

**Comment by posedge123** [comment]
迅雷之前已经卸了，家里的macbookpro是没问题的。。。

**Comment by Noisyfox** [comment]
试试看 netsh winsock reset

**Comment by 772807886** [comment]
卸载迅雷在有些时候还是会残留XLServicePlatform服务的。

**Comment by wongsyrone** [comment]
如果使用了旧版迅雷，通过下面的注册表脚本和命令完成清理。

```reg
Windows Registry Editor Version 5.00
[-HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\XLServicePlatform]
```

```bat
net stop XLServicePlatform
```
