### ISSUE TITLE
新版本（3.2）崩溃

### ISSUE THREAD

**Issue by sunday1103** [shadowsocks/shadowsocks-windows#679]
新版本经常崩溃，这是最近一次弹出的信息。（以前没有弹出过）

![image](https://cloud.githubusercontent.com/assets/3799028/17923133/308444b8-6a15-11e6-91fa-d2386d9874ff.png)

系统状况：
![image](https://cloud.githubusercontent.com/assets/3799028/17923176/6e49a59a-6a15-11e6-8d2c-99614fd31590.png)

**Comment by chenshaoju** [comment]
请尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/uvu9en8tpxn5c2pe/artifacts

**Comment by wongsyrone** [comment]
Please try latest Appveyor version.
