### ISSUE TITLE
与 Virtualbox 冲突，无法正常运行

### ISSUE THREAD

**Issue by littlee** [shadowsocks/shadowsocks-windows#680]
Windows 7 x64
安装 Docker Toolbox 之后，会顺带安装 Virtual Box 
Virtual Box 会创建虚拟网络适配器
![qq 20160825230238](https://cloud.githubusercontent.com/assets/7534668/17974309/2c15e95a-6b18-11e6-9bef-de009548da0a.png)

若启用这些虚拟的网络适配器，则无法使用 shadowsocks
有不禁用虚拟网络适配器的解决方案吗?

**Comment by 772807886** [comment]
我也安装了并使用Virtual Box，但并没有影响到ss的使用。。

**Comment by chenshaoju** [comment]
并没有影响，这两者不冲突。
VirtualBox  5.0.20 r106931

**Comment by wongsyrone** [comment]
According to feedbacks above, it is not caused by shadowsocks.
Closing this.
