### ISSUE TITLE
会阻止电脑自动睡眠吗？

### ISSUE THREAD

**Issue by WJvsToo** [shadowsocks/shadowsocks-windows#683]
电脑不知道从什么时候，没了自动睡眠。。今天测试策略组把，程序阻止自动睡眠禁用掉就可以了。
然后恢复之前设置，一个一个排查程序，发现退出shadowsocks竟然就没问题了，这是什么情况

**Comment by chenshaoju** [comment]
不会。
如果你坚持认为这是SS的问题，可通过系统自带的工具确认问题，详见：
https://plus.google.com/u/0/108281241220294160411/posts/eQXF5gDLR5L

**Comment by WJvsToo** [comment]
好的，谢谢
