### ISSUE TITLE
请问3.2如何进行ipv6设置？

### ISSUE THREAD

**Issue by andrew-wiseman** [shadowsocks/shadowsocks-windows#685]
我以前在2.5的时候，设置的ipv6的格式可以正常工作，现在不可以了。

设置格式如下：

    {
      "server": "[2607:1234:109:1234::]",
      "server_port": 443,
      "password": "自行设定",
      "method": "aes-256-cfb",
      "remarks": "自行设定",
      "auth": false
    }

**Comment by wongsyrone** [comment]
你说的不能工作，有没有错误日志或者弹窗提示。

**Comment by Noisyfox** [comment]
错误日志有么

**Comment by andrew-wiseman** [comment]
我已找到原因，是服务器端密码配置有问题。另外"server": "[2607:1234:109:1234::]"应改为"server": "2607:1234:109:1234::"

谢谢二位的热心回复 @wongsyrone @Noisyfox
