### ISSUE TITLE
Privoxy update

### ISSUE THREAD

**Issue by xbb123** [shadowsocks/shadowsocks-windows#686]
Privoxy 3.0.26 stable has been released, which introduced client-specific tags and included a couple of minor improvements. Please update the built-in Privoxy.
Thanks!

**Comment by wongsyrone** [comment]
Done in https://github.com/shadowsocks/shadowsocks-windows/commit/cbc94e0eb7d148a677518fd23a7e1fba7a90bbbe

**Comment by xbb123** [comment]
Wow, that was efficient!
Thanks for your work.
