### ISSUE TITLE
miui8上使用似乎会有些问题

### ISSUE THREAD

**Issue by ywg663** [shadowsocks/shadowsocks-windows#690]
miui8上使用似乎会有些问题，会使设备无法连接外网，断掉shadowsocks就可以了，需要fq时再行连接上shadowsocks,不过一会儿又不能连接外网了...!!

**Comment by pexcn** [comment]
miui?

**Comment by wongsyrone** [comment]
Wrong project

**Comment by ywg663** [comment]
xiaomi android miui8

**Comment by ywg663** [comment]
http://www.miui.com/

**Comment by chenshaoju** [comment]
你好，这是Windows版本，不是Android版本的Shadowsocks。

**Comment by ywg663** [comment]
抱歉！！

**Comment by 772807886** [comment]
安卓版本的影梭在这里：https://github.com/shadowsocks/shadowsocks-android
