### ISSUE TITLE
UDP relay does not work with IPv6

### ISSUE THREAD

**Issue by rayline** [shadowsocks/shadowsocks-windows#691]
To be clear I will use a table

  | IPv4 | IPv6
------------ | -----|--------
TCP | Good | Good
UDP | Good | Bad

I have made sure that my server has UDP relay on and it is listening on both IPv4 and IPv6 with both TCP and UDP.

**Comment by wongsyrone** [comment]
Do you mean 3.2? Please try https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/1.0.220/job/f2bufwqygnnfty8y/artifacts

**Comment by rayline** [comment]
same problem in that version

**Comment by Noisyfox** [comment]
More specifically. What problem?

**Comment by rayline** [comment]
As is described, UDP relay does not work when it connects to the remote server through IPv6. There is no log printed and no traffic is displayed.
I am using version 3.2

**Comment by Noisyfox** [comment]
Did you try the version in that link?

**Comment by wongsyrone** [comment]
Close due to inactive, reopen if you can provide more info.

**Comment by gerwang** [comment]
Same issue using version 3.4.3.

**Comment by gerwang** [comment]
I am using shadowsocks-python on server and test ipv6 udprelay using sockscap64. it succeed via ipv4 but failed via ipv6.

**Comment by gerwang** [comment]
### 重现方法：
使用教育网ipv6
为shadowsocks设置ipv6代理（服务器为搬瓦工）
测试网页能够正常访问
打开sockscap64
打开 代理->本地代理->右键我设置的shadowsocks代理->`测试选中代理的udp转发`
显示转发失败
切换成同一个服务器的ipv4代理，重复上面的测试步骤
显示转发成功
