### ISSUE TITLE
Shadowsocks Windows 3.2 切换服务器失效,得重启客户端才能生效

### ISSUE THREAD

**Issue by huilang-me** [shadowsocks/shadowsocks-windows#694]
Shadowsocks Windows 3.2 切换服务器失效,得重启客户端才能生效

**Comment by wongsyrone** [comment]
Try this https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/qhu72wtx1nmhld2h/artifacts

**Comment by huilang-me** [comment]
可以了,就是每次打开有一个安全警告,希望下次更新可以修复

其实切换也不多用,旧版先用着

**Comment by wongsyrone** [comment]
警告有截图吗

**Comment by Noisyfox** [comment]
@wongsyrone 应该是smartscreen的警告，类似不要执行从网上下载的exe之类的。应该就第一次会弹，同意了以后就不会再弹了

**Comment by huilang-me** [comment]
http://img.huilang.me/warning.png   去掉打开前总是询问就可以了

**Comment by wongsyrone** [comment]
右键属性，win10去掉“取消锁定”复选框就行了，在win7上是个按钮

**Comment by wongsyrone** [comment]
这个是Windows的安全机制，直接下载到的是exe就会默认锁定，不是SS本身的问题。

**Comment by huilang-me** [comment]
@wongsyrone 好的 谢谢
