### ISSUE TITLE
Shadowsocks-Windows 3.2 经常崩溃

### ISSUE THREAD

**Issue by hong6234** [shadowsocks/shadowsocks-windows#695]
![ss-windows 3.2](https://cloud.githubusercontent.com/assets/1768433/18235228/c6287ed8-734a-11e6-9a69-801c12e49ecd.png)

Shadowsocks-Windows 3.2 经常崩溃，大概1个小时内出现了10次左右，debug信息参考图片

**Comment by Noisyfox** [comment]
测试版已经解决了这个问题，你可以试试看

**Comment by wongsyrone** [comment]
Try this https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/qhu72wtx1nmhld2h/artifacts

**Comment by wongsyrone** [comment]
Close due to inactive.
