### ISSUE TITLE
Windows 10 permission issue.

### ISSUE THREAD

**Issue by zhuchun** [shadowsocks/shadowsocks-windows#699]
**Issue**

Throw an exception says can't read from "gui-config.json" when try to save server config file.

**Reason**

Windows 10 have extra limitation at C:\ so SS can't save that file.

**Solve**

Do NOT put the exe file at C:\.

**Comment by wongsyrone** [comment]
Use portable mode or grant Administrative permission to Shadowsocks.
I don't think this is Shadowsocks' issue.

**Comment by zhuchun** [comment]
That's correct, but we don't expect users are experts. In some case new user may rush here and download the release to somewhere like C:\Downloads and find it doesn't work. IMHO, it can be avoid by simply add lines in ReleaseNote/FAQ.

**Comment by wongsyrone** [comment]
Added in https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
