### ISSUE TITLE
希望能添加「启用系统代理」等功能的快捷键

### ISSUE THREAD

**Issue by taroxd** [shadowsocks/shadowsocks-windows#706]
类似于 chrome 的 switchyomega 插件，方便随时切换代理状态。（我不是很喜欢 pac。因为网络环境经常变化，即使是相同的网站也可能是一会儿用代理一会儿不用）

**Comment by wongsyrone** [comment]
Pull requests are welcome for this feature.

**Comment by reaCodes** [comment]
我也很需要快捷键，可是我没能力共享代码，只能发个声支持一下 😅

**Comment by wongsyrone** [comment]
Please test https://github.com/shadowsocks/shadowsocks-windows/pull/724

**Comment by wongsyrone** [comment]
Done.
If you find anything wrong, open another issue.
