### ISSUE TITLE
更新Shadowsocks至3.0之后版本无法启动报错的问题

### ISSUE THREAD

**Issue by Minalinsky9-12** [shadowsocks/shadowsocks-windows#707]
![image](https://cloud.githubusercontent.com/assets/12980376/18408534/f0aff60e-7764-11e6-84d2-1baaa41c4a05.png)

OS环境 Windows 10

经多次测试，发现回滚至使用3.0或以前版本则正常.
疑因或是与旧版本的gui-config.json (存放服务器地址等的配置文件)不兼容导致报错
望修复。

**Comment by wongsyrone** [comment]
Read release notes.
