### ISSUE TITLE
3.3版本出现延迟问题

### ISSUE THREAD

**Issue by D-Bood** [shadowsocks/shadowsocks-windows#710]
server：openSUSE Leap 42.1
ss-server：ver2.9
vps：ConoHa
服务端参数：
`ssserver -s :: -p 1755 -k pswd -t 300 -m aes-256-cfb --fast-open`
首先感谢作者的辛勤劳动
使用3.3版本能够明显感觉到延迟较为严重
更换成之前的版本之后情况极大地改善了
不知道是什么原因，还请各位指教

**Comment by Noisyfox** [comment]
你服务器地址填的是ip还是域名？

**Comment by D-Bood** [comment]
@Noisyfox ip地址

**Comment by Noisyfox** [comment]
是只有3.3才有这个延迟问题么？3.2正常？

**Comment by D-Bood** [comment]
@Noisyfox 嗯

**Comment by wongsyrone** [comment]
Please install latest libev server and test again.

**Comment by D-Bood** [comment]
@wongsyrone Thanks for your suggestion！
The problem seem to be solved and I used the python version before.
Please close the issue and I really appreciate your help！

**Comment by breakwa11** [comment]
我怀疑你把fast open关了就好了，你可以试试

**Comment by D-Bood** [comment]
这几天感觉还是有点延迟，用了libev也是有这种感觉，截图在这里
3.3
[http://i1.piimg.com/567571/a1a7b2f596f11e42.png](url)
3.2
[http://i1.piimg.com/567571/a1a7b2f596f11e42.png](url)
@breakwa11 关了，也不行

**Comment by breakwa11** [comment]
问题已确认，这是确实存在的，楼主可以reopen这个issue了
