### ISSUE TITLE
是否可以不显示任务栏图标上的两个小箭头？

### ISSUE THREAD

**Issue by nanxiaobei** [shadowsocks/shadowsocks-windows#711]
新版 shadowsocks 任务栏图标，在有数据时会显示上下两个小箭头，有没有办法可以不显示这两个小箭头，只显示个小飞机图标？

**Comment by wongsyrone** [comment]
No plan for this.

**Comment by MiffyLiye** [comment]
我有一份界面修改版，也去掉了小箭头，可以到 https://ci.appveyor.com/project/MiffyLiye/shadowsocks-csharp/build/artifacts 下载。

**Comment by nanxiaobei** [comment]
@MiffyLiye 好的，谢谢！

**Comment by RyanWestinLiu** [comment]
臣附议
