### ISSUE TITLE
建议添加自定义 server udp port 的功能

### ISSUE THREAD

**Issue by smounives** [shadowsocks/shadowsocks-windows#712]
为何会有这个需求:因为有些 docker 平台映射的 tcp 和 udp 端口是随机的并且不一致，且无法自定义，添加上这个功能会方便一点，虽然也可以用 libev 版的 ss-local 😂

**Comment by wongsyrone** [comment]
You can customize your docker image yourself.
No plan for this.

**Comment by smounives** [comment]
Of course I know how to expose port in docker image, but the plantform like [this](https://arukas.io/en/) doesn't support customize public port, the port is random

**Comment by smounives** [comment]
OK, I found ShadowsocksR-windows support customized udp port.
