### ISSUE TITLE
http代理

### ISSUE THREAD

**Issue by mucunmjin** [shadowsocks/shadowsocks-windows#714]
请问 同一端口能支持http代理吗，谢谢。

**Comment by breakwa11** [comment]
客户端能

**Comment by mucunmjin** [comment]
需要服务器什么版本支持吗？

**Comment by breakwa11** [comment]
这和服务没有关系，而且你也没有说清楚到底要客户端还是服务端的http

**Comment by wongsyrone** [comment]
The default port is providing SOCKS5 proxy, which will be converted into HTTP proxy via Privoxy.
In general, they are on different ports.

**Comment by luozekun** [comment]
上个月买了你家（大概？）的shadowsocks  
然后重装了系统，千方百计找不到那个ss的官网了  (╯‵□′)╯︵┻━┻ !!
麻烦能给个网址么..

**Comment by Noisyfox** [comment]
我们这个并不提供收费服务哦

**Comment by wongsyrone** [comment]
Paid service provided by shadowsocks.com has nothing to do with shadowsocks organization.
There is NO so-called official service provider.

**Comment by mucunmjin** [comment]
不好意思没说清楚，服务端用的python版本的 。

按照 wongsyrone 的说法就是客户端默认的端口只提供SOCKS5代理，不提供http代理。只能通过Privoxy 把SOCKS5转换成http代理是吧。
了解了。谢谢。

**Comment by Noisyfox** [comment]
客户端默认是在同一个端口同时提供的Socks5和http代理。

在 2016/9/13 15:36, mucunmjin 写道:
