### ISSUE TITLE
如何提交pac

### ISSUE THREAD

**Issue by nqzhang** [shadowsocks/shadowsocks-windows#715]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

从gfw更新的pac是在哪里
// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac

这个网址访问不了了

**Comment by chenshaoju** [comment]
目前Shadowsocks for Windows是基于GFWList的列表，请移步至：
https://github.com/gfwlist/gfwlist

**Comment by nqzhang** [comment]
好的 谢谢
