### ISSUE TITLE
3.3的状态灯 貌似没有3.2的看着美

### ISSUE THREAD

**Issue by iJayscn** [shadowsocks/shadowsocks-windows#720]
....

**Comment by breakwa11** [comment]
审美观的不同。还有很多人认为3.3的更好，我觉得你需要事先搞个投票
我考虑的，是直观，一左一右，你往往分不清哪个表示上传哪个表示下载，然而一上一下的话我不用说你都知道其意义了，对吧

**Comment by perqin** [comment]
也许可以搞成上下箭头各一个，在飞机右下角作角标。

**Comment by wongsyrone** [comment]
It makes no sense. It is just an indicator.

**Comment by celeron533** [comment]
其实当时第一版设计的候选方案里有这个想法，但是后来发现亮色系的箭头不显眼，所以用了色块，跟网卡接口类似。但是对于网络不熟悉的用户光看颜色也不一定能分辨出哪个是上行，哪个是下行。
不过这种东西很随意啦，箭头方案虽然没有以前的色块来的显眼，但是表达起来很直观。
![image](https://cloud.githubusercontent.com/assets/3608762/19021167/36fe35c2-88ee-11e6-9c06-d315dfc7fcec.png)
