### ISSUE TITLE
PAC模式Chrome中部分版权视频无法播放

### ISSUE THREAD

**Issue by mengskysama** [shadowsocks/shadowsocks-windows#722]
例如
https://www.youtube.com/watch?v=PT2_F-1esPk&list=PLvFYFNbi-IBFeP5ALr50hoOmKiYRMvzUq
请求https://www.youtube.com/watch?v=PT2_F-1esPk&list=PLvFYFNbi-IBFeP5ALr50hoOmKiYRMvzUq
可能会走QUIC（UDP）协议，此时规则PAC无效

解决方法：
1.禁用QUIC协议
2.SwitchOmega

**Comment by breakwa11** [comment]
chrome的QUIC（UDP）能正常通过s5代理发送么？

**Comment by Noisyfox** [comment]
我一直在用SwitchyOmega，开了代理的话会自动禁用QUIC的。

在 2016/9/15 20:58, 破娃酱 写道:

**Comment by breakwa11** [comment]
所以其实我也没听说过谁让chrome的QUIC能通过s5跑，这协议根本不管你的代理设置，所以更不管你的PAC了，当然PAC无效，但这应该是chrome的锅

**Comment by Noisyfox** [comment]
毕竟如果UDP还走了层代理。。那还不如直接用TCP连了23333而且也不是所有代理协议都支持UDP代理。

**Comment by mengskysama** [comment]
感觉没法整+1，还是用SwitchOmega吧

**Comment by breakwa11** [comment]
@Noisyfox 这里是你的锅 #710 ，快去修

**Comment by Noisyfox** [comment]
23333然而。。。并不知道是哪里出问题了啊！

在 2016/9/15 21:10, 破娃酱 写道:

**Comment by breakwa11** [comment]
@Noisyfox 那等我改吧，我知道是哪的问题

**Comment by Noisyfox** [comment]
麻烦你了

在 2016/9/15 21:19, 破娃酱 写道:

**Comment by celeron533** [comment]
switchyOmega那边已经开了QUIC的坑
https://github.com/FelisCatus/SwitchyOmega/issues/706

**Comment by Noisyfox** [comment]
@celeron533 那个是支持代理服务器用QUIC协议，然而现在问题是貌似只有个go的quic实现？反正几个常见的http服务器都还没有支持quic。嗨呀好气啊
