### ISSUE TITLE
A button duplicates a proxy configuration besides "Add".

### ISSUE THREAD

**Issue by Xorcerer** [shadowsocks/shadowsocks-windows#725]
### Motivation

Quicker adding proxies with similar configuration, e.g.
`sf.myproxy.com
password: 123
port: 234`
`sg.myproxy.com
password: 123
port: 234`

### Behaviour

Put a button texted "Duplicate" besides "Add".
When it is clicked, a new item would be added to the server list, with every single field exactly the same as the previously selected item.

### Who is going to do it?

I am, if you like it.
I posted an issue here before coding to make sure the idea (not implementation/coding style) would not be rejected.

**Comment by wongsyrone** [comment]
Why not just copy and paste entries in the json file?

**Comment by wongsyrone** [comment]
I don't think this feature really make sense.

**Comment by Xorcerer** [comment]
Yes, that is what I do for now.
But we don't edit the json for adding and deleting, right?
I do think the reason that we created the GUI, is that keeps users away from editing the json file.

**Comment by wongsyrone** [comment]
You can prepare a PR

**Comment by wongsyrone** [comment]
You can use `controller.GetCurrentServer()` and write a method very similar to `private void AddButton_Click(object sender, EventArgs e)`.

**Comment by Xorcerer** [comment]
Oh, I have just missed your last hint. Let me update it.

**Comment by Xorcerer** [comment]
Updated to use `controller.GetCurrentServer()`

**Comment by Xorcerer** [comment]
>            if (ServersListBox.SelectedIndex >= 0 && ServersListBox.SelectedIndex < _modifiedConfiguration.configs.Count)
>            {
>                Server selectedServer = _modifiedConfiguration.configs[ServersListBox.SelectedIndex];

I think this will do the job instead of `controller.GetCurrentServer()`, since *current server* does not get updated until the `OKButton` is clicked.

So I have reverted my last commit.
Sorry for committing without testing, my bad.
