### ISSUE TITLE
快捷键设置界面，在高分屏上显示很不理想

### ISSUE THREAD

**Issue by reaCodes** [shadowsocks/shadowsocks-windows#727]
Windows 10 系统 ，2560*1440分辨率，DPI缩放200%

![sshot-1](https://cloud.githubusercontent.com/assets/13817254/18606887/136c3178-7cef-11e6-8f7a-ac0f501eec9b.png)

**Comment by breakwa11** [comment]
这个很好解决，正式发布时就会弄好

**Comment by reaCodes** [comment]
正式版何时发布，有没有计划？

**Comment by wongsyrone** [comment]
功能正常吗，只是显示问题？

**Comment by reaCodes** [comment]
@wongsyrone 功能没问题，来回切换多次都很顺畅，就是没有对高分屏优化。（这是一个非常方便的功能，期待已久）

**Comment by wongsyrone** [comment]
因为我这里没有高分屏环境，所以需要有条件的帮助解决；功能我基本都测过了。

**Comment by breakwa11** [comment]
我来弄就好了

**Comment by reaCodes** [comment]
@wongsyrone @breakwa11 发现一个bug，重启shadowsocks，快捷键无法生效，必要打开“编辑快捷键”窗口，重新点击确定还可以使用。（Windows 10 14393）

**Comment by Noisyfox** [comment]
@reaCodes 新开一个issue

在 2016/9/17 21:30, reaCodes 写道:

**Comment by breakwa11** [comment]
@reaCodes 测测这个版本 https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.59

**Comment by reaCodes** [comment]
@breakwa11 解决了，不过“注销全部”没有居中对齐好别扭呀
![sshot-1](https://cloud.githubusercontent.com/assets/13817254/18608016/01d626c8-7d10-11e6-87e6-27604f65cef9.png)

**Comment by breakwa11** [comment]
@reaCodes 那么再试试这个版本 https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.60

**Comment by reaCodes** [comment]
@breakwa11 解决了什么问题？上个问题依旧。

**Comment by Noisyfox** [comment]
@breakwa11 那个按钮不够宽啦我觉得

**Comment by breakwa11** [comment]
@reaCodes 这个应该好了 https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.61
