### ISSUE TITLE
关于快捷键的一个bug

### ISSUE THREAD

**Issue by reaCodes** [shadowsocks/shadowsocks-windows#728]
版本：https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.58

环境：Windows 10 14393, .NET Framework 4.6.1

现象：重启shadowsocks，快捷键无法生效，必需打开“编辑快捷键...”窗口，重新点击确定才可以使用。

**Comment by wongsyrone** [comment]
Yes, this is expected. Please check https://github.com/shadowsocks/shadowsocks-windows/pull/708#issuecomment-247746140

> Also, a user should register all hotkeys explicitly when starting Shadowsocks, since environment may vary. If you want to open multiple instances of Shadowsocks, you have to change hotkeys for another instance. Otherwise, it will not work.

**Comment by wongsyrone** [comment]
That is why I choose NOT to register hotkeys when starting Shadowsocks automatically.
