### ISSUE TITLE
可否支持

### ISSUE THREAD

**Issue by Chadwick97** [shadowsocks/shadowsocks-windows#732]
目前的pac模式算是黑名单吧，在列表中的域名强制通过代理。能不能与此相反，在列表中的域名不走代理，其余全部通过代理。目前可行吗？因为我个人的特殊要求，用shadowsocks的时候需要全局模式，而只有一两个网站上我想直接访问的

**Comment by chenshaoju** [comment]
你好，SS本身是通过PAC文件控制的，你需要寻找相应功能的PAC文件即可。
比如这个第三方的服务：
https://github.com/breakwa11/gfw_whitelist

**Comment by wongsyrone** [comment]
You can write yourself rules.

**Comment by Noisyfox** [comment]
你可以用浏览器插件达到这个目的
