### ISSUE TITLE
支持.Net Framework2.0的SS版本

### ISSUE THREAD

**Issue by KingsFish** [shadowsocks/shadowsocks-windows#733]
你好，请问那个版本是支持.NetFramework2.0的呢？
我的电脑WindowsUpdate出了问题，无法更新.NetFramework4.0。
win7，想看一下哪个是能使用2.0的
谢谢

**Comment by breakwa11** [comment]
不支持，除非使用旧版本

**Comment by wongsyrone** [comment]
You can use standalone installer to get latest .NET Framework

**Comment by KingsFish** [comment]
你指的旧版本是哪些呢？

**Comment by breakwa11** [comment]
@KingsFish 3.0以前
