### ISSUE TITLE
gfwlist不知何种原因已经被清空，PAC已经跪了

### ISSUE THREAD

**Issue by doukai** [shadowsocks/shadowsocks-windows#734]
这是什么原因？有没有临时的解决的方法？

**Comment by reaCodes** [comment]
对的，突然pac就不能翻墙了

**Comment by Aura7988** [comment]
我右键更新本地PAC后碰到了这个问题，直到刚才才发现是这个原因。用之前的pac备份现在可以翻墙了。

**Comment by zhanghanyun** [comment]
谁共享个pac啊

**Comment by Noisyfox** [comment]
去gfwlist官方github然后看历史记录就行

在 2016/9/19 17:24, Pythonidea 写道:

**Comment by wongsyrone** [comment]
清空前的一次提交：https://raw.githubusercontent.com/gfwlist/gfwlist/dc8695c93d5f8dfd6180115c9a0a50eb5e0d72ab/gfwlist.txt

**Comment by reaCodes** [comment]
@wongsyrone gfwlist要怎么转成pac使用？

**Comment by colingpt** [comment]
同问。。。刚编辑了user-rule，然后发现pac更新下来的竟然是没有规则，可能是集成的那个pac源出现了问题吧。望修复

另外希望可以增加自定义更新pac地址的功能，以备不时之需

**Comment by doukai** [comment]
已经更新了，看来是误操作，虚惊一场！
