### ISSUE TITLE
window 10 Pac 代理不生效

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [shadowsocks/shadowsocks-windows#735]
刚刚更新到最新 3.3 版本的windows客户端，全局代理可以访问，选择pac 模式则无法访问google，已经从 GFWlist更新了本地 pac，请问有什么解决方法么？

**Comment by wongsyrone** [comment]
Try 3.3.1

**Comment by ZhengshuaiPENG** [comment]
经过测试，目前确定只有 Firefox 不兼容 PAC 模式：
Firefox 版本： 48.0.2， SS： 3.3.1， 全局模式正常，pac 模式不行
其余浏览器 pac 模式正常。

Firefox 升级到49版本正常

**Comment by chenshaoju** [comment]
这是Firefox的问题，详见： https://github.com/shadowsocks/shadowsocks-windows/issues/575
