### ISSUE TITLE
关于注册表项

### ISSUE THREAD

**Issue by Axtit** [shadowsocks/shadowsocks-windows#738]
如果想要在网吧使用，那么注册表是锁死的，所以有没有办法能够在网吧使用又能够解决注册表问题？

**Comment by wongsyrone** [comment]
Modify code in https://github.com/shadowsocks/shadowsocks-windows/tree/master/shadowsocks-csharp/Controller/System and compile it yourself.

**Comment by Axtit** [comment]
Thanks
