### ISSUE TITLE
放到坚果云同步目录下，保存user-rule.txt时抛异常

### ISSUE THREAD

**Issue by qinzhen353** [shadowsocks/shadowsocks-windows#741]
![qq 20160922110441](https://cloud.githubusercontent.com/assets/6756083/18735967/c55b2222-80b4-11e6-9ad9-24f182bdc342.png)

可能因为保存文件的时候坚果云就开始同步，导致ss客户端抛异常，是不是可以参照这个 http://www.cnblogs.com/qingcaoxiang/p/3272135.html 解决该问题呢？

**Comment by wongsyrone** [comment]
关闭自动同步或者手动复制到同步目录中。
