### ISSUE TITLE
gui-config.json文件手动修改后能否支持自动更新到主程序

### ISSUE THREAD

**Issue by easonjim** [shadowsocks/shadowsocks-windows#742]
请问gui-config.json文件手动修改后能否支持自动更新到主程序，我有个自定义程序会定时获取服务器账号密码然后进行更新，但是我发觉每次修改了gui-config.json文件后是无法立即生效的，重启后才能生效。

**Comment by wongsyrone** [comment]
新版本应该支持自动更新，不过还是建议首先备份；在程序内修改配置会触发ConfigChanged事件，之后会重新载入修改后的配置，自己在外部修改自然无法立即生效。

**Comment by easonjim** [comment]
我测试了最新版本，主程序设置了之后会自动更新到gui-config.json中，但是有一些场景是这样的，比如一些服务器账号密码是经常修改的，那么我想自定义一个采集程序定时获取最新的账号密码，然后修改gui-config.json中的服务器列表，所以能否支持如果外部手动修改了配置文件也能自动更新到主程序。

**Comment by wongsyrone** [comment]
那就类似于pac和user-rule的处理，加一个watcher，我看看吧。

**Comment by easonjim** [comment]
是啊，就是那样的，或者这样行不行，也像pac那样提供一个在线的地址列表，那么我就直接提供一个地址列表就行了，主程序自动检查我的在线服务器列表进行更新，如果这样就完美了。

**Comment by wongsyrone** [comment]
FileSystemWatcher虽然可以监视，但是无法区分是程序内部还是外部引起的文件修改，因为只要在程序内做修改，基本都会保存到文件，暂时不考虑实现，如果有兴趣的可以发PR。

**Comment by easonjim** [comment]
明白，我去研究一下pac的在线列表功能，看下能否加上一个-:)

**Comment by celeron533** [comment]
最暴力简单的方法是外部程序直接杀掉进程然后重启动。。。

**Comment by wongsyrone** [comment]
这样可能导致数据不完整

**Comment by easonjim** [comment]
@celeron533 我现在的做法就是这样
