### ISSUE TITLE
更新331 usb键盘鼠标卡死

### ISSUE THREAD

**Issue by 649775838** [shadowsocks/shadowsocks-windows#744]
鼠标键盘都是外置usb键盘
更新之后 客户端卡主 
重启 客户端启动之前 鼠标键盘正常
启动之后没有反应
删除了客户端之后 重启 鼠标键盘正常

**Comment by 649775838** [comment]
重启 指的是 重启电脑

**Comment by chenshaoju** [comment]
该问题无法在Windows 7和Windows 10上复现。
可能是你的鼠标或键盘驱动或控制程序在发现能翻墙后卡住了。

**Comment by 649775838** [comment]
win7下载了331 解压
打开 程序就会卡住
然后 重启电脑 鼠标正常 再打开程序
鼠标(罗技g402)usb提示音响一下 然后就没反应了 此时鼠标上的所有灯都亮
拔下鼠标 再插上 鼠标上dpi灯亮 罗技g灯不亮
任务管理器里关闭程序进程 等一会 拔插鼠标 就好了
在鼠标不能用的时候 有时候其他usb也没反应 但不是100%几率复现
包括外置键盘 外置声卡 xbox one 手柄
330的程序没有这个问题

**Comment by wongsyrone** [comment]
我也用罗技鼠标，更新你的罗技游戏软件和鼠标固件。

**Comment by 649775838** [comment]
鼠标驱动绝对最新 哎 330没这个问题的

**Comment by wongsyrone** [comment]
试试3.3.1的debug版本，看看日志有什么错误输出吗，如果没有能定位问题的，我也没办法下手。

https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.71/job/2o578dfqmkofnx1e/artifacts

**Comment by 649775838** [comment]
请问日志输出到哪里了?

**Comment by wongsyrone** [comment]
shadowsocks.log，便携模式在temp文件夹，否则在临时目录

**Comment by 649775838** [comment]
我先把shadowsocks.log文件删除了
然后运行1次331 
程序卡死 
生成了shadowsocks.log文件
但是里面是空的

**Comment by wongsyrone** [comment]
这个呢？
https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.52/job/tlfqohim99x5wkpe/artifacts

**Comment by 649775838** [comment]
不会卡死了
log 显示 [2016-09-24 13:47:14] Shadowsocks started

**Comment by wongsyrone** [comment]
问题出在快捷键初始化那部分，你看看有没有安全软件拦截什么的，应该是 https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Program.cs#L69 过不去。

**Comment by 649775838** [comment]
没有安全软件 也会卡主
我给鼠标侧键 在罗技驱动里 设置了按键 会是这个问题么

**Comment by wongsyrone** [comment]
应该不是，你可以取消试试。因为初始化那部分只是开了热键消息捕获，可能会误报。
