### ISSUE TITLE
自动更新PAC配置文件

### ISSUE THREAD

**Issue by Ghost-yc** [shadowsocks/shadowsocks-windows#746]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
v3.3.1

### Environment(Operating system, .NET Framework, etc)
windwos 10

### What did you expect to see?
是否能添加一个功能，能够自动更新PAC配置文件

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
You can update from GFWList and write user rules yourself.

**Comment by Loyalsoldier** [comment]
@Ghost-yc 可以使用白名单并且智能分流的翻墙软件，这样就不用管 PAC 了，例如 MEOW。

我写了一篇博文，你可以看看：http://t.cn/Rc3BOlO
