### ISSUE TITLE
Check for update direct to a differ subject

### ISSUE THREAD

**Issue by TacticalTwerking** [shadowsocks/shadowsocks-windows#749]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.7.4

### Environment(Operating system, .NET Framework, etc)
Windows 7 64

### Steps you have tried
Check for update

### What did you expect to see?
Correct version name (3.7.9) & download link (for **ShadowsocksR** not **Shadowsocks**)

### What did you see instead?
Incorrect version name and download link

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
Ask ShadowsocksR author.
