### ISSUE TITLE
快捷键无法自动注册

### ISSUE THREAD

**Issue by kop-still** [shadowsocks/shadowsocks-windows#752]
SS版本：3.3.1
操作系统：Windows 10 专业版 版本 1511 (OS 内部版本 10585.589)
现象：每次注销或者重启，快捷键失效，需要在编辑快捷键面板手动点击"注册全部热键"或"确定"才能重新生效

**Comment by wongsyrone** [comment]
It is expected. https://github.com/shadowsocks/shadowsocks-windows/issues/728

**Comment by itlangke** [comment]
现在的版本4.04依然存在这个问题，很需要这个功能，希望能解决。

**Comment by tmplinshi** [comment]
@itlangke 可以试试这个工具 https://github.com/tmplinshi/RegSsHotkey
