### ISSUE TITLE
can not work on windows 10 14936, the server is available on my phone

### ISSUE THREAD

**Issue by AutoRip** [shadowsocks/shadowsocks-windows#755]
### Version(release version or AppVeyor link)
3.3.1

### Environment(Operating system, .NET Framework, etc)
windows 10 14936

### Config and error log in detail (with all sensitive info masked)
`[2016-09-30 11:26:01] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)`

**Comment by wongsyrone** [comment]
try 3.3.1

**Comment by AutoRip** [comment]
@wongsyrone  thanks for ur quick response. Sorry for that I have report an wrong version in the issue, actually I'm using the latest client 3.3.1. The previous versions worked well, however, after the update, the 3.3.1 client does not work.

**Comment by wongsyrone** [comment]
> Received an unexpected EOF or 0 bytes from the transport stream

If this doesn't appear frequently, don't panic. You can also try latest master branch.

**Comment by AutoRip** [comment]
@wongsyrone  I don't know what does the error mean, and now the client can run and in the log it says that shadowsocks started, but actually it can not fuction as there's no data connections between my pc and the server. The target sever is ok and on my phone it can be connected and has data transferred, i'm sure I start the connection in the client.

**Comment by iiiplus** [comment]
Manually set the IE proxy with 127.0.0.1 and port 1080.

**Comment by iiiplus** [comment]
Manually set the IE proxy with 127.0.0.1 and port 1080.

**Comment by yzou** [comment]
I have the same problem. Shadowsocks can't set system proxy.
Build 14936.rs_prerelease.160923-1700

**Comment by Noisyfox** [comment]
Looks like it's a bug on the latest win 10 rs preview.

**Comment by yzou** [comment]
I debugged, it can set registry but soon the registry was cleared.

**Comment by AutoRip** [comment]
@yzou so, is there any solution for the issue?

**Comment by fzhw88** [comment]
Windows 10 14936 报告有同样的问题，shadowsocks无法修改IE的代理设置，意味着升级之前用的PAC模式，升级之后改全局无效，甚至关掉“启用代理服务器”选项也不能更改IE的代理设置，依然是代理状态，同样，如果手动取消了IE代理设置，则无论shadowsocks怎么更改设置都无效。

**Comment by wongsyrone** [comment]
Waiting for bug fixes from Microsoft or revert to stable version.

**Comment by yzou** [comment]
@AutoRip I didn't find a solution yet. I guess it may be the security issue. The new Settings center has a proxy config page. I didn't find a new way to set the proxy.

![image](https://cloud.githubusercontent.com/assets/1464693/19015008/199d63a6-882e-11e6-948e-59fdc74a6c34.png)

**Comment by Noisyfox** [comment]
Then just turn off the system proxy in SS and set the proxy setting manually.

**Comment by yzou** [comment]
I found two other proxy config in registry if I set manually:
Windows Registry Editor Version 5.00

```
[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\iphlpsvc\Parameters\ProxyMgr\{4E6015C0-9493-4FD0-A0AD-1BD12EE5D025}]
"AutoConfigUrl"="http://127.0.0.1:1080/pac"
"LastUseTime"=hex(b):9d,eb,14,d4,1e,1b,d2,01

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\iphlpsvc\Parameters\ProxyMgr\{4E6015C0-9493-4FD0-A0AD-1BD12EE5D025}]
"AutoConfigUrl"="http://127.0.0.1:1080/pac"
"LastUseTime"=hex(b):9d,eb,14,d4,1e,1b,d2,01

```

**Comment by philogicrock** [comment]
I also met the same problem, any agent software can't use in Windows 14936 quick update version of the PAC proxy mode of the system

**Comment by wongsyrone** [comment]
Can someone export `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Connections` via regedit after checked and unchecked "Automatically detect Proxy" for me?

**Comment by wongsyrone** [comment]
Please try this version https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.123 and post log or screenshots.

**Comment by wongsyrone** [comment]
Another one to solve this, convert to WinINET API and get rid of tricky registry bin value handling.
https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.124/job/1t613pmc8xkcekcl/artifacts

**Comment by AutoRip** [comment]
@wongsyrone I have checked the regedit for the keys and values, but it seems no changes there. The client u provided doesn't work either, and still the log reports nothing but "shadowsocks started".

**Comment by AutoRip** [comment]
@wongsyrone I have checked the regedit for the keys and values, but it seems no changes there. The client u provided doesn't work either, and still the log reports nothing but "shadowsocks started".

**Comment by fzhw88** [comment]
回楼上，今天升级到了14942预览版，依然无效，Shadowsocks不能接管系统的代理设置，试了下蓝灯也不行，看来是系统的问题，只是不知道怎么解决。
按照你的办法测试了一下，用的管理员模式，3.3.2版本，依然无效，删除了注册表的Connections下的键值，重启IE，恢复的数据如下：
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections]
"SavedLegacySettings"=hex:46,00,00,00,18,00,00,00,01,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00
"DefaultConnectionSettings"=hex:46,00,00,00,0a,00,00,00,01,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00

**Comment by wongsyrone** [comment]
It seems that the data format did not change on the insider preview. If other software cannot modify it, report it to Microsoft.

**Comment by wongsyrone** [comment]
I have no idea on this, you may want to try [this](http://answers.microsoft.com/en-us/ie/forum/ie10-windows_7/unable-to-change-iewindows-proxy-settings/c7c5c57e-21ff-4dec-aba4-0e44df653be6) and the latest AppVeyor release build.

**Comment by fzhw88** [comment]
感谢楼上，已经向微软反馈～

**Comment by wongsyrone** [comment]
I can confirm 14393.206.amd64fre.rs1_release.160915-0644 works well, before and after 70bff7d7cc97e87fc06aae3ae685a54c8f01e7a0. If someone has issue above on this Windows build, please reopen.

**Comment by wongsyrone** [comment]
> RS2开始的几个preview版本因windows安全策略调整，代理只能手动设置

如果有能力研究组策略或者其他设置，可以试试。

**Comment by wongsyrone** [comment]
Another one again, changed flag used in API and log errors if operation failed.
https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.148/job/26bvfvs10iqhmtu4/artifacts
