### ISSUE TITLE
 3.3.1版本在翻墙服务器解析失败后，被代理程序为何会出现疑似内存泄漏的情况？

### ISSUE THREAD

**Issue by mydansun** [shadowsocks/shadowsocks-windows#757]
### Version(release version or AppVeyor link)
3.3.1 问题持续了一段时间，这段时间内我至少升级了2个版本 

### Environment(Operating system, .NET Framework, etc)

Win 10 10586

### Steps you have tried
首先，远端服务器的DNS解析失败
![qq 20161001212128](https://cloud.githubusercontent.com/assets/8871143/19014326/1f8b10a8-881d-11e6-96a4-2b43fec26518.jpg)

然后，chrome，dropbox和微软的MSE进程都出现了资源占用异常的情况

![qq 20161001212151](https://cloud.githubusercontent.com/assets/8871143/19014334/4d1666da-881d-11e6-94c5-4c9d5c509532.jpg)

这个情况发生已经有一段时间，现在电脑无法持续开机超过半天

在之前曾经以为是chrome的V8独立代理进程出现泄漏，然后在设置里关闭了这个选项，现在想起来，那个进程的资源占用异常应该跟上面dropbox的原因是一样的

不过这个问题不知道是ss的问题还是被代理程序的问题，我怀疑是**后者**，但是后者在之前至少相当一段时间内也没有出过问题

有没有出现相同问题的同学，希望一起讨论

**Comment by breakwa11** [comment]
这肯定不是SS的锅，你有没有安装了任何LSP劫持程序？或杀软，防火墙，迅雷

**Comment by mydansun** [comment]
@breakwa11 我也这么认为不是SS的问题，我机器上是有装TGP和Proxifier，不过在上述日志期间两个软件并没有工作。但是我也并没有想到靠谱的解决方法

**Comment by mydansun** [comment]
@breakwa11 杀软就是win10自带的没有装别的防火墙和迅雷什么的

**Comment by wongsyrone** [comment]
Try latest version and report bugs to them.

**Comment by mydansun** [comment]
@wongsyrone 我已经升级到了最新版本，请问在哪里report bugs?

**Comment by wongsyrone** [comment]
check http://www.proxifier.com/support.htm

**Comment by mydansun** [comment]
@wongsyrone 在运行出问题的时候这些软件都没有运行啊，也会有影响？

**Comment by eastmalon** [comment]
TGP会进行LSP劫持
