### ISSUE TITLE
最新版本的3.3.1经常chrome无法连接

### ISSUE THREAD

**Issue by VampireSH** [shadowsocks/shadowsocks-windows#758]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.1

### Environment(Operating system, .NET Framework, etc)

windows 10 
### Steps you have tried
重启ss

### Config and error log in detail (with all sensitive info masked)

更新到3.3.1后chrome经常断线无法链接到服务器，日记里面并没有错误信息但是有一次不停显示time out

**Comment by wongsyrone** [comment]
Please test https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.87/job/pix3cyax95du0ivr/artifacts
