### ISSUE TITLE
Firefox failed to load the PAC file

### ISSUE THREAD

**Issue by slurin** [shadowsocks/shadowsocks-windows#760]
### Version:

Shadowsocks windows 3.3.1

### Environment

![Microsoft Windows 10.0.14393 x86 CLR 4.0](http://art25.photozou.jp/pub/296/3174296/photo/241564870_org.v1475411142.png)

![Firefox Version 45.4.0esr](http://art25.photozou.jp/pub/296/3174296/photo/241564340_624.v1475410739.png)

### Error log in detail

![Firefox Console](http://art25.photozou.jp/pub/296/3174296/photo/241563006_624.v1475409622.png)

I've tried delete "pac.txt" and then "Update Local PAC from GFWList" but not works.

"User rule for GFWList" is not used.

**Comment by wongsyrone** [comment]
Upgrade Firefox to 49.
