### ISSUE TITLE
可否像SSR那样添加一个绕过大陆IP模式？

### ISSUE THREAD

**Issue by Turing-Wu** [shadowsocks/shadowsocks-windows#762]
如题

**Comment by eastmalon** [comment]
使用自定义白名单pac。例如：
https://raw.githubusercontent.com/eastmalon/gfw_domain_whitelist/master/whitelist.pac

**Comment by Monsieurs** [comment]
@eastmalon 直接把这个链接添加到在线PAC吗？

**Comment by eastmalon** [comment]
@Monsieurs 下载该文件并重命名，替换shadowsocks.exe目录下的pac.txt。

**Comment by Monsieurs** [comment]
@eastmalon 谢谢
