### ISSUE TITLE
Is this a completely SOCKS5 client?

### ISSUE THREAD

**Issue by dinfer** [shadowsocks/shadowsocks-windows#765]
最近在写自己用的工具，用到了SOCKS5协议，于是用这个客户端测试协议。但是我发现协商SOCKS5链接的第一个数据包中，VER字段并不是和RFC1928描述的那一样，必须为X'05'。我多次视图重启shadow-socks，以获取第一个报文，但是问题依然存在。

**Comment by Noisyfox** [comment]
？？你是用前置代理的socks5模式连你的服务端的么？

**Comment by dinfer** [comment]
是的

**Comment by Noisyfox** [comment]
不会啊。。一定是0x5啊第一个字节

**Comment by breakwa11** [comment]
我看代码并没有什么问题，你把你在握手过程中所以收到的和发出的包发来看看，或使用抓包工具列出

**Comment by wongsyrone** [comment]
Close due to inactive.

**Comment by dinfer** [comment]
打开客户端，取消“启用系统代理”，退出，然后再次运行。此时客户端没有启动，收到的第一个数据包。

```bash
server/tcp listening on port 14000
bin/main create goroutine 3
bin/main create goroutine 1
bin/main create goroutine 0
bin/main create goroutine 2
server/tcp accept {conn:{fd:0xc042096000}}
bin/main receive in channel, about to handle {conn:{fd:0xc042096000}}
framework/application handlers [0x401040 <nil> <nil> <nil> <nil>]
bin/main frame handler [0xc042026040 0x478920]
bin/main buffer Buffer <F3 40 9E 46 C9 00 EE 52 8B 74 4A A8 32 A8 E7 AB
4D 3B 5F C8 31 83 C8 DD 57 40 3B 7B 14 D8 3F 79
7F EE DD 75 04 32 83 87 94 B2 6B 5D 66 3E 56 F3
A9 7E 6F 6A 3D D7 47 46 CB B3 61 D1 62 02 36 8F
30 B2 42 FB 77 2B 31 CD 1D 48 F6 5C 64 75 68 D4
8E 65 C5 0C CF EF 68 8C 79 21 A0 31 72 B3 52 11
58 0F 8E B7 06 91 96 FD EB 57 63 F9 2E B2 A5 09
C1 8B 24 7B B4 76 73 15 D6 A9 C8 4F 78 4C 2A 15
6D 1C 1E A6 2B 15 B7 20 8E 14 18 65 82 6B 52 6E
52 8E 36 4F 0B A6 30 65 4A BF 3B A9 8C D6 FA 83
11 16 95 43 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

![image](https://cloud.githubusercontent.com/assets/11496403/19221526/a9d0eaf2-8e77-11e6-9616-47807cd9e5e9.png)

**Comment by GangZhuo** [comment]
客户端发出的是从 ATYP 开始的数据包，前边的数据被去掉了。

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/TCPRelay.cs#L284

**Comment by wongsyrone** [comment]
感谢澄清。

**Comment by dinfer** [comment]
@GangZhuo 谢谢，这几天我再看看客户端的源代码。
@wongsyrone 空余时间不多，才发过来，也挺抱歉的

另外请教个问题。如果加密主要是为了混淆，那么，不必拘束于SOCKS5协议，也可以实现同样的功能吧。

**Comment by wongsyrone** [comment]
可能是为了远端dns解析的优势？我也不太清楚设计初衷。

**Comment by Noisyfox** [comment]
> 不必拘束于SOCKS5协议，也可以实现同样的功能吧
因为socks5是目前最简单最广泛使用的一个同时支持UDP/TCP代理以及支持远程dns解析和IPv4/v6的协议，而且整个协议异常简单，易于实现。

> 客户端发出的是从 ATYP 开始的数据包，前边的数据被去掉了。
那你这个不是正向代理的数据包啊，这只是SS自己的数据包解密后的结果啊。
如果启用了Socks5的正向代理的话，第一个数据包肯定是0x5开头的。
