### ISSUE TITLE
非预期性错误，Shadowsocks将退出。请提交此错误到

### ISSUE THREAD

**Issue by Ansonyi** [shadowsocks/shadowsocks-windows#766]
![](http://ww2.sinaimg.cn/large/62004c6agw1f8j1llkbvlj20dg08974o.jpg)
出现了这个错误，
于是就提交一下，
完全不懂。

**Comment by wongsyrone** [comment]
Check your server address, especially IPv6.

**Comment by eastmalon** [comment]
尝试重置winsoc
