### ISSUE TITLE
SS无法访问Google YT FB等网站，但Twitter可以

### ISSUE THREAD

**Issue by Stormeh** [shadowsocks/shadowsocks-windows#767]
### Version(release version or AppVeyor link)
- 3.3.2

### Environment(Operating system, .NET Framework, etc)
- Windows 10, .Net 4.6

### Steps you have tried
- 重新安装服务器+ssserver
- 清理客户端缓存
- netsh interface ipv4 reset
- netsh interface ipv6 reset
- netsh winsock reset
- 重新下载SS客户端，使用新的配置文件
- 重启电脑

### What did you expect to see?
- 前几天开始就没法打开某些网站，基本上就是Google Youtube Facebook

### What did you see instead?
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:
Could not load template file no-server-data or one of its included components.
Please contact your proxy administrator.
If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

### Config and error log in detail (with all sensitive info masked)
{
    "server":"",
    "server_port":15216,
    "local_port":1102,
    "password":"",
    "timeout":600,
    "method":"rc4-md5"
}

[2016-10-08 00:16:17] Shadowsocks started
[2016-10-08 00:16:38] 103.229.124.238:15216 timed out
[2016-10-08 00:16:57] 103.229.124.238:15216 timed out
[2016-10-08 00:17:59] 103.229.124.238:15216 timed out
[2016-10-08 00:52:21] Shadowsocks started
[2016-10-08 00:52:33] 103.229.124.238:15216 timed out
[2016-10-08 00:52:38] 103.229.124.238:15216 timed out

基本上第一次打开大部分网站一定会出现500错误，但是刷新后就没问题。我也测试过其他被屏蔽网站，如Twitter是没问题可以通过SS访问，但是Google YouTube Facebook等死活无法连上。

**Comment by wongsyrone** [comment]
Try https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/job/e5fkmkj78bqqqexf/artifacts and test different server timeout.

**Comment by Stormeh** [comment]
I'm afraid problem has not been closed using that build and still persists.
