### ISSUE TITLE
有个建议 测试所有节点的延迟

### ISSUE THREAD

**Issue by txmdiv** [shadowsocks/shadowsocks-windows#768]
平时有多个节点，然后节点之间速度和质量不一样，
希望添加一个功能，一次性测出所有节点的延迟。

参考 shadowsock-QT 的 测试所有节点的延迟。

感觉这个功能还是很有必要的。

**Comment by breakwa11** [comment]
如果只是延迟，那你用高可用模式就差不多了

**Comment by chenshaoju** [comment]
这儿有一个第三方的工具，叫PingInfoView，可以批量Ping然后显示结果：
http://www.nirsoft.net/utils/multiple_ping_tool.html

仅供参考。

**Comment by Justsoos** [comment]
虽然是关闭的issue，不过也留个言吧，希望ss开发者能看到也是个建议。虽然现在破娃 @breakwa11 也退隐了，但酸酸乳的windows客户端上 “服务器连接统计” 这个东西真是太有用了。

比如，我在这里提出的这个用法，用来测试账号和查看使用状态：
https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/33#issuecomment-355440457

**目前用ss的服务账号，在ssr上基本不通用了，希望 ss 的作者能引入这个功能到ss 客户端上来**，让使用者一目了然看到自己那些服务账号可用，丢包，延迟，…… 等等一系列有效信息。

更进一步，如果能做出来一键测试，那就更好了。在我用ssr过程里，这个功能太重要了。一目了然，而现在ss客户端，完全眼前一团黑，什么数据都未知。

发一个图片，你感觉一下，拥有上百ssr账号，如何挑选出一个好用的也是个难题（绝非臭显） …… 并且随时能查看自己科学上网的科学数据，这些账号可能几个小时前还可用，但突然就连接错误（被GFW了）或者空连（端口可能掉了）…… 总之，这些数据在 shadowsocks 里用户一无所知。顺便说，延迟84的和330的，使用体验天差地别：

![0099snap](https://user-images.githubusercontent.com/3480043/35470701-1fdf65ca-0389-11e8-9aa6-50e636597723.png)

**Comment by Justsoos** [comment]
ssr 和 ss 里的负载均衡，用机器自动来挑选好用服务器，实际上这功能一点都不好用。。。来回乱跳 IP，还会引发，比如 google 会经常跳人机检测，非常恶心人。还是希望有人工挑选 -- 而这就需要测试数据啊。大哥大姐们。

> @breakwa11 如果只是延迟，那你用高可用模式就差不多了

**Comment by liushilive** [comment]
>虽然是关闭的issue，不过也留个言吧，希望ss开发者能看到也是个建议。

这个功能确实需要，如果怕`污染`本体，为何不考虑以插件的形式加入？让用户选择是否启用？

这个功能可以拆分为两个个需求：

1. `ping` 延迟
1. 测速：用户自定义一个网址，针对该网址进行访问测速，这总不会产生`特征`了吧！
