### ISSUE TITLE
HTTP代理中似乎存在问题。

### ISSUE THREAD

**Issue by ffii4455** [shadowsocks/shadowsocks-windows#769]
3.3.2版本  Windows 7 32bit 专业版。

我所处的网络需要在IE中设置HTTP代理才可以上网。3.3.2版本新增HTTP代理后我第一时间尝试。
全局模式没有问题。但是PAC模式下只有在GFWLIST中的地址会通过SS转发并走HTTP代理，不在GFWLIST中的地址会直连而不走HTTP代理，导致无法上网。

请问，本来就是这样设计的还是存在问题？

**Comment by Noisyfox** [comment]
pac的作用就是仅让特定的流量走某一代理，而其余流量是直接出去的，完全不会从ss走。
你可以使用自定义的pac来让剩余流量走你特定的代理服务器

**Comment by Yekaho** [comment]
Use proxifier

**Comment by wongsyrone** [comment]
Proxifier is recommended.
