### ISSUE TITLE
Feature Suggestion: easy and fast way to add new entry to PAC txt

### ISSUE THREAD

**Issue by faeriebug** [shadowsocks/shadowsocks-windows#770]
For now, it is very inconvenient to add a new entry to PAC because you need to find the PAC file from the context menu and edit using native editor. Too many steps!

So I hope we can simplify the procedure like this: use some shortcut key to trigger a new dialog window and copy & paste the new entry to finish PAC addition. easy and fast.

Will someone consider contributing such kind of feature to the master branch?

**Comment by wongsyrone** [comment]
No plan.
