### ISSUE TITLE
非预期错误，Shadowsocks将退出

### ISSUE THREAD

**Issue by whchengcai** [shadowsocks/shadowsocks-windows#772]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### What did you see instead?
![default](https://cloud.githubusercontent.com/assets/10474300/19228956/7c02d3a8-8efc-11e6-936b-d092f925aaab.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
检查服务端地址。

**Comment by whchengcai** [comment]
小白一枚，现在用着之前的版本就正常，如何查看服务端地址？服务端地址正确的应该是怎样呢？

**Comment by whchengcai** [comment]
ss账号是买来的，就提供了服务器的网址，端口号，加密方式，密码，其他没了。这个问题怎么之前的老版本没有，新版本却一直有这个问题。

**Comment by wongsyrone** [comment]
如果不知道就扫二维码。

**Comment by whchengcai** [comment]
谢谢赐教，受到启发，尝试将原来放置旧版本shadowsocks的整个文件夹全删除，然后重新打开新版本的shadowsocks，重新重复原来配置，问题解决。以前都是在这个原有的文件夹中直接将旧版替换成新版。
