### ISSUE TITLE
可不可以提供关闭选项来关闭shadowsocks图标上的流量指示箭头

### ISSUE THREAD

**Issue by 1558204459** [shadowsocks/shadowsocks-windows#773]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
关闭它有什么好处吗？

**Comment by x1596357** [comment]
没有那么让人分散注意力. 自己把shadowsocks-csharp/View/MenuViewController.cs中controller_TrafficChanged()函数内容注释掉就行啦, 自己编译个版本用.

**Comment by wongsyrone** [comment]
你可以折叠进任务栏里面，这个理由不成立

**Comment by wongsyrone** [comment]
当然可以维护自己修改的版本，这也是开源的好处。
