### ISSUE TITLE
youtube上传用户已禁止在您的国家/地区播放此视频

### ISSUE THREAD

**Issue by liaoran** [shadowsocks/shadowsocks-windows#774]
我在google上查了，很多都是以前GoAgent，以及现在XX-Net的解决方法，就是没有ss的解决方法，我安装了一个youtube的浏览器插件，也不太有用。
        哪位大神在使用ss的过程中解决了次问题，请说明下，我看google论坛上很多问的。

**Comment by eastmalon** [comment]
换节点位置。另外这种问题就不要到这里来提了，去论坛发帖就好了。

**Comment by liaoran** [comment]
ok,I know,嘿嘿

**Comment by applewithtea** [comment]
怎么解决的这个问题？
