### ISSUE TITLE
Proxy settings cannot be applied correctly on Windows 10 build 14942

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [shadowsocks/shadowsocks-windows#776]
It seems that windows changed its proxy setting interface, now it looks like this:
![image](https://cloud.githubusercontent.com/assets/12868093/19255033/76dc2862-8f8c-11e6-823d-c07feaa4d49c.png)
When I apply the proxy setting in shadowsocks, it fails to make change in system proxy settings, no idea why.

**Comment by wongsyrone** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/755

**Comment by MichaelSuen-thePointer** [comment]
@wongsyrone
But it's not the same issue.

**Comment by MichaelSuen-thePointer** [comment]
Ah forget it, I will debug it myself.
