### ISSUE TITLE
3.3.3 非预期错误

### ISSUE THREAD

**Issue by s5s5** [shadowsocks/shadowsocks-windows#777]
![qq 20161011145058](https://cloud.githubusercontent.com/assets/473706/19261443/d333a072-8fc3-11e6-8125-6db38c881d7e.png)
下载最新 Shadowsocks
解压到原来 Shadowsocks 3.3.2目录，覆盖
双击 Shadowsocks.exe 出现这个，关闭后无法工作

### Version(release version or AppVeyor link)
3.3.3

### Environment(Operating system, .NET Framework, etc)
Microsoft Windows 7 专业版 64位（ 6.1.7601 Service Pack 1 Build 7601）
.NET Framework: v4.0.30319

### Steps you have tried
下载最新 Shadowsocks
解压到原来 Shadowsocks 3.3.2目录，覆盖
双击 Shadowsocks.exe 出现这个，关闭后无法工作

**Comment by wongsyrone** [comment]
It is caused by your .NET Framework, reinstall or upgrade to 4.6.2

**Comment by s5s5** [comment]
谢谢，解决了
