### ISSUE TITLE
shadowsocks3.3.3   win7 启动异常

### ISSUE THREAD

**Issue by fi5** [shadowsocks/shadowsocks-windows#781]
软件版本 3.3.3.0

windows7 旗舰版  .net 4.5，4.0 ， 3.5 ，2.0 SP2 , 1.0 SP3 , 1.1  

双击软件启动时弹出异常窗口

![image](https://cloud.githubusercontent.com/assets/8827201/19273732/3162fc6a-9000-11e6-8fc3-ff462db8fad1.png)

有谁遇到过这个问题吗？

**Comment by wongsyrone** [comment]
更新到.net 4.6.2

**Comment by wongsyrone** [comment]
This will use https://msdn.microsoft.com/en-us/library/dn261468(v=vs.110).aspx.

> [Supported in the .NET Framework 4.5.1 and later versions]

**Comment by fi5** [comment]
升级到4.5.1搞定，多谢！！
