### ISSUE TITLE
An Exception at first time running Shadowsocks.exe without gui-config.json file

### ISSUE THREAD

**Issue by ianmay139** [shadowsocks/shadowsocks-windows#782]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.3 or Earlier

### Environment(Operating system, .NET Framework, etc)
windows 10, .net framework 4.6.2

### Steps you have tried
1. run Shadowsocks.exe;
2. right click tray icon, click "显示日志...";
3. execption thrown out;

### What did you expect to see?
The log viewer comes out

### What did you see instead?
An exception, this problem is due to null server list called by strategy modes;
[exception.png](https://raw.githubusercontent.com/ianmay139/Miscellaneous/master/exception.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
You should configure at least one server when running the first time, this will save gui-config.json file for you.
