### ISSUE TITLE
Win7系统，3.3.3版本启动报异常

### ISSUE THREAD

**Issue by RadixIsatidis** [shadowsocks/shadowsocks-windows#783]
win7 系统，.NET Framework 4.5，启动程序报错。见附件图片。
![qq 20161012094238](https://cloud.githubusercontent.com/assets/3702144/19294539/42baf23c-9060-11e6-8595-1d91c033c21b.png)

**Comment by wongsyrone** [comment]
#777 #781
Search closed issues before opening new one.
