### ISSUE TITLE
shadowsocks-windows 3.3.3 用不了了

### ISSUE THREAD

**Issue by gouqingping** [shadowsocks/shadowsocks-windows#785]
shadowsocks-windows 3.3.3 在win8.1 上面显示
无法访问此网站

www.google.com 的响应时间过长。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT

求解啊

**Comment by gouqingping** [comment]
配置全好，除非3.3.3需要从新配置其他的东西。

**Comment by ikkyusan123** [comment]
Do you work out this problem?
