### ISSUE TITLE
Win10 LTSB 2016  14393.321 版编辑服务器对话框弹不出.

### ISSUE THREAD

**Issue by Rememberli** [shadowsocks/shadowsocks-windows#789]
请看一下什么问题，谢谢。

Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.3

### Environment(Operating system, .NET Framework, etc)
Win10 LTSB 2016  14393.321

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
You didn't provide any useful info.

**Comment by Rememberli** [comment]
不是写清楚了吗？
Win10 LTSB 2016 14393.321 下，3.3.3 版本无法弹出编辑服务器对话框。
你要是同样环境下无法复现就指出来我好查找是否有其他原因。

**Comment by wongsyrone** [comment]
I cannot reproduce on Win10 pro 14393.321

**Comment by Rememberli** [comment]
我删除了temp文件夹，shadowsocks_portable_mode.txt ， 以及statistics-config.json 后关闭重新打开后OK了，谢谢！
