### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Gitiy** [shadowsocks/shadowsocks-windows#792]
---------------------------
Shadowsocks Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.FormatException: Invalid Server Address.

   在 Shadowsocks.Model.Server.FriendlyName()

   在 Shadowsocks.View.MenuViewController.UpdateTrayIcon()

   在 Shadowsocks.View.MenuViewController..ctor(ShadowsocksController controller)

   在 Shadowsocks.Program.Main()
---------------------------
确定   
---------------------------

**Comment by wongsyrone** [comment]
> Invalid Server Address.
