### ISSUE TITLE
反馈一个 3.3.3 版本的问题（3.3.2 没有这个问题）

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-windows#795]
3.3.3 启动代理不会将 “拨号和虚拟专用网络设置”里的连接设置代理
![sp20161015_000521](https://cloud.githubusercontent.com/assets/9424775/19394378/84d7ee2e-926b-11e6-8754-e3ca6ed53fae.png)

**Comment by wongsyrone** [comment]
Fixed in https://github.com/shadowsocks/shadowsocks-windows/commit/1c1cc622356fa598251d2726f27a90c3a1ebc38b, please note that if your connection name isn't in English, it will not work.
