### ISSUE TITLE
反馈3.3.3/2 版本的快捷键功能的问题

### ISSUE THREAD

**Issue by cbdzz** [shadowsocks/shadowsocks-windows#796]

**Comment by xqin** [comment]
另外 在注册热键的时候, 不支持Windows键.

**Comment by 123npszjhl** [comment]
另外我遇到了软件重启后热键失效的情况。（设置已经正常保存，但重启后没有激活）

补充一点：建议将条目【切换到PAC模式】、【切换到全局模式】合并为【系统代理模式切换】一键实现状态相互切换。

功能建议：“在编辑服务器”窗口增加“ping”按钮测试服务器延迟。

**Comment by wongsyrone** [comment]
This is by design.

**Comment by wongsyrone** [comment]
If you want to find reasons, check issues already closed and README file.
