### ISSUE TITLE
Win10 预览版无法使用客户端

### ISSUE THREAD

**Issue by MoeGakuen** [shadowsocks/shadowsocks-windows#797]
客户端版本：`3.3.3`
操作系统：`Windows10 Pro Insider Preview 14942`

自从升到`14942`还是再上一个版本，SS客户端就无法使用。

手动设置IE代理地址为`http://127.0.0.1:1080/pac`基本可以使用，但是全局模式已废。且无法自动设置代理。

**Comment by crzidea** [comment]
物业发现了，系统代理的API好像变了。

**Comment by wongsyrone** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/755

**Comment by wongsyrone** [comment]
> RS2开始的几个preview版本因windows安全策略调整，代理只能手动设置

**Comment by wongsyrone** [comment]
You can try https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.102/job/g7l1q11ie7q5xf6y/artifacts

**Comment by MoeGakuen** [comment]
所有版本都不行，只能自己手动设置IE代理了。全局模式是不行了

**Comment by wongsyrone** [comment]
Report to Microsoft.

**Comment by SmallFork** [comment]
PAC模式：
1、启动系统代理，选择PAC模式
2、打开IE>Internet选项>连接>局域网设置
3、使用自动配置脚本：填写 http://127.0.0.1:1080/pac
全局模式：
1、启动系统代理，选择全局模式
2、打开IE>Internet选项>连接>局域网设置
3、使用自动配置脚本前面对号去掉
4、代理服务器里面：地址填写127.0.0.1   端口填写 1080

**Comment by wongsyrone** [comment]
> http://127.0.0.1:1080/pac

This link will persist browser cache and might cause issues when PAC file changes. You can add a param like `?t=<timestamp-here>` to force reading. In general, it is just a workaround, not a solution. 

You should blame Microsoft for API breakage or lack of API change announcement.

**Comment by xflcx1991** [comment]
「反馈」@wongsyrone 提供的新链接里的exe在win10下可用。

**Comment by wongsyrone** [comment]
@xflcx1991 Do you mean **Insider Preview**?

**Comment by OldBai** [comment]
试了下win10 14942以前的版本，发现能用。设置shadowsocks代理设置时发现PAC和全局不能自动切换了

**Comment by MoeGakuen** [comment]
@xflcx1991 你确定你是**预览版**？我测试无效，只能手动设置代理

**Comment by yeszhangyi** [comment]
Windows 10 Version 1607 不能用

**Comment by wongsyrone** [comment]
@yeszhangyi Don't post irrelevant issue in this one. BTW, the info you provided is too vague; nobody can find a clue.

**Comment by fzhw88** [comment]
经网友提示，使用ShadowsocksR（别鄙视我啊）客户端可以自动更改代理设置了，测试环境是14951 x64版本，猜测是不是微软修改了相关的api？

**Comment by wongsyrone** [comment]
I'm sticking to Win32 API without poking registry binary values

**Comment by wongsyrone** [comment]
According to https://github.com/shadowsocks/shadowsocks-windows/issues/814#issuecomment-255987341, it has been fixed in new insider preview build.

**Comment by Noisyfox** [comment]
Try the latest pre-release version.
