### ISSUE TITLE
3.3.3 isn't available in windows 7

### ISSUE THREAD

**Issue by ikkyusan123** [shadowsocks/shadowsocks-windows#798]
### Version(release version or AppVeyor link)
3.3.3

### Environment(Operating system, .NET Framework, etc)
Windows 7 ultimate, .NET Framework 4.6.1

### Steps you have tried
I have tried potable model and run shadowsocks.exe with administrator, it doesn't work。Whether it is with system proxy model or switchyomega extension, there is no internet access to google in chrome.

### What did you see instead?
There are a lot of timed out in log of shadowsocks,

### Config and error log in detail (with all sensitive info masked
![default](https://cloud.githubusercontent.com/assets/18085459/19415780/c2657926-93ad-11e6-94d8-2088d61cc9dc.jpg)
)

**Comment by rebiu** [comment]
#781

**Comment by wongsyrone** [comment]
Check your server.

**Comment by ikkyusan123** [comment]
I have tried four different ss account, and updated to .net 4.6.2, but there is always a lot of timed out, so I think it's problem of client. I also tried it in other computers.
![1](https://cloud.githubusercontent.com/assets/18085459/19416550/0d420776-93c6-11e6-94f3-d66f0424120f.jpg)

**Comment by chenshaoju** [comment]
I pinged your server IP,and time is 300ms+,And packet lost,This is too lag.
Please try faster server.
![default](https://cloud.githubusercontent.com/assets/515763/19417542/24b414aa-93e2-11e6-817d-34e3d6aff2d6.png)

**Comment by ikkyusan123** [comment]
However，it's normal to ping in my computer, there is no packet loss.
![2](https://cloud.githubusercontent.com/assets/18085459/19417655/dd2e0124-93e4-11e6-8fe0-8c424ae4126d.png)

**Comment by chenshaoju** [comment]
odd

**Comment by breakwa11** [comment]
You should use tcping instead of ping

**Comment by ikkyusan123** [comment]
I just tcping my ip, there is no difference with ping.
![3](https://cloud.githubusercontent.com/assets/18085459/19418288/695fb1ca-93f3-11e6-8807-d74657189747.png)

**Comment by jiaozhh** [comment]
DO is blocked intermittently, so I have given it up.

**Comment by ikkyusan123** [comment]
I have tried different vps, such as DO,Vultr and Choopa, however, there are still lots of timed out  in client 3.3.3. Now, I am using old client 3.0, it's very normal in shadowsocks.log, so I think it's the problem of client 3.3.3, I just report this bug.

**Comment by wongsyrone** [comment]
Enlarge server timeout should do the trick. We reconnect in the previous version when timeout exceeded.

**Comment by ikkyusan123** [comment]
I tempted to enlarge timeout to 20 in client, but it's invalid.  There are still lots of timed out  in shadowsocks.log. Should I enlarge timeout in my server?

**Comment by ikkyusan123** [comment]
Now，there is a serious problem in various client. The Networks are often not responding,including website in China. There are lots of timed out in log campus network, but it was normal in client 3.0 several days ago. I think it may be  related to campus network, but I can't verify that.
