### ISSUE TITLE
it doesn't work in Windows7

### ISSUE THREAD

**Issue by ZombieAki** [shadowsocks/shadowsocks-windows#799]
**Version**
3.3.3

Environment
Windows7 ultimate .NET Framework 4.5

Steps you have tried
run it with admin model.

What did you see instead?
it warnd me.
![ykvx l623d0 ixt5 je kev](https://cloud.githubusercontent.com/assets/19723289/19415976/e460201a-93b4-11e6-9913-225337222804.png)

**Comment by rebiu** [comment]
#781
