### ISSUE TITLE
“统计配置”窗口 icon 和窗口位置调整

### ISSUE THREAD

**Issue by mwacgi** [shadowsocks/shadowsocks-windows#800]
@wongsyrone
Shadowsocks 右键 -> “服务器” ->“ 统计配置” 这个窗口的 icon 能否换成 Shadowsocks 的图标？现在是 Visual Studio 默认的图标，感觉很不正式。另外这个窗口打开时，窗口位置也不是固定的，建议居中显示。

谢谢！

**Comment by wongsyrone** [comment]
This feature is experimental.
