### ISSUE TITLE
shadowsocks 3.3.3 unhandled exception

### ISSUE THREAD

**Issue by sea0x** [shadowsocks/shadowsocks-windows#801]
### Version(release version or AppVeyor link)
shadowsocks 3.3.3

### Environment(Operating system, .NET Framework, etc)
Framework Version: v4.0.30319

### Steps you have tried

错误应用程序名称: Shadowsocks.exe，版本: 3.3.3.0，时间戳: 0x57fb2c18
错误模块名称: KERNELBASE.dll，版本: 6.1.7601.17514，时间戳: 0x4ce7bafa
异常代码: 0xe0434352
错误偏移量: 0x0000b727
错误进程 ID: 0x1354

### What did you expect to see?

Application: Shadowsocks.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
   at Shadowsocks.Controller.I18N.GetString(System.String)
   at Shadowsocks.View.MenuViewController.LoadMenu()
   at Shadowsocks.View.MenuViewController..ctor(Shadowsocks.Controller.ShadowsocksController)
   at Shadowsocks.Program.Main()

### when i run Shadowsocks.exe then terminated..

and i found unhandled exception information in the windows application event log..

My windows version:  Windows Server 2008 R2 Enterprise Service Pack 1

**ps: i use old version 2.5.8 is OK**  

![ss20161017142618](https://cloud.githubusercontent.com/assets/7335401/19427533/1b9b9e8e-9477-11e6-913b-a0fc2fe9197d.jpg)

**Comment by wongsyrone** [comment]
Post screenshot and describe how to reproduce.

**Comment by sea0x** [comment]
when i run Shadowsocks.exe then terminated..

and i found unhandled exception information in the windows application event log..

**ps: i use old version 2.5.8 is OK**  


![ss20161017142618](https://cloud.githubusercontent.com/assets/7335401/19427533/1b9b9e8e-9477-11e6-913b-a0fc2fe9197d.jpg)

**Comment by wongsyrone** [comment]
install .NET 4.6.2

**Comment by wongsyrone** [comment]
If you upgrade from a very old version, delete old configs and temp folder, reconfigure from scratch.

**Comment by sea0x** [comment]
After installing the .NET 4.6.2, the problem is Resolved...

thanks @wongsyrone
