### ISSUE TITLE
什么时候可以提供类似sockscap指定软件进行代理的功能

### ISSUE THREAD

**Issue by SpeedMe** [shadowsocks/shadowsocks-windows#802]
希望能有这样的功能，主要用非开源的软件有点不放心。

**Comment by Yekaho** [comment]
proxifier (closed source) is recommended

**Comment by chenshaoju** [comment]
此类软件太多，没必要在造轮子了。。。
FreeCap,SocksCap32,SocksCap64,Proxifier...

这是开源免费的SocksCap64：
https://sourceforge.net/projects/sockscap64/files/
