### ISSUE TITLE
3.3.3 crashes (sometimes) at start

### ISSUE THREAD

**Issue by henrypijames** [shadowsocks/shadowsocks-windows#804]
3.3.3 crashed on Windows 7 SP1 x64 upon start:

![ss333_crash](https://cloud.githubusercontent.com/assets/164315/19507065/ffaa1826-9602-11e6-8e85-aa9e54a3105a.png)

And after a few tries and crashes, it suddenly started okay. No idea what the cause was.

**Comment by wongsyrone** [comment]
dup https://github.com/shadowsocks/shadowsocks-windows/issues/783

**Comment by wongsyrone** [comment]
Install at least .NET 4.5.1
4.6.2 is recommended.
