### ISSUE TITLE
希望可以添加一个鼠标左键单击任务栏图标以轮换PAC与全局模式的功能。

### ISSUE THREAD

**Issue by NER000** [shadowsocks/shadowsocks-windows#805]
如题。因为有时，虽然把网站的主域名添加进了pac文件，但往往网站所引用的静态资源并不存在于同一个域名之下，比如在其CDN里，导致网页显示不完全。所以这样的时候我总是临时更改为全局模式，用完后再改回来。每次都要右击、浏览菜单、更改，很麻烦，所以希望可以添加一个鼠标左键单击任务栏图标以 **轮换PAC模式与全局模式** 的功能，这样就省事多了。谢谢。

**Comment by wongsyrone** [comment]
Use global hotkey
