### ISSUE TITLE
新版3.3.3报错

### ISSUE THREAD

**Issue by ruiruige** [shadowsocks/shadowsocks-windows#806]
新版本有问题，一打开这样：
![image](https://cloud.githubusercontent.com/assets/8370100/19524454/6450211a-9650-11e6-8d38-a97838bb947a.png)

有的时候还能进去，然后选个服务器  就这样
win7 x64
![image](https://cloud.githubusercontent.com/assets/8370100/19524337/f7e8efde-964f-11e6-8047-9343d9ae75df.png)

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/804

**Comment by chenshaoju** [comment]
PS：我觉得可以先加一个判断，如果.NET版本不对，要求用户升级。
