### ISSUE TITLE
点击 详细记录日志 报错

### ISSUE THREAD

**Issue by Telisa** [shadowsocks/shadowsocks-windows#807]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.3

### Environment(Operating system, .NET Framework, etc)
Windows 7 64.

### Steps you have tried
点击详细记录日志

### What did you expect to see?
无

### What did you see instead?
Excpetion throwed

### Config and error log in detail (with all sensitive info masked)
![image](https://cloud.githubusercontent.com/assets/6258973/19542781/de30444e-96a3-11e6-92f1-c8edd0160358.png)

**Comment by wongsyrone** [comment]
Upgrade to .NET 4.6.2
