### ISSUE TITLE
3.3.3打开“高可用”后google等网页显示“意外终止了连接”（Can't use High availability）

### ISSUE THREAD

**Issue by MichaelZZY1998** [shadowsocks/shadowsocks-windows#809]
SS版本（Version）：3.3.3

系统：Windows 10周年版（已更新），.NET 4.6.2，广东电信，有5个香港节点，2个美国节点，1个新加坡节点。

尝试过的方法：
1.首先参阅了wiki上的TroubleShooting，删除了配置文件，重启电脑，只录入了5个香港节点（都可用），打开Chrome和IE11，打开Gooogle，显示“意外中止了连接”。
2.重启路由器，清理了Hosts，显示出错。
3.清理了注册表，重新下载了GitHub里的最新shadsocks 3.3.3，重新配置文件，显示出错。

理想状态下：
1.Google等网页应该能够正常打开。
2.速度方面应该有所提升。

现状：
除国内网址能正常打开外，google一系列的网址包括Youtube，Google+，Google相册等都打不开，全部显示“意外中止了连接”。

（我本人怀疑是SS逻辑上的问题，因为使用“负载均衡”和“根据统计”没有任何问题，唯独“高可用”无法使用。）

先感谢各位开发者的帮助，谢谢，THX:)

![default](https://cloud.githubusercontent.com/assets/22961675/19566543/4ba85592-971d-11e6-969d-b44d5416d1e6.PNG)

**Comment by wongsyrone** [comment]
This feature is unstable, don't use it.

**Comment by MichaelZZY1998** [comment]
Thx for ur notice:)@wongsyrone
