### ISSUE TITLE
多个实例开启时，清空日志，软件崩溃。

### ISSUE THREAD

**Issue by zhuziyi1989** [shadowsocks/shadowsocks-windows#810]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.3 or 3.3.4 

### Environment(Operating system, .NET Framework, etc)
Windows 7 (6.1.7601 Service Pack 1 Build 7601)

### Steps you have tried
打开了两个实例，并能正常使用，然后打开打开"显示日志"，并点击“清空日志”

### What did you expect to see?
正常清空日志。

### What did you see instead?
软件报错，并崩溃退出。

### Config and error log in detail (with all sensitive info masked)
![20161021101511](https://cloud.githubusercontent.com/assets/4889586/19585001/6d6af334-977b-11e6-80df-a1010fb710d7.jpg)

**Comment by wongsyrone** [comment]
Use portable mode for both instances.
