### ISSUE TITLE
3.3版本覆盖升级到3.4之后，无法连接到服务器

### ISSUE THREAD

**Issue by zhuziyi1989** [shadowsocks/shadowsocks-windows#811]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.4

### Environment(Operating system, .NET Framework, etc)
Windows 7 (6.1.7601 Service Pack 1 Build 7601)

### Steps you have tried
3.3版本覆盖升级之后。

### What did you expect to see?
日志部分：
Socket connected to ss server: xxxxx (ss.xxxxx.com:12345)

System.MissingMethodException: Method not found: 'Void System.Security.Cryptography.RandomNumberGenerator.GetBytes(Byte[], Int32, Int32)'.
   at Shadowsocks.Encryption.IVEncryptor.randBytes(Byte[] buf, Int32 length)
   at Shadowsocks.Encryption.IVEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   at Shadowsocks.Controller.TCPHandler.PipeConnectionReceiveCallback(IAsyncResult ar)

### What did you see instead?
无法正常连接

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
Read release note.
