### ISSUE TITLE
Win7 崩溃

### ISSUE THREAD

**Issue by simonkuang** [shadowsocks/shadowsocks-windows#812]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

3.3.4

### Environment(Operating system, .NET Framework, etc)

Win7 & .NET 4.0

### Steps you have tried

解压 exe 程序到 D 盘根目录，运行，崩溃。
崩溃时弹出 warning 对话框，并且能看到 Shadowsocks 的配置主界面，只是不能对主界面进行操作。
关闭 warning 对话框，主界面也一并消失。

### What did you expect to see?

不要报错，直接能操作主界面。

### What did you see instead?

有 warning 对话框。

### Config and error log in detail (with all sensitive info masked)

    ---------------------------
    Shadowsocks non-UI Error
    ---------------------------
    非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues     

    System.TypeInitializationException: “Shadowsocks.Controller.PrivoxyRunner”的类型初始值设定项引发异常。 ---> System.MissingMethodException: 找不到方法:“Void System.Runtime.InteropServices.Marshal.StructureToPtr(!!0, IntPtr, Boolean)”。    

       在 Shadowsocks.Util.ProcessManagement.Job..ctor()    

       在 Shadowsocks.Controller.PrivoxyRunner..cctor()    

       --- 内部异常堆栈跟踪的结尾 ---    

       在 Shadowsocks.Controller.PrivoxyRunner..ctor()    

       在 Shadowsocks.Controller.ShadowsocksController.Reload()    

       在 Shadowsocks.Program.Main()
    ---------------------------
    确定   
    ---------------------------

**Comment by wongsyrone** [comment]
Upgrade to .NET 4.6.2

**Comment by simonkuang** [comment]
> @wongsyrone commented 2 hours ago
> Upgrade to .NET 4.6.2

I upgrade .NET to 4.6, and it works.
Thank you :)
