### ISSUE TITLE
Windows10预览版1495x以后无法设置系统代理

### ISSUE THREAD

**Issue by zhanghaoyu1993** [shadowsocks/shadowsocks-windows#814]
### Version

版本-3.3.4
### Environment(Operating system, .NET Framework, etc)

操作系统-Windows10-14951.1000 64位
.NET Framework 4.6.1
### Steps you have tried

下载3.3.4版本，设置[**启用系统代理**]时发生Exception。
clone了源码到本地，重新编译了版本3.3.3，使用没有这个问题。
### Config and error log in detail (with all sensitive info masked)

![image](https://cloud.githubusercontent.com/assets/3580577/19600967/ddd54706-97d9-11e6-8c89-ce3292ac398e.png)
![image](https://cloud.githubusercontent.com/assets/3580577/19601037/216cece4-97da-11e6-9978-2453c57a4b26.png)

**Comment by wongsyrone** [comment]
The behavior is correct. This is why https://github.com/shadowsocks/shadowsocks-windows/issues/797 not working. Microsoft changes WinINET API, but I cannot get details.

> ERROR_INVALID_PARAMETER
> 87 (0x57)
> The parameter is incorrect.

**Comment by fzhw88** [comment]
楼主是不是写错了，是14951.1000，我的是x64版本，试了3.3.4倒不会报错，只是依然不能修改系统的代理设置，这个问题是从预览版14936（也许更早？）开始的。猜测是微软改变了相关API，不过在answer社区里微软的人没有给出正面回复。

**Comment by zhanghaoyu1993** [comment]
系统版本写错了，已经改过来了。
我的机器上之前的版本使用**系统代理：PAC模式**正常工作，更新到3.3.4之后就报异常退出。

**Comment by wongsyrone** [comment]
In general, if they decide to change API behavior, they should list them in the release note. I guess they break this by accident.

**Comment by fzhw88** [comment]
明白了，原来那个客户端是通过修改注册表做到的，那么还是继续等微软吧……

**Comment by fzhw88** [comment]
answer社区回复这个问题已经解决了，需要等待更新新的预览版。

**Comment by wongsyrone** [comment]
Can you paste the link?

**Comment by fzhw88** [comment]
https://answers.microsoft.com/zh-hans/insider/forum/insider_wintp-insider_web/%E4%BB%8Ewindows-10/1462cf0c-20e2-45a4-bcab-6521050433ac

**Comment by wongsyrone** [comment]
从

> 恭喜您的问题得以解决，请您等待之后陆续更新。

这句话来看，只是客套话而已，从全部对话来看他们并没有明确说已经找到问题根源。你应该明确说使用wininet internetsetoption api的程序无法完成预定功能。

**Comment by fzhw88** [comment]
我后来也发现了……真是蛋疼，已经在知乎把问题反馈给了@vczh 希望有效吧，真的不明白微软是怎么搞的，解决了这个问题我就不用快速通道的预览版了，晕死。
https://www.zhihu.com/question/51947290/answer/128250526?group_id=774221773766946816#comment-176841049

**Comment by wongsyrone** [comment]
但愿有用吧，总比正式版出来之后才发现不能用好。

**Comment by fzhw88** [comment]
@vczh回复问”GetLastError返回什么“，我电脑上没有编译环境……还是本科做过C，现在都不知道怎么搭建环境……尴尬啊，哪位大神系统刚好是insider版本的又有编译环境的试试？或者指点一下怎么简单的搭建编译环境？最好不要vc……

**Comment by breakwa11** [comment]
@fzhw88 返回87

**Comment by fzhw88** [comment]
@breakwa11 已经看到知乎有人回复～

**Comment by fzhw88** [comment]
从另外的反馈里得知wininet API是在3.3.3之后才被使用的，尝试退回到3.3.2甚至2.x版本的shadowsocks客户端，依然不能修改系统代理，不知何故～

**Comment by yuzhiqiangorg** [comment]
Error 67 似乎是 ERROR_BAD_NET_NAME: The network name cannot be found.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

**Comment by leoshh** [comment]
win10_14965也设置不了系统代理，希望尽早解决啊

**Comment by rc452860** [comment]
win10_14965 慢速更新通道同无法修改代理。刚更新的。

**Comment by Noisyfox** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101679/

**Comment by fzhw88** [comment]
@yuzhiqiangorg 不明白微软在干嘛，今天快速通道已经更新到了14971，依然没有解决问题。
@leoshh @rc452860 这是微软的问题。

**Comment by Noisyfox** [comment]
https://ci.appveyor.com/project/Noisyfox/shadowsocks-windows/build/job/el3wt3hjcuf9u7lb/artifacts

请尝试这个版本。如果有杀毒软件或者360提示一个叫做sysproxy.exe的进程在修改代理，可以加入白名单。

**Comment by DaoYangM** [comment]
楼上的ss确实可以用，也不用添加代理了。

**Comment by wongsyrone** [comment]
Noisyfox贴的那个版本里面用到的设置代理的小程序有内存泄露，不宜长期使用。

**Comment by wongsyrone** [comment]
有兴趣的可以试试https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.187/job/yrbfmmxu0q49v0aq/artifacts

相关修改：
https://github.com/wongsyrone/sysproxy/tree/mem
https://github.com/wongsyrone/shadowsocks-windows/commits/proxy_dev

**Comment by zhanghaoyu1993** [comment]
@wongsyrone  提供的版本没问题

**Comment by DaoYangM** [comment]
win10 14971用了这个软件后。开启正向代理设置。cpu占用100%，用Proxifier正常。
On Nov 19, 2016 17:20, 白井黑子 <notifications@github.com> wrote:有兴趣的可以试试https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.187/job/yrbfmmxu0q49v0aq/artifacts

相关修改：
https://github.com/wongsyrone/sysproxy/tree/mem
https://github.com/wongsyrone/shadowsocks-windows/commits/proxy_dev

**Comment by Noisyfox** [comment]
@DaoYangM 正式版的SS 3.3.5有这个问题么？

**Comment by Noisyfox** [comment]
Try the latest pre-release version.

**Comment by leoshh** [comment]
@Noisyfox 在14986上可以使用了！

**Comment by fzhw88** [comment]
升级到了14986，特意试了一下3.3.6是不行的，看起来微软并没有解决问题，失望。ss4.0倒是可以，不过似乎有bug，具体表现在退出SS后网络可能出问题，提示代理服务器问题之类。

因为这个问题，已经彻底转向路由器代理了。

**Comment by Noisyfox** [comment]
退出SS后的具体是什么问题呢？
有看过退出后网络设置里面代理设置有没有正确还原么？可不可以试一下然后提供一下具体的结果便于我们改进。

**Comment by wongsyrone** [comment]
从3.4.0开始设置代理是由单独的exe完成的，代码可见https://github.com/Noisyfox/sysproxy
可以看看是不是sysproxy.exe被拦截了。

**Comment by angoen** [comment]
3.3.6 14986好像还是用不了啊

**Comment by leoshh** [comment]
@fzhw88 @angoen 我也是醉了，明明说了要用pre版，还在用正式版却在这发帖是什么心态

**Comment by angoen** [comment]
@leoshh 不好意思，没有注意，不过预先版也不能用，3.4和3.4.1都试了试，都不行

**Comment by leoshh** [comment]
@angoen 抱歉，我口气也冲了点。。我这是能用的，ie开twitter什么的没问题，而下载东西就需要开全局了。你是怎么用不了？是有弹窗报错，还是就是连接超时？

**Comment by angoen** [comment]
@leoshh 没有报错，没有超时，就是打不开那些网站，甚至我可以在chrome上利用Proxy SwitchyOmega这个扩展程序实现代理，但是单独使用ss就不行

**Comment by Noisyfox** [comment]
全局模式呢？目前pac似乎也有人说有问题

**Comment by leoshh** [comment]
@angoen 用插件也是用的ss的服务器啊，单独使用插件，不用SS软件是打不开的吧

**Comment by angoen** [comment]
@Noisyfox 也不行

**Comment by angoen** [comment]
@leoshh 对，插件也需要ss的支持，但是单独使用ss就不行

**Comment by angoen** [comment]
对了，我曾经使用过win10 重至此电脑 这个功能，会不会跟这个有关系？

**Comment by Noisyfox** [comment]
你SwitchyOmega用的是http代理还是socks5？试试看http模式能不能用？因为ie用的是http代理

**Comment by angoen** [comment]
@Noisyfox 用的SOCKS5，刚刚试了试http模式，没有问题

**Comment by angoen** [comment]
@Noisyfox 不好意思，刚才是在使用chrome的情况下不能使用ss，我试了试ie，发现可以正常工作

**Comment by Noisyfox** [comment]
？？？用SwitchyOmega也不行？

**Comment by angoen** [comment]
@Noisyfox 在chrome浏览器使用SwitchyOmega的情况下，SOCKS5协议和http协议都可以使用，但是关闭SwitchyOmega，chrome浏览器就不能访问google。ie可以正常使用ss

**Comment by angoen** [comment]
@Noisyfox 很抱歉我刚刚没有说清楚

**Comment by Noisyfox** [comment]
去chrome的代理设置里面检查是否使用系统代理设置

**Comment by rc452860** [comment]
ssr可以用，但是不知道会不会被喷，因为那个作者没有遵守开源协议。。。貌似是这样的

**Comment by Noisyfox** [comment]
@rc452860 楼上的问题不在设置系统代理上，估计是chrome没有读系统代理设置

**Comment by Noisyfox** [comment]
@angoen 你所说的关闭SwitchyOmega是指禁用这个插件还是说SwitchyOmega里面设置 [直接连接]

**Comment by angoen** [comment]
@Noisyfox 直接连接

**Comment by Noisyfox** [comment]
那肯定不行啊，请选择[系统代理]

**Comment by Noisyfox** [comment]
直接连接是忽略一切代理设置的

**Comment by leoshh** [comment]
@Noisyfox 说到这，我请教一下，就是发现用chrome下载不走SS，这是机制决定的吗？

**Comment by angoen** [comment]
@Noisyfox 我把插件删掉了，已经可以使用了，非常感谢：）

**Comment by Noisyfox** [comment]
@angoen 我个人还是建议用这个插件，比较灵活，也方便随时添加规则，比起PAC要方便的多

**Comment by Noisyfox** [comment]
@leoshh 不应该啊？你确定下载用的地址在规则列表里么？

**Comment by leoshh** [comment]
@Noisyfox 这就不清楚了。可能是这个原因吧

**Comment by Noisyfox** [comment]
理论上浏览网页和下载是没有什么区别的。

**Comment by ding352** [comment]
以管理员身份运行 shadowsocks.exe 可以
