### ISSUE TITLE
How to change UI language to English

### ISSUE THREAD

**Issue by gaoyve** [shadowsocks/shadowsocks-windows#817]
Change language to English

**Comment by Robin2009** [comment]
why its closed? Is there any solution or this's the question should not be asked at all?

**Comment by chenshaoju** [comment]
Shadowsocks change language by system language settings.

String is here: https://github.com/shadowsocks/shadowsocks-windows/blob/aacc4edf6971594d07932e7db59018aef804d774/shadowsocks-csharp/View/ConfigForm.cs#L41
