### ISSUE TITLE
访问Apache建立的站点会出现 Apache2 Ubuntu Default Page

### ISSUE THREAD

**Issue by yerikyy** [shadowsocks/shadowsocks-windows#819]
不能正常访问Apache建立的站点，显示为Apache2 Ubuntu Default Page
关闭代理可以正常访问。不知道是什么原因。
打开代理显示如下图所示：
****
![image](https://cloud.githubusercontent.com/assets/19756219/19626215/f43a58f2-995e-11e6-8cf5-35fddd771e41.png)

**Comment by wongsyrone** [comment]
I don't think this is caused by Shadowsocks.

**Comment by yerikyy** [comment]
How can you be so sure?

**Comment by yerikyy** [comment]
Have yo tested it?
