### ISSUE TITLE
Please test it! Something is wrong when visiting sites built by Apache?

### ISSUE THREAD

**Issue by yerikyy** [shadowsocks/shadowsocks-windows#820]
First of all,  I am not here to waste my or your time. Read carefully before you close my issue.
I run into a question which can be expressed as follow.
When my SS service is stopped, everything goes quite well.
When I start my SS, the original site disappeared and a Apache default page is shown.
The only difference between two ways of visiting this site is whether the SS service is running.
So how can you say it's not the problem of SS? How can you close my issue without the discussion of other people? Have you tested it?  @wongsyrone 
The server is an windows server not a ubuntu one, why a page with items of ubuntu shows out?
It not as easy as what you think @wongsyrone 

![image](https://cloud.githubusercontent.com/assets/19756219/19626215/f43a58f2-995e-11e6-8cf5-35fddd771e41.png)

**Comment by chenshaoju** [comment]
This issue not happened on my system.
Windows 7 SP1 x86

**Comment by Yekaho** [comment]
Please give more information (OS vision, Chrome/IE/Edge/Firefox.... , ver. of the app)

**Comment by yerikyy** [comment]
@Yekaho can I send you private info about my link?

**Comment by eastmalon** [comment]
However, have you posted any info as you listed?
Try to reproduce it on a new server and figured out whether the shadowsocks-windows is a problem and post the log before you ask others test this.

**Comment by yerikyy** [comment]
Sorry about items used above. I am just quite pissed off about the one who closed my last post 5min after I created that post without any test and even tagged it with invalid. 
I restarted this post just for discussion. Apologist for my temper-loss.
@eastmalon

**Comment by yerikyy** [comment]
I am transferring that site to a new server provided by VULTR now. I'll be back with my test result.

**Comment by yerikyy** [comment]
I have transfer all my file to a brand new server. The problem remained.
Test link www.mythu.cn.
Anyone who can help?

**Comment by yerikyy** [comment]
Problem solved.
If you are using Ramnode VPS as SS server, it required a domain when you buy it.
DO NOT assign your own domain to it, just input something random, even something doesn't make sense. 
Cause the Ramnode will add a line off your domain and IP into HOSTS file automatically, which is really shit to me!
