### ISSUE TITLE
Websites showing 500 Internal Privoxy Error

### ISSUE THREAD

**Issue by Stormeh** [shadowsocks/shadowsocks-windows#821]
Version(release version or AppVeyor link)
3.3.4

Environment(Operating system, .NET Framework, etc)
Windows 10, .Net 4.6

Steps you have tried
Reinstalled SS Server End
Reinstalled Windows 10 Client End
Downloaded 3.3.4, reset config

What did you expect to see?
All sites should be working.

What did you see instead?

For the websites I have tested, this shows up 100% for Google, Youtube, Facebook, not sure about others, but given the situation I believe it's just not working for sites that are blocked by the GFW most of the time.

500 Internal Privoxy Error
Privoxy encountered an error while processing your request:
Could not load template file no-server-data or one of its included components.
Please contact your proxy administrator.
If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

Config and error log in detail (with all sensitive info masked)

{
"server":"",
"server_port":15216,
"local_port":1102,
"password":"",
"timeout":600,
"method":"rc4-md5"
}

I have reported this defect under #767 last time and was closed after getting a link which I verified did not fix the issue.

**Comment by wongsyrone** [comment]
Show some examples.

> please put the required file(s)in the (confdir)/templates directory

We don't use templates in Privoxy, as far as I know, only ShadowsocksR uses it.

**Comment by Stormeh** [comment]
@wongsyrone what type of examples do you need?

I'll go step by step exactly on how I've been using Shadowsocks since 2.4.

I have a server setup on a VPS in HK, following instructions on https://goo.gl/9NoH4o and this is the only thing setup on the VPS, it's used for nothing else.  

As for client end, all I do is download the latest Shadowsocks client, setup config and I set System proxy to use 127.0.0.1:1102, and I've tried this on both HTTP and Socks.  Neither works.

My habit of using the software didn't suddenly change 2 weeks ago, I've tried resetting internet, reinstalling both machines and yet somehow this Google series website and Facebook just run into this 500 error while other websites work as intended.

**Comment by eastmalon** [comment]
Try running these two commands on client and reboot
`netsh winsoc reset`
`ipconfig/flushdns`

**Comment by Noisyfox** [comment]
It'll be great if you could try different release versions and tell us from which version this issue happens. That'll be a great help.
