### ISSUE TITLE
Shadowsock seem have some incompatible issue with new Windows sleep feature.

### ISSUE THREAD

**Issue by yoyoyoooooooo** [shadowsocks/shadowsocks-windows#822]
I found Shadowsocks-windows seem have some incompatible issue with new Windows sleep feature.

The environment to trigger this issue: 
1) Windows 10
2) Intel 6 Generation CPU or later
3) enable "connect stand by" feature and Sleep S0 status
Typical environment: Surface Book or Surface Pro 4 connected with charger, when entering Sleep S0 status for more than 2 hours.

Symptom:
Before Shadowsock 3.3.2 (included), it is unable to use PAC to open "blocked website" when resume from sleep. However, it is fine to use global setting after wake up. Only solution is turn off and on "enable system proxy". 
After Shadowsock 3.3.2, the total software become unusable when resume from sleep. It cannot open any website at all and would work again only turn on and off. It is a issue since all background programs cannot connect to internet. For example the Outlook cannot connect even with "unblocked servers" during the sleep, otherwise it will keep up to date all the time.

This issue does not found in computer with "normal sleep status" such as S3 Sleep Status. Surface pro 3 does not affected by it. I`m not confirm the issue is caused by incompatibility with Sleep S0. But as far as I know, just Surface Book and Surface Pro 4 enable this feature (probably more laptop with Intel 7th CPU will enable it), and do not find this issue in other computer. It is not a big issue, but some time make me frustrating :(  

Hope my information above make the case clear. At the end, thanks for all your work :)

**Comment by wongsyrone** [comment]
Check log. We set the timeout to be 5 secs before start controller.

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Program.cs#L110

**Comment by wongsyrone** [comment]
Test https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.109/job/vtw3690e30acjnyq/artifacts

**Comment by yoyoyoooooooo** [comment]
Just download it, I will tell you result later :)

**Comment by yoyoyoooooooo** [comment]
After sleeping 4 hours, the Shadowsocks still work :) 
I will check it in following sleeping and report it to you. Hope it is solved :)
Thanks again. 👍

**Comment by wongsyrone** [comment]
Close due to inactive.

**Comment by yoyoyoooooooo** [comment]
sorry for late reply, I think the issue is fixed :) 👍 👍 👍

**Comment by yoyoyoooooooo** [comment]
Bad news, I am here to confirm the issue still. How would I provide the information you need to resolve the issue? @wongsyrone
