### ISSUE TITLE
为什么一用3.3.4 就打不开

### ISSUE THREAD

**Issue by xdeng** [shadowsocks/shadowsocks-windows#823]
用回3.3.3就没问题！
日志
[2016-10-24 11:10:52] System.MissingMethodException: 找不到方法:“Void System.Security.Cryptography.RandomNumberGenerator.GetBytes(Byte[], Int32, Int32)”。
   在 Shadowsocks.Encryption.IVEncryptor.randBytes(Byte[] buf, Int32 length)
   在 Shadowsocks.Encryption.IVEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.PipeConnectionReceiveCallback(IAsyncResult ar)
[2016-10-24 11:10:52] System.MissingMethodException: 找不到方法:“Void System.Security.Cryptography.RandomNumberGenerator.GetBytes(Byte[], Int32, Int32)”。
   在 Shadowsocks.Encryption.IVEncryptor.randBytes(Byte[] buf, Int32 length)
   在 Shadowsocks.Encryption.IVEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.PipeConnectionReceiveCallback(IAsyncResult ar)

两台电脑都这样，设置应该没问题的。

**Comment by xdeng** [comment]
还有就是 统计配置 里为啥不用中文 ？菜单都用中文了！  还有就是数值问题 有些值是越大越好 还是越小越好？各种搞不懂。

**Comment by chenshaoju** [comment]
你需要升级到最新的 .NET Framework 4.6.2
https://www.microsoft.com/zh-cn/download/details.aspx?id=53344

请仔细阅读发布说明。

![1](https://cloud.githubusercontent.com/assets/515763/19633588/ea8adf5c-99e5-11e6-8843-8e34a0481b02.png)

英文的问题，欢迎提交汉化。

**Comment by xdeng** [comment]
@chenshaoju  =.=!  我是看到你3.3.3里面写了 Upgrade to .NET Framework 4.6.2  然后我3.3.3是能用的，所以就以为我已经是4.6.2了。

**Comment by celeron533** [comment]
升级framework导致的兼容问题。。。
