### ISSUE TITLE
无法使用代理，日志显示缺少方法

### ISSUE THREAD

**Issue by MyDeity** [shadowsocks/shadowsocks-windows#825]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.4

### Environment(Operating system, .NET Framework, etc)
Win 7 x64 .NET framework 4.5

### Config and error log in detail (with all sensitive info masked)
System.MissingMethodException: Method not found: 'Void System.Security.Cryptography.RandomNumberGenerator.GetBytes(Byte[], Int32, Int32)'.
   at Shadowsocks.Encryption.IVEncryptor.randBytes(Byte[] buf, Int32 length)
   at Shadowsocks.Encryption.IVEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   at Shadowsocks.Controller.TCPHandler.PipeConnectionReceiveCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
你需要升级到最新的 .NET Framework 4.6.2
https://www.microsoft.com/zh-cn/download/details.aspx?id=53344

请仔细阅读发布说明。

https://cloud.githubusercontent.com/assets/515763/19633588/ea8adf5c-99e5-11e6-8843-8e34a0481b02.png
