### ISSUE TITLE
我用的2.5.6的版本,为啥更新PAC文件时不能更新,提示是Failed to update PAC file

### ISSUE THREAD

**Issue by lxk0301** [shadowsocks/shadowsocks-windows#826]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by lxk0301** [comment]
我用的是2.5.6版本的,更新PAC文件的时候会报错,提示是"Failed to update PAC file"

**Comment by wongsyrone** [comment]
URL changed
