### ISSUE TITLE
shadowsocks 3.3.4无法使用

### ISSUE THREAD

**Issue by Alasmercer** [shadowsocks/shadowsocks-windows#827]
### Version
shadowsocks 3.3.4

### Environment
win7 x64
.NET 4.5.2

### 问题
更新以后浏览器使用ss代理无法打开任何连接，chrome显示“XXX.com意外终止了链接”，ERR_CONNECTION_CLOSED。

日志持续报错

除了了gui-config.json外的文件全部是重新生成的，未作改动。

服务器正常，ss换回2.5.6正常使用。

### error log
> [2016-10-25 09:40:00] System.MissingMethodException: 找不到方法:“Void System.Security.Cryptography.RandomNumberGenerator.GetBytes(Byte[], Int32, Int32)”。
   在 Shadowsocks.Encryption.IVEncryptor.randBytes(Byte[] buf, Int32 length)
   在 Shadowsocks.Encryption.IVEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.PipeConnectionReceiveCallback(IAsyncResult ar)

**Comment by chenshaoju** [comment]
你需要升级到最新的 .NET Framework 4.6.2
https://www.microsoft.com/zh-cn/download/details.aspx?id=53344

请仔细阅读发布说明。

![1](https://cloud.githubusercontent.com/assets/515763/19633588/ea8adf5c-99e5-11e6-8843-8e34a0481b02.png)

**Comment by Alasmercer** [comment]
直接通过ss升级的，没有注意.net要求，抱歉

由于一些问题，现在没法升级.net了，只能继续使用旧版了

感谢
