### ISSUE TITLE
Shadowsocks.Controller.PrivoxyRunner"的类型初始值设定项引发异常

### ISSUE THREAD

**Issue by lornlee** [shadowsocks/shadowsocks-windows#828]
Shadowsocks.Controller.PrivoxyRunner"的类型初始值设定项引发异常。
System.MissingMethodException:找不到方法：‘vodi。System.runtime.interopservices.marshal.structuretoptr（！！0，IntPtr,Boolean）“
    在shadowsocks.util.processmanagement.job..ctor()
    在shadwosocks。controller.privoxyrunner..cctor()
    内部异常堆栈跟踪的结尾
    在shadowsocks.controller.privoxyrunner..ctor()
    在shadowsocks.controller.shadwosockscontroller.reload()
    在shadowsocks.program.main()

**Comment by chenshaoju** [comment]
你需要升级到最新的 .NET Framework 4.6.2
https://www.microsoft.com/zh-cn/download/details.aspx?id=53344

请仔细阅读发布说明。

![1](https://cloud.githubusercontent.com/assets/515763/19633588/ea8adf5c-99e5-11e6-8843-8e34a0481b02.png)
