### ISSUE TITLE
SOCKS protocol error

### ISSUE THREAD

**Issue by yiwuwang** [shadowsocks/shadowsocks-windows#829]
how solve the error.

504 Connect to www.google.com:80 failed: SOCKS protocol error
The following error occurred while trying to access http://www.google.com/:
504 Connect to www.google.com:80 failed: SOCKS protocol error
Generated Tue, 25 Oct 2016 16:41:54 中国标准时间 by Polipo on SKY-20160514MCE:8123.

**Comment by wongsyrone** [comment]
>  by Polipo

We don't use Polipo.
