### ISSUE TITLE
3.3.4 下载后Windows Defender提示报毒

### ISSUE THREAD

**Issue by blackfoxsar** [shadowsocks/shadowsocks-windows#833]
RT
从git上下载的zip包
下载好的瞬间Chrome和Defender均提示有病毒，并直接将压缩包彻底删除
另外：在添加了允许列表后 解压缩出来的exe没有任何报毒问题
（请允许我做一个比较蛋疼的推测，是否会有有关部门将压缩包的MD5等特征码提交给各大杀软厂商的可能性）

**Comment by wongsyrone** [comment]
You can compile it yourself.

**Comment by chenshaoju** [comment]
请更新你的杀毒软件，截至目前，全球５６款杀毒软件均未报毒。
https://www.virustotal.com/en/file/555a4dff6092d015d113b618f7cd645350387c5501568ae1d6dbf42c72c8bd94/analysis/1477479775/

PS：请注意核验下载回来的压缩包中的 Shadowsocks.exe 的MD5和SHA1。
