### ISSUE TITLE
最新版3.3.4，chrome Windows Defender均有报毒。

### ISSUE THREAD

**Issue by Ziglr** [shadowsocks/shadowsocks-windows#834]
Version
3.3.4

Environment
Windows 10/7 Chrome 54 IE1
![20161026165428](https://cloud.githubusercontent.com/assets/8709028/19720093/4f272442-9b9f-11e6-985e-0c9c57a4f4eb.png)
![20161026165616](https://cloud.githubusercontent.com/assets/8709028/19720095/513ee922-9b9f-11e6-8d7a-48ed0789b732.png)

**Comment by wongsyrone** [comment]
> 这个程序很危险，而且执行来自攻击者的命令。推荐的操作：立即删除这个软件。

**Comment by chenshaoju** [comment]
请更新你的杀毒软件，截至目前，全球５６款杀毒软件均未报毒。
https://www.virustotal.com/en/file/555a4dff6092d015d113b618f7cd645350387c5501568ae1d6dbf42c72c8bd94/analysis/1477479775/

PS：请注意核验下载回来的压缩包中的 Shadowsocks.exe 的MD5和SHA1。

**Comment by lixingcong** [comment]
@chenshaoju 是zip文件报毒，解压出来的exe没有报毒。。。md5也是正确的，很是奇怪。。

**Comment by Ziglr** [comment]
@chenshaoju 那么看来是Windows Defender误报了。
正如楼上所言，shadowsocks.exe本身不报毒，Shadowsocks-3.3.3.zip不知道为什么被Windows Defender报毒。

**Comment by chenshaoju** [comment]
非常奇怪的问题 ![pcmoren_tanshou_org](https://cloud.githubusercontent.com/assets/515763/19731733/01aa7aca-9bd1-11e6-98a2-624075c1039b.png)

**Comment by jerry74** [comment]
https://www.virustotal.com/en/file/555a4dff6092d015d113b618f7cd645350387c5501568ae1d6dbf42c72c8bd94/analysis/

7款报毒了

**Comment by chenshaoju** [comment]
我用Windows 10 自带的 Windows Defender 扫描了 3.3.4 版本的 .zip 文件和 .exe 文件，仍然没有问题（校验码在右边）：

![2016-10-29](https://cloud.githubusercontent.com/assets/515763/19826851/75ec037e-9dc8-11e6-94ec-74e5f3b6eb6b.png)

**Comment by jerry74** [comment]
现在又好了 是误报吧
F-Secure
![2016-10-29_11-25-46](https://cloud.githubusercontent.com/assets/3943094/19826920/9a84ee10-9dca-11e6-9137-ecf36a908632.png)

**Comment by Ziglr** [comment]
@chenshaoju 我是win7版的最新mse，今天Shadowsocks-3.3.4.zip依旧报毒。
![20161029234637](https://cloud.githubusercontent.com/assets/8709028/19830980/2eb3fe34-9e32-11e6-95ac-bf5f1f0cd3ed.png)
![20161029234424](https://cloud.githubusercontent.com/assets/8709028/19830981/2f95bf36-9e32-11e6-8557-11bc24c0ff8a.png)
![20161029234335](https://cloud.githubusercontent.com/assets/8709028/19830983/32d87daa-9e32-11e6-9b9f-b446ca126559.png)

**Comment by Ziglr** [comment]
我去微软反馈了，然后更新病毒库定义后，不再报毒了。问题终于解决了。
![20161030000514](https://cloud.githubusercontent.com/assets/8709028/19831160/c6a8d342-9e35-11e6-834c-d17309c6faa9.png)

**Comment by laalaguer** [comment]
@jerry74 你也用的是F-Secure....
