### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by Anjon-github** [shadowsocks/shadowsocks-windows#836]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.4

### Environment(Operating system, .NET Framework, etc)
Windows 7 专业版

### What did you expect to see?
正常启动

### What did you see instead?
双击启动出错页面

**Comment by chenshaoju** [comment]
能否将错误的截图附上？

**Comment by DavidLining** [comment]
Update the version of .net framework to 4.6.2 or higher.
