### ISSUE TITLE
建议：能否提供单独的user-defined-pac.txt文件

### ISSUE THREAD

**Issue by zhanghaoyu1993** [shadowsocks/shadowsocks-windows#837]
### Version
版本3.3.3

### Environment
OS：Windows10-64位

### 建议及解决的问题

- 现在在使用Chrome的[SwitchOmega](https://github.com/FelisCatus/SwitchyOmega/)插件配Shadowsocks使用，在Chrome浏览器中体验不错。
- 但是有时需要通过其他方式（浏览器之外的方式）使用ss代理访问pac没有定义的位置，就要修改pac文件：
![image](https://cloud.githubusercontent.com/assets/3580577/19752970/c80a5836-9c33-11e6-9687-13aa65b0d21b.png)
- 为了保证pac准确，又要定时的更新pac文件。
- 所以能不能提供一个**编辑自定义pac文件**的功能，这样即使更新了pac文件，自己定义的规则也还在，类似这种。
![image](https://cloud.githubusercontent.com/assets/3580577/19753000/0c4f7dbe-9c34-11e6-82cc-a4a22601e1bb.png)

**Comment by fzhw88** [comment]
支持，我都是直接修改pac，但是修改了pac之后，每次更新gfwlist得先备份自己添加的部分。

**Comment by wongsyrone** [comment]
Send a PR.
