### ISSUE TITLE
你好大神，shadowsocks-windows程序的窗口大小能不能自己拉大点啊，现在太小了

### ISSUE THREAD

**Issue by lsnmx** [shadowsocks/shadowsocks-windows#839]
shadowsocks-windows程序的窗口大小能不能自己拉大点啊，现在太小了
最好能自定拉大放小，程序记住调整过的大小
![1](https://cloud.githubusercontent.com/assets/8983585/19782927/95bf86dc-9cc2-11e6-86cf-4e01adfc7e3a.jpg)

**Comment by wongsyrone** [comment]
Send a PR.

**Comment by lsnmx** [comment]
@wongsyrone  大神，我不懂啊，麻烦你收录一下吧
