### ISSUE TITLE
请问shadowsocks-windows支持插件的形式开发吗？

### ISSUE THREAD

**Issue by easonjim** [shadowsocks/shadowsocks-windows#841]
请问可以以插件的形式开发类似获取服务器列表数据后更新json文件的功能吗？

**Comment by wongsyrone** [comment]
插件应该是没有办法，不过我感觉SS客户端只做好必须做的就行了，其他的交给外部实现。

**Comment by easonjim** [comment]
我想checkout然后加入插件机制的开发规范，是SS对于插件快速集成，如果不想要插件那就不装，你看可行不。

**Comment by easonjim** [comment]
我想checkout然后加入插件机制的开发规范，是SS对于插件快速集成，如果不想要插件那就不装，你看可行不。

**Comment by easonjim** [comment]
我想checkout然后加入插件机制的开发规范，是SS对于插件快速集成，如果不想要插件那就不装，你看可行不。
