### ISSUE TITLE
System.NullReferenceException: 未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by hushing** [shadowsocks/shadowsocks-windows#842]
System.NullReferenceException: 未将对象引用设置到对象的实例。
在 Shadowsocks.Controller.TCPHandler.Close()

这是什么错误？

**Comment by chenshaoju** [comment]
是否升级到了最新的 .NET Framework 4.6.2 ？
https://www.microsoft.com/zh-cn/download/details.aspx?id=53344

**Comment by Noisyfox** [comment]
有完整的异常信息么？

**Comment by Noisyfox** [comment]
Close due to inactive.

**Comment by RadarNyan** [comment]
有 UDP 流量的时候日志里会报这个错，但 UDP Relay 本身是能用的。
```text
System.NullReferenceException: Object reference not set to an instance of an object.
   at Shadowsocks.Controller.TCPHandler.Close()
```
