### ISSUE TITLE
win7系统无法使用shadowsocks3.3.4版本

### ISSUE THREAD

**Issue by XADlwx** [shadowsocks/shadowsocks-windows#845]
win7系统无法使用shadowsocks3.3.4版本

**Comment by breakwa11** [comment]
更新.NET到4.6以上

**Comment by celeron533** [comment]
准确讲是4.6.2，不过4.6.1跑起来也没什么问题

**Comment by yangg** [comment]
这样。。。不兼容还提示新版本，加上.net依赖判断才好。

**Comment by wongsyrone** [comment]
你不能在鸡蛋里面检测鸡蛋是否变成小鸡，只能在鸡蛋外面检测。

**Comment by dq19871123** [comment]
发布的时候选一下系统必备组件，以发布模式打包即可。。。不过个人感觉没有必要，而且发布更麻烦

**Comment by XADlwx** [comment]
没错！更新.NET到4.6.2
