### ISSUE TITLE
v3.3.4 版本被windows 10识别为木马？

### ISSUE THREAD

**Issue by xiongyihui** [shadowsocks/shadowsocks-windows#846]
Trojan:Win32/Matta.A!cl

https://github.com/shadowsocks/shadowsocks-windows/releases/download/3.3.4/Shadowsocks-3.3.4.zip

**Comment by chenshaoju** [comment]
请更新你的杀毒软件病毒库，详见：https://github.com/shadowsocks/shadowsocks-windows/issues/834
