### ISSUE TITLE
How to make other application(cmd) going through the proxy? 

### ISSUE THREAD

**Issue by marxwolf** [shadowsocks/shadowsocks-windows#848]
How to make other application(cmd) going through the proxy? 
When I use `lantern` or `VPN`, set http_proxy="" works well, but when using ss, it doesnot work.
How to do it?

**Comment by smounives** [comment]
Try [Proxifier](https://www.proxifier.com/).

**Comment by Noisyfox** [comment]
If the other application support define http proxy through environment variables, then it should works with ss. Otherwise, try Proxifier.
