### ISSUE TITLE
github和vscode这些未墙网站会走代理，导致无法打开

### ISSUE THREAD

**Issue by klezy** [shadowsocks/shadowsocks-windows#849]
http://code.visualstudio.com
以及
https://github.com
这些没被墙的网站会走代理，导致打开缓慢，甚至打不开。

希望添加个“排除名单”，名单上的网址不走代理。

**Comment by z43204320** [comment]
我也有类似问题，在user-rules.txt添加的排除名单好像没作用阿。
回去pac.txt 看发现连自带的排除名单都会走ss通路
![default](https://cloud.githubusercontent.com/assets/17777583/19863678/18601812-9fd0-11e6-9915-203aceb76c71.png)
![2](https://cloud.githubusercontent.com/assets/17777583/19863679/186290b0-9fd0-11e6-8bf9-a44fa796f0d8.png)
感觉是排除功能没有正常运作

**Comment by chenshaoju** [comment]
请联系GFWList： https://github.com/gfwlist/gfwlist

**Comment by cpjp** [comment]
自带的 PAC 规则不是来自 https://github.com/clowwindy/gfwlist2pac 吗？这个项目已经废弃很久了
希望可以改正

另外，排除功能是可以工作的
因为 pac.txt 经常恢复成默认，会自动加入 v2ex.com
我在 user-rule.txt 里加入了 @@||v2ex.com^  ，测试过 v2ex.com 不会再走代理

**Comment by chenshaoju** [comment]
目前最新的版本是来自 GFWList ，详见代码： https://github.com/shadowsocks/shadowsocks-windows/blob/f06f6f2fbb716c898df27e93d15b16e9def19f66/shadowsocks-csharp/Controller/Service/GfwListUpdater.cs#L13

**Comment by celeron533** [comment]
我一般都是直接在浏览器上安装switchomega直接指定代理
