### ISSUE TITLE
Shadowsock UI Error  

### ISSUE THREAD

**Issue by Bill-Zhang-BUAA** [shadowsocks/shadowsocks-windows#850]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.4

### Environment(Operating system, .NET Framework, etc)
Windows 10  周年更新版
.NET Framework 4.6.2

### Steps you have tried

原来不出现这个问题，今天下午在装了一波软件后，突然出现的问题。
安装的软件为：
Adobe CC Family Photoshop
Microsoft VIsual C++ 2010-2015运行库
Tecplot 360 EX 360 R1 //安装的时候修改host 增加了一行，删掉问题依旧
UltraEdit
Notepad++ 7.1
MATALAB 2016b

已经开启当前账户对 gui-config.json 的所有读取权限
已经开启当前账户对 statistics-config.json 的所有读取权限

### What did you expect to see?

软件可以正常运行，但是在打开软件的对话框后，会跳出“Shadowsock UI Error”
关闭对话框后程序闪退。

### Config and error log in detail (with all sensitive info masked)
“Shadowsock UI Error”

<img width="383" alt="_20161031215145" src="https://cloud.githubusercontent.com/assets/13661728/19860112/7d852cf4-9fc2-11e6-83b5-331f99d03e9c.png">

重新把Shadowsocks复制到别的地方后，打开界面，过一会儿就会出现这样的提示：
<img width="383" alt="_20161031233720" src="https://cloud.githubusercontent.com/assets/13661728/19860227/edc74d4e-9fc2-11e6-80d2-16dd5a740681.png">

**Comment by Bill-Zhang-BUAA** [comment]
还有，我的Visual Studio 今天刚装了一堆，因为要安装 Adobe 
<img width="726" alt="_20161031234910" src="https://cloud.githubusercontent.com/assets/13661728/19860666/88f608d6-9fc4-11e6-902e-6f4070684e8f.png">

**Comment by hangchao** [comment]
请问最后解决了吗？升级3.3.4后也出现这个问题了，使用原来的版本也出现了这种情况

**Comment by chenshaoju** [comment]
请尝试以修复模式重新安装  .NET Framework 4.6.2 https://www.microsoft.com/zh-cn/download/details.aspx?id=53344

**Comment by Noisyfox** [comment]
请尝试portable mode
