### ISSUE TITLE
托盘活动指示图标对比度低难以识别

### ISSUE THREAD

**Issue by 476210180** [shadowsocks/shadowsocks-windows#851]
新版本改变了托盘指示数据活动图标的样式及颜色，但是颜色较为暗淡难以识别，希望可以改回绿色和橙色。
![2016-11-01_091049](https://cloud.githubusercontent.com/assets/8447650/19876711/ae6e531c-a013-11e6-8a71-088deb4d50c6.png)

**Comment by breakwa11** [comment]
好吧，有空我再改改

**Comment by reaCodes** [comment]
![qq 20161104223644](https://cloud.githubusercontent.com/assets/13817254/20009431/7ae81a18-a2df-11e6-98b2-4e5a4e918530.png)
-----------------------------------------------------------------------------------------------
不用改吧，毕竟现在Windows 10的用户越来越多，这个图标在Win10的托盘里更统一好看！😊

**Comment by 476210180** [comment]
@reaCodes
并不是想冒犯谁，不过毕竟现在还有非 Windows 10
用户（比如我），总不能强制这些人升级系统或者干脆不考虑来自他们的声音吧？另外我说的只是希望把上下行指示图标的颜色换为对比更明显的，并不是说想整体改变图标风格。

**Comment by 772807886** [comment]
或者其实可以增加主题DIY的功能。。。
可以预置多个图标风格、图标颜色等供自行选择，还可以自行导入适当尺寸的图标等。。。
之前也有人提出过要统一所有界面的风格，#747，我觉得可以使用界面主题的方案，使用配置文件来操纵所有控件的位置、窗口大小等。。。

**Comment by wongsyrone** [comment]
作为一个托盘程序，搞一堆主题没必要吧，另外那个issue说的风格是界面排布什么的。

**Comment by celeron533** [comment]
最暴力的解决方案是给图标加上一层背景，比如浅灰，这样在任何地方都能清楚看到箭头。
自定义主题不建议，会使程序臃肿、健壮性下降、使用复杂度提高、兼容性下降。

**Comment by Quiet95scholar** [comment]
如果技术可以实现的话，可以让指示图标根据背景自己变颜色，比如说黑色背景--白色图标，绿色背景--红色图标这样

**Comment by 476210180** [comment]
我觉得把指示图标改成之前的绿色和橙色，并且三角形不带黑边应该不错。

**Comment by Quiet95scholar** [comment]
是不是可以把纸飞机的两片机翼利用起来，作为指示工具

**Comment by ye4241** [comment]
同觉得Windows 10 不用改。。。

**Comment by chenshaoju** [comment]
@Quiet95scholar 那样看起来只有1px……太大了空间不够。。。

**Comment by garveen** [comment]
@chenshaoju 我觉得 @Quiet95scholar 的意思是把整个飞机的翅膀染色而不是边缘，就好像这样

![image](https://cloud.githubusercontent.com/assets/3214266/20229716/f2fa6b2e-a892-11e6-89dc-750c1e0fdf47.png)

**Comment by chenshaoju** [comment]
@garveen 我觉得。。。好难看。。。。。。

**Comment by Quiet95scholar** [comment]
@garveen 这正是我所想的 @chenshaoju 我觉得难看是因为颜色不对，负责美工的人可以让它更漂亮

**Comment by garveen** [comment]
@chenshaoju 所以你要用设计师的眼光设计个好看的出来啊~

**Comment by celeron533** [comment]
纸飞机机翼不适合改变颜色

**Comment by chenshaoju** [comment]
我还是倾向于第二列的。

**Comment by Noisyfox** [comment]
我觉得有个箭头比较直观些

**Comment by chenshaoju** [comment]
但是实际效果不好，准确的说，整个图标看起来跟啃过一样。

Win7：
![unnamed qq screenshot20161113163547](https://cloud.githubusercontent.com/assets/515763/20244481/6575b1ae-a9bf-11e6-8f2d-17ec7c1f4f19.png)


Win10：
![unnamed qq screenshot20161113163649](https://cloud.githubusercontent.com/assets/515763/20244482/677e7350-a9bf-11e6-98d7-a9c8d34e4186.png)

有没有考虑换个颜色？左绿色为DOWNLOAD，右红色为UPLOAD，许多速度标识软件默认都是这个设定，比如Networx：

![unnamed qq screenshot20161113163808](https://cloud.githubusercontent.com/assets/515763/20244486/942e0de8-a9bf-11e6-900e-2ae907e78216.png)

**Comment by xenonz95** [comment]
干脆白色小三角就好？上下箭头已经可以区分上传下载了（其实我个人还不怎么需要看它）统一为纯白看着挺干净的。

**Comment by xenonz95** [comment]
![-1](https://cloud.githubusercontent.com/assets/16556163/20253926/97ea84ec-aa6a-11e6-84dc-354c65beac85.jpg)
用我自己通知栏的截图p了一个效果图，因为是色键抠图的所以有点丑

**Comment by xenonz95** [comment]
![-1](https://cloud.githubusercontent.com/assets/16556163/20254071/f6ab0320-aa6b-11e6-80f2-185879b1b75a.jpg)

进一步的话，翅膀的可以这样嘛

**Comment by xenonz95** [comment]
![-2](https://cloud.githubusercontent.com/assets/16556163/20254085/053399d4-aa6c-11e6-84e5-ba5cac00fd1d.jpg)
进一步的话，翅膀的可以这样嘛

**Comment by garveen** [comment]
其实我不关心现在有没有在上下传，我只关心断线了没……所以连续若干次失败后有个类似感叹号的东西对我更有意义

**Comment by 772807886** [comment]
这样怎么样
![1](https://cloud.githubusercontent.com/assets/10294977/20256484/df61bb06-aa7e-11e6-8c1d-ee3ba4328bf5.png)
![1](https://cloud.githubusercontent.com/assets/10294977/20256496/f3a5c6f2-aa7e-11e6-9248-4d104966ea5e.png)
![1](https://cloud.githubusercontent.com/assets/10294977/20256509/041bbb7c-aa7f-11e6-8f14-a95301f49e2c.png)
![1](https://cloud.githubusercontent.com/assets/10294977/20256529/1ecdd23e-aa7f-11e6-926a-7e058b0d1ce8.png)

**Comment by garveen** [comment]
@772807886 一分钟内10个exception，连接质量就肯定有问题了，这个阈值可能可以更低

**Comment by 772807886** [comment]
或者其实纯白的话也不错的，Win10下，系统的那些音量、电池、网络等的默认图标也是纯白的。
![qq 20161114162631](https://cloud.githubusercontent.com/assets/10294977/20257854/477cf46e-aa87-11e6-81fd-5dae5ebc386b.png)
```html
<!DOCTYPE>
<html>
<head>
<style>
body {
    background-image: url('https://source.unsplash.com/800x600/');
}
</style>
</head>
<body>
<svg width="24" height="24" viewBox="0 0 128 128" stroke="black" stroke-width="1" xmlns="http://www.w3.org/2000/svg">
    <path fill="white" d="M125 7L5 68L43 82L98 36L57 85L103 99ZM58 95V121L71 101Z"></path>
    <path fill="white" d="M4 44H42L23 11Z"></path>
    <path fill="white" d="M4 84H42L23 117Z"></path>
</svg>
</body>
</html>
```

**Comment by chenshaoju** [comment]
@garveen 这需要增加试探功能（每隔一段时间访问一个特定地址检查连接情况），但是闲置状态下的重复试探将会出现特征，加大被封锁概率。

**Comment by chenshaoju** [comment]
@772807886 纯白的看起来不错。但是在16x16的Windows 7 托盘区表现情况下会怎么样？

**Comment by garveen** [comment]
@chenshaoju 不需要试探功能，正常访问时看exception频率就好了

**Comment by chenshaoju** [comment]
@garveen Hmmm...如果用户刚启动，然后访问的目标网站凑巧挂了？当然，这个情况有点极端。

**Comment by garveen** [comment]
@chenshaoju 我相信你能判断断线是发生在远端服务器到目标网站，还是本地到远端服务器中间吧……我期望的是显示本地到远端服务器的连通性

**Comment by chenshaoju** [comment]
@garveen 很早以前有人提过这个，但是后来给否了，忘记是怎么回事了。

**Comment by xenonz95** [comment]
@chenshaoju 看日志里会记录服务器超时，当出现连续几次超时就显示感叹号不就行了

**Comment by garveen** [comment]
@chenshaoju #100 应该是这个，但是和我目前的需求（当前连接通还是不通）并不完全一样

**Comment by Jandaes** [comment]
纯白多好、简约不简单、大气！

**Comment by PeoceWang** [comment]
@772807886 软件的初衷是为了科学上网，整太多花里花哨的东西不好。

**Comment by Jandaes** [comment]
@PeoceWang 是的、现在都是追求卓越，越简单越好

**Comment by celeron533** [comment]
我当初最开始加入上传下载流量指示的理由是为了在网页卡顿的时候能够直观的从图标判断当前手法状态而已。就像早些年win98的系统托盘网络标识（两个电脑）一样

**Comment by wongsyrone** [comment]
一千个哈姆雷特问题。

**Comment by loveGEM** [comment]
对的，我还是喜欢底部黄绿的指示，4.0以后的版本可否考虑改回去
