### ISSUE TITLE
使用 .NET Framework 最新版本有哪些的优点？

### ISSUE THREAD

**Issue by hellofwy** [shadowsocks/shadowsocks-windows#852]
看到 shadowsocks-windows 3.3.4 版本要求 .NET Framework 4.6 以上，这样的话如果要使用新版本，得单独安装 .NET Framework 最新版。

**Comment by breakwa11** [comment]
我也不知道

**Comment by chenshaoju** [comment]
你可以在 https://github.com/Microsoft/dotnet/blob/master/releases/net462/dotnet462-changes.md 查看到 .NET Framework 的 Changelog 。

**Comment by hellofwy** [comment]
@chenshaoju 
[微软页面](Framework Versions)说最新的 .NET Framework 4.6.2 会包含在 Win10 Anniversary Update 中。
可不知为什么我的 Win10 目前还没收到更新推送。

我知道使用最新版可以保证最新安全和 bug 补丁。

可能是项目中使用了新版中的 API 吧，目前我还看不太懂 C#，不知道在那些地方。


[Framework Versions]: https://msdn.microsoft.com/en-us/library/bb822049(v=vs.110).aspx

**Comment by chenshaoju** [comment]
我也是，我的Windows 7 开着 Windows Update，但是没收到这个更新，我手动安装的。![pcmoren_tanshou_org](https://cloud.githubusercontent.com/assets/515763/19731733/01aa7aca-9bd1-11e6-98a2-624075c1039b.png)

**Comment by wongsyrone** [comment]
新api是 https://github.com/shadowsocks/shadowsocks-windows/commit/ce26bc15a91f7e9fa64edab263091d8745810e28 里面引进来的。如果感觉不爽，可以改回去，末尾记得Dispose。

这个新引进来的我看参考实现里面避免了复制，可以直接写到原buf里面。
