### ISSUE TITLE
新手一个 显示VPN图标 无法打开网页 可收到推送

### ISSUE THREAD

**Issue by KanVivii** [shadowsocks/shadowsocks-windows#853]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
 shadowsocks 1.15

### Environment(Operating system, .NET Framework, etc)

CentOS6
### Steps you have tried
 All

### What did you expect to see?

connection

### Config and error log in detail (with all sensitive info masked)
shadowrocket连接之后 显示VPN图标 能收到推送 但是无法打开网页

**Comment by KanVivii** [comment]
求大神们帮忙解决 完全新手 希望解释详细点

**Comment by breakwa11** [comment]
连issue都发错地方那你最好自行close

**Comment by KanVivii** [comment]
...

**Comment by KanVivii** [comment]
我的错我的错 因为都不是很懂 所以看了windows和centos两个 然后先试了下centos的 发现不会弄 两个网页弄错了 实在对不起
