### ISSUE TITLE
3.3.2 and 3.3.3 Virus Problem 杀毒软件报毒

### ISSUE THREAD

**Issue by laalaguer** [shadowsocks/shadowsocks-windows#854]
### Version(release version or AppVeyor link)

3.3.2 and 3.3.3
### Environment(Operating system, .NET Framework, etc)

Windows

F-Secure Anti Virus scan has removed those two files, because of virus detection.
![shdowsocks](https://cloud.githubusercontent.com/assets/6841046/19879328/774de974-a02c-11e6-95fa-dda9aec4e550.PNG)

**Comment by chenshaoju** [comment]
请更新你的杀毒软件，详见：https://github.com/shadowsocks/shadowsocks-windows/issues/846
