### ISSUE TITLE
【已解决】反馈问题win7下打开程序出现非预期性错误

### ISSUE THREAD

**Issue by shyboy** [shadowsocks/shadowsocks-windows#855]
### Version(release version or AppVeyor link)
3.3.4

### Environment(Operating system, .NET Framework, etc)
win7

![](http://o7rfj6p7p.bkt.clouddn.com/snipaste20161102_142841.png)

**Comment by chenshaoju** [comment]
你需要升级到最新的 .NET Framework 4.6.2
https://www.microsoft.com/zh-cn/download/details.aspx?id=53344

请仔细阅读发布说明。

![1](https://cloud.githubusercontent.com/assets/515763/19633588/ea8adf5c-99e5-11e6-8843-8e34a0481b02.png)

**Comment by shyboy** [comment]
额，我的错。抱歉！
