### ISSUE TITLE
Windows blocking 443 port

### ISSUE THREAD

**Issue by xiaogangsang** [shadowsocks/shadowsocks-windows#856]
I am running on windows 10, once I switch to port 443 on server(other ports are fine), I cannot open https webpage in browser any more(http is fine). The log is also looking fine, looks like some stupid software is blocking the 443 data, any one knows what that could be. I have turned off firewall, the problem still remains.
### Version(release version or AppVeyor link)
3.3.4

### Environment(Operating system, .NET Framework, etc)
Windows 10

### Steps you have tried
Turn off the firewall, allow shadowsocks to go through

### Errors I get on Safari
Make sure firewall settings aren't blocking your web access

### Errors I get on firefox
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

**Comment by chenshaoju** [comment]
This look's like your OS issue,Please try:
Right click start menu,click command prompt (Administrator),And entering:
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
And restart computer.

**Comment by Noisyfox** [comment]
Did you check the firewall settings on your server?

**Comment by Noisyfox** [comment]
Close due to inactive
