### ISSUE TITLE
公司内网不能使用

### ISSUE THREAD

**Issue by QingShiLuoGu** [shadowsocks/shadowsocks-windows#858]
公司的网络是通过代理上网的,shadowsocks就用不了,但是使用lantern就可以啊,想问问能不能加上这个功能啊?

**Comment by Noisyfox** [comment]
SS现在支持设置代理啊，你们公司是用什么类型的代理

**Comment by Noisyfox** [comment]
SS现在支持设置代理啊，你们公司是用什么类型的代理

**Comment by Noisyfox** [comment]
Close due to inactive
