### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by iliul** [shadowsocks/shadowsocks-windows#859]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

3.3.4

### Environment(Operating system, .NET Framework, etc)

windows 7 64bit

### Steps you have tried

none

### What did you expect to see?

```
[2016-11-04 22:47:04] Socket connected to ss server:{myserver}:8989
[2016-11-04 22:47:04] connect to clients4.google.com:443
[2016-11-04 22:47:04] System.MissingMethodException: 找不到方法:“Void System.Security.Cryptography.RandomNumberGenerator.GetBytes(Byte[], Int32, Int32)”。
   在 Shadowsocks.Encryption.IVEncryptor.randBytes(Byte[] buf, Int32 length)
   在 Shadowsocks.Encryption.IVEncryptor.Encrypt(Byte[] buf, Int32 length, Byte[] outbuf, Int32& outlength)
   在 Shadowsocks.Controller.TCPHandler.PipeConnectionReceiveCallback(IAsyncResult ar)
```

### What did you see instead?

none

**Comment by chenshaoju** [comment]
你需要升级到最新的 .NET Framework 4.6.2
https://www.microsoft.com/zh-cn/download/details.aspx?id=53344

请仔细阅读发布说明。

![1](https://cloud.githubusercontent.com/assets/515763/19633588/ea8adf5c-99e5-11e6-8843-8e34a0481b02.png)

**Comment by iliul** [comment]
@chenshaoju 谢谢回复，安装后正常工作了。:+1:
