### ISSUE TITLE
How could I use telnet (port 22) via shadowsocks ? 

### ISSUE THREAD

**Issue by bittorrent3389** [shadowsocks/shadowsocks-windows#860]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.4

### Environment(Operating system, .NET Framework, etc)
.NET Framework 4.6

### Config and error log in detail (with all sensitive info masked)
How could I use telnet (port 22) via shadowsocks ?

**Comment by chenshaoju** [comment]
Use putty.

http://www.chiark.greenend.org.uk/~sgtatham/putty/

![unnamed qq screenshot20161106101502](https://cloud.githubusercontent.com/assets/515763/20034875/e1b47d56-a409-11e6-98ed-bbce9e943c1e.png)
