### ISSUE TITLE
请问有没有计划推出Windows10Mobile客户端？

### ISSUE THREAD

**Issue by wanzhiyu** [shadowsocks/shadowsocks-windows#862]

**Comment by wongsyrone** [comment]
现在有些功能已经依赖于Win了，比如快捷键这类的，如果要支持移动端，可能要改架构。
不过全取决于 @Noisyfox

**Comment by smdhz** [comment]
我赌五毛WinRT架构权限绝对不够，后台进程还得访问网络

**Comment by Explorare** [comment]
我记得之前有过类似的讨论，当时就说过是 wp8 底层不支持来着，不知道 win10 mobile 是什么情况。

**Comment by Noisyfox** [comment]
我在做相关的研究，但是目前微软把win10 uwp vpn的相关api限制仅开放给partner，而且msdn上面也没有提供相关的文档。
目前仅有的成果：

![qq 20161107155950](https://cloud.githubusercontent.com/assets/1537155/20046914/43152b1e-a503-11e6-95e0-83e3dd891a12.png)

相关API现在处于尝试摸索阶段，预计很长时间不会有相关突破。

**Comment by Explorare** [comment]
@Noisyfox 如果能有精力整理出开发记录就好了，集思广益，方便更多的 dalao 加入工作。

**Comment by wanzhiyu** [comment]
如果是系统限制，的确挺麻烦的。。。大神加油~如果实在不行，就安卓和pc用用吧，也还算足够

**Comment by Noisyfox** [comment]
倒也不是系统限制，目前是微软政策的问题，这部分的开发文档不对外开放，只公布了api而且还没有使用说明。目前我也只能去尝试各种api调用的姿势看看能不能歪打正着。
至于目前现有的几款uwp的vpn插件，均是cisco之流和微软有合作关系的，开源的方案中目前还没有人实现了，包括openvpn论坛也有人在讨论这个事情。也有尝试去逆向这些现有的app过，但是难度太大。

**Comment by wongsyrone** [comment]
开发记录可以开个分支放到里面，也可以方便测试。

**Comment by Noisyfox** [comment]
uwp版本是一个全新的项目，基于win10的vpn framework

**Comment by wanzhiyu** [comment]
微软文档不放出来？我还一直以为没开放相应的api呢，话说微软干嘛这样做啊，是不是因为微软这块还没完全做好？

**Comment by Noisyfox** [comment]
因为只提供给微软的合作伙伴

**Comment by hellofwy** [comment]
利用安卓和 macOS 的 VPN 接口实现的 ShadowSocks 客户端，使用体验很好。
不知道 Windows 能不能有类似实现，而不是现在的系统代理模式。

了解到 Windows UWP 提供了 VPN 接口，所以搜到了这个讨论话题。
UWP 版本有进展吗？
不知道 UWP 的 VPN API 是否可以接管其他非 UWP 应用的网络连接。

看之前 ShadowVPN 有用到 OpenVPN 的 TAP-Windows driver，不知道利用这个能不能实现 VPN 模式的ShadowSocks 客户端？

**Comment by Noisyfox** [comment]
@hellofwy 
UWP 的 VPN 是全局的，会影响整个系统的应用。但是这部分并没有什么进展（除非微软开放这部分的文档否则短期内不会有太大希望）

**Comment by florianmonfort** [comment]
We should ask some Microsoft people about this. This is problematic.

**Comment by florianmonfort** [comment]
Created a Feedback Hub link and sent some comments on Twitter: https://aka.ms/Oghltb

**Comment by florianmonfort** [comment]
You might want to upvote that feedbackhub comment actually to draw more attention to the issue

**Comment by likidu** [comment]
@Noisyfox 
我这边或许能给api说明提供些内部的信息。我目前也在研究把SS移植到UWP上。想问下你上面添加一个新的vpn plugin有例程可以分享么？

**Comment by florianmonfort** [comment]
@likidu @Noisyfox 你认为你会设法使它工作有一天吗？

**Comment by likidu** [comment]
@florianmonfort Under investigation...

**Comment by zhcm** [comment]
@Noisyfox 
我在stackoverflow上看到，如果对VPN API有问题的话，可以联系msftvpnapi@microsoft.com。

**Comment by florianmonfort** [comment]
@likidu @Noisyfox did somebody contact them?

**Comment by bdbai** [comment]
@zhcm `msftvpnapi@microsoft.com` 这个邮箱不存在，邮件发过去就被拒绝了。
尴尬的是，微软文档那边也只留了这个邮箱。

**Comment by iljfsdi** [comment]
@Noisyfox 微软计划于六月完全关闭WP手机业务……（

**Comment by celeron533** [comment]
巨硬坑了啊，当然，诺基亚更惨

**Comment by bdbai** [comment]
手机业务停了，Win10 总不会停吧，还有 Surface。那啥 Win10 S 大概也用得上。

**Comment by zhcm** [comment]
@iljfsdi WP业务关不关其实无所谓，本来也没人用那玩意，主要是希望能有一个应用商店里的客户端

**Comment by bdbai** [comment]
https://social.msdn.microsoft.com/Forums/en-US/26b089e4-2448-42d7-a4fd-0fe65629b352/uwp-questions-about-vpn-plugin?forum=wpdevelop

按照官人的说法，一个 VpnChannel 只能开俩 Socket，估计是没戏了。除非微软改架构或者自己在 TCP 上衍生一套 IP 协议出来，然而后者就不叫 Shadowsocks 了。

**Comment by edsgerlin** [comment]
@bdbai 既然只能开一个TCP Socket，实际上可以换一个思路做吧。不用做成本身支持Shadowsocks协议的VPN，而是做成支持通过Socks5代理协议全局代理化的通用Proxifier，这样本项目的代码也可以继续被利用。localhost的Socks5代理，只要用户手动开Loopback Exemption就能访问了。既然是桌面系统，就没必要做成All-in-One的应用。如果Windows Phone还活着的话，新出的Surface Phone也应该要可以跑桌面应用了……

**Comment by Noisyfox** [comment]
然而问题依旧是，微软什么时候给vpn的sample

**Comment by bdbai** [comment]
@edsgerlin iOS 跟安卓都用 tun2socks 实现了，同理 WinRT 也没问题。

**Comment by ShiWei-L** [comment]
还在搞么~~

**Comment by bdbai** [comment]
@realLiangshiwei 

> 还在搞么~~

https://github.com/YtFlow/YtFlowApp
