### ISSUE TITLE
Windows 10 Pro Insider Preview Build 14955 上无法运行最新的v3.3.5客户端。

### ISSUE THREAD

**Issue by qzhsjz** [shadowsocks/shadowsocks-windows#864]
InternetSetOption:87
一直报这个错误。
![default](https://cloud.githubusercontent.com/assets/10796024/20048986/3aeaa3fe-a4fb-11e6-83a4-76a050aeb41a.PNG)

**Comment by wongsyrone** [comment]
#814

**Comment by Noisyfox** [comment]
Try the latest pre-release version.
