### ISSUE TITLE
3.3.2版本可用，3.3.3及之后的版本不可用

### ISSUE THREAD

**Issue by zyjisdog** [shadowsocks/shadowsocks-windows#865]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.3

### Environment(Operating system, .NET Framework, etc)
Win10， .NET 4.6.2

### Steps you have tried
在3.3.2版本，PAC模式和全局模式均可连接；
3.3.3及以后的版本均不可连接

我查看了更新日志，发现从3.3.3开始使用了wininet API，我在想是不是与这个有关？

**Comment by wongsyrone** [comment]
#814 

你猜对了。

**Comment by zyjisdog** [comment]
那有什么解决办法吗？或者该如何查错

**Comment by Noisyfox** [comment]
这个问题暂时不好解决，要看win10预览版之后会不会再改动这个接口。

**Comment by wongsyrone** [comment]
可以退回旧版ss或者稳定版win10

**Comment by Noisyfox** [comment]
Dup #814

**Comment by zyjisdog** [comment]
稳定版win10？我也不知道我是什么版本的win10，查看版本号是14393

**Comment by Noisyfox** [comment]
咦那不应该有这个问题啊
请问有错误日志么？

**Comment by fzhw88** [comment]
@zyjisdog  14393应该是稳定版的，不知道为什么也有这个问题。

**Comment by fzhw88** [comment]
楼主描述的情况和我遇到的似乎不同，我的问题是从Windows 10预览版某个版本开始（大概是14936），shadowsocks客户端修改系统代理无效，只能手动改。尝试退回3.3.2版本的shadowsocks甚至是2.x版本也无效，很奇怪。如果真的是wininet API的问题，那应该退回3.3.2及早期版本就可以用了？

**Comment by zyjisdog** [comment]
错误日志我找找看

**Comment by zyjisdog** [comment]
咦 竟然可以用了，不过日志里还是有报错：

[2016-11-08 17:16:48] Shadowsocks started
[2016-11-08 17:16:53] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 无法从传输连接中读取数据: 连接已关闭。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by Noisyfox** [comment]
如果你其它网页可以正常用ss打开，那就可以忽略这个异常

**Comment by Sherlock-Holo** [comment]
不知道为什么，开了全局之后，steam也不走代理了，慢速14965，ss是3.3.5

**Comment by Noisyfox** [comment]
Try the latest pre-release version.
