### ISSUE TITLE
Shadowsocks non-UI Error

### ISSUE THREAD

**Issue by aixlx** [shadowsocks/shadowsocks-windows#866]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.4

### Environment(Operating system, .NET Framework, etc)
OS Name	Microsoft Windows 8.1 Enterprise
OS Kernel Type	Multiprocessor Free (64-bit)
OS Version	6.3.9600.18505 (Win8.1 RTM)
.NET Framework	4.6.81.0 built by: NETFXREL2

### Steps you have tried
After a long run, a 'Shadowsocks non-UI Error' occurred

### Config and error log in detail (with all sensitive info masked)

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。

   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)

   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()

   在 System.Collections.Generic.List`1.Enumerator.MoveNext()

   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()

   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   在 Shadowsocks.Model.StatisticsRecord..ctor(String identifier, ICollection`1 inboundSpeedRecords, ICollection`1 outboundSpeedRecords, ICollection`1 latencyRecords)

   在 Shadowsocks.Controller.AvailabilityStatistics.UpdateRecords()

   在 Shadowsocks.Controller.AvailabilityStatistics.Run(Object _)

   在 System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)

   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.TimerQueueTimer.CallCallback()

   在 System.Threading.TimerQueueTimer.Fire()

   在 System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)

   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   在 System.Threading.ThreadPoolWorkQueue.Dispatch()

   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by wongsyrone** [comment]
Disable statistics.

**Comment by aixlx** [comment]
Still occurred
```
[2016-11-08 23:38:21] [server] timed out
[2016-11-09 06:49:58] [E] System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Shadowsocks.Model.StatisticsRecord..ctor(String identifier, ICollection`1 inboundSpeedRecords, ICollection`1 outboundSpeedRecords, ICollection`1 latencyRecords)
   在 Shadowsocks.Controller.AvailabilityStatistics.UpdateRecords()
   在 Shadowsocks.Controller.AvailabilityStatistics.Run(Object _)
   在 System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.TimerQueueTimer.CallCallback()
   在 System.Threading.TimerQueueTimer.Fire()
   在 System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by Noisyfox** [comment]
服务器->统计配置->去掉Enable Statistics的勾

**Comment by aixlx** [comment]
好了，谢谢。

> 之前以为是去掉`记录详细日志`了
