### ISSUE TITLE
怎么加了检查.net的版本

### ISSUE THREAD

**Issue by yangqingmang** [shadowsocks/shadowsocks-windows#867]
我电脑是win7的，兼容性最好的是.net 4.6.1，非让我下载4.6.2干啥

**Comment by chenshaoju** [comment]
我也是Windows 7 x64 SP1，已经升级到 4.6.2 ，没有问题。
4.6.2支持 TLS 1.1和1.2，SSL3已经不再安全，并且已经在4.6.2中停止支持。
即使是在非SS的环境中使用，也建议升级。

详见：
https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/

**Comment by Noisyfox** [comment]
Because #863 #859 #855 #845 #832 #830 #828 #825 #823 #815 etc. That's why we add version check.

It can run under .net 4.6.1 is a coincidence, we already switch to the latest sdk which is 4.6.2 for now and we have no spare time to check if our program is compatible with earlier version.
