### ISSUE TITLE
最新的要求.net 4.6.2版本，但是我的电脑上级玩4.6.2之后右下角一直提示一个suptab!blnk

### ISSUE THREAD

**Issue by yangqingmang** [shadowsocks/shadowsocks-windows#871]
最新的要求.net 4.6.2版本，但是我的电脑上级玩4.6.2之后windows defender一直提示一个suptab!blnk可以程序。这个能不能不要强制要求.net 4.6.2才能登陆，否则老一点的系统都不能登陆了。

**Comment by chenshaoju** [comment]
这是你的系统中毒了： https://www.reddit.com/r/techsupport/comments/5ar0fi/window_defender_is_constantly_finding_malware/

请确保你是从微软官网下载的.NET Framework 4.6.2：
https://www.microsoft.com/zh-CN/download/details.aspx?id=53344
