### ISSUE TITLE
点击启用系统代理时候弹出框

### ISSUE THREAD

**Issue by J-J-J** [shadowsocks/shadowsocks-windows#872]
![qq 20161109160342](https://cloud.githubusercontent.com/assets/13718575/20131162/b24ef246-a696-11e6-9f05-6751f0f6c6f3.png)
![qq 20161109160448](https://cloud.githubusercontent.com/assets/13718575/20131161/b0b0ddb4-a696-11e6-9beb-b07490b7c019.png)

**Comment by chenshaoju** [comment]
Windows 10 14959？详见： https://github.com/shadowsocks/shadowsocks-windows/issues/868
