### ISSUE TITLE
Win7sp1，启动ss后，再次启动系统时，无法连接网络

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-windows#876]
### Version(release version or AppVeyor link)
3.3.5.0

### Environment(Operating system, .NET Framework, etc)
Windows7sp1 

![as](https://cloud.githubusercontent.com/assets/10991795/20202299/33ed4178-a7f9-11e6-9ff0-eaf29972810c.JPG)

![default](https://cloud.githubusercontent.com/assets/10991795/20202293/1fe9469a-a7f9-11e6-9bf5-3c4d4047cc24.JPG)

经过检查，在internet选项\连接\局域网设置中，使用自动配置脚本地址栏内发现ss的本地pac地址

![as](https://cloud.githubusercontent.com/assets/10991795/20202354/a0367886-a7f9-11e6-86e9-2e481f168195.JPG)

![123](https://cloud.githubusercontent.com/assets/10991795/20202365/abd654fe-a7f9-11e6-95a4-5821299df110.JPG)

取消选择后，能正常连接网络

只要在上一次关机前有启动过ss客户端，那么开机时会出现无法连接网络的情况，需要手动将自动配置脚本地址栏取消选择才能正常访问，能否让ss在关机时能自动取消自动配置脚本，让下一次开机无需经过上述步骤也能正常连接网络？

**Comment by chenshaoju** [comment]
你是否使用了某些系统优化软件加快了系统关机速度？

**Comment by Aniark** [comment]
@chenshaoju
我用软媒魔方，如果是软媒造成的，要如何设置？

**Comment by chenshaoju** [comment]
刚试了一下，和系统优化无关，该问题的确存在，Windows 10 x64。

可能需要加一个关机事件(?)之类的。

@wongsyrone

**Comment by wongsyrone** [comment]
需要详细问题复现步骤

**Comment by Aniark** [comment]
@wongsyrone
1，连接网络，开启ss，启用系统代理并设置使用本地pac
2，重启，或着关机再开机
3，开机后检查internet选项\连接\局域网设置，在使用自动配置脚本地址栏内发现ss的本地pac地址，且此时无法连接网络

**Comment by wongsyrone** [comment]
确保休眠已关闭: `powercfg -h off`
无法复现

**Comment by chenshaoju** [comment]
不不不，和休眠无关，的确有这个问题。

**Comment by wongsyrone** [comment]
对啊，这是正确的行为啊，你需要手动关闭系统代理才行。只要启动ss就会默认应用配置文件里面的设置，代理自然不例外。

**Comment by chenshaoju** [comment]
但是在关机的时候，用户侧认为应该会撤销代理设置？

在关机或者重启的时候，系统会发送事件给所有应用，理论上可以收到这个事件后撤销代理再退出。。。

搜了一下：
http://10141389.blog.51cto.com/10131389/1642222

当然，具体的代码实现我不懂。。。

**Comment by wongsyrone** [comment]
退出程序的时候会关闭shadowsockscontroller，在 https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/ShadowsocksController.cs#L273 会强制关闭系统代理设置。

启动程序的时候会根据配置文件设置对应的系统代理模式 https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/ShadowsocksController.cs#L502

**Comment by wongsyrone** [comment]
最简单的办法就是关机前右键退出SS

**Comment by chenshaoju** [comment]
话说我一直没遇到过该问题的原因就是我关机前会手动退出所有应用。。。

**Comment by wongsyrone** [comment]
加关机事件对我来说没有意义，如果 Noisyfox 想改可以试试。能用简单办法解决的不要引入没什么大用的代码。

**Comment by Noisyfox** [comment]
奇怪的是为啥关机的时候没有触发Application_ApplicationExit

**Comment by Aniark** [comment]
@Noisyfox 同学用win8，也出现了这样的情况；如果触发了，那么应该会自动退出。显然我和我同学都没有触发

**Comment by wongsyrone** [comment]
> You must attach the event handlers to the Exit event to perform unhandled, required tasks before the application stops running. You can close files opened by this application, or dispose of objects that garbage collection did not reclaim.
Because this is a static event, you must detach any event handlers attached to this event in the ApplicationExit event handler itself. If you do not detach these handlers, they will remain attached to the event and continue to consume memory.

这个只在调用Application.Exit()的时候才会触发，并且也需要detach.

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/View/MenuViewController.cs#L545

**Comment by Noisyfox** [comment]
其实我觉得最简单的方法就是把ss设置成开机启动

**Comment by Noisyfox** [comment]
已确认这个是IE的一个bug，目前没有好的解决方法。
详情可以参见 https://github.com/getlantern/lantern/issues/2776

**Comment by wongsyrone** [comment]
关于关机的时候调用api的问题，MS已经标记为Wontfix了。所以这个不用想了。

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101679/
