### ISSUE TITLE
CPU consumption by 'WinHTTP Web Proxy Auto-Discovery Service' in 'High Availability' mode while idle

### ISSUE THREAD

**Issue by tradstone** [shadowsocks/shadowsocks-windows#879]
'WinHTTP Web Proxy Auto-Discovery Service' consumpts CPU cycles (~5% continuously in taskmgr 'processes' view, ~12% peak in Procmon) periodically in high frequency for about 15min.

This issue happens some times after wake from sleep, and it will be gone if I kill the shadowsocks process.

I never saw this in versions earlier than 3.2 or ShadowsocksR.
Is this an issue or it can be dealt with by configuration? 

Version=3.3.5
Environment=Windows 10 Pro 14393.447; .Net Framework 4.6.1
I'm running Shadowsocks in 'High Availability' mode with 12 server profiles

**Comment by Noisyfox** [comment]
If you re-open the shadowsocks will the cpu usage become normal?

**Comment by tradstone** [comment]
@Noisyfox No, not every time. It happens by chance, or it can be triggered by something I don't know yet. But this happened many times on my machine, It's pretty annoying.

**Comment by tradstone** [comment]
@Noisyfox It this relevant? #371

**Comment by Noisyfox** [comment]
I'm not sure. Seems it's not an issue in 'High Availability' mode.

**Comment by tradstone** [comment]
![capture](https://cloud.githubusercontent.com/assets/15955186/20460590/9e38e804-af22-11e6-9f57-2d980c56a55e.PNG)
![capture1](https://cloud.githubusercontent.com/assets/15955186/20460592/9e3db190-af22-11e6-8065-06735748a43c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15955186/20460593/9e3e4128-af22-11e6-950d-7a820befaf00.PNG)
![capture3](https://cloud.githubusercontent.com/assets/15955186/20460591/9e3d614a-af22-11e6-813e-6c178554a536.PNG)
![capture4](https://cloud.githubusercontent.com/assets/15955186/20460594/9e5b1e4c-af22-11e6-90b8-0c4daf868363.PNG)
![capture5](https://cloud.githubusercontent.com/assets/15955186/20460595/9e5bdcf6-af22-11e6-8a29-7fd66301bbc2.PNG)
![capture6](https://cloud.githubusercontent.com/assets/15955186/20460596/9e68c510-af22-11e6-8c5e-6179aae5e916.PNG)

**Comment by Noisyfox** [comment]
Hmmm... I have no idea...
Did you enable the system proxy?

**Comment by tradstone** [comment]
@Noisyfox  Yeah, I enabled system proxy.

**Comment by Noisyfox** [comment]
Well next time if these happens, please try disable the system proxy instead of close the ss and see if it gets better.

**Comment by tradstone** [comment]
@Noisyfox OK, will do.

**Comment by wongsyrone** [comment]
What mode are you using when this issue happens? If this only occurs when using PAC mode, you can try https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.190/job/617s0o7a1rnor351/artifacts

**Comment by tradstone** [comment]
@wongsyrone I was indeed using PAC mode. and thanks for the suggestion, I'll give it a shot next time this happens.

**Comment by tradstone** [comment]
@Noisyfox Issue reproduced, and it won't go away by disabling the system proxy, I have to shut down the process to make it disappear. 

This issue happened when I wake my laptop from sleep (connected standby),  and there was a Warnning even in windows's Event Viewer that says the 'WLAN Extensibility Module has stopped'.

**Comment by tradstone** [comment]
@wongsyrone No, it's not working.

**Comment by tradstone** [comment]
Reproduces with 3.3.6 and 3.4.0. And it is persistant.
Anybody seen this issue?

[windows syslog.txt](https://github.com/shadowsocks/shadowsocks-windows/files/644167/windows.syslog.txt)

![capture](https://cloud.githubusercontent.com/assets/15955186/21077371/5f6d4828-bf84-11e6-8f0c-e17c6c236e43.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15955186/21077372/5f88cef4-bf84-11e6-8975-46c301d6795b.PNG)
![capture3](https://cloud.githubusercontent.com/assets/15955186/21077373/5f9b96ec-bf84-11e6-9fb5-1974e09edd74.PNG)

**Comment by Noisyfox** [comment]
Have you tried to switch to global mode instead of PAC?

**Comment by tradstone** [comment]
@Noisyfox Yes, the issue would be gone once I switch to global mode.

**Comment by tradstone** [comment]
@wongsyrone Itsn't there a way to use SS in PAC mode with lighter/less frequent CPU consumption? I don't want to re-route all of my data traffics through SS.

**Comment by tradstone** [comment]
@Noisyfox @wongsyrone This is really annoying, and it happens in your latest version. 
 I don't want to re-route all of my data traffics through SS, so most of the time I'm in PAC mode.
