### ISSUE TITLE
win10_14955无法设置代理

### ISSUE THREAD

**Issue by WuXuBaiYang** [shadowsocks/shadowsocks-windows#881]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
所有版本

### Environment(Operating system, .NET Framework, etc)
WIN10_14955.RS_prerelease.161020-1700

### Steps you have tried
系统盘的文档文件夹下无法使用

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
有无尝试便携版本？在Shadowsocks.exe 所在目录新建一个名为 shadowsocks_portable_mode.txt 的空文件。

**Comment by fzhw88** [comment]
如果只是不能修改系统代理这个问题，那么应该是放哪里都无法修改。

**Comment by Noisyfox** [comment]
"无法使用"究竟是什么问题？有没有日志或者弹窗报错的截图？

**Comment by WuXuBaiYang** [comment]
我又测试了一下，好像跟位置无关，放在哪里都无法代理，就只是无法代理，并没有报错什么的

**Comment by Noisyfox** [comment]
#814

**Comment by Noisyfox** [comment]
Try the latest pre-release version.
