### ISSUE TITLE
[ ERROR ] Windows 10 Pro Insider Preview Build 14946

### ISSUE THREAD

**Issue by theonorchina** [shadowsocks/shadowsocks-windows#882]
Version : 3.3.4 & 3.3.5

Operating System: Win10 / Net.Framework 4.6

First Step ：Try to replace the shadowsocks.exe (coz i'm lazy...)but seems i can't use the old configuration files ,crash report shows while opening up "shadowsocks.exe" as below.

<img width="381" alt="default" src="https://cloud.githubusercontent.com/assets/23441288/20250068/403d3112-aa43-11e6-889e-d003954a438d.PNG">

Second Step ：Try to use the orginal client , and it can be opened up to get into server settings,fill out all fields needed,then crash report shows again while clicking "enable" as below.

<img width="382" alt="2" src="https://cloud.githubusercontent.com/assets/23441288/20250101/067889f8-aa44-11e6-893d-2beec82f8d99.PNG">

<img width="379" alt="3" src="https://cloud.githubusercontent.com/assets/23441288/20250103/08d7ac42-aa44-11e6-8075-04560b1003ed.PNG">

**Comment by wongsyrone** [comment]
#814

**Comment by Noisyfox** [comment]
Try the latest pre-release version.
