### ISSUE TITLE
关于gui-config.json配置文件在不同电脑上同步的问题

### ISSUE THREAD

**Issue by yxest** [shadowsocks/shadowsocks-windows#883]
我把客户端放在OneDrive中，因此配置文件被同步。我有一个普通分辨率的笔记本和一个Surface，当时两台电脑的分辨率差距太大。而显示日志窗口的属性被保存在此配置文件中，两个被同步了。导致要么在一台电脑上巨大，要么在另一台电脑上很小。能否考虑加入配置文件的重命名，并选择加载不同的配置文件

**Comment by chenshaoju** [comment]
请将Shadowsocks工作在便携模式，然后在OneDrive的设置中点击账户选项卡，点击选择文件夹，然后取消Shadowsocks.exe所在目录下的temp目录即可。

**Comment by Noisyfox** [comment]
这个。。。日志窗口的大小这个是在主配置文件的。我觉得移到temp里面比较好

**Comment by chenshaoju** [comment]
我看错了。。。以为是他在说他的日志文件很大。。。

**Comment by Noisyfox** [comment]
This should be fixed via b63bab0d1a0a34f4c2de4a41da87da72c5c576f9
