### ISSUE TITLE
请问怎样解决断线问题？

### ISSUE THREAD

**Issue by shenyunhuan** [shadowsocks/shadowsocks-windows#884]
每天使用的时候总会有那么几次断线的问题，需要重启ss才能解决，确定不是ss商家的原因，拿我同学不同商家的也会出现，家里移动和公司联通，都有这个问题。（版本是3.3.5，设置启动检测更新）。

**Comment by chenshaoju** [comment]
以管理员身份启动命令提示符，复制并粘贴：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
然后重新启动计算机，再观察一下。另外，如果你有使用迅雷，请升级到最新版本。
