### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by dimzon** [shadowsocks/shadowsocks-windows#885]
I propose to run HttpProxy (for example privoxy) at server side (at same host ss-server is running). This allows centralized ad-blocking and routing rules (for example redirect *.i2p to i2p-router and *.onion to tor). 
In this deployment scenario shadowsocks can be used as socks4/5 server itself and as encrypted tunnel to http-proxy.

Every time proxy-client (browser) connects to shadowsocks-client (ss-local) it can distinguish protocol based on first byte.
If byte==5 serve as socks5. if byte==4 serve as socks4, otherwise tunnel  data (just using it's own socks capabilities) to server-side 127.0.0.1:8118 (can be taken from configuration)

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues

**Comment by dimzon** [comment]
this is ss-local proposal, it doesnt affect ss-server

**Comment by Noisyfox** [comment]
As you said you are talking about server side feature and this repo is pure client.

**Comment by dimzon** [comment]
I'm really confused. Is my English so bad so nobody understand my proposal. 
This proposal require such CLIENT software changes: to add additional logic when handling BROWSER-to-SHADOWSOCKSCLIENT iteraction:
- add optional client configuration parameter: remoteHttpProxyPort
- analyze first bytes from browser-to-ssclient handshake
- if first byte==5 proceed as Socks5 server (as is)
- (optional for old browsers)  if first byte==4 proceed as Socks4a server
- otherwise establish tunnel ```[browser]<-->[ssclient]<-->[ssserver]<-->[127.0.0.1:remoteHttpProxyPort]```

This proposal doesn't require SERVER software changes, just install any preferred HTTP proxy onto same host and make it listen onto loopback address

**Comment by breakwa11** [comment]
Those two can not easy to work together. It's not a good idea
这两一起跑会爆炸，为啥要跑一个端口

**Comment by Noisyfox** [comment]
首先这个客户端本身在同一个端口就支持http代理和socks5代理复用。
而且协议中并没有区分流量来源是http代理还是socks5代理的功能。
