### ISSUE TITLE
on my windows,the version 3.3.5 can not start,be crash

### ISSUE THREAD

**Issue by liangzhineng** [shadowsocks/shadowsocks-windows#886]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	3.3.5.0
  问题签名 03:	58201258
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	4ba1da6f
  问题签名 07:	11cd
  问题签名 08:	89
  问题签名 09:	System.TypeLoadException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by liangzhineng** [comment]
I tried the historical version one by one,the version 3.3.2 is normal

**Comment by chenshaoju** [comment]
Please Install/Update .NET Framework 4.6.2
https://www.microsoft.com/en-us/download/details.aspx?id=53344
