### ISSUE TITLE
能否使用一个快捷键在全局和pac之间来回切换，而不是各自设置一个？

### ISSUE THREAD

**Issue by Gigglelife** [shadowsocks/shadowsocks-windows#887]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
可以

**Comment by wongsyrone** [comment]
#888
