### ISSUE TITLE
Exception Type: UnauthorizedAccessException

### ISSUE THREAD

**Issue by oososo** [shadowsocks/shadowsocks-windows#889]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
newest

### Environment(Operating system, .NET Framework, etc)
win10

### Steps you have tried
install fiddler 4 then uninstall

### Config and error log in detail (with all sensitive info masked)
at system.windows.forms.NativeWindo.Callback
at shadowsocks.Model.Configuration.Save
at Shadowsocks.View.MenuViewController.EnableItem_Click

**Comment by wongsyrone** [comment]
这个一般是权限不够，尝试管理员运行或者使用便携模式。另外错误日志不全，没法判断。
