### ISSUE TITLE
Shadowsocks non-UI Error: System.InvalidOperationException: Collection was modified;

### ISSUE THREAD

**Issue by dengshaojiang** [shadowsocks/shadowsocks-windows#890]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

![shadows-error](https://cloud.githubusercontent.com/assets/11343384/20348010/8d2b8012-ac3e-11e6-97f3-a6f7e1f15e06.png)

### Version(release version or AppVeyor link)
3.3.5

### Environment(Operating system, .NET Framework, etc)
OS: Windows 7 64bit

.Net version: 
![version](https://cloud.githubusercontent.com/assets/11343384/20347897/1638e31e-ac3e-11e6-9e87-e33e41751270.png)

### Config and error log in detail (with all sensitive info masked)

    {
      "Calculations": {
        "AverageLatency": 0.0,
        "MinLatency": 0.0,
        "MaxLatency": 0.0,
        "AverageInboundSpeed": 0.0,
        "MinInboundSpeed": 0.0,
        "MaxInboundSpeed": 0.0,
        "AverageOutboundSpeed": 0.0,
        "MinOutboundSpeed": 0.0,
        "MaxOutboundSpeed": 0.0,
        "AverageResponse": 0.0,
        "MinResponse": 0.0,
        "MaxResponse": 0.0,
        "PackageLoss": 0.0
      },
      "StatisticsEnabled": true,
      "ByHourOfDay": true,
      "Ping": false,
      "ChoiceKeptMinutes": 10,
      "DataCollectionMinutes": 10,
      "RepeatTimesNum": 4
    }

**Comment by Noisyfox** [comment]
请禁用统计功能

**Comment by celeron533** [comment]
#906
