### ISSUE TITLE
非预期错误

### ISSUE THREAD

**Issue by lesteryou** [shadowsocks/shadowsocks-windows#891]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

version:3.3.5
### Environment(Operating system, .NET Framework, etc)
windows 7 .NET Framework 4.6.2

### Steps you have tried

正常打开，异常报错
### What did you expect to see?

...
### What did you see instead?
![2016-11-17_124222](https://cloud.githubusercontent.com/assets/23516202/20377099/7ecc2c36-acc7-11e6-88ab-d057970efcfd.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
服务器地址填写有问题，请复查。

**Comment by wongsyrone** [comment]
最简单的办法就是删掉旧配置文件，在程序里面手动设置。

**Comment by Trim21** [comment]
我刚刚遇到了一样的问题,看配置文件,是在服务器地址后面多复制了一个'/'
