### ISSUE TITLE
托盘不显示图标！

### ISSUE THREAD

**Issue by huibiny** [shadowsocks/shadowsocks-windows#892]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.5

### Environment(Operating system, .NET Framework, etc)
windows7 旗舰版   .NET Framework 4.0.30319

### Steps you have tried
双击SHADOWSOCKS.exe打开没有反应。右下角也没有图标。

### What did you expect to see?
右下角托盘出现图标。

### What did you see instead?
右下角没有出现图标

### Config and error log in detail (with all sensitive info masked)

**Comment by breakwa11** [comment]
update your .NET Framework to 4.6.2
