### ISSUE TITLE
程序运行时修改自定义规则 user-rule.txt 导致程序崩溃

### ISSUE THREAD

**Issue by garywzh** [shadowsocks/shadowsocks-windows#894]
### Version(release version or AppVeyor link)
3.3.5

### Environment(Operating system, .NET Framework, etc)
win7 .NET Framework 4.6.2

### Steps you have tried
1.正常使用程序
2.修改user-rule.txt ，保存

### What did you expect to see?
正常运行

### What did you see instead?
![shadowsockswinbug](https://cloud.githubusercontent.com/assets/15074069/20418318/505bdb88-ad87-11e6-8163-e0067344343d.PNG)

**Comment by wongsyrone** [comment]
我这里无法复现，确保不是被其他扫描的软件临时锁定了

**Comment by garywzh** [comment]
刚才试了下用记事本确实不会出毛病。

用 VS code 连续执行两次修改保存操作就会崩溃，可能是编辑器的问题

**Comment by wongsyrone** [comment]
也可以试试 Notepad++

**Comment by Gigglelife** [comment]
@wongsyrone  我也有这个问题 SublimeText3，从来没想过会是编辑器的问题，所以添加规则都是先退掉ss，再修改，在启动！

**Comment by wongsyrone** [comment]
这个猜测可能与编辑器打开文件后不关闭文件流有关，导致SS无法再次打开文件。有些编辑器可能读取完文件之后关闭文件，在自己的缓存中处理，等到保存的时候再写入修改。

**Comment by garywzh** [comment]
崩溃发生在点击保存的一瞬间

**Comment by 772807886** [comment]
在我电脑上，Windows 10自带的记事本也同样有较大几率复现。

**Comment by 772807886** [comment]
这个问题应该是因为文件在保存时，记事本软件会先独占文件进行安全写入，而在写入完毕的一瞬间SS获得CPU并监测到文件变化，立即开始读取，此时记事本软件还没来得及解除文件锁，从而导致问题的发生。

我尝试在读取的时候抓取异常，读取失败的时候重新读取尝试，经过试验，这个办法在我电脑上可以解决问题。在两次尝试都失败时*记录日志*而不是出现异常退出。

大家可以试一试这样能不能解决问题。

**Comment by wongsyrone** [comment]
可以试一下https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.215/job/olk8pptpdma9o1dt/artifacts
