### ISSUE TITLE
Enable System Proxy doesn't work on Windows 10 Build 14965

### ISSUE THREAD

**Issue by Kyandi** [shadowsocks/shadowsocks-windows#896]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.5

### Environment(Operating system, .NET Framework, etc)
Windows 10 Pro Insider Preview Build 14965.rs_prerelease.161104-1700

### Steps you have tried
Start proxy by myself
Script address set: http://127.0.0.1:1080/pac
Proxy Server set: 127.0.0.1:1080
but not good.

### What did you expect to see?
can start system proxy

### What did you see instead?
Successfully opened the proxy but did not

### Config and error log in detail (with all sensitive info masked)
Not required

**Comment by wongsyrone** [comment]
#814

**Comment by Noisyfox** [comment]
Try the latest pre-release version.
