### ISSUE TITLE
是不是现在的影梭还不可以支持win10应用的翻墙？

### ISSUE THREAD

**Issue by Quiet95scholar** [shadowsocks/shadowsocks-windows#897]
请仔细阅读维基，尤其是https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting。
请在提交您的问题之前回答这些问题。 谢谢！

###版本（发布版本或AppVeyor链接）
3.3.5

###环境（操作系统，.NET Framework等）
windows10 14393.447

###我的问题：
是不是现在的影梭还不可以支持win10应用的翻墙？
比如说win10版的outlook应用无法同步google邮箱
![outlook1](https://cloud.githubusercontent.com/assets/20389206/20456091/fcc336d4-aea7-11e6-8be6-fd7ccaa44e8b.png)

![image](https://cloud.githubusercontent.com/assets/20389206/20456090/f095b9b8-aea7-11e6-8b52-f330f0d91ffd.png)

**Comment by Noisyfox** [comment]
设置系统代理以后win10应用就会走代理的呀

**Comment by wongsyrone** [comment]
Run as Admin
```
netsh
winhttp
import proxy source=ie
```

**Comment by Ikamusumi** [comment]
uwp应用由于安全限制，需要手动添加代理例外

参考:
> http://blog.csdn.net/wtwsgs/article/details/51333912

另外，[Fiddler4](http://www.telerik.com/fiddler) 中提供了Tools->Win8 Loopback exemptions 的工具，可以快速添加uwp应用代理例外。

**Comment by JohnYinlubin** [comment]
我的可以啊

**Comment by Quiet95scholar** [comment]
@JohnYinlubin 你是怎么设置的？

**Comment by Quiet95scholar** [comment]
@JohnYinlubin 分享一下你的经验呗

**Comment by Quiet95scholar** [comment]
`@echo OFF
echo 清楚所有程序 && CheckNetIsolation.exe LoopbackExempt -c 1>nul
pause
cd %USERPROFILE%\AppData\Local\Packages
echo 开始添加程序
for /d %%i in (*) do  echo 添加程序%%i && CheckNetIsolation.exe LoopbackExempt -a -n = %%i 1>nul
pause`

**Comment by Quiet95scholar** [comment]
我根据 @Ikamusumi 提供的链接还有网上搜到的教程，写了一个批处理程序
`@echo OFF`
 `echo 清楚所有程序 && CheckNetIsolation.exe LoopbackExempt -c 1>nul` 
`cd %USERPROFILE%\AppData\Local\Packages` 
`echo 开始添加程序 for /d %%i in (*) do` 
`echo 添加程序%%i && CheckNetIsolation.exe LoopbackExempt -a -n = %%i 1>nul` 
`pause`

**Comment by JohnYinlubin** [comment]
不能评论了

**Comment by JohnYinlubin** [comment]
？我看错了，我应用没试过，不好意思，只能网页暂时😭

**Comment by chenshaoju** [comment]
Note: https://github.com/shadowsocks/shadowsocks-windows/issues/1963#issuecomment-413378963

run these script in powershell with administrator:
以管理员身份启动PowerShell后运行下列命令：
```
foreach($f in Get-ChildItem $env:LOCALAPPDATA\Packages) {CheckNetIsolation.exe LoopbackExempt -a "-n=$($f.Name)"}
```

if only need few apps:
如果只需要少量应用：
```
CheckNetIsolation.exe LoopbackExempt –a –n=<App Directory>
```
change <App Directory> to the directory name in %LOCALAPPDATA%\Packages directory with your app name.
将 <App Directory> 替换成出现在 %LOCALAPPDATA%\Packages 目录中的应用目录名即可。

**Comment by kurikomoe** [comment]
fiddler 里面自带了一个 EnableLoopback.exe 的程序可以更方便的运行

[fiddler](https://www.telerik.com/fiddler)

[咱自己提取的，自行验证签名是否是 telerik 家的](https://file.io/yYHaqj)

**Comment by Hipd** [comment]
loopback 的办法好像对 UWP『邮件和日历』中的 Gmail 账号无效

**Comment by zzhhbyt1** [comment]
@kurikomoe 我试过的 Fiddler 自己的独立版程序 [Windows 8 AppContainer Loopback Utility](https://www.telerik.com/fiddler/add-ons) 反正至少邮件里面添加 Gmail 是不行的。
脚本则可以。
我今天在台式机上再试试看。

**Comment by zzhhbyt1** [comment]
@Hipd 就是 chenshaoju 说的[这个](https://github.com/shadowsocks/shadowsocks-windows/issues/897#issuecomment-413400908)啊

**Comment by YolineWu** [comment]
@zzhhbyt1 我下载了[Fiddler](https://www.telerik.com/fiddler)，使用下图那里的功能是可以添加google邮箱的
![_20180905065533](https://user-images.githubusercontent.com/37880389/45061884-f7b41980-b0d8-11e8-96cb-daa00a3fe195.png)

**Comment by zzhhbyt1** [comment]
感谢提醒去，我之前按照一些博客里说的下载的那个单独出的组件，是不行的。这个今后我试试。（主要是不想装很多东西）

**Comment by zzhhbyt1** [comment]
> 
> 
> @zzhhbyt1 我的也是windows10，我下载了[Fiddler](https://www.telerik.com/fiddler)，使用下图那里的功能是可以添加google邮箱的
> ![_20180905065533](https://user-images.githubusercontent.com/37880389/45061884-f7b41980-b0d8-11e8-96cb-daa00a3fe195.png)

我今天试了一下用`fiddler`自带的`wincofig`，对于google uwp 似乎还是可以的，只要重启 app 就能用上 ss 了，但是 mail 似乎还是不行。
如果您用这个软件调成了，麻烦您赐教一下。
目前我只有用`CheckNetIsolation.exe`的方法才能调好 Gmail 在 Mail 里的同步和推送。

**Comment by kid1412621** [comment]
> @YolineWu 我今天试了一下用 Fiddler 自带的 WinConfig，对于 Google UWP 似乎还是可以的，只要重启 app 就能用上 ss 了，但是 Mail 似乎还是不行。
> 如果您用这个软件调成了，麻烦您赐教一下。
> 目前我只有用 `CheckNetIsolation.exe` 的方法才能调好 Gmail 在 Mail 里的同步和推送。
> 我怀疑是 WinConfig 只能添加有 AppContainer 的条目的缘故， chenshaoju 的批处理命令能够一起添加所有的。
> 您可以试试两种方法后 `CheckNetIsolation.exe LoopbackExempt –s`，条目数量是批处理命令多的，至于多了啥，是有用的后台进程还是删除的 UWP 留了空文件夹导致批处理多算进去了，我就没再琢磨了，目前用着还挺好的。

@zzhhbyt1 用 Fiddler 的方式本质上就是 `CheckNetIsolation.exe` ,但我以前成功了, 今天弄了几个小时都没搞好, 好奇怪

**Comment by RudeTheJack** [comment]
> @Hipd 就是 chenshaoju 说的[这个](https://github.com/shadowsocks/shadowsocks-windows/issues/897#issuecomment-413400908)啊

![QQ图片20191109012629](https://user-images.githubusercontent.com/27954602/68497634-fa3b7180-028f-11ea-961f-c0412b8f234c.png)
大佬，请问AppContainer Loopback Exemption Utility打开之后出现图里这个情况该怎么解决呢，win10自带邮件UWP的displayname是哪个啊，找了半天都找不到呀，谢谢

**Comment by escape0707** [comment]
@RudeTheJack 我现在在用v2ray和Linux，不能帮你测试了。但是我还是回复一下，我是用chenshaoju发的脚本，别的软件我试了不管用。

**Comment by RudeTheJack** [comment]
> @RudeTheJack 我现在在用v2ray和Linux，不能帮你测试了。但是我还是回复一下，我是用chenshaoju发的脚本，别的软件我试了不管用。

谢谢，用其他软件都没用，果然只能用chenshaoju大佬发的这个方法，谢谢了
