### ISSUE TITLE
UnauthorizaitonAccess Exception 

### ISSUE THREAD

**Issue by suihonggang** [shadowsocks/shadowsocks-windows#900]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.5

### Environment(Operating system, .NET Framework, etc)
Win 10 64Bit Professional .Net Framework 6.4

### Steps you have tried
Copy file to below path:
C:\Program Files (x86)\Shadowsocks-3.3.5

### What did you see instead?
UnauthorizaitonAccess Exception 
![proxy](https://cloud.githubusercontent.com/assets/23631337/20478971/4c8e20aa-b017-11e6-81bb-ec769692370e.png)

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
这个一般是权限不够

**Comment by suihonggang** [comment]
怎么可以解决呢？ 有具体的方法吗

谢谢

**Comment by wongsyrone** [comment]
管理员运行或者放到其他盘里面应该就可以了

**Comment by Noisyfox** [comment]
windows 不允许没有管理员全写的程序读写program files，请将ss放到其它目录中
