### ISSUE TITLE
非预期错误，Shadowsocks将退出。

### ISSUE THREAD

**Issue by LiHaoGit** [shadowsocks/shadowsocks-windows#901]
### Windows 10 
---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。

   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)

   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()

   在 System.Collections.Generic.List`1.Enumerator.MoveNext()

   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()

   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   在 Shadowsocks.Model.StatisticsRecord..ctor(String identifier, ICollection`1 inboundSpeedRecords, ICollection`1 outboundSpeedRecords, ICollection`1 latencyRecords)

   在 Shadowsocks.Controller.AvailabilityStatistics.UpdateRecords()

   在 Shadowsocks.Controller.AvailabilityStatistics.Run(Object _)

   在 System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)

   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.TimerQueueTimer.CallCallback()

   在 System.Threading.TimerQueueTimer.Fire()

   在 System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)

   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   在 System.Threading.ThreadPoolWorkQueue.Dispatch()

   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Noisyfox** [comment]
#890 
请暂时不要用统计功能
