### ISSUE TITLE
Feature Request: Access Control on Local Socks5/HTTP Proxy.

### ISSUE THREAD

**Issue by RadarNyan** [shadowsocks/shadowsocks-windows#902]
Sometimes I need to expose the local proxy to LAN (so I can use it from a Virtual Machine with bridged network adapter) but I don't really want everyone in the same LAN being able to use my proxy.

Can you add a separate access control to the local proxy, even better to LAN interface only (w/o auth on 127.0.0.1:1080 & w/ auth on 192.168.1.100:1080)

**Comment by wongsyrone** [comment]
The use case doesn't look very common IMO.

**Comment by 772807886** [comment]
我也想过如果可以的话，给局域网的代理增加账号密码控制的功能。

**Comment by Noisyfox** [comment]
privoxy不支持http代理认证
而且ie代理设置貌似不能设置密码？
可以做基于ip的认证

**Comment by PINK-FL0YD** [comment]
Privoxy的端口会每次重启软件后变化

**Comment by celeron533** [comment]
可以在privoxy和浏览器之间再加一层代理。然后将这个中间层代理设置各种访问控制

**Comment by Noisyfox** [comment]
变化就变化咯，反正又不会直接用privoxy的端口

**Comment by Noisyfox** [comment]
@celeron533 于是就变成了自己写一套http协议解析然后再 从privoxy那里过一次。。。诶我不想说啥了

**Comment by celeron533** [comment]
@Noisyfox 也不是自己写一套啊，nginx，squid3等作为前级代理服务器，不但能加上代理验证，还能添加本地缓存、站点访问控制，pac在代理处直接消化等功能。

正如原po所述，在局域网中有多人使用代理。比方说先后有5人同时访问某个站点，虽然主流浏览器都有本地缓存功能，但是着5个人还是要分别缓存，现在在代理上已经有一套短期内可用的缓存，可以加快访问速度并减少出口流量。
有的代理支持使用pac，这样的话，http请求来了以后，可以判定是将这个请求转发到privoxy或是走直连。

甚至privoxy都可以和ss主体分离出来。ss里可以设置“切换代理时运行以下程序”，然后有几个内置参数比如IP，端口等用于直接启动外部代理或交给批处理文件进行后续操作。

**Comment by ddcouples** [comment]
@celeron533  nginx 代理 privoxy服务没有通，是什么原因，直连privoxy是可以的！但是proxy_pass http://localhost:1090;  却一直失败，不能联通
