### ISSUE TITLE
为什么pac文件添加网址无效？

### ISSUE THREAD

**Issue by AirmaZ** [shadowsocks/shadowsocks-windows#904]
![qq 20161123141145](https://cloud.githubusercontent.com/assets/18375475/20552518/e03c9352-b186-11e6-9791-1bad666e2849.jpg)
比如说我把百度加入pac，在百度搜索ip还是本地的ip。

**Comment by Noisyfox** [comment]
试试看改user-rule.txt

**Comment by AirmaZ** [comment]
@Noisyfox 可是我的目录下没有user-rule.txt文件啊，只有
+ gui-config.json 
+ pac.txt
+ shadowsocks.exe
+ statistics-config.json
这几个文件

**Comment by chenshaoju** [comment]
右击托盘区的纸飞机图标，选择PAC，点击 编辑 GFWList 的用户规则。

**Comment by 772807886** [comment]
我这里也测试了，把百度加到user-rule里无效，chrome里远程ip不变。
但是我将github加到user-rule里是有效的，可以看到Chrome里远程ip已经变成本地ss的了。
并不知道原理。。
![qq 20161126161513](https://cloud.githubusercontent.com/assets/10294977/20639044/8d9027e4-b3f3-11e6-8232-4d4d4a294931.png)

**Comment by wongsyrone** [comment]
百度可以试试
```
@@|http://baidu.com
```
其他的反馈到GFWList

**Comment by AirmaZ** [comment]
@772807886 
我已经解决了，原因是pac文件本身包含了baidu.com的规则，你在pac.txt中搜索就知道。把默认规则删了就好了。

**Comment by 772807886** [comment]
原来如此。。规则冲突了。。。
