### ISSUE TITLE
Windows 8.1 Pro X64 report error time out forever 

### ISSUE THREAD

**Issue by imxieke** [shadowsocks/shadowsocks-windows#907]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
Windows 8.1 Pro X64  Shadowsocks 3.3.5 

### Environment(Operating system, .NET Framework, etc)

Windows 8.1 Pro X64 .Net FrameWork 4.6.2  (System just install success for a moment)

### Steps you have tried
reboot, 
change version to latest
other shadowsocks account 
test in other computer(Windows 7 And ubuntu 16.04), work is normal

### Config and error log in detail (with all sensitive info masked)
```
[2016-11-26 21:36:39] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2016-11-26 21:36:42] us01.ssn6.net:20088 timed out
```
##### default config , i don't modify it !

**Comment by breakwa11** [comment]
防火墙

**Comment by imxieke** [comment]
@breakwa11 请问你是遇到过么？  我试了下 不行哎 我将防火墙关闭了  还总是超时  我可以确定的是SS的确可以用 因为我在另一台Windows7 Pro X64  试了下 可以 但是我这台不可以 刚刚安装的系统。。。

**Comment by 772807886** [comment]
你在这台电脑上尝试直接`ping us01.ssn6.net`看看能不能ping通？

**Comment by imxieke** [comment]
@772807886 可以的 

不知道是不是环境问题  我看到另一台电脑安装了 `.net Framework 3.5 3.0 2.0 `三个版本 我将
 `防火墙关闭`之后  不行,  我又安装了 VC运行库合集  还有`.net Framework 3.5 3.0 2.0` 三个版本 重启就好了

**Comment by rocren3** [comment]
楼主及楼上各位，我从上周开始，家中win81和win10系统机器用ss均受阻。ping服务器地址延迟低于60ms，丢包率零，但一挂ss就基本上全time out，油管谷歌都没法用。但同一路由下，用安卓手机挂ss体验正常，YouTube不卡。已经尝试还原台机系统，重启路由器，重启ss服务器，更换ss服务器端口和密码，均无解。奇怪的是，我购置的另一台ss帐号可用。有哪位知道是什么缘故吗？ 在单位和另外居所使用均不受影响。

**Comment by celeron533** [comment]
最新版的shadowsocks-win使用了 framework 4.6.2

**Comment by rocren3** [comment]
是的，这个已经试过，无果。
这两天又发现新情况：在家里手机的昨天也挂了，用移动流量OK；而今晨移动流量也挂了，但在单位的瘟8.1上OK。。。
我现在不能确定是本地运营商的拦截问题还是ss服务器挑运营商。本来打算换联通的，现在手机流量也不好使了，搞得我不确定是不是家里电信的主动拦截造成。

**Comment by celeron533** [comment]
@rocren3 看样子你的机器被关照了

**Comment by rocren3** [comment]
现在不清楚是如何被关照的。直接ping都没问题，但挂代理就不行。回去重装一下ss试试。。。

**Comment by chengzijiazu** [comment]
我跟你的情况一样，ios 端PC 都挂了，ping可以，但是就是连不上！！！

**Comment by chengzijiazu** [comment]
@rocren3 你的问题解决了吗。我的账号刚买不到一个月，就这样挂了很不爽啊，已经解决的话求分享啊！
