### ISSUE TITLE
Win 10 1607这个版本无法自动设置代理

### ISSUE THREAD

**Issue by 023yangbo** [shadowsocks/shadowsocks-windows#909]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.5
### Environment(Operating system, .NET Framework, etc)
Windows 10 1607 14965.1001
就是这个版本的win 10无法自动设置IE代理了，必须手动更改

**Comment by wongsyrone** [comment]
#814 

看到这个头像我还以为是tomato那个佐须之男
