### ISSUE TITLE
多实例 端口冲突

### ISSUE THREAD

**Issue by chenTest2013** [shadowsocks/shadowsocks-windows#910]
不是ss的端口，而是ss的privoxy端口冲突
listen-address 127.0.0.1:**_8123_**
show-on-task-bar 0
activity-animation 0
forward-socks5 / 127.0.0.1:1084 .
hide-console
这个8123，每次我改后，总是被自动改为8123，无法改为其他的值，导致启动多个ss提示冲突。
我的每个ss在不同文件夹，监听不同端口，这个shadowsocks_portable_mode.txt也加上了。
各位遇到这种情况了吗？

**Comment by Noisyfox** [comment]
你用的什么版本的ss

**Comment by wongsyrone** [comment]
我测试没问题，你肯定shadowsocks_portable_mode.txt变成了shadowsocks_portable_mode.txt.txt了

**Comment by Noisyfox** [comment]
理论上就算不是便携模式这个privoxy的端口也不会冲突的

**Comment by wongsyrone** [comment]
log如果有贴出来

**Comment by chenTest2013** [comment]
@Noisyfox 用的是最新版3.3.5的

**Comment by chenTest2013** [comment]
@wongsyrone 我扩展名显示了，没有多余的txt

**Comment by chenTest2013** [comment]
@wongsyrone 刚才又测试下，端口还是会变为8123，但是没有报错了，不知啥情况。日志都是正常的日志

**Comment by chenTest2013** [comment]
刚重启复现了问题：
错误日志1：
controller stopped
[2016-11-27 20:22:27] os suspend
[2016-11-27 20:28:12] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1084
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
错误日志2：controller stopped
[2016-11-27 20:22:28] os suspend
[2016-11-27 20:28:12] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:1083
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, Co

nnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-11-27 20:28:15] System.ComponentModel.Win32Exception (0x80004005): 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。
   在 System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   在 System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   在 System.Diagnostics.Process.get_MainModule()
   在 Shadowsocks.Controller.PrivoxyRunner.IsChildProcess(Process process)
[2016-11-27 20:28:15] Shadowsocks started
[2016-11-27 20:28:19] no enough statistics data or all factors in calculations are 0
[2016-11-27 20:29:04] System.InvalidOperationException: 进程已退出，因此无法获得所请求的信息。
   在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.get_MainWindowHandle()
   在 System.Diagnostics.Process.CloseMainWindow()
   在 Shadowsocks.Controller.PrivoxyRunner.KillProcess(Process p)
![Uploading 2.PNG…]()

**Comment by chenTest2013** [comment]
为啥无法上传图片

**Comment by Noisyfox** [comment]
要等图片上传完才能提交comment

**Comment by Noisyfox** [comment]
一种可能性是你两个ss实例同时启动，此时两者的privoxy都没有在运行，所以两个ss都检测到8123端口是可用的然后导致随后privoxy的端口冲突。请尝试一下手动启动第二个ss实例看看是不是不会再报错。

**Comment by chenTest2013** [comment]
测试是的，一个先启动，一个后启动。不报错了

**Comment by Noisyfox** [comment]
这个是一个bug，以后应该会修复

**Comment by wongsyrone** [comment]
你是怎样同时启动两个SS的呢？

**Comment by chenTest2013** [comment]
@wongsyrone  都加入开机启动项，启动启动时会同时启动

**Comment by chenTest2013** [comment]
感谢
