### ISSUE TITLE
Shadowsocks已停止工作

### ISSUE THREAD

**Issue by Yuenggpong** [shadowsocks/shadowsocks-windows#912]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	3.3.5.0
  问题签名 03:	58201258
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	53b50a71
  问题签名 07:	1205
  问题签名 08:	89
  问题签名 09:	System.TypeLoadException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/886
