### ISSUE TITLE
希望增加快捷键自动注册选项

### ISSUE THREAD

**Issue by voq** [shadowsocks/shadowsocks-windows#913]
看了相关Issues知道是有意设计成手动注册的（好像是避免冲突），但是很不方便。

希望增加自动注册热键选项，默认关闭，给用户以选择空间。

谢谢

对应Pull request #1130

**Comment by wongsyrone** [comment]
这个当时是我设计的，可能不合理，但是有一点我很确认，不要对用户做过多假设。

**Comment by coooleon** [comment]
每个人的需求不同，我觉得可以做一个是否自动注册快捷键的开关按钮，默认是关闭状态，这样就皆大欢喜了。

**Comment by reaCodes** [comment]
支持 @coooleon 给出的解决办法，这样照顾到了绝大部分人的需求（嫌程序臃肿的同学除外😁），我个人也很需要快捷键自动注册，不然每次重新启动就要手动启动一下快捷键，很不方便。因为经常需要访问国外的网站，需要在PAC和全局模式间切换，以加速国外网站访问。

**Comment by reaCodes** [comment]
支持 @coooleon 给出的解决办法，这样照顾到了绝大部分人的需求（嫌程序臃肿的同学除外😁），我个人也很需要快捷键自动注册，不然每次重新启动就要手动启动一下快捷键，很不方便。因为经常需要访问国外的网站，需要在PAC和全局模式间切换，以加速国外网站访问。😁

**Comment by dawnfantasy** [comment]
默认不设置快捷键。如果有需求的就设置一个，而且软件判断一下，如果有设置就自动注册。~皆大欢喜？

**Comment by Choutouketsu** [comment]
确实啊，尤其是PAC模式和全局模式切换，还是快捷键来得方便，可以让需要的人设置自动注册嘛，@wongsyrone相当喜欢这个软件，实在不行可以设个Pro版本，需要的可以买嘛

**Comment by juerte** [comment]
我把切换pac和全局模式绑定了一个全局热键，之后通过鼠标手势软件绑定到鼠标动作上，那么问题来了，我一重启ss或者重启电脑这个热键就没用了，我现在唯一的解决办法是，从不关机不关ss..............顺带把windows更新也关了，那货天天催我重启更新

**Comment by reaCodes** [comment]
@juerte 你这太极端了，重启了注册热键也就是动动鼠标的问题。也就是说有自动注册功能最好，没有影响也不大。

**Comment by juerte** [comment]
@reaCodes 也不是说极端吧，我知道很多人几乎都不关机的，而且windows更新越更越多问题（例如最近的游戏摇杆问题），很多人也关闭的，想起来才开一下更新。最多只能算顺带解决这个全局热键的问题吧..........

**Comment by keyrratuff** [comment]
非常需要pac和全局的自动注册热键！！

**Comment by ColdZoo** [comment]
希望能有自动注册的功能，或者能否给个源码位置，我们自行修改？@wongsyrone

**Comment by JonasGao** [comment]
@ColdZoo  https://github.com/shadowsocks/shadowsocks-windows/pull/1130 on the way
