### ISSUE TITLE
可以加入kcptun的配置吗?

### ISSUE THREAD

**Issue by dongamp1990** [shadowsocks/shadowsocks-windows#914]
可以加入kcptun的配置吗。android端是支持了。谢谢

**Comment by chenshaoju** [comment]
你好，kcptun已经有Windows的客户端了，在SS中加入过多第三方功能容易导致不稳定。

Android版本和Windows版本并非同一人控制，决策上也是隔离的。

**Comment by dongamp1990** [comment]
了解了解，感谢回答。
