### ISSUE TITLE
使用shadowsocks访问外网的速度与什么有关？

### ISSUE THREAD

**Issue by mycwcgr** [shadowsocks/shadowsocks-windows#916]
我申请了一个VPS 768M内存+1CPU+SSD，基本上一个人用，使用shadowsocks Windows client，我总觉得访问外网速度不够快。

请问shadowsocks服务的访问速度的主要影响因素有哪些？

1. SSD Vs 普通硬盘
   是不是基本上没有什么影响？

2. CPU
   1个是不是够了？

3. 768M内存
   将768M提高到1024M，访问速度是不是更快？

4. 客户端与服务器所在地之间的连接速度
   这是不是一个主要因素？超过了1、2、3是影响？

https://www.dropbox.com/s/ewv1mflotngsamm/SS.PNG?dl=0

**Comment by celeron533** [comment]
256内存就能跑的很顺利了

最最关键的还是网络带宽，尤其是现在大陆国际出口严重拥挤的情况下。
拥挤的一个主要原因就是根据相关法律法规，凡是要设置大陆CDN节点的网站必须到大陆备案。所以大量站点无法部署CDN，导致了本不应该产生的国际流量。

**Comment by wongsyrone** [comment]
这种和项目本身关系不大的一般问题去论坛吧。

**Comment by mycwcgr** [comment]
Thanks!
To wongsyrone：我找不到其他论坛可以讨论这个问题，你能推荐一个吗？

BTW，讨论这个话题，可以让用户在选择SS主机时，可以知道应该选择什么性能的主机，避免无谓的浪费

**Comment by Explorare** [comment]
http://www.hostloc.com/ 不谢。

**Comment by mycwcgr** [comment]
Thanks! To Explorare ：
http://www.hostloc.com/是主机论坛， 我想知道是的影响SS速度的因素，也就是，在一个人使用的情况下，应该选择什么配制的主机作为SS服务器？

**Comment by Explorare** [comment]
ShadowSocks 对性能要求不高，单核 512M RAM 的 VPS 都足够跑。主要问题出在路由上。主要的影响因素有用户的本地 ISP，地理位置，出口节点，IDC 的国际线路，目前在我看来主要瓶颈在出口节点和 IDC 的线路上，日本有三条主流线路，Softbank / NTT / KDDI ，其中 Vultr 使用的是 NTT ，对联通用户优化好，电信用户体验较差。其他 IDC 的信息在论坛内都有，请自行查阅。线路和出口节点影响了丢包率和延迟，高峰期上海出口节点的丢包率较高，延迟会上涨 20% 左右。日本线路这半年延迟从 90ms 涨到了 150ms，原因不明。

**Comment by mycwcgr** [comment]
To  Explorare : Thanks!
我一般使用电信的宽带，请问该申请哪个的主机？ DigitalOcean 的San Francisco 和New York速度 似乎也不快 :(

**Comment by Explorare** [comment]
主要考虑西海岸的机房，比如 SFO，LA，和 Phoenix, AZ，NYC 的除非业务关系一般不考虑。具体速度得看路由了，建议注册账户后先试用一段时间，一般都有免费配额的。

**Comment by celeron533** [comment]
@mycwcgr 电信去美国没有很好的线路。目前很多人都是在日本中转的，香港和韩国也有。新加坡连接质量也不太好。

**Comment by mycwcgr** [comment]
我用的就是Vultr  768M内存+1CPU+SSD，但是速度真的不快

**Comment by Explorare** [comment]
主要问题不在 VPS 的运算性能上，而是机房的路由，你的 ISP、VPS 所属的机房都会影响最终的路由结果，也就是所谓的线路。建议用 MTR 工具看看你的 VPS 的路由。

**Comment by Noisyfox** [comment]
就目前所见的情况，网络带宽以及通信质量（比如丢包率，路由跳数以及转发延迟等）是（可以说）唯一的影响了，ss本身消耗的资源微乎其微。我有一个ss服务端是跑在一个小路由上的，我不相信还有比这性能更差的主机了。

**Comment by eastmalon** [comment]
据我测试，锐速和netspeed之类的并不能提高速度，修改内核也不能。新的vps裸装ss与各种优化之后的速度并没有大的区别。不同的linux发行版装ss也没啥区别。同一商家不同配置的vps也没影响。
总之就是想说和vps的软硬件没什么关系，主要看线路。

**Comment by Explorare** [comment]
@eastmalon 所说的并不完全正确，锐速等倍发工具无法改善高延迟的问题，但可以在一定程度上降低丢包率，在高延迟的情况下，重新发包对网络请求的响应速度有很大影响。没能观测到倍发工具的效果是因为基础丢包率已经很低了，倍发的效果难以被观测到。
但在高峰期国际出口节点本身已经处于满载状态，倍发虽然能有所改善丢包率但我认为这是损人利己的行为，诸位自行判断。

**Comment by mycwcgr** [comment]
谢谢！
现在看来选择SS服务器时，是不是需要关注两点？

1、SS服务器所在地能要能快速的访问主流的网站，如google、Facebook 

2、国内能快速的访问这个SS服务器


对于第1点， 是不是日本、香港等地的主机都能快速访问流的网站，如google、Facebook  ？

对于第2点， 不同的线路（电信宽带、移动）是不是都能快速访问日本、香港等地的SS主机 ？

**Comment by Explorare** [comment]
第一点主要考虑到你经常使用的服务，比如日本代理可以提供 DMM 等提供日本地区限定内容的网站，美国代理可以提供 Netflix 的区域限定内容。另外日本代理访问 Google 会默认自动调整 google.co.jp，搜索部分中文关键词时会提供日语结果，比较麻烦，不过可以通过修饰关键词来解决。
第二点是伺服器区域选择的主要条件。同区域不同 IDC 的机房走的线路不通，对国内不同地区不同 ISP 的线路优化不同，主流 IDC 都有提供至少一个月的试用期，建议你亲自测试一下。

**Comment by Noisyfox** [comment]
还要考虑你选的IDC有没有被墙。不同宽带运营商连接部分国外地址的稳定性是千差万别的。

**Comment by mycwcgr** [comment]
谢谢！

请问有没有一个好的工具能测试从当地到不同地点的SS服务器速度分析情况？ 用Ping或下载远程文件的方式似乎不是这么可靠！ 因为涉及到本地ISP的空闲或繁忙时段，服务器端的空闲或繁忙时段，国际出中的空闲或繁忙时段！

**Comment by mycwcgr** [comment]
请问使用 AWS的主机  https://amazonlightsail.com/是不是会好一些？

**Comment by HankAviator** [comment]
这个问题可以去hostloc论坛问了，已经离题。
@mycwcgr

**Comment by dolphin836** [comment]
请问如果使用阿里云的 ECS，选那个地区的访问 Youtube、PronHub 比较快

目前使用的是美国硅谷的，卡的很

**Comment by xheeex** [comment]
为什么我的vps上测试速度有几十M，但是上谷歌速度只有几十k
