### ISSUE TITLE
统一GFWList用户自定义规则

### ISSUE THREAD

**Issue by jan4984** [shadowsocks/shadowsocks-windows#921]
有多台设备，每个设备上要同步规则文件好烦。能不能增加一个功能，比如填写一个onedriver或者其他url，就可以自动下载规则文件

**Comment by celeron533** [comment]
其中一台设备做中央代理。同步数据觉得没什么必要

**Comment by jan4984** [comment]
@celeron533 但是我的设备一个在公司一个在家里不能直连啊

**Comment by chenshaoju** [comment]
使用Dropbox同步 Shadowsocks.exe 所在的文件夹即可，如果是Portable模式，不要同步 ./temp 文件夹。

**Comment by jan4984** [comment]
好吧
