### ISSUE TITLE
自定义规则怎么写才能达到类似 Sugar 的“FINAL,PROXY”效果？

### ISSUE THREAD

**Issue by Gigglelife** [shadowsocks/shadowsocks-windows#923]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by Gigglelife** [comment]
就是除了规则里写的，其余都走代理。这样就不用遇到打不开的网站一条条添加规则了。

**Comment by Explorare** [comment]
[breakwa11/gfw_whitelist: gfw_whitelist](https://github.com/breakwa11/gfw_whitelist)
