### ISSUE TITLE
Forward Proxy 的设置无法保存

### ISSUE THREAD

**Issue by crazyxhz** [shadowsocks/shadowsocks-windows#926]
Forward Proxy 的设置无法保存，每次取消之后都要重新输入，比较麻烦
![111](http://ww2.sinaimg.cn/large/6410d966jw1faj76xxt2lg20bt0500su.gif)

**Comment by celeron533** [comment]
@Noisyfox quick response!

**Comment by yehh** [comment]
Is there anyone knows whether the qt5 version supports forward proxy?

**Comment by celeron533** [comment]
@yehh you could ask this question under ss-qt projects

**Comment by yehh** [comment]
@celeron533  Sure, sorry for inconvenience. Thanks.
