### ISSUE TITLE
服务器连续出错时能否暂时禁用此服务器

### ISSUE THREAD

**Issue by huxim** [shadowsocks/shadowsocks-windows#929]
比如在使用统计来选择服务器时,自动选择某个服务器后,如果此服务器突然不可用,日志中出现timed out,但依然没有切换到其他可用服务器,此时ss就处于不可用的状态,直到下次重选才可用.
![image](https://cloud.githubusercontent.com/assets/2505801/21014214/1c6faf0e-bd98-11e6-9e3c-36c51b909d9e.png)

**Comment by Noisyfox** [comment]
目前新的统计功能正在开发中，请暂时忍耐一下目前的不便，蟹蟹~

**Comment by 18818569575** [comment]
提交了一个pull request，欢迎提出意见
#929 增加服务器禁用配置项 #1028
