### ISSUE TITLE
win10 全局打不开应用商店

### ISSUE THREAD

**Issue by dapao9999** [shadowsocks/shadowsocks-windows#932]
what's wrong?
![2016-12-09_144008](https://cloud.githubusercontent.com/assets/6910161/21040073/6d59f250-be1d-11e6-8ea6-6b7d9d51be36.png)

**Comment by chenshaoju** [comment]
是最新的 3.3.6 版本吗？

**Comment by dapao9999** [comment]
是的

Chen Shaoju <notifications@github.com>于2016年12月9日周五 下午2:53写道：

**Comment by Noisyfox** [comment]
默认win10的modern应用是无法连接localhost的，请使用fiddler修改一下设置
#897
