### ISSUE TITLE
gui-config.json配置文件中如果server 地址中包含字母，会导致shadowsocks异常退出

### ISSUE THREAD

**Issue by penn201500** [shadowsocks/shadowsocks-windows#933]
gui-config.json配置文件中如果server 地址中包含字母，会导致shadowsocks异常退出

环境：win7 64 + ss3.3.6

gui-config.json配置：
"server": "44.33.22.11 abcd",

报错：
![image](https://cloud.githubusercontent.com/assets/16840448/21043694/24428e54-be33-11e6-935b-335558128297.png)

**Comment by wongsyrone** [comment]
本来也不存在这样的地址啊。

> 44.33.22.11 abcd

**Comment by wongsyrone** [comment]
有对服务器的说明可以写到remarks里面

**Comment by Noisyfox** [comment]
Fixed via 8a68a3515b92460093c65f39d520b15d49a9f8ab
Wait for next release/pre-release, and you will need to manually fix the address in gui-config.json.

**Comment by Noisyfox** [comment]
请尝试最新版本
