### ISSUE TITLE
Should switch to native AES instead of mbed TLS.

### ISSUE THREAD

**Issue by edsgerlin** [shadowsocks/shadowsocks-windows#934]
AES-NI provides a performance boost to make AES faster than RC4, mbed TLS currently uses inline assembly to implement AES-NI which is not supported by Visual C++ in 64-bit mode.

I suggest to switch to .NET's native cryptography provider, by doing that we can utilize AES-NI with a x86_64 binary.

Microsoft will release an ARM64-based Windows 10 in near future(https://www.thurrott.com/windows/windows-10/86298/arm-based-windows-10-portable-pcs-hell-yes), it is predictable that it will use ARM64's AES instruction in .NET Framework.

I am thrilled to see the removal of Privoxy. if we can remove dependency on mbed TLS, we can achieve 100% manage code to run one binary on both ARM and x86. With Windows's support for RC4 and AES, we can cover 99% usage cases, the rest of ciphers is rarely used.

**Comment by wongsyrone** [comment]
加密不是瓶颈，网络才是

**Comment by Noisyfox** [comment]
First of all, we don't have x64 binary so mbed TLS is fast.
