### ISSUE TITLE
3.4 替换掉了Privoxy之后，本地http代理端口是多少？

### ISSUE THREAD

**Issue by Remonli** [shadowsocks/shadowsocks-windows#935]
之前有Privoxy的时候，shadowsocks 开一个端口代理socks5，Privoxy开8123 代理http，
现在没有Privoxy了，http代理走哪个端口？

**Comment by breakwa11** [comment]
`shadowsocks 开一个端口代理socks5`  <－－ 用这个端口

**Comment by Remonli** [comment]
端口不会冲突么？

**Comment by breakwa11** [comment]
所以你能先试过再说么？

**Comment by Remonli** [comment]
刚试了确实可以。但这是为什么呢？socks5 不是支持tcp/udp么？为什么跟http代理的tcp端口不冲突。

**Comment by Noisyfox** [comment]
请去百度/谷歌socks5协议

**Comment by Noisyfox** [comment]
以及tcp和udp是两套玩意两者端口不存在任何关联
