### ISSUE TITLE
关闭shadowsocks后不能上网

### ISSUE THREAD

**Issue by WaltChen** [shadowsocks/shadowsocks-windows#936]
shadowsocks 3.3.6 ，使用全局模式后，切换到 PAC 模式或者关闭 shadowsocks 都不能上网了，查看了浏览器和系统的代理设置的没问题，Win 10 和 Win 8.1 都出现了这个问题。

**Comment by wongsyrone** [comment]
有错误日志吗

**Comment by WaltChen** [comment]
@wongsyrone 没有，shadowsocks 倒没提示过错误，就是关闭shadowsocks后不能上网了。

**Comment by Noisyfox** [comment]
关了以后网络设置里面代理有没有自动切回去？

**Comment by WaltChen** [comment]
@Noisyfox  切换回去了，但是不知道为什么不能上网，再打开shadowsocks就可以了。

**Comment by wongsyrone** [comment]
可以尝试一下最新pre-release

**Comment by WaltChen** [comment]
使用最新的没问题了，多谢！
