### ISSUE TITLE
新版3.4.0部分網站出現重新導向迴圈的問題。

### ISSUE THREAD

**Issue by akzhangweiyi** [shadowsocks/shadowsocks-windows#937]
比如：
http://www.dmm.com/
用了日本的節點伺服器，之前的Shadowsocks版本一律正常進入。但3.4.0版本無法打開，Google Chrome報告的問題是重新導向迴圈。

> www.dmm.com 頁面無法正常運作
> 
> www.dmm.com 將您重新導向的次數過多。
> 試試看清除 Cookie.
> ERR_TOO_MANY_REDIRECTS

請問此問題如何解決？

**Comment by Noisyfox** [comment]
请暂时用socks5代理，这个bug争取下一个版本解决

**Comment by celeron533** [comment]
很好奇是为什么引起的？

**Comment by Noisyfox** [comment]
新的http代理不是很成熟

**Comment by Noisyfox** [comment]
请尝试一下最新版本
