### ISSUE TITLE
3.3.6在win7下无法运行

### ISSUE THREAD

**Issue by fenglipop29** [shadowsocks/shadowsocks-windows#939]
貌似3.3.5也是不行
win7下面打不开
错误信息是
问题事件名称:	CLR20r3
  问题签名 01:	shadowsocks.exe
  问题签名 02:	3.3.6.0
  问题签名 03:	5846a492
  问题签名 04:	mscorlib
  问题签名 05:	4.0.0.0
  问题签名 06:	53b50a71
  问题签名 07:	1205
  问题签名 08:	89
  问题签名 09:	System.TypeLoadException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by celeron533** [comment]
请确认安装了.Net 4.6.2
