### ISSUE TITLE
同一个局域网、部分电脑不能连接SS、部分电脑可以连接，这是什么问题？

### ISSUE THREAD

**Issue by Jandaes** [shadowsocks/shadowsocks-windows#942]
### 我在自己的VPS搭建一个SS服务端
在自己公司电脑上用SS客户端是不可以登录连接、但是同一个路由器下面的其它电脑却是可以连接啊？
这是怎么回事？我怀疑是自己电脑问题、但是我按照网上说的方法，什么防火墙、代理都设置了！然而还是没有用。`WIN 7 64bit系统`

但是我在家里打开SS客户端却可以连接`WIN 10`，难道这和操作系统有关系吗？

请各位大神支个招儿、我都搞的懵圈了

**Comment by celeron533** [comment]
你可以检查一下IE里的系统代理是否被正确设置

**Comment by Jandaes** [comment]
@celeron533  设置不是只要设置一个 localhost和端口1080吗？
我看网上是这样的、设置了、还是没用

**Comment by 772807886** [comment]
@Jandaes SS服务器设置右下角的“代理端口”设置的是1080吗？

**Comment by Noisyfox** [comment]
试一下全局模式呢？

**Comment by xiaobaisaber** [comment]
dns 服务别用国内的 试试

**Comment by Jandaes** [comment]
@772807886 是1080的

**Comment by Jandaes** [comment]
@Noisyfox  全局模式没用的、我试过了啊

**Comment by Jandaes** [comment]
@xiaobaisaber  没用的

**Comment by Jandaes** [comment]
就是这样配置的也没用
![@设置代理](https://cloud.githubusercontent.com/assets/9146622/21215843/98089810-c2de-11e6-944f-3d43d60d2bd6.jpg)

**Comment by Jandaes** [comment]
@Noisyfox  1080也没有用啊

**Comment by Noisyfox** [comment]
地址用127.0.0.1呢

**Comment by Jandaes** [comment]
@Noisyfox 也是没用

**Comment by chenshaoju** [comment]
按 Win+R ，输入cmd，然后输入：
```
netstat -ano -p tcp >list.txt
```

然后输入：
```
notepad list.txt
```

会打开记事本，搜索有无：
```
:1080
```
或
```
:1081
```

**Comment by Jandaes** [comment]
@chenshaoju  命令窗口 输入netstat -ano 一样的效果吧？

打开记事本、搜索不到1080和1081，怎么办？

**Comment by chenshaoju** [comment]
确保是在启动了SS的情况下执行的命令。如果找不到1080或1081，以管理员身份启动命令提示符，然后执行：
```
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
```
一行一个，之心完毕后重启即可。如果是XP/2003系统，将第一行替换为：
```
netsh interface ip reset c:\log.txt
```

**Comment by ShineDe** [comment]
其实只要换台电脑就好了。

**Comment by Jandaes** [comment]
@ShineDe 
![会玩](https://cloud.githubusercontent.com/assets/9146622/21253436/8bee5d6a-c399-11e6-8d1c-f4abf3f70a5d.jpg)

会玩

**Comment by Jandaes** [comment]
@chenshaoju 按照你的方法试了、也是没有用

**Comment by gongsunqingyang** [comment]
@xiaobaisaber 我把也遇到了同样的问题，这个问题困扰了我将近一两个月，我把dns首选设为8 8 8 8 备用设为空，就好了

**Comment by Jandaes** [comment]
@gongsunqingyang  只要设置首选8888就可以吗？代理服务器要不要设置？

**Comment by Jandaes** [comment]
@gongsunqingyang按照你的方法试过了！还是没用啊

**Comment by ShineDe** [comment]
C盘  windows/sysyem32/drivers/etc   里面的hosts 配置注释掉。

**Comment by Jandaes** [comment]
`shadowsocks`是不可以使用、但是`lantern`是可以使用的

**Comment by Jandaes** [comment]
> 谷歌浏览器可以科学上网了，但是我那个`shadowsocks`没有一闪一闪的、不知道怎么回事！

解决办法是：设置使用自动配置脚本
![自动检测设置](https://cloud.githubusercontent.com/assets/9146622/21335879/c6967dc0-c69c-11e6-9d96-c5796188a13d.jpg)

**Comment by 772807886** [comment]
你的PAC地址里面是127.0.0.1:1080可以用的话，你下面的代理服务器设置为地址127.0.0.1，端口1080应该也是可以用的。我看你前面的截图里都填的是1081。。。
（这里最好不要填localhost，我遇到过localhost被解析为IPv6地址[::1]的，SS现在不支持监听本地的IPv6，所以最好手动填成IPv4的127.0.0.1）

**Comment by Jandaes** [comment]
@772807886 我在下面设置的话、设置`127.0.0.1`，端口`1080` 没用的！
而且我发现下面写死的话、还不能正常上网了！
就现在上面这种写法、就行

**Comment by 772807886** [comment]
理论上不应该啊。。。
你现在是使用PAC可以正常代理。那你使用Chrome（或Chromium内核浏览器）、Firefox打开需要科学上网的网站，按F12切换到Network，看看Remote Address是什么呢？
![qq 20161220131428](https://cloud.githubusercontent.com/assets/10294977/21339021/6da017f2-c6b6-11e6-95be-1b03b0ada4ec.png)
![qq 20161220131525](https://cloud.githubusercontent.com/assets/10294977/21339022/6da6005e-c6b6-11e6-994b-be92309fe4c0.png)
填成这个地址的话应该就是可以正常全局代理的了。
如果不行的话，那应该就是系统的问题了。

**Comment by Jandaes** [comment]
最终是这样的 @772807886  
![network](https://cloud.githubusercontent.com/assets/9146622/21340461/b54fb728-c6c1-11e6-9bbd-fd85f56819f6.jpg)

**Comment by 772807886** [comment]
那**理论上**设置为`127.0.0.1`和`1080`就应该是正常的了。如果不正常的话，那就是系统其他方面的问题了。

**Comment by Jandaes** [comment]
@772807886 我在家里的win 10系统、什么不用配置、直接打开影梭客户端输入信息就可以访问！也不用设置什么代理啥的

**Comment by ednew2018** [comment]
有些浏览器插件会更改你的代理，关掉之后我的就好了

**Comment by w934940943** [comment]
> @xiaobaisaber 我把也遇到了同样的问题，这个问题困扰了我将近一两个月，我把dns首选设为8 8 8 8 备用设为空，就好了

我用这个方法尝试确实解决问题了。

**Comment by Jandaes** [comment]
> > @xiaobaisaber 我把也遇到了同样的问题，这个问题困扰了我将近一两个月，我把dns首选设为8 8 8 8 备用设为空，就好了
> 
> 我用这个方法尝试确实解决问题了。

现在已经换成使用clash工具了

**Comment by quantiqilizy** [comment]
我是用更新时间解决的   参考的这个 baiyunju.cc/2763

**Comment by gongsunqingyang** [comment]
亲，邮件已收到
