### ISSUE TITLE
为啥一直提示3.79更新，打开又是3.41

### ISSUE THREAD

**Issue by weigeloveu** [shadowsocks/shadowsocks-windows#943]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by celeron533** [comment]
看上去像是SSR的问题，可去 https://github.com/breakwa11/shadowsocks-rss/issues 讨论
