### ISSUE TITLE
设置pac模式，ie无法上网，全局模式就可以

### ISSUE THREAD

**Issue by BZbyr** [shadowsocks/shadowsocks-windows#944]
win10 1607

shadowsockets 3.3.6

pac模式下，ie、edge无法上网，firebox和chrome正常

全局模式下，ie、edge可以上网。

求各位大大分析一下情况呀，感觉是一些设置没有设置对。。。

**Comment by Noisyfox** [comment]
不能上网是所有网页都打不开还是需要翻墙的打不开？

**Comment by Noisyfox** [comment]
试试看pre-release版本呢？

**Comment by BZbyr** [comment]
> 不能上网是所有网页都打不开还是需要翻墙的打不开？

所有都打不开

>试试看pre-release版本呢？

pre-release 3.4.1 版本 没有这个问题了
