### ISSUE TITLE
（win10专业版） System.Security.SecurityException: 不允许所请求的注册表访问权等问题

### ISSUE THREAD

**Issue by abc2017666** [shadowsocks/shadowsocks-windows#945]
win10专业版 System.Security.SecurityException: 不允许所请求的注册表访问权等问题

shadowsocks_2016-12.log

[2016-12-14 21:13:44] ShadowsocksR started on port 1080
[2016-12-14 21:13:45] [Error]connect to update server error
[2016-12-14 21:15:11] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 21:15:11] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void GlobalModeItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-14 21:16:06] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 21:16:06] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void EnableItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-14 21:41:31] ShadowsocksR started on port 1080
[2016-12-14 21:41:36] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 21:41:36] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void GlobalModeItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-14 21:41:50] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 21:41:50] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void SelectRandomItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-14 21:41:55] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 21:41:55] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void SelectRandomItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-14 21:42:01] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 21:42:01] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void EnableItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-14 22:24:58] ShadowsocksR started on port 1080
[2016-12-14 22:25:04] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 22:25:04] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void GlobalModeItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-14 22:25:29] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 22:25:29] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void EnableItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-14 22:32:43] ShadowsocksR started on port 1080
[2016-12-14 22:32:50] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 22:32:50] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void GlobalModeItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-14 22:32:55] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-14 22:32:55] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void EnableItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-15 12:04:42] ShadowsocksR started on port 1080
[2016-12-15 12:04:46] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-15 12:04:46] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void GlobalModeItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-15 12:05:21] ShadowsocksR started on port 1081
[2016-12-15 12:05:21] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-15 12:05:21] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void SaveServersConfig(Shadowsocks.Model.Configuration)
Void OKButton_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void OnClick(System.EventArgs)
Void OnMouseUp(System.Windows.Forms.MouseEventArgs)
Void WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
Void OnMessage(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-15 12:05:29] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-15 12:05:29] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void EnableItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-15 12:06:29] ShadowsocksR started on port 1081
[2016-12-15 12:06:32] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-15 12:06:32] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void GlobalModeItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-15 12:06:38] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-15 12:06:38] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void EnableItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-15 12:07:27] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-15 12:07:27] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void GlobalModeItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

[2016-12-15 12:07:55] System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.OpenUserRegKey(String name, Boolean writable)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable)
失败的程序集的区域是:
MyComputer
[2016-12-15 12:07:55] Void LogUsefulException(System.Exception)
Void Update(Shadowsocks.Model.Configuration, Boolean)
Void UpdateSystemProxy()
Void Reload()
Void ToggleMode(Int32)
Void EnableItem_Click(System.Object, System.EventArgs)
Void OnClick(System.EventArgs)
Void Execute()
Boolean Invoke()
Boolean DispatchID(Int32)
Void WndProc(System.Windows.Forms.Message ByRef)
Void WndProc(System.Windows.Forms.Message ByRef)
IntPtr Callback(IntPtr, Int32, IntPtr, IntPtr)
IntPtr DispatchMessageW(MSG ByRef)
Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
Void Run()
Void Main(System.String[])

不知道怎么进一步修复，电脑有迅雷，ss客户端口改了1081，也是会弹出注册表窗口，还有以上报告问题

**Comment by Noisyfox** [comment]
请反馈给SSR的作者

**Comment by abc2017666** [comment]
怎么反馈？@Noisyfox

**Comment by celeron533** [comment]
@abc2017666 https://github.com/breakwa11/shadowsocks-rss/issues
