### ISSUE TITLE
建议客户端增加一个自动下载json配置文件，自动删除无法连接服务器的功能

### ISSUE THREAD

**Issue by 023yangbo** [shadowsocks/shadowsocks-windows#946]
如题，觉得电脑端，手机端这个功能都挺实用的，尤其是一些新手刚接触的时候一般都是找网上免费账号来试用，每次到处找挺麻烦的，至于功能做出来了谁来提供服务，这个事肯定会有人提供的

**Comment by breakwa11** [comment]
要我我肯定不做

**Comment by wenliyang** [comment]
至于功能做出来了谁来提供服务，这个事肯定会有人提供的 <-- 没人会提供的，即使提供也不会是长期，免费服务只会越来越少

**Comment by celeron533** [comment]
让你的供应商自己提供启动器或者更新器。。。
