### ISSUE TITLE
windows版本的很好用，作者有没有想法把mac下的客户端更新一下呢？

### ISSUE THREAD

**Issue by afboyxiyang** [shadowsocks/shadowsocks-windows#947]
Mac下的现在更新很困难啊！

**Comment by breakwa11** [comment]
mac版本一直有更新

**Comment by celeron533** [comment]
而且windows版本和mac版本是不同的小组。。。

**Comment by afboyxiyang** [comment]
@breakwa11 能否给个地址呢？我现在用的是ShadowsocksX-2.6.3,现在更新gfwlist.js老是出现错误，都不能更新了！非常感谢

**Comment by celeron533** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG
