### ISSUE TITLE
Replacing Privoxy with built-in http proxy.

### ISSUE THREAD

**Issue by xbb123** [shadowsocks/shadowsocks-windows#948]
Hi all,
  First of all, I would like to thank all of you for your contributions.
  In Pre-Release version, Privoxy was replaced by a built-in implementation of http proxy, I would like to express my views on this issue:
  1. Privoxy is a open-source and well supported project. It has gone through so many versions and is considered very stable;
  2. Implementing a http proxy of our own is very likely to introduce bugs and security flaws (ie, code execution) and bring reduced features(ie. keep-alive);
  3. Being a leading project in web proxy enables Privoxy to receive security audits more frequently and as a result, more secure;
  4. Implementing our own http proxy will the this project harder to maintain in the future.
  If I am missing anything, please correct me.
  Thanks!

**Comment by wongsyrone** [comment]
Totally agree with you.

**Comment by celeron533** [comment]
And if it is possible, Privoxy could be replaced to other proxy servers by the ServiceProvider if they would like to have some http cache to give quicker response and/or save the bandwidth.

**Comment by xbb123** [comment]
I don't think you can deploy a caching system using Privoxy since it's running on clients' PC. The best way to cache is simply allowing browsers to follow http headers.

**Comment by xbb123** [comment]
BTW, why this issue is closed already? I think it would be better for a project to open to any suggestions.

**Comment by xbb123** [comment]
Sorry, I didn't see the changes have been reverted. I apologize for my comments earlier.

**Comment by Remonli** [comment]
@wongsyrone  Now Privoxy open a random port instead of previous 8123 for HTTP proxy ? Is it possible to rollback to Privoxy default port 8123  ?

**Comment by breakwa11** [comment]
@Remonli 我认为这是无理的要求

**Comment by celeron533** [comment]
极少数情况下会随机到正准备使用的端口，比如8080，在启动SS后再想启动一个需要监听8080的程序就会悲剧。但基本上只要重启SSwindows应该就没大问题了
>@Remonli 我认为这是无理的要求

**Comment by Remonli** [comment]
如无必要，勿增实体。没有充分的理由，就没必要去改变软件原有的行为。

**Comment by wongsyrone** [comment]
可以自己改代码啊

**Comment by breakwa11** [comment]
@Remonli 之所以说这是无理，是因为你本来就不应该直接使用8123这个端口，而如果不直接使用，那你管它开什么端口呢？

**Comment by shizhilei2** [comment]
有2个疑问，一是为什么每次重新启动SS之后，相应的监听端口就会被随机复写，如何设置固定？二是我用3.3.5这些没有更新Privoxy的版本，还是会报告缺少Privoxy的设置文件，然而用8123端口功能却没有影响
