### ISSUE TITLE
请移除Privoxy，不要使用Privoxy

### ISSUE THREAD

**Issue by xiaoqidun** [shadowsocks/shadowsocks-windows#950]
shadowsocks windows 2.5某个版本引入Privoxy后shadowsocks windows就再也不能跑在沙箱sandboxie中了
前几天shadowsocks windows再次成功运行在沙箱sandboxie中，原因就是Privoxy被拿掉了，今天再次不行了
看了下，原因是Privoxy又回来了，sandboxie跑不起shadowsocks windows，这本身就是一个安全性问题，Privoxy是开源的，安全与否我相信不是每个人都是大牛不是每个人都能看懂源码，我不怀疑Privoxy的安全性
之前也有人反馈过shadowsocks某个版本之后再也不能跑在沙盘sandboxie中了，那就是加入了Privoxy之后的所有版本
刚刚我再次体验到了进入shadosocks就卡死的情况，可爱的Privoxy你回来了，但是我又不能正常使用了，看到这情况我赶紧下载了3.4.1的源码编译了一个3.4.1使用
sandboxie+shadowsocks windows == 正常工作
sandboxie+shadowsocks windows +Privoxy == 异常卡死
我相信很多程序员或者软件开发者都有使用sandboxie的习惯
借助sandboxie官网一句话，不要相信程序（即使是开源的）
希望能再次移除Privoxy，不能的话，我又只能基于3.4.1使用了
在前几天移除Privoxy支持之前，我一直都使用的2.5那个没有Privoxy的版本
能在沙盘中运行，至少我是感觉放心的
我不知道Privoxy为什么会造成sandboxie卡死
sandboxie能跑chrome等很多大软件都没有死，有Privoxy的shadowsocks直接死了，Privoxy动了什么我不知道的资源或者注册表或者有什么资源钩子么，当然，我不是专家，我不知道，开源软件有很多大牛审计，但是带Privoxy的shadowsocks不能运行在sandboxie中，我相信Privoxy是安全的，但是不能跑在sandboxie中很难让我信任其安全性。

**Comment by chenshaoju** [comment]
试着以便携模式运行Shadowsocks看看？

**Comment by xiaoqidun** [comment]
新建shadowsocks_portable_mode.txt文件使用便携式模式运行跟不使用便携式模式运行结果完全一样
有Privoxy的版本，使用Sandboxie运行是必然卡死，win7-10 64bit下都能重现这个问题，不要信任程序

**Comment by xbb123** [comment]
You should report this issue to Sandboxie. 
http://forums.sandboxie.com/phpBB3/viewtopic.php?f=11&t=19746

**Comment by chenshaoju** [comment]
试了一下，该问题的确存在。能释出文件，但是没有Privoxy进程，然后整个进程卡住了。

**Comment by celeron533** [comment]
刚才在`sandboxie`下直接开`visualstudio`调试了一下代码，找到了原因：
`PrivoxyRunner.cs`里面有个方法
```
        private static void RefreshTrayArea(IntPtr windowHandle)
        {
            const uint wmMousemove = 0x0200;
            RECT rect;
            GetClientRect(windowHandle, out rect);
            for (var x = 0; x < rect.right; x += 5)
                for (var y = 0; y < rect.bottom; y += 5)
                    SendMessage(windowHandle, wmMousemove, 0, (y << 16) + x);
        }
```
似乎是直接用了user32.dll模拟鼠标移动去刷新图标，然而这种操作在沙箱里是不允许的。直接注释掉该功能后，SS成功启动，代理功能正常。
```
        [DllImport("user32.dll")]
        public static extern IntPtr SendMessage(IntPtr hWnd, uint msg, int wParam, int lParam);
```

![image](https://cloud.githubusercontent.com/assets/3608762/21263910/5b74f55a-c3d4-11e6-95fa-a6f57979aa25.png)

**Comment by celeron533** [comment]
补充：
`PrivoxyRunner.cs`中的相关内容更改发生在以下commit：
4e01a40dd8013b6efbda3fb7396e717eff18f306

**Comment by wongsyrone** [comment]
privoxy这个如果直接用发布版本的话，无论怎么设置，还是会自动创建托盘图标的。后来直接修改二进制去掉了创建托盘图标的调用，近期的两个privoxy的二进制是我改的。我赞成去掉图标刷新功能。

详细：

jmp dword ptr [<&SHELL32.Shell_NotifyIconA>] --> nop

**Comment by celeron533** [comment]
Pull request created to fix this issue
https://github.com/shadowsocks/shadowsocks-windows/pull/954

**Comment by wongsyrone** [comment]
Wait for next release or compile it yourself.
