### ISSUE TITLE
user-rule.txt被占用导致shadowsocks更新Pac时崩溃

### ISSUE THREAD

**Issue by AoEiuV020** [shadowsocks/shadowsocks-windows#951]
### Version(release version or AppVeyor link)
https://github.com/shadowsocks/shadowsocks-windows/releases/download/3.4.2/Shadowsocks-3.4.2.zip

### Environment(Operating system, .NET Framework, etc)
win10

### Steps you have tried
notepad打开user-rule.txt，
修改，保存，不关闭，
shadowsocks更新本地Pac，
重复上面两步，突然崩溃，

### What did you expect to see?
按理说应该是能正常读取上次保存的内容才对，
不应该被强退，

### What did you see instead?
。。。

### Config and error log in detail (with all sensitive info masked)
[2016-12-17 09:28:01] Detected: PAC file 'pac.txt' was created.
[2016-12-17 09:28:29] Detected: User Rule file 'user-rule.txt' was created.
[2016-12-17 09:28:34] Detected: PAC file 'pac.txt' was changed.
[2016-12-17 09:29:18] Shadowsocks started
[2016-12-17 09:38:20] Detected: User Rule file 'user-rule.txt' was changed.
[2016-12-17 09:38:20] [E] System.IO.IOException: 文件“D:\aoeiuv020\programe\net\Shadowsocks-3.4.2\user-rule.txt”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   在 System.IO.File.ReadAllText(String path, Encoding encoding)
   在 Shadowsocks.Controller.ShadowsocksController.pacServer_UserRuleFileChanged(Object sender, EventArgs e)
   在 Shadowsocks.Controller.PACServer.UserRuleFileWatcher_Changed(Object sender, FileSystemEventArgs e)
   在 System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   在 System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   在 System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   在 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
[2016-12-17 09:38:27] Detected: PAC file 'pac.txt' was changed.
[2016-12-17 09:39:50] Detected: PAC file 'pac.txt' was changed.

![ss](https://cloud.githubusercontent.com/assets/11682198/21283679/9ebed8a4-c441-11e6-924a-4a805c58689d.PNG)

**Comment by wongsyrone** [comment]
#894
