### ISSUE TITLE
非预期错误

### ISSUE THREAD

**Issue by kaimisite** [shadowsocks/shadowsocks-windows#952]
### Version(release version or AppVeyor link)
3.4.2

### Environment(Operating system, .NET Framework, etc)
win7 32位  .net：4.6.2

### Steps you have tried
写好服务器配置，点击启动系统代理，报错。
![](http://p1.bqimg.com/567571/286f23b91324066f.jpg)
360报病毒：木马win32/Trojan.97a    sysproxy.exe

**Comment by celeron533** [comment]
一般而言，使用SS的机器不建议安装国产杀毒软件，尤其是360

V2EX曾经有人汇报并高度怀疑360会向真理部通报翻墙服务器地址。

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/959#issuecomment-268421804
