### ISSUE TITLE
[UI error] 非预期错误：系统找不到指定的文件

### ISSUE THREAD

**Issue by h404bi** [shadowsocks/shadowsocks-windows#957]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)

3.4.2

### Environment(Operating system, .NET Framework, etc)

Windows 10 Build 14393

### Steps you have tried

突然弹出

### What did you expect to see?

None

### What did you see instead?

![image](https://cloud.githubusercontent.com/assets/5764917/21314335/6d574f48-c631-11e6-9498-8257ad675da6.png)

### Config and error log in detail (with all sensitive info masked)

``` log
[2016-12-19 21:19:39] Shadowsocks started
[2016-12-19 21:19:39] [E] Exception Detail: 
System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start()
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
   在 Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.View.MenuViewController.AStrategyItem_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.Command.DispatchID(Int32 id)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

直接崩退出了。。以下是部分 config，另勾选了“高可用”、本地 PAC、保护 PAC：

![image](https://cloud.githubusercontent.com/assets/5764917/21314429/0495b458-c632-11e6-9878-df44a867e1aa.png)

*report 时只出现一次，因为非预期错误故开此 issue 提交。*

**Comment by breakwa11** [comment]
你解压缩时请不要只把主程序的exe复制出来，其它东西也要的

**Comment by wongsyrone** [comment]
检查是否有个名为sysproxy.exe的文件被杀毒软件杀掉了。

**Comment by h404bi** [comment]
@breakwa11 不明，是指 Shadowsocks-3.4.2.zip 解压？我是从 [releases](https://github.com/shadowsocks/shadowsocks-windows/releases) 下载的 zip，直接解压就只有一个 Shadowsocks.exe。然后更新覆盖旧的 Shadowsocks.exe..

![image](https://cloud.githubusercontent.com/assets/5764917/21315311/81b15d3a-c636-11e6-9c90-e9dd31ef03ac.png)

@wongsyrone 没发现有 sysproxy.exe 文件及被 kill，杀毒是自带的 Defender。

**Comment by celeron533** [comment]
不一定是kill，而是访问被拒绝

https://github.com/shadowsocks/shadowsocks-windows/issues/952#issuecomment-267764508

**Comment by 772807886** [comment]
创建一个`shadowsocks_portable_mode.txt`文件，使用便携模式试试呢？

**Comment by wongsyrone** [comment]
放在非系统盘根目录用便携模式试一下

**Comment by h404bi** [comment]
@wongsyrone 一直是放非系统盘的，不清楚因何造成出现这个。@772807886 谢谢。
目前我也无法再复现，先关闭 issue 吧，有问题再重开。
