### ISSUE TITLE
Feature Request: 添加内建 kcptun 支持

### ISSUE THREAD

**Issue by choleraehyq** [shadowsocks/shadowsocks-windows#958]
在 shadowsocks 的基础上架一个 [kcptun](https://github.com/xtaci/kcptun) 能够显著提高速度。

本来这个功能也许应该由第三方工具提供，但是考虑以下两点：
* shadowsocks-windows 内置了 privoxy 做 socks5 -> http 转换，那为什么不能再加一个 kcp 转换来增加便利性呢？
* [shadowsocks-android](https://github.com/shadowsocks/shadowsocks-android) 已经提供了内建的 kcp 支持。

**Comment by breakwa11** [comment]
reject

**Comment by chenshaoju** [comment]
实际上自行写一个批处理更好。
```
killall /f /im client_windows_amd64.exe
killall /f /im Shadowsocks.exe
killall /f /im ss_privoxy.exe
killall /f /im sysproxy.exe
start client_windows_amd64.exe
start Shadowsocks.exe
```
