### ISSUE TITLE
360查杀

### ISSUE THREAD

**Issue by zhuqichen0310** [shadowsocks/shadowsocks-windows#959]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.2

### Environment(Operating system, .NET Framework, etc)

win7 32
### Steps you have tried

安装后 sysproxy.exe 被查杀有木马 ：Trojan.97a

**Comment by chenshaoju** [comment]
该问题是３６０的问题，由于３６０使用白名单机制，所有不认识的应用均会报毒，请更换其他杀毒软，如Avira、Microsoft Security Essentials等。

**Comment by wongsyrone** [comment]
过一阵子我会推一个只有baidu 和 qihoo 360报毒的。

**Comment by chenshaoju** [comment]
@wongsyrone No。。。

**Comment by wongsyrone** [comment]
bug report for new sysproxy:

https://www.virustotal.com/en/file/c8c8c033dd17008c177e669900d473b5668e0b8ded2064f595845fc4afbbd059/analysis/1482289052/

https://www.virustotal.com/en/file/1c5460861a7ddc96a93088cf996bf7d05014f0a523f80808d76a9a10086dfccd/analysis/1482289101/

**Comment by Vstory** [comment]
360不是会把服务器上传到GFW吗？SS服务商默认都会拒绝360.

**Comment by celeron533** [comment]
V2EX有人架了公共服务器后三天两头被封，后来直接在转发规则里屏蔽一切360有关地址。且第一次发现警告，第二次封SS账号。
> 360不是会把服务器上传到GFW吗？SS服务商默认都会拒绝360.

**Comment by lixingcong** [comment]
@celeron533  你提到的ss屏蔽360地址可以共享一下嘛，我同样想屏蔽

**Comment by jasonliul** [comment]
36.96.0.0-36.127.255.255
101.198.0.0-101.231.255.255
104.192.108.0-104.192.111.255
106.32.0.0-106.121.255.255
120.132.0.0-120.132.127.255
123.112.0.0-123.127.255.255
180.152.0.0-180.175.255.255
210.52.0.0-210.53.255.255
220.181.0.0 - 220.181.255.255
 
116.208.93.0-116.211.255.255 
117.24.0.0-117.28.132.255 

360使用的腌臜ip段, 防火墙全部屏蔽掉

**Comment by celeron533** [comment]
这个没有研究过，我一直都是自用服务器，没有公开，自己也没有装过360
> @celeron533 你提到的ss屏蔽360地址可以共享一下嘛，我同样想屏蔽
