### ISSUE TITLE
大大们，如果ss可以增加笔记本电脑建立wifi热点的功能，我将感激不尽！

### ISSUE THREAD

**Issue by ku8h96de4** [shadowsocks/shadowsocks-windows#960]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
实现很困难，SS for Windows的主要目的仍然是提供单一环境的数据传输。

**Comment by xiaobaisaber** [comment]
希望你可以仔细读一下使用说明 ，已经提供开放热点功能了 自是你没理解而已```允许来自局域网的链接``` 你就可以理解成wifi啦，

**Comment by xiaobaisaber** [comment]
[你可以看看这个博客思路就是这样吧](http://jas0n.me/2014/11/12/up_14_11_12/)

**Comment by ku8h96de4** [comment]
SOpenSource <notifications@github.com>于2016年12月21日 周三上午10:50写道：

**Comment by tyfonet** [comment]
楼上有亲兄弟已经给答案了，在WINDOWS客户上勾选允许来自局域网的链接。手机的WIFI连接上配置下代理。
