### ISSUE TITLE
shadowsocks的pac规则不太好理解添加，感觉Faststunnel的不错

### ISSUE THREAD

**Issue by ANdrew88888888** [shadowsocks/shadowsocks-windows#962]
看pac里面有两个|| 的 ，还有一个| 的，还有 . 开头的。想自己加入pac规则也不太懂，都是英文。不如用faststunnel（快速安全通道）顺手，这个chrome插件可以直接复制网址进去，自动识别域名，并添加到个人pac域名列表里，如果shadowsocks也能有这样的功能设计就好了

Faststunnel  github项目：https://github.com/Faststunnel/FastStunnel
Faststunnel chrome插件：https://chrome.google.com/webstore/detail/faststunnel-vpn-unblack-s/bblcccknbdbplgmdjnnikffefhdlobhp?utm_campaign=en&utm_source=en-et-na-us-oc-webstrhm&utm_medium=et

**Comment by celeron533** [comment]
用switchyOmega
