### ISSUE TITLE
sysproxy 的访问被拒绝

### ISSUE THREAD

**Issue by icedream728** [shadowsocks/shadowsocks-windows#963]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.2

### Environment(Operating system, .NET Framework, etc)
win7 32bit, .NET 4.6.2

### Steps you have tried
1. 打开时出现这个错误，任务栏出现logo
2. 左击任务栏小图标无效，右击也无效
3. 再运行程序时报告程序已打开
4. 过段时间后任务栏小图标消失

### What did you see instead?
![qq 20161222162449](https://cloud.githubusercontent.com/assets/2726880/21419529/2e39834c-c863-11e6-9023-19640a5068a7.jpg)

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
权限不够

**Comment by icedream728** [comment]
已经右键选择管理员权限打开了。
而且%temp%里面找不到sysproxy这个文件

**Comment by wongsyrone** [comment]
看看是否被杀毒软件杀掉了

**Comment by icedream728** [comment]
确实是。。。谢谢
