### ISSUE TITLE
托盘那里有个 bug

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-windows#965]
![d](https://cloud.githubusercontent.com/assets/4590439/21453963/62be5ab0-c94f-11e6-80c4-1fcfc26dd675.png)

如图所示：服务器端口显示不全，只显示了 32，实际上服务器端口是 32xxx 五位数的。

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/View/MenuViewController.cs#L183

**Comment by wongsyrone** [comment]
try https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-pljx3/build/1.0.5/job/qomoqrxv2m9l1714/artifacts

**Comment by pexcn** [comment]
解决了 👍
