### ISSUE TITLE
共享给局域网安卓或ipad，wifi代理选“手动”可全局走ss，但如果选“自动”填入pac地址后则无法翻墙

### ISSUE THREAD

**Issue by zhuhangyu** [shadowsocks/shadowsocks-windows#966]
shadowsocks-windows 3.4.2
win7 64bit
.net framework 4.6.2

电脑使用ss客户端，勾选启用系统代理和PAC模式，本机浏览器可以正常翻墙。
勾选允许局域网的连接后，使用安卓手机或者ipad3，修改wifi，在代理处选手动，填入电脑的ip和1080端口，能正常翻墙，访问百度显示ip是ss服务端ip，说明全局走ss；如果在代理处选自动，填入http://电脑ip:1080/pac，则无法翻墙，能访问百度。

**Comment by wongsyrone** [comment]
手动指定pac需要去掉“保护本地PAC”的勾

**Comment by sid5785** [comment]
666

**Comment by tefiszx** [comment]
我的手机使用pc的ss-win客户端，win10开启移动热点，然后ss客户端开启【启用系统代理】和【允许局域网的连接】就可以给手机wifi做代理了。勾不勾选【保护本地pac】没有影响。

不过这个方式给手机代理，只能浏览网页，手机上的app都不会走代理的。google play可以浏览，但不能下载。

**Comment by XoloveStepth** [comment]
用PAC共享到局域网之后，facebook app不能打开，手动就可以，你也是吗？
