### ISSUE TITLE
更新到3.4.2之后，一定几率下Firefox无法读取代理设置，Edge浏览器崩溃

### ISSUE THREAD

**Issue by Mirr0ch1** [shadowsocks/shadowsocks-windows#967]
更新到3.4.2之后，可以从IE的代理设置中查看到设置了正确的代理（127.0.0.1:1080），Modern界面的设置 - 网络 - 代理也自动填写的是正确的代理设置。但Firefox打开后有一定几率无论使用PAC方式还是全局方式均无法使用代理（查看ipip.net / speedtest.net / bgp.he.net均返回真实IP）。且打开全局代理后Edge打开网页即有几率崩溃，一旦崩溃一次之后未重启系统前均会一直崩溃。
系统版本是Win 10 14393。依赖齐全，Firefox特意安装的51.0.1 x86_64。因为不会写代码也不会debug所以原因未知。求复现与修复。

**Comment by Mirr0ch1** [comment]
后续：退回到3.3.6版本之后一切正常。

**Comment by wongsyrone** [comment]
能否尝试一下新版本，给修改代理做了一点小修改。

**Comment by wongsyrone** [comment]
另外能否详细说一下复现步骤。

**Comment by Mirr0ch1** [comment]
@wongsyrone 我使用Shadowsocks客户端都是在C盘根目录建立shadowsocks文件夹，然后把shadowsocks.exe 复制进去然后执行使用的。每次遇到升级均直接覆盖shadowsocks.exe。上次是更新了3.4.2版本之后。重启电脑，发现Firefox一直使用的是32位版本，卸载了Firefox 51.0.1 x86然后从官网（mozilla.org/en-US/firefox/all）下载了51.0.1 x86_64安装使用。

**Comment by Mirr0ch1** [comment]
@wongsyrone  ，再过一阵之后发现网速有些慢（我同时有在用自建的dnsmasq和sni-proxy），打开ss的全局代理后问题依旧，于是去speedtest测速，发现speedtest给出的IP是我的真实IP。
换用Edge浏览器后发现无论什么网页打开以后均崩溃。Internet Explorer中访问beta.speedtest.net给出的则是VPS的IP。
反复尝试切换“启用系统代理”开关也没有效果，然后重启shadowsocks进程。几次之后Firefox可以显示VPS的IP了。但重启后又失败。
一周之后回家发现问题依旧，因为笔记本和我台式机的日常软件完全相同，开始我以为是PC的问题。然后发现笔记本上的ss还停留在3.3.6没更新，所以把台式机换回了3.3.6版本。就再也没有出现问题。

**Comment by myliyifei** [comment]
3.4.3版本  Firefox选择 使用系统代理设置 或者 自动检测 此网络的的代理设置 或者 自动PAC 均无效。

退回到 3.3.6 FF使用没有问题，其他版本未试。

**Comment by shansing** [comment]
我也发现 Firefox 下不行的事情了，用了扩展组件才行。我用的是 FoxyProxy，在里面新建一个配置，使用系统代理设置，启用，就好了。
