### ISSUE TITLE
有支持 libev 版本 obfs 功能的计划吗？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-windows#968]

**Comment by celeron533** [comment]
自己添加后置服务吧，包括但不限于：

- 其他web代理
- kcptun等新流控
- 其他vpn隧道
- 其他黑科技等

**Comment by breakwa11** [comment]
浓浓的答非所问感觉。。。。

**Comment by wongsyrone** [comment]
这个刚出来，还不成熟，等稳定了再说吧

**Comment by celeron533** [comment]
> 浓浓的答非所问感觉。。。。

额。。。上次也有朋友问obsf，我让他直接在机器上再架设一层混淆

最开始的那个回答确实有点误解

**Comment by pexcn** [comment]
额。。

**Comment by wongsyrone** [comment]
madeye decided to deprecate this feature.

ref: https://github.com/shadowsocks/shadowsocks-org/issues/26#issuecomment-269843409
