### ISSUE TITLE
最新的PAC导致QQ群文件无法访问

### ISSUE THREAD

**Issue by BigeYoung** [shadowsocks/shadowsocks-windows#969]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by chenshaoju** [comment]
Shadowsocks使用的是GFWList的列表，请前往 https://github.com/gfwlist/gfwlist/issues 反馈问题。
