### ISSUE TITLE
切换全局代理报错

### ISSUE THREAD

**Issue by longware** [shadowsocks/shadowsocks-windows#970]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.4.2

### Environment(Operating system, .NET Framework, etc)
win7 x64

### Steps you have tried
切换全局代理报错，然后挂了

### Config and error log in detail (with all sensitive info masked)

---------------------------
Shadowsocks UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues 
Exception Detail: 
System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start()
   在 Shadowsocks.Util.SystemProxy.Sysproxy.SetIEProxy(Boolean enable, Boolean global, String proxyServer, String pacURL)
   在 Shadowsocks.Controller.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
   在 Shadowsocks.Controller.ShadowsocksController.UpdateSystemProxy()
   在 Shadowsocks.Controller.ShadowsocksController.Reload()
   在 Shadowsocks.Controller.ShadowsocksController.ToggleGlobal(Boolean global)
   在 Shadowsocks.View.MenuViewController.GlobalModeItem_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.Command.DispatchID(Int32 id)
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
确定   
---------------------------

**Comment by wongsyrone** [comment]
sysproxy.exe被杀了
