### ISSUE TITLE
最近一礼拜SS都十分不稳定，外网有时可以打有时打不开，不知道是什么原因

### ISSUE THREAD

**Issue by smusicsanshu** [shadowsocks/shadowsocks-windows#971]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)

**Comment by wongsyrone** [comment]
我也不知道

**Comment by chenshaoju** [comment]
请检查到你SS服务器的延迟，如果延迟过高（超过300ms）或者严重丢包，请与你的VPS服务商或者SS服务商联系。

**Comment by myfingerhurt** [comment]
先看你的DNS是不被污染了。
