### ISSUE TITLE
打开软件报错

### ISSUE THREAD

**Issue by niaiai** [shadowsocks/shadowsocks-windows#972]
![image](https://cloud.githubusercontent.com/assets/9845669/21558594/9c14650c-ce77-11e6-823e-927af8216706.png)
![image](https://cloud.githubusercontent.com/assets/9845669/21558588/72826cd4-ce77-11e6-8142-6e16ab124b00.png)

**Comment by wongsyrone** [comment]
清理过临时文件吗，另外看一下杀毒软件的日志看看是否被杀掉了。

**Comment by wongsyrone** [comment]
如果是因为被杀掉，新版本应该已经解决了。开启的时候注意程序权限就行了。

**Comment by chenshaoju** [comment]
@wongsyrone 有报告称avast可能会误报，上传到VirusTotal没有检出问题，正在复查，先保持Close把。
https://www.virustotal.com/en/file/26705c8af4d56cc7d5ba703483a2e303d3b8e89adf1300c150998d450aa4cdda/analysis/1483108468/

**Comment by wongsyrone** [comment]
因为我本地编译之后就传到virustotal上看过了，只有Baidu和Qihoo 360报毒

**Comment by wongsyrone** [comment]
这里面的事情很简单，如果选择相信baidu和qihoo 360，可以用shadowsocks 2.5.6；如果选择相信后续开发者和国际大厂的杀毒软件，可以继续。

**Comment by niaiai** [comment]
我安装的双系统 C:\Users\Administrator\Local Settings 被破坏了
其他软件都安装不了 我把磁盘修复一下 一切都搞定了
软件本身没有问题 不好意思

**Comment by ZSmallX** [comment]
找到原因了：腾讯电脑管家清理垃圾

**Comment by ZSmallX** [comment]
会清理掉SS的临时文件
