### ISSUE TITLE
建议完善一下自动更新功能

### ISSUE THREAD

**Issue by ssc19940105** [shadowsocks/shadowsocks-windows#974]
自动更新功能一直比较鸡肋，考虑一下完善一下吗？

**Comment by wongsyrone** [comment]
你的完善意见？

**Comment by ssc19940105** [comment]
通过外置升级程序进行升级，就可以实现全自动。

**Comment by ssc19940105** [comment]
比如这样的：http://autoupdaterdotnet.codeplex.com
直接贴网址比较偷懒

**Comment by wongsyrone** [comment]
这个很像 https://github.com/shadowsocks/shadowsocks-windows/pull/122#issuecomment-69152686

我也赞成需要用户干预，目前的做法是只管下载下来，是否替换需要用户做决定。

**Comment by ssc19940105** [comment]
我的建议是不下载，点击通知进行下载升级，既保证了效率又又不会侵犯用户知情权

**Comment by BrillianceRen** [comment]
建议单独做一个update程序

检测更新，提示用户；
用户确认，下载并启动update；
update下载主程序（进度条），提示用户关闭主程序进程；
用户确认，kill主程序进程，替换主程序，启动主程序；
主程序删掉update及其他下载的文件

**Comment by celeron533** [comment]
我倒是对目前的更新机制不感冒
1. 虽然是后台自动下载且用户不可控制，但目前的zip包也就740k左右，带宽浪费可以忽略。
2. 手动更新：关ss，解压替换，开ss。算不上麻烦。

**Comment by WAAutoMaton** [comment]
我倒是建议点更新之后提示一下接下来的步骤（等待下载完成后解压覆盖），我第一次用自动更新的时候点了之后发现没反应有点懵逼（当时是在下载，但是没有任何提示）

**Comment by XingdaLee** [comment]
保持目前的安装方式就行了。没必要搞安装
