### ISSUE TITLE
[feature] 根据关键字指定 Proxy

### ISSUE THREAD

**Issue by wujun4code** [shadowsocks/shadowsocks-windows#976]
## 需求
背景： 我自己有 2 个代理，一个是阿里云香港的，一个是微软国际版的，现在出现的问题是，因为近期太多人在阿里云香港搭建梯子，谷歌的机器人识别服务已经开始 ban 掉阿里云这个 ip 段的一些请求了，要不然就得频繁的进行机器人验证，因此我的需求是，我在 PAC 里面针对 *.google.* 返回我微软国际版的 ss 代理，而其他的继续走阿里云的

## 一些提议
新增一个配置格式：

```js
[
    {
        "pattern": "DOMAIN-SUFFIX",
        "keyWord": "163.com",
        "proxy": "DIRECT"
    },
    {
        "pattern": "DOMAIN-KEYWORD",
        "keyWord": "google",
        "proxy": "Azure"
    },
    {
        "pattern": "DOMAIN-KEYWORD",
        "keyWord": "facebook.com",
        "proxy": "AliyunHK"
    }
]
```
然后新增一个 checkbox：

- [x] 开启关键字指定代理

最后实现一个 `IStrategy`

## 敲黑板，重点问题：允许这样修改的 PR 么？

**Comment by wongsyrone** [comment]
如果是在浏览器里面使用的话，我感觉可以配合switchyomega和SS的多实例来达到这个目的。SS这边只是提供一个极简的方案，如果要自己定制的话建议搭配更成熟的方案。

PR的话可以先在自己的fork实现出来，如果反响不错可以merge

**Comment by GhostFlying** [comment]
偶尔可能有类似的需求，不过个人感觉这个功能是不是由 pac 来实现会比较好，通过多个在不同端口的 ss 客户端的实例，让 pac 根据需求来转发，感觉会更干净。

**Comment by Noisyfox** [comment]
这个其实是服务器选择策略的一种。目前的框架是能够实现根据目标地址选择服务器的。但是呢，这种功能目前有更加有弹性的解决方法（比如用switchyomega），直接在ss里实现并不是非常划算。

**Comment by VMatrix1900** [comment]
> 偶尔可能有类似的需求，不过个人感觉这个功能是不是由 pac 来实现会比较好，通过多个在不同端口的 ss 客户端的实例，让 pac 根据需求来转发，感觉会更干净。

请问如果要用pac来实现的话，应该怎么做呢？Pac 文件返回的只是__PROXY__ 和DIRECT两种选择，可以把SS server的地址写在pac里面么？
