### ISSUE TITLE
在线Pac网址怎么填？

### ISSUE THREAD

**Issue by BlakGriffin** [shadowsocks/shadowsocks-windows#979]
不希望桌面有两个文件，请问这个在线Pac怎么弄

**Comment by chenshaoju** [comment]
比如填写：
```
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
```
另外，你可以将SS放到其他目录里即可。
如果你创建了快捷方式，请检查快捷方式的起始位置参数是否是SS所在目录。
如果起始位置为空，启动时产生的文件可能会出现在快捷方式所在目录。

**Comment by kkkisme** [comment]
@chenshaoju 可以把那个官方库fork下来然后填写自己的吗？ 但那个规则如何添加呢？ 在gfwlist 的issue里提交了新的域名，一个月了都不理

**Comment by chenshaoju** [comment]
@kkkisme 如果你希望自定义规则，可以右击任务栏托盘区的纸飞机图标，然后选择PAC，并点击“编辑GFWList的用户规则”，然后在出现的 .txt 文件里加入你想增加的域名，格式为：
```
||google.com
```
请将 google.com 替换为你想增加的域名。

**Comment by chenshaoju** [comment]
我没做过这方面的研究。。。也许后续回答者可能可以帮助你。

**Comment by celeron533** [comment]
@kkkisme 一直到现在，gfwlist的获取地址一直是hardcode的

**Comment by kkkisme** [comment]
没有办法定义一套属于自己的gfwlist吗(托管在github上的那种)

2018-04-19 21:32 GMT+08:00 Allen Zhu <notifications@github.com>:

**Comment by celeron533** [comment]
>没有办法定义一套属于自己的gfwlist吗(托管在github上的那种)

自己建一个repo
然后fork ss后改源代码

**Comment by kkkisme** [comment]
[https://github.com/shadowsocks/shadowsocks-windows/blob/502397b5f942ab4e64a0f5a3010cfa59d24d7999/shadowsocks-csharp/Controller/Service/GfwListUpdater.cs#L17](https://github.com/shadowsocks/shadowsocks-windows/blob/502397b5f942ab4e64a0f5a3010cfa59d24d7999/shadowsocks-csharp/Controller/Service/GfwListUpdater.cs#L17)
修改这一行吗？
所以做法是改掉ss-win的gfwlist的url（这个url是我自己的repo也就是kkkisme/gfwlist）后编译安装，

但文本内容是一段字符串，请问是用什么工具将那些白名单url转成这些字符串的呢
