### ISSUE TITLE
任务管理器上的图标问题

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-windows#980]
![dd](https://cloud.githubusercontent.com/assets/4590439/21584853/5b86b5ca-d0ee-11e6-9554-7e74d95c72d2.png)

SS 的图标好像不显示

**Comment by breakwa11** [comment]
确实有这问题，应该是图标的alpha导致的

**Comment by pexcn** [comment]
![ss](https://cloud.githubusercontent.com/assets/4590439/21585848/389e7de4-d103-11e6-849f-0993c06a0886.png)
之后就显示成这样了，不太清晰

**Comment by breakwa11** [comment]
这就没办法了，重画图标估计可以

**Comment by breakwa11** [comment]
顺便告诉你一个简单的解决办法，如果你有强迫症，那打开程序后，右键一下弹个菜单，问题就解决了
