### ISSUE TITLE
Fail to connect Google hangouts for video chat

### ISSUE THREAD

**Issue by CicoZhang** [shadowsocks/shadowsocks-windows#982]
Hi, buddies:

I have installed Shadowsocks windows on my Mom's computer, who is in China now. I have my own Shadowsocks servers. 

I notice a very vetting problem when using Google hangouts for video chat, it just fails. 

When she calls me, I can answer the call, but then the call is disconnected immediately.

When I call her, I just get a message: Invite failed. Everything is up to date: Chrome browser, hangout plugin and stuff. 

Does anyone have the same problem?

**Comment by suikatomoki** [comment]
https://support.google.com/a/answer/1279090

hangouts maybe use UDP connect server,but UDP is unstable in some places.

**Comment by celeron533** [comment]
I prefer using Skype instead of Google hangouts. :)

**Comment by cokebar** [comment]
Try forward the tracffic to proxy using Proxifier(or other similar program). It may helps.(not sure)

**Comment by Explorare** [comment]
@cokebar Proxifier doesn't support UDP ,but Proxicap (which is a commercial software) does. 
And UDP support should be enabled on server side. SSR C# client doesn't support UDP proxy. SS C# client supports.

**Comment by CicoZhang** [comment]
＠celeron533 In terms of the video quality and stability, Skype is not a patch on Google hangouts and Duo. I want Mom to see her son clearly...

**Comment by Explorare** [comment]
I don't think Skype is not as good as Hangouts. At least Skype don't need a proxy server to login. Most of my family members and development partners use Skype for video chat. Skype did her job as is.

**Comment by CicoZhang** [comment]
No, it isn't. It stands out a mile that Google hangouts and Duo are amazingly clear, even in my place  (1Gbps in office, 100 Mbps at home (Western Europe)) Skype cannot deliver what it should. In my academic conferences and meetings (CS), I (we) have been using Google hangouts, and skype just stays put and no substantial innovation's been made over the past few years.

**Comment by wongsyrone** [comment]
I don't have such environment to reproduce.

**Comment by fishtreesugar** [comment]
I meet the same issue, but connect via my global VPN it just fine.

**Comment by addohm** [comment]
I'm having this issue in China. Everything else works wonderfully. Any specific rules that anyone knows to make this work?
