### ISSUE TITLE
三个服务器，断掉两个就不能自动连到剩下一个了

### ISSUE THREAD

**Issue by aolm** [shadowsocks/shadowsocks-windows#983]
选择**高可用**模式，添加三个服务器，然后断掉其中两个的服务器，结果就一直等待，无法连接到第三个服务器了。手动选择第三个服务器则可以正常连接。

**Comment by breakwa11** [comment]
我没有出现这个问题，你咋反生的，能每次都重现吗

**Comment by aolm** [comment]
额，刚才又试了一遍，居然好了。我的应用场景是需要稳定的数据流（报价）。一个不行就自动切换到另一个。今晚G-F@W发飙，差不多一个小时三个机房（且属于三个独立的vps商）的主机全部连不上。遇到这种情况咋整。。话说回来还是谢谢了。
