### ISSUE TITLE
Do you have a plan for supporting obfs?

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-windows#985]
since shadowsocks-libev 2.6.0 add obfs function. Do you have a plan for supporting obfs in shadowsocks-windows?

**Comment by tlhc** [comment]
+1

**Comment by wongsyrone** [comment]
The original proposal has been deprecated. Obfs in shadowsocks-libev 2.6.0 will be replaced with plugin servers in the future.

**Comment by matsuz** [comment]
@wongsyrone Any plan to support simple-obfs plugin?

**Comment by suikatomoki** [comment]
the simple-obfs plugin is useful in company network
