### ISSUE TITLE
同一账号在A电脑能连网，在B电脑却无法连网

### ISSUE THREAD

**Issue by JFluo2011** [shadowsocks/shadowsocks-windows#986]
你好：请问出现下面问题的可能原因是什么？
环境：
    windows7电脑：A和B
    服务器账号：user1, user2
    shadowsocks版本：3.4.2和2.5.2
现象1：
    在版本2.5.2或者3.4.2时：
        A + user1 -- 正常使用；
        B+ user1 -- 无法使用（选择全局模式，百度也不能访问，日志显示connect to www.baidu.com:443）。
现象2：
    在版本2.5.2或者3.4.2时：
        B + user1 -- 无法使用，现象如上；
        B + user2 -- 正常使用。

备注：
在上周出现的问题，之前几种组合均能正常使用。

**Comment by breakwa11** [comment]
信息太少，无法判断，且不确定你写的内容是不是对的，你前面有A有B，后面只有B电脑了？前面也只有user1？应该是四种组合啊

**Comment by JFluo2011** [comment]
其实A电脑上所有都正常，只是B电脑上出现了差异。
不过我重新配置了user1 的服务器，然后B电脑也正常了。
