### ISSUE TITLE
如何在shadowsocks-windows内自动使用PAC

### ISSUE THREAD

**Issue by wycyxc** [shadowsocks/shadowsocks-windows#988]
现状描述：应用软件只能设置一个HTTP代理，如：127.0.0.1:1080，不能指定PAC，而应用软件访问的有部分国内地址是不需要代理的。
需求：在shadowsocks-windows内实现PAC的功能。
补充：该功能有可能比较小众，求给思路，不需要合并到现在的分支。

谢谢！

**Comment by wongsyrone** [comment]
你需要从SS里面点『复制本地PAC网址』

**Comment by wycyxc** [comment]
“复制本地PAC网址”是可以获取到一个PAC网址的。我的意思是在SS内部实现PAC的解析，我的应用软件只需要设置一个HTTP代理即可。

**Comment by celeron533** [comment]
应用软件可以设置成使用IE的代理配置么？
这样的话你在IE里设置pac后，应用程序也能享受到代理服务。
另外有没有可能在本机再加一层代理服务器，让其消费pac，然后以一个普通http代理的形式再次暴露给应用程序？

**Comment by wycyxc** [comment]
谢谢回复。应用程序无法配置代理。
现在只能采用您提到的第二种方案，再SS前再加一层代理。
但这样好麻烦，想找能修改SS代码的帮忙直接把这个功能集成到SS里面去。

**Comment by celeron533** [comment]
@wycyxc 代码没有这么容易修改的
pac文件都是web代理解析的，SS只提供隧道，从最初的设计中就没有这个考量。
