### ISSUE TITLE
可否实现所有SS服务器都挂掉的情况下，不走代理？

### ISSUE THREAD

**Issue by wycyxc** [shadowsocks/shadowsocks-windows#990]
现在的情况是没有ss服务器或者ss服务器挂掉的情况下，无法上网。是否可以增加这样一个可开启功能：
1.选择“服务器宕机，直接联网”
2.该功能默认处于关闭状态。

多谢！

**Comment by celeron533** [comment]
实用性不大。
一般建议使用pac规则文件来直接在本地完成流量区分：哪些地址直连，哪些走代理。
如果代理挂了，是不会影响到pac里面的那些直连地址的。而那些需要走代理的地址。。。你如果也直连的话也访问不到。

**Comment by aolm** [comment]
这个功能确实有需求。楼上想得太简单了。

**Comment by NateScarlet** [comment]
有时候用代理不是为了从没有到有 而是为了从慢到快呀

**Comment by breakwa11** [comment]
最大的问题是，“ss服务器挂掉” 不容易正确判断
