### ISSUE TITLE
连续好几个版本的错误

### ISSUE THREAD

**Issue by RacheGOD** [shadowsocks/shadowsocks-windows#991]
![_20170109085152](https://cloud.githubusercontent.com/assets/24996464/21755165/f394faba-d649-11e6-8228-4537b00c9691.png)
![_20170109085206](https://cloud.githubusercontent.com/assets/24996464/21755166/f3a2427e-d649-11e6-9556-6b950364d70f.png)

**Comment by wongsyrone** [comment]
#505
