### ISSUE TITLE
客户端报错

### ISSUE THREAD

**Issue by shenmadouyaowen** [shadowsocks/shadowsocks-windows#992]
如图客户端报错是什么原因
![qq 20170109105425](https://cloud.githubusercontent.com/assets/12426724/21756298/8204ff06-d65a-11e6-937e-2aa732d2b3ff.png)

**Comment by wongsyrone** [comment]
搜一下以往issue列表吧，聪明的你能找到答案的。

**Comment by shenmadouyaowen** [comment]
@wongsyrone 它不是一次的错误,我每天开机使用一段时间后就会报这个错,然后重新打开就没事了,我搜索了问题列表,只搜索出一个对于这个问题的答案

**Comment by hellofwy** [comment]
看到之前有人说是 360 类的杀毒软件的权限限制问题。杀毒软件限制更改代理设置，对应报错里的 SetIEProxy。

**Comment by ZSmallX** [comment]
我的也是这个问题，后面发现是因为我有按时清理垃圾文件的习惯，就是用腾讯电脑管家清理文件，可能会不小心清理掉SS的临时文件

**Comment by chenshaoju** [comment]
请使用Portable模式即可，在Shadowsocks.exe所在目录创建一个名为 shadowsocks_portable_mode.txt 的空文件即可（注意，不是shadowsocks_portable_mode.txt.txt）。
