### ISSUE TITLE
SS的这个文件会被当做系统临时文件而被杀毒软件清理，如何保护？

### ISSUE THREAD

**Issue by ZSmallX** [shadowsocks/shadowsocks-windows#995]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Config and error log in detail (with all sensitive info masked)
![image](https://cloud.githubusercontent.com/assets/14019790/21759439/42dec3be-d67f-11e6-89c4-e78a8237a80e.png)
以腾讯电脑管家为例

**Comment by boris1993** [comment]
卸载包括但不限于腾讯、数字等厂商的xx管家
另外说一下，管家不是杀毒软件

**Comment by chenshaoju** [comment]
请使用Portable模式即可，在Shadowsocks.exe所在目录创建一个名为 shadowsocks_portable_mode.txt 的空文件即可（注意，不是shadowsocks_portable_mode.txt.txt）。

**Comment by zhidd** [comment]
看样子是客户的PC吧，
