### ISSUE TITLE
请完善bug汇报机制

### ISSUE THREAD

**Issue by lgwangh** [shadowsocks/shadowsocks-windows#996]
刚才shadowsocks3.4.2.0在我的windos10上出现了一个错误，提示我到这里来报告。
但是作为一名小白，查了好一会也搞不懂怎么把错误报告的截图上传到github来。
希望之后能完善bug汇报机制，因为要汇报bug的是所有用户，而不仅仅是程序员。
很棒的工程，谢谢各位的努力。

**Comment by wongsyrone** [comment]
可以不贴截图的，错误日志里面是同样的内容。
另外github的使用我没办法。
