### ISSUE TITLE
是否会增加KCP协议

### ISSUE THREAD

**Issue by Shensven** [shadowsocks/shadowsocks-windows#997]
Windows版本是否考虑原生支持KCP协议，就像Android客户端那样

**Comment by breakwa11** [comment]
不会

**Comment by kzwr** [comment]
没必要增加kcp进去，

**Comment by celeron533** [comment]
我是直接在机器上启动一个kcp隧道，然后再把ss服务端和客户端都重定向到隧道的两端。

**Comment by gengjiawen** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG Mac版也有这个Feature了，Windows版也可以考虑加这个Feature吧

**Comment by celeron533** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/644#issuecomment-238067370
